### ISSUE TITLE
can't add edges from list

### ISSUE THREAD

**Issue by myHelios** [dmlc/dgl#1008]
---------------------------------------------------------------------------
RuntimeError                              Traceback (most recent call last)
<ipython-input-28-13db43d89e28> in <module>
----> 1 g.add_edges([0, 0, 0, 0], [1, 2, 3, 4]) # add 4 edges 0->1, 0->2, 0->3, 0->4

/opt/conda/lib/python3.6/site-packages/dgl/graph.py in add_edges(self, u, v, data)
   1100         add_edge
   1101         """
-> 1102         u = utils.toindex(u)
   1103         v = utils.toindex(v)
   1104         self._graph.add_edges(u, v)

/opt/conda/lib/python3.6/site-packages/dgl/utils.py in toindex(data)
    240     Index
    241     """
--> 242     return data if isinstance(data, Index) else Index(data)
    243 
    244 def zero_index(size):

/opt/conda/lib/python3.6/site-packages/dgl/utils.py in __init__(self, data)
     13     """Index class that can be easily converted to list/tensor."""
     14     def __init__(self, data):
---> 15         self._initialize_data(data)
     16 
     17     def _initialize_data(self, data):

/opt/conda/lib/python3.6/site-packages/dgl/utils.py in _initialize_data(self, data)
     20         self._dgl_tensor_data = None  # a dgl ndarray
     21         self._slice_data = None # a slice type data
---> 22         self._dispatch(data)
     23 
     24     def __iter__(self):

/opt/conda/lib/python3.6/site-packages/dgl/utils.py in _dispatch(self, data)
     73                                ' but got: %s' % str(data))
     74             self._pydata = data
---> 75             self._user_tensor_data[F.cpu()] = F.zerocopy_from_numpy(self._pydata)
     76 
     77     def tonumpy(self):

/opt/conda/lib/python3.6/site-packages/dgl/backend/pytorch/tensor.py in zerocopy_from_numpy(np_array)
    274 
    275 def zerocopy_from_numpy(np_array):
--> 276     return th.as_tensor(np_array)
    277 
    278 def zerocopy_to_dgl_ndarray(input):

RuntimeError: Could not infer dtype of numpy.int64

**Comment by VoVAllen** [comment]
Could you try `g.add_edges(np.array([0, 0, 0, 0]), np.array([1, 2, 3, 4]))`?
This seems a bug of pytorch. How do you get the src list and dst list?

**Comment by myHelios** [comment]
> Could you try `g.add_edges(np.array([0, 0, 0, 0]), np.array([1, 2, 3, 4]))`?
> This seems a bug of pytorch. How do you get the src list and dst list?

it not works for me.I just run the tutorial examples.
may i change pytorch version? my version is 1.2

**Comment by VoVAllen** [comment]
I'm not sure what's the problem. Another workaround is call int on each number, such as `[int(0), int(0), int(0), int(0)]`. However this is not ideal. Could you try upgrade the torch version?

**Comment by myHelios** [comment]
> I'm not sure what's the problem. Another workaround is calling int on each number, such as `[int(0), int(0), int(0), int(0)]`. However this is not ideal. Could you try upgrade the torch version?

Thanks, I upgrade my torch version to 1.3, it works.
