### ISSUE TITLE
Importing dgl on google colab / can't install from source

### ISSUE THREAD

**Issue by sgdantas** [dmlc/dgl#1009]
Hey, I'm having problems importing dgl, it seems that google collab has now CUDA 10.1 and it is not supported by dgl right now #950 .

I can't import dgl if I install it using !pip install dgl-cu100

and when I try to install from the source using
```

!git init
!git clone https://github.com/dmlc/dgl.git
!git submodule init
!git submodule update
```

I'm able to import it but I can't use any functions, e.g., "ModuleNotFoundError: No module named 'dgl.function'".

Even after adding dgl to the sys path

```
!git clone --recursive https://github.com/dmlc/dgl.git
import sys
sys.path.append('/content/dgl')
```

Any insights on how to fix this?
Thanks!

DGL Version (e.g., 1.0): 0.4.1
Backend Library & Version (e.g., PyTorch 0.4.1, MXNet/Gluon 1.3): torch==1.3.1
OS (e.g., Linux): Linux
Python version: 3.6.8
CUDA/cuDNN version (if applicable): 10.1.243

**Comment by yzh119** [comment]
Hi,
Firstly, we have supported cuda 10.1 now:
```bash
conda install -c dglteam dgl-cuda10.1
pip install dgl-cu101
```

Plus, it seems you just cloned but have not compiled dgl? Please follow the full [install from source] instructions.

**Comment by Parag17358official** [comment]
hey I am getting issue in importing dgl on colab, could you help?

**Comment by Abhijeet38** [comment]
!pip install torch torchvision torchaudio --index-url https://download.pytorch.org/whl/cu121

!pip install dgl -f https://data.dgl.ai/wheels/torch-2.2/cu121/repo.html

**Comment by jalencato** [comment]
Recommend to install with the torch 2.3 + DGL 2.3, take cu121 with an example:

GPU:
```
pip install torch==2.3.0 
pip install dgl==2.3.0+cu121 -f https://data.dgl.ai/wheels/torch-2.3/cu121/repo.html
```

CPU:
```
pip install torch==2.3.0 --index-url https://download.pytorch.org/whl/cpu
pip install dgl==2.3.0 -f https://data.dgl.ai/wheels/cu121/repo.html
```
