### ISSUE TITLE
DGL NeighborSampler prefetch=True cause VIRT increase

### ISSUE THREAD

**Issue by ustchhy** [dmlc/dgl#1014]
## 🐛 Bug

When sampling neighbor nodes, add 'prefetch=True' may cause VIRT increase.

## To Reproduce

```
import dgl
import torch
import time

g = dgl.DGLGraph()
g.add_nodes(1000)
edges = [[i, j] for i in range(1000) for j in range(i+1, 1000)]
edges = torch.tensor(edges)
g.add_edges(edges[:, 0], edges[:, 1])
g.add_edges(edges[:, 1], edges[:, 0])
g.readonly()

for i in range(10000):
    seed_nodes = torch.randint(0, 1000, (700,))
    sampler = dgl.contrib.sampling.NeighborSampler(
        g,
        1000,
        10,
        2,
        seed_nodes=seed_nodes,
        prefetch=True,
        num_workers=48,
    )
    for nf in sampler:
        pass
```

## Expected behavior

with prefetch :    VITR=12.4G
witout prefetch:  VIRT=2.3G

## Environment

 - DGL Version (e.g., 1.0): 0.3.1
 - Backend Library & Version (e.g., PyTorch 0.4.1, MXNet/Gluon 1.3): pytorch 1.2.0
 - OS (e.g., Linux): Linux
 - How you installed DGL (`conda`, `pip`, source): pip 
 - Python version: 3.7.3

**Comment by yzh119** [comment]
I suppose it's a expected behavior as we fetch more nodeflows in the memory?

@zheng-da I'm curious why we [doubled number of workers](https://github.com/dmlc/dgl/blob/15b951d4c4d4a75cc30442d5dd72fb72ed110e09/python/dgl/contrib/sampling/sampler.py#L416) when prefetch is set to True?

**Comment by jermainewang** [comment]
Please take a look at our new sampler example here: https://github.com/dmlc/dgl/tree/master/examples/pytorch/graphsage. The NodeFlow API will be deprecated in the recent release.
