### ISSUE TITLE
Error Using Bool Tensor in mul udf

### ISSUE THREAD

**Issue by JakeStevens** [dmlc/dgl#1023]
## 🐛 Bug

If you use a BoolTensor in the built-in multiply UDF, incorrect output is obtained for both CPU and GPU as compared against a custom UDF that does the same computation. Since it is only for the builtin, I assume the issues is somewhere in the C++ code, but I am not familiar enough to patch this myself.

I'm not sure if this is the case in other UDFs as well.

## To Reproduce
g = dgl.DGLGraph()
g.add_nodes(2)
g.add_edge(0, 1)
g.add_edge(1, 0)
h  = torch.Tensor([[0.0096, 0.2319, 0.9882],
                    [0.1223, 0.2653, 0.6676]])
w  = torch.Tensor([[0, 1, 0],
                    [1, 0, 0]])
w1  = torch.BoolTensor([[False, True, False],
                    [True, False, False]])
g.ndata['h'] = h
g.edata['w'] = w
g.edata['w1'] = w1
def mul(edges):
  return {'m' : edges.src['h'] * edges.data['w1']}

g.apply_edges(fn.u_mul_e('h', 'w1', 'm_builtin'))
g.apply_edges(func=mul)

## Expected behavior

The correct output is that of g.edata['m'].

## Environment

 - DGL Version: most recent pull from main (commit f1542b9dfa74c503269881135252f6517ae46260)
 - Backend Library & Version (e.g., PyTorch 0.4.1, MXNet/Gluon 1.3): Pytorch 1.3
 - OS (e.g., Linux): Linux
 - How you installed DGL (`conda`, `pip`, source): source
 - Build command you used (if compiling from source): cmake .. & make -j8
 - Python version: 3.7
 - CUDA/cuDNN version (if applicable): 
 - GPU models and configuration (e.g. V100): GTX 1060
 - Any other relevant information:

**Comment by yzh119** [comment]
Currently we only support float32 data type in built-in functions.
I think the bool tensor is mistakenly casted to float type somewhere in the code.
Thank you for reporting this!

**Comment by JakeStevens** [comment]
Ah, I see. For the record, casting to a float tensor before hand (i.e, g.edata['w1'] = w1.float()) results in the expected output. So, the issue may be that the bool tensor is **not** being cast to a float type, resulting in garbage output

**Comment by yzh119** [comment]
Yep, what I mean is that the bool tensor is viewed as a float tensor in C++ code but the its layout in memory has not been adapted to floating point type's.

**Comment by JakeStevens** [comment]
Yes exactly got it. In that case, if only float32 is supported, I can close this issue.
