### ISSUE TITLE
[Bug] Edges bucketed wrong in group_apply_edges after triggering `g.in_degrees()`

### ISSUE THREAD

**Issue by BarclayII** [dmlc/dgl#1036]
## 🐛 Bug

Apparently the edges being bucketed and sent into UDF of `group_apply_edges`

See the following test case.

## To Reproduce

```python
import dgl
import torch
import scipy.sparse as ssp

m = ssp.random(10, 10, 0.2)
g = dgl.DGLGraph(m, readonly=True)
g.ndata['deg'] = g.in_degrees()     # removing this line would pass the test
g.ndata['id'] = torch.arange(g.number_of_nodes())
g.edata['id'] = torch.arange(g.number_of_edges())

# This function checks whether the edge IDs in the bucket indeed match those of the
# inbound edges
def apply(edges):
    w = edges.data['id']
    n_nodes, deg = w.shape

    dst = edges.dst['id'][:, 0]
    eid1 = g.in_edges(dst, 'eid').view(n_nodes, deg).sort(1)[0]
    eid2 = edges.data['id'].sort(1)[0]
    print(dst)
    print(eid1)
    print(eid2)
    assert torch.equal(eid1, eid2)
    return {'id2': w}

print(g.all_edges(order='eid'))
g.group_apply_edges('dst', apply, inplace=True)
```

## Expected behavior

The test above should pass.

## Environment

 - DGL Version (e.g., 1.0): master
 - Backend Library & Version (e.g., PyTorch 0.4.1, MXNet/Gluon 1.3):
 - OS (e.g., Linux):
 - How you installed DGL (`conda`, `pip`, source):
 - Build command you used (if compiling from source):
 - Python version:
 - CUDA/cuDNN version (if applicable):
 - GPU models and configuration (e.g. V100):
 - Any other relevant information:

## Additional context

In https://github.com/dmlc/dgl/blob/master/python/dgl/graph.py#L2211, adding `'eid'` to the `edges()` call would solve the problem.  But could anybody explain why this happens only if `in_degrees()` is there (before I figure it out myself)?

`send()` and those in heterographs may also have the same problem.

**Comment by classicsong** [comment]
I also curious about why in_degrees() cause the problem.

**Comment by VoVAllen** [comment]
Maybe we should force `g.edges()` to return edges in the eid orders
