### ISSUE TITLE
[Feature] Weighted adjacency matrix

### ISSUE THREAD

**Issue by MilkshakeForReal** [dmlc/dgl#1041]
## 🚀 Feature

If we have some weights stored in `g.edata['w']`, I want a functaion `DGLGraph.weighted_adjacency_matrix`  like `DGLGraph.adjacency_matrix` to return the corresponding weighted matrix
## Motivation

For example, in link prediction we can treat the weighted adjacency matrix as a feature map, it would be nice if we can track those feature maps .

**Comment by VoVAllen** [comment]
Hi,

We'll consider your request. Currently you can construct the sparse matrix from the index `g.all_edges(order=''eid)` and value from g.edata['w'].

```python
u,v = g.all_edges(order='eid')
wadj=np.zeros((num_nodes, num_nodes))
wadj[u.numpy(),v.numpy()]=g.edata['h'].numpy()
```
