### ISSUE TITLE
How to sample on heterogeneous graph??

### ISSUE THREAD

**Issue by yunhao7966** [dmlc/dgl#1043]
## ❓ Questions and Help

I try to sampling on RGCN. But I don't know to do it. who can answer me??   Thanks !!

**Comment by zheng-da** [comment]
@yunhao7966 we are working on it. Heterogeneous graph sampling will be supported in the next release. In the meanwhile, could you describe what kind of sampling strategies you like to use? Sampling gets much more complex in heterogeneous graph.

**Comment by yunhao7966** [comment]
@zheng-da   Hi guy .Thanks for your response. We hope that there are two kinds of heterogeneous graph sampling methods: one is to sample a certain number of all types of neighbor nodes; the other is to sample one or several types of nodes. Of course, we hope DGL can provide more flexible heterogeneous graph sampling methods. 

DGL是很个优秀的图神经网络框架，我们团队也很庆幸能基于DGL进行一些基于图数据的研究工作，可惜DGL基于中文的官方教程较少 ，在看英文资料时存在理解有偏差的情况。如果DGL有中文官方教程，很有可能在中国市场会有更广的应用。

**Comment by yunhao7966** [comment]
By the way, we are used to using pytorch, and mxnet is used less.

**Comment by jermainewang** [comment]
@yunhao7966 sampling APIs for heterogeneous graph has been landed and you could look at the example here: https://github.com/dmlc/dgl/tree/master/examples/pytorch/rgcn-hetero .
