### ISSUE TITLE
[Bug?] setting the number of workers to 1 in the sampler doesn't reduce the CPU utilization.

### ISSUE THREAD

**Issue by zheng-da** [dmlc/dgl#1047]
## 🐛 Bug

This isn't really a bug. But we should set the number of OMP threads based on the number of workers.

## To Reproduce

1.
1.
1.

## Environment

 - DGL Version (e.g., 1.0):
 - Backend Library & Version (e.g., PyTorch 0.4.1, MXNet/Gluon 1.3):
 - OS (e.g., Linux):
 - How you installed DGL (`conda`, `pip`, source):
 - Build command you used (if compiling from source):
 - Python version:
 - CUDA/cuDNN version (if applicable):
 - GPU models and configuration (e.g. V100):
 - Any other relevant information:

**Comment by jermainewang** [comment]
We find that the `copy_from_parent` operation spawns multiple threads.

**Comment by yzh119** [comment]
I agree that this is not a bug.
Just disabling multi-threading in both `NeighborSampler` and `copy_from_parent` does not throughly solve the problem as PyTorch would swpan multi threads, too.

The right way to control the number of workers in openmp is to use `OMP_NUM_THREADS=N` or specify `torch.set_num_threads(N)`, they have the same effect.
