### ISSUE TITLE
How to prepare the input graph data?

### ISSUE THREAD

**Issue by wenruij** [dmlc/dgl#1049]
## 📚 Documentation

Is there a plan for adding tutorials about graph data format ?

How should we prepare input files about nodes, edges and features  to use **dgl**?
Is there a specific requirement for input graph format?

**Comment by jermainewang** [comment]
We have plan to re-organize our API references and and tutorials in 0.5. So this is under our watch!

**Comment by wenruij** [comment]
Sound great, full of expectation.
