### ISSUE TITLE
functionality that converts between heterographs and homogeneous graphs using dgl.to_homo doesn't seem to work

### ISSUE THREAD

**Issue by amblee0306** [dmlc/dgl#1053]
## 🐛 Bug
the function 'to_homo' doesn't seem to be working as expected.

## To Reproduce
example on documention 
https://docs.dgl.ai/generated/dgl.to_homo.html#dgl.to_homo

>>> follows_g = dgl.graph([(0, 1), (1, 2)], 'user', 'follows')
>>> devs_g = dgl.bipartite([(0, 0), (1, 1)], 'developer', 'develops', 'game')
>>> hetero_g = dgl.hetero_from_relations([follows_g, devs_g])
>>> homo_g = dgl.to_homo(hetero_g)
>>> homo_g.ndata
>>> homo_g.edata

Error message:
raise DGLError('Index data must be an int64 vector, but got: %s' % str(data))
dgl._ffi.base.DGLError: Index data must be an int64 vector, but got: tensor([0., 1., 3., 4.])

## Expected behavior

>>> homo_g.ndata
{'_TYPE': tensor([0, 0, 0, 1, 1, 2, 2]), '_ID': tensor([0, 1, 2, 0, 1, 0, 1])}
First three nodes for 'user', next two for 'developer' and the last two for 'game'
>>> homo_g.edata
{'_TYPE': tensor([0, 0, 1, 1]), '_ID': tensor([0, 1, 0, 1])}
First two edges for 'follows', next two for 'develops'

## Environment

 - DGL Version (dgl==0.4)
 - OS (MacOS):
 - Python version: 3.7.4

**Comment by mufeili** [comment]
This seems to be the same issue as #1018 . Could you please try installing from source and see if the issue still exists?

**Comment by amblee0306** [comment]
hi there, i have tried installing from source but it doesn't seem to solve the issue. the same error message still pops up. I am using pytorch 1.3.1.

**Comment by mufeili** [comment]
@amblee0306 

Some follow-up questions and check items:
1. I assume by "building from source", you cloned the latest repo?
2. Have you uninstalled the old version of DGL? Any chance that you were still using an old version of DGL?

**Comment by amblee0306** [comment]
@mufeili 
Thanks for the reply. I didn't uninstall the old version of DGL previously. I have done so and install from source and it is working fine now. Thanks!
