### ISSUE TITLE
Windows setup problems

### ISSUE THREAD

**Issue by aaronmarkham** [dmlc/dgl#1062]
## 📚 Documentation

Windows installation issues:

- Pip packages were not available (for Windows) and the install guide doesn’t mention this. Had to use conda. (mention to use conda when installing for Windows)
- A CPU build option is listed under the GPU options. (remove this)
- I was able to create an environment and install a DGL conda package for CUDA 9.2 even though that isn’t listed. (add this and whatever others exist)
- pygraphviz is really hard to get setup on Windows right now; at least one of the tutorials has this in there. (I'd remove it in favor of something else more compatible)
- matplotlib is required throughout and should be included in the setup
- pytorch isn't found by installing dlg on its own; when you run the .py scripts it can't find torch, so you have to install it separately.

## Proposed solution

This worked for me on Windows 10 Home 64-bit with an NVIDIA GPU and CUDA 9.2.

```
conda create -n dgl python=3
source activate dgl
conda install matplotlib
conda install -c dglteam dgl-cuda9.2
conda install pytorch torchvision cudatoolkit=9.2 -c pytorch -c defaults -c numba/label/dev
```

**Comment by aaronmarkham** [comment]
Here are my notes in case they help:

Troubleshooting Tutorial 1 - DGL at a glance

This tutorial assumes Jupyter notebook. Running from CLI doesn’t work for the graphing it shows.
I couldn’t run it all the way through. See the error below.
I ran ipython  to go through the steps. It was using Python 3.7.3.

Then I downloaded the py script and tried that.
I tried python 1_first.py and received an error that torch was not installed. I verified that I could import it when using ipython, but not with python or python3. It seemed the ipython was running from a different environment that this new one created for dgl (and maybe I already had pytorch installed there?).
pip install torch failed. Error: “ No module named 'tools.nnwrap'”

Installing with a custom command from the PyTorch website fixed Python’s installation of PyTorch.
conda install pytorch torchvision cudatoolkit=9.2 -c pytorch -c defaults -c numba/label/dev

I was able to run the script further, but received:
ModuleNotFoundError: No module named 'matplotlib'
Then I ran conda install matplotlib and this worked.
Then I ran the .py file again, and it worked!!!

How to get started on Windows
To summarize, I think that a Windows installation guide for someone that has a GPU with CUDA 9.2 already setup, would be to run the following commands.

conda create -n dgl python=3
source activate dgl
conda install matplotlib
conda install -c dglteam dgl-cuda9.2
conda install pytorch torchvision cudatoolkit=9.2 -c pytorch -c defaults -c numba/label/dev
Then download the first tutorial, and run it.

Error from the DGL tutorial when using ipython right after a basic installation of DGL.
```
In [17]: for epoch in range(30):
    ...:     logits = net(G, inputs)
    ...:     # we save the logits for visualization later
    ...:     all_logits.append(logits.detach())
    ...:     logp = F.log_softmax(logits, 1)
    ...:     # we only compute loss for labeled nodes
    ...:     loss = F.nll_loss(logp[labeled_nodes], labels)
    ...:
---------------------------------------------------------------------------
NotImplementedError                       Traceback (most recent call last)
<ipython-input-17-2d044d9095cf> in <module>
      1 for epoch in range(30):
----> 2     logits = net(G, inputs)
      3     # we save the logits for visualization later
      4     all_logits.append(logits.detach())
      5     logp = F.log_softmax(logits, 1)

~\AppData\Local\conda\conda\envs\mxnet-docs\lib\site-packages\torch\nn\modules\module.py in __call__(se
lf, *input, **kwargs)
    487             result = self._slow_forward(*input, **kwargs)
    488         else:
--> 489             result = self.forward(*input, **kwargs)
    490         for hook in self._forward_hooks.values():
    491             hook_result = hook(self, input, result)

~\AppData\Local\conda\conda\envs\mxnet-docs\lib\site-packages\torch\nn\modules\module.py in forward(sel
f, *input)
     83             registered hooks while the latter silently ignores them.
     84         """
---> 85         raise NotImplementedError
     86
     87     def register_buffer(self, name, tensor):

NotImplementedError:
```

**Comment by BarclayII** [comment]
Hi Aaron,

Pip packages [should be available for Windows](https://pypi.org/project/dgl-cu92/#files).  If you wish to install a GPU build, you can run something like
```
pip install dgl-cu92
```
What kind of error were you getting with pip?

Thanks.

**Comment by jermainewang** [comment]
Hi Aaron,

Tutorials and main DGL packages have different dependencies. Main DGL package only depends on numpy, networkx and scipy, so they are included in setup.py. Dependencies like matplotlib, tqdm and pygraphviz are used only in tutorials and some of the examples.  How about we add a README about how to install these dependencies and run tutorials? It could go to [the tutorial folder](https://github.com/dmlc/dgl/tree/master/tutorials) or a new section in the [installation guide](https://docs.dgl.ai/install/index.html). What do you think?
