### ISSUE TITLE
review of Heterographs tutorial 

### ISSUE THREAD

**Issue by aaronmarkham** [dmlc/dgl#1063]
## 📚 Documentation

[Tutorial 1 - Heterographs](https://docs.dgl.ai/tutorials/hetero/1_basics.html)
This has really great overview and conceptual information about the power of graphs. I think this should be the first intro to DGL. However, it is too long, and meanders through some areas that could be reserved for a different tutorial.

There’s a typo and TMI in the following:
“Knowledge graphs are inherently heterogenous. For example, in Wikidata, Barack Obama (item Q76) is an instance of a human, which could be viewed as the entity class, whose spouse (item P26) is Michelle Obama (item Q13133) and occupation (item P106) is politician (item Q82955). The relationships are shown in the following. diagram.”

I would remove the item info as it is distracting and doesn’t add value to the discussion.

Later, this line should be a comment in the code block:
Creating from scipy matrix

I’d also break out that code block so you can run each variation as you wish, instead of altogether.

Move recommender below knowledge graph because the following graph creation examples use that graph. It would be easier to follow. The DGL example is repeated twice, so you can delete the last one.

The “manipulating a heterograph” section seems to be more about how to import and convert datasets from scipy. This is interesting on its own and should be discussed separately.

When discussing the knowledge graph for papers, it would help to update the word choices to better show the relationships.
```
G = dgl.heterograph({
        ('paper', 'written-by', 'author') : data['PvsA'],
        ('author', 'writing', 'paper') : data['PvsA'].transpose(),
        ('paper', 'citing', 'paper') : data['PvsP'],
        ('paper', 'cited', 'paper') : data['PvsP'].transpose(),
        ('paper', 'is-about', 'subject') : data['PvsL'],
        ('subject', 'has', 'paper') : data['PvsL'].transpose(),
    })
```

Changes to improve clarity:

- Paper written-by author
- Author wrote paper (update)
- Paper cites paper (update)
- Paper cited-by paper  (update)
- Paper is-about subject
- Subject is-referenced-by paper (update)
- 

The code that downloads the ACM dataset doesn’t work (on Windows).
I had  to remove /tmp/ from data_file_path to get it to work.

```
import scipy.io
import urllib.request

data_url = 'https://s3.us-east-2.amazonaws.com/dgl.ai/dataset/ACM.mat'
#data_file_path = '/tmp/ACM.mat'
data_file_path = 'ACM.mat'

urllib.request.urlretrieve(data_url, data_file_path)
data = scipy.io.loadmat(data_file_path)
print(list(data.keys()))
```

**Metagraph example - troubleshooting**
Metagraph could have it’s own main heading as it seems pretty important. However, it requires pygraphviz and this requires graphviz, and for Windows, I found this nearly impossible. I spent about 30 minutes, at least, trying to figure out how to install it and came up with a really complicated patch, that, IMO, isn’t worth the effort. Why can’t this section use matplotlib?

**R-GCN example**
The example at the end doesn’t really close out the topic. I’m not seeing any conclusion.

**Comment by winddd** [comment]
I found that in the R-GCN example, the following lines of codes are likely to report the error `AttributeError: 'int' object has no attribute 'item'`:

`        if epoch % 5 == 0:
            print('Loss %.4f, Train Acc %.4f, Val Acc %.4f (Best %.4f), Test Acc %.4f (Best %.4f)' % (
                loss.item(),
                train_acc.item(),
                val_acc.item(),
                best_val_acc.item(),
                test_acc.item(),
                best_test_acc.item(),
            ))`

It seems because it is possible that the `best_val_acc` and `best_test_acc` won't get updated during the first 5 epoches.
