### ISSUE TITLE
pagerank tutorial review

### ISSUE THREAD

**Issue by aaronmarkham** [dmlc/dgl#1064]
## 📚 Documentation

[Tutorial 3 - PageRank with DGL](https://docs.dgl.ai/tutorials/basics/3_pagerank.html)
Generally, I think I was distracted by the potential that I was going to do something with pagerank, but really it was there as a vehicle to discuss DGL's features. And even going through the features, I'm not sure I was getting the take-aways intended.

It creates a graph and doesn’t introduce what it is.
```
g = nx.nx.erdos_renyi_graph(N, 0.1)
```
What’s erdos_renyi_graph? Glancing at wikipedia, I think this generates two closely-related random graphs.
It runs fine, outputs one graph image, and then a tensor. I sort of expected a page rank script to, I don’t know, maybe show “page ranks”. 
Early on and throughout there’s “pv”. I wasn’t sure what this was. There’s a formula at the beginning. I think it would help to link the concepts and say, “you’re going to compute page value”, which is defined here as “PageRank value uniformly - PV(u)”.
I tried the suggestion to change `# pagerank_naive(g)` and uncomment that and rerun it to “see the differences”. The tensor was different, but I don’t know what else I am supposed to get from that change.

**Comment by jermainewang** [comment]
These are great suggestions. We think the pagerank tutorial in overall is quite distractive and is not directly relevant to graph deep learning. Thus, we are going to remove it in the future and probably write an in-depth tutorial about the message passing interface using GCN as an example. In addition, we might need to re-write the flow as follows:
* Directly use the modules in `dgl.nn` to build your models.
* Customize GNN layer using built-in message and reduce functions in `dgl.function`.
* Further customization using native python functions.
