### ISSUE TITLE
Exception in loading pickled heterogrpah

### ISSUE THREAD

**Issue by mjwen** [dmlc/dgl#1070]
## 🐛 Bug

Heterograph can be pickled without problem, but when loading it back, the below exception is thrown: 

```
Exception ignored in: <function ObjectBase.__del__ at 0x10905b7a0>
Traceback (most recent call last):
  File "/Users/mjwen/Applications/dgl/python/dgl/_ffi/_ctypes/object.py", line 46, in __del__
  File "/Users/mjwen/Applications/dgl/python/dgl/_ffi/_ctypes/object.py", line 50, in __getattr__
AttributeError: 'handle' is a reserved attribute name that should not be used
```
## To Reproduce

```python
import dgl
import pickle

g = dgl.heterograph({("author", "write", "paper"): [(0, 0), (0, 1)]})

with open("temp.pkl", "wb") as f:
    pickle.dump(g, f)

with open("temp.pkl", "rb") as f:
    g = pickle.load(f)
```

## Environment

 - DGL Version (e.g., 1.0): master (as of commit dca2580b8494f2)
 - Backend Library & Version (e.g., PyTorch 0.4.1, MXNet/Gluon 1.3): none
 - OS (e.g., Linux): macOS
 - How you installed DGL (`conda`, `pip`, source): source 
 - Python version: 3.7.4

**Comment by mufeili** [comment]
Currently you cannot pickle a `DGLHeteroGraph`. It's on our to-do list. Before that comes true, is it possible to to perform `g = dgl.to_homo(g)` first and then convert it to a NetworkX graph with `g = dgl.to_networkx(g)`?

References:
- [to_homo](https://docs.dgl.ai/generated/dgl.to_homo.html#dgl.to_homo)
- [to_networkX](https://docs.dgl.ai/generated/dgl.to_networkx.html#dgl.to_networkx)

**Comment by mjwen** [comment]
@mufeili  thanks for the suggestions! 

I wanted to pickle `DGLHeteroGraph` and the node data and edge data associated with it, because it takes a significant time to compute them. `to_homo` does not work here since the data on different nodes do not have the same size; in this case `to_homo` leads to the below error:
```
dgl._ffi.base.DGLError: Cannot concatenate column h with shape Scheme(shape=(2,), dtype=torch.float32) and shape Scheme(shape=(4,), dtype=torch.float32)
```  

For now, I am not going to pickle the `DGLHeteroGraph`, but instead pickle the node and edge data only and attach the loaded data to newly created `DGLHeteroGraph`.
