### ISSUE TITLE
[Bug?] Node id returned by bipartite.node(ntype) is different from the node ids we specified

### ISSUE THREAD

**Issue by Maybewuss** [dmlc/dgl#1072]
```python
g = dgl.bipartite([(0, 3), (1, 2), (0, 1)], 
                  'user', 'plays', 'game',
                   card=(2,3))
print(g.nodes('game') => tensor([0, 1, 2])
print(g.edges) => (tensor([0, 1, 0]), tensor([3, 2, 1]))
```

Here I use card to set of number of `games` nodes to 3. The node ids appeared in the input data is `3, 2, 1`.
However, by calling `g.nodes('game')` I get `0, 1, 2`.

**Comment by Maybewuss** [comment]
```python
g = dgl.bipartite([(0, 3), (1, 2), (0, 1)], 
                  'user', 'plays', 'game',
                   card=(2,3))
g.nodes['game'].data['w'] = torch.randn(3,4)
g.apply_edges(lambda edges:{'x':edges.dst['w']})
```
这里会报错index out of range

**Comment by yzh119** [comment]
Hi, this is not a bug.
Note that node ids in DGL is 0-based, this being said, if largest node id in your input data is 4, there are at least 4 nodes in total. In your case, `0` does not appeared in `game` nodes but it is created, and there is no edge connected to it. The cardinality of `game` nodes should be at least 4 but you only set it to 3, the node 3 is removed.

DGL should raise an error when users set invalid `card`, I'll fix it.

**Comment by Maybewuss** [comment]
Thanks!!!
