### ISSUE TITLE
Random walk sampling on a giant graph

### ISSUE THREAD

**Issue by nlj0011** [dmlc/dgl#1075]
Hi,
Awesome library, thank you for the good work!

I have a question about working on giant graph. There are about ten billion nodes in my heterogeneous graph, and I want using the metapath based method to embed them. However, before calling the metapath_random_walk, it shoud use the hetero_from_relations methods to construct the relationship, which consume large memory. Could you give me some suggestions to solve this problem?  Thank you very mach!

Best Regards!

**Comment by zheng-da** [comment]
`hetero_from_relations` constructs a heterograph with billions of nodes. So it should use a lot of memory.

**Comment by jermainewang** [comment]
This is a duplication of [this thread](https://discuss.dgl.ai/t/random-walk-sampling-on-a-giant-graph/568/6) on our discussion forum.
