### ISSUE TITLE
APPNP equation parentheses typo

### ISSUE THREAD

**Issue by dariodata** [dmlc/dgl#1079]
## 📚 Documentation

- API reference part
- The parentheses in the equation of the APPNPConv docstring are amiss. The implementation however fits the paper reference. 
- According to the APPNP paper the equations should be:

```
.. math::
        H^{0} & = X

        H^{t+1} & = (1-\alpha)\left(\hat{D}^{-1/2}
        \hat{A} \hat{D}^{-1/2} H^{t}\right) + \alpha H^{0}
```

**Comment by yzh119** [comment]
Thank you @dariodata , we have fixed the typo in #1083 .
