### ISSUE TITLE
[Feature] Convert edge data into adjacency matrices.

### ISSUE THREAD

**Issue by mufeili** [dmlc/dgl#1085]
## 🚀 Feature

An API called `edata_to_adj(g, feats)`, which converts `feats` to a (sparse) tensor of shape (N, N, D), where D is the size for the edge data. 

## Details

1. The assumption is that the order of rows in `feats` correspond to the edge ids in `g`. Note that this is the case with `g.edata[...]`.
2. I don't think this feature should be a class method so that it can be also compatible with things like sliced HeteroGraph.

## Motivation

This feature can be helpful when we want to perform analysis on edge data (e.g. attention) or compare DGL implementation with some dense implementations. It's not difficult to implement.

**Comment by chaitjo** [comment]
Looking forward to this.

**Comment by VoVAllen** [comment]
I made a simple version you can use for now
```python
from dgl.data import KarateClub
import torch as th
ds = KarateClub()
g = ds[0]
# Assuming you have edge data h
g.edata['h'] = th.ones(g.number_of_edges(), 5)
num_nodes = g.number_of_nodes()
out = th.zeros(size=(num_nodes, num_nodes)+g.edata['h'].shape[1:])
out[g.edges()]=g.edata['h'] # This is what you need
```

**Comment by mufeili** [comment]
@VoVAllen Just to be careful, let's replace `g.edges()` with `g.all_edges(order=’eid’)`.

**Comment by jermainewang** [comment]
> An API called `edata_to_adj(g, feats)`, which converts `feats` to a (sparse) tensor of shape (N, N, D), where D is the size for the edge data.

I don't think [PyTorch](https://pytorch.org/docs/stable/sparse.html) supports sparse tensors of >2 dimensions. Generating a `(N, N, D)` dense tensor on the other hand is too costly. Any solution to this?
