### ISSUE TITLE
metapath2vec in dgl/examples/pytorch/metapath2vec

### ISSUE THREAD

**Issue by Crice22** [dmlc/dgl#1086]
## ❓ Questions and Help

In sampler, why skip papers? If skip papers, is the calculated embedding  also not using papers' information ? In a HIN, we define the metapath is cpapc, but why omit papers in the output, which means that we are not using papers' structural information. thanks.

**Comment by zheng-da** [comment]
@ ShawXh any comments on this?

**Comment by BarclayII** [comment]
Hi @Crice22 ,

The main reason is that we were reproducing the official implementation [there](https://ericdongyx.github.io/metapath2vec/m2v.html) whose metapaths skip papers.  Of course, we can add in papers to learn their embeddings as well.

**Comment by Crice22** [comment]
> Hi @Crice22 ,
> 
> The main reason is that we were reproducing the official implementation [there](https://ericdongyx.github.io/metapath2vec/m2v.html) whose metapaths skip papers. Of course, we can add in papers to learn their embeddings as well.

OK,  get it, thanks.
