### ISSUE TITLE
alchemy edge featurizer not preserving order

### ISSUE THREAD

**Issue by mjwen** [dmlc/dgl#1098]
## 🐛 Bug

The [alchemy_edges()](https://github.com/dmlc/dgl/blob/869093e890ffface86430e378cc71ebcc080f2cf/python/dgl/data/chem/alchemy.py#L85) function does not preserve the bond order as stated in its docstring.  

For example, ignoring `self_loop`, the first element of the feature tensor `bond_feats_dict['e_feat']` corresponds to the bond between atoms `u=0` and `v=1`. Apparently, this is not necessarily the first bond in the molecule (first edge in the graph). 

This creates problems if [construct_bigraph_from_mol()](https://github.com/dmlc/dgl/blob/869093e890ffface86430e378cc71ebcc080f2cf/python/dgl/data/chem/utils.py#L896) is used to create the graph, which creates a graph where 

```
the **i** th bond in the molecule, i.e. ``mol.GetBondWithIdx(i)``, corresponds to the
**(2i)**-th and **(2i+1)**-th edges in the returned DGLGraph. The **(2i)**-th and
**(2i+1)**-th edges will be separately from **u** to **v** and **v** to **u**, where
**u** is ``bond.GetBeginAtomIdx()`` and **v** is ``bond.GetEndAtomIdx()``.
```
Unfortunately, this is what used in the [TencentAlchemyDataset()](https://github.com/dmlc/dgl/blob/869093e890ffface86430e378cc71ebcc080f2cf/python/dgl/data/chem/alchemy.py#L135).

Fix should be straightforward. Just loop over the bonds of a molecule and append features in the same order as how the graph is constructed, i.e. do the same loop in  [construct_bigraph_from_mol()](https://github.com/dmlc/dgl/blob/869093e890ffface86430e378cc71ebcc080f2cf/python/dgl/data/chem/utils.py#L896). 

P.S. I checked other molecule featurizers and they all seem fine.

**Comment by mufeili** [comment]
Hi, for this dataset we by default use [mol_to_complete_graph](https://github.com/dmlc/dgl/blob/master/python/dgl/data/chem/utils.py#L1036) at [L178](https://github.com/dmlc/dgl/blob/master/python/dgl/data/chem/alchemy.py#L178), which constructs complete graphs rather than bi-directed graph. The featurization for edges [alchemy_edges](https://github.com/dmlc/dgl/blob/master/python/dgl/data/chem/alchemy.py#L85) is intended to work with complete graphs.

**Comment by mjwen** [comment]
Oh my bad. You are right. There is no problem since it is intended for complete graph.
