### ISSUE TITLE
[Feature] Built-in function operating on the same type data for simplicity

### ISSUE THREAD

**Issue by MilkshakeForReal** [dmlc/dgl#1107]
## 🚀 Feature

Maybe we could add some built-in fuction like `u_add_u`, `e_dot_e` to operate on the same type but of different field data for simplicity.
## Motivation

I consider that built-in function can not only speed up the computation but also improve the simplicity of code. Especially when dealing with heterogeneous graphs this kind of operation could be very redundant like
`g.edges['xx'].data['c'] = g.edges['xx'].data['a']+g.edges['xx'].data['b']`, which could be replaced by

`g.apply_edges(fn.e_add_e('a','b','c'), type = 'xx')`.

**Comment by classicsong** [comment]
Take u_add_u as example, you can simply doing so by 
`g.ndata['c'] = g.ndata['b'] + g.ndata['a']` 
which is a simple tensor operation. This is a straight forward implementation and is efficient.

**Comment by yzh119** [comment]
@MilkshakeForReal  Thanks for your proposal, I think there are some other ways to handle it?
For example, using the context manage: 
```python
with g.edge_type('xx'):
    g.edata['c'] = g.edata['a'] + g.edata['b']
```

**Comment by jermainewang** [comment]
I agree with @classicsong and didn't see significant benefit from introducing new built-ins for this since there exists a pretty straight-forward implementation. Thanks for the proposal anyway!
