### ISSUE TITLE
Random state for NeighborSampler

### ISSUE THREAD

**Issue by JinYang88** [dmlc/dgl#1110]
Is it possible to add the parameter "Random state" to NeighborSampler to achieve reproducibility?

**Comment by yzh119** [comment]
Hi, we provide a [dgl.random.seed](https://docs.dgl.ai/en/latest/generated/dgl.random.seed.html#dgl.random.seed) API to set the random seed for sampling & random walks.

**Comment by VoVAllen** [comment]
However the sampler is deterministic only if the num_worker is 1 (or zero?). @BarclayII @zheng-da  Correct me if I'm wrong

**Comment by jermainewang** [comment]
@VoVAllen , that's right. Concurrency makes the result non-deterministic. @JinYang88 please try what @yzh119 suggested and let us know if anything is not correct.
