### ISSUE TITLE
How to calculate the number of common neighbors of two points on the edge quickly

### ISSUE THREAD

**Issue by annasmallcat** [dmlc/dgl#1111]
## ❓ Questions and Help
How to calculate the number of common neighbors of two nodes on the edge quickly?

**Comment by mufeili** [comment]
The example below might be helpful:

```python
import numpy as np
from dgl import DGLGraph

def find_common_in_nbrs(g, i, j):
    """Find nodes that have edges to both node i and node j.
    
    Returns
    --------
    NumPy array of int64
    """
    return np.intersect1d(g.in_edges(i)[0], g.in_edges(j)[0])

g = DGLGraph()
g.add_nodes(3)
g.add_edges([0, 0, 1, 2, 2], [1, 2, 1, 1, 2])
print(find_common_in_nbrs(g, 1, 2))
```

**Comment by annasmallcat** [comment]
Thank you, there is another question ,can we simultaneously calculate the number of common neighbors of all the two nodes on the graph?

**Comment by annasmallcat** [comment]
> 
> 
> The example below might be helpful:
> 
> ```python
> import numpy as np
> from dgl import DGLGraph
> 
> def find_common_in_nbrs(g, i, j):
>     """Find nodes that have edges to both node i and node j.
>     
>     Returns
>     --------
>     NumPy array of int64
>     """
>     return np.intersect1d(g.in_edges(i)[0], g.in_edges(j)[0])
> 
> g = DGLGraph()
> g.add_nodes(3)
> g.add_edges([0, 0, 1, 2, 2], [1, 2, 1, 1, 2])
> print(find_common_in_nbrs(g, 1, 2))
> ```
Thank you, there is another question ,can we simultaneously calculate the number of common neighbors of all the two nodes on the graph?

**Comment by mufeili** [comment]
You can prepare a list of 2-tuples representing all possible pairs of nodes in the graph and then use multiple processes to do computation.
