### ISSUE TITLE
edge sampler should support both sampling with or without replacement 

### ISSUE THREAD

**Issue by zheng-da** [dmlc/dgl#1112]
## 🚀 Feature
Currently, edge sampler behaves differently for uniform sampling and non-uniform sampling. For uniform sampling, it samples without replacement. For non-uniform sampling, it samples with replacement. This results in another difference: uniform sampler returns a fixed number of batches while non-uniform sampler can return any number of batches. We should add support of sampling with and without replacement for both uniform and non-uniform sampling and have a flag to determine whether to use with or without replacement. When sampling with replacement, users also need to provide how many batches to generate.

**Comment by classicsong** [comment]
Resolved
