### ISSUE TITLE
GCN sampler: pull instead of push model in copy reduce.

### ISSUE THREAD

**Issue by yuk12** [dmlc/dgl#1114]
Hi,

Need help.
I am working on GCN sampler example. In current GCN model, which uses 2hop neighbors, during block_compute: in first iteration: layer-0 nodes send (or push) the features to layer-1 and layer-1 then aggregates the neighbors. Similarly, in second iteration: layer-1 sends (or pushes) the features to layer-2 which then aggregates over the neighbors.

What I am trying to implement is a pull model: where each node in layer-1 pulls the features from layer-0 (similarly, layer-2 pulls from layer-1) and then aggregates. Thus, the pull model avoids the collision (and inturn gets rid of the omp atomics in reduce functions).

I am able to change the DGL code and implement the pull model. And the code is working fine for 1 thread. While running the same code on more than 1 thread resulting in NaNs out of optimizer.step().
I have no idea why it is happening. 

I am setting #omp threads as: $ export OMP_NUM_THREADS=2 
I even tried by commenting the omp parallel statement in minigun while setting OMP_NUM_THREADS=2. Still no useful. I am consistently getting NaNs from the optimizer.step() regardless of the number of threads (>1).

Can you help me out here? 
Happy to provide more details if you need.

Thanks.

**Comment by classicsong** [comment]
In the forward step, pull model can help eliminate atomic operations, but in the backward step, the model switch to push. Also you should take care of local variables and global variables in OMP loops.

BTW, we are currently investigating the possibility of applying target-parallelism for builtin message passing kernel which can totally eliminate atomic operations in both forward and backward.

**Comment by yuk12** [comment]
Hi, Thanks for the quick response. Can you tell where the push model is being applied in the backward step? -- the copy reduce operation does not go through the backward step.

Good to know about target parallelism: it will be a significant improvement performance-wise.
