### ISSUE TITLE
Installation problem with CUDA10.1

### ISSUE THREAD

**Issue by XionZi** [dmlc/dgl#1115]
Newest CUDA version is 10.1, but I found no available installation comand for CUDA10.1 provided.  I tried
`conda install -c dglteam dgl-cuda10.0` in [https://www.dgl.ai/pages/start.html](https://www.dgl.ai/pages/start.html)
but it didn't work.

Fanally I worked it out with
`conda install -c dglteam dgl-cuda10.1` .

A more specific installation instruction might be needed.

**Comment by mufeili** [comment]
@VoVAllen Could you please take a look?

**Comment by VoVAllen** [comment]
Hi,
it's now added to dgl's main page.
