### ISSUE TITLE
[RFC] Explicit device context and index type for DGLGraph

### ISSUE THREAD

**Issue by jermainewang** [dmlc/dgl#1120]
### Motivation

In DGL, a DGLGraph stores two types of data: graph topology and node/edge features. Currently, it stores graph topology in CPU. During message passing, if the feature data is on GPU, it will copy the graph structure to GPU and *cache* it for later use.

Another design flaw is the index type. Currently, we store graph topology only in int64 type. During message passing, we check and cast the graph to int32 type if the computation occurs on GPU.

From my perspective, the design causes several issues:
* **Storage overhead**: Storing graph topology first on CPU and then copy it to GPU is a waste.
* **Opaque conversion and caching mechanism**: It is hard to keep track of the memory usage when the system caches copies of graph for computation.
* **Index type cannot be controlled by users**: Creating a DGLGraph using int32 is not possible in DGL right now.

### Proposal

Just like that a tensor in MX/PT/TF has explicit device context and data type, the RFC proposes that DGLGraph should have explicit device context and index type as well:

```python
>>> g = DGLGraph(..., device='cuda:0', itype=np.int32)
>>> print(g.device)
cuda:0
>>> print(g.itype)
int32
```

Of course, the `device` and `itype` arguments could have default values. A `DGLGraph` with device type `cuda:0` means that **both graph topology and feature data** are stored on GPU#0.

```python
>>> import torch as th
>>> g = DGLGraph(..., device='cuda:0')
>>> h = th.zeros((g.number_of_nodes(), 5), device='cpu')
>>> g.ndata['h'] = h  # throw error due to mismatched device contexts
```

To copy the graph from one device to another, use the `to` API (already implemented), or use `cpu()`, `cuda(devid)` APIs.

```python
>>> g = DGLGraph(..., device='cuda:0')
>>> g0 = g.to('cuda:1')
>>> print(g0.device)
cuda:1
>>> g1 = g0.cpu()
>>> print(g1.device)
cpu
```

In the future, DGL will forbidden any operations whose input graphs or tensors have different device contexts and index types. Examples are:
* In `dgl.batch(graphs)`, the input graphs must all share the same device and index type.
* In `g.in_edges(nodes)`, if the `nodes` argument is of tensor type, it should have the same device and index type as `g`. Otherwise, the `nodes` argument must be a list or other python iterable and are converted to a tensor automatically.
* In `g.adj()`, the returned adjacency matrix will follow the device and index type of `g`.

These operations are carried out on the same device as their arguments.

### Dependency
The proposal depends on #1118 which removes graph data structure based on adjacency list.

### Implementation
The major effort comes from implementing operators on GPU. They include:
* All kinds of topological query such as `in_edges`, `in_degrees`, `subgraph` and so on. Fortunately,  #699 has implemented most operators on graphs as operators on sparse matrix (in `array.h`).
* Batching/unbatching.
* Graph traversal like BFS, DFS, topological. These operators are hard to implement on GPU. At the moment, we could throw `NotImplemented` error. To maintain backward compatibility, `DGLGraph.prop_nodes_topo` could first copy the graph to CPU, traverse the graph and use it to guide message passing on GPU.

@zheng-da @classicsong @VoVAllen @yzh119 Could you guys review this RFC?

**Comment by VoVAllen** [comment]
Fail `Graph traversal` on GPU seems not good. How much effort/extra code is needed to fall back to cpu?

**Comment by classicsong** [comment]
Agree with VoVAllen. We can give a warning or have a TODO hint for our self about that the Graph traversal is not done in GPU. But we can use CPU to do the traversal and copy data back to the GPU. 
We can make it work and then optimize it.
