### ISSUE TITLE
About unsupervised GraphSAGE

### ISSUE THREAD

**Issue by PuZhang-github** [dmlc/dgl#1121]
## ❓ Questions and Help

I want to implement graphsage_unsupervised on a giant graph, which need to sample neighbor nodes and do negative sampling. I want to employ the function "dgl.contrib.sampling.EdgeSampler",however, the returned result "pos_edges, neg_edges" is not what I want. As the returned negative edges exist in the original graph, and some positive edges exist in the neg_edges, although I set exclude_positive=True. I want to know how can I  implement unsupervised graphsage on a giant graph?

**Comment by classicsong** [comment]
Can you specify the sampling problem in more details? Current Edge-Sampler will first samples a batch of positive edges (positive node pairs witch means node A and B are connected with some relation), the it will corrupt one of the node in the positive edge (either A or B) for example A with a randomly sampled node C that do not have relation with B (which is the negative sampling). The sampled positive edges (e.g., A->B) will be stored in pos_subg and The sampled negative edges (e.g., C->B) will be stored in neg_subg.

I your case, I think, you can use Edge-Sampler to get your positive node pairs and negative node pairs. The you use these nodes as the starting point of the neighbor sampling.

**Comment by PuZhang-github** [comment]
The following is my code and the result of the first sampling, there is intersections between positive edges and negative edges. Is also has interactions between  negative edges and the edges in the original graph, which confuses me.

def testEdgeSampler():
    g = generate_rand_graph(100)
    etype = np.random.randint(0, 10, size=g.number_of_edges(), dtype=np.int64)
    g.edata['etype'] = F.tensor(etype)
    pos_gsrc, pos_gdst, pos_geid = g.all_edges(form='all', order='eid')
    pos_map = {}
    for i in range(len(pos_geid)):
        pos_d = int(F.asnumpy(pos_gdst[i]))
        pos_e = int(F.asnumpy(pos_geid[i]))
        pos_map[(pos_d, pos_e)] = int(F.asnumpy(pos_gsrc[i]))
    x = g.to_networkx()
    list_all = list(x.edges())
    print("list_all",list_all)
    EdgeSampler = getattr(dgl.contrib.sampling, 'EdgeSampler')
    for pos_edges, neg_edges in EdgeSampler(g, 50,
                                            negative_mode='head',
                                            neg_sample_size=10,
                                            exclude_positive=True,
                                            return_false_neg=True):
        pos = pos_edges.to_networkx()
        pos_list = list(pos.edges())
        print("pos_list:", pos_list)
        neg = neg_edges.to_networkx()
        neg_list = list(neg.edges())
        print("neg_list:", neg_list)
        print("intersection between neg_list and list_all",list(set(neg_list).intersection(set(list_all))))
        print("intersection between neg_list and pos_list", list(set(neg_list).intersection(set(pos_list))))
        print(neg_edges.edata['false_neg'])



list_all [(0, 0), (0, 5), (0, 31), (0, 34), (0, 49), (0, 51), (0, 61), (0, 62), (0, 63), (0, 75), (0, 80), (0, 85), (0, 91), (0, 94), (1, 1), (1, 15), (1, 31), (1, 35), (1, 48), (1, 60), (1, 65), (1, 72), (1, 73), (1, 76), (1, 78), (1, 80), (1, 85), (1, 90), (1, 97), (2, 17), (2, 26), (2, 28), (2, 41), (2, 42), (2, 43), (2, 45), (2, 52), (2, 57), (2, 58), (2, 62), (2, 68), (2, 91), (2, 92), (3, 0), (3, 1), (3, 3), (3, 18), (3, 37), (3, 40), (3, 49), (3, 54), (3, 55), (3, 57), (3, 59), (3, 66), (3, 72), (3, 81), (3, 84), (3, 87), (4, 3), (4, 23), (4, 32), (4, 34), (4, 37), (4, 45), (4, 47), (4, 60), (4, 72), (4, 83), (5, 31), (5, 33), (5, 52), (5, 55), (5, 56), (5, 58), (5, 60), (5, 72), (5, 82), (6, 1), (6, 16), (6, 29), (6, 30), (6, 37), (6, 52), (6, 53), (6, 56), (6, 69), (6, 87), (6, 94), (7, 1), (7, 11), (7, 21), (7, 30), (7, 75), (7, 78), (7, 79), (7, 81), (8, 0), (8, 1), (8, 12), (8, 14), (8, 16), (8, 29), (8, 49), (8, 59), (8, 64), (8, 66), (8, 68), (8, 77), (8, 87), (8, 93), (8, 98), (9, 15), (9, 26), (9, 33), (9, 53), (9, 56), (9, 64), (9, 81), (9, 87), (9, 97), (9, 99), (10, 4), (10, 5), (10, 21), (10, 23), (10, 29), (10, 34), (10, 42), (10, 59), (10, 64), (10, 71), (10, 83), (11, 3), (11, 11), (11, 45), (11, 78), (11, 79), (11, 94), (12, 11), (12, 15), (12, 24), (12, 33), (12, 34), (12, 39), (12, 41), (12, 47), (12, 48), (12, 86), (12, 93), (12, 94), (13, 7), (13, 14), (13, 15), (13, 17), (13, 22), (13, 29), (13, 41), (13, 43), (13, 45), (13, 46), (13, 48), (13, 62), (13, 77), (13, 83), (13, 84), (13, 98), (14, 0), (14, 26), (14, 33), (14, 44), (14, 45), (14, 54), (14, 58), (14, 74), (14, 75), (14, 82), (14, 87), (14, 92), (14, 94), (15, 3), (15, 13), (15, 22), (15, 26), (15, 30), (15, 73), (15, 74), (15, 80), (15, 91), (15, 95), (15, 96), (16, 3), (16, 4), (16, 15), (16, 23), (16, 25), (16, 42), (16, 45), (16, 47), (16, 62), (16, 65), (16, 70), (16, 72), (16, 75), (17, 12), (17, 16), (17, 24), (17, 33), (17, 38), (17, 42), (17, 65), (17, 70), (17, 74), (17, 85), (17, 92), (17, 93), (17, 94), (18, 3), (18, 5), (18, 14), (18, 16), (18, 20), (18, 28), (18, 57), (18, 69), (18, 76), (18, 85), (18, 86), (19, 1), (19, 30), (19, 35), (19, 48), (19, 49), (19, 50), (19, 81), (19, 88), (19, 99), (20, 20), (20, 24), (20, 26), (20, 28), (20, 61), (20, 72), (20, 74), (20, 76), (20, 80), (20, 85), (20, 87), (20, 94), (20, 99), (21, 3), (21, 6), (21, 11), (21, 39), (21, 43), (21, 45), (21, 47), (21, 52), (21, 54), (21, 55), (21, 60), (21, 66), (21, 78), (21, 89), (22, 25), (22, 29), (22, 31), (22, 41), (22, 48), (22, 58), (22, 75), (23, 0), (23, 6), (23, 11), (23, 16), (23, 25), (23, 28), (23, 30), (23, 31), (23, 37), (23, 41), (23, 44), (23, 51), (23, 53), (23, 66), (23, 73), (23, 80), (23, 91), (24, 6), (24, 12), (24, 21), (24, 58), (25, 20), (25, 46), (25, 66), (25, 78), (26, 10), (26, 17), (26, 29), (26, 35), (26, 50), (26, 58), (26, 68), (27, 26), (27, 29), (27, 48), (27, 55), (27, 56), (27, 60), (27, 67), (27, 77), (27, 81), (27, 88), (28, 51), (28, 59), (28, 63), (28, 64), (28, 67), (28, 72), (28, 77), (28, 78), (28, 83), (28, 87), (28, 98), (29, 0), (29, 20), (29, 35), (29, 49), (29, 63), (29, 75), (29, 86), (29, 87), (30, 3), (30, 13), (30, 17), (30, 31), (30, 41), (30, 46), (30, 48), (30, 66), (30, 68), (30, 79), (30, 90), (30, 99), (31, 0), (31, 1), (31, 16), (31, 17), (31, 32), (31, 46), (31, 47), (31, 53), (31, 62), (31, 66), (31, 72), (31, 79), (31, 87), (31, 97), (32, 5), (32, 9), (32, 17), (32, 22), (32, 30), (32, 70), (32, 79), (32, 85), (33, 0), (33, 3), (33, 7), (33, 18), (33, 22), (33, 30), (33, 58), (33, 60), (33, 73), (33, 89), (33, 92), (33, 97), (33, 98), (34, 25), (34, 33), (34, 34), (34, 38), (34, 47), (34, 52), (34, 66), (34, 68), (34, 81), (34, 88), (34, 91), (35, 0), (35, 1), (35, 3), (35, 7), (35, 18), (35, 56), (35, 57), (35, 72), (35, 75), (35, 82), (35, 93), (36, 0), (36, 22), (36, 74), (36, 76), (36, 83), (37, 6), (37, 27), (37, 33), (37, 38), (37, 39), (37, 43), (37, 55), (37, 81), (37, 85), (38, 32), (38, 40), (38, 43), (38, 44), (38, 46), (38, 59), (38, 74), (38, 79), (38, 81), (38, 90), (38, 92), (39, 0), (39, 4), (39, 13), (39, 22), (39, 30), (39, 41), (39, 60), (39, 69), (39, 75), (39, 82), (39, 84), (39, 90), (40, 23), (40, 41), (40, 45), (40, 46), (40, 54), (40, 59), (40, 63), (40, 69), (40, 76), (40, 93), (41, 19), (41, 35), (41, 57), (41, 78), (41, 83), (42, 7), (42, 38), (42, 44), (42, 47), (42, 49), (42, 64), (42, 76), (42, 77), (42, 79), (42, 81), (42, 83), (43, 5), (43, 67), (43, 68), (43, 82), (43, 87), (43, 96), (44, 1), (44, 23), (44, 51), (44, 55), (44, 71), (44, 74), (44, 76), (44, 77), (44, 89), (44, 96), (45, 2), (45, 11), (45, 20), (45, 21), (45, 25), (45, 30), (45, 31), (45, 60), (45, 94), (46, 3), (46, 36), (46, 66), (46, 71), (46, 76), (46, 81), (46, 84), (46, 88), (46, 89), (47, 0), (47, 4), (47, 6), (47, 11), (47, 12), (47, 13), (47, 21), (47, 30), (47, 47), (47, 49), (47, 55), (47, 65), (47, 70), (47, 84), (47, 88), (47, 95), (48, 2), (48, 56), (48, 57), (48, 75), (48, 91), (49, 3), (49, 11), (49, 21), (49, 22), (49, 40), (49, 49), (49, 50), (49, 61), (49, 63), (49, 77), (49, 88), (49, 90), (49, 91), (50, 0), (50, 4), (50, 8), (50, 16), (50, 27), (50, 33), (50, 35), (50, 50), (50, 52), (50, 55), (50, 65), (50, 66), (50, 68), (50, 71), (50, 78), (51, 2), (51, 18), (51, 22), (51, 31), (51, 32), (51, 41), (51, 47), (51, 48), (51, 58), (51, 69), (51, 70), (52, 2), (52, 9), (52, 22), (52, 62), (52, 65), (52, 79), (53, 12), (53, 14), (53, 27), (53, 50), (53, 56), (53, 58), (53, 67), (53, 76), (53, 77), (53, 97), (54, 12), (54, 22), (54, 31), (54, 67), (54, 74), (54, 90), (55, 6), (55, 11), (55, 13), (55, 16), (55, 28), (55, 33), (55, 49), (55, 71), (55, 83), (55, 91), (55, 96), (56, 8), (56, 10), (56, 11), (56, 48), (56, 51), (57, 4), (57, 32), (57, 38), (57, 49), (57, 74), (57, 87), (57, 98), (58, 9), (58, 15), (58, 16), (58, 17), (58, 23), (58, 24), (58, 40), (58, 70), (58, 81), (58, 83), (59, 2), (59, 53), (59, 54), (59, 55), (59, 81), (60, 3), (60, 9), (60, 13), (60, 16), (60, 17), (60, 22), (60, 23), (60, 31), (60, 60), (60, 82), (60, 83), (60, 86), (60, 98), (61, 4), (61, 7), (61, 12), (61, 30), (61, 58), (61, 61), (61, 62), (61, 65), (61, 72), (61, 83), (61, 89), (61, 91), (62, 15), (62, 18), (62, 36), (62, 43), (62, 50), (62, 56), (62, 60), (62, 72), (62, 83), (62, 87), (62, 93), (63, 2), (63, 5), (63, 19), (63, 49), (63, 61), (63, 63), (63, 86), (63, 90), (64, 7), (64, 18), (64, 26), (64, 34), (64, 57), (64, 74), (64, 82), (64, 87), (64, 88), (64, 99), (65, 2), (65, 7), (65, 9), (65, 19), (65, 21), (65, 34), (65, 56), (65, 67), (65, 83), (65, 89), (65, 97), (65, 99), (66, 52), (66, 57), (66, 62), (66, 79), (66, 99), (67, 2), (67, 3), (67, 5), (67, 20), (67, 37), (67, 40), (67, 43), (67, 54), (67, 69), (67, 82), (67, 84), (68, 5), (68, 6), (68, 10), (68, 15), (68, 17), (68, 21), (68, 28), (68, 47), (68, 59), (68, 69), (68, 79), (68, 88), (69, 1), (69, 15), (69, 27), (69, 38), (69, 42), (69, 52), (69, 71), (69, 80), (70, 9), (70, 30), (70, 35), (70, 41), (70, 51), (70, 59), (70, 60), (70, 68), (70, 77), (70, 86), (71, 9), (71, 10), (71, 27), (71, 37), (71, 40), (71, 47), (71, 74), (71, 87), (71, 98), (72, 8), (72, 13), (72, 14), (72, 16), (72, 38), (72, 46), (72, 48), (72, 52), (72, 55), (72, 58), (72, 64), (72, 70), (72, 77), (72, 78), (72, 86), (72, 89), (72, 99), (73, 6), (73, 13), (73, 24), (73, 26), (73, 29), (73, 34), (73, 39), (73, 47), (73, 87), (73, 98), (74, 2), (74, 56), (74, 80), (74, 81), (74, 85), (74, 86), (74, 95), (75, 11), (75, 15), (75, 17), (75, 20), (75, 44), (75, 45), (75, 47), (75, 85), (75, 92), (75, 94), (75, 99), (76, 0), (76, 3), (76, 5), (76, 28), (76, 61), (76, 73), (76, 80), (76, 82), (76, 91), (77, 5), (77, 44), (77, 60), (77, 69), (77, 70), (77, 73), (78, 10), (78, 15), (78, 26), (78, 75), (78, 81), (78, 82), (79, 30), (79, 32), (79, 33), (79, 48), (79, 82), (80, 0), (80, 11), (80, 40), (80, 60), (80, 80), (81, 3), (81, 40), (81, 43), (81, 53), (81, 54), (81, 66), (81, 81), (81, 84), (81, 88), (82, 5), (82, 7), (82, 34), (82, 50), (82, 64), (82, 72), (82, 78), (82, 83), (83, 4), (83, 6), (83, 11), (83, 13), (83, 16), (83, 33), (83, 49), (83, 51), (83, 59), (83, 73), (83, 82), (83, 86), (83, 97), (84, 10), (84, 16), (84, 21), (84, 24), (84, 28), (84, 40), (84, 46), (84, 52), (84, 60), (84, 76), (84, 82), (84, 83), (85, 17), (85, 41), (85, 58), (85, 60), (85, 66), (85, 74), (85, 90), (85, 94), (86, 2), (86, 5), (86, 22), (86, 25), (86, 36), (86, 43), (86, 57), (86, 70), (87, 4), (87, 10), (87, 22), (87, 31), (87, 33), (87, 37), (87, 38), (87, 66), (87, 74), (87, 78), (87, 81), (87, 91), (87, 95), (88, 0), (88, 3), (88, 11), (88, 26), (88, 73), (88, 74), (88, 90), (89, 7), (89, 21), (89, 54), (89, 55), (89, 62), (89, 67), (89, 91), (89, 99), (90, 2), (90, 5), (90, 10), (90, 11), (90, 37), (90, 41), (90, 48), (90, 50), (90, 65), (90, 66), (90, 67), (90, 75), (90, 91), (91, 2), (91, 16), (91, 18), (91, 48), (91, 77), (91, 81), (91, 87), (91, 97), (92, 0), (92, 5), (92, 16), (92, 23), (92, 24), (92, 25), (92, 39), (92, 62), (92, 74), (93, 9), (93, 13), (93, 15), (93, 33), (93, 49), (93, 70), (93, 74), (93, 80), (93, 93), (93, 98), (93, 99), (94, 7), (94, 14), (94, 17), (94, 28), (94, 31), (94, 41), (94, 50), (94, 57), (94, 78), (94, 86), (94, 87), (94, 88), (95, 7), (95, 17), (95, 30), (95, 35), (95, 43), (95, 46), (95, 57), (95, 65), (95, 76), (95, 88), (95, 94), (96, 0), (96, 33), (96, 51), (96, 64), (96, 73), (96, 78), (96, 82), (96, 90), (96, 96), (96, 98), (97, 15), (97, 35), (97, 43), (97, 68), (97, 69), (97, 88), (98, 14), (98, 20), (98, 24), (98, 38), (98, 40), (98, 43), (98, 48), (98, 50), (98, 51), (98, 57), (98, 59), (99, 7), (99, 15), (99, 33), (99, 39), (99, 65), (99, 73), (99, 86), (99, 87)]
pos_list: [(0, 0), (0, 4), (0, 5), (0, 6), (0, 7), (0, 8), (0, 9), (0, 10), (0, 11), (0, 12), (0, 13), (0, 14), (0, 15), (0, 16), (1, 1), (1, 17), (1, 5), (1, 18), (1, 19), (1, 20), (1, 21), (1, 22), (1, 23), (1, 24), (1, 25), (1, 13), (1, 14), (1, 26), (1, 27), (2, 28), (2, 29), (2, 30), (2, 31), (2, 32), (2, 33), (2, 34), (2, 35), (2, 36), (2, 37), (2, 10), (2, 38), (2, 15), (2, 39), (3, 0), (3, 1), (3, 3), (3, 40), (3, 41), (3, 42), (3, 7)]
neg_list: [(0, 14), (0, 15), (0, 21), (0, 27), (0, 32), (1, 3), (2, 4), (2, 11), (2, 34), (2, 35), (2, 12), (3, 2), (3, 8), (3, 16), (3, 17), (3, 26), (3, 34), (3, 14), (3, 41), (4, 7), (4, 2), (4, 19), (4, 20), (4, 21), (4, 27), (5, 3), (5, 22), (5, 27), (5, 30), (6, 4), (6, 26), (7, 1), (7, 3), (7, 8), (7, 2), (7, 29), (7, 41), (8, 0), (8, 5), (8, 7), (8, 19), (8, 11), (8, 29), (8, 37), (8, 41), (9, 1), (9, 18), (9, 7), (9, 4), (10, 7), (10, 22), (10, 23), (10, 28), (10, 34), (10, 38), (10, 4), (11, 3), (11, 2), (11, 19), (12, 30), (12, 4), (13, 1), (13, 8), (13, 9), (13, 11), (13, 24), (13, 38), (14, 4), (14, 13), (14, 27), (14, 31), (14, 32), (14, 37), (14, 38), (15, 23), (15, 35), (15, 14), (15, 4), (16, 12), (16, 15), (16, 22), (16, 11), (16, 26), (16, 36), (17, 11), (17, 14), (17, 29), (17, 32), (18, 13), (18, 15), (18, 23), (18, 24), (18, 7), (18, 0), (19, 12), (19, 14), (19, 22), (19, 23), (19, 31), (19, 34), (20, 0), (20, 6), (20, 7), (20, 19), (20, 34), (21, 0), (21, 19), (21, 21), (22, 3), (22, 11), (22, 17), (22, 18), (22, 20), (22, 32), (22, 39), (23, 4), (23, 8), (23, 12), (23, 21), (23, 22), (23, 10), (23, 30), (23, 37), (23, 38), (24, 24), (24, 0), (25, 10), (25, 21), (25, 7), (25, 12), (26, 1), (26, 6), (26, 10), (26, 12), (26, 18), (26, 26), (26, 32), (27, 0), (27, 9), (27, 11), (27, 15), (27, 18), (27, 33), (27, 38), (27, 39), (27, 4), (28, 2), (28, 13), (28, 21), (28, 11), (28, 31), (28, 0), (29, 2), (29, 20), (29, 29), (30, 13), (30, 40), (31, 24), (31, 25), (31, 33), (31, 35), (31, 41), (32, 5), (32, 8), (32, 37), (32, 38), (33, 8), (33, 10), (33, 21), (33, 24), (33, 25), (33, 26), (33, 29), (33, 30), (33, 0), (33, 40), (33, 4), (34, 3), (34, 6), (34, 12), (34, 16), (34, 25), (34, 28), (34, 33), (34, 36), (34, 39), (34, 40), (35, 2), (35, 7), (35, 10), (35, 24), (35, 27), (35, 33), (35, 36), (35, 12), (36, 16), (36, 19), (36, 24), (36, 25), (36, 36), (37, 14), (37, 18), (37, 39), (38, 2), (38, 5), (38, 11), (38, 18), (38, 23), (38, 36), (39, 6), (39, 14), (39, 18), (39, 19), (39, 40), (40, 14), (40, 26), (40, 29), (41, 12), (41, 18), (41, 11), (41, 37), (41, 14), (42, 0), (42, 2), (42, 9), (42, 17), (42, 11), (42, 12), (42, 39), (43, 0), (43, 28), (43, 39), (43, 41), (44, 0), (44, 26), (44, 31), (45, 0), (45, 1), (45, 27), (45, 12), (45, 37), (46, 0), (46, 2), (46, 10), (47, 0), (47, 4), (47, 13), (47, 17), (47, 22), (47, 39), (48, 1), (48, 2), (48, 16), (48, 17), (48, 18), (48, 10), (48, 25), (48, 14), (48, 40), (49, 1), (49, 5), (49, 6), (49, 9), (49, 10), (49, 14), (50, 1), (50, 8), (50, 17), (50, 34), (50, 35), (50, 37), (51, 1), (51, 34), (51, 35), (51, 14), (52, 1), (52, 4), (52, 8), (52, 20), (52, 23), (52, 25), (52, 32), (53, 2), (53, 30), (53, 31), (54, 2), (54, 6), (54, 28), (54, 35), (55, 3), (55, 15), (55, 7), (55, 41), (55, 4), (56, 3), (56, 5), (56, 2), (56, 17), (56, 23), (56, 29), (56, 36), (57, 3), (57, 33), (58, 3), (58, 7), (58, 11), (59, 4), (59, 12), (59, 18), (59, 19), (59, 21), (59, 29), (59, 35), (59, 0), (60, 4), (60, 16), (60, 20), (60, 23), (60, 27), (60, 0), (61, 4), (61, 12), (61, 10), (61, 35), (61, 7), (61, 14), (62, 4), (62, 10), (62, 14), (62, 28), (62, 31), (62, 33), (62, 7), (63, 5), (63, 25), (64, 5), (64, 19), (64, 34), (64, 40), (64, 41), (65, 5), (65, 15), (65, 24), (65, 36), (66, 5), (66, 8), (66, 13), (66, 20), (66, 32), (66, 34), (66, 41), (66, 4), (67, 5), (67, 7), (67, 15), (68, 6), (68, 10), (68, 22), (69, 6), (69, 2), (69, 22), (69, 28), (69, 30), (70, 6), (70, 7), (70, 17), (70, 20), (70, 10), (70, 14), (71, 6), (71, 11), (71, 13), (71, 19), (71, 28), (71, 30), (71, 34), (71, 12), (71, 14), (72, 7), (72, 10), (72, 37), (73, 7), (73, 12), (73, 14), (73, 20), (73, 23), (73, 28), (73, 30), (73, 35), (73, 36), (74, 8), (74, 16), (74, 20), (74, 10), (75, 9), (76, 9), (76, 11), (76, 17), (76, 36), (77, 9), (77, 10), (77, 13), (77, 32), (77, 38), (78, 9), (78, 11), (78, 27), (78, 28), (78, 29), (78, 32), (78, 36), (79, 9), (79, 24), (80, 9), (80, 11), (80, 13), (80, 2), (80, 16), (80, 4), (81, 10), (81, 14), (81, 33), (81, 12), (82, 11), (82, 15), (82, 25), (82, 29), (82, 0), (83, 12), (83, 13), (83, 16), (83, 22), (83, 26), (83, 38), (83, 39), (84, 14), (84, 28), (84, 35), (84, 41), (85, 15), (85, 21), (85, 30), (86, 15), (86, 22), (86, 10), (86, 11), (86, 31), (86, 33), (86, 39), (87, 2), (87, 10), (87, 39), (87, 41), (87, 4), (88, 16), (89, 16), (89, 11), (89, 30), (89, 7), (89, 40), (90, 17), (90, 24), (90, 33), (90, 7), (90, 38), (91, 20), (91, 0), (92, 21), (92, 25), (92, 27), (93, 23), (93, 25), (93, 26), (93, 40), (94, 10), (94, 11), (94, 26), (94, 31), (95, 27), (95, 32), (95, 40), (96, 31), (96, 38), (97, 31), (97, 37), (98, 33), (98, 40), (99, 37), (99, 0)]
intersection between neg_list and list_all [(68, 10), (80, 11), (23, 37), (87, 10), (98, 40), (8, 0), (89, 7), (34, 25), (83, 13), (33, 30), (64, 34), (30, 13), (10, 34), (67, 5), (23, 30), (47, 13), (50, 35), (68, 6), (86, 22), (83, 16), (37, 39), (48, 2), (84, 28), (8, 29), (16, 15), (35, 7), (61, 4), (50, 8), (92, 25), (87, 4), (10, 4), (7, 1), (60, 23), (63, 5), (47, 0), (34, 33), (61, 12), (94, 31), (47, 4), (10, 23), (61, 7), (60, 16), (29, 20), (11, 3), (32, 5), (26, 10), (33, 0)]
intersection between neg_list and pos_list [(0, 15), (0, 14), (3, 41), (2, 35), (2, 34)]

**Comment by classicsong** [comment]
You should check neg_subg.edata['false_neg'] for whether a edge in neg_subg is a True neg or not.

**Comment by PuZhang-github** [comment]
All the false_neg is 0.

**Comment by classicsong** [comment]
Also both pos_subg and neg_subg use local node_id, you should convert it into global_id by doing as following:
```
neg_lsrc, neg_ldst, neg_leid = neg_edges.all_edges(form='all', order='eid')
neg_src = neg_edges.parent_nid[neg_lsrc]
neg_dst = neg_edges.parent_nid[neg_ldst]
```
The neg_edges.parent_nid contains the mapping from local to global.

**Comment by PuZhang-github** [comment]
Get it,many thanks.
