### ISSUE TITLE
Where is the test file .../label 2/googlescholar.8area.author.label.txt

### ISSUE THREAD

**Issue by xemcerk** [dmlc/dgl#1122]
In the script **examples/pytorch/metapath2vec/test.py**, it says the test file's path is ".../label 2/googlescholar.8area.author.label.txt". 
Then I search **the whole repository** and directly google that file name, but still couldn't find it. 
Is that file omitted while pushing? Or I have to make one on my own?

**Comment by xemcerk** [comment]
And I search the discussion forum, still no result.
ddl is close, desparated.

**Comment by xemcerk** [comment]
I found that test file in the author's website...
[https://ericdongyx.github.io/metapath2vec/m2v.html](url)

**Comment by ziqiaomeng** [comment]
Sorry for late reply. The test dataset is available in author's website. I think I probably forget to upload it to s3. Will fix this issue in the future when I have time.

**Comment by xemcerk** [comment]
> Sorry for late reply. The test dataset is available in author's website. I think I probably forget to upload it to s3. Will fix this issue in the future when I have time.

tons of thx!
