### ISSUE TITLE
Got 'Check failed: allocated_.size() == 1 (2 vs. 1)' after 80 epochs

### ISSUE THREAD

**Issue by benbijituo** [dmlc/dgl#1126]
## 🐛 Bug
After training 80 epochs, I got this bug:
![image](https://user-images.githubusercontent.com/45055255/71305715-c026c900-2412-11ea-8456-ef51f86c80bc.png)
I don't know where should I begin to debug it because the first 80 epochs run well.
Some clues:
1. Since I pip-installed DGL, I updated mxnet to 1.5. There might be some correlations between the two Amazon projects
2. For my code, graph is build upon BERT encoder and which was run on 4 1080Ti. I used to try the same batch size solely on BERT encoder and everything was going well. Only after a graph was added, this bug appeared.

## Environment
PyTorch 1.0
dgl-cuda10.1
CUDA 10.1

**Comment by VoVAllen** [comment]
What do you mean by `a graph was added`?
Does the bug always occursed after epoch 81? 
Also could you try uninstall mxnet and see whether the bug still exists?

**Comment by benbijituo** [comment]
> What do you mean by `a graph was added`?
> Does the bug always occursed after epoch 81?
> Also could you try uninstall mxnet and see whether the bug still exists?
"A graph was added" means the others codes are okay, but when I add your DGLGraph in my project, this bug appears. And it only appears after training several epochs
Now I create a new conda env, but this bug still happens after 40 epochs
![image](https://user-images.githubusercontent.com/45055255/71342625-47517980-2598-11ea-87e7-2ccdb0457430.png)
