### ISSUE TITLE
problem on distributed sampling example

### ISSUE THREAD

**Issue by hynsk** [dmlc/dgl#1129]
Hello.

I'm testing distributed sampling of dgl according to https://github.com/dmlc/dgl/tree/master/examples/mxnet/sampling/dis_sampling

when I run
$ DGLBACKEND=mxnet python3 sampler.py --model gcn_ns --dataset cora --self-loop --num-neighbors 2 --batch-size 1000 --ip 127.0.0.1:50051 --num-sampler 1

The program is freezed.

For details, it freezed at 
https://github.com/dmlc/dgl/blob/master/python/dgl/contrib/sampling/sampler.py
line 32 : nfobjs = _CAPI_NeighborSampling

I think this is kind of parallel process problem.
Because in sampler.py code, it use SamplerPool abstract class that uses Pool for parallel process. And it isn't freezed when I modified MySamplerPool does not inherit SamplerPool class.

Can you let me know how to solve this problem?

Thank you.

**Comment by aksnzhy** [comment]
@hynsk Hi, can you try to add `OMP_NUM_THREADS=1` in the head of your command line?

**Comment by hynsk** [comment]
@aksnzhy 
OMP_NUM_THREADS=1 works well
Can you explain the reason and guide docs link about it?
Thank you for your help.

**Comment by aksnzhy** [comment]
@hynsk This is a bug caused by openmp library. On some intel gcc compiler, the openmp library can cause a deadlock bug when using fork() for multiple processes. I will add this into the document.

Thanks so much!

**Comment by hynsk** [comment]
@aksnzhy 
Thank you so much!
