### ISSUE TITLE
Core dumps in run a graph store server 

### ISSUE THREAD

**Issue by hynsk** [dmlc/dgl#1136]
## 🐛 Bug

https://github.com/dmlc/dgl/tree/master/examples/mxnet/sampling
In the last part of README, I'm trying to run multi-processing training.
so I run like this
python3 ./run_store_server.py --dataset cora --num-workers 4
then it stopped with
Bus error (core dumped)

## To Reproduce

just run below command

$ DGLBACKEND=mxnet python3 ./run_store_server.py --dataset cora --num-workers 4
----Data statistics------'
      #Edges 10556
      #Classes 7
      #Train samples 140
      #Val samples 300
      #Test samples 1000
graph name: cora
/usr/local/lib/python3.5/dist-packages/dgl/base.py:25: FutureWarning: Adjacency matrix by default currently returns edge IDs.  As a result there is one 0 entry which is not eliminated.  In the next release it will return 1s by default, and 0 will be eliminated otherwise.
  warnings.warn(msg, warn_type)
Bus error (core dumped)

## Expected behavior
I expect server runs.

## Environment
 - DGL Version : latest
 - Backend Library & Version : MXNet
 - OS: ubuntu 16.04
 - How you installed DGL: pip
 - Python version: python3.5
 - Any other relevant information: run it with docker

## Additional context
I test another pc(also with docker), it doesn't cause problem. So I think it's environment problem.

**Comment by hynsk** [comment]
For details, I think it makes core dump in 
https://github.com/dmlc/dgl/blob/master/python/dgl/contrib/graph_store.py
line 329,
graph_idx = from_csr(utils.toindex(indptr), utils.toindex(indices), multigraph, edge_dir, _get_graph_path(graph_name))

**Comment by NlpRookie** [comment]
Hey, man。 Did you solve this problem?

**Comment by savemuri** [comment]
Is this solved? I am still unable to find a solution to make graph store work.

**Comment by aksnzhy** [comment]
@savemuri Hi, the graphstore is not been used anymore. We are now using DistGraph instead of that. Please see the example: https://github.com/dmlc/dgl/tree/master/examples/pytorch/graphsage/experimental Thanks!
