### ISSUE TITLE
GraphSAGE implementation

### ISSUE THREAD

**Issue by ralzq01** [dmlc/dgl#1141]
## ❓ Questions and Help

Hi, after reading implementations in [sageconv](https://github.com/dmlc/dgl/blob/master/python/dgl/nn/pytorch/conv/sageconv.py), I find in DGL the forwarding does `fc(max(feats))` (take pooling aggegator for example) while in author's paper is `max(fc(feats))`. Can `max` and `fc` be exchanged with equivalence?

**Comment by yzh119** [comment]
Hi, 
I think what I wrote is actually `max(fc(feats))`:
https://github.com/dmlc/dgl/blob/master/python/dgl/nn/pytorch/conv/sageconv.py#L120-L121

**Comment by ralzq01** [comment]
Yeah, you are right. I read it wrong.
