### ISSUE TITLE
[Bug] BatchedDGLGraph is not readonly

### ISSUE THREAD

**Issue by mufeili** [dmlc/dgl#1148]
## 🐛 Bug

`BatchedDGLGraph` is not readonly while it is supposed to be readonly based on the documentation.

## To Reproduce

```python
import dgl

g1 = dgl.DGLGraph()
g2 = dgl.DGLGraph()
bg = dgl.batch([g1, g2])
bg.is_readonly # False
```

## Expected behavior

```python
bg.is_readonly # True
```

## Additional context

Reported in [discussion thread 645](https://discuss.dgl.ai/t/implementing-a-batch-of-batches/645/2).

**Comment by VoVAllen** [comment]
Batching mutable graph results in a mutable batchedgraph. It's expected. Maybe we want to fix our doc.

**Comment by mufeili** [comment]
@VoVAllen , this is not only reflected in the documentation, but also in APIs like [`add_nodes`, `add_edge` and `add_edges`](https://github.com/dmlc/dgl/blob/master/python/dgl/batched_graph.py#L253). Copy @jermainewang and @BarclayII .
