### ISSUE TITLE
[RFC] Unify the interface of BatchedDGLGraph, DGLSubGraph and DGLGraph

### ISSUE THREAD

**Issue by yzh119** [dmlc/dgl#1153]
## 🚀 Feature

This is the first step towards a unified graph interface(the next step is to merge HeteroDGLGraph and DGLGraph).

## Motivation

Currently we have several graph classes: HeteroGraph, BatchedHeteroGraph, BatchedDGLGraph, DGLSubGraph and DGLGraph, it's difficult to maintain so many seperated graph structures and make the interface consistent. (e.g. #1146 ).

## Pitch

A much cleaner interface like [torch.tensor](https://pytorch.org/docs/stable/torch.html#torch.tensor) to replace DGLSubGraph and BatchedDGLGraph. The refactor could both ease the developers' workload and make the interface easier for users.

## Additional context

The SubDGLGraph class and BatchedDGLGraph should not be deprecated soon, and we should redirect them to `dgl.graph(is_subgraph=True)` and `dgl.graph(batch_size=xx)`.

Pay attention to the use of `isinstance(g, SubDGLGraph)` and `instance(g, BatchedDGLGraph)` and replace them with DGLGraph class methods.

**Comment by jermainewang** [comment]
Would you mind elaborating more about the new APIs and behaviors of DGLGraph when they are merged? For example, I'd like to see a one-one correspondence between the old APIs and the new ones.

**Comment by mufeili** [comment]
# Data Structure Comparison
## `DGLGraph` vs `BatchedDGLGraph`
- `BatchedDGLGraph` has three additional internal attributes `_batch_size`, `_batch_num_nodes` and `_batch_num_edges` and three associated class functions `batch_size`, `batch_num_nodes` and `batch_num_edges`.
- `BatchedDGLGraph` is readonly. Therefore mutations like `add_nodes`, `add_edge`, `add_edges`, `remove_nodes`, `remove_edges` and `clear` should be forbidden in these cases. Currently, these are not well handled.
- Two class functions to be implemented for `BatchedDGLGraph`: `__getitem__(self, idx)` and `__setitem__(self, idx, val)`.

## `DGLGraph` vs `DGLSubGraph` 
- `DGLSubGraph` has four additional internal attributes `_parent`, `_parent_nid`, `_parent_eid`, `_subgraph_index` and 6 associated class functions `parent_nid`, `_get_parent_eid`, `parent_eid`, `copy_to_parent`, `copy_from_parent` and `map_to_subgraph_nid`.
- `DGLSubGraph` is readonly, just like `BatchedDGLGraph` above.

# New APIs

```python
class DGLGraph(DGLBaseGraph):
    def __init__(self, 
                 graph_data=None,
                 node_frame=None,
                 edge_frame=None,
                 multigraph=None,
                 readonly=False,
                 sort_csr=False,
                 batch_size=1,
                 batch_num_nodes=None,
                 batch_num_edges=None,
                 parent=None,
                 parent_nid=None,
                 parent_eid=None)
```

## Behavior for Old `DGLGraph`

The behavior of the current `DGLGraph` will remain unchanged.

## Behavior for Old `DGLSubGraph`

- The current behavior of the `DGLSubGraph` will remain unchanged, with the only exception being that we will deprecate `_subgraph_index`, which seems a bit redundant to me.
- We can add an API `self.has_parent` for the convenience of non-subgraphs.
- If we want to support share mode of subgraphs, where the subgraph shares node/edge features with the parent graph, we can pass the sliced node/edge frame of the parent graph.

## Behavior for Old `BatchedDGLGraph`

- `dgl.batch` will be responsible for merging graph index, node/edge frames and computing `batch_size`, `batch_num_nodes` and `batch_num_edges`.
- For non-batched graphs, the `batch_size` is 1 by default and `batch_num_nodes/batch_num_edges` will return a list of a single int.
- One possible enhancement with this unification would be to support batched subgraphs.

**Comment by VoVAllen** [comment]
Why aren't we directly merge this with DGLHeteroGraph also? Will we merge them in the future?

**Comment by mufeili** [comment]
Copy @jermainewang . We start with these three data structures because to unify them requires a pure python-based effort. I think we should also merge `DGLHeteroGraph` in the future, but that will need a more in-depth study.

**Comment by jermainewang** [comment]
The overall plan looks good to me. Some inlined comments.

> ## Behavior for Old `DGLSubGraph`
> * If we want to support share mode of subgraphs, where the subgraph shares node/edge features with the parent graph, we can pass the sliced node/edge frame of the parent graph.

We could ignore this support for now.

> ## Behavior for Old `BatchedDGLGraph`
> * One possible enhancement with this unification would be to support batched subgraphs. If all subgraphs share a single parent graph, then they can be batched together.

Shouldn't this be supported naturally? if subgraphs are essentially just DGLGraphs.

**Comment by mufeili** [comment]
> > ## Behavior for Old `BatchedDGLGraph`
> > 
> > * One possible enhancement with this unification would be to support batched subgraphs. If all subgraphs share a single parent graph, then they can be batched together.
> 
> Shouldn't this be supported naturally? if subgraphs are essentially just DGLGraphs.

I was thinking about keeping pointers related to the parent graphs by the time, which will not be an issue if we are going to throw away the parent-graph-related pointers.
