### ISSUE TITLE
Split hetero graph into different sets

### ISSUE THREAD

**Issue by zhangcaifu** [dmlc/dgl#1161]
I've seen the method and example you provided(gcmc pytorch version and https://github.com/dmlc/dgl/blob/master/examples/pytorch/gcn/train.py#L17)
As the example shows how to use masks to split the whole graph, how to use this method in spliting the hetero graph on different types of nodes?

**Comment by jermainewang** [comment]
Hi, sorry for the late reply. You can provide a dictionary of tensors as the mask for different node types. Pseudo-code:
```python
train_mask = {'user' : user_mask_tensor, 'game' : game_mask_tensor}
```
