### ISSUE TITLE
batch method in dgl need to improve and perfect

### ISSUE THREAD

**Issue by yyh14353191** [dmlc/dgl#1165]
the batch method in dgl is not like what i need.For example:
`batch_plan_input = model.gat(batched_graph , query)`
where batched_graph is preprocessed by dgl.batch()
i expect that batch_plan_input is in size(batch_size(such as 32) , ...),but it doesn not.
batch_plan_input  turns out to be in size(227,....)
i think it is the sum of all nodes appeared in the batched_graph.
it is not i need

**Comment by yzh119** [comment]
Hi, GATConv returns the representation of all nodes.
What you need is the combination of GATConv and `SumPooling`, try the following code:
```python
import torch as th
import networkx as nx
import dgl
from dgl.nn.pytorch.conv import GATConv
from dgl.nn.pytorch.glob import SumPooling

g1 = dgl.DGLGraph()
g1.add_nodes(5)
for i in range(5):
    for j in range(5):
        g1.add_edge(i, j)

g2 = dgl.DGLGraph()
g2.add_nodes(4)
for i in range(4):
    g2.add_edge(i, i)

g3 = dgl.DGLGraph()
g3.add_nodes(2)
g3.add_edge(0, 1)

bg = dgl.batch([g1, g2, g3])
x = th.rand(bg.number_of_nodes(), 100)
gat = GATConv(100, 10, 5) # input size: 100, output size: 10, num_heads: 5
pool = SumPooling()
y = pool(bg, gat(bg, x))
print(y.shape)
```
