### ISSUE TITLE
support for CUDA 10.2?

### ISSUE THREAD

**Issue by fguney** [dmlc/dgl#1167]
Would you consider adding support for CUDA 10.2?

**Comment by VoVAllen** [comment]
Sure, we would add it soon. @BarclayII

**Comment by BarclayII** [comment]
CUDA 10.2 should be available as nightly build:

```
pip install --pre dgl-cu102
```

**Comment by Jingyi-MASY** [comment]
Thanks for the support! It would be better if you could also post the nightly build dgl-cu102 link on the readme.md
