### ISSUE TITLE
build_graph in MovieLens class 

### ISSUE THREAD

**Issue by frankbass3** [dmlc/dgl#1182]
## ❓ Questions and Help

Dear Quan (Andy) Gan,

i have a question about the method build_graph in the MovieLens class.
I see that the dataset is processed and you consider all the User and Movie features in generating the node features of the graph. In particular, you assign id of the node with this scheme: 

from [  0 : Length(Users)  ]  ->  Features of User (encoded) 
from [ Length(Users) : Length(Users)  + Length(Movies) ] -> Features of Movies (encoded) 

The problem comes out when you consider the Title of the movies because in the code there is the following (line 158): 

        for i, tw in enumerate(tqdm.tqdm(title_words)):
            g.ndata['title'][i, [vocab_invmap[w] for w in tw]] = 1

which would mean that the encoded title would be assigned to the nodes related to the Users
[0 : Len(Movies)]
Maybe i didn't understand the logic behind this, is this correct ? or am i missing something? 

Thank you,
Best regards
Francesco

**Comment by BarclayII** [comment]
You're absolutely right.
