### ISSUE TITLE
[Feature] Allowing access of node & edge type in UDFs

### ISSUE THREAD

**Issue by QipengGuo** [dmlc/dgl#1185]
## 🚀 Feature

Improving the user experience of dgl.to_hetero and UDF functions on hetero graphs.
Relax the constraint of using integer tensors for to_hetero() and allow the user to access meta-info in UDF on hetero graphs.
## Motivation

The dgl.to_hetero asks the NTYPE and the ETYPE fields to be contiguous span starting from the zero if using integer tensor as type ids, and this is not a rational requirement for users. 

For example,
```=python
NTYPES = {'none':0, 'relation_1':1}
g = dgl.DGLGraph()
g.add_nodes(10, {dgl.NTYPE: torch.zeros(10).long()+NTYPES['relation_1']})
g.add_edges([1,2,3],[2,3,1], {dgl.ETYPE: torch.zeros(3).long()})
g.add_edges([1,2,3],[1,3,1], {dgl.ETYPE: torch.zeros(3).long()})
hg = dgl.to_hetero(g, ['n1'], ['a', 'b'])
```
it will raise an error since the index of NTYPE is not starting from zero. 

And anther desired feature is accessing the information of canonical_etypes in NodeBatch and EdgeBatch, it would be helpful for UDF on hetero graphs.

**Comment by BarclayII** [comment]
For the `to_hetero()` example, the last line should be instead

```python
hg = dgl.to_hetero(g, NTYPES.keys(), ['a', 'b'])
```

I believe the second proposal (i.e. adding type as an attribute to NodeBatch and EdgeBatch) should be useful.
