### ISSUE TITLE
[Feature] Add environment variable to switch on/off MXNet set_np_shape

### ISSUE THREAD

**Issue by hetong007** [dmlc/dgl#1186]
In https://github.com/dmlc/dgl/blob/d30a69bf277effd9a013ddd81fa33661f2e31a01/python/dgl/backend/mxnet/tensor.py#L20, we have `mx.set_np_shape(True)`. Since at this moment MXNet and its community packages (GluonCV/GluonNLP etc) are not fully compatible with MXNet's np shape feature, users need to be able to turn it on/off, for example through an environmental variable.

**Comment by jermainewang** [comment]
@hetong007 go ahead push a PR for this. The solution using environment variable looks fine to me.
