### ISSUE TITLE
[Installation] 'ios' file not found

### ISSUE THREAD

**Issue by mufeili** [dmlc/dgl#1197]
## 🐛 Bug

When installing from source on Mac OS Catalina 10.15.1 with `pip install -e .`, an error occurs as below:

```
dgl/_ffi/_cython/core.cpp:632:10: fatal error: 'ios' file not found
#include "ios"
```

I manage to solve this error with `CFLAGS='-stdlib=libc++' pip install -e .`, but I'm not sure how general this case is and if it should be better handled.

**Comment by yzh119** [comment]
I have met this problem before.
Please try the solution described [here](https://stackoverflow.com/questions/52509602/cant-compile-c-program-on-a-mac-after-upgrade-to-mojave).
