### ISSUE TITLE
[Tutorial] Use one-hot encoding instead of eye in "DGL at a glance"

### ISSUE THREAD

**Issue by zheng-da** [dmlc/dgl#1202]
## 📚 Documentation
It's very memory consuming to generate one-hot encoding with eye(). We should replace it with an embedding layer.

**Comment by jermainewang** [comment]
Another solution is to have a pointer about how to train on large graphs. The very first tutorial is not meant to cover all the scenarios.

**Comment by zheng-da** [comment]
What I notice is that users read one of the example code and start to try out on their datasets. Another solution is to explicitly warn users that this implementation isn't scalable and refer users to a more scalable solution if they want to scale to large datasets.

**Comment by jermainewang** [comment]
Done in #1380
