### ISSUE TITLE
PinSage sampling with Nodeflow

### ISSUE THREAD

**Issue by fiorinin** [dmlc/dgl#1206]
## 🚀 Feature
Nodeflow support for PinSage.

## Motivation
I'm trying to scale up PinSage a bit (2.8M nodes), in order to assess its performances on another dataset. Currently, Nodeflow isn't integrated in the example and I'm struggling to adapt this part of the code — I'm still learning DGL.

## Alternatives
I understand this should be released with 0.5. Could you please give me an outline of the steps to be taken in order to implement a Nodeflow equivalent of the current random walk?

## Pitch
I'd like to see a prototype of a Nodeflow integration for this bit, or get some help in implementing it myself.

Thanks a lot!

**Comment by BarclayII** [comment]
Unfortunately, I was struggling with integrating NodeFlow with PinSAGE as well.  That's why we had the initiative of implementing the new sampler spec #1199 in the first place.

Once the new sampling spec is implemented, we will gradually deprecate NodeFlow in favor of the new one.

**Comment by fiorinin** [comment]
"Glad" to see I'm not the only one then! :) 
Thanks so much for the summary, it's definitely helpful since finding information on overall progress is otherwise complicated.

**Comment by jermainewang** [comment]
Close this and let's move the discussion to the open PR.
