### ISSUE TITLE
code and doc are not consistent for expand_factor in NeighborSampler

### ISSUE THREAD

**Issue by zhao-tong** [dmlc/dgl#1223]
In the documentation, it says:
> expand_factor (int, float, str) – The number of neighbors sampled from the neighbor list of a vertex. The value of this parameter can be:
> int: indicates the number of neighbors sampled from a neighbor list.
> float: indicates the ratio of the sampled neighbors in a neighbor list.
> str: indicates some common ways of calculating the number of sampled neighbors, e.g., sqrt(deg).

However, in the source code for expand_factor, there is a integer check: 
`assert isinstance(expand_factor, Integral), 'non-int expand_factor not supported'`
It is possible to add the support of taking float expand_factors (like the doc described)?

**Comment by zheng-da** [comment]
Thanks for pointing it out. The doc is fixed in this PR: https://github.com/dmlc/dgl/pull/1236
