### ISSUE TITLE
Hello, is there a tutorial written using MXnet in "https://docs.dgl.ai/"? 

### ISSUE THREAD

**Issue by AwesoneJ** [dmlc/dgl#1231]
## ❓ Questions and Help

Before proceeding, please note that we recommend
using our discussion forum (https://discuss.dgl.ai) for
general questions. As a result, this issue will
likely be CLOSED shortly.

**Comment by zheng-da** [comment]
https://doc.dgl.ai/tutorials/models/1_gnn/8_sse_mx.html

**Comment by zheng-da** [comment]
https://doc.dgl.ai/tutorials/models/5_giant_graph/1_sampling_mx.html

**Comment by zheng-da** [comment]
https://doc.dgl.ai/tutorials/models/5_giant_graph/2_giant.html
