### ISSUE TITLE
Cluster GCN: example to verify metis installation is outdated

### ISSUE THREAD

**Issue by 1byxero** [dmlc/dgl#1234]
## 📚 Documentation

This is part of tutorial

Following part of code  to verify metis installation is outdated
```
import networkx as nx
import metis
G = metis.example_networkx()
(edgecuts, parts) = metis.part_graph(G, 3)
```
Mostly, due to updates to networkx library.

**Comment by yzh119** [comment]
Bug confirmed, I think it's because python-metis is not compatible with latest networkx api, could we create a bug report to the author of python-metis?

**Comment by 1byxero** [comment]
I Created an issue there.
Link to issue: https://github.com/networkx/networkx-metis/issues/70

**Comment by klicperajo** [comment]
Note that if you do `pip install metis` you don't get networkx-metis but [this older library](https://pypi.org/project/metis/).

**Comment by classicsong** [comment]
@1byxero DGL now has included metis partition support maintained by Karypis George. 

How to use:
```
part_dict = dgl.transform.metis_partition(g, num_parts, 1)
```

We will add docstrings for it soon.
