### ISSUE TITLE
dataset making

### ISSUE THREAD

**Issue by luyifanlu** [dmlc/dgl#1235]
if i have a lot of  graph,like 
```python
train=[]
label=[]
for i in range(10):
     g = dgl.DGLGraph()
     g.add_nodes(5)                          # add 5 nodes
     g.add_edges([0, 0, 0, 0], [1, 2, 3, 4]) # add 4 edges 0->1, 0->2, 0->3, 0->4
     g.ndata['h'] = th.randn(5, 3)           # assign one 3D vector to each node
     g.edata['h'] = th.randn(4, 4)           # assign one 4D vector to each edge
     train.append(g)
     label.append(i)
     
```
how to make a dataset pipline

**Comment by luyifanlu** [comment]
I tried 
`
demo=torch.utils.data.TensorDataset(th.tensor(ret)，th.tensor(label))
`
but got a error:SyntaxError: invalid character in identifier
``

**Comment by VoVAllen** [comment]
Hi, 

Are you trying to do graph classification? Have you seen our [tutorial](https://docs.dgl.ai/tutorials/basics/4_batch.html) on this?

**Comment by luyifanlu** [comment]
> Hi,
> 
> Are you trying to do graph classification? Have you seen our [tutorial](https://docs.dgl.ai/tutorials/basics/4_batch.html) on this?

i had do it.but there same thing i got confuse.Classifier out  with shape (batch_size,n_classes),but label with shape (batch_size),why it can be work

**Comment by mufeili** [comment]
In the tutorial, we assume the each graph has one label only and there are `n_classes` possible labels. The model is trained to predict the probability for a graph to have each label.
