### ISSUE TITLE
HAN example error on version 0.4.2

### ISSUE THREAD

**Issue by gtcslance** [dmlc/dgl#1237]
get the below error running HAN example on version 0.4.2,  version 0.4.1 works though

AttributeError: '<class 'dgl.heterograph_index.HeteroGraphIndex'>' object has no attribute 'get_immutable_gidx'

**Comment by VoVAllen** [comment]
@mufeili

**Comment by mufeili** [comment]
@BarclayII @yzh119 It seems that the use of [`get_immutable_gidx`](https://github.com/dmlc/dgl/blob/master/python/dgl/nn/pytorch/softmax.py#L52) in `edge_softmax` as of PR #1139 breaks the use of `edge_softmax` for `DGLHeteroGraph`. What's the recommended way to fix it?

**Comment by BarclayII** [comment]
PR #1139 was a temporary fix and we really should look further into it to see what was actually happening with message passing APIs (but we never had time to do it).

Made another PR to patch up the heterograph example.
