### ISSUE TITLE
G.to(torch.device('cuda:0')) return nothing

### ISSUE THREAD

**Issue by LeeHuan18** [dmlc/dgl#1241]
Hi,
    This may be a trivial question, but I don't know how to solve it.
    I create some graphs with cuda, however after I store them and load them, they are type gpu. So I think there should be a to convert graph from cpu to gpu, and I find that in the web:

> G = dgl.DGLGraph()
> G.add_nodes(5, {'h': torch.ones((5, 2))})
> G.add_edges([0, 1], [1, 2], {'m' : torch.ones((2, 2))})
> G.add_edges([0, 1], [1, 2], {'m' : torch.ones((2, 2))})
> G = G.to(torch.device('cuda:0'))
> 

However this code doesn't work for me, after the last sentence, G is nothing. Anything wrong here?

Thank you!

**Comment by VoVAllen** [comment]
Could you install the latest version? The behavior is fixed in the latest one. Previously `G.to(torch.device('cuda:0'))` would change `G` inplacely. After calling `G.to(torch.device('cuda:0'))`, G would on cuda:0, it would return nothing therefore G becomes None.
