### ISSUE TITLE
Floating point exception in GATConv 

### ISSUE THREAD

**Issue by wadmes** [dmlc/dgl#1245]
## To Reproduce

1. Generate a graph without edges (G.number_of_edges == 0)
2. Feed the graph into GATconv

## Expected behavior
`Floating point exception (core dumped)`

When I use a dirty code (when `new_g.number_of_edges() == 0)`, simply generate a zero vector instead of call `GATconv`)
Then error is fixed.

## Environment
 - Backend Library : Pytorch
 - OS ( Linux):
 - Python version: 3.6
 - CUDA/cuDNN version (if applicable): 10.2
 - GPU models and configuration (e.g. V100): TITAN Xp

**Comment by yzh119** [comment]
Hi, could you please provide the code snippet to reproduce the error? I've not met the error when applying GATConv on a DGLGraph without edges.

**Comment by jermainewang** [comment]
Closed due to inactivity.
