### ISSUE TITLE
RGCN entity classification

### ISSUE THREAD

**Issue by KotaroImura** [dmlc/dgl#1247]
In the RGCN entity classification,
I'm trying to run "python entity_classify.py -d aifb --testing --gpu 0"

here's the error I'm getting:
"""
Traceback (most recent call last):
  File "entity_classify.py", line 171, in <module>
    main(args)
  File "entity_classify.py", line 110, in main
    logits = model(g, feats, edge_type, edge_norm)
                                         ・・・
  File "<・・・>\dgl\nn\pytorch\utils.py", line 90, in bmm_maybe_select
    BB = B.index_select(0, index)
RuntimeError: Expected object of scalar type Long but got scalar type Int for argument #3 'index' in call to _th_index_select
"""
Why is that?

**Comment by classicsong** [comment]
Can you give more details about:
Which DGL version you use? Which pytorch version you use? And which system you use? (Linux, windows or mac)

**Comment by KotaroImura** [comment]
I Just started today.(dgl pytorch)

DGL version 　  : dgl-cuda10.0  0.4.2
pytorch version : 1.4.0
system               : windows 10

I made it by looking at the DGL document(Install DGL).

**Comment by KotaroImura** [comment]
-> logits = model(g, feats, edge_type, edge_norm)
(Pdb) edge_type
tensor([ 0, 10,  4,  ..., 41, 41,  0], device='cuda:0', dtype=torch.int32)
(Pdb) edge_type.long()
tensor([ 0, 10,  4,  ..., 41, 41,  0], device='cuda:0')

I am using "Previous versions of PyTorch".
cuda : 10.0
pytorch : v1.2.0

**Comment by VoVAllen** [comment]
Seems you need to manually change ` logits = model(g, feats, edge_type, edge_norm)` to ` logits = model(g, feats, edge_type.long(), edge_norm)`
The difference may differ from Pytorch's version.

**Comment by KotaroImura** [comment]
I could do it if I changed "edge_type.long()" & "labels[train or val or test idx].long".

Thank you very much.

**Comment by VoVAllen** [comment]
Thanks for your report. Due to the PyTorch version changes, it's hard for us to track such bugs. We will stay concerned about this kind of issues.
