### ISSUE TITLE
Deconvolution

### ISSUE THREAD

**Issue by KotaroImura** [dmlc/dgl#1250]
I want to do pool and unpool like "Unet" with R-GCN.
Can I make "unpool" on DGL?

**Comment by yzh119** [comment]
Hi, I think you can try using [bipartite graph](https://docs.dgl.ai/generated/dgl.bipartite.html?highlight=bipartite#dgl.bipartite) to describe the semantics of message passing between layers in pooling/unpooling. For more information about how the bipartite graph works, please refer to our [heterograph tutorial](https://docs.dgl.ai/api/python/heterograph.html).

```python
g_arr = []
cross_layer_edge_list = []
bipartite = []
for i in range(n):
    g_arr.append(dgl.DGLGraph(...)) # the graph at level i
    cross_layer_edge_list.append(...)
    bipartite.append(dgl.bipartite(edge_list, 'u', 'e', 'v')
```

The generic procedure of pooling layers could be described as:
```python
for i in range(n):
    g_arr[i].update_all(...)
    bipartite[i].nodes['u'].data['h'] = g_arr[i].ndata['h']
    bipartite[i]['e'].update_all(...)
    g_arr[i+1].ndata['h'] = bipartite[i].nodes['v'].data['h']
```

Please let me know if you have more questions, if necessary I can help implement a prototype of the model.

**Comment by KotaroImura** [comment]
Thank you
I'm going to try "bipartite graph".

But now, I'm making "Global max pooling and unpool" and watching data.
I will try to seek the right way.

**Comment by chushan89** [comment]
Hi,
I am also trying to do with a 'Deconvolution' or 'unpool' on graph. Did you find a good way for that? 
Does the bipartite graph work for you?
