### ISSUE TITLE
Improvement of backend choices of DGL

### ISSUE THREAD

**Issue by VoVAllen** [dmlc/dgl#1258]
## 🚀 Feature
Since we are introducing Tensorflow support, it's not ideal still using PyTorch as backend. Also tf's setup procedure is a bit complex, thus we'd like to introduce more convenient one-click setup.

## Pitch
Create a configuration file in `~/.dgl/config` to store the preferred the backend name, since most people won't change from one framework to another frequently.

Related issue: https://github.com/dmlc/dgl/pull/1191#issuecomment-585129846

Feel free to leave your thoughts.

**Comment by jermainewang** [comment]
1. How about windows?
2. What if user hasn't created the configuration file? Raise an error or populate a default value?

**Comment by VoVAllen** [comment]
I think there's also a similar directory where we put the dataset now.
I would prefer an API like `dgl.set_default_backend('pytorch')` and this would create the configuration file. For situation without default value, we can raise error. (I'm not sure whether there's better way or which should be the default value?)

**Comment by jermainewang** [comment]
> For situation without default value, we can raise error. (I'm not sure whether there's better way or which should be the default value?)

We could provide an interactive script for user to set the proper backend value. It will be launched if no configure file exists and also inform users for how to set configurations by themselves. As for the config file, do you have any format preference?
