### ISSUE TITLE
multi_update_all with 'stack' reducer

### ISSUE THREAD

**Issue by gurdaspuriya** [dmlc/dgl#1264]
## 🚀 Feature
1) Stack order is inconsistent, better to have it consistent.
2) The shape of the output is not consistent, when there is only one message-type (single frame), the same frame is returned; while for multiple message-types, an additional dimension is introduced.

**Comment by BarclayII** [comment]
@gurdaspuriya We have submitted a patch.

One quick question: after you stack-reduce the per-type (reduced) messages, how would you like to use it (e.g. pass the whole thing through an MLP, or access each per-type reduced message individually)?

**Comment by gurdaspuriya** [comment]
@BarclayII Thanks for taking care.
For my current use case, I would pass the whole thing through a MLP.

**Comment by jermainewang** [comment]
@gurdaspuriya The patch has been merged. Please checkout the lastest master. Let us know if there are more issues.
