### ISSUE TITLE
[Feature Request] NN Module Graph Matching Network Model

### ISSUE THREAD

**Issue by Youarerare** [dmlc/dgl#1271]
## 🚀 Feature

I want to input a pair of graphs and calculate the similarity of the two graphs based on node embedding and edge embedding. I think graph matching will become more and more useful in the future。But I don't have the ability to achieve it. The implement detail is in https://arxiv.org/pdf/1904.12787.pdf

## Pitch

input: a pair of graph
output: the similarity  score between them

**Comment by yzh119** [comment]
Thanks for your suggestion, yes we do think graph matching module is important, I'll take the responsibility to implement this model, please stay tuned.

**Comment by amorehead** [comment]
I am also interested in achieving something like this, with a siamese GNN architecture. I currently have implemented a baseline model trainer with PyTorch Lightning, but I can only use a batch size of one for the time being since I need to ensure that pairs of graphs are retrieved simultaneously for each forward pass of the network. Any ideas on how I could batch pairs of graphs without having to resort to using a batch size of one?

**Comment by BarclayII** [comment]
> I am also interested in achieving something like this, with a siamese GNN architecture. I currently have implemented a baseline model trainer with PyTorch Lightning, but I can only use a batch size of one for the time being since I need to ensure that pairs of graphs are retrieved simultaneously for each forward pass of the network. Any ideas on how I could batch pairs of graphs without having to resort to using a batch size of one?

In DGL 0.6 we have a `GraphDataLoader` that works similarly as `torch.utils.data.DataLoader`.  For instance, you can prepare a dataset of graph pairs and then load them into a pair of batched graphs:

```python
# Set of graph pairs
g = [(
    dgl.graph((torch.randint(0, 10, (20,)), torch.randint(0, 10, (20,)))),
    dgl.graph((torch.randint(0, 10, (20,)), torch.randint(0, 10, (20,))))) for _ in range(200)]
# Dataloader
dl = dgl.dataloading.GraphDataLoader(g, batch_size=10)
# Load
next(iter(dl))
#  [Graph(num_nodes=100, num_edges=200,
#         ndata_schemes={}
#         edata_schemes={}),
#   Graph(num_nodes=100, num_edges=200,
#         ndata_schemes={}
#         edata_schemes={})]
```

**Comment by amorehead** [comment]
Thank you for pointing this out, @BarclayII!
