### ISSUE TITLE
Knowledge graph embedding

### ISSUE THREAD

**Issue by chengjiali** [dmlc/dgl#1272]
## To Reproduce

1. go to dgl/apps/kg
1. run the gpu-only test
1.

Traceback (most recent call last):
  File "train.py", line 395, in <module>
    run(args, logger)
  File "train.py", line 350, in run
    train(args, model, train_sampler, valid_samplers, rel_parts=rel_parts)
  File "/scratch/cheng.jial/knowledge_graph_pubmed/src/embedding/dgl/apps/kg/train_pytorch.py", line 61, in train
    loss, log = model.forward(pos_g, neg_g, gpu_id)
  File "/scratch/cheng.jial/knowledge_graph_pubmed/src/embedding/dgl/apps/kg/models/general_models.py", line 357, in forward
    neg_deg_sample=self.args.neg_deg_sample)
  File "/scratch/cheng.jial/knowledge_graph_pubmed/src/embedding/dgl/apps/kg/models/general_models.py", line 266, in predict_neg_score
    neg_tail = neg_tail.reshape((num_chunks * neg_sample_size, -1))
RuntimeError: shape '[1024, -1]' is invalid for input of size 2044000

## Environment

 - DGL Version (e.g., 1.0): DGL 
 - Backend Library & Version (e.g., PyTorch 0.4.1, MXNet/Gluon 1.3): PyTorch 1.13.0
 - OS (e.g., Linux): CentOS
 - How you installed DGL (`conda`, `pip`, source): conda
 - Build command you used (if compiling from source):
 - Python version: 3.7
 - CUDA/cuDNN version (if applicable): 9.2
 - GPU models and configuration (e.g. V100): V100
 - Any other relevant information:

**Comment by classicsong** [comment]
Can you list all the arguments you use? Also your graph size.

**Comment by zheng-da** [comment]
Could you show us what your configurations are when running the training script?

**Comment by chengjiali** [comment]
Hi,

Thanks for the quick response!

Here is what I did:
1. installed DGL with conda
1. go to dgl/apps/kg
1. start training with the first recommended arguments, input format 1, which is shown below

python3 train.py --model DistMult --dataset my_dataset --data_path path --batch_size 1024 \
    --neg_sample_size 256 --hidden_dim 2000 --gamma 500.0 --lr 0.1 --max_step 100000 \
    --batch_size_eval 16 --gpu 0 --valid --test -adv

I used my own dataset not FB15k. I'm sure I followed the format.

I will try installing with pip.

Thank you!

**Comment by classicsong** [comment]
> Hi,
> 
> Thanks for the quick response!
> 
> Here is what I did:
> 
> 1. installed DGL with conda
> 2. go to dgl/apps/kg
> 3. start training with the first recommended arguments, input format 1, which is shown below
> 
> python3 train.py --model DistMult --dataset my_dataset --data_path path --batch_size 1024
> --neg_sample_size 256 --hidden_dim 2000 --gamma 500.0 --lr 0.1 --max_step 100000
> --batch_size_eval 16 --gpu 0 --valid --test -adv
> 
> I used my own dataset not FB15k. I'm sure I followed the format.
> 
> I will try installing with pip.
> 
> Thank you!

I suggest you to pip install the nightly built version.

**Comment by chengjiali** [comment]
nightly built solved the problem. Thanks a lot!
