### ISSUE TITLE
requests_failed_to_import occurs when downloading a dataset with tu.LegacyTUDataset

### ISSUE THREAD

**Issue by yttty** [dmlc/dgl#1273]
## 🐛 Bug

```requests_failed_to_import``` occurs when downloading a dataset with ```tu.LegacyTUDataset``` if ```requests``` was not installed.

## To Reproduce

```
from dgl.data import tu
dataset = tu.LegacyTUDataset(name="DD")
```

## Expected behavior

DGL should check whether ```requests``` is installed before downloading.

## Environment

 - DGL Version (e.g., 1.0): 0.4
 - How you installed DGL (`conda`, `pip`, source): pip
 - Python version: 3.7

## Additional context

Simple to solve this issue. Just check if ```requests`` is installed before downloading.

**Comment by mufeili** [comment]
Thanks for the suggestion! Previously `requests` was an additional dependency and it is now made a required dependency in #1268 .
