### ISSUE TITLE
[Feature] Filtered MRR function in dgl/examples/pytorch/rgcn/utils.py

### ISSUE THREAD

**Issue by hgalioulline** [dmlc/dgl#1275]
## 🚀 Feature

Filtered MRR metric in link prediction using R-GCN.

## Motivation

Since R-GCN is used as a baseline model for many link prediction experiments, and since the vast majority of metrics reported are filtered, it would be useful to have filtered metrics implemented for the R-GCN link prediction example.

## Pitch

A filtered MRR function in dgl/examples/pytorch/rgcn/utils.py

**Comment by classicsong** [comment]
@hgalioulline can you help contribute 'filtered MRR' into the R-GCN link prediction example?

**Comment by classicsong** [comment]
The PR has been merged.
@hgalioulline
