### ISSUE TITLE
GATConv code questions

### ISSUE THREAD

**Issue by quan-jiayi** [dmlc/dgl#1279]
## ❓ Questions and Help

Hello,will you give me a help?
about the GATConv source code in [GATConv](https://docs.dgl.ai/_modules/dgl/nn/pytorch/conv/gatconv.html#GATConv)
```python
        feat = self.fc(h).view(-1, self._num_heads, self._out_feats)
        el = (feat * self.attn_l).sum(dim=-1).unsqueeze(-1)
        er = (feat * self.attn_r).sum(dim=-1).unsqueeze(-1)
        graph.ndata.update({'ft': feat, 'el': el, 'er': er})
        # compute edge attention
        graph.apply_edges(fn.u_add_v('el', 'er', 'e'))
        e = self.leaky_relu(graph.edata.pop('e'))
        # compute softmax
        graph.edata['a'] = self.attn_drop(edge_softmax(graph, e))
        # message passing
        graph.update_all(fn.u_mul_e('ft', 'a', 'm'),
                         fn.sum('m', 'ft'))
```
here:
(1) what is the meaning of el and er ?
(2) what is the meaning of fn.u_add_v,fn.u_mul_e ,I have found them in https://docs.dgl.ai/api/python/function.html ,however the introductions are so brief and there is no any examples。
(3) why there is no concatenate operation is the source code，I think this code is very different from the paper。

thank you!

**Comment by yzh119** [comment]
Hi, @quan-jiayi .
`u_add_v('el', 'er', 'e')` means each edge computes the addition of the `el` feature of source node and the `er` feature of the destination node.

In effect it's the same as:
```
def u_add_v(src_field, dst_field, msg_field):
    def message_func(edges):
        return {msg_field: edges.src[src_field] + edges.dst[dst_field]}
    return message_func
```

`u_mul_e('ft', 'a', 'm')` means each edge computes the multiplication of the `ft` feature of source node and `a` feature on the edge.
In effect it's the same as:
```
def u_add_v(src_field, dst_field, msg_field):
    def message_func(edges):
        return {msg_field: edges.src[src_field] + edges.dst[dst_field]}
    return message_func
```


Our implementation is the same as the paper. We decompose the "first concatenation then linear projection" to "first linear projection then addition", you can find my explanation here #963. `el` and `er` means the feature after linear projection on the left/right side of the formula respectively.

**Comment by quan-jiayi** [comment]
Hi, thank you very much,now I have solved these question,where el and er is a very nice tricks.Thank you!
