### ISSUE TITLE
A potential bug in DGL pooling layer

### ISSUE THREAD

**Issue by zheng-da** [dmlc/dgl#1280]
## 🐛 Bug
In all of DGL's nn pooling layer, it overwrites the node data 'h' of the given graph with the input features. What if the graph already has node data 'h'? The original node data 'h' will be overwritten. Some information will be lost. One example is [here](https://github.com/dmlc/dgl/blob/master/python/dgl/nn/pytorch/glob.py#L46-L48).

**Comment by yzh119** [comment]
@zheng-da we overwrite `h` under `graph.local_scope` so to avoid the problem you mentioned.
