### ISSUE TITLE
GCN nn module should support weighted graphs.

### ISSUE THREAD

**Issue by zheng-da** [dmlc/dgl#1281]
## 🚀 Feature
In some cases, the edges in the graph have weights. When running GCN on the graph, we want to have weighted sparse matrix instead of the binary adjacency matrix.

## Motivation

This is useful for some cases. For example, the graph is a KNN similarity graph. We definitely want to take the similarity score into consideration in the model. Another use case is to hide the edges when running GCN for link prediction. @bioannidis

**Comment by jermainewang** [comment]
How to calculate the c_i and c_j normalizer for weighted adj matrix?

**Comment by classicsong** [comment]
Why not store the weight as edge value?

**Comment by jermainewang** [comment]
> Why not store the weight as edge value?

I think Da is asking why the `nn.GraphConv` module does not support weighted graph by default. My concern is what is the right formulation then?

**Comment by zheng-da** [comment]
I don't mean supporting weighted graph by default. I think there is such an option that messages are rescaled by the edge weights.

**Comment by Zhiyu-Chen** [comment]
yes. I am also about to asking for non-binary adjacency matrix...

**Comment by kyawlin** [comment]
How to calculate the c_i and c_j normalizer for weighted adj matrix?

**Comment by gfei713** [comment]
Is there any schedule for support of this feature ?In our project we also want this feature ,it is very important for weighted convolutional ( weighted adj matrix considered) in GraphConv.
