### ISSUE TITLE
Link prediction with rgcn-hetero

### ISSUE THREAD

**Issue by bioannidis** [dmlc/dgl#1282]
Hi,
Could you please provide a link_predict.py version 
with the corresponding utils.py 
for the rgcn-hetero package? 

Specifically, I would like to use a link prediction
objective using directly a DGLHeteroGraph. 

Is there any way to obtain sample a subset of
edges positive and negative samples directly
from a DGLHeteroGraph?

Thank you,
Vassilis Ioannidis
Applied Scientist, Amazon.

**Comment by bioannidis** [comment]
A related feature, is the implemented of the API 
dgl.contrib.sampling.sampler.EdgeSampler
for Heterographs, towards link prediction.

Thank you

**Comment by je-dbl** [comment]
Hi,
Thanks for this question, I'm working on something similar.
@bioannidis did you find anything that suits your needs? I would also be interested in obtaining a samples of
positive and negative edges directly from a DGLHeteroGraph.
Thanks again!

**Comment by frozenbugs** [comment]
Duplicated with https://github.com/dmlc/dgl/issues/6241
