### ISSUE TITLE
[Bug] NodeFlow.block_compute came up with error "NodeFlowobject has no attribute num_edges"

### ISSUE THREAD

**Issue by zengxy** [dmlc/dgl#1288]
version v0.4.1

I found that it has been asked in https://discuss.dgl.ai/t/nodeflow-questions/593.

It only appears when using  build in send / reduce functions, you can reproduce by the following snippet
```python
import dgl
import numpy as np
g = dgl.DGLGraph()
g.add_nodes(5)
g.add_edges([1,2], [2,3])
g.ndata["f"] = np.zeros([5,6])
g.readonly()
nfs = dgl.contrib.sampling.NeighborSampler(g, 10, 5)
for nf in nfs:
    break
nf.copy_from_parent()
nf.apply_block(0, lambda edges: {"m": edges.src["f"]})   # running successful
nf.apply_block(0, dgl.function.copy_src("f", "m"))   # throw exception
```
The root cause is as following:

The exception is raised from `scheduler._gen_send`, in which the  old  `DGLBaseGraph.number_of_edges` invoking is changed to `AdaptedDGLGraph.num_edges` in a certain commit. But while all the passed in graphs is wrapped  in DGLGraph, nodeflow dosen't do it.

**Comment by jermainewang** [comment]
Confirmed this is a bug. I actually found this bug and patched it when I was developing an example for multi-GPU training (#1143 ). Since that PR would take more time to merge, I have pushed a patch in a standalone PR.

**Comment by zengxy** [comment]
Thank you! The pacth is very useful for me.

**Comment by jermainewang** [comment]
Done in PR1289.
