### ISSUE TITLE
AttributeError: module 'dgl' has no attribute 'sampling'

### ISSUE THREAD

**Issue by maelstrom9** [dmlc/dgl#1294]
## ❓ Questions and Help

Before proceeding, please note that we recommend
using our discussion forum (https://discuss.dgl.ai) for
general questions. As a result, this issue will
likely be CLOSED shortly.

**Comment by maelstrom9** [comment]
Using python 3.6.9 in macos. 
Installed dgl using conda.
Running sampler.py from dgl/examples/metapthresulting into this issue.

**Comment by linbang** [comment]
i meet same question, how to solve it？

**Comment by VoVAllen** [comment]
@linbang Update to the nightly build of dgl by `pip install --pre dgl/dgl-cu90/dgl-cu92/dgl-cu100`
