### ISSUE TITLE
how to aggregate edata to ndata

### ISSUE THREAD

**Issue by srtianxia** [dmlc/dgl#1311]
## ❓ Questions and Help

I want to know how to aggregate edata to ndata,  such as this code,  each edge has a value , i want to aggregate these values to node data. this result should be  **node0 : 0.5 , node1 : 0.3, node2 : 0.9, node3 : 0.5, node 4 : 0.2.** I tried two ways but neither worked
```python
import dgl
import torch
import numpy as np
import dgl.function as fn

if __name__ == '__main__':
    edge_list = [(0, 1), (1, 3), (3, 2), (2, 0), (2, 4)]
    g = dgl.DGLGraph(edge_list)
    g.edata['w'] = torch.from_numpy(np.array([0.1, 0.2, 0.3, 0.4, 0.2]))
    print(g.edata['w'])
    # g.update_all(lambda edge: {'m': edge.data['w']}, fn.sum('m', 'h_f'))  # my method 1

    # g.update_all(fn.copy_e('w', 'm'), fn.sum('m', 'h_f'))   # my method 2

```

**Comment by VoVAllen** [comment]
You could add edges for both side.
```pyrhon
reverse_edge_list = [(item[1], item[0]) for item in edge_list]
g.add_edges(edge_list)
g.add_edges(reverse_edge_list )
```

**Comment by srtianxia** [comment]
@VoVAllen  thanks for you reply but my method 1  and method 2  will give an error ... I don't know how to  do, thanks!

**Comment by VoVAllen** [comment]
Hi,

You need to change to 
```python
    g.edata['w'] = torch.from_numpy(np.array([0.1, 0.2, 0.3, 0.4, 0.2])).float()
```

The reason is that dgl's kernel only supports float instead of double. Or you can use custom user defined function
```python
g.update_all(fn.copy_e('w', 'm'), lambda nodes: {'h_f': th.sum(nodes.mailbox['m'], dim=1)}
```

**Comment by srtianxia** [comment]
> Hi,
> 
> You need to change to
> 
> ```python
>     g.edata['w'] = torch.from_numpy(np.array([0.1, 0.2, 0.3, 0.4, 0.2])).float()
> ```
> 
> The reason is that dgl's kernel only supports float instead of double. Or you can use custom user defined function
> 
> ```python
> g.update_all(fn.copy_e('w', 'm'), lambda nodes: {'h_f': th.sum(nodes.mailbox['m'], dim=1)})
> ```

Thanks a lot !
