### ISSUE TITLE
Segmentation fault (core dumped) when use tf as backend

### ISSUE THREAD

**Issue by yuaneryuaner** [dmlc/dgl#1315]
## To Reproduce

python3 train.py --dataset=cora --gpu=0 in 
dgl/examples/tensorflow/gat

## Environment

 - DGL Version (e.g., 0.4):
 - Backend Library & Version tf2.0:
 - OS (e.g., ubuntu 16.04):
 - How you installed DGL (source):
 - Build command you used (if compiling from source): 
mkdir build
cd build
cmake -DUSE_CUDA=ON ..
make -j4
 - Python version:3.6.9
 - CUDA/cuDNN version (if applicable):cuda10 cudnn7.4.1
 - GPU models and configuration (e.g. V100):1080ti
 - Any other relevant information:

**Comment by VoVAllen** [comment]
Are you using macos or linux?

**Comment by yuaneryuaner** [comment]
> Are you using macos or linux?

linux
