### ISSUE TITLE
supporting graph level feature on `dgl.DGLGraph`

### ISSUE THREAD

**Issue by Junyoungpark** [dmlc/dgl#1316]
## 🚀 Feature
supporting graph level feature of `dgl.DGLGraph`

## Motivation

For some case of graph neural network, they might be incorporate with the global feature.
Those global features are usually a tensor for each graph. **Relational inductive biases, deep learning, and graph networks** written by DeepMind (https://arxiv.org/abs/1806.01261) is the exact case where the global features are used inside of GNN computations.

pseudo code of an expected usecase
```
g = dgl.DGLGraph()
g.gdata['field_name'] = some tensor

batched_g = dgl.batch([g, g])
g_features = batched_g.gdata['field_name'] # a stack of global feature tensors
```

fyi, `pytorch_geometric`  supports this feature

**Comment by yzh119** [comment]
The topic has been discussed for several times #417 , #714 , #737 .
I think graph level data is useful in the context of batched graphs. @Junyoungpark could you please read our discussions in #737 and reopen the issue if you want to elaborate more ?

**Comment by Junyoungpark** [comment]
As discussed in https://github.com/dmlc/dgl/issues/737, the graph level feature and its related computations on message passing could be implemented easily. I agree and already do the similar job. Thanks @yzh119
