### ISSUE TITLE
[BUG] dgl.heterograph() not supporting node types with no inbound/outbound edges

### ISSUE THREAD

**Issue by BarclayII** [dmlc/dgl#1320]
## 🐛 Bug

See below:

## To Reproduce

```
In [2]: g = dgl.heterograph({('A', 'AB', 'B'): [(0, 1), (1, 2)]}, num_nodes_dict={'A': 3, 'B': 3, 'C': 3})

In [3]: g
Out[3]: 
Graph(num_nodes={'A': 3, 'B': 3},
      num_edges={('A', 'AB', 'B'): 2},
      metagraph=[('A', 'B')])
```

The node type `C` is missing.

## Expected behavior

Node type `C` should be there even if no edges connect to/from C.

## Environment

 - DGL Version (e.g., 1.0): master
 - Backend Library & Version (e.g., PyTorch 0.4.1, MXNet/Gluon 1.3):
 - OS (e.g., Linux):
 - How you installed DGL (`conda`, `pip`, source):
 - Build command you used (if compiling from source):
 - Python version:
 - CUDA/cuDNN version (if applicable):
 - GPU models and configuration (e.g. V100):
 - Any other relevant information:

## Additional context

A similar issue exist in the C API `CreateHeteroGraph` where we have no way to specify the number of nodes of a node type without any inbound/outbound edges.

**Comment by Maybewuss** [comment]
Maybe you can write like :
```python
g = dgl.heterograph({('A', 'AB', 'B'): [(0, 1), (1, 2)], ('C','_','C'):[]},              
                     num_nodes_dict={'A': 3, 'B': 3, 'C': 3})
```

**Comment by BarclayII** [comment]
> Maybe you can write like :
> 
> ```python
> g = dgl.heterograph({('A', 'AB', 'B'): [(0, 1), (1, 2)], ('C','_','C'):[]},              
>                      num_nodes_dict={'A': 3, 'B': 3, 'C': 3})
> ```

Sure.  I would still prefer fixing this though, as otherwise lots of unexpected stuff will happen (e.g. when a graph sampler picked some nodes and one node type has no inbound/outbound edges).
