### ISSUE TITLE
How to perform edge classification tasks

### ISSUE THREAD

**Issue by yzc1103** [dmlc/dgl#1322]
## ❓ Questions and Help
Is there a model or interface where edges and node characteristics can be entered together, and finally each edge can be classified.

**Comment by BarclayII** [comment]
For starters, one can simply combine the edge features as well as their source node features and destination node features together, and pass the combination into a neural network to get a final result.

Say, you have a function

```python
def classify_edge(source_node_features, destination_node_features, edge_features):
    """
    source_node_features : 
        A tensor whose rows stands for features of source nodes of each edge
    destination_node_features : 
        A tensor whose rows stands for features of destination nodes of each edge
    edge_features : 
        A tensor whose rows stands for features of each edge itself
    """
    pass
```

which returns a class prediction for each edge.  Then with DGL you can do:

```python
g.ndata['node_features'] = node_features
g.edata['edge_features'] = edge_features
g.apply_edges(lambda edges:
    {'edge_prediction': classify_edges(
        edges.src['node_features'],
        edges.dst['node_features'],
        edges.data['edge_features'])})
edge_predictions = g.edata['edge_prediction']
```

More advanced models involve message passing that let the node features (and potentially edge features) interact with each other in a sophisticated manner.  GCMC (graph convolutional matrix completion) for instance is a typical example that applies message passing for rating prediction, a kind of edge classification/regression.  DGL has an example implementation for GCMC.  [Spam Review Detection with GCN](https://arxiv.org/abs/1908.10679) is another example.

**Comment by saharshleo** [comment]
@BarclayII (or anyone) can you please provide some starting point for that classify_edge function?
I am new to GCN, so if anyone can provide some network to start with, it would help a lot!
