### ISSUE TITLE
dgl.DGLHeteroGraph.multi_update_all

### ISSUE THREAD

**Issue by gumowangfei** [dmlc/dgl#1329]
## 📚 Documentation
```python
import dgl
import dgl.function as fn
import torch

g1 = dgl.graph([(0, 1), (1, 1)], 'user', 'follows')
g2 = dgl.bipartite([(0, 1)], 'game', 'attracts', 'user')
g = dgl.hetero_from_relations([g1, g2])
g.nodes['user'].data['h'] = torch.tensor([[1.], [2.]])
g.nodes['game'].data['h'] = torch.tensor([[1.]])

g.multi_update_all(
    {'follows': (fn.copy_src('h', 'm'), fn.sum('m', 'h')),
     'attracts': (fn.copy_src('h', 'm'), fn.sum('m', 'h'))},
"sum")
g.nodes['user'].data['h']
# out
tensor([[0.],
        [4.]])
```

Why is 0 the data of node 0? Node 0 has no degree of entry. The value of h should be the original value of 1.

**Comment by jermainewang** [comment]
When triggering message passing on nodes recving no in-coming messages, DGL sets default values depending on the provided reduce function.
* If it is a UDF, use the corresponding feature initializer, which could be set by `g.set_n_initializer`. The feature initializer can be any function like:
  ```python
  def myinitializer(shape, dtype, ctx, id_range):
      return torch.ones(shape, dtype=dtype, device=ctx)
  g.set_n_initializer(myinitializer)
  ```
* If it is a built-in function, use the zero element of the provided aggregator (e.g., `max` will use smallest negative value, `min` will use largest positive value, etc.)

**Comment by gumowangfei** [comment]
Thanks
