### ISSUE TITLE
module 'dgl' has no attribute 'sampling'

### ISSUE THREAD

**Issue by linbang** [dmlc/dgl#1344]
## ❓ Questions and Help

when i use metapath2vec algorithm, the problem shows in "dgl.sampling.randomwalk()".
how to fix it?

**Comment by classicsong** [comment]
Please try 
```
import dgl.contrib.sampling.randomwalk
```

**Comment by BarclayII** [comment]
The master branch examples run on DGL nightly build, and `dgl.sampling.random_walk` is a new interface only available in nightly builds.  You can try either of the following:
* Install nightly build via `pip install --pre dgl` for CPU, or `pip install --pre dgl-cu100` for CUDA 10.0, etc.  Note that nightly builds are only available for Linux.
* (Build from source is always another option.)
* Use the examples in branch `0.4.x`, which uses `dgl.contrib.sampling.randomwalk`.  It has very different interface from the new version.

**Comment by linbang** [comment]
Thanks for all comments.
I find the way to solve this problem: using:
`import dgl.contrib.sampling.metapath_random_walk()`
In this way, we can generate paths which are guided by metapath
