### ISSUE TITLE
error: "is_assignable_v" is not a function or static data member

### ISSUE THREAD

**Issue by hongjuny** [dmlc/dgl#1346]
I am having trouble with compiling dgl on PowerPC, received many errors saying:

error: "is_assignable_v" is not a function or static data member
error: "constexpr" is not valid here
...
100 errors detected in the compilation of "/tmp/tmpxft_0000a50e_00000000-6_binary_bcast_reduce_none.cpp1.ii".
Compilation terminated.
CMake Error at dgl_generated_binary_bcast_reduce_none.cu.o.cmake:279 (message):
  Error generating file
  ./dgl/build/CMakeFiles/dgl.dir/src/kernel/cuda/./dgl_generated_binary_bcast_reduce_none.cu.o

make[2]: *** [CMakeFiles/dgl.dir/build.make:1066: CMakeFiles/dgl.dir/src/kernel/cuda/dgl_generated_binary_bcast_reduce_none.cu.o] Error 1
make[1]: *** [CMakeFiles/Makefile2:81: CMakeFiles/dgl.dir/all] Error 2
make: *** [Makefile:130: all] Error 2

I've been using the dgl 0.4 on the same machine, which has been working flawlessly.

**Comment by hongjuny** [comment]
Problem resolved. It was due to my recent conda environment. The compilation was successful if I deactivated it and compiled with the gcc on the system. Sorry for the confusion.

**Comment by migalkin** [comment]
I'm facing the same issue on PowerPC and GCC 8.3.0, all conda/venv environments are deactivated, but the same problem exists. Could you please elaborate wow you solved it in details?
