### ISSUE TITLE
weird behavior of edge_ids

### ISSUE THREAD

**Issue by zheng-da** [dmlc/dgl#1356]
## 🐛 Bug

The behavior of `edge_ids` is different with or without calling `is_multigraph` before it. If `is_multigraph` is called before, `edge_ids` returns a tensor. If not, it returns a tuple of tensors.

```python
import numpy as np
import dgl
from dgl.graph_index import from_scipy_sparse_matrix
from scipy import sparse as spsp

def create_large_graph_index(num_nodes):
    row = np.random.choice(num_nodes, num_nodes * 10)
    col = np.random.choice(num_nodes, num_nodes * 10)
    spm = spsp.coo_matrix((np.ones(len(row)), (row, col)))
    return from_scipy_sparse_matrix(spm, True)

g = dgl.DGLGraph(create_large_graph_index(1000), readonly=True)
src, dst = g.all_edges(form='uv', order='eid')
#print('multigraph:', g.is_multigraph)
orig_eid = g.edge_ids([0, 1, 2, 3], [2, 5, 7, 8])
print(orig_eid)
```

## To Reproduce

1.
1.
1.

## Environment

 - DGL Version (e.g., 1.0):
 - Backend Library & Version (e.g., PyTorch 0.4.1, MXNet/Gluon 1.3):
 - OS (e.g., Linux):
 - How you installed DGL (`conda`, `pip`, source):
 - Build command you used (if compiling from source):
 - Python version:
 - CUDA/cuDNN version (if applicable):
 - GPU models and configuration (e.g. V100):
 - Any other relevant information:

**Comment by BarclayII** [comment]
This is intended: if it is a simple graph we return a single tensor of edge IDs.  Otherwise it will return a triplet of source, destination, and edge IDs.  If you want consistent behaviors, set `force_multi` to True.

Or maybe you want to have `force_multi` to be True as default?
