### ISSUE TITLE
Add `canonical_etype` to the document of `dgl.udf.EdgeBatch`

### ISSUE THREAD

**Issue by AlfredWGA** [dmlc/dgl#1372]
## 📚 Documentation

I was wondering if I can obtain etype for heterograph in `dgl.udf.EdgeBatch`, however I find that this feature has been implemented long ago in [here](https://github.com/dmlc/dgl/blob/master/python/dgl/udf.py#L98) but not referred in the [EdgeBatch documentation](https://docs.dgl.ai/api/python/udf.html). 

Also I find that [`ntype`](https://github.com/dmlc/dgl/blob/master/python/dgl/udf.py#L180) doesn't appear in the documentation either.

It would be great to add this into the documentation to benefit future users!

UPDATE: I can't access these methods in dgl-cu100 (0.4.2), are these features not officially published yet?

**Comment by yzh119** [comment]
Yep they are newly introduced features (#1243), if you want to use them, install our nightly-build version or install from source.

@BarclayII I found that you have finished docstring for `NodeBatch` and `EdgeBatch` class but we have a unique rst file for udf, could you please refine them according?

**Comment by AlfredWGA** [comment]
> Yep they are newly introduced features (#1243), if you want to use them, install our nightly-build version or install from source.
> 
> @BarclayII I found that you have finished docstring for `NodeBatch` and `EdgeBatch` class but we have a unique rst file for udf, could you please refine them according?

Thanks for your help!
