### ISSUE TITLE
how to assignment edata to edges.src['data'] or edges.dst['data']

### ISSUE THREAD

**Issue by srtianxia** [dmlc/dgl#1373]
## ❓ Questions and Help
I know how to assignment src['n_data'] or dst['n_data']  to edata such as 

```python
g.apply_edges(lambda edges: {'e_data': edges.src['n_data']})
```

But how to assignment edata to edges.src['data'] or edges.dst['data']
```python
g.edata['e_data'] = torch.from_numpy(np.array([1, 2, 3, 4]))

g.ndata['data'] = ?
```

**Comment by yzh119** [comment]
The problem with copying edge data to source/destination node is that several edges may share the same source/destination node, how do you like to merge them? If you would like you take their summation, then
```
import dgl.function as fn
g.update_all(fn.copy_e('e_data', 'm'), fn.sum('m', 'n_data'))
```
is what you need (the same for `min/max/mean`).

But if you would like to take the concatenation of them, unfortunately DGL do not support a node attribute to have variable length.

**Comment by srtianxia** [comment]
> The problem with copying edge data to source/destination node is that several edges may share the same source/destination node, how do you like to merge them? If you would like you take their summation, then
> 
> ```python
> import dgl.function as fn
> g.update_all(fn.copy_e('e_data', 'm'), fn.sum('m', 'n_data'))
> ```
> 
> is what you need to "copy" edge data to destination nodes(the same for `min/max/mean`).
> 
> But if you would like to take the concatenation of them, unfortunately DGL do not support a node attribute to have variable length.

thanks!
