### ISSUE TITLE
libdgl.dylib installed to wrong directory, import dgl fails

### ISSUE THREAD

**Issue by adamjstewart** [dmlc/dgl#1379]
## 🐛 Bug

When I install DGL from source, the `libdgl.dylib` library gets installed to `<prefix>/dgl/libdgl.dylib`, which isn't searched by the default search locations in `dgl/_ffi/libinfo.py`.

## To Reproduce

First, install DGL from source.
```console
$ git clone --recursive https://github.com/dmlc/dgl.git
$ git checkout v0.4.2
$ git submodule init
$ git submodule update
$ mkdir build
$ cd build
$ cmake ..
$ make -j4
$ cd ../python
$ python setup.py install --prefix=<prefix> --single-version-externally-managed --root=/
```
Note that the `--single-version-externally-managed --root=/` flags are crucial to reproducing this issue. Without these flags, setuptools builds eggs, which I don't want, but with these flags, the library is installed to the wrong location.

Then, try to import the library.
```console
$ export PYTHONPATH=<prefix>/lib/python3.7/site-packages:$PYTHONPATH
$ python
Python 3.7.6 (default, Mar 20 2020, 17:25:19) 
[Clang 11.0.0 (clang-1100.0.33.17)] on darwin
Type "help", "copyright", "credits" or "license" for more information.
>>> import dgl
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "<prefix>/lib/python3.7/site-packages/dgl/__init__.py", line 8, in <module>
    from .backend import load_backend
  File "<prefix>/lib/python3.7/site-packages/dgl/backend/__init__.py", line 48, in <module>
    load_backend(os.environ.get('DGLBACKEND', 'pytorch').lower())
  File "<prefix>/lib/python3.7/site-packages/dgl/backend/__init__.py", line 18, in load_backend
    mod = importlib.import_module('.%s' % mod_name, __name__)
  File "<prefix>/lib/python3.7/importlib/__init__.py", line 127, in import_module
    return _bootstrap._gcd_import(name[level:], package, level)
  File "<prefix>/lib/python3.7/site-packages/dgl/backend/pytorch/__init__.py", line 1, in <module>
    from .tensor import *
  File "<prefix>/lib/python3.7/site-packages/dgl/backend/pytorch/tensor.py", line 9, in <module>
    from ... import ndarray as nd
  File "<prefix>/lib/python3.7/site-packages/dgl/ndarray.py", line 14, in <module>
    from ._ffi.ndarray import DGLContext, DGLType, NDArrayBase
  File "<prefix>/lib/python3.7/site-packages/dgl/_ffi/ndarray.py", line 8, in <module>
    from .base import _LIB, check_call, c_array, string_types, _FFI_MODE, c_str
  File "<prefix>/lib/python3.7/site-packages/dgl/_ffi/base.py", line 42, in <module>
    _LIB, _LIB_NAME = _load_lib()
  File "<prefix>/lib/python3.7/site-packages/dgl/_ffi/base.py", line 33, in _load_lib
    lib_path = libinfo.find_lib_path()
  File "<prefix>/lib/python3.7/site-packages/dgl/_ffi/libinfo.py", line 80, in find_lib_path
    raise RuntimeError(message)
RuntimeError: Cannot find the files.
List of candidates:
<prefix>/lib/python3.7/site-packages/dgl/libdgl.dylib
<prefix>/lib/python3.7/build/libdgl.dylib
<prefix>/lib/python3.7/build/Release/libdgl.dylib
<prefix>/lib/python3.7/lib/libdgl.dylib
<prefix>/lib/libdgl.dylib
```

## Expected behavior

Either `libdgl.dylib` should be installed to one of these default search locations, or the directory it is installed to should be added to this list.

For now, I can move the `<prefix>/dgl` directory to `<prefix>/lib` to get around this problem.

## Environment

 - DGL Version (e.g., 1.0): 0.4.2
 - Backend Library & Version (e.g., PyTorch 0.4.1, MXNet/Gluon 1.3): PyTorch 1.4.0
 - OS (e.g., Linux): macOS 10.15.3
 - How you installed DGL (`conda`, `pip`, source): source/`spack`
 - Build command you used (if compiling from source): `python setup.py install --prefix=<prefix> --single-version-externally-managed --root=/`
 - Python version: 3.7.6
 - CUDA/cuDNN version (if applicable): N/A
 - GPU models and configuration (e.g. V100): N/A
 - Any other relevant information: Clang 11.0.0

## Additional context

I'm actually using the [Spack](https://spack.io/) package manager to build DGL from source. Here are the relevant build logs:

* [spack-build-out.txt](https://github.com/dmlc/dgl/files/4362473/spack-build-out.txt)
* [spack-build-env.txt](https://github.com/dmlc/dgl/files/4362474/spack-build-env.txt)

**Comment by jermainewang** [comment]
One workaround is `export DGL_LIBRARY_PATH=<prefix>/dgl`. That should make it find the correct library.

**Comment by adamjstewart** [comment]
Was this behavior fixed?

**Comment by lostinplace** [comment]
this was not fixed, I'm still running into the error 4 years later

it's also not clear what prefix should be used in the proposed workaround
