### ISSUE TITLE
for cora, may i know why use 1-140 as train,200-500 as validation, what happened to 140-120 thanks

### ISSUE THREAD

**Issue by laurahdy** [dmlc/dgl#1396]
## ❓ Questions and Help

Before proceeding, please note that we recommend
using our discussion forum (https://discuss.dgl.ai) for
general questions. As a result, this issue will
likely be CLOSED shortly.

**Comment by yzh119** [comment]
Hi, the train/val/test partition comes from thomas kipf's original implementation of gcn: https://github.com/tkipf/pygcn/blob/master/pygcn/utils.py#L41-L43.

**Comment by gcucurull** [comment]
I think that the train/val/test partitions are not the same as the ones used in the original paper of GCNs. 
In https://github.com/tkipf/pygcn it says that:

> This implementation makes use of the Cora dataset from [2].

Which is a different paper, and I believe uses different splits.

For example, in tkipf/pygcn the validation indexes range from 200 to 500, but in the original implementation, which was coded in Tensorflow (https://github.com/tkipf/gcn/) the validation indexes range from 140 to 639, as can be checked in https://github.com/tkipf/gcn/blob/master/gcn/utils.py#L77

**Comment by jermainewang** [comment]
Thanks @gcucurull for more inputs on this question. I close this since this is more a general discussion rather than an actual issue. Please use our [discuss forum](https://discuss.dgl.ai) for such kinds. Thanks!
