### ISSUE TITLE
Why DGL has multi-threading in pytorch?

### ISSUE THREAD

**Issue by JinYang88** [dmlc/dgl#1407]
Multi-threading will not improve the efficiency if a python task requires lots of cpu computation because of GIL.  

However, DGL use multi-threading in functions like `copy_from_parent`. 

I was wondering why DGL is designed to use multi-threading? Thanks!

**Comment by yzh119** [comment]
We use multi-threading on C-end rather than Python-end and they will not be influenced by GIL.

**Comment by JinYang88** [comment]
In my practice, multi-threading may make DGL un-reproducible even when dgl.random.seed is fixed, is there any solution?

**Comment by yzh119** [comment]
Of course, set environment variable `OMP_NUM_THREADS=1` is enough imo.

**Comment by JinYang88** [comment]
Thanks！
