### ISSUE TITLE
PyPI is missing the macOS Python 3.8 wheel for version 0.4.3

### ISSUE THREAD

**Issue by willfrey** [dmlc/dgl#1415]
[PyPI](https://pypi.org/project/dgl/#files) appears to be missing a wheel for Python 3.8 on macOS for the 0.4.3 release. Could you please upload that when you get a chance?

Thank you!

**Comment by VoVAllen** [comment]
Hi,

I just uploaded the 0.4.3 for MacOS 10.14. Could you try whether `pip install dgl==0.4.3` now works?

**Comment by willfrey** [comment]
Success! Thank you.
