### ISSUE TITLE
Documentation not appearing correctly for DGLGraph.remove_nodes & DGLGraph.remove_edges

### ISSUE THREAD

**Issue by Axeln78** [dmlc/dgl#1431]
## 📚 Documentation

Though it seems that the documentation is complete in the source code it does not appear correctly on the documentation website for the two polling functions:

DGLGraph.remove_nodes
DGLGraph.remove_edges
DGLGraph.add_edges
DGLGraph.add_edge
DGLGraph.add_node

**Comment by yzh119** [comment]
Thanks for your notification, will fix soon.

**Comment by yzh119** [comment]
Should have been fixed in the latest version: https://docs.dgl.ai/en/latest/api/python/graph.html
