### ISSUE TITLE
Is multi-gpu supported in DGL (Pytorch) ?

### ISSUE THREAD

**Issue by ChangoLin** [dmlc/dgl#1434]
Is multi-gpu supported in DGL (Pytorch) ?

**Comment by mufeili** [comment]
Yes, see our example for [transformer](https://github.com/dmlc/dgl/tree/master/examples/pytorch/transformer), which supports multi-gpu training with PyTorch by multiprocessing. The REAMDE is outdated for multi-gpu support and will be fixed in #1435 .

**Comment by jermainewang** [comment]
If you are looking for multi-GPU training on one giant graph by sampling. We have an example for training GraphSAGE [here](https://github.com/dmlc/dgl/tree/master/examples/pytorch/graphsage).
