### ISSUE TITLE
How to implement dynamic GCN (e.g. EvolveGCN) in dgl?

### ISSUE THREAD

**Issue by ahmedelmahy** [dmlc/dgl#1442]
## 🚀 Feature 
I am looking into the approach in this paper (EvolveGCN), where additional weights are added when the graph changes over time (To allow the network to be modelled while being dynamic). I don't know how they handle it because they coded it with pytorch while I am familiar with tensorflow. What should I do to reproduce their work .. Are there any suggestions? It's also mentioned that dgl supports dynamic networks, How ? Is there any example ? 
- [EvolveGCN: Evolving Graph Convolutional Networks for Dynamic Graphs](https://arxiv.org/abs/1902.10191)

**Comment by jermainewang** [comment]
We have two tutorials about models that generate networks [here](https://docs.dgl.ai/tutorials/models/index.html#generative-models).

DGL has added TensorFlow support in the latest release and you could find some examples [here](https://github.com/dmlc/dgl/tree/master/examples/tensorflow). My general suggestion will be starting with our TF examples to get familiar with DGL such as how the training loop and model definition look like. I believe the author's implementation also has these concepts so you will find it easier to port it to TF afterwards. Let us know if you met any problem during implementation and use the [discuss forum](https://discuss.dgl.ai) if you need some in-detailed discussion. Look forward to your work and don't forget to contribute it to DGL once you've finished~

**Comment by maqy1995** [comment]
Hi @jermainewang, I recently implemented EvolveGCN on the Elliptic dataset using DGL, may I submit a PR?
