### ISSUE TITLE
Memory Leak with TF2

### ISSUE THREAD

**Issue by Rohanjames1997** [dmlc/dgl#1443]
## 🐛 Bug

Each time certain functions (like find_edges() ) is called, a new TF device is created and it eats up some memory (CPU and GPU) and doesn't free it.

## To Reproduce

`import tensorflow as tf`
`import os`
`os.environ['USE_OFFICIAL_TFDLPACK'] = "true"`
`os.environ['DGLBACKEND'] = "tensorflow"`
`import dgl`
`import networkx as nx`
`graph = nx.complete_graph(4)`
`graph = dgl.DGLGraph(graph)`
`for i in range(100):
       graph.find_edges([1])`

While running this, I noticed my GPU memory used via nvidia-smi and also my CPU RAM was constantly rising. And the stack trace shows the following message continuously getting printed. Here is one instance of it:

![DGL error](https://user-images.githubusercontent.com/23419169/79298113-26e25d80-7eae-11ea-95b8-dc3744863ef9.png)

## Environment

 - DGL Version `dgl-cu101==0.4.3`:
 - TF Version `tensorflow==2.2.0rc2`
 - OS - Linux
 - How you installed DGL and TF2 (`pip`):
 - Python version: 3.8.2
 - CUDA/cuDNN version (if applicable): 10.1
 - GPU models and configuration - Nvidia 1070Ti

**Comment by VoVAllen** [comment]
Thanks for the report. I'll take a look on this.

**Comment by VoVAllen** [comment]
Could you try tf-nightly instead of tensorflow 2.2.0rc2? There's one bug fix is not included in 2.2.0rc2

**Comment by Rohanjames1997** [comment]
@VoVAllen Yep! Running it with tf-nightly solves this issue and a few others which I was about to report! :smiley: 
Thanks!
