### ISSUE TITLE
cannot import name 'CFConv' from 'dgl.nn.pytorch'

### ISSUE THREAD

**Issue by laixindev** [dmlc/dgl#1444]
when I test the code below:
from dgllife.model import load_pretrained

model = load_pretrained('DGMG_ZINC_canonical')
model.eval()
smiles = []
for i in range(4):
    smiles.append(model(rdkit_mol=True))

print(smiles)

out:ImportError: cannot import name 'CFConv' from 'dgl.nn.pytorch'

???

**Comment by mufeili** [comment]
Hi, this issue should be addressed in DGL v0.4.3. To install the latest version, you may need to uninstall the older version first.
