### ISSUE TITLE
torch.bool support

### ISSUE THREAD

**Issue by GaiYu0** [dmlc/dgl#1448]
## 🚀 Feature

It would be nice if DGL's PyTorch backend supports `torch.bool`.

**Comment by VoVAllen** [comment]
Do you mean kernel support for torch.bool?

**Comment by GaiYu0** [comment]
Seems that DGL cannot recognize `torch.bool`. I think all we need is to add `torch.bool` to PyTorch backend's `data_type_dict`.

**Comment by jermainewang** [comment]
@GaiYu0 done in https://github.com/dmlc/dgl/pull/1487.
