### ISSUE TITLE
Cannot map edge indices in block to parent graph

### ISSUE THREAD

**Issue by toooooodo** [dmlc/dgl#1450]
## To Reproduce

> g = dgl.graph([(0, 2), (0, 3), (1, 2)])
> frontier = dgl.sampling.sample_neighbors(g, torch.tensor([3]), fanout=5)
> block = dgl.to_block(frontier, torch.tensor([3]))
> print(block.edata[dgl.EID])
> print(block[’_E’].edata[dgl.EID])

Both line output `tensor([0])`

## Expected behavior
output `tensor([1])` & `tensor([1])`

## Environment

 - DGL Version (e.g., 1.0): 0.4.3
 - Backend Library & Version (e.g., PyTorch 0.4.1, MXNet/Gluon 1.3): Pytorch 1.2.0
 - OS (e.g., Linux): Linux 
 - How you installed DGL (`conda`, `pip`, source): `pip`
 - Python version: 3.7.2
 - CUDA/cuDNN version (if applicable): CUDA10.0
 - GPU models and configuration (e.g. V100): GTX1080Ti

**Comment by BarclayII** [comment]
The edge IDs returned by `to_block` are induced by the edges of the graph in the argument, i.e. `frontier`.  So if you want to get the real edge IDs that come from the original graph you need to do a double indexing:
```python
frontier.edata[dgl.EID][block.edata[dgl.EID]]
```

**Comment by toooooodo** [comment]
Wow, thanks. It's cool!!

**Comment by UtkrishtP** [comment]
@BarclayII 
Is it possible to achieve the same without use of frontier in the latest DGL?
