### ISSUE TITLE
Possibly bug in GCMC pytorch example

### ISSUE THREAD

**Issue by kimjh12** [dmlc/dgl#1456]
https://github.com/dmlc/dgl/blob/5efd1c4aced3c7e0840eb9ee205e3f6517906f2a/examples/pytorch/gcmc/train.py#L164-L170

Looks like a mistake at line 169, which seems better to set to `new_lr` rather than `learning_rate`. Plz check.

**Comment by classicsong** [comment]
Yes. It should be new_lr

**Comment by classicsong** [comment]
Merged
