### ISSUE TITLE
After dgl in Pycharm,module 'dgl' has no attribute 'DGLGraph'?

### ISSUE THREAD

**Issue by caiguozhihua** [dmlc/dgl#1459]
## To Reproduce

1.
1.
1.

## Environment

 - DGL Version (e.g., 1.0):
 - Backend Library & Version (e.g., PyTorch 0.4.1, MXNet/Gluon 1.3):
 - OS (e.g., Linux):
 - How you installed DGL (`conda`, `pip`, source):
 - Build command you used (if compiling from source):
 - Python version:
 - CUDA/cuDNN version (if applicable):
 - GPU models and configuration (e.g. V100):
 - Any other relevant information:

**Comment by yzh119** [comment]
Could you please provide more information? Have you set up the "project interpreter" to the python environment that have dgl installed?
Will you meet the same problem when you do not use PyCharm?
