### ISSUE TITLE
a question about sageconv

### ISSUE THREAD

**Issue by naivefaith** [dmlc/dgl#1461]
i notice the code in dgl/python/dgl/nn/pytorch/conv/sageconv.py line 154.
rst = self.fc_self(h_self) + self.fc_neigh(h_neigh)
if it means that DGL use add() instead of concat()? the operation is different from the paper？

**Comment by yzh119** [comment]
Hi, before we add `h_self` and `h_neigh`, we have already applied linear transformation on these features by `self.fc_self` and `self.fc_neigh`, it's equivalent to the original paper.

**Comment by naivefaith** [comment]
> Hi, before we add `h_self` and `h_neigh`, we have already applied linear transformation on these features by `self.fc_self` and `self.fc_neigh`, it's equivalent to the original paper.

thank you for your answer.i wander if it is an universal trick that can instead of concat. in other situation, applying linear transformation and adding the feature will better than just concat it?

**Comment by yzh119** [comment]
It's case if the network applies only linear transformation on the concatenation (e.g. GraphSAGE and GAT, for GAT we use the same trick: https://github.com/dmlc/dgl/blob/master/python/dgl/nn/pytorch/conv/gatconv.py), but not the case when you apply an MLP on the concatenation (e.g. Relational Network or Recurrent Relational Network: https://github.com/dmlc/dgl/blob/master/examples/pytorch/rrn/rrn.py).
