### ISSUE TITLE
How to add a matrix or a set of vectors for each node and edge as attributes to the rgcn

### ISSUE THREAD

**Issue by Hosein47** [dmlc/dgl#1462]
I am using rgcn for a link prediction problem. The problem is that I want to use a matrix of features on each node and edge of the graph, thus their types would be different from each other. Will the rgcn model support these types of attributes?

**Comment by classicsong** [comment]
Can you give more details about 'use a matrix of features on each node and edge of the graph, thus their types would be different from each other.' 
You want to put some feature in nodes?

**Comment by Hosein47** [comment]
Yes, instead of a vector of features, I want to use a matrix of features in which each column describes a certain feature. In other words, I want the feature representation of each node and edge to be of a matrix form instead of a vector.

**Comment by classicsong** [comment]
> Yes, instead of a vector of features, I want to use a matrix of features in which each column describes a certain feature. In other words, I want the feature representation of each node and edge to be of a matrix form instead of a vector.

Does your node and edge has initial feature matrix?

**Comment by BarclayII** [comment]
> Yes, instead of a vector of features, I want to use a matrix of features in which each column describes a certain feature. In other words, I want the feature representation of each node and edge to be of a matrix form instead of a vector.

In DGL it is OK to assign a feature matrix to a node/edge.  For instance, consider the following graph with 4 nodes:

```python
g = dgl.graph([(0, 1), (1, 2), (2, 3)])
```

You can assign 6x7 feature matrices to nodes with the following:

```python
g.ndata['x'] = torch.randn(4, 6, 7)
```

**Comment by BarclayII** [comment]
Please feel free to reopen if this did not address your question.
