### ISSUE TITLE
the `put_embeddings` function only update partial `new_embeddings` to the `h`

### ISSUE THREAD

**Issue by DeepColin** [dmlc/dgl#1464]
## ❓ Questions and Help

> the `put_embeddings` function only update partial `new_embeddings` to the `h`
although we get the `new_embeddings` in the shape  of `(len(nodeset), out_features)`, the `h_new` stays in the shape of `(len(nodeset), in_features)`

**Comment by jermainewang** [comment]
Hi there, the question is not clear to us. Please provide more information (e.g. where and what is the problem) and reopen the issue. Thanks.
