### ISSUE TITLE
Link Prediction on Sequential Graph Data

### ISSUE THREAD

**Issue by rwer81** [dmlc/dgl#1472]
I am new at DGL or Graph Neural Networks. I have some experience in NN and Graph Data but not in DGL.
I have some data includes; “user” ,“location”(not spatial only Id) and datetime. Users check in in these locations. So I think this data can be represented as Graph. “user1”–>checked_in–>“location1”.A user can check in same location at different times. For trial purposes for now I did not add user or location features. But edges have time feature.
I want to predict “at which location will the next check_in of a specific user?” to send mail about deals around to that location.
So, what model should i use? or, Is there any solution for this problem in Graph Neural Networks world?
Thanks.

**Comment by VoVAllen** [comment]
Hi, I've replied at the [discussion forum](
https://discuss.dgl.ai/t/link-prediction-on-sequential-graph-data/922). Let's move to there for further discussion.
