### ISSUE TITLE
Graph.batch(graph_list) should copy even when len(graph_list) == 1

### ISSUE THREAD

**Issue by sneakerkg** [dmlc/dgl#1475]
## 🐛 Bug

In current implementation, graph.batch(graph_list) will create a new graph and copy the links from each individual graph in graph_list if len(graph_list) > 1. However, if len(graph_list) == 1, it will not do the copy, instead, directly return the single graph in graph_list. This might cause some trouble for usage like graph pool, one of the element of graph pool might be polluted after forward.

## To Reproduce

<pre><code>
import dgl
import torch as th

graphpool = [dgl.DGLGraph() for _ in range(5)]
for g in graphpool:
     g.add_nodes(1)
batch0 = dgl.batch([graphpool[0], graphpool[1]])
batch0.nodes[:].data['x'] = th.zeros(2, 3)
batch1 = dgl.batch([graphpool[2]])
batch1.nodes[:].data['x'] = th.zeros(1, 3)
batch3 = dgl.batch([graphpool[2], graphpool[1]])
</code></pre>

## Expected behavior
<pre><code>
ValueError: Expect graph 0 and 1 to have the same node attributes when node_attrs=ALL, got {'x'} and set().
</code></pre>

## Environment

 - DGL Version: 0.4
 - Backend Library & Version: Pytorch 1.4.0

**Comment by yzh119** [comment]
Solved in #1483.
