### ISSUE TITLE
Loading dataset PROTEINS leads to IndexError

### ISSUE THREAD

**Issue by wwwfan628** [dmlc/dgl#1477]
## 🐛 Bug

When loading dataset PROTEINS using function `LegacyTUDataset()`, raise `IndexError: too many indices for array`
## To Reproduce

```python
from dgl.data import LegacyTUDataset

dataset = LegacyTUDataset(name='PROTEINS')
 ```
The error message as following:
```
~/opt/anaconda3/lib/python3.7/site-packages/dgl/data/tu.py in __init__(self, name, use_pandas, hidden_size, max_allow_node)
     78                 self._file_path("node_attributes"), delimiter=",")
     79             for idxs, g in zip(node_idx_list, self.graph_lists):
---> 80                 g.ndata['feat'] = DS_node_attr[idxs, :]
     81             self.data_mode = "node_attr"
     82         except IOError:

IndexError: too many indices for array
```

## Expected behavior

Successfully loading PROTEINS dataset
## Environment

 - DGL Version (e.g., 1.0): 0.4.2
 - Backend Library & Version (e.g., PyTorch 0.4.1, MXNet/Gluon 1.3): PyTorch
 - OS (e.g., Linux): MacOS X
 - How you installed DGL (`conda`, `pip`, source): pip
 - Build command you used (if compiling from source):
 - Python version: 3.7
 - CUDA/cuDNN version (if applicable):
 - GPU models and configuration (e.g. V100):
 - Any other relevant information:

**Comment by VoVAllen** [comment]
Added fix at https://github.com/dmlc/dgl/pull/1467. However, the new TUDataset class is recommended. And dataset preprocessing is different for TUDatasets, please check carefully with the original paper/code
