### ISSUE TITLE
How to implement a modified RGCN model?

### ISSUE THREAD

**Issue by sakuraiiiii** [dmlc/dgl#1485]
Hi.I have a question about implement heterogeneous graph with DGL.
Analogous to the model of Relational Graph Convolutional Networks (R-GCNs)
$$
h_i^{(l+1)}=\sigma (\sum_{r \in R} \sum_{j \in N_i^r} \frac {1} {c_{i, r}} W_r^{l}h_j^{(l)}+W_0^{(l)}h_i^{(l)}),
$$
I want to implement the following modified model
$$
h_i^{(l+1)}=\sigma (\sum_{r \in R} \sum_{j \in N_i^r} W_r^{(l)}(h_j^{(l)}+h_i^{(l)}))
$$
I think maybe I need to re-define the message function,but I don’t know how to specify the GCN-dict for different `etypes` in the message function.Or maybe there is another approach to implement it?Could you give me some advice?Thank you.

**Comment by classicsong** [comment]
Here is the example of how to define each GCN layer for each relation type:
https://github.com/dmlc/dgl/blob/3c4506e91e563d519dae084ff9ad46dfba93ef2e/examples/pytorch/rgcn-hetero/model.py#L55

**Comment by sakuraiiiii** [comment]
So if I want to implement the model I defined,it looks like that I need to define message function for each ```GraphConv``` of meta-path and call these re-defined GraphConv in ```dgl.nn.pytorch.HeteroGraphConv``` class?

**Comment by classicsong** [comment]
You can define your own GraphConv and build your own GraphConv layers.
```
def NewGraphConv(nn.Module):
   ...

self.conv = dglnn.HeteroGraphConv({
                rel : NewGraphConv(in_feat, out_feat, ...) for rel in rel_names
            })
```

**Comment by sakuraiiiii** [comment]
Yep,that's what I mean above.Thank you very much.
