### ISSUE TITLE
inferencing module (beam decoder) for Transformer.

### ISSUE THREAD

**Issue by baozixifan** [dmlc/dgl#1488]
## 🐛 Bug

Using backend: pytorch
start creating graph pool...
successfully created graph pool, time: 1.207s
Traceback (most recent call last):
  File "translation_test.py", line 43, in <module>
    output = model.infer(g, dataset.MAX_LENGTH, dataset.eos_id, k, alpha=0.6)
  File "/home/ljj/PycharmProjects/dgl-master/examples/pytorch/transformer/modules/models.py", line 173, in infer
    edges_ed = g.filter_edges(lambda e: (e.dst['pos'] < step) & ~e.dst['mask'] , eids['ed'])
  File "/home/ljj/anaconda3/lib/python3.7/site-packages/dgl/graph.py", line 3785, in filter_edges
    e_mask = F.copy_to(predicate(ebatch), F.cpu())
  File "/home/ljj/PycharmProjects/dgl-master/examples/pytorch/transformer/modules/models.py", line 173, in <lambda>
    edges_ed = g.filter_edges(lambda e: (e.dst['pos'] < step) & ~e.dst['mask'] , eids['ed'])
RuntimeError: Expected object of scalar type Bool but got scalar type Byte for argument #2 'other' in call to _th_and

## To Reproduce

dgl-master/examples/pytorch/transformer/translation_test.py

$ python3 translation_test.py --gpu 0 --N 1 --dataset copy --batch 8 --checkpoint 9

## Expected behavior

For evaluating BLEU score on test set

## Environment

 - DGL Version (e.g., 1.0): dgl-cu101        0.5a200429 
 - Backend Library & Version (e.g., PyTorch 0.4.1, MXNet/Gluon 1.3):torch  1.4.0 ;torchvision      0.2.1 
 - OS (e.g., Linux):ubuntu 16.04
 - How you installed DGL (`conda`, `pip`, source):pip
 - Python version:3.7.3
 - CUDA/cuDNN version (if applicable):cuda 10.1
 - GPU models and configuration (e.g. V100):nvidia RTX 2070 super

**Comment by yzh119** [comment]
Sorry the transformer code is out-dated, I'll check it later.
If you are interested in research work on regarding transformer as GNNs, you can refer to our [BP-Transformer paper](https://arxiv.org/abs/1911.04070) and the [code repo](http://github.com/yzh119/bpt).

**Comment by baozixifan** [comment]
> Sorry the transformer code is out-dated, I'll check it later.
> If you are interested in research work on regarding transformer as GNNs, you can refer to our [BP-Transformer paper](https://arxiv.org/abs/1911.04070) and the [code repo](https://github.com/yzh119/bpt).

thanks
