### ISSUE TITLE
solver fails in unsupervised graphsage

### ISSUE THREAD

**Issue by naveenkumarmarri** [dmlc/dgl#1490]
## To Reproduce

1. python3 examples/pytorch/graphsage/train_sampling_unsupervised.py

```
/home/ubuntu/anaconda3/envs/pytorch_p36/lib/python3.6/site-packages/sklearn/linear_model/logistic.py:433: FutureWarning: Default solver will be changed to 'lbfgs' in 0.22. Specify a solver to silence this warning.
  FutureWarning)
Traceback (most recent call last):
  File "graphsage_sampling_unsup.py", line 336, in <module>
    run(args, device, data)
  File "graphsage_sampling_unsup.py", line 288, in run
    eval_acc, test_acc = evaluate(model, g, g.ndata['features'], labels, train_nid, val_nid, test_nid, args.batch_size, device)
  File "graphsage_sampling_unsup.py", line 216, in evaluate
    return compute_acc(pred, labels, train_nids, val_nids, test_nids)
  File "graphsage_sampling_unsup.py", line 193, in compute_acc
    lr.fit(emb[train_nids], labels[train_nids])
  File "/home/ubuntu/anaconda3/envs/pytorch_p36/lib/python3.6/site-packages/sklearn/linear_model/logistic.py", line 1294, in fit
    len(self.classes_))
  File "/home/ubuntu/anaconda3/envs/pytorch_p36/lib/python3.6/site-packages/sklearn/linear_model/logistic.py", line 473, in _check_multi_class
    "a multinomial backend." % solver)
ValueError: Solver liblinear does not support a multinomial backend.
```
## Expected behavior

No error when I change https://github.com/dmlc/dgl/blob/master/examples/pytorch/graphsage/train_sampling_unsupervised.py#L192 to
```
lr = lm.LogisticRegression(multi_class='multinomial', max_iter=10000, solver='newton-cg')
```

## Environment

 - DGL Version (e.g., 1.0):0.4.3post2
 - Backend Library & Version (e.g., PyTorch 0.4.1, MXNet/Gluon 1.3): PyTorch1.3.1
 - OS (e.g., Linux): Linux
 - How you installed DGL (`conda`, `pip`, source): conda
 - Build command you used (if compiling from source):
 - Python version: 3.7
 - CUDA/cuDNN version (if applicable): 10.1
 - GPU models and configuration (e.g. V100): V100
 - Any other relevant information:

**Comment by BarclayII** [comment]
Hi,

Scikit-learn 0.22 and later changed the default optimizer from liblinear to LBFGS so the code should work fine as is.
