### ISSUE TITLE
Question about DGL performance numbers in the README file

### ISSUE THREAD

**Issue by yuk12** [dmlc/dgl#1502]
## ❓ Questions and Help

I've the following quick questions about the performance numbers reported in the readme file (Table 1 and Table 2):
1. Which DGL version was used to get the performance numbers, 0.4.3?
2. Which XPU was used, CPU or GPU? if GPUs were used then which one (Pascal/Volta??), or if CPU then which one (Skylake/cascadelake??).
3. How many CPUs and GPUs units were used?
4. Which methods were used? sampling or full graphs codes of GCN/GAT.

Many thanks in advance.

**Comment by yzh119** [comment]
For Table 1 and Table 2.
1. DGL v0.3+
2. GPU, NVIDIA P100.
3. Just one.
4. Full graph (these datasets are small except for Reddit.).

**Comment by yzh119** [comment]
Please refer to the DGL paper: https://arxiv.org/pdf/1909.01315.pdf for more details.

**Comment by yuk12** [comment]
Thanks a ton :)
