### ISSUE TITLE
Transductive or inductive learning on OGB Products?

### ISSUE THREAD

**Issue by Elizabeth1997** [dmlc/dgl#1513]
## ❓ Questions and Help
Hi dgl team, I would like to know on OGB products dataset, you used transductive or inductive learning to get the result posted on the LeaderBoard? Thank you for answering in advance!

**Comment by BarclayII** [comment]
Good question!

I used the transductive learning scenario, and I think it matches the setting of ClusterGCN and Full-batch GraphSAGE OGB has provided in their examples.  However, it looks like OGB's GraphSAINT example works under an inductive learning setting.

I have raised an issue https://github.com/snap-stanford/ogb/issues/27 in OGB as well.

**Comment by Elizabeth1997** [comment]
I see, got it. Thanks for your reply! Yes, exactly, as you said, only GraphSAINT example works under an inductive learning setting.
