### ISSUE TITLE
[TensorFlow] Symbolic tensor support

### ISSUE THREAD

**Issue by AlpAribal** [dmlc/dgl#1515]
## 🚀 Feature
Support symbolic tensors so that tf.keras API can be used to its full extent.

## Motivation

Symbolic tensors (a.k.a. Keras tensors) are very useful when building models using the Functional Keras API. Currently, passing a symbolic tensor through a GraphConv layers results in an error (I have not checked other layers). Hence, it is not possible to use most of the Keras API (such as [Model.summary()](https://www.tensorflow.org/api_docs/python/tf/keras/Model#summary) or [Model.fit()](https://www.tensorflow.org/api_docs/python/tf/keras/Model#fit)) without pushing real data through the network. 

## Alternatives

I could not find any alternative solutions.

## Pitch

Suppose that my model takes the node features as input and classifies the graph. A simple implementation can be as follows:

    class Classifier(tf.keras.Model):
        def __init__(self, g, in_dim, hidden_dim, n_classes):
            super(Classifier, self).__init__()
            self.g = g
            self.conv = dgl.nn.GraphConv(in_dim, hidden_dim)
            self.classify = tf.keras.layers.Dense(n_classes, input_shape=(hidden_dim,))

        def call(self, feats):
            # Take node features as input, perform convolution and activation
            feats = tf.nn.relu(self.conv(self.g, feats))
            return self.classify(feats)

With a "literal" tensor, we can make predictions as follows:

    # create a graph and add some edges
    g = dgl.DGLGraph()
    g.add_nodes(5)
    g.add_edge(0, 1)
    g.add_edge(1, 2)
    g.add_edge(2, 3)
    g.add_edge(3, 4)

    # instantiate the classifier
    model = Classifier(g, 3, 5, 2)

    # create dummy features and make predictions
    feats = [row * np.array([1,2,3]) for row in range(5)]
    feats = tf.constant(feats, dtype="float32")
    print(feats)
    ==========
    tf.Tensor(
    [[ 0.  0.  0.]
     [ 1.  2.  3.]
     [ 2.  4.  6.]
     [ 3.  6.  9.]
     [ 4.  8. 12.]], shape=(5, 3), dtype=float32)

    prediction = model(feats)
    print(prediction)
    ==========
    tf.Tensor(
    [[0.        0.       ]
     [0.        0.       ]
     [2.6460838 2.1525013]
     [5.2921677 4.3050027]
     [7.938251  6.4575047]], shape=(5, 2), dtype=float32)

I want similar functionality, where I can provide the `feats` symbolically:

    # create symbolic keras input with the same size as before
    keras_feats = tf.keras.Input(shape=(5,3))
    model(keras_feats)
    ==========
    <tf.Tensor, shape=(None, 5, 2) dtype=float32>

## Additional context

Currently, when the example with the symbolic tensor is run, an error occurs.

    <ipython-input-21-995b6f88cfb6>:12 call  *
        h = tf.nn.relu(self.conv(self.g, h))
    /usr/local/lib/python3.6/dist-packages/tensorflow/python/keras/engine/base_layer.py:968 __call__  **
        outputs = self.call(cast_inputs, *args, **kwargs)
    /usr/local/lib/python3.6/dist-packages/dgl/nn/tensorflow/conv/graphconv.py:128 call
        degs = tf.clip_by_value(tf.cast(graph.out_degrees(), tf.float32),
    /usr/local/lib/python3.6/dist-packages/dgl/graph.py:794 out_degrees
        return self._graph.out_degrees(v).tousertensor()
    /usr/local/lib/python3.6/dist-packages/dgl/graph_index.py:518 out_degrees
        v_array = v.todgltensor()
    /usr/local/lib/python3.6/dist-packages/dgl/utils.py:113 todgltensor
        dlpack = F.zerocopy_to_dlpack(tsor)
    /usr/local/lib/python3.6/dist-packages/dgl/backend/tensorflow/tensor.py:40 zerocopy_to_dlpack
        return tfdlpack.to_dlpack(input)
    /usr/local/lib/python3.6/dist-packages/tfdlpack/core.py:30 to_dlpack
        cap = to_capsule(_to_dlpack_address(tf_tensor))
    /usr/local/lib/python3.6/dist-packages/tfdlpack/capsule_api.py:35 to_capsule
        add = int(ad_tensor.numpy())

    AttributeError: 'Tensor' object has no attribute 'numpy'

**Comment by VoVAllen** [comment]
Hi,

Unfortunately we are unable to support this right now. The mean reason is that there's lots of customized operation in DGL, which is hard to transform into symbolic execution in tensorflow. However, we are still looking for solutions, if you have found any resources or cases about this, we'll be glad to investigate so.

**Comment by kitbransby** [comment]
Gutted that symbolic tensors are not supported in dgl tensorflow as the Keras Functional API is so useful. Are there any workarounds?
