### ISSUE TITLE
[bug] There is a bug with RGCN norm implementation

### ISSUE THREAD

**Issue by Riroaki** [dmlc/dgl#1519]
In `build_graph_from_triplets(num_nodes, num_rels, triplets)`, `return g, rel.astype('int64'), norm.astype('int64')`returns a `norm` of integer type, and I'll encounter the following error in message passing:
```
dgl/nn/pytorch/conv/relgraphconv.py", line 150, in bdd_message_func
    msg = msg * edges.data['norm']
RuntimeError: expected device cuda:1 and dtype Float but got device cuda:1 and dtype Long
```
Location：
https://github.com/dmlc/dgl/blob/59aefe6e31ac1d7206ea874625b34e5d06102b9b/examples/pytorch/rgcn/utils.py#L144

The bug would be fixed if we remove the data type casting part.

**Comment by classicsong** [comment]
Which torch version you are using.

**Comment by Riroaki** [comment]
> Which torch version you are using.

torch==1.2.0, cuda==10.0

**Comment by classicsong** [comment]
> > Which torch version you are using.
> 
> torch==1.2.0, cuda==10.0

You can try torch version larger than 1.4.0.
