### ISSUE TITLE
unsupervised graph sage negative sampling

### ISSUE THREAD

**Issue by naveenkumarmarri** [dmlc/dgl#1535]
## To Reproduce

```
import dgl
from graphsage_sampling_unsup import NegativeSampler,\
                                    NeighborSampler

g_ = dgl.DGLGraph()
g_.add_nodes(4)
g_.add_edges([0,1,2], [1,2,0])
heads_, tails_ = g_.find_edges([0, 1])
neg_sampler_ = NegativeSampler(g_)
neg_tails_ = neg_sampler_(2 * 2)
neg_heads_ = heads_.view(-1, 1).expand(2, 2).flatten()

print(heads_, tails_)
tensor([0, 1]) tensor([1, 2])
print(neg_heads_, neg_tails_)
tensor([0, 0, 1, 1]) tensor([2, 1, 1, 1])

```

## Expected behavior

From the above graph output we can see that edge `0 -> 1` is a positive edge but it still appears in negative edge. I assume that the negative graph edges and positive graph edges are disjoint. 

## Environment

 - DGL Version (e.g., 1.0): `0.4.3post2`
 - Backend Library & Version (e.g., PyTorch 0.4.1, MXNet/Gluon 1.3):
 - OS (e.g., Linux): Linux
 - How you installed DGL (`conda`, `pip`, source):`conda`
 - Build command you used (if compiling from source):
 - Python version: `3.7`
 - CUDA/cuDNN version (if applicable): `10.1`
 - GPU models and configuration (e.g. V100): `V100`
 - Any other relevant information:

**Comment by classicsong** [comment]
This is a performance trick. When the dataset is large, sampling a little number of false negative edges does not affect the training progress.
