### ISSUE TITLE
The GATLayer seem have some randomness

### ISSUE THREAD

**Issue by ZhongLi-Shi** [dmlc/dgl#1536]
I found that GATLayer seemed have some randomness(Zihao Ye explained there were some atomic operation).I can't reproduce my experiment result anyway :(

**Comment by yzh119** [comment]
Yep we are working on this, please stay tuned.

**Comment by yzh119** [comment]
Duplicate of several issues: https://github.com/dmlc/dgl/issues?q=is%3Aissue+is%3Aopen+randomness.
