### ISSUE TITLE
The correspondence between the user's real id and the id in the graph

### ISSUE THREAD

**Issue by mliwang** [dmlc/dgl#1537]
dgl/examples/pytorch/pinsage/ 这个目录中，用户或者item的实际id怎么和图中的id对应啊，我应该用什么方法才可以取出节点的真实id

In `dgl/examples/pytorch/pinsage`, how did user/item's actual ID in the dataset correspond to the user/item node ID in the graph?

**Comment by BarclayII** [comment]
We did not save the correspondence between user/item IDs and user/item nodes, but they are maintained in the `PandasGraphBuilder` instance.

The graph is built from DataFrames by these lines:
https://github.com/dmlc/dgl/blob/0b902d032ab92f9c4fd6d3d8b283129851fb43d2/examples/pytorch/pinsage/process_nowplaying_rs.py#L32-L38

And `add_entities` method will save the correspondence between entity ID and entity index (as integer) via a Pandas Category series:
https://github.com/dmlc/dgl/blob/0b902d032ab92f9c4fd6d3d8b283129851fb43d2/examples/pytorch/pinsage/builder.py#L86

If you need the correspondence, you can pickle the `PandasGraphBuilder` during preprocessing and get the correspondence in the `entity_key_map` attribute.
