### ISSUE TITLE
Release DGL source code on PyPI (in addition to wheels)

### ISSUE THREAD

**Issue by 235** [dmlc/dgl#1539]
## ❓ Can you please release source .tar.gz packages on PyPI as well as in Github?

Hey, 
You currently release for pip (PyPI) only binary "wheel" packages: https://pypi.org/project/dgl/#files

Can you in addition release "source" .tar.gz packages? This would be similar to other pip packages: https://pypi.org/project/networkx/#files
You already have source packages released in GitHub, and they clearly are driving the Wheel package builds:  https://github.com/dmlc/dgl/releases

This would enable local source-based builds with `pip` with version tracking & remove the hard-coded links to Github.

Thank you

**Comment by yejingxin** [comment]
Any updates on this request?

**Comment by jermainewang** [comment]
My question is that since our source code contains C++, how will pip handle them? Will it trigger compilation on user's machine?
