### ISSUE TITLE
[Question] Implementing my own embedding algorithm in DGL

### ISSUE THREAD

**Issue by spapadias** [dmlc/dgl#1543]
Hello DGL people!

I read the arxiv 2020 paper and I found it very interesting. It is great that the project is open source.

I am wondering if I can implement my own graph embedding algorithm on top of your system, which focuses only in knowledge graph embeddings. For example, can I implement DeepWalk in DGL?

If yes, do you provide abstractions for defining random-walk operations in DGL?
If no, is it possible to build such abstractions in your system?

Thanks in advance.

Best,
Makis

**Comment by classicsong** [comment]
Hi, spapadisa:
    Yes, we welcome any contributions for DGL and DGL-KE.
    Currently, we have a PR for DeepWalk right now and are refining it: https://github.com/dmlc/dgl/pull/1503. 

    BTW, you are still welcomed to contribute to DGL/DGL-KE. Do you want to implement LINE based on DGL?

**Comment by spapadias** [comment]
Hi Xiang,

That is great! Myself (PhD Researcher) and a group of Master students from TU Berlin, we work on extending/implementing properly a set of Graph Embedding (GE) algorithms atop DGL(-KE) system.

We believe your system has great potential and this is why we chose it.

Sure, we want to contribute so that our implementation and efforts become part of DGL. This would be awesome. One of us is working on DeepWalk, so maybe we can be 

And LINE is also into our scheme of things and we plan to implement it. So, yes we want to implement this. 

Can I put my team in the loop?

Best,
Makis

**Comment by classicsong** [comment]
> Hi Xiang,
> 
> That is great! Myself (PhD Researcher) and a group of Master students from TU Berlin, we work on extending/implementing properly a set of Graph Embedding (GE) algorithms atop DGL(-KE) system.
> 
> We believe your system has great potential and this is why we chose it.
> 
> Sure, we want to contribute so that our implementation and efforts become part of DGL. This would be awesome. One of us is working on DeepWalk, so maybe we can be
> 
> And LINE is also into our scheme of things and we plan to implement it. So, yes we want to implement this.
> 
> Can I put my team in the loop?
> 
> Best,
> Makis

Hi, Makis:
    Your team are welcomed !!!
    Can you open an RFC issue and write down your current plan, e.g., DeepWalk, node2vec (random walk-based) and VERSE (PPR-based)? We can discuss there and DGL team are willing to provide any help.
   BTW, here is an PR of DeepWalk https://github.com/dmlc/dgl/pull/1503, if you are interested, feel free to review it.
