### ISSUE TITLE
HeteroConv does not work for graph with multiple node types

### ISSUE THREAD

**Issue by WowCZ** [dmlc/dgl#1545]
## ❓ Questions and Help

Before proceeding, please note that we recommend
using our discussion forum (https://discuss.dgl.ai) for
general questions. As a result, this issue will
likely be CLOSED shortly.

**Comment by BarclayII** [comment]
I found that our `HeteroGraphConv` has a bug when running on heterograph:

```python
g = dgl.heterograph({('A', 'AB', 'B'): [(0, 1), (1, 2)], ('B', 'BA', 'A'): [(3, 0), (0, 1), (1, 2)]})
m = dgl.nn.HeteroGraphConv({'AB': dgl.nn.GATConv(5, 3, 2), 'BA': dgl.nn.GATConv(5, 3, 2)})
m(g, x)        # <-- crashes
```

To work around it you can instead write something like:

```python
g = dgl.heterograph({('A', 'AB', 'B'): [(0, 1), (1, 2)], ('B', 'BA', 'A'): [(3, 0), (0, 1), (1, 2)]})
m = dgl.nn.HeteroGraphConv({'AB': dgl.nn.GATConv((5, 5), 3, 2), 'BA': dgl.nn.GATConv((5, 5), 3, 2)})
m(g, (x, x))
```

**Comment by WowCZ** [comment]
Thanks for your quick reply. It actually works following your tuple-type inputs.

**Comment by WowCZ** [comment]
> I found that our `HeteroGraphConv` has a bug when running on heterograph:
> 
> ```python
> g = dgl.heterograph({('A', 'AB', 'B'): [(0, 1), (1, 2)], ('B', 'BA', 'A'): [(3, 0), (0, 1), (1, 2)]})
> m = dgl.nn.HeteroGraphConv({'AB': dgl.nn.GATConv(5, 3, 2), 'BA': dgl.nn.GATConv(5, 3, 2)})
> m(g, x)        # <-- crashes
> ```
> 
> To work around it you can instead write something like:
> 
> ```python
> g = dgl.heterograph({('A', 'AB', 'B'): [(0, 1), (1, 2)], ('B', 'BA', 'A'): [(3, 0), (0, 1), (1, 2)]})
> m = dgl.nn.HeteroGraphConv({'AB': dgl.nn.GATConv((5, 5), 3, 2), 'BA': dgl.nn.GATConv((5, 5), 3, 2)})
> m(g, (x, x))
> ```
> 
> This also holds for `SAGEConv` etc. as well.

Thanks for your quick reply. It actually works following your tuple-type inputs.

**Comment by wjdghks950** [comment]
Having exactly the same problem here. Need revision for the dgl documentation that specifically refers to this issue.
