### ISSUE TITLE
Message computation and aggregation of dgl.bipartite

### ISSUE THREAD

**Issue by yzc1103** [dmlc/dgl#1546]
## ❓ Questions and Help
After building a heterogeneous directed bipartite graph with two types of nodes (similar to the example of a user-review-movie in a recommended scenario), I found that messaging and aggregation can only go from the source node to the target node, so I have some questions when classification using two layers GCN : 1. if the source node characteristics (user types) have not been updated; 2. If I want to update both the user-type node characteristics and the movie-type node characteristics, should I create an undirected graph?
Thank you for your reply!

**Comment by classicsong** [comment]
You can manually add a reverse edge. Some thing like:
https://github.com/dmlc/dgl/blob/7ba9cbc63e337f207c0707d1018d0d4e1c83ca51/examples/pytorch/gcmc/data.py#L256-L259
