### ISSUE TITLE
How to find n-hop neighbors (of the same type) for a node in dgl.heterograph

### ISSUE THREAD

**Issue by mliwang** [dmlc/dgl#1554]
In a dgl.heterograph object (there are two node types: `item` and `user`), how could I find n-hop neighbors of type `item` for a given `item` node efficiently?
I found the `successors` API extremely slow in finding k-hop neighbors, do you have related APIs that have better efficiency?

**Comment by VoVAllen** [comment]
Could you try `predecessor` also? I believe one of them should be fast. This is due to the way of how the graph is stored(CSR vs CSC)

**Comment by BarclayII** [comment]
`predecessors` and `successors` can only take one node ID so far.  You can try `in_edges` or `out_edges`, which can take in an array of nodes.

```python
g = dgl.graph([(0, 1), (1, 2)])
_, succs = g.out_edges([0, 1])   # (tensor([0, 1]), tensor([1, 2]))
```
