### ISSUE TITLE
Keep node feature when transform graph

### ISSUE THREAD

**Issue by sneakerkg** [dmlc/dgl#1562]
## 🚀 Feature
When we transform a graph (to_bidirected, metis_partition, etc), graph node feature will not be copied to transformed graph. This is inconvenient since copy all the ndata is also not trivial to users. 

The requested feature is: If the transform will not change the number of nodes in graph, or if there's mapping between nodes in old and new graph, maybe we can add an option in transform func that keep the node feature fields.

**Comment by mufeili** [comment]
Do you think if we should do a deep copy or shallow copy of the original node features?
