### ISSUE TITLE
"metis_partition_assignment" transform fails at HeteroGraph

### ISSUE THREAD

**Issue by sneakerkg** [dmlc/dgl#1564]
## 🐛 Bug

Since we are trying to use DGLHeteroGraph by default for all application. The behavior of DGLHeteroGraph should be same with DGLGraph. However, seems some of our transform functions do not take HeteroGraph as input. For example, metis_partition_assignment.
My code:
```
nd_group = dgl.transform.metis_partition_assignment(g, psize)
``` 
The error message is:
```
dgl._ffi.base.DGLError: [03:16:16] /home/ubuntu/git-repo/dgl/include/dgl/packed_func_ext.h:117: Check failed: ObjectTypeChecker<TObjectRef>::Check(sptr.get()): Expected type graph.Graph but get graph.HeteroGraph
```

**Comment by BarclayII** [comment]
Should be fixed in 0.5.
