### ISSUE TITLE
Add "self-loop" option for GraphConv Module

### ISSUE THREAD

**Issue by sneakerkg** [dmlc/dgl#1566]
## 🚀 Feature
Adding "self-loop" edges is a common trick for GCN implementation. Without which, we might have trouble stacking multiple layers of GCN, since the isolated nodes' feature will be washed out. It's verified causing model performance issue (accuracy) training several models like ClusterGCN.

The suggestion is adding "self-loop" option for GraphGonv module and by default, it should be True.

**Comment by mufeili** [comment]
In general it is still preferred to add `V` self loops in the data pre-processing steps. To add self loops in `GraphConv` can be wasteful as we are likely to add `V * L * E` self loops in total, where `L` is the number of `GraphConv` layers and `E` is the number of epochs. In this case, maybe we can leave a note in the documentation instead?

**Comment by Ian09** [comment]
It seems that the tutorial https://docs.dgl.ai/tutorials/models/1_gnn/1_gcn.html does NOT add the self loop, right?

**Comment by mufeili** [comment]
> It seems that the tutorial https://docs.dgl.ai/tutorials/models/1_gnn/1_gcn.html does NOT add the self loop, right?

Thank you for the report. This should be addressed in #1587 . @Ian09

**Comment by sneakerkg** [comment]
> In general it is still preferred to add `V` self loops in the data pre-processing steps. To add self loops in `GraphConv` can be wasteful as we are likely to add `V * L * E` self loops in total, where `L` is the number of `GraphConv` layers and `E` is the number of epochs. In this case, maybe we can leave a note in the documentation instead?

@mufeili I see your point. We need to try to avoid silent issue causing regression. Adding the option in GraphConv make it less likely to fail silently. Let's do a survey. Do you have examples that self-loop is not required in GCN? If there's a lot, then we don't add it in GCN. If almost every GCN model is using self-loop, let's add it in GraphConv Op. What do you think?
