### ISSUE TITLE
Detection of all zero or all one label when evaluate with roc_auc_score.

### ISSUE THREAD

**Issue by kexul** [dmlc/dgl#1572]
## 🚀 Feature
Detection of all zero or all one label when evaluate with roc_auc_score.

## Motivation
when the Label was all zero or all one, it would raise an error by roc_auc_score 
`ValueError: Only one class present in y_true. ROC AUC score is not defined in that case.`

## Alternatives

https://github.com/chemprop/chemprop/blob/0047bf489492e277334fefe8a3d4544da923073c/chemprop/train/evaluate.py#L48

**Comment by mufeili** [comment]
Hi, are you using `roc_auc_score` [here](https://github.com/dmlc/dgl/blob/master/apps/life_sci/python/dgllife/utils/eval.py#L236)?

**Comment by kexul** [comment]
@mufeili yes

**Comment by mufeili** [comment]
This should be addressed in #1581 , thanks.
