### ISSUE TITLE
Make edata['w'] learnable

### ISSUE THREAD

**Issue by unbreakablegao** [dmlc/dgl#1579]
Hi, 

I am wondering how I make the edge weight learnable. 

I tried this in SAGEConv as following:
1. In SAGEConv "__init__" I added: 
       if aggregator_type == 'gcn':
            self.g.edata['w'] = nn.Parameter(torch.randn(self.g.number_of_edges(), 1))

2. In "forward":
       graph = self.g.local_var()
       ... ...
       elif self._aggre_type == 'gcn':
            check_eq_shape(feat)
            graph.srcdata['h'] = feat_src
            graph.dstdata['h'] = feat_dst     # same as above if homogeneous
            graph.update_all(fn.u_mul_e('h', 'w', 'm'), fn.sum('m', 'neigh'))

but when I checked model.named_parameters(), self.g.edata['w'] is not shown in the learnable parameter set.

**Comment by VoVAllen** [comment]
Try this
```
self.etensor = nn.Parameter(torch.randn(self.g.number_of_edges(), 1))
self.g.edata['w'] = self.etensor
```

**Comment by unbreakablegao** [comment]
@VoVAllen  Wow, it worked!  Thank you so much!
