### ISSUE TITLE
Inconsistency in ndata of DGLGraph and DGLHeteroGraph

### ISSUE THREAD

**Issue by zheng-da** [dmlc/dgl#1582]
## 🐛 Bug

`DGLGraph`'s `ndata` always stores the tensors of the underlying framework, but `DGLHeterograph`'s `ndata` doesn't. As such, some of the APIs fails to run when a user passes a NumPy array to `DGLHeterograph`'s `ndata`

## To Reproduce

```
import dgl
import numpy as np
g = dgl.DGLGraph()
g.add_nodes(10)
g.add_edges([0, 1, 5, 8], [2, 8, 7, 1])
g.ndata['feat'] = np.ones((g.number_of_nodes()))
print(type(g.ndata['feat']))
g.readonly()
g = dgl.as_heterograph(g)
g.ndata['feat'] = np.ones((g.number_of_nodes()))
print(type(g.ndata['feat']))
g1 = dgl.batch_hetero([g, g])
```
The first print shows `<class 'torch.Tensor'>` while the second print shows `<class 'numpy.ndarray'>`. Because of this, `batch_hetero` fails.

## Environment

 - DGL Version (e.g., 1.0):
 - Backend Library & Version (e.g., PyTorch 0.4.1, MXNet/Gluon 1.3):
 - OS (e.g., Linux):
 - How you installed DGL (`conda`, `pip`, source):
 - Build command you used (if compiling from source):
 - Python version:
 - CUDA/cuDNN version (if applicable):
 - GPU models and configuration (e.g. V100):
 - Any other relevant information:

**Comment by BarclayII** [comment]
I guess a plausible resolution could be only allowing people to store tensors, while disallowing numpy ndarrays?

**Comment by VoVAllen** [comment]
My bad. The modification on DGLGraph is due to the dataset construction problem. To be framework agnostic, we use numpy array in the construction. However, at user side, users would expect to get backend tensors. Therefore I implicitly converted it into backend tensors to avoid tedious `F.zerocopy_from_numpy`. Maybe this is a bad practice

**Comment by zheng-da** [comment]
i would prefer the behavior of DGLGraph. when DGLHeteroGraph has a numpy tensor as node data, dgl.batch_hetero fails. i believe many operations on it will fail. why not convert numpy array to the framework array automatically?
