### ISSUE TITLE
dgl.dgmg Encounter problems？

### ISSUE THREAD

**Issue by WangYibucea** [dmlc/dgl#1591]
![image](https://user-images.githubusercontent.com/65903769/83809116-84459e80-a6e8-11ea-8c05-539d189aac9d.png)

The Encounter problems is  “Expect graph 0 and 1 to have the same node attributes when node_attrs=ALL, got {'hv', 'hg', 'a'} and {'hv', 'a'}.”

Why is there such a problem? How to deal with it？

**Comment by mufeili** [comment]
Hi, how did you encounter the problem? Did you just run `python main_batch.py`? Have you done any modification to our example code?

**Comment by WangYibucea** [comment]
yes,i just run the&nbsp;&nbsp;python main_batch.py.&nbsp; I never modify the example.




------------------&nbsp;原始邮件&nbsp;------------------
发件人: "Mufei Li"<notifications@github.com&gt;; 
发送时间: 2020年6月5日(星期五) 下午2:52
收件人: "dmlc/dgl"<dgl@noreply.github.com&gt;; 
抄送: "Mr.Pro"<1207918198@qq.com&gt;; "Author"<author@noreply.github.com&gt;; 
主题: Re: [dmlc/dgl] dgl.dgmg Encounter problems？ (#1591)





 
Hi, how did you encounter the problem? Did you just run python main_batch.py? Have you done any modification to our example code?

**Comment by VoVAllen** [comment]
What's your dgl version?

**Comment by WangYibucea** [comment]
0.4.3post2

**Comment by mufeili** [comment]
For a workaround, you can replace `dgl.batch(g_list)` with `dgl.batch(g_list, node_attrs=['hv', 'a'])`. Nevertheless, I cannot reproduce the issue by running `python main_batch.py`.

**Comment by WangYibucea** [comment]
thanks for your helpo(*￣▽￣*)ブ
