### ISSUE TITLE
RuntimeError: Expected object of device type cuda but got device type cpu for argument #1 'self' in call to _th_mm

### ISSUE THREAD

**Issue by jinserk** [dmlc/dgl#1594]
## ❓ Questions and Help

Before proceeding, please note that we recommend
using our discussion forum (https://discuss.dgl.ai) for
general questions. As a result, this issue will
likely be CLOSED shortly.

Hi,
I'm newbie of DGL, and try to make a working training model on it. 
I installed `dgl-cu102` using `pip`, but got an error as:
```
RuntimeError: Expected object of device type cuda but got device type cpu for argument #1 'self' in call to _th_mm
```
codes are based on [here](https://docs.dgl.ai/en/latest/tutorials/basics/4_batch.html)
Can I get any clue to resolve the above error? Thank you!

**EDIT**: it looks like `g.in_degrees()` doesn't return cuda tensor even though `g` is already in `cuda:0`. `graph.to(device)` has to be more consistent according to the its device.

**Comment by mufeili** [comment]
Hi, `graph.to(device)` only moves ndata/edata to the corresponding device. Besides, `in_degrees` is generated from the underlying adjacency list only when it is needed. So it is not a python tensor with the graph from the beginning.

**Comment by jinserk** [comment]
Thanks for the replying, @mufeili ! 
At least I understood what's wrong and how to workaround, but still doubt that any tensor generation from the graph need to be on the device where the graph is, i.e. `graph.in_degrees()` on the `cuda:0` need to give `tensor on cuda:0`.
