### ISSUE TITLE
Using GATConv on empty graph raises error in GPU setting

### ISSUE THREAD

**Issue by shuki-hpcnt** [dmlc/dgl#1598]
## 🐛 Bug

Using DGL + Pytorch.
Using GATConv on an empty graph (no edges) raises a `floating point exception (core dumped)` error and crashes. This error only appears when using GPUs.

## To Reproduce

```
import dgl
import torch as th
from dgl.nn.pytorch.softmax import edge_softmax
from dgl.nn.pytorch.conv import GATConv

g = dgl.DGLGraph()
g.add_nodes(4)

conv = GATConv(in_feats=2, out_feats=2, num_heads=1)
conv.to("cuda:0")

features = th.ones((4, 2)).to("cuda:0")
conv(g, features)
```

Using the interactive debugger, I'm assuming that the crash appears in this particular line in GATConv.
https://github.com/dmlc/dgl/blob/master/python/dgl/nn/pytorch/conv/gatconv.py#L146
```
            graph.apply_edges(fn.u_add_v('el', 'er', 'e'))
```

## Expected behavior

No crash.

## Environment

 - DGL Version (e.g., 1.0): 0.4.3.post2
 - Backend Library & Version (e.g., PyTorch 0.4.1, MXNet/Gluon 1.3): Pytorch 1.3.1
 - OS (e.g., Linux): Ubuntu 18.04
 - How you installed DGL (`conda`, `pip`, source): conda (`conda install -c dglteam dgl-cuda10.1`)
 - Build command you used (if compiling from source):
 - Python version: 3.6.10 
 - CUDA/cuDNN version (if applicable): CUDA 10.1,  cuDNN 7.6.5
 - GPU models and configuration (e.g. V100): Titan Xp
 - Any other relevant information:

**Comment by yzh119** [comment]
Hi @shuki-hpcnt the problem exist in our `edge_softmax` module, where the divisor is initialized as zeros, and if the graph has no edges we will divide the divident by zero, which results in this error.
I'll fix it by return a null tensor for graphs with no edges, thanks for your feedback.

**Comment by decoherencer** [comment]
we can close this. GATConv worked with empty graph on dgl 0.8
