### ISSUE TITLE
Cuda Error when dgl=0.43 is used

### ISSUE THREAD

**Issue by zerolxf** [dmlc/dgl#1606]
### Env
```
conda create -n dgl python=3.7 pip pytorch==1.2.0 torchvision==0.4.0 cudatoolkit=10.0
conda activate dgl
pip install --pre dgl-cu100
```

### Description
I have installed dgl-cu100 by pip.
When I run a demo, there is error about cuda.

demo.py
```
import torch
import dgl
import dgl.nn.pytorch as dglnn

a = torch.zeros((3,3)).to(0)
print(a)
sage = dglnn.SAGEConv(10,10,"mean").cuda()
print(sage)

```
output
> a = torch.zeros((3,3)).to(0)
  File "**/envs//lib/python3.7/site-packages/torch/cuda/__init__.py", line 178, in _lazy_init
    _check_driver()
  File "**/envs/lxf/lib/python3.7/site-packages/torch/cuda/__init__.py", line 99, in _check_driver
    http://www.nvidia.com/Download/index.aspx""")
AssertionError:
Found no NVIDIA driver on your system. Please check that you
have an NVIDIA GPU and installed a driver from
http://www.nvidia.com/Download/index.aspx

However, everything is fine if I run the following code.
```py
import torch

a = torch.zeros((3,3)).to(0)
print(a)
```
output
>tensor([[0., 0., 0.],
        [0., 0., 0.],
        [0., 0., 0.]], device='cuda:0')

In addition, the example graphsage [here](https://github.com/dmlc/dgl/blob/master/examples/pytorch/graphsage/train_sampling_unsupervised.py) seems to use api with 0.43, but 0.43 is not a stable version. This may cause problems for some people.

**Comment by VoVAllen** [comment]
Hi,

First you can try `import dgl` before `import torch`. If this doesn't work, please uninstall dgl and use `conda install -c dglteam dgl-cuda10.0`. The principle is if you use conda install torch, you need to install dgl using conda also, vice versa.

**Comment by zerolxf** [comment]
Thanks for your reply.

'import dgl' before 'import torch' does not work, and 'conda install -c dglteam dgl-cuda10.0'  can solve the above problem. However, I can not install dgl=0.43 by conda.

(p.s. I also install dgl with source code, but not works. )

**Comment by VoVAllen** [comment]
Which version did you get with ` 'conda install -c dglteam dgl-cuda10.0'`?

**Comment by zerolxf** [comment]
Sorry, I just checked it, and the version I got is 0.43.
