### ISSUE TITLE
NeighborSampler for Heterograph 

### ISSUE THREAD

**Issue by Ian09** [dmlc/dgl#1610]
## 🚀 Feature
NeighborSampler dose not support heterograph

## Motivation

The Heterograph might also be very large and It is desirable to use Neighbor sampling to make it trainable. The current Neighbor sampler does not support heterograph, and it will be great if it support Heterograph.

**Comment by classicsong** [comment]
Here is an example of doing neighbor sampling on  heterograph:
https://github.com/dmlc/dgl/blob/57d111f9e521a1adbc0c47236f6190c87b569ccf/examples/pytorch/rgcn-hetero/entity_classify_mb.py#L37-L51

**Comment by Ian09** [comment]
> Here is an example of doing neighbor sampling on heterograph:
> https://github.com/dmlc/dgl/blob/57d111f9e521a1adbc0c47236f6190c87b569ccf/examples/pytorch/rgcn-hetero/entity_classify_mb.py#L37-L51

Thanks! I will have a look.
