### ISSUE TITLE
Testing models on DGLHeteroGraph with features

### ISSUE THREAD

**Issue by bioannidis** [dmlc/dgl#1628]
## 🚀 Feature
I suggest we include in the basic set of datasets for heterogenous graphs e.g. AIFB, some datasets that some node types have node features. This way we can test the developed model we provide and verify they behave appropriately on these featured graphs.  We will avoid bugs this way. Some of such graphs are the IMDB, OAG, and other. This is also related to this PR https://github.com/dmlc/dgl/pull/1516/files.

**Comment by classicsong** [comment]
We are working on that. #1629
