### ISSUE TITLE
why is there no documents about how to generate a valid dataset

### ISSUE THREAD

**Issue by Muggle-Du** [dmlc/dgl#1632]

**Comment by jermainewang** [comment]
Hi, you could take a look at the [citation graph dataset](https://github.com/dmlc/dgl/blob/master/python/dgl/data/citation_graph.py). Although it borrows many codes from Kipf's original repo, the basic structure is applicable to other cases. Essentially, you

1. Download or load data from files.
1. Construct a DGLGraph object and save the node/edge features into it via `ndata` and `edata`.
1. Save it as the member of your dataset class, so you can get it via `dataset.graph`, for example.

If you have more questions, welcome to our [discuss forum](https://discuss.dgl.ai) for further discussion.
