### ISSUE TITLE
Sample_neighbors not supports the general graph, like dgl.DGLGraph

### ISSUE THREAD

**Issue by zerolxf** [dmlc/dgl#1640]
## 🚀 Feature
Neighbor sampling APIs:Sample_neighbors in [source](https://github.com/dmlc/dgl/blob/master/python/dgl/sampling/neighbor.py#L14) only supports DGLHeteroGraph. It would be better if it can compatible with general graph, like dgl.DGLGraph().

## Motivation
I try to sample the neighbors by using dgl.sampling.sample_neighbor(). However, sample_neighbor only supports DGLHeteroGraph. If I use the general graph like dgl.DGLGraph(), there will be some compatibility errors.

>File "xxx/envs/dgl/lib/python3.7/site-packages/dgl/sampling/neighbor.py", line 53, in sample_neighbors
    if len(g.ntypes) > 1:
AttributeError: 'DGLGraph' object has no attribute 'ntypes'

**Comment by VoVAllen** [comment]
We are planning to deprecate DGLGraph in the future. You can use `dgl.as_heterograph(dglgraph)` to convert a DGLGraph to DGLHeteroGraph. The design of DGLHeteroGraph is to be 100% compatible with original DGLGraph.

**Comment by zerolxf** [comment]
Thanks for your reply, which helps me a lot.

If you are planning to deprecate DGLGraph in the future, it is better to remind the readers in the relevant documents or update them with DGLHeteroGraph, e.g. [basic tutorials](https://docs.dgl.ai/en/0.4.x/tutorials/basics/2_basics.html).

**Comment by VoVAllen** [comment]
Thanks for your suggestion. We are planning a huge refactoring including the current documentations.
