### ISSUE TITLE
module not found error 

### ISSUE THREAD

**Issue by pournami123** [dmlc/dgl#1649]
## To Reproduce

1.
1.
1.

## Environment

 - DGL Version (e.g., 1.0):
 - Backend Library & Version (e.g., PyTorch 0.4.1, MXNet/Gluon 1.3):
 - OS (e.g., Linux):
 - How you installed DGL (`conda`, `pip`, source):
 - Build command you used (if compiling from source):
 - Python version:
 - CUDA/cuDNN version (if applicable):
 - GPU models and configuration (e.g. V100):
 - Any other relevant information:

**Comment by pournami123** [comment]
I am having a tensorflow.10 version with cuda 9.0.m I installed dgl using the command 'conda install -c dglteam dgl-cuda9.0'. install was successful. When I treid to import dgl I am getting ModuleNotFoundError: No module named 'torch' error. Such Pytorch be also installed alongside tensorflow

**Comment by VoVAllen** [comment]
Hi you can set environment variable `DGLBACKEND=tensorflow`, or execute `python -m dgl.backend.set_default_backend tensorflow`

**Comment by VoVAllen** [comment]
And we required tf>=2.1

**Comment by pournami123** [comment]
oh... ok thanks you.. will try that

**Comment by ShivaniNR** [comment]
Hi,
How did you solve the issue?

**Comment by cappadavide** [comment]
I'm facing this issue as well
@ShivaniNR have you solved it?
