### ISSUE TITLE
Creating a graph store with Heterograph

### ISSUE THREAD

**Issue by dewang23** [dmlc/dgl#1655]
## ❓ Questions and Help

Hi, I am trying to perform distributed training of r-gcn for link prediction. For this, I am creating a graph store, but it does not support heterogeneous graphs -> https://docs.dgl.ai/en/0.4.x/api/python/graph_store.html#construct-a-graph-store

To perform distributed training, I am referring to the following link -> https://docs.dgl.ai/en/0.4.x/tutorials/models/5_giant_graph/2_giant.html

From this link, I understand that first step would be to create a graph store, but dgl.DGLHeterograph cannot be used.

Are there any alternative ways to create graph store using heterograph, or any alternative methods to perform distributed training?

**Comment by aksnzhy** [comment]
@dewang23  Hi, the full pipeline of distributed training will be supported in the next version. Please notice our release news. Thanks!

**Comment by dkalim** [comment]
Hi Team,
Can you let me know any tentative timeline for the next release?
