### ISSUE TITLE
Adding node with data dictionary of different sizes

### ISSUE THREAD

**Issue by roholazandie** [dmlc/dgl#1658]
## 🚀 Feature
Is there any specific reason why in adding nodes we can't use different sizes for data dictionary? I try to add two features to each node in the graph like:
```
graph.add_nodes(1, {"embedding": entity_dict[entity_id]["embedding"], "text_ids": entity_dict[entity_id]["text_ids"]})
```
But I get the following error:
```
dgl._ffi.base.DGLError: Expected all columns to have same # rows (1), got 3 on 'text_ids'.
```
Can you please let me know if there is any way around this and if not Is it possible to add it as a feature in future?

**Comment by BarclayII** [comment]
The features in the dictionary must have the same number of rows as the number of nodes you add.  Could you check whether the size of the first axis of `entity_dict[entity_id]['text_ids']` is 1?

**Comment by pbonazzi** [comment]
I have got the same error when trying to build an homogeneous graph inside a for loop. 

This code reproduces the error. 
`
g = dgl.DGLGraph()
ids = 1
global_id = 100
dimension = [1, 2, 3]
g = dgl.add_nodes(g, 1, {'id': torch.tensor([ids]),
                                                       "global_id": torch.tensor([global_id]), 
                                                       "dimension": torch.tensor(dimension)})
`

**Comment by pbonazzi** [comment]
A work around I have found is to build your graph only with features that have the same dimensions. At the same time append the other features in a list (list_feature) . Finally, when the graph is build, do `g.ndata["feature_name"] = tensor.torch(list_feature)`
