### ISSUE TITLE
Could there be an example using GAT directly from adj_list, labels and node feature matrix?

### ISSUE THREAD

**Issue by alexucb** [dmlc/dgl#1666]
## 🚀 Feature
Train GAT directly from adjlist, labels and node features

## Motivation

Right now there is an existing example showing how to use dgl gat for training on multiple graphs, such as Protein-protein interaction (PPI) networks dataset. see code below:
https://github.com/dmlc/dgl/blob/0.4.x/examples/pytorch/gat/train_ppi.py

However, I was wondering whether there is some example could help us to build the graph/features/labels/mask_list directly from adj_list and original labels?

say we have adj_list as:
{0: [3, 1], 1: [5, 2], 2: [6], 3: [8, 4], 4: [9, 5], 5: [9, 6], 6: [14, 7], 7: [15], 8: [12, 9]} 9: [12, 10], 10: [13, 11], 11: [13, 14], 12: [20, 13], 13: [21, 14], 14: [19, 15], 15: [19], 16: [35, 17], 17: [32, 18], 18: [32, 19], 19: [32], 20: [25, 21], 21: [27, 22], 22: [28, 23], 23: [28, 24], 24: [28, 16], 25: [29, 26], 26: [29, 27], 27: [54, 28], 28: [30], 29: [36, 30], 30: [37, 31], 31: [37, 32], 32: [44], 33: [38, 34], 34: [43, 35], 35: [43], 36: [52, 38], 37: [55, 38], 38: [41, 39], 39: [41, 40], 40: [42, 43], 41: [59, 42], 42: [61, 43], 43: [62, 44], 44: [47, 45], 45: [48, 46], 46: [48], 47: [147, 48], 48: [49], 49: [50], 50: [51], 52: [63, 53], 53: [63, 54], 54: [63, 55], 55: [64, 56], 56: [65, 57], 57: [65, 58], 58: [65, 59], 59: [65, 60], 60: [65, 61], 61: [71, 62], 62: [71], 63: [66, 64], 64: [67, 65], 65: [67], 66: [68, 67], 67: [69], 68: [70, 69], 69: [71], 70: [72, 71], 71: [73], 72: [74, 73], 73: [75], 74: [76, 75], 75: [77], 76: [81, 77], 77: [82, 78], 78: [95, 79], 79: [96, 80], 80: [97], 81: [85, 82], 82: [86, 83], 83: [87, 84], 84: [88], 85: [89, 86], 86: [89, 87], 87: [91, 88], 88: [92], 89: [100, 90], 90: [100, 91], 91: [101, 92], 92: [102, 93], 93: [103, 94], 94: [103, 95], 95: [105, 96], 96: [106, 97], 97: [106, 98], 98: [107, 99], 99: [108], 100: [109, 101], 101: [111, 102], 102: [112, 103], 103: [113, 104], 104: [115, 105], 105: [115, 106], 106: [117, 107], 107: [142, 108], 108: [143], 109: [119, 110], 110: [120, 111], 111: [121, 112], 112: [121, 113], 113: [122, 114], 114: [124, 115], 115: [125, 116], 116: [126, 117], 117: [127, 118], 118: [127], 119: [128, 120], 120: [129, 121], 121: [130, 122], 122: [130, 123], 123: [135, 124], 124: [135, 125], 125: [139, 126], 126: [140, 127], 127: [140], 128: [131, 129], 129: [132, 130], 130: [133], 131: [136, 132], 132: [137, 133], 133: [137, 134], 134: [138, 135], 135: [138], 136: [137], 137: [138], 138: [139], 139: [140], 140: [141], 141: [142], 142: [143], 143: [144], 144: [145], 145: [146], 146: [147]}
...assuming there are 9 other similar adj_lists. for simplicity I just list one

and labels:
[1, 2, 3, 4, 5, 6, 0, 0, ....] in which the first 6 nodes have labels as listed and the rest as 0.
...assuming there are 9 other label lists. for simplicity I just list one

and node features:
assume each node has feature vector with shape of <1, fixed_feature_dim=100>

## Alternatives
one work around that might work is to convert above adj_list, node_feature and labels to PPI dataset .json and .npy format. but it could have a lot of overhead in converting data back and forth.

## Pitch
the goal is directly apply dgl gat on adj_list, node features and labels.

## Additional context
None

**Comment by yzh119** [comment]
Hi @alexucb , you can build a DGLGraph from the `adj_list` and assign the label as node features, e.g.
```
g = dgl.DGLGraph()
g.add_nodes(148)  # in your case there are 148 nodes in total. 
for v, neigh in adj_list.items():  # suppose adj_list is given in the format you mentioned.
    for j in neigh:
        g.add_edge(v, j)
```
and then use the graph as the input to your GNN model.

You don't actually need to convert the data to `.json` and `.npy` format that PPIDataset required, they are only used to load standard dataset. In your case, what you need only is a DGLGraph, just build a graph in the way I just described is okay.
