### ISSUE TITLE
Confusion about removing nodes and edges

### ISSUE THREAD

**Issue by jacobma-create** [dmlc/dgl#1670]
## 📚 Documentation

(1) In this webpage:  https://docs.dgl.ai/en/0.4.x/api/python/graph.html
There is a statement:
NOTE: Removing nodes and edges is not supported by DGLGraph.

(2) Also this webpage: https://docs.dgl.ai/en/0.4.x/tutorials/basics/2_basics.html
There is a statement:
Nodes and edges can be added but not removed.

However, the edges and nodes can be removed by using methods:

DGLGraph.remove_nodes(*args, **kwargs)
DGLGraph.remove_edges(*args, **kwargs)

Is there anything wrong with the document, or I misunderstand anything? Thanks.

**Comment by yzh119** [comment]
Sorry about the confusion, we have fixed the problem before but you can only see the changes in the latest version of documentation: https://docs.dgl.ai/en/latest/ (you are viewing the 0.4.x branch).
