### ISSUE TITLE
Tree-LSTM

### ISSUE THREAD

**Issue by GouthamanAsokan** [dmlc/dgl#1691]
I was going through the code for Tree-LSTM in the dgl site,I was not able to understand the 2 lines of code mentioned below and why the use of 'view' and *, and what is the purpose of structuring nodes.mailbox in this particular way

# concatenate h_jl for equation (1), (2), (3), (4)
h_cat = nodes.mailbox['h'].view(nodes.mailbox['h'].size(0), -1)
f = th.sigmoid(self.U_f(h_cat)).view(*nodes.mailbox['h'].size())

**Comment by jermainewang** [comment]
Duplicate of https://discuss.dgl.ai/t/tree-lstm-nodes-mailbox/1065/2.
