### ISSUE TITLE
Mini-batch evaluation for R-GCN

### ISSUE THREAD

**Issue by Riroaki** [dmlc/dgl#1695]
## ❓ Questions and Help

I often met CPU out of memory during the link prediction training process for R-GCN (https://github.com/dmlc/dgl/blob/master/examples/pytorch/rgcn/link_predict.py), and I wonder how can I do evaluation using smaller batches?

A similar issue is discussed here, and the code of hetero-graph using neighbor sampling is hard to understand...
https://discuss.dgl.ai/t/r-gcn-run-time-error-during-evaluation/564

**Comment by classicsong** [comment]
We will handle it in #1629
