### ISSUE TITLE
[Question]: Personalized Page Rank 

### ISSUE THREAD

**Issue by sidhantwadhwani** [dmlc/dgl#1699]
Does DGL has Personalized Pagerank. I managed to find the method in DGL for pagerank, but when i analysed the code, there was nothing related to personlaized page rank. Can you provide any guidance with the implementation of Personalised Pagerank on top of DGL.

**Comment by mufeili** [comment]
You may find our [example of APPNP](https://github.com/dmlc/dgl/tree/f99725adbc9cef2fd6cc6eef18a86e3d7c1e5339/examples/pytorch/appnp) helpful.
