### ISSUE TITLE
gcn tensorflow example: GCN not found

### ISSUE THREAD

**Issue by RamonBeast** [dmlc/dgl#1740]
Hello, 

I'm trying to run the GCN example that uses tensorflow from [here](https://github.com/dmlc/dgl/blob/master/examples/tensorflow/gcn/train.py). I've installed everything using ``pip`` on Linux (on MacOS there seems to be no available ``tfdlpack`` package so I can't run it), I'm using:

- dgl 0.4.3.post2
- tensorflow-gpu 2.2.0

This is the error I get:

``Using backend: tensorflow
Traceback (most recent call last):
  File "train.py", line 8, in <module>
    from gcn import GCN
ModuleNotFoundError: No module named 'gcn'``

What else am I missing to be able to run the example?
Thank you for any help and for creating this great project.

**Comment by knightXun** [comment]
I meet this problem too. @RamonBeast how do you solve this?

**Comment by VoVAllen** [comment]
@knightXun Hi, Do you meet the problem of no module named `gcn` or `tfdlpack` not found?

**Comment by knightXun** [comment]
@VoVAllen i fixed this already
