### ISSUE TITLE
Error in GraphSage Pytorch example

### ISSUE THREAD

**Issue by wangxiaoyunNV** [dmlc/dgl#1757]
## 🐛 Bug

I try to run 
`python3 train_sampling_multi_gpu.py --num-epochs 30    # neighbor sampling with multi GPU
`
I got error message
`Traceback (most recent call last):
  File "train_sampling_multi_gpu.py", line 293, in <module>
    run(0, n_gpus, args, devices, data)
  File "train_sampling_multi_gpu.py", line 170, in run
    sampler = dgl.sampling.MultiLayerNeighborSampler(
AttributeError: module 'dgl.sampling' has no attribute 'MultiLayerNeighborSampler'`
## To Reproduce

1.python3 train_sampling_multi_gpu.py --num-epochs 30  
1.
1.

## Expected behavior

It should not give me any errors
## Environment

 - DGL Version (e.g., 1.0): '0.4.3post2'
 - Backend Library & Version (e.g., PyTorch 0.4.1, MXNet/Gluon 1.3): PyTorch 1.5
 - OS (e.g., Linux): Linux
 - How you installed DGL (`conda`, `pip`, source): Conda
 - Build command you used (if compiling from source):
 - Python version: 3.7.7
 - CUDA/cuDNN version (if applicable): cuda11
 - GPU models and configuration (e.g. V100):
 - Any other relevant information:

**Comment by classicsong** [comment]
Can you try the nighly-build?
