### ISSUE TITLE
Does GCN support batch size?

### ISSUE THREAD

**Issue by cfangplus** [dmlc/dgl#1767]
## ❓ Questions and Help

Hi，

I found that the demo program of GCN does not provide batch size parameter so I have to load all data into device and  if device only contain one GPU with small memory then the training would be failed. So does GCN algorithm support batch size?  Or just DGL implement does not support it yet? thx.

**Comment by classicsong** [comment]
You need to implement mini-batch based GCN.
Here is the example of mini-batch based GraphSage: https://github.com/dmlc/dgl/blob/master/examples/pytorch/graphsage/train_sampling_multi_gpu.py

**Comment by cfangplus** [comment]
Seems GraphSage works when we sampled only part of its neighbors, however, GCN needs to sample all of one's neighbors because we need to compute the degree number from its neighbors. And sampling all the neighbors for the batch entities would costs too much time, also we need to sample again for the next batch. So I think maybe one operation that could sample neighbors, compute and store the degree numbers for all entity is admirable. Is that right?

**Comment by classicsong** [comment]
Currently, our GCN nn module use the subgraph's degree number.
https://github.com/dmlc/dgl/blob/5c92f6c21855c3f7bd90f3ace1a4ec89d36a87f7/python/dgl/nn/pytorch/conv/graphconv.py#L139-L144

You can also compute and store the degree numbers for all entity. As in our relation graph conv module, we store norm value in edge features:
https://github.com/dmlc/dgl/blob/5c92f6c21855c3f7bd90f3ace1a4ec89d36a87f7/python/dgl/nn/pytorch/conv/relgraphconv.py#L210-L214

**Comment by Wufang1997** [comment]
this is so inconvenient. I just don't understand why GCN cannot support the batch size.

**Comment by jermainewang** [comment]
@Wufang1997  This is an old issue and we shall close it. If you have specific question about batched graph and NN module. Please open a new issue. Thanks!
