### ISSUE TITLE
How to paritition 1TB graph data?

### ISSUE THREAD

**Issue by cozilla** [dmlc/dgl#1774]
## ❓ Questions and Help

Before proceeding, please note that we recommend
using our discussion forum (https://discuss.dgl.ai) for
general questions. As a result, this issue will
likely be CLOSED shortly.

**Comment by cozilla** [comment]
how to partition 1TB graph data? how to start graph store in multiple machines?

**Comment by aksnzhy** [comment]
@cozilla We will release distributed training in the next version: https://github.com/dmlc/dgl/issues/930. Please follow our latest news. Thanks!

**Comment by VoVAllen** [comment]
Hi there's distributed metis partition library you can use, or use random partition for graph too large. Or you can consider aws's largest machine with 24TB memory

**Comment by cozilla** [comment]
thanks :)
