### ISSUE TITLE
[dgl.sampling.sample_neighbors]  fanout= -1 does not work

### ISSUE THREAD

**Issue by snash4** [dmlc/dgl#1777]
## To Reproduce
The documentation dgl.sampling.sample_neighbors lists that setting fanout=-1 returns all neighbors of a node. But this throws core dump error 'terminate called after throwing an instance of 'std::bad_alloc''

1. Create a sample dgl graph
example_graph_nx = nx.Graph(
    [(0, 2), (0, 4), (0, 6), (0, 7), (0, 8), (0, 9), (0, 10),
     (1, 2), (1, 3), (1, 5), (2, 3), (2, 4), (2, 6), (3, 5),
     (3, 8), (4, 7), (8, 9), (8, 11), (9, 10), (9, 11)])

2.  Try to get all neighbors of a node
sampled_node_batch = torch.LongTensor([0])
sampled_graph = dgl.sampling.sample_neighbors(example_graph,sampled_node_batch,-1)

## Expected behavior

Following the documentation of dgl.sampling.sample_neighbors on github, setting fanout=-1, it should return all the neighbors of a sampled node.

**Comment by BarclayII** [comment]
-1 is introduced in recent master/nightly builds after 0.4.3post2.  What was your DGL version?

If it's 0.4.3post2 or earlier, please install the nightly build by

```
pip install --pre dgl
```
or
```
pip install --pre dgl-cuXX
```
for GPUs.

**Comment by snash4** [comment]
ok thanks.
