### ISSUE TITLE
multi GPU training

### ISSUE THREAD

**Issue by trinayan** [dmlc/dgl#1787]
## ❓ Questions and Help

Hi,

I am a GPU systems and architecture researcher looking at using your suite for multi-GPU study. I looked at the examples and it seems a few of them have multi-GPU support while the others do not at the moment.

Is it because the other models do not benefit from multi-GPU or do you plan to add it later?. As pytorch recommends using distributed training instead of data parallel, is it simple for a user to modify the provided DGL examples to use distributed training or is it a complex process?. Thanks for the information.

Best,
Trinayan

**Comment by mufeili** [comment]
> ## ❓ Questions and Help
> Hi,
> 
> I am a GPU systems and architecture researcher looking at using your suite for multi-GPU study. I looked at the examples and it seems a few of them have multi-GPU support while the others do not at the moment.
> 
> Is it because the other models do not benefit from multi-GPU or do you plan to add it later?. As pytorch recommends using distributed training instead of data parallel, is it simple for a user to modify the provided DGL examples to use distributed training or is it a complex process?. Thanks for the information.
> 
> Best,
> Trinayan

Hi Trinayan,

I think the examples are presented in a relatively casual fashion. For examples without multi-GPU support, it can be the case that the gain of multi-gpu support is relatively small compared with the implementation effort or simply people did not add that. Most likely we will not add multi-GPU support for those examples unless we are convinced about the potential gain. Personally I had some experience of adding multi-GPU support to DGL models with distributed training and I did not find it very hard. 

Best,

Mufei

**Comment by trinayan** [comment]
Is it a matter of wrapping your models  just with DistributedDataParallel or are there other things that need to be taken care of ?. I am not really looking for the most efficient multi-GPU optimization to be clear. Thanks for the help

**Comment by aksnzhy** [comment]
@trinayan Hi, actually training GNN models across multiple GPUs is a little bit different from traditional data-parallel training like image classification. For image classification, we only have the dense model parameters that should be learned by parameter server or Allreduce. But in GNN training, we also have sparse embedding and node features that could beyond the capability of a single GPU. The users' tasks are different and their demand also different. Now we are trying to define a set of general API for large-scale GNN training across multi-GPUs, multi-core, and distributed settings, which will be released in the next version. Please let us know if you have any good ideas for that. Thanks!
