### ISSUE TITLE
RuntimeError: Expected object of backend CPU but got backend CUDA

### ISSUE THREAD

**Issue by bjascob** [dmlc/dgl#1805]
## 🐛 Bug

When training `examples/pytorch/graphwriter`, I'm failing after completing a random number of epochs with the message
`RuntimeError: Expected object of backend CPU but got backend CUDA for sequence element 16 in sequence argument at position #1 'tensors'`
I'm running the training on a 12GB GPU which is obviously being utilized during the initial epochs so I'm not sure why it's expecting the data to be allocated to the CPU.  The fact that this is only happening after several hours and a random N epochs, makes it difficult to troubleshoot.

## To Reproduce

1. Perpare the data as described in the Readme for  `examples/pytorch/graphwriter`
2. Run the training per the Readme

## Stack trace

...
Train Ep 6: 1714it [18:58,  1.51it/s, loss=3.44]                                                    
Train Ep  6 AVG Loss  3.436203928870603 Steps  38720.0 Time  1138.5625348091125 GPU 10.73828125
Eval Ep 6: 100%|█████████████████████████████████████████| 32/32 [00:08<00:00,  3.62it/s, loss=3.64]
Eval Ep  6 AVG Loss  3.635833351135254 Steps  1000.0 Time  8.850606441497803
Saving best model  Ep  6  loss  3.635833351135254
Train Ep 7:  72%|██████████████████████████▋          | 871/1210 [11:11<04:21,  1.30it/s, loss=3.45]
Traceback (most recent call last):
  File "./10_Train.py", line 22, in <module>
    train.main(args)
  File "/home/bjascob/Files/Projects/AMR/031_DGL_GraphWriter/lib/graphwriter/train.py", line 109, in main
    train_one_epoch(model, train_dataloader, optimizer, args, epoch)
  File "/home/bjascob/Files/Projects/AMR/031_DGL_GraphWriter/lib/graphwriter/train.py", line 21, in train_one_epoch
    for batch in tq:
  File "/home/bjascob/.local/lib/python3.6/site-packages/tqdm/std.py", line 1102, in __iter__
    for obj in iterable:
  File "/usr/local/lib/python3.6/dist-packages/torch/utils/data/dataloader.py", line 346, in __next__
    data = self.dataset_fetcher.fetch(index)  # may raise StopIteration
  File "/usr/local/lib/python3.6/dist-packages/torch/utils/data/_utils/fetch.py", line 47, in fetch
    return self.collate_fn(data)
  File "/home/bjascob/Files/Projects/AMR/031_DGL_GraphWriter/lib/graphwriter/utils.py", line 279, in batch_fn
    batch_graph = dgl.batch(batch_graph)
  File "/usr/local/lib/python3.6/dist-packages/dgl/graph.py", line 4189, in batch
    for key in node_attrs}
  File "/usr/local/lib/python3.6/dist-packages/dgl/graph.py", line 4189, in <dictcomp>
    for key in node_attrs}
  File "/usr/local/lib/python3.6/dist-packages/dgl/backend/pytorch/tensor.py", line 141, in cat
    return th.cat(seq, dim=dim)
RuntimeError: Expected object of backend CPU but got backend CUDA for sequence element 16 in sequence argument at position #1 'tensors'

## Environment

 - DGL Version: dgl-cu100  0.4.3.post2
 - Backend: Library & Version: torch 1.2.0
 - OS (e.g., Linux):  Ubuntu 18.04
 - How you installed DGL: `sudo -H pip3 install dgl-cu100`
 - Build command you used (if compiling from source): N/A
 - Python version: 3.6.9
 - CUDA/cuDNN version:  Cuda 10.0 (libcudnn.so.7.3.1)
 - GPU models and configuration:  GeForce GTX TITAN X (12GB memory)

## Additional context

It's confusing to me that it runs for a random number of epochs before it fails.  Could this be a memory allocation problem?  The error message doesn't look like that and the dataset doesn't appear to be that large with only a batch size of 32.  My card has 12GB.

Any thoughts on where to look / what to try, would be appreciated.

**Comment by bjascob** [comment]
I added `export CUDA_VISIBLE_DEVICES=0` to my .bashrc file and was able to complete the 20 epochs for training.
I'm not sure why this makes a difference since there is an `args.device`  which sets the location for model and data in the code.
I also don't understand why this is intermittently causing crashes at the start of an epoch.
If you have any thoughts, please post.  I still think there's a bug somewhere but it looks like I have my issue solved for now so I'll close this if no one has additional input.

**Comment by QipengGuo** [comment]
Thanks for reporting this. It's a bug, and I am still checking the code. It seems the beam search process in g2t_model.py causes this error, but I still need some time to debug because it's really hard to reproduce.

**Comment by QipengGuo** [comment]
Finally, I found a bug in the code. I am not sure it's the reason of this error because I haven't reproduced the same error. But I found a related error. After some epochs of training, the model may output the nan in the inference mode (you can add epsilon to the copy gate and softmax to avoid this), and the pytorch has a bug of [using topk with nan](https://github.com/pytorch/pytorch/issues/16762) in the lower version. As a result, the topk function returns some random integers. And the solution is simple, add some epsilon or update your pytorch version. I have tested pytorch 1.5.1, and it works fine.
