### ISSUE TITLE
When I installed from source, the following erros occurred:

### ISSUE THREAD

**Issue by ZM7** [dmlc/dgl#1806]
## ❓ Questions and Help
When performing  'cmake -DUSE_CUDA=ON ..'，the following erros occurred:
![image](https://user-images.githubusercontent.com/26395667/87499844-c1109800-c68d-11ea-9d16-dc414ef20f42.png)

**Comment by yzh119** [comment]
It seems cublas is not found, have you installed culabs correctly?

**Comment by ZM7** [comment]
> cublas
I use this method to verify whether I have installed cublas.
![image](https://user-images.githubusercontent.com/26395667/88447508-aea11600-ce66-11ea-906c-c4e29e23004e.png)
Besides, I can use pip to install, but I am not sure whether pip can install the nightly version.
