### ISSUE TITLE
graph.device not updated

### ISSUE THREAD

**Issue by yifeim** [dmlc/dgl#1829]
## 🐛 Bug

If I do `G.to(torch.device('cuda:0')).device`, it will still show `cpu`.

## Environment

 - DGL Version (e.g., 1.0): `dgl-cu100==0.5a200712`
 - Backend Library & Version (e.g., PyTorch 0.4.1, MXNet/Gluon 1.3): `torch==1.4.0`
 - OS (e.g., Linux): amazon linux
 - How you installed DGL (`conda`, `pip`, source): `pip install --pre dgl-cu100`
 - Build command you used (if compiling from source):
 - Python version: `p36`
 - CUDA/cuDNN version (if applicable): `cu100`
 - GPU models and configuration (e.g. V100): `V100`
 - Any other relevant information: `conda_pytorch_p36`

**Comment by classicsong** [comment]
try G = G.to(torch.device('cuda:0'))

**Comment by yifeim** [comment]
Sorry, this does not address my original question, which is
```
print(G.to(torch.device('cuda:0')).device)
# result shows cpu
```

**Comment by classicsong** [comment]
This is fixed in master branch.
Please try the nightly-build.
