### ISSUE TITLE
Expect graph have the same node attributes

### ISSUE THREAD

**Issue by HTian1997** [dmlc/dgl#1831]
## 🐛 Bug

ValueError: Expect graph 0 and 12 to have the same node attributes when node_attrs=ALL, got {'label'} and set().

I have checked that all nodes in graphs dataset have the same feature of 'label'. The ValueError happens sometimes but not always.

## Environment

 - DGL Version (e.g., 1.0): 0.4.3.post2
 - Backend Library & Version (e.g., PyTorch 0.4.1, MXNet/Gluon 1.3): 1.5.1
 - OS (e.g., Linux): MacOS
 - How you installed DGL (`conda`, `pip`, source): pip
 - Python version: 3.6.10

**Comment by VoVAllen** [comment]
Hi,

Could you post your code(or part of it) here? It's hard to for us to give advices only with the error message

**Comment by HTian1997** [comment]
> Hi,
> 
> Could you post your code(or part of it) here? It's hard to for us to give advices only with the error message

Sorry, please see the following code:

Construct graphs:
```python3
g = dgl.DGLGraph((u, v))
g.ndata['label'] = node_feature
```

Split graphs with corresponding labels (binary classification) into `trainset` and `testset`.

Train on `trainset`:
```python3
data_loader = DataLoader(trainset, batch_size=16, shuffle=True, collate_fn=collate)
model = Classifier(1, 256, 2)
loss_func = nn.CrossEntropyLoss()
optimizer = optim.Adam(model.parameters(), lr=0.0001)
model.train()


epoch_losses = []
for epoch in range(50):
    epoch_loss = 0
    for iter, (bg, label) in enumerate(data_loader):
        prediction = model(bg)
        loss = loss_func(prediction, label)
        optimizer.zero_grad()
        loss.backward()
        optimizer.step()
        epoch_loss += loss.detach().item()
    epoch_loss /= (iter + 1)
    print('Epoch {}, loss {:.4f}'.format(epoch, epoch_loss))
    epoch_losses.append(epoch_loss)
```

I tried to rule out graphs with different node attribute, but there is none. 
```python3
count = 0
for item in graphs:
    if type(item[0].node_attr_schemes()) == dict:
        graph.append(item[0])
        label.append(item[1])
    else:
        count += 1

print("failed graph: ", count)
# output: failed graph:  0
```

**Comment by HTian1997** [comment]
Never mind, to detect not qualified graph, it should be 

```python3
graph.node_attr_schemes() != {}
```
