### ISSUE TITLE
AttributeError: module 'dgl' has no attribute 'DGLGraph' raised when following DGL at a glance tutorial

### ISSUE THREAD

**Issue by rgee3894** [dmlc/dgl#1832]
## To Reproduce

1. Type and run the following code

```
import dgl
import numpy as np

def build_karate_club_graph():
    # All 78 edges are stored in two numpy arrays. One for source endpoints
    # while the other for destination endpoints.
    src = np.array([1, 2, 2, 3, 3, 3, 4, 5, 6, 6, 6, 7, 7, 7, 7, 8, 8, 9, 10, 10,
        10, 11, 12, 12, 13, 13, 13, 13, 16, 16, 17, 17, 19, 19, 21, 21,
        25, 25, 27, 27, 27, 28, 29, 29, 30, 30, 31, 31, 31, 31, 32, 32,
        32, 32, 32, 32, 32, 32, 32, 32, 32, 33, 33, 33, 33, 33, 33, 33,
        33, 33, 33, 33, 33, 33, 33, 33, 33, 33])
    dst = np.array([0, 0, 1, 0, 1, 2, 0, 0, 0, 4, 5, 0, 1, 2, 3, 0, 2, 2, 0, 4,
        5, 0, 0, 3, 0, 1, 2, 3, 5, 6, 0, 1, 0, 1, 0, 1, 23, 24, 2, 23,
        24, 2, 23, 26, 1, 8, 0, 24, 25, 28, 2, 8, 14, 15, 18, 20, 22, 23,
        29, 30, 31, 8, 9, 13, 14, 15, 18, 19, 20, 22, 23, 26, 27, 28, 29, 30,
        31, 32])
    # Edges are directional in DGL; Make them bi-directional.
    u = np.concatenate([src, dst])
    v = np.concatenate([dst, src])
    # Construct a DGLGraph
    return dgl.DGLGraph((u, v))

G = build_karate_club_graph()
print('We have %d nodes.' % G.number_of_nodes())
print('We have %d edges.' % G.number_of_edges())
```
2. The following stack trace was displayed
```
Traceback (most recent call last):
  File "dgl.py", line 1, in <module>
    import dgl
  File "/home/rgga16/Desktop/dgl.py", line 25, in <module>
    G = build_karate_club_graph()
  File "/home/rrgga16/Desktop/dgl.py", line 23, in build_karate_club_graph
    return dgl.DGLGraph((u, v))
AttributeError: module 'dgl' has no attribute 'DGLGraph'
```

## Expected behavior

A DGLGraph to be created with the specified parameters

## Environment

 - DGL Version (e.g., 1.0): 0.4.3post2
 - Backend Library & Version (e.g., PyTorch 0.4.1, MXNet/Gluon 1.3): Pytorch 1.5.1
 - OS (e.g., Linux): Ubuntu 20.04
 - How you installed DGL (`conda`, `pip`, source): `conda install -c dglteam dgl-cuda10.1`
 - Build command you used (if compiling from source): N/A
 - Python version: 3.7.6 (in Anaconda)
 - CUDA/cuDNN version (if applicable): 10.1.243
 - GPU models and configuration (e.g. V100): Nvidia Geforce GTX 960M
 - Any other relevant information:

**Comment by VoVAllen** [comment]
Do you have a folder named `dgl` at the same directory of the code file? You can check it by `import dgl; print(dgl.__path__)` to see whether dgl is properly imported

**Comment by rgee3894** [comment]
No, I do not have a folder named dgl in the same directory.

Running `import dgl; print(dgl.__path__)` gives the following error:

```
Traceback (most recent call last):
  File "dgl.py", line 1, in <module>
    import dgl
  File "/home/rgga16/Desktop/dgl.py", line 5, in <module>
    print(dgl.__path__)
AttributeError: module 'dgl' has no attribute '__path__'
```

**Comment by rgee3894** [comment]
Sorry I found the mistake. The file I was running is named `dgl.py`. That must have been read as the library. I just renamed my code file to something else.
