### ISSUE TITLE
Is dgl.function.u_add_v same with dgl.function.v_add_u? 

### ISSUE THREAD

**Issue by pyli0628** [dmlc/dgl#1842]
## ❓ Questions and Help
In dgl.function, is u_add_v same with v_add_u? and many other similar functions, such as u_add_e and e_add_u, v_mul_u and u_mul_v

**Comment by yzh119** [comment]
Yes they are exactly the same, except for the order of operands.

**Comment by pyli0628** [comment]
Thanks

**Comment by pyli0628** [comment]
i
