### ISSUE TITLE
Unable to Build Public Docs Locally

### ISSUE THREAD

**Issue by ngluna** [dmlc/dgl#1849]
## 📚 Documentation

I am following the [instructions](https://docs.dgl.ai/contribute.html#contributing-documentations) on how to build docs. locally.

After building MXNet, DGL from source and after installing the required packages, I went to /dgl/docs and ran:

`> ./clean.sh  ` 
  
followed by:  

`> run html`

I then see a: 

`Bus Error` or `Segmentation Fault Error`. 

This happens specifically when generating the gallery for tutorials:

`.`
`.`
`.`
`generating gallery for tutorials/models/1_gnn... [100%] 9_gat.py `   
`generating gallery for tutorials/models/2_small_graph... [100%] 3_tree-lstm.py`                                                                                                                        
`generating gallery for tutorials/models/3_generative_model... [100%] 5_dgmg.py `                                                                                                                        
`generating gallery for tutorials/models/4_old_wines... [100%] 7_transformer.py `                                                                                                                       
`make: *** [mxnet] Segmentation fault: 115_giant_graph... [ 50%] 1_sampling_mx.py `

 The packages and versions are as follows:
`mxnet==2.0.`
`Sphinx==3.1.2`  
`sphinx-gallery==0.7.0  `
`sphinx-rtd-theme==0.5.0. `  
`torch==1.5.1`

**Comment by jermainewang** [comment]
Hi, you can skip the mxnet tutorials by
```
make pytorch
```

**Comment by ngluna** [comment]
Awesome. That worked. Thanks! 

**Note:** 
I had to first install graphviz and pygraphviz. For MacOS I ran the following:

`brew install graphviz`
`pip install pygraphviz`
