### ISSUE TITLE
Confusion in obtaining h_i and h_j in GATconv.py

### ISSUE THREAD

**Issue by amblee0306** [dmlc/dgl#1854]
Hi there,

In the GATConv.py, there are these lines of codes which I am curious on how they work. I understand that we are aiming to perform **a^T [Wh_i || Wh_j] = a_l Wh_i + a_r Wh_j** but I can't see how h_i and h_j are obtained respectively since the h_src and h_dst seems to be the same as well as feat_src and feat_dst.

                h_src = h_dst = self.feat_drop(feat)
                feat_src = feat_dst = self.fc(h_src).view(
                    -1, self._num_heads, self._out_feats)
 
            el = (feat_src * self.attn_l).sum(dim=-1).unsqueeze(-1)
            er = (feat_dst * self.attn_r).sum(dim=-1).unsqueeze(-1)
            graph.srcdata.update({'ft': feat_src, 'el': el})
            graph.dstdata.update({'er': er})
            # compute edge attention, el and er are a_l Wh_i and a_r Wh_j respectively.
            graph.apply_edges(fn.u_add_v('el', 'er', 'e'))

Any enlightenment will be appreciated. Thanks in advance.

**Comment by maqy1995** [comment]
In my understanding, the 'feat' in 'h_src = h_dst = self.feat_drop(feat)' contains all nodes feature in the graph, so they are the same. Each node in the graph will be used as both src and dst.

**Comment by amblee0306** [comment]
@maqy1995 firstly, thanks for the reply :)
I understand the part where feat contains all nodes' features and that possibly each pairwise combination of nodes will be considered during calculation. However, I m confused on how it is done in the code. In other words, if `feat_src` and `feat_dst` are the same matrix due to assignment (since `feat_src = feat_dst`), wouldn't variables el and er be the same? However, el and er are `a_l Wh_i and a_r Wh_j respectively`. Hence, I wonder how did the code specifically get all pairwise combination of h_i and h_j (to calculate all attention scores)? This is because even if all the nodes' features are in `feat`, how can we differentiate their order during calculation to ensure that the specific src and dst nodes' features are utilised and not a repetition of them where h_i = h_j?

**Comment by maqy1995** [comment]
I'm not sure if I understood your question accurately...
'el' and 'er' is different, because in the code below:
```
el = (feat_src * self.attn_l).sum(dim=-1).unsqueeze(-1)
er = (feat_dst * self.attn_r).sum(dim=-1).unsqueeze(-1)
```
'self.attn_l' and 'self.attn_r' is different, they are init in the '__init__' function:
```
self.attn_l = nn.Parameter(th.FloatTEnsor(size=(1, num_heads, out_feats)))
self.attn_r = nn.Parameter(th.FloatTEnsor(size=(1, num_heads, out_feats)))
```
After that, each node will storage there own 'el', 'er' and 'feat', which 'el' and 'er' is for 'e'=a^T[Wh_i || Wh_j]. Each edge will has their 'e'. These should correspond to the code:
```
graph.srcdata.update({'ft': feat_src, 'el': el})
graph.dstdata.update({'er': er})
graph.apply_edges(fn.u_add_v('el', 'er', 'e'))
```
I guess that the graph.srcdata and graph.dstdata here know their relation with original graph.nodes.

ps: 
I found the gatconv in master branch has changed the code above(my DGL version is 0.4.3):
https://github.com/dmlc/dgl/blob/a00636a02b61a1e0a1d5f330bd0e6a19c28d69a3/python/dgl/nn/pytorch/conv/gatconv.py#L106

pps:
I don’t know how DGL implemented their message passing under the hood...

**Comment by amblee0306** [comment]
I believe 'self.attn_l' and 'self.attn_r' are different but I don't think it is because of the fact that they are init via the two lines

`
self.attn_l = nn.Parameter(th.FloatTEnsor(size=(1, num_heads, out_feats)))
self.attn_r = nn.Parameter(th.FloatTEnsor(size=(1, num_heads, out_feats)))
`

Correct me if I am wrong cause I am still relatively new to this... but 'self.attn_l' and 'self.attn_r' are parameters that are to be learnt. And they are initialized separately cause they are going to learn something different due to the differences in the inputs being fed. But if the input is going to be the same, wouldn't they thus learn the same thing?

Given that `feat_src = feat_dst` and 

`
el = (feat_src * self.attn_l).sum(dim=-1).unsqueeze(-1)
er = (feat_dst * self.attn_r).sum(dim=-1).unsqueeze(-1)
`

wouldn't they learn the same thing and result in the same el and er? I can't seem to convince myself of the statement that "el and er are a_l Wh_i and a_r Wh_j respectively" since I can't see how h_i and h_j are being fed. Even though feat_src and feat_dst consist of features of all of the nodes, shouldn't there be some ordering that has to come into place? I might be overlooking something, please do tell me if you realised something is missing in my understanding.

**Comment by yzh119** [comment]
https://github.com/dmlc/dgl/blob/master/python/dgl/nn/pytorch/conv/gatconv.py#L133-L142
this explains how does it work.

Here is another related issue: https://github.com/dmlc/dgl/issues/963

**Comment by yzh119** [comment]
> but I can't see how h_i and h_j are obtained respectively since the h_src and h_dst seems to be the same as well as feat_src and feat_dst.

`feat_src` and `feat_dst` are the same, both referring to `h`. If you separate `feat_src` and `feat_dst`, you are actually operating on `h_i` and `h1_j` where `h` is `feat_src` and `h1` is `feat_dst.`
