### ISSUE TITLE
Subgraph of batched DGLGraph

### ISSUE THREAD

**Issue by Utenaq** [dmlc/dgl#1865]
## 🐛 Bug

Taking the subgraph of batched DGLGraphs will cause the batches to be merged, leading to incorrect behavior when performing `dgl.sum_nodes`.

## To Reproduce

```
print(g.batch_num_nodes) # Prints the num of individual graphs
g1 = g.subgraph(filter)
g1.copy_from_parent()
print(g1.batch_num_nodes) # This instead prints a scalar quantity
res = dgl.sum_nodes(g1, "x") # Incorrect summation
```

## Expected behavior

`g1.batch_num_nodes` should print out the number of nodes for individual graphs

## Environment

 - DGL Version: 0.4.3post2
 - Backend Library & Version: PyTorch 1.4.0
 - OS: Linux
 - How you installed DGL: pip
 - Python version: 3.7.6
 - CUDA/cuDNN version: 10.1
 - GPU models and configuration: V100

**Comment by classicsong** [comment]
The batched information is not maintained after subgraph()

**Comment by Utenaq** [comment]
@classicsong Thanks! Then what is the recommended way to perform message passing/readout on subgraphs after batching?

**Comment by classicsong** [comment]
Is your progress: graphs -> batched-graphs -> subgraph -> message passing -> readout?

Is this minibatch training when you are using subgraphs.

**Comment by classicsong** [comment]
Can you try:
```
subgs = [subg for g.sugraph(filter) in g)
batched_sugb = dgl.batch(subgs)
...
```

**Comment by jalexvig** [comment]
FFR the way I did this was

```
graph.ndata["h"] = feat
individual_graphs = dgl.unbatch(graph)
node_ids = [g.nodes()[g.ndata["filter_attr"].bool()] for g in individual_graphs]
all_subgraphs = [dgl.node_subgraph(g, ids) for g, ids in zip(individual_graphs, node_ids)]
batched_subgraphs = dgl.batch(all_subgraphs)
```
