### ISSUE TITLE
Duplicate edges in Pytorch RRN Model

### ISSUE THREAD

**Issue by ynandwan** [dmlc/dgl#1872]
## 🐛 Bug

While creating a graph for sudoku puzzle, duplicate edges are being created. While there is a check to prevent self-loop, the edges with the nodes that are in the same row as well as same block are repeated, e.g. edges (1,0), (2,0) occur twice as node number 1 and 2 are in the same row as well as same block for the destination node 0. Similarly for edges (9,0) and (18,0)

## To Reproduce

1. Execute the code snippet pasted below.  It compares the number of edges with the number of unique edges.

```
cd examples/pytorch/rrn
import sudoku_data as gd
o = sd._basic_sudoku_graph()
num_edges= len(o.edges()[0])
num_unique_edges = set(list(zip(o.edges()[0].numpy(), o.edges()[1].numpy())))
num_edges != num_unique_edges
```
## Environment

 - DGL Version (e.g., 1.0):
 - Backend Library & Version (e.g., PyTorch 0.4.1, MXNet/Gluon 1.3):
 - OS (e.g., Linux):
 - How you installed DGL (`conda`, `pip`, source):
 - Build command you used (if compiling from source):
 - Python version:
 - CUDA/cuDNN version (if applicable):
 - GPU models and configuration (e.g. V100):
 - Any other relevant information:

**Comment by yzh119** [comment]
@ynandwan thanks for reporting this bug, @HuXiangkun would you like to fix this bug?

**Comment by ynandwan** [comment]
What is the behavior when we train such a model with duplicate edges? The pre-trained model does achieve good performance though.

**Comment by HuXiangkun** [comment]
@ynandwan I fixed the example, please check the PR above. I changed the graph construction using new API `dgl.graph`. Please use pre-release version of DGL, or [build it from source](https://docs.dgl.ai/install/index.html#install-from-source).

**Comment by ynandwan** [comment]
@HuXiangkun Thanks! I checked the code. It looks good to me. Let me know if I am supposed to do anything else. 

Thanks!

**Comment by HuXiangkun** [comment]
@ynandwan @yzh119 I re-trained the RRN model for sudoku, and the model is updated to the server. It has better performance than the paper reported.
