### ISSUE TITLE
reproduce GAT network of tutorial by dgl.nn.pytorch.conv.GATConv

### ISSUE THREAD

**Issue by asurada404** [dmlc/dgl#1887]
## 📚 Documentation

Can I reproduce the [GAT](https://docs.dgl.ai/en/0.4.x/tutorials/models/1_gnn/9_gat.html#put-everything-together) network in [Graph attention network](https://docs.dgl.ai/en/0.4.x/tutorials/models/1_gnn/9_gat.html#sphx-glr-tutorials-models-1-gnn-9-gat-py) by [GATConv](https://docs.dgl.ai/api/python/nn.pytorch.html#gatconv)?

**Comment by SamujjwalSam** [comment]
I tried the same, didn't work. 
`
class MultiHeadGATLayer(torch.nn.Module):
    def __init__(self, g, in_dim, out_dim, num_heads, merge='cat'):
        super(MultiHeadGATLayer, self).__init__()
        self.heads = torch.nn.ModuleList()
        for i in range(num_heads):
            self.heads.append(GATConv(g, in_dim, out_dim))
        self.merge = merge

    def forward(self, h):
        head_outs = [attn_head(h) for attn_head in self.heads]
        if self.merge == 'cat':
            # concat on the output feature dimension (dim=1)
            return torch.cat(head_outs, dim=1)
        else:
            # merge using average
            return torch.mean(torch.stack(head_outs))
`
Replaced "GATLayer" with "GATConv" and it failed with this error:
`
---------------------------------------------------------------------------

TypeError                                 Traceback (most recent call last)

<ipython-input-14-d1d6cc87fe8b> in <module>
      4           hidden_dim=8,
      5           out_dim=7,
----> 6           num_heads=2)

<ipython-input-13-1d650b3d8eab> in __init__(self, g, in_dim, hidden_dim, out_dim, num_heads)
      5         super(GAT, self).__init__()
      6         print(in_dim, hidden_dim, out_dim)
----> 7         self.layer1 = MultiHeadGATLayer(g, in_dim, hidden_dim, num_heads)
      8         # Be aware that the input dimension is hidden_dim*num_heads since
      9         # multiple head outputs are concatenated together. Also, only

<ipython-input-6-c3feaeef9ffb> in __init__(self, g, in_dim, out_dim, num_heads, merge)
      6         self.heads = torch.nn.ModuleList()
      7         for i in range(num_heads):
----> 8             self.heads.append(GATConv(g, in_dim, out_dim))
      9         self.merge = merge
     10 

~/anaconda3/envs/gnn/lib/python3.7/site-packages/dgl/nn/pytorch/conv/gatconv.py in __init__(self, in_feats, out_feats, num_heads, feat_drop, attn_drop, negative_slope, residual, activation)
     70         else:
     71             self.fc = nn.Linear(
---> 72                 self._in_src_feats, out_feats * num_heads, bias=False)
     73         self.attn_l = nn.Parameter(th.FloatTensor(size=(1, num_heads, out_feats)))
     74         self.attn_r = nn.Parameter(th.FloatTensor(size=(1, num_heads, out_feats)))

~/anaconda3/envs/gnn/lib/python3.7/site-packages/torch/nn/modules/linear.py in __init__(self, in_features, out_features, bias)
     70         self.in_features = in_features
     71         self.out_features = out_features
---> 72         self.weight = Parameter(torch.Tensor(out_features, in_features))
     73         if bias:
     74             self.bias = Parameter(torch.Tensor(out_features))

TypeError: new(): argument 'size' must be tuple of ints, but found element of type DGLGraph at pos 2`

**Comment by SamujjwalSam** [comment]
Finally made it work with below code:

**NOTE:** No need for multi-head attention as GATConv already have the attention layer inside.

```python
class GATDefault(torch.nn.Module):
    def __init__(self, in_dim, hidden_dim, out_dim, num_heads):
        super(GATDefault, self).__init__()
        self.layer1 = GATConv(in_dim, hidden_dim, num_heads)
        # Be aware that the input dimension is hidden_dim*num_heads since
        # multiple head outputs are concatenated together. Also, only
        # one attention head in the output layer.
        self.layer2 = GATConv(hidden_dim * num_heads, out_dim, 1)

    def forward(self, g, h):
        h = self.layer1(g, h)
        # Concat last 2 dim (num_heads * out_dim)
        h = h.view(-1, h.size(1) * h.size(2))
        h = F.elu(h)
        h = self.layer2(g, h)
        # Sueeze the head dim as it's = 1 
        h = h.squeeze()
        return h

net = GATDefault(
          in_dim=features.size(1),
          hidden_dim=8,
          out_dim=7,
          num_heads=2)
print(net)

# create optimizer
optimizer = torch.optim.Adam(net.parameters(), lr=1e-3)

# main loop
dur = []
for epoch in range(30):
    if epoch >= 3:
        t0 = time.time()

    logits = net(g, features)
    logp = F.log_softmax(logits, 1)
    loss = F.nll_loss(logp[mask], labels[mask])

    optimizer.zero_grad()
    loss.backward()
    optimizer.step()

    if epoch >= 3:
        dur.append(time.time() - t0)

    print("Epoch {:05d} | Loss {:.4f} | Time(s) {:.4f}".format(
        epoch, loss.item(), np.mean(dur)))

```

**Comment by miriamelia** [comment]
I actually have the same issue when I tried to use GATConv instead of a GATLayer Class in the example code from here : 

https://discuss.dgl.ai/t/gat-for-graph-classification/366/18

my output then is:

![GAT_error1](https://user-images.githubusercontent.com/29278598/95720798-fec39380-0c71-11eb-8bc2-a3ff2d009afa.png)

Does anybody have any ideas what else I could try to solve this?

**Comment by SamujjwalSam** [comment]
@miriamelia there are so many code snippets in the forum post, could you please refer correctly or post the code here. Also, I would suggest to try the code I posted above. Although the code is bit old I think it should work fine.

**Comment by miriamelia** [comment]
@SamujjwalSam sure, here the code I use:

class GATLayer(nn.Module):
    def __init__(self, in_dim, out_dim, num_heads, feat_drop=0., attn_drop=0., alpha=0.2, agg_activation=F.elu):
        super(GATLayer, self).__init__()
        self.num_heads = num_heads
        # During training, randomly zeroes some of the elements of the input tensor with probability p using samples
        # from a Bernoulli distribution. Each channel will be zeroed out independently on every forward call. This
        # has proven to be an effective technique for regularization and preventing the co-adaptation of neurons
        self.feat_drop = nn.Dropout(feat_drop)
        # Linear transformation of bidirectional graph
        self.fc = nn.Linear(in_dim, num_heads * out_dim, bias=False)

        # add attention as parameter - 2 values because bidirectional
        self.attn_l = nn.Parameter(torch.Tensor(size=(num_heads, out_dim, 1)))
        self.attn_r = nn.Parameter(torch.Tensor(size=(num_heads, out_dim, 1)))
        # Dropout rate on attention weight, defaults: "0"
        self.attn_drop = nn.Dropout(attn_drop)

        self.activation = nn.LeakyReLU(alpha)
        # to compute attention weights
        self.softmax = edge_softmax
        self.agg_activation = agg_activation

    def clean_data(self):
        ndata_names = ['ft', 'a1', 'a2']
        edata_names = ['a_drop']
        for name in ndata_names:
            self.g.ndata.pop(name)
        for name in edata_names:
            self.g.edata.pop(name)

    def forward(self, bg, feat):
        # prepare, inputs are of shape V x F, V the number of nodes, F the dim of input features
        self.g = bg
        h = self.feat_drop(feat)
        # V x K x F', K number of heads, F' dim of transformed features             -1: placeholder, torch finds number
        ft = self.fc(h).reshape((h.shape[0], self.num_heads, -1))
        head_ft = ft.transpose(0, 1)  # K x V x F'
        # create attention parameter values for all nodes and all heads via a batch matrix-matrix product
        a1 = torch.bmm(head_ft, self.attn_l).transpose(0, 1)  # V x K x 1
        a2 = torch.bmm(head_ft, self.attn_r).transpose(0, 1)  # V x K x 1
        self.g.ndata.update({'ft': ft, 'a1': a1, 'a2': a2})
        # 1. compute edge attention; apply func to all edges
        self.g.apply_edges(self.edge_attention)
        # 2. compute softmax in two parts: exp(x - max(x)) and sum(exp(x - max(x)))
        self.edge_softmax()
        # 2. compute the aggregated node features scaled by the dropped,
        # unnormalized attention values. (attention values added to node features)
        # Builtin message function that computes message by performing binary operation mul between src feature and
        # edge feature
        self.g.update_all(fn.src_mul_edge('ft', 'a_drop', 'ft'), fn.sum('ft', 'ft'))
        ret = self.g.ndata['ft']  # V x K x F'
        # Remove all batching information of the graph, and regard the current graph as an independent graph
        # rather then a batched graph. Graph topology and attributes would not be affected.
        ret = ret.flatten(1)

        # 3. apply normalizer
        if self.agg_activation is not None:
            ret = self.agg_activation(ret)

        # Clean ndata and edata
        self.clean_data()

        return ret

    def edge_attention(self, edges):
        # an edge UDF (User-defined functions (UDFs) are flexible ways to configure message passing computation)
        # to compute un-normalized attention values from src and dst; LeakyRelU
        a = self.activation(edges.src['a1'] + edges.dst['a2'])
        return {'a': a}

    def edge_softmax(self):
        attention = self.softmax(self.g, self.g.edata.pop('a'))
        # Dropout attention scores and save them
        self.g.edata['a_drop'] = self.attn_drop(attention)


class GATClassifier(nn.Module):
    def __init__(self, in_dim, hidden_dim, num_heads, n_classes):
        super(GATClassifier, self).__init__()

        # the input dimension is hidden_dim*num_heads since multiple head outputs are concatenated together
        self.layers = nn.ModuleList([
            GATLayer(in_dim, hidden_dim, num_heads),
            GATLayer(hidden_dim * num_heads, hidden_dim, num_heads),
            GATLayer(hidden_dim * num_heads, hidden_dim, num_heads),
            GATLayer(hidden_dim * num_heads, hidden_dim, num_heads)
            # GATConv(in_dim, hidden_dim, num_heads),
            # GATConv(hidden_dim * num_heads, hidden_dim, num_heads),
            # GATConv(hidden_dim * num_heads, hidden_dim, num_heads)
        ])
        # for the read out from the hidden features of the graph; linear transformation
        self.classify = nn.Linear(hidden_dim * num_heads, n_classes, 1)  # 1 ?

    def forward(self, bg):
        # For undirected graphs, in_degree is the same as
        # out_degree.
        h = bg.in_degrees().view(-1, 1).float()
        # logging.info(h.shape)
        for i, layer in enumerate(self.layers):
            h = layer(bg, h)  # graph, then features for GATConv
        bg.ndata['h'] = h
        # Readout process: graph is aggregated to a 1 by x vector
        hg = dgl.mean_nodes(bg, 'h')
        return self.classify(hg)


I tried applying what you did above, but I haven't yet found a way to transfer

**Comment by decoherencer** [comment]
with [this](https://github.com/dmlc/dgl/tree/master/examples/pytorch/gat) in place now, I think we can close this issue
