### ISSUE TITLE
Should 'dglnn.expand_as_pair' be ’dgl.utils.expand_as_pair‘ ?

### ISSUE THREAD

**Issue by Ruiping-Li** [dmlc/dgl#1899]
https://github.com/dmlc/dgl/blob/b9ae536ecfc889b07ba3e7b116953b06cd5f616c/examples/pytorch/rgcn-hetero/model.py#L104

'dglnn.expand_as_pair' is not exist. It seems to be ’dgl.utils.expand_as_pair‘.

**Comment by yzh119** [comment]
Yes you are right, thanks for reporting this bug.

**Comment by Ruiping-Li** [comment]
> Yes you are right, thanks for reporting this bug.
Glad to be helpful
btw, nice Avatar (doge

**Comment by yzh119** [comment]
I found that in `dgl.nn` we import `expand_as_pair` from `dgl.utils`:
https://github.com/dmlc/dgl/blob/ec2e24be6dcc3bcc3d4ad5dff78212735f9db00f/python/dgl/nn/__init__.py

So there is no need for a change.

btw, Thanks for your commend :)
