### ISSUE TITLE
Pinsage example meets KeyError: 'weights'

### ISSUE THREAD

**Issue by Woooosz** [dmlc/dgl#1900]
## To Reproduce

Pinsage Example

1.python model.py data.pkl --num-epochs 300 --num-workers 2 --device cpu --hidden-dims 64

## Environment

certifi         2020.6.20
chardet         3.0.4
decorator       4.4.2
dgl             0.4.3.post2
future          0.18.2
idna            2.10
networkx        2.4
numpy           1.19.1
pandas          1.1.0
pip             20.1.1
protobuf        3.12.4
python-dateutil 2.8.1
pytz            2020.1
requests        2.24.0
scipy           1.5.2
sentencepiece   0.1.91
setuptools      49.2.0.post20200714
six             1.15.0
stanfordnlp     0.2.0
torch           1.6.0
torchtext       0.7.0
tqdm            4.48.0
urllib3         1.25.10
wheel           0.34.2

**Comment by VoVAllen** [comment]
Which example are you trying to run?

**Comment by Woooosz** [comment]
![image](https://user-images.githubusercontent.com/16368530/89009685-a43bbc00-d33f-11ea-8282-8041ae58e45d.png)


> Which example are you trying to run?

Pinsage thx

**Comment by BarclayII** [comment]
I cannot reproduce this error with either MovieLens or NowPlaying-RS.  Could you try installing the nightly build and running the example again?

```
pip install --upgrade dgl   # or dgl-cuXX for GPU
```

**Comment by Woooosz** [comment]
> I cannot reproduce this error with either MovieLens or NowPlaying-RS. ~Could you try installing the nightly build and running the example again?~ Are you running the example on the master branch? If so, for now you might need to build the package from source, or wait for a day until our next nightly build goes online.
> 
> ```
> pip install --upgrade dgl   # or dgl-cuXX for GPU
> ```

Thank you for your reply. 

When I am running the example on the 2f6ab43a1b55c7993ac923671ec039cbfbf4710d, no errors
When I am running the example on the 44089c8b4d4db4ca71e816e0de50dca972dbabdb, then meets KeyError

**Comment by Woooosz** [comment]
![image](https://user-images.githubusercontent.com/16368530/89011735-748eb300-d343-11ea-88c0-4ca321c9d2e6.png)

Maybe this is the answer.

**Comment by Woooosz** [comment]
Yes, When I  add
"frontier.edata['weights'] = old_frontier.edata['weights'][frontier.edata[dgl.EID]]"

then no errors

**Comment by BarclayII** [comment]
I see.  That is caused by a recent update in DGL on the master branch.  If you install nightly build you can probably fix it.

Please feel free to reopen if you have further questions.  Thanks.
