### ISSUE TITLE
MXNet sampling examples broken

### ISSUE THREAD

**Issue by slayton58** [dmlc/dgl#1923]
## 🐛 Bug

examples/mxnet/sampling/train.py no longer runs with: 

```
  File "examples/mxnet/sampling/train.py", line 55, in main
    g = dgl.DGLGraph(data.graph, readonly=True)
  File "/usr/local/lib/python3.6/dist-packages/dgl-0.4-py3.6-linux-x86_64.egg/dgl/heterograph.py", line 204, in __init__
    raise DGLError('The input is already a DGLGraph. No need to create it again.')
dgl._ffi.base.DGLError: The input is already a DGLGraph. No need to create it again.
```

## To Reproduce

1. Build DGL with MXNet
2. `python examples/mxnet/sampling/train.py --model graphsage_cv --batch-size 1000 --test-batch-size 5000 --n-epochs 200 --dataset reddit --num-neighbors 1 --n-hidden 128 --dropout 0.2 --weight-decay 0 --gpu 0
`

Error:

```
  File "examples/mxnet/sampling/train.py", line 55, in main
    g = dgl.DGLGraph(data.graph, readonly=True)
  File "/usr/local/lib/python3.6/dist-packages/dgl-0.4-py3.6-linux-x86_64.egg/dgl/heterograph.py", line 204, in __init__
    raise DGLError('The input is already a DGLGraph. No need to create it again.')
dgl._ffi.base.DGLError: The input is already a DGLGraph. No need to create it again.
```

Note: replacing above line with `g = data.graph` causes issues with following `g.set_n_repr(...)` calls.

## Expected behavior

Example should run

## Environment

 - DGL Version (e.g., 1.0): master
 - Backend Library & Version (e.g., PyTorch 0.4.1, MXNet/Gluon 1.3): MXNet 
 - OS (e.g., Linux): Linux
 - How you installed DGL (`conda`, `pip`, source): source
 - Build command you used (if compiling from source): 
```
mkdir build && \
    cd build && \
    cmake -DUSE_CUDA=ON -DBUILD_CPP_TEST=1 .. && \
    make -j && \
    cd ../python && \
    python setup.py install
```

 - Python version:
3.7
 - CUDA/cuDNN version (if applicable):
11.0 / 8
 - GPU models and configuration (e.g. V100):
V100 (in a DGX 8xV100 box)
 - Any other relevant information:

**Comment by classicsong** [comment]
The sampling examples in MXNet is very old and is deprecated in v0.5
