### ISSUE TITLE
Link Prediction for RGCN-Hetero

### ISSUE THREAD

**Issue by sophiakrix** [dmlc/dgl#1940]
## Link Prediction for RGCN Heterograph
Could you add to the [Relational Graph Convolutional Neural Network an Implementation for Heterographs](https://github.com/dmlc/dgl/tree/c801a164ee6ea189c284ca42f5a06503a8c874be/examples/pytorch/rgcn-hetero) (next to the Entity Classification) for Link Prediction?

## Motivation

Since this is a very relevant task in graph based ML, it would be very helpful to have an implementation for the Link Prediction. Many applications are looking for an implementation for a heterograph.

**Comment by classicsong** [comment]
Currently, I am implementing link prediction for RGCN: https://github.com/dmlc/dgl/pull/1925
It convert the heterograph into homogeneous graph and do the RGCN-style training.

**Comment by sophiakrix** [comment]
@classicsong Oh that's great! Could you tell me where exactly the conversion from the heterograph into a homogeneous graph is happening?

And how would it be possible to enable to compatibility with hetergraphs?

**Comment by classicsong** [comment]
In Line 375 there is a g = dgl.to_homo(hg)

All edge types are stored in edge features and node types are stored in node features.
The dgl.nn.RelGraphConv will handle the edge type

**Comment by sophiakrix** [comment]
@classicsong To which file are you referring to? In all of the files that were changed in your issue, I couldn't fine one with `g = dgl.to_homo(hg)`.

**Comment by classicsong** [comment]
https://github.com/dmlc/dgl/blob/729ff2ef385f302af562c8305b1006d067d2067f/examples/pytorch/rgcn/entity_classify_mp.py#L487

Here is an example
