### ISSUE TITLE
AttributeError: 'DGLHeteroGraph' object has no attribute 'create_format_' in graphsage example

### ISSUE THREAD

**Issue by samkitjain** [dmlc/dgl#1945]
## 🐛 Bug

I get "AttributeError: 'DGLHeteroGraph' object has no attribute 'create_format_'" error when I try to run graphsage example supplied in dgl/examples/pytorch/graphsage

## To Reproduce

1. cd dgl/examples/pytorch/graphsage
2. python train_sample.py --num-hidden 256 --gpu -1

AttributeError: 'DGLHeteroGraph' object has no attribute 'create_format_'

## Expected behavior

I am expecting it to train graphSAGE Network on reddit dataset.

## Environment

 - DGL Version (e.g., 1.0): 0.4.3.post2
 - Backend Library & Version (e.g., PyTorch 0.4.1, MXNet/Gluon 1.3): PyTorch 1.6.0 [cpuonly]
 - OS (e.g., Linux): Windows 10
 - How you installed DGL (`conda`, `pip`, source): conda (conda install -c dglteam dgl)
 - Build command you used (if compiling from source): N/A
 - Python version: 3.6.10
 - CUDA/cuDNN version (if applicable): N/A
 - GPU models and configuration (e.g. V100): N/A
 - Any other relevant information: N/A

**Comment by classicsong** [comment]
Please try the latest DGL version.

**Comment by samkitjain** [comment]
@classicsong 0.4.3.post2 is latest package available with conda. Are you suggesting I should build dgl from source?

**Comment by classicsong** [comment]
Yes.
If you are using pip, you can use pip install --pre. But it is conda, you may need to build from source.
https://docs.dgl.ai/en/latest/install/index.html

**Comment by samkitjain** [comment]
Works on latest version. Thanks ! Closing ticket.
