### ISSUE TITLE
Split tensor equally for multi gpu

### ISSUE THREAD

**Issue by cfangplus** [dmlc/dgl#1949]
When we run this example demo https://github.com/dmlc/dgl/blob/master/examples/pytorch/graphsage/train_sampling_multi_gpu.py to enable multi gpu graphsage training, we found there exists a mirror error that is located at line148. 
![图片](https://user-images.githubusercontent.com/42287875/89497424-e7d67000-d7ee-11ea-864d-28f8068a245d.png)
Actually, its split result would drop some training data. For Example, if we have a tensor and the split logic is same as the example demo:
![图片](https://user-images.githubusercontent.com/42287875/89497007-0851fa80-d7ee-11ea-9e9f-36859e7bdb84.png)
The split result would be as follow and as you can see the final tensor element 8 is dropped.
![图片](https://user-images.githubusercontent.com/42287875/89497129-4bac6900-d7ee-11ea-9e4b-0d3402758e94.png)

What we expected is to change the split logic as follow:
![图片](https://user-images.githubusercontent.com/42287875/89497194-726a9f80-d7ee-11ea-8fcb-65878037b684.png)
Now the split result is:
![图片](https://user-images.githubusercontent.com/42287875/89497224-81515200-d7ee-11ea-9d90-3fd58a674397.png)
This time, all the training tensor would be loaded to its corresponding GPU to be trained.

Our Environment：
- DGL Version (master branch)

**Comment by VoVAllen** [comment]
You are right. Thanks for your report!

**Comment by cfangplus** [comment]
the commit is not right, actually math.ceil(len(train_nid) / n_gpus) is correct.

**Comment by VoVAllen** [comment]
Thanks 😢  Will fix this later
