### ISSUE TITLE
Error in re-running GraphSAGE example: train_sampling.py

### ISSUE THREAD

**Issue by samkitjain** [dmlc/dgl#1958]
## 🐛 Bug

I am trying to train graphSAGE using example provided in dgl/examples/pytorch/graphsage/train_sampling.py. When I run it for the first time, training takes places as expected. It downloads reddit data set, unzips it and uses it to train graphSAGE model. When I try to re-run after first successful run, reddit dataset is not downloaded as it is already there and it keeps erroring out with error as described below. 

    Expect argument "nodes["_N"]" to have data type torch.int64 and device context cpu. But got torch.uint8 and cpu

However, if I delete downloaded reddit data set, specifically the unzipped folder, every time before subsequent runs, it works fine.

## To Reproduce

1. Goto to test dir
    `cd dgl/examples/pytorch/graphsage`
2. Run training script (following will succeed first time)
    `python train_sampling.py --num-epochs 30 --inductive --gpu 0 --num-hidden 256`
3. Re-run it and it fails
    `python train_sampling.py --num-epochs 30 --inductive --gpu 0 --num-hidden 256`
4. Delete unzipped reddit data set
    `rm .dgl/reddit_self_loop -rf`
5. Rerun it and it passes
    `python train_sampling.py --num-epochs 30 --inductive --gpu 0 --num-hidden 256`

Error Message when it fails:

Using backend: pytorch
/home/samkitja/anaconda3/lib/python3.8/site-packages/dgl/data/utils.py:285: UserWarning: Property dataset.num_labels will be deprecated, please use dataset.num_classes instead.
  warnings.warn('Property {} will be deprecated, please use {} instead.'.format(old, new))
/home/samkitja/anaconda3/lib/python3.8/site-packages/dgl/base.py:45: DGLWarning: DEPRECATED: DGLGraph and DGLHeteroGraph have been merged in v0.5.
        dgl.as_heterograph will do nothing and can be removed safely in all cases.
  return warnings.warn(message, category=category, stacklevel=1)
Traceback (most recent call last):
  File "train_sampling.py", line 232, in <module>
    train_g, val_g, test_g = inductive_split(g)
  File "/home/samkitja/gnn/graphSAGE_implementations/pytorch-dgl/load_graph.py", line 46, in inductive_split
    train_g = g.subgraph(g.ndata['train_mask'])
  File "/home/samkitja/anaconda3/lib/python3.8/site-packages/dgl/heterograph.py", line 2546, in subgraph
    induced_nodes = [_process_nodes(ntype, nodes.get(ntype, [])) for ntype in self.ntypes]
  File "/home/samkitja/anaconda3/lib/python3.8/site-packages/dgl/heterograph.py", line 2546, in <listcomp>
    induced_nodes = [_process_nodes(ntype, nodes.get(ntype, [])) for ntype in self.ntypes]
  File "/home/samkitja/anaconda3/lib/python3.8/site-packages/dgl/heterograph.py", line 2545, in _process_nodes
    return utils.prepare_tensor(self, v, 'nodes["{}"]'.format(ntype))
  **File "/home/samkitja/anaconda3/lib/python3.8/site-packages/dgl/utils/checks.py", line 33, in prepare_tensor
    raise DGLError('Expect argument "{}" to have data type {} and device '
dgl._ffi.base.DGLError: Expect argument "nodes["_N"]" to have data type torch.int64 and device context cpu. But got torch.uint8 and cpu.**

## Expected behavior

I expect successful back to back runs without having to delete downloaded dataset everytime

## Environment

 - DGL Version (e.g., 1.0): dgl-cu102==0.5a200805
 - Backend Library & Version (e.g., PyTorch 0.4.1, MXNet/Gluon 1.3): Pytorch 1.6.0
 - OS (e.g., Linux): CentOS 8 (Linux)
 - How you installed DGL (`conda`, `pip`, source): pip install --pre dgl-cu102
 - Build command you used (if compiling from source):
 - Python version: 3.8.3
 - CUDA/cuDNN version (if applicable): 10.2
 - GPU models and configuration (e.g. V100): GeForce RTX 2080 Ti
 - Any other relevant information:

**Comment by classicsong** [comment]
The problem is solved in https://github.com/dmlc/dgl/pull/1987.
