### ISSUE TITLE
Support for Cuda 11

### ISSUE THREAD

**Issue by bjascob** [dmlc/dgl#1969]
## 🚀 Feature
Cuda 11 in now supported by pytorch 1.6 (at least for Ubuntu via `pip3 install torch`).  I'm wondering if there are plans to support this in DGL?

The current binaries won't install because of missing cuda .so files but I was able to build and and run DGL with a few small mods.  Here's specifics in case someone else wants to try this...

**System:**
Ubuntu 20.04.1
Python 3.8 
Cuda 11
torch 1.6
GPU: GTX Titan X (5.2 compute capability)

**Mods starting from DGL master 8/7/2020**
1 - In `cmake/modules/CUDA.cmake`  change 2 instances of `sm_30` to something newer like `sm_52`.  Cuda 11 doesn't support `sm_30` anymore and fails on this argument.

2 - Cuda sparse functions `cusparseScsrmm2` and `cusparseDcsrmm2` no longer available.  These are replaced with `cusparseSpMM`.  The arguments are different and I didn't look into how to fix this but if you're not using sparse vectors these functions can be commented out in 3 different files.

- In `src/array/cuda/spmm.cu` and `src/kernel/cuda/binary_reduce_sum.cu` comment out the 2 functions that use the above.
- In `src/array/cuda/csr_transpose.cc`, comment out the code where cusparseScsr2csc is on about line 76

With those changes I was able to build and install.  I haven't tried to run any unit tests but the GraphWriter example is able to train.

**Comment by yzh119** [comment]
Yes we do have plan to support CUDA 11, I'm take over the job.
For cusparse, they have several new APIs and we need to set up a benchmark to decide which one to use in practice.

**Comment by yzh119** [comment]
Hi @bjascob , I've finished the CUDA 11 support in #1979 , I'm not sure if it would be merged into the master branch recently but you can try this feature by installing from source on [this branch](https://github.com/yzh119/dgl/tree/cu11).

**Comment by bjascob** [comment]
Nice.  Everything built, installed, and at least started training like it should.  You even got rid of the C++14 warning messages.  
I'll let you close this out when you think it's appropriate (maybe after merge?)

BTW... with these type of libs (tensorflow, pytorch,..) and Cuda I always find it difficult to find a definitive answer on what version of the library works with what version of Cuda.  It would be nice to have a compatibility matrix somewhere that users can find.  In the past with Tensorflow, I've had to search issues/PR's, release notes, etc.. to get the answer.  Just a thought if you've got any ideas where that might get documented (and updated with new releases).

**Comment by yzh119** [comment]
@bjascob good idea, I will try to make a dependency table, please stay tuned.

**Comment by bjascob** [comment]
With release 0.5.1 DGL source now supports Cuda 11.  Pre-compiled binaries are not being created yet.  The user must compile from source for Cuda 11 support.
