### ISSUE TITLE
DGLGraph edge id mechanism

### ISSUE THREAD

**Issue by JiangTanZJU** [dmlc/dgl#1978]
How are edge IDs of the graph allocated? Does it depend on the order of add_edges operation?

For example:
~~~py
g = dgl.DGLGraph()
g.add_nodes(10)
g.add_edges([0,0,0,0,0],[0,1,2,3,4])
g.add_edges([0,0,0,0,0],[5,6,7,8,9])
print(g.find_edges([8]))
~~~
I tested it for many times, and it always return `(tensor([0]), tensor([8]))`.
Does it certainly return `(tensor([0]), tensor([8]))`, not `(tensor([8]), tensor([0]))` or something else? Is this a feature that I can depend？

**Comment by jermainewang** [comment]
Yes, that's a behavior you can rely on. The edge IDs are assigned according to the addition order.
