### ISSUE TITLE
How to get a deterministic results?

### ISSUE THREAD

**Issue by broken-dream** [dmlc/dgl#1990]
I tried using GAT for relation classfication but couldn't get a stable F1 score. My settings are follows:
```
        torch.manual_seed(args.seed)
        torch.cuda.manual_seed_all(args.seed)
        np.random.seed(args.seed)
        random.seed(args.seed)
        dgl.random.seed(args.seed)
        torch.backends.cudnn.deterministic = True
```
I have read the reply in #1471, but my problem is not same. The F1 score fluctuates from 70.1% to 73.6%, so I don't think it's caused by the atomic operators.

**Comment by yzh119** [comment]
@broken-dream Hi, please try our nightly build version, or install the code on master branch from source.
We have fixed all deterministic related problems.

**Comment by yzh119** [comment]
btw, your claim
> so I don't think it's caused by the atomic operators.
is wrong. Actually, the atomic operator caused larger variance than you can imagined...

We have turned to use deterministic operators to avoid such problems.

**Comment by broken-dream** [comment]
👌I will try it.
For my claim, I know nothing about atomic operator so I intuitively think it's just a small noise accroding to the result showded in #1471 :joy:.
Thanks for your help!
