### ISSUE TITLE
Pinsage sampler.py meets 'MultiDiGraph' object is not callable

### ISSUE THREAD

**Issue by B1ACK917** [dmlc/dgl#2004]
## 🐛 Bug

Pinsage sampler.py meets 'MultiDiGraph' object is not callable

## To Reproduce

1.python process_movielens1m.py ./ml-1m ./data.pkl
2.python model.py data.pkl --num-epochs 300 --num-workers 2 --device cuda:0 --hidden-dims 64

## Expected behavior

This is the TraceBack pic
![Expected](https://user-images.githubusercontent.com/45218430/89972096-8b140300-dc8f-11ea-9417-1e81fd35d4d7.JPG)

## Environment

 - DGL Version (e.g., 1.0): 0.4.3.post2
 - Backend Library & Version (e.g., PyTorch 0.4.1, MXNet/Gluon 1.3):
  torch           1.6.0
  torchtext       0.7.0
 - OS (e.g., Linux): Ubuntu
 - How you installed DGL (`conda`, `pip`, source): pip
 - Python version: Python 3.7.3
 - CUDA/cuDNN version (if applicable): CUDA Version 10.0.130
 - GPU models and configuration (e.g. V100): TITAN RTX

**Comment by farazmah** [comment]
all instances of `g.metagraph()` need to be changed to `g.metagraph` in the init of `ItemToItemBatchSampler` and `NeighborSampler` in `sampler.py`

**Comment by BarclayII** [comment]
The code on master branch must run on nightly build.  Could you try using nightly build?

```
pip install --pre dgl-cuXX  # XX is the version number
```
