### ISSUE TITLE
 Error in running GraphSAGE: KeyError: 'features'

### ISSUE THREAD

**Issue by samkitjain** [dmlc/dgl#2053]
## 🐛 Bug

I get an error (KeyError: 'features' , see below) when I try to run graphsage/train_sampling.py. I printed offending "blocks[0].srcdata" dictionary and it indeed doesn't contain 'feature' key.

Printing blocks[0].srcdata :
{'_ID': tensor([126656,  10563,  78396,  ..., 127507, 153229,  55315])}

After looking at recent commits, there was a patch (commit edfbee2ca8d24aef8600a440d7ab3fd70c61e1f8) pushed that updates line causing this issue. **I am able to run train_sampling.py to completion if I make following changes in it**:

comment:

```
#batch_inputs = blocks[0].srcdata['features']
#batch_labels = blocks[-1].dstdata['labels']
```

uncomment:

`batch_inputs, batch_labels = load_subtensor(train_g, seeds, input_nodes, device)`

## To Reproduce

1. cd dgl/examples/pytorch/graphsage
2. python train_sampling.py --num-epochs 1 --inductive --gpu -1 --num-hidden 256

Traceback (most recent call last):
  File "train_sampling.py", line 260, in <module>
    run(args, device, data)
  File "train_sampling.py", line 173, in run
    batch_inputs = blocks[0].srcdata['features']
  File "/home/samkitja/anaconda3/lib/python3.8/site-packages/dgl/view.py", line 66, in __getitem__
    return self._graph._get_n_repr(self._ntid, self._nodes)[key]
  File "/home/samkitja/anaconda3/lib/python3.8/site-packages/dgl/frame.py", line 371, in __getitem__
    return self._columns[name].data
KeyError: 'features'

## Expected behavior

It should work out of the box.

## Environment

 - DGL Version (e.g., 1.0): dgl-cu102==0.5a200818
 - Backend Library & Version (e.g., PyTorch 0.4.1, MXNet/Gluon 1.3):  Pytorch 1.6.0
 - OS (e.g., Linux): CentOS 8 (Linux)
 - How you installed DGL (`conda`, `pip`, source): pip install --pre dgl-cu102
 - Build command you used (if compiling from source):
 - Python version: 3.8.3
 - CUDA/cuDNN version (if applicable): 10.2
 - GPU models and configuration (e.g. V100):
 - Any other relevant information:

**Comment by BarclayII** [comment]
The patch is applied after the nightly build 200818.  You may probably want to wait for build 200819 (the building process starts every day 8:00 AM UTC) or you can try the source build instead.

**Comment by samkitjain** [comment]
Thanks for this info. I will keep this in mind moving forward.
