### ISSUE TITLE
SpMM DDS format support

### ISSUE THREAD

**Issue by kira-lin** [dmlc/dgl#2060]
## 🚀 Feature

Support dds format for SpMM on CPU so that dgl can compute SpMM on graph partitioned on columns.

## Motivation

* Column Partition can make the working set(node feature) smaller so that cache can be better utilized. 
* :x:  We can combine it with non temporal load to see how well it works (nontemporal load only work on write-combining memory, so impractical)

## Pitch

Column partitioning has already been implemented. We can expose this kernel as a packed_func to python, just for testing.
@yzh119

**Comment by yzh119** [comment]
# Some context

## What is dds format?
@kira-lin please describe where this term comes from, what does dds stand for?

Briefly speaking, dds partitions the columns of a sparse matrix, and stores the CSR representation correspond to each partition. 
e.g. for a sparse matrix with 100 rows and 16 columns, and we set the number of column partitions to four.

Then we collect the non zero elements that reside in the columns [0, 4) and save them in CSR format. Then we do the same thing for column [4, 8), [8, 12), [12, 16) respectively.

## What is this format used for?
In featgraph we partition the column of sparse matrix to accelerate SpMM on CPU.

## Should we write a set of graph operators for this format?
Absolutely no, we only support spmm on this format.

**Comment by kira-lin** [comment]
DDS stands for dense-dense-sparse, this term is used in @Huyuwei's repo. 

I have implemented the partition functions, and added them to DGL. One is for SDDMM, which just returns a reordered COO matrix. They both take a `CSRMatrix` as input, and return a vector of `NDArray`. The output is passed to python as input to respective kernels. Therefore, no change is needed for other parts of code, except if they want to use partition.

Besides, these partition functions only work on CPU, because GPU benefits little from partitioning.
