### ISSUE TITLE
AttributeError: 'DGLGraph' object has no attribute 'create_format_'

### ISSUE THREAD

**Issue by valeriylo** [dmlc/dgl#2066]
Hey, I cloned whole dgl repo and tried to run pytorch graphsage example, this command to be exact:
 ` python3 train_sampling.py --num-epochs 30` 
and got this error:

```
Traceback (most recent call last):
 File "train_sampling.py", line 232, in <module>
    train_g.create_format_()
AttributeError: 'DGLGraph' object has no attribute 'create_format_'
```

I am running Ubuntu 20.04, Python 3.8

**Comment by VoVAllen** [comment]
Hi,

Please install the nightly build version by `pip install --pre dgl` or `pip install --pre dgl-cuXX`
