### ISSUE TITLE
Cannot load the PTC dataset via dgl.data.GINDataset

### ISSUE THREAD

**Issue by Kqiii** [dmlc/dgl#2087]
Hi,

I encountered a bug when loading the PTC dataset through [dgl.data.GINDataset](https://docs.dgl.ai/api/python/data.html#dgl.data.GINDataset). My dgl version is 0.4.3post2.
Please see the screenshot:
<img width="1225" alt="Screen Shot 2020-08-21 at 7 17 21 PM" src="https://user-images.githubusercontent.com/38380341/90885126-94197880-e3e3-11ea-816f-308fe6269e30.png">

Thank you!

**Comment by VoVAllen** [comment]
Hi,

I made a fix at https://github.com/dmlc/dgl/pull/2103. I check the original author's code. If we follow the preprocessing there, the result of MUTAG would be changed (the labels will be relabeled, however this shouldn't change the final result). Therefore I did a slight change to avoid that, which you can find the comment in the codes

**Comment by Kqiii** [comment]
@VoVAllen Hi,
Thank you very much for your help!
