### ISSUE TITLE
Attributes of different nodes are identical in MUTAG and PROTEINS dataset

### ISSUE THREAD

**Issue by Kqiii** [dmlc/dgl#2093]
Hi,

I notice that the node attribute vectors for different nodes are identical in the MUTAG and PROTEINS dataset provided by [dgl.data.GINDataset](https://docs.dgl.ai/api/python/data.html#graph-isomorphism-network-dataset).

Please see the following figure that is a screenshot of my Ipython history.
![Xnip2020-08-22_10-39-45](https://user-images.githubusercontent.com/38380341/90947580-78f14c00-e469-11ea-89d7-12876a24f166.jpg)

Besides, I notice that there is a 'label' value for every node in a graph provided by dgl. E.g. for the first graph in PROTEINS, the node labels are:
<img width="801" alt="Screen Shot 2020-08-22 at 11 23 08 AM" src="https://user-images.githubusercontent.com/38380341/90947628-e1d8c400-e469-11ea-826d-a664aa3ffa6d.png">
We can see the node labels are different, though the node attributes are identical. Specially, the first 22 nodes belong to class 0, and the following nodes belong to class 1. See the screen shot below:
<img width="1447" alt="Screen Shot 2020-08-22 at 11 25 16 AM" src="https://user-images.githubusercontent.com/38380341/90947690-6592b080-e46a-11ea-9079-6d3bd0b084bc.png">

This accords with the first graph of PROTEINS provided by pyg, where the attributes for the first 22 nodes are [1,0,0], and the following nodes all have attributes [0,1,0]. See the screenshot below:
<img width="780" alt="Screen Shot 2020-08-22 at 11 28 36 AM" src="https://user-images.githubusercontent.com/38380341/90947775-126d2d80-e46b-11ea-9725-9144253b8336.png">

I believe the node attributes should not be identical, as these are important information for the neural networks.

Thanks!

**Comment by VoVAllen** [comment]
Hi,

I may need more time to take look into this. However, GINDataset and TUDataset can be different for the same dataset. The main difference may from the preprocessing process, and pyg's TUDataset seems using one-hot node labels as node features.

**Comment by BarclayII** [comment]
The MUTAG dataset looks correct for me:
![image](https://user-images.githubusercontent.com/2978100/91010894-e7730d00-e615-11ea-9f59-a26d1f36b200.png)
Could you try deleting the DGL caches (usually located in `~/.dgl`) and run the program again?

For PROTEINS, I found a bug which will be fixed in #2100 .

**Comment by Kqiii** [comment]
@VoVAllen @BarclayII  Thank you for your reply!
I tried deleting the caches and running again, but the issue persists. I also tried running the same code on other computers and servers, but still encountered this issue.

**Comment by VoVAllen** [comment]
Hi,

We've recently released new version of dgl, could you try update your dgl to v0.5?

**Comment by Kqiii** [comment]
@VoVAllen Hi,
upgrading to v0.5 works for me.
Thank you very much!
