### ISSUE TITLE
[Bug] Context Issue for bfs_edges_generator on GPU Graphs

### ISSUE THREAD

**Issue by mufeili** [dmlc/dgl#2098]
## 🐛 Bug

Got 

> Check failed: csr.indptr->ctx.device_type == source->ctx.device_type (2 vs. 1) : Graph and source should in the same device context

even when both the graph and the source are on the same GPU.

## To Reproduce

```python
import dgl
import torch

device = 'cuda:0'
g = dgl.graph(([1, 2], [3, 4]), device=device)
root_ids = torch.tensor([1, 2]).to(device)
for _ in dgl.bfs_edges_generator(g, root_ids):
    pass
```

## Environment

 - DGL Version (e.g., 1.0): 0.5.0
 - Backend Library & Version (e.g., PyTorch 0.4.1, MXNet/Gluon 1.3): PyTorch 1.5.1
 - OS (e.g., Linux): ubuntu
 - How you installed DGL (`conda`, `pip`, source): pip 
 - Python version: 3.6.10
 - CUDA/cuDNN version (if applicable): 10.2
 - GPU models and configuration (e.g. V100): Tesla T4
 - Any other relevant information:

**Comment by yzh119** [comment]
What if you don't move `root_ids` to gpu?

**Comment by mufeili** [comment]
> What if you don't move `root_ids` to gpu?

It raises the same error.
