### ISSUE TITLE
Heterogeneous graph nodes/edges features

### ISSUE THREAD

**Issue by chengmonk** [dmlc/dgl#2099]
### About Heterogeneous graph!
From the document of DGL, there is an assumption, nodes in the same type have no different features and share the same feature vector, right?   What should I do, if my nodes in one type have different feature, these nodes in one type need different feature vector to distinguish each other.

**Comment by BarclayII** [comment]
Answered in https://discuss.dgl.ai/t/heterogeneous-graph-nodes-edges-features/1217/2
