### ISSUE TITLE
Using DGL(DGL-lifesci) on windows

### ISSUE THREAD

**Issue by Chokerino** [dmlc/dgl#2104]
## To Reproduce

1.Im trying to use Graphein library and while setting up the environment I get the following error. 

`File "d:\desktop2.0\prot\graphein\graphein\construct_graphs.py", line 23, in <module>
    from dgllife.utils import mol_to_bigraph, mol_to_complete_graph, mol_to_nearest_neighbor_graph
  File "D:\Anaconda\envs\myenv\lib\site-packages\dgllife\__init__.py", line 9, in <module>
    from . import model
  File "D:\Anaconda\envs\myenv\lib\site-packages\dgllife\model\__init__.py", line 8, in <module>
    from .model_zoo import *
  File "D:\Anaconda\envs\myenv\lib\site-packages\dgllife\model\model_zoo\__init__.py", line 33, in <module>
    from .acnn import *
  File "D:\Anaconda\envs\myenv\lib\site-packages\dgllife\model\model_zoo\acnn.py", line 14, in <module>
    from dgl import BatchedDGLHeteroGraph
ImportError: cannot import name 'BatchedDGLHeteroGraph' from 'dgl' (D:\Anaconda\envs\myenv\lib\site-packages\dgl\__init__.py)`

## Environment

 - DGL Version (e.g., 1.0):
 - Backend Library & Version (e.g., PyTorch 0.4.1, MXNet/Gluon 1.3):
 - OS (e.g., Linux): Windows 10
 - How you installed DGL (`conda`, `pip`, source): conda
 - Build command you used (if compiling from source):
 - Python version: 3.6
 - CUDA/cuDNN version (if applicable): 10.2
 - GPU models and configuration (e.g. V100):
 - Any other relevant information:

**Comment by Chokerino** [comment]
Facing the same on linux

**Comment by VoVAllen** [comment]
Please use dgl 0.4.3 with dgllife for now. We havn't make if fully compatible with latest dgl v0.5

**Comment by mufeili** [comment]
The master branch of DGL-LifeSci should now be compatible with DGL 0.5 and you can try installing it from source. Meanwhile I'm not sure if Graphein is now compatible with DGL 0.5 and you may use DGL 0.4.3 for the time being.

**Comment by lingxu00** [comment]
Has anyone solved the problem yet？

**Comment by mufeili** [comment]
> Has anyone solved the problem yet？

If you only want to use DGL-LifeSci, the latest version should be compatible with DGL 0.5 now. For graphein, it's undergoing a code refactoring. For the time being, you should be able to use graphein with DGL 0.4.3 and a previous version of DGL-LifeSci, say 0.2.4.
