### ISSUE TITLE
Cora data set is different from PyTorch-Geometric

### ISSUE THREAD

**Issue by nd7141** [dmlc/dgl#2109]
## 🐛 Bug

I can see that the features and labels in Cora dataset are different across two packages. Which one is correct? 

## To Reproduce

For DGL: 
```
from dgl.data import citation_graph as citegrh
def load_cora_data():
    data = citegrh.load_cora()
    features = torch.FloatTensor(data.features)
    labels = torch.LongTensor(data.labels)
    train_mask = torch.BoolTensor(data.train_mask)
    val_mask = torch.BoolTensor(data.val_mask)
    test_mask = torch.BoolTensor(data.test_mask)
    g = DGLGraph(data.graph)
    return g, features, labels, train_mask, val_mask, test_mask
```

For PyG:
```
dataset = 'Cora'
path = './data/Cora/'
dataset = Planetoid(path, dataset, transform=T.NormalizeFeatures())
data = dataset[0]
features = data.x
labels = data.y
```

## Expected behavior
If I compare features for two packages they would be completely different (although having the same shape). Features for DGL have only one 1 per row (so it's one-hot encoded), while for PyG it has different number of 1s per row. 

Moreover, the labels are also different (although having the same number of classes). 
```
(Counter({3: 818, 4: 426, 0: 351, 2: 418, 1: 217, 5: 298, 6: 180}) # PyG,
 Counter({2: 818, 5: 180, 4: 217, 3: 426, 6: 351, 1: 418, 0: 298})) #1595 
```

## Environment

 - DGL Version : 0.5a200512
 - Backend Library & Version (e.g., PyTorch 0.4.1, MXNet/Gluon 1.3): 1.5.0
 - OS (e.g., Linux): Linux
 - Python version: 3

## Additional context

As this is the most common data set, this is a critical issue.

**Comment by classicsong** [comment]
For dgl's cora's feature are normalized.
For the labels, if you look at the numbers there, it is just using a different label mapping.
