### ISSUE TITLE
Usage about dgl.contrib.sampling.EdgeSampler() in v0.5 release

### ISSUE THREAD

**Issue by Francis-Zheng** [dmlc/dgl#2116]
## 📚 Documentation

I need to deploy negative sampling on a graph to construct both positive an negative samples, but I got error when running the following code: 
![image](https://user-images.githubusercontent.com/18651616/91409030-661ab500-e877-11ea-859d-a97e4f03d4e4.png)

the error is like:
![image](https://user-images.githubusercontent.com/18651616/91409342-dd504900-e877-11ea-9649-fc8763daf6ba.png)

Maybe could write a document about how to use negative sampling in v0.5 ? 

Thank you.

**Comment by yzh119** [comment]
Hi, the `EdgeSampler` defined in `dgl.contrib` should be dropped, it's designed for `DGLGraph` class in DGL 0.4.3, which has been deprecated (the DGLGraph class in DGL 0.5 is the alias of `HeteroGraph`).

We will implement new `EdgeSampler` api for DGL 0.5, if you still want to use `dgl.contrib.samping.EdgeSampler`, create your graph using `dgl.DGLGraphStale` (the old DGLGraph api).

**Comment by jermainewang** [comment]
@BarclayII What is the replacement of this EdgeSampler in 0.5?

**Comment by BarclayII** [comment]
We have `dgl.dataloading.EdgeDataLoader` for that purpose.
