### ISSUE TITLE
[RFC][Feature Request] Hashing function for graph index and DGLGraph

### ISSUE THREAD

**Issue by yzh119** [dmlc/dgl#2122]
## 🚀 Feature
Currently the DGLGraph lacks functionality to identify if two graph index object refers to the same graph structure, I think it's helpful to provide a `DGLGraph.hash()` API to expose the hash value of a graph index. If two graphs have the same structure, their graph index hash value would be the same, and vice versa (very likely).

* When do we mean by `same` is two graph structures are created with the same edge lists (in the same order)
  * Change graph formats would not affect the hash value.
  * Change the data frame of a DGLGraph would not affect the hash value.
  * Mutation on graphs (add/remove nodes/edges) would affect hash value.
  * Change the index type (int32/int64) would affect the hash value.
  * The hash value should be deterministic and platform agnostic.

## Pitch

@kira-lin and I'm working on featgraph integration, considering different operators have different best configurations, we allow user to tune the hyperparameters in featgraph by their own.

However, since compling a featgraph op depends on the graph structure. Without a graph identity function such as hash, it's hard to specify a unique configuration for each operator.

**Comment by VoVAllen** [comment]
Do you mean `GraphIndex` or `DGLGraph`?

**Comment by yzh119** [comment]
Exactly.
