### ISSUE TITLE
[Patch Release] 0.5.1

### ISSUE THREAD

**Issue by BarclayII** [dmlc/dgl#2125]
This is a patch release including the following bug fixes and minor features

**Documentation fixes**

* #2081 Reorganize user guide and split chapters into multiple pages
* #2085 #2090 Fix links
* #2091 #2114 User guide on distributed training
* #2096 #2097 Other documentation fixes
* #2086
* #2123 Temporarily remove SSE MXNet tutorial

**Bug fixes**

* #2100 add_edges() crashes if the input tensor is empty
* #2084 Fix distributed GraphSage running with GPU
* #2107 Building with HDFS previously fails
* #2087 Cannot load the PTC dataset via `dgl.data.GINDataset`
* #2076 Empty cuda graph raise error in create_formats_
* #2121 Disable hypersparse memory optimization due to incomplete COO graph support on GPU
* #2115 Fallback to CPU for graph traversal functions on GPU graphs
* #2108 Force `num_workers` and `num_samplers` to be the same for distributed training
* #2118 (#2127 )

**Bug fixes in examples**

* #2119 Bug in using Layer Normalization in RGCN

**New features**

* #2102 5 utility functions that handle raw data features
* #1979 #2117 CUDA 11 support - We will not release binary builds of CUDA 11 for now

**Release changes**

* Linux now requires GCC 5 to build DGL from source.
* DGL now supports Mac 10.9+.

**Comment by jermainewang** [comment]
> #2076 Empty cuda graph raise error in create_formats_

Shall we rename this API to `create_formats_`? The naming is inconsistent with `DGLGraph.formats`. @yzh119 

Since there are many changes, will you just merge the master to 0.5.x branch or do cherry-pick one-by-one?

**Comment by BarclayII** [comment]
If we don't exclude commits I'll just do a merge.

**Comment by yzh119** [comment]
> > #2076 Empty cuda graph raise error in create_formats_
> 
> Shall we rename this API to `create_formats_`? The naming is inconsistent with `DGLGraph.formats`. @yzh119
> 
> Since there are many changes, will you just merge the master to 0.5.x branch or do cherry-pick one-by-one?

I'm okay.

**Comment by BarclayII** [comment]
0.5.1 has been released.
