### ISSUE TITLE
cannot request out_edges() for empty node sets on cuda

### ISSUE THREAD

**Issue by chwan-rice** [dmlc/dgl#2128]
## 🐛 Bug

I'm using the latest DGL version. The following code throws a DGLError: Check failed: dim != 0 (0 vs. 0) : 

``` Python
import dgl
import torch

g = dgl.DGLGraph(([0, 1], [1, 2])).to('cuda:0')
idx = torch.LongTensor([]).to('cuda:0')
g.out_edges(idx)

```

However, if the graph runs on CPU, the code works well. I'm not sure whether this is a bug.

**Comment by VoVAllen** [comment]
Empty tensor should not be allowed in `out_edges` function. Do you have any expected behavior here?

**Comment by chwan-rice** [comment]
Actually, I just feel it's strange that `out_edges` has different behavior on CPU and GPU. It would be better if it returns an empty edge set.

**Comment by chwan-rice** [comment]
A similar problem is found in `out_degrees`

**Comment by BarclayII** [comment]
Should be fixed in master.  Will go into 0.5.2 release.
