### ISSUE TITLE
How to train the adjacency (weight) matrix of the graph as a parameter？

### ISSUE THREAD

**Issue by WeiyiLee6666** [dmlc/dgl#2134]
## ❓ Questions and Help

The previous papers, including implementation, have already established graph structures. But suppose we have n sets of data {𝑥_𝑖,𝑦_𝑖 }_(𝑖=1)^𝑛, where 𝑦_𝑖∈{0,1}, 𝑥_𝑖∈R^(n×F), n is the number of points and F is the feature Number. My idea is to build a graph structure for each 𝑦_𝑖, in which the parameters of the adjacency matrix are randomly initialized and then GCN is performed. How should this be achieved?
Thank you！

**Comment by yzh119** [comment]
Hi @WeiyiLee6666 , could you please elaborate more on "build a graph structure for each y_i"?

**Comment by WeiyiLee6666** [comment]
> Hi @WeiyiLee6666 , could you please elaborate more on "build a graph structure for each y_i"?

Sorry, I didn't make it clear. For a graph classification task, for each graph, we will have the node features of the graph 𝑥_𝑖∈R^(n×F), and the category y_i of each graph. If we know the adjacency matrix in advance, then we can directly GCN convolution. But suppose we don’t know the graph structure, can we use the parameters of the adjacency matrix as trainable parameters to find the optimal adjacency matrix based on backpropagation?
thank you!

**Comment by VoVAllen** [comment]
Hi,

You can take a look on this thread https://discuss.dgl.ai/t/gradient-wrt-input-using-dglgraph/977. The key is to thinking of adjacency matrix as one edata for differentiation. Is this what you want?

**Comment by WeiyiLee6666** [comment]
> Hi,
> 
> You can take a look on this thread https://discuss.dgl.ai/t/gradient-wrt-input-using-dglgraph/977. The key is to thinking of adjacency matrix as one edata for differentiation. Is this what you want?

Thanks for you help!
