### ISSUE TITLE
error with "module 'matplotlib.cbook' has no attribute 'iterable' "

### ISSUE THREAD

**Issue by chaoshengt** [dmlc/dgl#2150]
error with "module 'matplotlib.cbook' has no attribute 'iterable' "
when I run the demo code:
```python
import networkx as nx
# Since the actual graph is undirected, we convert it for visualization
# purpose.
nx_G = G.to_networkx().to_undirected()
# Kamada-Kawaii layout usually looks pretty for arbitrary graphs
pos = nx.kamada_kawai_layout(nx_G)
nx.draw(nx_G, pos, with_labels=True, node_color=[[.7, .7, .7]])
```
my dgl.__version__:  0.5.1
matplotlib.__version__  :3.3.1

**Comment by jermainewang** [comment]
What's your networkx version? It looks like a compatibility issue of networkx with the latest matplotlib. https://stackoverflow.com/questions/63198347/attributeerror-module-matplotlib-cbook-has-no-attribute-iterable

**Comment by chaoshengt** [comment]
thank you @jermainewang ,  I update networkx version to 2.5.
