### ISSUE TITLE
ValueError: Feature size must be a multiplier of num_bases (88). 

### ISSUE THREAD

**Issue by akshayparakh25** [dmlc/dgl#2151]
I am working on **pytorch** **rgcn** link prediction. I modified the code to use locally available datasets. And the link_prediction code was able to replicate the results for **FB15k-237** dataset. But when I tried to use a dataset generated from Wikipedia triples, I get the following error,

`Number of Train data :: 72069`
`Number of Valid data :: 9009`
`Number of Test data :: 9009`
`Number of Nodes  :: 32078`
`Number of relations :: 44`
`Traceback (most recent call last):`
  `File "link_prediction.py", line 288, in <module>`
   ` main(args)`
  `File "link_prediction.py", line 138, in main`
   ` reg_param=args.regularization)`
  `File "link_prediction.py", line 52, in __init__`
   ` num_hidden_layers, dropout, use_cuda)`
  `File "/home/akshay/rgcn-dgl/model.py", line 20, in __init__`
   ` self.build_model()`
  `File "/home/akshay/rgcn-dgl/model.py", line 30, in build_model`
   ` h2h = self.build_hidden_layer(idx)`
  `File "link_prediction.py", line 45, in build_hidden_layer`
  `  dropout=self.dropout)`
 ` File "/home/akshay/pyTorch-env/lib/python3.6/site-packages/dgl/nn/pytorch/conv/relgraphconv.py", line 156, in __init__`
 `   % self.num_bases`
`ValueError: Feature size must be a multiplier of num_bases (88).`

I ran the code using following command,
`python3 link_prediction.py  --dataset "data/Wikipedia/" --gpu 0 --eval-protocol filtered`

Could you please explain how can I resolve the error?

**Comment by VoVAllen** [comment]
Please refer to https://github.com/dmlc/dgl/issues/2110

The hidden size should be the multiplier of num_bases

**Comment by akshayparakh25** [comment]
I got it.
Thanks
