### ISSUE TITLE
Cannot reproduce Deepwalk Example results for ogbl-citation

### ISSUE THREAD

**Issue by qibinc** [dmlc/dgl#2156]
## 🐛 Bug

Link prediction results are constantly **worse** than reported by a significant margin when running deepwalk on ogbl-citation. **The obtained result 81.82 is apparently an outlier from the expected 0.8284 ± 0.0005.** When experimenting multiple times, I constantly get test results around 0.818. Please check if hyper-parameters posted in [DGL deepwalk for ogbl README](https://github.com/dmlc/dgl/tree/master/examples/pytorch/ogb/deepwalk#used-config) are consistent with the highest results or share the deepwalk embeddings for the highest results. @ShawXh Thanks in advance for your help!

## To Reproduce

(Following https://github.com/dmlc/dgl/tree/master/examples/pytorch/ogb/deepwalk#used-config)

```bash
python3 deepwalk.py --ogbl_name ogbl-citation --load_from_ogbl --save_in_pt --output_emb_file embedding.pt --window_size 2 --num_walks 10 --negative 1 --neg_weight 1 --walk_length 80 --batch_size 128 --print_loss --print_interval 1000 --mix --gpus 0 --use_context_weight --num_threads 4 --lap_norm 0.05 --lr 0.1
python3 mlp.py --use_node_embedding
```

### Deepwalk results:

```
Batch 219000 training time: 64.78s loss: 0.1863
Batch 220000 training time: 66.69s loss: 0.1861
Batch 221000 training time: 66.93s loss: 0.1862
Batch 222000 training time: 64.87s loss: 0.1861
Batch 223000 training time: 62.98s loss: 0.1861
Batch 224000 training time: 65.60s loss: 0.1862
Batch 225000 training time: 65.23s loss: 0.1862
Batch 226000 training time: 66.07s loss: 0.1862
Batch 227000 training time: 65.98s loss: 0.1862
Batch 228000 training time: 65.78s loss: 0.1861
Training used time: 12995.00s
Total used time: 13341.13
```

### OGBL results:

```
Run: 01, Epoch: 90, Loss: 0.0318
Run: 01, Epoch: 90, Loss: 0.0318, Train: 0.8838, Valid: 0.8174, Test: 0.8182
Run: 01, Epoch: 91, Loss: 0.0318
Run: 01, Epoch: 92, Loss: 0.0319
Run: 01, Epoch: 93, Loss: 0.0318
Run: 01, Epoch: 94, Loss: 0.0318
Run: 01, Epoch: 95, Loss: 0.0317
Run: 01, Epoch: 96, Loss: 0.0318
Run: 01, Epoch: 97, Loss: 0.0317
Run: 01, Epoch: 98, Loss: 0.0316
Run: 01, Epoch: 99, Loss: 0.0317
Run: 01, Epoch: 100, Loss: 0.0318
Run: 01, Epoch: 100, Loss: 0.0318, Train: 0.8830, Valid: 0.8166, Test: 0.8176
Run 01:
Highest Train: 88.38
Highest Valid: 81.74
  Final Train: 88.38
   Final Test: 81.82
```

## Expected behavior

ogbl-citation
\#params: 757811178(model) + 131841(mlp) = 757943019
MRR
 Highest Train: 0.8994 ± 0.0004
 Highest Valid: 0.8271 ± 0.0003
  Final Train: 0.8991 ± 0.0007
  Final Test: 0.8284 ± 0.0005

## Environment

 - DGL Version (e.g., 1.0): 0.5.0
 - Backend Library & Version (e.g., PyTorch 0.4.1, MXNet/Gluon 1.3): 1.5.0
 - CUDA/cuDNN version (if applicable): 10.1
 - GPU models and configuration (e.g. V100): TITAN X

**Comment by ShawXh** [comment]
Sorry here the parameter settings are given wrongly. You can try this
`python3 deepwalk.py --ogbl_name ogbl-citation --load_from_ogbl --save_in_pt --output_emb_file embedding.pt --window_size 2 --num_walks 10 --negative 1 --neg_weight 1 --walk_length 80 --batch_size 128 --print_loss --print_interval 1000 --mix --gpus 0 --use_context_weight --num_threads 4 --lap_norm 0.03 --lr 0.1
`
Thanks for your reminding

**Comment by qibinc** [comment]
Hi @ShawXh ,

Thanks for your help! We've obtained the desired results. @classicsong  Please also update the parameter setting on DGL https://github.com/dmlc/dgl/tree/master/examples/pytorch/ogb/deepwalk.
