### ISSUE TITLE
edge_softmax function

### ISSUE THREAD

**Issue by yankaiii** [dmlc/dgl#2157]
## To Reproduce

1. Just run the demo codes in dgl.ops.edge_softmax  
1. run the demo: "edge_softmax(g, edata[:4], th.Tensor([0,1,2,3]))"
1. Got the error: "gidx = gidx.edge_subgraph(eids.type(gidx.dtype), True)
ValueError: invalid type: 'int64'"

## Expected behavior

eids.type may not accept the type from gidx.dtype, where gidx.dtype is a string and eids.type() can only accept objects like torch.int32. So in order to correctly create the subgraph here, edge_subgraph may accept the tensor-typed index? Look forward to your reply. Thx!

## Environment

 - DGL Version: latest
 - PyTorch: 1.6.0
 - OS (e.g., Linux): windows
 - How you installed DGL (`conda`, `pip`, source): conda
 - Build command you used (if compiling from source):
 - Python version:3.8.5

**Comment by yzh119** [comment]
@yankaiii , thanks for reporting this bug, will fix it soon.
