### ISSUE TITLE
[feature request] API to query DGL allocated memory

### ISSUE THREAD

**Issue by yzh119** [dmlc/dgl#2158]
## 🚀 Feature
`dgl.memory_stats(device)` that returns the memory allocated via DGL on a given device. 

## Motivation
DGL has its own memory allocation mechanism which is seperated from backend frameworks, in PyTorch, the `torch.cuda.max_memory_cached` API cannot get accurate GPU memory usage of a model written in DGL.

Reference:
* PyTorch's memory_stats function: https://pytorch.org/docs/stable/cuda.html#torch.cuda.memory_stats

## Implementation

Maintain the size of total allocated memory in `AllocWorkspace` function and `FreeWorkspace` function: https://github.com/dmlc/dgl/blob/870da747eaee96313aa798806a22573ea1e1e8eb/src/runtime/workspace_pool.cc.

**Comment by BarclayII** [comment]
This doesn't count the memory allocated by `AllocDataSpace` or `NDArray::Empty`.  I guess a better solution if possible would be using the framework-specific allocator.

**Comment by jermainewang** [comment]
Closed. DGL now can use backend frameworks' allocators so it also supports querying memory usage using backend APIs.
