### ISSUE TITLE
The dgl.data.TUDataset class returns labels in {0,2} for some binary classes. Can we instead return {0, 1}? 

### ISSUE THREAD

**Issue by HenryKenlay** [dmlc/dgl#2165]
## 🚀 Feature
The graph class labels returned by some binary TUDatasets are {0, 2} (such as `dgl.data.TUDataset('BZR')`. Some datasets are {0, 1} such as `dgl.data.TUDataset('MCF-7')`. It would be good if this behaviour was more consistent.  

## Motivation

By having consistent behaviour users wouldn't have to wrap the class in a preprocessing layer to make sure the labels are consistent with standard conventions (such as a model using a logistic activation function for binary prediction models with binary cross-entropy loss). 

I did notice that in the notes section of the docs it reads 

> Graphs may have node labels, node attributes, edge labels, and edge attributes, varing from different dataset. This class does not perform additional process.

However, this isn't actually the case since the raw BZR graph labels are {-1, 1}, the labels are preprocessed by adding the minimum label to all labels. 

## Alternatives

Do not modify the graph labels at all, as per the docs.

## Pitch

Preprocessing the labels so that the labels are `{0, ..., n-1}` where `n` is the number of classes would be the easiest for the user. An additional argument could be added which allows the user to access the `raw` labels if needed. 

## Additional context

I can put in a pull request if this change seems reasonable.

**Comment by classicsong** [comment]
hi, HenryKenlay:
    Can you help provide this feature. Currently, we just let the label id start from 0: https://github.com/dmlc/dgl/blob/b10b541c11ec4fe9afc722c559aa60fde08bd17d/python/dgl/data/tu.py#L320-L330

    Your help is really appreciated.

**Comment by BarclayII** [comment]
Fixed in #2173
