### ISSUE TITLE
Cannot assign node feature "h" on device /gpu:0 to a graph on device /cpu:0. Call DGLGraph.to() to copy the graph to the same device

### ISSUE THREAD

**Issue by 15151874182** [dmlc/dgl#2171]
## ❓ Questions and Help

(Pdb) l 80
 75  	        graph = nx.from_numpy_matrix(L)
 76  	        g = dgl.DGLGraph(graph)
 77  	        input_shape = (177, 9)
 78  	        input_layer = tf.ones((177,9))
 79  	 #       input_layer = tfk.Input(shape = input_shape, name="input_obs")
 80  	        #lay1 = tfkl.Dense(self.observation_size * 2, name="fc_1")(input_layer)
 81  	        conv = GraphConv(9, 2, norm='both', weight=True, bias=True)
 82  	        pdb.set_trace()
 83  ->	        res = conv(g, input_layer)
 84  	        print(res)
 85  	
(Pdb) res = conv(g, input_layer)
*** dgl._ffi.base.DGLError: Cannot assign node feature "h" on device /gpu:0 to a graph on device /cpu:0. Call DGLGraph.to() to copy the graph to the same device.
(Pdb) g.to('cuda:0')
*** ValueError: Unknown attribute: 'cuda' in 'cuda:0'

Hello,how can i put grahp on '/gpu:0', I tried g.to('cuda:0'),unknown. I tried g.to('/gpu:0'),but g.device is still '/cpu:0',could u give me a example of how to use DGLGraph.to() as mentioned,thx

**Comment by VoVAllen** [comment]
Are you using tensorflow? Did you set `DGLBACKEND=tensorflow` as environment variable?

**Comment by 15151874182** [comment]
> Are you using tensorflow? Did you set `DGLBACKEND=tensorflow` as environment variable?

**Comment by 15151874182** [comment]
> Are you using tensorflow? Did you set `DGLBACKEND=tensorflow` as environment variable?

Yes,I changed the config.json from pytorch to tensorflow

**Comment by VoVAllen** [comment]
Could you try run `python -m dgl.backend.set_default_backend tensorflow` and see whether the problem still exists?

**Comment by wjw1309397040** [comment]
I use pytorch. The same problem exists.

**Comment by mufeili** [comment]
> I use pytorch. The same problem exists.

Note that moving a `DGLGraph` to a specified device is not an in-place operation, you need to use `g = g.to(device)` rather than `g.to(device)`

**Comment by sevencheung2021** [comment]
> > I use pytorch. The same problem exists.
> 
> Note that moving a `DGLGraph` to a specified device is not an in-place operation, you need to use `g = g.to(device)` rather than `g.to(device)`.

i have the same problem ，but  i can not fix it

**Comment by VoVAllen** [comment]
@sevencheung2021 Can you open a new issue and describe your problem there?

**Comment by NitishOritro** [comment]
def construct_graph(adjacency):
    g = DGLGraph()
    adj = pre_adj(adjacency)
    g.add_nodes(adj.shape[0])
    g.add_edges(adj.row,adj.col)
    adjdense = adj.A
    adjd = np.ones((adj.shape[0]))
    for i in range(adj.shape[0]):
        adjd[i] = adjd[i] * np.sum(adjdense[i,:])
    weight = torch.from_numpy(adj.data.astype(np.float32))
    g.ndata['d'] = torch.from_numpy(adjd.astype(np.float32))
    g.edata['w'] = weight

    if args.cuda:
        #g.to(torch.device('cuda:0'))
        g = g.to(device)
        print("args.cuda = True")
    else:
      print("args.cuda = False")
    
    return g
