### ISSUE TITLE
Line graph does not share storage anymore.

### ISSUE THREAD

**Issue by maclandrol** [dmlc/dgl#2174]
## 🐛 Bug

Line graph does not share storage in >=0.5 anymore. 

## To Reproduce

1. Create a line graph with shared storage from initial graph G
2. Modify `ndata` or `edata` of G
3. The changes is not reflected in the line graph

An example here: 

```python
import dgl 
import torch
import numpy as np 
   
def build_karate_club_graph(): 
    # All 78 edges are stored in two numpy arrays. One for source endpoints 
    # while the other for destination endpoints. 
    src = np.array([1, 2, 2, 3, 3, 3, 4, 5, 6, 6, 6, 7, 7, 7, 7, 8, 8, 9, 10, 10, 
    10, 11, 12, 12, 13, 13, 13, 13, 16, 16, 17, 17, 19, 19, 21, 21, 
    25, 25, 27, 27, 27, 28, 29, 29, 30, 30, 31, 31, 31, 31, 32, 32, 
    32, 32, 32, 32, 32, 32, 32, 32, 32, 33, 33, 33, 33, 33, 33, 33, 
    33, 33, 33, 33, 33, 33, 33, 33, 33, 33]) 
    dst = np.array([0, 0, 1, 0, 1, 2, 0, 0, 0, 4, 5, 0, 1, 2, 3, 0, 2, 2, 0, 4, 
    5, 0, 0, 3, 0, 1, 2, 3, 5, 6, 0, 1, 0, 1, 0, 1, 23, 24, 2, 23, 
    24, 2, 23, 26, 1, 8, 0, 24, 25, 28, 2, 8, 14, 15, 18, 20, 22, 23, 
    29, 30, 31, 8, 9, 13, 14, 15, 18, 19, 20, 22, 23, 26, 27, 28, 29, 30, 
    31, 32]) 
    # Edges are directional in DGL; Make them bi-directional. 
    u = np.concatenate([src, dst]) 
    v = np.concatenate([dst, src]) 
    # Construct a DGLGraph 
    return dgl.DGLGraph((u, v)) 
                                                                                                                                 

G = build_karate_club_graph()                                                                                                  
G.ndata['h'] = torch.rand(G.number_of_nodes(), 10)   
line_G = G.line_graph(backtracking=False, shared=True)
G.edata['he'] = torch.rand(G.number_of_edges(), 2)                                                                              
print(line_G.ndata['he'])
```

## Expected behavior

I expect the `line_G` object to have node feature `he`, instead `line_G.ndata` is empty and the last line raises a KeyError 
The above code works fine on dgl<0.5.

## Environment

 - DGL Version: 0.5.1
 - Backend Library & Version (e.g., PyTorch 0.4.1, MXNet/Gluon 1.3):
 - OS: linux
 - How you installed DGL: `conda`
 - Python version: 3.7.6

## Additional context

The newest dgl version broke a lot of code. Although some are easy to fix, this one is not just an API change.

**Comment by BarclayII** [comment]
We have found that sharing the node and edge features may cause additional complexities in composing transformation functions so we changed the semantics of `shared` argument to be just "copies the feature from the original graph to the line graph" instead of "making changes on one side visible to the other".

Could you try updating the features of the line graph's node data using
```
line_G.ndata.update(G.edata)
```
This operation should be very light as there is no actual feature cloning.  See [here](https://github.com/dmlc/dgl/blob/master/examples/pytorch/jtnn/jtnn/mpn.py#L160) in the Junction Tree VAE implementation for example.
