### ISSUE TITLE
[Patch Release] 0.5.2

### ISSUE THREAD

**Issue by BarclayII** [dmlc/dgl#2178]
This is a patch release including the following bug fixes and new models.

**Documentation fixes**
#2172 CoraFull dataset remove redundant reference
#2167 #2177 Fix multiple docstring typos and inconsistencies in `dgl.dataloading` and minibatch training user guide.  (Thanks @ustchhy for reviewing)
#2131 Update Doc for UDFs

**Bug fixes**
#2128 cannot request out_edges() for empty node sets on cuda
#2098 Context Issue for bfs_edges_generator on GPU Graphs
#2135 Pickling a subgraph stores the feature of the original graph
#2137 0.5.x taking too much shared memory during multiprocess training
#2145 dgl.batch() in 0.5.x is slower than 0.4.x
#2157 edge_softmax function not working on subgraphs
#2161 #2165 #2173 TUDataset (Thanks @HenryKenlay)
#2175 Messages not ordered by edge IDs in degree bucketing
#2166 Error when call apply_edges for dec_graph
#2169 Multiprocessing neighbor sampling sometimes have the memory corrupted
#2106 Bad file descriptor error when saving dgl graph to HDFS

**Bug fixes in examples**
#2143 Fix unsupervised graphsage

**New examples**
#2153 GCN on OGB-Arxiv (Thanks @Espylapiza )

**Comment by VoVAllen** [comment]
https://github.com/dmlc/dgl/pull/2155 now checks all the relation graphs should be on the same device
