### ISSUE TITLE
format of input file for rcgn

### ISSUE THREAD

**Issue by monaalsh** [dmlc/dgl#2181]
For the rcgn examples, how to use it for my own dataset instead of  the available example kg?
What is the format of the input files?

**Comment by classicsong** [comment]
You can look at here on how we process the builtin kg dataset.
Basically the input file is just list of triplets (head, rel, tail)

**Comment by classicsong** [comment]
> Thank you, but where can I find the information about input files training, validation and testing.
> Do knowledge graphs entities get mapped to some IDs first as in other libraries?
> I need to see where such information about input files are documented, so I can follow the exact format.

You can just run the example and the data will be downloaded automatically.

Here is another example of how I load the data of wn18: https://github.com/classicsong/dgl-graphloader/blob/master/examples/wn18/wn18.py. The data only contains train.txt, valid.txt and test.txt.

**Comment by monaalsh** [comment]
I meant for user own data?

**Comment by classicsong** [comment]
> I meant for user own data, not the pre-packaged dataset?

you just need to follow the data format of the pre-packaged dataset. And use the same methods to parse it into DGLGraph.

**Comment by monaalsh** [comment]
That would do it, but wouldn't be much better to have it 
documented somewhere!
