### ISSUE TITLE
A bug in the example code of ogbn-arxiv dataset

### ISSUE THREAD

**Issue by Kqiii** [dmlc/dgl#2183]
Hi,

I encountered a bug when directly running [the example ogbn-arxiv code](https://github.com/dmlc/dgl/tree/master/examples/pytorch/ogb/ogbn-arxiv). My dgl version is 0.5.1. Please see below:
<img width="966" alt="Screen Shot 2020-09-12 at 11 17 27 AM" src="https://user-images.githubusercontent.com/38380341/92985922-943ffc00-f4e9-11ea-922a-7fa293da51fa.png">

Thanks!

**Comment by VoVAllen** [comment]
Thanks. It should be `create_formats_` in the latest dgl

**Comment by Kqiii** [comment]
> Thanks. It should be `create_formats_` in the latest dgl

Thank you for your help!
