### ISSUE TITLE
How does SpMM kernel work?

### ISSUE THREAD

**Issue by khaled-rahman** [dmlc/dgl#2189]
Hi,
I have understood the SDDMM kernel; however, I am facing a problem in the SpMM kernel. I am giving an example below:
```
>>> import dgl
>>> from dgl.sparse import _gsddmm
>>> dg = dgl.graph(([0, 0, 1, 1, 2, 3], [1, 2, 2, 4, 3, 4]))
>>> gv
tensor([[0.4232, 0.9601, 0.8417, 0.1231, 0.8972],
        [0.3720, 0.4548, 0.9230, 0.5866, 0.0704],
        [0.0403, 0.9350, 0.1792, 0.2651, 0.8910],
        [0.3374, 0.5880, 0.0425, 0.0515, 0.2620],
        [0.5516, 0.6965, 0.6732, 0.0291, 0.2540]])
>>> _gsddmm(dg._graph, "dot", gv, gv, lhs_target='u', rhs_target='v')
tensor([[1.5063],
        [1.8976],
        [0.8239],
        [1.1783],
        [0.8181],
        [0.6924]])
```
No problem in sddmm kernel.
However, for SpMM, it shows like the following:
```
>>> from dgl.sparse import _gspmm
>>> dg.edges()
(tensor([0, 0, 1, 1, 2, 3]), tensor([1, 2, 2, 4, 3, 4]))
>>> _gspmm(dg._graph, "add", "sum", gv, gv[dg.edges()[0]])
(tensor([[0.0000, 0.0000, 0.0000, 0.0000, 0.0000],
        [0.8463, 1.9202, 1.6834, 0.2462, 1.7944],
        [1.5903, 2.8298, 3.5294, 1.4194, 1.9353],
        [0.0806, 1.8699, 0.3584, 0.5301, 1.7819],
        [1.4188, 2.0856, 1.9310, 1.2763, 0.6650]]), (None, None))
>>> _gspmm(dg._graph, "mul", "sum", gv, gv[dg.edges()[0]])
(tensor([[0.0000, 0.0000, 0.0000, 0.0000, 0.0000],
        [0.1791, 0.9218, 0.7085, 0.0152, 0.8050],
        [0.3174, 1.1286, 1.5604, 0.3593, 0.8100],
        [0.0016, 0.8742, 0.0321, 0.0703, 0.7938],
        [0.2522, 0.5526, 0.8537, 0.3468, 0.0736]]), (None, None))
```

I am not able to interpret the results of _gspmm kernel. Could you please help me understand the output of these two functions calls? Specifically, why the first row has zero elements, and how other rows are being calculated? It would be great if you can provide a tutorial link to understand the output. Thank you so much for your time.

**Comment by yzh119** [comment]
Firstly, we suggest user using `gspmm` and `gsddmm` API in `dgl.ops`, functions defined in `dgl.sparse` is designed for internal use.

For your question, `gspmm(dg, 'add', sum', gv, gv[dg.edges()[0]])` is equivalent to:
```
msg = gsddmm(dg, 'add', gv, gv[dg.edges()[0]], lhs_target='u', rhs_target='e')
rst = copy_e_sum(dg, msg)
```
where the `copy_e_sum` is equivalent to `gspmm(dg, 'copy_rhs', 'sum', None, msg)` i.e. copying the message to destination nodes and aggregate them by summation.

Likewise for `mul`.

**Comment by khaled-rahman** [comment]
Thank you so much @yzh119 
This is really helpful.
Actually, I am developing a new kernel in DGL. That's why I am using those functions.

**Comment by yzh119** [comment]
Wow, that's cool. Actually we (DGL team) also have some updates on kernels, you can check PR #2136 and [this paper](https://arxiv.org/pdf/2008.11359.pdf) for more details.

**Comment by khaled-rahman** [comment]
Hi @yzh119 , I was wondering to ask you regarding the general sparse-dense matrix multiplication using SpMM.
Suppose, I want to perform `Z = XY` using SpMM, where `X` is a sparse N x N matrix and `Y` is a dense N x M matrix. I can accurately reproduce the results using just `gspmm` function. What parameter should I pass to the function? The output should be a N x M matrix. Your suggestion would be much appreciated. Thank you.

**Comment by khaled-rahman** [comment]
I resolved it.
