### ISSUE TITLE
Is there a way to message passing from target to source?

### ISSUE THREAD

**Issue by kyawlin** [dmlc/dgl#2193]
## ❓ Questions and Help

Before proceeding, please note that we recommend
using our discussion forum (https://discuss.dgl.ai) for
general questions. As a result, this issue will
likely be CLOSED shortly.

**Comment by kyawlin** [comment]
does dgl.reverse()  have effect on undirected graphs?

**Comment by mufeili** [comment]
> does dgl.reverse() have effect on undirected graphs?

Given an arbitrary graph `g`, `dgl.reverse(g)` simply returns a new graph with all edges reversed. For more details, see the [doc](https://docs.dgl.ai/generated/dgl.reverse.html#dgl.reverse). 

For a workaround of message passing from target to source, you can first apply `dgl.reverse` to get the reverse graph and then perform message passing on the reverse graph.
