### ISSUE TITLE
"Graph Contrastive Coding" author code doesn't work with latest dgl version

### ISSUE THREAD

**Issue by DoThingYo** [dmlc/dgl#2194]
Sorry for the inconvenience I might cause.

But I got the problem as title. I am using python3.6, ubuntu18.04, pytorch1.4, cuda10.0. Please assist me with this problem. I just wonder what's wrong with the setting

**Comment by DoThingYo** [comment]
This is the concrete information:

(pytorch) dothingyo@dothingyo-G3-3590:~/Documents/GCC-master$ python train.py
Using backend: pytorch
/home/dothingyo/anaconda3/envs/pytorch/lib/python3.6/site-packages/dgl/base.py:45: DGLWarning: Detected an old version of PyTorch. Suggest using torch>=1.5.0 for the best experience.
  return warnings.warn(message, category=category, stacklevel=1)
Traceback (most recent call last):
  File "train.py", line 26, in <module>
    from gcc.datasets import (
  File "/home/dothingyo/Documents/GCC-master/gcc/datasets/__init__.py", line 1, in <module>
    from .graph_dataset import (
  File "/home/dothingyo/Documents/GCC-master/gcc/datasets/graph_dataset.py", line 22, in <module>
    import dgl.nodeflow
ModuleNotFoundError: No module named 'dgl.nodeflow'

**Comment by VoVAllen** [comment]
Hi,

nodeflow is removed in the latest dgl version. Which model are you looking for?

**Comment by DoThingYo** [comment]
> Hi,
> 
> nodeflow is deprecated in the latest dgl version. Which model are you looking for?

Thank you very much for your reply.

I am see this one "https://github.com/THUDM/GCC". It use nodeflow.

**Comment by VoVAllen** [comment]
Hi,

You can use `pip install 'dgl-cuXX<0.5'` to install old dgl version. We'll try to work with author to update the code

**Comment by DoThingYo** [comment]
> Hi,
> 
> You can use `pip install 'dgl-cuXX<0.5'` to install old dgl version. We'll try to work with author to update the code

Thank you very much for your reply!

It means the command "dgl-cu10.0<0.5" ? or use "dgl-cu10.0=0.4" or something else? Could you please give me a specific example? I am using python3.6, ubuntu18.04, pytorch1.4, cuda10.0. 

So nice of you to collaborate with author to update the code!

**Comment by VoVAllen** [comment]
Hi, `pip install 'dgl-cu100<0.5'` should work

**Comment by DoThingYo** [comment]
> Hi, `pip install 'dgl-cu100<0.5'` should work

Ok, I will try it. Thank you very much for your help!

**Comment by Mrslock** [comment]
> Hi, `pip install 'dgl-cu100<0.5'` should work

It solves my problem too, thx a lot~

**Comment by Austinzhenghua** [comment]
Hi, I still can not run this code, can you give me some hlep? Thanks a lot!

**Comment by Austinzhenghua** [comment]
E   OSError: libcudart.so.10.0: cannot open shared object file: No such file or directory
 the error like this, what's wrong with it?

**Comment by jermainewang** [comment]
It looks like you don't have CUDA 10.0 installed. Could you please double check? Also, since this requires a pretty old DGL version, our support will be limited.

**Comment by Austinzhenghua** [comment]
Thank you so much. by the way can I have your wechat then we can talk about the problems we interested in. my is HuaWithTut hua zheng ***@***.*** 签名由 网易邮箱大师 定制 On 06/21/2021 15:30, Minjie Wang wrote: It looks like you don't have CUDA 10.0 installed. Could you please double check? Also, since this requires a pretty old DGL version, our support will be limited. — You are receiving this because you commented. Reply to this email directly, view it on GitHub, or unsubscribe.

**Comment by Austinzhenghua** [comment]
OSError: libcudart.so.10.0: cannot open shared object file: No such file or directory
I also get this error information, pls tell me how can i solve it?

**Comment by Austinzhenghua** [comment]
> It looks like you don't have CUDA 10.0 installed. Could you please double check? Also, since this requires a pretty old DGL version, our support will be limited.

Only CUDA 10.0 can be used? My CUDA is 10.1

**Comment by Austinzhenghua** [comment]
> Sorry for the inconvenience I might cause.
> 
> But I got the problem as title. I am using python3.6, ubuntu18.04, pytorch1.4, cuda10.0. Please assist me with this problem. I just wonder what's wrong with the setting

Hi, my CUDA is 10.1 and I got another error:"OSError: libcudart.so.10.0: cannot open shared object file: No such file or directory"
Do you know how to solve it? Should I change my CUDA to 10.0? Thank you!

**Comment by VoVAllen** [comment]
@Austinzhenghua Can you try `pip install 'dgl-cu101<0.5'`

**Comment by Austinzhenghua** [comment]
> @Austinzhenghua Can you try `pip install 'dgl-cu101<0.5'`?

Yes，I have got the right dgl. maybe there are some CUDA problem, problem about cudnn
