### ISSUE TITLE
RuntimeError in examples/pytorch/GATNE-T: element 0 of tensors does not require grad and does not have a grad_fn

### ISSUE THREAD

**Issue by sangyx** [dmlc/dgl#2196]
If I run the code in CPU, there is an error: 

```bash
Using backend: pytorch
Namespace(att_dim=20, batch_size=64, dimensions=200, edge_dim=10, epoch=100, eval_type='all', features=None, input='data/example', negative_samples=5, neighbor_samples=10, num_walks=20, patience=5, schema=None, walk_length=10, window_size=5)
We are loading data from: data/example/train.txt
Total training nodes: 511
We are loading data from: data/example/valid.txt
We are loading data from: data/example/test.txt
epoch 0:   0%|| 0/7066 [00:00<?, ?it/s]
Traceback (most recent call last):
  File "src/main.py", line 394, in <module>
    average_auc, average_f1, average_pr = train_model(training_data_by_type)
  File "src/main.py", line 291, in train_model
    loss.backward()
  File "/Users/yusang/miniconda3/envs/gatne/lib/python3.7/site-packages/torch/tensor.py", line 185, in backward
    torch.autograd.backward(self, gradient, retain_graph, create_graph)
  File "/Users/yusang/miniconda3/envs/gatne/lib/python3.7/site-packages/torch/autograd/__init__.py", line 127, in backward
    allow_unreachable=True)  # allow_unreachable flag
RuntimeError: element 0 of tensors does not require grad and does not have a grad_fn
```

But if I run the code in GPU, it works fine.

**Comment by yzh119** [comment]
Hi @sangyx I've not successfully reproduced the error you encountered.
Would you mind telling us what version of DGL you were using? btw, it would be helpful if you also introduce how do you run the code in CPU (I use `CUDA_VISIBLE_DEVICES=-1` to hide the GPU).

**Comment by sangyx** [comment]
I use dgl on my mac. The version is `dgl                       0.5.2                    py37_0    dglteam`

**Comment by yzh119** [comment]
Do you have the same problem with Linux on CPU?

**Comment by sangyx** [comment]
No. I haven't tested it in Linux.

**Comment by yzh119** [comment]
I did not reproduce this error on my mac as well.
Can you confirm that your GATNE-T code is not out-dated? I noticed that the line 291 and line 394 are different from our example on master branch (https://github.com/dmlc/dgl/blob/master/examples/pytorch/GATNE-T/src/main.py).

**Comment by sangyx** [comment]
Thanks for your response. I think it is the problem. I have fixed it by using the new code.
