### ISSUE TITLE
GINDataset cannot be displayed correctly in the doc.

### ISSUE THREAD

**Issue by Kqiii** [dmlc/dgl#2214]
Hi, there might be something wrong the [GINDataset](https://docs.dgl.ai/en/latest/api/python/dgl.data.html?highlight=tud#graph-isomorphism-network-dataset) in the doc.

It is shown as:
https://docs.dgl.ai/en/latest/api/python/dgl.data.html?highlight=tud#graph-isomorphism-network-dataset

The source code of this dataset is also not accessible.

Thank you!

**Comment by mufeili** [comment]
This should be addressed in #2217 .

**Comment by Kqiii** [comment]
> This should be addressed in #2217 .

Hi, thank you for your reply!
