### ISSUE TITLE
Optimized DGL Kernels?

### ISSUE THREAD

**Issue by khaled-rahman** [dmlc/dgl#2222]
Hi there,

Thank you for this awesome library. I was wondering to ask you about the optimized kernel of DGL. I was looking at the [FeatGraph](https://arxiv.org/pdf/2008.11359.pdf) paper. I saw a link there that mentions the repository of the FeatGraph (https://github.com/dglai/FeatGraph); however, I could not locate the repository. Basically, we are developing an optimized kernel (intrinsic version) for CPU in DGL as it is now being widely used. It would be great to compare the results of your optimized kernel. If you have any suggestions/comments, that would be appreciable.

Best,
Khaled

**Comment by yzh119** [comment]
Part of FeatGraph's source code is included in https://github.com/dmlc/dgl/pull/2136.
The full repo would be released recently.
