### ISSUE TITLE
some error in the tutorial doc of 0.5.x

### ISSUE THREAD

**Issue by annihi1ation** [dmlc/dgl#2224]
## 📚 Documentation

the codes in this section cannot run, and there is even a bug in the model definition. Also, there is no 'feats' in the batched_graph!

here is the link:
https://docs.dgl.ai/guide/training-graph.html#writing-neural-network-model

**Comment by annihi1ation** [comment]
looking forwards your reply

**Comment by mufeili** [comment]
Could you take a look at #2225 and see if it addresses the problem?

**Comment by annihi1ation** [comment]
thank a lot<3
or more intimately:
谢谢大佬orz
