### ISSUE TITLE
Cannot import name’BatchedDGLHeteroGraph’ from’dgl’ 

### ISSUE THREAD

**Issue by lingxu00** [dmlc/dgl#2226]
## ❓ Questions and Help

When I installed dgl, I got the error “cannot import name’BatchedDGLHeteroGraph’ from’dgl’”, see the picture for details, I don’t know why
![image](https://user-images.githubusercontent.com/39981676/93989771-ea038680-fdbc-11ea-8aab-87cc43ffb044.png)
Environment
DGL Version :0.5.2
Backend Library & Version :PyTorch 1.5.0
OS (e.g., Linux): Linux
How you installed DGL ( conda , pip , source): conda
Build command you used (if compiling from source):
Python version: 3.7
CUDA/cuDNN version (if applicable): 10.1
GPU models and configuration (e.g. V100):
Any other relevant information:

**Comment by lingxu00** [comment]
after I do the "conda install -c dglteam dgl-cuda10.1  ","sudo apt-get update" and
"sudo apt-get install -y build-essential python3-dev make cmake", I got the error "CMake Error: The source directory "/home/admin/anaconda3/envs/dgl" does not appear to contain CMakeLists.txt.
Specify --help for usage, or press the help button on the CMake GUI.
"
![image](https://user-images.githubusercontent.com/39981676/94003599-0825b280-fdce-11ea-8203-7843718ede98.png)

![image](https://user-images.githubusercontent.com/39981676/94003584-ff34e100-fdcd-11ea-8213-60a8b2e5f69f.png)

**Comment by lingxu00** [comment]
@Mufei Li

**Comment by lingxu00** [comment]
@mufeili

**Comment by classicsong** [comment]
When you do
```
>>> g1 = dgl.heterograph({
...         ('user', 'follows', 'user'): ([0, 1], [1, 2]),
...         ('user', 'plays', 'game'): ([0, 1], [0, 0])
...     })
>>> g2 = dgl.heterograph({
...         ('user', 'follows', 'user'): ([0, 1], [1, 2]),
...         ('user', 'plays', 'game'): ([0, 1], [0, 0])
...     })
>>> bg1 = dgl.batch([g1, g2])
```
The batched graph bg1 is still a DGLGraph in 0.5.

**Comment by mufeili** [comment]
This should be addressed in https://discuss.dgl.ai/t/cannot-import-namebatcheddglheterograph-fromdgl/1315
