### ISSUE TITLE
Listening port (30050 by default) is not released after server being shut down

### ISSUE THREAD

**Issue by ChenAris** [dmlc/dgl#2227]
## 🐛 Bug

When finishing training in distributed mode, worker 0 will send a "shutdown" message to DistGraphServer to finalize their sender/receiver sockets. However, after shutting down in DistGraphServer side, the port (30050 by default in dgl) is still being listened. 

After checking the code, I guess it it because the "server_socket_" created in "SocketReceiver::Wait" is never closed when calling "SocketReceiver::Finalize". Please correct me if I am wrong.

## To Reproduce

In "dgl/python/distributed/rpc_server.py", sleep 30s at the end of the code (after breaking the last while loop) and check if port 30050 is being used.

## Expected behavior

The port is available after finalizing the sockets of DistGraphServer.
## Environment

 - DGL Version (e.g., 1.0): 0.5.2
 - Backend Library & Version (e.g., PyTorch 0.4.1, MXNet/Gluon 1.3): PyTorch 1.4
 - OS (e.g., Linux): Linux
 - How you installed DGL (`conda`, `pip`, source): pip
 - Build command you used (if compiling from source):
 - Python version: 3.8
 - CUDA/cuDNN version (if applicable): no
 - GPU models and configuration (e.g. V100): no
 - Any other relevant information:

## Additional context

Below is the traceback:

[20:53:08] /opt/dgl/src/rpc/network/tcp_socket.cc:69: Failed bind on 10.153.44.134:30050 ,errno=98
Traceback (most recent call last):
  File "train_dist.py", line 324, in <module>
    main(args)
  File "train_dist.py", line 261, in main
    dgl.distributed.initialize(args.ip_config, args.num_servers, num_workers=args.num_workers)
  File "/usr/local/lib/python3.8/site-packages/dgl/distributed/dist_context.py", line 101, in initialize
    serv.start()
  File "/usr/local/lib/python3.8/site-packages/dgl/distributed/dist_graph.py", line 294, in start
    start_server(server_id=self.server_id,
  File "/usr/local/lib/python3.8/site-packages/dgl/distributed/rpc_server.py", line 70, in start_server
    rpc.receiver_wait(ip_addr, port, num_clients)
  File "/usr/local/lib/python3.8/site-packages/dgl/distributed/rpc.py", line 152, in receiver_wait
    _CAPI_DGLRPCReceiverWait(ip_addr, int(port), int(num_senders))
  File "dgl/_ffi/_cython/./function.pxi", line 287, in dgl._ffi._cy3.core.FunctionBase.__call__
  File "dgl/_ffi/_cython/./function.pxi", line 222, in dgl._ffi._cy3.core.FuncCall
  File "dgl/_ffi/_cython/./function.pxi", line 211, in dgl._ffi._cy3.core.FuncCall3
  File "dgl/_ffi/_cython/./base.pxi", line 155, in dgl._ffi._cy3.core.CALL
dgl._ffi.base.DGLError: [20:53:08] /opt/dgl/src/rpc/network/socket_communicator.cc:197: Cannot bind to 10.153.44.134:30050

**Comment by VoVAllen** [comment]
Usually this should not happen, the socket is closed by the destructor of a shared pointer, which should be done at most case. The exception could be the process is killed by the system. Did you kill the server manually?

**Comment by ChenAris** [comment]
Actually, it happens when you do not kill the server, on the contrary. If the worker fails, then the server does not exit normally, and its sender socket, receiver socket and "server_socket_" used to listen 30050 port remains unclosed. However, if the worker exits normally, the ShutDownRPCRequest is sent to server, and only sender socket and receiver socket are closed. The "server_socket_" can only be closed when the server is down. We do not want the server being killed, and the problem happens.

I wonder why you close the sender and receiver socket, but leave this listening socket open. Is there any reason for it, e.g., it will be used afterwards?

**Comment by aksnzhy** [comment]
@ChenAris Hi, thanks for reporting this issue. Actually, the server-side will release the port if the server has been shutdown normally. But, we found that when you shut down your server, you cannot restart it immediately (typically you need to wait for 20 seconds). This is because the Linux kernel will not release the port immediately and the waiting time is a kernel argument.

**Comment by aksnzhy** [comment]
@ChenAris If the server is not shutdown normally. e.g., runtime error, the port will not be released normally.

**Comment by ChenAris** [comment]
Thanks for reply. Yes, we also notice the TCP TIME_WAIT and unreleased port issue when server is not shutdown normally.

**Comment by aksnzhy** [comment]
We close the server_socket when the server receives the 'shutdown' message in: https://github.com/dmlc/dgl/blob/master/python/dgl/distributed/rpc.py#L1064

**Comment by ChenAris** [comment]
https://github.com/dmlc/dgl/blob/b885c82f3fafcefb7beb32a543f5764ef1af0452/src/rpc/network/socket_communicator.cc#L244

It seems that this "SocketReceiver::Finalize()" function does not close the "server_socket_". 

BTW, the "server_socket_" here is created here: 
https://github.com/dmlc/dgl/blob/b885c82f3fafcefb7beb32a543f5764ef1af0452/src/rpc/network/socket_communicator.cc#L194

**Comment by aksnzhy** [comment]
You are right. I just fix this issue by: https://github.com/dmlc/dgl/pull/2236

Does this help for your problem?

**Comment by ChenAris** [comment]
Yes, after I manually close the "server_socket_", this port is released. Here comes another problem for my further modification. It may not related to this issue, but I wonder if you have any clue:

**Comment by aksnzhy** [comment]
@VoVAllen I remember you have the same problem about create socket dynamically before?

**Comment by aksnzhy** [comment]
@ChenAris I got your point. You want to make server as a longtime running process, which can dynamically create socket communicator. But I think this is very hack because our distributed training is not designed for that pattern, and many small issue has potential bugs. For example, we use shared-memory file for local communication. If we doesn't kill the process, can we ensure that of the states of shared-memory file are right for the next training?

**Comment by ChenAris** [comment]
Yes, indeed. I understand the difficulties. I will look into it and check which part blocks the training, since this is almost a must if we want to do some experiments on large graph dataset. Thank you for your reply, and you can close this issue.

**Comment by aksnzhy** [comment]
Sure. Feel free to let me know if you have any other questions.
