### ISSUE TITLE
Question about building graph using my own dataset in Transformer

### ISSUE THREAD

**Issue by yl3639** [dmlc/dgl#2229]
## ❓ Questions and Help

Hi dgl team,
I have a question about implementing the transformer on my own dataset.
According to 
https://docs.dgl.ai/en/latest/tutorials/models/4_old_wines/7_transformer.html#graph-structure 
the tutorial of transformer, it seems we need to build the graph with nids['enc'], nids['dec'], eids['ee'], eids['ed'], eids['dd'] so that the transformer can run successfully.

But since I am implementing transformer on my own dataset, I build the graph by myself, but there is error with 

<img width="455" alt="image" src="https://user-images.githubusercontent.com/20362958/94106852-251fad00-fdf1-11ea-95bb-6376d9aa45c5.png">

and my code is like this:
<img width="440" alt="image" src="https://user-images.githubusercontent.com/20362958/94106843-1e913580-fdf1-11ea-92c7-359bd1f4f6e8.png">

May I ask what is the correct way to build my own dataset graph? Thanks a lot!

Before proceeding, please note that we recommend
using our discussion forum (https://discuss.dgl.ai) for
general questions. As a result, this issue will
likely be CLOSED shortly.

**Comment by yl3639** [comment]
<img width="409" alt="image" src="https://user-images.githubusercontent.com/20362958/94107583-a9befb00-fdf2-11ea-835d-4052ba94f6f6.png">

**Comment by yzh119** [comment]
Sorry for the very late reply, would you mind taking a look at the graph construction part of [BPT](https://github.com/yzh119/bpt) which follows the spirit of the transformer tutorial (it is out-dated and no longer maintained)?
