### ISSUE TITLE
run Distributed Server occur core dump

### ISSUE THREAD

**Issue by lixusign** [dmlc/dgl#2230]
I run distServer ，then core dump as follow  why ? thanks

File "/pytorch/graphsage/experimental/train_dist_server.py", line 261, in main
    dgl.distributed.initialize(args.ip_config, args.num_servers, num_workers=args.num_workers)
  File "python3.7/site-packages/dgl-0.6-py3.7-macosx-10.7-x86_64.egg/dgl/distributed/dist_context.py", line 100, in initialize
    os.environ.get('DGL_CONF_PATH'))
  File "python3.7/site-packages/dgl-0.6-py3.7-macosx-10.7-x86_64.egg/dgl/distributed/dist_graph.py", line 270, in __init__
    self.client_g = _copy_graph_to_shared_mem(self.client_g, graph_name)
  File "python3.7/site-packages/dgl-0.6-py3.7-macosx-10.7-x86_64.egg/dgl/distributed/dist_graph.py", line 65, in _copy_graph_to_shared_mem
    new_g.ndata['inner_node'] = _to_shared_mem(g.ndata['inner_node'], local_node_path)
  File "python3.7/site-packages/dgl-0.6-py3.7-macosx-10.7-x86_64.egg/dgl/distributed/shared_mem_utils.py", line 19, in _to_shared_mem
    new_arr = empty_shared_mem(name, True, F.shape(arr), DTYPE_DICT[F.dtype(arr)])
  File "python3.7/site-packages/dgl-0.6-py3.7-macosx-10.7-x86_64.egg/dgl/_ffi/ndarray.py", line 149, in empty_shared_mem
    ctypes.byref(handle)))
  File "python3.7/site-packages/dgl-0.6-py3.7-macosx-10.7-x86_64.egg/dgl/_ffi/base.py", line 62, in check_call
    raise DGLError(py_str(_LIB.DGLGetLastError()))
dgl._ffi.base.DGLError: [15:08:22] dgl/src/runtime/shared_mem.cc:52: Check failed: res != -1 (-1 vs. -1) : Failed to truncate the file. Invalid argument
Stack trace:
  [bt] (0) 1   libdgl.dylib                        0x000000011c9319c0 dmlc::LogMessageFatal::~LogMessageFatal() + 64
  [bt] (1) 2   libdgl.dylib                        0x000000011c8fe0e5 dmlc::LogMessageFatal::~LogMessageFatal() + 21
  [bt] (2) 3   libdgl.dylib                        0x000000011d8f0ba5 dgl::runtime::SharedMemory::CreateNew(unsigned long) + 1061
  [bt] (3) 4   libdgl.dylib                        0x000000011d8d2ef7 dgl::runtime::NDArray::EmptyShared(std::__1::basic_string<char, std::__1::char_traits<char>, std::__1::allocator<char> > const&, std::__1::vector<long long, std::__1::allocator<long long> >, DLDataType, DLContext, bool) + 199
  [bt] (4) 5   libdgl.dylib                        0x000000011d8d4eab DGLArrayAllocSharedMem + 219
  [bt] (5) 6   libffi.6.dylib                      0x000000010444d884 ffi_call_unix64 + 76
  [bt] (6) 7   ???                                 0x00007ffeecb3c8b0 0x0 + 140732869626032

环境如下

Environment
DGL Version (e.g., 1.0): 0.5.2
Backend Library & Version (e.g., PyTorch 0.4.1, MXNet/Gluon 1.3): PyTorch 1.6
OS (e.g., Linux): Linux
How you installed DGL (conda, pip, source): pip
Build command you used (if compiling from source):
Python version: 3.7
CUDA/cuDNN version (if applicable): no
GPU models and configuration (e.g. V100): no
Any other relevant information:

**Comment by aksnzhy** [comment]
@lixusign Can you share your command?

**Comment by lixusign** [comment]
yes， my dist server env as follow  on mac 10.14  
   i only run demo graphsage
  
  here is os env:
    os.environ.setdefault('DGL_ROLE', 'server')
    os.environ.setdefault('DGL_SERVER_ID', '0')
    os.environ.setdefault('DGL_IP_CONFIG', 'ip_config.txt')
    os.environ.setdefault('DGL_NUM_SERVER', '2')
    os.environ.setdefault('DGL_NUM_SAMPLER','1')
    os.environ.setdefault('DGL_NUM_CLIENT', '1')
    os.environ.setdefault('DGL_CONF_PATH', 'data/reddit.json')
    os.environ.setdefault('OMP_NUM_THREADS', '1')

 here is option I used：
    parser.add_argument('--num_workers', type=int, default=1)
    parser.add_argument('--num_clients', type=int, help='The number of clients', default=1)
    parser.add_argument('--num_servers', type=int, default=2, help='The number of servers')
    parser.add_argument('--num_gpus', type=int, default=-1)
    parser.add_argument('--graph_name', type=str, help='graph name', default='reddit')

**Comment by lixusign** [comment]
and what a supervised is " I run the server with this config success occasionally"

**Comment by aksnzhy** [comment]
@lixusign Hi, does this issue solved for now?

**Comment by aksnzhy** [comment]
issue solved: https://discuss.dgl.ai/t/0-5-2dgl-coredump-when-run-dist-server/1321/7
