### ISSUE TITLE
What does DGLGraph.is_block mean?

### ISSUE THREAD

**Issue by e-yi** [dmlc/dgl#2231]
## 📚 Documentation
Hi,

`is_blcok` was used [here](https://docs.dgl.ai/en/latest/_modules/dgl/nn/pytorch/conv/gatconv.html) and [a few other places](https://docs.dgl.ai/en/latest/search.html?q=is_block&check_keywords=yes&area=default).

But I can not find any explanations about this property in the documentation.

**Comment by yzh119** [comment]
It identifies whether the given graph is a block (i.e. generated via [`dgl.to_block`](https://docs.dgl.ai/en/latest/generated/dgl.to_block.html?highlight=to_block#dgl.to_block)). You can just ignore it if you are not dealing with subgraphs generated by DGL's sampler.

**Comment by e-yi** [comment]
Thanks for your help! Maybe `DGLBlock` should be included in the document.

**Comment by yzh119** [comment]
Actually the blocks are still DGLGraphs instead of a separate class, yes I agree with you that we should elaborate more on block's behaviour in documentation.

**Comment by jermainewang** [comment]
See https://docs.dgl.ai/tutorials/large/L0_neighbor_sampling_overview.html#sphx-glr-tutorials-large-l0-neighbor-sampling-overview-py for the explanation.
