### ISSUE TITLE
PinSAGE distributed generator object is not callable

### ISSUE THREAD

**Issue by trinayan** [dmlc/dgl#2232]
Hi,

I was trying to implement multi-GPU PinSAGE using Distributed Data Parallel. Unfortunately the line https://github.com/dmlc/dgl/blob/25a8e3f181a78ff3facc1f46ec52c175dfc46850/examples/pytorch/pinsage/model.py#L83 returns an error "generator object is not callable'. On searching online someone encountered similar issues in Pytorch lightning(https://github.com/PyTorchLightning/pytorch-lightning/issues/3379). I am guessing the problem is related to the fact that the samples are generated on the fly in PinSage.  Is there any way to get around this error to get a distributed version of PinSage to work?.

**Comment by aksnzhy** [comment]
Can @BarclayII or @yzh119 help?

**Comment by BarclayII** [comment]
Did you change the definition of `dataloader`?  According to #2159 you probably don't have to change the definition of `dataloader` at all.

**Comment by trinayan** [comment]
@BarclayII : Thanks for getting back. I did not change anything at the dataloader. If you take a look at my code here(https://github.com/trinayan/PinSageMultiGPU/blob/5f326fa4bf5d59eb552bbb0d234c97e813dfb5b1/model.py#L103) its fairly straightforward. All I have done is restructure the code and the wrap the model using DistributedDataParallel. I did not add a new sampler or anything like that. Let me know what are your thoughts after taking a look. And thanks for the help

**Comment by BarclayII** [comment]
Your code works for me.  What was your PyTorch/DGL/CUDA version?

**Comment by trinayan** [comment]
@BarclayII . Thanks for looking. Here is the version info:  Pytorch :1.5.1, DGL 0.5.0, CUDA 10.2
 Just to verify here is the command I executed on my 2 GPU system.  "python3 model.py data.pkl --num-epochs 1 --num-workers 2 --hidden-dims 64 --batch-size 32   -n 1 -g 2 -nr 0 " . The "n,g,nr" are extra options to run in the distributed setting Were you using a similar command?.

**Comment by BarclayII** [comment]
Can you try upgrading DGL to 0.5.2?  I kept the arguments as the default except that `-g` is 2.

**Comment by trinayan** [comment]
Got it . I will try after updating. thank you

**Comment by trinayan** [comment]
Ok I updated and ran into the same problem. this seems like it is connected to torchtext somehow. can you tell what is the torchtext version on your system?

**Comment by BarclayII** [comment]
My torchtext version is 0.5.0.

**Comment by trinayan** [comment]
For anyone having this problem, the solution is to set the params "num-workers to  0" when using multiprocessing with the above example. I revisited this problem recently and @BarclayII  probably did not observe the error  above because he might be using the default num workers which is 0. This seems to be related to using multiple workers inside each process on the pytorch dataloader which is most likely buggy.
