### ISSUE TITLE
missing return 

### ISSUE THREAD

**Issue by andreaapice** [dmlc/dgl#2237]
## 📚 Documentation

I think that in def concat_message_function(edges):
    {'cat_feat': torch.cat([edges.src.ndata['feat'], edges.dst.ndata['feat']])}
misses the return keyword 

https://github.com/dmlc/dgl/blob/0.5.x/docs/source/guide/message.rst

**Comment by mufeili** [comment]
Thank you for the report. This should be fixed in #2247 .
