### ISSUE TITLE
Why DGL 0.5.2 Close Cuda available ? 

### ISSUE THREAD

**Issue by lixusign** [dmlc/dgl#2241]
python -c ‘import torch; import dgl; print(torch.cuda.is_available())’

Using backend: pytorch
False

python -c ‘import torch; print(torch.cuda.is_available())’

True

Environment
DGL Version (e.g., 1.0): 0.5.2
Backend Library & Version (e.g., PyTorch 0.4.1, MXNet/Gluon 1.3): PyTorch 1.6
OS (e.g., Linux): Linux
How you installed DGL (conda, pip, source): pip
Build command you used (if compiling from source):
Python version: 3.6
CUDA/cuDNN version (if applicable): 10.0
GPU models and configuration (e.g. V100): V100
Any other relevant information:

**Comment by lixusign** [comment]
I use dgl-cu100            0.5.2

**Comment by BarclayII** [comment]
Reversing the order of import gives `True` instead:
```python
import dgl
import torch
torch.cuda.is_available()   # True
```

**Comment by lixusign** [comment]
ython -c 'import dgl; import torch; print(torch.cuda.is_available())'
Using backend: pytorch
False

**Comment by BarclayII** [comment]
I tried with torch 1.6 + dgl 0.5.2 + cuda 10.1 and both ways worked without problems.  How did you get torch 1.6 with CUDA 10.0 support?  I didn't see 1.6 showing up in CUDA 10.0 wheels released by PyTorch: https://download.pytorch.org/whl/cu100/torch_stable.html

**Comment by lixusign** [comment]
I compile self , oh  i try 10.1 one more time

**Comment by VoVAllen** [comment]
You need to use conda install dgl if your torch is installed by conda. Because conda will change the rpath of torch's c library to its own cuda release instead of the system one. If you use pip install dgl, the dgl will be linked with system cuda library, which might results a divergence and weird behavior as you mentioned

**Comment by yzh119** [comment]
That's interesting.

**Comment by lixusign** [comment]
3q
