### ISSUE TITLE
one question of guide-training-node-classification

### ISSUE THREAD

**Issue by Stonesusu** [dmlc/dgl#2243]
## ❓ Questions and Help

path:  https://docs.dgl.ai/guide/training-node.html#guide-training-node-classification
"
node_features = {'user': user_feats, 'item': item_feats}
h_dict = model(hetero_graph, {'user': user_feats, 'item': item_feats})
h_user = h_dict['user']
h_item = h_dict['item']
"

can it be changed to 
"
node_features = {'user': user_feats, 'item': item_feats}
h_dict = model(hetero_graph, node_features)
h_user = h_dict['user']
h_item = h_dict['item']
"
?

**Comment by BarclayII** [comment]
You are right.
