### ISSUE TITLE
[Doc] Missing Doc for NodeCollator and EdgeCollator

### ISSUE THREAD

**Issue by mufeili** [dmlc/dgl#2245]
## 🐛 Bug

The API reference manual is missing doc for `NodeCollator` and `EdgeCollator`, which are referenced in many places.

**Comment by BarclayII** [comment]
They are removed in 0.8.

**Comment by lbq8942** [comment]
too bad

**Comment by BarclayII** [comment]
We removed `NodeCollator` and `EdgeCollator` and replaced them with `dgl.dataloading.as_edge_prediction_sampler` in 0.8 which translates a sampler for node classification into another for edge classification and link prediction.
