### ISSUE TITLE
Missing tutorial for SPMV optimization for GAT

### ISSUE THREAD

**Issue by ekagra-ranjan** [dmlc/dgl#2253]
## 📚 Documentation

Tutorial:

Hi,
In the "What's Next section" of this [tutorial](https://docs.dgl.ai/en/latest/tutorials/models/1_gnn/9_gat.html#what-s-next) there is a bullet point saying "The next tutorial describes how to speedup GAT models by parallelizing multiple attention heads and SPMV optimization."

 Is there a doc missing to SPMV optimization of GAT?

**Comment by mufeili** [comment]
Basically the original GAT implementation involves an iteration over the attention heads as [here](https://github.com/PetarV-/GAT/blob/master/models/sp_gat.py#L21). DGL's GAT implementation processes all attention heads in parallel as [here](https://github.com/dmlc/dgl/blob/master/python/dgl/nn/pytorch/conv/gatconv.py#L156).

**Comment by ekagra-ranjan** [comment]
Thanks!
