### ISSUE TITLE
segfault or free(): invalid pointer when importing dgl with other libraries due to RTLD_GLOBAL

### ISSUE THREAD

**Issue by skrsna** [dmlc/dgl#2255]
## 🐛 Bug

importing dgl after importing C++ based library with pybind interface leads to segfault or `free(): invalid pointer`. The C++ library in question is an internal library that is not available publicly. I found some relevant issues on pytorch repo https://github.com/pytorch/pytorch/issues/3059 and https://github.com/RobotLocomotion/drake/issues/12073. I was able to find a workaround by deleting `ctypes.RTLD_GLOBAL` [here ](https://github.com/dmlc/dgl/blob/master/python/dgl/_ffi/base.py#L34) in the dgl source code. Pytorch and tensorflow seemed to move away from RTLD_GLOBAL. ref (https://github.com/pytorch/pytorch/pull/28536). Just wondering if something similar can be done in dgl. 
## To Reproduce
Sorry the library I'm using that causes this error is not available publicly and uses TBB allocator. 

1.
1.
1.

## Expected behavior
import dgl without segfault or `free(): invalid pointer Aborted` 

## Environment

 - DGL Version (e.g., 1.0): 0.5.2 cpu 
 - Backend Library & Version (e.g., PyTorch 0.4.1, MXNet/Gluon 1.3): pytorch 1.7 nightly 
 - OS (e.g., Linux): linux 
 - How you installed DGL (`conda`, `pip`, source): conda 
 - Build command you used (if compiling from source):
 - Python version: 3.8
 - CUDA/cuDNN version (if applicable): 10.2, 7.6
 - GPU models and configuration (e.g. V100): 
 - Any other relevant information:

**Comment by VoVAllen** [comment]
bump this

**Comment by BarclayII** [comment]
Does it immediately crash after importing the said library?

**Comment by skrsna** [comment]
Hi @BarclayII, 

If I import dgl then import the private library, it doesn't crash right away but crashes when there's a call to any dgl functions or the library's functions. On the other hand if I import the library first and then dgl it crashes right away.

**Comment by dgasmith** [comment]
This issue was references in #2328, but then the line was crossed out. I didn't see an immediate reason of why in the issue.

If this is a longer term item, could we introduce an env variable to dynamically change the CDLL load in specific circumstance-- perhaps `DGL_RTLD_SETTING`?

**Comment by BarclayII** [comment]
As I mentioned in the crossed-out text, directly changing `RTLD_GLOBAL` will make some examples freeze.  I wasn't able to figure out the reason yet so I opted for a middle-ground.

**Comment by dgasmith** [comment]
Ah got it. In the meantime would take a PR that allows us to alter this setting via env variable?

**Comment by BarclayII** [comment]
> Ah got it. In the meantime would take a PR that allows us to alter this setting via env variable?

I'm kinda reluctant to do so since deleting the flag may cause other problems.  If you really would like to change it you can patch the file in `site-packages` directory.

**Comment by BarclayII** [comment]
@dgasmith  @skrsna I removed the flag in a recent PR.  Please give the nightly builds a try.  I tested on the GraphSAGE examples and it currently run without any problems.

**Comment by dgasmith** [comment]
@BarclayII Thanks! I really appreciate that, we will evaluate the nightly builds ASAP.

**Comment by BarclayII** [comment]
So far no issues as per our experience.  Please reopen the issue if the problem still exists in your case.
