### ISSUE TITLE
embeddings and relation matrix for rcgn

### ISSUE THREAD

**Issue by xin-zhao0** [dmlc/dgl#2257]
How to get the models learned embeddings for entities and the relation projection matrix for r-cgn after training?

**Comment by mufeili** [comment]
> How to get the models learned embeddings for entities and the relation projection matrix for r-cgn after training?

Any explicit code snippet that you are referring to?

**Comment by xin-zhao0** [comment]
I need to a way to directly access the final model parameters (embedding and relation), so I can use them later to calculate scores between entities using the relations as in the DistMult model scoring function. For example, the output of loading the model and examining its content. we have the following:
```
>>> ch['state_dict'].keys()
odict_keys(['w_relation', 'rgcn.layers.0.embedding.weight', 'rgcn.layers.1.weight', 'rgcn.layers.1.h_bias', 'rgcn.layers.1.loop_weight', 'rgcn.layers.2.weight', 'rgcn.layers.2.h_bias', 'rgcn.layers.2.loop_weight'])
```
It seems that  'w_relation' is the relations embeddings and 'rgcn.layers.0.embedding.weight' has same number of of entities. But is this the final entities embeddings?
 
It would be ideal if I can extract the models parameters (entities and relation embeddings), so I can use them to calculate the scores as in the following:
```
    def calc_score(self, embedding, triplets):
        # DistMult
        s = embedding[triplets[:,0]]
        r = self.w_relation[triplets[:,1]]
        o = embedding[triplets[:,2]]
        score = torch.sum(s * r * o, dim=1)
```

**Comment by classicsong** [comment]
> I need to a way to directly access the final model parameters (embedding and relation), so I can use them later to calculate scores between entities using the relations as in the DistMult model scoring function. For example, the output of loading the model and examining its content. we have the following:
> 
> ```
> >>> ch['state_dict'].keys()
> odict_keys(['w_relation', 'rgcn.layers.0.embedding.weight', 'rgcn.layers.1.weight', 'rgcn.layers.1.h_bias', 'rgcn.layers.1.loop_weight', 'rgcn.layers.2.weight', 'rgcn.layers.2.h_bias', 'rgcn.layers.2.loop_weight'])
> ```
> 
> It seems that 'w_relation' is the relations embeddings and 'rgcn.layers.0.embedding.weight' has same number of of entities. But is this the final entities embeddings?

This is the initial embedding. You should using message passing to generate final embedding for nodes.
w_relation is the final relation embedding.
> 
> It would be ideal if I can extract the models parameters (entities and relation embeddings), so I can use them to calculate the scores as in the following:
> 
> ```
>     def calc_score(self, embedding, triplets):
>         # DistMult
>         s = embedding[triplets[:,0]]
>         r = self.w_relation[triplets[:,1]]
>         o = embedding[triplets[:,2]]
>         score = torch.sum(s * r * o, dim=1)
> ```

**Comment by xin-zhao0** [comment]
How to get the final embeddings for the entities?

**Comment by vino5211** [comment]
any progress with this issue? I am facing the same problem, want to extract node embeddings of a trained rgcn link prediction model.
