### ISSUE TITLE
OSError: libcusparse.so.10: cannot open shared object file: No such file or directory

### ISSUE THREAD

**Issue by ChaoYue0307** [dmlc/dgl#2258]
## 🐛 Bug

When import dgl, just got this error, I already set the pytorch as backend, but still cannot work, system info is described as below.

## To Reproduce
DGL backend not selected or invalid.  Assuming PyTorch for now.
Setting the default backend to "pytorch". You can change it in the ~/.dgl/config.json file or export the DGLBACKEND environment variable.  Valid options are: pytorch, mxnet, tensorflow (all lowercase)
Using backend: pytorch
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "/usr/local/lib/python3.6/dist-packages/dgl/__init__.py", line 14, in <module>
    from .backend import load_backend, backend_name
  File "/usr/local/lib/python3.6/dist-packages/dgl/backend/__init__.py", line 73, in <module>
    load_backend(get_preferred_backend())
  File "/usr/local/lib/python3.6/dist-packages/dgl/backend/__init__.py", line 23, in load_backend
    mod = importlib.import_module('.%s' % mod_name, __name__)
  File "/usr/lib/python3.6/importlib/__init__.py", line 126, in import_module
    return _bootstrap._gcd_import(name[level:], package, level)
  File "/usr/local/lib/python3.6/dist-packages/dgl/backend/pytorch/__init__.py", line 1, in <module>
    from .tensor import *
  File "/usr/local/lib/python3.6/dist-packages/dgl/backend/pytorch/tensor.py", line 11, in <module>
    from ... import ndarray as nd
  File "/usr/local/lib/python3.6/dist-packages/dgl/ndarray.py", line 14, in <module>
    from ._ffi.object import register_object, ObjectBase
  File "/usr/local/lib/python3.6/dist-packages/dgl/_ffi/object.py", line 8, in <module>
    from .object_generic import ObjectGeneric, convert_to_object
  File "/usr/local/lib/python3.6/dist-packages/dgl/_ffi/object_generic.py", line 7, in <module>
    from .base import string_types
  File "/usr/local/lib/python3.6/dist-packages/dgl/_ffi/base.py", line 42, in <module>
    _LIB, _LIB_NAME = _load_lib()
  File "/usr/local/lib/python3.6/dist-packages/dgl/_ffi/base.py", line 34, in _load_lib
    lib = ctypes.CDLL(lib_path[0], ctypes.RTLD_GLOBAL)
  File "/usr/lib/python3.6/ctypes/__init__.py", line 348, in __init__
    self._handle = _dlopen(self._name, mode)
OSError: libcusparse.so.10: cannot open shared object file: No such file or directory

## Expected behavior

shoud be no error

## Environment

 - DGL Version (e.g., 1.0):
 - Backend Library & Version ( PyTorch 1.6.0):
 - OS (Ubuntu18.04):
 - How you installed DGL (pip3 install dgl-cu102):
 - Build command you used (if compiling from source):
 - Python version: 3.6.9
 - CUDA/cuDNN version (10.2):
 - GPU models and configuration (RTX2080Ti):
 - Any other relevant information:

**Comment by yzh119** [comment]
Have you installed cuDNN? (cusparse is a part of cuDNN).

**Comment by ChaoYue0307** [comment]
> Have you installed cuDNN? (cusparse is a part of cuDNN).

![image](https://user-images.githubusercontent.com/9592372/95031526-01117500-06e9-11eb-81e5-8c7290ba75d0.png)
This is when I check my cuDNN with cat /usr/local/cuda/include/cudnn.h | grep CUDNN_MAJOR -A 2

**Comment by jermainewang** [comment]
Could you provide the following information?

* DGL Version (e.g., 1.0):
* Backend Library & Version ( PyTorch 1.6.0):
* OS (Ubuntu18.04):
* How you installed DGL (pip3 install dgl-cu102):
* Build command you used (if compiling from source):
* Python version: 3.6.9
* CUDA/cuDNN version (10.2):
* GPU models and configuration (RTX2080Ti):
* Any other relevant information:

**Comment by ChaoYue0307** [comment]
> Could you provide the following information?
> 
> * DGL Version (e.g., 1.0):
> * Backend Library & Version ( PyTorch 1.6.0):
> * OS (Ubuntu18.04):
> * How you installed DGL (pip3 install dgl-cu102):
> * Build command you used (if compiling from source):
> * Python version: 3.6.9
> * CUDA/cuDNN version (10.2):
> * GPU models and configuration (RTX2080Ti):
> * Any other relevant information:

This is exactly what I provided.....

**Comment by VoVAllen** [comment]
Could you post the result of `echo $LD_LIBRARY_PATH`?

**Comment by jermainewang** [comment]
> DGL Version (e.g., 1.0):

What's your DGL version? The latest release is 0.5.2.

**Comment by ChaoYue0307** [comment]
> Could you post the result of `echo $LD_LIBRARY_PATH`?
ok, but it shows nothing...

**Comment by ChaoYue0307** [comment]
> > DGL Version (e.g., 1.0):
> 
> What's your DGL version? The latest release is 0.5.2.

I cannot import dgl, how do I know the version? I installed from this page, does it indicate 0.4.x?

**Comment by ChaoYue0307** [comment]
> > DGL Version (e.g., 1.0):
> 
> What's your DGL version? The latest release is 0.5.2.

https://docs.dgl.ai/en/0.4.x/install/

**Comment by VoVAllen** [comment]
Sorry for the late reply, could you check whether libcusparse.so.10 exists in `/usr/local/cuda/lib64`? If so, you should set `export LD_LIBRARY_PATH=/usr/local/cuda/lib64:$LD_LIBRARY_PATH`, then trying import dgl.

**Comment by qihongda** [comment]
> Sorry for the late reply, could you check whether `libcusparse.so.10` exists in `/usr/local/cuda/lib64`? If so, you should set `export LD_LIBRARY_PATH=/usr/local/cuda/lib64:$LD_LIBRARY_PATH`, then trying import dgl. Does this fix your issue?

I have tried these oprations, but it still occurs the error.

**Comment by ch3njust1n** [comment]
I'm getting this same issue

- DGL Version (e.g., 1.0):
- Backend Library & Version ( PyTorch 1.3.1):
- OS (Ubuntu16.04):
- How you installed DGL (pip install dgl-cu101):
- Build command you used (if compiling from source):
- Python version: 3.7.9
- CUDA/cuDNN version (10.1):
- GPU models and configuration (TitanX):

Any progress on this issue?

**Comment by jermainewang** [comment]
@ch3njust1n Could you try `python -c 'import dgl; print(dgl.__path__); print(dgl.__version__)'`?

**Comment by qihongda** [comment]
We changed our CPU, and it works correctly. I don't konw why. lol

**Comment by EJHyun** [comment]
I think i found the answer.. the reason is
when you are inside the virtual environment,
you can not open shared directory of cudatoolkit
which is standing outside the virtual environment.

you can use sudo like

--> sudo python main.py

or just install cudatoolkit inside the virtual environment like

--> conda activate [your env]
--> conda install -c anaconda cudatoolkit=10.1
--> python main.py

I used second way (installing cudatoolkit inside the environment)
because "sudo python" uses "python" outside the virtual environment.
So it's not using the right version I want to use inside the virtual environment.

**Comment by mathamateur** [comment]
> I think i found the answer.. the reason is when you are inside the virtual environment, you can not open shared directory of cudatoolkit which is standing outside the virtual environment.
> 
> you can use sudo like
> 
> --> sudo python main.py
> 
> or just install cudatoolkit inside the virtual environment like
> 
> --> conda activate [your env] --> conda install -c anaconda cudatoolkit=10.1 --> python main.py
> 
> I used second way (installing cudatoolkit inside the environment) because "sudo python" uses "python" outside the virtual environment. So it's not using the right version I want to use inside the virtual environment.

Thanks a lot! That was exactly a solution of this problem for me!!!
