### ISSUE TITLE
[pytorch/han]  

### ISSUE THREAD

**Issue by senllh** [dmlc/dgl#2259]
When i run the \examples\pytorch\han\main.py , there is a bug: AttributeError: module 'dgl' has no attribute 'from_scipy'. Can you help me?

**Comment by mufeili** [comment]
You need to install DGL 0.5.0+. 

- If you previously installed different version(s) of DGL, you need to uninstall them first until you cannot import DGL.
- If you thought you had installed 0.5.0, then likely you have multiple versions installed and you need to uninstall them as above.
