### ISSUE TITLE
Splitting a heterograph across devices

### ISSUE THREAD

**Issue by trinayan** [dmlc/dgl#2270]
Hi,

I am working on implementing a multi-GPU version of HAN using distributed data parallel. I split the train mask,features and labels based on my understanding of how the graphsage multi gpu example does it. My code is here(https://github.com/trinayan/MultiGPUGNN/blob/main/HAN/main.py). I get errors at runtime which is because the  hetero graph "g" also needs to be split accordingly. "dgl._ffi.base.DGLError: Expect number of features to match number of nodes (len(u)). Got 1513 and 3025 instead." . But I am not really sure how to split this graph across my multiple GPUs. If someone can give some advice, that would be really helpful. Thanks

**Comment by BarclayII** [comment]
The HAN example itself is not particularly friendly to large graphs because it computes a graph whose edges represents metapaths.  This will usually yield a lot of edges which cannot fit into GPU memory.

An alternative will be using metapath-based neighbor sampling as mentioned in #2248.
