### ISSUE TITLE
dgl._ffi.base.DGLError: Cannot assign node feature "h" on device cuda:0 to a graph on device cpu. Call DGLGraph.to() to copy the graph to the same device.

### ISSUE THREAD

**Issue by xhjcxxl** [dmlc/dgl#2273]
how to fix it, my dgl version is cu101 0.5.2

**Comment by classicsong** [comment]
You have to make sure the feature is on CPU when the graph on CPU

**Comment by xhjcxxl** [comment]
I change the version,it's ok.

**Comment by wangzeyu135798** [comment]
What's your changed version? I meet this situation as same as yours.

**Comment by xhjcxxl** [comment]
> What's your changed version? I meet this situation as same as yours.

the version is 0.4.1, you can find it in the history

**Comment by wangzeyu135798** [comment]
Thanks！I changed dgl-cu101(0.5.1) to 0.4.1, code can be run.
------------------&nbsp;原始邮件&nbsp;------------------
发件人:                                                                                                                        "dmlc/dgl"                                                                                    <notifications@github.com&gt;;
发送时间:&nbsp;2020年11月2日(星期一) 下午4:30
收件人:&nbsp;"dmlc/dgl"<dgl@noreply.github.com&gt;;
抄送:&nbsp;"天津工业大学王泽宇"<1051533398@qq.com&gt;;"Comment"<comment@noreply.github.com&gt;;
主题:&nbsp;Re: [dmlc/dgl] dgl._ffi.base.DGLError: Cannot assign node feature "h" on device cuda:0 to a graph on device cpu. Call DGLGraph.to() to copy the graph to the same device. (#2273)





  
What's your changed version? I meet this situation as same as yours.
  
the version is 0.4.1, you can find it in the history

**Comment by DemonQiJQ** [comment]
> Thanks！I changed dgl-cu101(0.5.1) to 0.4.1, code can be run. ------------------&nbsp;原始邮件&nbsp;------------------ 发件人: "dmlc/dgl" <notifications@github.com&gt;; 发送时间:&nbsp;2020年11月2日(星期一) 下午4:30 收件人:&nbsp;"dmlc/dgl"<dgl@noreply.github.com&gt;; 抄送:&nbsp;"天津工业大学王泽宇"<1051533398@qq.com&gt;;"Comment"<comment@noreply.github.com&gt;; 主题:&nbsp;Re: [dmlc/dgl] dgl._ffi.base.DGLError: Cannot assign node feature "h" on device cuda:0 to a graph on device cpu. Call DGLGraph.to() to copy the graph to the same device. (#2273) What's your changed version? I meet this situation as same as yours. the version is 0.4.1, you can find it in the history — You are receiving this because you commented. Reply to this email directly, view it on GitHub, or unsubscribe.

i meet the same question and why i cannot find the version dgl 0.4.1, could you tell me how can download it?

**Comment by VoVAllen** [comment]
Please try `pip install dgl==0.4.1`
