### ISSUE TITLE
RuntimeError: "sum_cuda" not implemented for 'Bool'

### ISSUE THREAD

**Issue by Jamesyang2333** [dmlc/dgl#2274]
## 🐛 Bug

I was training a Graph Convolution Network built using the GraphConv module. But I encountered RuntimeError: "sum_cuda" not implemented for 'Bool' during the forward pass.

File "/.venv/lib/python3.7/site-packages/torch/nn/modules/module.py", line 493, in __cal
l__
    result = self.forward(*input, **kwargs)
  File "/model.py", line 419, in forward
    c = self.gcn(T)
  File "/.venv/lib/python3.7/site-packages/torch/nn/modules/module.py", line 493, in __cal
l__
    result = self.forward(*input, **kwargs)
  File "/model.py", line 68, in forward
    h = layer(self.g, h)
  File "/.venv/lib/python3.7/site-packages/torch/nn/modules/module.py", line 493, in __cal
l__
    result = self.forward(*input, **kwargs)
  File "/.venv/lib/python3.7/site-packages/dgl/nn/pytorch/conv/graphconv.py", line 250, in forward
    degs = graph.out_degrees().float().clamp(min=1)
  File "/.venv/lib/python3.7/site-packages/dgl/heterograph.py", line 3322, in out_degrees
    if F.as_scalar(F.sum(self.has_nodes(u_tensor, ntype=srctype), dim=0)) != len(u_tensor):
  File "/.venv/lib/python3.7/site-packages/dgl/backend/pytorch/tensor.py", line 118, in su
m
    return th.sum(input, dim=dim, keepdim=keepdims)
RuntimeError: "sum_cuda" not implemented for 'Bool'

## To Reproduce

I was using the example GCN code under dgl/examples/pytorch/gcn/

```
class GCN(nn.Module):
    def __init__(self,
                 g,
                 in_feats,
                 n_hidden,
                 n_classes,
                 n_layers,
                 activation,
                 dropout):
        super(GCN, self).__init__()
        self.g = g
        self.layers = nn.ModuleList()
        # input layer
        self.layers.append(GraphConv(in_feats, n_hidden, activation=activation))
        # hidden layers
        for i in range(n_layers - 1):
            self.layers.append(GraphConv(n_hidden, n_hidden, activation=activation))
        # output layer
        self.layers.append(GraphConv(n_hidden, n_classes))
        self.dropout = nn.Dropout(p=dropout)

    def forward(self, features):
        h = features
        for i, layer in enumerate(self.layers):
            if i != 0:
                h = self.dropout(h)
            h = layer(self.g, h)
        return h
```
## Expected behavior

No error during the forward pass

## Environment

 - DGL Version (e.g., 1.0): 0.5.2
 - Backend Library & Version (e.g., PyTorch 0.4.1, MXNet/Gluon 1.3): pytorch 1.1.0
 - OS (e.g., Linux): linux
 - How you installed DGL (`conda`, `pip`, source): pip
 - Build command you used (if compiling from source):
 - Python version: 3.7.6
 - CUDA/cuDNN version (if applicable): 9.0
 - GPU models and configuration (e.g. V100): V100
 - Any other relevant information:

**Comment by BarclayII** [comment]
Currently PyTorch requires 1.5.0+ to run.  Please upgrade your PyTorch to the latest version.

Feel free to reopen if it does not work for you.
