### ISSUE TITLE
KeyError: 'h'

### ISSUE THREAD

**Issue by senllh** [dmlc/dgl#2280]
when I execute  graph.apply_edges()    
like this:
def apply_edges(self, edges):
        h_u = edges.src['h']
        h_v = edges.dst['h']
        score = self.W(torch.cat([h_u, h_v], 1))
        return {'score': score}

There is a bug is : KeyError: 'h'.
Why this mistake?  I need your help.  Thank you very much!

**Comment by mufeili** [comment]
Have you assigned a node feature to `ndata['h']`?

**Comment by senllh** [comment]
Yes. After I add code : 
                         hetero_graph.nodes['user'].data['h'] = torch.randn(n_users, 10)
                         hetero_graph.nodes['item'].data['h'] = torch.randn(n_items, 10)
This program can run. Thank you!
