### ISSUE TITLE
test data in dgl

### ISSUE THREAD

**Issue by xin-zhao0** [dmlc/dgl#2282]
Why do you pass the test train data when creating the test graph 
```

    # build test graph
    test_graph, test_rel, test_norm = utils.build_test_graph(
        num_nodes, num_rels, train_data)
    test_deg = test_graph.in_degrees(
                range(test_graph.number_of_nodes())).float().view(-1,1)
    test_node_id = torch.arange(0, num_nodes, dtype=torch.long).view(-1, 1)
    test_rel = torch.from_numpy(test_rel)
    test_norm = node_norm_to_edge_norm(test_graph, torch.from_numpy(test_norm).view(-1, 1))
```

Also in here 

```
            mrr = utils.calc_mrr(embed, model.w_relation, torch.LongTensor(train_data),
                                 valid_data, test_data, hits=[1, 3, 10], eval_bz=args.eval_batch_size,
                                 eval_p=args.eval_protocol)
```

**Comment by mufeili** [comment]
> test_graph, test_rel, test_norm = utils.build_test_graph(
  num_nodes, num_rels, train_data)
test_deg = test_graph.in_degrees(
            range(test_graph.number_of_nodes())).float().view(-1,1)
test_node_id = torch.arange(0, num_nodes, dtype=torch.long).view(-1, 1)
test_rel = torch.from_numpy(test_rel)
test_norm = node_norm_to_edge_norm(test_graph, torch.from_numpy(test_norm).view(-1, 1))

For GNN-based link prediction during the test, one wants to predict unseen edges based on known edges. Therefore the graph contains all training edges.

**Comment by classicsong** [comment]
When doing test, all nodes (both from train-set, valid-set and test-set) should be considered as candidate negative-nodes. And if you want to exclude positive edges during ranking, we also need the  train-set, valid-set and test-set.
