### ISSUE TITLE
Should MiB be changed to MB in `GPU {:.1f} MiB` ?

### ISSUE THREAD

**Issue by maqy1995** [dmlc/dgl#2293]
the `gpu_mem_alloc` is calculated by `th.cuda.max_memory_allocated() / 1000000`, use `MB` may be more precise.
https://github.com/dmlc/dgl/blob/da9f14dff38c9939958ab1126438b7be2c3c39fc/examples/pytorch/graphsage/train_sampling.py#L177

https://github.com/dmlc/dgl/blob/da9f14dff38c9939958ab1126438b7be2c3c39fc/examples/pytorch/graphsage/train_sampling_multi_gpu.py#L199

**Comment by jermainewang** [comment]
Yes, thanks for pointing it out. Would you like to take a lead on a PR?

**Comment by maqy1995** [comment]
of course! I will do it later.
