### ISSUE TITLE
when using dgl.from_networkx()/dgl.from_scipy(), some errors occured

### ISSUE THREAD

**Issue by Chuan1997** [dmlc/dgl#2294]
My code is like:
graph_u1 = nx.from_numpy_matrix(adj_u1)
g_u1 = **dgl.from_networkx**(graph_u1)
g_u1 = dgl.add_self_loop(g_u1)

And the error is:
TypeError: len is not well defined for symbolic Tensors. (Const_4:0) Please call `x.shape` rather than `len(x)` for shape information.

I set tensorflow as default backend, and the version is 2.3.1, how can I solve this problem?

**Comment by mufeili** [comment]
Can you provide a complete code snippet for reproducing the issue?

**Comment by Chuan1997** [comment]
The complete code snippet is like:
import matplotlib.pyplot as plt
import numpy as np
import pandas as pd
import networkx as nx
import scipy.sparse as sp
from sklearn.manifold import TSNE
import tensorflow as tf
from tensorflow.data import Dataset, Iterator
#tf.compat.v1.disable_eager_execution()
import os
import pickle as pkl
import sys
import scipy.sparse as sp
import time
from datetime import datetime
import pickle
import math
import heapq 
import dgl  
from dgl import DGLError
from dgl import function as fn
from scipy.io import loadmat
from sklearn.utils import shuffle
from sgc import SGConv
np.seterr(divide='ignore',invalid='ignore')

unum=943
bnum=1682
def load_ub(ubfile):
        ub = np.zeros((unum, bnum))
        with open(ubfile, 'r') as infile:
            for line in infile.readlines():
                user, business, rating, timestep = line.strip().split('\t')
                ub[int(user)][int(business)] = 1 
        return ub
    
ub = load_ub('.../movie.train.rating')
uu = ub.dot(ub.T)
uu=uu-np.diag(uu.diagonal())
adj_u1 = uu

graph_u1 = nx.from_numpy_matrix(adj_u1)
**g_u1 = dgl.from_networkx(graph_u1)**
g_u1 = dgl.add_self_loop(g_u1)

(explannation: ub is adjacency matrix)
And the error is like:
Traceback (most recent call last):

  File "<ipython-input-42-72bc46023216>", line 1, in <module>
    g_u1 = dgl.from_networkx(graph_u1)

  File "D:\Anaconda3\envs\tf2\lib\site-packages\dgl\convert.py", line 986, in from_networkx
    nx_graph, idtype, edge_id_attr_name=edge_id_attr_name)

  File "D:\Anaconda3\envs\tf2\lib\site-packages\dgl\utils\data.py", line 186, in graphdata2tensors
    if len(src) != len(dst):

  File "D:\Anaconda3\envs\tf2\lib\site-packages\tensorflow\python\framework\ops.py", line 853, in __len__
    "shape information.".format(self.name))

TypeError: len is not well defined for symbolic Tensors. (Const_2:0) Please call `x.shape` rather than `len(x)` for shape information.

**Comment by Chuan1997** [comment]
The code for SGConv layer is collected from DGL.
