### ISSUE TITLE
Is it possible support convert model to onnx format for online serving?

### ISSUE THREAD

**Issue by dengfy** [dmlc/dgl#2296]
I have finish trained DGL model, I want to use the model for online serving,
as I know, pytorh model can convert to onnx for online serving, Is it possible to support?
otherwise, is there other way for online serving?

**Comment by yzh119** [comment]
This thread is related: https://discuss.dgl.ai/t/exporting-graphsage-model-into-onnx-format-train-sampling-py/1263
