### ISSUE TITLE
Running TODOs

### ISSUE THREAD

**Issue by jermainewang** [dmlc/dgl#23]
Hi all,

Let's use this thread to book-keep all the major TODOs before our first major milestone.

**High priority**
Tasks that have a major contributor to be in charge of.
- [x] C <=> Python interface (probably borrow from TVM).
- [ ] Lowering graph related logic to C++
  - [x] Light weight & efficient C++ graph data structure
  - [x] Graph construction and graph batching
  - [x] Graph query logic (the current cached graph)
  - [ ] Graph traversal logic
  - [x] Fast generation of adj or incident matrix
- [ ] generic-SPMV in C++
  - [ ] Operator interface and implementation
  - [ ] Plugin to Pytorch
- [x] Improve end-to-end training time of tree-lstm to be 2x faster than DyNet.
- [ ] Improve GAT-spmv implementation to be faster than TF.
- [ ] Document & tutorial plans
  - [x] Setup sphinx doc

**Low priority**
Tasks that anyone can contribute when they don't have high priority tasks at the moment.
- [x] Setup CI
  - [x] Basic CI (#30 )
  - [x] GPU CI
- [x] Setup lint check
- [x] Scaling tests using generated graphs (#32 )
- [ ] Scale to multi-card

**Applications**
- [ ] GCN-like
  - [x] GCN (#35 )
  - [x] GAT (#37)
  - [ ] MGCN
  - [ ] relational GCN
  - [ ] GeniePath
  - [ ] PageRank
  - [ ] MPNN
  - [ ] GraphSAGE with different aggregators
- [x] TreeLSTM
- [x] LineGraph
- [ ] Graph generation model
  - [x] DGMG (#14 )
  - [ ] Junction Tree VAE
- [ ] DeepWalk/node2vec
- [ ] Transformer (?)
- [ ] CapsuleNet (?)

**Comment by kitaev-chen** [comment]
I think "Dynamic graph (in the generative_model branch)" will be a real competitive feature compared with other graph libraries since graph based generative model / gaussian process will be very prevalent .

**Comment by mufeili** [comment]
Thanks a lot for the suggestion @kitaev-chen . I'm personally a big fan of generative models and yes we are likely to incorporate some more examples on generative models in the future. As this issue is closed now, you may want to instead post your suggestion at #450 . Also let us know if there are some models that you are particularly interested.
