### ISSUE TITLE
Heterogeneous Graph Attention Module

### ISSUE THREAD

**Issue by xwjim** [dmlc/dgl#2301]
## ❓ Questions and Help

I did not find a module about Heterogeneous Graph Attention. Is there a tutorial about the  Heterogeneous Graph Attention Module.

**Comment by mufeili** [comment]
Have you checked the example [here](https://github.com/dmlc/dgl/tree/master/examples/pytorch/han)? You can try adapting the example.

**Comment by xwjim** [comment]
Thank you. I would try it.
