### ISSUE TITLE
It seems forget to load `batch_inputs` to device in graphsage `train_dist.py`?

### ISSUE THREAD

**Issue by maqy1995** [dmlc/dgl#2302]
the code snippet is below:
https://github.com/dmlc/dgl/blob/38b3d0c4ccfada8c5034932d0559d65f0d39bddc/examples/pytorch/graphsage/experimental/train_dist.py#L212-L222

It seems missed code:
```
batch_inputs = batch_inputs.to(device)
```
before
```
batch_pred = model(blocks, batch_inputs)
```
another solution is to move
```
batch_inputs = blocks[0].srcdata['features']
batch_labels = blocks[-1].dstdata['labels']
batch_labels = batch_labels.long()
```
behind
```
blocks = [block.to(device) for block in blocks]
```
same as dgl/examples/pytorch/graphsage/train_sampling.py

**Comment by VoVAllen** [comment]
You are right, but currently the speed of distributed training on gpu didn't outperform cpu too much. Therefore we are still tuning the performance, and recommend user to use cpu instead, since it's much cheaper.

**Comment by maqy1995** [comment]
get. Looking forward to your future work.
