### ISSUE TITLE
[Mini-batch Training] Doc and Behavior Definition for DGLBlock

### ISSUE THREAD

**Issue by mufeili** [dmlc/dgl#2303]
For mini-batch training, many users have no idea about what they can do with the blocks constructed. This gives rise to the need for:
- A documentation on DGLBlock, which does not exist now.
- A better definition on the behavior of DGLBlock. While DGLBlock is a subclass of DGLGraph, many functionalities do not support DGLBlock.

**Comment by jermainewang** [comment]
The general conclusion is to have the following changes in the next DGL release:
* Try to avoid having an additional concept called DGLBlock in our documentation/tutorial. DGLBlocks should just be some sampled subgraphs.
* Modify the codebase to make DGLBlock fully-compatible with DGLGraph.

Should add to #2252 .
