### ISSUE TITLE
Cannot find CMAKE_Fortran_Compiler using Anaconda3

### ISSUE THREAD

**Issue by Maulpy** [dmlc/dgl#2304]
Dear All

I use windows 10 and follow the guide from the https://docs.dgl.ai/tutorials/basics/1_first.html
I stumble on the last part

"md build
cd build
cmake -DCMAKE_CXX_FLAGS="-DDMLC_LOG_STACK_TRACE=0 -DDGL_EXPORTS" -DCMAKE_MAKE_PROGRAM=mingw32-make .. -G "MSYS Makefiles"
mingw32-make
cd ..\python
python setup.py install"

At first i can't find CMakelists.txt when i run the 'cmake -DCMAKE_CXX....." after i activate the specific environment immediately (in "C:/Users/Acer"), but i change the directory to deeper folder where i found the text manually.
After that the following error shown.

-- The Fortran compiler identification is unknown
CMake Error at CMakeLists.txt:2 (project):
  No CMAKE_Fortran_COMPILER could be found.

  Tell CMake where to find the compiler by setting either the environment
  variable "FC" or the CMake cache entry CMAKE_Fortran_COMPILER to the full
  path to the compiler, or to the compiler name if it is in the PATH.

-- Configuring incomplete, errors occurred!
See also "C:/Users/Acer/anaconda3/pkgs/cmake-3.18.2-hab937c2_0/Library/share/cmake-3.18/Modules/IntelVSImplicitPath/build/CMakeFiles/CMakeOutput.log".
See also "C:/Users/Acer/anaconda3/pkgs/cmake-3.18.2-hab937c2_0/Library/share/cmake-3.18/Modules/IntelVSImplicitPath/build/CMakeFiles/CMakeError.log".

I don't know what is went wrong. from what i see manually, the file "CMakeFortranCompilerId.F" actually exist inside the lowest sub folder of 'build' folder.

Any hint will be very appreciated, i cannot thank you enough, thank you very much.

**Comment by BarclayII** [comment]
MinGW is no longer supported.  You can build DGL using CMake and MSBuild.

**Comment by Maulpy** [comment]
Oh God that explains everything, i try to install fortran compiler in conda forge but CMAKE_FORTRAN_COMPILER isn't exist either.

Do i need to remove cmake m2w64-gcc m2w64-make (and the fortran compiler) too before @BarclayII 
?

Thank you very much.

**Comment by BarclayII** [comment]
The bottom of the installation instruction in https://docs.dgl.ai/install/index.html describes how to build with MSBuild.  We didn't update the instruction to remove MinGW though.

**Comment by Maulpy** [comment]
Dear Mr.@BarclayII , thank you for your response.

This morning I have just finished upgrade my windows 10 into the latest version (Build 19042) from previously the 2015 version to install VS.
I have installed cmake-3.18.4-win64-x64 in C, add it into path and check it in Developer Command Prompt for VS 2019, and it shown.

**Usage

  cmake [options] <path-to-source>
  cmake [options] <path-to-existing-build>
  cmake [options] -S <path-to-source> -B <path-to-build>

Specify a source directory to (re-)generate a build system for it in the
current working directory.  Specify an existing build directory to
re-generate its build system.

Run 'cmake --help' for more information.**

But when i try to make directory 'build', the access is denied. I try to uninstall it and set it in Users, typing 'cmake' and it return nothing, i reinstall it in the former place and run VS as administrator.
Then directory changed into system32, entering 'cmake' and following the guideline return.

C:\Windows\System32>cd build

C:\Windows\System32\build>cmake -DCMAKE_CXX_FLAGS="-DDMLC_LOG_STACK_TRACE=0 -DDGL_EXPORTS" -DCMAKE_MAKE_PROGRAM=mingw32-make .. -G "MSYS Makefiles"
CMake Error: The source directory "C:/Windows/System32" does not appear to contain CMakeLists.txt.
Specify --help for usage, or press the help button on the CMake GUI.

The CMakeLists.txt file again not found.

I don't know what is wrong, the CMakeLists.txt files exist in C:\Program Files\CMake, and the Visual Studio in C:\Program Files(x86)\Microsoft Visual Studio. Maybe the difference in directory is the root of the problem, but i am not sure, because PATH is defined in environment variables.  i add the both User Variables and System Variables PATH to C:\Program Files\CMake.

I hope my description is clear.

Thank you very much.

**Comment by Maulpy** [comment]
I am trying to install VS Community 2017 version 15.9 for now, and maybe i will install MSBuild 15.0 separatedly.

**Comment by Maulpy** [comment]
C:\Windows\System32\DGL\Build>cmake -DCMAKE_CXX_FLAGS="/DDGL_EXPORTS" -DCMAKE_CONFIGURATION_TYPES="Release" .. -G "Visual Studio 15 2017 Win64"
CMake Error: The source directory "C:/Windows/System32/DGL" does not appear to contain CMakeLists.txt.
Specify --help for usage, or press the help button on the CMake GUI.

C:\Windows\System32\DGL\Build>msbuild dgl.sln
Microsoft (R) Build Engine version 15.9.21+g9802d43bc3 for .NET Framework
Copyright (C) Microsoft Corporation. All rights reserved.

MSBUILD : error MSB1009: Project file does not exist.
Switch: dgl.sln

**Comment by BarclayII** [comment]
Does your source directory (`C:\Windows\System32\DGL`) contain the file called `CMakeLists.txt`?  Also I'm not sure why you were building in Windows system folder.

**Comment by Maulpy** [comment]
Morning @BarclayII 

I just have time to figure it out again since week ago, this time i run the Developer Command Prompt for VS 2017 as administrator just to gain an access.
after i cd into CMake, i use "cmake [options] -S <path to source> -B <path to build>". 
CMakeLists.txt files exist in three location and i just choose that is located in 'FortranCInterface' folder, it return the error like this.


**C:\Windows\System32>cd ..

C:\Windows>cd ..

C:\>cd Program Files

C:\Program Files>cd CMake

C:\Program Files\CMake>cmake [options] -S share\cmake-3.18\Modules\FortranCInterface -B build
-- Building for: NMake Makefiles
-- The C compiler identification is unknown
-- The Fortran compiler identification is unknown
CMake Error at CMakeLists.txt:5 (project):
  The CMAKE_C_COMPILER:

    cl

  is not a full path and was not found in the PATH.

  To use the NMake generator with Visual C++, cmake must be run from a shell
  that can use the compiler cl from the command line.  This environment is
  unable to invoke the cl compiler.  To fix this problem, run cmake from the
  Visual Studio Command Prompt (vcvarsall.bat).

  Tell CMake where to find the compiler by setting either the environment
  variable "CC" or the CMake cache entry CMAKE_C_COMPILER to the full path to
  the compiler, or to the compiler name if it is in the PATH.


CMake Error at CMakeLists.txt:5 (project):
  No CMAKE_Fortran_COMPILER could be found.

  Tell CMake where to find the compiler by setting either the environment
  variable "FC" or the CMake cache entry CMAKE_Fortran_COMPILER to the full
  path to the compiler, or to the compiler name if it is in the PATH.


-- Configuring incomplete, errors occurred!
See also "C:/Program Files/CMake/build/CMakeFiles/CMakeOutput.log".
See also "C:/Program Files/CMake/build/CMakeFiles/CMakeError.log".**

I am getting stuck again, should i :

1. Set directory ..\CMake\share\cmake-3.18\Modules\Compiler" to CC or FC? i don't know where is the CMAKE_Fortran_Compiler, i set compiler folder location "C:\Program Files\CMake\share\cmake-3.18\Modules\Compiler" to path and rerun and it is still the same.
2. Run the command prompt differently?

here is the error log if you are interested in seeing.
[CMakeError.log](https://github.com/dmlc/dgl/files/5476864/CMakeError.log)
[CMakeOutput.log](https://github.com/dmlc/dgl/files/5476867/CMakeOutput.log)

Thank you very much.

**Comment by Maulpy** [comment]
> 
> 
> Morning @BarclayII
> 
> I just have time to figure it out again since week ago, this time i run the Developer Command Prompt for VS 2017 as administrator just to gain an access.
> after i cd into CMake, i use "cmake [options] -S -B ".
> CMakeLists.txt files exist in three location and i just choose that is located in 'FortranCInterface' folder, it return the error like this.
> 
> **C:\Windows\System32>cd ..
> 
> C:\Windows>cd ..
> 
> C:>cd Program Files
> 
> C:\Program Files>cd CMake
> 
> C:\Program Files\CMake>cmake [options] -S share\cmake-3.18\Modules\FortranCInterface -B build
> -- Building for: NMake Makefiles
> -- The C compiler identification is unknown
> -- The Fortran compiler identification is unknown
> CMake Error at CMakeLists.txt:5 (project):
> The CMAKE_C_COMPILER:
> 
> ```
> cl
> ```
> 
> is not a full path and was not found in the PATH.
> 
> To use the NMake generator with Visual C++, cmake must be run from a shell
> that can use the compiler cl from the command line. This environment is
> unable to invoke the cl compiler. To fix this problem, run cmake from the
> Visual Studio Command Prompt (vcvarsall.bat).
> 
> Tell CMake where to find the compiler by setting either the environment
> variable "CC" or the CMake cache entry CMAKE_C_COMPILER to the full path to
> the compiler, or to the compiler name if it is in the PATH.
> 
> CMake Error at CMakeLists.txt:5 (project):
> No CMAKE_Fortran_COMPILER could be found.
> 
> Tell CMake where to find the compiler by setting either the environment
> variable "FC" or the CMake cache entry CMAKE_Fortran_COMPILER to the full
> path to the compiler, or to the compiler name if it is in the PATH.
> 
> -- Configuring incomplete, errors occurred!
> See also "C:/Program Files/CMake/build/CMakeFiles/CMakeOutput.log".
> See also "C:/Program Files/CMake/build/CMakeFiles/CMakeError.log".**
> 
> I am getting stuck again, should i :
> 
>     1. Set directory ..\CMake\share\cmake-3.18\Modules\Compiler" to CC or FC? i don't know where is the CMAKE_Fortran_Compiler, i set compiler folder location "C:\Program Files\CMake\share\cmake-3.18\Modules\Compiler" to path and rerun and it is still the same.
> 
>     2. Run the command prompt differently?
> 
> 
> here is the error log if you are interested in seeing.
> [CMakeError.log](https://github.com/dmlc/dgl/files/5476864/CMakeError.log)
> [CMakeOutput.log](https://github.com/dmlc/dgl/files/5476867/CMakeOutput.log)
> 
> Thank you very much.

I don't have vcvarsall.bat file too in my installation, should i instll different version?

**Comment by BarclayII** [comment]
If you have installed Visual Studio Build Tools, you may find something like "Visual Studio 2017" -> "x64 Native Tools Command Prompt" in your start menu.  That runs `vcvars64.bat` which includes tools like `cl` in `PATH`.

**Comment by Maulpy** [comment]
Oke mr @BarclayII , sorry i took too long to reply. i am bit preoccupied with my work, and i also try to learn too what the architecture build really is to little avail.

i just renew the package from C++ dekstop development, and now my default window of x64 Native Tools Command Prompt for VS2017 is.

**********************************************************************
** Visual Studio 2017 Developer Command Prompt v15.9.28
** Copyright (c) 2017 Microsoft Corporation
**********************************************************************
[vcvarsall.bat] Environment initialized for: 'x64'

C:\Program Files (x86)\Microsoft Visual Studio\2017\Community>

Maybe the question i should ask from the first time is, where should i set the build folder? from CMake folder or anaconda3?
i still got "CMakelists.txt not found" when i cd build (right inside CMake folder), the text location is in another subfolder.

In anaconda 3, the three location of CMakeLists.txt. are the following :
- C:\Users\Acer\anaconda3\pkgs\cmake-3.18.2-hab937c2_0\Library\share\cmake-3.18\Modules\FortranCInterface
- C:\Users\Acer\anaconda3\pkgs\cmake-3.18.2-hab937c2_0\Library\share\cmake-3.18\Modules\FortranCInterface\Verify 
- C:\Users\Acer\anaconda3\envs\DGL\Library\share\cmake-3.18\Modules\IntelVSImplicitPath

should i run the prompt as administrator too?

Thank you very much.

**Comment by BarclayII** [comment]
You should run the commands in the directory containing the source code.  For instance, if you ran `git clone https://github.com/dmlc/dgl` in the directory called, say `C:\Users\Acer`, then the source code directory would be `C:\Users\Acer\dgl`.  You can make the build directory and run CMake etc. there.

**Comment by Maulpy** [comment]
Thank you Mr @BarclayII , finally i'm onto something.

I have finished the installation, but along the way i encountered enormous error. 122 warning(s) and 67 error(s). Should i be wary of it? could it impend the software to run properly later? this is a bit of the outputs.

**********************************************************************
** Visual Studio 2017 Developer Command Prompt v15.9.28
** Copyright (c) 2017 Microsoft Corporation
**********************************************************************
[vcvarsall.bat] Environment initialized for: 'x64'

C:\Windows\System32>cd ..

C:\Windows>cd ..

C:\>cd Users

C:\Users>cd Acer

C:\Users\Acer>cd dgl

C:\Users\Acer\dgl>md build

C:\Users\Acer\dgl>cd build

C:\Users\Acer\dgl\build>cmake -DCMAKE_CXX_FLAGS="/DDGL_EXPORTS" -DCMAKE_CONFIGURATION_TYPES="Release" .. -G "Visual Studio 15 2017 Win64"
-- Selecting Windows SDK version 10.0.17763.0 to target Windows 10.0.19042.
-- The C compiler identification is MSVC 19.16.27043.0
-- The CXX compiler identification is MSVC 19.16.27043.0
-- Detecting C compiler ABI info
-- Detecting C compiler ABI info - done
-- Check for working C compiler: C:/Program Files (x86)/Microsoft Visual Studio/2017/Community/VC/Tools/MSVC/14.16.27023/bin/Hostx86/x64/cl.exe - skipped
-- Detecting C compile features
-- Detecting C compile features - done
-- Detecting CXX compiler ABI info
-- Detecting CXX compiler ABI info - done
-- Check for working CXX compiler: C:/Program Files (x86)/Microsoft Visual Studio/2017/Community/VC/Tools/MSVC/14.16.27023/bin/Hostx86/x64/cl.exe - skipped
-- Detecting CXX compile features
-- Detecting CXX compile features - done
-- Start configuring project dgl
-- Found OpenMP_C: -openmp (found version "2.0")
-- Found OpenMP_CXX: -openmp (found version "2.0")
-- Found OpenMP: TRUE (found version "2.0")
-- Looking for clock_gettime in rt
-- Looking for clock_gettime in rt - not found
-- Looking for fopen64
-- Looking for fopen64 - not found
-- Looking for C++ include cxxabi.h
-- Looking for C++ include cxxabi.h - not found
-- Looking for nanosleep
-- Looking for nanosleep - not found
-- Looking for backtrace
-- Looking for backtrace - not found
-- Could NOT find Backtrace (missing: Backtrace_LIBRARY Backtrace_INCLUDE_DIR)
-- Check if the system is big endian
-- Searching 16 bit integer
-- Looking for sys/types.h
-- Looking for sys/types.h - found
-- Looking for stdint.h
-- Looking for stdint.h - found
-- Looking for stddef.h
-- Looking for stddef.h - found
-- Check size of unsigned short
-- Check size of unsigned short - done
-- Searching 16 bit integer - Using unsigned short
-- Check if the system is big endian - little endian
-- C:/Users/Acer/dgl/third_party/dmlc-core/cmake/build_config.h.in -> include/dmlc/build_config.h
-- Found PythonInterp: C:/Users/Acer/anaconda3/python.exe (found version "3.8.3")
-- Configuring done
-- Generating done
-- Build files have been written to: C:/Users/Acer/dgl/build

C:\Users\Acer\dgl\build>msbuild dgl.sln
Microsoft (R) Build Engine version 15.9.21+g9802d43bc3 for .NET Framework
Copyright (C) Microsoft Corporation. All rights reserved.

Building the projects in this solution one at a time. To enable parallel build, please add the "/m" switch.
Build started 07-Nov-20 2:24:21 PM.
Project "C:\Users\Acer\dgl\build\dgl.sln" on node 1 (default targets).
ValidateSolutionConfiguration:
  Building solution configuration "Release|x64".

.....
.....
> >::sputc(char)" (?sputc@?$basic_streambuf@DU?$char_traits@D@std@@@std@@QEAAHD@Z) already defined in msvcprt.lib(MSVCP
140.dll) [C:\Users\Acer\dgl\build\dgl.vcxproj]
  libcpmt.lib(xdateord.obj) : error LNK2038: mismatch detected for 'RuntimeLibrary': value 'MT_StaticRelease' doesn't m
atch value 'MD_DynamicRelease' in array.obj [C:\Users\Acer\dgl\build\dgl.vcxproj]
  libcpmt.lib(xwctomb.obj) : error LNK2005: _Getcvt already defined in msvcprt.lib(MSVCP140.dll) [C:\Users\Acer\dgl\bui
ld\dgl.vcxproj]
  libcpmt.lib(winapisupp.obj) : error LNK2038: mismatch detected for 'RuntimeLibrary': value 'MT_StaticRelease' doesn't
 match value 'MD_DynamicRelease' in array.obj [C:\Users\Acer\dgl\build\dgl.vcxproj]
  libcpmt.lib(winapinls.obj) : error LNK2038: mismatch detected for 'RuntimeLibrary': value 'MT_StaticRelease' doesn't
match value 'MD_DynamicRelease' in array.obj [C:\Users\Acer\dgl\build\dgl.vcxproj]
  libcpmt.lib(StlCompareStringW.obj) : error LNK2038: mismatch detected for 'RuntimeLibrary': value 'MT_StaticRelease'
doesn't match value 'MD_DynamicRelease' in array.obj [C:\Users\Acer\dgl\build\dgl.vcxproj]
  libcpmt.lib(StlLCMapStringW.obj) : error LNK2038: mismatch detected for 'RuntimeLibrary': value 'MT_StaticRelease' do
esn't match value 'MD_DynamicRelease' in array.obj [C:\Users\Acer\dgl\build\dgl.vcxproj]
  C:\Users\Acer\dgl\build\Release\dgl.dll : fatal error LNK1169: one or more multiply defined symbols found [C:\Users\A
cer\dgl\build\dgl.vcxproj]

    122 Warning(s)
    67 Error(s)

Time Elapsed 00:10:03.23

C:\Users\Acer\dgl\build>cd ..\python

C:\Users\Acer\dgl\python>python setup.py install

C:\Users\Acer\dgl\python>

Mr @BarclayII , If this could put some light, i am just trying to explore and extract the graph 'features' from some engineering situation, and if possible to gain some features from the graph, the chance that this is possible maybe very weak but i am still very interested to see the result.


n.b : this is the documentation of installation.
[DGL Installation documentation.txt](https://github.com/dmlc/dgl/files/5504469/DGL.Installation.documentation.txt)

Thank you very much.
