### ISSUE TITLE
g.in_edges() function not work at GPU device

### ISSUE THREAD

**Issue by dengfy** [dmlc/dgl#2307]
my code:
import os
os.environ["DGLBACKEND"] = "pytorch"

import dgl
import torch as th

u, v = th.tensor([0, 1, 2]), th.tensor([2, 3, 4])
g = dgl.graph((u, v))
g.ndata['x'] = th.randn(5, 3)
print(g.device)

g = g.to('cuda:0')
print(g.device)

src = th.tensor([4]).to('cuda:0')  or src = 4
src_1, dst_1, edge_1 = g.in_edges(src, form='all')
print(src_1)
print(dst_1)
print(edge_1)

error:
terminate called after throwing an instance of 'dmlc::Error'
  what():  [10:34:37] /opt/dgl/src/runtime/cuda/cuda_device_api.cc:103: Check failed: e == cudaSuccess || e == cudaErrorCudartUnloading: CUDA: an illegal memory access was encountered
Stack trace:
  [bt] (0) /usr/local/python3/lib/python3.6/site-packages/dgl/libdgl.so(dmlc::LogMessageFatal::~LogMessageFatal()+0x4f) [0x7f8cb5101bdf]
  [bt] (1) /usr/local/python3/lib/python3.6/site-packages/dgl/libdgl.so(dgl::runtime::CUDADeviceAPI::FreeDataSpace(DLContext, void*)+0x15d) [0x7f8cb58f3d8d]
  [bt] (2) /usr/local/python3/lib/python3.6/site-packages/dgl/libdgl.so(dgl::runtime::NDArray::Internal::DefaultDeleter(dgl::runtime::NDArray::Container*)+0x1ad) [0x7f8cb57b57bd]
  [bt] (3) /usr/local/python3/lib/python3.6/site-packages/dgl/libdgl.so(dgl::runtime::NDArray::reset()+0x27) [0x7f8cb58f7c99]
  [bt] (4) /usr/local/python3/lib/python3.6/site-packages/dgl/libdgl.so(dgl::runtime::NDArray::~NDArray()+0x18) [0x7f8cb58f7b62]
  [bt] (5) /usr/local/python3/lib/python3.6/site-packages/dgl/libdgl.so(dgl::aten::COOMatrix dgl::aten::impl::CSRToCOO<(DLDeviceType)2, long>(dgl::aten::CSRMatrix)+0x3ea) [0x7f8cb594aa9a]
  [bt] (6) /usr/local/python3/lib/python3.6/site-packages/dgl/libdgl.so(dgl::aten::CSRToCOO(dgl::aten::CSRMatrix, bool)+0x556) [0x7f8cb50e0456]
  [bt] (7) /usr/local/python3/lib/python3.6/site-packages/dgl/libdgl.so(dgl::UnitGraph::CSR::OutEdges(unsigned long, dgl::runtime::NDArray) const+0xf7) [0x7f8cb58d2a77]
  [bt] (8) /usr/local/python3/lib/python3.6/site-packages/dgl/libdgl.so(dgl::UnitGraph::InEdges(unsigned long, dgl::runtime::NDArray) const+0xc9) [0x7f8cb58cb7b9]

## Environment
CUDA 10.0    pytorch1.4   python3.6
pip install /tmp/dgl_cu100-0.5.2-cp36-cp36m-manylinux1_x86_64.whl

**Comment by mufeili** [comment]
I used `src = th.tensor([4]).to('cuda:0')` and it runs properly on my machine without the error. How did you install DGL and PyTorch?

**Comment by dengfy** [comment]
just pip install whl, the error is at  in_edges method

**Comment by yzh119** [comment]
dgl 0.5+ is not compatible with pytorch 1.4 on cuda, please upgrade your pytorch and see if the problem persists.

**Comment by LILI-ZHOU** [comment]
I also met the same mistake, could you solve it
