### ISSUE TITLE
confused about dgl.ops

### ISSUE THREAD

**Issue by Wjk666** [dmlc/dgl#2317]
## ❓ Questions and Help
I want to use edge_softmax function, so I use the command `from dgl.ops import edge_softmax`, but when I try to do it, some issues occur:
> Traceback (most recent call last):
> File "<stdin>", line 1, in <module>
>ModuleNotFoundError: No module named 'dgl.ops'

My machine is : python 3.6.12 cuda 10.0 torch: 1.4.0+cu100

**Comment by yzh119** [comment]
I've answered your question in discussion forum, please upgrade your DGL (to v0.5+) and PyTorch (to v1.6+, DGL 0.5 is not compatible with PyTorch 1.5)

**Comment by Wjk666** [comment]
Thanks a lot. I have understood it!
