### ISSUE TITLE
Can't reproduce the results on youtube dataset

### ISSUE THREAD

**Issue by ykntjsnw** [dmlc/dgl#2320]
## ❓ Questions and Help

I run the deepwalk.py with the same arguments setting on youtube datasets, but the performance is much worse than that presented in the README. So i wonder what causes this. what's the parameter setting in measuring f1-micro and f1-macro?

**Comment by yzh119** [comment]
Hi @ykntjsnw , do you mean this example?
https://github.com/dmlc/dgl/tree/master/examples/pytorch/ogb/deepwalk

**Comment by ykntjsnw** [comment]
Right. Could i have the code for computing f1-micro and f1-macro? My e-mail address is jwshen_fzj@163.com, i will really appreciate it. @yzh119

**Comment by classicsong** [comment]
The command we got the f1-micro and f1-macro in the README is here:
`python3 deepwalk.py --data_file youtube --output_emb_file emb.txt --mix --lr 0.2 --gpus 0 1 2 3 --batch_size 100 --negative 5`
It uses 4 gpus to do the training. If you are using single gpu for training, HP should be changed.

**Comment by ykntjsnw** [comment]
Actually, I have run this command and got the embedding, but the result is still not desirable using my own score code. So i wonder whether there is something wrong on my score code. Could i have your score code? @classicsong

**Comment by classicsong** [comment]
The evaluation methods this example use is here: https://github.com/ShawXh/Evaluate-Embedding

**Comment by ykntjsnw** [comment]
thanks, Iet me try


| |
沈佳炜
|
|
邮箱：jwshen_fzj@163.com
|

签名由 网易邮箱大师 定制

On 11/11/2020 16:07, xiang song(charlie.song) wrote:

The evaluation methods this example use is here: https://github.com/ShawXh/Evaluate-Embedding
