### ISSUE TITLE
Install cuda11.0

### ISSUE THREAD

**Issue by senllh** [dmlc/dgl#2322]
My CUDA version is 11.0

I didn't find the corresponding version from DGL website.

How do I install the DGL-cuda?

**Comment by fmellomascarenhas** [comment]
@senllh, I also have cuda 11.0, and I installed the 10.2 and ran 2 different examples without any problems. I am new to DGL, but if you have any problems, I assume that you can downgrade your cuda to 10.2.

**Comment by GZYZG** [comment]
> @senllh, I also have cuda 11.0, and I installed the 10.2 and ran 2 different examples without any problems. I am new to DGL, but if you have any problems, I assume that you can downgrade your cuda to 10.2.

did you install DGL by "pip install dgl-cu101"?

**Comment by fmellomascarenhas** [comment]
@senllh i used conda: conda install -c dglteam dgl-cuda10.2

https://docs.dgl.ai/en/0.4.x/install/

**Comment by jermainewang** [comment]
Hi guys, we are working on releasing cu11 compatible DGL. Please stay tuned!

**Comment by 5AGE-zhang** [comment]
> 
> 
> @senllh, I also have cuda 11.0, and I installed the 10.2 and ran 2 different examples without any problems. I am new to DGL, but if you have any problems, I assume that you can downgrade your cuda to 10.2.
@fmellomascarenhas, did you run your 2 examples with GPU?

**Comment by BarclayII** [comment]
Hi all, we have released DGL with CUDA 11.0.  You can install it with either `pip install dgl-cu110` or `conda install dgl-cuda11.0 -c dglteam`.

**Comment by goodman1204** [comment]
> pip install dgl-cu110

works for me. My cuda version is 11.2, but **dgl-cu110** is working.
