### ISSUE TITLE
install dgl gpu version on cuda 10.2

### ISSUE THREAD

**Issue by jianjinlayer6ai** [dmlc/dgl#2347]
Hi there, I tried to install dgl gpu version on cuda 10.2 using anaconda. The command I used is `conda install -c dglteam dgl-cuda10.2` 
During the installation process, everything is fine. However, when I tried to import dgl, it says `dgl cuda libcudart.so.10.2: cannot open shared object file: No such file or directory`. Do you know how to solve it? Thank you.

Btw, the cpu version works fine before I tried to install the gpu version.

**Comment by jermainewang** [comment]
Could you please check if your cuda library is in the right path?
