### ISSUE TITLE
Copy-on-access Problem in Data Loading with num_workers > 0 When Dealing with A Dataset of Multiple Graphs

### ISSUE THREAD

**Issue by mufeili** [dmlc/dgl#2349]
## 🐛 Bug

A common practice for working with multiple graphs is to first construct them and store them in a list and then use multiple workers in data loading for acceleration. However, this can cause copy-on-access problem as discussed in https://github.com/pytorch/pytorch/issues/13246.

**Comment by BarclayII** [comment]
Bump this because it is impacting the CPU memory consumption in OGB-LSC graph classification task.
