### ISSUE TITLE
How can DGL gurantee a evenly split subgraph from the original full graph ?

### ISSUE THREAD

**Issue by Zarca** [dmlc/dgl#2357]
Hi,

  I'm wondering if there exist any mechanism or principal by which DGL use to support a well-distributed or relative evenly 
sub_graph neighbor sampling from the original graph? 
For instance, the official DGL's GraphSage example in multi gpu version like below:
https://github.com/dmlc/dgl/blob/f8f0d362bcf482f4a82c31c5baca90c5147b7dd0/examples/pytorch/graphsage/train_sampling_multi_gpu.py#L152
  What if the sub_graphs divided into different gpu or process have a very different size in node's number and edge's number?
Is there any API i can use to get a evenly sub_graph for each process?

**Comment by mufeili** [comment]
For this particular example, there does not involve graph partition across multiple GPUs. It simply launches multiple processes, one per GPU. Each process takes the original graph and performs neighbor sampling independently.
