### ISSUE TITLE
Possible error in RGCN conv implementation

### ISSUE THREAD

**Issue by fmellomascarenhas** [dmlc/dgl#2360]
## 🐛 Bug

When working with dimensions in RGNN conv, instead of using tensor.permute(), the implementation is using tensor.view(), which mixes relations bases. I am not sure if, at the end, the NN learns to work around it, but it looks different than what was intended initially by the equation below:

Tutorial and implementation do the same thing:
https://docs.dgl.ai/_modules/dgl/nn/pytorch/conv/relgraphconv.html#RelGraphConv
https://docs.dgl.ai/en/latest/tutorials/models/1_gnn/4_rgcn.html

![image](https://user-images.githubusercontent.com/23004953/99835145-069c1080-2b19-11eb-8661-23700496d041.png)

## To Reproduce

When reading the code below, please pay attention to the difference between doing .view and .permute at the end.
```
import torch

num_bases = 2
in_feat = 2
out_feat = 2
num_rels = 3

w_comp = torch.ones(num_rels * num_bases).view(num_rels, num_bases).float()
weight = torch.arange(num_bases*in_feat*out_feat).view(num_bases, in_feat, out_feat).float()

weight_transposed = weight.view(in_feat, num_bases, out_feat) #<-- view also used here, instead of permute.
weight_matmul = torch.matmul(w_comp, weight_transposed)
weight_matmul_transposed_view = weight_matmul.view(num_rels, in_feat, out_feat)
weight_matmul_transposed_permute = weight_matmul.permute(1,0,2)

print('w_comp - (num_rels, num_bases) \n', w_comp)
print('weight - (num_bases, in_feat, out_feat) \n', weight)
print('weight_transposed - (in_feat, num_bases, out_feat) \n', weight_transposed)
print('weight_matmul - (in_feat, num_rels, out_feat) \n', weight_matmul)
print('weight_matmul_transposed_view - (num_rels, in_feat, out_feat) \n', weight_matmul_transposed_view)
print('weight_matmul_transposed_permute - num_rels, in_feat, out_feat) \n', weight_matmul_transposed_permute)
```

**Output**
```
w_comp - (num_rels, num_bases) 
 tensor([[1., 1.],
        [1., 1.],
        [1., 1.]])
weight - (num_bases, in_feat, out_feat) 
 tensor([[[0., 1.],
         [2., 3.]],

        [[4., 5.],
         [6., 7.]]])
weight_transposed - (in_feat, num_bases, out_feat) 
 tensor([[[0., 1.],
         [2., 3.]],

        [[4., 5.],
         [6., 7.]]])
weight_matmul - (in_feat, num_rels, out_feat) 
 tensor([[[ 2.,  4.],
         [ 2.,  4.],
         [ 2.,  4.]],

        [[10., 12.],
         [10., 12.],
         [10., 12.]]])
**weight_matmul_transposed_view - (num_rels, in_feat, out_feat)** 
 tensor([[[ 2.,  4.],
         [ 2.,  4.]],

        [[ 2.,  4.],
         [10., 12.]],

        [[10., 12.],
         [10., 12.]]])
**weight_matmul_transposed_permute - num_rels, in_feat, out_feat)** 
 tensor([[[ 2.,  4.],
         [10., 12.]],

        [[ 2.,  4.],
         [10., 12.]],

        [[ 2.,  4.],
         [10., 12.]]])
```

**Comment by jermainewang** [comment]
I don't see a problem of using view operation in `RelGraphConv`. https://github.com/dmlc/dgl/blob/58775ada1f5c830c33be59a9be1229341f7ab56f/python/dgl/nn/pytorch/conv/relgraphconv.py#L188-L197

The equation only requires each base matrix (of size `(in_feat, out_feat)`) to multiply with the right coefficient parameter alpha. The view operation will not change the layout (i.e., column-major or row-major) of a tensor so each base matrix will always multiply the corresponding parameter alpha (Line 194).
