### ISSUE TITLE
I have one question in implementation metapath2vec

### ISSUE THREAD

**Issue by TangQiyou** [dmlc/dgl#2364]
When calling the method of dgl.sampling.random_walk(), why dose the code only sample the path of CPAPC and remove the node of peper between line 92 and line 97 in sampler.py?

**Comment by ziqiaomeng** [comment]
Hello, thanks for your questions. You can check to see the graph construction. Conference is connected to paper, paper is connected to author, while there is no direct link between conference and author. So if you we want to sample C-A-C relations, we need to firstly sample CPAPC path and then remove paper nodes.

**Comment by ziqiaomeng** [comment]
> When calling the method of dgl.sampling.random_walk(), why dose the code only sample the path of CPAPC and remove the node of peper between line 92 and line 97 in sampler.py?

Hello, thanks for your questions. You can check to see the graph construction. Conference is connected to paper, paper is connected to author, while there is no direct link between conference and author. So if you we want to sample C-A-C relations, we need to firstly sample CPAPC path and then remove paper nodes.

**Comment by TangQiyou** [comment]
> > When calling the method of dgl.sampling.random_walk(), why dose the code only sample the path of CPAPC and remove the node of peper between line 92 and line 97 in sampler.py?
> 
> Hello, thanks for your questions. You can check to see the graph construction. Conference is connected to paper, paper is connected to author, while there is no direct link between conference and author. So if you we want to sample C-A-C relations, we need to firstly sample CPAPC path and then remove paper nodes.

Thank you for your answer! I have understood the problem, but now I have a new question. If I want to embed the author, paper and conference nodes at the same time, can I use the meta path APCPAPCPA... directly when sampling? How does the meta path instance formed in this way distinguish different semantics of authors between meta path APA and APCPA mentioned in the paper. In the code, it is considered that as long as they are in the window, they are similar nodes.

**Comment by ziqiaomeng** [comment]
> > > When calling the method of dgl.sampling.random_walk(), why dose the code only sample the path of CPAPC and remove the node of peper between line 92 and line 97 in sampler.py?
> > 
> > 
> > Hello, thanks for your questions. You can check to see the graph construction. Conference is connected to paper, paper is connected to author, while there is no direct link between conference and author. So if you we want to sample C-A-C relations, we need to firstly sample CPAPC path and then remove paper nodes.
> 
> Thank you for your answer! I have understood the problem, but now I have a new question. If I want to embed the author, paper and conference nodes at the same time, can I use the meta path APCPAPCPA... directly when sampling? How does the meta path instance formed in this way distinguish different semantics of authors between meta path APA and APCPA mentioned in the paper. In the code, it is considered that as long as they are in the window, they are similar nodes.

Thanks for your questions. Actually metapath sampling is just a way to convert a graph into a text (you can just imagine each path is a line of text). So what metapath determines what kind of surrounding context you want to consider. So APA and APCPA are different since APCPA additionally take C into considerations. As for APCPAPCPA, it is not easy to sample this long path in the graph, it is expected that you could only sample few number of paths in this form and I don't think sampling APCPAPCPA is necessary as sampling APCPA is sufficient enough.

**Comment by TangQiyou** [comment]
> > > > When calling the method of dgl.sampling.random_walk(), why dose the code only sample the path of CPAPC and remove the node of peper between line 92 and line 97 in sampler.py?
> > > 
> > > 
> > > Hello, thanks for your questions. You can check to see the graph construction. Conference is connected to paper, paper is connected to author, while there is no direct link between conference and author. So if you we want to sample C-A-C relations, we need to firstly sample CPAPC path and then remove paper nodes.
> > 
> > 
> > Thank you for your answer! I have understood the problem, but now I have a new question. If I want to embed the author, paper and conference nodes at the same time, can I use the meta path APCPAPCPA... directly when sampling? How does the meta path instance formed in this way distinguish different semantics of authors between meta path APA and APCPA mentioned in the paper. In the code, it is considered that as long as they are in the window, they are similar nodes.
> 
> Thanks for your questions. Actually metapath sampling is just a way to convert a graph into a text (you can just imagine each path is a line of text). So what metapath determines what kind of surrounding context you want to consider. So APA and APCPA are different since APCPA additionally take C into considerations. As for APCPAPCPA, it is not easy to sample this long path in the graph, it is expected that you could only sample few number of paths in this form and I don't think sampling APCPAPCPA is necessary as sampling APCPA is sufficient enough.

Thank you very much! I understand it, I will do some experiment later.
