### ISSUE TITLE
adj.norm computation in the implementation of gat for ogbn-arxiv

### ISSUE THREAD

**Issue by skepsun** [dmlc/dgl#2370]
I notice that the norm term for dst nodes use the power of 0.5 instead of -0.5 from standard symmetric normalization. Though I also find that it is better, why it works? 

https://github.com/dmlc/dgl/blob/12a193f2652e2f3bf92403727df57f872381d899/examples/pytorch/ogb/ogbn-arxiv/models.py#L184

**Comment by yzh119** [comment]
@Espylapiza do you have any ideas?

**Comment by Espylapiza** [comment]
This is the standard symmetric normalization, because the sum of alpha is equal to 1, that is, we have averaged it when computing attention.

**Comment by skepsun** [comment]
@Espylapiza 
Alpha matrix (or attention matrix) is already row-wise normalized, the symmetric normalization for alpha matrix is already done without extra multiplications, as its "degree matrix" is just identity matrix. 

I can understand that applying extra normalization terms calculated from raw node degrees (in another word, gcn_norm style normalization terms) is to incorporate pure structural information into alpha matrix. But in the two-step normalization computations (src, dst), the term for dst nodes is calculated its reciprocal. I can confirm that it somehow works better, but it remains confusing.
<a href="https://www.codecogs.com/eqnedit.php?latex=\boldsymbol&space;A_{att}=[\alpha_{ij}],{\boldsymbol&space;D}_{att}={\boldsymbol&space;I},{\boldsymbol&space;D}={\rm&space;diag}(\{d_i\}),{\boldsymbol&space;H}^{l}={\boldsymbol&space;D}^{\frac{1}{2}}{\boldsymbol&space;A}_{att}{\boldsymbol&space;D}^{-\frac{1}{2}}{\boldsymbol&space;H}^{l-1}" target="_blank"><img src="https://latex.codecogs.com/gif.latex?\boldsymbol&space;A_{att}=[\alpha_{ij}],{\boldsymbol&space;D}_{att}={\boldsymbol&space;I},{\boldsymbol&space;D}={\rm&space;diag}(\{d_i\}),{\boldsymbol&space;H}^{l}={\boldsymbol&space;D}^{\frac{1}{2}}{\boldsymbol&space;A}_{att}{\boldsymbol&space;D}^{-\frac{1}{2}}{\boldsymbol&space;H}^{l-1}" title="\boldsymbol A_{att}=[\alpha_{ij}],{\boldsymbol D}_{att}={\boldsymbol I},{\boldsymbol D}={\rm diag}(\{d_i\}),{\boldsymbol H}^{l}={\boldsymbol D}^{\frac{1}{2}}{\boldsymbol A}_{att}{\boldsymbol D}^{-\frac{1}{2}}{\boldsymbol H}^{l-1}" /></a>

**Comment by Espylapiza** [comment]
It's not that complicated. Just consider the case when the attention values are equal on each edge, we should make GAT the same as GCN.

**Comment by yzh119** [comment]
@Espylapiza As attention values have been normalized by destination nodes, attention values can not be equal on all edges in non-uniform graphs.

**Comment by Espylapiza** [comment]
@yzh119 Do you mean irregular graphs? I mean when <img src="https://latex.codecogs.com/svg.latex?\boldsymbol&space;A_{att}=\boldsymbol&space;D^{-1}\boldsymbol&space;A" title="\boldsymbol A_{att}=\boldsymbol D^{-1}\boldsymbol A" />, and <img src="https://latex.codecogs.com/svg.latex?\boldsymbol&space;A_{att}" title="\boldsymbol A_{att}" /> is not a symmetric matrix.
Thus <img src="https://latex.codecogs.com/svg.latex?{\boldsymbol&space;H}^{l}={\boldsymbol&space;D}^{\frac{1}{2}}{\boldsymbol&space;A}_{att}{\boldsymbol&space;D}^{-\frac{1}{2}}{\boldsymbol&space;H}^{l-1}={\boldsymbol&space;D}^{-\frac{1}{2}}{\boldsymbol&space;A}{\boldsymbol&space;D}^{-\frac{1}{2}}{\boldsymbol&space;H}^{l-1}" title="{\boldsymbol H}^{l}={\boldsymbol D}^{\frac{1}{2}}{\boldsymbol A}_{att}{\boldsymbol D}^{-\frac{1}{2}}{\boldsymbol H}^{l-1}={\boldsymbol D}^{-\frac{1}{2}}{\boldsymbol A}{\boldsymbol D}^{-\frac{1}{2}}{\boldsymbol H}^{l-1}" />.

**Comment by yzh119** [comment]
That makes sense, thanks for your explaination.
