### ISSUE TITLE
cannot import name 'SSTBatch' from 'dgl.data'

### ISSUE THREAD

**Issue by Crescentz** [dmlc/dgl#2383]
## ❓ Questions and Help
`from dgl.data import SSTBatch`
or 'from dgl.data.tree import SSTBatch'

cannot import name 'SSTBatch' from 'xXXX'

**Comment by mufeili** [comment]
Where did you see that? Is this the same as `SSTDataset`(https://docs.dgl.ai/api/python/dgl.data.html#stanford-sentiment-treebank-dataset) ?

**Comment by Crescentz** [comment]
https://docs.dgl.ai/en/0.4.x/tutorials/models/2_small_graph/3_tree-lstm.html

`import dgl
from dgl.data.tree import SST
from dgl.data import SSTBatch`

**Comment by mufeili** [comment]
> https://docs.dgl.ai/en/0.4.x/tutorials/models/2_small_graph/3_tree-lstm.html

I think this has been replaced with `SSTDataset` in [the latest tutorial](https://docs.dgl.ai/en/latest/tutorials/models/2_small_graph/3_tree-lstm.html) as of DGL 0.5.0. If you really need to use `SSTBatch`, you can install DGL 0.4.x.
