### ISSUE TITLE
Simplify RGCN Example

### ISSUE THREAD

**Issue by mufeili** [dmlc/dgl#2388]
## 🚀 Feature

The current RGCN example seems to be too complex. For example, `entity_classify_mp.py` has more than 600 lines of code. We should try simplifying it.

**Comment by ZZy979** [comment]
I have a simpler implementation at https://github.com/ZZy979/pytorch-tutorial/tree/master/pytorch_tutorial/gnn/rgcn
But it doesn't support minibatch or distributed parallel training.

**Comment by mufeili** [comment]
> I have a simpler implementation at https://github.com/ZZy979/pytorch-tutorial/tree/master/pytorch_tutorial/gnn/rgcn
> But it doesn't support minibatch or distributed parallel training.

@classicsong @jermainewang Can you take a look?
