### ISSUE TITLE
DGLError when creating array of DGLGraphs

### ISSUE THREAD

**Issue by wendli01** [dmlc/dgl#2416]
## 🐛 Bug

Creating a `np.ndaray` of `DGLGraph`s results in a DGLError.

Easily indexable feature arrays are very useful and wrapping a Sequence in a numpy array achieves this.
However, doing this for DGLGraphs seems to be broken, going from v0.4.3 to v0.5.3 in my case.

## To Reproduce

Steps to reproduce the behavior (MWE):

```python
from dgl import DGLGraph
import numpy as np
np.array([DGLGraph(), DGLGraph()])
```

```python
---------------------------------------------------------------------------
DGLError                                  Traceback (most recent call last)
<ipython-input-45-34f27a1a6a1c> in <module>
      1 from dgl import graph
----> 2 np.array([graph([]), graph([]),])

~/anaconda3/envs/cross/lib/python3.7/site-packages/dgl/heterograph.py in __getitem__(self, key)
   1966 
   1967         if len(etypes) == 0:
-> 1968             raise DGLError('Invalid key "{}". Must be one of the edge types.'.format(orig_key))
   1969 
   1970         if len(etypes) == 1:

DGLError: Invalid key "0". Must be one of the edge types.
```

## Expected behavior

An array of DGLGraphs.

## Environment

 - DGL Version: 0.5.3
 - Backend Library & Version: pytorch 1.7.1
 - OS (e.g., Linux): Ubuntu 18.04 LTS
 - How you installed DGL: conda
 - Python version: 3.7.6
 - numpy version: 1.19.2

## Workaround

The expected result can still be achieved by avoiding calls to `numpy.shape`, inelegant as it may be:
```python
from dgl import DGLGraph
import numpy as np
graphs = [DGLGraph(), DGLGraph()]
a = np.empty(len(graphs), dtype=DGLGraph)
for i, graph in enumerate(graphs):
    a[i] = graph
```

**Comment by yzh119** [comment]
Could you please elaborate more on the motivation of wrapping a list in a numpy array (A python list is enough in my opinion)?
btw, you can you `dgl.batch` to batch a list of graphs.

**Comment by wendli01** [comment]
@yzh119 The motivation is mostly convenience, such as indexing.
It also allows for manipulation with all numpy functions, e.g. `nump.random.choose`, `np.random.permutation`, `np.take` and so forth.
`dgl.batch` does not cover any of that functionality.

Going further, I use numpy quite often as it offers much better handling of stochasticity, e.g. multiple RNGs for different purposes.

**Comment by yzh119** [comment]
Got it, in dgl 0.5 the `__getitem__` function is not compatible with numpy:
https://github.com/dmlc/dgl/blob/1c976222d54162a03fa75be8a35be3d644b87bae/python/dgl/heterograph.py#L1875

because we merged homogeneous graph (graph with single node/edge type) and heterogeneous graph (graph with multiple node/edge types), I'll try to find a way to make it compatible with numpy.
