### ISSUE TITLE
float16 support

### ISSUE THREAD

**Issue by ufimtsev** [dmlc/dgl#2423]
## 🚀 Feature
Please add float16 support. I modified src/kernel/common.h as suggested here https://discuss.dgl.ai/t/builtin-functions-give-unsupported-dtype-error-on-torch-double-tensors/411 

`// Macro for dispatch dtype flag to template argument. Currently only
// support float32.
#define DGL_DTYPE_SWITCH(val, DType, ...)       
  if (val.code == kDLFloat && (val.bits == 32 || val.bits == 16)) { 
    typedef float DType;                        
    { __VA_ARGS__ }                             
  } else {                                      
    LOG(FATAL) << "Unsupported dtype: " << val; 
  }`

but then I'm getting this error...
dgl._ffi.base.DGLError: but then I get dgl/src/array/kernel.cc:94: Feature data can only be float32 or float64

is there any possible work around at this point? Thanks!

**Comment by yzh119** [comment]
@ufimtsev Thanks for the feature request.
Currently you can use the following workaround:
https://discuss.dgl.ai/t/is-there-a-way-of-running-graphsage-model-with-half-precision/1372/3

**Comment by yzh119** [comment]
Solved in #2552 .
@ufimtsev [this tutorial](https://docs.dgl.ai/en/latest/guide/mixed_precision.html) explains how to do mixed precision training in DGL.
