### ISSUE TITLE
Compilation on osx-arm64 apple silicon m1

### ISSUE THREAD

**Issue by yingzhu146** [dmlc/dgl#2424]
## 🐛 Bug

Trying to compile from source on the new macbook air with arm64e. 

## To Reproduce

mkdir build
cd build
cmake ..
make -j 8

```
/Users/yingzhu/dgl/include/intel/cpu_support.h:70:16: error: no type named 'Reg64' in namespace 'Xbyak'
  const Xbyak::Reg64 &r_out_;
        ~~~~~~~^
/Users/yingzhu/dgl/include/intel/cpu_support.h:71:16: error: no type named 'Reg64' in namespace 'Xbyak'
  const Xbyak::Reg64 &r_left_;
        ~~~~~~~^
/Users/yingzhu/dgl/include/intel/cpu_support.h:72:16: error: no type named 'Reg64' in namespace 'Xbyak'
  const Xbyak::Reg64 &r_right;
        ~~~~~~~^
/Users/yingzhu/dgl/include/intel/cpu_support.h:73:16: error: no type named 'Reg64' in namespace 'Xbyak'
  const Xbyak::Reg64 &r_size_;
        ~~~~~~~^
/Users/yingzhu/dgl/include/intel/cpu_support.h:156:42: error: use of undeclared identifier 'r9'
    alias_load<IType>(zmm0, ptr[r_out_ + r9 * sizeof(IType)]);
                                        ^
```
## Expected behavior

Build without error

## Environment

 - DGL Version from master
 - Backend Library & Version pytorch 1.7 installed
 - OS (e.g., Linux): osx-arm64
 - How you installed DGL (`conda`, `pip`, source): source
 - Build command you used (if compiling from source): see above
 - Python version: 3.8.5
 - CUDA/cuDNN version (if applicable): na
 - GPU models and configuration (e.g. V100): na 
 - Any other relevant information:

## Additional context

It clearly tries to use intel-specifc code - is there support for arm? i would expect 80% of all mac users to switch to arm in the next 5 years

**Comment by yzh119** [comment]
Yes that's related to intel-specific optimizations (use AVX instructions, see #2309 ). Actually we should only include this header when a intel CPU with avx support is detected, I'll fix it soon.

**Comment by yingzhu146** [comment]
@yzh119 thanks keep me posted. sorry for being dense but setting `DGL_CPU_INTEL_KERNEL_ENABLED=0` doesn't work for me - any other way to disable this so I can build in mean time?

**Comment by yzh119** [comment]
`DGL_CPU_INTEL_KERNEL_ENABLED=0` only controls whether to use AVX optimized operator at runtime instead of compile time, I'll set a cmake flag to indicate whether to include the header at compile time.

**Comment by yzh119** [comment]
@yingzhu146 does #2428 works in your case? (checkout the `fix-arm` branch in my fork).

**Comment by yingzhu146** [comment]
@yzh119 yes that worked perfectly thanks a lot for the help!
