### ISSUE TITLE
[Batching] Require Graphs with No Edges/Nodes to Have the Same Data Schema

### ISSUE THREAD

**Issue by mufeili** [dmlc/dgl#2440]
## 🚀 Feature
Currently, `dgl.batch` skips node/edge types without instances for feature concatenation [here](https://github.com/dmlc/dgl/blob/master/python/dgl/batch.py#L14). Below is an example

```python
import dgl
import torch

# Case1: One graph is empty, the other is not
g1 = dgl.graph(([1, 0], [2, 0]))
g1.edata['h'] = torch.randn(2, 1)
g2 = dgl.graph(([], []))
g2.edata['h'] = torch.randn(0, 1)
bg = dgl.batch([g1, g2])
print(bg.edata.keys())
# dict_keys(['h'])

# Case2: Both graphs are empty with feature placeholders
g3 = dgl.graph(([], []))
g3.edata['h'] = torch.randn(0, 1)
g4 = dgl.graph(([], []))
g4.edata['h'] = torch.randn(0, 1)
bg = dgl.batch([g3, g4])
print(bg.edata.keys())
# dict_keys([])
```

A related issue is https://github.com/awslabs/dgl-lifesci/issues/117.

## Motivation

When a user has multiple heterogeneous graphs to work with, each has multiple node/edge types, this can happen silently in graph construction and yield errors hard to track.

## Pitch

- Require graphs with no edges/nodes to have the same data schema
- If all graphs have a particular node/edge feature, then `dgl.batch` should perform feature concatenation whether the graphs are empty or not.

**Comment by jermainewang** [comment]
Fixed in #2527.
