### ISSUE TITLE
get stucked when runing the "dgl.prop_nodes_topo" on Linux with Cuda

### ISSUE THREAD

**Issue by unikcc** [dmlc/dgl#2441]
## 🐛 Bug

I use the dgl to implement TreeLSTM, which refer to [https://github.com/dmlc/dgl/tree/master/examples/pytorch/tree_lstm](https://github.com/dmlc/dgl/tree/master/examples/pytorch/tree_lstm). 
But the program get stuck in this [line:](https://github.com/dmlc/dgl/blob/5d3da4bcefb50840bb47818abb51c190af83bba7/examples/pytorch/tree_lstm/tree_lstm.py#L108) for a long long time. It doesn't output anything or proceed to the next step.
When I run the same code on Windows, it runs fluently, no matter GPU or CPU the device is. 
If I switch the model device from CUDA to CPU on Linux, It also work normally.

## To Reproduce

```python 
        embeds = self.embedding(batch.node_value * batch.mask)
        g.ndata['iou'] = self.cell.W_iou(self.dropout(embeds)) * batch.mask.float().unsqueeze(-1)
        g.ndata['h'] = h
        g.ndata['c'] = c
        # propagate

        dgl.prop_nodes_topo(g, self.cell.message_func, self.cell.reduce_func, apply_node_func=self.cell.apply_node_func)
        graphs =dgl.unbatch(g)
        hidden_states = []
        word_states, np_states = [], []
        max_nodes_num = max([graph.number_of_nodes() for graph in graphs])
        max_word_num = max([(graph.ndata['np'] == 0).sum() for graph in graphs])
        max_np_num = max([(graph.ndata['np'] == 1).sum() for graph in graphs])
        ...
```

## Environment

 - DGL Version (e.g., 1.0): dgl-cu101            0.6a201218
 - Backend Library & Version (e.g., PyTorch 0.4.1, MXNet/Gluon 1.3): PyTorch 1.4.0
 - OS (e.g., Linux): Ubuntu 20.04
 - How you installed DGL (`conda`, `pip`, source): pip 
 - Build command you used (if compiling from source): None
 - Python version: 3.7.4
 - CUDA/cuDNN version (if applicable): Cuda V10.1.243  CUDNN: 7.41
 - GPU models and configuration (e.g. V100): RTX 2080Ti
 - Any other relevant information:

**Comment by mufeili** [comment]
Did you directly run the DGL example? I tried running the example on Linux with GPU and it worked well.

**Comment by unikcc** [comment]
> Did you directly run the DGL example? I tried running the example on Linux with GPU and it worked well.

I run the TreeLSTM example, It throw `RuntimeError: CUDA error: invalid configuration argument`

Then I update the torch version from 1.4.0 to 1.5.0, It works well on GPU, Thank You!
