### ISSUE TITLE
Supporting TPU

### ISSUE THREAD

**Issue by Junyoungpark** [dmlc/dgl#2444]
## ❓ Questions and Help

Hi, I'm wondering the DGL team has a plan for supporting TPU for pytorch backend. If so, when the TPU supporting version DGL would release?

**Comment by VoVAllen** [comment]
Hi,

I don't think we will support TPU through pytorch backend. Probably we will support TPU by jax backend.

There's no public information on how to implement TPU kernels, so we can only port our kernel over XLA to support TPU. I'm not sure how we can do this over pytorch for the ragged tensor. And through the benchmark, the performance over XLA on cuda is significantly worse than our current custom cuda kernel. Therefore I would believe you will see similar bad performance if we support TPU through JAX.

**Comment by Junyoungpark** [comment]
Thanks for the clear explanation @VoVAllen!
