### ISSUE TITLE
WN18Dataset.__len__ raises NameError

### ISSUE THREAD

**Issue by ZZy979** [dmlc/dgl#2473]
## 🐛 Bug

`WN18Dataset.__len__` raises `NameError: name 'idx' is not defined`, same problem for `FB15k237Dataset` and `FB15kDataset`

## To Reproduce

```
>>> from dgl.data import WN18Dataset
>>> data = WN18Dataset()
>>> len(data)
Traceback (most recent call last):
...
  File "D:\anaconda3\envs\academic\lib\site-packages\dgl\data\knowledge_graph.py", line 740, in __len__
    return super(WN18Dataset, self).__len__(idx)
NameError: name 'idx' is not defined
```

Both `FB15k237Dataset` and `FB15kDataset` also have this problem.

## Expected behavior

It should return 1
The problem is caused by the extra argument `idx`:
```python
def __len__(self):
    r"""The number of graphs in the dataset."""
    return super(FB15kDataset, self).__len__(idx)
```

## Environment

 - DGL Version (e.g., 1.0): 0.5.2
 - Backend Library & Version (e.g., PyTorch 0.4.1, MXNet/Gluon 1.3): PyTorch 1.6.0
 - OS (e.g., Linux): Windows 10
 - How you installed DGL (`conda`, `pip`, source): `pip`
 - Build command you used (if compiling from source):
 - Python version: 3.7.6
 - CUDA/cuDNN version (if applicable):
 - GPU models and configuration (e.g. V100):
 - Any other relevant information:

**Comment by classicsong** [comment]
Confirmed bug.
