### ISSUE TITLE
Interacts with aws-data-wrangler to cause crashes

### ISSUE THREAD

**Issue by zjost** [dmlc/dgl#2477]
## 🐛 Bug

In a Jupyter notebook, if I import DGL before aws-data-wrangler (wr), the kernel will crash when I try to use wr.  If I import DGL after wr, it works fine. 

## To Reproduce

```
import dgl # results in crash if imported here
import awswrangler as wr
# import dgl # works fine if imported here

df = wr.s3.read_parquet(
    "s3://<MY_PARQUET>", 
    dataset=True,
)
```

## Environment

 - DGL Version (e.g., 1.0): 0.5.2 (dgl-cu100==0.5.2)
 - Backend Library & Version (e.g., PyTorch 0.4.1, MXNet/Gluon 1.3): PyTorch 1.5.0
 - OS (e.g., Linux):  Amazon Linux?  (SageMaker notebook on p3)
 - How you installed DGL (`conda`, `pip`, source):  I don't remember.  Probably pip.  Definitely not from source.
 - Python version:  Python 3.6.10
 - CUDA/cuDNN version (if applicable): 10.0
 - GPU models and configuration (e.g. V100):  p3 instance

## Additional context
As mentioned, the above code will crash the Jupyter kernel.  However, running in a terminal gives the following output:
```
terminate called after throwing an instance of 'std::regex_error'
  what():  Number of NFA states exceeds limit. Please use shorter regex string, or use smaller braceexpression, or make _GLIBCXX_REGEX_STATE_LIMIT larger.
Aborted
```

**Comment by VoVAllen** [comment]
Probably related to https://github.com/dmlc/dgl/issues/2255 @BarclayII

**Comment by YankeeTsao** [comment]
Same question. Have you solved this?

**Comment by VoVAllen** [comment]
I cannot reproduce it on my own machine (ubuntu 16.04) but can reproduce it on the aws sagemaker instances.
Sample code below
```python
import dgl
bucket = 'xxxx'
path = f"s3://{bucket}/test_parquet/"
from datetime import date
import awswrangler as wr
import pandas as pd
df = pd.DataFrame({
    "id": [1, 2],
    "value": ["foo", "boo"],
    "date": [date(2020, 1, 1), date(2020, 1, 2)]
})
wr.s3.to_parquet(
    df=df,
    path=path,
    dataset=True,
    mode="overwrite"
)
wr.s3.read_parquet(path, dataset=True)
```

**Comment by VoVAllen** [comment]
I found this is solved by using the nightly build of dgl. Probably related to the RTLD_GLOBAL flag

**Comment by jermainewang** [comment]
@zjost @YankeeTsao Would you please try install DGL's nightly build to see whether the issue still exists?

**Comment by YankeeTsao** [comment]
> @zjost @YankeeTsao Would you please try install DGL's nightly build to see whether the issue still exists?

I'll try later. Thanks!

**Comment by YankeeTsao** [comment]
> @zjost @YankeeTsao Would you please try install DGL's nightly build to see whether the issue still exists?
@jermainewang I have tried the nightly build of DGL with different versions of PyTorch(1.5.0, 1.6.0, 1.7.0), and all work fine.
