### ISSUE TITLE
Graph meta data not updating in heterogeneous subgraphs

### ISSUE THREAD

**Issue by Andy-Border** [dmlc/dgl#2493]
## 🐛 Bug
The subgraph generated by `dgl.node_subgraph()` function copies the graph meta data (e.g. node types and edge types) of the original graph even if the graph meta data has changed.

The incorrect graph meta data becomes more troublesome when converting the sampled heterogeneous subgraphs to homogeneous by `dgl.to_homogeneous()`. Check the example below.

## To Reproduce

```python
import torch
import dgl
# Construct a toy hete subgraph with features
g = dgl.heterograph({
    ('user', 'plays', 'game'): ([0, 1, 1, 2], [0, 0, 2, 1]),
    ('user', 'follows', 'user'): ([0, 1, 1], [1, 2, 2])
})
g.nodes['user'].data['feat'] = torch.Tensor([[1,0],[0,1],[1,1]])
sub_g = dgl.node_subgraph(g, {'user': [1, 2]})
print(sub_g)
# Accessing subgraph features
sub_homo_g1 = dgl.to_homogeneous(sub_g, ndata=['feat'])
features = sub_homo_g1.ndata['feat'] # KeyError: 'feat'
```

The code above will generate a "KeyError: 'feat'" error 

```shell
Using backend: pytorch
Graph(num_nodes={'game': 0, 'user': 2},
      num_edges={('user', 'follows', 'user'): 2, ('user', 'plays', 'game'): 0},
      metagraph=[('user', 'user', 'follows'), ('user', 'game', 'plays')])
Traceback (most recent call last):
  File "/home/zja/PyProject/SSHINE/src/models/SSHINE/hg_encoder.py", line 188, in <module>
    sub_homo_g1 = dgl.to_homogeneous(sub_g, ndata=['feat'])
  File "/home/zja/anaconda3/envs/dglnew/lib/python3.8/site-packages/dgl/convert.py", line 665, in to_homogeneous
    comb_nf = combine_frames(G._node_frames, range(len(G.ntypes)), col_names=ndata)
  File "/home/zja/anaconda3/envs/dglnew/lib/python3.8/site-packages/dgl/heterograph.py", line 5777, in combine_frames
    schemes = {key: frames[ids[0]].schemes[key] for key in col_names}
  File "/home/zja/anaconda3/envs/dglnew/lib/python3.8/site-packages/dgl/heterograph.py", line 5777, in <dictcomp>
    schemes = {key: frames[ids[0]].schemes[key] for key in col_names}
KeyError: 'feat'

Process finished with exit code 1
```

As we can see in the message above, the metagraph of subgraph is incorrect, with node type 'game' still exists. This inconsistancy leads to failure in accessing features after converting the hete subgraphs to homogeneous graph.

## A Workaround

A simple workaround would be to manually subset the subgraph before converting to homogeneous graph.

```python
# Obtain sub_g via the code shown above
# Manually subset types before convertion
sub_g2 = dgl.node_type_subgraph(sub_g, ['user'])
sub_homo_g2 = dgl.to_homogeneous(sub_g2, ndata=['feat']) # works fine
```

## Expected behavior

Described above.

## Environment

 - DGL Version: 0.5.3
 - Backend Library & Version: Pytorch 1.7.0
 - OS (e.g., Linux): Linux
 - How you installed DGL (`conda`, `pip`, source): pip install dgl-cu101
 - Build command you used (if compiling from source):
 - Python version: 3.8.3
 - CUDA/cuDNN version (if applicable): 10.1
 - GPU models and configuration (e.g. V100): GeForce GTX 1080
 - Any other relevant information:

## Additional context

I found this problem while I was trying to apply homogeneous GNNs (e.g. GCN, GIN) on sampled heterogeneous subgraphs.

**Comment by hedantas** [comment]
Any news?

**Comment by Rhett-Ying** [comment]
1. metagraph of the subgraph after calling dgl.subgraph() is expected. 'game' exists indeed. if you want 'user' only, dgl.node_type_subgraph() should be used.
2. as for the crash issue when calling dgl.to_homogeneous(), this is actually a bug. confirmed. FYI, here's a PR I just made for fix: https://github.com/dmlc/dgl/pull/3110. I will get back to you if PR is updated/merged.

**Comment by Rhett-Ying** [comment]
Hi, PR has been merged into DGL master branch. could you have a try?
