### ISSUE TITLE
tensor to adaptive adjacency matrix

### ISSUE THREAD

**Issue by WangYibucea** [dmlc/dgl#2494]
How to pass tensor into DGLgraph and make this tensor back-propagated so as to achieve adaptive adjacency matrix.

**Comment by VoVAllen** [comment]
The key idea is considering each entry in adjacency matrix as edata. 
You can take a look on this thread https://discuss.dgl.ai/t/gradient-wrt-input-using-dglgraph/977 and this one https://discuss.dgl.ai/t/how-to-compute-the-gradient-of-edge-with-respect-to-some-loss/860/2

**Comment by WangYibucea** [comment]
Thanks for your help. 
But
"dgl.update_all(fn.copy_u('h', 'm'), fn.sum('m', 'h_neigh')) " and  "dgl.update_all(fn.u_mul_e('h', 'weight', 'm'), fn.sum('m', 'h_neigh'))"

I do not understand too much, could you explain the code and meaning in detail？

**Comment by VoVAllen** [comment]
@WangYibucea When the weight is all one, they are the same. (fn.u_mul_e is multiplying one, which is an identity mapping) All one means all entry in adjacency matrix is one. Similar for the weighted adjacency matrix
