### ISSUE TITLE
Wrong number of edges in using dgl.from_networkx(G)

### ISSUE THREAD

**Issue by 3mmjd** [dmlc/dgl#2499]
## 🐛 Bug

When I use dgl.from_networkx() to convert a network to dgl graph, the number of edges becomes twice!
my network is undirected and the adjacency matrix is symmetric. 

## To Reproduce
-------------------------------------------
```python
adjacency_matrix = np.load('Adjacency_matrix.npy')
G = nx.convert_matrix.from_numpy_array(adjacency_matrix)
g = dgl.from_networkx(G)
g
```
-------------------------------------------
```
Graph(num_nodes=8508, num_edges=135984,
      ndata_schemes={'train_mask': Scheme(shape=(), dtype=torch.bool), 'val_mask': Scheme(shape=(), dtype=torch.bool), 'test_mask': Scheme(shape=(), dtype=torch.bool), 'label': Scheme(shape=(), dtype=torch.int64), 'feat': Scheme(shape=(33,), dtype=torch.float32)}
      edata_schemes={})
```
-------------------------------------------
```python
G.number_of_edges()
```
-------------------------------------------
```
67992
```

**Comment by mufeili** [comment]
NetworkX uses separate data structures to handle directed and undirected graphs while DGL uses a unified data structure to represent both of them. See [Creating Graphs from External Libraries](https://docs.dgl.ai/guide/graph-external.html#creating-graphs-from-external-libraries) for more details.
