### ISSUE TITLE
 cuda11.1+dgl-cuda11.0 can't run

### ISSUE THREAD

**Issue by wangzeyu135798** [dmlc/dgl#2507]
## ❓ Questions and Help
Hi:
   My cuda version is 11.1 and dgl is dgl-cuda11.0. I install  this dgl according to your github web guide. While I meet a question as following:
   dgl._ffi.base.DGLError: [22:06:34] /opt/dgl/include/dgl/packed_func_ext.h:117: Check failed: ObjectTypeChecker<TObjectRef>::Check(sptr.get()): Expected type graph.Graph but get graph.HeteroGraph
    My dgl data is stored in dgl-10.1.
    I'm looking forward your reply.
    Thanks.

**Comment by VoVAllen** [comment]
What API are you using? This not seems a cuda problem. Can you try cpu-only dgl version

**Comment by wangzeyu135798** [comment]
Hi:
&nbsp; &nbsp;The API i used is dgl.contrib.sampling.random walk to get a trace based on a seed node. When my cuda is 11 and dgl is cu110, the code problem is as following:
&nbsp; &nbsp;




While in cuda 10 the code is OK.


------------------&nbsp;原始邮件&nbsp;------------------
发件人:                                                                                                                        "dmlc/dgl"                                                                                    <notifications@github.com&gt;;
发送时间:&nbsp;2021年1月8日(星期五) 晚上11:57
收件人:&nbsp;"dmlc/dgl"<dgl@noreply.github.com&gt;;
抄送:&nbsp;"天津工业大学王泽宇"<1051533398@qq.com&gt;;"Author"<author@noreply.github.com&gt;;
主题:&nbsp;Re: [dmlc/dgl]  cuda11.1+dgl-cuda11.0 can't run (#2507)





 
What API are you using? This not seems a cuda problem. Can you try cpu-only dgl version?

**Comment by VoVAllen** [comment]
@BarclayII What's the alternative of `dgl.contrib.sampling.random_walk` in dgl 0.5+?

**Comment by VoVAllen** [comment]
`dgl.contrib.sampling.random_walk` is deprecated in dgl 0.5+. You can use new API `dgl.sampling.random_walk` or use old version by `pip install "dgl-cuXX<0.5"`

**Comment by wangzeyu135798** [comment]
I used API is dgl.contrib.sampling.random_walk_with_restart and&nbsp; I want to learn the changed API.




------------------&nbsp;原始邮件&nbsp;------------------
发件人:                                                                                                                        "dmlc/dgl"                                                                                    <notifications@github.com&gt;;
发送时间:&nbsp;2021年1月11日(星期一) 下午3:28
收件人:&nbsp;"dmlc/dgl"<dgl@noreply.github.com&gt;;
抄送:&nbsp;"天津工业大学王泽宇"<1051533398@qq.com&gt;;"Author"<author@noreply.github.com&gt;;
主题:&nbsp;Re: [dmlc/dgl]  cuda11.1+dgl-cuda11.0 can't run (#2507)





 
dgl.contrib.sampling.random_walk is deprecated in dgl 0.5+. You can use new API dgl.sampling.random_walk or use old version by pip install "dgl-cuXX<0.5"

**Comment by wangzeyu135798** [comment]
My dgl version now is 0.5+, in files I find there is a function dgl.sampling.random_walk_with_restart, while when i&nbsp; run this code, there is a problem that "module dgl.sampling has no attribute random_walk_with_restart"






------------------&nbsp;原始邮件&nbsp;------------------
发件人:                                                                                                                        "dmlc/dgl"                                                                                    <notifications@github.com&gt;;
发送时间:&nbsp;2021年1月11日(星期一) 下午3:28
收件人:&nbsp;"dmlc/dgl"<dgl@noreply.github.com&gt;;
抄送:&nbsp;"天津工业大学王泽宇"<1051533398@qq.com&gt;;"Author"<author@noreply.github.com&gt;;
主题:&nbsp;Re: [dmlc/dgl]  cuda11.1+dgl-cuda11.0 can't run (#2507)





 
dgl.contrib.sampling.random_walk is deprecated in dgl 0.5+. You can use new API dgl.sampling.random_walk or use old version by pip install "dgl-cuXX<0.5"

**Comment by BarclayII** [comment]
`dgl.sampling.random_walk` includes a `restart_prob` argument.  Please feel free to give it a try.

**Comment by wangzeyu135798** [comment]
Yes, I totally input the corresponding params. While the error is 'module dgl.module has no attribute random_walk_with_restart'




------------------&nbsp;原始邮件&nbsp;------------------
发件人:                                                                                                                        "dmlc/dgl"                                                                                    <notifications@github.com&gt;;
发送时间:&nbsp;2021年1月11日(星期一) 下午4:42
收件人:&nbsp;"dmlc/dgl"<dgl@noreply.github.com&gt;;
抄送:&nbsp;"天津工业大学王泽宇"<1051533398@qq.com&gt;;"Author"<author@noreply.github.com&gt;;
主题:&nbsp;Re: [dmlc/dgl]  cuda11.1+dgl-cuda11.0 can't run (#2507)





 
dgl.sampling.random_walk includes a restart_prob argument.  Please feel free to give it a try.

**Comment by wangzeyu135798** [comment]
------------------&nbsp;原始邮件&nbsp;------------------
发件人:                                                                                                                        "dmlc/dgl"                                                                                    <notifications@github.com&gt;;
发送时间:&nbsp;2021年1月11日(星期一) 下午4:42
收件人:&nbsp;"dmlc/dgl"<dgl@noreply.github.com&gt;;
抄送:&nbsp;"天津工业大学王泽宇"<1051533398@qq.com&gt;;"Author"<author@noreply.github.com&gt;;
主题:&nbsp;Re: [dmlc/dgl]  cuda11.1+dgl-cuda11.0 can't run (#2507)





 
dgl.sampling.random_walk includes a restart_prob argument.  Please feel free to give it a try.

**Comment by wangzeyu135798** [comment]
My cuda version is cuda 11.1, so I need install dgl-cu110,while this dgl-cu110 version at least is 0.5.3.






------------------&nbsp;原始邮件&nbsp;------------------
发件人:                                                                                                                        "dmlc/dgl"                                                                                    <notifications@github.com&gt;;
发送时间:&nbsp;2021年1月11日(星期一) 下午3:28
收件人:&nbsp;"dmlc/dgl"<dgl@noreply.github.com&gt;;
抄送:&nbsp;"天津工业大学王泽宇"<1051533398@qq.com&gt;;"Author"<author@noreply.github.com&gt;;
主题:&nbsp;Re: [dmlc/dgl]  cuda11.1+dgl-cuda11.0 can't run (#2507)





 
dgl.contrib.sampling.random_walk is deprecated in dgl 0.5+. You can use new API dgl.sampling.random_walk or use old version by pip install "dgl-cuXX<0.5"

**Comment by yzh119** [comment]
@wangzeyu135798 could you please elaborating more on
> Yes, I totally input the corresponding params. While the error is 'module dgl.module has no attribute random_walk_with_restart'

How do you use `dgl.sampling.random_walk`? Would you mind posting a code snippet?

**Comment by hughiephan** [comment]
@yzh119 Here's an example of  `dgl.sampling.random_walk` 

From this (old-version)
```
g1 = dgl.graph(([0, 1, 1, 2, 3], [1, 2, 3, 0, 0]))
dgl.sampling.random_walk_with_restart(g1, [0, 1, 2, 0], restart_prob=0.9, max_nodes_per_seed=4)
```

To this (new-version)
```
g1 = dgl.graph(([0, 1, 1, 2, 3], [1, 2, 3, 0, 0]))
dgl.sampling.random_walk(g1, [0, 1, 2, 0], restart_prob=0.9, length = 4)
```
