### ISSUE TITLE
AmazonCoBuyPhotoDataset num_classes returns incorrect number of classes

### ISSUE THREAD

**Issue by titaniumrain** [dmlc/dgl#2509]
## 🐛 Bug

AmazonCoBuyPhotoDataset num_classes returns incorrect number of classes

## To Reproduce

1. run the following piece of code

import dgl
import numpy as np
data = dgl.data.AmazonCoBuyPhotoDataset()
g = data[0]
num_class = data.num_classes
feat = g.ndata['feat']  # get node feature
label = g.ndata['label']  # get node labels
print(len(np.unique(label)), num_class)

you then get, 

>>> 8 5

## Expected behavior

These two variables should be the same.

## Environment

 - DGL Version: 0.5.3
 - Backend Library & Version: Pytorch 1.6.0
 - OS: Linux 18.04

**Comment by VoVAllen** [comment]
Hi,

This is already fixed by https://github.com/dmlc/dgl/pull/2488, which should be available through nightly build now. You can try it by `pip install --pre dgl` or `pip install --pre dgl-cuXX`
