### ISSUE TITLE
Putting the graph on GPU will arise AssertionError: all the graphs must be on CPU

### ISSUE THREAD

**Issue by YankeeTsao** [dmlc/dgl#2514]
When I trained unsupervised graphsage model, too much time was wasted on I/O between CPU and GPU. Therefore, I put the whole graph on GPU.

```
def run(proc_id, n_gpus, args, devices, data):
    device = devices[proc_id]
    in_feats, g = data
    g = g.to(device)
```

And got the following error：
File "dgl/transform.py", line 1526, in compact_graphs
assert all(g.device == F.cpu() for g in graphs), 'all the graphs must be on CPU'

**Comment by mufeili** [comment]
If you use the example DGL code for unsupervised GraphSage, it performs mini-batch training and you don't need to put the whole graph on GPU.

**Comment by YankeeTsao** [comment]
> If you use the example DGL code for unsupervised GraphSage, it performs mini-batch training and you don't need to put the whole graph on GPU.

It cost too much time on I/O between CPU and GPU. I tried to tune the parameter  'num_workers' of DataLoader, but got another error: shm-size is sufficient(Running in docker). That's why I want to put the whole graph on GPU.

**Comment by mufeili** [comment]
@BarclayII Have you profiled this example before? Any suggestions?

**Comment by VoVAllen** [comment]
@YankeeTsao You can manually increase the shared memory size inside docker by `--shm-size 4G` to increase it to 4G

**Comment by YankeeTsao** [comment]
> @YankeeTsao You can manually increase the shared memory size inside docker by `--shm-size 4G` to increase it to 4G

Exactly! However, I don't have permission to modify the docker. Is there any other chance to decrease the time wasted on I/O between CPU and GPU? Thanks for help!

**Comment by BarclayII** [comment]
The tricky thing is that currently `EdgeDataLoader` will require the graph to reside on CPU, since it uses the function `dgl.compact_graphs` and `dgl.to_block`, both of which currently do not have GPU implementation.

One possible workaround is to put the features on GPU while putting the graph topology itself on CPU, so you don't have to spend time copying node features from CPU to GPU.  That is, instead of calling `g.to(device)`, add a `.cuda()` call to the following statement:
https://github.com/dmlc/dgl/blob/5d4995e6e8381ecc3c6b9b3e6e3a8eb9d0bf72c8/examples/pytorch/graphsage/train_sampling_unsupervised.py#L179
while keeping `g` unchanged.

**Comment by YankeeTsao** [comment]
> The tricky thing is that currently `EdgeDataLoader` will require the graph to reside on CPU, since it uses the function `dgl.compact_graphs` and `dgl.to_block`, both of which currently do not have GPU implementation.
> 
> One possible workaround is to put the features on GPU while putting the graph topology itself on CPU, so you don't have to spend time copying node features from CPU to GPU. That is, instead of calling `g.to(device)`, add a `.cuda()` call to the following statement:
> https://github.com/dmlc/dgl/blob/5d4995e6e8381ecc3c6b9b3e6e3a8eb9d0bf72c8/examples/pytorch/graphsage/train_sampling_unsupervised.py#L179
> 
> 
> while keeping `g` unchanged.

I move g.ndata['feat'] to GPU, which still doesn't work. (The graph has 650 thousand nodes and 5 million edges, and the dimention of the features is 24.)
``
def run(proc_id, n_gpus, args, devices, data):
    device = devices[proc_id]
    in_feats, g = data
    nfeat = g.ndata.pop('feat').to(device)
    ...
    ...
    # Training loop
    for epoch in range(args.num_epochs):
        for step, (input_nodes, pos_graph, neg_graph, blocks) in enumerate(dataloader):
            # batch_inputs = load_subtensor(g, input_nodes, device)
            batch_inputs = nfeat[input_nodes]
            ...
            ...
``

**Comment by BarclayII** [comment]
Is the error reported in
```python
batch_inputs = nfeat[input_nodes]
```
?

`input_nodes` is on CPU in this case.  You will need this:
```python
batch_inputs = nfeat[input_nodes.cuda()]
```

**Comment by YankeeTsao** [comment]
> Is the error reported in
> 
> ```python
> batch_inputs = nfeat[input_nodes]
> ```
> 
> ?
> 
> `input_nodes` is on CPU in this case. You will need this:
> 
> ```python
> batch_inputs = nfeat[input_nodes.cuda()]
> ```

No errors. It's just that the training time hasn't been shortened.
