### ISSUE TITLE
[Bug][Windows] Python cannot pickle DGLDataset._hash_func during multiprocessing GraphDataLoader startup

### ISSUE THREAD

**Issue by dylansnow** [dmlc/dgl#2530]
## 🐛 Bug

SAGPool example not working. Attempted running examples/pytorch/sagpool/main.py with command `python main.py --dataset 'DD'` and received error 'Import Error: cannot import name 'GraphDataLoader' from 'dgl.dataloading'. Cannot run SAGPool training.

```powershell
git clone https://github.com/dmlc/dgl.git
cd dgl
python -m venv dgl-env
dgl-env/scripts/activate
pip install torch==1.7.1+cu101 torchvision==0.8.2+cu101 torchaudio===0.7.2 -f https://download.pytorch.org/whl/torch_stable.html
pip install dgl-cu101
cd examples/pytorch/sagpool
python main.py --dataset 'DD' <-- error occurs here
```

Error message:

Using backend: pytorch
Traceback (most recent call last):
  File "main.py", line 11, in <module>
    from dgl.dataloading import GraphDataLoader
**ImportError: cannot import name 'GraphDataLoader' from 'dgl.dataloading' (C:\...\dgl\dgl-env\lib\site-packages\dgl\dataloading\__init__.py)**

## Expected behavior

Expected SAGPool to begin training it's classifier.

## Environment

 - DGL Version (e.g., 1.0): 0.5.3
 - Backend Library & Version (e.g., PyTorch 0.4.1, MXNet/Gluon 1.3): PyTorch version 1.7.1+cu101
 - OS (e.g., Linux): Windows 10 Enterprise
 - How you installed DGL (`conda`, `pip`, source): pip
 - Build command you used (if compiling from source): N/A
 - Python version: 3.83
 - CUDA/cuDNN version (if applicable): 10.1
 - GPU models and configuration (e.g. V100): NVIDIA Quadro RTX 5000
 - Any other relevant information: N/A

## Additional context

N/A

**Comment by yzh119** [comment]
Hi @dylansnow , I think `GraphDataLoader` is a new API that you could use with DGL's nightly built version.

Please try reinstalling DGL by `pip install --pre dgl-cu101`.

**Comment by jermainewang** [comment]
@hetong007

**Comment by hetong007** [comment]
@dylansnow If you don't want to update DGL, you might also try an ealier version of this example at: https://github.com/dmlc/dgl/tree/72ef642f29b1615613f595fb5a9e075feda0b499/examples/pytorch/sagpool

**Comment by dylansnow** [comment]
Hi @yzh119, I tried the exact same steps as above in my original post, except including the '--pre' flag to get the latest dgl version. It still throws the same error.

Hi @hetong007, I downloaded the complete project for that SHA from github, and tried the SAGPool training again. I got a new error: 
```
python main.py --dataset 'DD'
Using backend: pytorch
Trial 1/1
Downloading ./dataset\DD.zip from https://www.chrsmrrs.com/graphkerneldatasets/DD.zip...
Extracting file to ./dataset\DD
No Node Attribute Data
Traceback (most recent call last):
  File "main.py", line 179, in <module>
    acc, train_time = main(args)
  File "main.py", line 152, in main
    train_loss = train(model, optimizer, train_loader, device)
  File "main.py", line 81, in train
    for batch in trainloader:
  File "C:\Users\Dylan.Snow\Work\dgl-72ef642f29b1615613f595fb5a9e075feda0b499\dgl-env\lib\site-packages\torch\utils\data\dataloader.py", line 352, in __iter__
    return self._get_iterator()
  File "C:\Users\Dylan.Snow\Work\dgl-72ef642f29b1615613f595fb5a9e075feda0b499\dgl-env\lib\site-packages\torch\utils\data\dataloader.py", line 294, in _get_iterator
    return _MultiProcessingDataLoaderIter(self)
  File "C:\Users\Dylan.Snow\Work\dgl-72ef642f29b1615613f595fb5a9e075feda0b499\dgl-env\lib\site-packages\torch\utils\data\dataloader.py", line 801, in __init__
    w.start()
  File "C:\Users\Dylan.Snow\Miniconda3\lib\multiprocessing\process.py", line 121, in start
    self._popen = self._Popen(self)
  File "C:\Users\Dylan.Snow\Miniconda3\lib\multiprocessing\context.py", line 224, in _Popen
    return _default_context.get_context().Process._Popen(process_obj)
  File "C:\Users\Dylan.Snow\Miniconda3\lib\multiprocessing\context.py", line 326, in _Popen
    return Popen(process_obj)
  File "C:\Users\Dylan.Snow\Miniconda3\lib\multiprocessing\popen_spawn_win32.py", line 93, in __init__
    reduction.dump(process_obj, to_child)
  File "C:\Users\Dylan.Snow\Miniconda3\lib\multiprocessing\reduction.py", line 60, in dump
    ForkingPickler(file, protocol).dump(obj)
TypeError: cannot pickle '_hashlib.HASH' object
Using backend: pytorch
(dgl-env) PS C:\Users\Dylan.Snow\Work\dgl-72ef642f29b1615613f595fb5a9e075feda0b499\examples\pytorch\sagpool> Traceback (most recent call last):
  File "<string>", line 1, in <module>
  File "C:\Users\Dylan.Snow\Miniconda3\lib\multiprocessing\spawn.py", line 116, in spawn_main
    exitcode = _main(fd, parent_sentinel)
  File "C:\Users\Dylan.Snow\Miniconda3\lib\multiprocessing\spawn.py", line 126, in _main
    self = reduction.pickle.load(from_parent)
EOFError: Ran out of input
```

Any ideas how to fix this? Both regular and administrator PowerShell prompts give the same error, so I'm reasonably certain it's not a file permissions issue.

**Comment by hetong007** [comment]
@dylansnow Please try to upgrade your dgl version via `pip install --pre --upgrade dgl-cu101`, and try again on the example from the master branch. It works on my side.

You can check DGL's version via `print(dgl.__version__)` in python, to ensure that the upgrade is successful.

**Comment by yzh119** [comment]
@dylansnow the `--pre` flag is important...

**Comment by BarclayII** [comment]
@jermainewang This issue is reported on Windows.  I assume @hetong007 is running on Linux.  Please triage Windows-related issue to me or other people who use Windows next time.

> I downloaded the complete project for that SHA from github, and tried the SAGPool training again. I got a new error:

Issue confirmed on Windows with this particular commit.  The reason is that Windows Python somehow cannot pickle the `DGLDataset._hash_func` object, while Linux Python can.  I assume that the same issue will occur even with master build.  Not sure what is the proper way to fix this.

To work around you need to set `num_workers` to 0.
