### ISSUE TITLE
Allow setting values for feature that doesn't exist yet at indices

### ISSUE THREAD

**Issue by noncomputable** [dmlc/dgl#2531]
## 🚀 Feature

It's possible to set and create a new feature with `g.ndata["new_key"] = torch.tensor([...])`. But often an algorithm calls for setting the feature just at one index or subset of indices at once, e.g. `g.ndata["new_key"][i] = torch.tensor([...])`, so it would be convenient for DGL to set the given values at those indices and properly initialize values for all other indices.

## Alternatives

Checking if the feature exists, and if it doesn't, creating it, and then finally setting it with the desired values at the specific indices.

**Comment by noncomputable** [comment]
On the difficulty of creating features with no feature data: https://github.com/dmlc/dgl/issues/2535

**Comment by jermainewang** [comment]
Thanks for the suggestion. To properly initialize it, DGL needs (1) device context, (2) data type and (3) feature shape, all of which needs to be inferred from the right hand side value. However, `g.ndata['key']` returns a `torch.Tensor` object, leaving no chance for such inference. I think the burden of creating an initial feature tensor and set it to `DGLGraph` is quite small and I will prefer stay simple for this case.
