### ISSUE TITLE
Allow specifying the shape of a feature without adding feature data

### ISSUE THREAD

**Issue by noncomputable** [dmlc/dgl#2535]
## 🚀 Feature

It can be useful to specify features in a graph even before there are any nodes or edges. The only way to do this is, for example, `g.ndata["h"] = torch.tensor([])`. But this will force the shape=() for h. There should be a way to specify a feature and its shape before adding any rows to its frame.

## Alternatives

The workaround is to add an initial node to the graph with the desired feature, and then remove that node. Now the specified feature with that specified shape will exist despite the graph being empty.

**Comment by jermainewang** [comment]
You could use `g.ndata["h"] = torch.zeros((0, D))` to specify a feature of shape `(D,)`.

**Comment by noncomputable** [comment]
Minjie you are a grand scholar of great erudition
