### ISSUE TITLE
Performance issue of TreeLSTM in MXNet

### ISSUE THREAD

**Issue by zheng-da** [dmlc/dgl#255]
TreeLSTM in MXNet is about 2 times as slow as in Pytorch. Profiling shows that quite a few operators in MXNet are slower than Pytorch:
* split: the operation required by dgl isn't supported by MXNet. Jin Hao is working on this.
* the conversion between MXNet and NumPy requires memory copy, but Pytorch doesn't.
* sort in CPU in MXNet seems to use a single thread.
* the overhead of freeing MXNet NDArray is more expensive than Pytorch.
* index_copy in MXNet is also slower than Pytorch.
@szha

**Comment by jermainewang** [comment]
Closed due to inactive and shifted priority.
