### ISSUE TITLE
Could we add customized graph-level features in DGL?

### ISSUE THREAD

**Issue by zhangxiaochen95** [dmlc/dgl#2556]
Hello, thanks for offering DGL as a powerful tool for geometric learning. Sometimes I would like to store multiple graph-level features instead of `ndata` or `edata`. It seems the only solution at the moment is to store it as the label. However, then I have to create a dictionary to organize multiple features of varying sizes in the label (e.g., `{'x': data_1, 'y': data_2}`), which makes batching operation rather complex. I think it might be better to enable users to customize some feature `x` for the graph `g`, e.g., `g.x`. (BTW, if there are other alternatives to solve this issue, I would be much happy to see some advice from the community.)

**Comment by mufeili** [comment]
To save graphs along with graph-level features using `save_graphs`, you are right that you need to pass a dictionary of features to the `labels` argument. For batching, it's just batching tensors in addition to batching graphs.

**Comment by zhangxiaochen95** [comment]
Ok, thank you very much for the help.
