### ISSUE TITLE
Failed bind on IP addr

### ISSUE THREAD

**Issue by lzheyu** [dmlc/dgl#2560]
## 🐛 Bug

when I run the train_dist.py in this repo, I got this bug:
/opt/dgl/src/rpc/network/tcp_socket.cc:69: Failed bind on 16x.1xx.1xx.1xx:3026 ,errno=99

dgl._ffi.base.DGLError: [11:33:22] /opt/dgl/src/rpc/network/socket_communicator.cc:197: Cannot bind to 16x.1xx.1xx.1xx:3026

## Environment

 - DGL Version: dgl-cuda10.1-0.5.3
 - pytorch 1.7.1
 - Linux
 - How you installed DGL (`conda`):
 - Python version: 3.6
 - CUDA/cuDNN version (if applicable): 10.1
 - GPU models and configuration (e.g. V100): v100

**Comment by aksnzhy** [comment]
You can try to kill all the processes before re-start the job.

**Comment by VoVAllen** [comment]
```python
'''    Simple socket server using threads
'''
import socket
import sys
HOST = ''   # Symbolic name, meaning all available interfaces
PORT = 3026 # Arbitrary non-privileged port
s = socket.socket(socket.AF_INET, socket.SOCK_STREAM)
print('Socket created')
#Bind socket to local host and port
try:
    s.bind((HOST, PORT))
except socket.error as msg:
    print('Bind failed. Error Code : ' + str(msg[0]) + ' Message ' + msg[1])
    sys.exit()
print('Socket bind complete')
#Start listening on socket
s.listen(10)
print('Socket now listening')
```

Could you try the code above to see whether you can directly bind the socket to your port?

**Comment by lzheyu** [comment]
Thanks for your mending, I maybe find the problem.
