### ISSUE TITLE
Questions about pinsage edges

### ISSUE THREAD

**Issue by LucasSDresl** [dmlc/dgl#2566]
## ❓ Questions and Help

Want to ask if in the pinsage implementation model is capturing the value of the rating that the user did in the past ? i believe this is not being recognize, if i change ratings values for some customer in favour of a specially genre i dont see more recommendations in favour of that genre for that specific users

**Comment by BarclayII** [comment]
PinSAGE model itself does not consider rating values (explicit feedback).  It only considers implicit feedback.  So changing the rating values alone would have no impact.  I also did not consider rating values when I port it to MovieLens.

**Comment by LucasSDresl** [comment]
thanks very much for the answer! :) 
how do u think is a good way to make pinsage rely a little bit more in ratings values ?

**Comment by BarclayII** [comment]
> thanks very much for the answer! :) @BarclayII
> how do u think is a good way to make pinsage rely a little bit more in ratings values ?

A caveat is that you will need to consider which ratings are "good" and which ratings are "bad", and how you would like to bias the probability towards the "good" ones and away from the "bad" ones.

A quick and dirty fix is to either remove the edges with low ratings and keep the edges with high ratings, or duplicate the edges with high ratings to allow more probable traversal by random walks.  Another possibility is to change the uniform random walks in PinSage to non-uniform random walks that biases towards high ratings.

Closing this thread.  Please feel free to reopen this issue or move to https://discuss.dgl.ai for general discussions if you wish to follow up.  Thanks!
