### ISSUE TITLE
dgl.data.QM9Dataset lacks edge attribute

### ISSUE THREAD

**Issue by hengruizhang98** [dmlc/dgl#2567]
## 🚀 Feature
Each edge in QM9Dataset should have a one-hot feature vector (4-dimensional) indicting its bond type. The QM9Dataset of Pytorch Geometric has this feature while dgl does not.

## Motivation
InfoGraph(ICLR 2020) model needs to use NNConv to calculate node embeddings of Molecular Graphs.

## Additional context

The QM9 dataset from the `"MoleculeNet: A Benchmark for Molecular
Machine Learning" <https://arxiv.org/abs/1703.00564>`_ paper, consisting of about 130,000 molecules with 19 regression targets.

**Comment by xnuohz** [comment]
Yes, this makes sense. But bond type should be transformed from SMILES while `Directional Message Passing for Molecular Graphs` only provides the 3D coordinates of the atom. So, should we change the current data file to the original data sources and make `dgl.dataset` supporting `preprocess`? @mufeili

**Comment by Jack-XHP** [comment]
The original QM9 data file includes the connectivity and bond type in XYZ format. I think that is better than using a cut-off distance to compute the connectivity.  Also, QM9 also includes more node features apart from atomic number and position, ie hybridization, aromatic flag. I write a new dataset following the approach from PyTorch geometric's qm9 dataset. https://github.com/Jack-XHP/DGL_QM9EDGE/blob/main/QM9Edge.py

**Comment by hengruizhang98** [comment]
> The original QM9 data file includes the connectivity and bond type in XYZ format. I think that is better than using a cut-off distance to compute the connectivity. Also, QM9 also includes more node features apart from atomic number and position, ie hybridization, aromatic flag. I write a new dataset following the approach from PyTorch geometric's qm9 dataset. https://github.com/Jack-XHP/DGL_QM9EDGE/blob/main/QM9Edge.py

Yes, your QM9EdgeDataset looks very good. We are now trying to add a new QM9Dataset with edges, your implementation will be a great help!

**Comment by xnuohz** [comment]
Should we add some parameters in QM9Dataset to choose edge or node features that will be used in model?

**Comment by hengruizhang98** [comment]
> Should we add some parameters in QM9Dataset to choose edge or node features that will be used in model?

We can provide all the features but should tell readers what each feature stands for and let the readers themselves decide which feature to use or not.

**Comment by hengruizhang98** [comment]
We support QM9EdgeDataset now! #2704 
[QM9EdgeDataset](https://docs.dgl.ai/en/latest/_modules/dgl/data/qm9_edge.html#QM9EdgeDataset)
