### ISSUE TITLE
Dictionary for HeteroNodeDataView

### ISSUE THREAD

**Issue by sophiakrix** [dmlc/dgl#2573]
## 🚀 Feature
Enable dictionary as possible instance of the HeteroNodeDataView

## Motivation

 I have a heterograph with different node types, and again for each of those node types I have multiple feature types. This is why it would be great to have a dictionary mapping the different feature types to the corresponding tensors for each node type.  
Currently, [this line here in the code](https://github.com/dmlc/dgl/blob/master/python/dgl/view.py#L78) prohibits the use of a dictionary, which would be useful in my case, and probably many more, too.

## Pitch

 Could you please add the functionality of a dictionary as a value for the HeteroNodeDataView?

**Comment by jermainewang** [comment]
Hi @sophiakrix , thanks for the suggestion. Could you elaborate more on how the user experience will look like? Do you wish to set multiple feature data in one call? Current we allow this:
```python
G = ...  # some heterograph
G.nodes['user'].data.update({'feat1' : ..., 'feat2' : ..., 'feat3': ...})
```
