### ISSUE TITLE
Why the distributed-dgl can not run when setting different trainers and gpus in different machines 

### ISSUE THREAD

**Issue by lzheyu** [dmlc/dgl#2577]
## To Reproduce
1.modify the tools/launch.py to launce different trainers and gpus in different machines.
2.run the code

## Expected behavior
1.Expexted: dist-dgl runs on different machines with different gpus and trainers.
2.But: can not run.

## Environment
DGL Version: dgl-cuda10.1-0.5.3
pytorch 1.7.1
Linux
How you installed DGL (conda):
Python version: 3.6
CUDA/cuDNN version (if applicable): 10.1
GPU models and configuration (e.g. V100): v100

**Comment by jermainewang** [comment]
@zheng-da  @aksnzhy Could you guys take a look?

**Comment by classicsong** [comment]
Can you provide more details about how you modify the launch.py and set up the training clusters?

**Comment by zheng-da** [comment]
I think this is a problem of Pytorch, instead of DGL.
