### ISSUE TITLE
ModuleNotFoundError: No module named 'dgl.dataloading.pytorch.GraphDataLoader' for dgl-cuda10.2 0.5.3

### ISSUE THREAD

**Issue by yrf1** [dmlc/dgl#2589]
Hi, I am using dgl-cuda10.2 0.5.3 and dgllife 0.2.6.
But when I try to call the dgl.dataloading.pytorch.GraphDataLoader() function, the pytorch.GraphDataLoader library name cannot be found.

Any fixes?

**Comment by yrf1** [comment]
a

**Comment by yzh119** [comment]
Hi, `GraphDataLoader` is a incoming feature of dgl 0.6, you can try nightly build version by `pip install --pre dgl-cuda102`.
