### ISSUE TITLE
[Doc] Emphasizing the behavior of graph operations on subgraphs

### ISSUE THREAD

**Issue by sneakerkg** [dmlc/dgl#2606]
## 📚 Documentation

After we apply transformation on the subgraphs, some information about the whole graph (dgl.NID and dgl.EID) will be dropped, as described in the [forum question](https://discuss.dgl.ai/t/removing-edges-cause-previous-nid-overwritten/1716).  As answered in the forum, remove_edges and remove_nodes by default no longer generate dgl.NID and dgl.EID. We might need to emphasize this behavior somewhere in the doc, otherwise users may still try to access those field. For example, in the user guide graph [section](https://docs.dgl.ai/guide/graph.html), or when users access 'dgl.NID', we add additional error message.

**Comment by mufeili** [comment]
Addressed after a discussion with @sneakerkg
