### ISSUE TITLE
DGLBlock contains two node types instead of one

### ISSUE THREAD

**Issue by theisjendal** [dmlc/dgl#2613]
## 🐛 Bug

When I'm using EdgeDataLoader with a homogenous graph, the blocks contain two node types, making it difficult to perform subsequent calculations (compared to a simple homogenous).

Thanks in advance.

## To Reproduce

1. Create graph of one node type and one edge type: `[('_U', '_V', '_U')]`.
2. Create EdgeDataLoader, with MultiLayerFull and Uniform negative sampling.
3. Iterate over dataloader, getting blocks.
4. A block now contains two nodetypes, s.t. `ntype=['_U', '_U']` and `canonical_etypes=[('_U', '_V', '_U')]`.

## Expected behavior

As my initial graph have one node type, I would expect each of my blocks to be of one node type, s.t. `ntype=['_U']` as in my original graph, and in the positive and negative graph. 

## Environment

 - DGL Version (e.g., 1.0): 0.5.3
 - Backend Library & Version (e.g., PyTorch 0.4.1, MXNet/Gluon 1.3): PyTorch 1.4.0
 - OS (e.g., Linux): Manjaro KDE, Ubuntu 18.04LTS
 - How you installed DGL (`conda`, `pip`, source): pip
 - Build command you used (if compiling from source):
 - Python version: 3.8.5
 - CUDA/cuDNN version (if applicable):
 - GPU models and configuration (e.g. V100):
 - Any other relevant information:

**Comment by jermainewang** [comment]
Hi @theisjendal , this is intended because the source side and the destination side usually have different number of nodes. It is essentially a bipartite graph. It is just that they happen to have the same type name, which we are thinking about how to tinker it to be more friendly. Can I know what kind of *subsequent calculations* you'd like to perform?

**Comment by theisjendal** [comment]
> Hi @theisjendal , this is intended because the source side and the destination side usually have different number of nodes. It is essentially a bipartite graph. It is just that they happen to have the same type name, which we are thinking about how to tinker it to be more friendly. Can I know what kind of _subsequent calculations_ you'd like to perform?

I made it work, by treating as a biparte, it was just not what I expected. 

An unrelated question, but for EdgeDataLoader, should you always provide `reverse_eids = torch.cat([torch.arange(n_edges // 2, n_edges), torch.arange(0, n_edges // 2)])` to the field `reverse_edge_ids`?

**Comment by jermainewang** [comment]
> An unrelated question, but for EdgeDataLoader, should you always provide reverse_eids = torch.cat([torch.arange(n_edges // 2, n_edges), torch.arange(0, n_edges // 2)]) to the field reverse_edge_ids?

Not necessarily. It depends on how your graphs are constructed and how the reverse edges are stored in the graph.

**Comment by theisjendal** [comment]
Thanks :-)
