### ISSUE TITLE
dgl.to_heterogeneous

### ISSUE THREAD

**Issue by Theheavens** [dmlc/dgl#2619]
## To Reproduce

The code example is that

import dgl
import torch as th

g = dgl.heterograph({('author', 'a-p', 'paper'): (th.tensor([9]), th.tensor([9]))})
g.ndata['h'] = {'paper': th.randn(10, 5),
                'author': th.randn(10, 5)}
g_homo = dgl.to_homogeneous(g, ndata=['h'])
hg_2 = dgl.to_heterogeneous(g_homo, g.ntypes, g.etypes)

## Expected behavior

I wish hg_2.ndata['h'] can be same with g.ndata['h'] 
But hg_2.ndata['_ID'] is tensor([0, 8, 7, 6, 5, 9, 3, 2, 1, 4])} which means it has different index order with g_homo.
So hg_2.ndata['h'] can not be same with g.ndata['h'] .

**Comment by fmellomascarenhas** [comment]
I made the same comment while back, but didn't have the chance to try and implement it: #2445
