### ISSUE TITLE
Customized inputs to user-defined message functions

### ISSUE THREAD

**Issue by zhangxiaochen95** [dmlc/dgl#2621]
I am trying to let different types of nodes in a heterograph call a different `nn.Module` stored in a `dict` to construct the corresponding message. Therefore, I want to add a string as the second argument to the message function such as to indicate which `nn.Module` is used.

According to the docs, users are allowed to define their own message functions by defining a function (e.g., `msg_fn`) with `EdgeBatch` as input. When using it in `update_all`, there is no need to explicitly state the argument. The code should be like `g.update_all(msg_fn, reduce_fn)` and I suppose the edges of graph `g` would be called automatically. 

Then I would like to ask can I add other inputs (e.g., `x`) to message functions (here, `x` may be a string telling node type)? The input to `msg_fn` would be `(edges, x)`. Is this supported? If so, how to specify the input `msg(???, x)`? I do not know how to explicitly specify the edge batch. If not, is there any other alternatives to achieve my goal?

**Comment by BarclayII** [comment]
Could you try partial functions?  Basically it creates a function from another function having some arguments assigned.
```python
from functools import partial
def f(a, b):
    return a + b
g = partial(f, b=5)
print(g(2))   # 7
```

**Comment by jermainewang** [comment]
@zhangxiaochen95 Please also checkout `HeteroGraphConv`. It invokes different nn module for different relations.
