### ISSUE TITLE
NameError when early stopping in Citeseer on Grand model

### ISSUE THREAD

**Issue by sneakerkg** [dmlc/dgl#2626]
## 🐛 Bug

When run the experiment on citeseer and face with early stopping, an error will be raise: NameError: name 'best_epoch' is not defined.

**Comment by sneakerkg** [comment]
@hengruizhang98

**Comment by hengruizhang98** [comment]
Hi, I've already fixed it, can you please try the latest version?

**Comment by hengruizhang98** [comment]
It is solved in #2616 .

**Comment by sneakerkg** [comment]
Great. Cool. Thanks for the information.
