### ISSUE TITLE
Performance difference of customized GCN vs built-in GCN

### ISSUE THREAD

**Issue by YukeWang96** [dmlc/dgl#2637]
Hi, All

For Pytorch example implementation, `gcn.py` and `gcn_mp.py`, why the latter have much lower performance compared with the former when running on GPU?  is it because the `update_all` function is not efficient?

For example, on an RTX 3090 GPU with CUDA 11.0, GCNconv from the `gcn.py` achieves 7.698 ms per epoch while `gcn_mp` achieves  81.143  ms per epoch (both are averaged over 100 epoch).

Thanks!

**Comment by yzh119** [comment]
Hi @YukeWang96 , Both of them uses `update_all`. The `gcn_mp` uses UDF(user defined functions) while `gcn` uses builtin functions (which is the recommended way to do message passing).

Please read this section for more details: https://docs.dgl.ai/guide/message.html.

**Comment by YukeWang96** [comment]
> Hi @YukeWang96 , Both of them uses `update_all`. The `gcn_mp` uses UDF(user defined functions) while `gcn` uses builtin functions (which is the recommended way to do message passing).
> 
> Please read this section for more details: https://docs.dgl.ai/guide/message.html.

So if a customized graph convolutional layer is needed then we can only leverage the UDF for programming and the performance is not guaranteed, right?

**Comment by yzh119** [comment]
yes and we are working on compiling udfs and general code generation for customized message passing functions. Please stay tuned.
