### ISSUE TITLE
[Feature Request] Non-blocking GPU memory management by default

### ISSUE THREAD

**Issue by nv-dlasalle** [dmlc/dgl#2652]
## 🚀 Feature

Provide non-blocking GPU memory management by default in DGL, that is easy for new users to utilize.

## Motivation

Currently, by default, DGL directly calls `cudaMalloc()` and `cudaFree()` when creating tensors on the GPU. `cudaMalloc()` is an expensive call, but more problematic is `cudaFree()` blocks until all GPU work is finished, which can have a significant impact on performance.

While #2158 solves this issue for PyTorch, it requires building from source, making its use not common. It also does not solve the issue for TensorFlow or MXNET.

It would be great to have a solution, where if a user installs DGL via `pip` or `conda`, they would have the performance benefit of non-blocking memory management.

## Alternatives

Alternative solutions would be create TensorAdapter's for TensorFlow and MXNET, but I'm not sure how enabling these by default in PyPI would work, or any other non-binary would work.

## Pitch

Cuda 11.2 adds `cudaMallocAsync` and `cudaFreeAsync` which make use of per-stream memory pool https://docs.nvidia.com/cuda/cuda-runtime-api/group__CUDART__HIGHLEVEL.html#group__CUDART__HIGHLEVEL_1ga31efcffc48981621feddd98d71a0feb.

#2651 implements this strategy, but it fails to address two issues raised by @yzh119 are that:
1) the cuda memory pool would compete with the backend memory pool for resources,
2) and that using the backend to query in use GPU memory would not account for that in the cuda memory pool.

Unless PyTorch enables a way to also use `cudaMallocAsync` internally (https://github.com/pytorch/pytorch/issues/51075), I don't know of a solution to 1.

For 2, cuda 11.2 does not provide a way to query the size of pool, so memory usage in DGL would have to be tracked manually. Total GPU memory usage can be accessed via `cudaGetMemInfo()` (https://docs.nvidia.com/cuda/cuda-runtime-api/group__CUDART__MEMORY.html#group__CUDART__MEMORY_1g376b97f5ab20321ca46f7cfa9511b978), however this reports usage for the device, and not just the current process.

**Comment by jermainewang** [comment]
> While #2158 solves this issue for PyTorch, it requires building from source, making its use not common.

@BarclayII Does it require building from source to use TorchAllocator?

**Comment by BarclayII** [comment]
> > While #2158 solves this issue for PyTorch, it requires building from source, making its use not common.
> 
> @BarclayII Does it require building from source to use TorchAllocator?

DGL binary by default already uses TorchAllocator.

Tensorflow and MXNet will still need their own TensorAdapter though, and I prefer this solution because that would save us from (1) maintaining our own memory allocator and (2) potential OOMs when PyTorch/MXNet/Tensorflow weren't able to tell how much GPU memory is left, which occurs occasionally prior to the incorporation of TensorAdapter.

**Comment by nv-dlasalle** [comment]
@BarclayII Thanks. I didn't think this was already case. I'll close this then.
