### ISSUE TITLE
Further descriptions for `dgl.data.GINDataset`

### ISSUE THREAD

**Issue by Junyoungpark** [dmlc/dgl#2655]
Hi, I'm wondering how the node `attr` and `label` are constructed from `dgl.data.GINDataset`.

- it might be better to have a description what is `attr` and `label` and how they are formulated when building `dgl.graph`.

---------

when I check the source code of `dgl.data.GINDataset` (https://docs.dgl.ai/_modules/dgl/data/gindt.html#GINDataset), it seems like the node label is a kind of one-hot encoded node types (?). If so, it will be totally okay to use `label` also as an input for GNNs predicting the graph labels in terms of data leakage problems. 

So hereby what I want to know is
- When someone build a GNN that is for predicting the graph labels of `dgl.data.GINDataset`,  what is the appropriate node inputs (features) from `attr` and `label` of graphs?

Since the `label` is named as `label`, I'm a little bit worried to use `label` as an input of GNNs. But on the other hand, I'm also feel okay to use the node `label` as an input of GNN,  since the `label` often indicates the node features in graph theory.

**Comment by hetong007** [comment]
Thanks for raising the issue! I've added explanation in the PR. 

If your purpose is to use `GINDataset` for graph classification, then it is valid to consider node-level attributes as input features for your model. For instance, the `PROTEINS` data has nodes representing secondary structure elements, and the node-level may possibly contain useful chemical information.

We have an example implementation using `GINDataset`, and here's how we use the `attr` field: https://github.com/dmlc/dgl/blob/master/examples/pytorch/gin/main.py#L27

**Comment by Junyoungpark** [comment]
Thanks for the comments :)
