### ISSUE TITLE
The code given in tutorial does not work , seems there is a gap between current release code and the code given in tutorials

### ISSUE THREAD

**Issue by 123nishant** [dmlc/dgl#2656]
## 📚 Documentation

Please check the doc and update the tutorials. 

![image](https://user-images.githubusercontent.com/8594023/107847996-4e7bbc80-6e16-11eb-99a2-ceec0237a2b2.png)

**Comment by 123nishant** [comment]
Similar issue on tutorial 

https://docs.dgl.ai/en/latest/generated/dgl.heterograph.html

![image](https://user-images.githubusercontent.com/8594023/107848077-bcc07f00-6e16-11eb-8846-48e88b122475.png)

**Comment by 123nishant** [comment]
https://docs.dgl.ai/en/latest/generated/dgl.from_scipy.html

![image](https://user-images.githubusercontent.com/8594023/107848110-f0030e00-6e16-11eb-90bc-e90fbe5885fb.png)

**Comment by yzh119** [comment]
It's a problem of your environment instead of our tutorial. `dgl.function`, `dgl.graph` and `dgl.heterograph` should be available.

**Comment by yzh119** [comment]
Could you please check the if your dgl is correctly installed?
Pring `dgl.__path__` in your jupyter notebook.

**Comment by jermainewang** [comment]
It is very likely a path problem. @123nishant Have you double checked the installation path of your DGL as Zihao suggested?

**Comment by jermainewang** [comment]
Close due to lack of activity.
