### ISSUE TITLE
Can DGL support AMD GPU with ROCM ?

### ISSUE THREAD

**Issue by znsoftm** [dmlc/dgl#2659]
## 🚀 Feature
I'm using an AMD GPU to train models, so can DGL support AMD GPU with ROCM ?

**Comment by yzh119** [comment]
Currently the answer is no, but I do think it possible after we fully integrate [featgraph](https://arxiv.org/abs/2008.11359).

**Comment by znsoftm** [comment]
Thanks for your answer.

**Comment by paulamartingonzalez** [comment]
Hi! I am also using AMD GPUs to train my models. I was wondering if there's any update regarding ROCm support. Thanks!
