### ISSUE TITLE
Question about the number of seed vectors in set transformer decoder

### ISSUE THREAD

**Issue by lsyysl9711** [dmlc/dgl#2660]
len_pma = graph.batch_num_nodes()
        len_sab = [self.k] * graph.batch_size
        feat = self.pma(feat, len_pma)
        for layer in self.layers:
            feat = layer(feat, len_sab)
        return feat.view(graph.batch_size, self.k * self.d_model)

The above codes come from the forward function of set transformer decoder. It is almost the same comparing to the encoder but here comes one new thing "number of seed vectors k". If we set k = 1, then we can use multi-head attention to calculate alpha. The output shape of alpha would be [batch size, max_len, 1, 1]. Note that the sum of softmax function will be 1. So the value of this 1*1 tensor will always be 1, which means the softmax function is a constant function. We know that the gradient of any constant function will be zero, so the W_q and W_k will remain unchanged. And this would limt the ability of set transformer greatly. I am not sure if it is a bug since we can change k to other numbers. But I think DGL team can add some related alerts to the doc.

**Comment by lsyysl9711** [comment]
If you do not get my points or lost in details, please feel free to leave a message.

**Comment by yzh119** [comment]
@lsyysl9711 thanks for your feedback, how about we raise a warning when `k` is set to 1?

**Comment by lsyysl9711** [comment]
Yep, I think that is necessary. Thanks for replying.
