### ISSUE TITLE
Using other datasets for TreeLSTM

### ISSUE THREAD

**Issue by trinayan** [dmlc/dgl#2663]
Hi,

I am trying to use other datasets such as the SICK dataset which is also used in sentiment analysis. For the current SST dataset, I observed that the data downloaded from your servers is already preprocessed in the files like train.txt, test.txt and vocab.txt. I am wondering how can we generate data in such a format for other sentiment analysis datasets so that it can be used with the current TreeLSTM code as well. Any tips will be really helpful.

Thanks.

**Comment by jermainewang** [comment]
Hi @trinayan , our hosted SST dataset is no different than the original dataset available here: https://nlp.stanford.edu/sentiment/index.html. The trees are stored in PTB format and can be loaded by `nltk`. To generate them, you may need tools like [Stanford Parser](https://nlp.stanford.edu/software/lex-parser.shtml). I think once you've prepared the dataset in the same format, you could directly use DGL's code to load them.
