### ISSUE TITLE
Concatenation in SageConv

### ISSUE THREAD

**Issue by pmorerio** [dmlc/dgl#2664]
https://github.com/dmlc/dgl/blob/0cbaa1fbcbeede48b2b1f828a0bb5c2ec4adc43c/python/dgl/nn/pytorch/conv/sageconv.py#L23

I would expect concatenation after aggregation, but could not see it anywhere in the code.
Am I missing something?
Thanks.
P.

**Comment by BarclayII** [comment]
Concatenation of two input vectors followed by a linear layer is identical to adding up two linear layer outputs for each input:
```
W[x1; x2] = W1 x1 + W2 x2
```
The code is in https://github.com/dmlc/dgl/blob/0cbaa1fbcbeede48b2b1f828a0bb5c2ec4adc43c/python/dgl/nn/pytorch/conv/sageconv.py#L234

**Comment by pmorerio** [comment]
Right, thank you.
