### ISSUE TITLE
How to deploy a cluster? I didn't find out the guideline.

### ISSUE THREAD

**Issue by leeivan** [dmlc/dgl#2666]
## ❓ Questions and Help

Before proceeding, please note that we recommend
using our discussion forum (https://discuss.dgl.ai) for
general questions. As a result, this issue will
likely be CLOSED shortly.

**Comment by jermainewang** [comment]
Please provide more contexts on the question. I will close it for now. For general question, as suggested in the issue template, please move the discussion to our forum. Thanks!
