### ISSUE TITLE
EdgeConv message passing

### ISSUE THREAD

**Issue by pmorerio** [dmlc/dgl#2668]
https://github.com/dmlc/dgl/blob/ff64bd0de83f865a8076cf50f69525549c32ca87/python/dgl/nn/pytorch/conv/edgeconv.py#L112

According to the equation, the node h_i itself should be the input of `phi`. Shouldn't this be `edges.dst['x']` instead of `edges.src['x']` ?(I am assuming the message travels from src to dst, and thus dst is the node i which receives messages from neighbours)

**Comment by BarclayII** [comment]
Good catch!  Would you like to submit a PR?
