### ISSUE TITLE
Clarify link prediction docs

### ISSUE THREAD

**Issue by nguyenhungquang** [dmlc/dgl#2670]
## 📚 Documentation

 Tutorial part

On your new tutorial about [link prediction](https://docs.dgl.ai/en/latest/new-tutorial/4_link_predict.html), you stated that it followed [SEAL model](https://papers.nips.cc/paper/2018/file/53f0d7c537d99b3824f0f99d62ea2428-Paper.pdf), but what was represented there is just simply applying score function after message passing, which is quite different from SEAL. More particular, SEAL model does not use node feature but node labeling instead, which allows it to apply to inductive setting. Node labeling also requires constructing a local subgraph for each pair of nodes beforehand, then message passing on these graphs, which is really computationally inefficient, and quite difficult to implement.

**Comment by jermainewang** [comment]
Hi, I think the tutorial follows the practice of SEAL on formulating a link prediction problem as a binary classification problem and the way SEAL prepares positive/negative samples. Yes, I agree we should be more precise on the statement.
