### ISSUE TITLE
Cora Dataset - one-hot encoding of the labels

### ISSUE THREAD

**Issue by Kristof-Neys** [dmlc/dgl#2677]
Hi, 
I need to get the one-hot encoding of the labels. From the Thomas Kipf code  (https://github.com/tkipf/pygcn/blob/1600b5b748b3976413d1e307540ccc62605b4d6d/pygcn/utils.py) I can retrieve which are the vectors for which labels. Unfortunately, I can't for the DGL code. All I see are the y & ty vectors but I do not know which labels they match up to. I assume they are the same. Can you confirm or can you help me out getting the labels for the one-hot vectors? Thanks!

**Comment by jermainewang** [comment]
I can confirm that we used the same processed data as Kipf's code.
