### ISSUE TITLE
construct_negative_graph in link prediction

### ISSUE THREAD

**Issue by chrischen1** [dmlc/dgl#2712]
## 📚 Documentation

User Guide 5.3 Link Prediction

```
def construct_negative_graph(graph, k):
    src, dst = graph.edges()

    neg_src = src.repeat_interleave(k)
    neg_dst = torch.randint(0, graph.num_nodes(), (len(src) * k,))
    return dgl.graph((neg_src, neg_dst), num_nodes=graph.num_nodes())
```

This could possibly sample positive edges as well? I believe the one mentioned in the 60-min blitz works better for this:
```
adj = sp.coo_matrix((np.ones(len(u)), (u.numpy(), v.numpy())))
adj_neg = 1 - adj.todense() - np.eye(g.number_of_nodes())
neg_u, neg_v = np.where(adj_neg != 0)
```

**Comment by jermainewang** [comment]
You are right that the one in the blitz introduction also constructs a negative graph. However, it only works for small graph because `adj.todense()` creates a dense adjacency matrix. The code in the user guide shows a more efficient solution which corrupts the destination nodes of the edges.

**Comment by jermainewang** [comment]
You may wonder that the code in the user guide could accidentally pick positive edges as negative ones. This is true but the chance is quite small because graphs with a fair size tend to be very sparse.

**Comment by chrischen1** [comment]
Thanks for the explaination!
