### ISSUE TITLE
[Example VGAE] error on direct conversion from cuda tensor to numpy

### ISSUE THREAD

**Issue by ziqiaomeng** [dmlc/dgl#2720]
## 🐛 Bug

"edges_all = edges_all.t().numpy()" in preprocess.py will cause error since edges_all is a cuda tensor which is not supported by numpy. 

## To Reproduce

Directly run command "python train.py --datasrc dgl --dataset cora" will trigger this error. 

## Expected behavior

I think this line "edges_all = edges_all.t().numpy()" should be "edges_all = edges_all.cpu().t().numpy()", but the program will have new errors on this problem after fixing this line. I fixed all these problems and finally could run it right now. 

## Environment

 Is current numpy supporting direct conversion from cuda tensor to numpy format?

**Comment by sneakerkg** [comment]
@JuliaSun623 Please take a look at this issue.

**Comment by yzh119** [comment]
@ziqiaomeng Currently no, you must copy data from device to host and then convert torch tensor to NumPy format (this step is zero-copy).
