### ISSUE TITLE
How can I use DGL module as a function?

### ISSUE THREAD

**Issue by myhrbeu** [dmlc/dgl#2732]
Now I have a network that uses CNN、LSTM modules, and I want to add a GAT module to fuse multi-channel information,  but when I use the code to insert DGL GAT I found it‘s hard to use data in batch。  And I have an idea to use GAT implements by Keras or Pytorch, but I think if DGL has a  solution is much better。Thanks！

**Comment by jermainewang** [comment]
I don't fully understand your question. Are you asking how to use DGL NN module? It is the same as how you use PyTorch NN module.
```python
from dgl.nn import GraphConv

g = ...   # some graph
x = ...  # some node feature tensor
conv = GraphConv(...)  # create a graph convolution module
y = conv(g, x)   # apply graph convolution on graph and node feature
```
