### ISSUE TITLE
Convert block(MFG) to graph

### ISSUE THREAD

**Issue by bdy9527** [dmlc/dgl#2735]
In a block, the src_node contains both source nodes and target nodes.

When I use "block_to_graph" to convert the block to a graph, the src_node are copied. So, the graph is not the same as the block I want.

Is there any solution?

Thanks in advance.

**Comment by BarclayII** [comment]
A block (MFG) is a bipartite graph, so `block_to_graph` will convert the said MFG into a bipartite graph:
```python
g = dgl.graph(([0,1,2],[2,3,4]))
b = dgl.to_block(g, dst_nodes=[2, 3, 4])
gg = dgl.block_to_graph(b)
# Graph(num_nodes={'_N_src': 5, '_N_dst': 3},
#       num_edges={('_N_src', '_E', '_N_dst'): 3},
#       metagraph=[('_N_src', '_N_dst', '_E')])
```

What was your expectation from this operation?  Do you want some kind of inverse operation that reverts it back to a homogeneous graph?

**Comment by bdy9527** [comment]
Thanks for the reply!

It seems that the graph _g_ contains three source nodes (0, 1, 2), while _gg_ has five source nodes (2, 3, 4, 0, 1). 

I'm not sure whether _gg_ is the same as _g_.

**Comment by BarclayII** [comment]
> It seems that the graph _g_ contains three source nodes (0, 1, 2)

A small correction: `g` contains 5 nodes (0, 1, 2, 3, 4).

> I'm not sure whether _gg_ is the same as _g_.

They are indeed different because `block_to_graph` does not revert the block (MFG) back to the original graph.  If you want to revert it back to the original graph, you will need to construct a graph by your own (which is possible because the block (MFG) keeps track of the original node IDs).

Just curious: what are you trying to accomplish with the reverted graph?  Maybe there exists a more efficient way.

**Comment by bdy9527** [comment]
Thanks for the answer and it's surprising to find that the src_nodes, target_nodes and nodes are the same in a graph.

What I want to do is to combine an edge-based loss and a node-based loss together in my model.

My solution is to sample a three-layer subgraph of the rooted nodes and aggregate the information twice based on the first two MFGs. While the third MFG, i.e., the minimum MFG, is used to play a role like the positive graph in the link prediction task. So I need to convert the third MFG into a graph and use it to generate a negative graph.

As your suggestion, I build a new graph, where the nodes and edges are from MFG (it's very convenient \^o^/).

While there is another question, does DGL plan to add some graph augmentation operators? I think this is an important component in the graph computation framework. For example, I'm trying to reproduce the augmentation operators in [Nodeaug: semi-supervised node classification with data augmentation](https://bhooi.github.io/papers/nodeaug_kdd20.pdf). The hardest part is to add edges between the center node and its 2-hop or 3-hop neighbors. Honestly, I do not find a proper way to add these edges in both full-batch and mini-batch way. Can you provide some suggestions? Thank in advances!

**Comment by mufeili** [comment]
Can you provide a list of graph augmentation operators you would like to see?

**Comment by bdy9527** [comment]
1. Feature augmentation. For example, dropout and drop_node (proposed by GRAND, which has been implemented by DGL).
2. Structure augmentation. For example, drop_edge and add_edge randomly. 
3. For an advanced version, I think DGL can consider the random walk-based drop_edge, i.e., neighbors are dropped according to the arrival probability of random walk, and hop-based add_edge, i.e., randomly connect 2-hop or 3-hop neighbors with the center nodes.

Because I'm not focus on graph augmentations, there may be some missing operators, e.g., graph-level augmentation.

Besides, from my point of view, the augmentation may happen in both full-batch and mini-batch setting. For the full-batch setting, we can preprocess the graph. But for the mini-batch setting, in order to make the augmentation more diversified, we hope the graph can be augmented in each mini-batch. Therefore, we need to augment MFGs instead of graph, which may bring some problems. For example, if we want to add edges between the target node and its 3-hop neighbors, it is easy to find all the 3-hop neighbors of a batch of target nodes. But it's hard to define the 3-hop neighbors of each target node separately. My solution is to convert MFGs to graph and uses dgl.khop_graph to find the 3-hop edges, because the MFGs are directed graphs.

Hope for the official solutions!
