### ISSUE TITLE
Deployment guide

### ISSUE THREAD

**Issue by bs1119** [dmlc/dgl#2736]
I searched both the tutorial and the forum, there seems no guide on how to deploy a dgl-based graph model. 
Can anyone share some experience or point a way on how to deploy a dgl-based model to be loaded in C++?
Thanks.

**Comment by jermainewang** [comment]
That's currently a limitation of DGL. We do notice the problem though and are planning for the feature in later releases.

**Comment by bs1119** [comment]
> That's currently a limitation of DGL. We do notice the problem though and are planning for the feature in later releases.

Thanks for the reply. Do you know if there is any existing walk-around solution?

**Comment by jermainewang** [comment]
Someone mentioned TorchServe on our discuss forum and it looks viable at a first glance because it allows flexible customization. But take my word with a grain of salt.
