### ISSUE TITLE
RGCN Example Link Prediction "--n-epochs" bug 

### ISSUE THREAD

**Issue by turoger** [dmlc/dgl#2752]
https://github.com/dmlc/dgl/blob/d3a058226cec48d48c556e4c4a19d619114bcc25/examples/pytorch/rgcn/link_predict.py#L194

To whom this may concern,

When running the `link_predict.py` with the `--n-epochs` flag, I encountered the algo exceeding my specified epochs.  On closer inspection, I realized that the break statement to exit out of the while loop is nested within the step to save the best model. 

I believe the proper fix should be:

```
if mrr< best_mrr:
    pass
else:
    best_mrr = mrr
    torch.save({...})
if epoch >= args.n_epochs:
   break
```

**Comment by classicsong** [comment]
Can you try to fix the bug?

**Comment by turoger** [comment]
I'll submit a pull request.

**Comment by classicsong** [comment]
Thanks

**Comment by turoger** [comment]
@classicsong , the PR is located [https://github.com/dmlc/dgl/pull/2757](url)

**Comment by BarclayII** [comment]
Thanks!
