### ISSUE TITLE
Does DGL accept a batch of feature matrix?

### ISSUE THREAD

**Issue by Suesoso** [dmlc/dgl#2759]
## ❓ Questions and Help

Before proceeding, please note that we recommend
using our discussion forum (https://discuss.dgl.ai) for
general questions. As a result, this issue will
likely be CLOSED shortly.

Hi I would like to use a batch of features to update the GCN's weights in DGI. Would that function be feasible in DGL? How should I implement it? Thanks.

**Comment by jermainewang** [comment]
It's not entirely clear what's the requirement here. If you mean a batch of node features, that is a classical setting. Pls checkout our blitz introduction tutorial: https://docs.dgl.ai/tutorials/blitz/index.html

**Comment by jermainewang** [comment]
I will close this issue. For general usage questions, please use our discuss forum. Thanks.
