### ISSUE TITLE
remove_nodes() does not preserve edge order 

### ISSUE THREAD

**Issue by mjwen** [dmlc/dgl#2764]
## 🐛 Bug

The documentation of [remove_nodes()](https://docs.dgl.ai/en/latest/generated/dgl.DGLGraph.remove_nodes.html#dgl.DGLGraph.remove_nodes) reads that: `After removing nodes and edges, the rest nodes and edges will be re-indexed using consecutive integers from 0, with their relative order preserved.` Although the order of nodes is preserved, the order of edges may not be. 

For example, the below snippet gives `eid = [1, 3, 0]`; if order is preserved, I'd expect `eid=[0, 1, 3]`. 

Taking a look at the implementation of `remove_nodes()`, I see `subgraph()` is called internally and there seems no action to preserve edge order. If this is the intended behavior, the documentation should be updated accordingly. But I'd love to have `remove_nodes()` preserving edge order. 

```python 
g = dgl.graph((torch.tensor([2, 0, 0, 0]), torch.tensor([4, 1, 3, 2])))
g.remove_nodes([3], store_ids=True)
eid = g.edata["_ID"]

print(eid)  #  tensor([1, 3, 0])
```

**Comment by BarclayII** [comment]
Our docstring is wrong and we would fix it.

Just a question: is preserving edge order a requirement of your model?  What is the scenario if this is the case?  If it is a requirement then we will consider changing the implementation instead.

**Comment by mjwen** [comment]
Thanks for the clarification!

 I've been playing with some difference graphs; more specifically, a graph is the difference of the subgraphs of two other graphs (say subgraphs 1 and 2). In this case, edge correspondence between subgraphs 1 and 2 needs to be known to take the difference of edge features. I'd say this is not how people typically use GNNs; I just need it. Currently I make it work by bookkeeping eids and reorder the edges features manually. This is not too much extra work, but it would be nicer if the relative order of edges are kept and then I can remove these bookkeepings.

**Comment by mufeili** [comment]
The doc should be updated now.

**Comment by Dvirbeno** [comment]
I believe there is still an inaccuracy in the docstring of `remove_edges()`.

According to the docstring, for the case of `DGLHeteroGraph`:

```python
>>> g = dgl.heterograph({
...     ('user', 'plays', 'game'): (torch.tensor([0, 1, 1, 2]),
...                                 torch.tensor([0, 0, 1, 1])),
...     ('developer', 'develops', 'game'): (torch.tensor([0, 1]),
...                                         torch.tensor([0, 1]))
...     })
>>> g.remove_edges(torch.tensor([0, 1]))
DGLError: Edge type name must be specified
if there are more than one edge types.
>>> g.remove_edges(torch.tensor([0, 1]), 'plays')
>>> g.edges('all', etype='plays')
(tensor([0, 1]), tensor([0, 0]), tensor([0, 1]))
```

while in practice the resulting tuple of the last call will be:
```python
(tensor([1, 2]), tensor([1, 1]), tensor([0, 1]))
```
