### ISSUE TITLE
Node attributes in TUDataset('ENZYMES') are all torch.int64 but some feature maps are float. 

### ISSUE THREAD

**Issue by HenryKenlay** [dmlc/dgl#2774]
## 🐛 Bug

The features for the graphs in `TUDataset('ENZYMES')` are all integer. But if you download the dataset from [TUDataset website](https://chrsmrrs.github.io/datasets/docs/datasets/) some feature maps are continuous. For example row 0 column 1 of `ENZYMES_node_attributes.txt` is `15.887014`. 

## To Reproduce

The following shows the features are all stored as ints 

```
from dgl.data import TUDataset
import torch

dataset = TUDataset('ENZYMES')

for graph, label in dataset:
    assert example_graph.ndata['node_attr'].dtype == torch.int64
```

The following gives `15` but the value should be `15.887014`. 
```
graph, _ = dataset[0]
print(graph.ndata['node_attr'][0][1])
``` 

## Expected behaviour

The tensor in `graph.ndata['node_attr']` should be float type. 

## Environment

 - DGL Version (e.g., 1.0): Same error in both `0.6.0` and `'0.6.0post1'`
 - Backend Library & Version: `PyTorch 1.8.0`
 - OS (e.g., Linux): `MacOX 10.15.5`
 - How you installed DGL (`conda`, `pip`, source): `conda install -c dglteam dgl` and `pip install --pre dgl`
 - Build command you used (if compiling from source): N/A
 - Python version: `3.8.5`
 - CUDA/cuDNN version (if applicable): N/A
 - GPU models and configuration (e.g. V100): N/A
 - Any other relevant information: I imagine this effects other datasets too.

**Comment by jermainewang** [comment]
@HuXiangkun could you take a look?
