### ISSUE TITLE
SAGEConv produces NANs on a graph with no edges on dgl v0.6.0.post1

### ISSUE THREAD

**Issue by drsealks** [dmlc/dgl#2777]
## To Reproduce

Execute this code:
```
import dgl
import networkx as nx
import numpy as np
import torch
from dgl.nn import SAGEConv
adjacency = np.array([[0, 0], [0, 0]])
g = nx.DiGraph(adjacency)
G = dgl.from_networkx(g)

embedding = torch.nn.Embedding(2, 4)
embedding.weight = torch.nn.Parameter(
    torch.from_numpy(
        np.array([[1, 2, 3, 4],
                  [5, 6, 7, 8]])).float(),
    requires_grad=False)

conv = SAGEConv(4, 16, aggregator_type="mean", activation=torch.nn.LeakyReLU())

print(conv(G, embedding.weight))

```
produces 
```
tensor([[nan, nan, nan, nan, nan, nan, nan, nan, nan, nan, nan, nan, nan, nan, nan, nan],
        [nan, nan, nan, nan, nan, nan, nan, nan, nan, nan, nan, nan, nan, nan, nan, nan]],
       grad_fn=<LeakyReluBackward0>)
```

## Expected behavior

It must not produce a tensor full of nans, should be an array full of floats.

## Environment

 - DGL Version (e.g., 1.0): v0.6.0.post1
 - Backend Library & Version (e.g., PyTorch 0.4.1, MXNet/Gluon 1.3): pytorch 1.8.0
 - OS (e.g., Linux): Linux
 - How you installed DGL (`conda`, `pip`, source): pip
 - Build command you used (if compiling from source):
 - Python version: 3.8.6
 - CUDA/cuDNN version (if applicable): n/a
 - GPU models and configuration (e.g. V100): n/a
 - Any other relevant information: cpu inference

**Comment by drsealks** [comment]
I've traced the error and it happens here:
```
    if reduce_op == 'mean':
        ret_shape = F.shape(ret)
        deg = g.in_degrees()
        deg = F.astype(F.clamp(deg, 1, g.number_of_edges()), F.dtype(ret))
        deg_shape = (ret_shape[0],) + (1,) * (len(ret_shape) - 1)
        return ret / F.reshape(deg, deg_shape)
```
in `spmm.py`
Basically, the degree is zero and we divide by zero here `F.reshape(deg, deg_shape)`. Since zeroing the neigh embedding is a hack anyway, one solution would be to do elementwise maximum between the degree and one. That would prevent division by zero in this case.

**Comment by yzh119** [comment]
@drsealks thanks for your investigation, yes we welcome your PR.

**Comment by drsealks** [comment]
Closing as the PR was merged.
