### ISSUE TITLE
Metis partitioning yields high % of halo nodes

### ISSUE THREAD

**Issue by ableiweiss** [dmlc/dgl#2779]
For example, when I try partitioning Reddit for 4 parts, I get an average of ~30% nodes in the partition. When I partition to higher numbers (>100), I get an average of %5 nodes inside the partition.

Here is the code I use

    balance_ntypes = g.ndata['train_mask']
    dgl.distributed.partition_graph(g, graph_name=graph_name, num_parts=num_workers, out_path='4part_data',
                                    balance_ntypes=balance_ntypes,
                                    balance_edges=True,
                                    part_method='metis')

I would expect % halo nodes to be much lower as this level of locality will require lots of data movement between nodes.

## Environment

 - DGL Version (e.g., 1.0): 0.5.1
 - Backend Library & Version (e.g., PyTorch 0.4.1, MXNet/Gluon 1.3): 1.6
 - OS (e.g., Linux): Ubuntu
 - How you installed DGL (`conda`, `pip`, source): pip
 - Build command you used (if compiling from source):
 - Python version:
 - CUDA/cuDNN version (if applicable):
 - GPU models and configuration (e.g. V100):
 - Any other relevant information:

**Comment by zheng-da** [comment]
you cannot partition Reddit into many partitions and expect that majority of the nodes are within partitions. Reddit is a very small graph and nodes are densely connected. There is no good way to partition this graph into many partitions with a small number of edge cut. METIS works well for partitioning large graphs into a small number of partitions.

**Comment by ableiweiss** [comment]
When I ran METIS on ogbn-products, I get a slight lower % of halo nodes (~55% for 32 partitions), but still relatively high. Is there a rule of thumb for graph size/structure and optimal number of partitions?

**Comment by zheng-da** [comment]
we don't have rules of thumb for partitioning. in practice, we don't need a cluster of 32 machines to train ogbn-products. when we use a cluster of 32 machines, most likely we are training on a graph of billions of nodes.
for a power-law graph, it's very difficult to cut it into many partitions with a small number of edge cuts. In DGL, edge cuts mean data communication. it's fine to have data communication between machines. our goal is to reduce data communication as much as possible.
