### ISSUE TITLE
When will cuda 11.2 be supported?

### ISSUE THREAD

**Issue by zhanglu-cst** [dmlc/dgl#2790]
## 🚀 Feature

NVIDIA 3090 need pytorch 1.8 and cuda 11.2，I tried to compile myself, but ran with an error of CUDA order. 
When will cuda 11.2 be supported?

**Comment by VoVAllen** [comment]
CUDA 11.2 has been reported with some serious bugs. Therefore you can see PyTorch didn't release with 11.2 also. I don't think we will release 11.2 binary until PyTorch did so. Could you post your compilation error here? Thus we can help make it work on your machine.

**Comment by fmellomascarenhas** [comment]
Hi, just wanted to share that after 2 days debugging my code using cuda 11.1, I decided to switch pytorch/dgl to cuda 10.x, and got my program to work.

I dont have the compilation error, but the code would work normally on CPU. In GPU, it would work until a certain type of operation was done. If I tried to print the tensor, the notebook would crash. Also, trying to do reduce operations (more specifically torch.cumsum, would also break the notebook. Sending to CPU and doing the same operation would work.

The errors I got were:
RuntimeError: CUDA error: invalid device ordinal
CUDA error 59: Device-side assert triggered

**Comment by yzh119** [comment]
@fmellomascarenhas the bug you mentioned should have been fixed in #2308 . What version of DGL you were using?

**Comment by fmellomascarenhas** [comment]
> @fmellomascarenhas the bug you mentioned should have been fixed in #2308 . What version of DGL you were using?

No idea. I uninstalled everything and reinstalled the new version :/ But I am glad to know that it was fixed. Btw, let me just ask a quick question: To use fp16, do I really have to compile DGL from source, as [described in the website](https://docs.dgl.ai/en/latest/guide/mixed_precision.html)? Thanks!

**Comment by zhanglu-cst** [comment]
> @fmellomascarenhas the bug you mentioned should have been fixed in #2308 . What version of DGL you were using?
When I compiled and ran on cuda11.1, I encountered the same problem: CUDA error: invalid device ordinal.
My DGL is the clone from the lastest github source.

**Comment by BarclayII** [comment]
> > @fmellomascarenhas the bug you mentioned should have been fixed in #2308 . What version of DGL you were using?
> > When I compiled and ran on cuda11.1, I encountered the same problem: CUDA error: invalid device ordinal.
> > My DGL is the clone from the lastest github source.

For now, compiling with CUDA 11.1+ would require you specify the following macro definition esp. for PyTorch 1.8.0-:
```
-DCUB_CPP_DIALECT=2003
```
The reason is kinda complicated and discussed in multiple places, for instance https://github.com/NVIDIA/thrust/issues/1401 and https://github.com/pytorch/pytorch/issues/54245.

**Comment by TristonC** [comment]
NVIDIA build CUDA enabled docker container for DGL. Welcome to try the [early access](https://developer.nvidia.com/dgl-container-early-access) DGL container with 0.8.0post2.
