### ISSUE TITLE
Out of memory error with CUDA 11.0

### ISSUE THREAD

**Issue by talnish** [dmlc/dgl#2803]
## 🐛 Bug

I am trying to run the cluster GCN algorithm from ```examples/pytorch/cluster_gcn``` and getting an out of memory issue with a CUDA 11.0 version on RTX 3090.
I tried to run the same code on a 2080 Ti by downgrading my CUDA version to 10.2, and it seems to work just fine. But on the same GPU, when I upgrade the version to CUDA 11.0, I get the same error. So, I am guessing it's the CUDA version that is causing the error?

## To Reproduce

Run ```run_reddit.sh``` from ```examples/pytorch/cluster_gcn```
I also get the same error with ```run_ppi.sh```

Here's the error message:
Traceback (most recent call last):
  File "cluster_gcn.py", line 222, in <module>
    main(args)
  File "cluster_gcn.py", line 139, in main
    print("shape(pred):", pred[batch_train_mask])
RuntimeError: CUDA out of memory. Tried to allocate 160.16 GiB (GPU 0; 23.70 GiB total capacity; 8.36 GiB already allocated; 4.59 GiB free; 16.23 GiB reserved in total by PyTorch)

It fails at ```pred[batch_train_mask]```

## Environment

 - DGL Version: (I installed using ```pip install dgl-cu110```, so guessing the up-to-date version?)
 - Torch: 1.8.0
  - OS: Ubuntu 16.04
 - How you installed DGL: pip
 - Python version: 3.7
 - CUDA/cuDNN version: 11.0
 - GPU models and configuration (e.g. V100): RTX 3090, RTX 2080

P.S. I looked for other similar issues, but could not find the one that exactly solves this. If I missed something, please point that out.

**Comment by VoVAllen** [comment]
We've recently released `0.6.0post1`. Could you check your dgl version? Or try update with `pip install --upgrade dgl-cu11`

**Comment by talnish** [comment]
Thanks, with ```cu111```, it seems to work fine (vs. ```cu110```).
