### ISSUE TITLE
QM9EdgeDataset labels are wrong

### ISSUE THREAD

**Issue by milesial** [dmlc/dgl#2806]
## 🐛 Bug

With QM9EdgeDataset, it seems that the prediction labels are broken. This may be because of the preprocessing, or because of a bad source for QM9.

@hengruizhang98 @mufeili 

## To Reproduce

```python
from dgl.data import QM9EdgeDataset as DGLQM9Edge
from dgl.data import QM9Dataset as DGLQM9
import matplotlib.pyplot as plt

keys = ['mu', 'alpha', 'homo', 'lumo', 'gap', 'r2', 'zpve']
f, axs = plt.subplots(2, len(keys), figsize=(20, 5))
for i, task in enumerate(keys):
    ds_dgl = DGLQM9Edge([task])
    ds_dgl2 = DGLQM9([task])

    targets_dgl = ds_dgl.targets[:,i]
    targets_dgl2 =ds_dgl2.label[:,0]
    
    axs[0][i].hist(targets_dgl2, bins=50)
    axs[1][i].hist(targets_dgl, bins=50)

f.tight_layout()
plt.show()
```
The first row is the histograms of labels from QM9Dataset, and the second row is the ones from QM9EdgeDataset.

![image](https://user-images.githubusercontent.com/30204471/113320641-03106580-9313-11eb-9622-d2d33713e9e6.png)

## Expected behavior

Labels should be the same for all QM9 datasets.

## Environment

 - DGL Version (e.g., 1.0): commit 1f4c0b7
 - Backend Library & Version (e.g., PyTorch 0.4.1, MXNet/Gluon 1.3): PyTorch 1.9.0
 - OS (e.g., Linux): Linux
 - How you installed DGL (`conda`, `pip`, source): source
 - Build command you used (if compiling from source): cmake -DUSE_CUDA=ON -DUSE_FP16=ON .. && make -j8
 - Python version: 3.8.8

## Additional context
In the docs it says that the preprocessing is done here https://gist.github.com/hengruizhang98/a2da30213b2356fff18b25385c9d3cd2 so there must be something wrong there.

**Comment by hengruizhang98** [comment]
The sources of QM9 and QM9Edge are indeed different. In fact, QM9Edge uses the same source as the QM9 dataset in PyG. 
I will check again whether there is a preprocessing mistake.

Thank you for this information!

**Comment by milesial** [comment]
![image](https://user-images.githubusercontent.com/30204471/113336587-ef6efa00-9326-11eb-9a74-e225a9609cfd.png)

Third row is pytorch-geometric. So if the source is the same, then the processing is to blame.

**Comment by hengruizhang98** [comment]
I've fixed this issue. There was a minor mistake in my processing program leading to bad indexing, and I'm sorry about that.
The dataset file has been updated so you can try it again now.

![image](https://user-images.githubusercontent.com/26669850/113381271-21c53980-93b1-11eb-862b-41776333671a.png)

Thanks again for raising this issue.

**Comment by milesial** [comment]
Thank you for fixing this fast. Works for me too now. I suggest that you update your gist so that people who try to reproduce the preprocessing don't run into the same issue.
Closing this.

**Comment by milesial** [comment]
Also, @hengruizhang98 what is the difference between https://github.com/dmlc/dgl/blob/1f4c0b71934b67cd3451bc22d4f83d1b1fba8411/examples/pytorch/infograph/qm9_v2.py and QM9EdgeDataset?

**Comment by hengruizhang98** [comment]
In fact they are just the same. QM9_v2 was created earlier for convenience, and  I will update this example using QM9Edge Dataset soon.

**Comment by milesial** [comment]
I see that QM9V2 is directly loading DGL graphs with load_graphs, and QM9Edge is creating them on the fly. Maybe one is faster than the other.

**Comment by hengruizhang98** [comment]
Yes, It will take about 1 min to load graphs from QM9v2. While using QM9Edge is much faster as the graphs are constructed when called. You can choose the way you prefer.
