### ISSUE TITLE
Node ids of different types intersect in a DGL heterograph

### ISSUE THREAD

**Issue by jsuagee** [dmlc/dgl#2815]
I am attempting to initialize a heterograph with two node types (A and B) and it seems that the nodes of one of the types ends up containing the nodes of the other type as a subset (which it should not as far as I understand). If A contains a single node of index 0, and B contains 3 nodes of index set {1, 2}, then a call to 
G.nodes('B') will give [0, 1, 2] instead of [1, 2].

Here is a minimal example:
```
import torch as th
import dgl

edge_dict = {
             ('A', 'A2B', 'B'): (th.IntTensor([0, 0]), th.IntTensor([1, 2])),
             ('B', 'B2A', 'A'): (th.IntTensor([1, 2]), th.IntTensor([0, 0])),
             ('B', 'B2B', 'B'): (th.IntTensor([1, 2]), th.IntTensor([2, 1]))
            }
G = dgl.heterograph(edge_dict)
print(G.nodes('A'))
print(G.nodes('B'))
```
Then the output is:
```
tensor([0], dtype=torch.int32)
tensor([0, 1, 2], dtype=torch.int32)
```

I tried with a different ordering (the index of A is 2, and the index set of B is {0, 1}) and I get the output of 
```
print(G.nodes('A'))
print(G.nodes('B'))
```
is 
```
tensor([0, 1, 2], dtype=torch.int32)
tensor([0, 1], dtype=torch.int32)
```

My version of DGL is 0.6.0post1. Thanks in advance for looking at this.

**Comment by ZZy979** [comment]
This is what it should be. In DGL, The node id of all node types always starts from 0. The graph you created looks like this:

```
A       0
       / \
B  0  1---2
```

Node 0 of type A is not the same node as node 0 of type B.

**Comment by jermainewang** [comment]
Thanks @ZZy979 for the perfect explanation! This is indeed the intended design.

@jsuagee If you'd like to know more, please checkout the user guide chapter https://docs.dgl.ai/guide/graph-heterogeneous.html .

**Comment by jsuagee** [comment]
OK thanks so much! This makes sense.
