### ISSUE TITLE
Running time difference in "DGL Baseline Code for MAG240M"

### ISSUE THREAD

**Issue by fighting-zzz** [dmlc/dgl#2823]
## ❓ Questions and Help

I saw "Every epoch takes around 6 minutes 30 seconds to train and 1 minutes 40 seconds to validate." from https://github.com/dmlc/dgl/tree/master/examples/pytorch/ogb_lsc/MAG240M. 
However, it takes 30minutes to run one epoch on my server, which has a Nvidia Tesla T4. 
May I know the detailed CPU and GPU settings, such as how many CPUs and the specific version of Nvidia GPUs?

**Comment by weihua916** [comment]
Hi! I think the biggest bottleneck is numpy's memmap data loading---reading data from disk into CPU memory (not the actual GNN's computation on GPU). You may want to try some solutions [here](https://github.com/snap-stanford/ogb/issues/131).

**Comment by BarclayII** [comment]
Just to add to Weihua's comment, the bottleneck of memmap reading is the reason we choose the AWS p4d instance, which has very fast NVMe SSD access.  SATA SSD may also work.  The CPU and GPU power are not bottlenecks so T4 should work fine provided that you have faster hard drives.

**Comment by fighting-zzz** [comment]
原始的np.load 还是很慢
Thanks for your reply! !
In addition, I modify the "np.memmap" and "np.load(path, mmap_mode='r')" to "np.load(path)". However, it seems not accelerate the training speed. May I know the reason?
Thanks a lot !

**Comment by maqy1995** [comment]
Hi @fighting-zzz, How do you use `numpy.load` to read `full.npy`? I get an error when I try to load it:

>>> ​np.load("full.npy")

Value
Error: Cannot load file containing pickled data when allow_pickle=False

>>> np.load("full.npy", allow_pickle=True)
File "/python3.7/site-packages/numpy/lib/npyio.py", line 450, in load "Failed to interpret file %s as a pickle" % repr(file)"
OSError:Failed to interpret file 'full.npy' as pickle

**Comment by BarclayII** [comment]
> Thanks for your reply! !
> In addition, I modify the "np.memmap" and "np.load(path, mmap_mode='r')" to "np.load(path)". However, it seems not accelerate the training speed. May I know the reason?
> Thanks a lot !

Our results was obtained on a p4d instance which has A100 GPUs.

I changed to a g4dn.metal instance which has 384GB memory, 96 CPUs, and 8 T4 GPUs.  The training time is around 25 minutes per epoch.  I checked the GPU utilization and it seems that the GPUs are already fully utilized.

Here's my profiling result with line profiler showing that the majority of time is spent on GPU computation:
```
   113         1         12.0     12.0      0.0      print('Initializing model...')
   114         1    4982870.0 4982870.0      2.3      model = RGAT(dataset.num_paper_features, dataset.num_classes, 1024, 5, 2, 4, 0.5, 'paper').cuda()
   115         1        728.0    728.0      0.0      opt = torch.optim.Adam(model.parameters(), lr=0.001)
   116         1         94.0     94.0      0.0      sched = torch.optim.lr_scheduler.StepLR(opt, step_size=25, gamma=0.25)
   117
   118         1          2.0      2.0      0.0      best_acc = 0
   119
   120         1          4.0      4.0      0.0      for _ in range(args.epochs):
   121         1        527.0    527.0      0.0          model.train()
   122         1       2906.0   2906.0      0.0          with tqdm.tqdm(train_dataloader) as tq:
   123       153   18752626.0 122566.2      8.6              for i, (input_nodes, output_nodes, mfgs) in enumerate(tq):
   124       153     607742.0   3972.2      0.3                  mfgs = [g.to('cuda') for g in mfgs]
   125       153   24946232.0 163047.3     11.5                  x = mfgs[0].srcdata['x']
   126       152      30360.0    199.7      0.0                  y = mfgs[-1].dstdata['y']
   127       152   68713558.0 452062.9     31.6                  y_hat = model(mfgs, x)
   128       152      67583.0    444.6      0.0                  loss = F.cross_entropy(y_hat, y)
   129       152     130655.0    859.6      0.1                  opt.zero_grad()
   130       152   68071127.0 447836.4     31.3                  loss.backward()
   131       152    1739730.0  11445.6      0.8                  opt.step()
   132       152      26553.0    174.7      0.0                  acc = (y_hat.argmax(1) == y).float().mean()
   133       152   29501389.0 194088.1     13.6                  tq.set_postfix({'loss': '%.4f' % loss.item(), 'acc': '%.4f' % acc.item()}, refresh=False)
```

**Comment by BarclayII** [comment]
> Hi @fighting-zzz, How do you use `numpy.load` to read `full.npy`? I get an error when I try to load it:
> 
> ```
> >>> ​np.load("full.npy")
> 
> Value
> Error: Cannot load file containing pickled data when allow_pickle=False
> 
> >>> np.load("full.npy", allow_pickle=True)
> File "/python3.7/site-packages/numpy/lib/npyio.py", line 450, in load "Failed to interpret file %s as a pickle" % repr(file)"
> OSError:Failed to interpret file 'full.npy' as pickle
> ```

Could you try updating numpy?  Mine is 1.18.5 and I opened it without problems.

**Comment by maqy1995** [comment]
Hi @BarclayII ,
I download `inst.npy` from https://dgl-data.s3-accelerate.amazonaws.com/dataset/OGB-LSC/inst.npy to test `numpy.load()` again:

```
(base) maqy@ubuntu:~/work$ pip list |grep numpy
numpy                  1.18.5   

(base) maqy@ubuntu:~/work$ ll inst.npy 
-rw-rw-r-- 1 maqy maqy 39507456 4月  11 10:04 inst.npy

(base) maqy@ubuntu:~/work$ python
Python 3.7.4 (default, Aug 13 2019, 20:35:49) 
[GCC 7.3.0] :: Anaconda, Inc. on linux
Type "help", "copyright", "credits" or "license" for more information.
>>> import numpy as np
>>> np.load("inst.npy")
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "/home/maqy/miniconda3/lib/python3.7/site-packages/numpy/lib/npyio.py", line 457, in load
    raise ValueError("Cannot load file containing pickled data "
ValueError: Cannot load file containing pickled data when allow_pickle=False
>>> np.load("inst.npy", allow_pickle=True)
Traceback (most recent call last):
  File "/home/maqy/miniconda3/lib/python3.7/site-packages/numpy/lib/npyio.py", line 460, in load
    return pickle.load(fid, **pickle_kwargs)
_pickle.UnpicklingError: invalid load key, '\xe9'.

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "/home/maqy/miniconda3/lib/python3.7/site-packages/numpy/lib/npyio.py", line 463, in load
    "Failed to interpret file %s as a pickle" % repr(file))
OSError: Failed to interpret file 'inst.npy' as a pickle
>>> 
>>> np.memmap("inst.npy",mode='r',dtype='float16')
memmap([ 0.1534 , -0.12396,  0.10803, ...,  0.787  , -0.2355 ,  1.06   ],
       dtype=float16)

```
I can use `np.memmap()` to get data, but I still cannot use `numpy.load()` to read it.
I want to use `numpy.load` to read all the data into the main memory. Is it possible to do so?

**Comment by BarclayII** [comment]
@maqy1995 Try `np.memmap(...).copy()`.

**Comment by maqy1995** [comment]
thanks @BarclayII , 'np.memmap(...).copy()' works. 
By the way, what is the time-consuming tool for testing each line of code in the previous comment? It looks good to use.

**Comment by skepsun** [comment]
> @maqy1995 Try `np.memmap(...).copy()`. `np.load` cannot directly read the memmap files unless `mmap_mode` is not None (`r` to read).

I find in ogb scripts the same .npy file can be read by np.load() both with and without memmap mode:
`    @property
    def paper_year(self) -> np.ndarray:
        path = osp.join(self.dir, 'processed', 'paper', 'node_year.npy')
        return np.load(path, mmap_mode='r')

    @property
    def all_paper_year(self) -> np.ndarray:
        path = osp.join(self.dir, 'processed', 'paper', 'node_year.npy')
        return np.load(path)`
Is there any difference between the ways of saving .npy files for "node_year.npy" and "full_feat.npy" ?
