### ISSUE TITLE
what is etype in RelGraphConv can anyone please let me know.

### ISSUE THREAD

**Issue by Nirikshatk** [dmlc/dgl#2833]

**Comment by Nirikshatk** [comment]
Here is the example specified in the document:
import dgl
import numpy as np
import torch as th
from dgl.nn import RelGraphConv
>>>
g = dgl.graph(([0,1,2,3,2,5], [1,2,3,4,0,3]))
feat = th.ones(6, 10)
conv = RelGraphConv(10, 2, 3, regularizer='basis', num_bases=2)
conv.weight.shape
torch.Size([2, 10, 2])
**etype = th.tensor(np.array([0,1,2,0,1,2]).astype(np.int64))**
res = conv(g, feat, etype)
res
tensor([[ 0.3996, -2.3303],
        [-0.4323, -0.1440],
        [ 0.3996, -2.3303],
        [ 2.1046, -2.8654],
        [-0.4323, -0.1440],
        [-0.1309, -1.0000]], grad_fn=<AddBackward0>)


etype here is [0,1,2,0,1,2] , what does it signify?

**Comment by jermainewang** [comment]
It is a tensor of length |E| (E be the number of edges in the graph). Each element specifies which type the edge belongs to.

The API doc also describes this. I wonder which part confuses you? We'd like to further clarify it.

![image](https://user-images.githubusercontent.com/4057701/114333910-0958da00-9b7c-11eb-9c50-d43e59706c37.png)

**Comment by ZZy979** [comment]
R-GCN is intended for heterogeneous graph, while `RelGraphConv` takes a homogeneous graph. The parameter `etype` is a tensor that represents the original type of each edge.

**Comment by Nirikshatk** [comment]
understood, thanks a lot for clarifying.
