### ISSUE TITLE
Hi , I want to use RelGraphConv to explicitly specify the weights for the edges, how can i do it?? 

### ISSUE THREAD

**Issue by Nirikshatk** [dmlc/dgl#2834]
## ❓ Questions and Help

Before proceeding, please note that we recommend
using our discussion forum (https://discuss.dgl.ai) for
general questions. As a result, this issue will
likely be CLOSED shortly.

i want to apply RelGraphConv on a heterogeneous graph, and specify the edge weights manually in the code, how can i do it. please help.
thanks in advance!!!

**Comment by ZZy979** [comment]
Perhaps you can save the edge weights on `g.edata`.

**Comment by jermainewang** [comment]
You need to define a new NN module. You could start by copy-pasting the [`RelGraphConv` module](https://github.com/dmlc/dgl/blob/master/python/dgl/nn/pytorch/conv/relgraphconv.py) into your codebase. Then, as @ZZy979 suggested, save your edge weights into `g.edata`, which you could retrieve in the message function using `edges.data`. For example, you could modify L212 below
https://github.com/dmlc/dgl/blob/d70eade4f29744b84fa11805c9ea2244ec61625e/python/dgl/nn/pytorch/conv/relgraphconv.py#L187-L213

to

```python
h = edges.src['h'] * edges.data['w']  # suppose you have saved the edge weights to `g.edata['w']`
```

**Comment by Nirikshatk** [comment]
Thanks , i will try this out. 

i saw in the previous issue that @ZZy979 told, RelGraphConv is for homogeneous graph , i want to implement this for heterogeneous graph. so i should be doing similar changes in code of RGCN instead of RelGraphConv right?

**Comment by Nirikshatk** [comment]
> Perhaps you can save the edge weights on `g.edata`.

Thanks :)!
