### ISSUE TITLE
Heterogenous Graph Attention Network for Graph Classification

### ISSUE THREAD

**Issue by msintaha** [dmlc/dgl#2839]
## ❓ Questions and Help

Hi, the implementation of HAN in the repository is very suited for node classification. Is there any example implementation to support for graph classification? I have an example code if you want to take a look, but the output that the model is giving is a tensor that considers the number of nodes - when i need a tensor that considers the number of graphs. Here's the example: https://github.com/msintaha/BugClassificationWithGNN/blob/master/gat_classifier_heterographs.py

Appreciate your help in any way possible!

**Comment by e-yi** [comment]
Hi, msintaha. 

I guess what you need is a graph readout function.  You can find more about Global Pooling Layers [HERE](https://docs.dgl.ai/en/latest/api/python/nn.pytorch.html#module-dgl.nn.pytorch.glob) and some *graph property prediction* examples [HERE](https://github.com/dmlc/dgl/tree/master/examples).
