### ISSUE TITLE
libdgl not found

### ISSUE THREAD

**Issue by ccoulombe** [dmlc/dgl#2845]
## 🐛 Bug

With `v0.6.1`, 
libdgl.so is not found by `dgl_cpu/dgl/_ffi/_cy3/core.cpython-37m-x86_64-linux-gnu.so`.

When building DGL (cpu or gpu), libdgl.so is not found :
```
$ ldd dgl_cpu/dgl/_ffi/_cy3/core.cpython-37m-x86_64-linux-gnu.so
	libdgl.so => not found
```

## To Reproduce

Build from source :
```
git clone --recursive https://github.com/dmlc/dgl.git -b 0.6.1
mkdir build
cd build
cmake -DUSE_CUDA=ON ..
make -j4
```

## Expected behavior

If `libdgl.so` is used, it should be found.

## Additional context

I did not encounter any issues since I spotted this before deploying the wheel.

I fixed it by updating the runpath of `dgl_cpu/dgl/_ffi/_cy3/core.cpython-37m-x86_64-linux-gnu.so` with `$ORIGIN/../..` so `libdgl.so` is found.

**Comment by BarclayII** [comment]
The output from `ldd` is expected because `libdgl.so` is not in ldconfig cache.  That doesn't mean Python cannot load the library though.  Did you encounter any error during running?

**Comment by ccoulombe** [comment]
I did not and I won't know since I patched the lib. Just wanted to let you know.
If the lib is needed then it should be found or otherwise be removed/strip of the needed ones.
