### ISSUE TITLE
[RFC] A base class for graph property prediction datasets

### ISSUE THREAD

**Issue by mufeili** [dmlc/dgl#2851]
## 🚀 Feature
The base class creates a batched graph of all graphs during pre-processing and then reconstructs a small graph in `__getitem__` given its ID.

## Motivation

Multiprocessing is a common practice to accelerate data loading and training for graph property prediction.

As reported in #2349 , passing a list of `DGLGraph` to `DataLoader` in PyTorch with `num_workers > 0` can result in a significant increase in CPU memory usage. This is because applying python multiprocessing to arbitrary python objects will trigger copy-on-write behaviour due to the addition of refcounts. The CPU memory usage will continue to grow within an epoch and then drop by the end of the epoch. 

Inspired by https://github.com/snap-stanford/ogb/blob/master/ogb/lsc/pcqm4m_pyg.py#L95 and https://github.com/rusty1s/pytorch_geometric/blob/master/torch_geometric/data/batch.py#L162, one possible solution is to have a base class as described above as it will not trigger copy-on-write behaviour to apply python multiprocessing to a single `DGLGraph`.

## Alternatives

Built-in support for slicing a batched `DGLGraph`.

## Pitch

We will inherit this base class for all built-in graph property prediction datasets and write a tutorial for it. In the future, when users want to develop custom graph property prediction datasets, they will inherit this class. In this way, we will not trigger the copy-on-write behaviour for large graph property prediction datasets.

## Additional context

@jermainewang 

This issue was partially motivated by our observation with experiments on PCQM4M-LSC. Nevertheless, this may be less an issue for the dataset itself as multiprocessing helps little in that case. See the table below.

| Setting                  | Time/epoch (mins) | 
| ----------------- | ------------------  |
| DGL + 0 workers | 16                              | 
| DGL + 4 workers | 15                              |
| PyG + 0 workers | 17                               |
| PyG + 4 workers | 14                              |

**Comment by jermainewang** [comment]
Could you further describe how a user will create a new dataset by inheriting that class? What are the interfaces to override?

**Comment by mufeili** [comment]
See the example below.

```python
import dgl
from dgl.data import DGLDataset

class GraphPropDataset(DGLDataset):
    def get_g(self, bg, idx):
        batch_num_nodes = {ntype : bg.batch_num_nodes(ntype) for ntype in bg.ntypes}
        node_start = {ntype : batch_num_nodes[ntype][:idx].sum() for ntype in bg.ntypes}
        node_end = {ntype : node_start[ntype] + batch_num_nodes[ntype][idx] for ntype in bg.ntypes}

        batch_num_edges = {rel : bg.batch_num_edges(rel) for rel in bg.canonical_etypes}
        edge_start = {rel : batch_num_edges[rel][:idx].sum() for rel in bg.canonical_etypes}
        edge_end = {rel : edge_start[rel] + batch_num_edges[rel][idx] for rel in bg.canonical_etypes}

        # Split edges for each relation
        edge_dict = {}
        for rel in bg.canonical_etypes:
            srctype, _, dsttype = rel
            u, v = bg.edges(order='eid', etype=rel)
            edge_dict[rel] = (u - node_start[srctype], v - node_start[dsttype])

        # Create graph
        g = dgl.heterograph(edge_dict, {ntype : batch_num_nodes[ntype][idx]}, idtype=bg.idtype)

        # Slice node features
        for ntype in bg.ntypes:
            for key, feat in bg.nodes[ntype].data.items():
                g.nodes[ntype].data[key] = feat[node_start[ntype]: node_end[ntype]]

        # Slice edge features
        for rel in bg.canonical_etypes:
            for key, feat in bg.edges[rel].data.items():
                g.edges[rel].data[key] = feat[edge_start[rel]: edge_end[rel]]

        return g

class CustomDataset(GraphPropDataset):
     def __getitem__(self, idx):
        return self.get_g(self.g, idx), ...
```
