### ISSUE TITLE
Can I run dgl 0.6.1 in cuda 10.0?

### ISSUE THREAD

**Issue by JiaquanYe** [dmlc/dgl#2865]
## ❓ Questions and Help

Before proceeding, please note that we recommend
using our discussion forum (https://discuss.dgl.ai) for
general questions. As a result, this issue will
likely be CLOSED shortly.

My cuda version is 10.0, I have found that dgl-cu100 only with 0.5.3 version. But my code use the function 'block_to_graph'(API of dgl), which was implement in 0.6.x, not 0.5.3. 
So can I run dgl-cu100 with 0.6.1 version? How can I install this version package? Or which API can be instead of 'block_to_graph' in dgl 0.5.3?

**Comment by VoVAllen** [comment]
We didn't release binary with cuda 10.0 because PyTorch also no longer released binary for cuda 10.0. But you can build from source on your machine following guides at https://docs.dgl.ai/install/index.html#install-from-source
