### ISSUE TITLE
dgl.to_homogenous doesn't work correctly on graphs with 0 nodes of a given type

### ISSUE THREAD

**Issue by s4chin** [dmlc/dgl#2870]
## 🐛 Bug

Assume that we have a heterogenous graph of 2 ntypes - A and B. There are some type A nodes in the graph but 0 type B nodes(This can happen if the graph is sampled via `EdgeLoader` such that the `Block` has no dstnodes of type B).

As a result, I have features for type A nodes but not type B.
```py
g.ndata['h'] = block_outputs
hg = dgl.to_homogeneous(g, ndata=['h'])
print(hg.ndata['h'])
```
Line 1 and 2 give no errors but line 3 results in `KeyError: 'h'` since `hg` doesn't contain any `ndata['h']`.

I can fix this by using
```py
for ntype in ['A', 'B']:
    if ntype in block_outputs:
        emb_size = block_outputs[ntype].shape[1]
for ntype in ['A', 'B']:
    if ntype not in block_outputs:
        block_outputs[ntype] = th.zeros(0, emb_size)
```

## To Reproduce

I think the error is clear from above but I can attach a script if necessary, though the script won't be super straightforward.

## Expected behavior

1. If there are 0 nodes of a given type, then the resulting homogeneous graph has `ndata['h']` for the rest of the nodes.
2. An error message on `dgl.to_homogeneous(g, ndata=['h'])` call if the output graph won't contain `ndata` of the specified key.

## Environment

 - DGL Version (e.g., 1.0): 0.6.0post1
 - Backend Library & Version (e.g., PyTorch 0.4.1, MXNet/Gluon 1.3): 1.7.1
 - OS (e.g., Linux): Mac 10.15.7
 - How you installed DGL (`conda`, `pip`, source):
 - Python version: 3.6.10
 - CUDA/cuDNN version (if applicable): N/A
 - Any other relevant information:

**Comment by VoVAllen** [comment]
I made a patch as the option 1 in your suggestion at https://github.com/dmlc/dgl/pull/3011
