### ISSUE TITLE
MXNet utest failed on bfs traversal

### ISSUE THREAD

**Issue by jermainewang** [dmlc/dgl#291]
## 🐛 Bug

The MX utest CI failes occasionally on bfs traversal. An example log:
```
======================================================================

FAIL: test_traversal.test_bfs

----------------------------------------------------------------------

Traceback (most recent call last):

  File "/usr/local/lib/python3.5/dist-packages/nose/case.py", line 198, in runTest

    self.test(*self.arg)

  File "/var/jenkins_home/workspace/DGL_PR-288-AFYFS7TRSIJ4ZSLNYUFPMPLCF37N7LB5U4CYHHB77TRI4XEOIBXQ@3/tests/mxnet/test_traversal.py", line 47, in test_bfs

    assert len(layers_dgl) == len(layers_nx)

AssertionError
```

## To Reproduce

(cannot reproduce reliably on my pc)
1. Any PR will occasionally trigger this bug.

## Expected behavior

CI should pass.

## Environment

 - DGL Version (e.g., 0.1.2):
 - Backend Library & Version (e.g., PyTorch 0.4.1, MXNet/Gluon 1.3): MXNet
 - OS (e.g., Linux): Ubuntu 16.04
 - Python version: 3.5

**Comment by zheng-da** [comment]
I tried running the code for 10000 times, but couldn't reproduce the bug.
