### ISSUE TITLE
 dgl.prop_nodes_topo() to work on GPU

### ISSUE THREAD

**Issue by LysSanzMoreta** [dmlc/dgl#2910]
## 🚀 Feature

Request dgl.prop_nodes_topo() to work on GPU. This is useful for models like TreeLSTM. I was struggling figuring out why I could run my model on the cpu and not in the GPU when I saw this comment inside the function. So, apparently, it's already in the TODO list

    # TODO(murphy): Graph traversal currently is only supported on
    # CPP graphs. Move graph to CPU as a workaround,
    # which should be fixed in the future.

## Motivation

TreeLSTM cannot be used with cuda and this restricts model's speed. Executing this type of models solely on the CPU or moving parts of the model to the GPU and parts to the CPU does not make sense in terms of efficiency.

Thanks in advance!

**Comment by jermainewang** [comment]
That's a fair ask. I also mentioned this as a motivation example in the RFC (#2861) for DGL + cuGraph.
