### ISSUE TITLE
change the structure of nodeflow 

### ISSUE THREAD

**Issue by gerrardmai** [dmlc/dgl#2913]
Suppose I uesed  **NeighborSampler** to creat a nodeflow which  batch_size=1, num_hops=2 and expand_factor=3;  
So layer0 had 6 nodes (assumed, full connection ) layer1 had 3 nodes and layer0 had1 node;
Now I want to select some of nodes in layer0, suppose i only want specific 4 nodes in this structure to the further process; 

How should I do?

Thank you;

**Comment by BarclayII** [comment]
NodeFlow is now deprecated in favor of `dgl.sampling.NeighborSampler`.  Please refer to https://docs.dgl.ai/tutorials/large/index.html for more details.
