### ISSUE TITLE
AttributeError

### ISSUE THREAD

**Issue by wsprogrammeryang** [dmlc/dgl#2919]
## ❓ Questions and Help

hello，

when i run this code:
    data = citegrh.load_cora()
    data.features = torch.FloatTensor(data.features)
the compiler shows
 data.features = torch.FloatTensor(data.features)
AttributeError: can't set attribute

Has anyone seen this problem？
Is there a problem with the version of the library？
my dgl version 0.6.1

thank you

**Comment by VoVAllen** [comment]
Hi,

Why you want to do `data.features = torch.FloatTensor(data.features)`? Also which example are you following?

**Comment by wsprogrammeryang** [comment]
> Hi,
> 
> Why you want to do `data.features = torch.FloatTensor(data.features)`? Also which example are you following?

the code comes from a paper   i failed to contact the author 
is it a wrong usage?
i have searched the question but no one like this.

**Comment by VoVAllen** [comment]
@wsprogrammeryang Could you try set `data.features.float()` to another variable and use it later?

**Comment by wsprogrammeryang** [comment]
@VoVAllen 
thanks for replying.
yes,i have uesd another variable  to replace it.  it works.
thank you
