### ISSUE TITLE
ImportError: cannot import name 'SSTBatch' from 'dgl.data'

### ISSUE THREAD

**Issue by Kunjal1999** [dmlc/dgl#2949]
## ❓ Questions and Help

Before proceeding, please note that we recommend
using our discussion forum (https://discuss.dgl.ai) for
general questions. As a result, this issue will
likely be CLOSED shortly.

**Comment by Kunjal1999** [comment]
After installing dgl by 'pip3 install dgl'
While writing 
from dgl.data import SSTBatch

I am getting the error:
ImportError: cannot import name 'SSTBatch' from 'dgl.data' (/usr/local/lib/python3.7/dist-packages/dgl/data/__init__.py)

**Comment by VoVAllen** [comment]
It's renamed to SSTDataset, which you can get by `from dgl.data import SSTDataset`
