### ISSUE TITLE
[Bug] Cython is broken with python 3.6

### ISSUE THREAD

**Issue by VoVAllen** [dmlc/dgl#2951]
## 🐛 Bug
```
>>> import dgl._ffi._cy3.core
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
ImportError: libpython3.6m.so.rh-python36-1.0: cannot open shared object file: No such file or directory
```

## To Reproduce

1.
1.
1.

## Environment

 - DGL Version (e.g., 1.0):
 - Backend Library & Version (e.g., PyTorch 0.4.1, MXNet/Gluon 1.3):
 - OS (e.g., Linux):
 - How you installed DGL (`conda`, `pip`, source):
 - Build command you used (if compiling from source):
 - Python version:
 - CUDA/cuDNN version (if applicable):
 - GPU models and configuration (e.g. V100):
 - Any other relevant information:

**Comment by BarclayII** [comment]
The reason is that the Cython library built in nightly and releases are linking to Python 3.6 provided by CentOS 7 SCL, which actually modifies the Python shared object.  Should be fixed in next nightly and release versions.
