### ISSUE TITLE
Add advanced hyperparameter tuning like Keras Tuner

### ISSUE THREAD

**Issue by nashid** [dmlc/dgl#2954]
## 🚀 Feature
Add advanced hyperparameter tuning like Keras Tuner 
https://github.com/keras-team/keras-tuner

## Motivation
It would be great if there is a way to hyperparameter tuning in an automated fashion. As an example, Keras Tuner provides a way to specify tuning parameters. Would be great to have a similar option with DGL.

**Comment by VoVAllen** [comment]
We're not familiar with this area very much. However, I believe most of the HPO framework on PyTorch can also be used with DGL. If you found any good solution, contribution is welcomed :)

**Comment by BarclayII** [comment]
You can use third-party hyperparameter tuners such as [Ray + PyTorch Lightning](https://towardsdatascience.com/how-to-tune-pytorch-lightning-hyperparameters-80089a281646) (DGL supports PyTorch Lightning in recent nightly builds) or [AutoGluon](https://auto.gluon.ai/stable/tutorials/torch/index.html).
