### ISSUE TITLE
DGMG Example: reset node representations to initial representations after ChooseDestAndUpdate

### ISSUE THREAD

**Issue by FunkMonkey** [dmlc/dgl#2963]
## 🐛 Bug

I think in the DGMG example, the node representations should be reset to their initial representations after each call to ChooseDestAndUpdate. Otherwise the graph propagation will update the vectors constantly, so they accumulate more and more neighbourhood information over time (and not only through the X rounds of message propagation). This is especially troublesome because older nodes will have more "history" in their vector (and as such further neighbourhood information) than newer nodes. 

For this to work the graph propagation should also be at the start of ChooseDestAndUpdate.

I hope this makes sense or did I just misunderstand something?

## Environment

 - DGL Version (e.g., 1.0): 0.6
 - Backend Library & Version (e.g., PyTorch 0.4.1, MXNet/Gluon 1.3): Pytorch 1.8.1
 - OS (e.g., Linux): Windows
 - How you installed DGL (`conda`, `pip`, source): conda
 - Build command you used (if compiling from source):
 - Python version: 3.7.9
 - CUDA/cuDNN version (if applicable):
 - GPU models and configuration (e.g. V100):
 - Any other relevant information:

**Comment by mufeili** [comment]
According to the description below, I don't think we need to reset the node representations.

> After the predictions are made, the new node vectors h^(T)_V
are carried over to the next step, and the same carry-over
is applied after each and any decision step. This makes the
node vectors recurrent, across both the propagation steps
and the different decision steps.

**Comment by FunkMonkey** [comment]
@mufeili 

Yes you are right. Sorry, I must have missed that. I guess this idea of adding a new node based on the current graph's complete history (as in learning the action sequence by not resetting hvs) and not only the current state of the graph just isnt applicable to my own problem of generating graphs based on partial graphs, where this type of aggregated history may have certain downsides (unless many random decision sequences leading to the same intermediary result are trained).

Thanks a lot for clearing this up for me!

**Comment by mufeili** [comment]
> @mufeili
> 
> Yes you are right. Sorry, I must have missed that. I guess this idea of adding a new node based on the current graph's complete history (as in learning the action sequence by not resetting hvs) and not only the current state of the graph just isnt applicable to my own problem of generating graphs based on partial graphs, where this type of aggregated history may have certain downsides (unless many random decision sequences leading to the same intermediary result are trained).
> 
> Thanks a lot for clearing this up for me!

Glad it helps!
