### ISSUE TITLE
Support multiple cuda streams

### ISSUE THREAD

**Issue by nv-dlasalle** [dmlc/dgl#2974]
## 🚀 Feature
Right now cuda stream support is fully handled in the code base. There is a stream associated with each thread via `CUDAThreadEntry::ThreadLocal()->stream`, however this generally only supports operations on the default stream. Because DGL operates via DL pack with backends, whenever a tensor is moved from DGL to a backend or vice versa, we need to make sure the default stream is synchronized with (the same goes for using TensorAdapter).

It would be great to support using multiple threads within in DGL, synchronizing with the default stream whenever passing data in/out of DGL to ensure coherence.

## Motivation

One major challenge for achieving performance with DGL and GNNs in general, is keeping the GPU busy. Having to synchronize between the CPU and GPU, often causes the GPU to stall waiting for more work to be launched. Allowing computations on the non-default stream would help to alleviate this.

## Pitch

We could make DGLContext not a direct descendant of DLContext, and add a stream parameter. Then add a conversion function for DLContext to DGLContext, that makes the DGLContext's stream wait for an event in the default stream, and a conversion function for DGLContext to DLContext that makes the default stream wait for an event in the  DGLContext's stream.

We would also then require a `.to()` call to transfer tensors between DGLContexts, that would have the streams wait for an event to guarantee synchronization.

Memory management is something we would need to keep in mind, but CUDA 11.2's stream based allocator (#2651) may be one option (at least for DGL workspaces).

## Additional context

The current stream support is proving to be challenge in heterograph operations (#2925).

**Comment by nv-dlasalle** [comment]
@yaox12 Am I correct that there is no more work to do to support multiple streams and that this can be closed?

**Comment by yaox12** [comment]
I think so. Other work is to write multi-stream code on the Python side.
