### ISSUE TITLE
Possible typo in DGL base dataset class

### ISSUE THREAD

**Issue by universvm** [dmlc/dgl#2977]
Hi, 

I believe the line:
https://github.com/dmlc/dgl/blob/195f99362d883f8b6d131b70a7868a537e55b786/python/dgl/data/dgl_dataset.py#L119

references perhaps an old / wrong path `dgl.utils.data.load_graphs`, when I think you mean `dgl.data.utils.load_graphs`

let me know your thoughts

**Comment by universvm** [comment]
Also the English in this sentence:

https://github.com/dmlc/dgl/blob/195f99362d883f8b6d131b70a7868a537e55b786/python/dgl/data/dgl_dataset.py#L15

`The following steps will are executed automatically:`

Could be fixed to:

`The following steps will **be** executed automatically:`

**Comment by jermainewang** [comment]
Nice catch! Would you mind fixing them for us? Thanks!

**Comment by jermainewang** [comment]
Great thanks!
