### ISSUE TITLE
Need another version of uniform negative_sampler 

### ISSUE THREAD

**Issue by dwang55** [dmlc/dgl#2978]
## 🚀 Feature

Need for 'truly' uniform negative_sampler

## Motivation

Dgl has a uniform negative sampler class in `dgl.dataloading.negative_sampler`. In fact, this class will return edges which are existed in the graph because of its implemention here:
`src, _ = g.find_edges(eids, etype=canonical_etype)`
`src = F.repeat(src, self.k, 0)`
`dst = F.randint(shape, dtype, ctx, 0, g.number_of_nodes(vtype))`

This uniform negative sampler is widely used in other source code. Using this to build models may be harmful to perfomance specifically for link prediction task in dense graphs.

## Alternatives

Users can implement own negative sampler class by defining sampling distribution to achive this. But I think it's necessary to have a official implemention of this feature.

**Comment by BarclayII** [comment]
Does this work for you?  https://discuss.dgl.ai/t/negative-sampling-in-dgl-edgedataloader/1888

**Comment by dwang55** [comment]
> Does this work for you? https://discuss.dgl.ai/t/negative-sampling-in-dgl-edgedataloader/1888

Thanks for replying!
This link works fine for me. And I think it will be better to points out this possible side effect in docs of negative sampling.

**Comment by BarclayII** [comment]
We now provide a `GlobalUniform` negative sampler that ensures the positive edges are not included.
