### ISSUE TITLE
dgl basic example add the same edge twice

### ISSUE THREAD

**Issue by hurun** [dmlc/dgl#299]
## 📚 Documentation

DGL Basic Example.

g.add_nodes(10)
src = th.tensor(list(range(1, 10)));
g.add_edges(src, 0)
 g.edata['w'] = th.randn(9, 2)
---------------------------------------------
it works. but add twice the same edge, report error, seems graph not recognition the edge was exist.
the code is here.
----------------------------------------------
g.add_nodes(10)
src = th.tensor(list(range(1, 10)));
g.add_edges(src, 0)
g.add_edges(src, 0)  #twice add the same edge

 g.edata['w'] = th.randn(9, 2)

Traceback (most recent call last):
 File "<ipython-input-33-1d2f1232fb8b>", line 1, in <module>
    g.edata['w'] = th.randn(9, 2)

  File "D:\Anaconda3\lib\site-packages\dgl\view.py", line 116, in __setitem__
    self._graph.set_e_repr({key : val}, self._edges)

  File "D:\Anaconda3\lib\site-packages\dgl\graph.py", line 1609, in set_e_repr
    ' Got %d and %d instead.' % (nfeats, num_edges))

DGLError: Expect number of features to match number of edges. Got 9 and 18 instead.

**Comment by BarclayII** [comment]
Are you trying to create a multigraph (where multiple edges may exist between the same node pair)?

If so, [please specify `multigraph=True`](https://docs.dgl.ai/tutorials/basics/2_basics.html#multigraphs).

If not, currently DGL does not attempt to check for duplicate edges, and doing so would cause undefined behavior (see the docstring of [`edge_ids`](https://docs.dgl.ai/generated/dgl.DGLGraph.edge_ids.html#dgl.DGLGraph.edge_ids))

**Comment by hurun** [comment]
> Are you trying to create a multigraph (where multiple edges may exist between the same node pair)?
> 
> If so, [please specify `multigraph=True`](https://docs.dgl.ai/tutorials/basics/2_basics.html#multigraphs).
> 
> If not, currently DGL does not attempt to check for duplicate edges, and doing so would cause undefined behavior (see the docstring of [`edge_ids`](https://docs.dgl.ai/generated/dgl.DGLGraph.edge_ids.html#dgl.DGLGraph.edge_ids))

not to create multigraph, just find this problem by accident.
