### ISSUE TITLE
DGLGraph Errors

### ISSUE THREAD

**Issue by askaskall** [dmlc/dgl#3001]
## 🐛 Bug

Hi, I'm a newbie in GitHub, programming, and DGL, but I want to learn how to build GCN so I followed dgl tutorial. When I'm trying to rerun the DGLGraph and Node/Edge Features, I encountered some problems even though I followed exactly the same steps and code from the tutorial.

### 1. The edge broadcasting feature from int (0) to the array.
```
import torch as th
import numpy as np
import scipy.sparse as `spp`

u = th.tensor([0,0,0,0,0])
v = th.tensor([1,2,3,4,5])
star1 = dgl.DGLGraph((u,v))

star2 = dgl.DGLGraph((0,v))
```

It's successfully running the `star1` but produces an error when running `star2`

![image](https://user-images.githubusercontent.com/64197384/121364346-ff631580-c937-11eb-9ef3-3506d9db158b.png)

### 2. g.clear() not working

```
g = dgl.DGLGraph()
g.add_nodes(10)
src = th.tensor([8, 9]); dst = th.tensor([0, 0])
g.add_edges(src, dst)

# Edge broadcasting will do star graph in one go!
g.clear(); g.add_nodes(10)
src = th.tensor(list(range(1, 10)));
g.add_edges(src, 0)

# Visualize the graph.
nx.draw(g.to_networkx(), with_labels=True)
plt.show()
```

![image](https://user-images.githubusercontent.com/64197384/121388854-1dd30c00-c94c-11eb-8090-c99afea85ece.png)

## Additional context
Please kindly help, is there anything I missed (maybe I need to input some other codes), or is it a problem with my laptop/program? I tried both using Jupyter notebook in Anaconda and Google Colab but they both produce the same error. 
Thank you in advance!

## Environment

 - DGL Version: 0.6.1
 - Backend Library & Version : pytorch 1.7.1 (py3.6_cuda110_cudnn8_0)
 - OS : Windows 10
 - How you installed DGL (`conda`, `pip`, source): `conda install -c dglteam dgl`
 - Python version: 3.6.13

**Comment by turoger** [comment]
With regards to Q1 I'm no expert either, but for the line:
> star2 = dgl.DGLGraph((0,v))

it looks like you're trying to map a value 0, to the vector v. I think you have to use a tensor to tensor like what you did in `star1`.  Effectively in `star1` you're adding to the graph `(0,1), (0,2), (0,3)...`

**Comment by askaskall** [comment]
@turoger Yes, even though we can also use the tensor like in the `star1`, I'm curious that it didn't work since it's explicitly stated in the [tutorial](https://docs.dgl.ai/en/0.4.x/tutorials/basics/2_basics.html) that "if one of the arrays is a scalar, the value is automatically broadcasted to match the length of the other array -- a feature called _edge broadcasting_" 

And yes, we can do `g = dgl.DGLGraph()` to emptied the object again. Thank you for mentioning from the webdoc!

**Comment by jermainewang** [comment]
Hi @askaskall , look like you are reading some out-dated tutorials. Please checkout the latest one: https://docs.dgl.ai/tutorials/blitz/index.html . I will close this for now. If you have other questions, feel free to open another issue.
