### ISSUE TITLE
Support for graph isomorphism network (GIN) for graph classification

### ISSUE THREAD

**Issue by nashid** [dmlc/dgl#3006]
## Motivation

I am wondering whether there are plans to include any of the following models:

[1] Xu et al. How Powerful are Graph Neural Networks?, ICLR 2019.
[2] Veronika Thost and Jie Chen. Directed acyclic graph neural networks. In ICLR, 2021.

Implementation is here: 
https://github.com/IBM/Project_CodeNet/tree/main/model-experiments/gnn-based-experiments

**Comment by jermainewang** [comment]
Hi, please checkout the repo of Benchmark GNNs: https://github.com/graphdeeplearning/benchmarking-gnns. They have GIN implementation for graph classification.
