### ISSUE TITLE
SAGEConv implementation differs from paper

### ISSUE THREAD

**Issue by wullli** [dmlc/dgl#3007]
## 🐛 Bug

In the forward pass for the SAGEConv layer, the concatenation is missing. The paper specifically mentions in section 3.3, that concatenation leads to significant gains in performance as opposed to a sum.

## To Reproduce

Current implementation:
```python
            # GraphSAGE GCN does not require fc_self.
            if self._aggre_type == 'gcn':
                rst = h_neigh
            else:
                rst = self.fc_self(h_self) + h_neigh
```

## Expected behavior

From the paper I think it should be:
```python
           # GraphSAGE GCN does not require fc_self.
            if self._aggre_type == 'gcn':
                rst = h_neigh
            else:
                rst = torch.cat([self.fc_self(h_self), h_neigh], dim=1)
```

Of course then the output would consequently be `out_dim * 2`.

![image](https://user-images.githubusercontent.com/29056346/121583727-e8ecb500-ca30-11eb-9d17-14451a582421.png)

## Environment

 - DGL Version (e.g., 1.0): 0.6.1
 - Backend Library & Version (e.g., PyTorch 0.4.1, MXNet/Gluon 1.3): PyTorch 1.5
 - OS (e.g., Linux): Ubuntu 20.04
 - How you installed DGL (`conda`, `pip`, source): pip
 - Build command you used (if compiling from source): -
 - Python version: 3.7.5
 - CUDA/cuDNN version (if applicable): 11.3
 - GPU models and configuration (e.g. V100): -
 - Any other relevant information: -

## Additional context

Thanks for looking into it.

Edit: Fix expected implementation to match GraphSAGE reference implementation.
Edit: Reformulate issue to match observation better after having investigated more.

**Comment by wullli** [comment]
Okay so I've investigated the paper's reference implementation. And It should be even different:

```python
# [nodes] x [out_dim]        
from_neighs = tf.matmul(neigh_means, self.vars['neigh_weights'])
from_self = tf.matmul(self_vecs, self.vars["self_weights"])                 
if not self.concat:            
        output = tf.add_n([from_self, from_neighs])        
else:            
        output = tf.concat([from_self, from_neighs], axis=1)
# bias        
if self.bias:            
        output += self.vars['bias']               
return self.act(output)
```

It turns out the separate linear transformations are fine, but the concatenation is not implemented anywhere. The line in the else statement.

**Comment by BarclayII** [comment]
Note that the original formulation is `W x concat(h_v, h_Nv)`, meaning that the linear projection is *after* concatenation.  This is equivalent to applying two linear transformations on `h_v` and `h_Nv` then adding them up.

So I guess you are requesting for a new feature that directly outputs the concatenation without linear projection?

**Comment by wullli** [comment]
So it seems that the concatenation in the reference implementation would indeed be a new feature here. Sorry for the confusion. I assumed that this concatenation in the reference implementation was what they meant in their algorithm, but you are right in that they apply the transformation after concatenation in the paper.

It might still be worth thinking about, since in my case it improved performance significantly. I am unsure why.
