### ISSUE TITLE
[Bug][Windows] Cannot build dgl with NCCL on Windows

### ISSUE THREAD

**Issue by lygztq** [dmlc/dgl#3012]
## 🐛 Bug

After #2934 , NCCL is a submodule of DGL. However, when built dgl with external-nccl on Windows, I encountered this error:

```
'env' is not an internal or external command, nor is it a runnable program or batch file
```

I think currently NCCL does not support Windows?

## To Reproduce

Just follow the steps for building dgl on Windows with CUDA-support (see [here](https://docs.dgl.ai/install/index.html#windows))

## Environment

 - DGL Version (e.g., 0.6):
 - OS: Windows
 - How you installed DGL: source
 - Python version: 3.7
 - CUDA/cuDNN version (if applicable): cuda10.1

**Comment by jermainewang** [comment]
NCCL is now optional when building from source (fixed by #3056 ). Pass `USE_NCCL=ON` to turn it on.
