### ISSUE TITLE
Node-type aware sampling on distributed heterogeneous graphs?

### ISSUE THREAD

**Issue by erickim555** [dmlc/dgl#3030]
According to the "Distributed Heterogeneous graph training" wiki (v0.6.x), my understanding is that `sample_neighbors()` (eg N-hop neighbors) samples neighbors in a node-type-agnostic manner:

https://docs.dgl.ai/guide/distributed-hetero.html

Is my understanding correct? Does DGL plan to implement a node-type aware sampling method on distributed heterogeneous graphs in the near future (eg metapath-based sampling)?

I ask because: on heterogeneous graphs, node-type-agnostic sampling could introduce an undesirable sampling bias. If a particular node-type `nodeTypeA` tends to have significantly higher degree than other node types, then `nodeTypeA` will dominate the sampled subgraphs. For this reason, it's often useful to use node-type-aware sampling methods (eg meta-path based) when training heterogeneous graph models.

**Comment by jermainewang** [comment]
cc @zheng-da . Also related to https://github.com/dmlc/dgl/issues/2693
