### ISSUE TITLE
ChebConv is much slower than PyTorch Geometric

### ISSUE THREAD

**Issue by WilliamKRobert** [dmlc/dgl#3038]
## 🐛 Bug

Runtime of ChebConv is at least 100x slower than the implementation in PyTorch Geometric
## To Reproduce

1. Generate a random graph with 1000 nodes
2. Run ChebNet
3. Average runtime over 1000 runs

## Environment

 - DGL Version (e.g., 1.0): 0.6.1
 - Backend Library & Version (e.g., PyTorch 0.4.1, MXNet/Gluon 1.3): PyTorch 1.7
 - OS (e.g., Linux): Linux
 - How you installed DGL (`conda`, `pip`, source): conda
 - Python version: 3.8.8
 - CUDA: 10.2
 - GPU models and configuration (e.g. V100): V100

**Comment by BarclayII** [comment]
Turns out that if `lambda_max` is not specified, the module will compute the largest eigenvalue every time you call the module, which is super slow.
