### ISSUE TITLE
Copying graphs and deleting edges will result in an increase GPU memory

### ISSUE THREAD

**Issue by FANTASTPATR** [dmlc/dgl#3042]
I constructed a complete graph, where weights on edges are generated by learnable parameters and adjusted by back propagation, we will remove edges by its weights and construct a proper graph to support downstream tasks.
However, we found that the GPU memory will increase suddenly at a certain moment and cause CUDA out of memory, while the GPU memory will keep stable before the moment. 
The version of DGL is 0.5.3, detailed source code of the process is given as follows:
![image](https://user-images.githubusercontent.com/21437254/122669708-2ef40680-d1f1-11eb-9a3b-79c57bf5c71c.png)

Hope for replying!

Update:
After checking, we found that the bug will happen when ops.edge_softmax(graph, e) in GATConv and dgl.remove_edges occur in a forward propagation simultaneously, if we replace  "graph.edata['a'] = self.attn_drop(ops.edge_softmax(graph, e))" with " graph.edata['a'] = self.attn_drop(e)", the bug will be disappeared.

**Comment by VoVAllen** [comment]
The bug also exists when changing from `g.remove_edges(...)` to `g = dgl.remove_edges(...)` seems there's unexpected reference in the removed graph

**Comment by jermainewang** [comment]
Duplicate issue #3044 .
