### ISSUE TITLE
ModuleNotFoundError: No module named 'dgl.graph'

### ISSUE THREAD

**Issue by HenryPaik1** [dmlc/dgl#3048]
Hi, it seems this issue has been pending.
Where can I find the solution? I found some discussion but they were all closed without solution.

e.g. https://discuss.dgl.ai/t/modulenotfounderror-no-module-named-dgl-graph/1662/7

**Comment by jermainewang** [comment]
Could you please provide us the detailed reproducible steps and system environment (your OS, DGL version, cuda, pip or conda etc.)? Please follow the bug report issue template. Otherwise, the team cannot look into your problem.
