### ISSUE TITLE
calling SAGE module in graphsage pytorch example

### ISSUE THREAD

**Issue by adityauser** [dmlc/dgl#3058]
Hey, I trying to run the graphsage pytorch example. 
I don't understand why we are passing hidden layer size as number of classes? https://github.com/dmlc/dgl/blob/411bef5498bc79641858ea15ee79b6085c855187/examples/pytorch/graphsage/train_sampling_unsupervised.py#L98
Please guide me, I'm new to dgl library.

Thanks

**Comment by VoVAllen** [comment]
The num_classes is actually the hidden dim of the final layer. In unsupervised task, we don't care the num_classes. Therefore you can specify arbitrary number of num_classes, which will only affect the output dimension size
