### ISSUE TITLE
[RFC] Accelerate train by re-ordering graph

### ISSUE THREAD

**Issue by Rhett-Ying** [dmlc/dgl#3059]
## 🚀 Feature

Add a utility API named reorder() into dgl.transform to enable reorder graph according to several strategies such as 'rcmk', 'metis'. self-designed strategies should also be supported in this reorder() interface.
## Motivation
Denser and more banded adjacency matrix of graph has the advantage of better locality which could further accelerate train.
Though reorder incurs additional overheads, we could apply reorder before train, save the reordered graph for further use. In this way, overheads could be off-lined.
We want to see whether this simple strategy could improve kernel speed without changing any kernel implementation. If so, we could perform such reordering in our datasets.

## Alternatives
re-order could be implemented by leveraging existing dgl.node_subgraph(). what we need to do is generate a new node permutation which has more banded adjacency matrix. 

The reordering algorithms we have tried so far:
‘rcmk’: scipy.sparse.csgraph.reverse_cuthill_mckee
‘metis’: dgl.partition.metis_partition_assignment

Perf results
Significant (10~70)% improvement or even more for large graphs(150K+nodes) such as ‘reddit‘ whose adj_matrix could be changed to banded or more banded.
Obtained improvement varies across test level(kernel/model) and datasets.

## Pitch
Below is the API signature we proposed for now.

    dgl.reorder(g, strategy = 'rcmk', nodes_perm = None, store_ids=True, k = None)

    """
    Return a new graph which re-order and re-label the nodes according to the specified strategy or nodes_perm.

    Homogeneous graph is supported only.

    This API is basically implemented by leveraging dgl.node_subgraph(), so the function signature is similar and raw IDs could be stored in dgl.NID and dgl.EID.

    Parameters
    ----------
    g : DGLGraph
        * The homogeneous graph.
    strategy: str, optional
        * can be ``'rcmk'`` or ``'metis'``. ``'rcmk'`` is the default strategy.
    nodes_perm: nodes, optional
        * Graph is re-ordered according to the specified nodes_perm. This enables user to use self-designed re-order algorithm. IntTensor and IntArray are supported.
    store_ids: bool, optional
        * It's passed into dgl.node_subgraph(). If True, it will store the raw IDs of the extracted nodes and edges in the ndata and edata of the resulting graph under name dgl.NID and dgl.EID, respectively.
    k: integer, used/required by ``'metis'`` only
        * when strategy is specified as ``'metis'``, k is required to indicates the target partition parts.

    Return
    ------
    DGLGraph
        The re-ordered graph
    """

**Comment by yzh119** [comment]
Yes reordering like rcmk could greatly improve the node index locality thus accelerating message-passing kernels. I'm in favor of this proposal.
Reordering node index for heterographs would be much for tricky because one node type might be associated with several edge types, do you have any ideas on this?

Implementation-wise, there are several design choices:
1. Implement these reordering algorithms in C++ side, we can reuse existing libraries like [Boost Graph Library](https://www.boost.org/doc/libs/1_76_0/libs/graph/doc/index.html) and they have implemented RCMK.
2. Use scipy's API, we need python-side API to get access to indptr, indices array for csr representation.

btw, do you have any speed numbers on graph ordering, on both coo and csr format?

**Comment by Rhett-Ying** [comment]
@yzh119 
thanks for your comments.

I'd like to focus on homograph only. Reordering heterograph is not easy indeed. I have no ideas on this for now.

implementation part, I'd like to leverage existing APIs/primitives[**dgl.node_subgraph()**] in DGL. I mentioned it in the 'Alternatives' part in this ticket. Actually, users could implement such re-order logic on their own with existing available APIs in DGL. 
the main purpose of this feature/ticket is to give a hint and utility API to users that we could accelerating train if re-order original graph before hand by utilizing the primitives DGL offers. as for which re-order algo is applied or how the node permutation is generated, it's up to users. benefits could vary a lot in different scenarios(dataset, feature size...). dedicated research and trial  is required.

I tried RCMK(scipy) and metis_partition(dgl.partition) on several datasets and measured with //dgl/benchmarks/benchmarks/kernel/*.py.  Significant improvements are obtained and the number varies on datasets/feature_size(10%~200%). in my experience, re-order via RCMK/metis has great benefits for several large graphs such as reddit. But, many conditions(num_nodes, density, degree, feature_size, meaure level(kernel/model)) could have impact on the real speed-up we could obtain by re-order, not mention the various re-order algos.

**Comment by jermainewang** [comment]
One issue with the current signature is that some arguments are coupled with each other. For example, when `node_perm` is not None, the `strategy` argument will be invalid. And when `strategy` is not `metis`, the `k` argument will be invalid. Besides, adding new strategies in the future will likely cause more arguments being introduced. How about:
```python
dgl.reorder(g, permute_alg='rcmk', store_ids=True, permute_config={}):
```

* There are three algorithms to choose for the first version. `'rcmk'`, `'metis'` and `'custom'`.
* `permute_config` is a dictionary storing the extra configurations users can specify for the chosen algorithm.
* When `permute_alg='metis'`, users need to provide `k`, the number of partitions.
* When `permute_alg='custom'`, users need to provide `node_perm`, the new order of node IDs.

**Comment by Rhett-Ying** [comment]
sure. Below one is preferable.

    dgl.reorder(g, permute_alg='rcmk', store_ids=True, permute_config={}):
