### ISSUE TITLE
Request for an official way to solve 0 in-degree nodes manually in heterogeneous graph

### ISSUE THREAD

**Issue by YuxianMeng** [dmlc/dgl#3061]
## Motivation

When dealing with heterogeneous graph `g`, one can often use `g[etype]` to get the subgraph, then do message passing 
on it. However, the above subgraph sometimes have 0-in-degree nodes. I noticed that in dgl tutorial we are recommended to
solve it manually, but there is not a clear/elegant/efficient way to do that.

**Comment by classicsong** [comment]
When you apply Conv layers on g[etype] you can look at the doc here: https://docs.dgl.ai/en/latest/api/python/nn.pytorch.html#module-dgl.nn.pytorch.conv to see if the ConvLayer support allow_zero_in_degree.
