### ISSUE TITLE
Question about building graph with in-going and out-going concatenated adjacency for GatedGraphConv?

### ISSUE THREAD

**Issue by icmpnorequest** [dmlc/dgl#3062]
Hi team, 

I was reading Gated Graph Neural Network paper and want to reproduce the experiment. I was wondering how to construct the graph with `dgl library`, which contains in-going adjacency and out-going adjacency concatenated, and then feed into `dgl.nn.pytorch.GatedGraphConv`. 

The input for `GatedGraphConv` should be 3 parameters:
- graph (DGLGraph) – The graph.
- feat (torch.Tensor) – The input feature of shape (𝑁,𝐷𝑖𝑛) where 𝑁 is the number of nodes of the graph and 𝐷𝑖𝑛 is the input feature size.
- etypes (torch.LongTensor) – The edge type tensor of shape (𝐸,) where 𝐸 is the number of edges of the graph.

I was wondering how to construct such graph fit for GatedGraphConv. Thanks in advance.

**Comment by VoVAllen** [comment]
Discussed at https://discuss.dgl.ai/t/concat-in-going-adjacency-and-out-going-adjacency-for-gatedgraphconv/2095/2
