### ISSUE TITLE
Windows 10 Failed to find module dgl.dll

### ISSUE THREAD

**Issue by Ramlinbird** [dmlc/dgl#3067]
Hello, I installed the CPU-version dgl by `pip install dgl`, and failed to import it while I excuted follow command
```
import dgl
```
The error message is 
```
FileNotFoundError: Could not find module 'c:\users\ewindpeng\appdata\local\programs\python\python38\lib\site-packages\dgl\dgl.dll' (or one of its dependencies). Try using the full path with constructor syntax.
```
However, while I excuted bellow commands,
```
import sklearn
import dgl
```
All things seems good. What's the matter? Look forward for your reply. Thanks a lot.

**Comment by VoVAllen** [comment]
It seems there are some linking probelm. Some library that dgl depends cannot be found directly. But `import sklearn` can find that and load it, therefore then dgl can find those.

**Comment by Ramlinbird** [comment]
> It seems there are some linking probelm. Some library that dgl depends cannot be found directly. But `import sklearn` can find that and load it, therefore then dgl can find those.

Thanks. Do you know how  to fix this?

**Comment by VoVAllen** [comment]
What's your python version? It's probably related to this https://github.com/dmlc/dgl/issues/1416#issuecomment-856034526.

You can follow https://stackoverflow.com/questions/7378959/how-to-check-for-dll-dependency to see whether the dependent libraries can be found

**Comment by BarclayII** [comment]
Could you install VC2015 redistributable and see if this problem still occurs?

**Comment by jermainewang** [comment]
Closed due to lack of activity. Please re-open if the problem still exists.

**Comment by rubmz** [comment]
https://stackoverflow.com/questions/214852/python-module-dlls/74645015#74645015

Has gave NICE answer that works (at least in my case - windows 11 python 3.9.X pytorch):

```
def add_cuda_to_path():
    if os.name != "nt":
        return
    path = os.getenv("PATH")
    if not path:
        return
    path_split = path.split(";")
    for folder in path_split:
        if "cuda" in folder.lower() or "tensorrt" in folder.lower():
            os.add_dll_directory(folder)

add_cuda_to_path()
import <my_module_that_depends_on_cuda>
```
