### ISSUE TITLE
Return edge IDs for the random walk sampler

### ISSUE THREAD

**Issue by gurdaspuriya** [dmlc/dgl#3072]
## 🚀 Feature
It'll be helpful to also provide the edge IDs in addition to the node IDs for the random walk sampler. This will particularly be helpful in the case of multigraphs (multiple possible edge IDs for the same random walk).

## Motivation
An additional step is required to get the edge IDs at this point (retrieve the edge IDs from the node Ids returned by the random walk sampler). This is not efficient in the case of multigraphs with weighted edges, as it requires another sampling step.

**Comment by BarclayII** [comment]
This is implemented in #2992 and is available in nightly build.
