### ISSUE TITLE
DGL_KE：Expected type graph.Graph but get graph.HeteroGraph

### ISSUE THREAD

**Issue by eedalong** [dmlc/dgl#3073]
DGL version: '0.6.1' 

command: python train.py --model DistMult --dataset FB15k --batch_size 1024 --neg_sample_size 256  
   --hidden_dim 400 --gamma 143.0 --lr 0.08 --batch_size_eval 16 --valid --test -adv     --gpu 0 --max_step 40000 

error: Expected type graph.Graph but get graph.HeteroGraph

**Comment by yzh119** [comment]
DGL KE has not supported DGL 0.5+ yet.

**Comment by eedalong** [comment]
> DGL KE has not supported DGL 0.5+ yet.

Alright...., thx bro!
