### ISSUE TITLE
ModuleNotFoundError: No module named 'dgl.multiprocessing'

### ISSUE THREAD

**Issue by 634671436** [dmlc/dgl#3074]
I was testing DeepWalk using your gus dgl，but I got error like this:
       ModuleNotFoundError: No module named 'dgl.multiprocessing'

the version of dgl I was using is:
![image](https://user-images.githubusercontent.com/22366758/123777465-d1536e80-d902-11eb-8d44-43c59ea3e14d.png)

when I was change 'dgl.multiprocessing' to 'nn.multiprocessing' like your are saying in docs, but I meets another mp problem

**Comment by VoVAllen** [comment]
It's only available in the nightly version for now. However, it's almost the same as `torch.multiprocessing`. If you didn't meet any problem, it's fine to use `torch.multiprocessing`

**Comment by 634671436** [comment]
I don't know it is convenient for you to test the example/pytorch/ogb/deepwalk in your environment，maybe there is another problems I meet, it will stuck in somewhere.

 Running the code, i find the code in [reading_data.py] will stuck and it's strange.
     self.neg_table += [node] * node_degree[idx]

thanks in advance~

**Comment by VoVAllen** [comment]
You can use the example in the 0.6.x branch at https://github.com/dmlc/dgl/tree/0.6.x/examples/pytorch/ogb/deepwalk, which should be fine without dgl.multiprocessing

**Comment by 634671436** [comment]
Thanks a lot.
However, it meets the same problem, the code stuck somewhere and it does't work well, in spite of using a small dataset

**Comment by VoVAllen** [comment]
It will generate an embedding beforehand, which is efficient for large dataset. You can add `--fast_neg` to the args to skip this step

**Comment by 634671436** [comment]
And, when i use --fast_neg -> 'False'(which is default ),  I find it is much slower than  --fast_neg -> 'true' when I use the same youtube dataset, is it normal?

--fast_neg -> 'False'
![image](https://user-images.githubusercontent.com/22366758/123805870-053d8c80-d921-11eb-8b60-2275d7a7a0b8.png)

--fast_neg -> 'True'
![image](https://user-images.githubusercontent.com/22366758/123805949-125a7b80-d921-11eb-8ff7-c91dd3802522.png)

Which difference between them, the --fast_neg -> 'False' has the better result?

**Comment by VoVAllen** [comment]
The fast-neg option is designed for extremely large dataset, thus in small dataset, it doesn't work fast enough

**Comment by jermainewang** [comment]
We should doc that clearly in the example README.

**Comment by 634671436** [comment]
hi，I have found that —fast_neg=False  was using for truest Negative sampleing in every batch , but the neg_table  has been Loaded into memory at read_dataset phrase, so np.random.choise doesn’t cost much time , I just connot understand why it diff so much in time cost , thx

**Comment by VoVAllen** [comment]
Deep walk docs fixed in https://github.com/dmlc/dgl/pull/3126

**Comment by VoVAllen** [comment]
@634671436 I haven't fully benchmarked the code, because it has many optimized fast paths for performance reason. If this problem matters to you, you can try `pyinstrument` tools to see which parts impact the performance.

Close this issue since the original problem is resolved. Feel free to raise a new issue if you still have any problem about deepwalk
