### ISSUE TITLE
How can I use dgl=0.4.3 with cuda 11.1

### ISSUE THREAD

**Issue by DingXiangYuanZhiXing** [dmlc/dgl#3083]
## ❓ Questions and Help

Before proceeding, please note that we recommend
using our discussion forum (https://discuss.dgl.ai) for
general questions. As a result, this issue will
likely be CLOSED shortly.
I'm using RTX 3090 to do my research, which needs Cuda >= 11.1.
But some repos like this: https://github.com/wzxxxx/MGA needs dgl=0.4.3.
How can I use both dgl=0.4.3 and cuda=11.1?

If I directly use dgl-cu111, which is dgl=0.6.1 or use dgl=0.4.3, it won't work.

**Comment by yzh119** [comment]
We don't have pre-built wheels for dgl-cu111==0.4.3, but you can build one from source:
```
git clone https://github.com/dmlc/dgl.git
git checkout 0.4.x
git submodule update --init --recursive
mkdir build
cd build
cmake -DUSE_CUDA=ON ..
make -j4
cd ../python
python setup.py install
```
I'm not sure if you will met bugs in this way.

The best way is to port MGA code to dgl 0.6.

**Comment by yzh119** [comment]
btw, `dgl-cu111` and `dgl` (the name of package you build from source) could co-exists so please ensure you have removed `dgl-cu111` before trying to compile the repo.

**Comment by DingXiangYuanZhiXing** [comment]
I have tried to install 0.4.3 with cuda 11.1， but it gives me the following error
error: identifier "cusparseScsrmm2" is undefined
Which is deprecated in CUDA 11.1


BTW, I delete "compute_30" cmacmakecmakCUDA for the compilation to work.

----------

该邮件从移动设备发送


--------------原始邮件--------------
发件人："Zihao Ye ***@***.***&gt;;
发送时间：2021年7月1日(星期四) 晚上7:28
收件人："dmlc/dgl" ***@***.***&gt;;
抄送："dxyzx ***@***.***&gt;;"Author ***@***.***&gt;;
主题：Re: [dmlc/dgl] How can I use dgl=0.4.3 with cuda 11.1 (#3083)
-----------------------------------

 

 
btw, dgl-cu111 and dgl (the name of package you build from source) could co-exists so please ensure you have removed dgl-cu111 before trying to compile the repo.

**Comment by yzh119** [comment]
That's unrelated to `compute_30`, cuda 11 have deprecated `cusparseScsrmm2` API and we have fixed that in dgl 0.5+. But the code change has not been reflected in branch 0.4.3.

**Comment by DingXiangYuanZhiXing** [comment]
Is there any solution to this problem?
Or if I can use multiple versions of dgl? I don't how to accomplish this.
----------

该邮件从移动设备发送


--------------原始邮件--------------
发件人："Zihao Ye ***@***.***&gt;;
发送时间：2021年7月1日(星期四) 晚上8:11
收件人："dmlc/dgl" ***@***.***&gt;;
抄送："dxyzx ***@***.***&gt;;"Author ***@***.***&gt;;
主题：Re: [dmlc/dgl] How can I use dgl=0.4.3 with cuda 11.1 (#3083)
-----------------------------------

 

 
That's unrelated to compute_30, cuda 11 have deprecated cusparseScsrmm2 API and we have fixed that in dgl 0.5+. But the code change has not been reflected in branch 0.4.3.

**Comment by yzh119** [comment]
You can use conda environment to separate different dgl versions and cuda versions: https://conda.io/projects/conda/en/latest/user-guide/tasks/manage-environments.html

**Comment by DingXiangYuanZhiXing** [comment]
@yzh119 Is there a way to install dgl=0.4.3 with cuda? I cannot find a dgl=0.4.3 with cuda, not to mention cuda 11.
Sorry, I mean multiple dgl versions in the same py script.

**Comment by yzh119** [comment]
That's easy, just use `pip install dgl-cu102==0.4.3` (you can change `cu102` to other cuda versions).

**Comment by Abigale001** [comment]
Hi @dxyzx0 , how did you deal with the problem? I have met the same problem as you.

**Comment by dxyzx0** [comment]
@Abigale001 Sorry, it was a long time ago and I couldn't remember whether I solved this problem.
