### ISSUE TITLE
how to get a batch successor/predecessor nodes? thanks.

### ISSUE THREAD

**Issue by wmingdao** [dmlc/dgl#3084]
## ❓ Questions and Help
hi! Thanks for your great work. I have a question: If I have a  tensor(a batch nodes ID), How can to get the  successors/predecessors of these nodes? I just know that **DGLHeteroGraph.successors/ DGLHeteroGraph.predecessors** , but its only can get one node's   successor/predecessor.  what should I do? Thanks ~

**Comment by BarclayII** [comment]
You can use `in_degrees` or `out_degrees`.
