### ISSUE TITLE
Why is the num_hops in partition scripts not the same value as GNN num_layers?

### ISSUE THREAD

**Issue by xcwanAndy** [dmlc/dgl#3108]
## ❓ Questions and Help

Hello, I have a question related to distributed GNN training using **DistDGL**, and I hope you may give me some advice if I was wrong or not.

- My understanding of distributed GNN training: To my knowledge, after partitioning the graph, each worker should have its own partition with all its _k_-hop neighbors, where _k_ is the num of GNN layers, together with its own partition's node/edge embeddings. And then during training, workers use `DistTensor` to request embeddings from other hosts according to their own partitions.

- Thus, I wonder why does the [partition example](https://github.com/dmlc/dgl/blob/master/examples/pytorch/graphsage/experimental/partition_graph.py) not assign `num_hops` according to the GNN `num_layers` but use the default value 1, while the `num_layers` in [training scripts](https://github.com/dmlc/dgl/blob/master/examples/pytorch/graphsage/experimental/train_dist.py) is by default 2. I wonder if this is correct for training. 

- Besides, if I change the `num_layers` in  the [training scripts](https://github.com/dmlc/dgl/blob/master/examples/pytorch/graphsage/experimental/train_dist.py), is the training process still correct in this example?

**Comment by VoVAllen** [comment]
Discussed at https://discuss.dgl.ai/t/why-is-the-num-hops-in-partition-scripts-not-the-same-value-as-gnn-num-layers/2137/3
