### ISSUE TITLE
Function implementation incomplete in RGCN-hetero example

### ISSUE THREAD

**Issue by caowencai** [dmlc/dgl#3115]
Something is missing when block is not none.

https://github.com/dmlc/dgl/blob/5496a99d69ca4bbcb6a068082c6f3c3bf7d2aa89/examples/pytorch/rgcn-hetero/model.py#L145

**Comment by classicsong** [comment]
The RelGraphEmbed here only works for full graph training. If you want to do minibatch training,  you can follow the way how RelGraphEmbedLayer in example/pytorch/rgcn/model.py (
https://github.com/dmlc/dgl/blob/5496a99d69ca4bbcb6a068082c6f3c3bf7d2aa89/examples/pytorch/rgcn/model.py#L57) deals with certain cases.

We may update this example in the future.
