### ISSUE TITLE
add nodes fails with custom node ids

### ISSUE THREAD

**Issue by leila-you** [dmlc/dgl#3124]
I have problem https://github.com/dmlc/dgl/issues/984
but the answer not enough for my task.
I want do node classification but by this answer, some node did not label and true class since they did not exist.
can you help me to solve it?

**Comment by VoVAllen** [comment]
You can use -1 to represent nodes without labels. All nodes are required for the same schema

**Comment by leila-you** [comment]
You can send me a link for more help؟

**Comment by VoVAllen** [comment]
Could you elaborate your question?

**Comment by leila-you** [comment]
Yes,
For example, I created the following graph and I have a total of 10 nodes:
graph_data[("type1", "5", "type2")]= (th.tensor([2,5,8,9,0]), th.tensor([1,7,3,4,6]))
G = dgl.heterograph(graph_data)
but when run it, I have 18 nodes
"  Graph(num_nodes={'type1': 10, 'type2': 8},
      num_edges={('type1', '5', 'type2'): 5},
      metagraph=[('type1', 'type2', '5')])
"
When I want to add features to nodes, I do not know how to lable because I have 10 nodes but with dgl I have 18 nodes.
nodes:[0,1,2,3,4,5,6,7,8,9]
lables:[0,0,1,1,1,1,2,2,0,2]
types:[type1,type2,type1,type2,type2,type1,type2,type2,type1,type1]

G.nodes["type1"].data["class"] = th.tensor(listtype1)
I do not know how to define the listtype1 because I do not know where the nodes are in the listtype1.
The listtype1 should have 10 elements while I only have 5 nodes of type1.

**Comment by VoVAllen** [comment]
Hi,

You can first construct a homogenous DGLGraph by `dgl.graph`. And then use dgl's `dgl.to_heterogenous` https://docs.dgl.ai/generated/dgl.to_heterogeneous.html?highlight=to_hetero#dgl.to_heterogeneous to convert it into a heterograph you want
