### ISSUE TITLE
DGL does not yet support setting edge weights on heterographs, right?

### ISSUE THREAD

**Issue by Kitten-Rec** [dmlc/dgl#3125]
## ❓ Questions and Help

Before proceeding, please note that we recommend
using our discussion forum (https://discuss.dgl.ai) for
general questions. As a result, this issue will
likely be CLOSED shortly.

**Comment by VoVAllen** [comment]
We do support edge weight on heterograph

**Comment by VoVAllen** [comment]
You can follow the doc at https://docs.dgl.ai/guide/graph-heterogeneous.html

For example,
```python
g = dgl.heterograph({
   ('drug', 'interacts', 'drug'): (th.tensor([0, 1]), th.tensor([1, 2])),
   ('drug', 'treats', 'disease'): (th.tensor([1]), th.tensor([2]))})
g.nodes['drug'].data['hv'] = th.zeros(3, 1)
g.nodes['disease'].data['hv'] = th.ones(3, 1)
g.edges['interacts'].data['he'] = th.zeros(2, 1)
g.edges['treats'].data['he'] = th.zeros(1, 2)

```
