### ISSUE TITLE
DGL support  Graph Inited with weighted egde，but dgl.sampling.randomwalk do not support weighted random work, right?

### ISSUE THREAD

**Issue by 634671436** [dmlc/dgl#3127]
## ❓ Questions and Help

Before proceeding, please note that we recommend
using our discussion forum (https://discuss.dgl.ai) for
general questions. As a result, this issue will
likely be CLOSED shortly.

**Comment by 634671436** [comment]
Does graph support weighted random walk? How to do that, thx

**Comment by BarclayII** [comment]
It does.  See https://docs.dgl.ai/generated/dgl.sampling.random_walk.html.
