### ISSUE TITLE
HGT | Using different input feature sizes for different node types

### ISSUE THREAD

**Issue by egealpay** [dmlc/dgl#3129]
I was able to run the example code for HGT, however I have a question to ask. In that example, there are 3 node types ('author', 'paper', 'subject'). During the initialization of input features, I saw that all 3 node types have the same input feature size. Is it possible to assign different input feature sizes for different node types? For example, 'paper' node type with input feature size of 256 and 'author' node type with input feature size of 64?

**Comment by BarclayII** [comment]
HGT does not work with node types with different feature sizes.  You could try projecting the features to the same dimension with a Linear layer though.

**Comment by fmellomascarenhas** [comment]
@egealpay, you could add a linear layer in the beginning to convert each node to the same feat size.
