### ISSUE TITLE
descriptor 'handle' for 'FunctionBase' objects doesn't apply to 'Function' object

### ISSUE THREAD

**Issue by hurun** [dmlc/dgl#314]
## To Reproduce

1.RUN 1_gcn.py

## Environment

 - DGL Version (e.g., 1.0): 0.1.3
 - Backend Library & Version (e.g., PyTorch 0.4.1, MXNet/Gluon 1.3): pytorch 1.0
 - OS (e.g., Linux):windows 10
 - How you installed DGL (`conda`, `pip`, source): conda
 - Build command you used (if compiling from source):
 - Python version:3.7
 - CUDA/cuDNN version (if applicable):9.0
 - GPU models and configuration (e.g. V100):
 - Any other relevant information:

## Additional context

Net(
  (gcn1): GCN(
    (apply_mod): NodeApplyModule(
      (linear): Linear(in_features=1433, out_features=16, bias=True)
    )
  )
  (gcn2): GCN(
    (apply_mod): NodeApplyModule(
      (linear): Linear(in_features=16, out_features=7, bias=True)
    )
  )
)
Traceback (most recent call last):

  File "<ipython-input-4-78564ae8b894>", line 1, in <module>
    runfile('D:/下载/1_gcn.py', wdir='D:/下载')

  File "D:\Anaconda3\lib\site-packages\spyder_kernels\customize\spydercustomize.py", line 668, in runfile
    execfile(filename, namespace)

  File "D:\Anaconda3\lib\site-packages\spyder_kernels\customize\spydercustomize.py", line 108, in execfile
    exec(compile(f.read(), filename, 'exec'), namespace)

  File "D:/下载/1_gcn.py", line 117, in <module>
    g, features, labels, mask = load_cora_data()

  File "D:/下载/1_gcn.py", line 109, in load_cora_data
    g = DGLGraph(data.graph)

  File "D:\Anaconda3\lib\site-packages\dgl\graph.py", line 181, in __init__
    self._graph = create_graph_index(graph_data, multigraph, readonly)

  File "D:\Anaconda3\lib\site-packages\dgl\graph_index.py", line 898, in create_graph_index
    handle = _CAPI_DGLGraphCreate(multigraph)

  File "D:\Anaconda3\lib\site-packages\dgl\_ffi\_ctypes\function.py", line 174, in __call__
    self.handle, values, tcodes, ctypes.c_int(num_args),

TypeError: descriptor 'handle' for 'FunctionBase' objects doesn't apply to 'Function' object

**Comment by BarclayII** [comment]
The error suggests that somehow the attribute `handle` in the `FunctionBase` class didn't show up in the `Function` class, which is a subclass of `FunctionBase`.  Weird...

Could you run the following three lines in Python interactive console (or IPython/Spyder/other equivalents) and paste the output if it doesn't match mine?

```python
In [1]: import dgl

In [2]: dgl.graph_index._CAPI_DGLGraphCreate
Out[2]: <dgl._ffi.function.Function at 0x220598b1948>

In [3]: type(dgl.graph_index._CAPI_DGLGraphCreate).__mro__
Out[3]: (dgl._ffi.function.Function, dgl._ffi._ctypes.function.FunctionBase, object)
```

**Comment by hurun** [comment]
> The error suggests that somehow the attribute `handle` in the `FunctionBase` class didn't show up in the `Function` class, which is a subclass of `FunctionBase`. Weird...
> 
> Could you run the following three lines in Python interactive console (or IPython/Spyder/other equivalents) and paste the output if it doesn't match mine (the hex-address doesn't matter)?
> 
> ```python
> In [1]: import dgl
> 
> In [2]: dgl.graph_index._CAPI_DGLGraphCreate
> Out[2]: <dgl._ffi.function.Function at 0x220598b1948>
> 
> In [3]: type(dgl.graph_index._CAPI_DGLGraphCreate).__mro__
> Out[3]: (dgl._ffi.function.Function, dgl._ffi._ctypes.function.FunctionBase, object)
> ```



> The error suggests that somehow the attribute `handle` in the `FunctionBase` class didn't show up in the `Function` class, which is a subclass of `FunctionBase`. Weird...
> 
> Could you run the following three lines in Python interactive console (or IPython/Spyder/other equivalents) and paste the output if it doesn't match mine (the hex-address doesn't matter)?
> 
> ```python
> In [1]: import dgl
> 
> In [2]: dgl.graph_index._CAPI_DGLGraphCreate
> Out[2]: <dgl._ffi.function.Function at 0x220598b1948>
> 
> In [3]: type(dgl.graph_index._CAPI_DGLGraphCreate).__mro__
> Out[3]: (dgl._ffi.function.Function, dgl._ffi._ctypes.function.FunctionBase, object)
> ```

dgl.graph_index._CAPI_DGLGraphCreate
Traceback (most recent call last):

  File "<ipython-input-6-92b5a302a318>", line 1, in <module>
    dgl.graph_index._CAPI_DGLGraphCreate

AttributeError: module 'dgl' has no attribute 'graph_index'

**Comment by BarclayII** [comment]
Can you try importing dgl.graph_index between 1 and 2?

**Comment by hurun** [comment]
somethings happend misterry, i don't know why.
if use this command line, it was error.

import dgl.graph_index

dgl.graph_index._CAPI_DGLGraphCreate

Traceback (most recent call last):

  File "<ipython-input-10-92b5a302a318>", line 1, in <module>
    dgl.graph_index._CAPI_DGLGraphCreate

AttributeError: module 'dgl' has no attribute 'graph_index'

-----------------------------------------------------------------
but if use this, it was okay and can get _mro_
import dgl.graph_index as dglindex

dglindex._CAPI_DGLGraphCreate
Out[14]: <dgl._ffi.function.Function at 0x171810f0dc8>

type(dglindex._CAPI_DGLGraphCreate).__mro__
Out[16]: (dgl._ffi.function.Function, dgl._ffi._ctypes.function.FunctionBase, object)

**Comment by hurun** [comment]
it's sorry, restarting ipython, it works well.
