### ISSUE TITLE
hilander: the share data subcenter_arcface_deepglint_train_1_in_10_recreated.pkl

### ISSUE THREAD

**Issue by youmingdeng** [dmlc/dgl#3142]
## ❓ Questions and Help
it seems that the labels in subcenter_arcface_deepglint_train_1_in_10_recreated.pkl not right, because it has 128914 categories.
In the paper, Table 6 describe the number of category is 18084
Before proceeding, please note that we recommend
using our discussion forum (https://discuss.dgl.ai) for
general questions. As a result, this issue will
likely be CLOSED shortly.

**Comment by hetong007** [comment]
Thanks for the catch. We are working on the update of the data and codebase, will ping here once the PR is available.

**Comment by hetong007** [comment]
The dataset has been updated in all three hostings, please re-download and try again, thanks!
