### ISSUE TITLE
About edge_subgraph API in pinsage example

### ISSUE THREAD

**Issue by fishmingyu** [dmlc/dgl#3151]
It seems that pinsage in examples/pytorch still uses the old version of edge_subgraph API. The link below shows that the code implements ```relabel_nodes=False```, which should be replaced by ```preserve_nodes=True``` instead.
https://github.com/dmlc/dgl/blob/34426a98e9ecc9f4b90d2b29ea243e095e9eb19e/examples/pytorch/pinsage/data_utils.py#L34

**Comment by mufeili** [comment]
It's actually the other way. We will replace `preserve_nodes` by `relabel_nodes` in 0.7. Currently you can either install the nightly-built version of DGL or clone the [0.6.x branch](https://github.com/dmlc/dgl/tree/0.6.x).
