### ISSUE TITLE
Directly manipulating adjacency matrix of dgl graph

### ISSUE THREAD

**Issue by ziqiaomeng** [dmlc/dgl#3156]
## 🚀 Feature

Could directly assign new adjacent matrix to DGL graph and directly manipulate on adjacent matrix entries. 

## Motivation

Currently I want to add some noises to adjacent matrix of DGL graph, which will also involve add or remove edges. 

## Alternatives

I currently need to store additional adjacency matrix as feature and need to make the original graph fully connected. 

## Pitch

Something like dglgraph.adj = new_adj and dglgraph.adj[0,4] = 1

## Additional context
No

**Comment by VoVAllen** [comment]
Can you create a new graph each time when you want to modify it?

**Comment by ziqiaomeng** [comment]
> Can you create a new graph each time when you want to modify it?

This is also an alternative solution. But not that convenient. For example, if an edge is added, for reconstructing graphs I need to add that edge to the edge list. However, in order to specify which edge I am going to add, I still need to manipulate (add noise) on the complete edge list. Is this the case?

**Comment by BarclayII** [comment]
That depends on how you define your noise.

For instance, if your noise is a sparse Bernoulli mask then you can use `dgl.add_edges` and `dgl.remove_edges`.  If your noise is a dense Gaussian then a fully-connected graph is the best option.
