### ISSUE TITLE
(Distributed) Allow passing username for ssh commands in tools/launch.py

### ISSUE THREAD

**Issue by erickim555** [dmlc/dgl#3159]
## 🚀 Feature
Optionally add a desired username for the ssh commands used by `tools/launch.py`

## Motivation

Context: `tools/launch.py` is the tool that DGL uses to launch distributed (multi-machine) graph training jobs. It primarily communicates to other machines in the cluster via ssh commands, eg:
```
cmd = 'ssh -o StrictHostKeyChecking=no -p ' + str(port) + ' ' + ip + ' \'' + cmd + '\''
```

Sometimes -- as is it the case at my environment+infra -- root-level ssh access isn't possible for security/permission reasons. Thus, it would instead be desirable to optionally pass the username to these `ssh` commands, eg something like:
```
# without passing in a username, I get permission denied errors
ssh -o StrictHostKeyChecking=no -p 20 1.2.3.4 ...

# but passing in the username, the connection is successful!
ssh -o StrictHostKeyChecking=no -p 20 some_user@1.2.3.4 ...
```

In terms of implementation: this would be an opt-in feature, and will default to passing in no "user@" prefix. On our infrastructure, I've implemented this functionality and verified that it works. 
For illustration, the new parser argument would be:
```
+    parser.add_argument(
+        "--ssh_username", default="",
+        help="Optional. When issuing commands (via ssh) to cluster, use the provided username in the ssh cmd. "
+             "Example: If you provide --ssh_username=bob, then the ssh command will be like: 'ssh bob@1.2.3.4 CMD' "
+             "instead of 'ssh 1.2.3.4 CMD'"
+    )
```

## Alternatives
I can't think of any.

## Pitch
By implementing this feature request, DistDGL will work in environments where root-level SSH access is not permitted due to security reasons.

## Additional context
I have implemented + tested this functionality, I'll put together a pull request shortly.

**Comment by VoVAllen** [comment]
Thanks! Also I did this(set username) through ssh config(`~/.ssh/config`) file on my machine. Therefore we didn't have this function previously

**Comment by erickim555** [comment]
Fixed by: https://github.com/dmlc/dgl/pull/3202
