### ISSUE TITLE
(Distributed) Allow multi-command udf_command to work in `tools/launch.py`

### ISSUE THREAD

**Issue by erickim555** [dmlc/dgl#3160]
## 🚀 Feature
Upgrade `tools/launch.py` to correctly handle multi-command `udf_command`, aka "chained" commands.

## Motivation
Context: in `tools/launch.py`, a `udf_command` is a unix command that the DistDGL tooling will execute on your cluster of machines. 
As a concrete example, for distributed GraphSage training, the `udf_command` would be a python command that launches the trainer on a given cluster host:

```
# from: https://github.com/dmlc/dgl/tree/d7390763f0b04d458f2d0edd66ec66620d4da1f5/examples/pytorch/graphsage/experimental
# here, "python3 train_dist.py ..." is the udf_command, which kicks off the trainer
python3 ~/workspace/dgl/tools/launch.py \
--workspace ~/workspace/dgl/examples/pytorch/graphsage/experimental/ \
--num_trainers 1 \
--num_samplers 0 \
--num_servers 1 \
--part_config data/ogb-product.json \
--ip_config ip_config.txt \
"python3 train_dist.py --graph_name ogb-product --ip_config ip_config.txt --num_epochs 30 --batch_size 1000"
```

The Problem: currently, `tools/launch.py` can only handle a `udf_command` that consists of exactly a single command, specifically just a single `python FILE` call. For instance, the following would fail:
```
# chaining together pwd does not work
python3 ~/workspace/dgl/tools/launch.py \
--workspace ~/workspace/dgl/examples/pytorch/graphsage/experimental/ \
...
"pwd; python3 train_dist.py --graph_name ogb-product --ip_config ip_config.txt --num_epochs 30 --batch_size 1000"

# chaining via && does not work either
python3 ~/workspace/dgl/tools/launch.py \
--workspace ~/workspace/dgl/examples/pytorch/graphsage/experimental/ \
...
"pwd && python3 train_dist.py --graph_name ogb-product --ip_config ip_config.txt --num_epochs 30 --batch_size 1000"
```
In my use case, I have to run several commands prior to running the final `python launch_my_trainer.py` command. But, the following would fail with very mysterious and difficult-to-diagnose errors due to the mis-setting of DGL env-vars on the cluster hosts:
```
python3 ~/workspace/dgl/tools/launch.py \
--workspace ~/workspace/dgl/examples/pytorch/graphsage/experimental/ \
...
"cd SOME_DIR && do_some_thing && python3 train_dist.py --graph_name ogb-product --ip_config ip_config.txt --num_epochs 30 --batch_size 1000"
```
Specifically: the client/server processes would be started up on each host with the wrong env-vars, causing DistDGL to fail in subtle and exciting ways. For an explanation of what's going on behind the scenes causing this bug, see the "Additional Context" section below.

## Alternatives
A workaround would be to express a "chained" udf_command inside of a single Python script. This would require no `tools/launch.py` code changes, which is a plus.
If we decide that this is the "right, preferred" way of doing things, then we should make this more explicit, either in documentation or via checks in the `tools/launch.py` itself. For instance, if we really want DGL users to only do something like `python SOME_FILE.py ARGS`, then rather than passing in a general unix command in `udf_command`, we should have users just pass `SOME_FILE.py ARGS`.

## Pitch
Support "chained" `udf_command` in `tools/launch.py`.
OR: commit to a specific interface, and refactor `tools/launch.py` to explicitly only allow passing in the python file to run, vs allowing arbitrary shell commands that can fail in a subtle, hard-to-debug way.

## Additional context

Fortunately, there's nothing fundamentally preventing `tools/launch.py` from supporting "chained" (or multi-command) `udf_command`'s. The reason that it doesn't work today is due to how unix handles env-vars. 
Recall that DGL sets env-vars that are required for the DGL client/server processes to function correctly, like `DGL_ROLE=[client,server]`. The command that `tools/launch.py` runs on each host is something like:
```
cmd = "DGL_ROLE={dgl_role} <other DGL env-vars> {udf_command}".format(
    dgl_role="server",
    ...
    udf_command="python train_dist.py ..."
)
execute_remote(cmd, ip, ...)  # remotely run cmd on host `ip` via SSH access
```
An example looks like:
```
DGL_ROLE=server python train_dist.py
```
However, if `udf_command` is a "chained" command, it then looks like:
```
DGL_ROLE=server pwd && python train_dist.py
```
Crucially, the DGL env-vars `DGL_ROLE` is ONLY APPLIED to the first command (`pwd`), and NOT the subsequent `python train_dist.py` call which actually needs the DGL env-vars to function correctly.

To illustrate why chained commands are interfering with DGL's attempts to set env-vars, see the following:
```
# as expected, the SOME_VAR env-var is correctly visible
$ SOME_VAR=42 python -c "import os; print(os.getenv('SOME_VAR', 'not set'))"
42

# here, SOME_VAR is only applied to `pwd`, oops
$ SOME_VAR=42 pwd; python -c "import os; print(os.getenv('SOME_VAR', 'not set'))"
/Users/erickim
not set

# similarly, chaining via && does not work either
$ SOME_VAR=42 pwd && python -c "import os; print(os.getenv('SOME_VAR', 'not set'))"
/Users/erickim
not set

# what does work is: export the env-var, and now it's visible to all commands within the chain
# Note: Enclosing the `export` within parenthesis prevents SOME_VAR from polluting the global env.
#     Hence, why the second "echo $SOME_VAR" doesn't output 42.
(pinboard_py3) ~ $ (export SOME_VAR=42 pwd && python -c "import os; print(os.getenv('SOME_VAR', 'not set'))")
42
(pinboard_py3) ~ $ echo $SOME_VAR

# On the other hand, if I don't enclose in parenthesis, then SOME_VAR pollutes the global env, 
# which isn't desirable:
(pinboard_py3) ~ $ export SOME_VAR=42 pwd && python -c "import os; print(os.getenv('SOME_VAR', 'not set'))"
42
(pinboard_py3) ~ $ echo $SOME_VAR
42
```

**Comment by VoVAllen** [comment]
Hi,

I'm actually walking on a kubernetes solution for distributed training, which makes the command more flexible but need k8s infrastructure. Do you/your company has k8s to run the distributed training tasks?

**Comment by erickim555** [comment]
Hi @VoVAllen , our company does happen to have k8s, so a DistDGL + K8s integration would be nice!
