### ISSUE TITLE
(Distributed) tools/launch.py does not support udf_command with `python3.x`

### ISSUE THREAD

**Issue by erickim555** [dmlc/dgl#3161]
## 🐛 Bug
`tools/launch.py` will incorrectly mangle a udf_command like: `python3.7 train_dist.py`
This is because, in the `tools/launch.py` code, it does a blind string replace for a substring like "python3" and replaces it with "python3 " (note the space):
```
# https://github.com/dmlc/dgl/blob/d7390763f0b04d458f2d0edd66ec66620d4da1f5/tools/launch.py#L201
new_torch_cmd = torch_cmd.replace('node_rank=0', 'node_rank='+str(node_id))
if 'python3' in udf_command:
    new_udf_command = udf_command.replace('python3', 'python3 ' + new_torch_cmd)
elif 'python2' in udf_command:
    new_udf_command = udf_command.replace('python2', 'python2 ' + new_torch_cmd)
else:
    new_udf_command = udf_command.replace('python', 'python ' + new_torch_cmd)
cmd = client_cmd + ' ' + new_udf_command
cmd = 'cd ' + str(args.workspace) + '; ' + cmd
execute_remote(cmd, ip, args.ssh_port, thread_list)
```
Thus, my `cmd` looks something like: `python3 .7 train_dist.py` (note the errant space between 3 and .7), which predictably causes errors.
This completely breaks `tools/launch.py` on infra that uses Python interpreters other than `python2`, `python3`, or `python`, eg: `python3.7, python3.8`, etc.

## To Reproduce

1. on a host where `python3.7` is the python interpreter with the required libs (eg pytorch), do:
```
python3.7 ~/workspace/dgl/tools/launch.py \
--workspace ~/workspace/dgl/examples/pytorch/graphsage/experimental/ \
--num_trainers 1 \
--num_samplers 0 \
--num_servers 1 \
--part_config data/ogb-product.json \
--ip_config ip_config.txt \
"python3.7 train_dist.py --graph_name ogb-product --ip_config ip_config.txt --num_epochs 30 --batch_size 1000"
```
You'll get errors as each host attempts to run `python3 .7 train_dist.py`, eg something like "File not found: .7"

## Expected behavior
The hosts should correctly run `python3.7 train_dist.py`

## Environment

 - DGL Version (e.g., 1.0): 0.6.1, but I see that even on master this bug still exists.
 - Backend Library & Version (e.g., PyTorch 0.4.1, MXNet/Gluon 1.3):
 - OS (e.g., Linux): Linux
 - How you installed DGL (`conda`, `pip`, source): pip
 - Build command you used (if compiling from source):
 - Python version: 3.7
 - CUDA/cuDNN version (if applicable):
 - GPU models and configuration (e.g. V100):
 - Any other relevant information:

## Additional context
The fix could be straightforward + short, but I'd be curious what the context is for the python string replace, as there could be a good reason for it being in there.

**Comment by VoVAllen** [comment]
There's no good reason to do that. It's just we don't have multiple python version on the target machine yet. Sorry for the inconvenience and any patch is welcomed!
