### ISSUE TITLE
why here not wait until set successful ?

### ISSUE THREAD

**Issue by lixusign** [dmlc/dgl#3164]
https://github.com/dmlc/dgl/blob/d1cc096956fb8b829479657f5cfc2ec982144d75/python/dgl/nn/pytorch/sparse_emb.py#L128

why not wait ? 

self._store.wait([XXXXXXXX])

**Comment by classicsong** [comment]
For torch.distributed.Store.get(), if key is not present in the store, the function will wait for timeout.

**Comment by lixusign** [comment]
thx
