### ISSUE TITLE
getting Expect number of features to match number of nodes (len(u)) 

### ISSUE THREAD

**Issue by ankit-garg** [dmlc/dgl#3165]
receiving when I am dividing a big graph into 2 sub graphs via parMetis and running convert_partition.py to covert it into .dgl graph.

Error logs for the same

Traceback (most recent call last):
  File "convert_partition.py", line 182, in <module>
    compact_g.ndata['orig_id'] = th.as_tensor(per_type_ids)
  File "/home/ubuntu/.local/lib/python3.8/site-packages/dgl/view.py", line 81, in __setitem__
    self._graph._set_n_repr(self._ntid, self._nodes, {key : val})
  File "/home/ubuntu/.local/lib/python3.8/site-packages/dgl/heterograph.py", line 3992, in _set_n_repr
    raise DGLError('Expect number of features to match number of nodes (len(u)).'
dgl._ffi.base.DGLError: Expect number of features to match number of nodes (len(u)). Got 18612081 and 18612080 instead.

**Comment by jermainewang** [comment]
Hi, thanks for reporting the bug. We also found that ParMetis may accidentally drop some nodes or edges after partitioning. We are in the process of investigation.

**Comment by VoVAllen** [comment]
Is this fixed by https://github.com/dmlc/dgl/pull/3137?
