### ISSUE TITLE
The default canonical_etypes of dgl.graph() and dgl.DGLGraph() should be the same

### ISSUE THREAD

**Issue by e-yi** [dmlc/dgl#3168]
The default `canonical_etypes` of dgl.graph and dgl.DGLGraph are different, and I think this is not a desirable behavior. Or could someone explain to me the reason for using different `canonical_etypes` here? 

```python
print(dgl.graph(([],[])).canonical_etypes)  # [('_N', '_E', '_N')]
print(dgl.DGLGraph().canonical_etypes)  # [('_U', '_V', '_U')]
```

**Comment by Rhett-Ying** [comment]
fix has been merged into dgl/master. pls take a look.

**Comment by e-yi** [comment]
> fix has been merged into dgl/master. pls take a look.

Good job, Rhett. 

I thought about submitting a PR myself, but `_N` `_U` are somewhat confusing and I did not know if I can just replace one with another.
