### ISSUE TITLE
ImportError: DLL load failed: The specified module could not be found.

### ISSUE THREAD

**Issue by alanlisten** [dmlc/dgl#317]
## To Reproduce

1.
1.
1.

## Environment

 - DGL Version (e.g., 1.0):  dgl-0.1.3:
 - Backend Library & Version (e.g., PyTorch 0.4.1, MXNet/Gluon 1.3):PyTorch 1.0
 - OS (e.g., Linux): Windows10
 - How you installed DGL (`conda`, `pip`, source): pip
 - Build command you used (if compiling from source):
 - Python version: 3.6
 - CUDA/cuDNN version (if applicable): cpu
 - GPU models and configuration (e.g. V100):
 - Any other relevant information:

**Comment by VoVAllen** [comment]
Can you take a look on [this](https://github.com/dmlc/dgl/issues/293)? Is this the same problem as yours?

**Comment by alanlisten** [comment]
> Can you take a look on [this](https://github.com/dmlc/dgl/issues/293)? Is this the same problem as yours?

Thank you for your reply, but I still have not solved the problem. I use Anaconda.

**Comment by BarclayII** [comment]
Duplicate of #293
