### ISSUE TITLE
DGLError: [20:50:35] C:\Users\Administrator\dgl-0.5\third_party\dmlc-core\src\io\local_filesys.cc:209: Check failed: allow_null:  LocalFileSystem::Open "./data2": Permission denied

### ISSUE THREAD

**Issue by cwer191** [dmlc/dgl#3173]
I can't deal with this problem. It's on win10.

**Comment by VoVAllen** [comment]
Could you try other path?

**Comment by cwer191** [comment]
I've tried to modify the install path to other disk, but it seems that it just make no sense. The file is still in the same place. This is my command "pip install dgl-cu111 -f https://data.dgl.ai/wheels/repo.html --user", and the error is the same.

**Comment by cwer191** [comment]
> Could you try other path?

I've tried to modify the install path to other disk, but it seems that it just make no sense. The file is still in the same place. This is my command "pip install dgl-cu111 -f https://data.dgl.ai/wheels/repo.html --user", and the error is the same.

**Comment by VoVAllen** [comment]
Could you try save to the full path with permission such as "D:\\data2"? And is there any anti virus software on your machine?

**Comment by cwer191** [comment]
> Could you try save to the full path with permission such as "D:\data2"? And is there any anti virus software on your machine?

It still doesn't work. I don't install any anti virus software on my machine at all

**Comment by VoVAllen** [comment]
Could you provide the full traceback? Is this happening in `save_graphs`?

**Comment by VoVAllen** [comment]
It's weird. It works on my machine. I think it's still the permission problem on your machine

**Comment by cwer191** [comment]
> It's weird. It works on my machine. I think it's still the permission problem on your machine

Traceback (most recent call last):

  File "I:\chatter on DGL.py", line 79, in <module>
    main()

  File "I:\chatter on DGL.py", line 59, in main
    dataset = load_data()

  File "I:\chatter on DGL.py", line 25, in load_data
    dataset = load_graphs("D:\data2")

  File "I:\anaconda3\envs\torch\lib\dgl\data\graph_serialize.py", line 175, in load_graphs
    version = _CAPI_GetFileVersion(filename)

  File "I:\anaconda3\envs\torch\lib\dgl\_ffi\_ctypes\function.py", line 188, in __call__
    check_call(_LIB.DGLFuncCall(

  File "I:\anaconda3\envs\torch\lib\dgl\_ffi\base.py", line 64, in check_call
    raise DGLError(py_str(_LIB.DGLGetLastError()))

DGLError: [15:46:43] C:\Users\Administrator\dgl-0.5\third_party\dmlc-core\src\io\local_filesys.cc:209: Check failed: allow_null:  LocalFileSystem::Open "D:\data2": Permission denied

**Comment by cwer191** [comment]
well, when I test the torchvision.datasets.ImageFolder, it works. This problem makes me confused.

**Comment by cwer191** [comment]
I also tried to run Spyder as administrator, but the load_graphs() still didn't work.

**Comment by VoVAllen** [comment]
How did you save the graph? Where did this file come from?

**Comment by VoVAllen** [comment]
Can you try
```python
import dgl
g = dgl.graph([(0,1)])
dgl.save_graphs("D:\\data2", g)
print(dgl.load_graphs("D:\\data2"))
```
to see whether it works?

**Comment by cwer191** [comment]
> How did you save the graph? Where did this file come from?

the data2 has two subfolders, each contains a series of graphs belong to one kind, and I named the subfolders as 1 and 2.

**Comment by cwer191** [comment]
> Can you try
> 
> ```python
> import dgl
> g = dgl.graph([(0,1)])
> dgl.save_graphs("D:\\data2", g)
> print(dgl.load_graphs("D:\\data2"))
> ```
> 
> to see whether it works?

I just uninstall the anaconda and try to install it again. I will send you the result later.

**Comment by VoVAllen** [comment]
`dgl.load_graphs` can only load from files, and cannot directly load from a folder

**Comment by cwer191** [comment]
Thank you for your help. I will try. If I meet any problems, I will connect you.
