### ISSUE TITLE
How to know whether a model supports weighted graph?

### ISSUE THREAD

**Issue by ZhangGongjie** [dmlc/dgl#3174]
## ❓ Questions and Help

Before proceeding, please note that we recommend
using our discussion forum (https://discuss.dgl.ai) for
general questions. As a result, this issue will
likely be CLOSED shortly.

**Comment by jermainewang** [comment]
Hi, the model search tool we just created on [dgl.ai](https://www.dgl.ai/) could be helpful. You could search for weight to find the model and the corresponding example implementation.
