### ISSUE TITLE
[Docs] `num_traces` in `dgl.sampling.random_walk`

### ISSUE THREAD

**Issue by Wang-Yu-Qing** [dmlc/dgl#3179]
## 📚 Documentation

This is a API reference part.

In the doc of `dgl.sampling.random_walk`: [page link](https://docs.dgl.ai/generated/dgl.sampling.random_walk.html?highlight=random%20walk#dgl.sampling.random_walk) , it says: `For a single starting node, num_traces traces would be generated`. However, I can't find `num_traces` in the following parameters list nor function explaination and examples. And calling of `dgl.sampling.random_walk(g, nodes, num_traces=n)` will raise an Error: `TypeError: random_walk() got an unexpected keyword argument 'num_traces'`.

**Comment by VoVAllen** [comment]
What's your dgl version? We've justed release 0.7

**Comment by BarclayII** [comment]
Yeah that's a mistake.  We don't use `num_traces` argument any more.  Will fix it.
