### ISSUE TITLE
how to  preprocess and create dataset acm.mat for the model [dgl/examples/pytorch/han/]?

### ISSUE THREAD

**Issue by Kitten-Rec** [dmlc/dgl#3185]
## ❓ Questions and Help

I want to create other datasets  by myself following the data set creation process of acm.mat, but I do not know how to do it. I hope to get your guidance.

**Comment by BarclayII** [comment]
Unfortunately I'm not sure how the dataset is created either.  I took the dataset from [the official repository](https://github.com/Jhy1993/HAN/tree/master/data/acm) so I would recommend you raise the issue in that repository.
