### ISSUE TITLE
Is it a typo in the PR template?

### ISSUE THREAD

**Issue by maqy1995** [dmlc/dgl#3191]
## ❓ Questions and Help

> To the my best knowledge, examples are either not affected by this change,...

**Comment by yzh119** [comment]
I don't think so, it mean:
examples are either "not affected by this change", or "have been fixed to be compatible with this change"

feel free to make it more readable.

**Comment by maqy1995** [comment]
My English is not very good, so I use `Grammarly` to check some common errors. Here `Grammarly` suggests that I should change `To the my best knowledge` to `To my best knowledge, this is the why I submitted this issue.   
`Grammarly` may have made a mistake here.  
Anyway, thank you Zihao for your reply.

**Comment by yzh119** [comment]
Sorry I didn't notice the first sentence, it should be "to the best of my knowledge", would you mind creating a PR fixing that?

**Comment by maqy1995** [comment]
I am glad to fix it, but I noticed that the issue has been fixed.  :joy:
