### ISSUE TITLE
[Distributed Training] Support per edge type sampling for heterogeneous DistGraph 

### ISSUE THREAD

**Issue by classicsong** [dmlc/dgl#3193]
## 🚀 Feature
We need to support per edge type sampling for heterogeneous DistGraph.

- [x] Step 1: Support per edge type sampling for heterogeneous DistGraph.
- [x] Step 2: Optimize the performance of per edge type sampling mechanism.

**Comment by erickim555** [comment]
Is this similar to this issue? https://github.com/dmlc/dgl/issues/3030

**Comment by classicsong** [comment]
Yes. Now with PR#3131, we can sample N neighbors for each relation type of the target node.
