### ISSUE TITLE
Small typo in GAT tutorial

### ISSUE THREAD

**Issue by universvm** [dmlc/dgl#3195]
## 📚 Documentation

Hi there,

there's a small typo in this tutorial page for GAT: https://docs.dgl.ai/en/v0.7.0/tutorials/models/1_gnn/9_gat.html

```
**GAN** uses weighting neighbor features with feature dependent and structure-free normalization, in the style of attention.
```

I think you mean _GAT_.

**Comment by jermainewang** [comment]
Thanks! Would you like to push a patch? :)
