### ISSUE TITLE
LOG(INFO)<<!!!!! where we can get the log of cuda?

### ISSUE THREAD

**Issue by gmfff** [dmlc/dgl#3217]
## ❓ Questions and Help

Before proceeding, please note that we recommend
using our discussion forum (https://discuss.dgl.ai) for
general questions. As a result, this issue will
likely be CLOSED shortly.

**Comment by VoVAllen** [comment]
What's your exact questions?

**Comment by jermainewang** [comment]
Please be more specific and describe the question more clearly. I will close this issue for now.
