### ISSUE TITLE
DGL 0.7 pip release doesn't have the pytorch allocator enabled

### ISSUE THREAD

**Issue by nv-dlasalle** [dmlc/dgl#3220]
## 🐛 Bug

The pytorch allocator is not enabled in the DGL version available from pip. See all of the cudaMalloc and cudaFree calls in the below profile:
![memalloc_0 7](https://user-images.githubusercontent.com/63612878/128244734-4a15eae0-0d02-44b5-8f82-ceccecf2ba58.png)

## To Reproduce

1. `pip install dgl-cu111 -f https://data.dgl.ai/wheels/repo.html`
1. `cd examples/pytorch/graphsage`
1. `nsys profile -o /tmp/graphsage_memalloc -f true --trace=cuda python3 train_sampling_multi_gpu.py --dataset ogbn-products --fan-out 8,8 --num-workers 0 --num-epochs 3 --batch-size=4096 --num-hidden 128`

## Expected behavior

According to discussion on #2652, using the pytorch allocator should be enabled by default in binary versions of DGL.

## Environment

 - DGL Version (e.g., 1.0): 0.7
 - Backend Library & Version (e.g., PyTorch 0.4.1, MXNet/Gluon 1.3): pytorch 1.8.1
 - OS (e.g., Linux): Linux
 - How you installed DGL (`conda`, `pip`, source): pip
 - Build command you used (if compiling from source):
 - Python version: 3.6.9
 - CUDA/cuDNN version (if applicable):
 - GPU models and configuration (e.g. V100): TitanV
 - Any other relevant information:

**Comment by VoVAllen** [comment]
We have a new flag `dgl._ffi.base.tensor_adapter_loaded` to indicate the torch allocator. Could you check that?

**Comment by VoVAllen** [comment]
My dgl(`pip install dgl-cu111 -f https://data.dgl.ai/wheels/repo.html`) works well with pytorch 1.8.1+cu11.

**Comment by nv-dlasalle** [comment]
`dgl._ffi.base.tensor_adapter_loaded` shows that it's not loaded for me.

I've done more digging, and it looks to be an issue with the cuda version. I have 11.2 and 11.3 on these machines, and when I output the errors from `dlopen()`, I'm seeing `libnvrtc.so.11.1: cannot open shared object file: No such file or directory`, but I don't think the tensoradapater shared library needs to depend on that.
