### ISSUE TITLE
A small question on the Cora dataset.

### ISSUE THREAD

**Issue by Ononoki-Yotsugi** [dmlc/dgl#3222]
Hi! I am trying to reproduce a paper using dgl. 
I notice that the order of nodes and the split in *CoraGraphDataset* is different from the original gcn setting. After carefully looking into it, I find the files *CoraGraphDataset* uses have a 'v2', which is different from the original setting. 
How is this going？Dose it mean that if I want to use the original order and split, I have to give up the API dgl provides?

**Comment by Orion-wyc** [comment]
> Dose it mean that if I want to use the original order and split, I have to give up the API dgl provides?

Writing a new class for the dataset (e.g. [cora](https://github.com/dragen1860/GCN-PyTorch/tree/master/data)) you are going to use is  feasible, and this keeps the original API unchanged. 

The process function [CODE1](https://github.com/dmlc/dgl/blob/8b5f4f5b1c470db5ab969de9bbba2b3a53558178/python/dgl/data/citation_graph.py#L74) is similar to [CODE2](https://github.com/dragen1860/GCN-PyTorch/blob/623aa67f0d1c3384fe56f3a20e14e2c13845bcd9/data.py#L28).

```python
def load_data(dataset_str):
    """
    Loads input data from gcn/data directory
    ind.dataset_str.x => the feature vectors of the training instances as scipy.sparse.csr.csr_matrix object;
    ind.dataset_str.tx => the feature vectors of the test instances as scipy.sparse.csr.csr_matrix object;
    ind.dataset_str.allx => the feature vectors of both labeled and unlabeled training instances
        (a superset of ind.dataset_str.x) as scipy.sparse.csr.csr_matrix object;
    ind.dataset_str.y => the one-hot labels of the labeled training instances as numpy.ndarray object;
    ind.dataset_str.ty => the one-hot labels of the test instances as numpy.ndarray object;
    ind.dataset_str.ally => the labels for instances in ind.dataset_str.allx as numpy.ndarray object;
    ind.dataset_str.graph => a dict in the format {index: [index_of_neighbor_nodes]} as collections.defaultdict
        object;
    ind.dataset_str.test.index => the indices of test instances in graph, for the inductive setting as list object.
```

**Comment by Ononoki-Yotsugi** [comment]
Thanks.

**Comment by mufeili** [comment]
Hi @Ononoki-Yotsugi , the split should be the same as the one used in the original GCN paper. The reason we used `v2` is because `v1` was not the original version. See [this PR](https://github.com/dmlc/dgl/pull/1583). Can you tell me how did verify the node order and split consistencies?
