### ISSUE TITLE
Confused about how to use edata in edge dataloader

### ISSUE THREAD

**Issue by jinzijian** [dmlc/dgl#3223]
I want to train  a link predict task in a large graph with  mini batch
![image](https://user-images.githubusercontent.com/22198334/128452728-ccca44a7-2653-4f71-b136-b6073b9ced25.png)

I see we can assign srcdata as ndata
But how can I use the edge data data in the blocks

**Comment by jinzijian** [comment]
and I really confused about src and dst in  blocks
and what blocks really mean;
I think it is a list of subgraphs maybe? 
![image](https://user-images.githubusercontent.com/22198334/128471845-dc947548-1cbb-401e-9dc9-53691c712c5c.png)
why must do this?

**Comment by jermainewang** [comment]
@jinzijian Does the figure and animation [here](https://docs.dgl.ai/tutorials/large/L0_neighbor_sampling_overview.html#sphx-glr-tutorials-large-l0-neighbor-sampling-overview-py) help you understand the concept?

**Comment by jinzijian** [comment]
> @jinzijian Does the figure and animation [here](https://docs.dgl.ai/tutorials/large/L0_neighbor_sampling_overview.html#sphx-glr-tutorials-large-l0-neighbor-sampling-overview-py) help you understand the concept?

I see that but I do not understand how to give those input edges edata features?

**Comment by jinzijian** [comment]
@jermainewang 
Hi, I am still confused about the srcdata and dstdata.
Does edge data like data have the same API in MSF?

**Comment by BarclayII** [comment]
If you want to assign or get edge data of a block (MFG) you can use `block.edata[name]` as usual.

Basically a block (MFG) is a bipartite graph constructed by putting the nodes to be computed on a layer on one side, and the nodes needed to compute the outputs on the other, like in [this figure](https://docs.dgl.ai/tutorials/large/L0_neighbor_sampling_overview.html#sphx-glr-tutorials-large-l0-neighbor-sampling-overview-py).  That is why you need to pass in a pair to the `SAGEConv` layer with the features on both sides.

**Comment by jinzijian** [comment]
@BarclayIl Thanks a lot. I got it.
