### ISSUE TITLE
Diffpool model do not consider the loss of first diffpooling layer

### ISSUE THREAD

**Issue by yinpeiqi** [dmlc/dgl#3229]
## ❓ Questions and Help

In dgl/examples/pytorch/diffpool/model/encoder.py:

line 210:     def loss(self, pred, label):

This function compute the Entropyloss and linkpredloss for diffpoolinglayers. However, the firstdiffpoolinglayer is not consider yet cause it is not include in self.diffpoollayers. 

Before proceeding, please note that we recommend
using our discussion forum (https://discuss.dgl.ai) for
general questions. As a result, this issue will
likely be CLOSED shortly.

**Comment by VoVAllen** [comment]
You are right. Would you mind submit a PR to include the first diffpool layer?

**Comment by yinpeiqi** [comment]
Sure. I have submitted the PR #3233. 
By the way, I was a bit skeptical about the correctness of batch2tensor in dgl/examples/pytorch/diffpool/model/model_utils.py. If node_per_pool_graph is fixed, some information of adj is lost. If this place is a mistake?
