### ISSUE TITLE
RAM keeps increasing for every epoch when increasing number of edges and features

### ISSUE THREAD

**Issue by afdezt** [dmlc/dgl#3230]
## 🐛 Bug

When increasing the number of edges and features of a heterogenous graph, ram memory (CPU) keeps increasing in each epoch. 

## To Reproduce
For instance, let's take the example from the 5.1 section (Node Classification). When changing the number of _n_follows_ and _n_clicks_ to 500,000 and _n_hetero_features_ to 128, the RAM usage increases after each epoch:
```
import numpy as np
import torch
import dgl
import dgl.nn as dglnn
import torch.nn as nn
import torch.nn.functional as F

n_users = 1000
n_items = 500
n_follows = 500000 # Originally 3000
n_clicks = 500000 # Originally 5000
n_dislikes = 500
n_hetero_features = 128 # Originally 10
n_user_classes = 5
n_max_clicks = 10

follow_src = np.random.randint(0, n_users, n_follows)
follow_dst = np.random.randint(0, n_users, n_follows)
click_src = np.random.randint(0, n_users, n_clicks)
click_dst = np.random.randint(0, n_items, n_clicks)
dislike_src = np.random.randint(0, n_users, n_dislikes)
dislike_dst = np.random.randint(0, n_items, n_dislikes)

hetero_graph = dgl.heterograph({
    ('user', 'follow', 'user'): (follow_src, follow_dst),
    ('user', 'followed-by', 'user'): (follow_dst, follow_src),
    ('user', 'click', 'item'): (click_src, click_dst),
    ('item', 'clicked-by', 'user'): (click_dst, click_src),
    ('user', 'dislike', 'item'): (dislike_src, dislike_dst),
    ('item', 'disliked-by', 'user'): (dislike_dst, dislike_src)})

hetero_graph.nodes['user'].data['feature'] = torch.randn(n_users, n_hetero_features)
hetero_graph.nodes['item'].data['feature'] = torch.randn(n_items, n_hetero_features)
hetero_graph.nodes['user'].data['label'] = torch.randint(0, n_user_classes, (n_users,))
hetero_graph.edges['click'].data['label'] = torch.randint(1, n_max_clicks, (n_clicks,)).float()

# randomly generate training masks on user nodes and click edges
hetero_graph.nodes['user'].data['train_mask'] = torch.zeros(n_users, dtype=torch.bool).bernoulli(0.6)
hetero_graph.edges['click'].data['train_mask'] = torch.zeros(n_clicks, dtype=torch.bool).bernoulli(0.6)
class RGCN(nn.Module):
    def __init__(self, in_feats, hid_feats, out_feats, rel_names):
        super().__init__()

        self.conv1 = dglnn.HeteroGraphConv({
            rel: dglnn.GraphConv(in_feats, hid_feats)
            for rel in rel_names}, aggregate='sum')
        self.conv2 = dglnn.HeteroGraphConv({
            rel: dglnn.GraphConv(hid_feats, out_feats)
            for rel in rel_names}, aggregate='sum')

    def forward(self, graph, inputs):
        # inputs are features of nodes
        h = self.conv1(graph, inputs)
        h = {k: F.relu(v) for k, v in h.items()}
        h = self.conv2(graph, h)
        return h
    
model = RGCN(n_hetero_features, 20, n_user_classes, hetero_graph.etypes)
user_feats = hetero_graph.nodes['user'].data['feature']
item_feats = hetero_graph.nodes['item'].data['feature']
labels = hetero_graph.nodes['user'].data['label']
train_mask = hetero_graph.nodes['user'].data['train_mask']
node_features = {'user': user_feats, 'item': item_feats}

opt = torch.optim.Adam(model.parameters())

for epoch in range(1000):
    model.train()
    # forward propagation by using all nodes and extracting the user embeddings
    logits = model(hetero_graph, node_features)['user']
    
    # compute loss
    loss = F.cross_entropy(logits[train_mask], labels[train_mask])
    # Compute validation accuracy.  Omitted in this example.
    # backward propagation
    opt.zero_grad()
    loss.backward()
    opt.step()
    #print(loss.item())
```
## Expected behavior
Running in CPU, the RAM memory will keep increasing for each epoch.

## Environment

 - DGL Version (e.g., 1.0): **0.7.0**
 - Backend Library & Version (e.g., PyTorch 0.4.1, MXNet/Gluon 1.3): **PyTorch 1.9.0**
 - OS (e.g., Linux): **Linux**
 - How you installed DGL (`conda`, `pip`, source): **conda install -c dglteam dgl**
 - Build command you used (if compiling from source): -
 - Python version: **3.8.10**
 - CUDA/cuDNN version (if applicable): -
 - GPU models and configuration (e.g. V100) -:
 - Any other relevant information: -

**Comment by Rhett-Ying** [comment]
Thanks for your report. 

Issue could be reproduced in my side (**Python 3.6.9, torch 1.8.1+cu102**). root cause is not found yet, though I got several interesting findings.

1. such issue seems exist only if many parallel edges exist between nodes that have different types: 'user', 'click', 'item'. n_clicks(50K) is a bit larger than n_users/n_items(1k,0.5k). If such parallel edges are removed by calling **dgl.to_simple()**, issue is gone.
2. call **gc.collect()** at the end of HeteroGraphConv::forward() could stop RAM keeps increasing.

**Comment by afdezt** [comment]
Thanks to you for testing this!

Regarding your points:

1. I tried increasing also the number of nodes and even if I remove the possible parallel ones with dgl.to_simple(), the problem persists. My feeling is that the RAM is always increasing regardless of the graph although this increment is only noticeable when a big graph is used.
2. Indeed, by calling gc.collect() right after the forward of the convolution (in the forward method) the RAM does not keep increasing. If the root cause is not found implementing this by default (or in the tutorial) may be a solution (?)

**Comment by Rhett-Ying** [comment]
appending gc.collect() into forward look as weird as this issue. I will try to look deeper into it. there must be a BUG or something is waiting for me... For now, pls add it into your local branch as a WAR. thanks.

**Comment by Rhett-Ying** [comment]
a bug in python? But I tried with python3.9, failed yet.
