### ISSUE TITLE
Implement Inference in PinSAGE example

### ISSUE THREAD

**Issue by geo47** [dmlc/dgl#3232]
Hi @mufeili and @VoVAllen,

Thanks for the [PinSAGE](https://github.com/dmlc/dgl/tree/master/examples/pytorch/pinsage) implementation.
 It would be nice if you add inferencing for the PinSAGE example as implemented in (https://github.com/yoonjong12/pinsage) for a Wine recommendation.

Thanks

**Comment by VoVAllen** [comment]
The inference process is just the KNN recall process, which can differ from different scales by using ANN(faiss). This is also not coupled with dgl. Also we have the similar inference function https://github.com/dmlc/dgl/blob/799c091e6dccce965947d855e5aaa6fc30fac635/examples/pytorch/pinsage/evaluation.py#L60-L61, which I believe is enough in most scenarios

**Comment by geo47** [comment]
Hi @VoVAllen,

Thanks for the quick response.
I got the evaluation process mentioned here. Its also implemented very cleanly so I could understand the whole things. 
I am also trying to add evaluation based on user-item interaction similar to [this one](https://github.com/yoonjong12/pinsage/blob/b222ad6ffc050f793f71f3b3f6a8f177a90325e3/model.py#L158).

Could you please have a look at that piece of code and guide how can I achieve this in the current PinSAGE example, or update the evaluation steps in the current example if it is feasible for you and not time-consuming.

Thanks

**Comment by BarclayII** [comment]
I would love to.  The comments there are written in Korean which I unfortunately don't speak :(.  Could you highlight us the differences or which part to look at?

**Comment by geo47** [comment]
Hi @BarclayII, 
I would want to implement the inferencing part implemented here (https://github.com/yoonjong12/pinsage/blob/b222ad6ffc050f793f71f3b3f6a8f177a90325e3/model.py#L158)

The whole project is similar to the current dgl/PinSAGE implementation. However, they additionally implemented inferencing.

Also, When I apply my own dataset to the PinSAGE implementation, the results are all 0.0 at every epoch. Although, I apply all the same steps to process the data and make features.

Thanks.

**Comment by BarclayII** [comment]
I took a look in the code.  How is it different from the `LatestNNRecommender`?

**Comment by geo47** [comment]
In the training function, it computes the precision, recall, and F1 score.
How can we achieve this?
