### ISSUE TITLE
Import error from installation from source

### ISSUE THREAD

**Issue by jwyyy** [dmlc/dgl#3241]
## To Reproduce

1. Built master branch (cd2cf60) from source https://docs.dgl.ai/en/0.6.x/install/
2. ```import dgl``` in python shell
3. got import error message :
```Python 3.8.5 (default, Sep  4 2020, 07:30:14)
[GCC 7.3.0] :: Anaconda, Inc. on linux
Type "help", "copyright", "credits" or "license" for more information.
>>> import dgl
[23:48:28] /home/tiger/usr_name/dgl/src/runtime/tensordispatch.cc:43: TensorDispatcher: dlopen failed: /home/tiger/anaconda3/envs/usr_name/lib/python3.8/site-packages/dgl-0.8-py3.8-linux-x86_64.egg/dgl/tensoradapter/pytorch/libtensoradapter_pytorch_1.9.0.so: cannot open shared object file: No such file or directory
Using backend: pytorch
>>>
```

## Environment

 - DGL Version (e.g., 1.0): **0.8**
 - Backend Library & Version (e.g., PyTorch 0.4.1, MXNet/Gluon 1.3): **PyTorch 1.9.0**
 - OS (e.g., Linux): **Debian**
 - How you installed DGL: **source**
 - Build command you used (if compiling from source):
 ```
git clone --recurse-submodules https://github.com/dmlc/dgl.git
sudo apt-get update
sudo apt-get install -y build-essential python3-dev make cmake
cd dgl
mkdir build
cd build
cmake ..
make -j4
```
 - Python version: **3.8.5**
 - CUDA/cuDNN version (if applicable): **NA**
 - GPU models and configuration (e.g. V100): **NA**
 - Any other relevant information:

**Comment by VoVAllen** [comment]
This is not required for dgl but an optimization when allocating cpu and gpu memory. To enable this optimization, you need to change `cmake ..` to `cmake -DBUILD_TORCH=ON ..`

**Comment by jwyyy** [comment]
@VoVAllen Thanks for your reply! Does it mean that when using ```-DBUILD_TORCH=ON``` CUDA is also required? I tried to build with this option but failed. If I only use CPU, is it safe to ignore this error?

**Comment by nv-dlasalle** [comment]
@jwyyy It's safe to ignore this (the message was addedin of #3225), as the allocation on the CPU between DGL and PyTorch is pretty comparable.

We probably need a way to differentiate between a shared library failing to be loaded, and the shared library not existing in the first place.

**Comment by jwyyy** [comment]
Thanks for your clarification!

**Comment by jwyyy** [comment]
> P.S. I get the same message, also on debian when installing via anaconda

I think you can ignore it. The package should run okay even with the warning.

**Comment by Peter-1213** [comment]
> > > P.S. I get the same message, also on debian when installing via anaconda
> > 
> > 
> > I think you can ignore it. The package should run okay even with the warning.
> 
> While it should be functionally fine, if you're running on the GPU it will be significantly slower. @cgoliver What version of pytorch are you see this warning with?

Hello, I'm seeing the same message here. I look into the problem and find out it's because the pytorch version is not the standard release version in nvidia ngc containers (see [link](https://docs.nvidia.com/deeplearning/frameworks/pytorch-release-notes/rel_21-12.html#rel_21-12)). There's always an "a0" in the version string, making dgl keep reporting cannot find the so file for "pytorch_1.x.0**a0**". Is there a fix possible?

**Comment by nv-dlasalle** [comment]
When using a version of PyTorch the DGL binaries don't provide an adapter for (for example the version in the NGC containers), you will need to build DGL from source.

**Comment by 123carmen** [comment]
> > P.S. I get the same message, also on debian when installing via anaconda
> 
> I think you can ignore it. The package should run okay even with the warning.

----- I have the same problem. I know it can run okay.
but it runs on CPU, not on GPU, the GPU usage shows 0%. 
it is very slow, 

the torch: 1.10.1+cu113.
dgl-cu113 (0.7.2)
python 3.6.

could you please help me, how can I solve this and run the program on GPU.
https://github.com/dmlc/dgl/issues/3705
(i wrote some other problem on here)

------only cpu--start-
I use laptop to run with CPU(all packages and modules installed CPU version), it shows,
ModuleNotFoundError: No module named 'dgl.graph'---- I install dgl (with no cua version) pytorch with no cuda version.
all in CPU. it shows this bugs.
------only cpu--end---

--then try on GPU
I try to run the program
github: graphdeeplearning/graphtransformer
the molecule data works well, it runs ON GPU,-- GPU works and it show usage 25%,
but I run the BMs data it changes to CPU automatically. GPU with 0%.

**Comment by 123carmen** [comment]
I put other imformation , When I run the program
it shows -- 

cuda available with GPU: Tesla V100-
[I] Loading dataset SBM_CLUSTER...
train, test, val sizes : 10000 1000 1000
[I] Finished loading.
[I] Data load time: 23.4327s
MODEL DETAILS:

then I check the GPU usage and 
|   0  Tesla V100-.  Off  | 00000002:C1:00.0 Off |                    0 |
| N/A   30C    P0    23W / 250W |      4MiB / 32510MiB |      0%      Default |
|                               |                      |                  N/A |
+-------------------------------+----------------------+----------------------+
|   1  Tesla V100-P..  Off  | 00000003:41:00.0 Off |                    0 |
| N/A   31C    P0    24W / 250W |      4MiB / 32510MiB |      0%      Default |
|                               |                      |                  N/A |

| Processes:                                                                  |
|  GPU   GI   CI        PID   Type   Process name                  GPU Memory |
|        ID   ID                                                   Usage      |
|=============================================================================|
|  No running processes found                                                 
---------------
it shows no process running, 
but my code is running.

**Comment by 123carmen** [comment]
I have the same issues
when I import this dgl, it shows,
[23:48:28] //dgl/src/runtime/tensordispatch.cc:43: TensorDispatcher: dlopen failed: /home/tiger/anaconda3/envs/usr_name/lib/python3.8/site-packages/dgl-0.8-py3.8-linux-x86_64.egg/dgl/tensoradapter/pytorch/libtensoradapter_pytorch_1.9.0.so: cannot open shared object file: No such file or directory
Using backend: pytorch
>>>
----------
it can work, but  the process running very slow, and GPU is not use fully, only 2% usage.
most of time it shows the process D1 status.

could any one help me, how can i fix this, so my program can run fast. thank you

**Comment by YKQ98** [comment]
same problem here, need a solution

**Comment by VoVAllen** [comment]
@123carmen @YKQ98 The warning is safe to ignore and we'll remove that in the next release.

**Comment by nv-dlasalle** [comment]
@VoVAllen Just to clarify, do you mean silencing the warning, or fixing the underlying memory allocator linking issue?
