### ISSUE TITLE
Bug of dgl.nn.DotGatConv

### ISSUE THREAD

**Issue by Flawless1202** [dmlc/dgl#3267]
## 🐛 Bug

Equation error of `dgl.nn.DotGatConv`

## To Reproduce

In [line 211](https://github.com/dmlc/dgl/blob/a536772ed20220646f3a9404a5a5ce157aab8a91/python/dgl/nn/pytorch/conv/dotgatconv.py#L211) of the forward function of `DotGatConv`, the position of `/(self._out_feats**0.5)` seems to be wrong 

## Expected behavior

This line might be corrected as follow:
```
graph.edata['sa'] = edge_softmax(graph, graph.edata['a'] / (self._out_feats**0.5))
```

## Additional context

No

**Comment by yzh119** [comment]
Yes you are right, would you mind creating a PR to fix that?
