### ISSUE TITLE
[Distributed] Refactor ParMETIS pipeline to not require a single gigantic node/edge/stats text file

### ISSUE THREAD

**Issue by erickim555** [dmlc/dgl#3268]
## 🚀 Feature
My proposal is to modify the ParMETIS pipeline to allow ingesting the graph structure (nodes, edges) from a more scalable, modern input format, eg a multi-partition parquet-encoded dataset.

## Motivation

My understanding of the ParMETIS distributed pipeline is that, to perform distributed graph partitioning (eg via ParMETIS), we must do the following:
1. Prepare a "xxx-nodes.txt", "xxx-edges.txt", "xxx-stats.txt" file that contains the node and edge metadata
2. Pass these files to ParMETIS via `mpirun -np 4 pm_dglpart xxx 2`
3. Run `convert_partition.py` to process the `pm_dglpart` outputs to a DGL-friendly format

This is based on this wiki: https://docs.dgl.ai/en/latest/guide/distributed-preprocessing.html#guide-distributed-preprocessing

There are several downsides to the current ParMETS input format, such as:
- Text file encodings aren't very space efficient, something like a parquet-encoded table would likely reduce storage considerably
- Requiring gigantic single files is a little awkward when the graphs are generated from upstream big-data workflows (eg the multiple `part-*` files from big data workflows like Spark/MapReduce) 

## Alternatives

For now, users can continue writing jobs/scripts to generate the "xxx-nodes.txt", "xxx-edges.txt", "xxx-stats.txt" text files that ParMETIS requires.
However, this adds some friction for devs interested in interfacing DistDGL with the rest of their big-data infra.

## Pitch

My proposal is to modify the ParMETIS pipeline to allow ingesting the graph structure (nodes, edges) from a more scalable, modern input format, eg a multi-partition parquet-encoded dataset.

## Additional context

I understand that this is more of an issue for the ParMETIS/dgl repo, but this repo gets more attention, so I thought I'd create it here rather than there, to get some thoughts from core DistDGL devs: https://github.com/KarypisLab/ParMETIS/tree/dgl/programs

This isn't super high priority, but something interesting to consider as DistDGL continues building out its large-scale distributed graph support.

**Comment by jermainewang** [comment]
This is a scheduled task which will be tracked in #4358 . I will close this. Follow up discussions should go to the other thread.
