### ISSUE TITLE
[Feature Request] Node features to contain text (string) data

### ISSUE THREAD

**Issue by JonnyTran** [dmlc/dgl#3280]
## 🚀 Feature
I wish to assign a string to each node in a `DGLGraph`, but DGL forces to use a fixed-size numerical tensor for node features.

Currently, to assign node features for N nodes, we must assign a Tensor of size [N, D, ...]. In order to assign text-based node features, we must first have an one-hot encoding and pad all sequences to some max-length of D. This have limitations that make it very difficult to work with transformer models and BertTokenizer's.

I'd like `DGLGraph` to allow assigning a list of strings to `G.nodes().data` as a Python str primitive, rather than a tensor. This would allow greater flexibility for downstream string tokenizers. Is this possible?

## Motivation
This feature would support any applications involving NLP in a graph data structure. Think citation networks, protein-protein interactions.

## Alternatives

`DGLGraph` to allow assigning string to `G.nodes().data` as a Python str primitive, rather than a tensor. The strings should also be available through nodes in a MFG .

**Comment by mufeili** [comment]
Just like the last solution in [FAQ 14](https://discuss.dgl.ai/t/frequently-asked-questions-faq/1681), you can first compute the node embeddings with a model like BERT and then assign them to `g.ndata`.

**Comment by JonnyTran** [comment]
Thanks @mufeili, I understand it's possible to assign BERT output representations to node features. However, I want to train a BERT model and a GNN end-to-end from raw text, and it's still hard to figure out with DGL's `NodeCollator`, since there are many intermediate encoding steps that would require a separate torch's `DataLoader` to work with primitive string's.

For example, for the BERT tokenizer to encode string for a batch of nodes, its tokenization steps would need to store `token_ids`, `offsets`, `attention_mask`, and it is very memory-consuming to store all those padded tensors in `G.ndata`. In my opinion, the simplest option is to allow storing string primitives - but I understand there might be better options.

**Comment by mufeili** [comment]
I'm not sure if you want to touch `NodeCollator`. I guess you can write a data loader or dataset class that allows you to compute BERT embeddings in each iteration from text and then assign them to `ndata` of a graph. This should allow you to co-train a GNN and BERT end-to-end.

**Comment by JonnyTran** [comment]
Thanks! That sounds like a plausible option.
