### ISSUE TITLE
[Performance][Distributed] Optimize `distributed.partition_graph()` for large-scale heterogeneous graphs (billions of nodes, billions of edges)

### ISSUE THREAD

**Issue by erickim555** [dmlc/dgl#3283]
## 🚀 Feature
Proposal: Optimize `distributed.partition_graph()` to scale to large-scale heterogeneous graphs, eg graphs with billions of nodes and billions of edges.
The primary bottleneck is memory. For now, I'm focusing on CPU memory: the GPU memory representation is outside of my scope currently.
Related: It's unclear to me how the distributed graph partitioning pipeline (ParMETIS) behaves in terms of CPU memory usage. Perhaps somebody with expertise here can chime in?

## Motivation
If DistDGL can scale to large-scale heterogeneous graphs, then this makes DGL very attractive for people working on large-scale datasets (eg "web scale" graphs, etc).

## Alternatives
One alternative is to simply run DistDGL on a machine with a ton of CPU memory: for instance, Amazon EC2 has memory-optimized instance types like the X1.32XLarge with 1952 GB of CPU memory. However, these are fairly expensive (on-demand pricing is $13.338/hour according to this [AWS EC2 pricing tool](https://aws.amazon.com/ec2/pricing/on-demand/)). 

## Additional context
I'm currently in the middle of pushing a medium-scale graph (~2B nodes, ~15M edges) through DistDGL, and despite this graph being fairly small, I've identified several major memory bottlenecks, which I'll list below.
My ultimate intention is to get DistDGL working on heterogeneous graphs with billions of nodes AND billions of edges. 

(1) `convert.to_homogeneous() nids, eids`
Looking at the DistDGL code, fortunately it seems that DGL is already careful to avoid allocating unnecessary data, eg the `to_homogeneous(G, store_type=False, return_count=True)` trick to encode node/edge types via counts instead of explicitly encoding node/edge types via an int array with length num_nodes or num_edges.

I wonder if we can apply the same "counts" trick to avoid having to create+store the `nids, eids` arrays in `convert.to_homogeneous()`:
https://github.com/dmlc/dgl/blob/master/python/dgl/convert.py#L981

Context: `nids` is an array with length num_homogeneous_nodes that tells you how to go from a "node_type_agnostic_id" (aka homogeneous node ID) to a "node_type_aware_id" (aka heterogeneous node ID).
Similarly, `eids` is an array with length num_homogeneous_edges that tells you how to go from an "edge_type_agnostic_id" (aka homogeneous edge ID) to an "edge_type_aware_id" (aka heterogeneous edge ID).

It seems to me that this `nids, eids` is unnecessary, as one can use the "ntype_counts, etype_counts" to convert a homogeneous node/edge ID to its heterogeneous node/edge ID.

The overhead of `nids, eids` is (rough back-of-the-envelope calculations)
```
4B nodes, 4B edges
src, dst (dtype=int64) -> 64 GB
nids (dtype=int64) -> 32 GB
eids (dtype=int64) -> 32 GB
=> Unnecessary doubling of required CPU memory to partition a heterogeneous graph
```

Here, my proposal would be to refactor `convert.to_homogeneous()` to NOT store `nids, eids` in the output graph. This would considerably reduce CPU memory overhead.
Maybe add a new flag `convert.to_homogeneous(store_nids_eids=True)` that controls this behavior (and `store_nids_eids=False` can only occur when `return_count=True`).

(2) `_CAPI_DGLMakeSymmetric_Hetero()` large CPU memory overhead
I am observing that, with a graph containing ~2B nodes and ~15M edges, I end up using >240GB CPU memory when `distributed.partition_graph()` calls `_CAPI_DGLMakeSymmetric_Hetero()`, which exhausts the dev machine that I am on:
https://github.com/dmlc/dgl/blob/8341244a2dac850bd0c1153c7641c3b8a2bbfc30/python/dgl/partition.py#L271

I am not yet sure why this is the case, as I haven't dived into this source code yet. This is very peculiar, because the graph structure itself is quite small (num_edges=15M), so it has something to do with the num_nodes being large, or with some implementation detail. I hope that this memory explosion can be mitigated.

Thanks!

**Comment by erickim555** [comment]
Update: For (2), I discovered that setting `NUM_OMP_THREADS=5` (rather than `nproc=96`) avoids the CPU OOM that I was originally experiencing, but then I get a new one:
```
   Current memory used:           0 bytes
   Maximum memory used:           0 bytes
***Memory allocation failed for gk_csr_ExtractPartition: rowptr. Requested size: 18446744058309090232 bytes
```
This comes from a call to `Convert2GKCsr()`: https://github.com/dmlc/dgl/blob/195f99362d883f8b6d131b70a7868a537e55b786/src/graph/gk_ops.cc#L104

It's fairly absurd that we are trying to allocate `18446744058309090232` bytes. For an 8 byte `ssize_t`, this implies that the input `aten::CSRMatrix mat` has `2.3e18` rows, which is absurd: my graph only has ~2B nodes and ~15M edges!

I suspect that there's a bug somewhere here.

**Comment by VoVAllen** [comment]
Sorry for the bug. But here we depends on an external C package gklib. Could you also try calling `dgl.to_simple` for your graph before doing metis partition? We found there'll be bug if the input graph has duplicate edges

**Comment by erickim555** [comment]
Hey @VoVAllen , thanks for the tip, I've tried `dgl.to_simple()` but i'm still able to reproduce this `gklib` error.
I did some digging, and I think it's an `int32` overflow. A graph with 2.0B nodes works, but a graph with 2.2B nodes throws this gklib error (int32 max value is ~2.14B).

I'll attach a script that can reliably reproduce this error, provided that you have a dev machine with >100GB CPU memory:

**Comment by erickim555** [comment]
Here's a script that reproduces the error: https://gist.github.com/erickim555/3dbe132969841ad6be3c81996f9a078d

**Comment by erickim555** [comment]
Oh no! The underlying `gk_csr_t` (from GKLib) uses `int32` to represent `nrows,ncols`:
https://github.com/KarypisLab/GKlib/blob/1403a04bc40a306d09adfccced7d903d69de040a/gk_struct.h#L75
```
/*-------------------------------------------------------------
 * The following data structure stores a sparse CSR format
 *-------------------------------------------------------------*/
typedef struct gk_csr_t {
  int32_t nrows, ncols;
  ssize_t *rowptr, *colptr;
  int32_t *rowind, *colind;
  int32_t *rowids, *colids;
  int32_t *rlabels, *clabels;
  int32_t *rmap, *cmap;
  float *rowval, *colval;
  float *rnorms, *cnorms;
  float *rsums, *csums;
  float *rsizes, *csizes;
  float *rvols, *cvols;
  float *rwgts, *cwgts;
} gk_csr_t;
```

This is pretty serious, as any DGL code using GKLib is likely introducing an unexpected bug where graphs with >2.147B nodes will break in weird, unexpected ways.

What's the best way to get around this? We could patch the upstream GKLib to use `int64_t`'s, but not sure how involved that patch will be, as I'm not familiar with the GKLib/METIS code base...

**Comment by erickim555** [comment]
@zheng-da  I see that you introduced `GraphOp::ToBidirectedSimpleImmutableGraph()`. It seems that: because this function uses the GKLib graph representation, this function errors on graphs with >2.147B nodes due to an int32 overflow bug. This is because GKLib graphs can only support graphs with <2.147B nodes (eg int32 max value).

Do you have any advice/thoughts on how to fix this? Thanks!

**Comment by VoVAllen** [comment]
Thanks a lot for the detailed dig in! The `ToBidirectedSimpleImmutableGraph` is deprecated. Basically we found using function from gklib is much faster. This is definitely a bug we'd like to fix. However we need to figure out whether it's better for Gklib to handle such scenario or implement by our own.

**Comment by erickim555** [comment]
Hey @VoVAllen , I'm sorry, I misspoke: I didn't mean `ToBidirectedSimpleImmutableGraph()` (which you're right, is deprecated and wasn't in my call stack), I actually meant `_CAPI_DGLMakeSymmetric_Hetero()`, which calls `Convert2GKCsr()` that contains the int32 overflow bug:
https://github.com/dmlc/dgl/blob/6e7f19f27bdf6fddc69aaf8bf2b392d685703f76/src/graph/transform/partition_hetero.cc#L358

I've edited my above comments accordingly, sorry for the confusion

**Comment by erickim555** [comment]
Question: if the input graph to `dgl.distributed.partition_graph(graph, part_method="metis")` is already symmetric (eg if there is an edge from U->V, then there is also an edge from V->U), then can we omit the call to `_CAPI_DGLMakeSymmetric_Hetero()`? 

My gut says "yes, we can omit the call". If this is true, then we can add a flag `dgl.distributed.partition_graph(part_method="metis", is_graph_symmetric=True)` where, if `is_graph_symmetric=True`, then we SKIP the call to `_CAPI_DGLMakeSymmetric_Hetero()` and trust that the user knows what they're doing. 
Otherwise, we call `_CAPI_DGLMakeSymmetric_Hetero()` (the default).

What do you think?

**Comment by Rhett-Ying** [comment]
pls let me drop some comments on the issue of `convert.to_homogeneous() nids, eids`.

`nids/eids` does consume non-trivial memory for large graphs. Such info could be omitted when converting to homo and retrieved according to `ntypes/etypes` when needed as you said. But the benefit of simply picking up such logic in the impl of `distributed.partition_graph()` is **not very beneficial**, as we still need to construct `NID` or `EID` though we could avoid keep both of them alive at the same time. Memory consumption of `ID` could be reduced into half. But it's less intuitive and needs more dedicated logic (such as garbage collection in python). Or we could avoid constructing the whole `NID` or `EID` by more dedicated logic(for example, optimize in `F.gather_row(sim_g.ndata[NID], local_nodes)` https://github.com/dmlc/dgl/blob/master/python/dgl/distributed/partition.py#L746), but it may slow down the processing and requires more logic. It's probably a trade-off between time and space.

**Comment by Rhett-Ying** [comment]
> Question: if the input graph to `dgl.distributed.partition_graph(graph, part_method="metis")` is already symmetric (eg if there is an edge from U->V, then there is also an edge from V->U), then can we omit the call to `_CAPI_DGLMakeSymmetric_Hetero()`?
> 
> My gut says "yes, we can omit the call". If this is true, then we can add a flag `dgl.distributed.partition_graph(part_method="metis", is_graph_symmetric=True)` where, if `is_graph_symmetric=True`, then we SKIP the call to `_CAPI_DGLMakeSymmetric_Hetero()` and trust that the user knows what they're doing.
> Otherwise, we call `_CAPI_DGLMakeSymmetric_Hetero()` (the default).
> 
> What do you think?

I think so. If graph is already symmetric/bi-directed, `_CAPI_DGLMakeSymmetric_Hetero()` could be skipped. as for the improvement of this, adding additional arg to indicate whether graph is bi-directed is an option, but this requires to add such arg in `distributed.partition_graph()` and pass down to underlying call. This sounds not a very elegant way.

I think `is_bidirected` is an attribute of graph which is determined by the graph structure. we could query such attributes from graph. In order to avoid really checking whether graph is bi-directed, what we need to do is record the latest attribute status as it could be invalidated when graph structure is changed. **Probably, wrap all graph attributes and support validate/invalidate/query/record mechanics is good way to enable any potential performance improvement.** How do you think about it? @zheng-da
