### ISSUE TITLE
Could not found specified module (kernel32.dll) when import dgl

### ISSUE THREAD

**Issue by PuppyWolf** [dmlc/dgl#329]
## ❓ Questions and Help

I had build and install the dgl module followed by the instruction on Win10 . But when I import dgl module and ran the script and then I get back this error message : 
     "File "D:\ProgramData\Anaconda3\my_tensorflow\lib\site-packages\dgl-0.1.3-py3.5.egg\dgl\_ffi\base.py", line 35, in _load_lib
    lib = ctypes.CDLL(lib_path[0], ctypes.RTLD_GLOBAL)   
  File "D:\ProgramData\Anaconda3\my_tensorflow\lib\ctypes\__init__.py", line 357, in __init__
    self._handle = _dlopen(self._name, mode)
OSError: [WinError 126] could not find specified module 
 "

**Comment by mufeili** [comment]
Hi, it seems that the issue you encountered is very similar to #293 . If you did not install dgl with `conda`, could you please try installing dgl with `conda` and see if the problem still exists?
