### ISSUE TITLE
[Tools][Distributed] tools/launch.py is passing incorrect ip_config, part_config

### ISSUE THREAD

**Issue by erickim555** [dmlc/dgl#3295]
## 🐛 Bug

Currently, `tools/launch.py` passes ip_config, part_config without the `args.workspace` prefix. This is incorrect, as downstream DistDGL code assumes that `DGL_IP_CONFIG, DGL_CONF_PATH` contain the workspace prefix.

Example: if `args.workspace` is `/mnt/my-nfs/distdgl_workspace`, and `args.ip_config=ip_config.txt`, `args.part_config=data/graph/part_config.json`, and we have the following dir structure:
```
/mnt/my-nfs/distdgl_workspace/ip_config.txt
/mnt/my-nfs/distdgl_workspace/data/graph/part_config.json
```
Then, launching `tools/launch.py --ip_config ip_config.txt --part_config data/graph/part_config.json` will result in downstream DistDGL errors on the cluster hosts:
```
INFO:torch.distributed.elastic.agent.server.api:[default] starting workers for entrypoint: python3.7                INFO:torch.distributed.elastic.agent.server.api:[default] Rendezvous'ing worker group
Namespace(batch_size=1000, batch_size_eval=100000, dataset=None, dropout=0.5, eval_every=5, fan_out='10,25', graph_n
ame='ogb-product', id=None, ip_config='/mnt/efs-home/users/erickim/dgl_dist_workspace/ip_config.txt', local_rank=Non
e, log_every=20, lr=0.003, n_classes=None, num_clients=None, num_epochs=30, num_gpus=1, num_hidden=16, num_layers=2,
 part_config=None, standalone=False)
Traceback (most recent call last):
  File "/mnt/efs-home/users/erickim/dgl_dist_workspace/src/dgl/examples/pytorch/graphsage/experimental/train_dist.py
", line 319, in <module>
    main(args)
  File "/mnt/efs-home/users/erickim/dgl_dist_workspace/src/dgl/examples/pytorch/graphsage/experimental/train_dist.py
", line 256, in main
    dgl.distributed.initialize(args.ip_config)
  File "/usr/local/lib/python3.7/site-packages/dgl/distributed/dist_context.py", line 234, in initialize
    graph_format=formats)
  File "/usr/local/lib/python3.7/site-packages/dgl/distributed/dist_graph.py", line 318, in __init__
    num_clients=num_clients)
  File "/usr/local/lib/python3.7/site-packages/dgl/distributed/kvstore.py", line 636, in __init__
    assert os.path.exists(ip_config), 'Cannot open file: %s' % ip_config
AssertionError: Cannot open file: ip_config.txt
```
Here, the kvstore server is failing to init because it can't find ip_config.txt.

The fix is to pass `DGL_IP_CONFIG=/mnt/my-nfs/distdgl_workspace/ip_config.txt, DGL_CONF_PATH=/mnt/my-nfs/distdgl_workspace/data/graph/part_config.json`, instead of `DGL_IP_CONFIG=ip_config.txt, DGL_CONF_PATH=part_config.json`.

## To Reproduce

1. Run the `examples/pytorch/graphsage/experimental/train_dist.py`, and you'll see this error.

## Expected behavior

The trainer should work.

## Environment

 - DGL Version (e.g., 1.0):
 - Backend Library & Version (e.g., PyTorch 0.4.1, MXNet/Gluon 1.3):
 - OS (e.g., Linux):
 - How you installed DGL (`conda`, `pip`, source):
 - Build command you used (if compiling from source):
 - Python version:
 - CUDA/cuDNN version (if applicable):
 - GPU models and configuration (e.g. V100):
 - Any other relevant information:

**Comment by Rhett-Ying** [comment]
Hi, I tried below cmd with latest DGL (sync master branch this morning and build on my own). everything goes well. The path issue your reported cannot be reproduced. could you help check the difference between yours and mine?

cd  /home/ubuntu/workspace/dgl/examples/pytorch/graphsage/experimental

DGL_HOME=/home/ubuntu/workspace/dgl DGL_LIBRARY_PATH=$DGL_HOME/build PYTHONPATH=$DGL_HOME/python:$PYTHONPATH DGL_BACKEND=pytorch python3 ~/workspace/dgl/tools/launch.py --workspace ~/workspace/dgl/examples/pytorch/graphsage/experimental/ --num_trainers 1 --num_samplers 0 --num_servers 1 --part_config data/ogb-product.json --ip_config ip_config.txt "python3 train_dist.py --graph_name ogb-product --ip_config ip_config.txt --num_epochs 30 --batch_size 1000"
