### ISSUE TITLE
ModuleNotFoundError: No module named 'dgl.graph'

### ISSUE THREAD

**Issue by TXacs** [dmlc/dgl#3305]
## 🐛 Bug

When I run the gnns training, I got this error. I need help!

![image](https://user-images.githubusercontent.com/60869411/131479027-095ebd01-1e30-4f10-aca5-d16bdb73c272.png)

## Environment

 - DGL Version (e.g., 1.0):  0.6.1 or 0.5.3
 - Backend Library & Version (e.g., PyTorch 0.4.1, MXNet/Gluon 1.3):  pytorch 1.7.1
 - OS (e.g., Linux):  ubuntu  18.04
 - How you installed DGL (`conda`, `pip`, source):  pip install dgl
 - Build command you used (if compiling from source):  
 - Python version:  python3.6
 - CUDA/cuDNN version (if applicable):  cu11.0
 - GPU models and configuration (e.g. V100):  RTX 3090
 - Any other relevant information:

**Comment by VoVAllen** [comment]
Could you try newer dgl such as 0.7?

**Comment by TXacs** [comment]
> Could you try newer dgl such as 0.7?

yeah, I tried, got same error

**Comment by jermainewang** [comment]
Could you try `python -c 'import dgl; print(dgl.__path__)'`?

**Comment by maxueqi** [comment]
I got the same error. How did you solve it?

**Comment by TXacs** [comment]
> I got the same error. How did you solve it?

Oh, sorry, I forgot it. Because I changed the research direction, it has been useless for several months.
