### ISSUE TITLE
[Feat request] issue with attention mechanism in graphs

### ISSUE THREAD

**Issue by fmellomascarenhas** [dmlc/dgl#3309]
Hi all,

**1) lack of dst node score**
Vanilla attention mechanisms should take into consideration the dst node attention. In DGLs implementation, only the scores of the edges are calculated. Imagine that all neighbors are equally just noise and have very low scores. When you normalize with softmax, all neighbors will be forced to sum to 1. In vanilla attention, the model could avoid it by having a high score for the dst node, minimizing the att of all incoming edges. In current attention implementations, this is not possible. 

Feat: adapt edge softmax to consider the dst node score. 

edit: solving issue above would already be enough.
~~**2) hard to normalize attention if using sigmoid**: I have been trying to use sigmoid instead of softmax. When I calculate agg = sum(values * att), I have a hard time normalizing it~~

~~Case 1: Let's suppose that there are 2000 neighbors and only 20 have att > 0.5, then norm_sum should be something like sum/20.~~
~~Case 2: if I have 4 neighbors and all of them have low scores, for example, 0.05, then normalizing by the sum of scores will make all of them sum to 1, nullifying the purpose of the sigmoid.~~

~~Feat: I thought of using two normalization techniques: if scores are <0.5, then normalize by the num of neighbors. If they are >0.5, then normalize by the count of >0.5.~~

~~This sounds far for ideal, but using sigmoid is very important for my implementation, and a custom function is way too slow. Please let me know if you have any ideas. Thanks!!~~

**Comment by mufeili** [comment]
> Hi all,

> 1) lack of dst node score
Vanilla attention mechanisms should take into consideration the dst node attention. In DGLs implementation, only the scores of the edges are calculated. Imagine that all neighbors are equally just noise and have very low scores. When you normalize with softmax, all neighbors will be forced to sum to 1. In vanilla attention, the model could avoid it by having a high score for the dst node, minimizing the att of all incoming edges. In current attention implementations, this is not possible.

> Feat: adapt edge softmax to consider the dst node score.

Do you have an example implementation that may not be based on DGL? Is there a paper on vanilla attention for reference?

> 2) hard to normalize attention if using sigmoid
> I have been trying to use sigmoid instead of softmax. When I calculate agg = sum(values * att), I have a hard time normalizing it.
Case 1: Let's suppose that there are 2000 neighbors and only 20 have att > 0.5, then norm_sum should be something like sum/20.
Case 2: if I have 4 neighbors and all of them have low scores, for example, 0.05, then normalizing by the sum of scores will make all of them sum to 1, nullifying the purpose of the sigmoid.

> Feat: I thought of using two normalization techniques: if scores are <0.5, then normalize by the num of neighbors. If they are >0.5, then normalize by the count of >0.5.

> This sounds far for ideal, but using sigmoid is very important for my implementation, and a custom function is way too slow. Please let me know if you have any ideas. Thanks!!

The proposed normalization sounds a bit weird and I'm wondering if there is a better way to handle this. For example, you may pass the output of the sigmoid function to a softmax function with temperature.

**Comment by fmellomascarenhas** [comment]
@mufeili , thanks for answering!

Imagine you have a graph with 4 nodes, and you are trying to calculate the message for the blue node - h1:

![image](https://user-images.githubusercontent.com/23004953/131858781-ed029ce4-d5d0-487d-991d-90cd01a2b326.png)

What a transformer would do is: 
- compare the QUERY of h1 with the KEYS of h1,h2,h3,h4 
- generate a score
- multiply by the value V
- add as a message.

![image](https://user-images.githubusercontent.com/23004953/131859097-5c5ce0cb-1af2-4077-b3f2-df33769b6026.png)

What attention mechanisms are doing in DGL implementations is to ignore the h1 score and only compute for the edges. This means that if all neighbors have very low scores, they would still have a very meaningful message, removing from the model the ability to ignore noise and preserve information.

![image](https://user-images.githubusercontent.com/23004953/131859287-b856fab7-dc16-43d8-8f72-1717bcb44e53.png)

Does it make sense?

Here are two sources explaining attention in detail:
https://towardsdatascience.com/attn-illustrated-attention-5ec4ad276ee3
https://jalammar.github.io/illustrated-transformer/

**Comment by mufeili** [comment]
@fmellomascarenhas , thank you for the detailed reply. The GAT attention implementation you refer to is an outdated implementation and we now generally encourage the use of `edge_softmax`. Regarding the issue of ignoring the original destination node representation, I think you can fix it by adding self loops using the API [here](https://docs.dgl.ai/generated/dgl.add_self_loop.html#dgl.add_self_loop).

**Comment by fmellomascarenhas** [comment]
Thanks @mufeili , I will close the issue then. I just wonder if adding self loops is an obvious or viable solution for future users. Maybe adding a comment related to that in the edge_softmax page could help.

**Comment by mufeili** [comment]
Got it, thanks @fmellomascarenhas
