### ISSUE TITLE
[Performance] Pass `row_sorted, col_sorted` from `dgl.heterograph()` to `create_from_edges()`

### ISSUE THREAD

**Issue by erickim555** [dmlc/dgl#3310]
## 🚀 Feature
Modify `dgl.heterograph()` to pass `row_sorted, col_sorted` to `create_from_edges()`. 

## Motivation
As far as I can tell, currently the recommended way to create heterographs in DGL is to use `dgl.heterograph()`, which calls `create_from_edges()`.
There are some internal DGL functions that benefit if the COO graph data structure is in "row sorted order", for instance COOToCSR():
https://github.com/dmlc/dgl/blob/master/src/array/cpu/spmat_op_impl_coo.cc#L301

This PR is an example of adding the ability to "track" whether a COO graph is in sorted order or not, to enable various internal optimizations:
https://github.com/dmlc/dgl/pull/2645

I think we should expose this to `dgl.heterograph()` and encourage users to "opt into" this optimization if they ensure that their COO data structs are in sorted order.

## Alternatives
Continue using the existing unoptimized code. This isn't a hard blocker, but I think this would be a nice optimization, particularly for large graphs.

## Additional context
Here's an example where COOToCSR() memory usage can explode if the user isn't aware of the memory impact that NUM_OMP_THREADS has on the "COO row is not sorted" code path: https://github.com/dmlc/dgl/issues/3307

**Comment by erickim555** [comment]
Hey @nv-dlasalle , do you have any insights/advice into the importance of COO data structs being row/col sorted for performance? Perhaps in the context of doing neighbor sampling (eg randwalk based or n-hop based). Thanks!

**Comment by nv-dlasalle** [comment]
@erickim555 If you're doing node property prediction, just passing in the graph as CSC is probably the best option. Unfortunately for link/edge property prediction, I believe internally DGL needs to construct both CSC and COO, but conversion from CSC to COO should be quite fast and memory efficient.

Are you seeing this take a long time during sampling at each step, or just during initialization?

**Comment by erickim555** [comment]
@nv-dlasalle  I see, thanks for the info! 

`> Are you seeing this take a long time during sampling at each step, or just during initialization?`
Fortunately, only during initialization: my first call to `dgl.sampling.random_walk()` takes ~2-4 minutes since it seems to perform a `COOToCSR()` call, and my input graph is quite large (and created in COO format). Fortunately, subsequent calls are fast.

And, fortunately, memory usage can be controlled via `OMP_NUM_THREADS`, I was previously hitting CPU OOM's in `COOToCSR()` until I realized: https://github.com/dmlc/dgl/issues/3307

So, it's not a huge deal breaker, but could be a nice, easy-to-implement optimization.

**Comment by erickim555** [comment]
If we wanted to pursue this, this `create_unitgraph_from_coo()` function would be the place to pass `row_sorted, col_sorted` to `_CAPI_DGLHeteroCreateUnitGraphFromCOO()`:
https://github.com/dmlc/dgl/blob/acd21a6d60e40ab0da39ffd30ffa943c798b52a9/python/dgl/heterograph_index.py#L1073

**Comment by BarclayII** [comment]
@erickim555 Now heterogeneous graphs can be directly created from a CSR and CSC matrix.  Could you try that instead?
```python
g = dgl.heterograph({etype: ('csr', indptr, indices, edge_ids), ...})
```

**Comment by BarclayII** [comment]
You can create directly from CSR/CSC via
```python
g = dgl.heterograph({etype: ('csr', (indptr, indices, edge_id))})
```
