### ISSUE TITLE
[Design] Any ideas/takeaways from "P3 : Distributed Deep Graph Learning at Scale"?

### ISSUE THREAD

**Issue by erickim555** [dmlc/dgl#3311]
I saw this recent paper called "P3: Distributed Deep Graph Learning at Scale" from Microsoft that builds a new way to train GNN models on top of DGL, and they claim up to 7x better train throughput than DGL: https://www.microsoft.com/en-us/research/publication/p3-distributed-deep-graph-learning-at-scale/

Paper: https://www.usenix.org/system/files/osdi21-gandhi.pdf
Slides: https://www.usenix.org/system/files/osdi21_slides_gandhi.pdf

Their experiments are based off of DGL v0.5. I'm wondering what you all (DGL core devs) think about this paper, and if any ideas can be transferred to core DGL?

Thanks!

**Comment by zheng-da** [comment]
their solution is to parallelize mini-batch computation with multiple machines. this leads to two problems:
* we need to change the programming interface for distributed training,
* we need to perform backwad computation across machines.
For the first problem, we want to give users the similar programming interface for distributed training and single-process training.
The second problem will lead to large communication overhead if the hidden dimension size is large. As you may notice from the paper, their solution is slower than DGL/DistDGL when the hidden dimension size is large. In practice, we should use large dimension size for good model accuracy.
