### ISSUE TITLE
[BUG] Kernel crashes using new hg.update_all

### ISSUE THREAD

**Issue by fmellomascarenhas** [dmlc/dgl#3312]
## 🐛 Bug

I am using the latest version of DGL (PIP nightly), where update_all doesnt require the etype for heterogeneous graphs.
I have a batched graph with N=263 subgraphs. When I do hg.update_all(efunc, rfunc), my kernel restarts if N is big enough, without displaying any messages. I also dont see any spike or major change in memory (but I believe that this is probably the issue).

## To Reproduce

I tried to create a dummy code, but I couldn't reproduce the error, so I made my code available below and my batched graph available here: https://drive.google.com/file/d/1QIS1X3lfnkZynhaMJqDHzcky3dg3pxE_/view?usp=sharing

To narrow down the problem, I iterated over the edgetypes doing `subgraph_G = G.edge_type_subgraph([edge_to_test]) `, and found that edges types [2] and [27] where causing the issue.

Then I iterated over all b_i subgraphs `dgl.slice_batch(G, b_i) `, followed by .update_all, and didnt have any issue, so it isnt a subgraph problem.

Then I increased the number of subgraphs per batch by slicing N at a time: `sliced_G = dgl.batch([dgl.slice_batch(G, b_i) for b_i in range(init_idx, end_idx)])`, and found that if I sample enough subgraphs, then the crash will happen.

This makes me think that it is not a graph/node/edge/feature issue, however no errors are thrown, the kernel just restarts, and I dont see any memory spikes or increase while monitoring it.

```
import torch
import dgl
import dgl.function as fn

#load batched_graph
G = torch.load('subgraph')

#add features
for ntype in G.ntypes:
    v = torch.rand(G.num_nodes(ntype),4,8, device = 'cpu')
    node_att = torch.rand(G.num_nodes(ntype),4, device = 'cpu')
    G.nodes[ntype].data['v'] = v
    G.nodes[ntype].data['node_att'] = node_att

etypes = G.canonical_etypes

#create a smaller version of the batched_graph to prove that the problem is the size of sliced_G
#For ex: subgraphs 73-260 breaks for edge #2. subgraphs 74-261 works for edge #2.
init_idx = 0
end_idx = 262
sliced_G = dgl.batch([dgl.slice_batch(G, b_i) for b_i in range(init_idx, end_idx)])

########### BREAKS KERNEL ##############
#reduce the subgraph to a specific edgetype that is causing issues. I have found that edge#2 and edge#27 causes it. 
#All other edges between 0 and 27 dont case issues.
edge_to_test = etypes[2] #try changing to another number
subgraph_sliced_G = sliced_G.edge_type_subgraph([edge_to_test])

subgraph_sliced_G.update_all(fn.copy_u('node_att', 'node_att_src'), fn.sum('node_att_src', 'att'))
print(subgraph_sliced_G)
```

## Environment

 - Latest / Nightly (sept 1) pip install --upgrade --pre dgl-cu102 -f https://data.dgl.ai/wheels-test/repo.html
 - Pytorch 1.9
 - OS (e.g., Linux):
 - Python 3.7
 - CUDA 10.2
 - GPU 2080 TI

**Comment by VoVAllen** [comment]
I got error `IndexError: index 262 is out of bounds for dimension 0 with size 262` at line `sliced_G = dgl.batch([dgl.slice_batch(G, b_i) for b_i in range(init_idx, end_idx)])`. Did you see the same error?

**Comment by VoVAllen** [comment]
The error didn't happen when compiling DGL with `cmake -DUSE_CUDA=OFF -DUSE_AVX=OFF -DUSE_LIBXSMM=OFF ..`. Seems related to the new kernel

**Comment by BarclayII** [comment]
@isratnisa could you take a look?

**Comment by fmellomascarenhas** [comment]
> ~@isratnisa could you take a look?~ NVM I didn't notice that you sliced the subgraph to only one edge type.
> 
> @fmellomascarenhas Would the same error still occur if you use `update_all` but with given edge types?

I had the error using all edge types. When trying to narrow down the error source, I tested with one edge type at a time. I tested up to 27, and found that edges type 2 and 27  make it crash. I didn't go further in my analysis.

**Comment by fmellomascarenhas** [comment]
@BarclayII @VoVAllen , just wanted to let you know that installing the PIP stable version (I believe 0.7.1) fixes the issue: pip install dgl-cu102 -f https://data.dgl.ai/wheels/repo.html

**Comment by VoVAllen** [comment]
@sanchit-misra Hi, this seems related to the latest LIBXSMM kernel. Could you take a look?

**Comment by fmellomascarenhas** [comment]
> @sanchit-misra Hi, this seems related to the latest LIBXSMM kernel. Could you take a look?

@VoVAllen @sanchit-misra just an update, I had to issues using GPU.

#added .to('cuda')
```
import torch
import dgl
import dgl.function as fn

#load batched_graph
G = torch.load('subgraph').to('cuda')

#add features
for ntype in G.ntypes:
    v = torch.rand(G.num_nodes(ntype),4,8, device = 'cuda')
    node_att = torch.rand(G.num_nodes(ntype),4, device = 'cuda')
    G.nodes[ntype].data['v'] = v
    G.nodes[ntype].data['node_att'] = node_att

etypes = G.canonical_etypes

#create a smaller version of the batched_graph to prove that the problem is the size of sliced_G
#For ex: subgraphs 73-260 breaks for edge #2. subgraphs 74-261 works for edge #2.
init_idx = 0
end_idx = 262
sliced_G = dgl.batch([dgl.slice_batch(G, b_i) for b_i in range(init_idx, end_idx)])

########### BREAKS KERNEL ##############
#reduce the subgraph to a specific edgetype that is causing issues. I have found that edge#2 and edge#27 causes it. 
#All other edges between 0 and 27 dont case issues.
edge_to_test = etypes[2] #try changing to another number
subgraph_sliced_G = sliced_G.edge_type_subgraph([edge_to_test])

subgraph_sliced_G.update_all(fn.copy_u('node_att', 'node_att_src'), fn.sum('node_att_src', 'att'))
print(sliced_G)
```

**Comment by VoVAllen** [comment]
@fmellomascarenhas Hi, we are still investigating this issue. For now a temporary workaround, you can try building dgl from source with `-DUSE_LIBXSMM=OFF` in cmake flags, for example `cmake -DUSE_CUDA=ON -DUSE_LIBXSMM=OFF ..`. This works on my machine. https://docs.dgl.ai/install/index.html#install-from-source

**Comment by fmellomascarenhas** [comment]
@VoVAllen, thanks! My use case is with GPU, so I should be fine. Just wanted to share that the issue only appeared when using CPU, so it might help with the debugging.

**Comment by sanchit-misra** [comment]
I have created a PR #3345 that should fix this issue.

**Comment by VoVAllen** [comment]
Closed for now. Feel free to reopen if problem still exists
