### ISSUE TITLE
[Performance][Sampling][OpenMP] Implement a CPU multi-threaded random walk sampler

### ISSUE THREAD

**Issue by erickim555** [dmlc/dgl#3314]
## 🚀 Feature
Implement CPU multi-threaded random walks, to speed up CPU random walks on machines with multiple cores.

## Motivation
Speed. When random walks on large graphs (billions of nodes, edges) are in the graph model train loop (eg GraphSage/PinSage), we want random walk generation to be as efficient as possible. 

## Alternatives
I believe GPU-accelerated neighborhood sampling (possibly random walks? or maybe just N-hop neighbors) were recently added to DGL, which is definitely great.
Still, having the CPU implementation be as optimized as it can be seems like a good call, especially since random walks are embarrassingly parallel.

## Pitch
It'd be great to show that, after implementing multi-threading random walks, we see an X speedup as more cores are added, etc.

## Additional context

This blog post provides a working C example that implements multi-threaded random walks via OpenMP: https://lukaskoestler.com/blog/random_walk.html

Perhaps we can port this implementation into DGL?

Currently, I see that DGL's random walk C++ implementation does NOT use OpenMP, and I think this is a perfect scenario for OpenMP: https://github.com/dmlc/dgl/blob/195f99362d883f8b6d131b70a7868a537e55b786/src/graph/sampler/randomwalk.cc#L75

One thing to keep in mind is: it's important that adding more threads should NOT significantly increase CPU memory usage. I'm not 100% familiar with OpenMP details, but I'm hoping that an OpenMP-accelerated random walk code shouldn't require substantial memory overhead (eg things like copying graph structure for each thread, etc).

**Comment by BarclayII** [comment]
Our new random walk sampler in `dgl.sampling.random_walk` does use OpenMP across different starting nodes.  The C code is in directory `src/graph/sampling/randomwalks`.  `src/graph/sampler/randomwalk.cc` is deprecated.
