### ISSUE TITLE
confusion about dgl.contrib.sampling.NeighborSampler

### ISSUE THREAD

**Issue by And370** [dmlc/dgl#3330]
I defined the graph,there are just 3 connection with node '0' 
1.when I use the func 'NeighborSampler',the nodeflow.all_edges show me the result
```
(tensor([0, 0, 0, 1, 3, 2, 4]), tensor([ 6,  7,  8, 10, 11, 14, 15]))
```
if I change "add_nodes(node_num)" and "batch_size", the delta will be changed.
but what I expected is the raw data like ```(tensor([0, 0, 0, 1, 3, 2, 4]), tensor([ 1,2,3,5,6,9,10]))```

2.and I defined the num_neighbors = 2,just want to sample 2 neighbors, why output the 3 nodes```tensor([6, 7, 8])```

it is so confused!

env: python==3.7,dgl==0.4
code:
```
import dgl

G = dgl.DGLGraph()
G.add_nodes(100)
# node ‘0’ has 3 connection to [1,2,3]
G.add_edges([0,0,0,1,3,2,5], [1,2,3,5,6,9,10])

G.readonly(True)

# dropout probability
dropout = 0
# batch size
batch_size = 5000
# number of neighbors to sample
num_neighbors = 2
# number of epochs
num_epochs = 0
# layer
L = 1

# print()
for index,nf in enumerate(dgl.contrib.sampling.NeighborSampler(G, batch_size,
                                                               expand_factor=num_neighbors,
                                                               neighbor_type='in',
                                                               shuffle=False,
                                                               num_hops=L,
                                                               )):
    print(index)
    nf.copy_from_parent()
    print(nf.successors(v=0))
    print(nf.all_edges())
```
then the result is:
```
# index
0
# nf.successors(v=0)
tensor([6, 7, 8])
# nf.all_edges()
(tensor([0, 0, 0, 1, 3, 2, 4]), tensor([ 6,  7,  8, 10, 11, 14, 15]))
```

**Comment by VoVAllen** [comment]
dgl.contrib.sampling.NeighborSampler is fully deprecated. Please refer to our latest tutorial

**Comment by VoVAllen** [comment]
https://docs.dgl.ai/tutorials/large/index.html

**Comment by VoVAllen** [comment]
When you specify batch size equals 5000, it covers all the nodes in the graph, which means for each node you sampled two incoming edges, and merge it together as the nodeflow, which is the result you've seen

**Comment by And370** [comment]
Yes,I specify batch size equals 5000 to cover all nodes for test.
I'm not specify the edge between node 0 -> 6 or 7 or 8,just 0 -> 1,2,3.Then why the result is 0 -> 6,7,8
```
# nf.successors(v=0)
tensor([6, 7, 8])
# nf.all_edges()
(tensor([0, 0, 0, 1, 3, 2, 4]), tensor([ 6,  7,  8, 10, 11, 14, 15]))
```

I want know the delta, what happend ? You can run the code which in the top describe.
Thank you so much.

**Comment by BarclayII** [comment]
Since this is about an obsolete version, maybe you can add our Slack channel and we can discuss there?
