### ISSUE TITLE
Memory Leakage Problem

### ISSUE THREAD

**Issue by csypeng** [dmlc/dgl#3348]
## To Reproduce

1. The dataset has 190000 graphs. The graphs are AIDS graphs, which are very commonly used and publicly available. An example is https://github.com/JongikKim/Nass/tree/master/data

2. I use 1 GNN layer and the GNN layer only has a simple message propagation logic as follows

graph.update_all(fn.copy_u('h', 'm'), fn.mean('m', 'h'))

3. Memory keeps growing and finally out of memory

When I rollback to an old version of DGL, i.e.., DGL 0.5.3, the memory problem disappears. 

## Expected behavior

Expect no memory leakage problem.

## Environment

 - DGL Version (e.g., 1.0): 0.7.1, dgl-cu110
 - Backend Library & Version (e.g., PyTorch 0.4.1, MXNet/Gluon 1.3): PyTorch 1.7.1+cu110
 - OS (e.g., Linux): Linux
 - How you installed DGL (`conda`, `pip`, source): pip
 - Build command you used (if compiling from source):
 - Python version: 3.9.6
 - CUDA/cuDNN version (if applicable): 11.0
 - GPU models and configuration (e.g. V100): K80
 - Any other relevant information:

**Comment by VoVAllen** [comment]
Hi,

Could you provide a minimal code for us to reproduce it? And also could you try calling `gc.collect()` and `torch.cuda.empty_cache` to see whether the problem still exists?

**Comment by csypeng** [comment]
How to upload the code? 

I tried gc.collect() and torch.cuda.empty_cache(), but they are not helpful.

**Comment by VoVAllen** [comment]
You can use github gist or Google's colab notebook

**Comment by csypeng** [comment]
The code is here. 

https://gist.github.com/csypeng/a8120e398ceb34d7d5cfa97164196e89

**Comment by shinepig123** [comment]
Have you solved this problem? When I use rgcn to process batch data, its memory increases slowly and was killed finally.

**Comment by csypeng** [comment]
I use an old version of DGL. DGL 0.5.3 works.

**Comment by VoVAllen** [comment]
@csypeng Hi, what's the `train.data` file in your code?

**Comment by csypeng** [comment]
train.data is in the following form:

each line has two gids, separated by a space, and there are many lines
e.g., 
gid1 gid2
gid3 gid4
...

You can find the id of a graph in the AIDS dataset.
t # gid
v 0
v 1
...

**Comment by VoVAllen** [comment]
What's the meaning of each line? Can I just set it as 
1 2
3 4
5 6
...

**Comment by csypeng** [comment]
The numbers are ids of graphs. 
If you have graphs with ids 1, 2, 3, 4, 5, 6, then your set is okay.

**Comment by VoVAllen** [comment]
Hi, I cannot reporduce your issue at my side. I only change the GPUID to 0. Did you have the same issue when setting GPUID to 0? (with single GPU)
Also my dgl version is 0.7.1 with cuda 11.1
