### ISSUE TITLE
GAT on Batch Graph using dgl.batch

### ISSUE THREAD

**Issue by wutaiqiang** [dmlc/dgl#3350]
I build my gat following https://github.com/dmlc/dgl/blob/master/examples/pytorch/gat/gat.py
but it can not handle the batched graph, i have to handle the graphs in my batch one by one.
which is VERY slow.

Reading the docs and i fine the dgl.batch which can batch the small graph into huge one, i wanna to know how to combine the dgl.batch and GAT i use.

**Comment by adhall-synsor** [comment]
Hi, I've the same issue did you find a way to use dgl.batch for GAT?

**Comment by adhall-synsor** [comment]
> I build my gat following https://github.com/dmlc/dgl/blob/master/examples/pytorch/gat/gat.py but it can not handle the batched graph, i have to handle the graphs in my batch one by one. which is VERY slow.
> 
> Reading the docs and i fine the dgl.batch which can batch the small graph into huge one, i wanna to know how to combine the dgl.batch and GAT i use.

@wutaiqiang Hi, I've the same issue did you find a way to use dgl.batch for GAT?

**Comment by wutaiqiang** [comment]
@adhall-synsor I try the following strategy:
1. use the dgl.batch to batch N graphs in a batch into a big one
2. apply the gat network to the big graph
3. use the dgl.unbatch to split the big graph 

something for reference:
https://docs.dgl.ai/en/0.6.x/api/python/dgl.html#batching-and-reading-out-ops

**Comment by niushixiong** [comment]
@wutaiqiang Hi, how to use batch for GAT，can show some code demo?
