### ISSUE TITLE
Support `batch_size = None` for GraphDataLoader

### ISSUE THREAD

**Issue by eliphatfs** [dmlc/dgl#3358]
## 🚀 Feature
Supporting `None` batch size for unbatched parallel data loading, as the PyTorch DataLoader supports.

## Motivation
Currently, when passing None as `batch_size` for GraphDataLoader, it will give an error
```
  ...
  File "dgl/dataloading/dataloader.py", line 823, in collate
    elem = items[0]
  File "dgl/heterograph.py", line 2231, in __getitem__
    raise DGLError('Invalid key "{}". Must be one of the edge types.'.format(orig_key))
dgl._ffi.base.DGLError: Invalid key "0". Must be one of the edge types.
```

In some cases, for example as we want to preprocess data in parallel, it is simpler to use None as batch size so we do not need to implement the parallel data pipeline ourselves.

## Alternatives
A batch size of 1 with manual unbatching may be used, but it is less convenient.

**Comment by BarclayII** [comment]
Actually in DGL a single graph always has a batch size of 1.  So you don't have to do manual unbatching.  Setting batch size to 1 and then directly do stuff on the sampled minibatch should work.

**Comment by eliphatfs** [comment]
We have graph level data.
