### ISSUE TITLE
How to feed numpy adj matrix to DGL in graph format?

### ISSUE THREAD

**Issue by Abhinav43** [dmlc/dgl#3364]
Hi, I am new to this library and having issues understanding the input to the models. I have NumPy adj matrix and features matrix such as 

```
adj_matrix = np.random.randint(0,2,[50,50])
node_feat  = np.random.uniform(-1,1,[50,100])
```

How can I feed this into DGL models directly or convert this data into DGL input format?

**Comment by jwyyy** [comment]
For adjacent matrices, I think you need to convert it into edges first, and then create a DGLGraph using `dgl.graph((src, dst))`. For node features, you can do `your_graph.nodes[your_node_type].data[data_name] = node_feat`. You can read [Chapter 1](https://docs.dgl.ai/guide/graph.html) of the official doc (especially the first 4 sections) for more details.

**Comment by flursky** [comment]
Hi, @Abhinav43 this is how to construct a graph from an adjacency matrix. i hope this helps you
```python
src, dst = np.nonzero(adj_matrix)
g = dgl.graph((src, dst))
g.ndata['feat'] = node_feat
```
