### ISSUE TITLE
Memory leakage in `update_all` using heterogeneous graph

### ISSUE THREAD

**Issue by isratnisa** [dmlc/dgl#3365]
## 🐛 Bug

Using the message passing API `update_all` on heterogeneous (HT) graph accumulates memory with each epoch and eventually runs out of memory. For example, with AM dataset in the RGCN-hetero model, memory consumption is increased by 1GB per epoch (collected by python's line_profiler). Example code snippet from  [PR: RGCN with new heterograph API](https://github.com/dmlc/dgl/pull/3025) :
```        
  for rel in g.canonical_etypes:  
       _, etype, _ = rel  
       g.edges[rel].data['h*w_r'] = th.matmul(g.edges[rel].data['m'], wdict[etype]['weight']  )  
   g.update_all(fn.copy_e('h*w_r', 'm'), fn.sum('m', 'h'))   # triggers bug
```
Replacing the last line with `multi_update_all` solves the issue which mean the bug is indeed coming from the new `update_all` with HT support.

```
 g.multi_update_all({etype : (fn.copy_e('h*w_r', 'm'), fn.sum('m', 'h')) \
           for etype in g.canonical_etypes}, cross_reducer = 'sum')  # works fine
```

I think the bug is caused by Pytorch's autograd function because: 
1. if only inferencing is used (`with th.no_grad():`), the bug doesn't occur anymore.
2. Turning off the [update](https://github.com/dmlc/dgl/blob/bc5cac44265a2234b230d797d41c8d66f43e1c48/python/dgl/heterograph.py#L4892) of destination nodes by the output of `core.message_passing` function, which means the original node features will always be used, avoids causing the bug too.  Probably, the forward function does not store the tensors or intermediate data any more(!)

The issue might be related to Issue: https://github.com/dmlc/dgl/issues/3348

## To Reproduce

1. The [`update_all`](https://github.com/dmlc/dgl/blob/cafff1640deafc74071b503b3d1fb9c9509b06f6/examples/pytorch/rgcn-hetero/model.py#L230) function call in [PR: RGCN with new heterograph API](https://github.com/dmlc/dgl/pull/3025) triggers this issue. 

## Expected behavior

Each epoch in the RGCN model should use the same amount of memory. The memory consumption shouldn't increase or decrease with epochs.

## Environment

 - DGL Version (e.g., 1.0): 0.7, 0.7.1
 - Backend Library & Version (e.g., PyTorch 0.4.1, MXNet/Gluon 1.3): Pytorch 1.9.0+cu111
 - OS (e.g., Linux): Linux
 - How you installed DGL (`conda`, `pip`, source): source
 - Build command you used (if compiling from source):  `cmake -DBUILD_TORCH=ON -DUSE_OPENMP=ON -DUSE_CUDA=ON ..` . The bug occurs with torch flag ON or OFF.
 - Python version: 3.6.9
 - CUDA/cuDNN version (if applicable): 11.1
 - GPU models and configuration (e.g. V100): Tesla T4
 - Any other relevant information:

**Comment by Rhett-Ying** [comment]
just for your information. This is another memory keeps increasing issue I reproduced, but not figured out the root cause yet. I'm not sure it's helpful to debug this issue. https://github.com/dmlc/dgl/issues/3230
