### ISSUE TITLE
Add support for DGLHeteroGraph.to(dtype)

### ISSUE THREAD

**Issue by ksivaman** [dmlc/dgl#3368]
## 🚀 Feature
The current ```DGLHeteroGraph.to``` method takes in only a device type. To make this more similar to torch Tensors, add support for ```DGLHeteroGraph.to(dtype)``` which changes the type of torch Tensors located in the values of ```DGLHeteroGraph.edata``` and ```DGLHeteroGraph.ndata``` dictionaries.

## Motivation
The current API has no trivial method to convert datatypes for the ```edata``` and ```ndata``` dictionaries for ```DGLHeteroGraph``` objects. This makes it incompatible with libraries such as ```NVIDIA/apex```.

**Comment by yzh119** [comment]
Actually we have index data types and data types, idtype was used as graph data structure(node/edge id)'s data type, dtype was used as the feature's data type.

So if we support `.to` method, we must identify which data type we need to convert.

notice: we already have `.int` and `.long` for index data type conversion: https://github.com/dmlc/dgl/blob/01a221443031e0cb820e9fe5c56886eeef3418d0/python/dgl/heterograph.py#L5806-L5904.

**Comment by ksivaman** [comment]
How could the existing API be modified then to be able to support NVIDIA/apex? Currently the following error is the issue when using mixed precision training with apex ```amp```:

![image](https://user-images.githubusercontent.com/36168853/134088478-24e6e9a2-db61-4bab-92ee-30d3d53fa729.png)

**Comment by VoVAllen** [comment]
You don't have to change the graph index type. Just changing the dtype of tensors should work.

**Comment by BarclayII** [comment]
Seems that the problem is Apex treating the graph input as a tensor and trying to apply `to` on the graph, which caused the error.  Is there any way to tell Apex to ignore your graph argument?

**Comment by ksivaman** [comment]
Yes, that can be done to resolve the error, but we still need to cast the ```edata``` and ```ndata``` Tensors to the desired dtype.
