### ISSUE TITLE
【Question】 Negative Sampling 

### ISSUE THREAD

**Issue by Data-Designer** [dmlc/dgl#3370]
https://github.com/dmlc/dgl/blob/bc14829fb36f55de12cc3f39852e5fa21418f947/examples/pytorch/metapath2vec/reading_data.py#L72

target as a parameter is not used here. How can we avoid the situation that the node sample itself? For example (u,v,getNegative(v,5)) will face the worst situation that v samples 'v or u' as negative items.

**Comment by BarclayII** [comment]
In general we noticed that even including the false negative examples the performance impact is minimal.  Although you could remove it afterwards, we found that the additional operation is slow so we deemed not worth it.

Please feel free to follow up.  Thanks!
