### ISSUE TITLE
[Help] libtensoradapter_pytorch_1.9.1 cannot open 

### ISSUE THREAD

**Issue by CHOONGWONII** [dmlc/dgl#3377]
## ❓ Questions and Help

I got an error message when I run my code and the training didn't proceed. 
I use python=3.8 and cuda version 11.1.
When I installed the dgl library, I run "conda install -c dglteam dgl-cuda11.1"

/opt/dgl/src/runtime/tensordispatch.cc:43: TensorDispatcher: dlopen failed: /home/xxx/anaconda3/envs/xxx/lib/python3.8/site-packages/dgl/tensoradapter/pytorch/libtensoradapter_pytorch_1.9.1.so: cannot open shared object file: No such file or directory

**Comment by VoVAllen** [comment]
Hi,

This is an optional dependency. You can ignore the message if this doesn't affect the usage. @BarclayII for visibility

**Comment by ABChh26** [comment]
I use python=3.7and cuda version 10.2.
I got the same error like:
/opt/dgl/src/runtime/tensordispatch.cc:43: TensorDispatcher: dlopen failed: /home/xxx/anaconda3/envs/xxx/lib/python3.8/site-packages/dgl/tensoradapter/pytorch/libtensoradapter_pytorch_1.9.1.so: cannot open shared object file: No such file or directory

it reminds when running "import dgl".

**Comment by zixiaoshuixin** [comment]
> ## ❓问题和帮助
> 当我运行我的代码并且培训没有继续时，我收到一条错误消息。 我使用 python=3.8 和 cuda 版本 11.1。 当我安装 dgl 库时，我运行“conda install -c dglteam dgl-cuda11.1”
> 
> /opt/dgl/src/runtime/tensordispatch.cc:43：TensorDispatcher：dlopen 失败：/home/xxx/anaconda3/envs/xxx/lib/python3.8/site-packages/dgl/tensoradapter/pytorch/libtensoradapter_pytorch_1.9.1 .so：无法打开共享对象文件：没有这样的文件或目录

我也遇到了同样的问题，请问您解决了吗

**Comment by zixiaoshuixin** [comment]
> ## ❓ Questions and Help
> I got an error message when I run my code and the training didn't proceed. I use python=3.8 and cuda version 11.1. When I installed the dgl library, I run "conda install -c dglteam dgl-cuda11.1"
> 
> /opt/dgl/src/runtime/tensordispatch.cc:43: TensorDispatcher: dlopen failed: /home/xxx/anaconda3/envs/xxx/lib/python3.8/site-packages/dgl/tensoradapter/pytorch/libtensoradapter_pytorch_1.9.1.so: cannot open shared object file: No such file or directory

I also encountered the same problem, I would like to ask you if you have solved it and how to solve it.

**Comment by BarclayII** [comment]
@zixiaoshuixin This doesn't affect the usage and it is removed in 0.8+.
