### ISSUE TITLE
AttributeError: 'NodeEmbedding' object has no attribute 'all_set_embedding' and 'all_get_embedding'

### ISSUE THREAD

**Issue by Ian-Shu** [dmlc/dgl#3380]
The code I call NodeEmbedding is as follows:
      
        dgl_emb = NodeEmbedding(g.number_of_nodes(), self.dim, 'node_emb')
        dgl_emb.all_set_embedding(init_emb)
        g.ndata['user_embeddings'] = dgl_emb.all_get_embedding()

but I got an error: AttributeError: 'NodeEmbedding' object has no attribute 'all_set_embedding'/'all_get_embedding'.

Are 'all_set_embedding' and 'all_get_embedding ' functions available in the NodeEmbedding class? Thanks for your answer.
My dgl version is  0.6.1  and my backend is pytorch.

**Comment by classicsong** [comment]
Can you try dgl 0.7?

**Comment by Ian-Shu** [comment]
> Can you try dgl 0.7?
DGL 0.7 already has these functions, thank you

**Comment by Rhett-Ying** [comment]
no more questions/issues. let's close it.
