### ISSUE TITLE
[Saving/Loading] Allow caching CSR-related data structures to disk (`dgl.[load,save]_graphs()`)

### ISSUE THREAD

**Issue by erickim555** [dmlc/dgl#3384]
## 🚀 Feature
Currently, `dgl.[load,save]_graphs()` will serialize/deserialize graphs to disk and store the data required to create a graph in COO format.
Proposal: if a graph has the other graph formats "csr, csc" already created, then allow the user to also serialize these "csr, csc" representations to disk. This would avoid having to re-compute the COOToCSR/CSC conversions at run time.

## Motivation
For random walks, DGL requires the CSR graph format. In my use case, where I create my graph in COO (to my knowledge, in Python we can only create graphs in COO format initially), the COOToCSR() conversion can take up to 10 minutes with my 2B node, 2B edge graph. 
Even if I serialize my graph (after the COOToCSR() call) to disk via `dgl.save_graphs(), dgl.load_graphs()`, the loaded graph only contains the COO representation, not the CSR, so I always have to recompute the COOToCSR(), which is a bit of a pain.

I'm unsure what the disk space implications would be, eg whether storing CSR to disk is too space intensive?

**Comment by VoVAllen** [comment]
Hi,

Currently you can use `g_csr = g.formats(['csr'])` to force converting graph to csr format and dgl.save_graphs will use this csr format also. We'll consider support storing multiple formats in the future

**Comment by VoVAllen** [comment]
For graph loading, I think it's bounded by the disk IO and it's almost pure serial reading, which maximized the IO. Therefore I don't think multithread would help here. It may only help if you have lots of graph to read I think. Did you see much overhead in the `load_graph` operation?
