### ISSUE TITLE
Bugs in nxgraph(mxnet) to DGLgraph

### ISSUE THREAD

**Issue by sufeidechabei** [dmlc/dgl#339]
## To Reproduce

```
 # create graph
 g = DGLGraph(data.graph)
```

```
dgl._ffi.base.DGLError: Error while creating graph from input of type "<class 'networkx.classes.digraph.DiGraph'>".

```

## Environment

 - DGL Version (e.g., 1.0): 0.1.3
 - Backend Library & Version (e.g., PyTorch 0.4.1, MXNet/Gluon 1.3): MXNet
 - OS (e.g., Linux): Linux
 - How you installed DGL (`conda`, `pip`, source): pip
 - Python version: 3.6.7
 - CUDA/cuDNN version (if applicable): 9.0
 - GPU models and configuration (e.g. V100): V100
 - Any other relevant information: networkx(2.2)

**Comment by mufeili** [comment]
I assume this is a different issue from #334 ? Could you please provide a snippet of code with which we can really run and reproduce the issue?

**Comment by sufeidechabei** [comment]
examples/mxnet/gat_batch.py @mufeili

**Comment by mufeili** [comment]
@sufeidechabei I reproduced the problem with running `mxnet 1.3.0` on cpu. This problem does not occur with running `mxnet 1.5.0` on cpu. You can install `mxnet 1.5.0` with `pip install --pre mxnet`.

**Comment by sufeidechabei** [comment]
okay, thanks.

**Comment by sufeidechabei** [comment]
Do we need to inform the version of mxnet?

**Comment by jermainewang** [comment]
The version is nightly built. See build instruction here: https://docs.dgl.ai/install/index.html#working-with-different-backends.
