### ISSUE TITLE
Bug for disconnected nodes in the block graph during message passing

### ISSUE THREAD

**Issue by bioannidis** [dmlc/dgl#3395]
## 🐛 Bug

 When the block graph is disconnected during mini batch training or inference, which means that all the target nodes are not connected in the graph and hence the bipartite block graph is comprised by source nodes that are the same as the target nodes but without any connection among source nodes and destination nodes the dgl.nn.GraphConv layer will return an **empty dictionary**. Because the result is an empty dictionary the self-loop is not applied and hence the result of the overall hetero RGCN model will be an empty dictionary. On the other hand if even one connection exists in the block graph the result will **not** be an empty dictionary but will contain all zero vectors for disconnected nodes. This problem appears in our application since we may have disconnected nodes for which we require the embeddings.

## To Reproduce
Run the hetero RGCN in graphs with disconnected nodes and small batch size.

## Expected behavior
Expected behavior should be to return a zero vector after message passing.

## Environment

 - DGL Version (e.g., 1.0): Latest
 - Backend Library & Version (e.g., PyTorch 0.4.1, MXNet/Gluon 1.3): Standart
 - OS (e.g., Linux):
 - How you installed DGL (`conda`, `pip`, source):
 - Build command you used (if compiling from source):
 - Python version:
 - CUDA/cuDNN version (if applicable):
 - GPU models and configuration (e.g. V100):
 - Any other relevant information:

**Comment by Rhett-Ying** [comment]
`block = dgl.create_block(([],[]), num_src_nodes=4, num_dst_nodes=4)
feat = torch.rand(4, 10)
conv = dgl.nn.GraphConv(10, 2, allow_zero_in_degree=True)
res = conv(block, feat)
print(res)`

Is the code shown above what you depict? For this code snippet, zero tensor with shape of (4,2) is printed.

**Comment by bioannidis** [comment]
Can you try to create a dgl graph without connections, sample a block from that graph with data loading and use the dglheteroconv with a graphconv layer to reproduce?

**Comment by Rhett-Ying** [comment]
fix is merged into master. pls have a try.
