### ISSUE TITLE
heterogeneous graph: what if different graph instance contain slightly different metadata?

### ISSUE THREAD

**Issue by wadmes** [dmlc/dgl#3397]
For example, given 100 heterogeneous graphs, some of them have the edge type "author (works with) author" while such a edge type does not exist in other graphs in the 100 ones.

One idea is to generate "virtual nodes and edges" to make up non-existing edge types (node types) and all graphs have the same metadata, which is actually the union of all metadata in different graphs.

But this one may be too dirty and harms efficiency. Any better solution?

**Comment by Rhett-Ying** [comment]
duplicate with https://discuss.dgl.ai/t/heterogeneous-graph-what-if-different-graph-instance-contain-slightly-different-metadata/2385/2. let's discuss in that thread.
