### ISSUE TITLE
In distributed DGL, how can I get the network overhead?

### ISSUE THREAD

**Issue by Ningsir** [dmlc/dgl#3403]
## ❓ Questions and Help

In distributed DGL, network communication occurs during the sampling and backward propogation stage.I want to know the network communication and computation overhead respectively.How can I get the network overhead in distributed DGL?

**Comment by VoVAllen** [comment]
Currently we don't have such metrics. May I ask what kind of network overhead are you referring to? Do you mean the pure network transmission time?
