### ISSUE TITLE
[Distributed][Metis] Partitioning a graph assumes its in 64-bit format.

### ISSUE THREAD

**Issue by nv-dlasalle** [dmlc/dgl#3405]
## 🐛 Bug

`Convert2GKCsr()` assumes the graph is in 64-bit format, and leads to undefined behavior if it is not.
https://github.com/dmlc/dgl/blob/master/src/graph/gk_ops.cc#L26

## To Reproduce

1. Create a dgl.heterograph from a 32-bit edge list.
1. Call dgl.distributed.partition_graph() on it.
1. `Convert2GKCsr()` will then cast the `indptr` and `indices` to `dgl_id_t` without checking the `dtype`.

## Expected behavior
`Convert2GKCsr()` should check the dtype before making the cast, and either change the type based on that or raise an error.

## Environment

 - DGL Version (e.g., 1.0): 0.7.1
 - Backend Library & Version (e.g., PyTorch 0.4.1, MXNet/Gluon 1.3): Pytorch 1.9.1
 - OS (e.g., Linux): LInux
 - How you installed DGL (`conda`, `pip`, source): pip
 - Build command you used (if compiling from source):
 - Python version: 3.6
 - CUDA/cuDNN version (if applicable): 11.3
 - GPU models and configuration (e.g. V100): TitanV
 - Any other relevant information:

**Comment by Rhett-Ying** [comment]
reproduced. seems such check is missing in other files as well such as `grpah_op.cc`. data type conversion is a bit messy.
