### ISSUE TITLE
the edges in partitions constructed by convert_partition.py don't have a right order

### ISSUE THREAD

**Issue by zheng-da** [dmlc/dgl#3421]
## 🐛 Bug

The edges in a graph partition should be ordered based on the edge type. However, the partitions constructed by convert_partition.py don't have the right order for edges mainly because `node_subgraph` (https://github.com/dmlc/dgl/blob/master/tools/convert_partition.py#L218) doesn't preserve the original edge IDs after shuffling node IDs.

## To Reproduce

1.
1.
1.

## Environment

 - DGL Version (e.g., 1.0):
 - Backend Library & Version (e.g., PyTorch 0.4.1, MXNet/Gluon 1.3):
 - OS (e.g., Linux):
 - How you installed DGL (`conda`, `pip`, source):
 - Build command you used (if compiling from source):
 - Python version:
 - CUDA/cuDNN version (if applicable):
 - GPU models and configuration (e.g. V100):
 - Any other relevant information:

**Comment by Rhett-Ying** [comment]
fixed in https://github.com/dmlc/dgl/pull/3472.
