### ISSUE TITLE
The behaviour of ‘graph.formats()’ is not clear, and the degree information cannot be obtained in CSC format

### ISSUE THREAD

**Issue by I-Doctor** [dmlc/dgl#3438]
## To Reproduce

run this code:
```
import dgl
import torch as th
g = dgl.graph(
    (th.tensor([3, 5, 3]), th.tensor([1, 5, 2])),
)
print("g formats 1: ", g.formats())
degs = g.out_degrees().float()
print("degs: ", degs)

g=g.formats(['csr'])
print("g formats 2: ", g.formats())
degs = g.out_degrees().float()
print("degs: ", degs)

g=g.formats(['coo','csr','csc'])
print("g formats 3: ", g.formats())
degs = g.out_degrees().float()
print("degs: ", degs)

g=g.formats(['csr','csc'])
print("g formats 4: ", g.formats())
degs = g.out_degrees().float()
print("degs: ", degs)

g=g.formats(['coo','csc'])
print("g formats 5: ", g.formats())
degs = g.out_degrees().float()
print("degs: ", degs)

g=g.formats(['csc'])
print("g formats 6: ", g.formats())
degs = g.out_degrees().float()
print("degs: ", degs)
degs = g.in_degrees().float()
print("degs: ", degs)
```
get output:
```
g formats 1:  {'created': ['coo'], 'not created': ['csr', 'csc']}
degs:  tensor([0., 0., 0., 2., 0., 1.])
g formats 2:  {'created': ['csr'], 'not created': []}
degs:  tensor([0., 0., 0., 2., 0., 1.])
g formats 3:  {'created': ['csr'], 'not created': ['coo', 'csc']}
degs:  tensor([0., 0., 0., 2., 0., 1.])
g formats 4:  {'created': ['csr'], 'not created': ['csc']}
degs:  tensor([0., 0., 0., 2., 0., 1.])
g formats 5:  {'created': ['coo'], 'not created': ['csc']}
degs:  tensor([0., 0., 0., 2., 0., 1.])
g formats 6:  {'created': ['csc'], 'not created': []}
degs:  tensor([0., 1., 1., 0., 0., 1.])
degs:  tensor([0., 1., 1., 0., 0., 1.])
```

## Expected behavior
The output where 'csc' or 'coo' is not created is hard to understand. And the degree can not be obtained in CSC format.

## Environment

 - DGL Version (0.7.1)
 - Backend Library & Version (PyTorch 1.9.1)
 - OS (Ubuntu 18.04)
 - How you installed DGL (conda)
 - Python version: 3.8.8
 - CUDA/cuDNN version (if applicable): cuda11.1 cudnn8.0.5
 - GPU models and configuration (RTX 3090)

**Comment by Rhett-Ying** [comment]
1. OutDegrees of csc graph is not correct. thanks for reporting this. I will fix it.
2. as for the not created formats, it indicates these format are available, but not created for now. They will be created when needed.

**Comment by Rhett-Ying** [comment]
we have just merged https://github.com/dmlc/dgl/pull/3477 that aims to obtain correct results if degree is available or throw exception if degree is not available for some cases.

In details, for now, in_degrees() can be obtained if and only if CSC or COO format is allowed for this graph. out_degrees() can be obtained if and only if CSR or COO format is allowed. otherwise, such call will cause crash on purpose. Namely, in the case you mentioned, out_degrees() will throw exception for `g.formats('csc')`.

This behavior is not good enough and should be improved in the near future.
