### ISSUE TITLE
Finding edge and node information for stochastic link prediction

### ISSUE THREAD

**Issue by tanvirbKash** [dmlc/dgl#3439]
## ❓ Questions and Help

I am using stochastic link prediction to predict possible new links between nodes, but during testing phase, how do I find the nodes the model is predicting new links for or the information regarding new links? For example, node ids seem to be lost during converting the dgl Graph to data loader using dgl.dataloading.EdgeDataLoader()

**Comment by jermainewang** [comment]
Look like a similar question of #3447 . Let's move discussion there.
