### ISSUE TITLE
[Dist][ParMETIS]Same node is partitioned into multiple parts as dest node when partitioning across machines

### ISSUE THREAD

**Issue by Rhett-Ying** [dmlc/dgl#3443]
## 🐛 Bug

when partition large graph into partitions across machines via calling `mpirun --hostfile hostfile -np 2 pm_dglpart mag 1`, some nodes are partitioned into multiple partitions as destination nodes. This is not expected. We expect one node can only be partitioned into one partition as a destination node.

This issue does exist even when partitioning on single machine via `pm_dglpart mag 2`.

This issue is probably caused by duplicate edges existence in graph which is converted from heterograph to homo.
## To Reproduce

1. cd //examples/pytorch/rgcn/experimental/
2. python3 write_mag.py
3. mpirun -np 2 pm_dglpart mag 1
4. check if <orig_dst_id, etype_type> exists in multiple pxxx-mag_edges.txt.

## Expected behavior
<dist_id, etype_id> exists in single one pxxx-mag_edges.txt only.

## Environment

 - DGL Version (e.g., 1.0):
 - Backend Library & Version (e.g., PyTorch 0.4.1, MXNet/Gluon 1.3):
 - OS (e.g., Linux):
 - How you installed DGL (`conda`, `pip`, source):
 - Build command you used (if compiling from source):
 - Python version:
 - CUDA/cuDNN version (if applicable):
 - GPU models and configuration (e.g. V100):
 - Any other relevant information:

**Comment by Rhett-Ying** [comment]
As this issues exists on multi-graph only and https://github.com/dmlc/dgl/pull/3472 bypasses this issue by removing duplicate edges beforehand and added back after ParMETIS, we do have a FIX/WAR now. I think it's ok to close this issue now, though it's better to enable multi-graph in ParMETIS(much efforts are probably required).

**Comment by Rhett-Ying** [comment]
I was wrong. Even self-loops and duplicate edges are removed beforehand, nodes have a chance to be partitioned into multiple parts as dst node. **ISSUE IS NOT FIXED** yet. this could be reproduced (almost 100% with num_parts as 2) with latest code in `//dgl/examples/pytorch/rgcn/experimental/write_mag.py`(this is where self-loops and duplicate edges are removed) as mentioned in the ticket header. I think we have to look deep into ParMETIS (pm_dglpart) code. any suggestions on how to debug in `pm_dglpart`? @karypis

**Comment by ankit-garg** [comment]
> ParMetis does not support multi-graphs. However, this case can potentially be handled as part of the pre-processing that pm_dglpart is doing.

I have made a commit to retain multi edges : https://github.com/dmlc/dgl/pull/3137/files

**Comment by Rhett-Ying** [comment]
@ankit-garg thanks for your mention. I'm aware of that commit. But this issue remains exist even we merged another commit which removes duplicate edges beforehand.

**Comment by Rhett-Ying** [comment]
Fixed in `ParMETIS`: https://github.com/KarypisLab/ParMETIS/commit/71d24f40436c4ed9b5ca0da4dd37d454cbc21a73. The root cause is edges were partitioned based on `src_id` instead of `dst_id`. 

I have verified on `ogb-mag` under `//examples/pytorch/rgcn/experimental/` via `grep " " p0*edges.txt | awk '{printf("%s %d\n", substr($0, 0, 4), $4)}' | sort | uniq| awk '{print $2}' | sort | uniq -c | awk '{if ($1>1)ndup++}END{printf("ndup=%d\n", ndup)}'`
