### ISSUE TITLE
Feature vwctors

### ISSUE THREAD

**Issue by Abdullahi-Sherko** [dmlc/dgl#3460]
### hi I am sherko,
Thank you for your great lovely dgl package.
I have got a question on node classification. After the training, the node features should be updated but it does not!!
----------------------------------------------------------------------------------------------------------------------------------------g.ndata['feat']:
tensor([[0., 0., 0.,  ..., 0., 0., 0.],
        [0., 0., 0.,  ..., 0., 0., 0.],
        [0., 0., 0.,  ..., 0., 0., 0.],
        ...,
        [0., 0., 0.,  ..., 0., 0., 0.],
        [0., 0., 0.,  ..., 0., 0., 0.],
        [0., 0., 0.,  ..., 0., 0., 0.]])

after training I got same vectors as above!!!!

Thank you so much for your answering.

**Comment by VoVAllen** [comment]
Hi,

Do not initialize node feature as all zeros. At least try all ones or refer to the Question 14 at https://discuss.dgl.ai/t/frequently-asked-questions-faq/1681
