### ISSUE TITLE
[rgcn][experimental] run the distributed rgcn  (entity_classify_dist.py)  fails

### ISSUE THREAD

**Issue by luoyeguigen001** [dmlc/dgl#3462]
## 🐛 Bug

when i run the examples/pytorch/rgcn/experimental/entity_classify_dist.py, some errors have occurred. 

## To Reproduce

1. cd dgl/examples/pytorch/rgcn/experimental
2. python3 partition_graph.py --dataset ogbn-mag --num_parts 2 --balance_train --balance_edges
3. config ip_config.txt and others 
4. python3 ~/workspace/dgl/tools/launch.py \
--workspace ~/workspace/dgl/examples/pytorch/rgcn/experimental/ \
--num_trainers 1 \
--num_servers 1 \
--num_samplers 4 \
--part_config data/ogbn-mag.json \
--ip_config ip_config.txt \
"python3 entity_classify_dist.py --graph-name ogbn-mag --dataset ogbn-mag --fanout='25,25' --batch-size 1024  --n-hidden 64 --lr 0.01 --eval-batch-size 1024  --low-mem --dropout 0.5 --use-self-loop --n-bases 2 --n-epochs 3 --layer-norm --ip-config ip_config.txt  --sparse-embedding --sparse-lr 0.06 --num_gpus 1"

### code
```
def run(args, device, data):
    g, num_classes, train_nid, val_nid, test_nid, labels, all_val_nid, all_test_nid = data

    fanouts = [int(fanout) for fanout in args.fanout.split(',')]
    val_fanouts = [int(fanout) for fanout in args.validation_fanout.split(',')]

    sampler = dgl.dataloading.MultiLayerNeighborSampler(fanouts)
    dataloader = dgl.dataloading.NodeDataLoader(
        g,
        {'paper': train_nid},
        sampler,
        batch_size=args.batch_size,
        shuffle=True,
        drop_last=False)

    valid_sampler = dgl.dataloading.MultiLayerNeighborSampler(val_fanouts)
    valid_dataloader = dgl.dataloading.NodeDataLoader(
        g,
        {'paper': val_nid},
        valid_sampler,
        batch_size=args.batch_size,
        shuffle=False,
        drop_last=False)

    test_sampler = dgl.dataloading.MultiLayerNeighborSampler(val_fanouts)
    test_dataloader = dgl.dataloading.NodeDataLoader(
        g,
        {'paper': test_nid},
        test_sampler,
        batch_size=args.eval_batch_size,
        shuffle=False,
        drop_last=False)
....
```

### errors:
```
Traceback (most recent call last):
 File "entity_classify_dist.py", line 643, in <module>
    main(args)
  File "entity_classify_dist.py", line 583, in main
    run(args, device, (g, n_classes, train_nid, val_nid, test_nid, labels, all_val_nid, all_test_nid))
  File "entity_classify_dist.py", line 375, in run
    drop_last=False)
  File "/usr/local/lib/python3.6/dist-packages/dgl/dataloading/pytorch/dataloader.py", line 502, in __init__
    **dataloader_kwargs)
  File "/usr/local/lib/python3.6/dist-packages/dgl/distributed/dist_dataloader.py", line 80, in __init__
    self.dataset = F.tensor(dataset)
  File "/usr/local/lib/python3.6/dist-packages/dgl/backend/pytorch/tensor.py", line 46, in tensor
    return th.as_tensor(data, dtype=dtype)
ValueError: too many dimensions 'str'
```

## Environment

 - DGL Version (0.7.1):
 - Backend Library & Version ( PyTorch 1.10 or 1.09):
 - How you installed DGL (`conda`, `pip`, source):
 - Python version: 3.6.9
 - run in cpu

**Comment by VoVAllen** [comment]
Bug confirmed

**Comment by VoVAllen** [comment]
Hi,

Please try our nightly version for dist rgcn. It's not supported in 0.7.1
