### ISSUE TITLE
Allow to select libxsmm from system

### ISSUE THREAD

**Issue by ccoulombe** [dmlc/dgl#3464]
## 🚀 Feature
Allow to select libxsmm already installed from the system.

## Motivation

Smaller footprint wheel, optimized libxsmm rather than generic.

**Comment by mufeili** [comment]
We have no expertise in it. Could you make an contribution for it?

**Comment by BarclayII** [comment]
One concern is that we are not sure if LibXSMM's interface is stable enough to enable dynamic linkage - we may eventually need to release one wheel per version which quickly becomes unmanageable.  Our policy currently is to have as many static linkage as the wheel size permits (currently it's 100M which is OK).

**Comment by ccoulombe** [comment]
Can this be revisited? ;) It would allow for optimized pre-built wheel on our systems.
