### ISSUE TITLE
Allow to set cuda archs

### ISSUE THREAD

**Issue by ccoulombe** [dmlc/dgl#3465]
## 🚀 Feature
Since compute capabilities under 6.0 are deprecated with cuda 11.4. It should be possible to set the desired compute capabilities when building DGL. 

https://docs.nvidia.com/cuda/cuda-toolkit-release-notes/index.html#title-new-cuda-libraries

## Motivation

Deprecation of older compute capabilities, build for target GPUs within HPC centres not available on build infrastructure.

## Alternatives

Hardcode compute capabilities, not ideal.
Using `-DCUDA_ARCH_NAME=Manual` or listing arch names does not work with current CMake module. 

## Pitch
Support and listen to: `cmake -DCMAKE_CUDA_ARCHITECTURES='6.0;7.0;7.5;8.0'`. Or equivalent.

## Additional context

Since Cmake 3.18, Cmake support `CMAKE_CUDA_ARCHITECTURES` to set cuda compute capabilities.
https://cmake.org/cmake/help/git-stage/variable/CMAKE_CUDA_ARCHITECTURES.html

**Comment by VoVAllen** [comment]
Hi,

You can use `cmake -DCUDA_ARCH_BIN="60;70;75;80" -DCUDA_ARCH_NAME="Manual" ..` to select CUDA arch. We had a customized cuda build module at https://github.com/dmlc/dgl/blob/9c41e97cc02a5b2e69d807d7d6e598dea92046a9/cmake/modules/CUDA.cmake, for backward compatibility

**Comment by mboisson** [comment]
Using CMake's built-in CUDA_ARCHITECTURES would be better than defining your own custom variable.
