### ISSUE TITLE
heteroGraph.ndata.keys() throw TypeError

### ISSUE THREAD

**Issue by maqy1995** [dmlc/dgl#3466]
## 🐛 Bug

heteroGraph.ndata.keys() throw TypeError: list indices must be integers or slices, not list

## To Reproduce

```shell
Successfully installed dgl-cu102-0.7.1
(work) maqy@ubuntu:~$ python
Python 3.7.9 (default, Aug 31 2020, 12:42:55) 
[GCC 7.3.0] :: Anaconda, Inc. on linux
Type "help", "copyright", "credits" or "license" for more information.
>>> import dgl
Using backend: pytorch
>>> import torch as th
>>> g = dgl.heterograph({('drug', 'interacts', 'drug'): (th.tensor([0, 1]), th.tensor([1, 2])),('drug', 'treats', 'disease'): (th.tensor([1]), th.tensor([2]))})
>>> g.nodes['drug'].data['hv'] = th.zeros(3, 1)
>>> g.nodes['disease'].data['hv'] = th.ones(3, 1)
>>> g.edges['interacts'].data['he'] = th.zeros(2, 1)
>>> g.edges['treats'].data['he'] = th.zeros(1, 2)
>>> g.ndata.keys()
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "/home/maqy/miniconda3/envs/work/lib/python3.7/site-packages/dgl/view.py", line 105, in keys
    return self._graph._node_frames[self._ntid].keys()
TypeError: list indices must be integers or slices, not list
```

## Expected behavior

return a list of keys. 

-------------edit line-----------------
I'm not sure if this is a bug because `g.ndata['hv'].keys()` works fine. But when I type `g.ndata.`,  here is a `.keys()` api to use.

## Environment

 - DGL Version (e.g., 1.0):  dgl-cu102-0.7.1
 - Backend Library & Version (e.g., PyTorch 0.4.1, MXNet/Gluon 1.3): torch 1.8.1
 - OS (e.g., Linux): ubuntu18.04
 - How you installed DGL (`conda`, `pip`, source): pip
 - Build command you used (if compiling from source): no
 - Python version: 3.7
 - CUDA/cuDNN version (if applicable):  10.2
 - GPU models and configuration (e.g. V100):  2060s

**Comment by mufeili** [comment]
Since you have multiple node types and different features for each node type, you will need to use something like `g.nodes['drug'].data.keys()` instead.

**Comment by maqy1995** [comment]
@mufeili ,
thank you for your reply. I want to use `dgl.to_homogeneous(hetero_g, ndata=hetero_g_all_ndata)`  to convert a hetero graph to a homo-graph and keep the ndata. is there any easy way to get all of the features' names in a hetero graph?

**Comment by mufeili** [comment]
See the description of `ndata` argument for [`to_homogeneous`](https://docs.dgl.ai/generated/dgl.to_homogeneous.html#dgl.to_homogeneous).
