### ISSUE TITLE
Dependency 'requests' not included with conda installation

### ISSUE THREAD

**Issue by patrickgrad** [dmlc/dgl#347]
## 🐛 Bug
It seems that the required 'requests' library is not included when installing DGL through conda. 

## To Reproduce
This can be seen by running one of the example codes in a fresh conda environment(with no raw data downloaded).

conda create -n new_env python
conda activate new_env
conda install -c dglteam dgl
conda install pytorch
python examples/pytorch/gcn/gcn.py --dataset cora

**Comment by jermainewang** [comment]
The main package does not depend on `request` package. It is used in the examples to download data. But agree we should put an `requirements.txt` under the GCN folder.

**Comment by jermainewang** [comment]
Included in #355
