### ISSUE TITLE
Where is the code about the implementation of spmm and sddmm?

### ISSUE THREAD

**Issue by Ningsir** [dmlc/dgl#3480]
## ❓ Questions and Help

there is the interface code of [spmm](https://github.com/dmlc/dgl/blob/master/python/dgl/ops/spmm.py). I want to know where is the code about the implementation of spmm and sddmm, such as cuda code or cpp code.

**Comment by yzh119** [comment]
They are inside [this folder](https://github.com/dmlc/dgl/tree/master/src/array), check the `cpu`/`cuda` directory.

**Comment by Ningsir** [comment]
thx

**Comment by Ningsir** [comment]
SpMMCsr supports CSR matrix format, but why does this code use CSCMatrix [https://github.com/dmlc/dgl/blob/master/src/array/kernel.cc#L39-L42](https://github.com/dmlc/dgl/blob/master/src/array/kernel.cc#L39-L42)

**Comment by VoVAllen** [comment]
@Ningsir CSR is the format name. The format of CSC can be considered as CSR. It's just the transpose of one another.

**Comment by Ningsir** [comment]
Thx. But I am still confused about which kernel is invoked. For example, _CAPI_DGLKernelSpMM function in [https://github.com/dmlc/dgl/blob/master/python/dgl/sparse.py#L167-L172](https://github.com/dmlc/dgl/blob/master/python/dgl/sparse.py#L167-L172) will invoke which kernel in cuda.

**Comment by yzh119** [comment]
@Ningsir corresponding CAPI was defined [here](https://github.com/dmlc/dgl/blob/298e4fa6274d81460d9578501d0d7599d3a318f0/src/array/kernel.cc#L294), I suggest you using [ffi-navigator](https://github.com/tqchen/ffi-navigator) to navigate the source code.
