### ISSUE TITLE
Is there a function to merge graphs？

### ISSUE THREAD

**Issue by ZhouMingjie-code** [dmlc/dgl#3488]
## ❓ Questions and Help

Before proceeding, please note that we recommend
using our discussion forum (https://discuss.dgl.ai) for
general questions. As a result, this issue will
likely be CLOSED shortly.

**Comment by VoVAllen** [comment]
Does dgl.batch works for you?

**Comment by ZhouMingjie-code** [comment]
Thank you! But dgl.batch will reset index. It is not what i want. 

> Does dgl.batch work for you?

**Comment by ZhouMingjie-code** [comment]
For example, g1 has nodes[0,1,2,3,4] and g2 has nodes[0,2,4,6,8]. I want to get a big graph with nodes[0,1,2,3,4,6,8]

**Comment by ZhouMingjie-code** [comment]
For example, g1 has nodes[0,1,2,3,4] and g2 has nodes[0,2,4,6,8]. I want to get a big graph with nodes[0,1,2,3,4,6,8]

**Comment by VoVAllen** [comment]
I don't think we have such function. But You can achieve this by concating the edge array of each graph.
