### ISSUE TITLE
Is there a function to find all khop neighbor nodes around a node

### ISSUE THREAD

**Issue by ZhouMingjie-code** [dmlc/dgl#3489]
## ❓ Questions and Help

Before proceeding, please note that we recommend
using our discussion forum (https://discuss.dgl.ai) for
general questions. As a result, this issue will
likely be CLOSED shortly.

**Comment by BarclayII** [comment]
Although not exactly the same, there is a k-hop subgraph sampler in PR #3487 .

**Comment by BarclayII** [comment]
Also there is a PR in #3458 .
