### ISSUE TITLE
[Bug] FileExistsError when sometimes importing dgl from multiprocess training

### ISSUE THREAD

**Issue by erickim555** [dmlc/dgl#3492]
## 🐛 Bug
Sometimes, when I launch my Pytorch distributed trainer (which spawns multiple trainer processes, eg once for each GPU for multi-gpu model training), my training job fails with the following error:

```
# pardon the possibly out-of-order stack trace, multiple processes are interleaving the stdout
    import dgl
Traceback (most recent call last):
  File "/usr/local/lib/python3.7/site-packages/dgl/__init__.py", line 13, in <module>
    from .backend import load_backend, backend_name
  File "/usr/local/lib/python3.7/os.py", line 221, in makedirs
    mkdir(name, mode)
  File "trainer/utils/cli.py", line 137, in <module>
    locals()["run_" + args.which](args, extra)
  File "/usr/local/lib/python3.7/site-packages/dgl/backend/__init__.py", line 107, in <module>
    load_backend(get_preferred_backend())
  File "trainer/utils/cli.py", line 27, in run_local
    trainer_class = locate(args.trainer)
FileExistsError: [Errno 17] File exists: '/root/.dgl'
  File "/usr/local/lib/python3.7/site-packages/dgl/backend/__init__.py", line 103, in get_preferred_backend
    set_default_backend(default_dir, 'pytorch')
FileExistsError: [Errno 17] File exists: '/root/.dgl'
```

I see this occur fairly often, say ~10-20% of the time. Usually, retrying the train command fixes things.

For what it's worth: I am running this within a Docker container, using a DGL nightly build from `2021-10-18`

## To Reproduce

I don't have a repro script. But, hopefully this stack trace can point out a diagnosis + fix.

## Expected behavior

Importing dgl shouldn't cause an error.

## Environment

 - DGL Version (e.g., 1.0): >0.7 (Nightly build from 2021-10-18).
 - Backend Library & Version (e.g., PyTorch 0.4.1, MXNet/Gluon 1.3):
 - OS (e.g., Linux): Linux
 - How you installed DGL (`conda`, `pip`, source): From nightly
 - Build command you used (if compiling from source):
 - Python version: 3.7
 - CUDA/cuDNN version (if applicable):
 - GPU models and configuration (e.g. V100):
 - Any other relevant information:

**Comment by VoVAllen** [comment]
hi,

sorry for the inconvenience. You can try executing import dgl seperately before everything. Such a s `python -c 'import dgl'`. The reason is that it'll create config file. We'll consider adding Filelock for this in the future
