### ISSUE TITLE
Bug in dgl.data dataset

### ISSUE THREAD

**Issue by littleTown93** [dmlc/dgl#3494]
## Environment

 - DGL Version (0.6.1):
 - Backend Library & Version (PyTorch 1.10.0):
 - OS (Windows):
 - How you installed DGL (pip):
 - Build command you used (pip install dgl):
 - Python version: 3.7.11

## code
import dgl

dataset = dgl.data.CoraGraphDataset()
g = dataset[0]

##error

RuntimeError: Bool type is not supported by dlpack

**Comment by BarclayII** [comment]
This should be fixed in 0.7.2.
