### ISSUE TITLE
Failed to generate libxsmm kernel for the SpMM operation!

### ISSUE THREAD

**Issue by xiangyuwei** [dmlc/dgl#3499]
## ❓ Questions and Help

I have the error informaiton:

dgl._ffi.base.DGLError: [21:49:25] /opt/dgl/src/array/cpu/./spmm_blocking_libxsmm.h:267: Failed to generate libxsmm kernel for the SpMM operation!   How to fix it?

**Comment by BarclayII** [comment]
Potentially a duplicate of #3476
