### ISSUE TITLE
reproduce the code of NodeAug

### ISSUE THREAD

**Issue by ZoeyChen-lab** [dmlc/dgl#3508]
Is it possible to reproduce the method mentioned in the paper [NodeAug: semi-supervised node classification with data augmentation](https://bhooi.github.io/papers/nodeaug_kdd20.pdf)?

**Comment by BarclayII** [comment]
If I got it right, NodeAug involves adding some random edges, removing some random edges, and changing the attributes.  You can do that by customizing the neighbor sampler as in https://docs.dgl.ai/guide/minibatch-custom-sampler.html.  It shows an example of how to randomly remove some edges, but adding edges should be similar.

**Comment by JameZhaolong** [comment]
> 

So have managed to reproduce it? If so, would you mind to share your code with me?
