### ISSUE TITLE
Nccl software error is displayed when using pytorch as backend for multi GPU training

### ISSUE THREAD

**Issue by Patrick-Star125** [dmlc/dgl#3513]
## 🐛 Bug

Nccl software error is displayed when using pytorch as backend for multi GPU training

## To Reproduce

error code is here:
~~~
if n_gpus > 1:
     dist_init_method = 'tcp://{}:{}'.format('127.0.0.1', '33274')
     world_size = n_gpus
     print("init_method: {} \n world_size: {} \n rank: {} \n".format(dist_init_method, world_size, proc_id))
     # failed to initialize
     dist.init_process_group(backend='nccl',
                             init_method=dist_init_method,
                             world_size=world_size,
                             rank=proc_id)
~~~

then the error messages
Node's feature shape:torch.Size([3655452, 300])
Use GPU 0 for training ......
init_method: tcp://127.0.0.1:33274
 world_size: 4
 rank: 0

Use GPU 1 for training ......
init_method: tcp://127.0.0.1:33274
 world_size: 4
 rank: 1

Use GPU 2 for training ......
init_method: tcp://127.0.0.1:33274
 world_size: 4
 rank: 2

Use GPU 3 for training ......
init_method: tcp://127.0.0.1:33274
 world_size: 4
 rank: 3

LXC:71145:71146 [0] NCCL INFO Bootstrap : Using [0]eth0:172.17.0.10<0>
LXC:71145:71146 [0] NCCL INFO NET/Plugin : No plugin found (libnccl-net.so), using internal implementation

LXC:71145:71146 [0] misc/ibvwrap.cc:63 NCCL WARN Failed to open libibverbs.so[.1]
LXC:71145:71146 [0] NCCL INFO NET/Socket : Using [0]eth0:172.17.0.10<0>
LXC:71145:71146 [0] NCCL INFO Using network Socket
NCCL version 2.7.8+cuda10.2
LXC:71150:71151 [2] NCCL INFO Bootstrap : Using [0]eth0:172.17.0.10<0>
LXC:71152:71153 [3] NCCL INFO Bootstrap : Using [0]eth0:172.17.0.10<0>
LXC:71150:71151 [2] NCCL INFO NET/Plugin : No plugin found (libnccl-net.so), using internal implementation
LXC:71152:71153 [3] NCCL INFO NET/Plugin : No plugin found (libnccl-net.so), using internal implementation

LXC:71152:71153 [3] misc/ibvwrap.cc:63 NCCL WARN Failed to open libibverbs.so[.1]
LXC:71150:71151 [2] misc/ibvwrap.cc:63 NCCL WARN Failed to open libibverbs.so[.1]
LXC:71152:71153 [3] NCCL INFO NET/Socket : Using [0]eth0:172.17.0.10<0>
LXC:71150:71151 [2] NCCL INFO NET/Socket : Using [0]eth0:172.17.0.10<0>
LXC:71152:71153 [3] NCCL INFO Using network Socket
LXC:71150:71151 [2] NCCL INFO Using network Socket
LXC:71147:71148 [1] NCCL INFO Bootstrap : Using [0]eth0:172.17.0.10<0>
LXC:71147:71148 [1] NCCL INFO NET/Plugin : No plugin found (libnccl-net.so), using internal implementation

LXC:71147:71148 [1] misc/ibvwrap.cc:63 NCCL WARN Failed to open libibverbs.so[.1]
LXC:71147:71148 [1] NCCL INFO NET/Socket : Using [0]eth0:172.17.0.10<0>
LXC:71147:71148 [1] NCCL INFO Using network Socket
LXC:71145:71167 [0] NCCL INFO Channel 00/02 :    0   1   2   3
LXC:71145:71167 [0] NCCL INFO Channel 01/02 :    0   1   2   3
LXC:71150:71169 [2] NCCL INFO threadThresholds 8/8/64 | 32/8/64 | 8/8/64
LXC:71152:71168 [3] NCCL INFO threadThresholds 8/8/64 | 32/8/64 | 8/8/64
LXC:71152:71168 [3] NCCL INFO Trees [0] -1/-1/-1->3->2|2->3->-1/-1/-1 [1] -1/-1/-1->3->2|2->3->-1/-1/-1
LXC:71145:71167 [0] NCCL INFO threadThresholds 8/8/64 | 32/8/64 | 8/8/64
LXC:71145:71167 [0] NCCL INFO Trees [0] 1/-1/-1->0->-1|-1->0->1/-1/-1 [1] 1/-1/-1->0->-1|-1->0->1/-1/-1
LXC:71152:71168 [3] NCCL INFO Setting affinity for GPU 3 to 5555,55555555
LXC:71145:71167 [0] NCCL INFO Setting affinity for GPU 0 to 5555,55555555
LXC:71147:71170 [1] NCCL INFO threadThresholds 8/8/64 | 32/8/64 | 8/8/64
LXC:71150:71169 [2] NCCL INFO Trees [0] 3/-1/-1->2->1|1->2->3/-1/-1 [1] 3/-1/-1->2->1|1->2->3/-1/-1
LXC:71147:71170 [1] NCCL INFO Trees [0] 2/-1/-1->1->0|0->1->2/-1/-1 [1] 2/-1/-1->1->0|0->1->2/-1/-1
LXC:71150:71169 [2] NCCL INFO Setting affinity for GPU 2 to 5555,55555555
LXC:71147:71170 [1] NCCL INFO Setting affinity for GPU 1 to 5555,55555555
LXC:71152:71168 [3] NCCL INFO Could not enable P2P between dev 3(=40000) and dev 2(=3f000)
LXC:71150:71169 [2] NCCL INFO Could not enable P2P between dev 2(=3f000) and dev 1(=3e000)
LXC:71145:71167 [0] NCCL INFO Could not enable P2P between dev 0(=3d000) and dev 3(=40000)
LXC:71147:71170 [1] NCCL INFO Could not enable P2P between dev 1(=3e000) and dev 0(=3d000)
LXC:71145:71167 [0] NCCL INFO Could not enable P2P between dev 0(=3d000) and dev 1(=3e000)
LXC:71145:71167 [0] NCCL INFO Channel 00 : 0[3d000] -> 1[3e000] via direct shared memory
LXC:71152:71168 [3] NCCL INFO Could not enable P2P between dev 3(=40000) and dev 0(=3d000)
LXC:71152:71168 [3] NCCL INFO Channel 00 : 3[40000] -> 0[3d000] via direct shared memory
LXC:71150:71169 [2] NCCL INFO Could not enable P2P between dev 2(=3f000) and dev 3(=40000)
LXC:71150:71169 [2] NCCL INFO Channel 00 : 2[3f000] -> 3[40000] via direct shared memory
LXC:71147:71170 [1] NCCL INFO Could not enable P2P between dev 1(=3e000) and dev 2(=3f000)
LXC:71147:71170 [1] NCCL INFO Channel 00 : 1[3e000] -> 2[3f000] via direct shared memory
LXC:71147:71170 [1] NCCL INFO Could not enable P2P between dev 1(=3e000) and dev 2(=3f000)
LXC:71145:71167 [0] NCCL INFO Could not enable P2P between dev 0(=3d000) and dev 1(=3e000)
LXC:71150:71169 [2] NCCL INFO Could not enable P2P between dev 2(=3f000) and dev 3(=40000)
LXC:71152:71168 [3] NCCL INFO Could not enable P2P between dev 3(=40000) and dev 2(=3f000)
LXC:71152:71168 [3] NCCL INFO Channel 00 : 3[40000] -> 2[3f000] via direct shared memory

LXC:71150:71169 [2] include/shm.h:28 NCCL WARN Call to posix_fallocate failed : No space left on device
LXC:71147:71170 [1] include/shm.h:28 NCCL WARN Call to posix_fallocate failed : No space left on device
LXC:71145:71167 [0] include/shm.h:28 NCCL WARN Call to posix_fallocate failed : No space left on device
LXC:71147:71170 [1] NCCL INFO include/shm.h:41 -> 2
LXC:71145:71167 [0] NCCL INFO include/shm.h:41 -> 2
LXC:71150:71169 [2] NCCL INFO include/shm.h:41 -> 2

LXC:71145:71167 [0] include/shm.h:48 NCCL WARN Error while creating shared memory segment nccl-shm-recv-37615efd7c719251-0-1-0 (size 9637888)

LXC:71147:71170 [1] include/shm.h:48 NCCL WARN Error while creating shared memory segment nccl-shm-recv-cd34c5e6a2255653-0-2-1 (size 9637888)

LXC:71150:71169 [2] include/shm.h:48 NCCL WARN Error while creating shared memory segment nccl-shm-recv-68f0ffbd8c464a6d-0-3-2 (size 9637888)

LXC:71150:71169 [2] NCCL INFO transport/shm.cc:101 -> 2
LXC:71145:71167 [0] NCCL INFO transport/shm.cc:101 -> 2
LXC:71150:71169 [2] NCCL INFO transport.cc:30 -> 2
LXC:71145:71167 [0] NCCL INFO transport.cc:30 -> 2
LXC:71145:71167 [0] NCCL INFO transport.cc:49 -> 2
LXC:71147:71170 [1] NCCL INFO transport/shm.cc:101 -> 2
LXC:71150:71169 [2] NCCL INFO transport.cc:49 -> 2
LXC:71147:71170 [1] NCCL INFO transport.cc:30 -> 2
LXC:71147:71170 [1] NCCL INFO transport.cc:49 -> 2
LXC:71150:71169 [2] NCCL INFO init.cc:767 -> 2
LXC:71145:71167 [0] NCCL INFO init.cc:767 -> 2
LXC:71150:71169 [2] NCCL INFO init.cc:840 -> 2
LXC:71147:71170 [1] NCCL INFO init.cc:767 -> 2
LXC:71145:71167 [0] NCCL INFO init.cc:840 -> 2
LXC:71147:71170 [1] NCCL INFO init.cc:840 -> 2
LXC:71150:71169 [2] NCCL INFO group.cc:73 -> 2 [Async thread]
LXC:71145:71167 [0] NCCL INFO group.cc:73 -> 2 [Async thread]
LXC:71147:71170 [1] NCCL INFO group.cc:73 -> 2 [Async thread]
Process Process-2:
Process Process-3:
Process Process-1:
Traceback (most recent call last):
Traceback (most recent call last):
  File "/root/miniconda3/envs/torch17/lib/python3.7/multiprocessing/process.py", line 297, in _bootstrap
    self.run()
Traceback (most recent call last):
  File "/root/miniconda3/envs/torch17/lib/python3.7/multiprocessing/process.py", line 297, in _bootstrap
    self.run()
  File "/root/miniconda3/envs/torch17/lib/python3.7/multiprocessing/process.py", line 99, in run
    self._target(*self._args, **self._kwargs)
  File "/root/miniconda3/envs/torch17/lib/python3.7/multiprocessing/process.py", line 297, in _bootstrap
    self.run()
  File "/root/miniconda3/envs/torch17/lib/python3.7/multiprocessing/process.py", line 99, in run
    self._target(*self._args, **self._kwargs)
  File "/root/miniconda3/envs/torch17/lib/python3.7/site-packages/dgl/multiprocessing/pytorch.py", line 29, in decorated_function
    raise exception.__class__(trace)
  File "/root/miniconda3/envs/torch17/lib/python3.7/site-packages/dgl/multiprocessing/pytorch.py", line 29, in decorated_function
    raise exception.__class__(trace)
  File "/root/miniconda3/envs/torch17/lib/python3.7/multiprocessing/process.py", line 99, in run
    self._target(*self._args, **self._kwargs)
RuntimeError: Traceback (most recent call last):
  File "/root/miniconda3/envs/torch17/lib/python3.7/site-packages/dgl/multiprocessing/pytorch.py", line 17, in _queue_result
    res = func(*args, **kwargs)
  File "model_train.py", line 147, in gpu_train
    rank=proc_id)
  File "/root/miniconda3/envs/torch17/lib/python3.7/site-packages/torch/distributed/distributed_c10d.py", line 455, in init_process_group
    barrier()
  File "/root/miniconda3/envs/torch17/lib/python3.7/site-packages/torch/distributed/distributed_c10d.py", line 1960, in barrier
    work = _default_pg.barrier()
RuntimeError: NCCL error in: /pytorch/torch/lib/c10d/ProcessGroupNCCL.cpp:784, unhandled system error, NCCL version 2.7.8

RuntimeError: Traceback (most recent call last):
  File "/root/miniconda3/envs/torch17/lib/python3.7/site-packages/dgl/multiprocessing/pytorch.py", line 17, in _queue_result
    res = func(*args, **kwargs)
  File "model_train.py", line 147, in gpu_train
    rank=proc_id)
  File "/root/miniconda3/envs/torch17/lib/python3.7/site-packages/torch/distributed/distributed_c10d.py", line 455, in init_process_group
    barrier()
  File "/root/miniconda3/envs/torch17/lib/python3.7/site-packages/torch/distributed/distributed_c10d.py", line 1960, in barrier
    work = _default_pg.barrier()
RuntimeError: NCCL error in: /pytorch/torch/lib/c10d/ProcessGroupNCCL.cpp:784, unhandled system error, NCCL version 2.7.8

  File "/root/miniconda3/envs/torch17/lib/python3.7/site-packages/dgl/multiprocessing/pytorch.py", line 29, in decorated_function
    raise exception.__class__(trace)
RuntimeError: Traceback (most recent call last):
  File "/root/miniconda3/envs/torch17/lib/python3.7/site-packages/dgl/multiprocessing/pytorch.py", line 17, in _queue_result
    res = func(*args, **kwargs)
  File "model_train.py", line 147, in gpu_train
    rank=proc_id)
  File "/root/miniconda3/envs/torch17/lib/python3.7/site-packages/torch/distributed/distributed_c10d.py", line 455, in init_process_group
    barrier()
  File "/root/miniconda3/envs/torch17/lib/python3.7/site-packages/torch/distributed/distributed_c10d.py", line 1960, in barrier
    work = _default_pg.barrier()
RuntimeError: NCCL error in: /pytorch/torch/lib/c10d/ProcessGroupNCCL.cpp:784, unhandled system error, NCCL version 2.7.8

## Environment

ubuntu 16.04
python  3.7.6
pytorch 1.7.1
dgl 0.7.1
CUDA 10.2
GPU NVIDIA TITAN M10

## Additional context

by the way, In another torch version 1.10 environment, multi GPU training is normal, I don't know whether it's useful information or not.

I thought libibverbs.so was missing from the system before, but after inspection, it was not found that the software was missing

**Comment by Patrick-Star125** [comment]
Sorry, the GPU model is NVIDIA Tesla M10

**Comment by VoVAllen** [comment]
Could you try our nightly version? Probably related to https://github.com/dmlc/dgl/issues/3390

**Comment by Patrick-Star125** [comment]
> Could you try our nightly version? Probably related to #3390

Do you mean 0.7.2? I've tried 0.7.0 0.7.1 and 0.7.2. but none of them worked.

**Comment by nv-dlasalle** [comment]
PyTorch 1.10 has a different NCCL version than previous PyTorch releases, so it may be related to that. @Patrick-Star125 do you see this issue with any PyTorch workloads not using DGL?
