### ISSUE TITLE
How do you determine the number of heads of attention in a graph attention network?

### ISSUE THREAD

**Issue by tanjia123456** [dmlc/dgl#3515]
## ❓ Questions and Help

How do you determine the number of heads of attention in a graph attention network? For some graphs with a large number of nodes, there seems to be a problem that the more attention heads the better.

**Comment by BarclayII** [comment]
That's usually a hyperparameter you want to fiddle with.

**Comment by tanjia123456** [comment]
I made an innovation on the GAT model, so should the choice of the number of attention heads be the best performance on the original GAT or should I re-select the number of attention heads on the innovative model? Are there any related literature references?
