### ISSUE TITLE
TensorFlow EdgeConv leads differently shaped result than PyTorch

### ISSUE THREAD

**Issue by jackaraz** [dmlc/dgl#3520]
Hi, I was trying to use the `EdgeConv` module but when I tested the examples given in [this link](https://github.com/dmlc/dgl/blob/81915f55913a7a862f40fe2d8ea5b5319faf5bae/python/dgl/nn/pytorch/conv/edgeconv.py#L64) I realised that TensorFlow leads to completely different shapes. Here are my results;

```python
import dgl
from dgl.nn import EdgeConv
import tensorflow as tf
g = dgl.graph(([0,1,2,3,2,5], [1,2,3,4,0,3]))
g = dgl.add_self_loop(g)
feat = tf.ones((6, 10))
conv = EdgeConv(10, 2)
#conv.build((10,))
res = conv(g, feat)
res.shape
#TensorShape([6, 10])
```
same example with pytorch backend gives `torch.Size([6, 2])`. additionally with bipartite
```python
u = [0, 1, 0, 0, 1]
v = [0, 1, 2, 3, 2]
g = dgl.heterograph({('_U', '_E', '_V') : (u, v)})#bipartite((u, v))
u_fea = tf.random.uniform((2, 5))
v_fea = tf.random.uniform((4, 5))
conv = EdgeConv(5, 2, 3)
res = conv(g, (u_fea, v_fea))
res.shape
# TensorShape([4, 5])
```
with pytorch `torch.Size([4, 2])`.

I, unfortunately, couldn't find the reason for this difference. Any help would be appreciated.

Thanks

**System settings**
- dgl v0.6.1
- pytorch 1.10.0
- TensorFlow v2.6.0
- python 3.8.9

**Comment by Rhett-Ying** [comment]
Hi, this is caused by the different constructors between pytorch.EdgeConv and tf.EdgeConv. for td.EdgeConv, we just need to pass in the out_feat as the first argument. so you should call like this: `conv= EdgeConv(2)` in tf.

https://github.com/dmlc/dgl/blob/3aef46773332f2d5e179c0abc9d0ba428a09b6b4/python/dgl/nn/tensorflow/conv/edgeconv.py#L55

**Comment by jackaraz** [comment]
Ah yes, you are totally right, I missed that Thanks @Rhett-Ying !!
