### ISSUE TITLE
How to do adj.set_diag() in dgl

### ISSUE THREAD

**Issue by renmada** [dmlc/dgl#3521]
## ❓ Questions and Help
In pyg adj matrix can use set_diag, do dgl have same function, what is it?

**Comment by Rhett-Ying** [comment]
do you mean `torch_sparse.set_diag()` ? or try with `scipy.sparse`: `a=dgl.rand_graph(3,5).adj(scipy_fmt='coo') a.setdiag([])`

**Comment by BarclayII** [comment]
You can also try removing and adding self-loops via:
```
g = dgl.add_self_loop(dgl.remove_self_loop(g))
```
