### ISSUE TITLE
pinsage ItemToItemScorer bias addition issue

### ISSUE THREAD

**Issue by zmy1116** [dmlc/dgl#3523]
## 🐛 Bug

I don't know whether this is a bug, but this does not make sense:

In `examples/pytorch/pinsage/layers.py` Function `ItemToItemScore` 
If I understand well,  to score a pair of node u and v ,   we want to do h_u dot h_v + bias_u + bias_v 

However, if we look at the code: 

https://github.com/dmlc/dgl/blob/3aef46773332f2d5e179c0abc9d0ba428a09b6b4/examples/pytorch/pinsage/layers.py#L188

If the bipartite graph have N edges in total, source N nodes, destination N nodes
This line produce  dot product values of size `Nx1` and store at key `s` of edges 

When we retrieve the bias of sources and destinations, the `bias_src` and `bias_dst` has shape `N`
https://github.com/dmlc/dgl/blob/3aef46773332f2d5e179c0abc9d0ba428a09b6b4/examples/pytorch/pinsage/layers.py#L177-L179

And the sum of a `Nx1` and `N` in pytorch gives a matrix of size `NxN`

So we want compute similarity scores for `N` pairs of nodes, we ended with a matrix of size `NxN`

Since the original paper is vague on the implementation details and there is no official implementation, I actually don't know what the expected behavior is... but this just look wrong.. 

## To Reproduce

I'm new to dgl so I don't know what is the best way to create minimum example.. but essentially for any graph `g`:

1.  `g.apply_edges(fn.u_dot_v('h', 'h', 's'))`  produces matrix size of `Nx1`
1.  You add `Nx1` matrix to `N` size vector you will get `NxN` instead of `Nx1` 

## Expected behavior
I think  in 
https://github.com/dmlc/dgl/blob/3aef46773332f2d5e179c0abc9d0ba428a09b6b4/examples/pytorch/pinsage/layers.py#L179

we should flatten `edge_data['s']` before doing addition

## Environment

 - DGL Version (e.g., 1.0): 0.72
 - Backend Library & Version (e.g., PyTorch 0.4.1, MXNet/Gluon 1.3): 1.10
 - OS (e.g., Linux): Linux
 - How you installed DGL (`conda`, `pip`, source): conda
 - Build command you used (if compiling from source): no
 - Python version:   3.7
 - CUDA/cuDNN version (if applicable): 11.1
 - GPU models and configuration (e.g. V100): 2080TI
 - Any other relevant information:

## Additional context
Yeah again I'm not sure what the expected behavior is, but it looks wrong

**Comment by Rhett-Ying** [comment]
Thanks for reporting this. output dimension is not expected though current impl is supposed to have no accuracy issue as it's `.mean()` is called in https://github.com/dmlc/dgl/blob/7b4b8129e310ba577ded511a4a4c2d54bab7357d/examples/pytorch/pinsage/model.py#L101

**Comment by zmy1116** [comment]
> Thanks for reporting this. output dimension is not expected though current impl is supposed to have no accuracy issue as it's `.mean()` is called in
> 
> https://github.com/dmlc/dgl/blob/7b4b8129e310ba577ded511a4a4c2d54bab7357d/examples/pytorch/pinsage/model.py#L101

yeah... I understand how it's not going to throw errors .... I'm not too sure about no accuracy issue because now each item's feature is added to every items bias term and form a score....... which makes learning the bias terms invalid...   (although i don't even understand why we have bias terms here in the first place...)

**Comment by Rhett-Ying** [comment]
fix is merged.
