### ISSUE TITLE
DGL with cuda 11.0

### ISSUE THREAD

**Issue by tliu1023** [dmlc/dgl#3525]
## Motivation

Currently, DGL is only compatible with CUDA 11.3, since the cuda has been already upgraded to 11.4 (of course and 11.5). I really appreciate it if the contributor can make the dgl installation compatible with a newer version of cuda.

**Comment by Rhett-Ying** [comment]
previously discussed in https://discuss.dgl.ai/t/install-dgl-with-cuda-11-4/2502

**Comment by VoVAllen** [comment]
Hi,

Our cuda release follows the official release of PyTorch. We didn't find PyTorch with cuda 11.4. How did you install PyTorch in your environment?

**Comment by tliu1023** [comment]
> Hi,
> 
> Our cuda release follows the official release of PyTorch. We didn't find PyTorch with cuda 11.4. How did you install PyTorch in your environment?

Hi,

I'm using the singularity container on the cluster provided by the university, so I didn't install it by myself. And I can see there are several Cuda versions (11.0, 11.2, 11.4). So I checked the version by nvidia-smi. It always returns 11.4. I'm not sure what should I do right now.

**Comment by nv-dlasalle** [comment]
@tliu1023 can you share the error you're getting?

**Comment by tliu1023** [comment]
> @tliu1023 can you share the error you're getting?

Hi,

I managed to change the cuda to 11.0 but I still got the error.

(opence-v1.3.1) [tongl5@hal-login2 ~]$ pip install dgl-cu110 -f https://data.dgl.ai/wheels/repo.html
Defaulting to user installation because normal site-packages is not writeable
Looking in links: https://data.dgl.ai/wheels/repo.html
ERROR: Could not find a version that satisfies the requirement dgl-cu110 (from versions: none)
ERROR: No matching distribution found for dgl-cu110

The environment I'm using:
linux ppc64le
python 3.8
pytorch 1.8.1
cuda 11.0

**Comment by BarclayII** [comment]
We do not ship PowerPC binaries; I'm afraid you will have to install from source.  You can follow https://docs.dgl.ai/install/index.html#install-from-source for instructions.

**Comment by sunhao123456789** [comment]
请问解决了吗

**Comment by sunhao123456789** [comment]
请问解决了吗 @tliu1023
