### ISSUE TITLE
dgl.distributed.partition_graph is not working on Windows 10

### ISSUE THREAD

**Issue by kartikeyas00** [dmlc/dgl#3526]
## 🐛 Bug

I am following this tutorial [here](https://github.com/dmlc/dgl/blob/master/tutorials/dist/1_node_classification.py) and trying to partition the graph with dgl.distributed.partition_graph() method. When I execute this method, I get the error 

`DGLError: [01:49:56] C:\Users\Administrator\dgl-0.5\src\graph\transform\partition_hetero.cc:372: The fast version of making symmetric graph is not supported in Windows.`

## To Reproduce

This is the code I am running:

```
import dgl
import torch as th
from ogb.nodeproppred import DglNodePropPredDataset


data = DglNodePropPredDataset(name='ogbn-products')
graph, labels = data[0]
labels = labels[:, 0]
graph.ndata['labels'] = labels


splitted_idx = data.get_idx_split()
train_nid, val_nid, test_nid = splitted_idx['train'], splitted_idx['valid'], splitted_idx['test']
train_mask = th.zeros((graph.number_of_nodes(),), dtype=th.bool)
train_mask[train_nid] = True
val_mask = th.zeros((graph.number_of_nodes(),), dtype=th.bool)
val_mask[val_nid] = True
test_mask = th.zeros((graph.number_of_nodes(),), dtype=th.bool)
test_mask[test_nid] = True
graph.ndata['train_mask'] = train_mask
graph.ndata['val_mask'] = val_mask
graph.ndata['test_mask'] = test_mask


dgl.distributed.partition_graph(graph, graph_name='ogbn-products', num_parts=2,
                                    out_path='2part_data',
                                    balance_ntypes=graph.ndata['train_mask'],
                                    balance_edges=True)
```

## Expected behavior

I am expecting a folder with the name 2part_data containing partition data. 

## Environment

 - DGL Version (e.g., 1.0): 0.7.2
 - Backend Library & Version (e.g., PyTorch 0.4.1, MXNet/Gluon 1.3): torch 1.10.0
 - OS (e.g., Linux): Windows 10 64 bits
 - How you installed DGL (`conda`, `pip`, source): conda install -c dglteam dgl
 - Build command you used (if compiling from source): None
 - Python version: 3.7.11
 - CUDA/cuDNN version (if applicable): None
 - GPU models and configuration (e.g. V100): None
 - Any other relevant information:

**Comment by Rhett-Ying** [comment]
This exception is expected as distributed training on windows is not supported yet.
