### ISSUE TITLE
MNIST example in pytorch/model_zoo raises a device error

### ISSUE THREAD

**Issue by sinhaharsh** [dmlc/dgl#3527]
## 🐛 Bug

`mnist.py` example script for pytorch, raises a Runtime error at line 181, because the variable `g` is not moved to device explicitly.

## To Reproduce

python mnist.py

`~/github/dgl/examples/pytorch/model_zoo/geometric>python mnist.py
Using backend: pytorch
nb edges:  6396
Heavy Edge Matching coarsening with Xavier version
Layer 0: M_0 = |V| = 960 nodes (176 added), |E| = 3198 edges
Layer 1: M_1 = |V| = 480 nodes (77 added), |E| = 1618 edges
Layer 2: M_2 = |V| = 240 nodes (29 added), |E| = 781 edges
Layer 3: M_3 = |V| = 120 nodes (7 added), |E| = 388 edges
Layer 4: M_4 = |V| = 60 nodes (0 added), |E| = 194 edges
epoch 0 starts
loss: 2.2993332672119142, acc: 0.117
loss: 2.293206968307495, acc: 0.1426
loss: 2.1819214248657226, acc: 0.2112
loss: 1.9549490690231324, acc: 0.2916
loss: 1.8146379899978637, acc: 0.3576
loss: 1.6154630589485168, acc: 0.4566
loss: 1.4774926900863647, acc: 0.5098
loss: 1.2729893016815186, acc: 0.5848
loss: 1.1840235543251039, acc: 0.624
loss: 1.0735841548442842, acc: 0.6588
loss: 0.9746878004074097, acc: 0.6964
loss: 0.8865913331508637, acc: 0.7234
Traceback (most recent call last):
  File "mnist.py", line 180, in <module>
    out = model(g, x)
  File "miniconda3/envs/dglssb/lib/python3.8/site-packages/torch/nn/modules/module.py", line 722, in _call_impl
    result = self.forward(*input, **kwargs)
  File "mnist.py", line 132, in forward
    feat = self.pool(layer(g, feat, [2] * g.batch_size).transpose(-1, -2).unsqueeze(0))\
  File "miniconda3/envs/dglssb/lib/python3.8/site-packages/torch/nn/modules/module.py", line 722, in _call_impl
    result = self.forward(*input, **kwargs)
  File "miniconda3/envs/dglssb/lib/python3.8/site-packages/dgl/nn/pytorch/conv/chebconv.py", line 130, in forward
    lambda_max = broadcast_nodes(graph, lambda_max)
  File "miniconda3/envs/dglssb/lib/python3.8/site-packages/dgl/readout.py", line 418, in broadcast_nodes
    return F.repeat(graph_feat, graph.batch_num_nodes(ntype), dim=0)
  File "miniconda3/envs/dglssb/lib/python3.8/site-packages/dgl/backend/pytorch/tensor.py", line 183, in repeat
    return th.repeat_interleave(input, repeats, dim) # PyTorch 1.1
RuntimeError: Expected object of device type cuda but got device type cpu for argument #3 'index' in call to _th_index_select`

## Expected behavior
During test variable `g` should be moved to device

**Comment by Rhett-Ying** [comment]
Thanks for reporting this. I have reviewed your PR and dropped comments. pls take a look.

**Comment by Rhett-Ying** [comment]
https://github.com/dmlc/dgl/pull/3528 is merged.
