### ISSUE TITLE
An error in TGN example: 'TemporalEdgeDataLoader' object has no attribute 'is_distributed'

### ISSUE THREAD

**Issue by ZhipengHuang00** [dmlc/dgl#3536]
## 🐛 Bug

I got an error saying: 'TemporalEdgeDataLoader' object has no attribute 'is_distributed' in the TGN example (wikipedia). 
https://github.com/dmlc/dgl/tree/master/examples/pytorch/tgn

## To Reproduce

1. I just download and run the code followed by the tutorial without any modification.

## Expected behavior
The full message in the console are:
VB
Data is exist directly loaded.
========Training is Done========
Traceback (most recent call last):
  File "/Users/Documents/PHD Study/tgn-dgl/train.py", line 267, in <module>
    criterion, optimizer, args)
  File "/Users/Documents/PHD Study/tgn-dgl/train.py", line 32, in train
    for _, positive_pair_g, negative_pair_g, blocks in dataloader:
  File "/Users/opt/anaconda3/envs/myenv_3_7/lib/python3.7/site-packages/dgl/dataloading/pytorch/dataloader.py", line 818, in __iter__
    if self.is_distributed:
AttributeError: 'TemporalEdgeDataLoader' object has no attribute 'is_distributed'

## Environment
 - DGL Version (e.g., 1.0): 0.7.2
 - Backend Library & Version (e.g., PyTorch 0.4.1, MXNet/Gluon 1.3): 1.10.0
 - OS (e.g., Linux): All systems have the same issue: windows, macOS, Linus.
 - How you installed DGL (`conda`, `pip`, source): conda install -c dglteam dgl
 - Build command you used (if compiling from source):
 - Python version: 3.7.11
 - CUDA/cuDNN version (if applicable): No cuda
 - GPU models and configuration (e.g. V100):
 - Any other relevant information: 

## Additional context
It seems that other people do not have this error, so I wonder if there is something wrong with my installation or environment.

**Comment by VoVAllen** [comment]
I made a fix at https://github.com/dmlc/dgl/pull/3543

**Comment by ZhipengHuang00** [comment]
I tried to download the code again, but seems didn't have any changes there and shows the same error I had before; So I followed the changes you made in the dataloading.py and it still has errors:
`ImportError: cannot import name '_pop_storage' from 'dgl.dataloading.pytorch'`
And for graph_sampler, it also shows:
`AttributeError: 'TemporalEdgeCollator' object has no attribute 'graph_sampler'`

**Comment by BarclayII** [comment]
The fix above works for nightly build.  To make it work for your case I believe you only need to add at line 268 of `dataloading.py` the following as per the PR:
```python
super().__init__(g, eids, graph_sampler, device, **kwargs)
```

**Comment by ZhipengHuang00** [comment]
Great, It's working now! thank you so much and I'll close this issue.
