### ISSUE TITLE
RuntimeError: CUDA error: initialization error training use multi GPU

### ISSUE THREAD

**Issue by lfchener** [dmlc/dgl#3545]
## 🐛 Bug

When i train model use multi GPU, refer to https://docs.dgl.ai/en/0.7.x/tutorials/multi/1_graph_classification.html#, i get an error like:
![image](https://user-images.githubusercontent.com/6771821/143191420-1c46ef41-adf9-4429-91f8-cc1101d44d87.png)

and  i  refer to https://github.com/pytorch/pytorch/issues/21092 to  add `mp.set_start_method('spawn') `  before `mp.Process`

but i got anthor bug like:
![image](https://user-images.githubusercontent.com/6771821/143192000-0b483156-1923-4dcb-9693-a595c70c8b47.png)

How should i solve this trouble?

## To Reproduce

1.
1.
1.

## Environment

 - DGL Version (e.g., 1.0): 0.7.1
 - Backend Library & Version (e.g., PyTorch 0.4.1, MXNet/Gluon 1.3): PyTorch 1.7.1
 - OS (e.g., Linux): Linux
 - How you installed DGL (`conda`, `pip`, source): pip install dgl-cu102==0.7.1  -f https://data.dgl.ai/wheels/repo.html 
 - Build command you used (if compiling from source):
 - Python version: 3.6.8
 - CUDA/cuDNN version (if applicable): 10.2
 - GPU models and configuration (e.g. V100): v100
 - Any other relevant information:

**Comment by VoVAllen** [comment]
Hi,

Please post full codes you are runnnig for us to debug

**Comment by lfchener** [comment]
Thanks for reply. I solved above problem already. The `CUDA error` is because i  run `torch.cuda.is_available()` before `init_process_group`, when i delete `torch.cuda.is_available()` and  `mp.set_start_method('spawn') `,  the  model is running.
But i face an other error like:
![image](https://user-images.githubusercontent.com/6771821/143196581-a69abc9c-02b1-4a37-a2fc-3ed71e6e1188.png)
Have you encountered this problem before？
