### ISSUE TITLE
Is it more resonable to shuffle `TUDataset` when init it?

### ISSUE THREAD

**Issue by sangyx** [dmlc/dgl#3548]
## 🚀 Feature

shuffle `TUDataset` when init it

## Motivation

I found that models performed poorly if I don't set shuffle in the train loader. It is because that if I don't set `shuffle=True`, `TUDataset` will be loaded in order. Then the batches at the beginning all have label 0 and the batches behind all have label 1, which will hurt models. So I think it is more reasonable to shuffle `TUDataset` when init it or there should be a warning to remind users to set shuffle.

**Comment by hetong007** [comment]
Whether to shuffle or not is controlled by DataLoader, other than dataset, and it is also preferred to have deterministic Dataset behavior. 

I think a reasonable improvement is to address in the docstring of `TUDataset` that without shuffling, the graphs are sorted by their label. Could you take care of that by a PR?
