### ISSUE TITLE
Inconsistent documentation and code of MultiLayerNeighborSampler

### ISSUE THREAD

**Issue by ZZy979** [dmlc/dgl#3550]
## 📚 Documentation

In the docstring of `MultiLayerNeighborSampler`, the default value of parameter `replace` is `True`, while in the code it's `False`:
```python
class MultiLayerNeighborSampler(BlockSampler):
    """
    ...

    replace : bool, default True
        Whether to sample with replacement
    ...
    """
    def __init__(self, fanouts, replace=False, return_eids=False):
        super().__init__(len(fanouts), return_eids)
        self.fanouts = fanouts
        self.replace = replace
        # ...
```

Same issue exists in <https://docs.dgl.ai/api/python/dgl.dataloading.html#dgl.dataloading.neighbor.MultiLayerNeighborSampler>

**Comment by jermainewang** [comment]
Hi @ZZy979 , it is indeed a mistake. Would you like to fix it? Thanks in advance.
