### ISSUE TITLE
Too much memory in out_degrees in_degrees

### ISSUE THREAD

**Issue by gonzalesMK** [dmlc/dgl#3552]
## 🐛 Bug

I was working with big graphs in my project, and I realized that getting the degrees of the nodes is a very memory-consuming task. 

## To Reproduce

To reproduce the behavior, run the code:

```
import dgl
import torch
import os, psutil
import gc
process = psutil.Process(os.getpid())

print(f"Memory Usage (MB):{process.memory_info().rss/1024**2}")  # in bytes 
n = int(2e4)

nodes_a = torch.linspace(0, n, n, dtype=torch.int)
edges = torch.combinations(nodes_a, with_replacement=False, r=2)
print(f"Memory Usage (MB):{process.memory_info().rss/1024**2}")  # in bytes 
graph = dgl.graph((edges[:, 0], edges[:, 1]))
print(f"Memory Usage (MB):{process.memory_info().rss/1024**2}")  # in bytes 
graph.out_degrees()
gc.collect()
print(f"Memory Usage (MB):{process.memory_info().rss/1024**2}")  # in bytes 
graph.in_degrees()
gc.collect()
print(f"Memory Usage (MB):{process.memory_info().rss/1024**2}")  # in bytes 
```
In my computer, the output was:

> Memory Usage (MB):1708.96484375
> Memory Usage (MB):3240.51171875
> Memory Usage (MB):4770.21875
> Memory Usage (MB):6298.046875

## Expected behavior

I didn't expected the functions out_degrees and in_degrees to increase the memory of the object. I tried to collect the memory from the program, without success. 

## Environment

 - DGL Version: 0.7.2 
 - Backend Library & Version: Pytorch  '1.10.0+cu113'
 - OS: Linux
 - How you installed DGL: pip
 - Python version: Python 3.8.10

**Comment by yzh119** [comment]
This is because when you call `in_degrees` and `out_degrees`, CSC and CSR formats are created correspondingly.

**Comment by gonzalesMK** [comment]
Ok, got it. But how do I free that memory ?

**Comment by yzh119** [comment]
No you can't, but if your node/edge indices are inside the range of int32, you can create a int32 graph via
```python
graph = dgl.graph((edges[:, 0], edges[:, 1]), idtype=torch.int32)
```
