### ISSUE TITLE
Unable to import GATv2Conv from dgl.nn.pytorch.conv

### ISSUE THREAD

**Issue by Rayn2402** [dmlc/dgl#3554]
Hi! 

I actually use the latest version of DGL (dglteam/linux-64::dgl-cuda11.0-0.7.2-py37_0) and can't find GATv2Conv in dgl.nn.pytorch.conv.

Is there a way to import it in my project yet? Thank you!

**Comment by mufeili** [comment]
Can you try installing the nightly-built version or building from source? `GATv2Conv` was not included in 0.7.2.

**Comment by Rayn2402** [comment]
I've tried the nightly-built version and it worked. Thank you!
