### ISSUE TITLE
How to consider edge features in GAT?

### ISSUE THREAD

**Issue by liyongkang123** [dmlc/dgl#3556]
## ❓ Questions and Help

Hello, i am using GAT in dgl to do something,  I  wonder how to consider edge features in GAT.
In PYG, there is a corresponding parameter, but I didn't see it in dgl.
Can anyone help me, thank you very much

**Comment by mufeili** [comment]
Perhaps you can try [EGATConv](https://docs.dgl.ai/en/latest/api/python/nn.pytorch.html#egatconv).

**Comment by liyongkang123** [comment]
> 

Thank you very much. I found out that the document I was looking at was version 0.7x, not the latest version of the document. There is no EGAT in it. I have also modified the GAT code to implement EGAT.
However, thank you very much for your reminder!

**Comment by liyongkang123** [comment]
Thank you very much. I found out that the document I was looking at was version 0.7x, not the latest version of the document. There is no EGAT in it. I have also modified the GAT code to implement EGAT.
However, thank you very much for your reminder!
