### ISSUE TITLE
"TypeError: cannot unpack non-iterable NoneType object" when loss.backward()

### ISSUE THREAD

**Issue by PiggerZZM** [dmlc/dgl#3557]
## ❓ Questions and Help

My DGL version is 0.7.2 which is the latest one. This problem is similar to issue 1046 (https://github.com/dmlc/dgl/issues/1046). 

I am building a Light-GCN model using DGL with the PyTorch backend. I want to train the model in a mini-batch manner but I got this error:

```
D:\Anaconda3\envs\pytorch\lib\site-packages\torch\autocast_mode.py:141: UserWarning: User provided device_type of 'cuda', but CUDA is not available. Disabling
  warnings.warn('User provided device_type of \'cuda\', but CUDA is not available. Disabling')
Traceback (most recent call last):
  File "D:\lightgcn\src\LightGCN\main_movielens.py", line 122, in <module>
    batch_loss.backward()
  File "D:\Anaconda3\envs\pytorch\lib\site-packages\torch\_tensor.py", line 307, in backward
    torch.autograd.backward(self, gradient, retain_graph, create_graph, inputs=inputs)
  File "D:\Anaconda3\envs\pytorch\lib\site-packages\torch\autograd\__init__.py", line 154, in backward
    Variable._execution_engine.run_backward(
  File "D:\Anaconda3\envs\pytorch\lib\site-packages\torch\autograd\function.py", line 199, in apply
    return user_fn(self, *args)
  File "D:\Anaconda3\envs\pytorch\lib\site-packages\torch\cuda\amp\autocast_mode.py", line 111, in decorate_bwd
    return bwd(*args, **kwargs)
  File "D:\Anaconda3\envs\pytorch\lib\site-packages\dgl\backend\pytorch\sparse.py", line 272, in backward
    gidx, op, lhs_target, rhs_target, X_shape, Y_shape = ctx.backward_cache
TypeError: cannot unpack non-iterable NoneType object

Process finished with exit code 1
```

Here is the training code raising this problem:

```
    for epoch in range(epochs):
        # train
        model.train()
        # forward
        final_emb = model(train_g.ndata["id"])
        pred = DotPredictor()
        score = pred(train_g, final_emb)
        ratings = train_g.edata["rating"]
        data = torch.cat([score, ratings], dim=1).to(device)
        dataloader = DataLoader(data, batch_size=1024, shuffle=True)
        for batch in dataloader:
            batch_score = batch[:, 0]
            batch_ratings = batch[:, 1]
            batch_loss = torch.sqrt(torch.mean(mse_loss(batch_score, batch_ratings)))
            optimizer.zero_grad()
            batch_loss.backward()
            optimizer.step()
```

everything is ok when I use this code:

```
    for epoch in range(epochs):
        # train
        model.train()
        # forward
        final_emb = model(train_g.ndata["id"])

        pred = DotPredictor()
        score = pred(train_g, final_emb)
        ratings = train_g.edata["rating"]
        loss = torch.sqrt(torch.mean(mse_loss(score, ratings)))
        
        optimizer.zero_grad()
        loss.backward()
        optimizer.step()
```

Here is the model code:

```
class LightGCN_full(nn.Module):

    def __init__(self, graph, emb_dim, num_layers):
        super(LightGCN_full, self).__init__()
        self.graph = graph
        self.emb = nn.Embedding(graph.num_nodes(), emb_dim)
        self.light_conv = GraphConv(emb_dim, emb_dim, weight=False, bias=False, allow_zero_in_degree=True)
        self.num_layers = num_layers
        nn.init.normal_(self.emb.weight, std=0.1)

    def forward(self, id):
        out = self.emb(id)
        final_emb = out
        for i in range(self.num_layers):
            out = self.light_conv(self.graph, out)
            final_emb += out
        final_emb /= self.num_layers + 1

        return final_emb
```

**Comment by jermainewang** [comment]
You are feeding a tensor variable to PyTorch DataLoader which will break the autograd. I will suggest using `torch.split` to chunk the `data` tensor into batches and then looping over them.

**Comment by Ab-34** [comment]
> ## ❓ Questions and Help
> My DGL version is 0.7.2 which is the latest one. This problem is similar to issue 1046 (#1046).
> 
> I am building a Light-GCN model using DGL with the PyTorch backend. I want to train the model in a mini-batch manner but I got this error:
> 
> ```
> D:\Anaconda3\envs\pytorch\lib\site-packages\torch\autocast_mode.py:141: UserWarning: User provided device_type of 'cuda', but CUDA is not available. Disabling
>   warnings.warn('User provided device_type of \'cuda\', but CUDA is not available. Disabling')
> Traceback (most recent call last):
>   File "D:\lightgcn\src\LightGCN\main_movielens.py", line 122, in <module>
>     batch_loss.backward()
>   File "D:\Anaconda3\envs\pytorch\lib\site-packages\torch\_tensor.py", line 307, in backward
>     torch.autograd.backward(self, gradient, retain_graph, create_graph, inputs=inputs)
>   File "D:\Anaconda3\envs\pytorch\lib\site-packages\torch\autograd\__init__.py", line 154, in backward
>     Variable._execution_engine.run_backward(
>   File "D:\Anaconda3\envs\pytorch\lib\site-packages\torch\autograd\function.py", line 199, in apply
>     return user_fn(self, *args)
>   File "D:\Anaconda3\envs\pytorch\lib\site-packages\torch\cuda\amp\autocast_mode.py", line 111, in decorate_bwd
>     return bwd(*args, **kwargs)
>   File "D:\Anaconda3\envs\pytorch\lib\site-packages\dgl\backend\pytorch\sparse.py", line 272, in backward
>     gidx, op, lhs_target, rhs_target, X_shape, Y_shape = ctx.backward_cache
> TypeError: cannot unpack non-iterable NoneType object
> 
> Process finished with exit code 1
> ```
> 
> Here is the training code raising this problem:
> 
> ```
>     for epoch in range(epochs):
>         # train
>         model.train()
>         # forward
>         final_emb = model(train_g.ndata["id"])
>         pred = DotPredictor()
>         score = pred(train_g, final_emb)
>         ratings = train_g.edata["rating"]
>         data = torch.cat([score, ratings], dim=1).to(device)
>         dataloader = DataLoader(data, batch_size=1024, shuffle=True)
>         for batch in dataloader:
>             batch_score = batch[:, 0]
>             batch_ratings = batch[:, 1]
>             batch_loss = torch.sqrt(torch.mean(mse_loss(batch_score, batch_ratings)))
>             optimizer.zero_grad()
>             batch_loss.backward()
>             optimizer.step()
> ```
> 
> everything is ok when I use this code:
> 
> ```
>     for epoch in range(epochs):
>         # train
>         model.train()
>         # forward
>         final_emb = model(train_g.ndata["id"])
> 
>         pred = DotPredictor()
>         score = pred(train_g, final_emb)
>         ratings = train_g.edata["rating"]
>         loss = torch.sqrt(torch.mean(mse_loss(score, ratings)))
>         
>         optimizer.zero_grad()
>         loss.backward()
>         optimizer.step()
> ```
> 
> Here is the model code:
> 
> ```
> class LightGCN_full(nn.Module):
> 
>     def __init__(self, graph, emb_dim, num_layers):
>         super(LightGCN_full, self).__init__()
>         self.graph = graph
>         self.emb = nn.Embedding(graph.num_nodes(), emb_dim)
>         self.light_conv = GraphConv(emb_dim, emb_dim, weight=False, bias=False, allow_zero_in_degree=True)
>         self.num_layers = num_layers
>         nn.init.normal_(self.emb.weight, std=0.1)
> 
>     def forward(self, id):
>         out = self.emb(id)
>         final_emb = out
>         for i in range(self.num_layers):
>             out = self.light_conv(self.graph, out)
>             final_emb += out
>         final_emb /= self.num_layers + 1
> 
>         return final_emb
> ```

Hey I am facing the exact same error, did you manage to fix it?
