### ISSUE TITLE
[Doc] Improve Documentation for Message Passing and Computing

### ISSUE THREAD

**Issue by mufeili** [dmlc/dgl#357]
## 📚 Documentation

This issue is related to the API documentation for message passing and is motivated by [a discussion thread](https://discuss.dgl.ai/t/source-node-features-are-emptied/75/5). Briefly, when we are performing `update_all` or applying `recv`/`pull` to all nodes, if some nodes do not have incoming edges, a zero placeholder will be employed and likely to overwrite the original node features. This is a bit tricky and can be very harmful for models if not properly handled. Ideally we may also want to add a convenient way for users to check automatically whether a graph is completely connected. What will be a good way to notify users about this?

**Comment by jermainewang** [comment]
There is a paragraph about zero-degree behaviors in the docstring of [`recv`](https://docs.dgl.ai/generated/dgl.DGLGraph.recv.html#dgl.DGLGraph.recv). It's a little bit deep though.

**Comment by mufeili** [comment]
@jermainewang Probably we should still highlight it somewhere else as new comers may directly use `update_all` without paying attention to `recv`?

**Comment by jermainewang** [comment]
@mufeili agree. How about add things like "For nodes with no-incoming message, the reduce function will be skipped. See recv(give link) for more details." in the docstring of `update_all` and `pull`?

**Comment by mufeili** [comment]
@jermainewang Sure. But I think the emphasis should be placed on that if `update_all` and `pull` are applied to nodes with no incoming messages, their node features will be overwritten, yielding highly likely undesired behavior. In that case users should use `send_and_recv` instead.

**Comment by hbsun2113** [comment]
![image](https://user-images.githubusercontent.com/27994442/52909799-14c85780-32c9-11e9-8ef9-26d6c4768423.png)
Could you explain the picture of the PageRank tutorial? I am confused about the type of data and line.
@mufeili

**Comment by mufeili** [comment]
Basically for a directed edge `(i, j)` from source node `i` to destination node `j`, we want to update the feature of `j` (`edge.dst.data` in the figure) based on the feature of `i` (`edge.src.data` in the figure) and optionally the feature of the edge (`edge.data`). The whole process proceeds as follows:
1. The source node `i` sends a message computed by a function of the feature of node `i` and the edge feature `(i, j)` to the destination node `j` and the message is preserved in the `mailbox` of the destination node. 
2. The destination node `j` may have received multiple messages from different source nodes and it applies a reduce function to all the messages received (e.g. averaging over all messages received). The computed result is then used to replace the original node feature of `j`.
3. Finally an apply function may be applied to the node feature of `j` (e.g. a `ReLU` activation function).

I'm also cc @VoVAllen , who draw the figure and see if he wants to add points.

**Comment by VoVAllen** [comment]
The orange line means the output(destination) of the user defined functions and the blue line means the input of the user defined functions.

**Comment by Evgeneus** [comment]
Hi all! I just started with DGL and discovered this problem while debugging, because of observed many zeros. Found the answer in the source code.

@mufeili is right. What about automatically switching to 'send_and_recv' in case of presence of nodes without incoming edges? (of course, showing warnings)

**Comment by VoVAllen** [comment]
@Evgeneus We are trying to make the behavior consistent to the matrix operation, such as sum over neighborhoods operation comparing to `x'=Ax`, which A is the adjacency matrix and x is the feature. If there's no incoming edges, the new feature should be zero. 

We are also aware that the warning message sometimes is confusing, but haven't figure out any better plan.  If you have any good idea for this, feel free to tell us.
