### ISSUE TITLE
Documentation doesn't reflect current bug

### ISSUE THREAD

**Issue by zjost** [dmlc/dgl#3576]
## 📚 Documentation
The 0.7.x documentation talks about the ability to exclude edges in the returned sub-graph for link prediction tasks, which prevents a form of information leak (e.g., [EdgeCollator](https://docs.dgl.ai/api/python/dgl.dataloading.html#dgl.dataloading.EdgeCollator), [EdgeDataLoader](https://docs.dgl.ai/api/python/dgl.dataloading.html#dgl.dataloading.pytorch.EdgeDataLoader)).  However, this is known to not work (#3408) and was merged after the release in #3424.  

I'm not sure if the solution is a documentation update, pushing a minor release, or something else.

**Comment by miangangzhen** [comment]
You may using this function to remove edges in the returned sub-graph for link prediction tasks

```python
def remove_reverse_eid_from_pair_graph(pair_graph, blocks):
    u, v = pair_graph.edges()
    for block in blocks:
        index = block.has_edges_between(u, v)
        eid = block.edge_ids(u[index], v[index])
        block.remove_edges(eid)

        index = block.has_edges_between(v, u)
        eid = block.edge_ids(v[index], u[index])
        block.remove_edges(eid)
```

for example, the demo in #3408 can be fix in this way:
```python
import dgl
import torch

src = torch.tensor([1, 2, 3, 4])
dst = torch.tensor([0, 0, 0, 0])
graph = dgl.graph((torch.cat((src, dst)), torch.cat((dst, src))))
train_eid = torch.tensor([i for i in range(graph.edges()[0].shape[0])])
sampler = dgl.dataloading.MultiLayerFullNeighborSampler(1)
dataloader = dgl.dataloading.EdgeDataLoader(graph, train_eid, sampler, batch_size=1)

for input_nodes, pair_graph, blocks in dataloader:
    remove_reverse_eid_from_pair_graph(pair_graph, blocks) # call the function before gnn
    print(pair_graph.edges(form='uv'))
    print(blocks[0].edges(form='uv'))
    break
```
