### ISSUE TITLE
Is there a limitation on how large a graph can DGL handle?

### ISSUE THREAD

**Issue by nashid** [dmlc/dgl#3580]
## ❓ Questions and Help

Thanks for this great library which I am finding useful in my work. In my case, I have a large graph with many nodes and edges.

I would be curious to know whether there were any experiments with DGL on large graphs. Were there any experiments regarding how large graph DGL can handle effectively?

**Comment by jermainewang** [comment]
There is no theoretical limitation on the size of a graph DGL can handle. We have tried DGL on ogbn-paper100M and got no problem (see [our paper](https://arxiv.org/pdf/2010.05337.pdf)).
