### ISSUE TITLE
There is no runnable .py file in the distributed node classification tutorial

### ISSUE THREAD

**Issue by MiaoZzzz** [dmlc/dgl#3582]
## 📚 Documentation

The python script provided in the distributed node classification tutorial is 1_node_classification.py, but it is wrong and not executable. And in my understanding, it should be divided into two scripts, one for graph division and the other for training. Now these two scripts are together.

**Comment by Rhett-Ying** [comment]
This is expected. It's mainly for illustration. 

If you wanna try with distributed train, pls refer to https://github.com/dmlc/dgl/blob/5f4c8793997b4cbc7da45d829a426d89f84d793f/examples/pytorch/graphsage/experimental/README.md

**Comment by MiaoZzzz** [comment]
> This is expected. It's mainly for illustration.
> 
> If you wanna try with distributed train, pls refer to https://github.com/dmlc/dgl/blob/5f4c8793997b4cbc7da45d829a426d89f84d793f/examples/pytorch/graphsage/experimental/README.md

Thanks a lot. 
I have tried to run with distributed train followed by README file you mentioned, but i still can't run until i modify the source code in train_dist.py. Because in line 175 of the code, the source code is ```new_nids = th.cat([nids for _ in repeat_size] + [nids[:pad_size]], axis=0)```, and an error ```TypeError: int object is not iterable``` will be reported when running. When I change the ```repeat_size``` to ```range(repeat_size)```, it can run normally. I don't know if this modification is reasonable. Is it the source code itself has bug or my problem?

**Comment by VoVAllen** [comment]
@MiaoZzzz It's reasonbale. I just merged the change in https://github.com/dmlc/dgl/pull/3594

**Comment by MiaoZzzz** [comment]
> It's reasonbale. I just merged t

OK, thanks.
