### ISSUE TITLE
Can we add isolated nodes when constructing a heterogeneous graph

### ISSUE THREAD

**Issue by ws-researcher** [dmlc/dgl#3590]
## ❓ Questions and Help
Can we add isolated nodes when constructing a heterogeneous graph？

**Comment by VoVAllen** [comment]
Yes. It's viable

**Comment by BarclayII** [comment]
You could specify the number of nodes of each type in `num_nodes_dict` argument.  A node will be isolated if no edge connects to it (i.e. the node ID did not appear in either `src` or `dst`).

Say `g = dgl.graph(([0], [2]), num_nodes=5)`.  Then node 1, 3, 4 will be isolated.
