### ISSUE TITLE
Is HGT model's performance not so good? Why is it only 40+ accuracy on the ACM data set?

### ISSUE THREAD

**Issue by Mrxiahelong** [dmlc/dgl#3593]
![image](https://user-images.githubusercontent.com/40788339/146369239-db4fdba9-b745-4040-b5e2-d5d110a426ca.png)
In Other models,the acc could reach 80+....

**Comment by Mrxiahelong** [comment]
and I also find  if I change the data["PvsL"] to data["PvsV"], the acc could reach 99%. I don't know what V  means and what  L means, someone could tell me?thanks

**Comment by BarclayII** [comment]
I remember the two datasets are actually different and they also use different features.  I'm also not sure what `PvsL` and `PvsV` mean either :(
