### ISSUE TITLE
About the classification of edges

### ISSUE THREAD

**Issue by WindLWQ** [dmlc/dgl#3596]
I am trying to complete a binary classification task on opposite sides in an undirected graph.  As mentioned in the tutorial, I constructed a bidirectional graph and made MLP classification predictions for all edges.  Normally, the prediction result of the bidirectional edge between two points should be the same (because they are all the same undirected edge), but the final result is not like this.  How can I solve this problem?

**Comment by BarclayII** [comment]
If you want the output to be symmetric, you can sum the incident node representations before passing into the MLP.
