### ISSUE TITLE
 dgl._ffi.base.DGLError: Cannot assign node feature "h" on device cuda:0 to a graph on device cpu. Call DGLGraph.to() to copy the graph to the same device.

### ISSUE THREAD

**Issue by sevencheung2021** [dmlc/dgl#3601]
## To Reproduce

1.
1.
1.

## Environment

 - DGL Version (0.7.2):
 - Backend Library & Version (e.g., PyTorch1.5.0.):
 - OS (e.g., centos 7):
 - How you installed DGL (`conda):0 - Build command you used (if compiling from source):
 - Python version:3.6.5
 - CUDA/cuDNN version (if applicable): cu10.1
 - GPU models and configuration (e.g. V100):
 - Any other relevant information:

## Additional context

![image](https://user-images.githubusercontent.com/80093805/146742684-375d70bd-e227-4c9c-b523-192baacafb41.png)
![image](https://user-images.githubusercontent.com/80093805/146742796-ece87ba6-36a3-4da3-ae61-4ac924b510fe.png)

**Comment by VoVAllen** [comment]
Could you post your full error message?
