### ISSUE TITLE
Issue building from source:   Target "tensorpipe" links to target "uv::uv" but the target was not found.

### ISSUE THREAD

**Issue by hnisonoff** [dmlc/dgl#3605]
## 🐛 Bug

I am trying to build from source on a Power CPU. I keep getting errors about the uv library. 

## To Reproduce

1. cmake -DUSE_CUDA=ON -DUSE_AVX=OFF -DUSE_LIBXSMM=OFF  ..

> cmake -DUSE_CUDA=ON -DUSE_AVX=OFF -DUSE_LIBXSMM=OFF -DPYTHON_INTERP=/usr/workspace/nisonoff/anaconda/envs/opence/bin/python ..
-- Start configuring project dgl
-- Build with CUDA support
-- Found CUDA_TOOLKIT_ROOT_DIR=/usr/tce/packages/cuda/cuda-10.1.243
-- Found CUDA_CUDART_LIBRARY=/usr/tce/packages/cuda/cuda-10.1.243/lib64/libcudart.so
-- Found CUDA_CUBLAS_LIBRARY=/usr/lib64/libcublas.so
-- Found CUDA_CURAND_LIBRARY=/usr/tce/packages/cuda/cuda-10.1.243/lib64/libcurand.so
-- Detected CUDA of version 10.1. Use external CUB/Thrust library.
-- Found OpenMP_C: -fopenmp (found version "4.5")
-- Found OpenMP_CXX: -fopenmp (found version "4.5")
-- Build with OpenMP.
-- -fopenmp -O2 -Wall -fPIC -std=c++11  -DIDXTYPEWIDTH=64 -DREALTYPEWIDTH=32
-- Running GPU architecture autodetection
-- Found CUDA arch 7.0 7.0 7.0 7.0
-- CUDA flags: -Xcompiler ,-fopenmp,-O2,-Wall,-fPIC,,,-DIDXTYPEWIDTH=64,-DREALTYPEWIDTH=32;--expt-relaxed-constexpr;-gencode;arch=compute_70,code=sm_70;--expt-extended-lambda;-Wno-deprecated-declarations;-std=c++14
-- Found OpenMP_C: -fopenmp (found version "4.5")
-- Found OpenMP_CXX: -fopenmp (found version "4.5")
-- /usr/workspace/nisonoff/install_dgl/dgl/third_party/dmlc-core/cmake/build_config.h.in -> include/dmlc/build_config.h
-- Configuring done
CMake Error at /usr/tce/packages/cmake/cmake-3.21.1/share/cmake/Modules/FindCUDA.cmake:1985 (add_library):
  Target "dgl" links to target "uv::uv" but the target was not found.
  Perhaps a find_package() call is missing for an IMPORTED target, or an
  ALIAS target is missing?
Call Stack (most recent call first):
  CMakeLists.txt:199 (cuda_add_library)

CMake Error at third_party/tensorpipe/tensorpipe/CMakeLists.txt:193 (add_library):
  Target "tensorpipe" links to target "uv::uv" but the target was not found.
  Perhaps a find_package() call is missing for an IMPORTED target, or an
  ALIAS target is missing?

## Environment

 - DGL Version (e.g., 1.0):
 - Backend Library & Version (e.g., PyTorch 0.4.1, MXNet/Gluon 1.3):
 - OS (e.g., Linux): Linux
 - How you installed DGL (`conda`, `pip`, source): source
 - Build command you used (if compiling from source): cmake -DUSE_CUDA=ON -DUSE_AVX=OFF -DUSE_LIBXSMM=OFF
 - Python version:
 - CUDA/cuDNN version (if applicable):
 - GPU models and configuration (e.g. V100):
 - Any other relevant information:

**Comment by VoVAllen** [comment]
Have you tried calling `git submodule update --init --recursive`? The uv folder should be located at `third_party/tensorpipe/third_party/libuv` after calling that
