### ISSUE TITLE
The libuv dependency in tensorpipe generates `-Werror` flag and cannot compile.

### ISSUE THREAD

**Issue by yzh119** [dmlc/dgl#3608]
## 🐛 Bug

I tried to compile the master branch of DGL on my Fedora machine and got following errors.

```
/home/***/repos/dgl/third_party/tensorpipe/third_party/libuv/src/unix/thread.c: In function ‘thread_stack_size’:
/home/***/repos/dgl/third_party/tensorpipe/third_party/libuv/src/unix/thread.c:195:24: error: comparison of integer expressions of different signedness: ‘rlim_t’ {aka ‘long unsigned int’} and ‘long int’ [-Werror=sign-compare]
  195 |       if (lim.rlim_cur >= PTHREAD_STACK_MIN)
      |                        ^~
/home/***/repos/dgl/third_party/tensorpipe/third_party/libuv/src/unix/thread.c: In function ‘uv_thread_create_ex’:
/home/***/repos/dgl/third_party/tensorpipe/third_party/libuv/src/unix/thread.c:243:20: error: comparison of integer expressions of different signedness: ‘size_t’ {aka ‘long unsigned int’} and ‘long int’ [-Werror=sign-compare]
  243 |     if (stack_size < PTHREAD_STACK_MIN)
      |                    ^
cc1: all warnings being treated as errors
```

I checked that the configure file in libuv dependencies do generate `Werror` flags, which I cannot disable in outermost CMakeLists.txt. Any ideas on how to fix?

## Expected behavior

The `Werror` flag should not be enabled for those files, otherwise libuv should resolve those warning.

## Environment

 - DGL Version (e.g., 1.0): master branch
 - Backend Library & Version (e.g., PyTorch 0.4.1, MXNet/Gluon 1.3): PyTorch 1.10.1
 - OS (e.g., Linux): Fedora 35
 - How you installed DGL (`conda`, `pip`, source): source
 - Build command you used (if compiling from source):
 - Python version: 3.10
 - CUDA/cuDNN version (if applicable): 11.5
 - GPU models and configuration (e.g. V100):
 - Any other relevant information:

**Comment by VoVAllen** [comment]
You can try debug from here https://github.com/dmlc/dgl/blob/master/CMakeLists.txt#L256
. And I haven't meet the error you mentioned

**Comment by VoVAllen** [comment]
You can also try replace out `Werror` if needed

**Comment by BarclayII** [comment]
I think `Werror` should be removed as this is unfriendly for toolchains across different versions; one allowed feature will become a warning on the other.

**Comment by yzh119** [comment]
Actually, I haven't figured out where was this flag introduced.

**Comment by yzh119** [comment]
It turns out my gcc version is too new (v11.2), downgrading it would work... (holy fedora).

**Comment by tingyu66** [comment]
Same error here with GCC 11.2.0 on Ubuntu 22.04.1 LTS.

**Comment by beew** [comment]
I am still encountering this problem trying to build 1.0.1 on Ubuntu 22,.04. Any workaround?

I built with gcc 9.3 and still have the same error.

**Comment by fkh12345** [comment]
> I am still encountering this problem trying to build 1.0.1 on Ubuntu 22,.04. Any workaround?
> 
> I built with gcc 9.5.0 and still have the same error.

I can either build on Ubuntu 22.04. However, I can build DGL with the source code on Ubuntu 18.04 and 20.04 using gcc-9.5.0.
