### ISSUE TITLE
what should I do when batch the heterograph that don't have same number of edge types?

### ISSUE THREAD

**Issue by LawsonAbs** [dmlc/dgl#3610]
## 🚀 Feature

batch the heterograph that don't have same number of edge types.

## Motivation

the heterograph in batch may don't have the consistent number of edge types, while if we batch them, it coulb be error. So what should we do?

**Comment by Rhett-Ying** [comment]
as we mentioned in the doc: `For heterograph inputs, they must share the same set of relations (i.e., node types and edge types) and the function will perform batching on each relation one by one. `

you have to add missing etypes with empty edges like `('user', 'like', 'item'):([], [])` to meet the requirement.

**Comment by LawsonAbs** [comment]
If the completion of etypes can be done by batch function in dgl, that will be more conveninet.

**Comment by Rhett-Ying** [comment]
yeah, that could be an improvement. let me mark it for now.
