### ISSUE TITLE
[Benchmark] async_copy from CPU to multi-GPUs

### ISSUE THREAD

**Issue by Rhett-Ying** [dmlc/dgl#3612]
## 🚀 Feature

async_copy including graph and feature is enabled, we need to benchmark on multi-gpu: does NCCL supports transfer data from same CPU to different GPUs in parallel?

cc @BarclayII @nv-dlasalle

**Comment by nv-dlasalle** [comment]
NCCL is for GPU to GPU communication, not CPU to GPU.
