### ISSUE TITLE
results from faiss_gpu are different every time

### ISSUE THREAD

**Issue by GlennCGL** [dmlc/dgl#3617]
why results from faiss_gpu are different every time?

**Comment by hetong007** [comment]
FAISS is a third-party library: https://github.com/facebookresearch/faiss, and its GPU algorithm is approximation, thus the results from re-running can be different. To achieve deterministic result, please build the graph on CPU. 

More details can be found in their paper: https://arxiv.org/abs/1702.08734

**Comment by GlennCGL** [comment]
> FAISS is a third-party library: https://github.com/facebookresearch/faiss, and its GPU algorithm is a fast approximation, thus the results from re-running can be different. To achieve deterministic result, please build the graph on CPU.
> 
> More details can be found in their paper: https://arxiv.org/abs/1702.08734

thanks. and I want to know if there is an c++ version for dgl library?

**Comment by hetong007** [comment]
Are you looking for a C++ version of DGL, or a C++ version of the k-nearest neighbor algorithm?
