### ISSUE TITLE
How to build a symmetric heterogeneous graph? 

### ISSUE THREAD

**Issue by qhd1996** [dmlc/dgl#3618]
## 📚 Documentation
@yzhliu 

https://docs.dgl.ai/en/0.6.x/guide/graph-heterogeneous.html?highlight=heterograph
 I am wondering how to build a symmetric heterogeneous graph using DGL.
The doc says every has a src_node_type and a dst_node_type, but my graph is a undirected heterogeneous graph, which means there is not src_node and dst_node.

**Comment by mufeili** [comment]
What do you mean by "undirected heterogeneous graph"? Can you provide a concrete example for the graph?

**Comment by qhd1996** [comment]
> What do you mean by "undirected heterogeneous graph"? Can you provide a concrete example for the graph?

For instance，I build a graph consisting of node type 'word' and 'do, and the edge between 'word' and 'doc' is 'tf-idf'. The text graph is a undirected graph, which means the word can learn representaion from doc and vice versa.

**Comment by BarclayII** [comment]
This is now supported in https://docs.dgl.ai/generated/dgl.transforms.AddReverse.html#dgl.transforms.AddReverse.
