### ISSUE TITLE
Maybe a bug in dgl 0.7.2

### ISSUE THREAD

**Issue by kxchern** [dmlc/dgl#3624]
## 🐛 Bug

hi dgl-team,

    I need to use the torch.autograd.grad() to hook the grad information in GNN layers. However,  torch.autograd.grad() will return illegality information while performing muti-times with dgl-0.7.2 version.  

    For example, 

    We fist hook the outputs[0][0] using 'grads = torch.autograd.grad(outputs=outputs[0][0],inputs=inputs,retain_graph=retain_graph,create_graph=create_graph,allow_unused=True)[0]' , it can succeed, it returned a tensor.

    We second hook the outputs[0][1] using 'grads = torch.autograd.grad(outputs=outputs[0][1],inputs=inputs,retain_graph=retain_graph,create_graph=create_graph,allow_unused=True)[0]' , it failed, it return a ‘0x7fdc51046e50’.

    We installed dgl-0.7.2 by 'pip install dgl -f https://data.dgl.ai/wheels/repo.html' on Cuda 10.2 platform.

    Finally, we installed dgl-0.7.0 to fix the above problem. this maybe a bug in dgl-0.7.2 version, please check that.

That's all. Thank you.

**Comment by VoVAllen** [comment]
Could you provide a reproducible code for us to debug?

**Comment by Kai-Xuan** [comment]
Hello,

please find a  reproducible code at  https://github.com/kai-xuan/dgl072-debug

kaixuan
------------------------------------------------------------------
发件人：Jinjing Zhou ***@***.***>
发送时间：2022年1月6日(星期四) 11:00
收件人：dmlc/dgl ***@***.***>
抄　送：Kai-Xuan Chen ***@***.***>; Author ***@***.***>
主　题：Re: [dmlc/dgl] Maybe a bug in dgl 0.7.2 (Issue #3624)

Could you provide a reproducible code for us to debug?
—
Reply to this email directly, view it on GitHub, or unsubscribe.
Triage notifications on the go with GitHub Mobile for iOS or Android.

**Comment by MaKaili** [comment]
I also get an illegal memory access problem when I set retain_graph=True. It seems to occur in dgl/backend/pytorch/sparse.py line 524.
