### ISSUE TITLE
The mask in MultiLayerDropoutSampler should be set bool type .

### ISSUE THREAD

**Issue by szprob** [dmlc/dgl#3626]
## 📚 Documentation

In doc 6.4 Customizing Neighborhood Sampler.

The mask in MultiLayerDropoutSampler should be bool type .

**Comment by VoVAllen** [comment]
![image](https://user-images.githubusercontent.com/8686776/148515518-d61b9e2a-075a-4f93-9b45-ff8fa9c22915.png)

I think it's already bool?

**Comment by szprob** [comment]
i mean hear
![image](https://user-images.githubusercontent.com/22837128/150742660-5ca0c6b4-79ed-4af7-8e6a-a4244355dea9.png)

**Comment by VoVAllen** [comment]
Thanks for reporting. Make a PR at https://github.com/dmlc/dgl/pull/3683
