### ISSUE TITLE
Example distributed codes hang at initialization and never start training

### ISSUE THREAD

**Issue by Peter-1213** [dmlc/dgl#3629]
## 🐛 Bug

The example distributed codes in https://github.com/dmlc/dgl/tree/master/examples/pytorch/graphsage/experimental hangs at initialization. The hanged lines can be different at initialization, according to where the log stop to print anymore. I've tried all the .py files in the directory and the behaviors are the same.

## To Reproduce

1. Follow the instructions in the demo code directory
2. Run `python3 /workspace/tools/launch.py --workspace /workspace/examples/pytorch/graphsage/experimental/ --num_trainers 4 --num_samplers 4 --num_servers 1 --part_config data/ogb-product.json --ip_config ip_config.txt --ssh_port 4322 "/opt/conda/bin/python train_dist.py --graph_name ogb-product --ip_config ip_config.txt --num_epochs 30 --batch_size 1000 --num_gpus 4 --backend nccl" --extra_envs NCCL_DEBUG=INFO`. This is an running script in my environment and contains something env-specific. But I'll keep it in case there's some wrong configurations.

Here's an example of log when running `train_dist.py` using the above command line, I will mark where the log stop at different case of hanging:

> root@HOST-10-142-40-25:/workspace/examples/pytorch/graphsage/experimental# python3 /workspace/tools/launch.py --workspace /workspace/examples/pytorch/graphsage/experimental/ --num_trainers 4 --num_samplers 4 --num_servers 1 --part_config data/ogb-product.json --ip_config ip_config.txt --ssh_port 4322 "/opt/conda/bin/python train_dist.py --graph_name ogb-product --ip_config ip_config.txt --num_epochs 30 --batch_size 1000 --num_gpus 4 --backend nccl" --extra_envs NCCL_DEBUG=INFO GLOO_SOCKET_IFNAME=bond0 TP_SOCKET_IFNAME=bond0 NCCL_SOCKET_IFNAME=bond0
> The number of OMP threads per trainer is set to 14
> cleanupu process runs
> Warning: Permanently added '[10.142.40.25]:4322' (ECDSA) to the list of known hosts.
> Warning: Permanently added '[10.142.40.26]:4322' (ECDSA) to the list of known hosts.
> Warning: Permanently added '[10.142.40.27]:4322' (ECDSA) to the list of known hosts.
> Warning: Permanently added '[10.142.40.25]:4322' (ECDSA) to the list of known hosts.
> Warning: Permanently added '[10.142.40.26]:4322' (ECDSA) to the list of known hosts.
> Warning: Permanently added '[10.142.40.27]:4322' (ECDSA) to the list of known hosts.
> Using backend: pytorch
> Using backend: pytorch
> Using backend: pytorch
> Using backend: pytorch
> Using backend: pytorch
> Using backend: pytorchUsing backend: pytorchUsing backend: pytorch
> 
> 
> Using backend: pytorch
> Using backend: pytorch
> Using backend: pytorch
> Using backend: pytorch
> Namespace(backend='nccl', batch_size=1000, batch_size_eval=100000, dataset=None, dropout=0.5, eval_every=5, fan_out='10,25', graph_name='ogb-product', id=None, ip_config='ip_config.txt', local_rank=2, log_every=20, lr=0.003, n_classes=None, num_clients=None, num_epochs=30, num_gpus=4, num_hidden=16, num_layers=2, part_config=None, standalone=False)
> Namespace(backend='nccl', batch_size=1000, batch_size_eval=100000, dataset=None, dropout=0.5, eval_every=5, fan_out='10,25', graph_name='ogb-product', id=None, ip_config='ip_config.txt', local_rank=0, log_every=20, lr=0.003, n_classes=None, num_clients=None, num_epochs=30, num_gpus=4, num_hidden=16, num_layers=2, part_config=None, standalone=False)
> Namespace(backend='nccl', batch_size=1000, batch_size_eval=100000, dataset=None, dropout=0.5, eval_every=5, fan_out='10,25', graph_name='ogb-product', id=None, ip_config='ip_config.txt', local_rank=2, log_every=20, lr=0.003, n_classes=None, num_clients=None, num_epochs=30, num_gpus=4, num_hidden=16, num_layers=2, part_config=None, standalone=False)
> Namespace(backend='nccl', batch_size=1000, batch_size_eval=100000, dataset=None, dropout=0.5, eval_every=5, fan_out='10,25', graph_name='ogb-product', id=None, ip_config='ip_config.txt', local_rank=0, log_every=20, lr=0.003, n_classes=None, num_clients=None, num_epochs=30, num_gpus=4, num_hidden=16, num_layers=2, part_config=None, standalone=False)
> Namespace(backend='nccl', batch_size=1000, batch_size_eval=100000, dataset=None, dropout=0.5, eval_every=5, fan_out='10,25', graph_name='ogb-product', id=None, ip_config='ip_config.txt', local_rank=1, log_every=20, lr=0.003, n_classes=None, num_clients=None, num_epochs=30, num_gpus=4, num_hidden=16, num_layers=2, part_config=None, standalone=False)
> Warning! Interface: eth0 
> IP address not available for interface.
> ... (interface ...)
> Namespace(backend='nccl', batch_size=1000, batch_size_eval=100000, dataset=None, dropout=0.5, eval_every=5, fan_out='10,25', graph_name='ogb-product', id=None, ip_config='ip_config.txt', local_rank=0, log_every=20, lr=0.003, n_classes=None, num_clients=None, num_epochs=30, num_gpus=4, num_hidden=16, num_layers=2, part_config=None, standalone=False)
> Namespace(backend='nccl', batch_size=1000, batch_size_eval=100000, dataset=None, dropout=0.5, eval_every=5, fan_out='10,25', graph_name='ogb-product', id=None, ip_config='ip_config.txt', local_rank=2, log_every=20, lr=0.003, n_classes=None, num_clients=None, num_epochs=30, num_gpus=4, num_hidden=16, num_layers=2, part_config=None, standalone=False)
> Namespace(backend='nccl', batch_size=1000, batch_size_eval=100000, dataset=None, dropout=0.5, eval_every=5, fan_out='10,25', graph_name='ogb-product', id=None, ip_config='ip_config.txt', local_rank=1, log_every=20, lr=0.003, n_classes=None, num_clients=None, num_epochs=30, num_gpus=4, num_hidden=16, num_layers=2, part_config=None, standalone=False)
> Namespace(backend='nccl', batch_size=1000, batch_size_eval=100000, dataset=None, dropout=0.5, eval_every=5, fan_out='10,25', graph_name='ogb-product', id=None, ip_config='ip_config.txt', local_rank=1, log_every=20, lr=0.003, n_classes=None, num_clients=None, num_epochs=30, num_gpus=4, num_hidden=16, num_layers=2, part_config=None, standalone=False)
> Warning! Interface: eth0 
> ... (repeated warnings for interface)
> Namespace(backend='nccl', batch_size=1000, batch_size_eval=100000, dataset=None, dropout=0.5, eval_every=5, fan_out='10,25', graph_name='ogb-product', id=None, ip_config='ip_config.txt', local_rank=3, log_every=20, lr=0.003, n_classes=None, num_clients=None, num_epochs=30, num_gpus=4, num_hidden=16, num_layers=2, part_config=None, standalone=False)
> ... (repeated warnings for interface)
> Namespace(backend='nccl', batch_size=1000, batch_size_eval=100000, dataset=None, dropout=0.5, eval_every=5, fan_out='10,25', graph_name='ogb-product', id=None, ip_config='ip_config.txt', local_rank=3, log_every=20, lr=0.003, n_classes=None, num_clients=None, num_epochs=30, num_gpus=4, num_hidden=16, num_layers=2, part_config=None, standalone=False)
> Warning! Interface: eth0 
> IP address not available for interface.
> ... (repeated warnings for interface)
> Namespace(backend='nccl', batch_size=1000, batch_size_eval=100000, dataset=None, dropout=0.5, eval_every=5, fan_out='10,25', graph_name='ogb-product', id=None, ip_config='ip_config.txt', local_rank=3, log_every=20, lr=0.003, n_classes=None, num_clients=None, num_epochs=30, num_gpus=4, num_hidden=16, num_layers=2, part_config=None, standalone=False)
> ... (repeated warnings for interface)
> Warning! Interface: ib1 
> IP address not available for interface.
> [09:20:29] /opt/dgl/src/rpc/tensorpipe/tp_communicator.cc:46: Cannot connect to remove server tcp://10.142.40.27:2333. Wait to retry
> [09:20:29] /opt/dgl/src/rpc/tensorpipe/tp_communicator.cc:46: Cannot connect to remove server tcp://10.142.40.27:2333. Wait to retry
> [09:20:29] /opt/dgl/src/rpc/tensorpipe/tp_communicator.cc:46: Cannot connect to remove server tcp://10.142.40.27:2333. Wait to retry
> ... (repeated wait to retry logs)
> Machine (0) client (3) connect to server successfuly!
> Machine (0) client (7) connect to server successfuly!
> Machine (0) client (12) connect to server successfuly!
> Machine (0) client (19) connect to server successfuly!
> Machine (1) client (22) connect to server successfuly!
> Machine (1) client (24) connect to server successfuly!
> Machine (1) client (37) connect to server successfuly!
> Machine (1) client (38) connect to server successfuly!
> Machine (2) client (44) connect to server successfuly!
> Machine (2) client (47) connect to server successfuly!
> Machine (2) client (52) connect to server successfuly!
> Machine (2) client (59) connect to server successfuly!
> rank: 5
> rank: 6
> rank: 4
> rank: 7
> rank: 11
> rank: 8
> rank: 10
> rank: 9
> rank: 2rank:
>  0
> rank: 3
> rank: 1
> **!!The first hanging case. Sometimes the log stops here and doesn't print anything below anymore.**
> part 1, train: 16385 (local: 15395), val: 3277 (local: 3277), test: 184424 (local: 184424)
> part 3, train: 16384 (local: 15393), val: 3277 (local: 3277), test: 184424 (local: 184424)
> part 0, train: 16385 (local: 15380), val: 3277 (local: 3277), test: 184425 (local: 184425)
> part 2, train: 16385 (local: 15445), val: 3277 (local: 3277), test: 184424 (local: 184424)
> #labels: 47
> before pad data
> #labels: 47
> before pad data
> before ar
> before ar
> **!!The second hanging case. Only part of the processes(2 out of 4 here) print \#labels and continues, then get block at an all_reduce function in train_dist.py:170** 

**!!Rarely there's a third case. All the processes print \#labels and get to the all_reduce function. Then the NCCL_DEBUG=INFO will print some NCCL initialization logs. But the code will still hang at the above all_reduce function. An example:**
> ... (the same as case 2)
> #labels: 47
> before pad data
> #labels: 47
> before pad data
> #labels: 47
> before pad data
> #labels: 47
> before pad data
> before ar
> before ar
> before ar
> before ar
> HOST-10-142-40-25:105617:105617 [0] NCCL INFO Bootstrap : Using bond0:10.142.40.25<0>
> HOST-10-142-40-25:105617:105617 [0] NCCL INFO Plugin Path : /opt/hpcx/nccl_rdma_sharp_plugin/lib/libnccl-net.so
> HOST-10-142-40-25:105617:105617 [0] NCCL INFO P2P plugin IBext
> HOST-10-142-40-25:105617:105617 [0] NCCL INFO NET/IB : No device found.
> HOST-10-142-40-25:105617:105617 [0] NCCL INFO NET/IB : No device found.
> HOST-10-142-40-25:105617:105617 [0] NCCL INFO NET/Socket : Using [0]bond0:10.142.40.25<0>
> HOST-10-142-40-25:105617:105617 [0] NCCL INFO Using network Socket
> NCCL version 2.10.3+cuda11.3
> HOST-10-142-40-25:105619:105619 [2] NCCL INFO Bootstrap : Using bond0:10.142.40.25<0>
> HOST-10-142-40-25:105619:105619 [2] NCCL INFO Plugin Path : /opt/hpcx/nccl_rdma_sharp_plugin/lib/libnccl-net.so
> HOST-10-142-40-25:105619:105619 [2] NCCL INFO P2P plugin IBext
> HOST-10-142-40-25:105619:105619 [2] NCCL INFO NET/IB : No device found.
> HOST-10-142-40-25:105619:105619 [2] NCCL INFO NET/IB : No device found.
> HOST-10-142-40-25:105619:105619 [2] NCCL INFO NET/Socket : Using [0]bond0:10.142.40.25<0>
> HOST-10-142-40-25:105619:105619 [2] NCCL INFO Using network Socket
> HOST-10-142-40-25:105620:105620 [3] NCCL INFO Bootstrap : Using bond0:10.142.40.25<0>
> HOST-10-142-40-25:105620:105620 [3] NCCL INFO Plugin Path : /opt/hpcx/nccl_rdma_sharp_plugin/lib/libnccl-net.so
> HOST-10-142-40-25:105620:105620 [3] NCCL INFO P2P plugin IBext
> HOST-10-142-40-25:105620:105620 [3] NCCL INFO NET/IB : No device found.
> HOST-10-142-40-25:105620:105620 [3] NCCL INFO NET/IB : No device found.
> HOST-10-142-40-25:105620:105620 [3] NCCL INFO NET/Socket : Using [0]bond0:10.142.40.25<0>
> HOST-10-142-40-25:105620:105620 [3] NCCL INFO Using network Socket
> HOST-10-142-40-25:105618:105618 [1] NCCL INFO Bootstrap : Using bond0:10.142.40.25<0>
> HOST-10-142-40-25:105618:105618 [1] NCCL INFO Plugin Path : /opt/hpcx/nccl_rdma_sharp_plugin/lib/libnccl-net.so
> HOST-10-142-40-25:105618:105618 [1] NCCL INFO P2P plugin IBext
> HOST-10-142-40-25:105618:105618 [1] NCCL INFO NET/IB : No device found.
> HOST-10-142-40-25:105618:105618 [1] NCCL INFO NET/IB : No device found.
> HOST-10-142-40-25:105618:105618 [1] NCCL INFO NET/Socket : Using [0]bond0:10.142.40.25<0>
> HOST-10-142-40-25:105618:105618 [1] NCCL INFO Using network Socket

After a long time, the timeout logs for case 2-3 are:
> python3 /workspace/tools/launch.py --workspace /workspace/examples/pytorch/graphsage/experimental/ --num_trainers 4 --num_samplers 4 --num_servers 1 --part_config data/ogb-product.json --ip_config ip_config.txt --ssh_port 4322 "/opt/conda/bin/python train_dist.py --graph_name ogb-product --ip_config ip_config.txt --num_epochs 30 --batch_size 1000 --num_gpus 4 --backend nccl" --extra_envs NCCL_DEBUG=INFOTraceback (most recent call last):
>   File "train_dist.py", line 353, in <module>
>     main(args)
>   File "train_dist.py", line 323, in main
>     run(args, device, data)
>   File "train_dist.py", line 190, in run
>     train_nid = pad_data(train_nid, device)
>   File "train_dist.py", line 171, in pad_data
>     dist.all_reduce(num_nodes, dist.ReduceOp.MAX)
>   File "/opt/conda/lib/python3.8/site-packages/torch/distributed/distributed_c10d.py", line 1285, in all_reduce
>     work = default_pg.allreduce([tensor], opts)
> RuntimeError: Socket Timeout

I'd say the probability is 50%-40%-10% for the three cases.

## Expected behavior

Training goes smoothly and doesn't hang, of course.

## Environment

 - DGL Version (e.g., 1.0): dgl_cu113-0.8a220105
 - Backend Library & Version (e.g., PyTorch 0.4.1, MXNet/Gluon 1.3): Pytorch 1.10.0
 - OS (e.g., Linux): Linux (inside the ngc pytorch docker)
 - How you installed DGL (`conda`, `pip`, source): I've tried pip and source, the behavior was exactly the same.
 - Build command you used (if compiling from source): Following the official guide
 - Python version: 3.8
 - CUDA/cuDNN version (if applicable): 11.3
 - GPU models and configuration (e.g. V100): I've tried on A100 (3 nodes with 8 GPU each) and RTX 3090 (2 nodes with 4 GPU each) Machines. The behavior was the same.
 - Any other relevant information:

## Additional context

I've tried different installation method & running on different clusters, and also changing the configurations in the command lines (num of samplers, nccl/gloo, --dgl_sparse, num_gpus, etc.). But I haven't succeeded starting a distributed training yet. I tried the standalone code (by using --standalone) and it worked fine.

**Comment by VoVAllen** [comment]
Seems weird. Could you try remove pad_data functions?

**Comment by VoVAllen** [comment]
I tested it works well on my environment with 1 gpu + gloo backend. Could you try remove the usage of pad_data in the code first?

**Comment by VoVAllen** [comment]
Also could you reduce the number of trainer and sampler in your case?
