### ISSUE TITLE
error: no matching function for call to 'min' happens in parallel_for.h when compile.

### ISSUE THREAD

**Issue by kennethxian** [dmlc/dgl#3631]
## 🐛 Bug

When compile with "make -j4" command from MacOS, the error of "error: no matching function for call to 'min' " happens.
change the line: auto end_tid = std::min(end, chunk_size + begin_tid)
to: auto end_tid = std::min(end, (size_t)(chunk_size + begin_tid))

can make it pass.

 - DGL Version : master branch

**Comment by VoVAllen** [comment]
Thanks for the catch. Would you like to submit a PR for this? Thanks
