### ISSUE TITLE
How can I compute the  Assortivity or Disassortivity of a node classification dataset?

### ISSUE THREAD

**Issue by jiaruHithub** [dmlc/dgl#3639]
How can I compute the  Assortivity or Disassortivity of a node classification dataset?
I can't find the func. in the library.
Thank you for ur help.

**Comment by jermainewang** [comment]
Duplicate question here: https://discuss.dgl.ai/t/how-can-i-compute-the-assortivity-or-disassortivity-of-a-node-classification-dataset/2622/2
