### ISSUE TITLE
Is it possible to check if a graph is undirected in DGL?

### ISSUE THREAD

**Issue by LspongebobJH** [dmlc/dgl#3644]
## ❓ Questions and Help
I've already known that there's an API `dgl.to_bidirected` to convert a graph to an undirected graph. I'm wondering if there's an API to check if a graph is already an undirected/bidirected graph?

Before proceeding, please note that we recommend
using our discussion forum (https://discuss.dgl.ai) for
general questions. As a result, this issue will
likely be CLOSED shortly.

**Comment by mufeili** [comment]
You can implement that yourself as follows.

```python
import dgl

def is_undirected(g):
    # remove duplicate edges
    g = dgl.to_simple(g)
    bg = dgl.to_bidirected(g)
    return bg.num_edges() == g.num_edges()
```

**Comment by LspongebobJH** [comment]
noted and thks!
