### ISSUE TITLE
Error while compiling from source: "‘decay_t’ is not a member of ‘std’"

### ISSUE THREAD

**Issue by lvrcek** [dmlc/dgl#3651]
## 🐛 Bug

Hi,

I get an error while trying to compile DGL from source in order to enable FP16 computation. The first error message I get is this:
```
‘decay_t’ is not a member of ‘std’
```
The full error message is far longer though and I attached it at the end of this report.

## To Reproduce

I simply followed the instructions given here: https://docs.dgl.ai/en/0.6.x/guide/mixed_precision.html#installation
However when I run the command `make -j` the mentioned error. 

## Expected behavior

Compile without an error.

## Environment

 - DGL Version: 0.7.2 (latest-master branch)
 -  gcc version: 9.3.0
 - PyTorch: 1.9.0
 - OS: Ubuntu 20.04.2 LTS
 - Python version: 3.8.12
 - CUDA/cuDNN version: 11.2
 - GPU models and configuration (e.g. V100): A100

## Additional context

I am working on a server where I don't have admin privileges, so cmake and zlib are installed through conda:
https://anaconda.org/anaconda/cmake

Full error message:
[error.txt](https://github.com/dmlc/dgl/files/7870127/error.txt)

Thank you!

**Comment by VoVAllen** [comment]
What's your gcc version? 
Conda also supports newer gcc https://anaconda.org/conda-forge/gcc

**Comment by VoVAllen** [comment]
Similar to question at https://github.com/avast/yaracpp/issues/3.

You need gcc>=4.9

**Comment by lvrcek** [comment]
The gcc version is 9.3.0. I will update the first post with that info.

**Comment by VoVAllen** [comment]
Could you also upload the log of cmake? It's a bit weird. Probably the C++ standard is not properly set

**Comment by lvrcek** [comment]
Sure, here is the CMakeError.log and CMakeOutput.log

[CMakeError.log](https://github.com/dmlc/dgl/files/7874358/CMakeError.log)

[CMakeOutput.log](https://github.com/dmlc/dgl/files/7874359/CMakeOutput.log)

**Comment by VoVAllen** [comment]
Hi,

How did you get those output? I think it's different from what I saw when I type in `cmake ..`.

Also I found there's `-std=c++11` command in your log, which I think might cause the problem since now C++ 14 is needed

**Comment by lvrcek** [comment]
I just ran `cmake -DUSE_CUDA=ON -DUSE_FP16=ON ..` as given in the instructions for using mixed precision.

However, after some further testing I realized that gcc is already installed on the server by default. I also realized that somehow gcc also got installed inside the conda environment, not sure how as I'm certain I only installed cmake (which is not available on the server). This gcc inside the conda environment is also version 9.3.0.

Using the server's gcc I have managed to compile the dgl binaries now. It appears that different gcc executables somehow broke the compiling of DGL binaries, even though both gccs are of the same version.

I have another question. Now that I have managed to install it DGL inside my project repo, how do I import it?
The directory tree looks something like this:
```
project-repo
| - project file and other directories
| - dgl
    | - python
        | - dgl
            | - dgl implementation
```

Basically, in case I run python inside my project repo and type `import dgl.python.dgl` I will get the following error message:
```
>>> import dgl.python.dgl
[13:49:11] /home/vrcekl/npf_test/dgl/src/runtime/tensordispatch.cc:43: TensorDispatcher: dlopen failed: /home/vrcekl/npf_test/dgl/build/tensoradapter/pytorch/libtensoradapter_pytorch_1.9.0.so: cannot open shared object file: No such file or directory
Using backend: pytorch
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "/home/vrcekl/npf_test/dgl/python/dgl/__init__.py", line 13, in <module>
    from .backend import load_backend, backend_name
  File "/home/vrcekl/npf_test/dgl/python/dgl/backend/__init__.py", line 107, in <module>
    load_backend(get_preferred_backend())
  File "/home/vrcekl/npf_test/dgl/python/dgl/backend/__init__.py", line 46, in load_backend
    mod = importlib.import_module('.%s' % mod_name, __name__)
  File "/home/vrcekl/anaconda3/envs/dgl-fp16/lib/python3.8/importlib/__init__.py", line 127, in import_module
    return _bootstrap._gcd_import(name[level:], package, level)
  File "/home/vrcekl/npf_test/dgl/python/dgl/backend/pytorch/__init__.py", line 1, in <module>
    from .tensor import *
  File "/home/vrcekl/npf_test/dgl/python/dgl/backend/pytorch/tensor.py", line 12, in <module>
    from ... import ndarray as nd
  File "/home/vrcekl/npf_test/dgl/python/dgl/ndarray.py", line 224, in <module>
    _init_api("dgl.ndarray")
  File "/home/vrcekl/npf_test/dgl/python/dgl/_ffi/function.py", line 278, in _init_api
    _init_api_prefix(target_module_name, namespace[4:])
  File "/home/vrcekl/npf_test/dgl/python/dgl/_ffi/function.py", line 284, in _init_api_prefix
    module = sys.modules[module_name]
KeyError: 'dgl.ndarray'
```
Notice that there are 2 errors reported inside the message, one about not being able to open `libtensoradapter_pytorch_1.9.0.so` and the other one regarding `dgl.ndarray`.

I assume that the second error happens due to relative imports, because when I run python and import dgl from the `project-repo/dgl/python` directory, everything works fine. Any idea how to fix this isssue when running a script from the `project-repo` directory?

**Comment by VoVAllen** [comment]
You can do `pip install .` or `pip install -e .` (development mode) in the `python` folder

**Comment by lvrcek** [comment]
It's working now, thanks a lot for your help!
