### ISSUE TITLE
[Bug] The RGCN link_predict example incorrectly casts norm to an integer

### ISSUE THREAD

**Issue by Izzy-Newsham** [dmlc/dgl#3662]
## 🐛 Bug

In `dgl/examples/pytorch/rgcn/utils.py`, the function `build_graph_from_triplets` returns the following:

https://github.com/dmlc/dgl/blob/9ec9df57ca9a920250f4f0d6a010868a6866772e/examples/pytorch/rgcn/utils.py#L144

It casts norm to an integer. The range of the values in norm (before the cast) is [0,1], as [norm = 1.0 / in_deg](https://github.com/dmlc/dgl/blob/9ec9df57ca9a920250f4f0d6a010868a6866772e/examples/pytorch/rgcn/utils.py#L124) (line 124).

Thus when cast to int64, norm will become 0 where in_deg > 1 and 1 where in_deg == 1. This means during message passing, when the message is multiplied by the norm, any edges pointing to nodes with in_deg > 1 will have a message made up of 0s. 

I think that norm should hold float values, so that some messages are not simply multiplied by 0 and discarded.

## To Reproduce

There is a difference in scores between casting to int (the current version) and when not casting to int.
Firstly, run:
`python3 link_predict.py -d FB15k-237 --gpu 0 --eval-protocol filtered`
You get approximately the MRR value in the example README:
> MRR (filtered): 0.200854

Now, change line 144 in utils.py to not cast norm:
`return g, rel.astype('int64'), norm`
and run the same command:
`python3 link_predict.py -d FB15k-237 --gpu 0 --eval-protocol filtered`
Now the MRR is slightly higher:
> MRR (filtered): 0.225410

This difference is also apparent with a lower number of epochs.

### To double check norm is mostly 0s
In the training in `link_predict.py`, add:
`print(np.unique(edge_norm.numpy(), return_counts=True))`
just before [line 165](https://github.com/dmlc/dgl/blob/9ec9df57ca9a920250f4f0d6a010868a6866772e/examples/pytorch/rgcn/link_predict.py#L165).
And this results in outputs such as:
> (array([0, 1]), array([26368,  3632]))

Which says edge_norm is made up of 26,000 0s and 3600 1s.

## Expected behaviour
I would expect norm not to be cast into int64, as it should consist of floats. Then nodes with in-degrees greater than 1 can contribute during message passing.

## Environment
 - DGL Version (e.g., 1.0): 0.7.2
 - Backend Library & Version (e.g., PyTorch 0.4.1, MXNet/Gluon 1.3): torch 1.10.1+cpu
 - OS (e.g., Linux): Linux
 - How you installed DGL (`conda`, `pip`, source): pip
 - Python version: 3.7.7

**Comment by mufeili** [comment]
Nice catch and thank you for the report! I recently found the same bug when working on #3619 . This PR has fixed the bug. Meanwhile, it got much higher MRR scores. It will be great if you can take a look at it and see if it is done properly.
