### ISSUE TITLE
`dgl.add_reverse_edges` duplicates self-loops

### ISSUE THREAD

**Issue by zjost** [dmlc/dgl#3669]
## 🐛 Bug

I think it's the case that we don't want `dgl.add_reverse_edges` to create duplicates of the self-loops, but currently it does.  Are there use-cases where this is desirable?  I think the common case is that it is not--e.g., you may want to add self-loops and reverse friendships, but not duplicate self-loops.  If we expose a parameter on whether or not to reverse self-loops, I think the default should be False.

**Comment by mufeili** [comment]
I agree with you that adding duplicate self-loops is likely meaningless. Meanwhile, this should be expected from the description of `add_reverse_edges` that it adds an edge `(i, j)` for each edge `(j, i)` in the existing graph. There are also existing solutions to this problem:
- Use `[to_bidirected](https://docs.dgl.ai/generated/dgl.to_bidirected.html#dgl.to_bidirected)`, which returns a bidirected graph without duplicate edges
- Add self loops after calling `add_reverse`
- Call `to_simple` after calling `add_reverse`

Generally, I prefer making each transform function simple while allowing users to flexibly compose them.

**Comment by zjost** [comment]
Two pieces of direct user feedback I've heard:
> I was slightly surprised that self-loops aren't self-reversed by the api, but alas

> But, reversing the self loops doesn't make any sense right!

It also led to a bug in my code.  

Another aspect I find counter-intuitive is that if the reverse edge already exists, it creates it anyway.  E.g., 
```python
> g_tmp = dgl.graph((th.tensor([0, 1]), th.tensor([1, 0])))
> dgl.add_reverse_edges(g_tmp).edges()
(tensor([0, 1, 1, 0]), tensor([1, 0, 0, 1]))
```

In general, why would we want to keep duplicates?  If we removed them, it would solve both problems.  

Regardless of the decision, the documentation should be updated to make it explicit and point users to `to_bidirected` if that's the right API for creating de-duplicated reverse edges.

**Comment by mufeili** [comment]
I'll add an argument to `dgl.add_reverse_edges` for preventing duplicate self-loops and update the documentation of it for a pointer to `to_bidirected`. I'll request your review once it's ready. Thanks.
