### ISSUE TITLE
Error should be raised if aggregator_type provided is outside allowed values

### ISSUE THREAD

**Issue by thatlittleboy** [dmlc/dgl#3681]
## 🐛 Bug

As per title. [SAGEConv](https://docs.dgl.ai/api/python/nn.pytorch.html#sageconv) is missing some user input sanitization for the `aggregator_type` parameter, which can be error prone, e.g. if user enters in `max_pool` instead of `pool` as expected by SAGEConv.

## To Reproduce

1. Instantiate a SAGEConv layer with `aggregator_type` = 'foo'. 

```python
conv = SAGEConv(10, 2, aggregator_type='foo')
```
No errors raised.

## Expected behavior

A DGLError should be raised, similar to how if the user provides a `norm` value that is outside of the allowed values (right, none, both, left) in GraphConv, see [here](https://github.com/dmlc/dgl/blob/master/python/dgl/nn/pytorch/conv/graphconv.py#L281)

## Environment

 - DGL Version (e.g., 1.0): 0.7.1
 - Backend Library & Version (e.g., PyTorch 0.4.1, MXNet/Gluon 1.3): pytorch 1.9.1+cpu
 - OS (e.g., Linux): macos
 - How you installed DGL (`conda`, `pip`, source): pip
 - Build command you used (if compiling from source):
 - Python version: 3.6.8
 - CUDA/cuDNN version (if applicable):
 - GPU models and configuration (e.g. V100):
 - Any other relevant information:

## Additional context

I will also note that in the User Guide, https://docs.dgl.ai/guide/nn-construction.html, there *is* this check for the aggregator_type in the code samples. So I find it strange it is not in the code base. (Moreover, the listed allowed values are `['mean', 'max_pool', 'lstm', 'gcn']` there.)

I'll be happy to send in a PR if I receive confirmation that this is something the authors wish to fix. Thanks.

**Edit:** I just realized a KeyError is thrown during `forward()`, but I think throwing an error earlier during the init is appropriate as well.

**Comment by mufeili** [comment]
Could you open a pull request for this fix?

**Comment by thatlittleboy** [comment]
Sure, will do. Thanks for the feedback.
