### ISSUE TITLE
OSError: Too many open files. Occurs when running DistDGL with 'num_samplers' = 0

### ISSUE THREAD

**Issue by tonyjie** [dmlc/dgl#3693]
## 🐛 Bug

Trying to run distributed GraphSAGE example (https://github.com/dmlc/dgl/blob/master/examples/pytorch/graphsage/experimental/train_dist.py) using DistDGL on two CPUs. But an `OSError: [Error 24] Too many open files` caused by `python multiprocessing` occurs when the argument of `launch.py` `num_samplers` is **NOT** set to `0`. The error occurs when the code runs evaluating part on the val and test set (do model inference). The training part works fine. 

I am able to run it if I set `num_samplers` to `0` for `launch.py` script. It seems that there are bugs on the sampler code involving with multiprocessing. 

## To Reproduce

1. Setup the distributed prerequisite. Partition the reddit dataset into 2 (n) parts. Follows the prerequisite here. https://github.com/dmlc/dgl/tree/master/examples/pytorch/graphsage/experimental
2. Run `launch.py` with `num_samplers` != 0
```
python3 ~/workspace/dgl/tools/launch.py \
--workspace ~/workspace/dgl/examples/pytorch/graphsage/experimental/ \
--num_trainers 1 \
--num_samplers 1 \
--num_servers 1 \
--part_config data/ogb-product.json \
--ip_config ip_config.txt \
"python3 train_dist.py --graph_name reddit --ip_config ip_config.txt --num_epochs 2 --batch_size 1000 --eval_every=1"
```
I set `--eval_every=1` because the error occurs on evaluation part. The training part works fine. Specifically, the error will occur here (when itering the dataloader for evaluation): https://github.com/dmlc/dgl/blob/c8fef62928ca90766f5455de6b3253050b3a24a2/examples/pytorch/graphsage/experimental/train_dist.py#L118

3. The printed error message would be: 
```
[Training message] Part 2, Epoch Time(s): xxx, sample+data_copy: xxx, forward: xxx, backward: xxx, update: xxx, #seeds: xxx, #inpus: xxx......
|V|=232965, eval batch size: 100000
0it [00:00, ?it/s]Traceback (most recent call last):
  File ".../python3.8/multiprocessing/queues.py", line 239, in _feed
  File ".../python3.8/multiprocessing/reduction.py", line 51, in dumps
  File ".../python3.8/site-packages/torch/multiprocessing/reductions.py", line 329, in reduce_s$
orage
  File ".../python3.8/multiprocessing/reduction.py", line 198, in DupFd
  File ".../python3.8/multiprocessing/resource_sharer.py", line 48, in __init__
OSError: [Errno 24] Too many open files
```

## Expected behavior

Expect to see running evaluation and model inference correctly. The expected printed message should be a `tqdm` iteration like 
```
1it [00:07,  7.46s/it]
Part 0, Val Acc 0.5780, Test Acc 0.5813, time: 17.9267
```

## Environment

 - DGL Version: 0.7.2:
 - Backend Library & Version: PyTorch 1.10.0
 - OS: CentOS
 - How you installed DGL: conda
 - Python version: 3.8

**Comment by Rhett-Ying** [comment]
Thanks for reporting this. we are working on it yet.

**Comment by tonyjie** [comment]
> Thanks for reporting this. we are working on it yet.

**Comment by tonyjie** [comment]
So I should build from source in this repo, and then the error should be fixed, right?

**Comment by tonyjie** [comment]
> So I should build from source in this repo, and then the error should be fixed, right?

Solved. Thanks!
