### ISSUE TITLE
Presumably a minor error in description of DotGatConv

### ISSUE THREAD

**Issue by zachary-mcdargh** [dmlc/dgl#3702]
## 📚 Documentation

On the [NN modules pytorch page](https://docs.dgl.ai/en/latest/api/python/nn.pytorch.html), it is stated that the attention matrix is computed using (W_i h_i ) (W_j h_j), "where where W_i and W_j transform node 𝑖’s and node 𝑗’s features into the same dimension". This implies that a separate W matrix is learned for every node, which is presumably not what is meant. I believe these are transformation matrices for the source and destination features, usually called Q and K for query and value.

**Comment by VoVAllen** [comment]
We have a note about the implementation at https://github.com/dmlc/dgl/blob/master/python/dgl/nn/pytorch/conv/gatconv.py#L292-L303. Does this resolve your question?

**Comment by jermainewang** [comment]
Make sense. Thanks for pointing it out. Would you like to contribute a patch?
