### ISSUE TITLE
dgl_gpu can't work well

### ISSUE THREAD

**Issue by Ealeosd123** [dmlc/dgl#3705]
## 🐛 Bug

[21:43:56] /opt/dgl/src/runtime/tensordispatch.cc:43: TensorDispatcher: dlopen failed: /home/aigist/anaconda3/envs/traffic/lib/python3.7/site-packages/dgl/tensoradapter/pytorch/libtensoradapter_pytorch_1.10.1.so: cannot open shared object file: No such file or directory
## To Reproduce
1. I run 'conda install -c dglteam dgl-cuda11.3' to install
2. It can work well with above problem

## Expected behavior
import dgl

run without warning
## Environment

 - DGL Version (e.g., 1.0):
 - Backend Library & Version (e.g., PyTorch 0.4.1, MXNet/Gluon 1.3): PyTorch 1.10.1
 - Ubuntu 21.04:
 - How you installed DGL (`conda`, `pip`, source):conda
 - Build command you used (if compiling from source):
 - Python version:3.7
 - CUDA/cuDNN version (if applicable):11.3
 - GPU models and configuration (e.g. V100):Ti2080
 - Any other relevant information:

**Comment by 123carmen** [comment]
I have the same problem. it shows
/opt/dgl/src/runtime/tensordispatch.cc:43: TensorDispatcher: dlopen failed: /home/aigist/anaconda3/envs/traffic/lib/python3.7/site-packages/dgl/tensoradapter/pytorch/libtensoradapter_pytorch_1.10.1.so: cannot open shared object file: No such file or directory

and I use
dgl-cuda11.3
torch 1.10.1+cu113
python 3.6
,
the program running, just it does NOT run on GPU, it runs on CPU.
what should I do?
I install dgl use:
pip install dgl-cu113 -f https://data.dgl.ai/wheels/repo.html

**Comment by Ealeosd123** [comment]
您好，您的邮件我已收到。我将尽快回复

**Comment by BarclayII** [comment]
The warning is only related to how DGL allocates arrays and should not impact the performance or correctness much.

**Comment by scottlittle** [comment]
For me, I get this error:
```python
Using backend: pytorch
[14:13:01] /opt/dgl/src/runtime/tensordispatch.cc:43: TensorDispatcher: dlopen failed: /home/scott/anaconda3/envs/hm_env/lib/python3.8/site-packages/dgl/tensoradapter/pytorch/libtensoradapter_pytorch_1.10.1.so: cannot open shared object file: No such file or directory
```
Going to the directory, I see the shared object file, but it's one version off:
```bash
$ ~/anaconda3/envs/hm_env/lib/python3.8/site-packages/dgl/tensoradapter/pytorch$ ls
libtensoradapter_pytorch_1.10.0.so
```
I have torch 1.10.1:
```python
In [2]: import torch

In [3]: torch.__version__
Out[3]: '1.10.1'
```

**Comment by yzh119** [comment]
@BarclayII How about we make tensoradapter an independent library that releases new version whenever pytorch upgrades?

**Comment by BarclayII** [comment]
This warning is suppressed in 0.8.
