### ISSUE TITLE
Pinsage Example appears to use an older version of DGL

### ISSUE THREAD

**Issue by redraven984** [dmlc/dgl#3708]
Hello, I would like to run the PinSage example and I'm finding issues with processing the data.

- In data_utils.py Line 34 the function is passed a parameter  `relabel_nodes=False`. It looks like this is now `preserve_nodes = False`.
- Running the processing function:` python process_movielens1m.py ./ml-1m ./data.pk` Gives me an error: `DGLError: Expect number of features to match number of nodes (len(u)). Got 3706 and 3704 instead.`

Can you help me run through this example?

**Comment by BarclayII** [comment]
`relabel_nodes=False` corresponds to `preserve_nodes=True`.  Could you try changing that and see if the error still occurs?

**Comment by redraven984** [comment]
@BarclayII Thanks for your response! It looks like the code was actually expecting newer package versions. Here is what worked for me:

1. Upgrade DGL to 0.7.2
2. Torch Text to 0.11.2


Thanks for your help!

**Comment by redraven984** [comment]
Please feel free to close this issue.

**Comment by redraven984** [comment]
@BarclayII Thanks for your response! It looks like the code was actually expecting newer package versions. Here is what worked for me:

1. Upgrade DGL to 0.7.2
2. Torch Text to 0.11.2


Thanks for your help!

**Comment by zilinly** [comment]
> Hello, I would like to run the PinSage example and I'm finding issues with processing the data.
> 
> * In data_utils.py Line 34 the function is passed a parameter  `relabel_nodes=False`. It looks like this is now `preserve_nodes = False`.
> * Running the processing function:` python process_movielens1m.py ./ml-1m ./data.pk` Gives me an error: `DGLError: Expect number of features to match number of nodes (len(u)). Got 3706 and 3704 instead.`
> 
> Can you help me run through this example?

this example is still unresolved，who can help me？
torch==11.7
dgl=1.1.2
dgl_cu101
