### ISSUE TITLE
DGL 0.7.2 installed via conda seems to link an non-existent version of pytorch 1.10.2 libary

### ISSUE THREAD

**Issue by luobroad** [dmlc/dgl#3716]
## 🐛 Bug

It seems that dgl 0.7.2 supports up to pytorch 1.10.0. package dependency logic links it to  /lib/python3.9/site-packages/dgl/tensoradapter/pytorch/libtensoradapter_pytorch_1.10.2.so, but under this path I can only find libtensoradapter_pytorch_1.10.0.so

## To Reproduce

I use conda 4.11.0, python 3.9, all other packages installed using conda-forge. Using brand-new conda environment. Pytorch installed here is 1.10.2, dgl is 0.7.2
1. conda install pytorch torchvision torchaudio cudatoolkit=11.3 -c pytorch
2. conda install -c dglteam dgl-cuda11.3
3. go to python and import torch, import dgl

Error Message:
TensorDispatcher: dlopen failed: {my environment path}/lib/python3.9/site-packages/dgl/tensoradapter/pytorch/libtensoradapter_pytorch_1.10.2.so: cannot open shared object file: No such file or directory

## Environment

 - DGL Version: 0.7.2
 - Backend Library & Version: PyTorch 1.10.2
 - OS : Ubuntu 20.04LTS
 - How you installed DGL (`conda`, `pip`, source): conda
 - Build command you used (if compiling from source): N/A
 - Python version: 3.9.10
 - CUDA/cuDNN version (if applicable): 11.3/8.2.0
 - GPU models and configuration (e.g. V100): RTX A5000
 - Any other relevant information:

**Comment by Rhett-Ying** [comment]
`TensorAdaptor` is built only when `BUILD_TORCH` is `ON` during DGL build. Such option is not open for `conda install`.

It's ok to ignore this error message as this lib is for better performance(memory efficiency) only.

If you really want to pick up this change, you need to build from DGL source code on your own: `cmake -DUSE_CUDA=ON -DBUILD_TORCH=ON .. && make`.

**Comment by luobroad** [comment]
If you really want you can downgrade your PyTorch to 1.10.0, what I am
doing right now.

**Comment by Rhett-Ying** [comment]
> > It's ok to ignore this error message as this lib is for better performance(memory efficiency) only.
> 
> I am also seeing this message using DGL from conda. Would that be possible to silent it? It tends to pollute my logs which make it hard for debugging purposes.

we're working on a patch to suppress it. will ping you once ready.

**Comment by BarclayII** [comment]
Fixed in 0.8.
