### ISSUE TITLE
Is there any example for hetero link pred using EdgeDataLoader?

### ISSUE THREAD

**Issue by hojun0705** [dmlc/dgl#3726]
I only see NodeDataLoader examples. I wanna see how you implement EdgeDataLoader for hetero link prediction. Is there any? If not, would you make one?

**Comment by Rhett-Ying** [comment]
pls check following links.
https://docs.dgl.ai/en/0.7.x/guide/minibatch-link.html#for-heterogeneous-graphs
https://docs.dgl.ai/en/0.7.x/api/python/dgl.dataloading.html#dgl.dataloading.pytorch.EdgeDataLoader

**Comment by hojun0705** [comment]
I know they exist. But they are only snippets of the whole thing functioning. I would like to test end-to-end code like Pinsage you have in examples. Do you have a plan to update one such?
