### ISSUE TITLE
Why do metapath2vec samplig skip paper node

### ISSUE THREAD

**Issue by renmada** [dmlc/dgl#3730]
I plan to generating node feature using metapath2vec.
According to [example code](https://github.com/dmlc/dgl/blob/master/examples/pytorch/metapath2vec/sampler.py), paper node is skipped.
What shoule I do if I want to generate paper node feature meanwhile? Just keep the paper node?

**Comment by BarclayII** [comment]
> Just keep the paper node?

I think so.
