### ISSUE TITLE
When to use reverse edges for heterogenous graph between different node types?

### ISSUE THREAD

**Issue by Jeriousman** [dmlc/dgl#3738]
reverse edges are used to update richer information for edges that are connected by the same node types in homo, hetero G. What would be some intuitive reasons or use cases to use reverse edges in edges that are connected by different node types of hetero G? For example, node 1 of user connected to node 10 of movie in hetero G?

**Comment by VoVAllen** [comment]
Usually people will add the reverse edges to the graph to make it bidirected, so that every node can have information coming from other nodes
