### ISSUE TITLE
[BUGs] about example hilander

### ISSUE THREAD

**Issue by GlennCGL** [dmlc/dgl#3743]
Hello, I have a question In file hilander/utils/deduce.py, line 147 in build_next_level function.
Why center_features in each level are calculated from global_features and global_pred_labels, but not the features and pred_labels in each level?

**Comment by GlennCGL** [comment]
And I found a bug in file hilander/models/graphconv.py, line 22 in GraphConvLayer function.
is it 'graph.num_dst_nodes()' correct? Shouldn't be 'bipartite.num_dst_nodes()'?

**Comment by GlennCGL** [comment]
In hilander paper: Joint prediction for density and linkage For each edge (vi, vj ) in E, we concatenate the source and destination node features obtained from the encoder.
However, we can learn from the source code that src_feat+dst_feat instead of concatenate. I think that there are many differences between the paper description and the code implementation.

**Comment by GlennCGL** [comment]
In hilander paper, Figure 1, 'These clusters are then grouped into super-nodes as input for the next level'. However, super-nodes for each level are built in pre-process in dataset. It seems a huge difference between these.

**Comment by hetong007** [comment]
@GlennCGL Thank you for your interests in HiLANDER. 

1. `cluster_features` is a cluster-level representation. Our implementation collects information from all nodes to make it global. It is simply a design choice, and it is possible that you can do it differently and observe a better score.
2. Thanks for the catch! It should be `bipartite`.
3. We observe no major difference between addition and concatenation, while addition saves memory. You are welcome to catch more of such inconsistency and we can fix in the example.
4. In Figure 1 we talk about the forward pass, i.e. the inference logistic, while the code in dataset constructs such super nodes in order to help training. We describe the training graph construction in section 3.5 .

**Comment by GlennCGL** [comment]
> @GlennCGL Thank you for your interests in HiLANDER.
> 
> 1. `cluster_features` is a cluster-level representation. Our implementation collects information from all nodes to make it global. It is simply a design choice, and it is possible that you can do it differently and observe a better score.
> 2. Thanks for the catch! It should be `bipartite`.
> 3. We observe no major difference between addition and concatenation, while addition saves memory. You are welcome to catch more of such inconsistency and we can fix in the example.
> 4. In Figure 1 we talk about the forward pass, i.e. the inference logistic, while the code in dataset constructs such super nodes in order to help training. We describe the training graph construction in section 3.5 .

Thanks for reply. Also, I want to ask whether you trained on MS1M dataset before? if so, what is the result on this dataset? I had a try on this dataset using hilander with default configuration and I got a very low F-score. I can not find out the reason.

**Comment by sneakerkg** [comment]
Hi @GlennCGL, thanks for your interests in our paper!
We indeed tried HiLANDER on MS1M. Both Fb and Fp are > 0.88. What F-score do you get? How many levels does the model run?

**Comment by GlennCGL** [comment]
> Hi @GlennCGL, thanks for your interests in our paper!
> We indeed tried HiLANDER on MS1M. Both Fb and Fp are > 0.88. What F-score do you get? How many levels does the model run?

@sneakerkg I trained the model with knn_k = [10, 5, 3] and levels = [2, 3, 4], test the model with knn_k=10 and levels=10. F-score is < 0.4. Could you tell me about the configuration you tried before and I try it again?

**Comment by sneakerkg** [comment]
Thanks for the information. I'm using the same configuration (actually we use MS1M to find out the setting) so I'm a little surprised it's getting bad score. A few questions might be helpful for debugging:
1.Can you reproduce the results for other datasets? For example, on Hannah;
2.Where do you get the MS1M dataset and what is the feature you are using?
3.May I bother you have a check on the training curve to see if it makes sense?

**Comment by GlennCGL** [comment]
> Thanks for the information. I'm using the same configuration (actually we use MS1M to find out the setting) so I'm a little surprised it's getting bad score. A few questions might be helpful for debugging:
> 1.Can you reproduce the results for other datasets? For example, on Hannah;
> 2.Where do you get the MS1M dataset and what is the feature you are using?
> 3.May I bother you have a check on the training curve to see if it makes sense?

@sneakerkg hello, I can not still reproduce the result you trained on MS1M. 
1. I can reproduce the results for other datasets.
2. I train on MS1M_part0, features shape is (576494, 256). I test on MS1M_part1, features shape is (584013, 256). I got the dataset from gcnve github.
3. I put the related results here: [Google Drive](https://drive.google.com/drive/folders/1m27KGZXGIRmwYV0IU2sWeZUzAKinGhtT?usp=sharing)

**Comment by GlennCGL** [comment]
> Thanks for the information. I'm using the same configuration (actually we use MS1M to find out the setting) so I'm a little surprised it's getting bad score. A few questions might be helpful for debugging:
> 1.Can you reproduce the results for other datasets? For example, on Hannah;
> 2.Where do you get the MS1M dataset and what is the feature you are using?
> 3.May I bother you have a check on the training curve to see if it makes sense?

@sneakerkg hello, I can not still reproduce the result you trained on MS1M. 
1. I can reproduce the results for other datasets.
2. I train on MS1M_part0, features shape is (576494, 256). I test on MS1M_part1, features shape is (584013, 256). I got the dataset from gcnve github.
3. I put the related results here: [Google Drive](https://drive.google.com/drive/folders/1m27KGZXGIRmwYV0IU2sWeZUzAKinGhtT?usp=sharing)

**Comment by sneakerkg** [comment]
Oh, I recall one thing. for "--threshold", we are using "affine", not "prob". When we are working on MS1M, we are still mainly using the gcnv decoding. May I bother you have a check on this. A scan on "tau" is still required.

**Comment by GlennCGL** [comment]
> Oh, I recall one thing. for "--threshold", we are using "affine", not "prob". When we are working on MS1M, we are still mainly using the gcnv decoding. May I bother you have a check on this. A scan on "tau" is still required.

@sneakerkg Hello, I used "affine" and scan some "tau" value for experiments. And f-score can reach 0.8~0.85. May I ask you what is the meaning of "When we are working on MS1M, we are still mainly using the gcnv decoding"? Do you mean the code you used to test on MS1M is different from hilander test_subg? And if so, what are the differences? Thanks for your reply very much.

**Comment by zsz00** [comment]
Will the code issues mentioned above be fixed?
and
66row in train_subg.py  error:
ks += [k for g in dataset.gs]

**Comment by sneakerkg** [comment]
> 

It's the same code, just using "affine" decoding. Hmm, even 0.85 is lower than expected, it should reach 0.88. Can I bother you also scan on "GAT vs GCN" and "use_cluster_feat vs not using use_cluster_feat" and "focal loss vs bceloss".

**Comment by chenzhekl** [comment]
Hi, thanks for open-sourcing the code. I have a somewhat different problem with the Hi-Lander work. When building the next level, the paper seems to adopt an edge selection algorithm by finding the path that increases the node density. However, the code does the opposite where a downhill path is selected. Would you mind elaborating on that? Also, It would be greatly appreciated if you could help clarify why `affine` rather than `prob`, which is used in the paper, is preferred in the implementation. Thank you.

**Comment by hetong007** [comment]
@chenzhekl Thanks for your questions. 

1. Empirically the downhill path would give a similar result as an uphill implementation, but we think the former has more potential as each time we include a new node it knows which peak it attaches to, also it is possible to aggregate features for similarity comparison with the downhill approach.
2. `affine` and `prob` produces results that are not too far, and we pick the one that gives better results. You can tweak that on your own dataset.

**Comment by chenzhekl** [comment]
Thanks!
