### ISSUE TITLE
install error

### ISSUE THREAD

**Issue by ucasiggcas** [dmlc/dgl#3749]
backend tf2.2.0
`dgl._ffi.base.DGLError: [11:02:57] /opt/dgl/src/runtime/c_runtime_api.cc:88: Check failed: allow_missing: Device API gpu is not enabled. Please install the cuda version of dgl`

what's up?
help me ,please

**Comment by VoVAllen** [comment]
How did you install dgl? Did you install the dgl-cuXX version?

**Comment by ucasiggcas** [comment]
`pip install dgl`

**Comment by ucasiggcas** [comment]
@VoVAllen

**Comment by VoVAllen** [comment]
Try `pip install dgl-cu102 -f https://data.dgl.ai/wheels/repo.html` or change 102 to other version on your machine

**Comment by ucasiggcas** [comment]
Installed as you said,but the error ups according to the [link](https://github.com/dmlc/dgl/tree/master/examples/pytorch/graphsage)
```
dgl/examples/pytorch/graphsage$ python3 train_sampling_multi_gpu.py --num-epochs 30 --gpu 0,1
Using backend: pytorch
Traceback (most recent call last):
  File "train_sampling_multi_gpu.py", line 8, in <module>
    import dgl.multiprocessing as mp
ModuleNotFoundError: No module named 'dgl.multiprocessing'
```

**Comment by ucasiggcas** [comment]
@VoVAllen

**Comment by VoVAllen** [comment]
Could you try `python -c "import dgl;print(dgl.__version__)"` to see what's your dgl version?

**Comment by VoVAllen** [comment]
Also the examples are for PyTorch. You need PyTorch backend for this

**Comment by ucasiggcas** [comment]
I changed backend to pytorch
```
Using backend: pytorch
0.6.1

```

**Comment by ucasiggcas** [comment]
@VoVAllen

**Comment by VoVAllen** [comment]
Please try newer DGL by the command I provided above. 0.6.1 is too old

**Comment by avarbella** [comment]
I have windows 10 with Visual C++ 2022, I can install dgl but then some submodules are not recognized as all dgl.nn submodules. What should I do?

**Comment by Rhett-Ying** [comment]
> 

pls open a new ticket and provide all the context so that we could help debug.

**Comment by avarbella** [comment]
Thanks for your reply, I solved the problem, somehow the installation was failing because I had pycharm running, or at least I believe this was the problem
