### ISSUE TITLE
Error running R-GCN

### ISSUE THREAD

**Issue by giuseppefutia** [dmlc/dgl#375]
## 🐛 Bug

Following error running the example on rgcn:
`AttributeError: type object 'requests_failed_to_import' has no attribute 'get'`

## To Reproduce

1. Run the following commands to create a conda env and install required libraries:
```
$ conda create -n dgl python=3.6
$ conda activate dgl
$ conda install -c dglteam dgl
$ conda install -c conda-forge rdflib
$ conda install -c anaconda pandas
$ conda install -c pytorch pytorch
```
2. Run the test command:
```
python3 entity_classify.py -d aifb --testing --gpu 0
```

## Expected behavior

Obtain MRR on the R-GCN.

## Environment

 - DGL Version (e.g., 1.0): currently available on conda
 - Backend Library & Version (e.g., PyTorch 0.4.1, MXNet/Gluon 1.3): Pytorch 1.0
 - OS (e.g., Linux): Ubuntu 18.04
 - How you installed DGL (`conda`, `pip`, source): conda
 - Build command you used (if compiling from source):
 - Python version: 3.6
 - CUDA/cuDNN version (if applicable):
 - GPU models and configuration (e.g. V100):
 - Any other relevant information:

**Comment by ylfdq1118** [comment]
Did you install requests?
```
conda install requests
```

**Comment by giuseppefutia** [comment]
Thank you, now it works!

Can I create a pull request for the README.md, suggesting to install pytorch and requests?

**Comment by ylfdq1118** [comment]
Yeah, that's a good idea. 

And I think it's better to suggest installing tensor backend and requests package for every example model, not just R-GCN. Maybe let me create a PR to update all READMEs.

**Comment by ylfdq1118** [comment]
Done in #380
