### ISSUE TITLE
How are the distances between sensort calculated?

### ISSUE THREAD

**Issue by petrhrobar** [dmlc/dgl#3754]
Hi,

I would like to ask how are the distances between tensors calculated in the METR-LA dataset [LINK]?( https://www.researchgate.net/figure/The-dataset-was-collected-from-the-highway-of-Los-Angeles-County-METR-LA-from-1-March_fig7_344150366)

There is distances_la_2012.csv file available. However, how to obtain the same distances for a new personal dataset?

I was not able to find it in the documentation. Are those simply euclidian distances? and if 2 sensors are more away then some threshold we do not report the distance?

Does it make sense to compute euclidian distance - e.g. there may be one sensor in a tunnel and another above this tunnel. Using a euclidian distance, they are very close to one another. However, from a traffic point of view when getting from the tunnel sensor to another one it may be an hour-long commute. Therefore, euclidian distance does not make sense in this content.

Many thanks for your comments and amazing package

**Comment by BarclayII** [comment]
I think the distance comes with the the dataset itself from the DCRNN paper and I'm not sure about the meaning of those numbers either.

Speaking of the Euclidean distance itself, your concern is correct: the Euclidean distance does not necessarily equal the travel distance, so if travel distance is available one should use that instead.  That being said, using the road network directly would be the most reliable (which should be available from e.g. OpenStreetMap).
