### ISSUE TITLE
Storage Fallback in SPMV Trainig using MXNet 

### ISSUE THREAD

**Issue by ZiyueHuang** [dmlc/dgl#376]
Currently if we use SPMV schedule in training there is a message
```
[18:37:29] src/operator/tensor/././../../common/utils.h:450:
Storage type fallback detected:
operator = _backward_broadcast_mul
input storage types = [row_sparse, default, default, ]
output storage types = [default, default, ]
params = {}
context.dev_mask = cpu
```

This is because `dot(csr, default, transpose_a=True) = row_sparse` used in backward. In the setting of graph learning, the output storage type of `dot(csr, default, transpose_a=True)` is better to be dense then we can avoid this overhead of cast_storage.

Could we also support `dot(csr, default, transpose_a=True) = default` by  a parameter or environment variable? @eric-haibin-lin

**Comment by szha** [comment]
@ZiyueHuang this is probably better submitted as a feature request on mxnet repo.

**Comment by zheng-da** [comment]
agree
