### ISSUE TITLE
[BUG] Error when partitioning the heterogeneous graph

### ISSUE THREAD

**Issue by HouyuZhang1007** [dmlc/dgl#3767]
## 🐛 Bug

when ```len(g.etypes)=1``` and ```len(g.ntypes)=2```, it shows this error when partition the graph:
```AssertionError: Current HeteroNodeDataView has multiple node types, please passing the node type and the corresponding data through a dict.```

I dive deep into the code and found that in the ```_set_trainer_ids``` function of ```dgl/distributed/partition.py```, it only uses len(g.etypes) to determine whether the graph is heterogenous. 

## Environment

 - DGL Version (e.g., 1.0): 0.8a211206
 - Backend Library & Version (e.g., PyTorch 0.4.1, MXNet/Gluon 1.3): PyTorch 1.10.0a0+git36449ea
 - OS (e.g., Linux): Linux
 - How you installed DGL (`conda`, `pip`, source):
 - Build command you used (if compiling from source):
 - Python version: 3.7
 - CUDA/cuDNN version (if applicable):
 - GPU models and configuration (e.g. V100):
 - Any other relevant information:

**Comment by Rhett-Ying** [comment]
thanks for reporting this. I will make a fix for it....

**Comment by Rhett-Ying** [comment]
pls try with latest code... thanks.
