### ISSUE TITLE
[Bug] 'DistGraph' object has no attribute 'get_node_storage'

### ISSUE THREAD

**Issue by classicsong** [dmlc/dgl#3768]
## 🐛 Bug
I got this error when running distributed training:

```
File "/home/xiangsx/.local/lib/python3.7/site-packages/dgl/dataloading/dataloader.py", line 256, in _prefetch_for_subgraph
  File "/home/xiangsx/.local/lib/python3.7/site-packages/dgl/dataloading/dataloader.py", line 256, in _prefetch_for_subgraph
      File "/home/xiangsx/.local/lib/python3.7/site-packages/dgl/dataloading/dataloader.py", line 256, in _prefetch_for_subgraph
return [recursive_apply(v, fn, *args, **kwargs) for v in data]
  File "/home/xiangsx/.local/lib/python3.7/site-packages/dgl/utils/internal.py", line 921, in recursive_apply
            node_feats, subg._node_frames, subg.ntypes, dataloader.graph.get_node_storage,node_feats, subg._node_frames, subg.ntypes, dataloader.graph.get_node_storage,node_feats, subg._node_frames, subg.ntypes, dataloader.graph.get_node_storage,


AttributeErrorAttributeErrorAttributeError: : : 'DistGraph' object has no attribute 'get_node_storage''DistGraph' object has no attribute 'get_node_storage''DistGraph' object has no attribute 'get_node_storage'

```

## To Reproduce

1.
1.
1.

## Environment

 - DGL Version (e.g., 1.0): nightly build
 - Backend Library & Version (e.g., PyTorch 0.4.1, MXNet/Gluon 1.3): PyTorch 1.8.1
 - OS (e.g., Linux):
 - How you installed DGL (`conda`, `pip`, source):
 - Build command you used (if compiling from source):
 - Python version:
 - CUDA/cuDNN version (if applicable):
 - GPU models and configuration (e.g. V100):
 - Any other relevant information:

**Comment by BarclayII** [comment]
Did you use NodeDataLoader or DistNodeDataLoader?  The NodeDataLoader for DistGraph is now splitted into another class.

**Comment by jermainewang** [comment]
For backward compatibility, consider throwing an error with instructions about what to use.

**Comment by Rhett-Ying** [comment]
error is thrown within this merged PR:  [Doc and bugfix] Add docs and user guide and update tutorial for sampling pipeline #3774 
FYI @zheng-da
