### ISSUE TITLE
Where is the dgl.data.MiniGCDataset?

### ISSUE THREAD

**Issue by hbsun2113** [dmlc/dgl#377]
The tutorial uses a dataset ```dgl.data.MiniGCDataset```as following:
![image](https://user-images.githubusercontent.com/27994442/52529313-87b25b00-2d2a-11e9-8677-75808be8197d.png)

But when I import it, there occurs a problem:
![image](https://user-images.githubusercontent.com/27994442/52529314-8aad4b80-2d2a-11e9-9bb8-cc2160e361d0.png)

**Comment by yzh119** [comment]
I think this problem would have been fixed if you correctly installed the latest version of dgl.

**Comment by mufeili** [comment]
I guess you need to install from source for the time being. Sorry for the inconvenience. @hbsun2113

**Comment by jermainewang** [comment]
We will include this in our next release v0.2.
