### ISSUE TITLE
Support new pytorch Deep learning recommendation model, or DLRM

### ISSUE THREAD

**Issue by theisjendal** [dmlc/dgl#3771]
## 🚀 Feature
Support using [Deep learning recommendation model](https://arxiv.org/abs/1906.00091) for better utilization of GPUs. 
Links:
- https://pytorch.org/blog/introducing-torchrec/
- https://github.com/pytorch/torchrec/blob/main/Torchrec_Introduction.ipynb

## Motivation

DGL is often slow or does not fully utilize GPU resources. Often this is due to the sampling and moving to GPU. I'd imagine that this wrapper would allow for better utilization and quicker training times.

## Pitch

Make it possible to utilize the new TorchRec modules in the DGL framework.

**Comment by jermainewang** [comment]
Hi, thanks for the pointer. For the speed issue, DGL v0.7 and v0.8 (latest) have improved the pipeline by quite a lot. We now support sampling entirely in GPU or use UVA technique. You may find more details in our [release blog](https://www.dgl.ai/release/2022/03/01/release.html). In terms of DLRM, I think its focus at the moment is the traditional two-tower model. It will be interesting to see if GNN + two-tower architecture will be beneficial. If so, I think the difference in the model architectures will lead to quite different parallel training solutions. For now, we will keep our eyes on the latest development.
