### ISSUE TITLE
C++ api, how to return a sampled subgraph along with a node feature vector

### ISSUE THREAD

**Issue by mfbalin** [dmlc/dgl#3776]
Hello,

I am trying to implement a new sampling algorithm and my algorithm returns the sampled subgraph along with either node or edge features. When I try to change the return type to something like List<std::pair<NodeFlow, FloatArray>>, it complains because std::pair doesn't inherit from ObjectRef. How can I make it so that my function can return a pair or a tuple, and python integration still works? I checked "include/dgl/runtime/container.h" but couldn't see an equivalent of Tuple/std::tuple while there is one for List/std::vector. 

My other question is about the deprecated code. I implemented my sampling algorithm in the src/graph/sampler.cc file but I noticed that these algorithms and the types have been deprecated? I noticed that the new sampling algorithm in src/ just returns a COOMatrix which then gets converted into a HeteroGraph before being returned to Python. Should I move my algorithm to the appropriate places and follow the new implementation instead? Or do Nodeflows still continue to work?

Thanks,
Fatih

**Comment by VoVAllen** [comment]
Hi,

The nodeflow interface is deprecated. Please use the the new sampling method you mentioned to write customized sampling algorithm

**Comment by mfbalin** [comment]
Thanks for your answer. Can you also elaborate on how I can access the srcdata, dstdata or edata attributes of the sampled graph to return weighting probabilities for the sampled graph?

**Comment by jermainewang** [comment]
For your use case, you could directly use DGL's python API:
```python
g = ...   # original graph
sampler = ...  # some sampler
dataloader = ...  # create a dataloader
for mb in dataloader:
    mb.srcdata['x']   # As long as the original graph contains node feature 'x', it is automatically fetched to the subgraph.
```

**Comment by mfbalin** [comment]
Thanks for your reply, however the feature x is calculated in the C++ sampling code. It will be used as edge weights during the forward pass. So, I need a way to pass a FloatArray from the C++ part back to the Python code along with the sampled subgraph.

**Comment by jermainewang** [comment]
If that's the case, take a look at the doc for DGL's [FFI](https://docs.dgl.ai/developer/ffi.html). The `List` container allows you to pack/unpack objects of arbitrary type into one.

**Comment by mfbalin** [comment]
```std::shared_ptr<HeteroSubgraph> subg(new HeteroSubgraph);
    std::shared_ptr<FloatArray> importances(new FloatArray);
    std::tie(*subg, *importances) = sampling::SampleLayerNeighbors(
        hg.sptr(), nodes, layer_fanouts, fanouts, dir, exclude_edges);

    *rv = List<ObjectRef>({HeteroSubgraphRef(subg), });```

In this code, the shared_ptr to graph is wrapped into a heterosubgraphref but I don't know how I should wrap the shared_ptr to FloatArray. I am attempting to use List to return the two objects together as per your suggestion with ObjectRef as the template type. How should this part of the code for my use case look like?

**Comment by mfbalin** [comment]
@BarclayII can I ask you to weigh in here? I would appreciate some pointers otherwise I might create a very hacky solution.
