### ISSUE TITLE
How to read the source code?

### ISSUE THREAD

**Issue by hbsun2113** [dmlc/dgl#378]
I want to read the source code of ```dgl```, can you give me a guide?

**Comment by VoVAllen** [comment]
We will have a blog on explaining how dgl works. Please stay tuned!

**Comment by hbsun2113** [comment]
@VoVAllen Great! Can you tell me the timeline?

**Comment by jermainewang** [comment]
@hbsun2113 could you create a question in our [discussion forum](https://discuss.dgl.ai)? I will answer it there so more people can see it. Thanks.
