### ISSUE TITLE
Report error when using the dgl.data.utils.split_dataset function

### ISSUE THREAD

**Issue by xinleihe** [dmlc/dgl#3791]
## To Reproduce

Example code:

```
# https://docs.dgl.ai/generated/dgl.graph.html?highlight=dgl%20graph#dgl.graph
import dgl
import torch


# Source nodes for edges (2, 1), (3, 2), (4, 3)
src_ids = torch.tensor([2, 3, 4])
# Destination nodes for edges (2, 1), (3, 2), (4, 3)
dst_ids = torch.tensor([1, 2, 3])
g = dgl.graph((src_ids, dst_ids))

# https://docs.dgl.ai/generated/dgl.data.utils.split_dataset.html?highlight=split_dataset
a,b,c = dgl.data.utils.split_dataset(g, frac_list=[0.6, 0.2, 0.2])
```

Error:
```
TypeError: object of type 'DGLHeteroGraph' has no len()
```

## Expected behavior

Split the dataset randomly.

## Environment

 - DGL Version: 0.7.2
 - Backend Library & Version (e.g., PyTorch 0.4.1, MXNet/Gluon 1.3): Torch 1.10.2
 - OS (e.g., Linux): Linux
 - How you installed DGL (`conda`, `pip`, source): Conda
 - Python version: 3.9.7
 - CUDA/cuDNN version (if applicable): 11.3
 - GPU models and configuration (e.g. V100): A100

## Additional context

maybe consider a tiny change to https://github.com/dmlc/dgl/blob/master/python/dgl/data/utils.py#L78?
```
num_data = len(dataset)   =>  num_data = len(dataset.nodes())
```

**Comment by mufeili** [comment]
`split_dataset` aims at splitting a dataset of multiple graphs into a training set, validation set, and test set. You cannot use it to split a graph. Do you want to partition a graph into subgraphs? What's your task?
