### ISSUE TITLE
graphsage : Unable to run node_classification after version update

### ISSUE THREAD

**Issue by priyaradhakrishnan0** [dmlc/dgl#3792]
## ❓ Unable to run https://github.com/dmlc/dgl/tree/master/examples/pytorch/graphsage/node_classification.py

I updated DGL version to latest. After the version update I am unable to run node_classification. We are getting Attribute Error : module 'dgl.dataloading' has no attribute 'NeighborSampler'

`
dgl/examples/pytorch/graphsage$ git rev-parse --abbrev-ref HEAD
master
dgl/examples/pytorch/graphsage$ python3 node_classification.py 
Using backend: pytorch
Traceback (most recent call last):
  File "node_classification.py", line 72, in <module>
    sampler = dgl.dataloading.NeighborSampler(
AttributeError: module 'dgl.dataloading' has no attribute 'NeighborSampler'
(dgl_env) jupyter@query-reform-t5:~/DGL/dgl/examples/pytorch/graphsage$ 
`

**Comment by priyaradhakrishnan0** [comment]
Please help me with **steps to update dgl version to 0.8 using conda**

I am currently on dgl 0.7
_>>> print(dgl.__version__)
0.7.2_

I tried running 
_$ conda install -c dglteam dgl-cuda11.0
Collecting package metadata (current_repodata.json): done
Solving environment: done
 All requested packages already installed._

But version continues to be 7.2

Please provide instruction on **how to provide version in the install command**

**Comment by BarclayII** [comment]
The conda packages with CUDA 11.0 should be available now.  Could you try again?

**Comment by jermainewang** [comment]
Please reopen if the issue still exists.

**Comment by HGamalElDin** [comment]
I have the same problem, did you find any solution?
