### ISSUE TITLE
What is the difference between the internal class COO of UnitGraph and the COO in "immutable_graph.h"?

### ISSUE THREAD

**Issue by AI-Friend** [dmlc/dgl#3804]
## ❓ Questions and Help

What is the difference between the internal class COO of UnitGraph and the COO in "immutable_graph.h", 
why should we define the COO and CSR classes twice?

in "immutable_graph.h":
class CSR : public GraphInterface {... }

in UnitGraph Class:
class UnitGraph : public BaseHeteroGraph {
 public:
  // internal data structure
  class COO;
  class CSR;
  typedef std::shared_ptr<COO> COOPtr;
  typedef std::shared_ptr<CSR> CSRPtr;
  ...
}

**Comment by jermainewang** [comment]
The entire `immutable_graph.h` has been deprecated and will be removed in the next release.

**Comment by AI-Friend** [comment]
Currently, meta_graph is generated using immutableGraph, right?
