### ISSUE TITLE
Typo in message passing

### ISSUE THREAD

**Issue by xingjian-zhang** [dmlc/dgl#3809]
## 📚 Documentation

![image](https://user-images.githubusercontent.com/49838100/156863784-b4c8b0fb-6970-402e-ab27-71260ca27f7e.png)

m_e seems undefined. Should it be w_e instead?

**Comment by jermainewang** [comment]
Hi, I think the equations are correct. m_e is the message on edge e (defined by the Edge-wise equation) while w_e is the input edge feature.

**Comment by ketyi** [comment]
m_e is the output of the first equation.

**Comment by xingjian-zhang** [comment]
Hi @jermainewang @ketyi. Thank you for your reply. I still have a question. How is w_e updated in each iteration? It seems unspecified in the above equations. 🤔

**Comment by jermainewang** [comment]
You can think of w_e as the input feature but on edge, so it doesn't need to be updated in most settings.
