### ISSUE TITLE
Typo Message Passing API User Guide

### ISSUE THREAD

**Issue by ketyi** [dmlc/dgl#3812]
## 📚 Documentation

In User Guide Section 2.1 Built-in Functions and Message Passing APIs

![image](https://user-images.githubusercontent.com/14096902/157060557-66b4d078-7584-4046-9b6c-e12ecb16235a.png)

The example talks about source node feature ft:
![image](https://user-images.githubusercontent.com/14096902/157060901-772f4d51-6d6a-4965-9092-791138668cf9.png)

but in the math formula, ft_j feels to note a target node because of the indexing of a_ij.

**Comment by mufeili** [comment]
Hi @ketyi , I agree with you that it might be better to replace a_ij with a_ji. Could you open a PR to fix it?

**Comment by jermainewang** [comment]
I saw your PR was closed.

**Comment by ketyi** [comment]
Is it okay like this or I made something wrong?
