### ISSUE TITLE
Since using dgl.DGLGraph is not recommended for creating empty graph, how can we properly create an empty graph?

### ISSUE THREAD

**Issue by ZhichaoDuan** [dmlc/dgl#3813]
## ❓ Questions and Help

Before proceeding, please note that we recommend
using our discussion forum (https://discuss.dgl.ai) for
general questions. As a result, this issue will
likely be CLOSED shortly.

Since using dgl.DGLGraph is not recommended for creating empty graph, how can we properly create an empty graph?

**Comment by jermainewang** [comment]
`g = dgl.graph(([], []))`
