### ISSUE TITLE
I can not set 'num_workers=4' in dgl/examples/pytorch/caregnn/main_sampling.py line 42

### ISSUE THREAD

**Issue by yijicheng** [dmlc/dgl#3824]
## To Reproduce

1. I can not set 'num_workers=4' in dgl/examples/pytorch/caregnn/main_sampling.py line 42

<img width="893" alt="image" src="https://user-images.githubusercontent.com/53086386/157599484-875c0212-d57b-4b7c-af84-c28bc772b74c.png">

## Environment

 - DGL Version (e.g., 1.0): 0.7.2+cu111
 - Backend Library & Version (e.g., PyTorch 0.4.1, MXNet/Gluon 1.3): pytorch 1.8.1
 - OS (e.g., Linux): Linux
 - How you installed DGL (`conda`, `pip`, source): pip
 - Build command you used (if compiling from source):
 - Python version: 3.7.3
 - CUDA/cuDNN version (if applicable): 11.1
 - GPU models and configuration (e.g. V100): A100
 - Any other relevant information:

**Comment by nv-dlasalle** [comment]
`num_workers=0` is explicitly set to 0 on line 42, in order to copy the graph and all data to the GPU. When performing sampling on the GPU, `num_workers` must be 0.

**Comment by nv-dlasalle** [comment]
I had thought we had a better error message for this case however. We need to check to see if a more informative error message is output in the new sampling pipeline in 0.8.

**Comment by BarclayII** [comment]
When GPU sampling is enabled the DataLoader now explicitly checks `num_workers` and reports an error in 0.8.
