### ISSUE TITLE
copy-out vs. zero-copy

### ISSUE THREAD

**Issue by hbsun2113** [dmlc/dgl#383]
Can you explain the difference between of them in this code？
![image](https://user-images.githubusercontent.com/27994442/52561327-034cfe80-2e36-11e9-9311-76d08bd3380d.png)

**Comment by yzh119** [comment]
Could you elaborate more on your question?
Plus, you are encouraged to ask general questions in our [discussion forum](https://discuss.dgl.ai), we are trying to keep our issue list only about feature requests and bugs in code/documentation.

**Comment by hbsun2113** [comment]
OK! https://discuss.dgl.ai/t/implemention-copy-out-vs-zero-copy/106
