### ISSUE TITLE
Example for heterogenerous graph - level classification

### ISSUE THREAD

**Issue by pdhung3012** [dmlc/dgl#3831]
Hello sir/ madam
Do you have any datasets/ examples for graph-level classification using heterogeneous graph? I check the set of current examples and most of them are for homogeneous graph-level classification.

Thank you

**Comment by mufeili** [comment]
Do you have any paper references on heterogeneous graph classification?

**Comment by pdhung3012** [comment]
> Do you have any paper references on heterogeneous graph classification?

I don't see any papers that used hetero graph-level classification in their list. However, they have this article about how to use graph classification with. hetero graph (https://docs.dgl.ai/en/0.6.x/guide/training-graph.html). But the code snippet they provided didn't runnable when I ran it. I guess the problem is due to the GIN dataset being suitable for the homogeneous graph only.

**Comment by mufeili** [comment]
In that case, it will be difficult to add an example as we do not know datasets for this task and how a model performs.

**Comment by pdhung3012** [comment]
That's what I am concerned about. I wondered the code provided in the tutorial is actually runnable on a dataset for the heterogeneous graphs. I think even if we don't have a dataset, we can create a synthetic dataset and make the tutorial runnable.
