### ISSUE TITLE
CoraGraphDataset `reverse_edge=False` still includes bi-directional edges

### ISSUE THREAD

**Issue by yuanqing-wang** [dmlc/dgl#3832]
## To Reproduce

```
>>> import torch, dgl
>>> g0 = dgl.data.CoraGraphDataset(force_reload=True, reverse_edge=True)[0]
>>> g1 = dgl.data.CoraGraphDataset(force_reload=True, reverse_edge=False)[0]
>>> g0.number_of_edges(), g1.number_of_edges()
(10556, 10556)

```

## Expected behavior
when `reverse_edge=False`, only include half of the edges 

## Environment

 - DGL Version (e.g., 1.0): '0.6.1'
 - Backend Library & Version (e.g., PyTorch 0.4.1, MXNet/Gluon 1.3): `1.9.0`
 - OS (e.g., Linux): Linux
 - How you installed DGL (`conda`, `pip`, source): pip
 - Build command you used (if compiling from source):
 - Python version:
 - CUDA/cuDNN version (if applicable):
 - GPU models and configuration (e.g. V100):
 - Any other relevant information:

**Comment by mufeili** [comment]
I confirmed the bug. Meanwhile, are there particular reasons that you only want to use half of the edges?

**Comment by yuanqing-wang** [comment]
Thanks, @mufeili , for fixing this!

> Meanwhile, are there particular reasons that you only want to use half of the edges?
It appears that the original implementation of GCN doesn't duplicate edges? https://github.com/tkipf/gcn/blob/39a4089fe72ad9f055ed6fdb9746abdcfebc4d81/gcn/utils.py#L70

**Comment by mufeili** [comment]
> https://github.com/tkipf/gcn/blob/39a4089fe72ad9f055ed6fdb9746abdcfebc4d81/gcn/utils.py#L70

The original work deals with bidirected graphs and they do have bi-directional edges.
