### ISSUE TITLE
How to train a GNN model on multi GPUs?

### ISSUE THREAD

**Issue by LinghaoChan** [dmlc/dgl#3835]
DGL is a great tool for me to train GNNs and help me to do related research!

However, now I want to train a GNN of a very very large Graph on my 8 x A100 GPUs? Does DGL support this function? If so, is there any tutorial for it? 

Thanks a lot!

**Comment by decoherencer** [comment]
https://docs.dgl.ai/tutorials/multi/index.html

**Comment by LinghaoChan** [comment]
> https://docs.dgl.ai/tutorials/multi/index.html

Is multi-GPUs only supported in the 0.8.x version?

**Comment by decoherencer** [comment]
#https://github.com/dmlc/dgl/commit/a7fe461c1cf6532b51bfc9f73fe7877fe6b180af
The tutorial commit was added to 0.7, I am not sure whether you could do the same on 0.6 or previous. 
Maybe you can try once and check.

**Comment by LinghaoChan** [comment]
> #[a7fe461](https://github.com/dmlc/dgl/commit/a7fe461c1cf6532b51bfc9f73fe7877fe6b180af) The tutorial commit was added to 0.7, I am not sure whether you could do the same on 0.6 or previous. Maybe you can try once and check.

Thanks a lot~

**Comment by decoherencer** [comment]
You can also check this #3827 for multi-gpu on validation on testing too

**Comment by LinghaoChan** [comment]
> You can also check this #3827 for multi-gpu on validation on testing too

Thank you~
