### ISSUE TITLE
ModuleNotFoundError: No module named 'dgl.data'; 'dgl' is not a package

### ISSUE THREAD

**Issue by zohairhadi** [dmlc/dgl#3836]
## 🐛 Bug

I got this error while running a python file which was importing ```dgl.data```.

## To Reproduce

1. Create a py file with the following code:
```
import dgl
import torch
import torch.nn as nn
import torch.nn.functional as F
import dgl.data

dataset = dgl.data.CoraGraphDataset()
print('Number of categories:', dataset.num_classes)
```

2. create a conda env in the following manner and configuration:
 `conda create -n dglconda -c pytorch`
`conda activate dglconda`
`conda install -c dglteam dgl`
`conda install -c pytorch pytorch torchvision`

3. Run the python file in the conda env to see this error

## Expected behavior

The code should execute according to the behaviour shown here: https://docs.dgl.ai/tutorials/blitz/1_introduction.html#sphx-glr-tutorials-blitz-1-introduction-py

## Environment

 - DGL Version (e.g., 1.0): dgl-0.8.0post1
 - Backend Library & Version (e.g., PyTorch 0.4.1, MXNet/Gluon 1.3): PyTorch 1.11.0
 - OS (e.g., Linux): macOS 12.0.1
 - How you installed DGL (`conda`, `pip`, source): conda
 - Build command you used (if compiling from source): python filename.py
 - Python version: 3.9.7

**Comment by VoVAllen** [comment]
Do you have dgl folder in your working directory or file named as dgl.py?

**Comment by zohairhadi** [comment]
this worked. Thank you!

**Comment by ccyccxcl** [comment]
> this worked. Thank you!
I just got the same error, could you please tell me how to resolve this?Thanks a lot
