### ISSUE TITLE
Logic behind implementing separate embedding for center and neighbor words 

### ISSUE THREAD

**Issue by gokulprasadthekkel** [dmlc/dgl#3839]
https://github.com/dmlc/dgl/blob/57d2f31f20f124a5fd93077060d2f189faed0eb8/examples/pytorch/metapath2vec/model.py#L27

Hi, I didn't understand the logic behind implementing separate embeddings for center and neighbor words. Shouldn't it be the same embedding to better model the interactions?

**Comment by mufeili** [comment]
The original implementation uses two embeddings as you said, which is probably motivated by word2vec.

**Comment by gokulprasadthekkel** [comment]
Thanks for the reply @mufeili !, 
But the implementation of Node2Vec follows only a [single embedding scheme](https://github.com/dmlc/dgl/blob/57d2f31f20f124a5fd93077060d2f189faed0eb8/examples/pytorch/node2vec/model.py#L62)

Besides, having separate embeddings means that the [u_embeddings](https://github.com/dmlc/dgl/blob/57d2f31f20f124a5fd93077060d2f189faed0eb8/examples/pytorch/metapath2vec/model.py#L26) will be tuned only when the node is the source node?
