### ISSUE TITLE
Giant graph plan?

### ISSUE THREAD

**Issue by qzshadow** [dmlc/dgl#384]
I am quite curious about the scalability of dgl. In practice, I had to deal with graphs with millions of node and edges or even more. Based on my observations, dgl is a standalone framework which performs deep learning algorithms on the graph, that means it will suffer from the memory limitations of the machine it deployed, am I correct?

**Comment by zzhang-cn** [comment]
We are working on support for "giant graph". Beyond a certain scale, we
have to use sampling. Please stay tuned, but you can also try to see how
much you can scale for now.

On Tue, Feb 12, 2019 at 4:13 PM qzshadow <notifications@github.com> wrote:

> I am quite curious about the scalability of dgl. In practice, I had to
> deal with graphs with millions of node and edges or even more. Based on my
> observations, dgl is a standalone framework which performs deep learning
> algorithms on the graph, that means it will suffer from the memory
> limitations of the machine it deployed, am I correct?
>
> —
> You are receiving this because you are subscribed to this thread.
> Reply to this email directly, view it on GitHub
> <https://urldefense.proofpoint.com/v2/url?u=https-3A__github.com_dmlc_dgl_issues_384&d=DwMCaQ&c=slrrB7dE8n7gBJbeO0g-IQ&r=hT00ArSCDPGICoAESiAkOQ&m=NgGjCVRzZKONw3tiwLJ1pE4FjrM2Gzq_NEsZwHIC3yk&s=65Tmq-D5sF0mkT4RbvO4J87SLses9Tjx_OXTdNG36eo&e=>,
> or mute the thread
> <https://urldefense.proofpoint.com/v2/url?u=https-3A__github.com_notifications_unsubscribe-2Dauth_AIKVUfXE9QyZjlwht3hj6WTJQYITBzLXks5vMnfAgaJpZM4a11ER&d=DwMCaQ&c=slrrB7dE8n7gBJbeO0g-IQ&r=hT00ArSCDPGICoAESiAkOQ&m=NgGjCVRzZKONw3tiwLJ1pE4FjrM2Gzq_NEsZwHIC3yk&s=SylbsOY_rorfG7VOuKBtoKjBUKYF7ObAHkqtqyC5i8A&e=>
> .
>


-- 

*Zheng Zhang <https://shanghai.nyu.edu/academics/faculty/zheng-zhang> 张峥*

Professor of Computer Science, NYU  Shanghai 上海纽约大学计算机系教授


Room 1118, 1555 Century Avenue

Pudong New District, Shanghai 200122, China

中国上海市浦东新区世纪大道1555号1118室, 200122


T Shanghai office 上海办公室 +86 021 2059 5687
T China mobile 中国手机 +86 156 1808 6522
E 电子邮件 zz@nyu.edu

<jw5@nyu.edu>

**Comment by jermainewang** [comment]
@qzshadow for general questions, please use our [discussion forum](https://discuss.dgl.ai). Thank you.
