### ISSUE TITLE
[FEAT REQUEST] Keep batch_graph properties after adding new edges

### ISSUE THREAD

**Issue by fmellomascarenhas** [dmlc/dgl#3843]
## 🚀 Feature
Option to keep the batch graph properties even after adding new edges

## Motivation
My datataset is composed by subgraphs. The dataloader collates them as a batch_graph. I want to make edge modifications after the collate process, like edge augmentations. However, adding edges removes the batch_graph properties.

```
import dgl
import torch as th

g1 = dgl.graph((th.tensor([0, 1, 2]), th.tensor([1, 2, 3]))) # 4 nodes, 3 edges
g2 = dgl.graph((th.tensor([0, 0, 0, 1]), th.tensor([0, 1, 2, 0]))) # 3 nodes, 4 edges
bg = dgl.batch([g1, g2])

#BEFORE ADDING EDGES
print('before', bg.batch_num_nodes(), bg.batch_num_edges())
#output>>> before tensor([4, 3]) tensor([3, 4])

bg.add_edges(th.tensor([0, 0, 0, 1]), th.tensor([0, 1, 2, 0]))
bg.batch_num_nodes(), bg.batch_num_edges()

#AFTER ADDING EDGES
print('after', bg.batch_num_nodes(), bg.batch_num_edges())
#output>>> after tensor([7]) tensor([11])
```

I wonder if there is a way to add edges without merging all the subgraphs. Thanks!

**Comment by jermainewang** [comment]
> However, adding edges removes the batch_graph properties.

This is part of the API specification because it is difficult (inefficient) to keep the batch_graph properties when the topologies are changed. My question is that is it possible to add or remove edges *before* batching the graphs? If so, it will be much easier and you can use the new [`dgl.transforms`](https://docs.dgl.ai/api/python/transforms.html) package for that. If not, could you please share with us your scenario?

**Comment by fmellomascarenhas** [comment]
Thanks for replying! I have been using transforms and it works great :)

All transforms can be done before batching the graphs, but then it requires N transformations to be done, instead of a single one. It is probably not a huge inefficiency, but it is some. It also can limit strategies like per convolution augmentation. But if it is too complicated to change the API to allow this behavior, it think it is probably fine to leave it as it is.

**Comment by BarclayII** [comment]
Closed for won't fix.
