### ISSUE TITLE
Inquiry about the meaning in the PinSage documents

### ISSUE THREAD

**Issue by samaritanhu** [dmlc/dgl#3845]
## 📚 Documentation

Dears,

Hi, we are trying to run this model, but we met some problems in reading the documentation.

[](https://github.com/dmlc/dgl/tree/master/examples/pytorch/pinsage#difference-from-the-paper)The HITS@10 is 0.01241, compared to 0.01220 with SLIM with the same dimensionality.\

Does the HITS@10 mean that hit-rate on 10 epoch? Also, what does SLIM mean here?

Thanks

**Comment by BarclayII** [comment]
HITS@10 means the hit rate for the top-k predictions, and SLIM is [this model](http://glaros.dtc.umn.edu/gkhome/node/774).

**Comment by samaritanhu** [comment]
Thanks!
