### ISSUE TITLE
'BatchedDGLGraph' object has no attribute 'to'

### ISSUE THREAD

**Issue by yuchenlin** [dmlc/dgl#385]
## To Reproduce

1. Following the tutorial of using batched graphs [here](https://docs.dgl.ai/en/latest/tutorials/basics/4_batch.html)
2. in the for loop, I am trying to call `bg.to(device)`, where `device` is from `device = torch.device("cuda:0" if torch.cuda.is_available() else "cpu")`.  

## Expected behavior
1. My goal is to save the graph batch into gpu when I have cuda device available. 
1. but it seems the batched graphs has no `to` function implementation now. 

`AttributeError: 'BatchedDGLGraph' object has no attribute 'to'`

## Environment

 - DGL Version (e.g., 1.0): 0.1.3
 - Backend Library & Version (e.g., PyTorch 0.4.1, MXNet/Gluon 1.3): PyTorch 1.0
 - OS (e.g., Linux): linux and mac 
 - How you installed DGL (`conda`, `pip`, source): pip 
 - Build command you used (if compiling from source): 
 - Python version: 3.6
 - CUDA/cuDNN version (if applicable): no
 - GPU models and configuration (e.g. V100):  no
 - Any other relevant information:

**Comment by yuchenlin** [comment]
I think this `to` should be a recommended way in PyTorch 4.1 and 1.0 to replace `.cpu` and `.cuda`

**Comment by mufeili** [comment]
Hi, rather than moving the batched graph to gpu with `bg.to('cuda: 0')`, you only need to move the node  (and potentially edge) features to gpu with `features.to('cuda: 0')`. In the tutorial, this corresponds to `g.in_degrees().view(-1, 1).float().to('cuda: 0')`.

**Comment by yzh119** [comment]
Hi Bill, 
There are two important components of `DGLGraph`:
- [graph index](https://github.com/dmlc/dgl/blob/master/python/dgl/graph_index.py): the structure of the graph(adjacency matrix, csr/coo representations, ...), such information are supposed to be stored in cpu memory.
- [frame](https://github.com/dmlc/dgl/blob/master/python/dgl/frame.py): node/edge features of the graph. Different fields of features are not necessarily to be stored in the same device. For example, it's possible to write code like the following:
```
import dgl
import torch as th
g = dgl.DGLGraph()
g.add_nodes(10)
g.ndata['x'] = th.rand(10, 5)
g.ndata['y'] = th.rand(10, 2).to(0)
```
Thus we do not support a `.to` interface to specify the device of a graph. However, you could specify the device of the data given its field.

**Comment by jermainewang** [comment]
We didn't provide a graph level `to` API for two reasons:
* To allow different features on different devices as Zihao has pointed out.
* To allow distributed storage in the future (i.e, the feature tensors can be stored distributed on multiple GPUs).

So if feature 'x' is a GPU tensor, then in UDF, `nodes.data['x']` gives a GPU tensor. For built-in functions, we will look at the context of the feature tensor, and perform operation on the corresponding devices. However, there are debates that whether such behavior is convenient of not. Some people don't like it as it's too implicit. Feel free to leave your opinion on this.

**Comment by yuchenlin** [comment]
Hi Mufei, Zihao, and Minjie, 

Thanks so much for the help!  Yeah, I think this is a good, reasonable design for giving users more flexibility on assigning the node/edge features on different devices. It would be just better if we can have a section in the document for this example, so other users can know and follow this design. 

Thanks again for the great DGL!

**Comment by ZDstandup** [comment]
@mufeili thanks!
