### ISSUE TITLE
[Feature Request] Allow to create empty heterogeneous graph with a metagraph input

### ISSUE THREAD

**Issue by ketyi** [dmlc/dgl#3851]
## 🚀 Feature

Allow to create empty (i.e. zero node and zero edge) heterogeneous graph with a metagraph input.

## Motivation

It is possible to instantiate an empty (homogenous) graph, would be good to instantiate a heterogeneous graph too.

**Comment by BarclayII** [comment]
It's doable like this:
```python
g = dgl.heterograph({('A', 'AB', 'B'): ([], [])}, num_nodes_dict={'A': 0, 'B': 0})
```

**Comment by ketyi** [comment]
> 

Thank you, it is indeed. Shall we extend the documentation with it?
