### ISSUE TITLE
[Bug] in querying Heterograph structure

### ISSUE THREAD

**Issue by ketyi** [dmlc/dgl#3854]
## 🐛 Bug

Heterograph structure query sometimes yields weird results. Here is a super simple example:
![image](https://user-images.githubusercontent.com/14096902/158864868-f4dc3557-7587-4238-a1be-eea446e89e7c.png)
![image](https://user-images.githubusercontent.com/14096902/158868104-c9b70b7d-b2ab-4ecc-a61d-68545f170784.png)

I have experienced all these while I was testing whether it works to add an isolated node to a heterograph. Basically it seems to be okay but then couple of questions arise regarding node degree/edge querying as you can see on the pictures. I have written my explicit thoughts in the comments (lines 12-16).

## To Reproduce

import dgl
import torch as th

graph_data = {
    ('object_1', 'relation_1', 'object_1'): (th.tensor([0]), th.tensor([1])),
    ('object_1', 'relation_2', 'object_2'): (th.tensor([0]), th.tensor([0]))
}

g = dgl.heterograph(graph_data)
g.add_nodes(num=1, ntype='object_1')
print(g.num_edges)
print(g.in_degrees(v=3, etype='relation_1')) # For this I would rather expect an out of bounds exception than a random number
print(g.in_degrees(etype='relation_2'))  # Feels under-defined whether it is about ntype object_1 or object_2 but I expect it is somehow about object_2
print(g.out_degrees(etype='relation_2')) # It must be about ntype object_1 but why?
print(g.in_degrees(v=1, etype='relation_2')) # For this I would rather expect an out of bounds exception than a random number
print(g.in_edges(v=3, etype='relation_1')) # I would rather expect an out of bounds exception

C:\Users\20205115\Anaconda3\envs\env_py37_pytorch_19\python.exe C:/Users/20205115/Documents/github/dgl/examples/pytorch/dgmg/bug.py
<bound method DGLHeteroGraph.num_edges of Graph(num_nodes={'object_1': 3, 'object_2': 1},
      num_edges={('object_1', 'relation_1', 'object_1'): 1, ('object_1', 'relation_2', 'object_2'): 1},
      metagraph=[('object_1', 'object_1', 'relation_1'), ('object_1', 'object_2', 'relation_2')])>
5557490499615221106
tensor([1])
tensor([1, 0, 0])
65279
Traceback (most recent call last):
  File "C:/Users/20205115/Documents/github/dgl/examples/pytorch/dgmg/bug.py", line 18, in <module>
    print(g.in_edges(v=3, etype='relation_1')) # I would rather expect an out of bounds exception
  File "C:\Users\20205115\Anaconda3\envs\env_py37_pytorch_19\lib\site-packages\dgl\heterograph.py", line 3249, in in_edges
    src, dst, eid = self._graph.in_edges(self.get_etype_id(etype), v)
  File "C:\Users\20205115\Anaconda3\envs\env_py37_pytorch_19\lib\site-packages\dgl\heterograph_index.py", line 532, in in_edges
    edge_array = _CAPI_DGLHeteroInEdges_2(self, int(etype), F.to_dgl_nd(v))
  File "C:\Users\20205115\Anaconda3\envs\env_py37_pytorch_19\lib\site-packages\dgl\_ffi\_ctypes\function.py", line 190, in __call__
    ctypes.byref(ret_val), ctypes.byref(ret_tcode)))
OSError: [WinError -529697949] Windows Error 0xe06d7363

Process finished with exit code 1

## Expected behavior

- Proper exceptions in case of indexing errors
- Generally, node-type info in the return of the query functions

## Environment

 - DGL Version (e.g., 1.0): 0.8.0post1 (the CPU version!)
 - Backend Library & Version (e.g., PyTorch 0.4.1, MXNet/Gluon 1.3): pytorch 1.9.0           py3.7_cuda10.2_cudnn7_0
 - OS (e.g., Linux): Microsoft Windows 10
 - How you installed DGL (`conda`, `pip`, source):  pip install dgl dglgo -f https://data.dgl.ai/wheels/repo.html (the CPU version!)
 - Build command you used (if compiling from source):
 - Python version: 3.7.9
 - CUDA/cuDNN version (if applicable): cuda10.2_cudnn7_0 (but it is NOT used)
 - GPU models and configuration (e.g. V100): GPU is NOT used
 - Any other relevant information: CPU is used

**Comment by BarclayII** [comment]
Looks like we are not doing boundary checks in the arguments.

**Comment by ketyi** [comment]
Besides the boundary checks, let me revisit the 2nd part of bug:
![image](https://user-images.githubusercontent.com/14096902/159326401-75094b5f-c13c-4f62-83ac-6d2d003589a7.png)

Instead of this output I'd expect information of the two nodes in the given relation.

**Comment by BarclayII** [comment]
`in_degrees` returns the in-degrees of the nodes with the destination type of the given edge type (i.e. `object_2`).  Likewise, `out_degrees` returns the out-degrees of the nodes with the source type of given edge type (i.e. `object_1`).

> Instead of this output I'd expect information of the two nodes in the given relation.

What do you mean by "two nodes in the given relation"?

**Comment by ketyi** [comment]
> 

Thank you Quan,
It makes sense, just not documented. Maybe, that's the general behavior of such a function in case of hetero graphs, I was just not aware of it.

What I meant by "two nodes in the given relation" is: when DGLGraph.in_degrees(v='__ALL__', etype=R) is used, then it could be logical to get the degree lists of both the source and destination ntypes of etype=R.

**Comment by BarclayII** [comment]
In DGL the relation types are directional, that is, the edges of the same relation type always go from a single node type to another single node type.  So `out_degrees('relation_2')` will give you the out degree of the "source node type" which is `object_1`.  And since the relation types are directional, `in_degree` and `out_degree` will only be valid for either the source node type or the destination node type, but not both.
