### ISSUE TITLE
How can I sample nodes twice in a mini-batch?

### ISSUE THREAD

**Issue by jinzhuoran** [dmlc/dgl#3864]
Hi, thank you for noticing my problem!
I want to sample nodes twice in a mini-batch for contrastive learning, how can I use *MultiLayerNeighborSampler* and *NodeDataLoader* to solve this problem?

**Comment by BarclayII** [comment]
Currently `MultiLayerNeighborSampler` does not support sampling duplicated nodes.  You will need to write your own neighbor sampler.  Please refer to https://docs.dgl.ai/guide/minibatch-custom-sampler.html for an example on how to build a custom sampler.
