### ISSUE TITLE
Latest version of dgl (0.8.0.post1) is not available for python 3.9 on pypi.org (preventing python package dependency resolution using pip-compile)

### ISSUE THREAD

**Issue by balling-dev** [dmlc/dgl#3868]
## 🐛 Bug

The latest version of dgl (`0.8.0.post1`) is not available for python 3.9 on pypi.org (it appears to only be available for python 3.10 on pypi.org). Some older versions of `dgl` (e.g. `0.6.1`) are available for python 3.9 on pypi.org.

While `dgl` can be installed for python 3.9 using the [instructions provided at the www.dgl.ai web-site](https://www.dgl.ai/pages/start.html) (`pip install dgl dglgo -f https://data.dgl.ai/wheels/repo.html`), that mechanism does not allow python package dependency tools such as `pip-compile` to determine a collection of compatible python package versions.

I would expect releases of `dgl` to be available in pypi.org for all compatible versions of python, and thereby also available for dependency resolution by tools like `pip-compile`.

## To Reproduce

```dockerfile
FROM python:3.9
RUN python3 -m pip install dgl==0.8.0.post1
```

```bash
$ docker build .
Sending build context to Docker daemon  2.048kB
Step 1/2 : FROM python:3.9
 ---> 47abcf270bef
Step 2/2 : RUN python3 -m pip install dgl==0.8.0.post1
 ---> Running in 22e48d848549
ERROR: Could not find a version that satisfies the requirement dgl==0.8.0.post1 (from versions: 0.1.0, 0.1.2, 0.1.3, 0.6.0, 0.6.0.post1, 0.6.1)
ERROR: No matching distribution found for dgl==0.8.0.post1
The command '/bin/sh -c python3 -m pip install dgl==0.8.0.post1' returned a non-zero code: 1
```

## Expected behavior

I would expect `dgl` versions (including `0.8.0.post1`) to be available for all compatible version of python (including python 3.9)

## Environment

 - DGL Version (e.g., 1.0): 0.8.0.post1
 - Backend Library & Version (e.g., PyTorch 0.4.1, MXNet/Gluon 1.3): none
 - OS (e.g., Linux): Linux (debian 11)
 - How you installed DGL (`conda`, `pip`, source): `pip`
 - Build command you used (if compiling from source): none
 - Python version: 3.9
 - CUDA/cuDNN version (if applicable): none
 - GPU models and configuration (e.g. V100): none
 - Any other relevant information: none

**Comment by jermainewang** [comment]
Hi, thanks for reporting the issue. One question. Since DGL has multiple GPU builds (e.g., dgl-cu110, dgl-cu112), is there a way for users to specify a certain version but not care about which GPU build it is?
