### ISSUE TITLE
A bug in the tutorial of RGCN

### ISSUE THREAD

**Issue by yuchenlin** [dmlc/dgl#387]
## 📚 Documentation

For the [Relational Graph Convolutional Network Tutorial](https://docs.dgl.ai/en/latest/tutorials/models/1_gnn/4_rgcn.html#define-full-r-gcn-model), 
there is a line `h2h = self.build_hidden_layer(idx)` that will report a bug since the defination of `self.build_hidden_layer` has no argument for `idx`

**Comment by yuchenlin** [comment]
This `idx` was used to indicate whether it is the final layer, but I think it is not useful in this context.

**Comment by yzh119** [comment]
Thanks for pointing this out. We'll fix this.

**Comment by yzh119** [comment]
Fixed.
