### ISSUE TITLE
[IndexError] dgl/examples/pytorch/pinsage/model.py 

### ISSUE THREAD

**Issue by fanaev** [dmlc/dgl#3877]
Hello, I'm trying adapted pinsage implementation to H/M dataset (data: https://www.kaggle.com/competitions/h-and-m-personalized-fashion-recommendations/data). But I got error when launching model.py:

Traceback (most recent call last):
  File ".../model.py", line 143, in <module>
    train(dataset, args)
  File ".../model.py", line 101, in train
    loss = model(pos_graph, neg_graph, blocks).mean()
  File "/Library/Frameworks/Python.framework/Versions/3.9/lib/python3.9/site-packages/torch/nn/modules/module.py", line 1102, in _call_impl
    return forward_call(*input, **kwargs)
  File ".../model.py", line 24, in forward
    h_item = self.get_repr(blocks)
  File ".../model.py", line 30, in get_repr
    h_item = self.proj(blocks[0].srcdata)
  File "/Library/Frameworks/Python.framework/Versions/3.9/lib/python3.9/site-packages/torch/nn/modules/module.py", line 1102, in _call_impl
    return forward_call(*input, **kwargs)
  File ".../layers.py", line 106, in forward
    result = module(data)
  File "/Library/Frameworks/Python.framework/Versions/3.9/lib/python3.9/site-packages/torch/nn/modules/module.py", line 1102, in _call_impl
    return forward_call(*input, **kwargs)
  File "/Library/Frameworks/Python.framework/Versions/3.9/lib/python3.9/site-packages/torch/nn/modules/sparse.py", line 158, in forward
    return F.embedding(
  File "/Library/Frameworks/Python.framework/Versions/3.9/lib/python3.9/site-packages/torch/nn/functional.py", line 2044, in embedding
    return torch.embedding(weight, input, padding_idx, scale_grad_by_freq, sparse)
**IndexError:** index out of range in self

Below I show what code I change/adapted:

 dgl/examples/pytorch/pinsage/data_utils.py 
```
    customers = pd.read_csv('data/customers.csv')
    articles = pd.read_csv('data/articles.csv')
    transactions = pd.read_csv('data/transactions_train.csv')[['customer_id', 'article_id', 't_dat']]

    articles = articles.drop(columns = ['product_type_name', 'graphical_appearance_name', 'colour_group_name', 'perceived_colour_value_name',
                            'perceived_colour_master_name', 'index_name', 'index_group_name', 'section_name', 
                            'garment_group_name', 'prod_name', 'department_name', 'detail_desc'])

    for col in ['index_code', 'product_group_name']:
        number = LabelEncoder()
        articles[col] = number.fit_transform(articles[col].astype('str'))


    transactions['t_dat'] = transactions['t_dat'].values.astype('datetime64[s]').astype('int64')

    graph_builder = PandasGraphBuilder()
    graph_builder.add_entities(customers, 'customer_id', 'customer')
    graph_builder.add_entities(articles, 'article_id', 'article')
    graph_builder.add_binary_relations(transactions, 'customer_id', 'article_id', 'bought')
    graph_builder.add_binary_relations(transactions, 'article_id', 'customer_id', 'bought-by')
    g = graph_builder.build()

    for col in articles.columns:
        if col == 'article_id':
            continue
        else:
            g.nodes['article'].data[col] = torch.LongTensor(articles[col].values)
    g.edges['bought'].data['t_dat'] = torch.LongTensor(transactions['t_dat'].values)
    g.edges['bought-by'].data['t_dat'] = torch.LongTensor(transactions['t_dat'].values)

    train_indices, val_indices, test_indices = np.load('data/train_indices.npy'), np.load('data/val_indices.npy'), np.load('data/test_indices.npy')

    train_g = build_train_graph(g, train_indices, 'customer', 'article', 'bought', 'bought-by')
    val_matrix, test_matrix = build_val_test_matrix(
        g, val_indices, test_indices, 'customer', 'article', 'bought')

    dataset = {
            'train-graph': train_g,
            'val-matrix': val_matrix,
            'test-matrix': test_matrix,
            'item-texts': {},
            'item-images': None,
            'user-type': 'customer',
            'item-type': 'article',
            'user-to-item-type': 'bought',
            'item-to-user-type': 'bought-by',
            'timestamp-edge-column': 't_dat'}

    with open('data/graph', 'wb') as f:
        pickle.dump(dataset, f)
```

build_train_graph from dgl/examples/pytorch/pinsage/data_utils.py 
```
def build_train_graph(g, train_indices, utype, itype, etype, etype_rev):
    train_g = g.edge_subgraph(
        {etype: train_indices, etype_rev: train_indices},
        preserve_nodes=True)
        ...
    return train_g
```

**Comment by Rhett-Ying** [comment]
I think you need to check and print out the arguments/data when the script crashes such as `data` in `layers.py:line106`, the arguments of `DataLoader`, the `pos_graph`, `neg_graph` `blocks` of `dataloader_it` to see if any of them have incorrect index.

**Comment by fanaev** [comment]
There are some negative values in h/m dataset which cause problem
