### ISSUE TITLE
Allow process, save and load part of the dataset in the `DGLDataset`

### ISSUE THREAD

**Issue by chenzhekl** [dmlc/dgl#3882]
## 🚀 Feature

I would like to propose adding functionalities to process, load and save parts of the dataset in the `DGLDataset`.

## Motivation

The current design of `DGLDataset` class requires processing, saving and loading the complete dataset as a whole. This is fine for small datasets but is not appropriate if the dataset does not fit in the memory. 

## Alternatives

Writing the pre-processing and caching logic in `__getitem__`.

## Pitch

I would like finer control over the pre-processing pipeline, such that we can independently process, save and load each item of a dataset.

**Comment by Rhett-Ying** [comment]
Hi, could you elaborate more what the expected interfaces `NewDGLDataset` provides and how you will use it to handle your case: dataset cannot be fitted into memory? please list the interfaces and show a minimal demo.

**Comment by chenzhekl** [comment]
Hi, @Rhett-Ying , Thanks for your reply! For reference, the current data loading logic for `DGLDataset` is finishing everything from process to save and load all in `__init__`.

```python
load_flag = not self._force_reload and self.has_cache()

if load_flag:
    try:
        self.load()
        if self.verbose:
            print('Done loading data from cached files.')
    except KeyboardInterrupt:
        raise
    except:
        load_flag = False
        if self.verbose:
            print(traceback.format_exc())
            print('Loading from cache failed, re-processing.')
if not load_flag:
    self._download()
    self.process()
    self.save()
    if self.verbose:
        print('Done saving data into cached files.')
```

As seen in the code, it tries to load everything into the memory. For example, if we would like to train a GNN to do graph classification and each graph consists of millions of nodes, it might be better to move `load` out to `__getitem__` and accelerate data loading by multi-threading in the `DataLoader`. Accordingly, the pre-processing logic in `__init__` might be:

```python
process_flag = self._force_reload or (not self.has_cache())

if process_flag:
    self._download()
    self.process()
    self.save()
    if self.verbose:
        print('Done saving data into cached files.')
```

where one can arbitrarily divide the dataset into several files. The data loading logic can be manually implemented by the user in `__getitem__`, e.g.,

```python
data = torch.load(
    os.path.join(self.processed_dir, self.processed_file_names[idx])
)
return data
```

**Comment by Rhett-Ying** [comment]
if all the graphs cannot fit into memory, we may also need to split `self.process` and `self.save` besides `self.load`. process parts and save, then process other and save?
