### ISSUE TITLE
Unified device_type string for different backends

### ISSUE THREAD

**Issue by yaox12** [dmlc/dgl#3883]
## 🚀 Feature

Just realized we don't have a unified `F.device_type` string for different backends. Say we have a `tensor` on GPU, the `F.device_type(F.context(tensor))` will be `'gpu'` for Tensorflow and MXNet while `'cuda'` for PyTorch, which brings some difficulties in writing backend-agnostic code.

I know `F.device_type(F.context(tensor)) != 'cpu'` is a temporary alternative. However it could cause problems when we might support other device types in the future.

**Comment by Rhett-Ying** [comment]
how about having utility calls: `F.is_cpu()`, `F.is_gpu()` ?

**Comment by yaox12** [comment]
It works for me. A suggestion is that we should be careful with the name and logic of `F.is_gpu()`.

For example in PyTorch, they use `cuda` as the unified device type for both NVIDIA and AMD GPUs and introduce another flag `torch.version.cuda` or `torch.version.hip` to check the concrete hardware platform. I'm not familiar with MXNet/TensorFlow and don't know how they distinguish `cuda` and `hip`.

Here in DGL, we should take this into consideration in case we support AMD GPUs in the future (though we don't have a plan for now).
