### ISSUE TITLE
Hanging in distributed training when num_samplers > 0

### ISSUE THREAD

**Issue by ilil96** [dmlc/dgl#3887]
## 🐛 Bug

Hi, I'm running the code for distributed training with 2 GCP instances following the tutorial (https://docs.dgl.ai/en/0.7.x/tutorials/dist/1_node_classification.html). I used the same code as the tutorial except that I used DistNodeDataloader instead of NodeDataLoader.
And I found out that the training freezes with num_samplers greater than 0 while it works well when num_samplers=0. 
Specifically, the training loop randomly freezes after some iterations or even at the first iteration.

## To Reproduce

Run the code at https://docs.dgl.ai/en/0.7.x/tutorials/dist/1_node_classification.html with num_samplers > 0
Here is the script that I used:
python3 launch.py   --workspace path-to-workspace   --num_trainers 1   --num_samplers 1   --num_servers 1   --part_config path-to-config   --ip_config path-to-ip-config   "python3 train_dist.py"

## Environment

 - DGL Version (e.g., 1.0): 0.8.0post1
 - Backend Library & Version (e.g., PyTorch 0.4.1, MXNet/Gluon 1.3): 1.10.0
 - OS (e.g., Linux): Debian 10
 - How you installed DGL (`conda`, `pip`, source): pip
 - Build command you used (if compiling from source): N/A
 - Python version:  3.7.12
 - CUDA/cuDNN version (if applicable): N/A
 - GPU models and configuration (e.g. V100): N/A
 - Any other relevant information: N/A

**Comment by Rhett-Ying** [comment]
could you try with this: https://github.com/dmlc/dgl/tree/master/examples/pytorch/graphsage/dist ?

I tried, it works well in my side.

**Comment by ilil96** [comment]
I tested the code in the link you shared but I faced the same issue.
The program hangs when I set num_samplers > 0.
Can you share the command you used for the training with multiple samplers?

By the way, no command given as example in the document seems to support multiple sampler processes.
There are some commands that set num_samplers to 4 but they overwrite it with 0 like the following.
`python3 ~/workspace/dgl/tools/launch.py --workspace ~/workspace/dgl/examples/pytorch/graphsage/dist/ \
--num_trainers 4 \
--num_samplers 4 \
--num_servers 1 \
--num_samplers 0 \
--part_config data/ogb-product.json \
--ip_config ip_config.txt \
"python3 train_dist_transductive.py --graph_name ogb-product --ip_config ip_config.txt --batch_size 1000 --num_gpu 4 --eval_every 5"`

**Comment by Rhett-Ying** [comment]
Multiple samplers are supported. below is my command:
`python3 ~/workspace/dgl/tools/launch.py --workspace ~/workspace/dgl/examples/pytorch/graphsage/dist/ --num_trainers 1 --num_samplers 1 --num_servers 1 --part_config data/ogb-product.json --ip_config ~/workspace/ip_config.txt "python3 train_dist.py --graph_name ogb-product --ip_config ~/workspace/ip_config.txt --num_epochs 5 --batch_size 2048 --eval_every 1024"`

I am using `dgl-cu102, 0.9a220324` on `ubuntu18.04`.

have you tried to follow the steps in the example link I sent? it works for `num_samplers=0`?

could you try with latest nightly build? refer to https://www.dgl.ai/pages/start.html for detailed command.

**Comment by ilil96** [comment]
@Rhett-Ying 
The script now works after I upgrade DGL to the latest nightly build version.
Thanks so much for your help!
