### ISSUE TITLE
random issue in dgl.nn.GATConv

### ISSUE THREAD

**Issue by yimenren** [dmlc/dgl#3900]
## ❓ Questions and Help

Why is the training result still not fixed in dgl.nn.GATConv after the dgl random seed is fixed？Any answer is welcome，thanks!
we already set 
``   random.seed(seed)
    np.random.seed(seed)
    os.environ['PYTHONHASHSEED'] = str(seed)
    torch.manual_seed(seed)
    torch.cuda.manual_seed(seed)
    torch.cuda.manual_seed_all(seed)
    torch.backends.cudnn.deterministic = True
    torch.backends.cudnn.benchmark = False
    dgl.seed(seed)
    dgl.random.seed(seed)`

**Comment by decoherencer** [comment]
#3302

**Comment by yimenren** [comment]
> #3302
This randomness is not observed when the dataset is small (like 6k nodes). But when the dataset is large (like 100,000 nodes), some randomness is seen around the 4th decimal place, which makes the experiment not strictly reproducible
