### ISSUE TITLE
does dgl support  transformerconv

### ISSUE THREAD

**Issue by bookug** [dmlc/dgl#3902]
this algorithm is a mix of gnn and lpa

**Comment by jermainewang** [comment]
Hi, could you post more contexts? A question like this will be closed. Please provide what is the specific paper you are talking about? Is there any author implementation out there? etc.

**Comment by bookug** [comment]
Masked Label Prediction: Unified Message Passing Model for Semi-Supervised Classification

**Comment by yzh119** [comment]
It's just a transformer on graphs, like [DotGATConv](https://docs.dgl.ai/generated/dgl.nn.pytorch.conv.DotGatConv.html?highlight=dotgatconv#dgl.nn.pytorch.conv.DotGatConv).
