### ISSUE TITLE
Column missing pinned_by_dgl attribute

### ISSUE THREAD

**Issue by kkranen** [dmlc/dgl#3905]
## 🐛 Bug

When using use_uva with an edge dataloader and negative sampling on a heterograph, in dataloader instanatiation, a failure is thrown that AttributeError: 'Column' object has no attribute 'pinned_by_dgl'.

## To Reproduce

1. Create heterograph 
2. Create negative sampler (uniform ok)
3. Create edge dataloader

## Expected behavior

No error to be invoked when using UVA in the link prediction context.

## Environment

 - DGL Version: 0.8post2

**Comment by BarclayII** [comment]
I tried the following and it works:
```python
import dgl
import torch

g = dgl.heterograph(
    {('A', 'AB', 'B'): (torch.randint(0, 2000, (10000,)), torch.randint(0, 2000, (10000,))),
     ('B', 'BA', 'A'): (torch.randint(0, 2000, (10000,)), torch.randint(0, 2000, (10000,)))})
s = dgl.dataloading.as_edge_prediction_sampler(
    dgl.dataloading.NeighborSampler([2]),
    exclude='self', negative_sampler=dgl.dataloading.negative_sampler.Uniform(2))
dl = dgl.dataloading.DataLoader(
    g, {'AB': torch.arange(10000).cuda(), 'BA': torch.arange(10000).cuda()}, s, batch_size=2000, shuffle=True,
    drop_last=False, use_uva=True, device='cuda')
for k in dl:
    print(k[-1][0].device)   # <-- 'cuda:0'
```

Could you post your code that crashes?

**Comment by kkranen** [comment]
Hi! I can't post the code here, but I'm working on a minimum reproducible snippet to help track this one down.

**Comment by kkranen** [comment]
Still working on a minrep, but I'll include my stacktrace on current main: 
E torch.multiprocessing.spawn.ProcessRaisedException:
E
E       -- Process 0 terminated with the following error:
E       Traceback (most recent call last):
E         File "/opt/conda/lib/python3.8/site-packages/torch/multiprocessing/spawn.py", line 69, in _wrap
E           fn(i, *args)
E         File "/workspace/gp/workflow/trainers/utils.py", line 10, in run
E           trainer.fit_process(rank)
E         File "/workspace/gp/workflow/trainers/trainer.py", line 108, in fit_process
E           self.setup(rank)
E         File "/workspace/gp/workflow/trainers/trainer.py", line 159, in setup
E           self.data_object.build_test_dataloader_post_dist(device, False)
E         File "/workspace/gp/data_loaders/lp_data_object.py", line 313, in build_test_dataloader_post_dist
E           LPDataObject_DGL.build_test_dataloader_post_dist(
E         File "/workspace/gp/data_loaders/lp_data_object.py", line 260, in build_test_dataloader_post_dist
E           self.test_dataloader = dgl.dataloading.EdgeDataLoader(
E         File "/opt/conda/lib/python3.8/site-packages/dgl-0.8.0.post2-py3.8-linux-x86_64.egg/dgl/dataloading/dataloader.py", line 925, in __init__
E           super().__init__(
E         File "/opt/conda/lib/python3.8/site-packages/dgl-0.8.0.post2-py3.8-linux-x86_64.egg/dgl/dataloading/dataloader.py", line 766, in __init__
E           self.graph.pin_memory_()
E         File "/opt/conda/lib/python3.8/site-packages/dgl-0.8.0.post2-py3.8-linux-x86_64.egg/dgl/heterograph.py", line 5555, in pin_memory_
E           col.pin_memory_()
E         File "/opt/conda/lib/python3.8/site-packages/dgl-0.8.0.post2-py3.8-linux-x86_64.egg/dgl/frame.py", line 397, in pin_memory_
E           if not self.pinned_by_dgl and not F.is_pinned(self.data):
E       AttributeError: 'Column' object has no attribute 'pinned_by_dgl'

**Comment by Rhett-Ying** [comment]
could you try with latest DGL? or provide a minimal repro.

**Comment by kkranen** [comment]
@Rhett-Ying seems to resolve with the most recent DGL build that I tested with. Seems that a recent change (<1wk) resolved the issue. Closing as it seems resolved.
