### ISSUE TITLE
Disjoint split for link prediction

### ISSUE THREAD

**Issue by decoherencer** [dmlc/dgl#3907]
## 🚀 Feature
A split argument for the (training) graphs dataloader to generate x% supervision edges for link prediction similar to the [cs224w](https://web.stanford.edu/class/cs224w/slides/09-theory.pdf) and [deepsnap](https://github.com/snap-stanford/deepsnap/blob/6197dcefc7934c6019fe2f4b0aada562e6c17c7d/deepsnap/dataset.py#L928)

## Motivation
These supervision edges can help in training with suitable objective function and backpropagation and could provide better generalization with the link prediction

**Comment by jermainewang** [comment]
0.8 introduced a new [`AsLinkPredDataset`](https://docs.dgl.ai/generated/dgl.data.AsLinkPredDataset.html#dgl.data.AsLinkPredDataset) API which will add data splits to a dataset. Is this what you are looking for?

**Comment by decoherencer** [comment]
> Is this what you are looking for?

Sorry, but the split in the `AsLinkPredDataset` only gives train, val, and test split and doesn't provide a way to include supervision edges.

But, a way was provided [here ](https://discuss.dgl.ai/t/link-prediction-questions/2837/3)
