### ISSUE TITLE
How can I save a trained GNN model?(tensorflow backend)

### ISSUE THREAD

**Issue by hmliangliang** [dmlc/dgl#3920]
## ❓ Questions and Help

The GNN model can be trained well. However, it seems that model.save() cannot export the trained model. There are a few related tutorials or examples. I have been troubled by this problem for many days. Could you give me an example?

**Comment by VoVAllen** [comment]
Please try `model.save_weights('es_checkpoint.pb')` for keras model

**Comment by LukeLIN-web** [comment]
> ## ❓ Questions and Help
> The GNN model can be trained well. However, it seems that model.save() cannot export the trained model. There are a few related tutorials or examples. I have been troubled by this problem for many days. Could you give me an example?

I also tried it , the bottom error is AttributeError: 'Tensor' object has no attribute 'ndim'
