### ISSUE TITLE
Wrong numerical result in HeatKernel

### ISSUE THREAD

**Issue by Kh4L** [dmlc/dgl#3922]
## 🐛 Bug

The unit test `test_module_heat_kernel` is failing on some machines due to a numerical issue.

I narrowed the issue down to result of the scipy's  `expm` called in the `HeatKernel`:  

https://github.com/dmlc/dgl/blob/dc5035b1f32091847e512e2f9786e08e05495fa4/python/dgl/transforms/module.py#L988
 
On some machines, the `expm` returns different values.
The same element can be `0.27067056` on a machine but rounded to `0.2706706` on another one. This changes changes the final result by changing the later computed `eps` in the algorithm.

## To Reproduce

Steps to reproduce:

```
export DGLBACKEND=pytorch
export DGLTESTDEV=gpu
python3 -m pytest -v --junitxml=pytest_compute.xml tests/compute -k "test_module_heat_kernel"
```

## Environment

 - DGL Version:
 - Backend Library & Version (e.g., PyTorch 0.4.1, MXNet/Gluon 1.3):  PyTorch 1.11
 - OS : Linux
 - How you installed DGL : source
 - Python version: several

**Comment by BarclayII** [comment]
> The same element can be `0.27067056` on a machine but rounded to `0.2706706` on another one

Is it because one scipy uses float32 and another uses float64?

**Comment by Kh4L** [comment]
> > The same element can be `0.27067056` on a machine but rounded to `0.2706706` on another one
> 
> Is it because one scipy uses float32 and another uses float64?

Yes it could be a different type conversion at some point in the internals. The I/O dtypes of the ops are float32 on both machines.

I tried to track the datatypes in scipy but it's hard to track as it's going in helper functions such as:

https://github.com/scipy/scipy/blob/38cd478334a07b6e9dfe224a3ff66ad356c53524/scipy/sparse/linalg/matfuncs.py#L523

and 

https://github.com/scipy/scipy/blob/38cd478334a07b6e9dfe224a3ff66ad356c53524/scipy/sparse/linalg/matfuncs.py#L129

**Comment by BarclayII** [comment]
Are you using the same scipy versions?

Either way, I think it's best to rewrite the unit test to account for such numerical instability, since it's quite possible for complex functions like matrix exponential to yield slightly different results across calls.

@mufeili for awareness.

**Comment by mufeili** [comment]
I remember you previously mentioned that there was a bug in PyTorch's `geq` that is used in `HeatKernel`. Does that issue still exist?

**Comment by Kh4L** [comment]
@BarclayII the algorithm is super sensitive to these small variations and we get different results in the output. The easiest thing we could do is to accept 2 baselines, one for each variation.

@mufeili , I was wrong, the `torch.ge` works well, but its input values are slightly different because of the precision difference in the matrix exponential function.

**Comment by mufeili** [comment]
Alternatively, we can remove the LoC for checking the edges of the returned graph.
