### ISSUE TITLE
The test accuracy of distributed training is lower than standalone

### ISSUE THREAD

**Issue by zhixiongning** [dmlc/dgl#3931]
The test accuracy of standalone training is 0.78 but it is only 0.6 in distributed training. We use the same parameters for training.

**Comment by Rhett-Ying** [comment]
please provide more details such as `DGL version`, `platform` and so on. just follow the template we provided in `bug` category. 

Are you using your own dataset and train script, or one of the examples DGL provides? Could you provide a minimal repro?

**Comment by zhixiongning** [comment]
> please provide more details such as `DGL version`, `platform` and so on. just follow the template we provided in `bug` category.
> 
> Are you using your own dataset and train script, or one of the examples DGL provides? Could you provide a minimal repro?

The problem has been solved. Thanks.
