### ISSUE TITLE
A question about the GPU version of dgl

### ISSUE THREAD

**Issue by HEI-MENGZHE** [dmlc/dgl#3932]
hi, I have a question about the GPU version of dgl. Everything was fine when I just used the CPU to run my project, but if I tried to assign the graph to my GPU, it would report an error that is "Device API GPU is not enabled. Please install the Cuda version of dgl." But I had already installed dgl-cu111. I tried to uninstall the CPU version of dgl to solve the problem, but it would report that "No module named dgl. function" when I try to use the dgl. function. 
Here are more details about my environment:
torch: 
 1.5.1+cu92 | 1.11.0
system: Win 10
I install dgl through pip and I never use conda
CUDA 11.1

**Comment by BarclayII** [comment]
This is probably caused by your installation of multiple DGL versions.  You could try
```
pip freeze |grep dgl
```
to find all of them.  Then for each package you could run
```
pip uninstall dgl-xxx
```
repeatedly until it says `dgl is not installed`.

**Comment by HEI-MENGZHE** [comment]
thank you for your reply, I uninstalled all the dgl versions I had including dgl, dglgo, dglcu111 and it said can't find the module named dgl. Then I installed the GPU version of dgl by `pip install dgl-cu111 dglgo -f https://data.dgl.ai/wheels/repo.html`, but it said OSError: [WinError 126] cannot find the specified module.  Why is that?

**Comment by HEI-MENGZHE** [comment]
thank you for your reply, I uninstalled all the dgl versions I had including dgl, dglgo, dglcu111 and it said can't find the module named dgl. Then I installed the GPU version of dgl by `pip install dgl-cu111 dglgo -f https://data.dgl.ai/wheels/repo.html`, but it said OSError: [WinError 126] cannot find the specified module.  Why is that?

**Comment by BarclayII** [comment]
That probably means your system hasn't installed CUDA 11.1.

Note that PyTorch ships its own CUDA 11.1 runtime so it will work on GPU even if you didn't actually install CUDA 11.1.  DGL does not ship that and relies on system's CUDA runtime.
