### ISSUE TITLE
UVA performance with RGCN training using MAG dataset

### ISSUE THREAD

**Issue by oyilmaz-nvidia** [dmlc/dgl#3937]
I have been testing the UVA and noticed that I couldn't get any running time performance improvement for a node classification task using MAG dataset and RGCN model. Is this expected? Or, did you guys see any run time difference with UVA for RGCN model training?

**Comment by BarclayII** [comment]
The RGCN MAG example itself did not use UVA as far as I remember.  Did you set `use_uva=True` in the dataloaders?

**Comment by oyilmaz-nvidia** [comment]
Yes, I set `use_uva=True`. I actually see a different error right now. Will close this one for now and will open a new one for the bug I saw.
