### ISSUE TITLE
Does dgl support model parallel ?

### ISSUE THREAD

**Issue by Modberge** [dmlc/dgl#3938]
## ❓ Can I put a model on multi-GPUs in parallel training and testing?

I tried to use a GNN model for a large heterogeneous graph( [https://ogb.stanford.edu/docs/linkprop/#ogbl-wikikg2](url) ). The graph is so large that my model is out of memory when testing. So I have to set the dimension parameters of the GNN model to 64. I have one machine with four GPUs, thus I want to get the result in dimension=128 or even 256.

I have read the Single Machine Multi-GPU Minibatch Node Classification tutorial [https://docs.dgl.ai/tutorials/multi/2_node_classification.html#single-machine-multi-gpu-minibatch-node-classification](url). It seems that DGL supports data parallel. However, I don`t want to reduce the time of training, but want to run a bigger model in multi-GPUs. Can I deal with this problem that puzzled me for days by using DGL?

Hope to get your reply, Thanks.

**Comment by BarclayII** [comment]
Model parallel should work in DGL like in any [PyTorch modules](https://pytorch.org/tutorials/intermediate/model_parallel_tutorial.html).

Please feel free to reopen this issue if you find it not working for you.
