### ISSUE TITLE
AttributeError: module 'dgl.dataloading' has no attribute 'NeighborSampler'

### ISSUE THREAD

**Issue by HGamalElDin** [dmlc/dgl#3952]
I'm trying to use the dgl dataloader to train a node classifier on a graph, here's a sample code 

```
import dgl
sampler = dgl.dataloading.NeighborSampler([4, 4])
train_dataloader = dgl.dataloading.DataLoader(
    # The following arguments are specific to DGL's DataLoader.
    graph,              # The graph
    train_nids,         # The node IDs to iterate over in minibatches
    sampler,            # The neighbor sampler
    device=device,      # Put the sampled MFGs on CPU or GPU
    # The following arguments are inherited from PyTorch DataLoader.
    batch_size=1024,    # Batch size
    shuffle=True,       # Whether to shuffle the nodes for every epoch
    drop_last=False,    # Whether to drop the last incomplete batch
    num_workers=0       # Number of sampler processes
)
```

## Environment

 - DGL Version : 0.6.1
 - Backend Library & Version: PyTorch 1.11.0+cpu
 - OS: Windows 10 pro
 - How you installed DGL (`conda`, `pip`, source): pip install dgl

 - Python version: 3.7
 - CUDA/cuDNN version (if applicable): cpu version

**Comment by BarclayII** [comment]
The name `NeighborSampler` appears in 0.8+.  For older versions you could use `MultiLayerNeighborSampler` which is the same.

**Comment by HGamalElDin** [comment]
> The name `NeighborSampler` appears in 0.8+. For older versions you could use `MultiLayerNeighborSampler` which is the same.
