### ISSUE TITLE
[Memory][PyTorch] Use the TensorAdapter for workspace allocations

### ISSUE THREAD

**Issue by nv-dlasalle** [dmlc/dgl#3957]
## 🚀 Feature
Currently, DGL ends up using two memory pools if TensorAdapter is used, PyTorch's and then the workspace allocator in DGL. This has two issues, 1) having to concurrent memory pools means we cannot re-use allocations between and error messages from either allocator can be pretty confusing to users seeing each on use only half of the memory the and 2) the DGL workspace memory pool can often take about 2x the memory that is required.

This is relevant to #3933.

If tensoradapter is available, could we redirect workspace allocations to that?

**Comment by yaox12** [comment]
We discussed this issue in last week's core meeting and merging the memory allocator is already in our roadmap.

**Comment by nv-dlasalle** [comment]
Thanks, that great to hear!
