### ISSUE TITLE
I am confused about the calculation order of GAT

### ISSUE THREAD

**Issue by hbsun2113** [dmlc/dgl#396]
In the implementation of GAT, you apply normalizer after computing the aggregated node features as following:
![image](https://user-images.githubusercontent.com/27994442/52900525-d469ca80-3231-11e9-952d-92260e6a484a.png)
However, in the original paper, the authors apply normalizer before computing the aggregated node features as following:
![image](https://user-images.githubusercontent.com/27994442/52900541-0844f000-3232-11e9-98a8-31b705372c59.png)
I wonder why you adjust the order?

By the way, does the GAT model converges for the dataset cora?
I run the model by ``` python train.py --dataset=cora```. And the result is the following:
![image](https://user-images.githubusercontent.com/27994442/52900564-5d810180-3232-11e9-8fc2-fe9092e3f7ad.png)

**Comment by jermainewang** [comment]
Hey @hbsun2113 , could you ask it in the discussion forum? Thank you.
