### ISSUE TITLE
sample sub_graph from different big graphs

### ISSUE THREAD

**Issue by woshifzh** [dmlc/dgl#3964]
Hi, this is my question. Now I'm going with a node classification problem, and my dataset contains ~1K graph with node number varying from 0.1K to 100K.  I'm now using dataloader to sample a sub_graph from each graph in order, as below ——
```
for graph in graph_list:
    dataloader = dgl.dataloading.DataLoader(graph, train_inds, sampler, ...)
    for  input_nodes, output_nodes, sub_graph in enumerate(dataloader):
         train_with_sub_graph(....)
```

but I wonder can I randomly sample sub_graph from every graph,  maybe——
```
graphData = genDataset(graph_list)
dataloader = dgl.dataloading.DataLoader(graphData , train_inds, sampler, ...)
for  input_nodes, output_nodes, sub_graph in enumerate(dataloader):
     train_with_sub_graph(....)
```

**Comment by BarclayII** [comment]
Are you trying to sample a subgraph from a random graph in the dataset?  Is it OK to treat your whole dataset as a bigger graph?

**Comment by woshifzh** [comment]
> Are you trying to sample a subgraph from a random graph in the dataset? Is it OK to treat your whole dataset as a bigger graph?

Yes，I'm trying to sample a subgraph from a random graph in the dataset.

I do not treat them as a big graph because of cpu OOM. Besides, each graph is meaningful as single graph. I'm afraid if I make up a big graph with nodes with similar features but belonging to different graphs,  it may mislead the model.

**Comment by BarclayII** [comment]
> I do not treat them as a big graph because of cpu OOM.

Then I guess you could do a two-level loop where the outer loop samples a bunch of graphs and batch them together into a single graph, and the inner loop runs `dgl.dataloading.DataLoader` with neighbor sampling?

> Besides, each graph is meaningful as single graph. I'm afraid if I make up a big graph with nodes with similar features but belonging to different graphs, it may mislead the model.

I don't think you need to worry about this since the node representation will only depend on itself and its local neighborhood.  It should be fine even if the nodes sampled in a single batch belongs to different graphs.

**Comment by woshifzh** [comment]
> > I do not treat them as a big graph because of cpu OOM.
> 
> Then I guess you could do a two-level loop where the outer loop samples a bunch of graphs and batch them together into a single graph, and the inner loop runs `dgl.dataloading.DataLoader` with neighbor sampling?
> 
> > Besides, each graph is meaningful as single graph. I'm afraid if I make up a big graph with nodes with similar features but belonging to different graphs, it may mislead the model.
> 
> I don't think you need to worry about this since the node representation will only depend on itself and its local neighborhood. It should be fine even if the nodes sampled in a single batch belongs to different graphs.

Thank you, I'll try
