### ISSUE TITLE
Zerocopying a tensor from pytorch is out of place if non-contiguous (removes sharing and causes issues with in place pinning).

### ISSUE THREAD

**Issue by nv-dlasalle** [dmlc/dgl#3976]
## 🐛 Bug

In the PyTorch backend we use `.contiguous()` in the zerocopy functions, which is an out of place operation.
https://github.com/dmlc/dgl/blob/5b97a1a26ed5c68fb98d4452ea1672398481841f/python/dgl/backend/pytorch/tensor.py#L343

As a result, previously shared tensors become unshared. I believe this is related to the UVA issues #3939 and #3961.
Because we convert the pytorch tensor to a NDArray, but out of place, and then pin the NDArray in place. The NDArray gets freed without being unpinned. PyTorch then re-uses this memory range from its pool, but it remains pinned in the CUDA driver.
See #3800.

## To Reproduce

This script shows the issue outside of DGL:
```
import torch
from torch import multiprocessing as mp

def val(i, x):
    print("{}: x contiguous? {}".format(i, x.is_contiguous()))
    print("{}: x shared? {}".format(i, x.is_shared()))
    print("{}: x ptr 0x{:x}".format(i, x.data_ptr()))
    y = x.contiguous()
    print("{}: y contiguous? {}".format(i, y.is_contiguous()))
    print("{}: y shared? {}".format(i, y.is_shared()))
    print("{}: y ptr 0x{:x}".format(i, y.data_ptr()))

def test():
    x = torch.empty([2,2,10,5], memory_format=torch.channels_last)
    print("is x contiguous? {}".format(x.is_contiguous()))
    mp.spawn(val, (x,), nprocs=2)

if __name__ == '__main__':
        test()
```
I think we either need to support non-contiguous NDArrays (a huge effort as many kernels in DGL would need to be re-written), or throw an error if we attempt to zerocopy a non-contiguous array, and tell the user to convert to .contiguous().

**Comment by jermainewang** [comment]
Can we throw an error only if a tensor needs to be pinned on our side but it is non-contiguous?

**Comment by nv-dlasalle** [comment]
While pinning a temporary tensor is one of the big effects of this issue, it effects other things. Because its not actually a zerocopy at this point, anytime DGL does modifying operation on a pytorch tensor it is potentially a bug here, since any modifications will be out of place, despite the in-place semantics of zerocopy.

**Comment by nv-dlasalle** [comment]
Basically, unless we specifically mark the tensor as read only in DGL, I think we have to reject non-contiguous tensors. Either way we would want to reject pinned and shared tensors that are non-contiguous.
