### ISSUE TITLE
[RFC] Revert graph reorder applied to builtin datasets

### ISSUE THREAD

**Issue by yzh119** [dmlc/dgl#3987]
## 🐛 Bug

#3102 applies node reorder to a set of built-in datasets. However, this might affect the training of several networks on these datasets.

For example, `dropout` is node order sensitive, when using the same random seed, training on the reordered graph would be different from training on the original graph. Such behavior is confusing when
1. user training a network written in an old version of dgl on the latest dgl, and cannot reproduce results even if fixing the random seed.
2. user try to align their implementation with other frameworks such as PyG.

## Suggestion
Remove the `reorder_graph` from `process` function of these datasets, and encourage users to call `reorder_graph` explicitly.

@Rhett-Ying @mufeili

**Comment by jermainewang** [comment]
How severe is the issue? Could you provide some data points?

**Comment by yzh119** [comment]
I don't have concrete data points, but some users experience reproducibility issues because of the change.

**Comment by hhr114** [comment]
> ## 🐛 Bug
> #3102 applies node reorder to a set of built-in datasets. However, this might affect the training of several networks on these datasets.
> 
> For example, `dropout` is node order sensitive, when using the same random seed, training on the reordered graph would be different from training on the original graph. Such behavior is confusing when
> 
> 1. user training a network written in an old version of dgl on the latest dgl, and cannot reproduce results even if fixing the random seed.
> 2. user try to align their implementation with other frameworks such as PyG.
> 
> ## Suggestion
> Remove the `reorder_graph` from `process` function of these datasets, and encourage users to call `reorder_graph` explicitly.
> 
> @Rhett-Ying @mufeili

At mufeili's invitation, I will fix this bug soon by adding an argument like reorder in these built-in datasets classes and setting it a default value of False. Once I finished, I will pull a request.

**Comment by jermainewang** [comment]
Fixed by #4104 which added a `reorder` flag to builtin datasets (default is False).
