### ISSUE TITLE
How can I use DGL in an NPU machine?

### ISSUE THREAD

**Issue by Miracle6** [dmlc/dgl#3991]
We have our pytorch version to use NPU, and we can use it just like ( tensor.to('npu') )

We want to use NPU in your DGL, But we find that maybe you just support these platforms.

<img width="218" alt="Snipaste_2022-05-10_21-29-59" src="https://user-images.githubusercontent.com/61740563/167640391-4cc049a8-14b8-4498-899a-c6ac2ac0fc25.png">

Could you tell how can I change the code for me to use it in NPU. Thank you! (We mainly want to run it for Hilander)

**Comment by jermainewang** [comment]
Does NPU require new kernel implementations? Right now, DGL's low-level operators (e.g., spmm, sddmm for message passing) only support CPU and CUDA.
