### ISSUE TITLE
Can DGL support training with multiple machines each with multiple gpus?

### ISSUE THREAD

**Issue by Joeyzhouqihui** [dmlc/dgl#3995]
## ❓ Questions and Help

Before proceeding, please note that we recommend
using our discussion forum (https://discuss.dgl.ai) for
general questions. As a result, this issue will
likely be CLOSED shortly.

**Comment by jermainewang** [comment]
Hi, please take a look at our distributed training tutorials on docs.dgl.ai. For general questions, please use our discuss forum. Thanks!
