### ISSUE TITLE
pinsage example, why MLP isn't used?

### ISSUE THREAD

**Issue by fanaev** [dmlc/dgl#4001]
Hello! I'm interested why you didn't use MLP layer as in the Paper? Thanks

**Comment by BarclayII** [comment]
You could replace the dot product with an MLP layer; it's entirely customizable.  I chose dot product simply because I was working on a different dataset and dot product gave a better result than MLP.

**Comment by kontrabas380** [comment]
> Hello! I'm interested why you didn't use MLP layer as in the Paper? Thanks

Have you tried implementing MLP layer?

**Comment by fanaev** [comment]
> > Hello! I'm interested why you didn't use MLP layer as in the Paper? Thanks
> 
> @fanaev, have you tried implementing MLP layer?

No, I haven't. The Dataset, which I was working with, doesn't contain label column. So I preferred to use dot product
