### ISSUE TITLE
Apply Edges for Edges with features

### ISSUE THREAD

**Issue by zohairhadi** [dmlc/dgl#4007]
## 🚀 Feature
I want to use edges which have a feature set. Currently the apply_edges(). function does not cater to edge features.

## Motivation
I am trying to use a scene graph for edge classification problem which has edge features. To create an edge classification GNN, I need a GNN layer to classify edges using its features.  That is why i need this functionality.

## Pitch

The apply_edges() function should have a optional parameter for taking in edge_features and use them in classification and prediction tasks.

**Comment by jermainewang** [comment]
You can save the edge features to `g.edata` and access them in `edges.data` in the UDF provided to `apply_edges`.
