### ISSUE TITLE
How to fix it when my OS tell me that " cannot import name 'DGLDataset' from 'dgl' (unknown location)"?

### ISSUE THREAD

**Issue by Kevin-shihello-world** [dmlc/dgl#4011]
I found my os issue me the warning of" cannot import name 'DGLDataset' from 'dgl' (unknown location)"but I have just downloaded it properly by pip(stable) according to the official sites, besides, the same thing happened before when I was trying to use CSVDataset. Someone told me I should reinstall it using conda but my terminal told me it can't, for kernel things. So what happened? I mean why does my conda fail to work while my pip serve is OK? And why DGL would be different installed by different install serves? Thank you,I'm quite eager to know the answer

**Comment by jermainewang** [comment]
Installing from pip or conda should not have any difference. Does the error happen when `import dgl`? Any reproducible code would be appreciated.
