### ISSUE TITLE
KeyError for rgcn-hetero Entity Classification w/ minibatch training

### ISSUE THREAD

**Issue by Eurus-Holmes** [dmlc/dgl#4013]
## 🐛 Bug

KeyError for rgcn-hetero Entity Classification w/ minibatch training

```
Traceback (most recent call last):
  File "entity_classify_mb.py", line 201, in <module>
    main(args)
  File "entity_classify_mb.py", line 154, in main
    g, args.batch_size, 'cuda' if use_cuda else 'cpu', 0, node_embed)
  File "/content/dgl/examples/pytorch/rgcn-hetero/model.py", line 369, in inference
    y[k][output_nodes[k]] = h[k].cpu()
KeyError: 'Forschungsgebiete'
```

## To Reproduce

1. git clone https://github.com/dmlc/dgl
1. cd dgl/examples/pytorch/rgcn-hetero/
1. python entity_classify_mb.py -d aifb --testing --gpu 0 --fanout=8

## Expected behavior

AIFB: accuracy best=97.22% avg=94.44%
## Environment

pip install dgl-cu101 dglgo -f https://data.dgl.ai/wheels/repo.html

https://colab.research.google.com/drive/1jwhsebzMUDavSgdgzWkGzvDx-YWMFG4k?usp=sharing

 - DGL Version (e.g., 1.0): 
 - Backend Library & Version (e.g., PyTorch 0.4.1, MXNet/Gluon 1.3):
 - OS (e.g., Linux):
 - How you installed DGL (`conda`, `pip`, source):
 - Build command you used (if compiling from source):
 - Python version:
 - CUDA/cuDNN version (if applicable):
 - GPU models and configuration (e.g. V100):
 - Any other relevant information:

**Comment by mufeili** [comment]
I confirm the issue, which should be fixed in PR #4022.
