### ISSUE TITLE
QUESTION about GCN's back propagation?

### ISSUE THREAD

**Issue by Qksidmx** [dmlc/dgl#4021]
## ❓ Questions and Help

Hello:
     Recently, I started learning dgl and managed to run examples code, like gcn、graphsage.
     I konw that in forward propagation stage, the hidden features will be computed with learnable parameters W and  aggregated with neighbors' feature. And parameters W will be updated in backward propagation stage.
     But I wondered that will the hidden features be updated in backward propagation stage?  I try to search on the Google to find out , but got nothing.
     So, could someone tell me whether the  hidden features will be updated in backward propagation stage?

Thank you anyway!

**Comment by yzh119** [comment]
Of course the features would be updated, there is no difference between GNNs and other Deep Learning models.

**Comment by Qksidmx** [comment]
> 

thanks for your reply, but I still can't understand how the hidden features update in **GCN's backpropagation**, there is a simple NN's example. When we click `PLAY BACKPROPAGATE`, we can see that the hidden features(blue nodes) don't update.
This is a simple of traditional NN, I don't know the GNN backpropagation's strategy.
Could you give me some instance to explain how the  hidden features update in GCN's
Thank you!

**Comment by yzh119** [comment]
The only difference between back propagation between GNN and other Deep Neural Networks is that we are dealing with sparse matrices.

For example, for the operator $Y=AX$, where $A$ is the sparse matrix, the corresponding backward function should be $\nable X = A \nabla Y$.

For the generalized form, you should check https://github.com/dmlc/dgl/blob/3fe5eea791b84280513bcb495aa7c4e1bd0fad9d/python/dgl/backend/pytorch/sparse.py#L122-L193 and the section 3 of [DGL paper](https://arxiv.org/pdf/1909.01315.pdf).
