### ISSUE TITLE
AtomicAdd is not implemented correctly for old architectures

### ISSUE THREAD

**Issue by nv-dlasalle** [dmlc/dgl#4031]
## 🐛 Bug

For double if arch < 60 and for half < 70, it is just implemented as (https://github.com/dmlc/dgl/blob/master/src/array/cuda/atomic.cuh#L227):
```
  return *addr + val;
```
But we should be using atomicCAS to implement such things when not hardware supported (from the CUDA docs https://docs.nvidia.com/cuda/cuda-c-programming-guide/index.html#atomic-functions):
```
#if __CUDA_ARCH__ < 600
__device__ double atomicAdd(double* address, double val)
{
    unsigned long long int* address_as_ull =
                              (unsigned long long int*)address;
    unsigned long long int old = *address_as_ull, assumed;

    do {
        assumed = old;
        old = atomicCAS(address_as_ull, assumed,
                        __double_as_longlong(val +
                               __longlong_as_double(assumed)));

    // Note: uses integer comparison to avoid hang in case of NaN (since NaN != NaN)
    } while (assumed != old);

    return __longlong_as_double(old);
}
#endif
```

**Comment by nv-dlasalle** [comment]
It looks like min/max operators are similarly broken: https://github.com/dmlc/dgl/blob/master/src/array/cuda/fp16.cuh#L15

**Comment by mufeili** [comment]
Nice catch! Could you help fix this issue?

**Comment by ndickson-nvidia** [comment]
PR #4079 should hopefully have fixed the cases that are possible to fix.  `AtomicAdd<half>` for architectures before 70 won't be atomic, since there's no 16-bit `atomicCAS` support on the older GPUs, but the other functions should be fixed.

**Comment by jermainewang** [comment]
@ndickson-nvidia Do you think we should resolve this issue?

**Comment by ndickson-nvidia** [comment]
@jermainewang I think it's probably as fixed as it can be.  @nv-dlasalle suggested the possibility of raising an error if the FP16 one gets run on old hardware, though I suppose there may be cases where atomicity isn't strictly needed that happen to hit the codepath and it'd be unfortunate if those error out, but maybe there are no cases like that.  Maybe there's a way to warn on the first time encountering it?  Any thoughts?

**Comment by nv-dlasalle** [comment]
I think we still need to fix these non-atomic cases. If AtomicAdd is used, it should be assumed strict atomicity is required. While I think we could implement the 16-bit CAS operations via 32-bit CAS operations (checking the 16 bits being added to, and the 16 bits not being modified), the performance will almost definitely be worse than full precision. I'd rather just have an assert(false) with a printf notifying the user that half precision atomics are not supported on the current hardware. in those code paths.

So I'd vote as to keeping this issue open until those parts of the code are fixed.

**Comment by jermainewang** [comment]
+1 on @nv-dlasalle 's suggestion.
