### ISSUE TITLE
DGL built from source with mixed precision  get the following errors

### ISSUE THREAD

**Issue by bluseking** [dmlc/dgl#4032]
CMake Error: Files to be generated by multiple different commands: "/home/hwl/dgl/build/CMakeFiles/dgl.dir/src/array/cuda/uvm/dgl_generated_array_index_select_uvm.cu.o.cmake

Are there any software incompatibilities?
cmake version 3.10.2
gcc version 7.5.0

**Comment by mufeili** [comment]
Have you encountered this issue before? @ndickson-nvidia

**Comment by TristonC** [comment]
@bluseking  Does "with mixed precision" in your description mean build the DGL with USE_FP16=ON?  Could you share a little more of your error log? We have build the DGL with USE_FP16 ON without the issue your encountered.

**Comment by ndickson-nvidia** [comment]
As far as I know, I've never encountered this before, @mufeili .  It's a bit difficult to guess what might be going on from the limited information provided, though CMake 3.10.2 is from quite a while ago, so it could be a factor.  I'm using CMake 3.22.1 and GCC 9.4.0.  The CUDA version might or might not also be relevant, (I don't know).  I'm using CUDA 11.6.

**Comment by TristonC** [comment]
@bluseking Have you made any progress for your build? Let us know if you need any help.

**Comment by BarclayII** [comment]
CUDA FP16 support will be added in 0.9.
