### ISSUE TITLE
`update_all` is failing on TUDataset DBLP_v1

### ISSUE THREAD

**Issue by romainfd** [dmlc/dgl#4039]
## 🐛 Bug

`update_all` is failing on TUDataset DBLP_v1

## To Reproduce

```python
import dgl

dataset = dgl.data.TUDataset('DBLP_v1')
print(dataset[0])  # can see edges have 'edge_labels': Scheme(shape=(1,), dtype=torch.int64)
for g, i in dataset:
    g.ndata['attr'] = g.ndata['node_labels']
    g.update_all(fn.copy_edge('edge_labels', 'm'), fn.sum('m', 'h'))
```

Fails on a weird error `DGLError: [20:27:03] /opt/dgl/src/array/kernel.cc:38: Check failed: (out->dtype).code == kDLFloat (`

## Expected behavior

I expect the last line (`g.update_all(fn.copy_edge('edge_labels', 'm'), fn.sum('m', 'h'))`) to do an average of incoming edges `edge_labels` values on each node.

## Environment

 - DGL Version (e.g., 1.0): 0.6.1
 - Backend Library & Version (e.g., PyTorch 0.4.1, MXNet/Gluon 1.3): torch 1.10.2
 - OS (e.g., Linux): tested on several setups (AWS SageMaker, Google Colab, my Apple M1 laptop)
 - How you installed DGL (`conda`, `pip`, source): pip
 - Build command you used (if compiling from source):
 - Python version: 3.7
 - CUDA/cuDNN version (if applicable):
 - GPU models and configuration (e.g. V100):
 - Any other relevant information:

## Additional context

Thanks for all the work on DGL! Really cool framework!

**Comment by mufeili** [comment]
You need to first perform `g.ndata['node_labels'].float()`. `update_all` only supports FloatTensors.

**Comment by romainfd** [comment]
The fix was more precisely on the edges (`g.edata['edge_labels'] = g.edata['edge_labels'].float()`) but the `FloatTensor` support was the key element, thank you!
