### ISSUE TITLE
QUESTION: Empty Data Field of  DGLGraph in CSR/CSC Sparse Format 

### ISSUE THREAD

**Issue by initzhang** [dmlc/dgl#4041]
Hi, I know that `indices` and `indptr` field are stored for CSR format in DGL, but it seems that the `data` field is sometimes missing for some reasons? 

https://github.com/dmlc/dgl/blob/7b9afbfa28e9441fd3bfbe4e3c24eb62816cb1a7/src/array/cuda/spmat_op_impl_csr.cu#L208-L211

I am wondering when does DGL store the `data` field and when not, and can users manually control this? thank you!

**Comment by yzh119** [comment]
The three sparse representations (COO/CSR/CSC) in DGL don't contain the `data` field.
If users want to specify something such as edge weight, they should use the `edata` field of the `DGLGraph` class, which was stored separately (not tied to sparse format).

**Comment by yaox12** [comment]
According to this comment:
https://github.com/dmlc/dgl/blob/744896e2d8ff802420f9e89e52d5d73a736275d6/src/array/cpu/spmat_op_impl_coo.cc#L378-L384
Most of the time, CSR matrices contain a `data` field. If it's missing, it's assumed to be from 0 to NNZ - 1.

**Comment by initzhang** [comment]
Hi yzh119, Thanks for your reply!

Then I have a following up question about the storage of DGLGraph Instance. I use the Reddit dataset as an example:

```python
# load original graph
from dgl.data import RedditDataset
data = RedditDataset(self_loop=True)
g = data[0]

# pop all features
g.ndata.clear()
g.edata.clear()

# specify formats and idtype
g = g.formats('csc').int()
print(g)
```
The output is as follows:
```
# output 
Graph(num_nodes=232965, num_edges=114848857,
      ndata_schemes={}
      edata_schemes={})
```

So the generated graph has `232965` nodes and `114848857 ` edges with `idtype=int32` in format `csc`. From my understanding, the `csc` graph without `data` field takes `(#edges + #nodes + 1)*sizeof(int32)` bytes storage, (if no more extra data is stored.)

**However**, using `dgl.save_graphs('path.bin',[g])`, I found that it generates approximately `(2*#edges + #nodes + 1)*sizeof(int32)` bytes object. Does DGLGraph have other information or data to store? Thank you!

**Comment by yzh119** [comment]
@initzhang If the graph is created from coo, then we need to record the original edge index of each element in the CSR/CSC format, resulting in the external overhead.

**Comment by initzhang** [comment]
Hi @yzh119, got it, thank you!

Is it possible to **directly** create a DGLGraph in `csc`/`csr` format **without** storing the original edge index? it seems that current graph creating apis all use coo (for example, [`from_scipy`](https://docs.dgl.ai/en/0.6.x/_modules/dgl/convert.html#from_scipy) will first call `scipy.sparse.spmatrix.tocoo` even if you pass in a csr scipy mat, and `dgl.graph ` only takes arguments in coo format).

Actually I am dealing with a memory-constrained problem, and I want to get rid of the original edge index to save memory footprint.

**Comment by yzh119** [comment]
I agree that the edge index could be stored separately in `edata`. (if your model uses some edge weight, then this field is required for back-propagation).
@jermainewang @BarclayII @Rhett-Ying WDYT?

**Comment by initzhang** [comment]
Hi @yaox12 , thanks for your reply! 
From the pointed comments, it seems that the `data` field of CSR actually stores some kind of "default" edge index?

**Comment by BarclayII** [comment]
> Is it possible to **directly** create a DGLGraph in `csc`/`csr` format **without** storing the original edge index?

It is possible.  `dgl.graph()` and `dgl.heterograph()` supports specifying CSR/CSC tensors with the following format (see https://docs.dgl.ai/generated/dgl.graph.html#dgl.graph):
```python
g = dgl.graph(('csr', (indptr, indices, eids)))   # or 'csc'
```
where `eids` could be an empty tensor assuming the edge IDs are consecutive integers starting from 0.

**Comment by initzhang** [comment]
Hi @BarclayII , thanks for reply!
Sorry I forgot to check the latest version of DGL, the latest `dgl.graph` solves the problem, thank you!
