### ISSUE TITLE
Calling in_edges on a graph with zero destination nodes and non-empty node ID tensor kills the program

### ISSUE THREAD

**Issue by PiggerZZM** [dmlc/dgl#4047]
## 🐛 Bug

I am trying to remove some edges in a block when using NodeDataLoader. When some edges don't exist in the block, the code throw an OSError

I write a toy example code for reproducing this problem

## To Reproduce

```
import dgl
import torch

if __name__ == '__main__':
    click = ("user", "click", "item")
    clicked = ("item", "clicked", "user")
    het_graph = dgl.heterograph({
        click: ([0, 1], [0, 0]),
        clicked: ((), ()),
    })

    sampler = dgl.dataloading.MultiLayerFullNeighborSampler(1)
    dataloader = dgl.dataloading.NodeDataLoader(
        het_graph, {"item": het_graph.nodes("item")}, sampler,
        batch_size=1,
        shuffle=True,
        drop_last=False,
        num_workers=0,
    )
    for input_nodes, output_nodes, blocks in dataloader:

        g = blocks[-1]

        nids_to_drop = torch.tensor([0])

        clicked_eids_to_remove = g.in_edges(nids_to_drop, form="eid", etype="clicked")
        g.remove_edges(clicked_eids_to_remove, etype="clicked")
```

Using backend: pytorch
Traceback (most recent call last):
  File "E:/codes/python/GNNRec/src/test/bug.py", line 26, in <module>
    clicked_eids_to_remove = g.in_edges(nids_to_drop, form="eid", etype="clicked")
  File "D:\Anaconda3\envs\pytorchzzm\lib\site-packages\dgl\heterograph.py", line 3241, in in_edges
    src, dst, eid = self._graph.in_edges(self.get_etype_id(etype), v)
  File "D:\Anaconda3\envs\pytorchzzm\lib\site-packages\dgl\heterograph_index.py", line 493, in in_edges
    edge_array = _CAPI_DGLHeteroInEdges_2(self, int(etype), F.to_dgl_nd(v))
  File "D:\Anaconda3\envs\pytorchzzm\lib\site-packages\dgl\_ffi\_ctypes\function.py", line 188, in __call__
    check_call(_LIB.DGLFuncCall(
OSError: [WinError -529697949] Windows Error 0xe06d7363

Process finished with exit code 1

## Environment

 - DGL Version (e.g., 1.0): 0.7
 - Backend Library & Version (e.g., PyTorch 0.4.1, MXNet/Gluon 1.3): PyTorch 1.10
 - OS (e.g., Linux): Windows
 - How you installed DGL (`conda`, `pip`, source): conda
 - Build command you used (if compiling from source):
 - Python version: 3.8
 - CUDA/cuDNN version (if applicable): 10.2
 - GPU models and configuration (e.g. V100): GTX950
 - Any other relevant information:

**Comment by BarclayII** [comment]
The issue is that there is actually no user node on the destination side in your generated `g`:
```
Block(num_src_nodes={'item': 1, 'user': 2},
      num_dst_nodes={'item': 1, 'user': 0},
      num_edges={('item', 'clicked', 'user'): 0, ('user', 'click', 'item'): 2},
      metagraph=[('item', 'user', 'clicked'), ('user', 'item', 'click')])
```

**Comment by PiggerZZM** [comment]
For some purpose, I want to remove some incoming edges associated with "user" nodes. I can't make sure whether any "user" nodes exist in the block because I use NodeDataLoader to sample "user" nodes and "item" nodes at the same time.

I also want to remove some outgoing edges. However, it didn't raise an error when I use the `out_edges()` method

**Comment by PiggerZZM** [comment]
Thank you for answering my question. All I want to do is to remove some edges in the block instead of the original graph. 

What do you mean by "This is because the block is a directed bipartite graph where the user IDs sampled on the source side and the destination side are different, and the node IDs taken by in_edges should be on destination side."?

What happens calling `g.in_edges([0])` when g is a directed bipartite graph? Does it find the incoming edges associated with dstnode whose id is 0?

**Comment by BarclayII** [comment]
> What happens calling `g.in_edges([0])` when g is a directed bipartite graph? Does it find the incoming edges associated with dstnode whose id is 0?

Yes, but associated with `dstnode` whose ID is 0 *in the block*, which does not necessarily correspond to ID 0 in the original graph.  Is that what you want (i.e. removing the incoming edges to first destination node in the block)?

> What do you mean by "This is because the block is a directed bipartite graph where the user IDs sampled on the source side and the destination side are different, and the node IDs taken by in_edges should be on destination side."?

I meant to explain why you need to use `dstnodes` in this statement
```python
actual_uids = g.dstnodes['user'].data[dgl.NID].numpy()   # or change 'user' to 'item'
```
in case you want to remove incoming edges to the nodes corresponding to user ID 0 in the original graph.  If the answer to the question above is yes then you can ignore this.

**Comment by PiggerZZM** [comment]
> Yes, but associated with dstnode whose ID is 0 in the block, which does not necessarily correspond to ID 0 in the original graph. Is that what you want (i.e. removing the incoming edges to first destination node in the block)?

**I misunderstood the meaning of calling `g.in_edges([0])` when g is a directed bipartite graph.**
I expected it will remove the incoming edges to the first node no matter whether this node is on the source side or destination side just like calling it when `g` is a homogeneous graph or a heterogeneous graph.
It seems that my misunderstanding helps to find a bug. ^_^

Now I know how to fix the problem in my situation. Thank you so much!!!
