### ISSUE TITLE
Using dgl in a c++ project.

### ISSUE THREAD

**Issue by vicky1999** [dmlc/dgl#4065]
## ❓ Questions and Help

Hi,
I need to create a GNN model with libtorch in C++.  I have used the dgl library to create the same model in python.

I am checking if there is any way to use the dgl library in c++.  If so, please let me know if there are any sample implementations or examples.

Thanks

**Comment by jermainewang** [comment]
Hi, currently you need to build your code against DGL's source tree. However, please note that many DGL components (e.g., `DGLGraph`, NN modules, etc.) are Python only.
