### ISSUE TITLE
Remove requirement for known device at instantiation time

### ISSUE THREAD

**Issue by kkranen** [dmlc/dgl#4069]
## 🚀 Feature
Remove the requirement for components, like DGLNodeEmbedding, to have device known at instantiation time.

## Motivation
Oftentimes, when building models declaratively, the distributed state will not have yet been initialized, and thus the device on which to output the output of the layer is not known yet. Thus, components like DGLNodeEmbedding cannot be used in a declarative framework unless wrappers are made for them to defer the actual creation of the embedding until the model is in a process. 

## Alternatives

A defined API to wrap components like DGLNodeEmbedding to defer their instantiation until device is known.

## Pitch

Re-implement DGL objects with output_device or device in their initialization arguments to defer device inference until the object has been moved inside of a process. In order to support model-parallel, we should allow an optional argument to these objects akin to a policy, that dictates which portion of the model-parallel component should be stored on which device.

## Additional context

None

**Comment by Rhett-Ying** [comment]
could you share an example of current usage and expected usage?
