### ISSUE TITLE
Subgraphs' dstdata appears to be not reflected on original graph

### ISSUE THREAD

**Issue by Elnifio** [dmlc/dgl#4075]
## Summary

When operating on `block`, we encountered these two issues: 

#### Destination Node Data Not Available Within Graph Block

When we tried to assign variables to `srcdata` and `dstdata`, it appeared that the `srcdata` is assigned correctly but the `dstdata` was not. Specifically, the code below performs: 

1. within each subgraph of the block, assign matrices `A` to srcdata, and assign matrices `B` to dstdata
2. Then, try to access the matrices outside of the subgraph scope

From the output below, we can see that each matrices are assigned correctly within each iteration of subgraph, but **graph.dstdata["B"] is not available (empty dictionary) when we tried to print it out outside of the subgraph iteration**. 

#### Function multi_update_all Not Setting the New Attributes to Destination Nodes

We're currently expecting that `multi_update_all` function to be first calculating the message, then aggregate the result over all source nodes and incoming edges, and finally *assigns the result to the destination node*. 

However, from the code below, we see that the `multi_update_all` do not assign the attributes to destination nodes. Specifically, we tried to print out the `graph.ndata.keys()`, and the assigned attribute is not listed.

### Dependencies

```python
import dgl
import torch
import random
```

```python
dgl.__version__
```

    >>> '0.8.0post2'

### Test Graph Generation

The graph (block sampled from a larger graph) with issue is generated as follow: 
- Types of nodes are: `u`, `v`
- Types of edges are: `(u, e1, v)`, `(v, e2, u)`

```python
n_rel1 = 1000
n_rel2 = 500
u = 'u'
v = 'v'
e1 = 'e1'
e2 = 'e2'

edge1 = list(range(n_rel1))
edge2 = list(range(n_rel1))
edge3 = list(range(n_rel2))
edge4 = list(range(n_rel2))
random.shuffle(edge1)
random.shuffle(edge2)
random.shuffle(edge3)
random.shuffle(edge4)
edge1 = edge1 + [n_rel1]
edge2 = [n_rel1] + edge2
edge3 = edge3 + [n_rel2]
edge4 = [n_rel2] + edge4

g = dgl.heterograph({
    ('u', 'e1', 'v'): (edge1, edge2),
    ('v', 'e2', 'u'): (edge3, edge4)
})

sampler = dgl.dataloading.MultiLayerFullNeighborSampler(1)
sampler = dgl.dataloading.as_edge_prediction_sampler(sampler)
train_seeds = {canonical_etype: torch.arange(g.num_edges(canonical_etype[1]), dtype=torch.int64).to(torch.device('cuda')) for canonical_etype in g.canonical_etypes} 
dataloader = dgl.dataloading.DataLoader(
    g, train_seeds, sampler, use_uva=True, batch_size=16
)
_, _, blocks = next(iter(dataloader))
b = blocks[0]

# assigns the graph's edge data by a prime number
for zipped, prime in zip(b.canonical_etypes, [2, 3]):
    src, edge, dst = zipped
    b[src, edge, dst].edata['C'] = torch.ones(b[src, edge, dst].num_edges()).to("cuda:0") * prime
    
b
```

    >>> Block(num_src_nodes={'u': 16, 'v': 28},
    ...       num_dst_nodes={'u': 16, 'v': 16},
    ...       num_edges={('u', 'e1', 'v'): 16, ('v', 'e2', 'u'): 12},
    ...       metagraph=[('u', 'v', 'e1'), ('v', 'u', 'e2')])

#### Bug Description

From the output in cell 5/6 below, the `torch.ones` vector is available within the subgraph, but the data is not available at graph level. 

The graph's keys are the same before and after the `multi_update_all` function call, as shown in cell 7 & cell 10. **However, though the new key is not available on the graph level, it is available on each of the subgraphs.**

The argument passed in is of form `edge name -> (message function, reduce function)`, as shown in cell 8.

```python
# Cell 4
# assigns the subgraph's destination data "B" as a list of ones times a prime number for all of the subgraphs
# assigns the subgraph's source data "A" as a list of ones times a prime number for all of the subgraphs

b[u, e1, v].dstdata['B'] = torch.ones(b[u, e1, v].num_dst_nodes()).to("cuda:0") * 11
b[v, e2, u].dstdata['B'] = torch.ones(b[v, e2, u].num_dst_nodes()).to("cuda:0") * 7
b[u, e1, v].srcdata['A'] = torch.ones(b[u, e1, v].num_src_nodes()).to("cuda:0") * 5
b[v, e2, u].srcdata['A'] = torch.ones(b[v, e2, u].num_src_nodes()).to("cuda:0") * 13
```

```python
# Cell 5
# tries to print out the keys for node data
print("Entire graph's node data keys:", b.ndata.keys())          # No key 'B' here
print("Subgraph e1's node data keys:", b[u, e1, v].ndata.keys()) # key 'B' is present here
print("Subgraph e2's node data keys:", b[v, e2, u].ndata.keys()) # key 'B' is present here
```

    >>> Entire graph's node data keys: dict_keys(['_ID', 'A'])
    >>> Subgraph e1's node data keys: dict_keys(['_ID', 'A', 'B'])
    >>> Subgraph e2's node data keys: dict_keys(['_ID', 'A', 'B'])

```python
# Cell 6
# tries to access the data "B"
print("Access the subgraph e1's B attribute:", {x: y.shape for x, y in b[u, e1, v].ndata['B'].items()})
print("Access the subgraph e2's B attribute:", {x: y.shape for x, y in b[v, e2, u].ndata['B'].items()})
print("Access the entire graph's B attribute:", b.ndata['B'])
```

    >>> Access the subgraph e1's B attribute: {'v': torch.Size([16])}
    >>> Access the subgraph e2's B attribute: {'u': torch.Size([16])}
    >>> Access the entire graph's B attribute: {}

```python
# Cell 7
# log the graph's status before multi_update_all
print("Entire graph's node data keys:", b.ndata.keys())
print("Subgraph e1's node data keys:", b[u, e1, v].ndata.keys())
print("Subgraph e2's node data keys:", b[v, e2, u].ndata.keys())
print("----------------")
print("Entire graph's edge data keys:", b.edata.keys())
print("Subgraph e1's edge data keys:", b[u, e1, v].edata.keys())
print("Subgraph e2's edge data keys:", b[v, e2, u].edata.keys())
```

    >>> Entire graph's node data keys: dict_keys(['_ID', 'A'])
    >>> Subgraph e1's node data keys: dict_keys(['_ID', 'A', 'B'])
    >>> Subgraph e2's node data keys: dict_keys(['_ID', 'A', 'B'])
    >>> ----------------
    >>> Entire graph's edge data keys: dict_keys(['_ID', 'C'])
    >>> Subgraph e1's edge data keys: dict_keys(['_ID', 'C'])
    >>> Subgraph e2's edge data keys: dict_keys(['_ID', 'C'])

```python
# Cell 8
# defines the argument for multi_update_all
# performs the operation:
# for (u, e1, v) relation:
#     e1.temp := u.A * e1.C
#     v.D := sum(e1.temp)
# for (v, e2, u) relation:
#     e2.temp := v.A * e2.C
#     u.D := sum(e2.temp)

argument = {
    edge: (dgl.function.u_mul_e(f"A", "C", "temp"), dgl.function.sum("temp", "D"))
    for _, edge, _ in b.canonical_etypes
}
```

```python
# Cell 9
# cross-edge reducer: sum
b.multi_update_all(argument, "sum")
```

```python
# Cell 10
# log the graph's status after multi_update_all
print("Entire graph's node data keys:", b.ndata.keys())          # D key is absent here
print("Subgraph e1's node data keys:", b[u, e1, v].ndata.keys()) # NOTICE here that the subgraph now contains the key 'D'
print("Subgraph e2's node data keys:", b[v, e2, u].ndata.keys()) # NOTICE here that the subgraph now contains the key 'D'
print("----------------")                                        # we do not expect the new attribute to be updated on edge, so the edge's keys behave correctly
print("Entire graph's edge data keys:", b.edata.keys())
print("Subgraph e1's edge data keys:", b[u, e1, v].edata.keys())
print("Subgraph e2's edge data keys:", b[v, e2, u].edata.keys())
```

    >>> Entire graph's node data keys: dict_keys(['_ID', 'A'])
    >>> Subgraph e1's node data keys: dict_keys(['_ID', 'A', 'B', 'D'])
    >>> Subgraph e2's node data keys: dict_keys(['_ID', 'A', 'B', 'D'])
    >>> ----------------
    >>> Entire graph's edge data keys: dict_keys(['_ID', 'C'])
    >>> Subgraph e1's edge data keys: dict_keys(['_ID', 'C'])
    >>> Subgraph e2's edge data keys: dict_keys(['_ID', 'C'])

**Comment by Rhett-Ying** [comment]
Because `b.ndata` equals `b.srcdata` in your case as `b.ntypes` includes and only includes `b.srctypes`. Please refer to https://github.com/dmlc/dgl/blob/a3ea4873d343d8876d961621ca3bfb889ec78501/python/dgl/heterograph.py#L1187.

**Comment by jermainewang** [comment]
Calling `ndata` on a `DGLBlock` is inherently ambiguous because `DGLBlock` has two sets of nodes (e.g., `src` and `dst`). Our implementation points `ndata` to `srcdata`. Since `update_all` saves results to `dstdata`, that's why you cannot find them in `ndata`. The rule of thumb is to avoid `ndata` for bipartite graph.

**Comment by Elnifio** [comment]
### Update

Both data are available within `b.dstdata` after an inspection into the block, thanks @jermainewang! 

However, it appears that there is some sort of discrepancies between the behavior of full graph vs. blocks, since the data is available in `ndata` in the full graph, but not available in a sampled block. Is this the expected behavior? I suppose this is due to the fact that blocks are inherently assumed to be bipartite graphs, but there's no assumptions for full heterographs? 


```python
import dgl
import torch
import random
```


```python
dgl.__version__
```




    >>> '0.8.0post2'




```python
n_rel1 = 1000
n_rel2 = 500
u = 'u'
v = 'v'
e1 = 'e1'
e2 = 'e2'

edge1 = list(range(n_rel1))
edge2 = list(range(n_rel1))
edge3 = list(range(n_rel2))
edge4 = list(range(n_rel2))
random.shuffle(edge1)
random.shuffle(edge2)
random.shuffle(edge3)
random.shuffle(edge4)
edge1 = edge1 + [n_rel1]
edge2 = [n_rel1] + edge2
edge3 = edge3 + [n_rel2]
edge4 = [n_rel2] + edge4

g = dgl.heterograph({
    ('u', 'e1', 'v'): (edge1, edge2),
    ('v', 'e2', 'u'): (edge3, edge4)
})

# Assigns b directly as a heterograph
b = g.to("cuda:0")

# assigns the graph's edge data by a prime number
for zipped, prime in zip(b.canonical_etypes, [2, 3]):
    src, edge, dst = zipped
    b[src, edge, dst].edata['C'] = torch.ones(b[src, edge, dst].num_edges()).to("cuda:0") * prime
b
```




    >>> Graph(num_nodes={'u': 1001, 'v': 1001},
    ...       num_edges={('u', 'e1', 'v'): 1001, ('v', 'e2', 'u'): 501},
    ...       metagraph=[('u', 'v', 'e1'), ('v', 'u', 'e2')])




```python
# Cell 4
# assigns the subgraph's destination data "B" as a list of ones times a prime number for all of the subgraphs
# assigns the subgraph's source data "A" as a list of ones times a prime number for all of the subgraphs

b[u, e1, v].dstdata['B'] = torch.ones(b[u, e1, v].num_dst_nodes()).to("cuda:0") * 11
b[v, e2, u].dstdata['B'] = torch.ones(b[v, e2, u].num_dst_nodes()).to("cuda:0") * 7
b[u, e1, v].srcdata['A'] = torch.ones(b[u, e1, v].num_src_nodes()).to("cuda:0") * 5
b[v, e2, u].srcdata['A'] = torch.ones(b[v, e2, u].num_src_nodes()).to("cuda:0") * 13
```


```python
# Cell 5
# tries to print out the keys for node data
print("Entire graph's node data keys:", b.ndata.keys())          # key 'B' is present here
print("Subgraph e1's node data keys:", b[u, e1, v].ndata.keys()) # key 'B' is present here
print("Subgraph e2's node data keys:", b[v, e2, u].ndata.keys()) # key 'B' is present here
```

    >>> Entire graph's node data keys: dict_keys(['B', 'A'])
    >>> Subgraph e1's node data keys: dict_keys(['B', 'A'])
    >>> Subgraph e2's node data keys: dict_keys(['B', 'A'])



```python
# Cell 6
# tries to access the data "B"
print("Access the subgraph e1's B attribute:", {x: y.shape for x, y in b[u, e1, v].ndata['B'].items()})
print("Access the subgraph e2's B attribute:", {x: y.shape for x, y in b[v, e2, u].ndata['B'].items()})
print("Access the entire graph's B attribute:", {x: y.shape for x, y in b.ndata['B'].items()})
```

    >>> Access the subgraph e1's B attribute: {'u': torch.Size([1001]), 'v': torch.Size([1001])}
    >>> Access the subgraph e2's B attribute: {'v': torch.Size([1001]), 'u': torch.Size([1001])}
    >>> Access the entire graph's B attribute: {'u': torch.Size([1001]), 'v': torch.Size([1001])}

**Comment by jermainewang** [comment]
> However, it appears that there is some sort of discrepancies between the behavior of full graph vs. blocks, since the data is available in `ndata` in the full graph, but not available in a sampled block. Is this the expected behavior? I suppose this is due to the fact that blocks are inherently assumed to be bipartite graphs, but there's no assumptions for full heterographs?

I see what happens here. For `DGLBlock`, the src and dst node types can have the same name (in your case, there could be type `'u'` in both src and dst nodes), while general heterogeneous graph does not allow that (will raise error during graph construction). This further complicates the implementation of `ndata`, which both general heterograph and `DGLBlock` share. What happens is the feature dictionary of dst `'u'` overrides src `'u'`. I agree this is quite counter-intuitive. Let us think of how to improve it but right now, try to avoid calling `ndata` for `DGLBlock`.
