### ISSUE TITLE
[Doc] floating-point conversion functions are not included in the documentation

### ISSUE THREAD

**Issue by yaox12** [dmlc/dgl#4087]
## 📚 Documentation

Functions in `dgl.transforms.functional` are not included in the doc. Besides, floating-point conversion functions are not included in `__all__` and thus cannot be correctly imported.
https://github.com/dmlc/dgl/blob/eabcc58e41c0b94316f60ea74ba8bc5a7b0e2096/python/dgl/transforms/functional.py#L47

cc @mufeili @ndickson-nvidia

**Comment by ndickson-nvidia** [comment]
Thanks for catching this!  I don't know how to fix and test the docs part correctly, (maybe by adding another .rst file to docs/source/api/python and building the docs), but PR #4089 adds `to_half`, `to_float`, and `to_double` to `__all__` .

**Comment by mufeili** [comment]
`dgl.transforms.functional` is currently located at https://docs.dgl.ai/api/python/dgl.html#graph-transform-ops. I've discussed with @jermainewang about it before.

**Comment by yaox12** [comment]
@mufeili Thanks. So what we need to do is adding floating-point conversion functions to it as well. I think it should be docs/source/api/python/dgl.rst. cc @ndickson-nvidia

**Comment by jermainewang** [comment]
@ndickson-nvidia, what @yaox12 said is correct. The API docs are organized by their namespaces instead of their source file locations.

**Comment by yaox12** [comment]
@ndickson-nvidia These functions are imported in https://github.com/dmlc/dgl/blob/92e77330659fe0f5673c76b966aad727752cb7ef/python/dgl/transforms/__init__.py#L2 and can be called by `dgl.transforms.to_half()`. 
Then graph transform ops have their section under https://github.com/dmlc/dgl/blob/master/docs/source/api/python/dgl.rst#graph-transform-ops.

**Comment by ndickson-nvidia** [comment]
Thanks!  Should everything in `__all__` from dgl/transforms/functional.py be added to the list in dgl.rst?  Also, should they be in the same order?  (The ones there at the moment are in a different order than they appear in `__all__`.)  I can quickly fix up the list.  Anything else to add in there?

**Comment by ndickson-nvidia** [comment]
PR #4123 updates the list in dgl.rst to have the 18 functions from dgl.transforms.functional `__all__` that were missing before, and then sorts them all alphabetically, (in a separate commit so that it's easy to not sort if people don't want it sorted).
