### ISSUE TITLE
Question about the RPC of DistDGL

### ISSUE THREAD

**Issue by Ningsir** [dmlc/dgl#4091]
## ❓ Questions and Help

Why does DistDGL implement the RPC based on Tensorpipe instead of using the existing RPC framework(gRPC, bRPC, etc.) ?
Is the performance  better than the existing RPC?

**Comment by Rhett-Ying** [comment]
Because `TensorPipe` is tensor-aware and Pytorch RPC also relies on it.

We didn't try with gPRC, bRPC. Are there any advantages of gPRC, bRPC from your perspective?
