### ISSUE TITLE
Custom readout function

### ISSUE THREAD

**Issue by ysgncss** [dmlc/dgl#4097]
I am using RGCN for HeteroGraph classification. I use batch data for learning. When I export node features, can I get the features of each node of each graph? Despite the official define dgl.sum_ nodes(), dgl.mean_ nodes() and so on, but these readout operations cannot know the specific feature of each node.

**Comment by jermainewang** [comment]
You could use `dgl.unbatch` to get each graph in a list, and then get the node features from the `ndata` of each graph.
