### ISSUE TITLE
When will multi-gpu be supported?

### ISSUE THREAD

**Issue by DancingSoul** [dmlc/dgl#410]
## ❓ Questions and Help

Since my experiments are conducted on some large graphs, I want to know when will multi-gpu be supported?

Thanks a lot!

**Comment by yzh119** [comment]
multi-gpu is supported if you use pytorch as backend. We recommend you use `torch.distributed` rather than `DataParallel` to write your multi-gpu program.
You may find [this tutorial](https://pytorch.org/tutorials/intermediate/dist_tuto.html) useful.

**Comment by DancingSoul** [comment]
> multi-gpu is supported if you use pytorch as backend. We recommend you use `torch.distributed` rather than `DataParallel` to write your multi-gpu program.
> You may find [this tutorial](https://pytorch.org/tutorials/intermediate/dist_tuto.html) useful.

Thanks!
