### ISSUE TITLE
what happend when set the replace=False in NeighborSampler if the neighbors nums is less than sampling number that I set?

### ISSUE THREAD

**Issue by wangbingnan136** [dmlc/dgl#4106]
train_nodesampler = dgl.dataloading.NeighborSampler([1500,1000,1200])
If the neighbours number of a node is not enough and I set the replace=False,what will happend? Does it just sample all exist neighbours of the node?

**Comment by yaox12** [comment]
Yes, all the neighbors will be sampled.

**Comment by wangbingnan136** [comment]
> Yes, all the neighbors will be sampled.

Thanks a lot!
