### ISSUE TITLE
AttributeError: 'Column' object has no attribute `deferred_dtype`

### ISSUE THREAD

**Issue by mufeili** [dmlc/dgl#4107]
## 🐛 Bug

@ndickson-nvidia @BarclayII 

The introduction of `deferred_dtype` in PR #3890 seems to be causing issues when loading a graph file saved with an older version of DGL. Do you have any ideas on fixing the compatibility? We might also want to add a unit test for loading a graph data file saved with an older version of DGL.

![WechatIMG8012](https://user-images.githubusercontent.com/19576924/173212115-6cfe418c-6718-4cce-adbc-d06e193bb1c0.jpeg)

## Environment

 - DGL Version (e.g., 1.0): 0.8.2
 - Backend Library & Version (e.g., PyTorch 0.4.1, MXNet/Gluon 1.3):
 - OS (e.g., Linux):
 - How you installed DGL (`conda`, `pip`, source):
 - Build command you used (if compiling from source):
 - Python version:
 - CUDA/cuDNN version (if applicable):
 - GPU models and configuration (e.g. V100):
 - Any other relevant information:

**Comment by ndickson-nvidia** [comment]
Are there any plans to add a more robust system for saving/loading graph data?  Relying on just serializing Python objects, like what `dgl.data.utils.save_info` and `dgl.data.utils.load_info` do, seems like a risky approach that may not be able to support any sort of compatibility, especially since there's no version information.  I'd expect that a few data members of `Column`, for example, never need to be saved or loaded, since `device`, `index`, and `deferred_dtype` should be resolved and cleared before saving to disk, and there are probably other similar examples in other classes.

**Comment by Wxz666666** [comment]
博主，您这个问题怎么解决的

**Comment by Wxz666666** [comment]
Blogger, how did you solve this problem

**Comment by mufeili** [comment]
> Blogger, how did you solve this problem

For now, downgrading to `0.8.1` should address the issue.

**Comment by natalie-0430** [comment]
Hello, how can you downgrade to 0.8.1 from 0.8.2? I have a similar problem.

**Comment by nv-dlasalle** [comment]
@natalie-0430 That will depend on how you installed it. If you used pip for example:
```
pip uninstall dgl-cu113
pip install dgl-cu113==0.8.1 dglgo -f https://data.dgl.ai/wheels/repo.html
```

@mufeili What's your preferred fix for this? Should we add `hasattr` to check if the unpickled object has the new attribute, or should we override `__setstate__` (https://docs.python.org/3/library/pickle.html#object.__setstate__) to explicitly populate missing attributes from old versions?

**Comment by mufeili** [comment]
> @natalie-0430 That will depend on how you installed it. If you used pip for example:
> 
> ```
> pip uninstall dgl-cu113
> pip install dgl-cu113==0.8.1 dglgo -f https://data.dgl.ai/wheels/repo.html
> ```
> 
> @mufeili What's your preferred fix for this? Should we add `hasattr` to check if the unpickled object has the new attribute, or should we override `__setstate__` (https://docs.python.org/3/library/pickle.html#object.__setstate__) to explicitly populate missing attributes from old versions?

@jermainewang What do you think? Probably overriding `__setstate__` will be more general for future changes?

**Comment by jermainewang** [comment]
I vote for overriding `__setstate__` and `__getstate__`. Two other related questions:
* Shall we always make pickling/unpickling backward compatible? This may prevent us from making changes to `DGLGraph` and `Frame`.
* How to properly test pickling/unpickling? This is somewhat related to the question above.
