### ISSUE TITLE
PPI Test Set

### ISSUE THREAD

**Issue by rusty1s** [dmlc/dgl#411]
## 🐛 Bug

The `test_graph_id.npy` of the PPI dataset from https://s3.us-east-2.amazonaws.com/dgl.ai/dataset/ppi.zip has only 1 entry (136 byte), resulting in wrong test evaluation.

**Comment by jermainewang** [comment]
Thanks for the report. I confirm that there is only one test graph. @sufeidechabei could you have a look?

**Comment by sufeidechabei** [comment]
I have fixed that @jermainewang  @rusty1s , Thanks!

**Comment by rusty1s** [comment]
Can confirm, works like a charm :)
