### ISSUE TITLE
Shape inconsistency in dgl.nn.tensorflow.conv.GraphConv

### ISSUE THREAD

**Issue by jajupmochi** [dmlc/dgl#4112]
## To Reproduce

I am using the dgl.nn.tensorflow.conv.GraphConv class. When I set `in_feats=32`, `hidden_feats=8`, `weight=False` and `bias=True`, I got the following error:
```
File "/home/ljia/.local/lib/python3.8/site-packages/dgl/nn/tensorflow/conv/graphconv.py", line 291, in call
    rst = rst + self.bias

InvalidArgumentError: Exception encountered when calling layer "graph_conv" (type GraphConv).

Incompatible shapes: [45,32] vs. [8] [Op:AddV2]

Call arguments received:
  • graph=Graph(num_nodes=45, num_edges=129,
      ndata_schemes={'x': Scheme(shape=(32,), dtype=tf.float32), 'h': Scheme(shape=(32,), dtype=tf.float32)}
      edata_schemes={})
  • feat=tf.Tensor(shape=(45, 32), dtype=float32)
  • weight=None
```
It seems `self.bias` is set by
```
self.bias = tf.Variable(initial_value=zeroinit(
                shape=(out_feats), dtype='float32'), trainable=True) 
```
Thus has shape (8,), while `rst` has shape (45, 32), as it is not multiplied by the weight. I assume this is a bug, or am I doing it wrong? Thanks.

## Environment

 - DGL Version: 0.7.2
 - Backend Library & Version: Tensorflow 2.7.0
 - OS: Ubuntu 18.04.6 LTS
 - How you installed DGL: `pip`
 - Build command you used (if compiling from source): None
 - Python version: 3.8.5
 - CUDA/cuDNN version (if applicable): 11.3
 - GPU models and configuration (e.g. V100): This code is tested on CPU
 - Any other relevant information: None

**Comment by mufeili** [comment]
It seems that `GraphConv` of `PyTorch` backend also has this issue, what do you think? @BarclayII

**Comment by BarclayII** [comment]
> I guess the easiest fix will be setting `self._out_feats` to `in_feats` if `weight=False`.

Not necessarily.  People might feed in their own weight matrix in the forward function instead, which will give different size of output features.

I think this case falls in users specifying `weight=False`, `bias=True` *and* not providing custom weight matrix in the forward function.  In this case we should check if `self._out_feats` equals `self._in_feats`.

> When I set `in_feats=32`, `hidden_feats`, `weight=False` and `bias=True`, I got the following error:

@jajupmochi Are you setting `out_feats = 8` during initialization when this error is thrown?

**Comment by jajupmochi** [comment]
@BarclayII Yes.
