### ISSUE TITLE
Different behavior of the MultiLayerNeighborSampler when the graph has one node type and edge type and when the graph is heterogenous.

### ISSUE THREAD

**Issue by bioannidis** [dmlc/dgl#4115]
The block graph does not contain dst_node_types in the case where the graphs one node type and edge type, which requires a lot of custom code for writing a unified API. Can you please advice whether this is by design or not? 

https://github.com/dmlc/dgl/blob/92e77330659fe0f5673c76b966aad727752cb7ef/python/dgl/_dataloading/neighbor.py#L56

**Comment by bioannidis** [comment]
Also the dataloader we define needs to be different other wise the sampling will fail.

When the ntypes and etypes are 1 we need to give the tensor with node ids. Otherwise we need to give a dictionary with key the node id and values the node ids. This does not allow us to unify the interface. 

loader = dgl.dataloading.DistNodeDataLoader(g, train_idx
                                                    if len(g.etypes) == 1 and len(g.ntypes) == 1
                                                    else {predict_ntype: train_idx}, sampler,
                                                    batch_size=batch_size, shuffle=True, num_workers=0)

**Comment by jermainewang** [comment]
> When the ntypes and etypes are 1 we need to give the tensor with node ids. Otherwise we need to give a dictionary with key the node id and values the node ids. This does not allow us to unify the interface.

This is by design because DGL will not know which node type the `train_idx` belongs to. What's the ideal usage from your case?

**Comment by bioannidis** [comment]
By the way this is a distGraph and hence AttributeError: 'DistGraph' object has no attribute 'is_homogeneous'

**Comment by jermainewang** [comment]
> Ok thanks for this. I understand the need for the dictionary. The question is why it does not work with the dictionary when the graph is homogenous

I see. I think the issue should be with `DistDataLoader` / `DistGraph`. For normal `DataLoader`, we support such usage. Let me verify this once I got time.
