### ISSUE TITLE
[Bug] tests/pytorch/test_nn.py fails due to random graph sometimes having 0-in-degree

### ISSUE THREAD

**Issue by nv-dlasalle** [dmlc/dgl#4124]
## 🐛 Bug

The problem is we are generating the graph via:
```
g = dgl.rand_graph(num_nodes, num_edges)
```

But the GraphConv module `python/dgl/nn/pytorch/conv/graphconv.py:383`, prohibits 0-in-degree nodes.
```
dgl._ffi.base.DGLError: There are 0-in-degree nodes in the graph, output for those nodes will be invalid. This is harmful for some applications, causing silent performance regression. Adding self-loop on the input graph by calling `g = dgl.add_self_loop(g)` will resolve the issue. Setting ``allow_zero_in_degree`` to be `True` when constructing this module will suppress the check and let the code run.
```

This causes the CI to fail randomly.

This this Jenkins run: http://dgl-jenkins-eksvpc-2136217999.us-west-2.elb.amazonaws.com/blue/organizations/jenkins/dgl/detail/PR-4117/3/pipeline/558

**Comment by mufeili** [comment]
I guess it suffices to use a fixed graph without 0-in-degree nodes.
