### ISSUE TITLE
macOS compilation broken

### ISSUE THREAD

**Issue by apalha** [dmlc/dgl#4127]
## 🐛 Bug

With Xcode versions 13.1 and 13.4 and using clang following the [installation instructions](https://docs.dgl.ai/install/index.html#macos) fails to build dgl.

## To Reproduce

```
mkdir build
cd build
cmake -DUSE_OPENMP=off -DCMAKE_C_FLAGS='-DXBYAK_DONT_USE_MAP_JIT' -DCMAKE_CXX_FLAGS='-DXBYAK_DONT_USE_MAP_JIT' -DUSE_AVX=OFF -DUSE_LIBXSMM=OFF ..
make -j4
```

generates the following error:

```
Consolidate compiler generated dependencies of target dgl
[ 55%] Building CXX object CMakeFiles/dgl.dir/src/runtime/shared_mem.cc.o
[ 56%] Building CXX object CMakeFiles/dgl.dir/src/runtime/semaphore_wrapper.cc.o
[ 57%] Building CXX object CMakeFiles/dgl.dir/src/runtime/tensordispatch.cc.o
[ 57%] Building CXX object CMakeFiles/dgl.dir/src/runtime/system_lib_module.cc.o
/Users/apalha/work/libs/dgl/src/runtime/semaphore_wrapper.cc:45:3: warning: 'sem_init' is deprecated [-Wdeprecated-declarations]
  sem_init(&sem_, 0, 0);
  ^
/Library/Developer/CommandLineTools/SDKs/MacOSX12.1.sdk/usr/include/sys/semaphore.h:55:42: note: 'sem_init' has been explicitly marked deprecated here
int sem_init(sem_t *, int, unsigned int) __deprecated;
                                         ^
/Library/Developer/CommandLineTools/SDKs/MacOSX12.1.sdk/usr/include/sys/cdefs.h:204:40: note: expanded from macro '__deprecated'
#define __deprecated    __attribute__((__deprecated__))
                                       ^
/Users/apalha/work/libs/dgl/src/runtime/semaphore_wrapper.cc:73:17: error: use of undeclared identifier 'sem_timedwait'
  while ((ret = sem_timedwait(&sem_, &ts) != 0) && errno == EINTR) {
                ^
1 warning and 1 error generated.
make[2]: *** [CMakeFiles/dgl.dir/src/runtime/semaphore_wrapper.cc.o] Error 1
make[2]: *** Waiting for unfinished jobs....
make[1]: *** [CMakeFiles/dgl.dir/all] Error 2
make: *** [all] Error 2
```

After inspection, commit [cac3720b48dfe15fb3721d00624c2d18fec15680](https://github.com/dmlc/dgl/commit/cac3720b48dfe15fb3721d00624c2d18fec15680#diff-11eddbacdc1e79881f6ce3bd710d7f47d4ecd1f8f25ea53cea449dd1444f2d49) introduced the changes that cause the compilation to fail. Tag [0.8.2](https://github.com/dmlc/dgl/releases/tag/0.8.2) still works.

The reason for failing seems to be related to the use of `sem_timedwait`, which is no longer supported in macOS. See this [thread](https://stackoverflow.com/questions/641126/posix-semaphores-on-mac-os-x-sem-timedwait-alternative) for a discussion and possible solutions. 

## Expected behavior

Should build without errors.

## Environment

 - DGL Version (e.g., 1.0): latest commit, but any commit after [cac3720b48dfe15fb3721d00624c2d18fec15680](https://github.com/dmlc/dgl/commit/cac3720b48dfe15fb3721d00624c2d18fec15680#diff-11eddbacdc1e79881f6ce3bd710d7f47d4ecd1f8f25ea53cea449dd1444f2d49) should also fail
 - Backend Library & Version (e.g., PyTorch 0.4.1, MXNet/Gluon 1.3): PyTorch
 - OS (e.g., Linux): macOS 12.2.1
 - How you installed DGL (`conda`, `pip`, source): source
 - Build command you used (if compiling from source): followd [installation instructions](https://docs.dgl.ai/install/index.html#macos) 
 - Python version: 3.8.13
 - CUDA/cuDNN version (if applicable): not applicable
 - GPU models and configuration (e.g. V100): not applicable
 - Any other relevant information: as mentioned above, tried this with Xcode version 13.1 and 13.4 and both give the same error, reverting to commit tagged 0.8.2 solved the issue.

**Comment by mufeili** [comment]
Could you take a look? @Rhett-Ying

**Comment by Rhett-Ying** [comment]
thanks for reporting this. I will work on it.

**Comment by BarclayII** [comment]
Could you try building from master branch?  It should be fixed in #4168.

**Comment by apalha** [comment]
I will try it later today and I will get back to you.

**Comment by RecLusIve-F** [comment]
> Could you try building from master branch? It should be fixed in #4168.

[ 98%] Building CXX object CMakeFiles/dgl.dir/src/rpc/network/tcp_socket.cc.o
/Users/dgl/src/rpc/network/socket_pool.cc:12:10: fatal error: 'sys/epoll.h' file not found
#include <sys/epoll.h>
         ^~~~~~~~~~~~~
1 error generated.
make[2]: *** [CMakeFiles/dgl.dir/src/rpc/network/socket_pool.cc.o] Error 1

I'm now trying to build from the master branch on macOS, but there is a new error.

**Comment by apalha** [comment]
I got the same error as @RecLusIve-F:

```
[ 98%] Building CXX object CMakeFiles/dgl.dir/src/rpc/network/socket_pool.cc.o
/Users/apalha/work/temp/testing/dgl/src/rpc/network/socket_pool.cc:12:10: fatal error: 'sys/epoll.h' file not found
#include <sys/epoll.h>
         ^~~~~~~~~~~~~
1 error generated.
make[2]: *** [CMakeFiles/dgl.dir/src/rpc/network/socket_pool.cc.o] Error 1
make[1]: *** [CMakeFiles/dgl.dir/all] Error 2
make: *** [all] Error 2
```

This error is due to using epoll, which is available on linux but not on macOS: see [here](https://stackoverflow.com/questions/55591983/how-to-fix-fatal-error-sys-epoll-h-file-not-found-in-osx
).

In the discussion above one recommendation is to use libuv.

What I also check was the compile command that raises the error:

`/Applications/Xcode-13.4.app/Contents/Developer/Toolchains/XcodeDefault.xctoolchain/usr/bin/c++ -DDMLC_CORE_USE_CMAKE -DDMLC_USE_CXX11=1 -DDMLC_USE_CXX14=1 -DENABLE_PARTIAL_FRONTIER=0 -D__USE_XOPEN2K8 -Ddgl_EXPORTS -I/Users/apalha/work/temp/testing/dgl/include -I/Users/apalha/work/temp/testing/dgl/third_party/dlpack/include -I/Users/apalha/work/temp/testing/dgl/third_party/dmlc-core/include -I/Users/apalha/work/temp/testing/dgl/third_party/phmap -I/Users/apalha/work/temp/testing/dgl/third_party/xbyak -I/Users/apalha/work/temp/testing/dgl/third_party/METIS/include -I/Users/apalha/work/temp/testing/dgl/tensoradapter/include -I/Users/apalha/work/temp/testing/dgl/third_party/nanoflann/include -I/Users/apalha/work/temp/testing/dgl/third_party/libxsmm/include -I/Users/apalha/work/temp/testing/dgl/third_party/METIS/GKlib -I/Users/apalha/work/temp/testing/dgl/third_party/tensorpipe -I/Users/apalha/work/temp/testing/dgl/build/third_party/dmlc-core/include -I/Users/apalha/work/temp/testing/dgl/build/third_party/tensorpipe -I/Users/apalha/work/temp/testing/dgl/third_party/tensorpipe/third_party/libnop/include -O2 -Wall -fPIC -std=c++14 -DXBYAK_DONT_USE_MAP_JIT -DUSE_EPOLL -DIDXTYPEWIDTH=64 -DREALTYPEWIDTH=32 -arch arm64 -isysroot /Applications/Xcode-13.4.app/Contents/Developer/Platforms/MacOSX.platform/Developer/SDKs/MacOSX12.3.sdk -mmacosx-version-min=12.2 -fPIC -std=gnu++14 -MD -MT CMakeFiles/dgl.dir/src/rpc/network/socket_pool.cc.o -MF CMakeFiles/dgl.dir/src/rpc/network/socket_pool.cc.o.d -o CMakeFiles/dgl.dir/src/rpc/network/socket_pool.cc.o -c /Users/apalha/work/temp/testing/dgl/src/rpc/network/socket_pool.cc`

As you can see, there is a flag: `-DUSE_EPOLL`

I removed it and ran the compile command again and this command then compiles correctly.

**Comment by Rhett-Ying** [comment]
@apalha @RecLusIve-F  please have a try with latest mater branch...

**Comment by RecLusIve-F** [comment]
> @apalha @RecLusIve-F please have a try with latest mater branch...

There are no more errors now, thank you very much.
