### ISSUE TITLE
Expect argument "nodes["_N"]" to have data type torch.int32. But got torch.int64.

### ISSUE THREAD

**Issue by wkmyws** [dmlc/dgl#4132]
## To Reproduce

when i use SAGPool(200,ratio=0.8)(g,feats), error occurs.

DGLError: Expect argument "nodes["_N"]" to have data type torch.int32. But got torch.int64.

And I think bug is in  `dgl/subgraph.py/node_subgraph()`.

Line 140:
```
        nodes = {graph.ntypes[0]: nodes}
```
I change that:
```
        nodes=torch.tensor(nodes,dtype=torch.int32)
        nodes = {graph.ntypes[0]: nodes}
```
and then it work

## Environment

 - DGL Version (e.g., 1.0): 0.82
 - Backend Library & Version (e.g., PyTorch 0.4.1, MXNet/Gluon 1.3): pytorch
 - OS (e.g., Linux): windows
 - How you installed DGL (`conda`, `pip`, source): conda
 - Build command you used (if compiling from source):
 - Python version: 3.9
 - CUDA/cuDNN version (if applicable): 11
 - GPU models and configuration (e.g. V100):
 - Any other relevant information:

**Comment by wkmyws** [comment]
@mufeili 

https://github.com/dmlc/dgl/blob/35e66f426a95da5883d04ccc81b7cfa5fd677d57/python/dgl/subgraph.py

this file, line 137

**Comment by mufeili** [comment]
I think this is an expected behavior of `node_subgraph` and the fix should go to the example code. Could you help open a PR and fix the example code?
