### ISSUE TITLE
How can I upgrade DGL?

### ISSUE THREAD

**Issue by hbsun2113** [dmlc/dgl#414]
I installed DGL by  `conda install -c dglteam dgl`.
If you have already fixed the bug of DGL and then I want to update DGL. What should I do?

**Comment by mufeili** [comment]
You can always install from source for the latest patches.

**Comment by VoVAllen** [comment]
I think this might be a problem. The current interval between releases is too long which might prevent new user to follow our new tutorial and have a try.
