### ISSUE TITLE
[BUG] AttributeError: module 'dgl.data' has no attribute 'CSVDataset

### ISSUE THREAD

**Issue by RafaWong** [dmlc/dgl#4144]
## 🐛 Bug

module 'dgl.data' has no attribute 'CSVDataset'

## To Reproduce

1. Pip installed "dgl='0.5.2', pytorch='1.5.1+cuda10.1'"
2. From the part "Dataset of multiple graphs" in "4.6 Loading data from CSV files" ( "https://docs.dgl.ai/guide/data-loadcsv.html"), downloaded "meta.yaml", "node.csv", "edge.csv", and "graphs.csv". Then put them into a folder "./mini_multi_dataset"
3. Run the code 
>>> import dgl
>>> dataset = dgl.data.CSVDataset('./mini_multi_dataset')
4. The bug is "AttributeError: module 'dgl.data' has no attribute 'CSVDataset'"

## Expected behavior

no extra behavior

## Environment

 - DGL Version: 0.5.2
 - Backend Library & Version: pytorch='1.5.1'
 - OS: Windows 10
 - How you installed DGL (`conda`) : conda install -c dglteam dgl-cuda10.1
 - Build command you used (if compiling from source): /
 - Python version: 3.6.5
 - CUDA/cuDNN version (if applicable): CUDA 10.1
 - GPU models and configuration (e.g. V100): /
 - Any other relevant information: /

**Comment by mufeili** [comment]
Could you upgrade DGL to the latest version?

**Comment by RafaWong** [comment]
> Could you upgrade DGL to the latest version (0.8.2)?

Thank you very much!

Since my operating system is Windows 10, so I can only update to the version 0.8.1. And then came along a new bug: **ModelMetaclass object argument after ** must be a mapping, not str**
in <module>    trainset = dgl.data.CSVDataset('./mini_multi_dataset')

Could you help me with this bug?

**Comment by RafaWong** [comment]
Thank you very much!




Since my operating system is Windows 10, so I can only update to the version 0.8.1. The former bug has been successfully resolved after the DGL upgrade.




And then came along a new bug: 

ModelMetaclass object argument after ** must be a mapping, not str

in trainset = dgl.data.CSVDataset('./mini_multi_dataset')




Attached is the demo that I took from DGL Doc. Could you help me with this bug?







RafaWong







At 2022-06-20 14:10:18, "Mufei Li" ***@***.***> wrote:

Could you upgrade DGL to the latest version (0.8.2)?

**Comment by mufeili** [comment]
@Rhett-Ying Could you take a look?

**Comment by Rhett-Ying** [comment]
@RafaWong could you provide more call stacks? could you make sure non-CSV dataset works as expected? such as `RedditDataset`.

**Comment by RafaWong** [comment]
> @RafaWong could you provide more call stacks? could you make sure non-CSV dataset works as expected? such as `RedditDataset`.

Thanks! I failed to understand the input format of "meta.yaml". This bug has been resolved!
