### ISSUE TITLE
PicklingError when using DGP-Go

### ISSUE THREAD

**Issue by wanhanbo** [dmlc/dgl#4146]
## 🐛 Bug

When I try to use DGP-Go to reproduce the [tutorial](https://github.com/dmlc/dgl/tree/master/dglgo#training-graphsage-for-node-classification-on-cora) , this error happens.
I wonder what is the cause of the error. Thanks a lot!

## To Reproduce

1. dgl configure nodepred --data cora --model sage --cfg cora_sage.yaml
2. dgl train --cfg cora_sage.yaml
![1655707114825](https://user-images.githubusercontent.com/97089788/174540253-8c64fdb6-b26e-401d-92b7-a04c3336439c.jpg)

## Environment

 - DGL Version (e.g., 1.0): 0.8.2
 - Backend Library & Version (e.g., PyTorch 0.4.1, MXNet/Gluon 1.3): pytorch 1.11
 - OS (e.g., Linux): windows
 - How you installed DGL (`conda`, `pip`, source): pip
 - Build command you used (if compiling from source):
 - Python version: 3.7
 - CUDA/cuDNN version (if applicable): 10.2
 - GPU models and configuration (e.g. V100):
 - Any other relevant information: DGL-Go version 0.0.1

**Comment by mufeili** [comment]
Building DGL-Go from source should address the issue. If that's not convenient for you, we can also make a minor release.

**Comment by wanhanbo** [comment]
[This guide](https://docs.dgl.ai/en/latest/install/index.html#install-from-source) is about building DGL from source, and does it include DGL-Go?

**Comment by mufeili** [comment]
> [This guide](https://docs.dgl.ai/en/latest/install/index.html#install-from-source) is about building DGL from source, and does it include DGL-Go?

You will need to separately build from source for DGL-Go. I've updated the README file of DGL-Go in #4095 . For now, see https://github.com/mufeili/dgl/tree/apply/dglgo#install-from-source-for-experimental-features
