### ISSUE TITLE
[Help Wanted]How do I use the node_embedding to test my model for link predicition?

### ISSUE THREAD

**Issue by mokeeqian** [dmlc/dgl#4162]
## 📚 Documentation

I have constructed my heterograph and trained the model for linkprediction.
But:
- how can I use the node embedding to evaluate the model?
- how should I split the dataset into train and test?

**Comment by BarclayII** [comment]
> how can I use the node embedding to evaluate the model?

There are two approaches.  One is to use the same pipeline as training, which takes the least effort and is suitable for quickly checking the performance of a model on a small test set.  Another is to do offline inference like https://docs.dgl.ai/tutorials/large/L2_large_link_prediction.html#evaluating-performance-with-unsupervised-learning-optional and https://docs.dgl.ai/tutorials/large/L2_large_link_prediction.html#evaluating-performance-with-link-prediction-optional, whose advantage is that you can precompute and store all the node embeddings later for evaluating on a large test set.

> how should I split the dataset into train and test?

Normally it depends on your use scenario, e.g. sometimes you would like to split temporally.  If you are OK with splitting uniformly you could try 
 https://docs.dgl.ai/generated/dgl.data.AsLinkPredDataset.html#dgl.data.AsLinkPredDataset.

**Comment by mokeeqian** [comment]
> 
Currently, I use the `train_mask` params to hide part of the links during training, and then use the nodes connect with the masked edges to compute the score via the node_embedding.
OKEY, thanks!
