### ISSUE TITLE
[Bug][Test] `test_module_sign` occasionally fails

### ISSUE THREAD

**Issue by yaox12** [dmlc/dgl#4163]
## 🐛 Bug

`tests/compute/test_transform.py::test_module_sign[g0]` occasionally fails in Torch CPU/ Torch GPU/Windows CPU unit tests. For example:
- on CPU: [log file](https://dgl-ci-result.s3.us-west-2.amazonaws.com/dgl/PR-3885/20/20/logs/logs_dir/tmpjaa761ic.log) from PR-3885
- on GPU: [log file](https://dgl-ci-result.s3.us-west-2.amazonaws.com/dgl/PR-3713/9/9/logs/logs_dir/tmpxeedre3g.log) from PR-3713
- on Windows CPU: [log file](https://dgl-ci-result.s3.us-west-2.amazonaws.com/dgl/PR-4140/6/6/logs/logs_dir/tmp2_yorx7j.log) from PR-4140

cc @mufeili

**Comment by mufeili** [comment]
Do you have clues about why this occasionally fails?

**Comment by yaox12** [comment]
Not yet. The above logs are from several PRs and I just happened to find they all failed in `test_module_sign`.

**Comment by mufeili** [comment]
The error messages look strange. It seems that rather than comparing `X1` and `AX2`, they are comparing `X1` and `(A, matmul, X2)`. I'm not sure if having an additional line of code above for first computing `AX2` will be sufficient to address the issue.

**Comment by yaox12** [comment]
The error occurs again in http://dgl-jenkins-eksvpc-2136217999.us-west-2.elb.amazonaws.com/blue/organizations/jenkins/dgl/detail/PR-4183/1/pipeline/572. @mufeili

**Comment by yaox12** [comment]
I think this could be caused by matmul precision in PyTorch. In PyTorch 1.12, they add an option to provide the highest precision. https://github.com/pytorch/pytorch/pull/76509.

**Comment by mufeili** [comment]
> The error occurs again in http://dgl-jenkins-eksvpc-2136217999.us-west-2.elb.amazonaws.com/blue/organizations/jenkins/dgl/detail/PR-4183/1/pipeline/572. @mufeili

From the error message, it does seem to be a precision issue. Perhaps making the threshold larger in `torch.allcose` will address the issue.
