### ISSUE TITLE
Single Machine Multi-GPU Minibatch error

### ISSUE THREAD

**Issue by heihaizhengdong** [dmlc/dgl#4165]
## 🐛 Bug

Hi, I followed the tutorial here: https://docs.dgl.ai/tutorials/multi/1_graph_classification.html#sphx-glr-tutorials-multi-1-graph-classification-py to train a graph autoencoder on single Machine using multi-GPU minibatch. The code worked when I had 10000 graphs as input. But when I increased the input sample to 16000, I got the error message below. 

## To Reproduce

Traceback (most recent call last):
 File “/n/holystore01/LABS/xxx/Users/xxx/MultiGPU/graph_ae//graph_ae_multi.py”, line 187, in <module>
  mp.spawn(main, args=(num_gpus, dataset), nprocs=num_gpus)
 File “/n/home07/xxx/.conda/envs/C2/lib/python3.7/site-packages/torch/multiprocessing/spawn.py”, line 230, in spawn
  return start_processes(fn, args, nprocs, join, daemon, start_method=‘spawn’)
 File “/n/home07/xxx/.conda/envs/C2/lib/python3.7/site-packages/torch/multiprocessing/spawn.py”, line 179, in start_processes
  process.start()
 File “/n/home07/xxx/.conda/envs/C2/lib/python3.7/multiprocessing/process.py”, line 112, in start
  self._popen = self._Popen(self)
 File “/n/home07/xxx/.conda/envs/C2/lib/python3.7/multiprocessing/context.py”, line 284, in _Popen
  return Popen(process_obj)
 File “/n/home07/xxx/.conda/envs/C2/lib/python3.7/multiprocessing/popen_spawn_posix.py”, line 32, in __init__
  super().__init__(process_obj)
 File “/n/home07/xxx/.conda/envs/C2/lib/python3.7/multiprocessing/popen_fork.py”, line 20, in __init__
  self._launch(process_obj)
 File “/n/home07/xxx/.conda/envs/C2/lib/python3.7/multiprocessing/popen_spawn_posix.py”, line 47, in _launch
  reduction.dump(process_obj, fp)
 File “/n/home07/xxx/.conda/envs/C2/lib/python3.7/multiprocessing/reduction.py”, line 60, in dump
  ForkingPickler(file, protocol).dump(obj)
 File “/n/home07/xxx/.conda/envs/C2/lib/python3.7/site-packages/torch/multiprocessing/reductions.py”, line 321, in reduce_storage
  fd, size = storage._share_fd_()
RuntimeError: unable to mmap 5632 bytes from file </torch_20919_421696624>: Cannot allocate memory (12)

1. I just followed the tutorial here and revised input dataset and model.
1.  I have:
> if _ _ name _ _ == '__main__':
>   import torch.multiprocessing as mp
> num_gpus = 4
> dataset=generate_Dataset()
>  mp.spawn(main, args=(num_gpus, dataset), nprocs=num_gpus)

and main function to init_process_group, get_dataloaders, init_model, and do the training.

3. Since the code worked when I had 10000 graphs as input but failed when I have 16000 input. SoI assume the code is fine but somewhere it ran out of memory. 

## Expected behavior

Do you know how should I solve this large dataset training issue? I searched online but got very little information about this. Thanks!

## Environment

 - DGL Version (e.g., 1.0): 0.8.2 
 - Backend Library & Version (e.g., PyTorch 0.4.1, MXNet/Gluon 1.3): torch 1.8.0+cu111
 - OS (e.g., Linux):
 - NAME="CentOS Linux"
VERSION="7 (Core)"
ID="centos"
ID_LIKE="rhel fedora"
VERSION_ID="7"
PRETTY_NAME="CentOS Linux 7 (Core)"
ANSI_COLOR="0;31"
CPE_NAME="cpe:/o:centos:centos:7"
HOME_URL="https://www.centos.org/"
BUG_REPORT_URL="https://bugs.centos.org/"

CENTOS_MANTISBT_PROJECT="CentOS-7"
CENTOS_MANTISBT_PROJECT_VERSION="7"
REDHAT_SUPPORT_PRODUCT="centos"
REDHAT_SUPPORT_PRODUCT_VERSION="7"

 - How you installed DGL (`conda`, `pip`, source): pip 
 - Build command you used (if compiling from source):
 - Python version: 3.7
 - CUDA/cuDNN version (if applicable): 11.1.0
 - GPU models and configuration (e.g. V100): NVIDIA Tesla V100 16G
 - Any other relevant information:
499GB RAM

**Comment by heihaizhengdong** [comment]
Can you please help me with the large dataset training issue? Really looking forward to some suggestions! Thanks so much! @jermainewang @Rhett-Ying

**Comment by Rhett-Ying** [comment]
pls try to increase shared memory(`df -h /dev/shm`) and ulimit (`ulimit -n `)
