### ISSUE TITLE
Graph Global Context 

### ISSUE THREAD

**Issue by yuchenlin** [dmlc/dgl#417]
## Motivation

I am trying to implement deep mind's graph networks, which includes a graph-specific global context vector, which will be involved in edge/node feature updating and itself is also updated by aggregating features of all nodes and edges. 

I know that if we are dealing with a large graph as training data, we can set a trainable parameter in the model __init__. But it is not okay when I am having a lot of small graphs as training data. 
Is there any way to have something like `g.gdata["h"]`? 

## Additional context

Paper: https://arxiv.org/pdf/1806.01242.pdf (algorithm 1)

Thanks so much for your works!

**Comment by yzh119** [comment]
Hi,
To deal with a set of small graphs, we provide `BatchedDGLGraph` to handle this. You could call `dgl.batch(g_list)` to covert a list of `DGLGraph`s to `BatchDGLGraph`.

For a graph level representation, you may refer to the graph embedding section of our [DGMG tutorial](https://docs.dgl.ai/tutorials/models/3_generative_model/5_dgmg.html).

As for the "update of edge features", sorry but I'm not so clear about your requirement, currently we have `apply_edges` function to update node features given the node feature of src, dst nodes and the edge features itself.

**Comment by yuchenlin** [comment]
Hi Zihao, thanks so much for the prompt help!  Just took a look at the DGMG case, I feel like it is not the same situation that I am facing. In my case, I have a model for representing graphs, whose parameters are shared to all the input graphs. Each input graph is small and has an associated vector as initialized representation. Every time the forward has a graph (and its initialized global vector) as input, we update its edge features by using the shared model parameters (some MLPs) to incorporate global vectors. Then, update node features, and finally update its global vector by aggregating the node/edge features.

While the tutorial seems like they consider a single giant graph as input,  the global vector is part of the model, which is learnable. I think the key difference in my case is the global vector is not part of the model itself, but as input/output with each small particular graph.

**Comment by mufeili** [comment]
Then how about the proposal below:
```python
class Model(object):
    def __init__(self, ...):
        # A function taking edge features and graph features
        self.f = ...
        ...
    
    def update_edge(self, edges):
        return {'he': self.f(edges, self.g.gdata['h'])}
    
    def forward(g):
        self.g = g
        self.g.apply_edges(self.update_edge)

for iter, (batched_graph, label, graph_feats) in enumerate(data_loader):
    batched_graph.gdata['h'] = graph_feats
    model(batched_graph)
```

**Comment by yuchenlin** [comment]
Yeah, Mufei, it is very desirable. I think `g.gdata` can also be useful in many other cases. My current workaround is to set the global vector as of `g.ndata['g']`.

**Comment by mufeili** [comment]
@yuchenlin You can simply add an attribute to the DGLGraph objects yourself:
```
batched_graph.gdata = {}
```

**Comment by yuchenlin** [comment]
Oh! Amazing, I didn't know that I can even do this kind of attribute assignments with dgl... Haha, then this is not a problem anymore..

**Comment by jermainewang** [comment]
Hey, just want to bring up this question a little bit. My suggested way of doing global/graph level attribute is actually using function closure. For example, suppose you have a graph attribute `x` that will be used in a message function. Then the following code should achieves that:
```python
class YourNNModule(nn.Module):
  def __init__(self):
    self.x = ...  # the graph-level attribute
    self.graph = ...  # the graph
  def message_func(self, edges):
    return {'m' : edges.src['h'] * self.x}   # global/graph attribute is used to compute message
  def forward(...):
    self.graph.update_all(...)
```
This is in fact the reason why we decide not to have `gdata` as in graph_net. We found this is a better and cleaner way to implement graph attribute.
