### ISSUE TITLE
to_homogeneous() return heterograph (dgl.heterograph.DGLHeteroGraph)

### ISSUE THREAD

**Issue by renaultJB** [dmlc/dgl#4170]
## 🐛 Bug

 `dgl.to_homogeneous()` return `dgl.heterograph.DGLHeteroGraph` type.

## To Reproduce

```python
hg = dgl.heterograph({
    ('user', 'follows', 'user'): ([0, 1], [1, 2]),
    ('developer', 'develops', 'game'): ([0, 1], [0, 1])
    })
hg.nodes['user'].data['h'] = torch.ones(3, 1)
hg.nodes['developer'].data['h'] = torch.zeros(2, 1)
hg.nodes['game'].data['h'] = torch.ones(2, 1)
g = dgl.to_homogeneous(hg)
type(g)
# return: dgl.heterograph.DGLHeteroGraph
```

## Expected behavior

I was expecting `g` to be a homogeneous graph. 

## Environment

 - DGL Version: 0.8
 - Backend Library & Version:  PyTorch 1.10.2+cpu
 - OS: Linux
 - How you installed DGL: `pip install https://data.dgl.ai/wheels-test/dgl-0.8a220301-cp38-cp38-manylinux1_x86_64.whl`
 - Build command you used : None
 - Python version: 3.8.10
 - CUDA/cuDNN version (if applicable): None
 - GPU models and configuration (e.g. V100): None
 - Any other relevant information: using Databricks ML 10.4

## Additional context

I have noticed [here](https://docs.dgl.ai/en/0.8.x/_modules/dgl/convert.html) that `dgl.to_homogeneous()` call `dgl.graph()` that calls `dgl.create_from_edges()` that systematically return a `dgl.heterograph.DGLHeteroGraph`

**Comment by yaox12** [comment]
All graphs are `dgl.heterograph.DGLHeteroGraph` and a homogeneous graph is considered a heterograph with only one relation type. You can use `g.is_homogeneous` to check if it's homogeneous.

**Comment by renaultJB** [comment]
Thank you for your answer. I should have read the [documentation](https://docs.dgl.ai/en/0.8.x/guide/graph-heterogeneous.html) more carefully:
_"Note that homogeneous and bipartite graphs are just special heterogeneous graphs with one relation."_
