### ISSUE TITLE
MultiLayerNeighborSampler related typos in the document

### ISSUE THREAD

**Issue by chang-l** [dmlc/dgl#4172]
## 📚 Documentation

It seems MultiLayerNeighborSampler is deprecated/removed in doc and replaced by NeighborSampler.

Within the code example for NodeCollator class definition (https://docs.dgl.ai/en/rying_test/api/python/dgl.dataloading.html#collators), it states: 
_To train a 3-layer GNN for node classification on a set of nodes train_nid on a homogeneous graph where each node takes messages from **all neighbors** (assume the backend is PyTorch):_

However, here is the corresponding code snippet: 
```
sampler = dgl.dataloading.MultiLayerNeighborSampler([15, 10, 5])
collator = dgl.dataloading.NodeCollator(g, train_nid, sampler)
dataloader = torch.utils.data.DataLoader(
    collator.dataset, collate_fn=collator.collate,
    batch_size=1024, shuffle=True, drop_last=False, num_workers=4)
for input_nodes, output_nodes, blocks in dataloader:
    train_on(input_nodes, output_nodes, blocks)
```

Apparently, the example code is inconsistent with the statement, i.e., it is sampled with fanout [15,10,5], not full neighbor sampling.

Also, the example code for Dataloader definition at: https://docs.dgl.ai/generated/dgl.dataloading.DataLoader.html, has the same typo...

**Comment by yaox12** [comment]
`NodeCollator` is deprecated and the doc should be some legacy version. Master branch doc has been fixed in the above PR.
