### ISSUE TITLE
[Usability] to_undirected_graph method when constructing DGL graph using edgelist

### ISSUE THREAD

**Issue by HQ01** [dmlc/dgl#419]
## 🚀 Feature

Add a simple method to allow users to construct an "undirected" (which is essentially bi-directed) DGL graph from edge list when constructing the graph.
## Motivation
Some datasets (like ENZYMES) store graphs as edges list, and default the graph type to undirected. It would be convenient for users to initialize a DGL graph from an edgelist of undirected graph.
 

## Alternatives

Currently one could first construct a nx graph, then cast it to DGL graph. Or one could first double the edge list and make it bi-directional first. 
## Pitch

a = dgl.DGLGraph()
a.add_nodes(3)
edgeList = [(0,1),(1,0),(2,1)]
a.add_edges(edgeList)
a.to_undirected()
print(a.edges)
result: [(0,1),(1,0),(2,1),(1,2)]
## Additional context
Circumstances exists when users may not have prior knowledge of networkx, or the edge list is not purely undirected. If let user to handle it, it could be the case that 1) the constructed DGL graph is not "undirected", or it's a multigraph.

**Comment by jermainewang** [comment]
My question is if the graph already contains features. What will happen if `to_undirected` is called?

Also, suggest `to_bidirected`.

**Comment by HQ01** [comment]
If edges already have features, then one thing we can do is to simply copy the edge feature to the reverse direction, with the option of letting users specify them (reverse sign, different edge feature, etc.)

Yeah I agree, to_bidirected sounds better!

**Comment by jermainewang** [comment]
Sounds good. Two more questions:

* Would you prefer returning a new graph? or perform mutation inplace?
* As you've noticed, the `bi_directed` graph could become a multi-graph if edges are added accidentally. This is related to #340 by @BarclayII . The issue with that PR is it slows down the graph construction time a lot for extra duplication check. I've been thinking about this question a lot. My current intention is to (a) no duplication check during mutation; (b) provide a utility function called `to_simple_graph` that will prune out duplication. As a result, the extra time/space is confined in this API and is called by user explicitly. What do you guys think?

**Comment by HQ01** [comment]
1) I would prefer mutation in place since the most common use case of this will be in data-preprocessing and we don't need the original graph.

2) If I understand it correctly -- in this design, `to_bidirected` will simply double the number of edges (even if the original graph is already a multi-graph), and `to_simple_graph` will prune any graph with multiple edges between pairs of nodes to simple graph?

**Comment by jermainewang** [comment]
> 1. I would prefer mutation in place since the most common use case of this will be in data-preprocessing and we don't need the original graph.

I agree that inplace update is the common use case at the moment but we should be careful. Networkx usually returns a copy of the graph for these APIs (e.g. [`Graph.to_undirected`](https://networkx.github.io/documentation/networkx-1.10/reference/generated/networkx.Graph.to_undirected.html)), so I would follow this convention unless there are other concerns.

> 2. If I understand it correctly -- in this design, `to_bidirected` will simply double the number of edges (even if the original graph is already a multi-graph), and `to_simple_graph` will prune any graph with multiple edges between pairs of nodes to simple graph?

Yes.

**Comment by HQ01** [comment]
Should we also add this to 0.3 roadmap?

**Comment by jermainewang** [comment]
Yes. Please do. You could directly modify the post rather than reply the issue. Thanks!

**Comment by jermainewang** [comment]
I've done that. Let's leave this issue open until the feature is implemented.

**Comment by HQ01** [comment]
No problem. Thanks!

**Comment by mufeili** [comment]
Added with PR #598.
