### ISSUE TITLE
How can I install DGL on Mac M1?

### ISSUE THREAD

**Issue by LeifYaoYuXiang** [dmlc/dgl#4215]
Does anybody try to install DGL on Mac Apple Silicon?
If i install DGL on M1 by running the following command:
`conda install -c dglteam dgl` or `pip install dgl -f https://data.dgl.ai/wheels-test/repo.html`
It will be errors like:
ERROR: Could not find a version that satisfies the requirement dgl (from versions: none)
ERROR: No matching distribution found for dgl

**Comment by RecLusIve-F** [comment]
You may clone the repository with `git clone --recurse-submodules https://github.com/dmlc/dgl.git` or clone the repository first, and then run the `git submodule update --init --recursive`?

**Comment by LeifYaoYuXiang** [comment]
Got it! Everything is OK! Thanks
