### ISSUE TITLE
The puzzled about the formula of dgl.nn.pytorch.conv.GraphConv() function

### ISSUE THREAD

**Issue by shengwenLeong** [dmlc/dgl#423]
## 📚 Documentation

Hi,
  Recently, I read the doc of this project. And I confused about the formula of graph convolution operation. In doc, the formula is:
![image](https://user-images.githubusercontent.com/5969647/53644777-5ca89080-3c72-11e9-9150-8ea795f3bd33.png)
Why is not 
<a href="https://www.codecogs.com/eqnedit.php?latex=h_i^{(l&plus;1)}&space;=&space;\sigma(b^{(l)}&space;&plus;&space;\sum_{j\in\mathcal{N}(i)}\frac{1}{c_{ij}}h_j^{(l)}W^{(l)})" target="_blank"><img src="https://latex.codecogs.com/gif.latex?h_i^{(l&plus;1)}&space;=&space;\sigma(b^{(l)}&space;&plus;&space;\sum_{j\in\mathcal{N}(i)}\frac{1}{c_{ij}}h_j^{(l)}W^{(l)})" title="h_i^{(l+1)} = \sigma(b^{(l)} + \sum_{j\in\mathcal{N}(i)}\frac{1}{c_{ij}}h_j^{(l)}W^{(l)})" /></a>
And the source code 
`feat = th.matmul(feat, self.weight)`
in this function also show 
<a href="https://www.codecogs.com/eqnedit.php?latex=h_j^{(l)}W^{(l)}" target="_blank"><img src="https://latex.codecogs.com/gif.latex?h_j^{(l)}W^{(l)}" title="h_j^{(l)}W^{(l)}" /></a>

**Comment by jermainewang** [comment]
That's a good catch! Thanks! Will hot fix it.

**Comment by jermainewang** [comment]
Fixed in #425 .
