### ISSUE TITLE
How to build own dataset for HAN?

### ISSUE THREAD

**Issue by gongtian1234** [dmlc/dgl#4251]
I looked at the sample data "ACM" loaded by HAN under example. But I can't understand how the sparse matrices of "PAP" and "PLP" in the example come from, and how to understand and get this. At the same time, I can't understand whether PAP and PLP are meta-paths or nodes. For example, the sparse matrix of PLP is as follows: 
`matrix([[1., 0., 0., ..., 0., 0., 0.],
        [0., 1., 0., ..., 0., 1., 0.],
        [0., 0., 1., ..., 1., 0., 1.],
        ...,
        [0., 0., 1., ..., 1., 0., 1.],
        [0., 1., 0., ..., 0., 1., 0.],
        [0., 0., 1., ..., 1., 0., 1.]])`
What do the three 1s in the third line mean?
Without understanding the meaning of PAP and PLP, it will be difficult for me to further create my own dataset and train HAN.
I don't know whether I described the problem clearly enough for you to quickly understand my problem. Looking forward to your help and reply, thank you!

**Comment by mufeili** [comment]
I guess "PAP" means a meta-path "paper-author-paper", i.e., two papers that share common author(s). If you have an adjacency matrix representing the paper-author relationship, then AA^T will give you the resulted "PAP" adjacency matrix.

**Comment by gongtian1234** [comment]
> I guess "PAP" means a meta-path "paper-author-paper", i.e., two papers that share common author(s). If you have an adjacency matrix representing the paper-author relationship, then AA^T will give you the resulted "PAP" adjacency matrix.
I understand, thanks for your answer.
