### ISSUE TITLE
[Doc] The num_servers and num_workers arguments have been deprecated but not removed from distributed initialize

### ISSUE THREAD

**Issue by jermainewang** [dmlc/dgl#4272]
## 🚀 Feature

The doc says `num_servers` and `num_workers` arguments have been deprecated but not removed from `dgl.distributed.initialize`.

## Pitch

Should double check the logic and remove them.

**Comment by Rhett-Ying** [comment]
fix in https://github.com/dmlc/dgl/pull/4284
