### ISSUE TITLE
examples/pytorch/graphsage/dist/train_dist.py fails in standalone mode

### ISSUE THREAD

**Issue by brameret** [dmlc/dgl#4278]
## 🐛 Bug

When starting the distributed graph SAGE training in standalone mode, the `model` does not have the `join()` attribute, and the training stop with an error.

## To Reproduce

Steps to reproduce the behavior (following the `dist/README` about standalone mode, supervised training):

1. `cd examples/pytorch/graphsage/dist/`
1. `python3 partition_graph.py --dataset ogb-product --num_parts 1`
1. `python3 train_dist.py --graph_name ogb-product --ip_config ip_config.txt --num_epochs 3 --batch_size 1000 --part_config data/ogb-product.json --standalone`

gives:

```python
Traceback (most recent call last):
  File "train_dist.py", line 333, in <module>
    main(args)
  File "train_dist.py", line 299, in main
    run(args, device, data)
  File "train_dist.py", line 207, in run
    with model.join():
  File "/.../python3.8/site-packages/torch/nn/modules/module.py", line 1177, in __getattr__
    raise AttributeError("'{}' object has no attribute '{}'".format(
AttributeError: 'DistSAGE' object has no attribute 'join'
```

## Expected behavior

It is expected that the model trains.

## Environment

 - DGL Version: 0.8.2 with cu113
 - Backend Library & Version: PyTorch 1.10.2 with cu113
 - OS (e.g., Linux): linux
 - How you installed DGL (`conda`, `pip`, source): `pip`
 - Build command you used (if compiling from source):
 - Python version: 3.8.10
 - CUDA/cuDNN version (if applicable): 1.13
 - GPU models and configuration (e.g. V100):
 - Any other relevant information:

## Additional context

May be linked to #4264.

I think that `model` returned by `th.nn.parallel.DistributedDataParallel()` has the `join()` attribue, but in standalone mode, this cannot be called as `th.distributed.init_process_group` is not called.

I did not find other examples of distributed graph training running in standalone mode (e.g. in [distributed node classification training](https://docs.dgl.ai/tutorials/dist/1_node_classification.html) it just states that there is a standalone mode, but not how to run it).
What should be done? It seems that we can implement `DistSAGE.join(self)` as follows:
```python
class DistSAGE(nn.Module):
    # [...]
    @contextmanager
    def join(self):
        yield
```
It works in standalone mode but I don't have a setup yet to test it in distributed mode.

**Comment by Rhett-Ying** [comment]
thanks for reporting this. I have made fix alongside the refactor.
