### ISSUE TITLE
The problem about the formula of GCN in one formula.

### ISSUE THREAD

**Issue by shengwenLeong** [dmlc/dgl#428]
## 📚 Documentation

Hi, 
   Recently, I read the doc and find a problem. In [GCN in one formula](https://docs.dgl.ai/tutorials/models/1_gnn/1_gcn.html#gcn-in-one-formula) section, the doc said the GCN model follows this formula:
![image](https://user-images.githubusercontent.com/5969647/53691355-30e2f300-3db7-11e9-9a56-1726e7426d16.png)
However, from the source code 
` data = citegrh.load_cora()`  I find the citegrh.load_cora() has `_normilze function` shows the `r_inv= r_inv = np.power(rowsum, -1).flatten()`. This code shows the formula is 
<a href="https://www.codecogs.com/eqnedit.php?latex=H^{(l&plus;1)}&space;=&space;\sigma(\tilde{D}^{-1}\tilde{A}H^{(l)}W^{(l)})" target="_blank"><img src="https://latex.codecogs.com/gif.latex?H^{(l&plus;1)}&space;=&space;\sigma(\tilde{D}^{-1}\tilde{A}H^{(l)}W^{(l)})" title="H^{(l+1)} = \sigma(\tilde{D}^{-1}\tilde{A}H^{(l)}W^{(l)})" /></a>

**Comment by yzh119** [comment]
Hi,
We take the square root of D [here](https://github.com/dmlc/dgl/blob/master/examples/pytorch/gcn/train.py#L63)

**Comment by shengwenLeong** [comment]
> Hi,
> We take the square root of D [here](https://github.com/dmlc/dgl/blob/master/examples/pytorch/gcn/train.py#L63)

Ok, I see. Thanks.
