### ISSUE TITLE
[Example] A possible bug in GIN example implementation

### ISSUE THREAD

**Issue by chang-l** [dmlc/dgl#4281]
## ❓ Questions and Help

In the GIN example, when it comes to construct the GIN model, as [here](https://github.com/dmlc/dgl/blob/master/examples/pytorch/gin/gin.py#:~:text=self.ginlayers.,self.learn_eps), I wonder if it is a bug that `ApplyNodeFunc` is passed to `GINConv` rather than `MLP`

According to the orig. [paper](https://arxiv.org/pdf/1810.00826.pdf) and [code](https://github.com/weihua916/powerful-gnns/blob/master/models/graphcnn.py#:~:text=and%20center%20nodes-,pooled_rep%20%3D%20self.mlps%5Blayer%5D(pooled),-h%20%3D%20self), it seems MLP should directly go into GCN layer, i.e., `MLP` --> GCN(batch_norm + ReLU),  while the current implementation has:  `ApplyNodeFunc` (MLP + batch_norm + ReLU) --> GCN (batch_norm + ReLU).

Can someone please help confirm or correct me if I missed anything?

**Comment by mufeili** [comment]
Sorry, I did not get your question. When `linear_or_not` is True [here](https://github.com/dmlc/dgl/blob/master/examples/pytorch/gin/gin.py#L72), it is `MLP (linear)` rather than `MLP (linear + batch_norm + ReLU)`, right?

**Comment by chang-l** [comment]
Linear-or-not is true if it is a 1-layer perceptron (num_mlp_layer=1), ie, degenerate to classic GCN or Graphsage. 

When num_mlp_layer=2, linear_or_not is False, right?

**Comment by mufeili** [comment]
It seems that in the current example `linear_or_not` is always True and we can simply drop other code for simplicity.

**Comment by chang-l** [comment]
Sorry, I don't quite get it... `linear_or_not` is actually always False in the current example, right? Because `num_mlp_layer` is 2 by default, in other words, `num_layers` in MLP module should always be 2.  The comment `# default is linear model` is misleading though...

**Comment by mufeili** [comment]
> Sorry, I don't quite get it... `linear_or_not` is actually always False in the current example, right? Because `num_mlp_layer` is 2 by default, in other words, `num_layers` in MLP module should always be 2. The comment `# default is linear model` is misleading though...

My bad. You are right. Could you try removing the extra code and re-running the experiments? If the numbers are about the same, I'm fine with removing them.

**Comment by chang-l** [comment]
Thanks. 
I removed module `ApplyNodeFunc` and used (2-layer hard-coded) `MLP` to construct `GINConv` in this PR: https://github.com/dmlc/dgl/pull/4280. After I re-ran all experiments, the results were close enough and I updated them in README file.

**Comment by mufeili** [comment]
> Thanks. I removed module `ApplyNodeFunc` and used (2-layer hard-coded) `MLP` to construct `GINConv` in this PR: #4280. After I re-ran all experiments, the results were close enough and I updated them in README file.

Sounds good to me
