### ISSUE TITLE
Is it a inplace operation?

### ISSUE THREAD

**Issue by czqaq** [dmlc/dgl#4285]
## ❓ Questions and Help
I try to use the implement of [graphtransformer](https://github.com/graphdeeplearning/graphtransformer/blob/main/layers/graph_transformer_edge_layer.py), but when loss.backward() in second episode, such an error occurs: 
`RuntimeError: Trying to backward through the graph a second time (or directly access saved tensors after they have already been freed). Saved intermediate values of the graph are freed when you call .backward() or autograd.grad(). Specify retain_graph=True if you need to backward through the graph a second time or if you need to access saved tensors after calling backward.`
and there is my code:
```
criteria = nn.MSELoss()
for n in range(3):
    lp_pe = g_dgl.ndata["lap_pos_enc"].to(device)
    out = model(g_dgl, h, e, lp_pe)
    loss = criteria(node_label[0], out)
    print(f"epoch #{n}, loss:{loss}")
    optimizer.zero_grad()
    loss.backward()
    optimizer.step()
```
but when i use this code:
```
optimizer.zero_grad()
    with torch.autograd.set_detect_anomaly(True):
        loss.backward(retain_graph=True)
    optimizer.step()
```
another error occurs:
`RuntimeError: one of the variables needed for gradient computation has been modified by an inplace operation: [torch.cuda.FloatTensor [32, 32]], which is output 0 of AsStridedBackward0, is at version 2; expected version 1 instead. Hint: the backtrace further above shows the operation that failed to compute its gradient. The variable in question was changed in there or anywhere later. Good luck!`
I found maybe its because the code below use inplace operation, but i'm not familiar with dgl. I really appreciate it if you can help me solve this problem.
```
def src_dot_dst(src_field, dst_field, out_field):
    def func(edges):
        return {out_field: (edges.src[src_field] * edges.dst[dst_field])}

    return func

def scaling(field, scale_constant):
    def func(edges):
        return {field: ((edges.data[field]) / scale_constant)}

    return func

g.apply_edges(src_dot_dst('K_h', 'Q_h', 'score'))
g.apply_edges(scaling('score', np.sqrt(self.out_dim)))

```

**Comment by BarclayII** [comment]
The code you show does not have in-place operation per se, and I don't think you need `retain_graph=True`.  It's likely that you have overwritten one of the node and edge features.  Did you implement the model from scratch?  If so, could you show the full model implementation code?

**Comment by czqaq** [comment]
Thanks for replying!
I directly use the model code [layer](https://github.com/graphdeeplearning/graphtransformer/blob/main/layers/graph_transformer_edge_layer.py) and [net](https://github.com/graphdeeplearning/graphtransformer/blob/main/nets/molecules_graph_regression/graph_transformer_net.py)，only change the way get parameter in init(), and I write the train code myself. I want to understand the process, so I random initialize the input and label. The code before train loop:
```
cpu_size = np.random.uniform(100, 200, (NODE_NUM, 1))  
data_size = np.random.uniform(300, 500, (NODE_NUM, 1))  
trans_size = np.random.uniform(900, 1100, (EDGE_NUM, 1))  
feats = np.concatenate((cpu_size, data_size), axis=1)

g_dgl = dgl.from_networkx(g_networkx)
g_dgl = laplacian_positional_encoding(g_dgl)
g_dgl.ndata["feats"] = torch.from_numpy(feats)
g_dgl.edata["trans_size"] = torch.from_numpy(trans_size)

h = torch.tensor([i for i in range(NODE_NUM)], device=device) 
e = torch.tensor([i for i in range(EDGE_NUM)], device=device)
lp_pe = g_dgl.ndata["lap_pos_enc"].to(device)

node_label = np.zeros((NODE_NUM, 1), dtype=int)
for index in range(len(node_label)):
    node_label[index] = random.randint(1, SERVER_NUM)
node_label = torch.tensor(node_label, dtype=torch.int).to(device)
node_label = node_label.unsqueeze(0).repeat(BATCH_SIZE, 1, 1)

model = GraphTransformerNet(in_dim=2, out_dim=EDGE_NUM)
model.to(device)
optimizer = torch.optim.Adam(model.parameters(), lr=5e-3, weight_decay=5e-4)
```
