### ISSUE TITLE
Failed to change block.dstdata, where block is converted from a heterogenous graph

### ISSUE THREAD

**Issue by yifanQi98** [dmlc/dgl#4287]
## 🐛 Bug

Failed to change block.dstdata, where block is converted from a heterogenous graph

## To Reproduce

```code
hg = dgl.heterograph({('user', 'like', 'item'): (torch.tensor([0, 1]), torch.tensor([1,2])),
                      ('user', 'dislike', 'item'): (torch.tensor([3, 4, 1]), torch.tensor([4, 0, 3])),
                      ('item', 'link', 'item'): (torch.tensor([5,4,3,2]), torch.tensor([1,2,3,4]))})
block = dgl.to_block(hg)
block.dstdata['hr'] = {'item': torch.ones(block.num_nodes('item'), 4)}
```

## Expected behavior

I can set block.srcdata, but failed to set block.dstdata.

```code
hg = dgl.heterograph({('user', 'like', 'item'): (torch.tensor([0, 1]), torch.tensor([1,2])),
                      ('user', 'dislike', 'item'): (torch.tensor([3, 4, 1]), torch.tensor([4, 0, 3])),
                      ('item', 'link', 'item'): (torch.tensor([5,4,3,2]), torch.tensor([1,2,3,4]))})
block = dgl.to_block(hg)
block.srcdata['hl'] = {'item': torch.ones(block.num_nodes('item'), 4)}
```

## Environment

 - DGL Version: 0.9.0
 - Backend Library & Version: pytorch 1.12
 - OS (e.g., Linux): centos7
 - How you installed DGL (`conda`, `pip`, source): pip
 - Python version: 3.9
 - CUDA/cuDNN version (if applicable): 11.3
 - GPU models and configuration (e.g. V100): RTX3090
 - Any other relevant information:

**Comment by BarclayII** [comment]
Could you try
```python
block.srcnodes['item'].data['hr'] = torch.ones(...)
```
I think setting a dictionary to `block.dstdata[key]` (and similarly `srcdata` and `ndata`) has a problem.
