### ISSUE TITLE
Change released package from dgl-cuXX to dgl with cuda in version number

### ISSUE THREAD

**Issue by jermainewang** [dmlc/dgl#4294]
## 🚀 Feature

Change DGL wheels to follow PyTorch's naming convention:

```
dgl-<version>+<cpu/cuda_version>-<python_version>_<os_hardware>.whl
```
For example: `dgl-0.9.0+cu113-cp37-cp37m-linux_x86_64.whl`

## Motivation

Currently we are using different package names (e.g., dgl-cu110 and dgl-cu113) for different cuda versions, which causes many issues such as duplicate installation.

## Alternatives

No other alternative.

**Comment by frozenbugs** [comment]
Has done in V1.0 launch,
