### ISSUE TITLE
Add documentation about GraphStorage and FeatureStorage

### ISSUE THREAD

**Issue by jermainewang** [dmlc/dgl#4295]
## 📚 Documentation

v0.8 updates the sampling pipeline and brings two new concepts `GraphStorage` and `FeatureStorage` as in RFC #3600 . Although the codes have been checked in #3625 , the doc page is currently missing.

cc @BarclayII

**Comment by frozenbugs** [comment]
This work has been taken up by Graphbolt, a new dataloading framework by DGL.
