### ISSUE TITLE
ModuleNotFoundError: No module named 'psutil'

### ISSUE THREAD

**Issue by mufeili** [dmlc/dgl#4300]
## 🐛 Bug

`'psutil'` is not installed when installing dgl with conda

## To Reproduce

1. conda install -c dglteam dgl-cuda10.2
1. import dgl

It then raises `ModuleNotFoundError: No module named 'psutil'`

## Environment

 - DGL Version (e.g., 1.0): 0.9
 - Backend Library & Version (e.g., PyTorch 0.4.1, MXNet/Gluon 1.3):
 - OS (e.g., Linux): ubuntu
 - How you installed DGL (`conda`, `pip`, source): conda
 - Build command you used (if compiling from source):
 - Python version:
 - CUDA/cuDNN version (if applicable):
 - GPU models and configuration (e.g. V100):
 - Any other relevant information:

**Comment by jermainewang** [comment]
Strange. Should have been handled by `setup.py`

https://github.com/dmlc/dgl/blob/master/python/setup.py#L176

@BarclayII

**Comment by BarclayII** [comment]
Fixed in 0.9.1.
