### ISSUE TITLE
[Bug][Unittest] An error in task_unit_test.sh

### ISSUE THREAD

**Issue by yaox12** [dmlc/dgl#4302]
## 🐛 Bug

In PR #4196, an error was introduced to `task_unit_test.sh`. 

This line https://github.com/dmlc/dgl/blob/92f87f48c765e4987b8043155e10d65d1af7dc83/tests/scripts/task_unit_test.sh#L44 should be 
```bash
if [ $2 != "gpu" ] && [ $DGLBACKEND == "pytorch" ]; then
```

This results in that `tests/distributed/` have not been tested since then. And I believe a recent PR (not sure which one) has broken `tests/distributed/test_distributed_sampling.py`.

PS: `tests/distributed/` was tested with all backends but only PyTorch now. Is it expected?

cc @jermainewang

**Comment by jermainewang** [comment]
You are right. The if statement is incorrect.

> And I believe a recent PR (not sure which one) has broken tests/distributed/test_distributed_sampling.py

@Rhett-Ying Would you please help enable the tests back and see which one is failing?

> PS: tests/distributed/ was tested with all backends but only PyTorch now. Is it expected?

Yes. The entire `dgl.distributed` package only works with PyTorch backend.

**Comment by Rhett-Ying** [comment]
@jermainewang  you mean some tests from `test_distributed_sampling` failed on non-pytorch backend or pytorch backend?

**Comment by yaox12** [comment]
> @jermainewang you mean some tests from `test_distributed_sampling` failed on non-pytorch backend or pytorch backend?

The Pytorch backend.
