### ISSUE TITLE
Message passing inversely

### ISSUE THREAD

**Issue by flowerbeach** [dmlc/dgl#431]
Hi, I'm wondering if one node can get messages from the destination of its outgoing edges?

**Comment by mufeili** [comment]
How about adding edges for both directions?

**Comment by flowerbeach** [comment]
But I can't tell which edges are outcoming or incoming?

**Comment by mufeili** [comment]
@flowerbeach There are ways to convert edges into two tensors `[srcs, dsts]` such that edge `i` has source `srcs[i]` and destination `dsts[i]`. You may want to provide additional information for the particular case you are faced with. 

We encourage users to use our [discussion forum](https://discuss.dgl.ai/) for questions like this. If you have some further questions, it will be great if you can open a discussion thread there and see if we can help you better.
