### ISSUE TITLE
[Questions] Is there an efficient way to share/send/recv DGLBlock (on GPU) between processes?

### ISSUE THREAD

**Issue by initzhang** [dmlc/dgl#4315]
## ❓ Questions and Help

Hi, I have two processes running on GPU that need to communicate some graph structure data. Specifically, process $A$ will perform sampling on GPU and send the sampled subgraphs, and the other process $B$ will receive the subgraphs and perform training. 

To support such usage, a naive solution is to offload subgraphs produced by $A$ to Main memory/Disk, and then re-transfer it to process $B$, but this is very inefficient. I am wondering if there exist other way to share graph between processes ? Thank you!

**Comment by Rhett-Ying** [comment]
For the data sharing/transferring, you could refer to https://github.com/dmlc/dgl/blob/9a16a5e03d9f653702fa98001e1549692c4b8394/python/dgl/backend/__init__.py#L127-L131

For the pickling part, you could refer to https://github.com/dmlc/dgl/blob/9a16a5e03d9f653702fa98001e1549692c4b8394/python/dgl/heterograph_index.py#L1377 for more detals.

**Comment by initzhang** [comment]
Got it, many thanks!
