### ISSUE TITLE
How to embed relational information in a Transformer for NMT task?

### ISSUE THREAD

**Issue by smith-co** [dmlc/dgl#4330]
I was using Transformer model a text generation task. 

However, my input data has relational information. This semantic information is encoded between tokens using different kind of edges. I cannot really embed this information in the Transformer model to train the model. 

So I am considering to use DGL for this problem. Is there a graph to sequence model available from DGL?

(I already did a brief search though but looks like DGL is very poor in supporting generative model.)

Any help is welcome.

**Comment by jermainewang** [comment]
Check out graph4nlp https://github.com/graph4ai/graph4nlp which contains a bunch of Graph2Seq examples using DGL.

**Comment by smith-co** [comment]
@jermainewang already looked at it. That implementation is super restrictive and not flexible like DGL.
