### ISSUE TITLE
Reduce the memory consumption of constructing DGLGraph at the end of the pipeline

### ISSUE THREAD

**Issue by jimjlu99** [dmlc/dgl#4350]
## 🔨Work Item

**IMPORTANT:**
* This template is only for dev team to track project progress. For feature request or bug report, please use the corresponding issue templates.
* DO NOT create a new work item if the purpose is to fix an existing issue or feature request. We will directly use the issue in the project tracker.

Project tracker: https://github.com/orgs/dmlc/projects/2

## Description

Reduce the memory consumption of constructing DGLGraph at the end of the pipeline

**Comment by jermainewang** [comment]
Resolved by #4338
