### ISSUE TITLE
Implement sampling with edge masks for NeighborSampler and test on single-machine/distributed setting

### ISSUE THREAD

**Issue by jimjlu99** [dmlc/dgl#4354]
## 🔨Work Item

**IMPORTANT:**
* This template is only for dev team to track project progress. For feature request or bug report, please use the corresponding issue templates.
* DO NOT create a new work item if the purpose is to fix an existing issue or feature request. We will directly use the issue in the project tracker.

Project tracker: https://github.com/orgs/dmlc/projects/2

## Description

- [x] #4364 
- [x] #4614
- [x] ~~Add edge mask to `sample_neighbors` function~~ (handled in #4364)
- [x] ~~Add edge mask to `sample_etype_neighbors` function~~ (handled in #4364)
- [ ] #4619

**Comment by BarclayII** [comment]
We have reviewed the solution for September and agreed that Sampling with Edge Masks (#4441)  will be the way to go.  Renaming this work item to be more specific.
