### ISSUE TITLE
Save the ID mapping of shuffling node/edges in the graph partitioning

### ISSUE THREAD

**Issue by jimjlu99** [dmlc/dgl#4359]
## Motivation
During inference stage, we may need to map the NID/EID to original NID/EID of the original graph(the one before partitioning).

## Alternatives
saving NID/EID as node/edge feature before partitioning.

## Pitch
a more direct and convenient way is preferable. How about offering below APIs:
1. `DistGraph.get_orig_nids(ntype)`, `DistGraph.get_orig_eids(etype)`
2. `DistGraph.get_orig_nids(shuffled_homo_ids)`, `DistGraph.get_orig_eids(shuffuled_homo_eids)`.

**Comment by Rhett-Ying** [comment]
@zheng-da @classicsong could you help review the target APIs? or just write down what you expect. thanks.

**Comment by Rhett-Ying** [comment]
As discussed with @zheng-da , we decide to save such ID mapping into files, same path with partitions. then users can load them on their own.
