### ISSUE TITLE
[Roadmap] Distributed CI/CD

### ISSUE THREAD

**Issue by jermainewang** [dmlc/dgl#4373]
Enhance our CI/CD to include unit tests for distributed training.
- [x] #4374
- [x] #4375
- [x] #4376
- [x] #4377
- [x] #4378
- [x] #4379
- [x] #4380

**Comment by jermainewang** [comment]
@Rhett-Ying @Kh4L Please chime in.

**Comment by Kh4L** [comment]
#4374 #4375 #4377 are in progress and could take up to an additional 2 weeks
#4376 could add another week

**Comment by jermainewang** [comment]
Closed as this has been shipped in v1.0.
