### ISSUE TITLE
Support state save/load for DGL sparse optimizers

### ISSUE THREAD

**Issue by jermainewang** [dmlc/dgl#4383]
## 🔨Work Item

**IMPORTANT:**
* This template is only for dev team to track project progress. For feature request or bug report, please use the corresponding issue templates.
* DO NOT create a new work item if the purpose is to fix an existing issue or feature request. We will directly use the issue in the project tracker.

Project tracker: https://github.com/orgs/dmlc/projects/2

## Description

Currently, optimizers under https://github.com/dmlc/dgl/tree/master/python/dgl/distributed/optim/pytorch do not support save/load optimizer states, which leads to invalid model checkpoints for distributed training. The fix is to add such support.

**Comment by frozenbugs** [comment]
Duplicated with https://github.com/dmlc/dgl/issues/4744?

**Comment by frozenbugs** [comment]
confirmed dupilication.
