### ISSUE TITLE
[Community] Mechanism for Having New Committors

### ISSUE THREAD

**Issue by mufeili** [dmlc/dgl#4397]
Currently DGL has a list of committors [here](https://www.dgl.ai/pages/about.html). Will there be a formal process for other community members to become new committors?

**Comment by VoVAllen** [comment]
Do you mean attract new commitors? Usually this starts with being contributor first. Many projects will have a bunch of `good first issues` for newbie to start with to attract more contributors

**Comment by yzh119** [comment]
I think it's about a formal process to assess new candidates for committership.
You can refer to [Apache](https://community.apache.org/newcommitter.html) for reference.

**Comment by mufeili** [comment]
> I think it's about a formal process to assess new candidates for committership. You can refer to [Apache's guideline](https://community.apache.org/newcommitter.html) for reference.

That's right. Thanks.
