### ISSUE TITLE
DiagMatrix Python class with all the most necessary members and attributes

### ISSUE THREAD

**Issue by jimjlu99** [dmlc/dgl#4407]
## 🔨Work Item

**IMPORTANT:**
* This template is only for dev team to track project progress. For feature request or bug report, please use the corresponding issue templates.
* DO NOT create a new work item if the purpose is to fix an existing issue or feature request. We will directly use the issue in the project tracker.

Project tracker: https://github.com/orgs/dmlc/projects/2

## Description

Implement the `DiagMatrix` Python class with the following members and attributes:
- `D.shape`
- `D.nnz`
- `D.dtype`
- `D.device`
- `D.val` (support `D.val = x`)

**Comment by jermainewang** [comment]
Done in https://github.com/dmlc/dgl_sparse_dev/pull/1
