### ISSUE TITLE
SparseMatrix Python class with all the most necessary members and attributes

### ISSUE THREAD

**Issue by jimjlu99** [dmlc/dgl#4408]
## 🔨Work Item

**IMPORTANT:**
* This template is only for dev team to track project progress. For feature request or bug report, please use the corresponding issue templates.
* DO NOT create a new work item if the purpose is to fix an existing issue or feature request. We will directly use the issue in the project tracker.

Project tracker: https://github.com/orgs/dmlc/projects/2

## Description

Implement the `SparseMatrix` python class with the following members and attributes:

- `A.shape`
- `A.nnz`
- `A.dtype`
- `A.device`
- `A.i`/ `A.row`
- `A.j` / `A.col`
- `A.val` (support `A.val = x`); syntax sugar `A(x)`
- `A.indices(format, return_shuffle=False)`
- `A.coo()`, `A.csr()`, `A.csc()`  (mocking API; no actual implementation)
- `A.dense()`

**Comment by jermainewang** [comment]
Done in https://github.com/dmlc/dgl_sparse_dev/pull/2 and https://github.com/dmlc/dgl_sparse_dev/pull/3
