### ISSUE TITLE
Sparse Ops: Binary op (sparse-op-diag)

### ISSUE THREAD

**Issue by jimjlu99** [dmlc/dgl#4415]
## 🔨Work Item

**IMPORTANT:**
* This template is only for dev team to track project progress. For feature request or bug report, please use the corresponding issue templates.
* DO NOT create a new work item if the purpose is to fix an existing issue or feature request. We will directly use the issue in the project tracker.

Project tracker: https://github.com/orgs/dmlc/projects/2

## Description

Binary op (sparse-op-diag)
- `A <op> D`, `<op>` can be +-*/
- `D <op> A`, `<op>` can be +-*/

**Comment by isratnisa** [comment]
Merged [PR](https://github.com/dmlc/dgl/issues/4414).

**Comment by isratnisa** [comment]
PR https://github.com/dmlc/dgl/pull/4617
