### ISSUE TITLE
Sparse Ops: Transposition

### ISSUE THREAD

**Issue by jimjlu99** [dmlc/dgl#4418]
## 🔨Work Item

**IMPORTANT:**
* This template is only for dev team to track project progress. For feature request or bug report, please use the corresponding issue templates.
* DO NOT create a new work item if the purpose is to fix an existing issue or feature request. We will directly use the issue in the project tracker.

Project tracker: https://github.com/orgs/dmlc/projects/2

## Description

Short syntax: A.T

**Comment by jermainewang** [comment]
Done in https://github.com/dmlc/dgl_sparse_dev/pull/8
