### ISSUE TITLE
[Roadmap] Sparse Matrix API

### ISSUE THREAD

**Issue by jermainewang** [dmlc/dgl#4427]
This is the roadmap issue for the development of sparse matrix API. The general goal is to provide sparse matrix and its operations as user-facing APIs for expressing models that cannot be easily written in message passing style interface. We will deliver this in two phases:
* *Phase 1*: Mock up a Python library that includes the most necessary APIs. Finish all the API documentation. Unblock tutorial and exercise development. Use the simplest possible way of implementation.
* *Phase 2*: Continue fix API issues. Finish all low-level implementation such as packaging it as a native PyTorch library, high-performance CUDA kernels, Torchscript compatibility, etc.

Phase 1 tasks:
- [x] #4408 
- [x] #4407 
- [x] #4412 
- [x] #4413 
- [x] #4414 
- [x] #4415 
- [x] #4489
- [x] #4416 
- [x] #4417 
- [x] #4418 
- [x] #4419 
- [x] #4420 
- [ ] #4421 
- [ ] #4422 
- [ ] #4423 
- [x] #4490
- [x] #4491
- [x] #4492
- [x] #4493
- [x] #4494

Phase 2 tasks:
- [x] #4425 
- [x] #4818
- [x] #4819 
- [x] #4820 
- [x] #4852 
- [x] #4854 
- [x] #4855 
- [x] #4856 
- [x] #4857 
- [x] #4858 
- [x] #4859 
- [x] #4926
- [x] #4860 
- [x] #4861 
- [x] #4862 
- [x] #4863

**Comment by frozenbugs** [comment]
Closed as DGL 1.0 launched.
