### ISSUE TITLE
[RFC] [DataLoader] Decoupling FeatureStorage from GraphStorage

### ISSUE THREAD

**Issue by BarclayII** [dmlc/dgl#4443]
## 🚀 Feature
Add two methods `attach_ndata` and `attach_edata` to the DataLoader so that graph sampling on DGLGraphs can still use other FeatureStorage implementations.

## Motivation
Currently the DataLoader supports sampling from custom graph implementations with custom feature storage implementations.  However, if one wants to reuse DGLGraph for graph sampling but use some other feature storages, he/she has to implement a wrapper class of DGLGraph.  Given that DGL no longer supports creating a graph by directly instantiating a `DGLGraph` object, I don't think having a wrapper class is the most straightforward UX:

```python
class Wrapper(object):
    def __init__(g: DGLGraph, node_storage, edge_storage):
        self.g = g
        self.node_storage = node_storage   # dict[str, dict[str, FeatureStorage]]
        self.edge_storage = edge_storage   # dict[str, dict[str, FeatureStorage]]
    def __getattr__(self, key):
        # to reuse the methods from DGLGraph such as `sample_neighbors` etc.
        return getattr(self.g, key)
    def get_node_storage(self, key, ntype=None):
        return self.node_storage[key][ntype]
    def get_edgee_storage(self, key, etype=None):
        return self.edge_storage[key][etype]
```

## Alternatives

See above.

## Pitch

Add two methods to `DataLoader`: `attach_ndata` and `attach_edata`.
```python
def attach_ndata(self, key, feature_storage, ntype=None):
    pass
def attach_edata(self, key, feature_storage, etype=None):
    pass
```

The DataLoader already has an `attach_data` method for prefetching features that are neither node data nor edge data.  `attach_ndata` and `attach_edata` will just follow suit.
If `attach_ndata` and `attach_edata` has not been called, the DataLoader will fall back to calling `get_node_storage` and `get_edge_storage` to get the underlying FeatureStorage object.

Example:
```python
g = dgl.graph(...)
train_idx = ...
sampler = dgl.dataloading.NeighborSampler([5, 10, 15], prefetch_node_feats=['feat', 'feat2'])
dl = dgl.dataloading.DataLoader(g, train_idx, sampler, shuffle=True, batch_size=1000)
# RedisFeatureStorage is some custom FeatureStorage implementation.
dl.attach_ndata('feat2', RedisFeatureStorage(...))
for input_nodes, output_nodes, blocks in dl:
    # If attach_ndata hasn't been called for a given key, the DataLoader will go to
    # g.get_node_storage() and get the appropriate FeatureStorage (g.ndata in this case).
    print(blocks[0].srcdata['feat'])
    # If attach_ndata is called, the DataLoader will use the attached FeatureStorage
    # instead (RedisFeatureStorage in the example above).
    print(blocks[0].srcdata['feat2'])
```

**Comment by mufeili** [comment]
Could you provide some example scenarios for other feature storages?

**Comment by yaox12** [comment]
> Could you provide some example scenarios for other feature storages?

For example in https://github.com/dmlc/dgl/pull/4341, one has to implement a `CachedDGLGraph` wrapper to use `DGLGraph` with the contributed `GPUCachedTensorStorage`.

**Comment by yaox12** [comment]
I have been working on this. It's a pretty minor modification containing about 10 lines of code. Copy and paste two comments from the doc:
1) Should we pass FeatureStorage through a method `attach_ndata(key, feature_storage, ntype)` or the constructor of DataLoader?
2) Should FeatureStorage be a tensor-like object or dictionary of tensors?

`attach_ndata()` + tensor-like object is easier to use, compared to constructing a dictionary like `{(key, ntype) : FeatureStorage}`, while constructor + dictionary is more elegant from the perspective of API design.

**Comment by frozenbugs** [comment]
This work has been taken up by Graphbolt, a new dataloading framework by DGL.
