### ISSUE TITLE
install dgl by pip but lake some dll on windows

### ISSUE THREAD

**Issue by macroxmu** [dmlc/dgl#445]
## To Reproduce

I install dgl with command: 
`pip install dgl 
`
Install pytorch with :
`pip install https://download.pytorch.org/whl/cpu/torch-1.0.1-cp37-cp37m-win_amd64.whl
`
While I using "import dgl" in python, it show an error message box said it lake some dll such as 'libwinpthread-1.dll'

I found it doesn't just lake just a file named 'libwinpthread-1.dll' but a serious if dll with gcclib, etc.... I download then one by one but it's hard to find a correct dll file.
Can we provide a library package for dgl user under windows?

## Environment

 - DGL Version (e.g., 1.0): by pip
 - Backend Library & Version :PyTorch 1.0.1
 - OS (e.g., Linux):windows 7
 - How you installed DGL :pip
 - Python version:3.7.0
 - CUDA/cuDNN version (if applicable):NO GPU

**Comment by VoVAllen** [comment]
Do you have GCC/Mingw installed?

**Comment by BarclayII** [comment]
Currently 0.2 Windows conda/pip package is delayed.  We expect to release it soon.

**Comment by BarclayII** [comment]
DGL 0.2 for Windows is released on Conda and Pip.  Please feel free to reopen this issue if it doesn't work.
