### ISSUE TITLE
Just a little output mistake ?

### ISSUE THREAD

**Issue by zhangnuc** [dmlc/dgl#4458]
## 📚 Documentation

the website is : https://docs.dgl.ai/tutorials/blitz/2_dglgraph.html#sphx-glr-tutorials-blitz-2-dglgraph-py .the part is "Another common transformation is to add a reverse edge for each edge in the original graph with dgl.add_reverse_edges." 

 there is an example for undirected graph .BUT , the code "newg.edges()" can output nothing in python terminal .so i change it into print(newg.edges()) ,and then i got the right output like the docs shows . 

So ,if there exists a mistake in the docs ?

**Comment by Rhett-Ying** [comment]
if you're running the tutorial commands in inter-active python terminal, it will be printed. Anyway, add `print` explicitly is better.
