### ISSUE TITLE
[DISCUSSION] On the proper way to inherit batch graph structure when creating new graph

### ISSUE THREAD

**Issue by HQ01** [dmlc/dgl#446]
## 🚀 Feature

When implementing models that will create new graphs on the fly (such as diffpool), the newly created graph will not inherit the original BatchedGraph properties (it will just be a graph!). which makes seg_sum, seg_max much more difficult. What will be the ideal way to finish this?

**Comment by jermainewang** [comment]
Could you call `dgl.batch` on the fly?

**Comment by HQ01** [comment]
I think unbatch then batch again could solve this.
