### ISSUE TITLE
I find a link failed in the User Guide 

### ISSUE THREAD

**Issue by zhangnuc** [dmlc/dgl#4464]
## 📚 Documentation

 In the "User Guide 6.1 Training GNN for Node Classification with neighbourhood sampling" ，which website of https://docs.dgl.ai/guide/minibatch-node.html#guide-minibatch-node-classification-sampler ,  the part "Training Loop" has something wrong 
In the part "Training Loop" tell me that “DGL provides an end-to-end stochastic training example ” ，but the link of this is failed 
![image](https://user-images.githubusercontent.com/93856240/186559447-8c476a8b-57d4-40cf-9853-e87464a0caaf.png)

![image](https://user-images.githubusercontent.com/93856240/186559402-8666185b-21c0-4dcd-bbb5-3c3c9eea0168.png)

AND , Maybe the link now should point to https://github.com/dmlc/dgl/blob/master/examples/pytorch/graphsage/node_classification.py

**Comment by Rhett-Ying** [comment]
thanks for your reporting...
