### ISSUE TITLE
Cannot build DGL documentation

### ISSUE THREAD

**Issue by as51340** [dmlc/dgl#4484]
## 🐛 Bug

Hi, I wanted to add some changes to the documentation, that deals with this issue I opened `https://github.com/dmlc/dgl/issues/4453`. However, when I want to build the docs using `make html` I get the following output:

![image](https://user-images.githubusercontent.com/53269502/187408587-830820f1-d2a7-4293-a23f-b891216415b6.png)

## To Reproduce

Steps to reproduce the behaviour:

1. `git clone --recurse-submodules https://github.com/dmlc/dgl.git`
2. `sudo apt-get update`
3. `sudo apt-get install -y build-essential python3-dev make cmake`
4. `cd dgl`
5. `mkdir build`
6. `cd build`
7. `cmake ..`
8. `make -j4`
9. `cd ../python`
10. `sudo python setup.py install`
11. `cd ../docs`
12. `./clean.sh`
13. `make html`

I installed all packages stated here `https://github.com/dmlc/dgl/tree/master/docs`.

## Expected behaviour

Documentation generated without errors.

## Environment

 - DGL Version: 0.9
 - Backend Library & Version:
    `torch==1.12.1+cpu`
    `mxnet==1.9.1`
    `Sphinx==5.0.2`
    `sphinx-copybutton==0.5.0` 
    `sphinx-gallery==0.11.1`
    `sphinx-rtd-theme==1.0.0`
    `sphinxcontrib-applehelp==1.0.2`
    `sphinxcontrib-devhelp==1.0.2`
    `sphinxcontrib-htmlhelp==2.0.0`
    `sphinxcontrib-jsmath==1.0.1`
    `sphinxcontrib-qthelp==1.0.3`
    `sphinxcontrib-serializinghtml==1.1.5`
 - OS : Ubuntu 20.04.4 LTS(Focal Fossa)
 - How you installed DGL: source
 - Build command you used: Specified above
 - Python version: `3.8.10`
 - CUDA/cuDNN version (if applicable): None
 - GPU models and configuration (e.g. V100): None
 - Any other relevant information:

**Comment by jermainewang** [comment]
Building the doc requires DGL can be correctly imported. Could you double confirm?

**Comment by jermainewang** [comment]
Could you try `python -c 'from dgl.dataloading import DataLoader'` at the location you are building the doc?

**Comment by as51340** [comment]
I tried, and the command exits successfully but building docs results in the same error:
![Screenshot from 2022-09-01 09-20-22](https://user-images.githubusercontent.com/53269502/187855896-a64b6895-cb58-4f40-83eb-5e387e0f6b52.png)

**Comment by jermainewang** [comment]
Oh, I see what happened. It tries to build MXNet tutorials but `dataloader` package is not available for MXNet. Could you try `make pytorch` instead?

**Comment by as51340** [comment]
> Oh, I see what happened. It tries to build MXNet tutorials but `dataloader` package is not available for MXNet. Could you try `make pytorch` instead?

It builds but I had to install `nltk`, `seaborn`,`ogb`, `rdflib` which I think, is not mentioned in any place. But yes, now I have docs running locally, thank you!

**Comment by jermainewang** [comment]
> It builds but I had to install `nltk`, `seaborn`,`ogb`, `rdflib` which I think, is not mentioned in any place

Thanks for the report. We will fix the README.
