### ISSUE TITLE
For DGL, how to measure the time of transfering features and labels from cpu to gpu?

### ISSUE THREAD

**Issue by swordfate** [dmlc/dgl#4485]
## ❓ Questions and Help
I know we can use `mfg.srcdata['feat']` to get feature from CPU to GPU, but it is a lazy operator. The transferring will not happen until it is required to be computed when model forwarding. I don't know how to measure the real time of transferring features and labels respectively.

I use the following code, but it seems not right.
```python
with torch.autograd.profiler.record_function('cpu-gpu-load'):
        inputs = mfgs[0].srcdata['feat']
        labels = mfgs[-1].dstdata['label']
```
Looking forward to any reply~

**Comment by jermainewang** [comment]
CUDA event is the recommended way for timing. Here is a timer we used in our benchmarks: https://github.com/dmlc/dgl/blob/master/benchmarks/benchmarks/utils.py#L545

**Comment by swordfate** [comment]
> CUDA event is the recommended way for timing. Here is a timer we used in our benchmarks: https://github.com/dmlc/dgl/blob/master/benchmarks/benchmarks/utils.py#L545

Thanks for your reply. 
I see CUDA event in the link. However, I doubt that CUDA event can't force feature/label transfer from CPU to GPU immediately in the code `inputs = mfgs[0].srcdata['feat']`. It is said the transferring will happen automatically only when it is used. Will CUDA event and sync will force the data movement?

**Comment by jermainewang** [comment]
> I want to figure out the reasons. Will CUDA event trigger the feature transfer from CPU to GPU immediately? I will be very grateful if you could give me any hints!

No. CUDA event can be viewed as a micro kernel that takes almost no time. As you may know, most GPU kernels are asynchronous and CUDA uses a queue-like runtime to execute them (called stream). The idea behind CUDA event timer is to schedule one event before the kernel to be timed and one event after, so that the time interval between the two events is exactly the running time of that kernel.

> Is it because Graph Topology has been sent to GPU after enumerate trainer_dataloader, thus mfgs.device is CUDA?

That's right. The Dataloader argument `device` specifies which device the returned MFGs should be copied to.

**Comment by swordfate** [comment]
> > I want to figure out the reasons. Will CUDA event trigger the feature transfer from CPU to GPU immediately? I will be very grateful if you could give me any hints!
> 
> No. CUDA event can be viewed as a micro kernel that takes almost no time. As you may know, most GPU kernels are asynchronous and CUDA uses a queue-like runtime to execute them (called stream). The idea behind CUDA event timer is to schedule one event before the kernel to be timed and one event after, so that the time interval between the two events is exactly the running time of that kernel.
> 
> > Is it because Graph Topology has been sent to GPU after enumerate trainer_dataloader, thus mfgs.device is CUDA?
> 
> That's right. The Dataloader argument `device` specifies which device the returned MFGs should be copied to.

It's really a clear and helpful answer, thanks a lot !
I will close this issue and reopen it when it is necessary. Have a nice day :)
