### ISSUE TITLE
Support CI stage for CUDA 11.x

### ISSUE THREAD

**Issue by isratnisa** [dmlc/dgl#4501]
## 🚀 Feature
Current CI is based on only CUDA 10.2. We need to support later versions such as 11.0 to resolve and test issues (e.g., [issue 3444](https://github.com/dmlc/dgl/issues/3444))

## Motivation
Issue [3444](https://github.com/dmlc/dgl/issues/3444)

## Alternatives
Disable CSRGEMM APIs in CUDA 11.0 and used the obsolete CSRGEMM from CUDA 10.2 APIs.

**Comment by BarclayII** [comment]
PyTorch 1.13 now deprecated CUDA 10.2 support so the priority needs to be adjusted a little.

**Comment by mfbalin** [comment]
Are there any plans on deprecating CUDA 10.2 support for DGL? DGL dependencies such as thrust and CUB dropped support for it in their latest releases. For example, #5648 requires updating thrust and CUB.

**Comment by Rhett-Ying** [comment]
Hi @mfbalin  what's the minimum CUDA version required by #5648 ?

**Comment by mfbalin** [comment]
Hi @Rhett-Ying, that PR seems to successfully compile on the nvcr.io/nvidia/pytorch:20.12-py3 container which has CUDA 11.1.1. I am not sure if that is the lowest version that will compile though.

**Comment by Rhett-Ying** [comment]
Thanks for your info. We'll discuss the deprecation and get back to you as soon as possible.

**Comment by mfbalin** [comment]
@Rhett-Ying any news on CUDA 10.2 support/deprecation?

**Comment by Rhett-Ying** [comment]
@mfbalin We have added this into our special topic and will discuss it this Thursday.

**Comment by mfbalin** [comment]
Lowest supported cuda version is 11 now. Reopen if unresolved.
