### ISSUE TITLE
Distributed Training Without Using Sampler & DataLoader

### ISSUE THREAD

**Issue by EntongL** [dmlc/dgl#4504]
Hi,
I followed the distributed training instruction and the given GCN example with cora graph dataset, and tried to create a distributed training without using sampler and dataloader, but I found that DistGraph is not a valid input for GCN forward. Is it always needed to use sampler & dataloader when doing distributed training? Any suggestions are appreciated.

**Comment by jermainewang** [comment]
You are right that DGL currently only supports distributed training with mini-batch sampling.

**Comment by EntongL** [comment]
Got it, thank you!
