### ISSUE TITLE
error in GNNExplainer

### ISSUE THREAD

**Issue by yudizhangzyd** [dmlc/dgl#4506]
## 🐛 Bug
Hi I was trying to use GNNExplainer function, but had an error.
Although I have an hetero graph, this error seems not about that? Thanks.

## Error message

---------------------------------------------------------------------------
TypeError                                 Traceback (most recent call last)
Input In [25], in <cell line: 3>()
      1 explainer = GNNExplainer(model, num_hops=1)
      2 features = g.nodes['target'].data['features']
----> 3 feat_mask, edge_mask = explainer.explain_graph(g, features)

File ~/anaconda3/envs/pygnn/lib/python3.9/site-packages/dgl/nn/pytorch/explain/gnnexplainer.py:395, in GNNExplainer.explain_graph(self, graph, feat, **kwargs)
    393 # Get the initial prediction.
    394 with torch.no_grad():
--> 395     logits = self.model(graph=graph, feat=feat, **kwargs)
    396     pred_label = logits.argmax(dim=-1)
    398 feat_mask, edge_mask = self._init_masks(graph, feat)

File ~/anaconda3/envs/pygnn/lib/python3.9/site-packages/torch/nn/modules/module.py:1130, in Module._call_impl(self, *input, **kwargs)
   1126 # If we don't have any hooks, we want to skip the rest of the logic in
   1127 # this function, and just call forward.
   1128 if not (self._backward_hooks or self._forward_hooks or self._forward_pre_hooks or _global_backward_hooks
   1129         or _global_forward_hooks or _global_forward_pre_hooks):
-> 1130     return forward_call(*input, **kwargs)
   1131 # Do not call functions when jit is used
   1132 full_backward_hooks, non_full_backward_hooks = [], []

TypeError: forward() got an unexpected keyword argument 'graph'

**Comment by mufeili** [comment]
1. I don't think `GNNExplainer` supports heterogeneous graphs now.
2. What's the definition of your `model.forward` function? Does it have a `graph` argument?

**Comment by yudizhangzyd** [comment]
Like this:
    def forward(self, g, features):
        # get embeddings for all node types. for user node type, use passed in user features
        h_dict = {ntype: emb for ntype, emb in self.embed.items() if ntype != 'target'}
        h_dict['target'] = features
        # pass through all layers
        for i, layer in enumerate(self.layers[:-1]):
            if i != 0:
                h_dict = {k: F.leaky_relu(F.dropout(h, p=self.dropout, training=self.training)) for k, h in h_dict.items()}      
            h_dict = layer(g, h_dict) 
        self.target_embeddings = h_dict['target']
        # get user logits
        return self.layers[-1](h_dict['target'])

**Comment by mufeili** [comment]
As documented [here](https://docs.dgl.ai/generated/dgl.nn.pytorch.explain.GNNExplainer.html#dgl.nn.pytorch.explain.GNNExplainer), the `model` is required to take arguments `graph` and `feat`. So either you can modify the forward function to have `def forward(self, graph, feat):` or you can define some wrapper function.

**Comment by yudizhangzyd** [comment]
I think g is already the graph and feat are my features, you mean simply change the name?

**Comment by mufeili** [comment]
> I think g is already the graph and feat are my features, you mean simply change the name?

Yes.

**Comment by peizhou001** [comment]
Hi, I am closing this issue assuming you are happy about our response. Feel free to follow up and reopen the issue if you have more question with regard to our response.
