### ISSUE TITLE
num_workers>0 in Dataloader got ERROR: Prefetcher thread timed out at 30 seconds.

### ISSUE THREAD

**Issue by swordfate** [dmlc/dgl#4509]
## ❓ Questions and Help
When I run the code in tutorial (https://docs.dgl.ai/en/0.8.x/tutorials/multi/2_node_classification.html#sphx-glr-tutorials-multi-2-node-classification-py), it works well. However, after changing the dataset to a larger one `ogbn-products` and num_workers >0 in dataloader, it got error `RuntimeError: Prefetcher thread timed out at 30 seconds.`

In my understanding, when num_workers>0, some processings are doing sampling and  transferring graph topology to GPU simultaneously (maybe a queue in GPU storing the sampled topology?). I can not figure out why this error happens. Maybe I misunderstanding something.

If you could give some hints, I would be very grateful :)

**Comment by BarclayII** [comment]
Hmm the code worked well for me.  I noticed that you are looking at the 0.8.x documentation.  Could you try the 0.9.x documentation again? https://docs.dgl.ai/tutorials/multi/2_node_classification.html#sphx-glr-tutorials-multi-2-node-classification-py

If not, could you give the following information:
* PyTorch version (+CUDA)
* DGL version (+CUDA)
* CUDA driver and runtime version
* CPU memory
* Number of GPUs and GPU memory

**Comment by swordfate** [comment]
After I changed to another machine, the error disappeared. Maybe it is because the CPU is weak. I will close this issue. 
Thanks a lot anyway.

**Comment by amirassov** [comment]
@swordfate I also got such problem. To solve for a weak server you can make the environment parameter [`DGL_PREFETCHER_TIMEOUT`](https://github.com/dmlc/dgl/blob/master/python/dgl/dataloading/dataloader.py#L39) larger than 30.
