### ISSUE TITLE
Reduce the startup overhead in DistDGL

### ISSUE THREAD

**Issue by zheng-da** [dmlc/dgl#4514]
## 🔨Work Item

For a graph with 4B nodes and 30B edges, if we load the graph with 10 partitions on 10 machines, it takes more than one hour to load the graph and start distributed training. It's very painful to debug on such a large graph. We should reduce the startup overhead and reduce the startup time to around 10 minutes.

**IMPORTANT:**
* This template is only for dev team to track project progress. For feature request or bug report, please use the corresponding issue templates.
* DO NOT create a new work item if the purpose is to fix an existing issue or feature request. We will directly use the issue in the project tracker.

Project tracker: https://github.com/orgs/dmlc/projects/2

## Description

Currently, DistDGL takes a long time to load data and initialize the data for distributed training. There are multiple places we can improve to reduce the overhead:
- [x] avoid checking the loaded data (https://github.com/dmlc/dgl/blob/master/python/dgl/distributed/partition.py#L100-L119). checking the loaded graph structure is both time consuming and memory consuming. we should disable by default and only enable it for the debug mode.
- [ ] avoid converting the format (https://github.com/dmlc/dgl/blob/master/python/dgl/distributed/dist_graph.py#L351-L352). we should prepare the right format during the graph partitioning.
- [ ] avoid sorting (https://github.com/dmlc/dgl/blob/master/python/dgl/distributed/dist_graph.py#L354-L360). we should prepare the right format during the graph partitioning.

**Comment by jermainewang** [comment]
The task needs some breakdown. @Rhett-Ying could you pls have a look and think of how many PRs will this require? I remember you've already started on some of them.

**Comment by Rhett-Ying** [comment]
- [ ] avoid checking loaded data. 1 PR for enable/disable it. 1 PR for improving checking logic to be more memory efficient. Total: 2 PRs.
- [ ] avoid converting graph format. This depends on this open PR:  [Feature] enable to save graphs in multiple formats #[4266](https://github.com/dmlc/dgl/pull/4266) . Once it's ready, we could improve `dgl.distributed.partition_graph()` and the new distributed partition pipeline. Total: 3 PRs.
- [ ] avoid sorting. Total: 1 PR.

In total, 6 PRs are required and most of them are in small size. `[Feature] enable to save graphs in multiple formats` is probably the most time-consuming one.

**Comment by nv-dlasalle** [comment]
I take it this is meant to close #4474?

**Comment by Rhett-Ying** [comment]
@zheng-da If we implement all the items mentioned above, can we reach the target: `reduce the startup time to around 10 minutes.`? This seems too fast. How much time would it take to read such size of data into RAM?

**Comment by jermainewang** [comment]
@Rhett-Ying You can do some brief estimation. For a graph with 4B nodes/30B edges, we can assume each partition has 400 * r million nodes and 3 billion edges if partitioned into 10 pieces, where r is the expansion rate depends on the number of halo nodes introduced by the partition algorithm. Suppose we save two formats, CSR and COO, then:

For CSR:
* Indptr array takes 400 * r * 8 MB = 3.2r GB
* Indices array takes 3 * 8 GB = 24 GB

For COO:
* Two arrays, each is 3 * 8 GB, so the total amount is 48 GB

That gives a total size of (72+3.2r) GB. As METIS is usually good at finding minimal edge cut, we can have a rough estimation of 80GB amount of graph structure data to be loaded into memory. As SSD sequential read bandwidth can achieve Giga Byte per second, the 10 minutes startup time is a quite loose margin.

**Comment by Rhett-Ying** [comment]
node/edge feature data should be taken in account? node feature: 4B * 4Byte * 50dim / 10parts = 80GB.

**Comment by Rhett-Ying** [comment]
quick try with below partition:
```
-rw-r--r-- 1 root root  24 Aug 26 12:08 edge_feat.dgl
-rw-r--r-- 1 root root 15G Aug 26 11:54 graph.dgl
-rw-r--r-- 1 root root 25G Aug 28 08:17 node_feat.dgl
```

volume info: gp2, 16000 IOPS

consumed times in seconds(all items mentioned in description are implemented, namely, no additional check, no format conversion, COO only, no csr/csc sort):
```
Function 'load_graph' executed in 15.3831s
Function 'format_graph' executed in 0.0003s
Function 'move_graph_to_shm' executed in 7.6452s
Function 'load_feats' executed in 15.4655s
Function 'move_feats_to_shm' executed in 18.3293s
```

In contrast, if `graph_formats=('csc', 'coo')`, namely, csc will be created in run-time:
```
Function 'load_graph' executed in 14.2881s
Function 'format_graph' executed in 10.9102s
Function 'move_graph_to_shm' executed in 11.9455s
Function 'load_feats' executed in 13.4544s
Function 'move_feats_to_shm' executed in 18.2134s
```

**Comment by Rhett-Ying** [comment]
load partition which has similar size from EFS takes much longer than local disk.

```
total 37G
-rw-r--r-- 1 root root 1.8G Sep  6 09:59 edge_feat.dgl
-rw-r--r-- 1 root root  13G Sep  6 10:00 graph.dgl
-rw-r--r-- 1 root root  23G Sep  6 09:59 node_feat.dgl
load random
Function 'load_graph' executed in 94.1818s
Function 'format_graph' executed in 7.8912s
Function 'move_graph_to_shm' executed in 11.0029s
Function 'load_feats' executed in 194.5931s
Function 'move_feats_to_shm' executed in 26.9093s
```

**Comment by jermainewang** [comment]
Might be related to https://github.com/dmlc/dgl/issues/4636

**Comment by Rhett-Ying** [comment]
different from #4636 which is mainly about loading multiple graphs. the potential bottleneck here is storage type, namely, where the data lies. local disk, EFS, NFS? and they may differ a lot.

**Comment by Rhett-Ying** [comment]
@zheng-da which storage are you usually using to save partitions? any estimation on graph loading from storage to RAM? simultaneous loading.

**Comment by Rhett-Ying** [comment]
load from remote storage via NFS:

```
total 39G
-rw-r--r-- 1 root root  24 Aug 26 12:08 edge_feat.dgl
-rw-r--r-- 1 root root 15G Aug 26 11:54 graph.dgl
-rw-r--r-- 1 root root 25G Aug 28 08:17 node_feat.dgl
load random
Function 'load_graph' executed in 31.1309s
Function 'format_graph' executed in 11.4887s
Function 'move_graph_to_shm' executed in 12.1097s
Function 'load_feats' executed in 42.5451s
Function 'move_feats_to_shm' executed in 18.2032s
```

**Comment by jermainewang** [comment]
@Rhett-Ying Does your profiling already include the potential fixes (e.g., no checking, no format conversion, no sorting) or not?

**Comment by Rhett-Ying** [comment]
No, as I used the official release of `0.9.1`.

**Comment by jermainewang** [comment]
I see. Could you further benchmark it on heterogeneous graphs?

**Comment by Rhett-Ying** [comment]
fake partition(`560M nodes, 4.2B edges`), `r6i.metal`, `EBS`.
```
total 252G
-rw-rw-r-- 1 ubuntu ubuntu   24 Oct 18 08:49 edge_feat.dgl
-rw-rw-r-- 1 ubuntu ubuntu 174G Oct 18 08:44 graph.dgl
-rw-rw-r-- 1 ubuntu ubuntu  79G Oct 18 08:49 node_feat.dgl
---- load_graphs() takes 75.68613576889038s
------- checking nodes takes 6.60115647315979s
------- checking edges takes 64.7132716178894s
load random
Function 'load_graph' executed in 148.0332s
Function 'format_graph' executed in 61.2462s
Function 'sort_edges' executed in 49.5095s
Function 'move_graph_to_shm' executed in 197.3203s
Function 'load_feats' executed in 34.4718s
Function 'move_feats_to_shm' executed in 50.2369s
```
This result shows `checking node/edges`, `create new format`, `sorting edges` are **non-trivial** operations and should be removed.
