### ISSUE TITLE
Running error with dgl-cuda116

### ISSUE THREAD

**Issue by Ereboas** [dmlc/dgl#4522]
## 🐛 Bug

Code in https://github.com/dmlc/dgl/tree/master/examples/pytorch/ogb/seal_ogbl failed, if we change the GPU device to run on. And the error happens with `pytorch 1.12.0(cu116)` + `dgl-cu116`, but everything's well with `pytorch 1.12.0` + `dgl-cu113`.
See https://github.com/dmlc/dgl/pull/4291#issuecomment-1235597423 for more details.

## To Reproduce

1. Simply change the GPU device to run on (i.e. change `cuda` to `cuda:1` in line 417)
1. Error occurs whether running the code from command line or using debugger.

## Expected behavior

No error occurs. 

## Environment

 - DGL Version (e.g., 1.0): `dgl-cu116: 0.9.0`
 - Backend Library & Version (e.g., PyTorch 0.4.1, MXNet/Gluon 1.3): `Pytorch 1.12.0(Build: py3.9_cuda11.6_cudnn8.3.2_0)`
 - OS (e.g., Linux): `Linux`
 - How you installed DGL (`conda`, `pip`, source): `pip`
 - Python version: `3.9.13`
 - CUDA/cuDNN version (if applicable): `CUDA: 11.6.124` `cuDNN: 8.4.1`

**Comment by BarclayII** [comment]
I get a different error regarding to `to_simple` complaining about int64 features when I use the default input arguments:
https://github.com/dmlc/dgl/blob/master/examples/pytorch/ogb/seal_ogbl/main.py#L386-L388

Other than that I couldn't reproduce the issue you have encountered.  My environment is PyTorch 1.12.0+cu116 and DGL master build.  You could try nightly:
```
pip install --pre dgl-cu116 -f https://data.dgl.ai/wheels-test/repo.html
```

Also, when will it throw the error?  Like, in the beginning or happens randomly?

**Comment by Ereboas** [comment]
> I get a different error regarding to `to_simple` complaining about int64 features when I use the default input arguments: https://github.com/dmlc/dgl/blob/master/examples/pytorch/ogb/seal_ogbl/main.py#L386-L388
> 
> Other than that I couldn't reproduce the issue you have encountered. My environment is PyTorch 1.12.0+cu116 and DGL master build. You could try nightly:
> 
> ```
> pip install --pre dgl-cu116 -f https://data.dgl.ai/wheels-test/repo.html
> ```
> 
> Also, when will it throw the error? Like, in the beginning or happens randomly?

I also get the `to_simple` error by default arguments.

For the other datasets, It doesn't throw the cuda error after switched to the nightly build(dgl-cu116 0.9a220908), seems that it only happens in dgl-cu116 0.9.0.

**Comment by frozenbugs** [comment]
Please verify this is not reproduceable on 1.0

**Comment by mufeili** [comment]
> I get a different error regarding to `to_simple` complaining about int64 features when I use the default input arguments: https://github.com/dmlc/dgl/blob/master/examples/pytorch/ogb/seal_ogbl/main.py#L386-L388
> 
> Other than that I couldn't reproduce the issue you have encountered. My environment is PyTorch 1.12.0+cu116 and DGL master build. You could try nightly:
> 
> ```
> pip install --pre dgl-cu116 -f https://data.dgl.ai/wheels-test/repo.html
> ```
> 
> Also, when will it throw the error? Like, in the beginning or happens randomly?

It's possible that other versions of CUDA internally cast the edge weights to float tensors. I've opened a PR for the fix.
