### ISSUE TITLE
UnifiedTensor uses cudaHostRegister, no need to specify device

### ISSUE THREAD

**Issue by chang-l** [dmlc/dgl#4535]
## 📚 Documentation
When I went over the doc for [UnifiedTensor](https://docs.dgl.ai/en/latest/api/python/dgl.contrib.UnifiedTensor.htmlr), it confused me... It seems `UnifiedTensor` uses `cudaHostRegister`/`cudaHostUnregister` to pin/unpin a tensor. However, it takes `device` as an input for target GPU accessing the map-in address. I thought in the code we specify the flag as `cudaHostRegisterDefault` which is automatically portable/mapped to all GPU devices, so I don't think `device` is needed for `UnifiedTensor`. And the description to `UnifiedTensor` also needs update.

Moreover, the demo in the doc is not working as well (after fixing the typo `16` --> `(16,)`):
```
import dgl
import torch
feats = torch.rand(128)
feats_gpu0 = dgl.contrib.UnifiedTensor(feats, device=torch.device('cuda:0'))
feats_gpu1 = dgl.contrib.UnifiedTensor(feats, device=torch.device('cuda:1'))
feats_gpu2 = dgl.contrib.UnifiedTensor(feats, device=torch.device('cuda:2'))

feats_idx_gpu0 = torch.randint(128, (16,), device='cuda:0')
feats_idx_gpu1 = torch.randint(128, (16,), device='cuda:1')
feats_idx_gpu2 = torch.randint(128, (16,), device='cuda:2')

sub_feat_gpu0 = feats_gpu0[feats_idx_gpu0]
sub_feat_gpu1 = feats_gpu1[feats_idx_gpu1]
sub_feat_gpu2 = feats_gpu2[feats_idx_gpu2]
```
I guess it is because the index select, https://github.com/dmlc/dgl/blob/11532198b628a977a1d61c802931afda2dd4edf2/python/dgl/contrib/unified_tensor.py#L99-L100 always launches at the current device (dev0), and it cannot access indexes residing at a different device (eg. feats_idx_gpu1). And in this example, as I mentioned, I think we only need to call `dgl.contrib.UnifiedTensor` once, in a single thread, so it can be accessed by all other devices or processes (if feats is in shared_memory already).  

Not sure if this issue can be related to https://github.com/dmlc/dgl/issues/4388 though......

**Comment by yaox12** [comment]
You're right. The C++ API doesn't use the device info in fact.
https://github.com/dmlc/dgl/blob/11532198b628a977a1d61c802931afda2dd4edf2/src/runtime/ndarray.cc#L547-L548

> the index select always launches at the current device (dev0), and it cannot access indexes residing at a different device

You're right. I got the same error.

> in a single thread, so it can be accessed by all other devices or processes (if feats is in shared_memory already).

The pinned status can be seen by all devices in the same process, but not for different processes. For multi-process multi-GPU use cases, e.g., DDP training, you should first place the tensor in shared memory, and then register it in every process.

**Comment by chang-l** [comment]
> For multi-process multi-GPU use cases, e.g., DDP training, you should first place the tensor in shared memory, and then register it in every process.

I see... Thanks.

**Comment by BarclayII** [comment]
BTW I think UnifiedTensor is deprecated.  Can you use `dgl.utils.{gather,scatter}_pinned_tensor_rows`?

**Comment by chang-l** [comment]
Thanks @BarclayII 
BTW, are these functions documented? If so, can you please drop me a pointer here?

**Comment by BarclayII** [comment]
They are not in the documentation but you can find it in `python/dgl/utils/pin_memory.py`.

**Comment by chang-l** [comment]
I see. Thanks.

**Comment by peizhou001** [comment]
@chang-l Do you have any further questions?
