### ISSUE TITLE
How Can I Prefetch specific nodes' feature in the training of minibatch 

### ISSUE THREAD

**Issue by zhangnuc** [dmlc/dgl#4536]
I read the code tell me the prefetch specified by dataloader can only select  **all**  the src nodes of the first layer GNN of the preloaded blocks. I want to load the selected nodes (maybe these nodes do not appear in the minibatch generated by this sampling), how should I achieve this? (This idea is about the paper : _PaGraph: Scaling GNN Training on Large Graphs via Computation-aware Caching_ )

Looking forward to your answer , thanks  u veryyyyy muuuuuch !

**Comment by jermainewang** [comment]
@BarclayII Could you take a look?

**Comment by BarclayII** [comment]
So far the prefetching pipeline only supports loading all ndoe features.  Maybe you could check out the official code for your specific setting (https://github.com/zhiqi-0/PaGraph) which is also based on DGL?

**Comment by zhangnuc** [comment]
I got it ! thks a lot ! ！！
Also the version of this code is about dgl 0.4.1 , which have some function deleated in dgl0.9.1 . Will these function be republished in the future ?

**Comment by BarclayII** [comment]
We are unlikely to add the deleted functions back to later versions.  Which of the functions do they use that don't appear in 0.9.1?  Maybe I could give you pointers for replacements.

**Comment by frozenbugs** [comment]
Hi zhangnuc, I am closing this issue assuming you are happy about our response. Feel free to follow up and reopen the issue if you have more questions with regard to our response.
