### ISSUE TITLE
dgl-master/examples/pytorch/graphsage

### ISSUE THREAD

**Issue by caoqichun** [dmlc/dgl#4537]
## ❓ Questions and Help
I am trying to train Grpahsage with two nodes.

python3 ~/workspace/dgl/tools/launch.py \
--workspace ~/workspace/dgl/examples/pytorch/graphsage/dist/ \
--num_trainers 4 \
--num_samplers 0 \
--num_servers 1 \
--part_config data/ogb-product.json \
--ip_config ip_config.txt \
"python3 train_dist.py --graph_name ogb-product --ip_config ip_config.txt --num_epochs 30 --batch_size 1000 --num_gpus 4"

Then I would get an Error:
The number of OMP threads per trainer is set to 36
cleanupu process runs
[14:45:44] /home/hkk/research/gnn/distributed/dgl/src/rpc/tensorpipe/tp_communicator.cc:102: TPReceiver starts to wait on [tcp://192.168.10.102:30050].
/home/hkk/miniconda3/envs/torch110py39cu102/lib/python3.9/site-packages/torch/distributed/launch.py:178: FutureWarning: The module torch.distributed.launch is deprecated
and will be removed in future. Use torchrun.
Note that --use_env is set by default in torchrun.
If your script expects `--local_rank` argument to be set, please
change it to read from `os.environ['LOCAL_RANK']` instead. See 
https://pytorch.org/docs/stable/distributed.html#launch-utility for 
further instructions

  warnings.warn(
[14:45:45] /home/hkk/research/gnn/distributed/dgl/src/rpc/rpc.cc:140: Sender with NetType~socket is created.
[14:45:45] /home/hkk/research/gnn/distributed/dgl/src/rpc/rpc.cc:159: Receiver with NetType~socket is created.
/home/hkk/miniconda3/envs/torch110py39cu102/lib/python3.9/site-packages/torch/distributed/launch.py:178: FutureWarning: The module torch.distributed.launch is deprecated
and will be removed in future. Use torchrun.
Note that --use_env is set by default in torchrun.
If your script expects `--local_rank` argument to be set, please
change it to read from `os.environ['LOCAL_RANK']` instead. See 
https://pytorch.org/docs/stable/distributed.html#launch-utility for 
further instructions

  warnings.warn(
Namespace(dataset=None, graph_name='ogbn-arxiv', id=None, ip_config='ip_config.txt', part_config=None, num_clients=None, n_classes=None, backend='gloo', num_gpus=-1, num_epochs=30, num_hidden=16, num_layers=2, fan_out='10,25', batch_size=1000, batch_size_eval=100000, log_every=20, eval_every=5, lr=0.003, dropout=0.5, local_rank=0, standalone=False, pad_data=False, net_type='socket')
ai-02 Initializing DGL dist
Warning! Interface: enp2s0 
IP address not available for interface.
Warning! Interface: virbr0-nic 
IP address not available for interface.
Namespace(dataset=None, graph_name='ogbn-arxiv', id=None, ip_config='ip_config.txt', part_config=None, num_clients=None, n_classes=None, backend='gloo', num_gpus=-1, num_epochs=30, num_hidden=16, num_layers=2, fan_out='10,25', batch_size=1000, batch_size_eval=100000, log_every=20, eval_every=5, lr=0.003, dropout=0.5, local_rank=0, standalone=False, pad_data=False, net_type='socket')
ai-01 Initializing DGL dist
Warning! Interface: wlp166s0 
IP address not available for interface.
Warning! Interface: virbr0-nic 
IP address not available for interface.
[14:45:46] /home/hkk/research/gnn/distributed/dgl/src/rpc/rpc.cc:140: Sender with NetType~socket is created.
[14:45:46] /home/hkk/research/gnn/distributed/dgl/src/rpc/rpc.cc:159: Receiver with NetType~socket is created.
terminate called after throwing an instance of 'std::runtime_error'
  what():  In operator() at tensorpipe/transport/connection_impl_boilerplate.h:249 "status.has_error()Error reading nop object: Unexpected Encoding Type"
bash: line 1: 59742 Aborted                 (core dumped) python3.9 train_dist.py --graph_name ogbn-arxiv --ip_config ip_config.txt --num_epochs 30 --batch_size 1000

**Comment by jermainewang** [comment]
@Rhett-Ying Could you take a look?

**Comment by Rhett-Ying** [comment]
I just encountered this issue too. I will fix it.

**Comment by caoqichun** [comment]
OS：Centos7 
DGL：0.9
torch: 1.10.2+cu102
cuda: 10.2

**Comment by Rhett-Ying** [comment]
before the launch which hit this issue, have you tried to launch dist train on the same nodes? and have you ever tried with `net_type=tensorpipe`? In current launch, I found the net_type is socket.

**Comment by caoqichun** [comment]
I am use default paramerters. The port(30050) is not occupied. I just tried to use net_type=tensorpipe. I am get an error: " AssertionError: net_type (tensorpipe) can only be 'socket'".

**Comment by Rhett-Ying** [comment]
```
terminate called after throwing an instance of 'std::runtime_error'
what(): In operator() at tensorpipe/transport/connection_impl_boilerplate.h:249 "status.has_error()Error reading nop object: Unexpected Encoding Type"
```
above error log is printed when you're using the default arguments, namely `socket` net_type? Right?

**Comment by caoqichun** [comment]
The param of "net_type' is 'socket'. I am sure.

**Comment by hookk** [comment]
> The param of "net_type' is 'socket'. I am sure.



> ```
> terminate called after throwing an instance of 'std::runtime_error'
> what(): In operator() at tensorpipe/transport/connection_impl_boilerplate.h:249 "status.has_error()Error reading nop object: Unexpected Encoding Type"
> ```
> 
> above error log is printed when you're using the default arguments, namely `socket` net_type? Right?

Yes, exactly. Following your suggestion, we (@caoqichun and me) launched the dist_train job with "net_type=tensorpipe" and the job abnormally exited with "AssertionError: net_type (tensorpipe) can only be 'socket' ".

**Comment by hookk** [comment]
> ```
> terminate called after throwing an instance of 'std::runtime_error'
> what(): In operator() at tensorpipe/transport/connection_impl_boilerplate.h:249 "status.has_error()Error reading nop object: Unexpected Encoding Type"
> ```
> 
> above error log is printed when you're using the default arguments, namely `socket` net_type? Right?

Yes, exactly. Following your suggestion, we (@caoqichun and me) launched the dist_train job with "net_type=tensorpipe" and the job abnormally exited with "AssertionError: net_type (tensorpipe) can only be 'socket' ".

**Comment by caoqichun** [comment]
I pull the latest version. Using the net_type='tensorpipe', this issue is not find.
