### ISSUE TITLE
Deprecations: transforms.functional, subgraph, convert

### ISSUE THREAD

**Issue by mufeili** [dmlc/dgl#4540]
## Description

Remove the deprecation candidates in:

- `dgl.transforms.functional`
- `dgl.subgraph`
- `dgl.convert`

and adjust the unit tests accordingly

**Comment by frozenbugs** [comment]
functional, subgraph are done.
convert is pending.

**Comment by frozenbugs** [comment]
As discussed with @peizhou001 , it is done.
