### ISSUE TITLE
[Code Style] Use f-string for string formatting

### ISSUE THREAD

**Issue by jermainewang** [dmlc/dgl#4545]
Literal String Interpolation (or f-string) was introduced in [PEP-498](https://peps.python.org/pep-0498/) in 2015. Compared with old string formatting (e.g., using % or `.format`), it has the advantage of being more succinct, easier-to-read and less error-prone in most cases. It is also the recommended practice for Python 3.6 (see [reference](https://realpython.com/python-string-formatting/#3-string-interpolation-f-strings-python-36)), even though it is not part of the PEP-8 standard.

cc @frozenbugs

**Comment by frozenbugs** [comment]
Yes, it is a good idea to use f-string in our code.
Let me see whether it is easy to setup a lint warning for it.
