### ISSUE TITLE
Is possible dgl.graph() can support any Query Language?

### ISSUE THREAD

**Issue by YijianLiu** [dmlc/dgl#4551]
## ❓ Questions and Help
 As for my requirement, is it possible that "dgl.graph()" can support any query language?
1.  Query language like gremlin, Cypher whether support dgl.graph() to query?
2. If not, is it possible I  use gremlin or cypher on dgl or achieve by myself.

**Comment by BarclayII** [comment]
DGL is not a graph database.  It is more focused on graph machine learning.  I would recommend to base your solution on an existing graph database, execute your graph query there, and convert the output to DGL for later use.
