### ISSUE TITLE
[Code Style] Lint is not enabled for `.cuh` files

### ISSUE THREAD

**Issue by yaox12** [dmlc/dgl#4552]
## 🐛 Bug

I bring this up since there have been some efforts on improving code style recently. 

Currently we are using `third_party/dmlc-core/scripts/lint.py` to check the code style of C++/CUDA codes,
https://github.com/dmlc/dgl/blob/11532198b628a977a1d61c802931afda2dd4edf2/tests/scripts/task_lint.sh#L5
in which `.cuh` files are not included.
```python
CXX_SUFFIX = set(['cc', 'c', 'cpp', 'h', 'cu', 'hpp'])
```

Related issue https://github.com/dmlc/dmlc-core/issues/403.

## Expected behavior

I think we could make a copy of the latest `third_party/dmlc-core/scripts/lint.py` and add `.cuh` to the checklist. cc @jermainewang

**Comment by jermainewang** [comment]
Agree. Currently we are using a linter script provided by dmlc-core which is not convenient to modify. We should have our own script so that we can enable some custom settings.
