### ISSUE TITLE
AttributeError: module 'dgl.dataloading' has no attribute 'DataLoader'

### ISSUE THREAD

**Issue by chentao691** [dmlc/dgl#4578]
## To Reproduce

1.
![0b4e5ecc1a7407e60210657c10c2134](https://user-images.githubusercontent.com/70051962/190621694-a755b65e-7b86-48a8-9ff4-5d88eb45f50a.jpg)

1.
![cf4d2cdd7efac36dc5c8d502adcab21](https://user-images.githubusercontent.com/70051962/190621788-1a8d3502-6cb3-4d87-ad96-6c16da9025de.jpg)

1.

## Environment

 - DGL Version (e.g., 1.0):
 - Backend Library & Version (e.g., PyTorch 0.4.1, MXNet/Gluon 1.3):
 - OS (e.g., Linux):
 - How you installed DGL (`conda`, `pip`, source):
 - Build command you used (if compiling from source):
 - Python version:
 - CUDA/cuDNN version (if applicable):
 - GPU models and configuration (e.g. V100):
 - Any other relevant information:

**Comment by chentao691** [comment]
DGL Version:0.7.1
PyTorch 1.8.1
dgl 0.7.1
scikit-learn 0.23.2
This is the version of the library I use

**Comment by frozenbugs** [comment]
Hi, I am closing this issue assuming you are happy about our response. Feel free to follow up and reopen the issue if you have more questions with regard to our response.

**Comment by fjycomes** [comment]
I have the same issue, my version is 1.1.2
![Uploading dgl.png…]()
