### ISSUE TITLE
Hilander setup needs to be updated 

### ISSUE THREAD

**Issue by guangyangsjc18** [dmlc/dgl#4588]
## 🐛 Bug

Following the setup instructions of [Hilander](https://github.com/dmlc/dgl/tree/master/examples/pytorch/hilander), with the dataloader defined as following:
```
def set_train_sampler_loader(g, k):
    fanouts = [k-1 for i in range(args.num_conv + 1)]
    sampler = dgl.dataloading.MultiLayerNeighborSampler(fanouts)
    print('batch size:', args.batch_size)
    # fix the number of edges
    train_dataloader = dgl.dataloading.DataLoader(
        g, torch.arange(g.number_of_nodes()), sampler,
        batch_size=args.batch_size,
        shuffle=True,
        drop_last=False,
        num_workers=args.num_workers
    )
    return train_dataloader
```
it will have this error
```
Traceback (most recent call last):
  File "train_model.py", line 88, in <module>
    train_dataloader = set_train_sampler_loader(gs[gidx], ks[gidx])
  File "train_model.py", line 77, in set_train_sampler_loader
    train_dataloader = dgl.dataloading.DataLoader(
TypeError: __init__() got multiple values for argument 'batch_size'
```
## To Reproduce

1. install the virtual env following guidelines in ReadMe
2. launch the training model script

## Expected behavior
it will have this error
```
Traceback (most recent call last):
  File "train_model.py", line 88, in <module>
    train_dataloader = set_train_sampler_loader(gs[gidx], ks[gidx])
  File "train_model.py", line 77, in set_train_sampler_loader
    train_dataloader = dgl.dataloading.DataLoader(
TypeError: __init__() got multiple values for argument 'batch_size'
```

## Environment

 - DGL Version (e.g., 1.0): 0.6.1 
 - Backend Library & Version (e.g., PyTorch 0.4.1, MXNet/Gluon 1.3):PyTorch 1.7.0 
 - OS (e.g., Linux): Linux
 - How you installed DGL (`conda`, `pip`, source): pip install dgl-cu102 # install dgl for cuda 10.2 
 - Build command you used (if compiling from source):
 - Python version: 3.8
 - CUDA/cuDNN version (if applicable): 10.2
 - GPU models and configuration (e.g. V100): V100
 - Any other relevant information:

**Comment by guangyangsjc18** [comment]
Upgrade dgl to 0.8.0 will cause pytorch version issue

**Comment by peizhou001** [comment]
Hi, @guangyangsjc18, we have a minimum version requirement of pytorch 1.9.0+ which can be found [here](https://www.dgl.ai/pages/start.html), could you update to new version and have a try?

**Comment by guangyangsjc18** [comment]
Hi, Sure. Just wants to give a heads up that the instructions on the page needs to be updated.

**Comment by peizhou001** [comment]
> Hi, Sure. Just wants to give a heads up that the instructions on the page needs to be updated.

Thanks for reminder, we are trying our effort to make our doc always updated.

**Comment by peizhou001** [comment]
This PR https://github.com/dmlc/dgl/pull/4587 fix this issue.
