### ISSUE TITLE
Replace third_party/nccl with PyTorch's NCCL backend

### ISSUE THREAD

**Issue by nv-dlasalle** [dmlc/dgl#4590]
## 🚀 Feature
Starting in PyTorch 1.11, `send` and `recv` are supported by `torch.distributed`, which largely means we no longer need direct access to NCCL.

To do this, we should change python/dgl/cuda/nccl.py to use `torch.distributed`, and remove `src/runtime/cuda/nccl_api.h` and `src/runtime/cuda/nccl_api.cu`.

Before we remove it however, we should verify the performance of `sparse_all_to_all_push` and `spares_all_to_all_pull` do not suffer.

## Motivation

Removing our own version of NCCL will simplify code as we can use the existing communicator created by `torch.disrtibuted`, reduce build times, and decrease the likely-hood of conflicts of two versions of the libraries (and possibly multiple communicators).

**Comment by yaox12** [comment]
After some investigation, `send` and `recv` have been added to `ProcessGroupNCCL` since PyTorch 1.8 https://github.com/pytorch/pytorch/pull/44921. The update of the support chart was delayed to 1.11.

So it should be safe to use `torch.distributed` since DGL is supporting PyTorch 1.9+.
