### ISSUE TITLE
Post processing ParMETIS output to enable graph partitioning pipeline to generate graph partitions

### ISSUE THREAD

**Issue by kylasa** [dmlc/dgl#4591]

**Comment by kylasa** [comment]
This script takes the parmetis output, which is a single file, and converts this into a set of files whose number is equal to the no. of node-types in the input graph. And each of these files will have only one number (integer) per row and this is the partition id for this node.

**Comment by jermainewang** [comment]
https://github.com/dmlc/dgl/pull/4605
