### ISSUE TITLE
AttributeError: 'DGLGraph' object has no attribute 'group_apply_edges'

### ISSUE THREAD

**Issue by haif-liu** [dmlc/dgl#460]
## 🐛 Bug

AttributeError: 'DGLGraph' object has no attribute 'group_apply_edges'

## To Reproduce

1.
1.
1.

## Environment

 - DGL Version (e.g., 1.0):
 - Backend Library & Version (e.g., PyTorch 0.4.1, MXNet/Gluon 1.3):
 - OS (e.g., Linux):
 - How you installed DGL (`conda`, `pip`, source):
 - Build command you used (if compiling from source):
 - Python version:
 - CUDA/cuDNN version (if applicable):
 - GPU models and configuration (e.g. V100):
 - Any other relevant information:

**Comment by VoVAllen** [comment]
I cannot reproduce the problem. Could you provide more information about your environment and DGL version?

**Comment by haif-liu** [comment]
It is the version problem and has been solved. Thanks!
