### ISSUE TITLE
ParMETIS fails to process synthetic graph in Chunked format (dglpart2 works but dglpart3 fails in this case)

### ISSUE THREAD

**Issue by kylasa** [dmlc/dgl#4607]

**Comment by jermainewang** [comment]
@kylasa We can close this but could you please paste the link to the commit in your forked repo here? Just for logging purpose.

**Comment by kylasa** [comment]
Following is the commit ID through which this code changes have been pushed onto to the github branch. 

d4b86e6ace4bdb273adad5e6be66f716431be1b9
(https://github.com/KarypisLab/ParMETIS/compare/dgl...kylasa:ParMETIS:dgl)

The code changes are very simple. The root cause is the problem with the 'irealloc' function call. 
if the newsize is same as the 'oldsize' when irealloc function is called then this executable will run into this error. 
The solution is to handle this case explicitly, wherever this function is called in dglpart3.c. Now we explicitly add `1` to the num_chunks to address this issue.
