### ISSUE TITLE
does dgl support CUDA computation?

### ISSUE THREAD

**Issue by klyao** [dmlc/dgl#461]
hello, 
  I try to run 9_gat.py with cuda by setting net = net.cuda(), but it occurs error

RuntimeError: Expected object of backend CPU but got backend CUDA for argument #2 'mat2'

  does dgl support CUDA computation?

**Comment by VoVAllen** [comment]
Hi,

Did you also add `features=features.cuda()`?

**Comment by klyao** [comment]
> Hi,
> 
> Did you also add `features=features.cuda()`?

Thanks! That's the problem!

I find that the cuda version is only 2 times faster than the cpu version.

**Comment by VoVAllen** [comment]
The main reason is currently we are lack of custom kernel support for softmax and scatter_max operation. Please stay tuned and we will update soon!

**Comment by jermainewang** [comment]
Hey, adding some experiences from my side. The speedup really depends on whether the computation can be accelerated by GPU or not. How long your model trains for one iter? If it's already very fast(e.g. several ms), then other factors will kick in like Python wrapper cost which cannot benefit from GPU. It all comes down to Amdahl's law.
