### ISSUE TITLE
RuntimeError: invalid argument (RGCN example: link prediction task)

### ISSUE THREAD

**Issue by giuseppefutia** [dmlc/dgl#463]
## 🐛 Bug

During the evaluation stage of the rgcn example (link prediction task), the following error is generated: 
RuntimeError: invalid argument 3: Index is supposed to be 1-dimensional at /pytorch/aten/src/TH/generic/THTensorEvenMoreMath.cpp:164

## To Reproduce

1. python3 link_predict.py -d FB15k-237 --gpu 0

## Environment

 - DGL Version (e.g., 1.0):
 - Backend Library & Version (e.g., PyTorch 0.4.1, MXNet/Gluon 1.3):
 - OS (e.g., Linux):
 - How you installed DGL (`conda`, `pip`, source):
 - Build command you used (if compiling from source):
 - Python version:
 - CUDA/cuDNN version (if applicable):
 - GPU models and configuration (e.g. V100):
 - Any other relevant information:

## Additional context

If you replace line 116 in https://github.com/dmlc/dgl/blob/master/examples/pytorch/rgcn/link_predict.py

`test_rel = torch.from_numpy(test_rel).view(-1, 1)`

with 

`test_rel = torch.from_numpy(test_rel)`

the bug should be fixed. 

If you agree, I can open a pull request for this change.

**Comment by ylfdq1118** [comment]
You are right. You can open a PR

**Comment by ylfdq1118** [comment]
Thanks @giuseppefutia
