### ISSUE TITLE
Does HGTConv require full graph to be passed in forward function?

### ISSUE THREAD

**Issue by saketguru** [dmlc/dgl#4643]
## ❓ Questions and Help

I am trying to execute `HGT` on `OGB MAG` using heterogeneous sampler.
I am using `HeteroNeighborSampler` from `dgl/examples/pytorch/rgcn-hetero/entity_classify_mb.py`.

However, I see that `HGTConv` requires us to pass the graph `G` in the forward function. However, since `G` is too big and I want to train `HGT` on GPU (16GB), I was wondering if there exists `HGTConv` implementation that does not have this restriction of passing huge `G` in the forward call.

**Comment by frozenbugs** [comment]
We are still working on the PR.

**Comment by jermainewang** [comment]
PR #4664 has added the support of mini-batch graph to HGTConv.
