### ISSUE TITLE
DGL compile incomplete

### ISSUE THREAD

**Issue by 123carmen** [dmlc/dgl#4657]
Please help me, what is the problem, I do not understand. thank you.this is the log.

(dglvenv) @sumo1:~/python/venv/dglvenv/lib/python3.6/site-packages$ git clone --recurse-submodules https://github.com/dmlc/dgl.git
Cloning into 'dgl'...
remote: Enumerating objects: 34070, done.
remote: Counting objects: 100% (658/658), done.
remote: Compressing objects: 100% (584/584), done.
remote: Total 34070 (delta 129), reused 408 (delta 71), pack-reused 33412
Receiving objects: 100% (34070/34070), 19.69 MiB | 23.42 MiB/s, done.
Resolving deltas: 100% (21824/21824), done.
Submodule 'third_party/METIS' (https://github.com/KarypisLab/METIS.git) registered for path 'third_party/METIS'
Submodule 'third_party/dlpack' (https://github.com/dmlc/dlpack.git) registered for path 'third_party/dlpack'
Submodule 'third_party/dmlc-core' (https://github.com/dmlc/dmlc-core.git) registered for path 'third_party/dmlc-core'
Submodule 'third_party/googletest' (https://github.com/google/googletest.git) registered for path 'third_party/googletest'
Submodule 'third_party/libxsmm' (https://github.com/hfp/libxsmm.git) registered for path 'third_party/libxsmm'
Submodule 'third_party/nanoflann' (https://github.com/jlblancoc/nanoflann) registered for path 'third_party/nanoflann'
Submodule 'third_party/nccl' (https://github.com/nvidia/nccl) registered for path 'third_party/nccl'
Submodule 'third_party/phmap' (https://github.com/greg7mdp/parallel-hashmap.git) registered for path 'third_party/phmap'
Submodule 'third_party/tensorpipe' (https://github.com/pytorch/tensorpipe) registered for path 'third_party/tensorpipe'
Submodule 'third_party/thrust' (https://github.com/NVIDIA/thrust.git) registered for path 'third_party/thrust'
Submodule 'third_party/tvm' (https://github.com/apache/incubator-tvm) registered for path 'third_party/tvm'
Submodule 'third_party/xbyak' (https://github.com/herumi/xbyak) registered for path 'third_party/xbyak'
Cloning into '/dglvenv/lib/python3.6/site-packages/dgl/third_party/METIS'...
remote: Enumerating objects: 381, done.
remote: Counting objects: 100% (95/95), done.
remote: Compressing objects: 100% (27/27), done.
remote: Total 381 (delta 73), reused 68 (delta 68), pack-reused 286
Receiving objects: 100% (381/381), 4.73 MiB | 17.40 MiB/s, done.
Resolving deltas: 100% (196/196), done.
Cloning into '/dglvenv/lib/python3.6/site-packages/dgl/third_party/dlpack'...
remote: Enumerating objects: 437, done.
remote: Counting objects: 100% (106/106), done.
remote: Compressing objects: 100% (43/43), done.
remote: Total 437 (delta 78), reused 68 (delta 61), pack-reused 331
Receiving objects: 100% (437/437), 1.69 MiB | 17.67 MiB/s, done.
Resolving deltas: 100% (148/148), done.
Cloning into '/dglvenv/lib/python3.6/site-packages/dgl/third_party/dmlc-core'...
remote: Enumerating objects: 6284, done.
remote: Counting objects: 100% (148/148), done.
remote: Compressing objects: 100% (105/105), done.
remote: Total 6284 (delta 54), reused 75 (delta 27), pack-reused 6136
Receiving objects: 100% (6284/6284), 1.68 MiB | 7.52 MiB/s, done.
Resolving deltas: 100% (3800/3800), done.
Cloning into '/dglvenv/lib/python3.6/site-packages/dgl/third_party/googletest'...
remote: Enumerating objects: 24945, done.
remote: Counting objects: 100% (47/47), done.
remote: Compressing objects: 100% (35/35), done.
remote: Total 24945 (delta 14), reused 24 (delta 8), pack-reused 24898
Receiving objects: 100% (24945/24945), 10.67 MiB | 5.18 MiB/s, done.
Resolving deltas: 100% (18438/18438), done.
Cloning into '/dglvenv/lib/python3.6/site-packages/dgl/third_party/libxsmm'...
remote: Enumerating objects: 151119, done.
remote: Counting objects: 100% (1898/1898), done.
remote: Compressing objects: 100% (516/516), done.
remote: Total 151119 (delta 1253), reused 1800 (delta 1183), pack-reused 149221 
Receiving objects: 100% (151119/151119), 296.16 MiB | 25.94 MiB/s, done.
Resolving deltas: 100% (114290/114290), done.
Cloning into '/dglvenv/lib/python3.6/site-packages/dgl/third_party/nanoflann'...
remote: Enumerating objects: 2676, done.
remote: Counting objects: 100% (425/425), done.
remote: Compressing objects: 100% (157/157), done.
remote: Total 2676 (delta 247), reused 377 (delta 230), pack-reused 2251
Receiving objects: 100% (2676/2676), 2.47 MiB | 8.81 MiB/s, done.
Resolving deltas: 100% (1458/1458), done.
Cloning into '/dglvenv/lib/python3.6/site-packages/dgl/third_party/nccl'...
remote: Enumerating objects: 2255, done.
remote: Counting objects: 100% (568/568), done.
remote: Compressing objects: 100% (284/284), done.
remote: Total 2255 (delta 360), reused 405 (delta 282), pack-reused 1687
Receiving objects: 100% (2255/2255), 2.51 MiB | 5.12 MiB/s, done.
Resolving deltas: 100% (1446/1446), done.
Cloning into '/dglvenv/lib/python3.6/site-packages/dgl/third_party/phmap'...
remote: Enumerating objects: 2879, done.
remote: Counting objects: 100% (752/752), done.
remote: Compressing objects: 100% (291/291), done.
remote: Total 2879 (delta 479), reused 708 (delta 448), pack-reused 2127
Receiving objects: 100% (2879/2879), 2.98 MiB | 6.50 MiB/s, done.
Resolving deltas: 100% (1929/1929), done.
Cloning into '/dglvenv/lib/python3.6/site-packages/dgl/third_party/tensorpipe'...
remote: Enumerating objects: 10300, done.
remote: Counting objects: 100% (1691/1691), done.
remote: Compressing objects: 100% (240/240), done.
remote: Total 10300 (delta 1527), reused 1462 (delta 1451), pack-reused 8609    
Receiving objects: 100% (10300/10300), 2.46 MiB | 4.46 MiB/s, done.
Resolving deltas: 100% (7999/7999), done.
Cloning into '/dglvenv/lib/python3.6/site-packages/dgl/third_party/thrust'...
remote: Enumerating objects: 49532, done.
remote: Counting objects: 100% (1143/1143), done.
remote: Compressing objects: 100% (529/529), done.
remote: Total 49532 (delta 634), reused 1053 (delta 601), pack-reused 48389     
Receiving objects: 100% (49532/49532), 17.13 MiB | 20.94 MiB/s, done.
Resolving deltas: 100% (39343/39343), done.
Cloning into '/dglvenv/lib/python3.6/site-packages/dgl/third_party/tvm'...
remote: Enumerating objects: 156114, done.
remote: Counting objects: 100% (146/146), done.
remote: Compressing objects: 100% (109/109), done.
remote: Total 156114 (delta 60), reused 84 (delta 34), pack-reused 155968       
Receiving objects: 100% (156114/156114), 72.48 MiB | 23.01 MiB/s, done.
Resolving deltas: 100% (117984/117984), done.
Cloning into '/dglvenv/lib/python3.6/site-packages/dgl/third_party/xbyak'...
remote: Enumerating objects: 6508, done.
remote: Counting objects: 100% (1536/1536), done.
remote: Compressing objects: 100% (447/447), done.
remote: Total 6508 (delta 1116), reused 1383 (delta 1076), pack-reused 4972     
Receiving objects: 100% (6508/6508), 2.33 MiB | 2.35 MiB/s, done.
Resolving deltas: 100% (4498/4498), done.
Submodule path 'third_party/METIS': checked out '10603482cc055626ff99d2ac3ab7e73d1119439d'
Submodule 'GKlib' (https://github.com/KarypisLab/GKlib.git) registered for path 'third_party/METIS/GKlib'
Cloning into '/dglvenv/lib/python3.6/site-packages/dgl/third_party/METIS/GKlib'...
remote: Enumerating objects: 145, done.
remote: Counting objects: 100% (21/21), done.
remote: Compressing objects: 100% (16/16), done.
remote: Total 145 (delta 8), reused 14 (delta 5), pack-reused 124
Receiving objects: 100% (145/145), 247.84 KiB | 903.00 KiB/s, done.
Resolving deltas: 100% (47/47), done.
Submodule path 'third_party/METIS/GKlib': checked out '62de20c7f97c719abdc96d7c3e266a1f7cb52bc5'
Submodule path 'third_party/dlpack': checked out 'e2bdd3bee8cb6501558042633fa59144cc8b7f5f'
Submodule path 'third_party/dmlc-core': checked out 'bfad207b448480783a1f428ae3d93d87032d8349'
Submodule path 'third_party/googletest': checked out 'f71fb4f9a912ec945401cc49a287a759b6131026'
Submodule path 'third_party/libxsmm': checked out 'fa687556130b6298430f1c0555a14cf79ab6101c'
Submodule path 'third_party/nanoflann': checked out '4c47ca200209550c5628c89803591f8a753c8181'
Submodule path 'third_party/nccl': checked out 'e11238b3029795d33f958b5868d47c90c4f22628'
Submodule path 'third_party/phmap': checked out '25293cefd8b85491b45600c03fe8edf07647553f'
Submodule path 'third_party/tensorpipe': checked out '6042f1a4cbce8eef997f11ed0012de137b317361'
Submodule 'third_party/googletest' (https://github.com/google/googletest.git) registered for path 'third_party/tensorpipe/third_party/googletest'
Submodule 'third_party/libnop' (https://github.com/google/libnop.git) registered for path 'third_party/tensorpipe/third_party/libnop'
Submodule 'third_party/libuv' (https://github.com/libuv/libuv.git) registered for path 'third_party/tensorpipe/third_party/libuv'
Submodule 'third_party/pybind11' (https://github.com/pybind/pybind11.git) registered for path 'third_party/tensorpipe/third_party/pybind11'
Cloning into '/dglvenv/lib/python3.6/site-packages/dgl/third_party/tensorpipe/third_party/googletest'...
remote: Enumerating objects: 24945, done.
remote: Counting objects: 100% (47/47), done.
remote: Compressing objects: 100% (35/35), done.
remote: Total 24945 (delta 14), reused 24 (delta 8), pack-reused 24898
Receiving objects: 100% (24945/24945), 10.67 MiB | 18.16 MiB/s, done.
Resolving deltas: 100% (18438/18438), done.
Cloning into '/dglvenv/lib/python3.6/site-packages/dgl/third_party/tensorpipe/third_party/libnop'...
remote: Enumerating objects: 1588, done.
remote: Counting objects: 100% (10/10), done.
remote: Compressing objects: 100% (8/8), done.
remote: Total 1588 (delta 1), reused 4 (delta 1), pack-reused 1578
Receiving objects: 100% (1588/1588), 401.97 KiB | 1.46 MiB/s, done.
Resolving deltas: 100% (1047/1047), done.
Cloning into '/dglvenv/lib/python3.6/site-packages/dgl/third_party/tensorpipe/third_party/libuv'...
remote: Enumerating objects: 34850, done.
remote: Counting objects: 100% (29/29), done.
remote: Compressing objects: 100% (27/27), done.
remote: Total 34850 (delta 6), reused 7 (delta 1), pack-reused 34821
Receiving objects: 100% (34850/34850), 16.71 MiB | 4.99 MiB/s, done.
Resolving deltas: 100% (25701/25701), done.
Cloning into '/dglvenv/lib/python3.6/site-packages/dgl/third_party/tensorpipe/third_party/pybind11'...
remote: Enumerating objects: 24692, done.
remote: Counting objects: 100% (23/23), done.
remote: Compressing objects: 100% (15/15), done.
remote: Total 24692 (delta 7), reused 19 (delta 6), pack-reused 24669
Receiving objects: 100% (24692/24692), 9.09 MiB | 15.85 MiB/s, done.
Resolving deltas: 100% (17317/17317), done.
Submodule path 'third_party/tensorpipe/third_party/googletest': checked out 'aee0f9d9b5b87796ee8a0ab26b7587ec30e8858e'
Submodule path 'third_party/tensorpipe/third_party/libnop': checked out 'aa95422ea8c409e3f078d2ee7708a5f59a8b9fa2'
Submodule path 'third_party/tensorpipe/third_party/libuv': checked out '1dff88e5161cba5c59276d2070d2e304e4dcb242'
Submodule path 'third_party/tensorpipe/third_party/pybind11': checked out 'a23996fce38ff6ccfbcdc09f1e63f2c4be5ea2ef'
Submodule 'tools/clang' (https://github.com/wjakob/clang-cindex-python3) registered for path 'third_party/tensorpipe/third_party/pybind11/tools/clang'
Cloning into '/dglvenv/lib/python3.6/site-packages/dgl/third_party/tensorpipe/third_party/pybind11/tools/clang'...
remote: Enumerating objects: 368, done.
remote: Counting objects: 100% (13/13), done.
remote: Compressing objects: 100% (10/10), done.
remote: Total 368 (delta 3), reused 10 (delta 3), pack-reused 355
Receiving objects: 100% (368/368), 159.34 KiB | 5.90 MiB/s, done.
Resolving deltas: 100% (154/154), done.
Submodule path 'third_party/tensorpipe/third_party/pybind11/tools/clang': checked out '6a00cbc4a9b8e68b71caf7f774b3f9c753ae84d5'
Submodule path 'third_party/thrust': checked out '6a3078c64cab0e2f276340fa5dcafa0d758ed890'
Submodule 'cub' (https://github.com/NVIDIA/cub.git) registered for path 'third_party/thrust/dependencies/cub'
Cloning into '/dglvenv/lib/python3.6/site-packages/dgl/third_party/thrust/dependencies/cub'...
remote: Enumerating objects: 31921, done.
remote: Counting objects: 100% (199/199), done.
remote: Compressing objects: 100% (117/117), done.
remote: Total 31921 (delta 105), reused 156 (delta 79), pack-reused 31722       
Receiving objects: 100% (31921/31921), 17.10 MiB | 14.74 MiB/s, done.
Resolving deltas: 100% (27003/27003), done.
Submodule path 'third_party/thrust/dependencies/cub': checked out 'cdaa9558a85e45d849016e5fe7b6e4ee79113f95'
Submodule path 'third_party/tvm': checked out 'b2e418cb109df4cd1f17a2cf2894a1b396a6b838'
Submodule 'dlpack' (https://github.com/dmlc/dlpack) registered for path 'third_party/tvm/3rdparty/dlpack'
Submodule 'dmlc-core' (https://github.com/dmlc/dmlc-core) registered for path 'third_party/tvm/3rdparty/dmlc-core'
Submodule '3rdparty/rang' (https://github.com/agauniyal/rang) registered for path 'third_party/tvm/3rdparty/rang'
Submodule '3rdparty/vta-hw' (https://github.com/apache/incubator-tvm-vta) registered for path 'third_party/tvm/3rdparty/vta-hw'
Cloning into '/dglvenv/lib/python3.6/site-packages/dgl/third_party/tvm/3rdparty/dlpack'...
remote: Enumerating objects: 437, done.
remote: Counting objects: 100% (106/106), done.
remote: Compressing objects: 100% (43/43), done.
remote: Total 437 (delta 78), reused 68 (delta 61), pack-reused 331
Receiving objects: 100% (437/437), 1.69 MiB | 15.19 MiB/s, done.
Resolving deltas: 100% (148/148), done.
Cloning into '/dglvenv/lib/python3.6/site-packages/dgl/third_party/tvm/3rdparty/dmlc-core'...
remote: Enumerating objects: 6284, done.
remote: Counting objects: 100% (148/148), done.
remote: Compressing objects: 100% (105/105), done.
remote: Total 6284 (delta 54), reused 75 (delta 27), pack-reused 6136
Receiving objects: 100% (6284/6284), 1.68 MiB | 11.55 MiB/s, done.
Resolving deltas: 100% (3800/3800), done.
Cloning into '/dglvenv/lib/python3.6/site-packages/dgl/third_party/tvm/3rdparty/rang'...
remote: Enumerating objects: 735, done.
remote: Counting objects: 100% (31/31), done.
remote: Compressing objects: 100% (27/27), done.
remote: Total 735 (delta 9), reused 15 (delta 3), pack-reused 704
Receiving objects: 100% (735/735), 265.43 KiB | 5.42 MiB/s, done.
Resolving deltas: 100% (371/371), done.
Cloning into '/dglvenv/lib/python3.6/site-packages/dgl/third_party/tvm/3rdparty/vta-hw'...
remote: Enumerating objects: 3312, done.
remote: Counting objects: 100% (330/330), done.
remote: Compressing objects: 100% (137/137), done.
remote: Total 3312 (delta 258), reused 193 (delta 193), pack-reused 2982
Receiving objects: 100% (3312/3312), 1.43 MiB | 13.94 MiB/s, done.
Resolving deltas: 100% (1442/1442), done.
Submodule path 'third_party/tvm/3rdparty/dlpack': checked out '3ec04430e89a6834e5a1b99471f415fa939bf642'
Submodule path 'third_party/tvm/3rdparty/dmlc-core': checked out '6c401e242c59a1f4c913918246591bb13fd714e7'
Submodule path 'third_party/tvm/3rdparty/rang': checked out 'cabe04d6d6b05356fa8f9741704924788f0dd762'
Submodule path 'third_party/tvm/3rdparty/vta-hw': checked out '87ce9acfae550d1a487746e9d06c2e250076e54c'
Submodule path 'third_party/xbyak': checked out '757e4063f6464740b8ff4a2cae9136d2f8458020'
(dglvenv) @sumo1:~/python/venv/dglvenv/lib/python3.6/site-packages$ cd dgl
(dglvenv) @sumo1:~/python/venv/dglvenv/lib/python3.6/site-packages/dgl$ mkdir build
(dglvenv) @sumo1:~/python/venv/dglvenv/lib/python3.6/site-packages/dgl$ cd build
(dglvenv) @sumo1:~/python/venv/dglvenv/lib/python3.6/site-packages/dgl/build$ cmake -DUSE_CUDA=ON ..
-- The C compiler identification is GNU 7.5.0
-- The CXX compiler identification is GNU 7.5.0
-- Check for working C compiler: /usr/bin/cc
-- Check for working C compiler: /usr/bin/cc -- works
-- Detecting C compiler ABI info
-- Detecting C compiler ABI info - done
-- Detecting C compile features
-- Detecting C compile features - done
-- Check for working CXX compiler: /usr/bin/c++
-- Check for working CXX compiler: /usr/bin/c++ -- works
-- Detecting CXX compiler ABI info
-- Detecting CXX compiler ABI info - done
-- Detecting CXX compile features
-- Detecting CXX compile features - done
-- Start configuring project dgl
-- Build with CUDA support
-- Looking for pthread.h
-- Looking for pthread.h - found
-- Looking for pthread_create
-- Looking for pthread_create - not found
-- Looking for pthread_create in pthreads
-- Looking for pthread_create in pthreads - not found
-- Looking for pthread_create in pthread
-- Looking for pthread_create in pthread - found
-- Found Threads: TRUE
-- Found CUDA: /usr/local/cuda (found version "11.2")
-- Found CUDA_TOOLKIT_ROOT_DIR=/usr/local/cuda
-- Found CUDA_CUDART_LIBRARY=/usr/local/cuda/lib64/libcudart.so
-- Found CUDA_CUBLAS_LIBRARY=/usr/lib/x86_64-linux-gnu/libcublas.so
-- Found CUDA_CURAND_LIBRARY=/usr/local/cuda/lib64/libcurand.so
-- Performing Test SUPPORT_CXX14
-- Performing Test SUPPORT_CXX14 - Success
-- Use external CUB/Thrust library for a consistent API and performance.
-- Found OpenMP_C: -fopenmp (found version "4.5")
-- Found OpenMP_CXX: -fopenmp (found version "4.5")
-- Found OpenMP: TRUE (found version "4.5")
-- Build with OpenMP.
-- Looking for sys/epoll.h
-- Looking for sys/epoll.h - found
-- -fopenmp -O2 -Wall -fPIC -std=c++14  -DUSE_EPOLL -DIDXTYPEWIDTH=64 -DREALTYPEWIDTH=32
-- Running GPU architecture autodetection
nvcc warning : The 'compute_35', 'compute_37', 'compute_50', 'sm_35', 'sm_37' and 'sm_50' architectures are deprecated, and may be removed in a future release (Use -Wno-deprecated-gpu-targets to suppress warning).
-- Found CUDA arch 6.1 6.1 6.1 6.1
-- CUDA flags: -Xcompiler ,-fopenmp,-O2,-Wall,-fPIC,-std=c++14,,-DUSE_EPOLL,-DIDXTYPEWIDTH=64,-DREALTYPEWIDTH=32;--expt-relaxed-constexpr;-gencode;arch=compute_61,code=sm_61;--expt-extended-lambda;-Wno-deprecated-declarations;-std=c++14
-- Found OpenMP_C: -fopenmp (found version "4.5")
-- Found OpenMP_CXX: -fopenmp (found version "4.5")
-- Looking for clock_gettime in rt
-- Looking for clock_gettime in rt - found
-- Looking for fopen64
-- Looking for fopen64 - not found
-- Looking for C++ include cxxabi.h
-- Looking for C++ include cxxabi.h - found
-- Looking for nanosleep
-- Looking for nanosleep - found
-- Looking for backtrace
-- Looking for backtrace - found
-- backtrace facility detected in default set of libraries
-- Found Backtrace: /usr/include
-- Check if the system is big endian
-- Searching 16 bit integer
-- Looking for sys/types.h
-- Looking for sys/types.h - found
-- Looking for stdint.h
-- Looking for stdint.h - found
-- Looking for stddef.h
-- Looking for stddef.h - found
-- Check size of unsigned short
-- Check size of unsigned short - done
-- Using unsigned short
-- Check if the system is big endian - little endian
-- /dglvenv/lib/python3.6/site-packages/dgl/third_party/dmlc-core/cmake/build_config.h.in -> include/dmlc/build_config.h
-- Performing Test SUPPORT_MSSE2
-- Performing Test SUPPORT_MSSE2 - Success
-- Looking for execinfo.h
-- Looking for execinfo.h - found
-- Looking for getline
-- Looking for getline - found
-- Performing Test UV_LINT_W4
-- Performing Test UV_LINT_W4 - Failed
-- Performing Test UV_LINT_NO_UNUSED_PARAMETER_MSVC
-- Performing Test UV_LINT_NO_UNUSED_PARAMETER_MSVC - Failed
-- Performing Test UV_LINT_NO_CONDITIONAL_CONSTANT_MSVC
-- Performing Test UV_LINT_NO_CONDITIONAL_CONSTANT_MSVC - Failed
-- Performing Test UV_LINT_NO_NONSTANDARD_MSVC
-- Performing Test UV_LINT_NO_NONSTANDARD_MSVC - Failed
-- Performing Test UV_LINT_NO_NONSTANDARD_EMPTY_TU_MSVC
-- Performing Test UV_LINT_NO_NONSTANDARD_EMPTY_TU_MSVC - Failed
-- Performing Test UV_LINT_NO_NONSTANDARD_FILE_SCOPE_MSVC
-- Performing Test UV_LINT_NO_NONSTANDARD_FILE_SCOPE_MSVC - Failed
-- Performing Test UV_LINT_NO_NONSTANDARD_NONSTATIC_DLIMPORT_MSVC
-- Performing Test UV_LINT_NO_NONSTANDARD_NONSTATIC_DLIMPORT_MSVC - Failed
-- Performing Test UV_LINT_NO_HIDES_LOCAL
-- Performing Test UV_LINT_NO_HIDES_LOCAL - Failed
-- Performing Test UV_LINT_NO_HIDES_PARAM
-- Performing Test UV_LINT_NO_HIDES_PARAM - Failed
-- Performing Test UV_LINT_NO_HIDES_GLOBAL
-- Performing Test UV_LINT_NO_HIDES_GLOBAL - Failed
-- Performing Test UV_LINT_NO_CONDITIONAL_ASSIGNMENT_MSVC
-- Performing Test UV_LINT_NO_CONDITIONAL_ASSIGNMENT_MSVC - Failed
-- Performing Test UV_LINT_NO_UNSAFE_MSVC
-- Performing Test UV_LINT_NO_UNSAFE_MSVC - Failed
-- Performing Test UV_LINT_WALL
-- Performing Test UV_LINT_WALL - Success
-- Performing Test UV_LINT_NO_UNUSED_PARAMETER
-- Performing Test UV_LINT_NO_UNUSED_PARAMETER - Success
-- Performing Test UV_LINT_STRICT_PROTOTYPES
-- Performing Test UV_LINT_STRICT_PROTOTYPES - Success
-- Performing Test UV_LINT_EXTRA
-- Performing Test UV_LINT_EXTRA - Success
-- Performing Test UV_LINT_UTF8_MSVC
-- Performing Test UV_LINT_UTF8_MSVC - Failed
-- Performing Test UV_F_STRICT_ALIASING
-- Performing Test UV_F_STRICT_ALIASING - Success
-- summary of build options:
    Install prefix:  /usr/local
    Target system:   Linux
    Compiler:
      C compiler:    /usr/bin/cc
      CFLAGS:         -fopenmp -O2  -fPIC  -DUSE_EPOLL -DIDXTYPEWIDTH=64 -DREALTYPEWIDTH=32 -DLINUX -D_FILE_OFFSET_BITS=64 -std=c99 -fno-strict-aliasing -march=native -fPIC -Werror   -Wno-unused-function -Wno-unused-but-set-variable -Wno-unused-variable -Wno-unknown-pragmas -DNDEBUG -DNDEBUG2 -DHAVE_EXECINFO_H -DHAVE_GETLINE -O3

-- Found uv: 1.38.1 (found version "1.38.1")
CMake Error: The following variables are used in this project, but they are set to NOTFOUND.
Please set them or make sure they are set and tested correctly in the CMake files:
CUDA_cublas_device_LIBRARY (ADVANCED)
    linked by target "dgl" in directory /dglvenv/lib/python3.6/site-packages/dgl

-- Configuring incomplete, errors occurred!
See also "/dglvenv/lib/python3.6/site-packages/dgl/build/CMakeFiles/CMakeOutput.log".
See also "/dglvenv/lib/python3.6/site-packages/dgl/build/CMakeFiles/CMakeError.log".
------I install 
torch.1.10.0-cuda113

toml                          0.10.2
torch                         1.10.0+cu113
torchaudio                    0.10.0+cu113
torchvision                   0.11.0+cu113

ogb                           1.3.4
outdated                      0.2.1
packaging                     21.3
pandas                        1.1.5
Pillow                        8.4.0
pip                           21.3.1
pkg_resources                 0.0.0
protobuf                      3.19.5
psutil                        5.9.2
pycodestyle                   2.9.1
pydantic                      1.9.2
Pygments                      2.13.0
pyparsing                     3.0.9
python-dateutil               2.8.2
pytz                          2022.2.1
PyYAML                        6.0
rdkit-pypi                    2021.9.4
requests                      2.27.1
ruamel.yaml                   0.17.21
ruamel.yaml.clib              0.2.6
scikit-learn                  0.24.2
scipy                         1.5.4
thank you very much.

**Comment by 123carmen** [comment]
I also have another question. 
the first (above long compile is in linux with cuda)


the following one is i install the dgl by CPU-my laptop without cuda.

I can use dgl and import dgl..---i can run with dataset ZINC.
but i can not import dgl.graph(no mudle found)
so what is the problem with it.

in this case, I can use some dataset, but i can use other dataset like PATTER, CLUSTER (they need to call pickle.load(f)--)
then it report modulefounderror.
no dgl.graph.

thank you.

**Comment by BarclayII** [comment]
Do you have multiple CUDA versions installed?  It seems that cuBLAS installation has a problem.

**Comment by peizhou001** [comment]
And also could you post your python code and environments?

**Comment by 123carmen** [comment]
> 

I am sorry. After I post this issue, I totally forgot it,
first, the problem is solved. I do not know how it starts working. 
I tried many times and many methods, I do not even know what I had done for that.

second. yes, the school server has ridiculous many CUD versions. hahaha ^^.
  now the default is CUDA-116.

dgl.graph is not a module; it is a function.---- thank you for the reply, 
because it give me the error that it can not import dgl.graph, I thought i should  test this import, and verify if dgl is installed well..
now i get it. thank you.

**Comment by 123carmen** [comment]
> And also could you post your python code and environments?

I do not have my own code, I want to deploy this code graphdeeplearning/graphtransformer
on a server, but it failed.\then after many try, i totally forgot how
in the end, it works. 

> Do you have multiple CUDA versions installed? It seems that cuBLAS installation has a problem.
 ------YES, WE have cuda 102 till 116, the default cuda version is 116.
> 
> `dgl.graph` is not a module; it is a function.

thank you all, very much for your reply.
and sorry for my  bad memory

**Comment by BarclayII** [comment]
Glad that it worked for you.
