### ISSUE TITLE
I need the original order of nodes, but all nodes are relabeled after converting them.

### ISSUE THREAD

**Issue by haif-liu** [dmlc/dgl#466]
## 🐛 Bug

I need the original order of nodes, but all nodes are relabeled after converting them.

dgl.DGLGraph.from_networkx

nx_graph (networkx.DiGraph) – If the node labels of nx_graph are not consecutive integers, its nodes will be relabeled using consecutive integers. The new node ordering will inherit that of sorted(nx_graph.nodes())

## To Reproduce

1.
1.
1.

## Environment

 - DGL Version (e.g., 1.0):
 - Backend Library & Version (e.g., PyTorch 0.4.1, MXNet/Gluon 1.3):
 - OS (e.g., Linux):
 - How you installed DGL (`conda`, `pip`, source):
 - Build command you used (if compiling from source):
 - Python version:
 - CUDA/cuDNN version (if applicable):
 - GPU models and configuration (e.g. V100):
 - Any other relevant information:

**Comment by mufeili** [comment]
How about pre-sorting your nodes and maintain a mapping yourself before creating a `DGLGraph` object?

**Comment by jermainewang** [comment]
Hi, how about first using [`nx.relabel_nodes`](https://networkx.github.io/documentation/networkx-1.10/reference/generated/networkx.relabel.relabel_nodes.html#networkx.relabel.relabel_nodes) to map your nodes to consecutive integers first by providing custom mapping, and then convert to `DGLGraph`? Will that solve your problem?

**Comment by haif-liu** [comment]
> Hi, how about first using [`nx.relabel_nodes`](https://networkx.github.io/documentation/networkx-1.10/reference/generated/networkx.relabel.relabel_nodes.html#networkx.relabel.relabel_nodes) to map your nodes to consecutive integers first by providing custom mapping, and then convert to `DGLGraph`? Will that solve your problem?

I mean that the function 'dgl.DGLGraph.from_networkx' will relabel the original id of nodes no matter whether the ids of nodes are consecutive integers.

**Comment by mufeili** [comment]
When you perform `dgl.DGLGraph.from_networkx`, [L1207](https://github.com/dmlc/dgl/blob/master/python/dgl/graph.py#L1207) calls `nx.convert_node_labels_to_integers(nx_graph, ordering='sorted')`. [The source code of networkx](https://github.com/networkx/networkx/blob/33980ffeef6de64fa543692bcc713e2b1fcdbcce/networkx/relabel.py#L208) first sort nodes and then map them to `[0, number of nodes - 1]`.

**Comment by jermainewang** [comment]
> > Hi, how about first using [`nx.relabel_nodes`](https://networkx.github.io/documentation/networkx-1.10/reference/generated/networkx.relabel.relabel_nodes.html#networkx.relabel.relabel_nodes) to map your nodes to consecutive integers first by providing custom mapping, and then convert to `DGLGraph`? Will that solve your problem?
> 
> I mean that the function 'dgl.DGLGraph.from_networkx' will relabel the original id of nodes no matter whether the ids of nodes are consecutive integers.

My suggestion is use `nx.relabel_nodes` to relabel the nodes to consecutive integers before `dgl.DGLGraph.from_networkx`. For example,
```python
>>> import dgl
>>> import networkx as nx
>>> g = nx.DiGraph()
>>> g.add_nodes_from(['b', 'c', 'a'])
>>> g.nodes
NodeView(('b', 'c', 'a'))
>>> gg = nx.relabel_nodes(g, mapping={'b':0, 'c':1, 'a':2})  # suppose the order is 'b', 'c', 'a'
>>> gg.nodes
NodeView((0, 1, 2))
>>> dg = dgl.DGLGraph(gg)
>>> dg.nodes()
tensor([0, 1, 2])
```

**Comment by jermainewang** [comment]
Closed due to inactive. Please reopen if the problem still exists.
