### ISSUE TITLE
Validate the correctness of the dist. graph partitioning pipeline

### ISSUE THREAD

**Issue by kylasa** [dmlc/dgl#4670]
## 🔨Work Item

**IMPORTANT:**
* This template is only for dev team to track project progress. For feature request or bug report, please use the corresponding issue templates.
* DO NOT create a new work item if the purpose is to fix an existing issue or feature request. We will directly use the issue in the project tracker.

Project tracker: https://github.com/orgs/dmlc/projects/2

## Description

Use the Core Graph for validating the correctness of dist. graph partitioning pipeline. Following items are needed to be verified for this task. 
1. Run ParMETIS without Node-Degree, train/test/validation Masks as node constraints and generate METIS partition ids
2. With these METIS partitionids, Note down % of edges across partitions and note down training time for DistDGL training this dataset.  These will be the baseline numbers. 
3. Now generate METIS partitions with node-dgree, train/test/validation-masks as node constraints.
4. With these metis partitions, note down % of edges across partitions and note down training time for DistDGL training this dataset. 
5. Expected behaviour, out of these two experiments is that we should see some training speedup with node constraints compared to the baseline numbers.

**Comment by frozenbugs** [comment]
Covered by https://github.com/dmlc/dgl/issues/4727, dedup by closing.
