### ISSUE TITLE
Run Web-Graph with the dist. graph partitioning pipeline

### ISSUE THREAD

**Issue by kylasa** [dmlc/dgl#4671]
## 🔨Work Item

**IMPORTANT:**
* This template is only for dev team to track project progress. For feature request or bug report, please use the corresponding issue templates.
* DO NOT create a new work item if the purpose is to fix an existing issue or feature request. We will directly use the issue in the project tracker.

Project tracker: https://github.com/orgs/dmlc/projects/2

## Description

Using latest dist. Graph Partitioning Pipeline run web-graph and verify that the pipeline works without any issues.

**Comment by frozenbugs** [comment]
Covered by https://github.com/dmlc/dgl/issues/4727, dedup by closing.
