### ISSUE TITLE
Node2vec for directed graph will lead to "index out of range in self"

### ISSUE THREAD

**Issue by zhf-0** [dmlc/dgl#4696]
## To Reproduce
I modified the programs from [examples/pytorch/node2vec](https://github.com/dmlc/dgl/tree/master/examples/pytorch/node2vec) to get node features of a directed graph. 
- [main.txt](https://github.com/dmlc/dgl/files/9745722/main.txt): `main.py` ( uploading `py` file is not supported, so I change the suffix from `py` to `txt`)
- [model.txt](https://github.com/dmlc/dgl/files/9745749/model.txt): `model.py` is based on [examples/pytorch/node2vec/model.py](https://github.com/dmlc/dgl/blob/master/examples/pytorch/node2vec/model.py) and deletes  `eval` related functions and parameters

1. run `python main.py`

The error messages are
```
Traceback (most recent call last):
  File "main.py", line 41, in <module>
    trainer.train(
  File "model.py", line 301, in train
    loss = self._train_step(self.model, loader, optimizer, self.device)
  File "model.py", line 270, in _train_step
    loss = model.loss(pos_traces, neg_traces)
  File "model.py", line 146, in loss
    w_rest = self.embedding(pos_rest)
  File "python3.8/site-packages/torch/nn/modules/module.py", line 1051, in _call_impl
    return forward_call(*input, **kwargs)
  File "python3.8/site-packages/torch/nn/modules/sparse.py", line 158, in forward
    return F.embedding(
  File "python3.8/site-packages/torch/nn/functional.py", line 2043, in embedding
    return torch.embedding(weight, input, padding_idx, scale_grad_by_freq, sparse)
IndexError: index out of range in self
```

## Expected behavior
The `main.py` can exit normally

## Environment

 - DGL Version (e.g., 1.0): 0.9.1
 - Backend Library & Version (e.g., PyTorch 0.4.1, MXNet/Gluon 1.3): PyTorch 1.9.1
 - OS (e.g., Linux): ubuntu 18.04 LTS
 - How you installed DGL (`conda`, `pip`, source): `conda`
 - Build command you used (if compiling from source):
 - Python version: python 3.8.12
 - CUDA/cuDNN version (if applicable): cudatoolkit 10.2
 - GPU models and configuration (e.g. V100): GTX 960M
 - Any other relevant information:

## Additional context

I construct a simple directed graph with 4 nodes and 3 edges in `main.py`.
```
0  -->  1  -->  2  -->  3
```
The error " IndexError: index out of range in self " is from `model.py:146`
```
w_rest = self.embedding(pos_rest)
```
and the reason is tensor `pos_rest` consists `-1`. Since the input of `self.embedding`(which is an instance of `torch.nn.embedding`) should `>= 0`, therefore `self.embedding(torch.tensor([-1]))` will lead to the error.

Moreover, the reason why `pos_rest` consists `-1` is from `model.py:90`
```
pos_traces = node2vec_random_walk(
            self.g, batch, self.p, self.q, self.walk_length, self.prob
        )
...
...
pos_start, pos_rest = (
            pos_trace[:, 0],
            pos_trace[:, 1:].contiguous(),
        )
```
If I use the following codes to generate `pos_traces`
```
>>> row = [0,1,2]
>>> col = [1,2,3]
>>> g1 = dgl.graph((row,col))
>>> pos_traces = dgl.sampling.node2vec_random_walk(g1, list(range(4)), 1, 1, walk_length=5)
>>> pos_traces
tensor([[ 0,  1,  2,  3, -1, -1],
        [ 1,  2,  3, -1, -1, -1],
        [ 2,  3, -1, -1, -1, -1],
        [ 3, -1, -1, -1, -1, -1]])
```
It's clear that `-1` means there is no path for the current node to move on. 

So, all the error messages come to the question: how to deal with `-1` in `pos_traces`

**Comment by czkkkkkk** [comment]
Normally we only run node2vec on an undirected graph, where a node always has at least one successor. If you want to run it on a directed graph, you can try `pack_traces` in [https://github.com/dmlc/dgl/blob/ea48ce7a3742c5d4ee7c37279be741db6b45bf50/python/dgl/sampling/randomwalks.py#L231](url) to remove all -1s.

**Comment by zhf-0** [comment]
I found out that `model4direct.py` can deal with both directed and undirected graphs as long as the node id begins with 1. So I change the name from `model4direct.py` to `model4both.py`. The program is available in my repository [node2vec_dgl](https://github.com/zhf-0/node2vec_dgl).

Besides, the current `model.py` can only deal with graphs whose node id begins with 0 and is consecutive, detail explanation can be found in my repository.
