### ISSUE TITLE
Cannot convert a heterogenous graph to a homogenous one

### ISSUE THREAD

**Issue by NicoPiel** [dmlc/dgl#4717]
## 🐛 Bug

Using dgl.to_homogenous() on a batched graph yields a heterogenous graph, even though the original one has only a single node and edge type.

## To Reproduce

Reproduction may be hard, because this is custom data extracted from QM9 (check the link below to download my datasets):
In general:

1. Create a batched heterogenous graph
2. Apply dgl.to_homogenous()
3. Check type

```
dataset = dgl.data.CSVDataset('./graph_data')

# train.py
def main(hparams):
    dgl.data.utils.add_nodepred_split(dataset, [0.8, 0.1, 0.1])
    dataset_batched = dgl.batch(dataset)
    # dataset_batched = dgl.to_float(dataset_batched)
    dataset_homo = dgl.to_homogeneous(dataset_batched)

    print(type(dataset_homo))
    print(dataset_homo)

    node_features = dataset_homo.ndata['label']  #, 'depDeg', 'forC', 'isA', 'radEl', 'totDeg', 'totH', 'totV', 'isR']
    node_labels = dataset_homo.ndata['type']
    train_mask = dataset_homo.ndata['train_mask']
    valid_mask = dataset_homo.ndata['val_mask']
    test_mask = dataset_homo.ndata['test_mask']
    n_features = 1  # node_features.shape[1]
    n_labels = int(node_labels.max().item() + 1)

    model = SAGENet(in_feats=n_features, hid_feats=16, out_feats=n_labels)
    opt = optim.Adam(model.parameters())

    for epoch in range(1):
        model.train()
        # forward propagation by using all nodes and extracting the user embeddings
        logits = model(dataset_homo, node_features)
        # compute loss
        loss = F.cross_entropy(logits[train_mask], node_labels[train_mask])
        # Compute validation accuracy.  Omitted in this example.
        # backward propagation
        opt.zero_grad()
        loss.backward()
        opt.step()
        print(loss.item())
```

Which yields the following for `dataset_homo`:
```
> type(dataset_homo)
<class 'dgl.heterograph.DGLHeteroGraph'>

> print(dataset_homo)
Graph(num_nodes=2407753, num_edges=2489088,
      ndata_schemes={'_ID': Scheme(shape=(), dtype=torch.int64), '_TYPE': Scheme(shape=(), dtype=torch.int64)}
      edata_schemes={'_ID': Scheme(shape=(), dtype=torch.int64), '_TYPE': Scheme(shape=(), dtype=torch.int64)})
```

## Expected behavior

dgl.to_homogenous() should always return a homogenous graph or raise an exception otherwise.

## Environment

 - DGL Version (e.g., 1.0): 0.9.1
 - Backend Library & Version (e.g., PyTorch 0.4.1, MXNet/Gluon 1.3): PyTorch 1.11.0
 - OS (e.g., Linux): Linux
 - How you installed DGL (`conda`, `pip`, source): conda / mamba
 - Python version: 3.9
 - CUDA/cuDNN version (if applicable): 11.6
 - GPU models and configuration (e.g. V100): V100, but not in use
 - Any other relevant information:

## Additional context

My data to reproduce: https://drive.google.com/drive/folders/1_Fyp7nLFn0jepu7mJ6G82sRN98wDJ8jC?usp=sharing

**Comment by czkkkkkk** [comment]
Hello. `DGLGraph` is deprecated and we use `DGLHeteroGraph` to represent both homogeneous and heterogeneous graphs. The resulted graph in your code is a homogeneous graph.

**Comment by jermainewang** [comment]
Hi @NicoPiel , I am closing this issue assuming you are happy about our response. Feel free to follow up and reopen the issue if you have more questions with regard to our response.
