### ISSUE TITLE
How to compute the vector of each edge in training？

### ISSUE THREAD

**Issue by Zhao6924** [dmlc/dgl#472]
Thank for your code，that is a great job.

But i am not sure about the process of updating the edge vector. It's that employ the neighbor nodes vector as the input of the edges, and aggregate them as the new node's value?

**Comment by jermainewang** [comment]
Check out [`g.apply_edges`](https://docs.dgl.ai/generated/dgl.DGLGraph.apply_edges.html#dgl.DGLGraph.apply_edges).

P.S. try use our [discussion forum](https://discuss.dgl.ai) for richer support of questions and answering. Thank you!
