### ISSUE TITLE
Refactor sampling with edge masks

### ISSUE THREAD

**Issue by BarclayII** [dmlc/dgl#4720]
## 🔨Work Item

**IMPORTANT:**
* This template is only for dev team to track project progress. For feature request or bug report, please use the corresponding issue templates.
* DO NOT create a new work item if the purpose is to fix an existing issue or feature request. We will directly use the issue in the project tracker.

Project tracker: https://github.com/orgs/dmlc/projects/2

## Description

The current implementation of sampling with edge mask (#4633 ) needs to compute a mapping from in-partition homogenized edge IDs to local heterogenized edge IDs.  This costs a lot of memory.

**Comment by jermainewang** [comment]
PR links [#4749](https://github.com/dmlc/dgl/pull/4749) and [#4748](https://github.com/dmlc/dgl/pull/4748)
