### ISSUE TITLE
[Bug] UVA cannot work on old GPUs (K80)

### ISSUE THREAD

**Issue by lzc17** [dmlc/dgl#4726]
## 🐛 Bug

show 'Check failed: e == cudaSuccess || e == cudaErrorCudartUnloading: CUDA: an illegal memory access was encountered
' when I use 'python node_classification.py' .  But it is fine when use 'python node_classification.py --mide puregpu'.

1. cmd  'python node_classification.py'

## Environment

 - DGL Version :0.9
 - PyTorch :1.9
 - OS : linux
 - How you installed DGL (`conda`, `pip`, source): conda
 - Build command you used (if compiling from source): 
 - Python version:3.6.3
 - CUDA/cuDNN version (if applicable): 10.2
 - GPU models and configuration (e.g. V100): k80
 - Any other relevant information:
it is fine when use 'python node_classification.py --mide puregpu'

**Comment by TristonC** [comment]
@yaox12 Could you take a look? It seems the UVA is not working properly.

**Comment by 2905103060** [comment]
k80 cann't use USA or my environment have same problems？

**Comment by 2905103060** [comment]
I want to get the reasons that the UVA is not working properly. k80 can not use USA?

**Comment by TristonC** [comment]
BTW, @2905103060 Coud you give 0.9.1 a try. It might already solve this problem.

**Comment by 2905103060** [comment]
It show this error when I use dgl0.9.1.
![image](https://user-images.githubusercontent.com/41893135/196630541-80e2a1f8-2975-4039-93e9-4eeedffd14c2.png)

**Comment by 2905103060** [comment]
I don't have other types of GPU. I try dgl0.8.0 but this error still exist.

**Comment by czkkkkkk** [comment]
I succeed with settings of CUDA 11.3, V100, and DGL 0.9.1.

DGL uses `cudaHostRegister` to pin CPU memory. Could you write a short program to see whether you hardware has`cudaDevAttrHostRegisterSupported`?

**Comment by 2905103060** [comment]
![image](https://user-images.githubusercontent.com/41893135/196854191-2f590f9b-d6f9-4f49-a75d-c94d897f7977.png)
This shows whether k80 can not use  ”cudaHostRegister” to pin CPU memory？
This show I can not use USA in k80？

**Comment by czkkkkkk** [comment]
`1` means it supports UVA.

**Comment by yaox12** [comment]
I cannot find a K80 GPU card to reproduce this issue. Can you try `compute-sanitizer python node_classification.py` to figure out the very first CUDA error?

**Comment by lzc17** [comment]
![image](https://user-images.githubusercontent.com/41893135/197480521-0808beb8-83be-4024-92ea-e3ac9f96e765.png)
I run ’‘compute-sanitizer python node_classification.py‘’. It show this error.

**Comment by yaox12** [comment]
This is expected. We will manually clear this error.

Can you share the full log by `compute-sanitizer python node_classification.py > log.txt`?

**Comment by lzc17** [comment]
[log.txt](https://github.com/dmlc/dgl/files/9850309/log.txt)

**Comment by lzc17** [comment]
This is log.txt.

**Comment by yaox12** [comment]
Issue confirmed. The device attribute `cudaDevAttrCanUseHostPointerForRegisteredMem` of K80 is 0, so we cannot access the host pointer directly from the device even with UVA. We should get the corresponding device pointer via `cudaHostGetDevicePointer`.

**Comment by frozenbugs** [comment]
Thank yaox12, since this is confirmed, can you estimate the potential impact of this bug and assign the priority to it? I am tracking it in our project tracker.

**Comment by yaox12** [comment]
It won't affect GPUs with compute capability >= 6.0 (Pascal, Volta, Turing, Ampere, and later). K80 is 3.7. For Maxwell (compute capability 5.x), I'm not sure.

You can assign an 11.30 milestone for this. I should be able to fix it before that.
