### ISSUE TITLE
The Residual Module cannot work when input_dim equals to output_dim

### ISSUE THREAD

**Issue by yuanhaitao** [dmlc/dgl#4734]
## To Reproduce

1. using the class GATConv, 
2. set that "in_feats=100", "out_feats=100", "residual=True", "num_heads=3"

<img width="788" alt="image" src="https://user-images.githubusercontent.com/5829539/196854930-d7f503f8-94f4-4e70-af4b-339293638f81.png">

**Comment by frozenbugs** [comment]
Hi yuanhaitao:

Can you provide more information following our bug report template?

Thanks

**Comment by peizhou001** [comment]
<img width="599" alt="image" src="https://user-images.githubusercontent.com/110809584/207754376-a037e3aa-a12c-49f5-b2f2-4b9769da246a.png">
Seems it works well at my side, could give more information about graph and environment?

**Comment by jermainewang** [comment]
Hi @yuanhaitao , I am closing this issue assuming you are happy about our response. Feel free to follow up and reopen the issue if you have more questions with regard to our response.
