### ISSUE TITLE
Two node types with same edge types 

### ISSUE THREAD

**Issue by sabadaftari** [dmlc/dgl#4739]
## 🔨Work Item

**IMPORTANT:**
* This template is only for dev team to track project progress. For feature request or bug report, please use the corresponding issue templates.
* DO NOT create a new work item if the purpose is to fix an existing issue or feature request. We will directly use the issue in the project tracker.

Project tracker: https://github.com/orgs/dmlc/projects/2

## Description

Hello,

I would like to integrate two node types that have the same edge type in my .yaml file  just like this:
- file_name: edges_0.csv
  etype: [protein, binding, protein]
- file_name: edges_1.csv
  etype: [metabolite, binding, protein]

This binding etype is the same type of edge between two different node types.
Should I make two different types of edges like binding1 and binding2? or creating two graphs instead?

I got the following error:

`Exception has occurred: DGLError
Each edge CSV file must have a unique edge type name, but found duplicate edge type: [('protein', 'binding', 'protein'), ('metabolite', 'binding', 'protein')].
  File "/path1.py", line 66, in process
    graph = dgl.data.CSVDataset(self.raw_path)
  File "path2.py", line 31, in __init__
    super(PPI_data, self).__init__(
  File "path3", line 29, in <module>
    dataset = PPI_data(name='_copy')`

**Comment by frozenbugs** [comment]
Hi sabadaftari:

Yes, you can use 2 bindings as a workaround.
Ideally, our data loader should support assigning same edge type to different node type pairs.
It would be helpful if you can help us support this.
We are happy to guide.

Thanks

**Comment by sabadaftari** [comment]
Hi frozenbugs,

Of course, I would love to contribute to this. But I don't know how really, if you guide me I will do it! Tnx.

**Comment by Rhett-Ying** [comment]
@sabadaftari  canonical etype is used according to https://github.com/dmlc/dgl/blob/0cb5f0fdc00e1e6a040084c96ec9f16c532bed65/python/dgl/data/csv_dataset_base.py#L76-L82 and the log you shared. the exception is unexpected. could you provide a minimal repro code snippet.?

**Comment by Rhett-Ying** [comment]
Hi @sabadaftari , I am closing this issue assuming you are happy about our response. Feel free to follow up and reopen the issue if you have more questions with regard to our response.
