### ISSUE TITLE
GATv2Conv assigns src to dst if block

### ISSUE THREAD

**Issue by theisjendal** [dmlc/dgl#4775]
## 🐛 Bug
Hi, 

I think it is a bug given the definition of GATv2 attention mechanism:
<img src="https://latex.codecogs.com/svg.image?\alpha_{ij}^{(l)}&space;=&space;{a^T}^{(l)}\mathrm{LeakyReLU}(W^{(l)}_{left}&space;h_{i}&space;&plus;&space;W^{(l)}_{right}&space;h_{j})"/>

I.e., the head and tail are transformed with different weight matrices. Yet, the GATv2Conv on line 284 when the graph is a block, the src features are assigned to the dst features: `feat_dst = feat_src[:graph.number_of_dst_nodes()]`. I assume `feat_src` should have been `feat_dst`.

Best regards,
Theis

**Comment by peizhou001** [comment]
[DGLBlock](https://docs.dgl.ai/en/0.9.x/generated/dgl.to_block.html?highlight=dglblock) source nodes are prefixed by destination node, so this should not a bug. But it **feat_dst MLP** is redundant at that case.
