### ISSUE TITLE
Cannot imort JumpingKnowledge from dgl.nn

### ISSUE THREAD

**Issue by ck-ksst** [dmlc/dgl#4779]
## ❓ Questions and Help
I transcribed this repository in order to understand representation learning and graph neural network.
I implemented in singularity and the environment I made follows:

Python 3.6.15
dgl 0.6.0
scikit-learn 0.24.1
tqdm 4.56.0
torch 1.7.1+cuda110

However I can't import JumpingKnowledge from dgl.nn line 6 in model.py and I got an error like this:
```Traceback (most recent call last):
  File "main.py", line 8, in <module>
    from model import JKNet
  File "/work/koki-ki/GraphNeuralNetwork/JKNet/model.py", line 7, in <module>
    from dgl.nn import GraphConv, JumpingKnowledge
ImportError: cannot import name 'JumpingKnowledge'
```

Then I checked on Google Colab that dgl==0.6.0 has the function "JumpingKnowledge" by using : 
```
!pip install dgl==0.6.0
dir(dgl.nn)
```
Finally I couldn't see the function in the list.

How can I import dgl.nn.JumpingKnowledge?

Or I can't import this function today?

**Comment by mufeili** [comment]
You need to install DGL >= 0.8.0 for `JumpingKnowledge`.

Also make sure you check dgl.__version__ as sometimes you can have multiple versions of DGL installed.

**Comment by ck-ksst** [comment]
Thanks a lot!
I followed the mannual made by dgl so I couldn't believe it was a mistake.
