### ISSUE TITLE
‘ctx’ parameter in DGLGraph.adj() function not clear

### ISSUE THREAD

**Issue by RtekiX** [dmlc/dgl#4782]
## 📚 Documentation

![image](https://user-images.githubusercontent.com/40229223/198970618-6523315d-8481-4bec-af27-681e73b8339f.png)
I asked a question about ‘ctx’ parameter in DGLGraph.adj() a few days ago to ensure if ‘ctx’ parameter in the image means 'device', because the default is 'cpu'. And the anwser is below.
![image](https://user-images.githubusercontent.com/40229223/198971128-e34f53b7-2678-4468-a860-e49bfa2fd4aa.png)

**Comment by mufeili** [comment]
`ctx` is the device of the returned adjacency matrix if `scipy_fmt` is `None`. Do you have any further questions?

**Comment by RtekiX** [comment]
> `ctx` is the device of the returned adjacency matrix if `scipy_fmt` is `None`. Do you have any further questions?

Thank you for your explanation again. Actually I've got the answer in DGL Slack channel as you can see in the second image.

I created this issue just in response to the man who answered my question in Slack, so anyone working on documentation can track this and improve its description.

**Comment by mufeili** [comment]
Got it. Thanks. I'll close this issue then. Feel free to reopen it if you have further questions.
