### ISSUE TITLE
[Bug] YelpDataset Returns Masks with Type `torch.ByteTensor`

### ISSUE THREAD

**Issue by chwan1016** [dmlc/dgl#4806]
## 🐛 Bug

When YelpDataset is loaded, the type of masks are ByteTensor, which is not consistent with other popular datasets (e.g., Cora and Reddit).

## To Reproduce

```python
from dgl.data import CoraGraphDataset, RedditDataset, YelpDataset

cora_g = CoraGraphDataset()[0]
reddit_g = RedditDataset()[0]
yelp_g = YelpDataset()[0]

print(cora_g.ndata['train_mask'].type())  # torch.BoolTensor
print(reddit_g.ndata['train_mask'].type())  # torch.BoolTensor
print(yelp_g.ndata['train_mask'].type())  # torch.BoolTensor if Yelp is newly downloaded else torch.ByteTensor
print(yelp_g.ndata['train_mask'].type())  # torch.ByteTensor
```

## Expected behavior

The masks of the three datasets should have consistent tensor types.

## Environment

 - DGL Version (e.g., 1.0): 0.9.1
 - Backend Library & Version (e.g., PyTorch 0.4.1, MXNet/Gluon 1.3): PyTorch 1.12.0
 - OS (e.g., Linux): Linux

**Comment by BarclayII** [comment]
Since it happens only in old versions, I guess you can clear the downloaded data in `~/.dgl`?

**Comment by mufeili** [comment]
Could you try `yelp_g = YelpDataset(force_reload=True)`?

**Comment by chwan1016** [comment]
Thanks. After installing the master branch from source, the issue is fixed.
