### ISSUE TITLE
[Sparse] Support elementwise operators on matrices with different sparsity

### ISSUE THREAD

**Issue by czkkkkkk** [dmlc/dgl#4820]
## 🔨Work Item

**IMPORTANT:**
* This template is only for dev team to track project progress. For feature request or bug report, please use the corresponding issue templates.
* DO NOT create a new work item if the purpose is to fix an existing issue or feature request. We will directly use the issue in the project tracker.

Project tracker: https://github.com/orgs/dmlc/projects/2

**Comment by frozenbugs** [comment]
A <op> D, D <op> A
A1(w1) <op> A2(w2)

**Comment by frozenbugs** [comment]
duplicate with https://github.com/dmlc/dgl/issues/4859
