### ISSUE TITLE
How to avoid the problem that sampling will overlap with training

### ISSUE THREAD

**Issue by MrChen-NJU** [dmlc/dgl#4821]
## ❓ Questions and Help

I meet a question which caused trouble for my measurements of time of sampling.
I'm training a GNN model based on minibatch sampling, and I want to measue the decomposed time of sampling and transfering features and training.
But I find the problem that on the following two cases: graph feature data is on GPU or not, the time of sampling is very different.
I mean, when the graph feature data is on GPU, the epoch time is 11s = **10**s(sample) + 0s(transfer) + 1s(training),
when the graph feature data is **not** on GPU, the epoch time is 16s = **5**s(sample) + 10s(transfer) + 1s(training).
I use CPU to sample the blocks.
In my opinion, when the graph feature data is **not** on GPU, some of sampling time *overlapped* with transfering time. I know this will help improve the training performance, but it also make me having trouble measuring the time correctly.

I wanna is there any way that I can stop sampling when I'm doing transfering and training.

**Comment by yaox12** [comment]
One simple solution is popping out the node features before training and slicing them manually in the train loop. For example,
```python
# better to make sure you have popped all ndata out, even some are not used in training
node_features = g.ndata.pop('h') 
...
for input_nodes, output_nodes, blocks in train_loader:
    input_features = node_features[input_nodes].to(device)
    ...
```

**Comment by BarclayII** [comment]
How about removing all the code for training and measure the time of the empty for loop instead?
```python
t0 = time.time()
for _ in dataloader:
    pass
tt = time.time()
```

**Comment by MrChen-NJU** [comment]
> How about removing all the code for training and measure the time of the empty for loop instead?
> 
> ```python
> t0 = time.time()
> for _ in dataloader:
>     pass
> tt = time.time()
> ```

thanks for ur advice. i think i will adopt this way because it seems that there is no other availabel measures for this problem
