### ISSUE TITLE
Warning of the initializer

### ISSUE THREAD

**Issue by allanj** [dmlc/dgl#483]
## ❓ Questions and Help

I ran the example in [RGCN documentation](https://docs.dgl.ai/tutorials/models/1_gnn/4_rgcn.html), and got the following warning:

```
UserWarning: Initializer is not set. Use zero initializer instead. To suppress this warning, use `set_initializer` to explicitly specify which initializer to use.
warnings.warn(msg)
```

Do I need to take care of this OR I can simply ignore it?
Also, what does it mean actually?

I'm using PyTorch 0.4.1 and Python3.6

**Comment by jermainewang** [comment]
Hi, checkout this [thread](https://discuss.dgl.ai/t/about-setting-initializer/64) for the similar question. You could also follow up the discussion there. Basically, you could ignore it if you don't care what initial value is for node/edge features.
