### ISSUE TITLE
[Sparse] Support sparse-dense matmul and SDDMM

### ISSUE THREAD

**Issue by czkkkkkk** [dmlc/dgl#4855]
## 🔨Work Item

Project tracker: https://github.com/orgs/dmlc/projects/2

**Comment by jermainewang** [comment]
#4999 is reverted due to design flaw. Will need two PRs to finish this task:
- [ ] Expose DGL's `SpMMCsr`, `SpMMCoo`, `SDDMMCsr` and `SDDMMCoo` to as include headers.
- [ ] Add a new `transpose_A` flag to the SpMM signature in the new sparse library to support implicit format materialization.
