### ISSUE TITLE
batched graph classification example - gpu

### ISSUE THREAD

**Issue by hellboy5** [dmlc/dgl#486]
I am trying to convert the https://docs.dgl.ai/tutorials/basics/4_batch.html to use a single gpu, however i am getting an issue at 
 loss = loss_func(prediction, label)
RuntimeError: Expected object of backend CUDA but got backend CPU for argument #2 'target'

what other variables do I need to provide .cuda to .to for?

**Comment by VoVAllen** [comment]
Do you convert all `bg`, `label` and `model` to cuda?

**Comment by mufeili** [comment]
As @VoVAllen said, you will need to move `label` to cuda.

**Comment by hellboy5** [comment]
thanks

**Comment by mufeili** [comment]
@hellboy5 Do you still have issues here? If not we will close the issue.

**Comment by hellboy5** [comment]
Please Close the issue. Though you should add something on the documentation page about running on single and multi gpus.
