### ISSUE TITLE
AttributeError: module 'dgl.nn' has no attribute 'pytorch'

### ISSUE THREAD

**Issue by zhangyu2ustc** [dmlc/dgl#487]
## 🐛 Bug

I was trying to replicate the gat example when there was this error message saying that: AttributeError: module 'dgl.nn' has no attribute 'pytorch'

I have tried to uninstall and re-install the dgl package but still shows the same error
## To Reproduce

1.
1.
1.

## Environment

 - DGL Version (e.g., 1.0): dgl-0.2-cp36-cp36m-manylinux1_x86_64.whl 
 - Backend Library & Version (e.g., PyTorch 0.4.1, MXNet/Gluon 1.3): pytorch-1.0.0
 - OS (e.g., Linux): ubuntu 18.0
 - How you installed DGL (`conda`, `pip`, source): pip install dgl
 - Build command you used (if compiling from source):
 - Python version: 3.6
 - CUDA/cuDNN version (if applicable): 9.0
 - GPU models and configuration (e.g. V100): GTX1700
 - Any other relevant information:

**Comment by mufeili** [comment]
Could you please try installing dgl from source?

**Comment by jermainewang** [comment]
@zhangyu2ustc do you still have the problem? I cannot reproduce the problem. Could you also verify whether there is a "pytorch" folder under "<your_dgl_package_location>/nn"?

**Comment by jermainewang** [comment]
Closed due to inactivity. Please reopen if issue still exists.

**Comment by yxtj** [comment]
I got the same problem.
I installed dgl and pytorch (with GPU) using conda.
I am running Windows 10.

**Comment by yxtj** [comment]
I solved this problem and opened an issue at https://github.com/dmlc/dgl/issues/1292

Before the bug is fixed, we can add `import dgl.nn.python` instead of simply `import dgl` or `import dgl.nn` before access the modules.
