### ISSUE TITLE
[Sparse] Hypergraph Convolution and Hypergraph Attention

### ISSUE THREAD

**Issue by frozenbugs** [dmlc/dgl#4871]
## 🔨Work Item

**IMPORTANT:**
* This template is only for dev team to track project progress. For feature request or bug report, please use the corresponding issue templates.
* DO NOT create a new work item if the purpose is to fix an existing issue or feature request. We will directly use the issue in the project tracker.

Project tracker: https://github.com/orgs/dmlc/projects/2

**Comment by BarclayII** [comment]
HyperSCI has too much code for setting up evaluating causality, and hypergraph convolution is not the main part of it.
I propose changing this to implementing Hypergraph Convolution and Hypergraph Attention https://arxiv.org/pdf/1901.08150.pdf.
