### ISSUE TITLE
[DistDGL][Bug] Node type and node feature can not use the same name.

### ISSUE THREAD

**Issue by classicsong** [dmlc/dgl#4887]
## 🐛 Bug
In DistDGL, If both node type and one of its node feature have the same name, the system will crash.
The bug is related to https://github.com/dmlc/dgl/blob/ee9887d66a9eb6dc9663a5238e1874b7646acf3a/python/dgl/distributed/dist_graph.py#L172-L196

## To Reproduce

1.
1.
1.

## Environment

 - DGL Version (e.g., 1.0): NIghtly build and 0.9.0
 - Backend Library & Version (e.g., PyTorch 0.4.1, MXNet/Gluon 1.3):
 - OS (e.g., Linux):
 - How you installed DGL (`conda`, `pip`, source):
 - Build command you used (if compiling from source):
 - Python version:
 - CUDA/cuDNN version (if applicable):
 - GPU models and configuration (e.g. V100):
 - Any other relevant information:

**Comment by classicsong** [comment]
Any ETA?

**Comment by Rhett-Ying** [comment]
I will open a PR end of today
