### ISSUE TITLE
Decouple size of the features files (for nodes and edges data) from nodes_per_chunk and edges_per_chunk entries in the metadata json for Graph Partitioning Piepline

### ISSUE THREAD

**Issue by kylasa** [dmlc/dgl#4888]
## 🚀 Feature

Currently, in the distributed graph partitioning pipeline we use 

nodes_per_chunk
edges_per_chunk

to indicate the number of nodes/edges per node (or process). 

In addition to this constraint, we also enforce this constraint to be applicable on the node and edge feature files. The node and edge feature files, which are numpy files, are expected to have number of rows to be equal to the counts indicated in the "nodes_per_chunk" and "edges_per_chunk". 

For example, if we have 

edges_per_chunk = [
[100, 100, 100, 100],  #edge_type_1
[200, 200, 200, 200] #edge_type_2
]

then the graph is expected to partitioned 4 partitions. And if the edge_type_1 and edge_type_2 have associated edge feature data. Then the edge feature files are expected to have 100 for edge_type_1 and 200 for edge_type_2 number of rows in the numpy files. 

The same argument is applicable for nodes_per_chunk and associated node feature files as well. 

The problem with the above setup is that for massively large graphs, for instance graphs in the gnn framework, the edge and node feature files are expected to have hundereds or thousands of dimensions. If the edges, per edge_type, processed by a given node/process is very large then in this case the corresponding edge feature files may be very large occupying a very large disk space. And in some cases, during the data generation phase it might not be possible for the graph generation scripts to generate edge (and node) feature files to have same number of rows as indicated by the nodes_per_chunk ( and edges_per_chunk for edge feature files). 

To address these concerns, we requires that this constraint be relaxed so that edges_per_chunk and edges files and edge features files to have different number of rows/entries compared to edges_per_chunk. The argument is applicable for nodes and related node features as well.

**Comment by classicsong** [comment]
For large dataset, it is highly possible that we break a feature storage into tens or hundreds of files. So it is unlikely to ask every user to write a pre-processing script which will create node/edge feature files matches edges_per_chunk and nodes_per_chunk
