### ISSUE TITLE
Create Block for sampling

### ISSUE THREAD

**Issue by YijianLiu** [dmlc/dgl#4934]
I find that create_block is just a block not suitable sampling, it does no renumbering, and can not for training, 
whether any method can achieve such as I renumber for the block?

**Comment by YijianLiu** [comment]
Now I try to construct blocks by myself using to_block. And we get two blocks but they don't follow by right order for map and renumbering , Will this affect our training and message passing？ For example:
**Ours:** 
blocks[1].ndata[dgl.NID]  {'_N': tensor([ 8,  4,  5,  7, 11])}
blocks[0].ndata[dgl.NID]  {'_N': tensor([ 8,  2,  3,  6, 10,  4,  5,  7, 11])}

**Right by Using DataLoader**
blocks[1].ndata[dgl.NID]  {'_N': tensor([ 8,  4,  5,  7, 11])}
blocks[0].ndata[dgl.NID]  {'_N': tensor([ 8,  4,  5,  7, 11,  2,  3,  6, 10])}
We can see for daatloader, new numbers {2, 3, 6, 10} is after the previous one map index.

**Comment by czkkkkkk** [comment]
Hi, @YijianLiu . A block is a bipartite graph with source and destination nodes. You can inspect their IDs by `blocks[0].srcdata[dgl.NID]` and `blocks[0].dstdata[dgl.NID]`. The destination nodes are the first few nodes of the source nodes. In particular, the edges of a block are renumbered, so the message passing is working correctly.

**Comment by BarclayII** [comment]
Please feel free to reopen if the answer above did not resolve your problem.  Thanks!
