### ISSUE TITLE
How to define accuracy function in R-GCN?

### ISSUE THREAD

**Issue by Abhinav43** [dmlc/dgl#494]
Hi, 
I am working on edge prediction task and for that I am using r-gcn model. I have few questions related to r-gcn model :

What is MRR (raw) , Hits (raw ) in r-gcn?
How to get accuracy score in r-gcn during training and during evaluating?

Thank you !

**Comment by mufeili** [comment]
It seems that this is now being discussed in [a discussion thread](https://discuss.dgl.ai/t/how-to-define-accuracy-function-in-r-gcn/216) so I will close the issue.
