### ISSUE TITLE
[Bug] `test_hgt()` fails occasionally

### ISSUE THREAD

**Issue by yaox12** [dmlc/dgl#4947]
## 🐛 Bug

For example, https://dgl-ci-result.s3.us-west-2.amazonaws.com/dgl/PR-4945/2/2/logs/logs_dir/tmptu_jbww_.log 

`num_dst_nodes` of the block is 7 sometimes and results in the error.
https://github.com/dmlc/dgl/blob/c59000ac3ad12ad5e1f769267742d10174de4921/tests/pytorch/test_nn.py#L1530

cc @dddg617 @jermainewang 

## To Reproduce

1. Run the unit test locally by `python -m pytest -v tests/pytorch/test_nn.py`

## Expected behavior

CI always succeeds.

## Environment

 - DGL Version (e.g., 1.0): master
 - Backend Library & Version (e.g., PyTorch 0.4.1, MXNet/Gluon 1.3): PyTorch 1.13
 - OS (e.g., Linux): Linux
 - How you installed DGL (`conda`, `pip`, source): source
 - Build command you used (if compiling from source):
 - Python version: 3.8
 - CUDA/cuDNN version (if applicable): 
 - GPU models and configuration (e.g. V100):
 - Any other relevant information:

**Comment by BarclayII** [comment]
The reason is that the training index could generate duplicate indices.  So it's related to #3431 .  The "correct" fix would be changing the training index generation in L1519.
