### ISSUE TITLE
Loading and save model weights for GAT

### ISSUE THREAD

**Issue by karansapra** [dmlc/dgl#495]
Has anyone tried to save weights and then during inference load the saved weights. Seems like its not doing the right thing and producing garbage output as if it was starting from untrained weights.

**Comment by mufeili** [comment]
Could you please provide a minimal block of code about the dataset you use, the model architecture and how you load a pre-trained model? It will also be very appreciated if you can provide a link to your model weights.

**Comment by karansapra** [comment]
@mufeili 👍  let me get it you a snippet soon.
Just curious, has anyone tried loading and saving weights with DGL?

**Comment by jermainewang** [comment]
Which backend are you using? Loading and saving models should be the same
as other models in pytorch/mxnet.

**Comment by jermainewang** [comment]
@karansapra Any update on this?

**Comment by mufeili** [comment]
Close the issue as this seems to be no longer active.

**Comment by karansapra** [comment]
Sorry, it was a bug on my part. I apologize for the inconvenience.
