### ISSUE TITLE
cuGraph RGCN module doc is not rendered properly

### ISSUE THREAD

**Issue by jermainewang** [dmlc/dgl#4960]
## 📚 Documentation

https://docs.dgl.ai/en/latest/api/python/nn-pytorch.html

![image](https://user-images.githubusercontent.com/4057701/204203298-13c09abd-5942-4e5d-a806-a468448ba529.png)

@tingyu66 @mufeili

**Comment by tingyu66** [comment]
https://github.com/dmlc/dgl/blob/master/python/dgl/nn/pytorch/conv/__init__.py#L70-L75

It seems that the workflow that generated the docs did not have `pylibcugraphops` installed (as it is an optional dependency), and thus we don't have `dgl.nn.pytorch.conv.CuGraphRelGraphConv` defined. The release date of rapids 22.12 is 12/8/22, so we have to use the nightly build to generate docs before then.

**Comment by jermainewang** [comment]
I see. Maybe we should move the try/catch to class init. In this way, there will still be a `CuGraphRelGraphConv` class so the doc tool can correctly parse the docstring. Errors will be thrown when users try to create a module instance.

**Comment by tingyu66** [comment]
Shall we close this issue as the doc has been fixed?
