### ISSUE TITLE
[Sparse] Clean up unnecessary APIs from existing mock sparse code and api doc

### ISSUE THREAD

**Issue by frozenbugs** [dmlc/dgl#4964]
## 🔨Work Item

**IMPORTANT:**
* This template is only for dev team to track project progress. For feature request or bug report, please use the corresponding issue templates.
* DO NOT create a new work item if the purpose is to fix an existing issue or feature request. We will directly use the issue in the project tracker.

Project tracker: https://github.com/orgs/dmlc/projects/2

## Depending work items or issues

- [ ] indices() 
- [x] SparseMatrix.inv()
- [x] DiagMatrix.softmax()
- [x] all reduce methods on DiagMatrix

**Comment by jermainewang** [comment]
@mufeili Could you help check if the tasks here have already been done?

**Comment by mufeili** [comment]
@jermainewang `SparseMatrix.indices()` still exists. Do we want to remove it?

**Comment by jermainewang** [comment]
Yes, `SparseMatrx.indices()` can be removed as it is replaceable by `SparseMatrix.coo|csc|csr`.

**Comment by mufeili** [comment]
> Yes, `SparseMatrx.indices()` can be removed as it is replaceable by `SparseMatrix.coo|csc|csr`.

Addressed in #5108
