### ISSUE TITLE
[Bug] Labor Sampler not showing in documentation

### ISSUE THREAD

**Issue by mfbalin** [dmlc/dgl#4967]
## 📚 Documentation

API reference part.

The new algorithms and API for LABOR sampler added in #4668 don't show up in the documentation.

![image](https://user-images.githubusercontent.com/16190101/204451482-02e5feff-b3a8-4839-8b4f-aabd48c1744c.png)

**Comment by rudongyu** [comment]
I checked #4668. The corresponding item need to be added in [the doc index](https://github.com/dmlc/dgl/blob/master/docs/source/api/python/dgl.dataloading.rst) to be properly presented in the documentation.

**Comment by mfbalin** [comment]
It is not just dataloading, Labor sampler has functional sampling API too. Just like sample_neighbors, there is a function sample_labors.

**Comment by mfbalin** [comment]
> Sure. @mfbalin Could you open a corresponding PR to fix this? Thanks a lot!

Initially, I wasn't sure how the fix should be, but with the pointers you gave, I can do it.
