### ISSUE TITLE
dgl.graph dosn't support tensorflow's tensor 

### ISSUE THREAD

**Issue by StrangersZero** [dmlc/dgl#4978]
## To Reproduce

```python
import tensorflow as tf
import dgl
source = tf.constant([0,1,2,3,3,3], dtype=tf.int32)
target = tf.constant([1,0,1,0,1,2], dtype=tf.int32)
g = dgl.graph((source,target))
g = dgl.add_self_loop(g)
print(g)
```

## Expected behavior

Graph(num_nodes=4, num_edges=10,
      ndata_schemes={}
      edata_schemes={})

## Environment

 - DGL Version (e.g., 1.0):0.9
 - Backend Library & Version (e.g., PyTorch 0.4.1, MXNet/Gluon 1.3):tf 2.11.0
 - OS (e.g., Linux):windows
 - How you installed DGL (`conda`, `pip`, source):pip
 - Build command you used (if compiling from source):
 - Python version: 3.9
 - CUDA/cuDNN version (if applicable):
 - GPU models and configuration (e.g. V100):
 - Any other relevant information:

## Additional context
- It raise TypeError: Scalar tensor has no `len()`
- And when dgl.graph's parameters builtin torch.tensor, it can run well.
- I have seen user.doc about this, it only mentions usage of torch.
- So i think it may not support tensorflow's tensor

**Comment by StrangersZero** [comment]
#### I  forgot to set up the backend. Can you tell me is there any method to set up the backend? Thanks!!!

**Comment by yaox12** [comment]
Refer to https://docs.dgl.ai/en/latest/install/index.html#working-with-different-backends.
