### ISSUE TITLE
How do I predict certain triplet or relation on RGCN

### ISSUE THREAD

**Issue by eric2213** [dmlc/dgl#4981]
I'm training on RGCN with pytorch, I want to get the accuracy or MRR of each relation, is it possible?

I'm thinking of making several testing dataset, each of dataset consists of only one relation, and test them one by one by the trained and saved RGCN model, would this idea work?

I'm pretty new to computer science, an example would be very helpful.

**Comment by peizhou001** [comment]
If accuracy of each relation means training use each relation separately, the way you mention works.
If it is to measure the ratio each relation takes to overall model(trained using all relations), this doesn’t work. To achieve this, maybe check the final trained weight of each relation is more reasonable.

**Comment by Rhett-Ying** [comment]
Hi @eric2213 , I am closing this issue assuming you are happy about our response. Feel free to follow up and reopen the issue if you have more questions with regard to our response.
