### ISSUE TITLE
[Doc] Layout issues in doc 0.9.x

### ISSUE THREAD

**Issue by Ereboas** [dmlc/dgl#4993]
## 📚 Documentation

Please specify whether it's tutorial part or API reference part: API reference part, doc version 0.9.x
  

### Description
In some of the API reference pages, such as https://docs.dgl.ai/en/0.9.x/api/python/nn-pytorch.html, the method/class name is divided into multiple lines, thus reducing readability.

**Comment by yaox12** [comment]
The latest doc looks good. https://docs.dgl.ai/en/latest/api/python/nn-pytorch.html

**Comment by mufeili** [comment]
> The latest doc looks good. https://docs.dgl.ai/en/latest/api/python/nn-pytorch.html

Yes, now this issue only occurs for 0.9.x.

**Comment by mufeili** [comment]
fixed
