### ISSUE TITLE
Build from source fail with deprecation

### ISSUE THREAD

**Issue by flint-stone** [dmlc/dgl#5007]
## 🐛 Bug

I'm following the instruction provided here: https://docs.dgl.ai/install/index.html#install-from-source to build DGL from source and I'm getting the following error (with both library tensorpipe and libxsmm) :

```
dgl/third_party/tensorpipe/third_party/libuv/src/unix/thread.c:195:24: error: comparison of integer expressions of different signedness: ‘rlim_t’ {aka ‘long unsigned int’} and ‘long int’ [-Werror=sign-compare]
  195 |       if (lim.rlim_cur >= PTHREAD_STACK_MIN)
      |                        ^~
```

```
dgl/third_party/tensorpipe/third_party/libuv/src/unix/thread.c: In function ‘uv_thread_create_ex’:
dgl/third_party/tensorpipe/third_party/libuv/src/unix/thread.c:243:20: error: comparison of integer expressions of different signedness: ‘size_t’ {aka ‘long unsigned int’} and ‘long int’ [-Werror=sign-compare]
 243 |     if (stack_size < PTHREAD_STACK_MIN)
    |                    ^
```

```
./src/libxsmm_malloc.c:2434:5: error: ‘pthread_yield’ is deprecated: pthread_yield is deprecated, use sched_yield instead [-Werror=deprecated-declarations]
 2434 |     LIBXSMM_LOCK_ACQUIRE(LIBXSMM_LOCK, lock);
      |     ^~~~~~~~~~~~~~~~~~~~
In file included from /usr/include/features.h:486,
                 from /usr/include/pthread.h:21,
                 from include/libxsmm_macros.h:826,
                 from ./src/libxsmm_trace.h:14,
                 from ./src/libxsmm_malloc.c:11:
/usr/include/pthread.h:479:12: note: declared here
```

What is the correct version of compiler I should be using?

## To Reproduce

```
cmake ..
make -j4
```

 - DGL Version (e.g., 1.0): latest git repo
 - Backend Library & Version (e.g., PyTorch 0.4.1, MXNet/Gluon 1.3):
 - OS (e.g., Linux):  5.15.0-53-generic #59-Ubuntu SMP Mon Oct 17 18:53:30 UTC 2022 x86_64 x86_64 x86_64 GNU/Linux
 - How you installed DGL (`conda`, `pip`, source): source
 - Build command you used (if compiling from source): See above
 - Python version:  3.9.13
 - CUDA/cuDNN version (if applicable): 11.7
 - GPU models and configuration (e.g. V100): A100
 - Any other relevant information:

GNU Compiler Collection: gcc 9.5.0, g++ 9.5.0, and gfortran 11.3.0
cmake version 3.22.1, GNU Make 4.2.1

**Comment by jermainewang** [comment]
Hi @flint-stone , could you try build without tensorpipe and libxsmm? Will the error still happen?

**Comment by frozenbugs** [comment]
Hi @flint-stone , I am closing this issue assuming you are happy about our response. Feel free to follow up and reopen the issue if you have more questions with regard to our response.
