### ISSUE TITLE
Check failed: entrypoints_[i]: cannot locate symbol CUDARawAlloc

### ISSUE THREAD

**Issue by phu-minh** [dmlc/dgl#5018]
## ❓ Questions and Help
When i ran DGL on Google Colab (Pro), I got this bug. How to fix it :( Really need some help. Last week i ran it normally (different cuda version but its ran perfectly) 
> 
> DGL backend not selected or invalid.  Assuming PyTorch for now.
> Setting the default backend to "pytorch". You can change it in the ~/.dgl/config.json file or export the DGLBACKEND environment variable.  Valid options are: pytorch, mxnet, tensorflow (all lowercase)
> terminate called after throwing an instance of 'dmlc::Error'
>   what():  [14:38:14] /opt/dgl/src/runtime/tensordispatch.cc:50: Check failed: entrypoints_[i]: cannot locate symbol CUDARawAlloc
> Stack trace:
>   [bt] (0) /usr/local/lib/python3.9/dist-packages/dgl/libdgl.so(dmlc::LogMessageFatal::~LogMessageFatal()+0x4f) [0x7fb9f3c5ed7f]
>   [bt] (1) /usr/local/lib/python3.9/dist-packages/dgl/libdgl.so(dgl::runtime::TensorDispatcher::Load(char const*)+0x19b) [0x7fb9f3fb348b]
>   [bt] (2) /usr/local/lib/python3.9/dist-packages/dgl/libdgl.so(DGLLoadTensorAdapter+0x26) [0x7fb9f3f846f6]
>   [bt] (3) /usr/lib/x86_64-linux-gnu/libffi.so.6(ffi_call_unix64+0x4c) [0x7fba917d0dae]
>   [bt] (4) /usr/lib/x86_64-linux-gnu/libffi.so.6(ffi_call+0x22f) [0x7fba917d071f]
>   [bt] (5) /usr/lib/python3.9/lib-dynload/_ctypes.cpython-39-x86_64-linux-gnu.so(+0x12103) [0x7fba91a0e103]
>   [bt] (6) /usr/lib/python3.9/lib-dynload/_ctypes.cpython-39-x86_64-linux-gnu.so(+0xc34a) [0x7fba91a0834a]
>   [bt] (7) python3(_PyObject_MakeTpCall+0x31c) [0x5fa29c]
>   [bt] (8) python3(_PyEval_EvalFrameDefault+0x472e) [0x576fce]
> 

Python ver: 3.8.16, I have tried up/downgrade the python version but not working.
Cuda version: GPU: Colab Tesla T4, 
> Cuda compilation tools, release 11.2, V11.2.152
> Build cuda_11.2.r11.2/compiler.29618528_0

Installed with dgl111:
> !pip -q install dgl-cu111 dglgo -f https://data.dgl.ai/wheels/repo.html

**Comment by phu-minh** [comment]
Try to run it on Kaggle notebook with 2 T4 gpus, 

> Cuda compilation tools, release 11.0, V11.0.221
> Build cuda_11.0_bu.TC445_37.28845127_0

It ran perfectly, what happen to Colab then?

**Comment by phu-minh** [comment]
I'll leave it here if anybody encounter this issue. How to fix it: Downgrade the Pytroch version in Colab session (1.13 -> 1.12) and it will be fine.

**Comment by 664730** [comment]
> I'll leave it here if anybody encounter this issue. How to fix it: Downgrade the Pytroch version in Colab session (1.13 -> 1.12) and it will be fine.

What if the PyTorch version requires 1.13? thanks.
