### ISSUE TITLE
Construct BatchedDGLGraph from readonly DGLGraph

### ISSUE THREAD

**Issue by mwcvitkovic** [dmlc/dgl#502]
## 🚀 Feature

Currently readonly DGLGraphs cannot be combined into a BatchedDGLGraph.  But since a BatchedDGLGraph is itself readonly, this seems like an unnecessary blockage.

**Comment by jermainewang** [comment]
You are right. That should be fixed. @VoVAllen @mufeili  do you guys have time to look into this?

**Comment by jermainewang** [comment]
The feature should be supported via PR #539.
