### ISSUE TITLE
[Sparse] Disable Using Tensors of >=3D for Nonzero Values

### ISSUE THREAD

**Issue by mufeili** [dmlc/dgl#5023]
## 🔨Work Item

**IMPORTANT:**
* This template is only for dev team to track project progress. For feature request or bug report, please use the corresponding issue templates.
* DO NOT create a new work item if the purpose is to fix an existing issue or feature request. We will directly use the issue in the project tracker.

Project tracker: https://github.com/orgs/dmlc/projects/2

**Comment by mufeili** [comment]
@frozenbugs I set it to medium for the time being.

**Comment by frozenbugs** [comment]
Assign to czkkkkkk to make sure this is not missed in the planning.

**Comment by czkkkkkk** [comment]
Solved by #5204.
