### ISSUE TITLE
Are there benchmarks for DistDGL_v2 ?

### ISSUE THREAD

**Issue by husimplicity** [dmlc/dgl#5025]
## ❓ Questions and Help
It seems there are no benchmarks on distributed sampling or e2e training. Do you have benchmark examples for DistDGL_v2? Thanks!

**Comment by Rhett-Ying** [comment]
DistDGL_v2, which one do you mean? the one mentioned in this paper: https://arxiv.org/pdf/2112.15345.pdf ?

**Comment by husimplicity** [comment]
> DistDGL_v2, which one do you mean? the one mentioned in this paper: https://arxiv.org/pdf/2112.15345.pdf ?

yes

**Comment by Rhett-Ying** [comment]
It's not fully merged into DGL yet, so no benchmark from DGL.

@zheng-da do you have anything related that could be shared?

**Comment by husimplicity** [comment]
> It's not fully merged into DGL yet, so no benchmark from DGL.
Then have functions for DistDGL_v1 fully merged into this repo? Thanks!

**Comment by husimplicity** [comment]
Then have functions for DistDGL_v1 fully merged into this repo? Thanks!

**Comment by Rhett-Ying** [comment]
yes. `//python/dgl/distributed/`

**Comment by husimplicity** [comment]
Hello, do you have examples for distributed sampling or e2e training that support multi-node multi-GPU for the current version? Thanks!

**Comment by Rhett-Ying** [comment]
see here: https://github.com/dmlc/dgl/tree/master/examples/pytorch/graphsage/dist

**Comment by husimplicity** [comment]
Hello, I tried the example above in a two-machine scenario, but got the error below. It seems something wrong with environ that it cannot find python command. I am using `sshfs` for file sharing. I've checked that `ssh` works well and the single machine case works well.

`python /home/workspace/dgl/tools/launch.py --ssh_port 8888 --workspace /home/workspace/dgl/examples/pytorch/graphsage/dist/ --num_trainers 2 --num_samplers 2 --num_servers 1 --part_config data/ogb-product.json --ip_config ip_config.txt "python train_dist.py --graph_name ogb-product --ip_config ip_config.txt --num_epochs 30 --batch_size 1000 --num_gpus 4"

The number of OMP threads per trainer is set to 32
bash: python: command not found
Called process error Command 'ssh -o StrictHostKeyChecking=no -p 8888 ip0 'cd /home/workspace/dgl/examples/pytorch/graphsage/dist/; (export DGL_ROLE=server DGL_NUM_SAMPLER=2 OMP_NUM_THREADS=1 DGL_NUM_CLIENT=12 DGL_CONF_PATH=data/ogb-product.json DGL_IP_CONFIG=ip_config.txt DGL_NUM_SERVER=1 DGL_GRAPH_FORMAT=csc DGL_KEEP_ALIVE=0 PYTHONPATH=/opt/conda/lib/python3.8/site-packages:..  DGL_SERVER_ID=0; python train_dist.py --graph_name ogb-product --ip_config ip_config.txt --num_epochs 30 --batch_size 1000 --num_gpus 4)'' returned non-zero exit status 127.
bash: python: command not found
Called process error Command 'ssh -o StrictHostKeyChecking=no -p 8888 ip1 'cd /home/workspace/dgl/examples/pytorch/graphsage/dist/; (export DGL_ROLE=server DGL_NUM_SAMPLER=2 OMP_NUM_THREADS=1 DGL_NUM_CLIENT=12 DGL_CONF_PATH=data/ogb-product.json DGL_IP_CONFIG=ip_config.txt DGL_NUM_SERVER=1 DGL_GRAPH_FORMAT=csc DGL_KEEP_ALIVE=0 PYTHONPATH=/opt/conda/lib/python3.8/site-packages:..  DGL_SERVER_ID=1; python train_dist.py --graph_name ogb-product --ip_config ip_config.txt --num_epochs 30 --batch_size 1000 --num_gpus 4)'' returned non-zero exit status 127.

bash: python: command not found
Called process error Command 'ssh -o StrictHostKeyChecking=no -p 8888 ip0 'cd /home/workspace/dgl/examples/pytorch/graphsage/dist/; (export DGL_DIST_MODE=distributed DGL_ROLE=client DGL_NUM_SAMPLER=2 DGL_NUM_CLIENT=12 DGL_CONF_PATH=data/ogb-product.json DGL_IP_CONFIG=ip_config.txt DGL_NUM_SERVER=1 DGL_GRAPH_FORMAT=csc OMP_NUM_THREADS=32 DGL_GROUP_ID=0 PYTHONPATH=/opt/conda/lib/python3.8/site-packages:.. ; python -m torch.distributed.launch --nproc_per_node=2 --nnodes=2 --node_rank=0 --master_addr=ip0 --master_port=1234 train_dist.py --graph_name ogb-product --ip_config ip_config.txt --num_epochs 30 --batch_size 1000 --num_gpus 4)'' returned non-zeroexit status 127.
bash: python: command not found
Called process error Command 'ssh -o StrictHostKeyChecking=no -p 8888 ip1 'cd /home/workspace/dgl/examples/pytorch/graphsage/dist/; (export DGL_DIST_MODE=distributed DGL_ROLE=client DGL_NUM_SAMPLER=2 DGL_NUM_CLIENT=12 DGL_CONF_PATH=data/ogb-product.json DGL_IP_CONFIG=ip_config.txt DGL_NUM_SERVER=1 DGL_GRAPH_FORMAT=csc OMP_NUM_THREADS=32 DGL_GROUP_ID=0 PYTHONPATH=/opt/conda/lib/python3.8/site-packages:.. ; python -m torch.distributed.launch --nproc_per_node=2 --nnodes=2 --node_rank=1 --master_addr=ip0 --master_port=1234 train_dist.py --graph_name ogb-product --ip_config ip_config.txt --num_epochs 30 --batch_size 1000 --num_gpus 4)'' returned non-zeroexit status 127.
cleanupu process runs
Task failed`

Could you plz give me some hints to solve this? Many thanks!
