### ISSUE TITLE
Add DGLGraph.to and similar methods

### ISSUE THREAD

**Issue by mwcvitkovic** [dmlc/dgl#503]
## 🚀 Feature

The user should be able to call DGLGraph.to(<device_id>) if using the Pytorch backend to change the device context of the graph's ndata (or DGLGraph.as_in_context(<device_id>) if using the MXNet backend).

Or, if this is undesirable because it is not backend agnostic, then some other method should be added to DGLGraph that changes the context of all its tensor attributes.

**Comment by jermainewang** [comment]
That's a fair request. I will make a PR for this.

> The user should be able to call DGLGraph.to(<device_id>) if using the Pytorch backend to change the device context of the graph's ndata

Note that I will also change the device of edge data.

**Comment by zheng-da** [comment]
this seems to associate DGLGraph to a certain context. another related question is whether we should allow tensors in DGLGraph to be in different contexts?

**Comment by jermainewang** [comment]
> this seems to associate DGLGraph to a certain context. another related question is whether we should allow tensors in DGLGraph to be in different contexts?

We still do. The API is to help the user to move all feature tensors to one device, which is a quite common case.

**Comment by jermainewang** [comment]
The feature has been released in v0.3.
