### ISSUE TITLE
Whether each server just only stores its own partitioned graph structure?

### ISSUE THREAD

**Issue by YijianLiu** [dmlc/dgl#5031]
Whether each server only stores its own graph structure?
As far as I am concerned, I think  each server must store the whole graph structure but not just the partitioned graph structure, so they can achieve dist sampling, 
for example, **server A** can know that node _1's three hops neighbors_ are in **server B**. 
Looking forward to your reply!!!

**Comment by frozenbugs** [comment]
@YijianLiu share you share slightly more context about what's your motivation in using graph partitioning?

**Comment by Rhett-Ying** [comment]
The servers on each node/machine stores one partition graph only. 

As for how to achieve dist sampling, it's based on [GraphPartitionBook](https://docs.dgl.ai/en/latest/api/python/dgl.distributed.html#graph-partition-book) and HALO nodes. When sampling, each server knows whether the target neighbor node exist on current server via GPB. If not, a pull request will be sent to target remote server which holds the expected nodes.

**Comment by YijianLiu** [comment]
> The servers on each node/machine stores one partition graph only.
> 
> As for how to achieve dist sampling, it's based on [GraphPartitionBook](https://docs.dgl.ai/en/latest/api/python/dgl.distributed.html#graph-partition-book) and HALO nodes. When sampling, each server knows whether the target neighbor node exist on current server via GPB. If not, a pull request will be sent to target remote server which holds the expected nodes.

It means that each server will hold the same GPB, in fact, sampling is based on the GPB, because GPB holds the whole graph structure, and then just fetch the features from the partition graph  stores. So the neighbor samping is on GPB because it holds the whole graph structure?

**Comment by Rhett-Ying** [comment]
yes. GPB is instantiated from `graph.json` you passed by `--part_config`. It's lightweight. you could refer to https://github.com/dmlc/dgl/blob/9731e023255559b1c7537aad60b0d534738add85/python/dgl/distributed/graph_services.py#L722 for more details.

**Comment by YijianLiu** [comment]
> yes. GPB is instantiated from `graph.json` you passed by `--part_config`. It's lightweight. you could refer to
> 
> https://github.com/dmlc/dgl/blob/9731e023255559b1c7537aad60b0d534738add85/python/dgl/distributed/graph_services.py#L722
> 
> for more details.

Thanks, from your codes provided, I think it's training with the whole graph but I dont see it checking neighbors of seed nodes whether on the local server. I think it just checks the seed nodes whether on the local server, but not check the neighbors of seed nodes on the local server, can you provide more code details or my understanding is going wrong? Thanks so much
[https://github.com/dmlc/dgl/blob/9731e023255559b1c7537aad60b0d534738add85/python/dgl/distributed/graph_services.py#L80-L88](url)

**Comment by frozenbugs** [comment]
Hi @YijianLiu, I am one of the member of the core DGL team and we would like to learn more about your motivation on leveraging DGL for partitioning giant graph and potentially training models on it, such that we can ingest your feedback to our future roadmap.
Feel free to reach out to my personal email chenhongzhi.nkcs@gmail.com if you prefer off-record discussion.

**Comment by YijianLiu** [comment]
> graph is partitioned according to dst node which means if the seed_node lies in current server, the source node of it is expected to exist on this partition/server.

The method you used METIS will partition nodes onto different machines but why src and dst node will on the same machine?
Have you change the method? I think sometimes srd nodes and dst nodes will on different servers or machines for sampling on more hops.

**Comment by Rhett-Ying** [comment]
The method you used METIS will partition nodes onto different machines but why src and dst node will on the same machine?
>>>Do you mean the `inner_node` flag in the graph partitions. for a specific edge: [src, dst]. It's possible the src's `inner_node` is false while dst's `inner_node` is true.

Have you change the method?
>>> Not really. the core part remains the same.

I think sometimes src nodes and dst nodes will on different servers or machines for sampling on more hops.
>>> Yes. this is why we will send remote sample request in https://github.com/dmlc/dgl/blob/b3aec7aeb136910efcec0650857f5363ce32ccbc/python/dgl/distributed/graph_services.py#L465
