### ISSUE TITLE
Help me represent the graph

### ISSUE THREAD

**Issue by Z-Rajaei** [dmlc/dgl#5033]
Hello,
I have a question.
I have some nodes with some attributes. For Example node a of type A and attributes x,y,z (e.g. x=1, y=5, z=3). Another Node b of Type B and attributes p,k. 
I want to represent this structure as a graph in DGL.
Is it reasonable to consider all the elements as nodes and have an edge between them? For example nodes a, A, x, y, z , b, B, p, k. 
Or considering just a and b as nodes and A, x,y,z, B, p,k as attributes.

We have two cases a graph with a lot of nodes and edges, and a graph with small number of nodes and a lot of attributes.

I want to know which one is reasonable or better in terms of learning performance (learning faster and/or better) & wall clock performance (is the encoding overhead really expensive?)

I am very eager to know everyone opinion sooner.
Thank you.

**Comment by czkkkkkk** [comment]
Hi @Z-Rajaei . In DGL, you can represent your graph using `DGLHeteroGraph` (https://docs.dgl.ai/en/0.9.x/guide/graph-heterogeneous.html#guide-graph-heterogeneous).

**Comment by Z-Rajaei** [comment]
Thanks @czkkkkkk. Yes I know. 
So you recommend to represent graph using the second scenario. Yes?

**Comment by czkkkkkk** [comment]
Yes. The first solution does not make sense to me because different nodes could have different values for the same attribute.

**Comment by Z-Rajaei** [comment]
I have another question.
How can I embed the attribute values like x = "class" or y = "65"? The values are not pre defined and can be any possible string value. Can you give me a reference or site link with this case?

**Comment by czkkkkkk** [comment]
Normally the node or edge data in GNN would not be string. Depending on your application, you may need to convert them to int or float to store in DGL for training.

**Comment by czkkkkkk** [comment]
Hi @Z-Rajaei, I am closing this issue assuming you are happy about our response. Feel free to follow up and reopen the issue if you have more questions with regard to our response.
