### ISSUE TITLE
Support `DGLHeteroGraph` in `RelGraphConv`

### ISSUE THREAD

**Issue by SaizhuoWang** [dmlc/dgl#5035]
## ❓ Questions and Help

Is there any way that `DGLHeteroGraph` can be supported as input to `RelGraphConv`? We are currently using `DGLHeteroGraph` in our own library to implement RGCN but cannot use the official implementation of RGCN in DGL due to this issue. Thanks.

**Comment by yaox12** [comment]
Does https://github.com/dmlc/dgl/tree/master/examples/pytorch/rgcn-hetero work?

**Comment by SaizhuoWang** [comment]
Thanks for your reply. Will try.
