### ISSUE TITLE
[API Deprecation] Deprecate contrib module

### ISSUE THREAD

**Issue by peizhou001** [dmlc/dgl#5040]
Deprecate contrib module

**Comment by yaox12** [comment]
I tested the latest deprecate branch (with `contrib` and `_dataloading` being removed). All the other tests passed except for `examples/pytorch/graphsage/advanced/train_sampling_unsupervised.py`. The following two lines
https://github.com/dmlc/dgl/blob/53c700d64824e144a725c707f5742f6bc2d16bdd/examples/pytorch/graphsage/advanced/train_sampling_unsupervised.py#L136-L137
should be 
```python
if args.data_device == "uva":
    input_nodes = input_nodes.to(device)
    batch_inputs = dgl.utils.gather_pinned_tensor_rows(nfeat, input_nodes)
else:
    ...
```
In fact, I think we should refactor this example to match the latest usage of the dataloader, and move it to `examples/pytorch/multigpu`.
