### ISSUE TITLE
create heterogeneous graph using a json file

### ISSUE THREAD

**Issue by Z-Rajaei** [dmlc/dgl#5049]
Hello,
I have some problems creating a heterogeneous graph in DGL.
Is there any way to provide an input data file contains nodes, edges, node attributes and edge attributes like a json file and then convert it to a heterodgl graph? The node attributes are some attribute–value pairs.

It is appreciated If you can send me some links to help me.
Thanks

**Comment by frozenbugs** [comment]
Hi,

Currently we only support CSV as input for heterogeneous graph natively.
For json format, you can use suggest 3rd party tool as suggested [here](https://docs.dgl.ai/en/latest/guide/graph-external.html#json-gml-format).

**Comment by peizhou001** [comment]
Of course you can. We provide an API pair ```load_graphs/save_graphs``` to help you load/save graphs from/to disk using DGL binary formats. If you have other format, like CSV, JSON, you have 2 ways creating DGLGraph from files:

1. Read files into memory as tensor/ndarray(use tools according to your format, e.g pandas, torch.load) and create files using [dgl.heterograph](https://docs.dgl.ai/en/latest/generated/dgl.heterograph.html)
2. Using 3rd party tools to read it as 3rd graph structure, and then convert it to  ```DGLGraph```. E.g. use [Networkx](https://networkx.org/documentation/stable/reference/readwrite/index.html) to read files as networkx and convert it to DGLGraph using [dgl.from_networkx](https://docs.dgl.ai/en/latest/generated/dgl.from_networkx.html).

**Comment by frozenbugs** [comment]
Hi @Z-Rajaei , I am closing this issue assuming you are happy about our response. Feel free to follow up and reopen the issue if you have more questions with regard to our response.
