### ISSUE TITLE
[Sparse] Batched SpMM and SDDMM

### ISSUE THREAD

**Issue by frozenbugs** [dmlc/dgl#5057]
## 🔨Work Item

**IMPORTANT:**
* This template is only for dev team to track project progress. For feature request or bug report, please use the corresponding issue templates.
* DO NOT create a new work item if the purpose is to fix an existing issue or feature request. We will directly use the issue in the project tracker.

Project tracker: https://github.com/orgs/dmlc/projects/2

**Comment by frozenbugs** [comment]
Implement the mock first https://github.com/dmlc/dgl/issues/5055 to unblock #5056

**Comment by frozenbugs** [comment]
Let's wait for the example get drafted and see how well the API is, before we implement the release version of BSDDMM.

**Comment by jermainewang** [comment]
Extend this task to include bspmm which is needed by the GAT example.
