### ISSUE TITLE
dgl.radius_graph unexpected self loops

### ISSUE THREAD

**Issue by javiermcebrian** [dmlc/dgl#5065]
## 🐛 Bug

dgl.radius_graph sometimes provides self loops when specified self_loop = False in version dgl-cu102==0.9.1 in linux

## To Reproduce

Below a test code for illustration, returning the number of self loops in the created graph.

```
import dgl
import torch
import numpy as np

def test_dgl_radius_graph_self_loops(maximum, minimum, n_nodes, radius):
    src, dst = dgl.radius_graph((maximum - minimum) * torch.rand(size=(n_nodes, 2)), r=radius, p=2, self_loop=False).edges()
    return np.sum([i==j for i, j in zip(src.tolist(), dst.tolist())])

maximum = 3000
minimum = 0
n_nodes = 27

test_dgl_radius_graph_self_loops(maximum=maximum, minimum=minimum, n_nodes=n_nodes, radius=2000)
test_dgl_radius_graph_self_loops(maximum=maximum, minimum=minimum, n_nodes=n_nodes, radius=3000)
```

## Expected behavior

I would expect no self loops in the returned graph

## Environment

 - DGL Version (e.g., 1.0): dgl-cu102==0.9.1
 - Backend Library & Version (e.g., PyTorch 0.4.1, MXNet/Gluon 1.3): torch==1.13.0+cu117
 - OS (e.g., Linux): nvidia/cuda:10.2-cudnn7-devel-ubuntu18.04
 - How you installed DGL (`conda`, `pip`, source): pip
 - Build command you used (if compiling from source): N/A
 - Python version: 3.8
 - CUDA/cuDNN version (if applicable): CUDA 10.2 cuDNN 7
 - GPU models and configuration (e.g. V100): Tesla P100

**Comment by mufeili** [comment]
It seems that I got 0 with `(src == dst).sum()`.

**Comment by dmonterom** [comment]
I get the same error when using radius = 3000. It seems to be a rounding issue inside radius_graph function:
`if not self_loop:
    distances.fill_diagonal_(r + 1e-4)
edges = th.nonzero(distances <= r, as_tuple=True)`

It is weird because using radius = 3000.0001 works well.

**Comment by mufeili** [comment]
Could you take a look? @ksadowski13

**Comment by javiermcebrian** [comment]
@mufeili thanks, I saw PR is merged into master. Do you know in which DGL version will the fix be applied? Thanks!

**Comment by mufeili** [comment]
> @mufeili thanks, I saw PR is merged into master. Do you know in which DGL version will the fix be applied? Thanks!

Typically this should be included in the next release and available soon in the nightly-built version if you use linux. cc @BarclayII
