### ISSUE TITLE
Question about RGCNBasisLayer

### ISSUE THREAD

**Issue by fengxy7** [dmlc/dgl#507]
I'm wondering why self-loop is set to be false for RGCNBasisLayer, which is inherited from RGCNLayer, as the parameter passed in does not include it?
https://github.com/dmlc/dgl/blob/ca48787ae49e9d73ebf17b1c882cb66fb66fb828/examples/pytorch/rgcn/layers.py#L5-L7
https://github.com/dmlc/dgl/blob/ca48787ae49e9d73ebf17b1c882cb66fb66fb828/examples/pytorch/rgcn/layers.py#L52-L55

**Comment by ylfdq1118** [comment]
I can't remember if author's version has the loop message for entity classification task. But you can enable it if you prefer.

And if you are worried about self-relation, the data preprocessing code (see [here](https://github.com/dmlc/dgl/blob/master/python/dgl/contrib/data/knowledge_graph.py#L404)) already adds self loop as self-relation.

**Comment by VoVAllen** [comment]
Closed due to inactive. Please feel free to reopen this if you still have any question.
