### ISSUE TITLE
create heterogeneous graph with csv

### ISSUE THREAD

**Issue by Z-Rajaei** [dmlc/dgl#5078]
Hello,
I have some data and I want to convert them to heterogeneous graph.
Each graph has some nodes and some attributes. All the nodes of all graphs are of different types and so they have different attributes.
There are some edges between nodes, they have also some attributes.

What is the best structure for the input data? How can I organize them in csv files? If I want to have separate files for each type of node and edge the number of files will be increased terribly. 
Is there any related implemented work? 
Do you have any recommendation?

**Comment by mufeili** [comment]
Have you checked [this](https://docs.dgl.ai/guide/data-loadcsv.html#guide-data-pipeline-loadcsv)?

**Comment by Z-Rajaei** [comment]
Thanks @mufeili 
Yes, I checked. But, it proposes to create a file for each node type. I want to have all the node types in one file, or any other optimized solution. Because, I have to create one file for each node in the graphs (As I said all the nodes have different types).
If I have 1000 graph, each containing 50 nodes, the number of node files will become 50000.

Any Idea?

**Comment by Rhett-Ying** [comment]
Hi @Z-Rajaei 
As your case is quite special(each hetero-graph consists of many meta-graphs and each meta-graph probably has single edge as all the node types in graph is different from each other which means all the edges are of different canonical edge types except the non-simple graph. Is this right?), I don't think there exist any efficient way to handle this in current DGL? Probably you could compose the hetero-graph on your own via utilizing `dgl.heterograph()`. In your case, it's probably like `dgl.heterograph({('node_type_0', 'edge_type_0', 'node_type_1'): (torch.LongTensor([0]), torch.LongTensor([0])), ...})`. just list/iterate all the node/edge types.

I am wondering what kind of algo/model you will apply on such a graph. and how about encoding the node attribute into node's feature then the graph will be more common.

**Comment by BarclayII** [comment]
One other question I'd like to ask is: is treating every node as having different types necessary in your use case?  I wonder what your node attributes are.

**Comment by Z-Rajaei** [comment]
I tried to implement my graph in a better way.
Thank you
