### ISSUE TITLE
Data set in the SSE model example

### ISSUE THREAD

**Issue by tengwei12315** [dmlc/dgl#508]
## ❓ Questions and Help

Where is the data set used in the SSE model example downloaded, and how are the characteristics of the data set constructed?The reason for this problem is that I am getting an error when running the example.

**Comment by tengwei12315** [comment]
Traceback (most recent call last):
  File "sse_batch.py", line 398, in <module>
    data = load_data(args)
  File "/usr/local/miniconda3/lib/python3.7/site-packages/dgl/data/__init__.py", line 27, in load_data
    elif args.dataset.startswith('reddit'):
AttributeError: 'NoneType' object has no attribute 'startswith'

**Comment by zheng-da** [comment]
```
python3 examples/mxnet/sse/sse_batch.py --dataset pubmed
```
it works pretty well. how do you run the example?

**Comment by tengwei12315** [comment]
I am running the example on my PC, linux system, Python3.7,mxnet ,request has been installed.I downloaded all the dgl files directly from github.




--------------- 原始邮件 ------------------
发件人: "Da Zheng"<notifications@github.com>;
发送时间: 2019年4月24日(星期三) 下午4:10
收件人: "dmlc/dgl"<dgl@noreply.github.com>;
抄送: "我是大大"<1095975833@qq.com>; "Author"<author@noreply.github.com>; 
主题: Re: [dmlc/dgl] Data set in the SSE model example (#508)



python3 examples/mxnet/sse/sse_batch.py --dataset pubmed  
it works pretty well. how do you run the example?

**Comment by VoVAllen** [comment]
Did you start program with "--dataset pubmed"?

**Comment by tengwei12315** [comment]
I start program with "--dataset pubmed".But the download did not succeed。I am now downloading it to my local, what folder should I put the dataset into?

**Comment by zheng-da** [comment]
The error message is confusing. I have fixed it in this PR. https://github.com/dmlc/dgl/pull/509

**Comment by zheng-da** [comment]
the dataset is placed under ~/.dgl by default. you don't need to worry about where the data is placed.

**Comment by tengwei12315** [comment]
I have put pubmed.zip in the folder, but why is it wrong?

Traceback (most recent call last):
  File "sse_batch.py", line 398, in <module>
    data = load_data(args)
  File "/usr/local/miniconda3/lib/python3.7/site-packages/dgl/data/__init__.py", line 24, in load_data
    return citegrh.load_pubmed()
  File "/usr/local/miniconda3/lib/python3.7/site-packages/dgl/data/citation_graph.py", line 151, in load_pubmed
    data = CitationGraphDataset('pubmed')
  File "/usr/local/miniconda3/lib/python3.7/site-packages/dgl/data/citation_graph.py", line 36, in __init__
    extract_archive(self.zip_file_path, '{}/{}'.format(self.dir, name))
  File "/usr/local/miniconda3/lib/python3.7/site-packages/dgl/data/utils.py", line 146, in extract_archive
    archive = zipfile.ZipFile(file, 'r')
  File "/usr/local/miniconda3/lib/python3.7/zipfile.py", line 1222, in __init__
    self._RealGetContents()
  File "/usr/local/miniconda3/lib/python3.7/zipfile.py", line 1289, in _RealGetContents
    raise BadZipFile("File is not a zip file")
zipfile.BadZipFile: File is not a zip file

**Comment by tengwei12315** [comment]
> ```
> python3 examples/mxnet/sse/sse_batch.py --dataset pubmed
> ```
> it works pretty well. how do you run the example?



> the dataset is placed under ~/.dgl by default. you don't need to worry about where the data is placed.

How is the pubmed data set in the SSE model constructed? What does this data set include?

**Comment by tengwei12315** [comment]
> > ```
> > python3 examples/mxnet/sse/sse_batch.py --dataset pubmed
> > ```
> > it works pretty well. how do you run the example?
> 
> > the dataset is placed under ~/.dgl by default. you don't need to worry about where the data is placed.
> 
> How is the pubmed data set in the SSE model constructed? What does this data set include?



> Did you start program with "--dataset pubmed"?

We now want to use our own dataset in the SSE model. How do we construct our own dataset?Thank you.

**Comment by zheng-da** [comment]
actually, the SSE code shows you an example of loading your own data. Please see the code below.
https://github.com/dmlc/dgl/blob/master/examples/mxnet/sse/sse_batch.py#L394

**Comment by tengwei12315** [comment]
We want to use our own dataset, but in what format should we construct the dataset? Where is the description of the construction data set? thank you!




------------------ 原始邮件 ------------------
发件人: "Da Zheng"<notifications@github.com>;
发送时间: 2019年4月26日(星期五) 上午9:20
收件人: "dmlc/dgl"<dgl@noreply.github.com>;
抄送: "我是大大"<1095975833@qq.com>; "Author"<author@noreply.github.com>; 
主题: Re: [dmlc/dgl] Data set in the SSE model example (#508)




actually, the SSE code shows you an example of loading your own data. Please see the code below.
 https://github.com/dmlc/dgl/blob/master/examples/mxnet/sse/sse_batch.py#L394

**Comment by zheng-da** [comment]
Currently, we don't define format when loading your own data. For example, the code I show you here is to load a MXNet CSR NDArray from a file and create random feature tensors. You can do a similar thing. You can choose save your graph file as a scipy csr, and features as numpy tensors. After you load them, you can construct DGLGraph as usual.

**Comment by tengwei12315** [comment]
We now have only some node datasets for vertices and endpoints. Can we use the SSE model? How should we construct the data set needed by the model?


------------------ 原始邮件 ------------------
发件人: "Da Zheng"<notifications@github.com>;
发送时间: 2019年4月26日(星期五) 上午9:32
收件人: "dmlc/dgl"<dgl@noreply.github.com>;
抄送: "我是大大"<1095975833@qq.com>; "Author"<author@noreply.github.com>; 
主题: Re: [dmlc/dgl] Data set in the SSE model example (#508)




Currently, we don't define format when loading your own data. For example, the code I show you here is to load a MXNet CSR NDArray from a file and create random feature tensors. You can do a similar thing. You can choose save your graph file as a scipy csr, and features as numpy tensors. After you load them, you can construct DGLGraph as usual.

**Comment by tengwei12315** [comment]
> Currently, we don't define format when loading your own data. For example, the code I show you here is to load a MXNet CSR NDArray from a file and create random feature tensors. You can do a similar thing. You can choose save your graph file as a scipy csr, and features as numpy tensors. After you load them, you can construct DGLGraph as usual.

**Comment by zheng-da** [comment]
I don't understand what you mean by "node datasets"? I believe SSE works for any homogeneous graphs.

**Comment by tengwei12315** [comment]
> I don't understand what you mean by "node datasets"? I believe SSE works for any homogeneous graphs.

I mean, we only have side information, the side information is composed of a vertex and an end point. How do you construct the characteristics of the data set used by your SSE model? The final problem is that we have no features, how to construct the data set? Thank you！

**Comment by zheng-da** [comment]
SSE can run on a graph with only the graph structure (just node and edge, no node data or edge data). You can construct the initial node embeddings filled with 0. You don't need to provide node features as the input of the model.

**Comment by tengwei12315** [comment]
> SSE can run on a graph with only the graph structure (just node and edge, no node data or edge data). You can construct the initial node embeddings filled with 0. You don't need to provide node features as the input of the model.

Hi，
Thank you very much for your generous help. Can you send a data set file of your own construction as a reference? Just like the data set you said.
thanks in advance.

**Comment by tengwei12315** [comment]
> SSE can run on a graph with only the graph structure (just node and edge, no node data or edge data). You can construct the initial node embeddings filled with 0. You don't need to provide node features as the input of the model.

In other words, where is the  --graph-file ../../data/5_5_csr.nd \   What is he like?

**Comment by zheng-da** [comment]
sorry for the late reply. You can download the file from S3.
```
aws s3 cp s3://haibin-dgl/5_5_csr.nd .
```

**Comment by tengwei12315** [comment]
> sorry for the late reply. You can download the file from S3.
> 
> ```
> aws s3 cp s3://haibin-dgl/5_5_csr.nd .
> ```

Thank you very much for your answer. I am really grateful for answering so many questions. We currently think that the SSE model is an unsupervised classification. If I want to make a semi-supervised classification, should I set the train_mask like the mask in the GCN tutorial ？Do you have any good suggestions?

**Comment by zheng-da** [comment]
our implementation has the semi-supervised setting. we use some nodes with labels to train the model and infer on the nodes without labels.

**Comment by tengwei12315** [comment]
Hi，
Download the 5_5_csr.nd need Ak, SK, and now SSE model running pumbbed data set can only maintain the accuracy of the test set around 0.4?

**Comment by tengwei12315** [comment]
I use cora, pumbed and my own dataset to run the sse model. I found that the accuracy is not very high. Is this a parameter setting problem? Do you have any good suggestions?
