### ISSUE TITLE
recent dgl-cuXXX versions listed on official documentation aren't on pypi?

### ISSUE THREAD

**Issue by rgasper** [dmlc/dgl#5083]
## ❓ Questions and Help

For Example, looking up recommended dgl distro for my setup https://www.dgl.ai/pages/start.html:
![Screen Shot 2022-12-28 at 9 08 46 AM](https://user-images.githubusercontent.com/14928724/209824580-9e2c53b6-1414-4bd3-8cd4-1919a716ea2b.png)

Recommended version `dgl-cu113` doesn't exist on pypi:
https://pypi.org/search/?q=dgl-cu113&o=
![Screen Shot 2022-12-28 at 9 10 02 AM](https://user-images.githubusercontent.com/14928724/209824726-35a37788-75e8-453a-abf9-4057100dc3d4.png)

Pip installing it doesn't work (some details redacted from the log):
```
pip install dgl-cu113                                                               
#0 0.997 ERROR: Could not find a version that satisfies the requirement dgl-cu113
#0 0.997 ERROR: No matching distribution found for dgl-cu113
```

**Comment by mufeili** [comment]
Currently these distributions are too large for pypi.

**Comment by rudongyu** [comment]
Hi @rgasper , I am closing this issue assuming you are happy about our response. Feel free to follow up and reopen the issue if you have more questions with regard to our response.

**Comment by rgasper** [comment]
Didn't know there was a size limit, that's pretty frustrating. Okay thanks
