### ISSUE TITLE
[PyTorch Deprecation] `Tensor.storage()` has been deprecated

### ISSUE THREAD

**Issue by yaox12** [dmlc/dgl#5104]
## Description

`Tensor.storage()` has been [deprecated](https://github.com/pytorch/pytorch/pull/85303) in PyTorch master and this change would be shipped with PyT 2.0. We may need to update the code calling `Tensor.storage()` in DGL, because it will raise a warning and finally cause an error.

Note that `Tensor._storage()` has been renamed to `Tensor.untyped_storage()` in https://github.com/pytorch/pytorch/pull/91414, which makes it difficult to use a consistent API among PyTorch versions DGL's supporting.

## To Do
- [x] `zerocopy_to_dgl_ndarray_for_write` fixed by #5656.
- [ ] `InvertibleCheckpoint`

**Comment by jermainewang** [comment]
@peizhou001 Could you take a look? We should first locate where in DGL are we using `Tensor.storage()`.

**Comment by yaox12** [comment]
DGL is using `Tensor.storage()` in two places:
1. in `zerocopy_to_dgl_ndarray_for_write`, which is easy to fix https://github.com/dmlc/dgl/blob/9cb669391f784a54d9215c3a2c5b9ce095f03a15/python/dgl/backend/pytorch/tensor.py#L449
2. in `InvertibleCheckpoint`, which I'm not familiar with. Can you take a look to see if there's a workaround? @mufeili https://github.com/dmlc/dgl/blob/9cb669391f784a54d9215c3a2c5b9ce095f03a15/python/dgl/nn/pytorch/conv/grouprevres.py#L35

**Comment by Rhett-Ying** [comment]
close as fixed
