### ISSUE TITLE
[Questions] Is it possible to process the graphs in a DGL batch separately and concurrently?

### ISSUE THREAD

**Issue by venzino-han** [dmlc/dgl#5126]
## ❓ Questions and Help

I'm try to process by graph unit. 

Is there any method for map function for unbatched subgraphs? 

here is example, 
```
#example
# batch have 3 graph g1, g2, g3 
graph_batch = dgl.batch([g1, g2, g3])
#apply funtion 
batch = map_funtion_batch(graph_batch, udf_func)

#this is what I'm trying
gs = dgl.unbatch(graph_batch)

for g in gs:
  g = udf_func(g)  

```

**Comment by Rhett-Ying** [comment]
`dgl.batch` does aim to handle each graph individually and more efficiently(in parallel). Utility functions like `dgl.readout_nodes()` provides some operations. So what kind of operations do you want to apply on each graph? or you just want to apply any kind of user-defined functions on each graph in a batch?

**Comment by Rhett-Ying** [comment]
Any function applied on batched graphs should be supported by underlying operators. so it's unlikely to apply any kind of user defined functions.

**Comment by venzino-han** [comment]
@Rhett-Ying Thanks for your kind comment. I tried to apply function to calculate attention between target node and other nodes. However, I solved this problem by adding addtional edges between target node and other nodes, and masked them on other layers. 
Thank you!
