### ISSUE TITLE
[Example] RGCN-hetero example for link prediction

### ISSUE THREAD

**Issue by Rhett-Ying** [dmlc/dgl#5156]
## 🔨Work Item

**IMPORTANT:**
* This template is only for dev team to track project progress. For feature request or bug report, please use the corresponding issue templates.
* DO NOT create a new work item if the purpose is to fix an existing issue or feature request. We will directly use the issue in the project tracker.

Project tracker: https://github.com/orgs/dmlc/projects/2

## Description
For now, DGL does not include such an example. let's add one for users' reference.

**Comment by frozenbugs** [comment]
Let's add any core example while we launch new data loader.

**Comment by frozenbugs** [comment]
Duplicated with https://github.com/dmlc/dgl/issues/6241
