### ISSUE TITLE
RuntimeError: Boolean value of Tensor with more than one value is ambiguous.

### ISSUE THREAD

**Issue by liuli1221** [dmlc/dgl#5194]
When i use the 'inference' to get the val_acc, the line
'**for input_nodes, output_nodes, blocks in tqdm.tqdm(dataloader):**' raise the error:
 **RuntimeError: Boolean value of Tensor with more than one value is ambiguous**.
What is the problem?
Thank you very much.

**Comment by jermainewang** [comment]
Could you provide more details such as reproducible code?

**Comment by BarclayII** [comment]
Since this is not active, we will close the issue for now.  Please feel free to reopen the issue after providing the details requested (reproducible code, example code URL, etc.).  Thanks!
