### ISSUE TITLE
Python 2 Support?

### ISSUE THREAD

**Issue by mingloo** [dmlc/dgl#520]
I've found the [README](https://github.com/dmlc/dgl/blob/master/README.md) says the `Python 2 support is coming`. 

When will such support available for [DGL](https://github.com/dmlc/dgl)?

**Comment by jermainewang** [comment]
Hi @mingloo, py2 support is on our list but not at the top. As new features are still being added and developed, we're afraid that supporting py2 may put extra burden on the project maintenance. Thus, in the next few releases, we'll still stick with py3. Thanks for your comprehension.

**Comment by mingloo** [comment]
@jermainewang Understand. Thanks for your reply. 👍
