### ISSUE TITLE
Is CUDA 11.7 supported?

### ISSUE THREAD

**Issue by TernaryM01** [dmlc/dgl#5231]
I have installed PyTorch with CUDA 11.7 into a Conda environment:
`conda install pytorch torchvision torchaudio pytorch-cuda=11.7 -c pytorch -c nvidia`

Now, how am I supposed to install DGL? The DGL webpage offers some versions, such as "dgl-cuda11.6", which works with CUDA 11.6. But there is no version with CUDA 11.7.
Does it mean I have to start over from scratch in a new environment, and install "pytorch-cuda=11.6" along with "dgl-cuda11.6"?

**Comment by yaox12** [comment]
`dgl-cuda11.7` does exist but was not listed on the webpage.

**Comment by TernaryM01** [comment]
Oh... Got it.
I've successfully installed it. Thanks!
