### ISSUE TITLE
[Dist][lint] lint check is failing in Distributed Partition Pipeline code

### ISSUE THREAD

**Issue by Rhett-Ying** [dmlc/dgl#5234]
## 🔨Work Item

**IMPORTANT:**
* This template is only for dev team to track project progress. For feature request or bug report, please use the corresponding issue templates.
* DO NOT create a new work item if the purpose is to fix an existing issue or feature request. We will directly use the issue in the project tracker.

Project tracker: https://github.com/orgs/dmlc/projects/2

## Description
As lint check has already been enabled for each PR, we need to format the code in dist partition pipleline to follow DGL's format policy.

**Comment by Rhett-Ying** [comment]
here's the tool we're using for lint check
https://github.com/dmlc/dgl/blob/829ce109f1604ee59ac039331a3609896301e8de/.github/workflows/lint.yml#L32-L40

**Comment by Rhett-Ying** [comment]
pls refer to this doc about formatting: https://docs.google.com/document/d/1iHyj7zlmygKSk5gBPsqIqL5ASPzJSPREaNT_QdsiYA4/edit?usp=sharing

**Comment by frozenbugs** [comment]
The lint test can pass now.
