### ISSUE TITLE
Graph level features in dgl.DGLGraph()

### ISSUE THREAD

**Issue by Junyoungpark** [dmlc/dgl#527]
Hi! I'm a newbie of DGL. I'm wondering whether I can specify graph-level features in `dgl.DGLGraph()`. networkx `graph` supports `graph.graph` for assigning graph-level feature. Can I find an equivalent feature from `DGLGraph()` too?

```
import networkx as nx
import dgl

nx_g = nx.Graph()
nx_g.graph = [1,2,3]

dgl_d = dgl.DGLGraph()
dgl_d.graph = [1,2,3] # This is what I want to do.
```

**Comment by yzh119** [comment]
Hi, the best way is to maintain a graph level feature outside DGLGraph, you can read [this issue](https://github.com/dmlc/dgl/issues/417) for more details.

**Comment by Junyoungpark** [comment]
Thanks for the comments :)
