### ISSUE TITLE
Add `state_dict`, `load_state_dict`, `param_groups` to `dgl.optim.SparseGradOptimizer`

### ISSUE THREAD

**Issue by yaox12** [dmlc/dgl#5270]
## 🔨Work Item

- [ ] Add `state_dict`
- [ ] Add `load_state_dict`
- [ ] Add `param_groups`

## Description

`dgl.optim.SparseGradOptimizer` is very useful for training large-scale model-parallel node embeddings. However, it didn't follow PyTorch's optimizer APIs, and thus requires extra effort for debugging and checkpointing.

With this work item, we hope `dgl.optim.SparseGradOptimizer` to emulate PyTorch optimizers' behaviors.

## Depending work items or issues

This may depend on https://github.com/dmlc/dgl/pull/4989 to use PyTorch's NCCL communicator.

**Comment by yaox12** [comment]
Currently, optimizer states are attached to `dgl.nn.NodeEmbedding` instead of the optimizer. I won't change this for backward compatibility. I may add methods like `all_get_optim_state` and `all_set_optim_state` to handle the multi-GPU case.

**Comment by nv-dlasalle** [comment]
To enable backwards compatibility while ensuring moving forward we have the states attached to the correct object, could we have the sparse embedding save a reference to the optimizer, and just re-route the existing calls? e.g. Modify `optm_state` in `dgl.nn.NodeEmbeding` to call the associated optimizer?
```
def optm_state(self):
  return self._optm.all_get_optim_state()
```
