### ISSUE TITLE
metapath2vec fails with more than 2 metapaths

### ISSUE THREAD

**Issue by davidfstein** [dmlc/dgl#5273]
## 🐛 Bug

metapath2vec fails with more than 2 metapaths.

## To Reproduce

import torch
import dgl
from torch.optim import SparseAdam
from torch.utils.data import DataLoader
from dgl.nn.pytorch import MetaPath2Vec

g = dgl.heterograph({
    ('user', 'uc', 'company'): dgl.rand_graph(100, 1000).edges(),
    ('company', 'cp', 'product'): dgl.rand_graph(100, 1000).edges(),
    ('company', 'cu', 'user'): dgl.rand_graph(100, 1000).edges(),
    ('product', 'pc', 'company'): dgl.rand_graph(100, 1000).edges()
})
model = MetaPath2Vec(g, ['uc', 'cu', 'cp', 'pc'], window_size=1)

"File "dgl/_ffi/_cython/./function.pxi", line 241, in dgl._ffi._cy3.core.FuncCall
dgl._ffi.base.DGLError: [17:48:48] /opt/dgl/src/graph/sampling/randomwalks/get_node_types_cpu.cc:42: source of edge type 2 does not match destination of edge type 1"

## Environment

 - DGL Version (e.g., 1.0): 1.0.0
 - Backend Library & Version (e.g., PyTorch 0.4.1, MXNet/Gluon 1.3): pytorch 1.12.1
 - OS (e.g., Linux): ubuntu
 - How you installed DGL (`conda`, `pip`, source): conda
 - Build command you used (if compiling from source):
 - Python version: 3.9.15
 - CUDA/cuDNN version (if applicable):
 - GPU models and configuration (e.g. V100):
 - Any other relevant information:

**Comment by BarclayII** [comment]
The second edge type `cu` ends with `user` but the third edge type `cp` starts with `company`, so the metapath does not connect.  You will need a metapath that connects (e.g. something like `['uc', 'cp', 'pc', 'cu']`).

**Comment by davidfstein** [comment]
Ah I see, thank you! I didn't realize that the edge types together represent the metapath, now its working
