### ISSUE TITLE
Leverage conda to install instead of pip install dependency in test script.

### ISSUE THREAD

**Issue by frozenbugs** [dmlc/dgl#5274]
## 🔨Work Item

**IMPORTANT:**
* This template is only for dev team to track project progress. For feature request or bug report, please use the corresponding issue templates.
* DO NOT create a new work item if the purpose is to fix an existing issue or feature request. We will directly use the issue in the project tracker.

Project tracker: https://github.com/orgs/dmlc/projects/2

## Description

Leverage conda to install instead of pip install dependency in test scripts:
https://github.com/dmlc/dgl/blob/f0b7cc96bd679eba40632a0383535e7a9d3295c5/tests/scripts/task_unit_test.sh#L36
https://github.com/dmlc/dgl/blob/f0b7cc96bd679eba40632a0383535e7a9d3295c5/tests/scripts/task_unit_test.bat#L17
tests/scripts/task_distributed_test.sh

Also double check if we install dependencies in docker image, if so, consider move them to conda dependency as well.
https://github.com/dmlc/dgl/blob/master/docker/

**Comment by Rhett-Ying** [comment]
`conda` is not used in Windows tests, I'd like to leave it. we may need to enable conda first in another work item.

**Comment by Rhett-Ying** [comment]
`cugraph` test does not use `conda` for now, so let's skip it too.
