### ISSUE TITLE
Not intuitive implementations for GAT from the tutorial. Why get g when instantiate GAT layer?

### ISSUE THREAD

**Issue by Junyoungpark** [dmlc/dgl#528]
Hi! I may have a misunderstanding about GAT implementation. When I go over the GAT tutorial in https://docs.dgl.ai/tutorials/models/1_gnn/9_gat.html. 

``` python
class GATLayer(nn.Module):
    def __init__(self, g, in_dim, out_dim):
        super(GATLayer, self).__init__()
        self.g = g
        # equation (1)
        self.fc = nn.Linear(in_dim, out_dim, bias=False)
        # equation (2)
        self.attn_fc = nn.Linear(2 * out_dim, 1, bias=False)
```
when I followe the implemenation, the `GATLayer` get a fixed `g` as `self.g`. This is quite counter intuitve for me. Since `GATLayer()` itself is indeed capable to handle any toplogy of graphs, setting a fixed graph is not attractive in real applications. Is there any specific reason to get `g` when firstly initialize the `GATLayer()`? Maybe computationally efficient?

Also, I found a different version of the implementation of GAT from github page https://github.com/dmlc/dgl. Here, `GATLayer()` do not take `g` as a parameter.

``` python
class GATLayer(nn.Module):
    def __init__(self, in_feats, out_feats):
        super(GATLayer, self).__init__()
        self.Q = nn.Linear(in_feats, out_feats)
        self.K = nn.Linear(in_feats, out_feats)
        self.V = nn.Linear(in_feats, out_feats)
```

**Comment by mufeili** [comment]
Hi Junyoung, 

You can simply treat `g` as another argument in the `forward` function. Setting `g` in initialization is easy when we have one fixed graph only like in the case of Cora, Citeseer and Pubmed.

**Comment by Junyoungpark** [comment]
@mufeili. Thanks for the reply! I was just curious :)
