### ISSUE TITLE
Wrong Shaped Data

### ISSUE THREAD

**Issue by Root-DE** [dmlc/dgl#5283]
## 📚 Documentation

There is an error in one Tutorial

In the file https://github.com/dmlc/dgl/blob/0.8.x/docs/source/guide/minibatch-edge.rst the apply_edges method the variable data has the wrong shape, it should be:
data = torch.cat([edges.src['x'], edges.dst['x']], 1)

(At least for the homogeneous graph)

**Comment by czkkkkkk** [comment]
Many thanks for your suggestion. We will fix it ASAP.
