### ISSUE TITLE
Hits@1, Hits@3, Hits@10 for RGCN link prediction

### ISSUE THREAD

**Issue by eric2213** [dmlc/dgl#5286]
## ❓ Questions and Help
Hello, I'm working on R-GCN, trying to modify dgl/examples/pytorch/rgcn/link.py.
Is there a function or code to calculate HITS@1, HITS@3, HITS@10?

Thanks for replying.

**Comment by Rhett-Ying** [comment]
Hi @eric2213, I am closing this issue assuming you are happy about our response. Feel free to follow up and reopen the issue if you have more questions with regard to our response.
