### ISSUE TITLE
Getting SGC to work with reddit data

### ISSUE THREAD

**Issue by Tiiiger** [dmlc/dgl#529]
Been trying to get SGC to work on the Reddit dataset. However, it seems that the current release version (v0.2) takes too much memory. 

Here is a minimal snippet to replicate the issue:
```python
import argparse
import torch
import dgl.function as fn
from dgl import DGLGraph
from dgl.data import register_data_args, load_data

parser = argparse.ArgumentParser(description='SGC')
register_data_args(parser)
args = parser.parse_args()
args.dataset = "reddit-self-loop"
data = load_data(args)
features = torch.FloatTensor(data.features)
labels = torch.LongTensor(data.labels)
train_mask = torch.ByteTensor(data.train_mask)
val_mask = torch.ByteTensor(data.val_mask)
test_mask = torch.ByteTensor(data.test_mask)
in_feats = features.shape[1]
n_classes = data.num_labels
n_edges = data.graph.number_of_edges()

torch.cuda.set_device(0)
features = features.cuda()
labels = labels.cuda()
train_mask = train_mask.cuda()
val_mask = val_mask.cuda()
test_mask = test_mask.cuda()

g = DGLGraph(data.graph)
n_edges = g.number_of_edges()
# normalization
degs = g.in_degrees().float()
norm = torch.pow(degs, -0.5)
norm[torch.isinf(norm)] = 0
norm = norm.cuda()
g.ndata['norm'] = norm.unsqueeze(1)
h = features * g.ndata['norm']
g.ndata['h'] = h
g.update_all(fn.copy_src(src='h', out='m'),
             fn.sum(msg='m', out='h'))
```

It tries to allocate 257 GB GPU memory. For a reference, I am able to train SGC on the Reddit dataset with a [vanilla PyTorch implementation](https://github.com/Tiiiger/SGC/blob/master/reddit.py). I am aware that v0.3 is on its way and this issue might be solved trivially with kernel fusion. Can you point me to the nightly branch? simply want to get this example done sooner than later. 

Thanks in advance!

**Comment by jermainewang** [comment]
Hi @Tiiiger, sorry for the delayed reply. We don't have nightly branch at the moment. Currently, we put kernel-related codes on `kernel` branch. You could try build from source and see whether that fixes your issue. We are working on the release. Thank you for your patience.

**Comment by yzh119** [comment]
I'll look into this, thanks for your patience.

**Comment by Tiiiger** [comment]
@yzh119 any updates?

**Comment by yzh119** [comment]
Hi @Tiiiger , I have run your snippet and it works fine with the master branch of DGL.
We have merged kernel branch to master, you could built the master branch by running the folloing:
```
cp cmake/config.cmake . # and set USE_CUDA to ON
mkdir build && cd build
cmake .. && make -j8
cd ../python
python setup.py install
```
The compilation may take a while.

**Comment by Tiiiger** [comment]
```
#include <dlpack/dlpack.h>
```
I need to install `dlpack`. How do I do that?

**Comment by jermainewang** [comment]
git submodule update --init --recursive

**Comment by Tiiiger** [comment]
Thank you for your help. I have created a PR (#658). Please help review.
