### ISSUE TITLE
Edit on Github link invalid

### ISSUE THREAD

**Issue by abhi-11nav** [dmlc/dgl#5292]
## 📚 Documentation

I am unable to end up on the GitHub page of tutorial when I click on "edit on GitHub". It's leading to invalid URL and restricting me from submitting pull requests.

**Comment by abhi-11nav** [comment]
@zheng-da Could you please look into this. thanks :-)

**Comment by abhi-11nav** [comment]
@zheng-da could you please look into this. Thanks :-)

**Comment by czkkkkkk** [comment]
Hi @abhi-11nav , could you give a link about the tutorials that don't work? Thanks!

**Comment by abhi-11nav** [comment]
Here are a couple , 
Node classification documentation : https://docs.dgl.ai/tutorials/blitz/1_introduction.html
Graph Attention Networks: https://docs.dgl.ai/en/0.8.x/tutorials/models/1_gnn/9_gat.html
Thank you.

**Comment by czkkkkkk** [comment]
Hi @abhi-11nav , these documents are auto-generated during the building process. So they do not have corresponding files on github. We think it is not necessary for users to access their source files and will disable their edit-on-github button in the future.
