### ISSUE TITLE
Fix print statements in distDGL

### ISSUE THREAD

**Issue by isratnisa** [dmlc/dgl#5295]
### Misleading print statements
1. When training on large graphs, distDGL takes a while  to load the dataset and convert it to different storage formats (up to 1.5 hours in my experience). It does not show any log in the mean time which makes the user think that either the code got stuck or there is some issue with socket connection. 

For example, RGCN on papers100M dataset waits after this step for a long time:

```
[21:50:21] /opt/dgl/src/rpc/rpc.cc:159: Receiver with NetType~socket is created.
[21:50:21] /opt/dgl/src/rpc/rpc.cc:159: Receiver with NetType~socket is created.
```
 
We can add more statements such as:
```
Loading dataset...
Converting graph format...
Storing graph or embedding tables...
```
etc.

### Too many optional messages

Also, the current code prints too many optional messages like padding info (`Pad nids from 69525 to 69524`), partition info (`part 0, train: 69525, val: 8685, test: 5506`), etc. Most of the messages should be printed only if a user turns on the verbose mode.

@Rhett-Ying

**Comment by Rhett-Ying** [comment]
confirmed. thanks for reporting this...

**Comment by isratnisa** [comment]
Also, I think the current code prints too many optional messages like padding info (`Pad nids from 69525 to 69524`), partition info (`part 0, train: 69525, val: 8685, test: 5506`), etc. Most of the messages should be printed only if a user turns on the verbose mode.

**Comment by Rhett-Ying** [comment]
@isratnisa  could you help fix it? just print what you think that are essential messages.

**Comment by Rhett-Ying** [comment]
> 

These log are printed by the example script? `//examples/pytorch/grpahsage/dist/trian_dist.py`? Actually there's no `verbose` option in DistDGL for now.
