### ISSUE TITLE
DistDGL code does not have clean exit when submit as batch job

### ISSUE THREAD

**Issue by isratnisa** [dmlc/dgl#5300]
## To Reproduce

When distDGL training scripts are submitted as a job scripts at a local clusters often users have the issues where the processes do not exit after training. The script just hangs. Our team members also faced similar issue on ASW batch.

This behavior can be caused by any distributed training script. Following is an example to run ogbn-papers100M code on 4 partitions.

```python3 /dgl/tools/launch.py --workspace /dgl/examples/pytorch/rgcn/experimental/ --num_trainers 4 --num_servers 4 --num_samplers 4 --part_config /data/ogbn-papers100M-4p/ogbn-papers100M.json --ip_config /data/ip_list_p4.txt --ssh_port 2222 "python3 entity_classify_dist.py --graph-name ogbn-papers100M --dataset ogbn-papers100M --fanout='5,10,15' --batch-size 128  --n-hidden 128 --lr 0.001 --eval-batch-size 128 --dropout 0.0 --use-self-loop --n-layers 3 --n-bases 2 --n-epochs 1 --layer-norm --ip-config /data/ip_list_p4.txt --sparse-lr 0.06 --num_gpus 4"```

### Error messages
```
Client[1] in group[0] is exiting...
Client[19] in group[0] is exiting...
Client[15] in group[0] is exiting...
Client[0] in group[0] is exiting...
/usr/local/lib/python3.8/dist-packages/dgl/distributed/graph_partition_book.py:812: DGLWarning: Etype with 'str' format is deprecated. Please use '(str, str, str)'.
  dgl_warning(
Namespace(local_rank=-1, yaml_config_file='/home/ncastet/scratch/graphstorm/tests/regression-tests/nc/mag_nc.yaml')
{'version': 1.0, 'gsf': {'basic': {'model_encoder_type': 'rgcn', 'graph_name': 'ogbn-mag', 'backend': 'gloo', 'num_gpus': 4, 'ip_config': '/home/ncastet/scratch/graphstorm/ip_list_p1.txt', 'part_config': '/home/ncastet/scratch/graphstorm/ogbn-mag_1p/ogbn-mag.json', 'verbose': False, 'gnn_warmup_epochs': 0, 'mixed_precision': False, 'no_validation': False, 'mp_opt_level': 'O2', 'train_nodes': 0, 'debug': False}, 'gnn': {'fanout': '20,10', 'n_layers': 2, 'n_hidden': 256, 'mini_batch_infer': False}, 'input': {'restore_model_path': None}, 'output': {'save_model_path': None, 'save_embed_path': None}, 'hyperparam': {'dropout': 0.5, 'lr': 0.0005, 'bert_tune_lr': 0.0001, 'n_epochs': 1, 'batch_size': 1600, 'eval_batch_size': 1024, 'bert_infer_bs': 64, 'wd_l2norm': 0}, 'rgcn': {'n_bases': -1, 'use_self_loop': True, 'use_dot_product': True, 'self_loop_init': False, 'sparse_lr': '1e-2', 'use_node_embeddings': False}, 'node_classification': {'predict_ntype': 'paper', 'label_field': 'labels', 'multilabel': False, 'num_classes': 349}}}
load ogbn-mag
start graph service on server 0 for part 0
Server is waiting for connections on [127.0.0.1:30050]...
```

## Environment

 - DGL Version (e.g., 1.0): 0.10
 - Backend Library & Version (e.g., PyTorch 0.4.1, MXNet/Gluon 1.3): PyTorch
 - OS (e.g., Linux): Ubuntu
 - How you installed DGL (`conda`, `pip`, source): pip
 - Build command you used (if compiling from source):
 - Python version:
 - CUDA/cuDNN version (if applicable):
 - GPU models and configuration (e.g. V100): T4
 - Any other relevant information:

## Additional context

@Rhett-Ying Do you have any insight on this?

**Comment by Rhett-Ying** [comment]
Does this always happen? Always cannot exit as expected on AWS batch? I have set-up a Multi-Node Parallel job on batch too, and it works well(4 nodes, node classification on `ogbn-products`).  Are you submitting the train as multi-node parallel job too?

**Comment by isratnisa** [comment]
No, not always. But I have complains from NVIDIA and @ivasilei. I also faced similar issue.

**Comment by Rhett-Ying** [comment]
cannot be reproduced. As discussed offline, let's close this issue now. If we hit this issue again, let's file a new one.
