### ISSUE TITLE
Issues in NodeFlow when Extending GAT to Reddit

### ISSUE THREAD

**Issue by mufeili** [dmlc/dgl#531]
## 🐛 Bug

Just attempted extending GAT to Reddit with NodeFlow and encountered several issues. 

### To Reproduce

```python
nf.apply_block(self.index, func=self.edge_attention)
```

where 

```python
def edge_attention(self, edges):
    # an edge UDF to compute unnormalized attention values from src and dst
    a = self.leaky_relu(edges.src[self.src_atten_attr] + edges.dst[self.dst_atten_attr])
    return {self.atten_attr : a}
```

### Expected behavior

```
The size of tensor a (N1) must match the size of tensor b (N2) at non-singleton dimension 0
```

where

N1, N2 are two integers that are unequal. I've attempted all the three options at [apply_block](https://github.com/dmlc/dgl/blob/master/python/dgl/nodeflow.py#L718), but only managed to get it to work when `edges=nf.block_eid(self.index)`.

A related issue is #515 where the author has filed a PR.

### To Reproduce

```
nf.block_compute(self.index, fn.src_mul_edge('ft', 'a_drop', 'ft'), fn.sum('ft', 'ft'))
```

### Expected behavior

```
  File "/Users/MufeiLi/Desktop/research/projects/DGL-Consolidate/model/gat_nodeflow.py", line 74, in forward
    nf.block_compute(self.index, fn.src_mul_edge('ft', 'a_drop', 'ft'), fn.sum('ft', 'ft'))
  File "/Users/MufeiLi/Desktop/research/projects/dgl/python/dgl/nodeflow.py", line 818, in block_compute
    apply_func=apply_node_func)
  File "/Users/MufeiLi/Desktop/research/projects/dgl/python/dgl/runtime/scheduler.py", line 539, in schedule_nodeflow_update_all
    uv_getter, adj_creator, inc_creator)
  File "/Users/MufeiLi/Desktop/research/projects/dgl/python/dgl/runtime/scheduler.py", line 787, in _gen_send_reduce
    spmv_pairs, mfunc, rfunc = spmv.analyze_v2v_spmv(graph, mfunc, rfunc)
  File "/Users/MufeiLi/Desktop/research/projects/dgl/python/dgl/runtime/spmv.py", line 47, in analyze_v2v_spmv
    if mfn.is_spmv_supported(graph) and rfn.is_spmv_supported():
  File "/Users/MufeiLi/Desktop/research/projects/dgl/python/dgl/function/message.py", line 73, in is_spmv_supported
    return _is_spmv_supported_edge_feat(g, self.edge_field)
  File "/Users/MufeiLi/Desktop/research/projects/dgl/python/dgl/function/message.py", line 42, in _is_spmv_supported_edge_feat
    feat = g.get_e_repr()[field]
AttributeError: 'NodeFlow' object has no attribute 'get_e_repr'
```

This seems to be simply an issue that some built-in functions are not compatible with nodeflow now.

## Environment

 - DGL Version (e.g., 1.0): Built from source up to `acefb9a`
 - Backend Library & Version (e.g., PyTorch 0.4.1, MXNet/Gluon 1.3): PyTorch `1.0.1.post2`
 - OS (e.g., Linux): `Ubuntu 16.04.6/macOS Mojave 10.14.4`
 - How you installed DGL (`conda`, `pip`, source): source
 - Build command you used (if compiling from source): `python setup.py install`
 - Python version: 3.6

**Comment by zheng-da** [comment]
Does https://github.com/dmlc/dgl/pull/515 fix your problem?

**Comment by mufeili** [comment]
@zheng-da With an initial attempt, the first issue seem to be resolved and I will take a more careful look to see if the accuracy does not change. The second issue still exists.

**Comment by zheng-da** [comment]
I see. I just noticed the first issue.

**Comment by zheng-da** [comment]
this has been tested in https://github.com/dmlc/dgl/pull/628/files
the second issue has been fixed.
