### ISSUE TITLE
How to resolve copy.src error?

### ISSUE THREAD

**Issue by qubit0** [dmlc/dgl#5316]
I have a model written in dgl version 0.5.1. However, I have dgl 1.0.0. I am getting the following error:

`AttributeError: module 'dgl.function' has no attribute 'copy_src'`

How can I fix the error?

**Comment by qubit0** [comment]
Found the fix. In the new version it's called `copy_u` . I don't why this was done.

**Comment by whr819987540** [comment]
Really helps.
