### ISSUE TITLE
Cannot load large graph from sparse_matrix

### ISSUE THREAD

**Issue by zegzag** [dmlc/dgl#537]
## 🐛 Bug
I downloaded the `Reddit Graph Data` and unzip them into the directory `./data`, which is `./data/reddit_data.npz` and `./data/reddit_self_loop_graph.npz`. I loaded the graph data with `scipy.sparse.load_npz()` to `coo_adj`.  I tried to build the `DGLGraph` from the sparse adjacent matrix  with `g=DGLGraph().from_scipy_sparse_matrix(coo_adj)` but I got the `NoneType` return. I wonder if it is because the graph is too large.
## To Reproduce
here is the code:
![Screenshot_20190516_121057](https://user-images.githubusercontent.com/16755162/57825985-d103c200-77d3-11e9-8f90-f36cca1fd3d8.png)
![Screenshot_20190516_120806](https://user-images.githubusercontent.com/16755162/57826180-ba119f80-77d4-11e9-9b4f-18de758f6e99.png)

I would be quite grateful for some feedback and bug informations. Thx : )

**Comment by VoVAllen** [comment]
I think `from_scipy_sparse_matrix` is an inplace operation. Could you try `g=DGLGraph(); g.from_scipy_sparse_matrix(coo_adj)` and see whether `g` is loaded as expected?

**Comment by VoVAllen** [comment]
Please feel free to reopen this if you still have any question.
