### ISSUE TITLE
If DGL can support Numpy ecology ?

### ISSUE THREAD

**Issue by zegzag** [dmlc/dgl#538]
## Feature
We know that in data science field, python ecology of `Numpy, Scipy,  Scikit-Learn` is a rounded system. Much data in the rounded system is stored in numpy format or can be operated by `Numpy` easily. `Pytorch` paradigm is similar to `Numpy`, the people who are familiar to `Numpy` can transform easily to `Pytorch`. And `DGL` is derived from `Pytorch`. For the above reason, I wonder if `DGL` can support the `Numpy` ecology.
## Motivation
For example, I got the graph adjacent matrix stored in the `scipy.sparse.coo.coo_matrix`, say `coo_adj`. Many attributes I got from it are numpy format,such as `coo_adj.data, coo_adj.row, coo_adj.col` which is `numpy.narray` and etc. If I want use this to configure my  `DGLGraph`, I have to transform them to `torch.Tensor or python.list`. 
In the most common case, if I want draw some point values, say maxvalue by `max(coo_adj.col)`. Many of these values are in `numpy` format, such as `numpy.int, numpy.float` etc. And if I use these point values to configure my graph, it will call errors.
Example shown as below:
![Screenshot_20190516_134830](https://user-images.githubusercontent.com/16755162/57829468-a3257a00-77e1-11e9-80cb-6ee649f822f1.png)
![Screenshot_20190516_134912](https://user-images.githubusercontent.com/16755162/57829470-a6206a80-77e1-11e9-8880-beafe17f853f.png)

## Pitch
`DGL` is a quite outperforming and convenient library for Graph Learning. And I think if features and functions in `DGL` support `Numpy` format,  things will be much straightforward and intuitive. Thx : )

**Comment by VoVAllen** [comment]
The error here is saying the type of `nmax` should be int/long instead of float, we may need to improve the error message here.
And dgl currently support construct graph from a sparse matrix, you can directly use `g=DGLGraph(coo_matrix)` to do this.

**Comment by jermainewang** [comment]
Hi @zegzag, thanks for the report. I think the problem here is that `numpy.int` is actually a different type than python's native int. Therefore, when passing it to our own CAPIs, we should convert it to python native int.

More specifically,
https://github.com/dmlc/dgl/blob/d533e9ba62ebc5ed45ab2723c8a2c9f5598a9727/python/dgl/graph_index.py#L81
Should be:
```python
_CAPI_DGLGraphAddVertices(self._handle, int(num))
```

We should go through all such cases and fix them so numpy integer types could be supported.

**Comment by zzhang-cn** [comment]
I think the larger issue here is to zoom beyond particular errors and
support Numpy as the first citizen. This is consistent to our thinking in
the long run and in fact another team is planning work on this. If you like
to contribute I think that will be very exciting.

-zz

On Sat, May 18, 2019 at 9:13 AM Minjie Wang <notifications@github.com>
wrote:

> Hi @zegzag
> <https://urldefense.proofpoint.com/v2/url?u=https-3A__github.com_zegzag&d=DwMCaQ&c=slrrB7dE8n7gBJbeO0g-IQ&r=hT00ArSCDPGICoAESiAkOQ&m=1lCgAMK9_4nvCAlHYHzrB6Ftul1WHWlheLUd-rX0TM0&s=KZu4kiDPQ7m-vqJGZaDMo1JwuDfql9PiZx1xukzWSjM&e=>,
> thanks for the report. I think the problem here is that numpy.int is
> actually a different type than python's native int. Therefore, when passing
> it to our own CAPIs, we should convert it to python native int.
>
> More specifically,
>
> https://github.com/dmlc/dgl/blob/d533e9ba62ebc5ed45ab2723c8a2c9f5598a9727/python/dgl/graph_index.py#L81
> <https://urldefense.proofpoint.com/v2/url?u=https-3A__github.com_dmlc_dgl_blob_d533e9ba62ebc5ed45ab2723c8a2c9f5598a9727_python_dgl_graph-5Findex.py-23L81&d=DwMCaQ&c=slrrB7dE8n7gBJbeO0g-IQ&r=hT00ArSCDPGICoAESiAkOQ&m=1lCgAMK9_4nvCAlHYHzrB6Ftul1WHWlheLUd-rX0TM0&s=06Rn2xLQDy23kz0oAKjwSlH9ckXr5yqRYl7dTfA0SEo&e=>
> Should be:
>
> _CAPI_DGLGraphAddVertices(self._handle, int(num))
>
> We should go through all such cases and fix them so numpy integer types
> could be supported.
>
> —
> You are receiving this because you are subscribed to this thread.
> Reply to this email directly, view it on GitHub
> <https://urldefense.proofpoint.com/v2/url?u=https-3A__github.com_dmlc_dgl_issues_538-3Femail-5Fsource-3Dnotifications-26email-5Ftoken-3DACBJKUK32GSHQTFW7MDS7CTPV5J4ZA5CNFSM4HNJGNYKYY3PNVWWK3TUL52HS4DFVREXG43VMVBW63LNMVXHJKTDN5WW2ZLOORPWSZGODVWE3WI-23issuecomment-2D493637081&d=DwMCaQ&c=slrrB7dE8n7gBJbeO0g-IQ&r=hT00ArSCDPGICoAESiAkOQ&m=1lCgAMK9_4nvCAlHYHzrB6Ftul1WHWlheLUd-rX0TM0&s=lMNohtm9Hjsf8CALVorlh0_pIG57X36cZPqzx-NRUzU&e=>,
> or mute the thread
> <https://urldefense.proofpoint.com/v2/url?u=https-3A__github.com_notifications_unsubscribe-2Dauth_ACBJKUKCMA3LG7PVLYHPC73PV5J4ZANCNFSM4HNJGNYA&d=DwMCaQ&c=slrrB7dE8n7gBJbeO0g-IQ&r=hT00ArSCDPGICoAESiAkOQ&m=1lCgAMK9_4nvCAlHYHzrB6Ftul1WHWlheLUd-rX0TM0&s=9UxQtRT3loyryAJdBhhphmjEapwpy0NJBUkcR95rLQ8&e=>
> .
>


-- 

*Zheng Zhang <https://shanghai.nyu.edu/academics/faculty/zheng-zhang> 张峥*

Professor of Computer Science, NYU  Shanghai 上海纽约大学计算机系教授


Room 1118, 1555 Century Avenue

Pudong New District, Shanghai 200122, China

中国上海市浦东新区世纪大道1555号1118室, 200122


T Shanghai office 上海办公室 +86 021 2059 5687
T China mobile 中国手机 +86 156 1808 6522
E 电子邮件 zz@nyu.edu

<jw5@nyu.edu>

**Comment by jermainewang** [comment]
Should be fixed in #580 .
