### ISSUE TITLE
 Are the rows and columns returned by knn sorted according to the metric function, or are they returned out of order?

### ISSUE THREAD

**Issue by xiaomiao0428** [dmlc/dgl#5381]
## 📚 Documentation

![image](https://user-images.githubusercontent.com/56331443/221140938-f83841c5-db00-4347-ad78-3bca6f37e516.png)

![image](https://user-images.githubusercontent.com/56331443/221140880-de913962-44cb-4909-92ec-14f0a49126d5.png)

Are the rows and columns returned by knn sorted according to the metric function, or are they returned out of order?

**Comment by mufeili** [comment]
Could you help answer this question? @hetong007 @lygztq

**Comment by lygztq** [comment]
It depends on the algorithm you use. Overall, you can assert they are out of order.

**Comment by peizhou001** [comment]
Hi @xiaomiao0428 , I am closing this issue assuming you are happy about our response. Feel free to follow up and reopen the issue if you have more questions with regard to our response.

**Comment by peizhou001** [comment]
Hi @xiaomiao0428 , I am closing this issue assuming you are happy about our response. Feel free to follow up and reopen the issue if you have more questions with regard to our response.
