### ISSUE TITLE
Add new heterophilous datasets

### ISSUE THREAD

**Issue by OlegPlatonov** [dmlc/dgl#5383]
## 🚀 Feature
Hi! A recent [paper](https://arxiv.org/abs/2302.11640) found some issues with popular heterophilous graph datasets such as squirrel and chameleon and proposed several new datasets. It would be great to add them to DGL. The datasets are available [here](https://github.com/yandex-research/heterophilous-graphs).

**Comment by mufeili** [comment]
Thank you for sharing this paper! We will check it.

**Comment by mufeili** [comment]
@OlegPlatonov If you are interested, it will be great if you can help contribute these datasets. You might find it helpful to follow the practice of https://github.com/dmlc/dgl/pull/5477.

**Comment by mufeili** [comment]
Tracked in #5671 , close this request for now. Feel free to reopen it.
