### ISSUE TITLE
[DistDGL] Old numpy version is causing CI test failures

### ISSUE THREAD

**Issue by kylasa** [dmlc/dgl#5395]
## To Reproduce

https://github.com/dmlc/dgl/pull/5391 is failing CI tests because of older numpy version. 
This PR needs numpy to be >= 1.13.0 version. 

Please update the numpy version to the latest version.

1. PR https://github.com/dmlc/dgl/pull/5391 failiing CI tests.
1.
1.

## Environment

 - DGL Version (e.g., 1.0):
 - Backend Library & Version (e.g., PyTorch 0.4.1, MXNet/Gluon 1.3):
 - OS (e.g., Linux):
 - How you installed DGL (`conda`, `pip`, source):
 - Build command you used (if compiling from source):
 - Python version:
 - CUDA/cuDNN version (if applicable):
 - GPU models and configuration (e.g. V100):
 - Any other relevant information:

**Comment by Rhett-Ying** [comment]
`kind` argument is introduced in `numpy 1.24`. And `numpy 1.24` requires `Python >=3.8` while the minimum version of python DGL support is `3.6`. Upgrade numpy version in CI(currently, it's `3.7`.) needs discussion. @frozenbugs pls comment on this.

**Comment by kylasa** [comment]
This issue has been resolved now via a warning message to the user from the preprocessing pipeline.
