### ISSUE TITLE
RuntimeError: Expected tensor for argument #1 'indices' to have scalar type Long; but got CUDAType instead (while checking arguments for embedding)

### ISSUE THREAD

**Issue by Kokopelli84** [dmlc/dgl#540]
## 🐛 Bug

I'm truying to run the file link_prediction.py. 

## To Reproduce

1. I installed the dependencies and ran `python3 link_predict.py -d FB15k-237 --gpu 0` as instructed.

Here is the execution log.

(base) C:\Users\nfleig\dev\machine_learning\dgl\examples\pytorch\rgcn>python link_predict.py -d FB15k-237 --gpu 0
```
Namespace(dataset='FB15k-237', dropout=0.2, eval_batch_size=500, evaluate_every=500, gpu=0, grad_norm=1.0, graph_batch_size=30000, graph_split_size=0.5, lr=0.01, n_bases=100, n_epochs=6000, n_hidden=500, n_layers=2, negative_sample=10, regularization=0.01)
# entities: 14541
# relations: 237
# edges: 272115
Test graph:
C:\Users\nfleig\dev\machine_learning\dgl\examples\pytorch\rgcn\utils.py:112: RuntimeWarning: divide by zero encountered in true_divide
  norm = 1.0 / in_deg
# nodes: 14541, # edges: 544230
start training...
# sampled nodes: 9466
# sampled edges: 30000
# nodes: 9466, # edges: 30000
Done edge sampling
Traceback (most recent call last):
  File "link_predict.py", line 249, in <module>
    main(args)
  File "link_predict.py", line 164, in main
    loss = model.get_loss(g, data, labels)
  File "link_predict.py", line 75, in get_loss
    embedding = self.forward(g)
  File "link_predict.py", line 62, in forward
    return self.rgcn.forward(g)
  File "C:\Users\nfleig\dev\machine_learning\dgl\examples\pytorch\rgcn\model.py", line 54, in forward
    layer(g)
  File "C:\ProgramData\Anaconda3\lib\site-packages\torch\nn\modules\module.py", line 493, in __call__
    result = self.forward(*input, **kwargs)
  File "link_predict.py", line 31, in forward
    g.ndata['h'] = self.embedding(node_id)
  File "C:\ProgramData\Anaconda3\lib\site-packages\torch\nn\modules\module.py", line 493, in __call__
    result = self.forward(*input, **kwargs)
  File "C:\ProgramData\Anaconda3\lib\site-packages\torch\nn\modules\sparse.py", line 117, in forward
    self.norm_type, self.scale_grad_by_freq, self.sparse)
  File "C:\ProgramData\Anaconda3\lib\site-packages\torch\nn\functional.py", line 1506, in embedding
    return torch.embedding(weight, input, padding_idx, scale_grad_by_freq, sparse)
RuntimeError: Expected tensor for argument #1 'indices' to have scalar type Long; but got CUDAType instead (while checking arguments for embedding)
```
## Expected behavior

A similar thing happens when I run 4_rgcn.ipynb even after installing the dependencies. I know this is a different issue, but they might be related...

**Comment by jermainewang** [comment]
@ylfdq1118 could you have a look?

**Comment by ylfdq1118** [comment]
Hi @Kokopelli84 , I was not able to reproduce the error.

I initiated a clean environment (using docker container), and I tried both pip and anaconda installation. After installing current dgl 0.2 and the dependencies for RGCN model, everything works fine.

What's the command you used to install all the packages like the DGL as well as the dependencies?

**Comment by jermainewang** [comment]
Close due to not being active. Please reopen if issue still exists.

**Comment by abkds** [comment]
I just faced the same issue. I didn't see this thread so opened another one. I have tried everything on this thread but it still doesn't work.

**Comment by KimiakiShirahama** [comment]
I had the same runtime error on one PC (dgl=0.6.1, torch=1.7.1), although my code could run on another PC (dgl=0.6.1, torch=1.9.0). In my code, I feed a tensor of torch.int32 to an embedding layer, which works on the second PC, but doesn't work on the first PC. I changed the input tensor type to torch.int64, which made my code run on PC2. I don't know why, but the problem is solved anyway...
