### ISSUE TITLE
[DGL_RT] add DistDGL regression test - node classification + ogb-mag240m

### ISSUE THREAD

**Issue by Rhett-Ying** [dmlc/dgl#5405]
## 🔨Work Item

**IMPORTANT:**
* This template is only for dev team to track project progress. For feature request or bug report, please use the corresponding issue templates.
* DO NOT create a new work item if the purpose is to fix an existing issue or feature request. We will directly use the issue in the project tracker.

Project tracker: https://github.com/orgs/dmlc/projects/2

## Description
For now, `ogbn-products` is ready. But we need a much larger dataset to measure DistDGL performance. `ogb-mag240m` is a good choice.

**Comment by Rhett-Ying** [comment]
moved to a new milestone

**Comment by frozenbugs** [comment]
Deprecated.
