### ISSUE TITLE
Stuck when getting graph node sparse features

### ISSUE THREAD

**Issue by lpcxyi** [dmlc/dgl#5417]
## To Reproduce
I'm trying to do batch training on a large graph with high-dimensional sparse matrix features, using the api provided by dgl to create a dataloader.
```python
sampler = dgl.dataloading.MultiLayerFullNeighborSampler(2)
gtrain_dataloader = dgl.dataloading.DataLoader(
                        g, train_idx, sampler, device=device,
                        batch_size=args.bs, shuffle=True,
                        drop_last=False, num_workers=0) 
```
The following is the training code snippet:
```python
...
for epoch in range(args.epochs):
        model.train()
        total_loss = 0

        for input_nodes, output_nodes, blocks in gtrain_dataloader:
            x = blocks[0].srcdata['feat']
            # x = x.to_dense()
            y = blocks[-1].dstdata['label']
            ...
```
This code executes smoothly when I run it on the CPU. But when I run it on GPU, the code gets stuck at ```x = blocks[0].srcdata['feat']```. By the way, node features are high-dimensional sparse matrices. Why is this happening?

## Expected behavior

This code executes smoothly on GPU.
## Environment

 - DGL Version: 1.0.1
 - PyTorch: 1.11.0
 - OS (e.g., Linux): Linux
 - How you installed DGL (`conda`, `pip`, source): conda
 - Python version: 3.8.10
 - CUDA/cuDNN version (if applicable): cu113
 - GPU models and configuration (e.g. V100): RTX3090

**Comment by BarclayII** [comment]
> This code executes smoothly when I run it on the CPU. But when I run it on GPU, the code gets stuck at `x = blocks[0].srcdata['feat']`. By the way, node features are high-dimensional sparse matrices. Why is this happening?

Is your node features on CPU?  And how large is your graph and features?  Since your dimensionality is high and you are storing the features in `g.ndata` (which doesn't really support sparse features), my guess is that the code is spending too much time slicing out the features from CPU and copying it to GPU.  You could verify this by reducing the dimensionality of your node features and see if it is still stuck.

**Comment by lpcxyi** [comment]
> > This code executes smoothly when I run it on the CPU. But when I run it on GPU, the code gets stuck at `x = blocks[0].srcdata['feat']`. By the way, node features are high-dimensional sparse matrices. Why is this happening?
> 
> Is your node features on CPU? And how large is your graph and features? Since your dimensionality is high and you are storing the features in `g.ndata` (which treats sparse features as dense features), my guess is that the code is spending too much time slicing out the features from CPU and copying it to GPU. You could verify this by reducing the dimensionality of your node features and see if it is still stuck.

Thank you for your reply. Node features are indeed on the GPU. Following your advice, I tested my code on a low dimensional dataset and it works. The graph of the small dataset has more than 9,000 nodes, and the feature dimension of the nodes is also more than 9,000. The large dataset has 440,000 nodes, and the node feature dimension is 150,000. I'm guessing the data is taking too long to slice on the GPU.

**Comment by BarclayII** [comment]
I see.  My suggestion are
1. Reduce the dimensionality with something like PCA, or 
2. Store the sparse feature as a sparse tensor outside (e.g. in scipy), and slice the features manually with
   ```
   node_features = scipy.sparse.csr_matrix(...)
   for input_nodes, output_nodes, blocks in dataloader:
       input_features = node_features[input_nodes]
       input_features = torch.FloatTensor(input_features.todense())
       ...
   ```

**Comment by lpcxyi** [comment]
> I see. My suggestion are
> 
> 1. Reduce the dimensionality with something like PCA, or
> 2. Store the sparse feature as a sparse tensor outside (e.g. in scipy), and slice the features manually with
>    ```
>    node_features = scipy.sparse.csr_matrix(...)
>    for input_nodes, output_nodes, blocks in dataloader:
>        input_features = node_features[input_nodes]
>        input_features = torch.FloatTensor(input_features.todense())
>        ...
>    ```

Thank you very much for the solution, I will try it.
