### ISSUE TITLE
GNNExplainer not compatible with DGLLife models

### ISSUE THREAD

**Issue by tanyingjia** [dmlc/dgl#5421]
from dgl.nn import GNNExplainer
import dgl
My model :
GCNPredictor(
  (gnn): GCN(
    (gnn_layers): ModuleList(
      (0): GCNLayer(
        (graph_conv): GraphConv(in=39, out=256, normalization=none, activation=<function relu at 0x7f57eb80f550>)
        (dropout): Dropout(p=0.04711885823119413, inplace=False)
        (res_connection): Linear(in_features=39, out_features=256, bias=True)
        (bn_layer): BatchNorm1d(256, eps=1e-05, momentum=0.1, affine=True, track_running_stats=True)
      )
      (1): GCNLayer(
        (graph_conv): GraphConv(in=256, out=256, normalization=none, activation=<function relu at 0x7f57eb80f550>)
        (dropout): Dropout(p=0.04711885823119413, inplace=False)
        (res_connection): Linear(in_features=256, out_features=256, bias=True)
        (bn_layer): BatchNorm1d(256, eps=1e-05, momentum=0.1, affine=True, track_running_stats=True)
      )
      (2): GCNLayer(
        (graph_conv): GraphConv(in=256, out=256, normalization=none, activation=<function relu at 0x7f57eb80f550>)
        (dropout): Dropout(p=0.04711885823119413, inplace=False)
        (res_connection): Linear(in_features=256, out_features=256, bias=True)
        (bn_layer): BatchNorm1d(256, eps=1e-05, momentum=0.1, affine=True, track_running_stats=True)
      )
    )
  )
  (readout): WeightedSumAndMax(
    (weight_and_sum): WeightAndSum(
      (atom_weighting): Sequential(
        (0): Linear(in_features=256, out_features=1, bias=True)
        (1): Sigmoid()
      )
    )
  )
  (predict): MLPPredictor(
    (predict): Sequential(
      (0): Dropout(p=0.04711885823119413, inplace=False)
      (1): Linear(in_features=512, out_features=64, bias=True)
      (2): ReLU()
      (3): BatchNorm1d(64, eps=1e-05, momentum=0.1, affine=True, track_running_stats=True)
      (4): Linear(in_features=64, out_features=1, bias=True)
    )
  )
)
explainer = GNNExplainer(model, num_hops=1)
smi, g, _, _ = dataset[1236]
feats = g.ndata['h']
explaner.explain_graph(g,feats)
but an error has occurred:
TypeError                                 Traceback (most recent call last)
Cell In [34], line 1
----> 1 explaner.explain_graph(g,feats)

File ~/soft/miniconda3/envs/dgl/lib/python3.8/site-packages/dgl/nn/pytorch/explain/gnnexplainer.py:399, in GNNExplainer.explain_graph(self, graph, feat, **kwargs)
    397 # Get the initial prediction.
    398 with torch.no_grad():
--> 399     logits = self.model(graph=graph, feat=feat, **kwargs)
    400     pred_label = logits.argmax(dim=-1)
    402 feat_mask, edge_mask = self._init_masks(graph, feat)

File ~/soft/miniconda3/envs/dgl/lib/python3.8/site-packages/torch/nn/modules/module.py:1110, in Module._call_impl(self, *input, **kwargs)
   1106 # If we don't have any hooks, we want to skip the rest of the logic in
   1107 # this function, and just call forward.
   1108 if not (self._backward_hooks or self._forward_hooks or self._forward_pre_hooks or _global_backward_hooks
   1109         or _global_forward_hooks or _global_forward_pre_hooks):
-> 1110     return forward_call(*input, **kwargs)
   1111 # Do not call functions when jit is used
   1112 full_backward_hooks, non_full_backward_hooks = [], []

TypeError: forward() got an unexpected keyword argument 'graph'

**Comment by BarclayII** [comment]
According to the docstring, currently GNNExplainer assumes two arguments: `graph` and `feat`.  So your model's forward function should have these two arguments.  It should also have an optional `eweight` argument since GNNExplainer will tweak the graph with edge weights.  Does your model have them?

**Comment by tanyingjia** [comment]
Thank you for your answer,I see examples of "eweight"argument in the documentation. But I used GCNPredictor in dgllife Library,and this argument was not in my model. If this model is no this argument,it can not be used,right?

**Comment by BarclayII** [comment]
I don't think it can be used with GNNExplainer for now.

**Comment by mufeili** [comment]
> Thank you for your answer,I see examples of "eweight"argument in the documentation. But I used GCNPredictor in dgllife Library,and this argument was not in my model. If this model is no this argument,it can not be used,right?

You can copy the code in dgllife and modify it yourself.

**Comment by frozenbugs** [comment]
Hi @tanyingjia , I am closing this issue assuming you are happy about our response. Feel free to follow up and reopen the issue if you have more questions with regard to our response.
