### ISSUE TITLE
Device API cuda is not enabled

### ISSUE THREAD

**Issue by Sakura-del** [dmlc/dgl#5427]
## ❓ Questions and Help
My python environment is as follow:
torch==1.11.0+cu115
dgl==1.0.1
When I try to run dgl on a GPU with CUDA version=11.5, the following error occurred:
`dgl._ffi.base.DGLError: [14:00:04] /opt/dgl/src/runtime/c_runtime_api.cc:82: Check failed: allow_missing: Device API cuda is not enabled. Please install the cuda version of dgl.`
I try to install dgl and torch with different verions, but it not works. Is there any way to solve it?

**Comment by BarclayII** [comment]
DGL currently requires PyTorch 1.12+.  Moreover, `dgl==1.0.1` does not have GPU support; you will need something like `dgl==1.0.1+cu116` to have say CUDA 11.6 support.  You could check how to install DGL with GPU support in https://www.dgl.ai/pages/start.html.

**Comment by TristonC** [comment]
@Sakura-del Have you been able to install cuda version of dgl and run it on your GPU machine?

**Comment by frozenbugs** [comment]
Hi @Sakura-del , I am closing this issue assuming you are happy about our response. Feel free to follow up and reopen the issue if you have more questions with regard to our response.
