### ISSUE TITLE
Add GATNE-I example

### ISSUE THREAD

**Issue by luolo-cry** [dmlc/dgl#5429]
## ❓ Questions and Help

Before proceeding, please note that we recommend
using our discussion forum (https://discuss.dgl.ai) for
general questions. As a result, this issue will
likely be CLOSED shortly.
 
could you pls provide a example of GATNE- I ？or why there is GATNE-T but no GATNE-I？

**Comment by jermainewang** [comment]
Hi, thanks for the inquiry. I've marked this as a feature request. Note that this is probably a low priority unless GATNE-I can demonstrate a distinctive or inspiring usage of DGL. I'm also wondering how GATNE-I differs from GATNE-T? More specifically, could you share us what prevent you from modifying GATNE-T to be GATNE-I? The details may help us understand the learning barrier and enhance our APIs in the future.

**Comment by BarclayII** [comment]
I think the difference between GATNE-T and GATNE-I is minor, at least in math: you replace the base node embedding `b_i` in the paper, i.e. this line:
https://github.com/dmlc/dgl/blob/aa6c542aabd4cabc6533a0bee2aa7f85766e43ec/examples/pytorch/GATNE-T/src/main.py#L189
with some computation from the node's own features, e.g. the node feature passed into an MLP.  Please let us know if it works for you.

**Comment by frozenbugs** [comment]
Hi @luolo-cry , I am closing this issue assuming you are happy about our response. Feel free to follow up and reopen the issue if you have more questions with regard to our response.
