### ISSUE TITLE
AttributeError: 'DGLGraph' object has no attribute 'register_message_func'

### ISSUE THREAD

**Issue by alierkan** [dmlc/dgl#5435]
## 🐛 Bug

AttributeError: 'DGLGraph' object has no attribute 'register_message_func'

## To Reproduce

# Run this code:
import dgl
from dgl.data.tree import SST
from dgl.data import SSTDataset

trainset = SST(mode='tiny') 
tiny_sst = []
for tree in trainset:
    tiny_sst.append(tree)
graph = dgl.batch(tiny_sst)
graph.register_message_func(fn.copy_src('a', 'a'))

## Environment

 - DGL Version (e.g., 1.0): 1.0.1
 - Backend Library & Version (e.g., PyTorch 0.4.1, MXNet/Gluon 1.3):
 - OS (e.g., Linux): Ubuntu 22.04
 - How you installed DGL (`conda`, `pip`, source): pip
 - Build command you used (if compiling from source):
 - Python version: 3.10.6
 - CUDA/cuDNN version (if applicable): 11.7
 - GPU models and configuration (e.g. V100): Nvidia 3600
 - Any other relevant information:

**Comment by BarclayII** [comment]
`register_message_func` is deprecated since at least 0.6 I think.  You will need to specify the message function in `update_all`.

**Comment by alierkan** [comment]
Thank you.
