### ISSUE TITLE
when will python2 be supported?

### ISSUE THREAD

**Issue by VegaLearning** [dmlc/dgl#544]
## ❓ Questions and Help

Before proceeding, please note that we recommend
using our discussion forum (https://discuss.dgl.ai) for
general questions. As a result, this issue will
likely be CLOSED shortly.

**Comment by VoVAllen** [comment]
https://github.com/dmlc/dgl/issues/520#issuecomment-490552483

> Hi @mingloo, py2 support is on our list but not at the top. As new features are still being added and developed, we're afraid that supporting py2 may put extra burden on the project maintenance. Thus, in the next few releases, we'll still stick with py3. Thanks for your comprehension.

**Comment by VegaLearning** [comment]
> [#520 (comment)](https://github.com/dmlc/dgl/issues/520#issuecomment-490552483)
> 
> > Hi @mingloo, py2 support is on our list but not at the top. As new features are still being added and developed, we're afraid that supporting py2 may put extra burden on the project maintenance. Thus, in the next few releases, we'll still stick with py3. Thanks for your comprehension.

understand, thanks.
