### ISSUE TITLE
FileNotFoundError: Cannot find DGL C++ sparse library

### ISSUE THREAD

**Issue by tjb-tech** [dmlc/dgl#5442]
## 🐛 FileNotFoundError: Cannot find DGL C++ sparse library

I want to use the new `dgl.sparse`, a error `FileNotFoundError: Cannot find DGL C++ sparse library` occured. The detialed info is as below: 

## To Reproduce

my code: 
```python
import dgl.sparse as dglsp
```
the error: 
```shell
FileNotFoundError: Cannot find DGL C++ sparse library at /root/miniconda3/envs/crime/lib/python3.8/site-packages/dgl/dgl_sparse/libdgl_sparse_pytorch_1.9.0.so
```

## Expected behavior
I expect to use your new lib `dgl.sparse`. 

## Environment

 - DGL Version (e.g., 1.0): 1.0.1+cu113
 - Backend Library & Version (e.g., PyTorch 0.4.1, MXNet/Gluon 1.3): pytorch 1.9.0+cu111
 - OS (e.g., Linux): ubuntu 18.04.5 LTS (Bionic Beaver)
 - How you installed DGL (`conda`, `pip`, source): conda
 - Build command you used (if compiling from source): 
 - Python version: 3.8.10
 - CUDA/cuDNN version (if applicable): Cuda compilation tools, release 11.1, V11.1.105
 - GPU models and configuration (e.g. V100):   -
 - Any other relevant information:

**Comment by tjb-tech** [comment]
> duplicate of https://discuss.dgl.ai/t/filenotfounderror-cannot-find-dgl-c-sparse-library/3507

Thanks! I update my pytorch and it works!

**Comment by 523718** [comment]
i changed torch version,and it did not occur this problem again,it just lacks some packings. i don’t know if this works .in this web site: [Deep Graph Library (dgl.ai)](https://www.dgl.ai/pages/start.html),it talks windows uses 2.0 2.1 torch version.so the following is my env:openhgnn2
torch 2.0.0+cu118
torchaudio 2.0.0+cu118
torchdata 0.6.0
torchvision 0.15.0+cu118
dgl 1.1.2+cu118
i hope this can help you
