### ISSUE TITLE
Support converting heterogeneous graph to NetworkX graph

### ISSUE THREAD

**Issue by jermainewang** [dmlc/dgl#5443]
## 🚀 Feature

Extend [`dgl.to_networkx()`](https://docs.dgl.ai/generated/dgl.to_networkx.html?highlight=to_networkx#dgl.to_networkx) or add a new API `dgl.to_networkx_hetero` to support converting a DGL heterogeneous graph to a NetworkX graph.

## Motivation

Requested by user community: https://discuss.dgl.ai/t/k-hop-path-between-two-nodes-for-a-heterogeneous-graph/3448

## Alternatives

No alternative. Users need manual implementation.

### Heterogeneous graph in NetworkX
The key design decision is how to store a heterogeneous graph in NetworkX. Below are two proposals:

To create a user-item graph with two relations "follow" and "like":

**Idea 1** Set the "type" attributes of nodes and edges.

```python
>>> import networkx as nx
>>> G = nx.DiGraph()
>>> G.add_node(0, type="user")
>>> G.add_node(1, type="user")
>>> G.add_node(2, type="user")
>>> G.add_node(3, type="item")
>>> G.add_node(4, type="item")
>>> G.add_edge(0, 1, type="follow")
>>> G.add_edge(0, 2, type="follow")
>>> G.add_edge(2, 0, type="follow")
>>> G.add_edge(0, 3, type="like")
>>> G.add_edge(0, 4, type="like")
>>> G.add_edge(2, 4, type="like")
```

**Idea 2** Set the "triples" edge attribute ([rdflib's practice](https://rdflib.readthedocs.io/en/stable/_modules/rdflib/extras/external_graph_libs.html))

```python
>>> import networkx as nx
>>> G = nx.DiGraph()
>>> G.add_edge(0, 1, triples=("user", "follow", "user"))
>>> G.add_edge(0, 2, triples=("user", "follow", "user"))
>>> G.add_edge(2, 0, triples=("user", "follow", "user"))
>>> G.add_edge(0, 3, triples=("user", "like", "item"))
>>> G.add_edge(0, 4, triples=("user", "like", "item"))
>>> G.add_edge(2, 4, triples=("user", "like", "item"))
```

### API behavior

```python
import dgl
hg = ...  # DGL heterogeneous graph
hg_nx = dgl.to_networkx(hg)   # Converted to a networkx graph
```

### Handle node/edge attributes

```python
hg = ...  # DGL heterogeneous graph
hg.nodes["user"].data["x_user"] = ...   # some user node feature "x_user"
hg.nodes["item"].data["x_item"] = ...  # some item node feature "x_item"
hg_nx = dgl.to_networkx(hg, node_attrs={"user" : ["x_user"], "item" : ["x_item"]})
```

**Comment by frozenbugs** [comment]
Hi @AymericBasset , thank you for offering your help!

I think you can extend [dgl.to_networkx()](https://docs.dgl.ai/generated/dgl.to_networkx.html?highlight=to_networkx#dgl.to_networkx) by renaming existing to_networkx to _to_networkx_homo, adding a new _to_networkx_hetero method, and check the g.is_homogeneous in to_networkx to decide which internal method to call.

For "how to store a heterogeneous graph", idea2 is preferred within our internal team. If you have strong reason to adopt idea 1, we can continue our discussion here.

For leveraging canonical dev environment, build and test. You can easily leverage the script here: https://github.com/dmlc/dgl/tree/master/script.

Let us know if you encounter any issues.

**Comment by AymericBasset** [comment]
I'll give it a try then ! Thank you for the guidance

**Comment by mufeili** [comment]
Completed in #5726
