### ISSUE TITLE
bruteforce-sharemem knn algorithm is not correct for N>384

### ISSUE THREAD

**Issue by byphilipp** [dmlc/dgl#5448]
## To Reproduce

The bruteforce-sharemem (uncorrect) and bruteforce (correct) algorithms return differs results on CUDA if N>384

> from dgl.transforms import functional
    import torch
    k = 4
    for N in [128,256,380,381,382,383,384,385,386,512]:        
        x = torch.randn(N,5,device='cuda')
        y = torch.randn(N,5,device='cuda')
        inds = torch.sort(functional.knn(k,x,[N],y,[N], algorithm='bruteforce-sharemem')[1].reshape(-1,k),-1)[0]
        ind = torch.sort(functional.knn(k,x,[N],y,[N], algorithm='bruteforce')[1].reshape(-1,k),-1)[0]
        print(f"{N} errors={(ind!=inds).sum()}")

> 128 errors=0
256 errors=0
380 errors=0
381 errors=0
382 errors=0
383 errors=0
384 errors=0
385 errors=8
386 errors=11
512 errors=119

## Environment

 - DGL Version : 1.0.1+cu117
 - Backend Library & Version: PyTorch 1.13.1+cu117
 - OS (e.g., Linux): Ubuntu 22.04
 - How you installed DGL (`conda`, `pip`, source): 
pip install  dgl -f https://data.dgl.ai/wheels/cu117/repo.html
pip install  dglgo -f https://data.dgl.ai/wheels-test/repo.html
 - Build command you used (if compiling from source):
 - Python version: 3.9.13
 - CUDA/cuDNN version (if applicable): NVIDIA-SMI 525.85.12    Driver Version: 525.85.12    CUDA Version: 12.0
 - GPU models and configuration (e.g. V100): RTX4090
 - Any other relevant information:

**Comment by byphilipp** [comment]
After
pip install dgl==1.0.0 -f https://data.dgl.ai/wheels/cu117/repo.html
The number of errros are reduced
> 128 errors=0
256 errors=0
380 errors=0
381 errors=0
382 errors=0
383 errors=0
384 errors=0
385 errors=1
386 errors=8
512 errors=9

**Comment by Rhett-Ying** [comment]
such discrepancy is probably caused by the instability of `bruteforce-sharemem` algo. `bruteforce` seems stable.
```
512, num_mis_match for bruteforce-shm: 15, bruteforce: 0
1024, num_mis_match for bruteforce-shm: 98, bruteforce: 0
2048, num_mis_match for bruteforce-shm: 219, bruteforce: 0
4096, num_mis_match for bruteforce-shm: 932, bruteforce: 0
8192, num_mis_match for bruteforce-shm: 2885, bruteforce: 0
```

```
from dgl.transforms import functional
import torch
k = 4
for N in [512, 1024, 2048, 4096, 8192]:
    x = torch.randn(N,5,device='cuda')
    y = torch.randn(N,5,device='cuda')
    bf_s_0 = torch.sort(functional.knn(k,x,[N],y,[N], algorithm='bruteforce-sharemem')[1].reshape(-1,k),-1)[0]
    num_bfs = 0
    for _ in range(10):
        bf_s_1 = torch.sort(functional.knn(k,x,[N],y,[N], algorithm='bruteforce-sharemem')[1].reshape(-1,k),-1)[0]
        num_bfs += (bf_s_0!=bf_s_1).sum()
    num_bf = 0
    bf_0 = torch.sort(functional.knn(k,x,[N],y,[N], algorithm='bruteforce')[1].reshape(-1,k),-1)[0]
    for _ in range(10):
        bf_1 = torch.sort(functional.knn(k,x,[N],y,[N], algorithm='bruteforce')[1].reshape(-1,k),-1)[0]
        num_bf += (bf_0!=bf_1).sum()
    print(f"{N}, num_mis_match for bruteforce-shm: {num_bfs}, bruteforce: {num_bf}")
```

**Comment by Rhett-Ying** [comment]
@lygztq Hi, could you help take a look at this issue? I tried in my local and find `bruteforce-sharemem` seems to be not stable. is this expected?

**Comment by lygztq** [comment]
> @lygztq Hi, could you help take a look at this issue? I tried in my local and find `bruteforce-sharemem` seems to be not stable. is this expected?

Sorry for the delay, I will check this weekend.
