### ISSUE TITLE
Creating output buffers via `torch.empty()` instead of `torch.zeros()` when possible

### ISSUE THREAD

**Issue by yaox12** [dmlc/dgl#5454]
## Description

In cases where the output buffers don't have to be zeros, it's better to use `torch.empty()` to create output buffers instead of `torch.zeros()` in favor of better performance.

For example, in `segmentMM`,
https://github.com/dmlc/dgl/blob/f5ddb11448335c45b16fb1d0561c490d937ab8f5/python/dgl/backend/pytorch/sparse.py#L973
creating a buffer for the output matrix C can be significantly time-consuming for large graphs.

The following figure shows the profiling timeline for RGCN on MAG240M. As we can see, `aten::zeros` takes almost 1/3 of the total time of `segmentMM`.

![image](https://user-images.githubusercontent.com/3831900/225225116-df33a374-fe35-437d-96ea-9d745a67936d.png)

## Additional context

Pay attention to ops that require the output buffer to be strict zero, for example, `SpMMCoo` if I understand correctly.

**Comment by Rhett-Ying** [comment]
could you help optimize it

**Comment by mufeili** [comment]
Can we close this issue now? @yaox12
