### ISSUE TITLE
UVA sampling in multi-GPUs runs slower than single GPU

### ISSUE THREAD

**Issue by kaihaoma** [dmlc/dgl#5469]
## 🐛 Bug

In distributed training `torch.multiprocessing` using DGL `NeighborSampler` and `DataLoader(use_uva=True)`, UVA sampling in multi-GPUs runs slower than single GPU

## To Reproduce

1. run the example code with args world_size 1 and the average sampling time 5.03ms per batch
2. providing world_size 2 or 4, the average sampling time is 7.04ms and 7.39ms per batch respectively

```
import argparse
import time
import os
import torch
import torch.distributed as dist
import torch.multiprocessing as mp
from dgl.data import AsNodePredDataset
from dgl.dataloading import (
    DataLoader,
    NeighborSampler,
)
from ogb.nodeproppred import DglNodePropPredDataset
def get_time():
    torch.cuda.synchronize()
    dist.barrier()
    return time.time()


def run(proc_id, g, data, args):
    # find corresponding device for my rank
    device = f"cuda:{proc_id}"
    torch.cuda.set_device(device)
    # initialize process group and unpack data for sub-processes
    dist.init_process_group(
        backend="nccl",
        init_method="tcp://127.0.0.1:12345",
        world_size=args.world_size,
        rank=proc_id,
    )
    out_size, train_idx, val_idx, test_idx = data
    train_idx = train_idx.to(device)
    batch_size = 1024
    fanout = [25, 10]
    sampler = NeighborSampler(fanout, replace=True,)
    train_dataloader = DataLoader(
        g,
        train_idx,
        sampler,
        device=device,
        batch_size=batch_size,
        shuffle=True,
        drop_last=True,
        num_workers=0,
        use_ddp=True,
        use_uva=True,
    )
    warmup_batches = 5
    num_epochs = 10
    total_sampling_time = 0
    num_records = 0
    for epoch in range(num_epochs):
        for it, (input_nodes, output_nodes, blocks) in enumerate(
            train_dataloader
        ):
            t1 = get_time()
            if it >= warmup_batches:
                total_sampling_time += t1 - last_time
                num_records += 1
            last_time = t1
    print(f"Avg sampling time:{1000.*total_sampling_time / num_records}ms")
if __name__ == "__main__":

    parser = argparse.ArgumentParser()
    parser.add_argument("--world_size", type=int,
                        default=4, help="number of workers")
    args = parser.parse_args()
    dataset = AsNodePredDataset(DglNodePropPredDataset("ogbn-products"))
    g = dataset[0]
    # avoid creating certain graph formats in each sub-process to save momory
    g = g.formats("csc")
    # thread limiting to avoid resource competition
    os.environ["OMP_NUM_THREADS"] = str(mp.cpu_count() // 2 // args.world_size)
    data = (
        dataset.num_classes,
        dataset.train_idx,
        dataset.val_idx,
        dataset.test_idx,
    )
    mp.spawn(run, args=(g, data, args), nprocs=args.world_size)
```
## Expected behavior

UVA sampling in multi-GPUs should have the same overhead as in single GPU

## Environment

 - DGL Version (e.g., 1.0): 1.0.1+cu113
 - Backend Library & Version (e.g., PyTorch 0.4.1, MXNet/Gluon 1.3): PyTorch 1.12.0
 - OS: ubuntu 18.04
 - How you installed DGL (`conda`, `pip`, source): conda
 - Build command you used (if compiling from source):
 - Python version: 3.8.15
 - CUDA/cuDNN version (if applicable): CUDA 11.3 cuDNN v8.4.0
 - GPU models and configuration (e.g. V100): 4 * T4 GPUs
 - Any other relevant information:

**Comment by yaox12** [comment]
This could happen. 
In UVA sampling, GPUs will access the host memory through PCIe links. So when multiple GPUs share the PCIe bus, there would be bandwidth competition. The topology of GPUs and PCIe buses varies on different machines. You can try using the even or odd GPU cards and might see better scalability. 

Another point I'd like to bring up, even if the sampling speed per batch can be slower in multi-GPU training, you should be able to get an overall speedup because each process has fewer (1/world_size) `train_idx`.

**Comment by kaihaoma** [comment]
> This could happen. In UVA sampling, GPUs will access the host memory through PCIe links. So when multiple GPUs share the PCIe bus, which is usually the case, there would be a bandwidth competition. The topology of GPUs and PCIe buses varies on different machines, so I cannot say for sure how to avoid it. You can try using the even or odd GPU cards and might see better scalability.
> 
> Another point I'd like to bring up, even if the sampling speed per batch can be slower in multi-GPU training, you should be able to get an overall speedup because each process has fewer (1/world_size) `train_idx`.

Actually I'm using a g4dn instance and the output of `lspci -tvvv` is
```
-[0000:00]-+-00.0  Intel Corporation 440FX - 82441FX PMC [Natoma]
           +-01.0  Intel Corporation 82371SB PIIX3 ISA [Natoma/Triton II]
           +-01.3  Intel Corporation 82371AB/EB/MB PIIX4 ACPI
           +-03.0  Amazon.com, Inc. Device 1111
           +-04.0  Amazon.com, Inc. Device 8061
           +-05.0  Amazon.com, Inc. Elastic Network Adapter (ENA)
           +-1b.0  NVIDIA Corporation Device 1eb8
           +-1c.0  NVIDIA Corporation Device 1eb8
           +-1d.0  NVIDIA Corporation Device 1eb8
           +-1e.0  NVIDIA Corporation Device 1eb8
           \-1f.0  Amazon.com, Inc. NVMe SSD Controller
```
It can be seen that different GPUs are under different PCIe-switches, why there is still contention?

**Comment by yaox12** [comment]
I think in your case, all GPUs are under the **same** PCIe switch. An example of each GPU has its own PCIe-switch should be like
```
-+-[0000:d7]-+-00.0-[d8]----00.0  NVIDIA Corporation Device 20b7
 |           +-05.0  Intel Corporation Device 2034
 +-[0000:ae]-+-00.0-[af]----00.0  NVIDIA Corporation Device 20b7
 |           +-05.0  Intel Corporation Device 2034
 +-[0000:85]-+-00.0-[86]----00.0  NVIDIA Corporation Device 1eb8
 |           +-05.0  Intel Corporation Device 2034
 +-[0000:3a]-+-00.0-[3b]----00.0  NVIDIA Corporation Device 2236
 |           +-05.0  Intel Corporation Device 2034
```

**Comment by frozenbugs** [comment]
Hi @kaihaoma , I am closing this issue assuming you are happy about our response. Feel free to follow up and reopen the issue if you have more questions with regard to our response.
