### ISSUE TITLE
Querying source node index in mailbox

### ISSUE THREAD

**Issue by Junyoungpark** [dmlc/dgl#548]
Hi! I'm wondering if there any possible way to getting the source node indices in 'reduction_function'. especially, I want a get the corresponding edge indices of messages in the mailbox of a certain node in dgl graph.

**Comment by VoVAllen** [comment]
We don't support getting node indices in reduction function. 

One possible solution is adding extra field for node data and edge data and send them to reduce function. Something like
```python
g.ndata['nid']=th.arange(g.number_of_nodes())
g.update_all(lambda edges: {'id': edges.src.ndata['nid']}, ...)
```
However, this is not recommended. You may need API like `g.pull`([doc](https://docs.dgl.ai/generated/dgl.DGLGraph.pull.html)) or `g.send_and_recv`([doc](https://docs.dgl.ai/generated/dgl.DGLGraph.send_and_recv.html)), which can do partial computation on the whole graph.

**Comment by jermainewang** [comment]
@VoVAllen @Junyoungpark we actually support that. Checkout the following code snippet:

```python
>>> import dgl
>>> import networkx as nx
>>> import torch as th
>>> g = dgl.DGLGraph(nx.path_graph(5))
>>> g.ndata['h'] = th.randn((5, 5))
>>> def mfunc(edges):
...     print('Edges:', edges.edges())  # print the src, dst, and edge ids
...     return {'m' : edges.src['h']}
... 
>>> def rfunc(nodes):
...     print('Nodes', nodes.nodes())  # print the node ids being processed in this reduce function.
...     return {'h' : nodes.mailbox['m'].sum(1)}
... 
>>> g.update_all(mfunc, rfunc)
```
You will see output like this:
```
Edges: (tensor([0, 1, 1, 2, 2, 3, 3, 4]), tensor([1, 0, 2, 1, 3, 2, 4, 3]), tensor([0, 1, 2, 3, 4, 5, 6, 7]))
Nodes: tensor([3, 2, 1])
Nodes: tensor([4, 0])
```

Explanation:
* The graph is a bidirectional chain graph and all the edges are batched together for calculating messages. So you see three tensors: src id, dst id and edge id.
* The reduce function is batched by degrees. All the intermediate nodes (1,2,3) have degrees equal to four while the two end nodes (0,4) have degrees equal to two. Therefore, you see two outputs, the first computes nodes 3,2,1 while the second call computes nodes 4,0.
* The id order is consistent with the message order in the mailbox. For example, in the first rfunc call (for nodes 3,2,1), the first row of the mailbox tensor corresponds to the in-coming messages of node 3.

**Comment by Junyoungpark** [comment]
That's so nice! thanks for the comment. I gonna check it 👍
