### ISSUE TITLE
[DistDGL] Update the launch script to use `torchrun`

### ISSUE THREAD

**Issue by chang-l** [dmlc/dgl#5493]
## 🚀 Feature

Can we update the launch script below https://github.com/dmlc/dgl/blob/9e532e7def70ff0756e04676f88d4ffc80debe1f/tools/launch.py#L232 from using `torch.distributed.launch` to `torchrun`?  According to their doc, https://pytorch.org/docs/master/distributed.html#launch-utility, `torch.distributed.launch` is going to be deprecated soon. In fact, in PyT 2.0, `--local-rank` cmd argument is no longer supported in `torch.distributed.launch`.

It should be a drop-in replacement as `torchrun` provides a superset of the functionality of `torch.distributed.launch` and they support a same set of arguments. 

## Motivation

 `torch.distributed.launch` will soon be deprecated and its cmd argument `--local-rank` is no longer supported in PyT 2.0.

## Alternatives

`torchrun`

## Pitch

 `torch.distributed.launch` --> `torchrun`

**Comment by aishwaryyasarkar** [comment]
I pitch this too.

**Comment by aishwaryyasarkar** [comment]
There’s a typo in the node_classification.py. 
`local_rank` —> `local-rank`

**Comment by BarclayII** [comment]
Hi, for distributed training, please check out https://github.com/awslabs/graphstorm which simplifies a lot of errands in DistDGL.

**Comment by 9rum** [comment]
@Rhett-Ying This issue has been resolved in PR #6304. I think it can be closed as completed.

**Comment by Rhett-Ying** [comment]
@9rum thanks for your contribution.
