### ISSUE TITLE
Does GAT allow weighted adjacency matrix / graphs ?

### ISSUE THREAD

**Issue by yCobanoglu** [dmlc/dgl#5499]
Is it possible to use a weighted adjacency matrix with the GAT Model (so graph with edge weights) ?

**Comment by yCobanoglu** [comment]
`dgl.graph` doesn't allow edge weights from my understanding right ? So only unweighted graphs are allowed.

**Comment by rudongyu** [comment]
$$h_i^{(l+1)} = \sum_{j\in \mathcal{N}(i)} \alpha_{i,j} W^{(l)} h_j^{(l)}$$

$$\alpha_{ij}^{l} = \mathrm{softmax_i} (e_{ij}^{l})$$

$$  e_{ij}^{l} = \mathrm{LeakyReLU}\left(\vec{a}^T [W h_{i} \| W h_{j}]\right)$$

Hi, @yCobanoglu. According to the equations above, the weights ($\alpha_{ij}$) for message passing in GAT is computed based on src & dst node features. Could you describe where you would put your graph edge weights in the computation?

**Comment by yCobanoglu** [comment]
Good Point ! But from the tutorial i didn't see how to initialize a Graph with weights.

**Comment by rudongyu** [comment]
For storing weights in graphs, you can save weights as edge features: `g.edata["w"] = weights`.
For computation in classic GNN modules like GCN, you can pass weights to the [forward method](https://docs.dgl.ai/generated/dgl.nn.pytorch.conv.GraphConv.html#dgl.nn.pytorch.conv.GraphConv.forward).
Thanks for reporting the issue, we will optimize the docs & tutorials to make it clear.
