### ISSUE TITLE
[Sparse] SpMM does not handle strided torch tensor

### ISSUE THREAD

**Issue by jermainewang** [dmlc/dgl#5502]
## 🐛 Bug

SpMM does not handle strided torch tensor, leading to wrong computation result.

## To Reproduce

```python
import dgl.sparse as dglsp
import torch

dev = 'cuda:0'

i = torch.tensor([[1, 0, 1, 2],
                  [3, 0, 2, 1]])
v = torch.arange(4).float() + 1
A = dglsp.spmatrix(i, v, shape=(4, 4))
X = torch.arange(40).reshape(4, 5, 2).float()

print(A.to_dense())
print(X[:,:,0])

print('Correct result')
print(A.to_dense() @ X[:,:,0])

print('This is incorrect.')
print(A @ X[:,:,0])

print('This is correct.')
print(A @ X[:,:,0].clone())
```
Output:
```
tensor([[2., 0., 0., 0.],
        [0., 0., 3., 1.],
        [0., 4., 0., 0.],
        [0., 0., 0., 0.]])
tensor([[ 0.,  2.,  4.,  6.,  8.],
        [10., 12., 14., 16., 18.],
        [20., 22., 24., 26., 28.],
        [30., 32., 34., 36., 38.]])
Correct result
tensor([[  0.,   4.,   8.,  12.,  16.],
        [ 90.,  98., 106., 114., 122.],
        [ 40.,  48.,  56.,  64.,  72.],
        [  0.,   0.,   0.,   0.,   0.]])
This is incorrect.
tensor([[ 0.,  2.,  4.,  6.,  8.],
        [45., 49., 53., 57., 61.],
        [20., 24., 28., 32., 36.],
        [ 0.,  0.,  0.,  0.,  0.]])
This is correct.
tensor([[  0.,   4.,   8.,  12.,  16.],
        [ 90.,  98., 106., 114., 122.],
        [ 40.,  48.,  56.,  64.,  72.],
        [  0.,   0.,   0.,   0.,   0.]])
```

## Expected behavior

Regardless of whether `Tensor.clone()` is called (which converts a strided tensor to a non-strided one), the result should always be the same.

## Environment

 - DGL Version (e.g., 1.0): 1.0.1+cu113
 - Backend Library & Version (e.g., PyTorch 0.4.1, MXNet/Gluon 1.3): torch 1.12.1+cu113
 - OS (e.g., Linux): Linux
 - How you installed DGL (`conda`, `pip`, source): conda
 - Build command you used (if compiling from source):
 - Python version: 3.7.5
 - CUDA/cuDNN version (if applicable): 11.3
 - GPU models and configuration (e.g. V100):
 - Any other relevant information:

## Additional context

Perhaps many other operators have the same issue.

**Comment by nv-dlasalle** [comment]
I'm not aware of any of our kernels supporting strides currently (CPU or GPU), so we may need a fix much broader than just SpMM.

I think `byte_offset` is also unused in most of our code.
