### ISSUE TITLE
Add multi-machine support for DDP dataloader

### ISSUE THREAD

**Issue by chang-l** [dmlc/dgl#5522]
## 🚀 Feature

Currently, DGL dataloader only works with DDP in a single host, because dataloader uses shared memory to store indices like below: https://github.com/dmlc/dgl/blob/a244de579cbd964912aa46446a0a9b2a2f595c87/python/dgl/dataloading/dataloader.py#L262

The DGL dataloader currently does not support multiprocessing in a real distributed system, such as a multi-node architecture, unlike PyTorch's dataloader which offers this capability. While DistDGL provides a solution, it can pose a significant challenge for users due to its high level of complexity in code-base/setup/run.

I think that removing the dependency of DGL's dataloader on shared memory would be beneficial because: (1) it would improve the completeness of the dataloader, just like PyTorch; (2) it would allow users to scale up the number of GPUs at other machines without having to rely on DistDGL.

## Motivation

Extend the current dataloader (DDP) to support multi-node arch, just like PyTorch.

## Alternatives

DistDGL

## Pitch

In cases where the graph and features can fit into host memory, the DGL's dataloader should allow the multi-GPU example code to run smoothly on multi-node architectures with minimal modifications to the training script (should just be the setting in 
 `dist.init_process_group`)

For example, currently, if we run the following at each host:
```
torchrun  --nproc_per_node=2 --nnodes=2 --node_rank=xx --master_addr=XXX --master_port=1234  multi_gpu_node_classification.py --gpu 0,1,2,4

```
it would fail and print:
```
  File "multi_gpu_node_classification.py", line 118, in train
    train_dataloader = DataLoader(
  File "/usr/local/lib/python3.8/dist-packages/dgl/dataloading/dataloader.py", line 836, in __init__
    self.dataset = create_tensorized_dataset(
  File "/usr/local/lib/python3.8/dist-packages/dgl/dataloading/dataloader.py", line 562, in create_tensorized_dataset
    return DDPTensorizedDataset(indices, batch_size, drop_last, ddp_seed, shuffle)
  File "/usr/local/lib/python3.8/dist-packages/dgl/dataloading/dataloader.py", line 214, in __init__
    self._indices = call_once_and_share(
  File "/usr/local/lib/python3.8/dist-packages/dgl/multiprocessing/pytorch.py", line 104, in call_once_and_share
    result = get_shared_mem_array(name, shape, dtype)
  File "/usr/local/lib/python3.8/dist-packages/dgl/ndarray.py", line 163, in get_shared_mem_array
    new_arr = empty_shared_mem(
  File "/usr/local/lib/python3.8/dist-packages/dgl/_ffi/ndarray.py", line 169, in empty_shared_mem
    check_call(
  File "/usr/local/lib/python3.8/dist-packages/dgl/_ffi/base.py", line 70, in check_call
    raise DGLError(py_str(_LIB.DGLGetLastError()))
dgl._ffi.base.DGLError: [22:20:52] /opt/dgl/dgl-source/src/runtime/shared_mem.cc:115: Check failed: fd_ != -1 (-1 vs. -1) : fail to open shared3753903145: No such file or directory
```

## Proposal

A tentative fix for this issue could be to populate the same shared memory on each host. By duplicating the shared memory (`self.indices`), each process can continue to access the data as before without any issues.

Discussed with @nvcastet, I will create a draft PR for further discussion. (cc @TristonC @jermainewang)

@shaponiuk I think this is the same issue you brought up in the channel, right?

**Comment by shaponiuk** [comment]
@chang-l , yes, that's the same issue I've encountered.
