### ISSUE TITLE
Whether the text classification task is supported

### ISSUE THREAD

**Issue by yaoysyao** [dmlc/dgl#5533]
Does DGL support text classification tasks, and is there a related demo to refer to?

**Comment by frozenbugs** [comment]
Can you be more specific on what's the problem you are try to resolve? We don't have specific support for text classification.

**Comment by yaoysyao** [comment]
> 您能否更具体地说明您要解决的问题是什么？我们没有对文本分类的特定支持。

I want to use graph neural network to complete graph classification task of text classification, such as using R52 data set to construct a graph for each piece of data, and using graph neural network to complete graph classification. I want to know whether DGL supports such tasks. If I want to do this, do I need to construct data set into data format consistent with DGL and then build a model to complete graph classification? Are there any relevant examples you can refer to?

**Comment by BarclayII** [comment]
DGL does support graph classification.  You could see our GIN example.  To do text classification you will probably need to construct a graph yourself.  You could refer [here](https://docs.dgl.ai/guide/data-process.html#processing-graph-classification-datasets) for how to build a graph classification dataset.

**Comment by frozenbugs** [comment]
Hi @yaoysyao, I am closing this issue assuming you are happy about our response. Feel free to follow up and reopen the issue if you have more questions with regard to our response.
