### ISSUE TITLE
GNNExplainer questions

### ISSUE THREAD

**Issue by freddieyang** [dmlc/dgl#5535]
Suppose I have a graph named G1, and a graph G2 with a self-loop added:

G2 = dgl.add_self_loop(G1)

When I use the explain_node function in dgl to explain a vertex Vi in G2, I found that the length of edge_mask returned by the explain_node method will be larger than the edge corresponding to the Vi in the original graph G1. 

If I use the dgl.remofe_self_loop(G2), it will throw errors.

How to filter out the edges belonging to Vi in G1 from the G2 edge_mask?

**Comment by mufeili** [comment]
In general, the last |Vi| edges of G2 will be the added self-loops. You can also check the edge end nodes with https://docs.dgl.ai/generated/dgl.DGLGraph.edges.html#dgl.DGLGraph.edges

**Comment by freddieyang** [comment]
Does this mean that for the node VG1i in G1 and the corresponding VG2i in G2, their edge_masks are: 
`edge_mask_VG1i = [w1,w2,w3]`, 
`edge_mask_VG2i = [w1,w2,w3,w4,w5]`
Then, the corresponding w4's and w5's edges are the two new edges added in G2 using `dgl.add_self_loop(G2)`

**Comment by mufeili** [comment]
Yes, if G1 has two nodes. You can double check that with `G2.edges(...)`.

**Comment by freddieyang** [comment]
thank you for your answer.
