### ISSUE TITLE
DGLGraph.formats with list input doesn't work

### ISSUE THREAD

**Issue by mfbalin** [dmlc/dgl#5545]
## To Reproduce

```
g = g.formats(['csc', 'coo'])
g.formats()
```

Should create both csc and coo formats. But the output is:
`{'created': ['coo'], 'not created': ['csc']}`

https://colab.research.google.com/drive/1cbLt_NaWNI3X5R3ekVmLPaIrrt4iJI_g?usp=sharing

## Expected behavior

Both formats to be created.

## Environment

 - DGL Version (e.g., 1.0): 1.0
 - Backend Library & Version (e.g., PyTorch 0.4.1, MXNet/Gluon 1.3): Pytorch
 - OS (e.g., Linux):
 - How you installed DGL (`conda`, `pip`, source): pip
 - Build command you used (if compiling from source):
 - Python version:
 - CUDA/cuDNN version (if applicable):
 - GPU models and configuration (e.g. V100):
 - Any other relevant information:

**Comment by mufeili** [comment]
@frozenbugs @jermainewang @BarclayII 

Currently `DGLGraph.formats(formats)` always only creates a single sparse format even if multiple formats are passed. The format gets chosen based on some logic in C++. The rest formats appear only to be "allowed formats" and appear in `'not created'` when you invoke `DGLGraph.formats()`. I've tried DGL 0.6, and this was already the case with DGL 0.6. Do you still remember the context and expected behavior of `DGLGraph.formats(formats)`?

**Comment by jermainewang** [comment]
According to the [API doc](https://docs.dgl.ai/generated/dgl.DGLGraph.formats.html#dgl.DGLGraph.formats), "Get a cloned graph with the specified sparse format(s)", it should return a graph with all the formats specified by the users materialized. In this regard, the current implementation is buggy.

**Comment by mufeili** [comment]
@jermainewang Then do we want to fix the implementation or simply update the doc?

**Comment by mfbalin** [comment]
I think the behaviour of the code needs to be corrected, otherwise what would be the point of passing a list of formats to be created?

I had a nasty memory bug in a multi-gpu code, each process recreated formats after mp.spawn and I fixed it by using DGLGraph.create_formats_() because DGLGraph.formats is not working as intended. But this is not optimal because a user might not need all the formats and may want to save memory.

**Comment by jermainewang** [comment]
+1 w/ @mfbalin

**Comment by mufeili** [comment]
@mfbalin @jermainewang got it, added to backlog

**Comment by keli-wen** [comment]
Hi @mfbalin , I believe we have now addressed the issues with the current function. We've made two primary changes, corresponding to two separate PRs:

- [x] [[Sparse] Clean formats function docstring.](https://github.com/dmlc/dgl/pull/5851): We optimized the docstring of the `DGLGraph.formats()` function and clarified the difference between `created_formats` and `allowed_formats`.
- [x] [[Sparse] Update code and add unittest for.](https://github.com/dmlc/dgl/pull/5859): We identified the logic behind creating `created_formats` when the `DGLGraph.formats()` function return the cloned graph.

Perhaps the function's behavior is not exactly what you had anticipated. However, I am confident that our revisions have made the function more comprehensible for users and capable of accommodating all their needs. 

Lastly, thank you for raising the issue; I will now close it as resolved. Please feel free to reach out if you have any further questions. ✨

**Comment by mfbalin** [comment]
Thanks for looking into it. If I want to create only csc and coo, then do I create all the formats using create_formats_() and then use formats(['csc','coo']) so that the formats only in the intersection remain, which should be csc and coo in this case?

**Comment by keli-wen** [comment]
I believe Method 1 is the one that's invariably correct:

**Method 1:**

```python
g = dgl.rand_graph(10, 20)
g = g.formats(["csc", "coo"])
g.create_formats_()
g.formats()
# {'created': ['coo', 'csc'], 'not created': []}
```

**Method 2:**

```python
g = dgl.rand_graph(10, 20)
g.create_formats_()
g = g.formats(["csc", "coo"])
g.formats()
# {'created': ['coo', 'csc'], 'not created': []}
```

In this case, both methods yield identical results.

- For Method 1, we initially specify `allowed_formats = ["csc", "coo"]`, then proceed to create all the `allowed_formats`. This is undeniably correct.

- For Method 2, **in the context of this example**:
    - We first create all `created_formats = ["csc", "coo", "csr"]`
    - Then specify `allowed_formats = ["csc", "coo"]` using `formats(["csc", "coo"])`. As per our newly established rule, we retain the intersection of `allowed_formats` and `created_formats` from the original graph, which is `["csc", "coo"]`. 
    - **However, this operates under the assumption that `allowed_formats = ["csc", "coo", "csr"]` to begin with. If `allowed_formats = ["csc", "csr"]` initially, Method 2 fails to deliver the correct result.**


For instance, the following situation would yield an incorrect outcome. Therefore, my recommendation is: **first use `formats()` to define `allowed_formats`, then use `create_formats_()` to create all the `allowed_formats`.**

```python
g = dgl.rand_graph(10, 20)
g = g.formats(["csc", "csr"])
g.create_formats_()
g.formats()
# {'created': ['csr', 'csc'], 'not created': []}
######### The above is the pre-process #########
g.create_formats_()
g = g.formats(["csc", "coo"])
g.formats()
# {'created': ['csc'], 'not created': ['coo']}
# incorrect 
```
