### ISSUE TITLE
OSError: libcudart.so.11.0: cannot open shared object file: No such file or directory

### ISSUE THREAD

**Issue by TreastBean** [dmlc/dgl#5547]
## GPU version setup problem for help!
My cuda version is 10.2, Linux system, and iIencounter the OSError when I run the following code:
import os
os.environ['DGLBACKEND'] = 'pytorch'
import torch
import torch.nn as nn
import torch.nn.functional as F

import dgl
<img width="673" alt="image" src="https://user-images.githubusercontent.com/78266787/231693549-ec5511b5-caf3-439d-a8af-cbb2779bf5df.png">
<img width="762" alt="image" src="https://user-images.githubusercontent.com/78266787/231693602-d7d3b2fa-edad-4e49-8241-519505674746.png">

### The followings are the versions related:
dgl                           1.0.2+cu102
dglgo                         0.0.2
torch                         1.12.1
torchaudio                    0.12.1
torchvision                   0.13.1
CUDA Version: 11.3 

**Are there any effective solutions?**

**Comment by mufeili** [comment]
Could you try installing PyTorch 1.12.1 + CUDA 10.2 with conda?

**Comment by TreastBean** [comment]
> Could you try installing PyTorch 1.12.1 + CUDA 10.2 with conda?

Thanks! It has been soloved!

**Comment by peizhou001** [comment]
Hi @TreastBean , I am closing this issue assuming you are happy about our response. Feel free to follow up and reopen the issue if you have more questions with regard to our response.
