### ISSUE TITLE
Unable to build from source on ppc64le architecture

### ISSUE THREAD

**Issue by hnisonoff** [dmlc/dgl#5554]
## 🐛 Bug

I am trying to build DGL on a ppc64le architecture? Currently I have tried:
 
`cmake -DUSE_CUDA=ON -DUSE_LIBXSMM=OFF -DBUILD_CPP_TEST=OFF .. && make -j`
 
And this fails with:
 ```
[ 98%] Building CXX object CMakeFiles/dgl.dir/src/rpc/rpc.cc.o
/usr/workspace/testnewm/delete/opence-1.8.0/dgl/src/runtime/config.cc:9:10: fatal error: libxsmm_cpuid.h: No such file or directory
#include <libxsmm_cpuid.h>
          ^~~~~~~~~~~~~~~~~
compilation terminated.
make[2]: *** [CMakeFiles/dgl.dir/build.make:967: CMakeFiles/dgl.dir/src/runtime/config.cc.o] Error 1
```

I’m not sure why it is trying to include `libxsmm_cpuid.h` even though I specify to `cmake -DUSE_LIBXSMM=OFF`.

**Comment by mufeili** [comment]
@BarclayII Did we properly manage this flag?

**Comment by itaraban** [comment]
Looks strange, according to CMakeLists.txt:
`target_include_directories(dgl PRIVATE "third_party/libxsmm/include")` 
such header should be found if libxsmm submodule is correctly downloaded.
Anyway I'll prepare extra check for including such file

**Comment by hnisonoff** [comment]
(@jermainewang not sure how to re-open this issue, can you help?) 

I am running `bash script/build_dgl.sh -c` and getting the errors such as:

```
cc: error: unrecognized command line option '-march=native'; did you mean '-mcpu=native'?
make[2]: *** [third_party/tensorpipe/tensorpipe/CMakeFiles/tensorpipe_uv.dir/build.make:82: third_party/tensorpipe/tensorpipe/CMakeFiles/tensorpipe_uv.dir/__/third_party/libuv/src/fs-poll.c.o] Error 1
```

and 


```
include/libxsmm_macros.h:65:5: error: #error LIBXSMM requires X86_64, AArch64, or compatible CPUs!
 #   error LIBXSMM requires X86_64, AArch64, or compatible CPUs!
     ^~~~~
In file included from include/libxsmm_typedefs.h:14,
                 from include/libxsmm_mhd.h:14,
                 from ./src/libxsmm_math.c:11:
```

The full output of the build Is attached. 
[build_output.txt](https://github.com/dmlc/dgl/files/11392023/build_output.txt)

**Comment by Rhett-Ying** [comment]
According to the build log you shared, it failed to build `METIS` which does not take ppc into account:
```
make[2]: *** [third_party/METIS/libmetis/CMakeFiles/metis.dir/build.make:238: third_party/METIS/libmetis/CMakeFiles/metis.dir/__/GKlib/io.c.o] Error 1
cc: error: unrecognized command line option '-march=native'; did you mean '-mcpu=native'?
```

could you try to update below line in `//third-party/METIS/GKlib/GKlibSystem.cmake`:
```
set(GKlib_COPTIONS "${GKlib_COPTIONS} -march=native")
```
to
```
set(GKlib_COPTIONS "${GKlib_COPTIONS} -mcpu=native")
```

**Comment by hnisonoff** [comment]
Thanks for the help! I did this, and it seemed to fix the first error but not the second during the METIS build:

```
In file included from ./src/li
[build_output.txt](https://github.com/dmlc/dgl/files/11402960/build_output.txt)
bxsmm_trace.h:14,
                 from ./src/libxsmm_malloc.c:11:
include/libxsmm_macros.h:65:5: error: #error LIBXSMM requires X86_64, AArch64, or compatible CPUs!
 #   error LIBXSMM requires X86_64, AArch64, or compatible CPUs!

```

I've attached the full log again.

**Comment by Rhett-Ying** [comment]
seems the new log is not attached yet.

**Comment by hnisonoff** [comment]
Sorry! Should be there now

**Comment by Rhett-Ying** [comment]
seems `libxsmm` is being built. @itaraban could you help take a look at this issue: https://github.com/dmlc/dgl/issues/5554#issuecomment-1535632162 ?

**Comment by Rhett-Ying** [comment]
@hnisonoff  could you try on the latest master branch?

**Comment by hnisonoff** [comment]
Sorry for the delay will check today.

**Comment by hnisonoff** [comment]
I think we are making progress. After modifying `/third-party/METIS/GKlib/GKlibSystem.cmake` the build progressed further until erroring here:

```
-- Build files have been written to: /g/g12/nisonoff/projects/dgl/build
[  2%] Built target dmlc
[ 22%] Built target tensorpipe_uv
[ 32%] Built target metis
[ 49%] Built target tensorpipe
[100%] Built target dgl
-DCUDA_TOOLKIT_ROOT_DIR=/usr/tce/packages/cuda/cuda-11.6.1 -DTORCH_CUDA_ARCH_LIST=6.0;7.0;7.5;8.0;8.6 -DUSE_CUDA=ON -DDGL_INCLUDE_DIRS=/usr/tce/packages/cuda/cuda-11.6.1/include;/g/g12/nisonoff/projects/dgl/include;/g/g12/nisonoff/projects/dgl/third_party/dlpack/include;/g/g12/nisonoff/projects/dgl/third_party/dmlc-core/include;/g/g12/nisonoff/projects/dgl/third_party/phmap/;/g/g12/nisonoff/projects/dgl/third_party/xbyak/;/g/g12/nisonoff/projects/dgl/third_party/METIS/include/;/g/g12/nisonoff/projects/dgl/tensoradapter/include;/g/g12/nisonoff/projects/dgl/third_party/nanoflann/include;/g/g12/nisonoff/projects/dgl/third_party/libxsmm/include;/g/g12/nisonoff/projects/dgl/third_party/pcg/include;/g/g12/nisonoff/projects/dgl/third_party/METIS/GKlib;/g/g12/nisonoff/projects/dgl/third_party/METIS/include;/g/g12/nisonoff/projects/dgl/third_party/tensorpipe -DDGL_BUILD_DIR=/g/g12/nisonoff/projects/dgl/build
-- Using Python interpreter: python3
-- find_cmake.py output: /usr/workspace/nisonoff/anaconda/envs/opence-1.8.0/lib/python3.9/site-packages/torch/share/cmake;1.13.0
-- Configuring for PyTorch 1.13.0
-- Setting directory to /usr/workspace/nisonoff/anaconda/envs/opence-1.8.0/lib/python3.9/site-packages/torch/share/cmake/Torch
CMake Warning at /usr/workspace/nisonoff/anaconda/envs/opence-1.8.0/lib/python3.9/site-packages/torch/share/cmake/Caffe2/public/protobuf.cmake:88 (message):
  Protobuf cannot be found.  Depending on whether you are building Caffe2 or
  a Caffe2 dependent library, the next warning / error will give you more
  info.
Call Stack (most recent call first):
  /usr/workspace/nisonoff/anaconda/envs/opence-1.8.0/lib/python3.9/site-packages/torch/share/cmake/Caffe2/Caffe2Config.cmake:56 (include)
  /usr/workspace/nisonoff/anaconda/envs/opence-1.8.0/lib/python3.9/site-packages/torch/share/cmake/Torch/TorchConfig.cmake:68 (find_package)
  CMakeLists.txt:29 (find_package)

```

I tried installing protobuf with `condo install -c conda-forge protobuf` but this error remained.

**Comment by Rhett-Ying** [comment]
are you modifying manually? How about sync the latest master branch and build from scratch(`rm -rf builds` beforehand)?

**Comment by hnisonoff** [comment]
I did have to modify that file manually even after removing the directory and re-cloning the master branch. I am now trying to build the dev conda environment and re-build.

**Comment by hnisonoff** [comment]
@Rhett-Ying I wasn't able to build the conda environment using the script on this architecture. However, I do have a conda environment that should have the dependencies. 

It sounds like you were expecting that I shouldn't have to manually edit the `/third-party/METIS/GKlib/GKlibSystem.cmake` file. Is that correct?


I am still getting the protobuf errors that I described above.

**Comment by Rhett-Ying** [comment]
@hnisonoff  oh, sorry. for metis issue, I think you have to modify it manually. As for the protobuf issue, it looks like related to torch build. what torch version are you using? could you try to build torch from source to see if it's related to torch only?

**Comment by hnisonoff** [comment]
This was with torch 1.13.0

**Comment by Rhett-Ying** [comment]
@hnisonoff could you make sure torch is able to built from source on ppc? or you could file a ticket in torch forum?

**Comment by frozenbugs** [comment]
Hi @hnisonoff, I am closing this issue assuming you are happy about our response. Feel free to follow up and reopen the issue if you have more questions with regard to our response.
