### ISSUE TITLE
DGL 1.1  module 'dgl._ffi._cy3' has no attribute 'core'

### ISSUE THREAD

**Issue by kunmukh** [dmlc/dgl#5558]
## 🐛 Bug

In DGL 1.1, module 'dgl._ffi._cy3' has no attribute 'core'. So, tests/python/common/test_ffi.py::test_cython(), is failing. 

## To Reproduce

1. install dgl from source
1. run `bash tests/scripts/task_unit_test.sh pytorch gpu`

```shell
bash tests/scripts/task_unit_test.sh pytorch gpu
```
```shell
tests/python/common/test_ffi.py::test_cython - ModuleNotFoundError: No module named 'dgl._ffi._cy3.core'
```

## Expected behavior

The test will fail because module 'dgl._ffi._cy3' has no attribute 'core'.

## Environment

 - DGL Version (e.g., 1.0): 1.1
 - Backend Library & Version (e.g., PyTorch 0.4.1, MXNet/Gluon 1.3): torch: 2.0.0
 - OS (e.g., Linux): Linux
 - How you installed DGL (`conda`, `pip`, source): source
 - Build command you used (if compiling from source): `cmake -DUSE_CUDA=ON ..`
 - Python version: 3.8
 - CUDA/cuDNN version (if applicable): 12.1
 - GPU models and configuration (e.g. V100): NVIDIA GeForce RTX 3060

**Comment by jermainewang** [comment]
Thanks for the reporting and fix. @Rhett-Ying Could you take a look and the associated PR? I wonder what are the recent changes that cause this problem?

**Comment by Rhett-Ying** [comment]
Hi @kunmukh  I think you didn't build core extension. After running `python3 setup.py install`, please run `python3 setup.py build_ext --inplace` which will build 'dgl._ffi._cy3.core' extension. This should fix the issue.

**Comment by Rhett-Ying** [comment]
@jermainewang probably we need to mention this in the doc page: https://docs.dgl.ai/install/index.html#install-from-source ?

**Comment by jermainewang** [comment]
> @jermainewang probably we need to mention this in the doc page: https://docs.dgl.ai/install/index.html#install-from-source ?

+1

**Comment by kunmukh** [comment]
@Rhett-Ying I have having issues with `python3 setup.py build_ext --inplace`. 

1. first, `cc1plus` was not able to get the right cython version. So, I fixed it by adding the below lines to `./dgl/python/dgl/_ffi/_cython/core.pyx"`
```
# distutils: language=cython
# cython: language_level=3
```
Error:
```shell
(dgl-dev) {23-04-17 0:25}x86_64-conda_cos6-linux-gnu:~/dgl/python@master✗✗✗✗✗✗ syssec% python3 setup.py build_ext --inplace
[1/1] Cythonizing dgl/_ffi/_cython/core.pyx
/home/syssec/miniconda3/envs/dgl-dev/lib/python3.8/site-packages/Cython/Compiler/Main.py:369: FutureWarning: Cython directive 'language_level' not set, using 2 for now (Py2). This will change in a later release! File: /home/syssec/dgl/python/dgl/_ffi/_cython/core.pyx
  tree = Parsing.p_module(s, pxd, full_module_name)
cc1plus: warning: command-line option '-Wstrict-prototypes' is valid for C/ObjC but not for C++
```

2. With this error, I think it cannot switch context to C++ correctly. Am I correct?

Erro:
```shell
cc1: warning: command-line option '-std=c++11' is valid for C++/ObjC++ but not for C
dgl/_ffi/_cython/core.c:778:10: fatal error: ios: No such file or directory
  778 | #include "ios"
      |          ^~~~~
compilation terminated.
error: command '/home/syssec/miniconda3/envs/dgl-dev/bin/x86_64-conda-linux-gnu-cc' failed with exit code 1
```

I am using miniconda for env, can that cause this issue?

**Comment by Rhett-Ying** [comment]
@kunmukh How do you build DGL from source? could you try to follow this https://docs.dgl.ai/en/latest/install/index.html#linux and share the error log if possible.

**Comment by kunmukh** [comment]
I had `cmake` and `gcc` mismatched. I was able to restore my environment dependency correctly and got the `test` to work. Thank you for your support. 

![image](https://user-images.githubusercontent.com/25559310/232409933-8089fc4b-8369-46d0-8cab-8c6e7270dc97.png)

**Comment by mufeili** [comment]
fixed in the linked PR
