### ISSUE TITLE
how to create own data like citeseer, cora_v2 or pubmed?

### ISSUE THREAD

**Issue by cccusername** [dmlc/dgl#5576]
![20230420161702](https://user-images.githubusercontent.com/33566026/233304522-e8f652a5-e5cd-4eff-81b5-8a46e3a2f9fe.jpg)
hello, I trying to create own data like citeseer.But I don`t konw what this file represent.
Would you tell me how to generate this file? Looking forward to your reply. Thanks!

**Comment by czkkkkkk** [comment]
Hi @cccusername , actually you don't need to understand these files. You can follow [https://docs.dgl.ai/en/latest/tutorials/blitz/6_load_data.html](url) to create you own dataset.

**Comment by mufeili** [comment]
Close this issue for now. Feel free to reopen it if you have any further questions.
