### ISSUE TITLE
DGLError: Cannot assign node feature "h" on device cuda:0 to a graph on device cpu. Call DGLGraph.to() to copy the graph to the same device.

### ISSUE THREAD

**Issue by NitishOritro** [dmlc/dgl#5580]
## 🐛 Bug

---------------------------------------------------------------------------
DGLError                                  Traceback (most recent call last)
[<ipython-input-47-e83239312826>](https://localhost:8080/#) in <cell line: 4>()
      7 
      8     # Forward pass
----> 9     logits = model(t_features)
     10     loss = criterion(logits * tm_train_mask, torch.max(t_y_train, 1)[1])
     11     acc = ((torch.max(logits, 1)[1] == torch.max(t_y_train, 1)[1]).float() * t_train_mask).sum().item() / t_train_mask.sum().item()

5 frames
[/usr/local/lib/python3.9/dist-packages/torch/nn/modules/module.py](https://localhost:8080/#) in _call_impl(self, *args, **kwargs)
   1499                 or _global_backward_pre_hooks or _global_backward_hooks
   1500                 or _global_forward_hooks or _global_forward_pre_hooks):
-> 1501             return forward_call(*args, **kwargs)
   1502         # Do not call functions when jit is used
   1503         full_backward_hooks, non_full_backward_hooks = [], []

[<ipython-input-39-9a06b11e3ee4>](https://localhost:8080/#) in forward(self, features)
      7 
      8     def forward(self, features):
----> 9         x = self.gcn1(features)
     10         self.embedding = x
     11         x = self.gcn2(x)

[/usr/local/lib/python3.9/dist-packages/torch/nn/modules/module.py](https://localhost:8080/#) in _call_impl(self, *args, **kwargs)
   1499                 or _global_backward_pre_hooks or _global_backward_hooks
   1500                 or _global_forward_hooks or _global_forward_pre_hooks):
-> 1501             return forward_call(*args, **kwargs)
   1502         # Do not call functions when jit is used
   1503         full_backward_hooks, non_full_backward_hooks = [], []

[<ipython-input-38-5469a3918ffa>](https://localhost:8080/#) in forward(self, feat)
     47         #feat = self.feat_drop(feat)
     48         h_self = feat.mm(getattr(self, 'W'))
---> 49         g.ndata['h'] = h_self
     50         g.update_all(fn.copy_u('h', 'm'), fn.sum('m', 'neigh'))
     51         h_neigh = g.ndata['neigh']

[/usr/local/lib/python3.9/dist-packages/dgl/view.py](https://localhost:8080/#) in __setitem__(self, key, val)
     97                 "please pass a tensor directly"
     98             )
---> 99             self._graph._set_n_repr(self._ntid, self._nodes, {key: val})
    100 
    101     def __delitem__(self, key):

[/usr/local/lib/python3.9/dist-packages/dgl/heterograph.py](https://localhost:8080/#) in _set_n_repr(self, ntid, u, data)
   4033                                ' Got %d and %d instead.' % (nfeats, num_nodes))
   4034             if F.context(val) != self.device:
-> 4035                 raise DGLError('Cannot assign node feature "{}" on device {} to a graph on'
   4036                                ' device {}. Call DGLGraph.to() to copy the graph to the'
   4037                                ' same device.'.format(key, F.context(val), self.device))

DGLError: Cannot assign node feature "h" on device cuda:0 to a graph on device cpu. Call DGLGraph.to() to copy the graph to the same device.

## Environment

 - DGL Version: dgl-1.0.2+cu117
 - Backend Library & Version ( PyTorch 2.0.0):
 - OS (e.g., Windows Google Collab):
 - How you installed DGL ( `pip`, source): 
 -    1. pip install  dgl -f https://data.dgl.ai/wheels/cu117/repo.html
 -    2. pip install  dglgo -f https://data.dgl.ai/wheels-test/repo.html 
 - Build command you used (if compiling from source):
 - Python version:
 - CUDA/cuDNN version (if applicable):
 - GPU models and configuration : Google Collab 
 - Any other relevant information:

**Comment by czkkkkkk** [comment]
Hi @NitishOritro , it seems that you are assigning a GPU tensor to a CPU graph. You can make them on the same device before the assignment.

**Comment by mufeili** [comment]
Close the issue for now. Feel free to reopen it if you have any further questions.
