### ISSUE TITLE
Is there any solution to the problem of insufficient memory to construct a complete graph？

### ISSUE THREAD

**Issue by ZoroSunCT** [dmlc/dgl#5581]
## How should I use DGL to handle the dataset when graph size exceeds memory
When the number of graph datasets exceeds 100 million, I know that I can use **MultiLayerFullNeighborSampler** in conjunction with **dgl. dataloading. dataloader** to generate NodeFlow and convert massive graph data into blocks with limited memory.
But when actually using `dgl.dataloading.DataLoader(graph, ...)`, there seems to be a problem, which is that it needs to pass in an non iterative graph object. If your memory is limited, you will encounter OOM when constructing graph objects, like ,`graph = dgl.graph((u,v))` and therefore cannot construct blocks through **DataLoader** at all. It seems that if your graph object exceeds your memory, dgl will no longer be able to use it. Is there any solution to this problem, such as some lazy loading mechanisms.

**Comment by czkkkkkk** [comment]
Hi @ZoroSunCT . Sorry that DGL currently does not support loading a large graph that exceeds CPU memory. This is a direction we are actively working on.

**Comment by mufeili** [comment]
Close the issue for now. Feel free to reopen it if you have any further questions.
