### ISSUE TITLE
[GraphBlot] On-disk dataset loader

### ISSUE THREAD

**Issue by peizhou001** [dmlc/dgl#5595]
## 🔨Work Item

**IMPORTANT:**
* This template is only for dev team to track project progress. For feature request or bug report, please use the corresponding issue templates.
* DO NOT create a new work item if the purpose is to fix an existing issue or feature request. We will directly use the issue in the project tracker.

Project tracker: https://github.com/orgs/dmlc/projects/2

## Description

A loader and constructor that reads raw data from the disk and construct graph structure, features, train/val/test set objects, and also responsible for transforming the original COO format to CSR (which maybe moved to a separate preprocess setp in the future).

API:
dataset = Dataset('path')
dataset have :
1. graph storage (CSR)
2. feature storage
3. train set
4. valid set
5. test set

Code placement:
 `dgl/dataloading2/api/dataset.py`

## Depending work items or issues

#5593

**Comment by frozenbugs** [comment]
Duplicate with https://github.com/dmlc/dgl/issues/5808
