### ISSUE TITLE
[GraphBlot] LinkPrediction subgraph sampler: compact

### ISSUE THREAD

**Issue by peizhou001** [dmlc/dgl#5600]
## 🔨Work Item

**IMPORTANT:**
* This template is only for dev team to track project progress. For feature request or bug report, please use the corresponding issue templates.
* DO NOT create a new work item if the purpose is to fix an existing issue or feature request. We will directly use the issue in the project tracker.

Project tracker: https://github.com/orgs/dmlc/projects/2

## Description

Compact a COO graph or node pairs. Compact means map the original non-consecutive nodes to consecutive ones. Which is used in:

1. node pairs and negative pairs
2. subgraph after sampling

**Code**
+ C
`dgl_sparse/src/subgraph/compact.cc`
+ Python
`dgl/dataloading2/subgraph_sampler/compact.py`

**Comment by frozenbugs** [comment]
duplicate with #5828
