### ISSUE TITLE
[GraphBlot] In memory feature fetcher implementation

### ISSUE THREAD

**Issue by peizhou001** [dmlc/dgl#5602]
## 🔨Work Item

**IMPORTANT:**
* This template is only for dev team to track project progress. For feature request or bug report, please use the corresponding issue templates.
* DO NOT create a new work item if the purpose is to fix an existing issue or feature request. We will directly use the issue in the project tracker.

Project tracker: https://github.com/orgs/dmlc/projects/2

## Description

An in memory feature fetcher that follows the interface in [design doc](https://docs.google.com/document/d/1o09HS_9god5nCFmM4u7zP42GuEIoxwvy93bVgL3NYaI/edit#heading=h.41kzbcqfl0v9).

**Code**
`dgl/dataloading/data_fetcher/in_memory_fetcher.py`

**Comment by frozenbugs** [comment]
duplicate with #5823.
