### ISSUE TITLE
[CMake] Building fail on Mac M1.

### ISSUE THREAD

**Issue by czkkkkkk** [dmlc/dgl#5610]
## 🐛 Bug

When building on Mac M1, the CC compiler cannot find "pthread.h". 
![image](https://user-images.githubusercontent.com/17905585/234176284-17d69d26-3589-4edf-ab27-7265f5481e1d.png)

This is bacause #5497 uses CMAKE_C_COMPILER for building libxsmm, which is "/Library/Developer/CommandLineTools/usr/bin/cc" on Mac M1. 

However, if I simply remove this change and use "/usr/bin/cc", other errors popup.

![image](https://user-images.githubusercontent.com/17905585/234176478-ec8c1c2b-710f-4041-8eb0-f2d3d0f89ada.png)

## Environment

 - DGL Version (e.g., 1.0): master
 - Backend Library & Version (e.g., PyTorch 0.4.1, MXNet/Gluon 1.3):
 - OS (e.g., Linux): mac m1
 - How you installed DGL (`conda`, `pip`, source): 
 - Build command you used (if compiling from source):
 - Python version:
 - CUDA/cuDNN version (if applicable):
 - GPU models and configuration (e.g. V100):
 - Any other relevant information:

**Comment by itaraban** [comment]
@czkkkkkk could please check my changes(https://github.com/dmlc/dgl/pull/5626) on your machine?

**Comment by czkkkkkk** [comment]
> @czkkkkkk could you please check my changes(https://github.com/dmlc/dgl/pull/5626) on your machine?

Sure! Thanks for the fix.
