### ISSUE TITLE
[Benchmark] `bench_multigpu_sage` crashed on `master` branch

### ISSUE THREAD

**Issue by Rhett-Ying** [dmlc/dgl#5613]
## 🐛 Bug

Bechmark test [bench_multigpu_sage](https://github.com/dmlc/dgl/blob/master/benchmarks/benchmarks/multigpu/bench_multigpu_sage.py) crashed on `master` branch while works well on branch `1.0.x`.
```
[100.00%] ··· Running '/asv/dgl/benchmarks/env/06715dc6ea55f2b02b6ebc21bca7e34a/bin/python /opt/conda/lib/python3.10/site-packages/asv/benchmark.py run /asv/dgl/benchmarks/benchmarks multigpu.bench_multigpu_sage.track_time-0 
{}
 None /tmp/tmpazvmgqxd'
              OUTPUT -------->
              [W CUDAFunctions.cpp:109] Warning: CUDA initialization: CUDA driver initialization failed, you might not have a CUDA gpu. (function operator())
              Process Process-3:
              Traceback (most recent call last):
                File "/asv/dgl/benchmarks/env/06715dc6ea55f2b02b6ebc21bca7e34a/lib/python3.10/multiprocessing/process.py", line 314, in _bootstrap
                  self.run()
                File "/asv/dgl/benchmarks/env/06715dc6ea55f2b02b6ebc21bca7e34a/lib/python3.10/multiprocessing/process.py", line 108, in run
                  self._target(*self._args, **self._kwargs)
                File "/asv/dgl/benchmarks/benchmarks/utils.py", line 66, in decorated_function
                  raise exception.__class__(trace)
              RuntimeError: Traceback (most recent call last):
                File "/asv/dgl/benchmarks/benchmarks/utils.py", line 54, in _queue_result
                  res = func(*args, **kwargs)
                File "/asv/dgl/benchmarks/benchmarks/multigpu/bench_multigpu_sage.py", line 66, in run
                  th.distributed.init_process_group(
                File "/asv/dgl/benchmarks/env/06715dc6ea55f2b02b6ebc21bca7e34a/lib/python3.10/site-packages/torch/distributed/distributed_c10d.py", line 761, in init_process_group
                  default_pg = _new_process_group_helper(
                File "/asv/dgl/benchmarks/env/06715dc6ea55f2b02b6ebc21bca7e34a/lib/python3.10/site-packages/torch/distributed/distributed_c10d.py", line 897, in _new_process_group_helper
                  pg = ProcessGroupNCCL(prefix_store, group_rank, group_size, pg_options)
              RuntimeError: ProcessGroupNCCL is only supported with GPUs, no GPUs found!
              
              [W CUDAFunctions.cpp:109] Warning: CUDA initialization: CUDA driver initialization failed, you might not have a CUDA gpu. (function operator())
```

I tried to replace `mp.process()` with `mp.get_context("spawn").process()` and it resolves this issue. I am wondering why it works well on `1.0.x`.
https://github.com/dmlc/dgl/blob/ae8cbde5cfa699ff8d9e774ae6acd2cb8f7b451a/benchmarks/benchmarks/multigpu/bench_multigpu_sage.py#L180

## To Reproduce

1. build DGL on master branch.
2. `cd benchmarks`
3. run `DGL_HOME=/home/ubuntu/dgl DGL_LIBRARY_PATH=$DGL_HOME/build PYTHONPATH=$DGL_HOME/python:$PYTHONPATH asv run -n -e --python=same --verbose --bench bench_multigpu_sage`

## Environment

 - DGL Version (e.g., 1.0): 1.1
 - Backend Library & Version (e.g., PyTorch 0.4.1, MXNet/Gluon 1.3): PyTorch 1.13.1
 - OS (e.g., Linux): Ubuntu 20.04
 - How you installed DGL (`conda`, `pip`, source):
 - Build command you used (if compiling from source):
 - Python version: 3.10
 - CUDA/cuDNN version (if applicable): 11.6
 - GPU models and configuration (e.g. V100):
 - Any other relevant information:

**Comment by Rhett-Ying** [comment]
@nv-dlasalle @chang-l @yaox12 
could you help take a look at this issue? It's blocking us cut a new release.

One more question: For GPU training, should we always use `spawn` or `forkserver` instead of `fork` for multiprocessing start method? should we always use `nccl` backend instead of `gloo`?

**Comment by nv-dlasalle** [comment]
@Rhett-Ying can you list what the system configuration was and what the driver, cuda, and pytorch versions were?

While it works using `fork` in some cases, if a cuda context gets created prior to the call to `fork`, it leads to undefined behavior as it is not valid to duplicate a cuda context. So in general to be safe, we should always use `spawn`, as it may not always be obvious when a cuda context is created (I think for a while the ogb package was creating a cuda context when imported  if PyTorch Geometric was installed).
An important note here, is in cuda 12 the call `cudaSetDevice()` now initialized the cuda context, where in prior versions it did not (https://docs.nvidia.com/cuda/cuda-c-programming-guide/index.html#initialization).

When training on GPUs `nccl` should be used as the backend, to avoid doing communication across PCIe and host memory. Even if NVLINK is not present on the system, `nccl` should still be faster.

**Comment by Rhett-Ying** [comment]
@nv-dlasalle The benchmark tests are running with cuda 11.6, PyTorch 1.13.1, ubuntu 20.04

**Comment by nv-dlasalle** [comment]
Can you add the driver version (you can query it via `nvidia-smi`) and what GPU(s) the system has?

**Comment by Rhett-Ying** [comment]
Here's the configuration while reproducing in my local machine(reproduced though different from what we use in daily benchmark tests):
PyTorch: `2.0.0+cu117`
cuda + driver: `NVIDIA-SMI 515.65.01    Driver Version: 515.65.01    CUDA Version: 11.7`
ubuntu 22.04

**Comment by Rhett-Ying** [comment]
I made changes for these multigpu benchmark tests to utilize `spawn` and `nccl`, this does resolve the crash issue. But a new issue is hit which is caused by the benchmark framework(ASV) we're using. I will keep working on it.

**Comment by Rhett-Ying** [comment]
As this issue is mainly about ASV benchmark framework, let's close this ticket and I will track it on another ticket.
