### ISSUE TITLE
Unable to install DGL with CUDA support on Google Colabotary

### ISSUE THREAD

**Issue by yura-hb** [dmlc/dgl#5623]
## 🐛 Bug

Unable to install DGL library on Colab following instructions from [web](https://www.dgl.ai/pages/start.html) and GitHub release page. To be more precise sometimes `pip` installs CPU version and sometimes it installs GPU version.

## To Reproduce

1. Create a new notebook in the Google Colab. 
2. Select standard GPU instance
3. Try to install DGL

```
pip install  dgl -f https://data.dgl.ai/wheels/cu118/repo.html
```

Here are logs:

```
Looking in indexes: https://pypi.org/simple, https://us-python.pkg.dev/colab-wheels/public/simple/
Looking in links: https://data.dgl.ai/wheels/cu118/repo.html
Collecting dgl
  Downloading dgl-1.0.1-cp39-cp39-manylinux1_x86_64.whl (5.4 MB)
     ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 5.4/5.4 MB 62.3 MB/s eta 0:00:00
```

and here are second logs with GPU wheel:

```
Looking in indexes: https://pypi.org/simple, https://us-python.pkg.dev/colab-wheels/public/simple/
Looking in links: https://data.dgl.ai/wheels/cu118/repo.html
Collecting dgl
  Downloading https://data.dgl.ai/wheels/cu118/dgl-1.1.0%2Bcu118-cp39-cp39-manylinux1_x86_64.whl (86.4 MB)
     ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 86.4/86.4 MB 11.5 MB/s eta 0:00:00
```

I have tried to install nightly build. I can build from source, but on Colab it takes too long.

## Expected behavior

Wheel with GPU support is installed

## Environment

 - DGL Version (e.g., 1.0): 1.0.1
 - Backend Library & Version (e.g., PyTorch 0.4.1, MXNet/Gluon 1.3): PyTorch
 - OS (e.g., Linux): Linux
 - How you installed DGL (`conda`, `pip`, source): pip 
 - Build command you used (if compiling from source): pip install  dgl -f https://data.dgl.ai/wheels/cu118/repo.html
 - Python version: 3.9
 - CUDA/cuDNN version (if applicable): 11.8
 - GPU models and configuration (e.g. V100): Tesla T4
 - Any other relevant information: Colab

## Workarounds

You can install [conda-colab](https://pypi.org/project/condacolab/) and follow instructions to install DGL with conda

**Comment by czkkkkkk** [comment]
Hi @yura-hb , this issue should be resolved by #5645 . You can try again now.

**Comment by czkkkkkk** [comment]
I try to install DGL on Colab but cannot reproduce the issue. The problem may due to some unstable issues in our webpage.

**Comment by yura-hb** [comment]
Hi @czkkkkkk,

yes now it seems to work. Thanks for check. Close the issue.
