### ISSUE TITLE
unexpected keyword argument 'scipy_fmt'

### ISSUE THREAD

**Issue by beew** [dmlc/dgl#5624]
Hi,

I am trying out the tested codes here https://docs.dgl.ai/en/0.9.x/generated/dgl.DGLGraph.adj.html
```
g.adj(scipy_fmt='coo', etype='develops')
```
returns the error

```
DGLGraph.adj() got an unexpected keyword argument 'scipy_fmt'

```

dgl version 1.1 (built from git source) scipy 1.10.1, python 3.10.9. OS is Ubuntu 22.0.4

**Comment by czkkkkkk** [comment]
Hi @beew , in 1.1, the original `.adj()` is renamed as `.adj_external()` and `.adj()` will produce DGL sparse matrix. We will public the release note soon.

**Comment by galogm** [comment]
Since `DGLGraph.adj()` is no longer backward compatible, shouldn't this be considered a break change instead of iterating only minor versions?

**Comment by czkkkkkk** [comment]
> Since DGLGraph.adj() is no longer backward compatible, shouldn't this be considered a break change instead of iterating only minor versions?

In our 1.1.0 release note, we mentioned that `g.adj()` has a breaking change (https://github.com/dmlc/dgl/releases/tag/1.1.0).

**Comment by galogm** [comment]
> > Since DGLGraph.adj() is no longer backward compatible, shouldn't this be considered a break change instead of iterating only minor versions?
> 
> In our 1.1.0 release note, we mentioned that `g.adj()` has a breaking change (https://github.com/dmlc/dgl/releases/tag/1.1.0).

Does it mean that DGL does not follow the protocol of Semantic Versioning 2.0.0? This may not be what most users expect, since minor releases usually do not contain incompatible changes.
![image](https://github.com/dmlc/dgl/assets/65325063/95f5c31a-55d0-4917-b69e-58f2871315df)

**Comment by czkkkkkk** [comment]
> > > Since DGLGraph.adj() is no longer backward compatible, shouldn't this be considered a break change instead of iterating only minor versions?
> > 
> > 
> > In our 1.1.0 release note, we mentioned that `g.adj()` has a breaking change (https://github.com/dmlc/dgl/releases/tag/1.1.0).
> 
> Does it mean that DGL does not follow the protocol of [Semantic Versioning 2.0.0](https://semver.org/)? This may not be what most users expect, since minor releases usually do not contain incompatible changes. ![image](https://user-images.githubusercontent.com/65325063/248536538-95f5c31a-55d0-4917-b69e-58f2871315df.png)

Make sense! We will discuss this issue internally.
