### ISSUE TITLE
CUDA113 pip repository is down.

### ISSUE THREAD

**Issue by eliphatfs** [dmlc/dgl#5625]
## 🐛 Bug

When I visit https://data.dgl.ai/wheels/cu113/repo.html it only shows a blank page.
(didn't check others, but also with cu117)
cu102 works correctly.

**Comment by theisjendal** [comment]
Seems to be the same for cu118, but cu116 is up.

**Comment by eliphatfs** [comment]
The problem has been fixed. Closing.
