### ISSUE TITLE
Unable to build from source on ppc64le architecture

### ISSUE THREAD

**Issue by hnisonoff** [dmlc/dgl#5651]
I am running `bash script/build_dgl.sh -c` and getting the errors such as:

```
cc: error: unrecognized command line option '-march=native'; did you mean '-mcpu=native'?
make[2]: *** [third_party/tensorpipe/tensorpipe/CMakeFiles/tensorpipe_uv.dir/build.make:82: third_party/tensorpipe/tensorpipe/CMakeFiles/tensorpipe_uv.dir/__/third_party/libuv/src/fs-poll.c.o] Error 1
```

and 

```
include/libxsmm_macros.h:65:5: error: #error LIBXSMM requires X86_64, AArch64, or compatible CPUs!
 #   error LIBXSMM requires X86_64, AArch64, or compatible CPUs!
     ^~~~~
In file included from include/libxsmm_typedefs.h:14,
                 from include/libxsmm_mhd.h:14,
                 from ./src/libxsmm_math.c:11:
```

The full output of the build Is attached. 
[build_output.txt](https://github.com/dmlc/dgl/files/11392023/build_output.txt)

**Comment by jermainewang** [comment]
Hi @hnisonoff , it looks like a duplicate of #5554 . Does the fix there resolve your issue? If not, please reopen that issue and close this one so we can have one place to discuss.

**Comment by hnisonoff** [comment]
@jermainewang the fix did not resolve the issue. I will reopen (sorry didn't know I could do that).
