### ISSUE TITLE
The Python binding reinstalls /usr/local/lib/libdgl.so as /usr/local/dgl/libdgl.so

### ISSUE THREAD

**Issue by yurivict** [dmlc/dgl#5665]
## 🐛 Bug

```/usr/local/lib/libdgl.so``` is installed by the C++ part.

Then ```setup.py install``` reinstalls it as ```/usr/local/dgl/libdgl.so```.

## To Reproduce

Build/install using setup.py

## Environment

 - DGL Version (e.g., 1.0): 1.1.0
 - Backend Library & Version (e.g., PyTorch 0.4.1, MXNet/Gluon 1.3): TF
 - OS (e.g., Linux): FreeBSD 13.2
 - How you installed DGL (`conda`, `pip`, source): setup.py
 - Build command you used (if compiling from source):
 - Python version: 3.9
 - CUDA/cuDNN version (if applicable):
 - GPU models and configuration (e.g. V100):
 - Any other relevant information:

**Comment by Rhett-Ying** [comment]
How and why do you install the C++ project manually? After build libdgl.so, we just need to run `setup.py install`.
