### ISSUE TITLE
Bundled metis library isn't installed

### ISSUE THREAD

**Issue by yurivict** [dmlc/dgl#5666]
## 🐛 Bug

dgl bundles metis, builds libmetis.so, and then doesn't install it.

dgl should either use the standard metis library, or install the bundled one under a different name to avoid conflict with libmetis.so installed by the package.

## Environment

 - DGL Version (e.g., 1.0): 1.1.0
 - Backend Library & Version (e.g., PyTorch 0.4.1, MXNet/Gluon 1.3):
 - OS (e.g., Linux): FreeBSD 13.2
 - How you installed DGL (`conda`, `pip`, source):
 - Build command you used (if compiling from source):
 - Python version:
 - CUDA/cuDNN version (if applicable):
 - GPU models and configuration (e.g. V100):
 - Any other relevant information:

**Comment by Rhett-Ying** [comment]
did you fail to build metis? what's the error log?

**Comment by Rhett-Ying** [comment]
DGL links `build/third_party/METIS/libmetis/libmetis.a` statically instead of dynamically.
