### ISSUE TITLE
ImportError: cannot import name 'NodeDataLoader' from 'dgl.dataloading'

### ISSUE THREAD

**Issue by jellyfishovo** [dmlc/dgl#5667]
i was using py39,torch==2.0.0,dgl==1.1.0+cu117
while runing my code,it reports:
ImportError: cannot import name 'NodeDataLoader' from 'dgl.dataloading'
how can i do to sovle this
Thanks

**Comment by Rhett-Ying** [comment]
`NodeDataLoader` has been deprecated. please use `DataLoader` instead. refer to [here](https://docs.dgl.ai/generated/dgl.dataloading.DataLoader.html#dgl.dataloading.DataLoader) for more details.
