### ISSUE TITLE
Unsupervised Graph Embeddings

### ISSUE THREAD

**Issue by mihirtare** [dmlc/dgl#5675]
Are there any examples for generating embeddings for homogeneous graphs (preferably with node properties) using unsupervised methods?

**Comment by Rhett-Ying** [comment]
please refer to https://github.com/dmlc/dgl/blob/master/examples/pytorch/graphsage/advanced/train_lightning_unsupervised.py

**Comment by mihirtare** [comment]
Struggling to follow that example. Is there a guide to using it?

**Comment by mufeili** [comment]
There isn't a guide, but it might be helpful to read the related part in the GraphSAGE paper.

**Comment by frozenbugs** [comment]
Hi, I am closing this issue assuming you are happy about our response. Feel free to follow up and reopen the issue if you have more questions with regard to our response.
