### ISSUE TITLE
MiniGCDataset(80, 10, 20)

### ISSUE THREAD

**Issue by LYF14020510036** [dmlc/dgl#568]
MiniGCDataset(80, 10, 20)

Is the maximum number of nodes 20 for all graphs?  It seems that the number of nodes in some graphs is multiplied by 2.

**Comment by mufeili** [comment]
@LYF14020510036 , thanks for the report and we've filed a PR for fixing it.

**Comment by jermainewang** [comment]
Should be fixed in #585 .

**Comment by LYF14020510036** [comment]
Thank for your reply. I am a student. Recently, I will write a paper and use the MiniGCDataset of your DGL library. I don't know how to quote references.

> Should be fixed in #585 .

**Comment by mufeili** [comment]
@LYF14020510036 Thank you for your interest. We've published a [related paper](https://rlgm.github.io/papers/49.pdf) and you can cite it. Also note that we create the MiniGCDataset mainly for the purpose of tutorial and you may consider it rather as a synthetic dataset for graph classification. If you want to demonstrate your model, you should also include more serious datasets.

@jermainewang , maybe we should add an entry about how to cite the library in README?

**Comment by LYF14020510036** [comment]
> @LYF14020510036 Thank you for your interest. We've published a [related paper](https://rlgm.github.io/papers/49.pdf) at [Representation Learning on Graphs and Manifolds Workshop at ICLR 2019](https://rlgm.github.io/) and you can cite it. Also note that we create the MiniGCDataset mainly for the purpose of tutorial and you may consider it rather as a synthetic dataset for graph classification. If you want to demonstrate your model, you should also include more serious datasets.
> 
> @jermainewang , maybe we should add an entry about how to cite the library in README?

Thank you very much, We used seven classic graph classification data sets. We have also proposed new tasks, and hope to use your MiniGCDataset.

**Comment by salihkaragoz** [comment]
Great Work!
Can we quote this study as follows;

```
@Inproceedings{dgl2019,
  Author         = {Minjie Wang and Lingfan Yu and Da Zhend and Quan Gan and Yu Gai and 
Zihao Ye and Mufei Li and Jinjing Zhou and Qi Huang and Chao Ma and Ziyue Huang and 
Qipeng Guo and Hao Zhang and Haibin Lin and Junbo Zhao and Jinyang Li and Alexander Smola and Zhend Zhang},
  Title          = {Deep graph library: Towards efficient and scalable deep learning on graphs},
  Booktitle      = {Representation Learning on Graphs and Manifolds at (ICLR) Workshop},
  Year           = {2019}
}
```

Best

**Comment by mufeili** [comment]
@salihkaragoz Thank you for your interest and it looks great. There are some typos and I've fixed below:
```
@Inproceedings{dgl2019,
  Author         = {Minjie Wang and Lingfan Yu and Da Zheng and Quan Gan and Yu Gai and 
Zihao Ye and Mufei Li and Jinjing Zhou and Qi Huang and Chao Ma and Ziyue Huang and 
Qipeng Guo and Hao Zhang and Haibin Lin and Junbo Zhao and Jinyang Li and Alexander Smola and Zheng Zhang},
  Title          = {Deep Graph Library: Towards Efficient and Scalable Deep Learning on Graphs},
  Booktitle      = {Representation Learning on Graphs and Manifolds Workshop at ICLR},
  Year           = {2019}
}
```

**Comment by jermainewang** [comment]
@salihkaragoz We will put our paper on arxiv asap after this release so people could have a better citation point. In the meanwhile, you could use @mufeili 's citation. One quick question, since RLGM is a workshop so the paper is not really "inprocedings", how to fix that? article?

**Comment by salihkaragoz** [comment]
Hmm yes, you are right it's my mistake.

Here is another ICLR 2019 workshop and its bibtexs look good. 
https://sites.google.com/view/safeml-iclr2019/accepted-papers?authuser=0
apparently, it should be the article.
