### ISSUE TITLE
why add bias in pinsage ItemToItemScorer

### ISSUE THREAD

**Issue by Super-Louis** [dmlc/dgl#5682]
https://github.com/dmlc/dgl/blob/41baa0e4483b493e74c4dee6dc67abf6d120a1cc/examples/pytorch/pinsage/layers.py#L166-L169
In this code, the bias act as a learnable parameter. Therefore, the final loss is not only related to embedding. 
It's different from what being described in the paper, what is the purpose？
Can embedding dot product or embedding similarity still be used as a measure of item similarity?

**Comment by BarclayII** [comment]
We found that adding bias would help in our dataset (MovieLens).  They can also be thought of intrinsic properties of the users and items themselves (like a "baseline rating" of an item, etc.).  You cannot directly use dot product as item similarity though: you will need to add the bias of items.
