### ISSUE TITLE
`dgl.linkx_homophily` calculation fails for `value=0`.

### ISSUE THREAD

**Issue by galogm** [dmlc/dgl#5710]
## 🐛 Bug

`dgl.linkx_homophily` calculation fails for `value=0`.

## To Reproduce

```py
import dgl

dataset = dgl.data.TexasDataset('./data')
graph = dataset[0]

# remove self-loop and make the graph undirected
graph = dgl.remove_self_loop(graph)
graph = dgl.to_bidirected(graph, copy_ndata=True)

linkx_h = dgl.linkx_homophily(graph, graph.ndata['label'])
```

## Expected behavior

```log
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "${path_to_venv}/.venv/lib/python3.7/site-packages/dgl/homophily.py", line 189, in linkx_homophily
    return value.item() / (num_classes - 1)
AttributeError: 'int' object has no attribute 'item'
```

## Environment

 - DGL Version (e.g., 1.0): 1.1.0
 - Backend Library & Version (e.g., PyTorch 0.4.1, MXNet/Gluon 1.3): 1.12.1+cu113
 - OS (e.g., Linux): Linux
 - How you installed DGL (`conda`, `pip`, source): pip
 - Build command you used (if compiling from source): none
 - Python version: 3.7.16
 - CUDA/cuDNN version (if applicable): 11.3
 - GPU models and configuration (e.g. V100): none
 - Any other relevant information: none

## Additional context

The initial `value` of linkx_homophily needs to be `tensor(0.0)` rather than `int(0)`.

![image](https://github.com/dmlc/dgl/assets/65325063/b4a60993-ee30-439c-8a82-60597b6910d9)

**Comment by mufeili** [comment]
Thank you for the report. I confirm the bug. Could you help fix it by opening a PR?
