### ISSUE TITLE
request necesssary wranings

### ISSUE THREAD

**Issue by study1157** [dmlc/dgl#5732]
## 🚀 Feature

some warnings are necessary to be shown when the API  is called which  API contents change in a new version
## Alternatives

For example, the API, dgl.khop_adj,
please see the following figures
![捕获](https://github.com/dmlc/dgl/assets/96522577/e5cdecb8-2b26-46a8-8428-c4d28316bc46)
![捕获1](https://github.com/dmlc/dgl/assets/96522577/b35a4651-ff27-4178-8117-0180ed96a7a0)

**Comment by rudongyu** [comment]
Thanks for reporting the issue. We've identified it as a bug. It will be resolved by the linked PR.
