### ISSUE TITLE
[Unit Test] test_sampler.test_layer_sampler fails sometimes

### ISSUE THREAD

**Issue by VoVAllen** [dmlc/dgl#574]
## 🐛 Bug
test_sampler.test_layer_sampler fails sometimes. Maybe due to insufficient memory.

See this CI
http://ci.dgl.ai/blue/organizations/jenkins/DGL/detail/PR-567/13/pipeline

## To Reproduce
Steps to reproduce the behavior: Repeatedly run this test, and found always fail at some iteration.

**Comment by VoVAllen** [comment]
![image](https://user-images.githubusercontent.com/8686776/58416374-ede1a480-80b3-11e9-8984-dca640822fc7.png)

![image](https://user-images.githubusercontent.com/8686776/58416430-18336200-80b4-11e9-9ab3-f525e86237e9.png)

**Comment by jermainewang** [comment]
@aksnzhy could you take a look?

**Comment by aksnzhy** [comment]
I didn't reproduce this bug in my environment, but when I use a 500 * 500 graph by the code

`g = generate_rand_graph(200)`

The ` test_layer_sampler()` will break down with the following error:

```
  File "tests/compute/test_sampler.py", line 121, in test_layer_sampler
    assert all(sub_g.layer_size(i) < size for i, size in enumerate(layer_sizes))
```

@zheng-da

**Comment by jermainewang** [comment]
@aksnzhy you could try use the CI environment using the docker image. From my previous experience, some bugs can only be reliably reproduced there.

**Comment by VoVAllen** [comment]
Does https://github.com/dmlc/dgl/pull/616#event-2396172889 fix this? @zheng-da

**Comment by zheng-da** [comment]
@VoVAllen yes.
