### ISSUE TITLE
Any example with the layer wise sampling strategies like FastGCN, AdaptiveSampling?

### ISSUE THREAD

**Issue by RyanHuangNLP** [dmlc/dgl#578]
## ❓ Questions and Help

Is there any example like [fastgcn](https://github.com/matenure/FastGCN),  [AS-GCN](https://github.com/huangwb/AS-GCN) in DGL, thank you~~

**Comment by zheng-da** [comment]
We provide layer-wise sampler in DGL. @GaiYu0 do you have examples to demonstrate the sampler?

**Comment by GaiYu0** [comment]
Please have a look [here](https://github.com/dmlc/dgl/blob/master/examples/mxnet/sampling/gcn_ns_sc.py). All you need for FastGCN is to replace `dgl.contrib.sampling.NeighborSampler` with `dgl.contrib.sampling.LayerSampler`.

**Comment by RyanHuangNLP** [comment]
@GaiYu0 @zheng-da Thanks a lot!

**Comment by mufeili** [comment]
@RyanHuangNLP If there are no follow up problems, you may close the issue. Thanks.

**Comment by mfbalin** [comment]
A new layer sampler called Labor Sampler is available now in dgl as dgl.dataloading.LaborSampler and dgl.sampling.sample_labors.
