### ISSUE TITLE
negative sampling for specific nodes

### ISSUE THREAD

**Issue by gmsft** [dmlc/dgl#5789]
## 🚀 Feature

The current negative sampling is based on edge id, for example: dgl.dataloading.negative_sampler.PerSourceUniform(k). In my practice, I need sample negative samples based on node id and can't find a suitable  method.

Finally, I find an alternative method to sample negative samples by this:
1. make a global negative sampling as many as possible 

`neg_src, neg_dst = dgl.sampling.global_uniform_negative_sampling(g, n)`
` # n is a big enough number, we aim to sample all the negative edges, so it should be a big enough number!`

2. make a new graph based on the negative edges

`neg_graph = dgl.graph((neg_src, neg_dst))`

3. sampling neighbor for specific node

`g_neg_neighbors = dgl.sampling.sample_neighbors(neg_graph,[nid, ...], neg_num ,edge_dir='out')`
`# nid is node id; neg_num is the count of negative samples.`

**Comment by czkkkkkk** [comment]
Hi @gmsft, what is your application scenario of this interface?

**Comment by gmsft** [comment]
> 
hi,
I am doing research on recommendation. When training the model using BPR Loss(the equation is pasted below), I need positive and negative (user, item) pairs for a specific user. 
<img width="334" alt="image" src="https://github.com/dmlc/dgl/assets/6802304/b4f9c915-96e5-4d99-9761-67556f8963e4">

**Comment by peizhou001** [comment]
Hi, @gmsft, a workaround is using `randint` to generate negative samples.
E.G:
```
src = src.repeat_interleave(num_negative_samples)
dst = randint(0, g.num_nodes, num_negative_samples)
```

**Comment by gmsft** [comment]
> Hi, @gmsft, a workaround is using `randint` to generate negative samples.For example:
> 
> ```
> src = src.repeat_interleave(num_negative_samples)
> dst = randint(0, g.num_nodes, num_negative_samples)
> ```

@peizhou001 Thank you.
