### ISSUE TITLE
[Examples] Move the example to the `examples/core/` folder.

### ISSUE THREAD

**Issue by keli-wen** [dmlc/dgl#5797]
## 🔨Work Item

**IMPORTANT:**
* This template is only for dev team to track project progress. For feature request or bug report, please use the corresponding issue templates.
* DO NOT create a new work item if the purpose is to fix an existing issue or feature request. We will directly use the issue in the project tracker.

Project tracker: https://github.com/orgs/dmlc/projects/2

## Description
In the header comment of `examples/sampling/node_classification.py`, I guide readers to dive deeper by referring to `examples/pytorch/graphsage/node_classification.py`. In the future, I'd like us to move this example to `examples/core/`, and update the header comment in `examples/sampling/node_classification.py`.

## Task
- [x] Move `examples/pytorch/graphsage/node_classification.py` to `examples/core/`.
- [x] Update the header comment in `examples/sampling/node_classification.py`.

**Comment by frozenbugs** [comment]
https://github.com/dmlc/dgl/pull/5874
