### ISSUE TITLE
On Disk Dataset for link classification & file loader

### ISSUE THREAD

**Issue by frozenbugs** [dmlc/dgl#5813]

**Comment by Rhett-Ying** [comment]
TVT for link prediction/classification such as `node pair`, `(src, dst, label)`, `(src, dst, neg_srcs, neg_dsts)` are already supported in [OnDiskDataset](https://github.com/dmlc/dgl/blob/cff938c6adbac28fe38ef10079a51fe3f8d97d3e/python/dgl/graphbolt/impl/ondisk_dataset.py#L213).

`CSCSamplingGraph` is also supported in `OnDiskDataset`.
