### ISSUE TITLE
[Graphbolt] Offline CSC sample graph data validator.

### ISSUE THREAD

**Issue by frozenbugs** [dmlc/dgl#5821]
## 🔨Work Item

**IMPORTANT:**
* This template is only for dev team to track project progress. For feature request or bug report, please use the corresponding issue templates.
* DO NOT create a new work item if the purpose is to fix an existing issue or feature request. We will directly use the issue in the project tracker.

Project tracker: https://github.com/orgs/dmlc/projects/2

**Comment by Rhett-Ying** [comment]
@frozenbugs  what kinds of validation are supposed to do in this work item? Validations of data members of `CSCSamplingGraph` has already been included in various `TORCH_CHECK` such as https://github.com/dmlc/dgl/blob/cff938c6adbac28fe38ef10079a51fe3f8d97d3e/graphbolt/src/csc_sampling_graph.cc#L32-L34, https://github.com/dmlc/dgl/blob/cff938c6adbac28fe38ef10079a51fe3f8d97d3e/graphbolt/src/csc_sampling_graph.cc#L42-L54 and so on.

**Comment by frozenbugs** [comment]
This is needed if we support loading from a user provided CSCSamplingGraph, for now we only support user provided COO, so it is ok to skip this work for now.
