### ISSUE TITLE
[Sparse] Standardize the behavior of `formats()`

### ISSUE THREAD

**Issue by keli-wen** [dmlc/dgl#5846]
## Motivation

Suppose we have a graph $g$ with `created_formats = ['csr', 'csc']` and `allowed_formats = ['csr', 'csc']`. Such a graph can be generated using the following code:

```python
g = dgl.rand_graph(10, 20)
g = g.formats(["csr", "csc"])
g.create_formats_()
g.formats()
# output
# {'created': ['csr', 'csc'], 'not created': []}
```

We have observed the following scenarios:

1. When we run the following code, the previously `created_formats` are preserved.

    ```python
    g = g.formats(["csr", "csc", "coo"])
    g.formats()
    # output
    # {'created': ['csr', 'csc'], 'not created': ['coo']}
    ```

2. However, when we run the code below, `formats()` discards the already created `csr` format and instead creates a `coo` format.

    ```python
    g = g.formats(["coo", "csr"])
    g.formats()
    # output
    # {'created': ['coo'], 'not created': ['csr']}
    ```

This is because the underlying implementation of the `formats()` function only specially handles the `if (formats == ALL_CODE)` case. It does not have detailed behavior definitions when the input parameter is a different `List[str]`. Hence, I am contemplating if there is a need to further standardize the behavior of `formats()`?

## Alternatives

Currently, no alternatives have been identified.

## Pitch

Consider `param: List[str]` as the parameter in `formats()`, and `created_formats: List[str]` as the sparse format(s) in graph $g$ : 

- If `len(param) == 1`, we only need to create the sparse format of `param[0]`.
- If `len(param) == 3`, we should retain the `created_formats` of graph $g$.
- If `len(param) == 2` (**🌟HIGHLIGHT🌟**):
    - Following the order `coo -> csr -> csc`, we find the first format that exists in `param`, create it, and return the cloned graph. (Current method)
    - If the intersection of `created_formats` and `param` is not empty, we retain their intersection and return it. Otherwise, following the order `coo -> csr -> csc`, we find the first format that exists in `param`, create it, and return it. (Possible new method)

Therefore, the question I would like to discuss is, which logic should we adopt when `len(param) == 2`?

## Additional context

The source code of `formats()` in `unit_graph.cc`.

```cpp
HeteroGraphPtr UnitGraph::GetGraphInFormat(dgl_format_code_t formats) const {
  if (formats == ALL_CODE)
    return HeteroGraphPtr(
        // TODO(xiangsx) Make it as graph storage.Clone()
        new UnitGraph(
            meta_graph_,
            (in_csr_->defined()) ? CSRPtr(new CSR(*in_csr_)) : nullptr,
            (out_csr_->defined()) ? CSRPtr(new CSR(*out_csr_)) : nullptr,
            (coo_->defined()) ? COOPtr(new COO(*coo_)) : nullptr, formats));
  int64_t num_vtypes = NumVertexTypes();
  if (formats & COO_CODE)
    return CreateFromCOO(num_vtypes, GetCOO(false)->adj(), formats);
  if (formats & CSR_CODE)
    return CreateFromCSR(num_vtypes, GetOutCSR(false)->adj(), formats);
  return CreateFromCSC(num_vtypes, GetInCSR(false)->adj(), formats);
}
```

**Comment by keli-wen** [comment]
I'd like to discuss the behavior definition of the `formats()` function~ 

I hope you can help me. @frozenbugs @mufeili ✨

**Comment by frozenbugs** [comment]
Let's do this: if there are intersection, retain it, otherewise create new one  following the order coo -> csr -> csc.

**Comment by mufeili** [comment]
I'm fine either way, though you may need extra efforts to deal with the unit tests and regression tests if the behavior gets changed.
