### ISSUE TITLE
Question about get_homogeneous in partition_graph

### ISSUE THREAD

**Issue by Neur1n** [dmlc/dgl#5847]
I'm confused with the operation of converting a homogeneous graph to another homogeneous here in the nested method `get_homogeneous` of `partition_graph` in file [partition.py](https://github.com/dmlc/dgl/blob/1.1.x/python/dgl/distributed/partition.py):
https://github.com/dmlc/dgl/blob/2e6112e8b69b603e094c34d4fdeac929a4aa74c5/python/dgl/distributed/partition.py#L732-L739

And it seems that `sim_g` is not accessed.

**Comment by Rhett-Ying** [comment]
it's returned in https://github.com/dmlc/dgl/blob/2e6112e8b69b603e094c34d4fdeac929a4aa74c5/python/dgl/distributed/partition.py#L774
