### ISSUE TITLE
Bug: relabel_nodes=False in .subgraph() does not work

### ISSUE THREAD

**Issue by caojy1998** [dmlc/dgl#5880]
## To Reproduce
I am currently trying to get a subgraph of my big graph with dgl, and for that I am using the function :
graph.subgraph(…). In this function, there is the argument relabel_nodes and it seems that it does not work.

`li = [1, 1369, 1373, 1373, 1374, 1380, 22389, 140832, 143046, 145310, 145391, 145440, 148924, 413736, 564627] `
`g = graph.subgraph(li, relabel_nodes=False)`
`g_nx = dgl.to_networkx(g)`
`plt.figure(figsize=[15,7])`
`nx.draw(g_nx, with_labels = True)`

## Information 
This bug is reported from the DGL forum: https://discuss.dgl.ai/t/relabel-nodes-false-in-subgraph-does-not-work/3743
Currently, the DGL dev team is trying to reproduce and fix the bug.

 

## Environment

 - DGL Version (e.g., 1.2):
 - Backend Library & Version (e.g., PyTorch 0.4.1, MXNet/Gluon 1.3):
 - OS (e.g., Linux):
 - How you installed DGL (`conda`, `pip`, source):
 - Build command you used (if compiling from source):
 - Python version:
 - CUDA/cuDNN version (if applicable):
 - GPU models and configuration (e.g. V100):
 - Any other relevant information:

**Comment by Rhett-Ying** [comment]
closed as fixed.
