### ISSUE TITLE
Fix the paper link in the docstring of `dgl.data.utils.add_node_property_split`

### ISSUE THREAD

**Issue by gvbazhenov** [dmlc/dgl#5897]
Hi! I am not sure whether it requires creating a new PR (and I hope it does not), because the problem can be fixed easily — could you please change the paper link in the [docstring](https://docs.dgl.ai/generated/dgl.data.utils.add_node_property_split.html) of `dgl.data.utils.add_node_property_split` and `dgl.data.utils.mask_nodes_by_property` from https://arxiv.org/abs/2302.13875v1 to https://arxiv.org/abs/2302.13875? We want to cite the **latest version** of our paper, not the first one.

**Comment by mufeili** [comment]
That still requires creating a PR for security considerations. It's better if you can create a PR for this so that I can approve it. Otherwise, I will need to have a teammate approve it. Thanks.
