### ISSUE TITLE
[Graphbolt] Add E2E benchmark for canonical solutions.

### ISSUE THREAD

**Issue by frozenbugs** [dmlc/dgl#5916]
## 🔨Work Item

**IMPORTANT:**
* This template is only for dev team to track project progress. For feature request or bug report, please use the corresponding issue templates.
* DO NOT create a new work item if the purpose is to fix an existing issue or feature request. We will directly use the issue in the project tracker.

Project tracker: https://github.com/orgs/dmlc/projects/2

**Comment by frozenbugs** [comment]
Node classification and multi-GPU done, missing link prediction.

**Comment by caojy1998** [comment]
> I can quickly handle the coding part, but I might need assistance from @caojy1998 as I lack certain permissions. Previously, a lot of misaligned (benchmark) settings resulted in this being blocked.

OK, I will help to run benchmark test.

**Comment by keli-wen** [comment]
I think this task has been done.
