### ISSUE TITLE
The minibatch-gpu-sampling doc is outdated

### ISSUE THREAD

**Issue by LukeLIN-web** [dmlc/dgl#5927]
https://github.com/dmlc/dgl/blob/40dcc7152d930a8761b84d9ed2041a32fa06972c/docs/source/guide/minibatch-gpu-sampling.rst?plain=1#L99
This line has a link https://github.com/dmlc/dgl/blob/master/examples/pytorch/graphsage/multi_gpu_node_classification.py 
This file has been renamed or deleted.

**Comment by BarclayII** [comment]
The new code is in https://github.com/dmlc/dgl/blob/master/examples/multigpu/node_classification_sage.py.  I have made a PR to fix it.

**Comment by LukeLIN-web** [comment]
> The new code is in https://github.com/dmlc/dgl/blob/master/examples/multigpu/node_classification_sage.py. I have made a PR to fix it.

Thank you for your help!

**Comment by LukeLIN-web** [comment]
And https://github.com/dmlc/dgl/blob/1cbe0b275e3cf938782f581d3a9589f011b54a6d/README.md?plain=1#L12C114-L12C114 
`https://docs.dgl.ai/en/latest/`  it is 403 Forbidden

**Comment by LukeLIN-web** [comment]
> > And https://github.com/dmlc/dgl/blob/1cbe0b275e3cf938782f581d3a9589f011b54a6d/README.md?plain=1#L12C114-L12C114 `https://docs.dgl.ai/en/latest/` it is 403 Forbidden
> 
> The link is good from my side. Are you still facing the problem?

It has been fixed now
