### ISSUE TITLE
is node2vec using negative sampling?

### ISSUE THREAD

**Issue by lmxhappy** [dmlc/dgl#5954]
@BarclayII hello, [node2vec](https://github.com/dmlc/dgl/blob/master/examples/pytorch/node2vec/model.py) code, neg sampling is not seen in method sample() and loss(). In the implementation, negatives is sampled, but is not compared for loss to the positive node. The negative loss is not relative to the the positive one. The nodes to a node form positive pairs, while sampled nodes form negative pairs with the node. In your implementation, It's not like this.

**Comment by BarclayII** [comment]
The negative samples and positive samples have their losses computed as binary classification loss in https://github.com/dmlc/dgl/blob/master/examples/pytorch/node2vec/model.py#L156-L160.

**Comment by frozenbugs** [comment]
Hi @lmxhappy, I am closing this issue assuming you are happy about our response. Feel free to follow up and reopen the issue if you have more questions with regard to our response.
