### ISSUE TITLE
[RFC][Feature] DGL Builtin API Syntax

### ISSUE THREAD

**Issue by ylfdq1118** [dmlc/dgl#597]
## 🚀 Feature
I am working on adding more builtin message and reduce functions and I wonder what is a better syntax for builtins.

### Current builtin function syntax
Let's take element-wise multiply between source node feature and edge feature followed by sum reduction as an example. Currently, our interface looks like the following:
```python
import dgl.function as fn
g.update_all(fn.src_mul_edge(src="h", edge="h", out="m"), fn.sum(msg="m", out="h"))
```

### Current proposal 
The current syntax is not succinct enough. So we had the following proposal to change "src" to "u", "dst" to "v", and "edge" to "uv" or "e":
```python
g.update_all(fn.u_mul_e("h", "h", "m"), fn.sum("m", "h"))
```
Let's call the above one "**Proposal 0**".

### Two more proposals
After some discussion with @jermainewang , we came up with another two proposals:

**Proposal 1**: following PyG's way of using subscription
```python
g.update_all(fn.mul("h_u", "h_e", "m_e"), fn.sum("m_e", "h_v"))
g.update_all(fn.mul_sum("h_u", "h_e", "h_v"))
```
Here in first line `fn.mul("h_u", "h_e", "m_e")`, h_u means using feature "h" on source nodes and "h_e" means using feature "h" on edges. And then we generate feature "m" on edges. 
And we also propose to add a new builtin `mul_sum`(line 2) which better represents the idea of fusion and at the meanwhile eliminates the need to specify the message field.

**Proposal 2**: using keyword argument
```python
g.update_all(fn.mul(u="h", e="h", out="m"), fn.sum("m", "h"))
g.update_all(fn.mul_sum(u="h", e="h", out="h"))
```
This proposal is somewhat similar to our current syntax with a change in function and argument name. We will force users to use keyword argument (i.e. user CANNOT use positional argument like `fn.mul("h", "h", "m")`).

### Your comments
Please reply to this issue to let us know your response to the following questions:
- Which of the above three proposals do you like most? 
- Is there any confusion/ambiguity with the syntax?
- Better syntax you have in mind?
- Any other concern?

**Comment by mufeili** [comment]
Vote for proposal 2. I suppose there should also be keyword argument in `fn.sum("m", "h")`?

**Comment by ylfdq1118** [comment]
I think that can be omitted without confusion. But we can have it in keyword style for consistency.

**Comment by ylfdq1118** [comment]
BTW, let's call the current proposal "proposal 0"

**Comment by yzh119** [comment]
I vote for the current proposal.
I think the PyG solution looks like einstein sum but to add a dimension for "v" or "e"

**Comment by jermainewang** [comment]
One issue of the proposal 2 is the argument order. For example, is `fn.sub(u='h', e='h')` different with `fn.sub(e='h', u='h')`?

**Comment by ylfdq1118** [comment]
Yeah, you are right. It has to be different.

**Comment by ylfdq1118** [comment]
Conclusion is sticking to proposal 0
