### ISSUE TITLE
[Bug] An useless assignment in `GCN2Conv`

### ISSUE THREAD

**Issue by Michael1015198808** [dmlc/dgl#5975]
## 🐛 Bug

https://github.com/dmlc/dgl/blob/e178158616012f2e3bc83e28457127ce6dc0cf03/python/dgl/nn/pytorch/conv/gcn2conv.py#L258-L267

The assignment of Line 259 seems to be useless and thus can be replaced by

```python3
feat.add_(feat_0)
```

Or Line 260 mistyped `=` instead of `+=`?

## To Reproduce

1.
1.
1.

## Environment

 - DGL Version (e.g., 1.0):
 - Backend Library & Version (e.g., PyTorch 0.4.1, MXNet/Gluon 1.3):
 - OS (e.g., Linux):
 - How you installed DGL (`conda`, `pip`, source):
 - Build command you used (if compiling from source):
 - Python version:
 - CUDA/cuDNN version (if applicable):
 - GPU models and configuration (e.g. V100):
 - Any other relevant information:

**Comment by jermainewang** [comment]
@kyawlin the original contributor of this module. This indeed looks strange to me because `add_` is an inplace operation which should be avoided usually to prevent breaking autograd.

**Comment by Michael1015198808** [comment]
Hello, it seems this issue remains unresolved for a week. Is there someone WIP?

**Comment by Michael1015198808** [comment]
Thanks for your work!
