### ISSUE TITLE
How to replace nodeflow in dgl 0.4.3?

### ISSUE THREAD

**Issue by 20221051** [dmlc/dgl#5983]
I've been researching through the dgl0.4.3 version, but a lot of errors occur, so I'm trying to update the version. However, my old research has implemented the code with version 0.4.3, so there are codes that are not in the latest version.
How can I change the nf:dgl.NodeFlow code in the code below?

    def forward(self, nf: NodeFlow):
        nf.layers[0].data['activation'] = nf.layers[0].data['features']
        for i, layer in enumerate(self.layers):
            h = nf.layers[i].data.pop('activation')
            if self.dropout:
                h = self.dropout(h)
            nf.layers[i].data['h'] = h
            nf.block_compute(i, self.message_func, fn.mean('m', 'neigh'), layer)
        h = nf.layers[-1].data.pop('activation')
        h = self.linear(h)
        return h

## ❓ Questions and Help

Before proceeding, please note that we recommend
using our discussion forum (https://discuss.dgl.ai) for
general questions. As a result, this issue will
likely be CLOSED shortly.

**Comment by jermainewang** [comment]
The equivalent concept of nodeflow in newer DGL is message flow graph (mfg). Please check out the tutorial: https://docs.dgl.ai/tutorials/large/index.html

**Comment by nicksukie** [comment]
Is there any update on how to update the dgl.NodeFlow using Graphbolt in the newest version of DGL? (see detailed question here:https://discuss.dgl.ai/t/neighbor-sampling-and-aggregation-with-graphbolt/4457)
