### ISSUE TITLE
Importing Libraries while running a DGL Image in Docker

### ISSUE THREAD

**Issue by baygaliyev** [dmlc/dgl#6003]
I used DGL image `dgllib/dgl-ci-gpu:cu102_v230606` and after running `docker run -it dgllib/dgl-ci-gpu:cu102_v230606` tried to `import dgl` and `import mxnet` (shown in the screenshot). However, I got an error like `ModuleNotFoundError: No module named 'dgl'`. How is this possible?

I am a beginner Docker user so pardon my ignorance.

![Screenshot from 2023-07-14 14-52-09](https://github.com/dmlc/dgl/assets/77738468/0091b5a2-d9ed-46b5-99a3-b8f5bea6ae76)

**Comment by TristonC** [comment]
@baygaliyev This seems not the officially released DGL container. 
@jermainewang Does DGL team officially release docker containers?
@baygaliyev  For GPU cases, NVIDIA provide docker container release which has updated DGL in it. Check out [here](https://developer.nvidia.com/dgl-container-early-access)

**Comment by baygaliyev** [comment]
@TristonC Thank you! I did not know that it's not an official container.
I also sent the request for container of NVDIA.

**Comment by frozenbugs** [comment]
Yes, the docker is designed for build dgl source code from scratch. DGL does not provide official docker. 
May I ask how a docker makes it easy for you to run DGL?
