### ISSUE TITLE
Batched node index wrong

### ISSUE THREAD

**Issue by wzm2256** [dmlc/dgl#6012]
https://docs.dgl.ai/en/latest/generated/dgl.batch.html

Original:
<html>
<body>

Original node ID | 0 ~ N_0 | 0 ~ N_1 | … | 0 ~ N_k
-- | -- | -- | -- | --
New node ID | 0 ~ N_0 | N_0+1 ~ N_0+N_1+1 | … | 1+sum_{i=0}^{k-1} N_i ~ 1+sum_{i=0}^k N_i

</body>
</html>

Should be 

<html>
<body>

Original node ID | 0 ~ N_0 | 0 ~ N_1 | … | 0 ~ N_k
-- | -- | -- | -- | --
New node ID | 0 ~ N_0 | N_0 ~ N_0+N_1 | … | sum_{i=0}^{k-1} N_i ~ sum_{i=0}^k N_i

</body>
</html>

where all the +1 should be deleted.
By the way, have you considered using math rendering? The current formulations are not pretty.

**Comment by frozenbugs** [comment]
@wzm2256 I think you are right, can you provide a quick fix, if not, we will prioritize the fix in our next cycle.

**Comment by wzm2256** [comment]
@frozenbugs Hi, I'd like to help. But for now I do not know how to edit the document. I will make a pull request as soon as I figure it out.

**Comment by frozenbugs** [comment]
You can just edit this file https://github.com/dmlc/dgl/blob/master/python/dgl/batch.py directly, the html file will be updated automatically.

**Comment by wzm2256** [comment]
Sure, I have made a quick pull request fixing this.
