### ISSUE TITLE
Add Native PyTorch CUDA support to Graphbolt.

### ISSUE THREAD

**Issue by frozenbugs** [dmlc/dgl#6021]
## 🔨Work Item

**IMPORTANT:**
* This template is only for dev team to track project progress. For feature request or bug report, please use the corresponding issue templates.
* DO NOT create a new work item if the purpose is to fix an existing issue or feature request. We will directly use the issue in the project tracker.

Project tracker: https://github.com/orgs/dmlc/projects/2

**Comment by nv-dlasalle** [comment]
@frozenbugs can you expand this request a bit more? Looking at the existing graphbolt code, it's not obvious to me how GPU support should be integrated. For example, the `CSCSamplingGraph` does not contain any logic to check that the underlying tensors are CPU accessible. Are we planning to add dispatching logic to that class as part of this issue, where member functions like `SampleNeighborsImpl()` would also be templated by the device type?

**Comment by frozenbugs** [comment]
Hi @nv-dlasalle , thanks for taking action here. Graphbolt provides a framework for integrating different kinds of implementation of the pre-defined components. Which means, there is no fixed approach for adding GPU support. Here are the patterns that I can foresee would happen in the future:
- CSCSamplingGraph support CUDA code, which means a to-device method would be added to it, and move all related tensor to GPU.
- A brand new SampingGraph structure could be added in Python level for CUDA sampling only.
- Leverage UVA for feature fetching from CPU memory to GPU directly.

**Comment by mfbalin** [comment]
@frozenbugs @czkkkkkk Is it possible for me to join the effort to support GPUs? I have plans for making Graphbolt lightning-fast on GPUs, however, I will need help and closer collaboration to do so.
