### ISSUE TITLE
[Graphbolt] Redesign TVT sets to incorporate task concept.

### ISSUE THREAD

**Issue by frozenbugs** [dmlc/dgl#6024]
## 🔨Work Item

- [x] Only support 1 task in TVT set.
- [ ] Instead of making TVT set list, design the task data structure which include one TVT set, and make the task data structure list.

**IMPORTANT:**
* This template is only for dev team to track project progress. For feature request or bug report, please use the corresponding issue templates.
* DO NOT create a new work item if the purpose is to fix an existing issue or feature request. We will directly use the issue in the project tracker.

Project tracker: https://github.com/orgs/dmlc/projects/2

**Comment by Rhett-Ying** [comment]
TVT set has been changed from list of list to list in https://github.com/dmlc/dgl/pull/6080
