### ISSUE TITLE
[Graphbolt] Update the feature store API to support 3 keys: node/edge_type, feature_name, node/edge_id.

### ISSUE THREAD

**Issue by frozenbugs** [dmlc/dgl#6028]
## 🔨Work Item

- [ ] Rename current FeatureStore -> Feature, support read / update by id(s).
- [ ] Create a new FeatureStore abstraction, support read / update by 3 keys, node/edge_type, feature_name, id(s).

**IMPORTANT:**
* This template is only for dev team to track project progress. For feature request or bug report, please use the corresponding issue templates.
* DO NOT create a new work item if the purpose is to fix an existing issue or feature request. We will directly use the issue in the project tracker.

Project tracker: https://github.com/orgs/dmlc/projects/2

**Comment by Rhett-Ying** [comment]
PR in review: https://github.com/dmlc/dgl/pull/6103.
