### ISSUE TITLE
Potential repeated edges caused by "dgl.to_homogeneous()"

### ISSUE THREAD

**Issue by jingweio** [dmlc/dgl#6031]
## 🐛 Bug
In the context of DGL, the function "dgl.to_homogeneous()" may result in repeated edges in the homogeneous version of the given graph when the same edges denote different relationships in the heterogeneous version.

## To Reproduce
```
# here edges (0, 1) & (1, 0) apear in both 'a' and 'b' types
hg = dgl.heterograph({('user', 'a', 'user'): ([0, 1, 1, 2], [1, 2, 0, 1]), ('user', 'b', 'user'): ([0, 1, 0, 1], [0, 1, 1, 0])})
g = dgl.to_homogeneous(hg)
edge_index = torch.stack(g.edges(), dim=0)
# return error as False computed
assert torch.unique(edge_index.T, dim=0).shape == edge_index.T.shape
```

## Expected behavior
This demo code should produce "AssertionError" since the edges (0, 1) & (1, 0) are repeated twice in the homogeneous version of the graph.

## Environment
 - Ubuntu 18.04.4 LTS
 - dgl=1.1.1
 - torch=1.13.0

**Comment by peizhou001** [comment]
Hi, @jingweio, this is because the original graph have multi-edges between user nodes, so it expected to keep them after conversion.
