### ISSUE TITLE
-Werror Flag

### ISSUE THREAD

**Issue by sanjayjuneja** [dmlc/dgl#6041]
While  installing grpc for P4 Language  , After removing the  -Werror Flags the following error is occured
 On Ubuntu 20.04.6 LTS
git clone https://github.com/google/grpc.git
cd grpc
git checkout v1.3.2
git submodule update --init --recursive
export LDFLAGS="-Wl,-s"
make
submodule boringssl and boringssl-with-bazel are different branches of the same repo boringssl. If the compiling process stops and the following error occurs:
cc1: warnings being treated as errors
Open and edit Makefile. In the line that starts with CPPFLAGS, remove -Werror flag. Save and close Makefile. Then run make clean and make. This time the compiling should work well.

 Error come while running  make 

src/core/lib/support/log_linux.c:57:13: error: conflicting types for ‘gettid’
   57 | static long gettid(void) { return syscall(__NR_gettid); }
      |             ^~~~~~

In file included from /usr/include/unistd.h:1170,
                 from src/core/lib/support/log_linux.c:55:
/usr/include/x86_64-linux-gnu/bits/unistd_ext.h:34:16: note: previous declaration of ‘gettid’ was here
   34 | extern __pid_t gettid (void) __THROW;
      |                ^~~~~~

make: *** [Makefile:2472: /home/p4/grpc/objs/opt/src/core/lib/support/log_linux.o] Error 1

Tried all version of   7,8,9 version of GCC still the issue remain

**Comment by frozenbugs** [comment]
Hi @sanjayjuneja , this is DGL repo, how does grpc related to DGL? Or maybe you should post the issue to https://github.com/grpc/grpc/issues?
