### ISSUE TITLE
Polish and move the follow hetero example as core dgl example.

### ISSUE THREAD

**Issue by frozenbugs** [dmlc/dgl#6047]
## 🔨Work Item

https://github.com/dmlc/dgl/blob/master/examples/pytorch/rgcn-hetero/model.py

**IMPORTANT:**
* This template is only for dev team to track project progress. For feature request or bug report, please use the corresponding issue templates.
* DO NOT create a new work item if the purpose is to fix an existing issue or feature request. We will directly use the issue in the project tracker.

Project tracker: https://github.com/orgs/dmlc/projects/2

**Comment by keli-wen** [comment]
Done
