### ISSUE TITLE
Bug in creating heterograph

### ISSUE THREAD

**Issue by caojy1998** [dmlc/dgl#6087]
## 🐛 Bug

I encounter a bug when I try to create a heterogeneous graph with same source type. It seems that the problem is caused by the wrong form of graph.srcdata.

The error message is as follow:
```
Traceback (most recent call last):
  File "/home/ubuntu/bug_create_hetero.py", line 36, in <module>
    hg.apply_edges(fn.u_add_v("h", "h", "x"))
  File "/home/ubuntu/dgl/python/dgl/heterograph.py", line 4696, in apply_edges
    edata = core.invoke_gsddmm(g, func)
  File "/home/ubuntu/dgl/python/dgl/core.py", line 285, in invoke_gsddmm
    x = data_dict_to_list(graph, x, func, lhs_target)
  File "/home/ubuntu/dgl/python/dgl/core.py", line 234, in data_dict_to_list
    output_list[src_id] = data_dict[srctype]
TypeError: new(): invalid data type 'str'
```

The root cause of the bug is that when there is only a single type of source node. The node would be stored in the format of a dict instead of a default dict. When we add features to defaultdict, it would store use the node id as a secondary key. However, when we try to store features in a dict, I would not use the node id as a secondary key since there is only one source node. So when we try to use the secondary key to access the feature of a dict, it would raise this error.

The fix of this bug is to use an if branch in `core.py: data_dict_to_list()`  to judge whether the dict has secondary dict structure. If it is a single tensor, we skip the process of extracting the feature using node id as secondary key.

We have fixed the bug in PR https://github.com/dmlc/dgl/pull/6093.

## To Reproduce

Executing the following code can reproduce the error:
```
import inspect
import os
import shutil
import time

import dgl
import numpy as np
import torch
import dgl.function as fn

import scipy.sparse as spsp

def create_random_hetero():
    num_nodes = {"n1": 1000, "n2": 1010, "n3": 1020}
    etypes = [
        ("n1", "r1", "n2"),
        ("n1", "r2", "n2"),
    ]
    edges = {}
    for etype in etypes:
        src_ntype, _, dst_ntype = etype
        arr = spsp.random(
            num_nodes[src_ntype],
            num_nodes[dst_ntype],
            density=0.001,
            format="coo",
            random_state=100,
        )
        edges[etype] = (arr.row, arr.col)
    return dgl.heterograph(edges)

hg = create_random_hetero()
hg.nodes['n1'].data['h'] = torch.randn((hg.num_nodes("n1"), 1), device="cpu")
hg.nodes['n2'].data['h'] = torch.randn((hg.num_nodes("n2"), 1), device="cpu")

hg.apply_edges(fn.u_add_v("h", "h", "x"))
``` 

## Environment

 - DGL Version (e.g., 1.0):
 - Backend Library & Version (e.g., PyTorch 0.4.1, MXNet/Gluon 1.3):
 - OS (e.g., Linux):
 - How you installed DGL (`conda`, `pip`, source):
 - Build command you used (if compiling from source):
 - Python version:
 - CUDA/cuDNN version (if applicable):
 - GPU models and configuration (e.g. V100):
 - Any other relevant information:

**Comment by Rhett-Ying** [comment]
@caojy1998 for the record, please elaborate the root cause and details of fix here.

**Comment by caojy1998** [comment]
> @caojy1998 for the record, please elaborate the root cause and details of fix here.

OK, I have added the description and fix solution.
