### ISSUE TITLE
Hi I'm not pretty sure how can I use DGL for dynamic graphs for edge classification and nod eclassification?

### ISSUE THREAD

**Issue by fatemehteimury** [dmlc/dgl#609]
## ❓ Questions and Help

Before proceeding, please note that we recommend
using our discussion forum (https://discuss.dgl.ai) for
general questions. As a result, this issue will
likely be CLOSED shortly.

**Comment by VoVAllen** [comment]
Please using our discussion forum  (https://discuss.dgl.ai) for
general questions. We would be glad to help you there. Thanks!

**Comment by fatemehteimury** [comment]
Thanks for your help. I will ask my question there.
