### ISSUE TITLE
Is distributed training  available for tensorflow backend yet

### ISSUE THREAD

**Issue by lzujiao** [dmlc/dgl#6115]
I see that distributed training is only available for PyTorch backend in document(https://docs.dgl.ai/guide/distributed.html), but i am not sure if the document is up to date. Please leave me message, thank you.

**Comment by frozenbugs** [comment]
Yes, unfortunately, it is PyTorch only.

**Comment by lzujiao** [comment]
Is there a schedule in a short period of time?

**Comment by frozenbugs** [comment]
No, we don't have plan to support Tensorflow in near future.

**Comment by lzujiao** [comment]
All right, thank you
