### ISSUE TITLE
for link prediction although I import rdflib but I receive unkown dataset 'rdflib' I also try 'aifb' that have been used for community detection but I receive the same error

### ISSUE THREAD

**Issue by fatemehteimury** [dmlc/dgl#613]
## ❓ Questions and Help

Before proceeding, please note that we recommend
using our discussion forum (https://discuss.dgl.ai) for
general questions. As a result, this issue will
likely be CLOSED shortly.

**Comment by mufeili** [comment]
Could you please a minimal block of code for reproduction? Thank you.

**Comment by jermainewang** [comment]
Hey, please provide more details and descriptions. You could also use the discussion forum for more support. Close this for now. Please reopen if the problem still exists.
