### ISSUE TITLE
GraphSAGE: Feature Request | Feature Instruction Required: Exploring the Feasibility of Implementing Asymmetric Node Feature Masking & Slicing 

### ISSUE THREAD

**Issue by zzh8241102** [dmlc/dgl#6131]
## 🚀 Feature

When implementing the aggregation step in GraphSAGE's SAGEConv, I encountered significant challenges in implementing asymmetric node feature masking and slicing.
## Motivation
The motivation behind exploring asymmetric node feature masking and slicing in GraphSAGE arises from an industrial trial aimed at mitigating feature leakage during training. Additional context and details regarding this motivation have been provided in the previous conversation.

## Alternatives
* Find a way to work with existing codebase.

## Pitch
* Instructions for Implementation: instructions and guidelines on how to implement the desired feature masking and slicing functionality within the existing GraphSAGE framework.
* New API Development: If implementing the desired functionality proves to be challenging or impractical within the current framework, DGL (Deep Graph Library) can consider developing a new API specifically designed to handle asymmetric node feature masking and slicing. This new API would provide a more streamlined and intuitive approach for users to incorporate these features into their GraphSAGE models.

## Additional context
* **Here I pushed on the forum**
* [Additional context for this.issue](https://discuss.dgl.ai/t/very-intriguing-trial-graphsage-feature-request-feature-instruction-exploring-the-feasibility-of-implementing-asymmetric-node-feature-masking-slicing/3908) which is very Exhaustive！

**Comment by BarclayII** [comment]
I'll close this issue as the discussion is ongoing in the [referred discussion forum post](https://discuss.dgl.ai/t/very-intriguing-trial-graphsage-feature-request-feature-instruction-exploring-the-feasibility-of-implementing-asymmetric-node-feature-masking-slicing/3908)
