### ISSUE TITLE
How do I use DGL with Neo4j?

### ISSUE THREAD

**Issue by lmegha** [dmlc/dgl#615]
## ❓ Questions and Help

I am trying to using the DGL library with a Neo4j Database, and I'm really struggling in understanding how do I get the Neo4j graph into a DGL graph in order to use the libraries capabilities. Any help would be great.

**Comment by VoVAllen** [comment]
How big is your graph and is it dynamic (changed over time)?  We want to support various i/o method, but doesn't have any plan yet. It would be helpful for us if you could provide more information about your scenario. Thanks!

**Comment by zheng-da** [comment]
@lmegha With the current implementation of DGL, you could export the entire graph in Neo4j into NetworkX format and load it to DGL if your graph isn't very large. Otherwise, you may consider export the graph structure into scipy sparse matrix and export node data and edge data into numpy tensors, and load them into DGL. This solution should be able to handle fairly large graphs.

We do have plans to standardize DGL data format and have better interaction with other graph databases better. We'll keep you updated.

**Comment by lmegha** [comment]
Hello, Thanks for the prompt response. My Neo4j graph consists of almost a million nodes/relationships. And yes the graph is dynamic. The networks approach had not been working too well for me. Are there any examples in your documentation where you’ve talked about how to load large graphs as scipy sparse matrices?

**Comment by jermainewang** [comment]
Yes, we support conversion from scipy sparse matrix to DGLGraph if your graph is readonly.
```python
>>> import dgl
>>> import scipy as sp
>>> m = sp.sparse.random(100, 100, density=0.1, format='csr')
>>> g= dgl.DGLGraph(m, readonly=True)
>>> g.number_of_nodes()
100
>>> g.number_of_edges()
1000
```
In our v0.3 release (very soon, final wrap up), the above conversion is very efficient. You could wait for a couple of days or build from source using our master branch.

**Comment by lmegha** [comment]
Thank you so much, this was really helpful! Appreciate it.

**Comment by xwasco** [comment]
> @lmegha With the current implementation of DGL, you could export the entire graph in Neo4j into NetworkX format and load it to DGL if your graph isn't very large. Otherwise, you may consider export the graph structure into scipy sparse matrix and export node data and edge data into numpy tensors, and load them into DGL. This solution should be able to handle fairly large graphs.
> 
> We do have plans to standardize DGL data format and have better interaction with other graph databases better. We'll keep you updated.

Hi, which other databases are supported? sorry, but I can't find the answer in the documentation :) 

Thanks a lot!
