### ISSUE TITLE
Allow specification of cu118 build in conda `environment.yml` files.

### ISSUE THREAD

**Issue by CarlinLiao** [dmlc/dgl#6160]
## 🚀 Feature
Allow users to specify the cudatoolkit 11.8 build of DGL in conda `environment.yml` files.

## Motivation

More consistent environment replication when working with DGL on CUDA-compatible hardware.

## Alternatives

* Add `dgl-cuda11.8` channel to conda package manager.
* Emulate `pytorch` and create a [`dgl-cuda` metapackage](https://anaconda.org/pytorch/pytorch-cuda) where the version number corresponds to the CUDA version, not the DGL/pytorch version.
* Identify some way to specify installation of only `dgl` versions tagged `cu118` instead of having to use a separate conda package.

## Pitch

I would like some way to specify in `environment.yml` files I write and use to fetch the cudatoolkit 11.8 build of DGL.

## Additional context

Present, nonfunctioning `environment.yml` snippet:
```
channels:
  - defaults
dependencies:
  - dglteam::dgl-cuda11.8
  - nvidia::cuda-toolkit=11.8
  - pytorch::pytorch-cuda=11.8
```
Error thrown by conda
```
ResolvePackageNotFound: 
  - dglteam::dgl-cuda11.8
```
Error is not thrown if version numbers are bumped down to 11.7, or if `dgl-cuda11.8` is replaced with `dgl`. In the latter case, however, a non-coda build of DGL is installed.

**Comment by CarlinLiao** [comment]
I've been looking around but I've been unable to find a way to specify labels in `environment.yml`.

**Comment by BarclayII** [comment]
A late response but here is what I got from `conda env export`:
```yaml
name: base
channels:
  - dglteam/label/cu117
  - defaults
dependencies:
  - dgl
```

**Comment by CarlinLiao** [comment]
Thanks @BarclayII, that works.
