### ISSUE TITLE
How to save the attention weight in official Hgt model example

### ISSUE THREAD

**Issue by EverOasis** [dmlc/dgl#6181]
I’ve successfully train the hgt model on my dataset, but haven’t figured out how to save the attention weights and updated node features from the official hgt model tutorials

**Comment by Rhett-Ying** [comment]
duplicate with https://discuss.dgl.ai/t/how-to-save-the-attention-weight-in-official-hgt-model-example/3937

**Comment by czkkkkkk** [comment]
Hi @EverOasis , I am closing this issue assuming you are happy about our response. Feel free to follow up and reopen the issue if you have more questions with regard to our response.
