### ISSUE TITLE
Stochastic Training on official hgt example 

### ISSUE THREAD

**Issue by EverOasis** [dmlc/dgl#6219]
How to Use Neighborhood Sampling Approach on official hgt example

**Comment by jermainewang** [comment]
For general questions, I suggest posting them to our discuss forum (discuss.dgl.ai) to keep the issue tracker cleaner. Thanks!

Have you checked our tutorial/doc on neighbor sampling on heterogeneous graph? Also, the official example [here](https://github.com/dmlc/dgl/blob/master/examples/core/rgcn/hetero_rgcn.py) is also using neighbor sampling on heterogeneous graph.

**Comment by jermainewang** [comment]
Hi @EverOasis , I am closing this issue assuming you are happy about our response. Feel free to follow up and reopen the issue if you have more questions with regard to our response.
