### ISSUE TITLE
403 status code

### ISSUE THREAD

**Issue by hmliangliang** [dmlc/dgl#6248]
## 📚 Documentation
The request to access [docs.dgl.ai](http://docs.dgl.ai/) was denied, and it returned a 403 status code. Could the official team consider releasing a PDF document that provides comprehensive API information to prevent users from connecting to the page for extended periods of time? This way, developers do not need to access the document page for long periods of time.

**Comment by jermainewang** [comment]
Cannot reproduce the issue. In terms of PDF documentation, I agree there are merits in releasing a downloadable version. However, there are a couple of technical difficulties in this:

1. The current API doc uses various plugins to properly render math, codes and links. Many of them will be broken when converted to PDF.
2. We are still actively updating our document to fix inaccurate or mistaken information. I think keeping our document up-to-date is still more important at the current stage of the project.

That is said, if we received more and more report of connection issue, we will try our best to resolve that directly. So, if you could share more details such as your IP location, the period of time that you encounter connection issues, etc., these will be really helpful.

**Comment by hmliangliang** [comment]
> Cannot reproduce the issue. In terms of PDF documentation, I agree there are merits in releasing a downloadable version. However, there are a couple of technical difficulties in this:
> 
> 1. The current API doc uses various plugins to properly render math, codes and links. Many of them will be broken when converted to PDF.
> 2. We are still actively updating our document to fix inaccurate or mistaken information. I think keeping our document up-to-date is still more important at the current stage of the project.
> 
> That is said, if we received more and more report of connection issue, we will try our best to resolve that directly. So, if you could share more details such as your IP location, the period of time that you encounter connection issues, etc., these will be really helpful.

I am now able to access the document page normally after clearing the DNS cache of my local host. Thank you.
