### ISSUE TITLE
Does DGL have an explicit dependency on `packaging` library?

### ISSUE THREAD

**Issue by thvasilo** [dmlc/dgl#6258]
## 🐛 Bug

I was trying to use Poetry+pip to create a DGL environment and ran into an unexpected problem: seems like DGL might have a dependency on the `packaging` library but it's not explicitly listed as a dep? 

Unfortunately I wasn't able to get DGL to be installed with `poetry` so I resorted to adding all my other deps (torch, numpy etc.) using Poetry, and installing DGL using `pip install dgl -f "https://data.dgl.ai/wheels/repo.html"`

## To Reproduce

1. Create an env using `poetry` using a pyproject.toml with deps like:
```toml
[tool.poetry.dependencies]
python = "^3.8"
torch = "^2.0.1"
numpy = ">=1.20.2"
```
2. Do `poetry install && poetry shell`
3. `pip install dgl -f "https://data.dgl.ai/wheels/repo.html`
4. python -c 'import dgl'

```
>>> import dgl
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "redactedlib/python3.8/site-packages/dgl/__init__.py", line 16, in <module>
    from . import (
  File "redactedlib/python3.8/site-packages/dgl/dataloading/__init__.py", line 4, in <module>
    from .base import *
  File "redactedlib/python3.8/site-packages/dgl/dataloading/base.py", line 9, in <module>
    from ..transforms import compact_graphs
  File "redactedlib/python3.8/site-packages/dgl/transforms/__init__.py", line 2, in <module>
    from .functional import *
  File "redactedlib/python3.8/site-packages/dgl/transforms/functional.py", line 25, in <module>
    from packaging.version import Version
ModuleNotFoundError: No module named 'packaging'
```

## Expected behavior

If `packaging` is an explicit dependency of DGL, it should be installed when I do `pip install` right?

## Environment

 - DGL Version (e.g., 1.0): 1.1.2
 - Backend Library & Version (e.g., PyTorch 0.4.1, MXNet/Gluon 1.3):
 - OS (e.g., Linux): MacOS
 - How you installed DGL (`conda`, `pip`, source): `pip`
 - Build command you used (if compiling from source):
 - Python version: 3.8
 - CUDA/cuDNN version (if applicable):
 - GPU models and configuration (e.g. V100):
 - Any other relevant information:

**Comment by yaox12** [comment]
Thanks for reporting the issue. I pushed a PR to fix it.
