### ISSUE TITLE
How to install DGL 0.9 version

### ISSUE THREAD

**Issue by Chrisa142857** [dmlc/dgl#6267]
## ❓ Questions and Help

I was trying to reproduce codes using dgl==0.9, but I can't find a way to install this version.

I have downloaded the source code of 0.9.1, but I'm totally lost in that code according to the current doc.

Please show me a way how to install 0.9.1 with GPU, CUDA==11.7, Ubuntu 20.04. Thank you.

**Comment by rudongyu** [comment]
Hi, there is a step-to-step guide on this page for installing from source: https://docs.dgl.ai/en/0.9.x/install/index.html.
Could you elaborate on more specific difficulties you have encountered? (e.g., error messages)

**Comment by zerzerzerz** [comment]
```bash
pip install dgl_cu117==0.9.1 -f https://data.dgl.ai/wheels/repo.html
```
All `.whl` files for previous DGL (cpu version + CUDA version) are included [https://data.dgl.ai/wheels/repo.html](https://data.dgl.ai/wheels/repo.html)
