### ISSUE TITLE
Is there a graphGPS implement of DGL library available？

### ISSUE THREAD

**Issue by wuyuhui-zju** [dmlc/dgl#6278]
Hello, does DGL provide encapsulated graph transformer models? Such as graphGPS, thank you!

**Comment by paoxiaode** [comment]
We have implemented GraphGPS model under DGL based on the official GraphGPS code, but the code is not yet publicly available and needs a few days to be organized, I'll let you know when the code becomes public.

**Comment by paoxiaode** [comment]
The GraphGPS model code is here: https://github.com/paoxiaode/GraphGPS_DGL

**Comment by wuyuhui-zju** [comment]
> The GraphGPS model code is here: https://github.com/paoxiaode/GraphGPS_DGL

Thank you very much for your sharing
