### ISSUE TITLE
Release 1.1.2 on windows not found on repo

### ISSUE THREAD

**Issue by trin1t** [dmlc/dgl#6286]
I found that installation statements from website could not lead to cuda versions installation. 
`pip install  dgl -f https://data.dgl.ai/wheels/cu118/repo.html`
File [dgl-1.1.2+cu118-cp311-cp311-win_amd64.whl](https://data.dgl.ai/wheels/dgl-1.1.2%2Bcu118-cp311-cp311-win_amd64.whl) is not on [here](https://data.dgl.ai/wheels/cu118/repo.html). Please check whether this is expected.

**Comment by Rhett-Ying** [comment]
@trin1t https://data.dgl.ai/wheels/cu118/repo.html is updated. please try it out.
