### ISSUE TITLE
DGL cu118 does not work on Windows GPU

### ISSUE THREAD

**Issue by jayurbain** [dmlc/dgl#6320]
## 🐛 Bug

DGL cu118 does not work on Windows GPU

Download page: https://www.dgl.ai/pages/start.html

## To Reproduce
Install the following on Linux.
pip install  dgl -f https://data.dgl.ai/wheels/cu118/repo.html
pip install  dglgo -f https://data.dgl.ai/wheels-test/repo.html

Check install:  
$ conda list
torch                     2.0.1+cu118              pypi_0    pypi
...
dgl                       1.1.2+cu118              pypi_0    pypi

Everything works Ok.

Now, Install the following on Windows: 

pip install  dgl -f https://data.dgl.ai/wheels/cu118/repo.html
pip install  dglgo -f https://data.dgl.ai/wheels-test/repo.html

Check install:  
$ conda list
torch                     2.0.1+cu118              pypi_0    pypi
...
dgl                       1.1.2                           pypi_0    pypi <-- CUDA not listed

Note: Pytorch does see the GPU:

But DLG errors out.

`
Python 3.11.4 | packaged by Anaconda, Inc. | (main, Jul  5 2023, 13:47:18) [MSC v.1916 64 bit (AMD64)] on win32
Type "help", "copyright", "credits" or "license" for more information.
>>> import torch
>>> torch.__version__
'2.0.1+cu118'
>>> import dgl
>>> dgl.__version__
'1.1.2'
>>> import torch as th
>>> u, v = th.tensor([0, 1, 2]), th.tensor([2, 3, 4])
>>>
>>> g = dgl.graph((u, v))
>>> g.ndata['x'] = th.randn(5, 3)  # original feature is on CPU
>>> g.device
device(type='cpu')
>>> cuda_g = [g.to](http://g.to/)('cuda:0')  # accepts any device objects from backend framework
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "C:\Users\jayurb\.conda\envs\ups-ds\Lib\site-packages\dgl\heterograph.py", line 5709, in to
    ret._graph = self._graph.copy_to(utils.to_dgl_context(device))
                 ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\jayurb\.conda\envs\ups-ds\Lib\site-packages\dgl\heterograph_index.py", line 255, in copy_to
    return _CAPI_DGLHeteroCopyTo(self, ctx.device_type, ctx.device_id)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\jayurb\.conda\envs\ups-ds\Lib\site-packages\dgl\_ffi\_ctypes\function.py", line 212, in __call__
    check_call(
  File "C:\Users\jayurb\.conda\envs\ups-ds\Lib\site-packages\dgl\_ffi\base.py", line 70, in check_call
    raise DGLError(py_str(_LIB.DGLGetLastError()))
dgl._ffi.base.DGLError: [12:42:59] C:\Users\Administrator\DGL_scripts\release\win-64\dgl\src\runtime\c_runtime_api.cc:82: Check failed: allow_missing: Device API cuda is not enabled. Please install the cuda version of dgl.`
`

**Comment by peizhou001** [comment]
Hi @jayurbain, I follow your steps but can't reproduce in my PC
<img width="467" alt="138d81ba68ef72824782d3060615394" src="https://github.com/dmlc/dgl/assets/110809584/07f5ab61-c039-452d-b239-9da5864ac77a">
Could you try to reinstall the dgl and torch or provide more details?

**Comment by jayurbain** [comment]
I just reinstalled everything and it's now working. Trust me, I tried this several times before. Thanks for your help.
