### ISSUE TITLE
Install package according to official website gude leading to version mistake

### ISSUE THREAD

**Issue by ZionDoki** [dmlc/dgl#6343]
## 🐛 Bug

I want to install `dgl` cpu version on windows 11, but using official guide install by `pip install  dgl -f https://data.dgl.ai/wheels/repo.html` causing the wrong version to be installed.

```
> pip install  dgl -f https://data.dgl.ai/wheels/repo.html 
Looking in links: https://data.dgl.ai/wheels/repo.html
Collecting dgl
  Using cached https://data.dgl.ai/wheels/dgl-1.1.2%2Bcu118-cp311-cp311-win_amd64.whl (80.0 MB)
Requirement already satisfied: numpy>=1.14.0 in c:\users\xxx\appdata\local\programs\python\python311\lib\site-packages (from dgl) (1.24.4)
Requirement already satisfied: scipy>=1.1.0 in c:\users\xxx\appdata\local\programs\python\python311\lib\site-packages (from dgl) (1.11.1)
Requirement already satisfied: networkx>=2.1 in c:\users\xxx\appdata\local\programs\python\python311\lib\site-packages (from dgl) (3.1)
Requirement already satisfied: requests>=2.19.0 in c:\users\xxx\appdata\local\programs\python\python311\lib\site-packages (from dgl) (2.31.0)
Requirement already satisfied: tqdm in c:\users\xxx\appdata\local\programs\python\python311\lib\site-packages (from dgl) (4.65.0)
Requirement already satisfied: psutil>=5.8.0 in c:\users\xxx\appdata\local\programs\python\python311\lib\site-packages (from dgl) (5.9.5)
Requirement already satisfied: charset-normalizer<4,>=2 in c:\users\xxx\appdata\local\programs\python\python311\lib\site-packages (from requests>=2.19.0->dgl) (3.2.0)
Requirement already satisfied: idna<4,>=2.5 in c:\users\xxx\appdata\local\programs\python\python311\lib\site-packages (from requests>=2.19.0->dgl) (3.4)
Requirement already satisfied: urllib3<3,>=1.21.1 in c:\users\xxx\appdata\local\programs\python\python311\lib\site-packages (from requests>=2.19.0->dgl) (1.26.16)
Requirement already satisfied: certifi>=2017.4.17 in c:\users\xxx\appdata\local\programs\python\python311\lib\site-packages (from requests>=2.19.0->dgl) (2023.5.7)
Requirement already satisfied: colorama in c:\users\xxx\appdata\local\programs\python\python311\lib\site-packages (from tqdm->dgl) (0.4.6)
Installing collected packages: dgl
Successfully installed dgl-1.1.2+cu118
```

Obviously, I need dgl-1.1.2 not dgl-1.1.2+cu118 package, and which will lead to `dgl.dll` can not found error.

I simply uninstall the wrong package and reinstall using `pip install dgl` solved the question. Hopefully this is just a problem caused by my own environment.

## Environment

 - DGL Version (e.g., 1.0): 1.1.2
 - Backend Library & Version (e.g., PyTorch 0.4.1, MXNet/Gluon 1.3): PyTorch 2.0.1
 - OS (e.g., Linux): Windows 11
 - How you installed DGL (`conda`, `pip`, source): `pip install  dgl -f https://data.dgl.ai/wheels/repo.html `
 - Build command you used (if compiling from source): 
 - Python version: 3.11.4
 - CUDA/cuDNN version (if applicable): 
 - GPU models and configuration (e.g. V100):
 - Any other relevant information: CPU version

**Comment by czkkkkkk** [comment]
@ZionDoki, thanks for reporting this issue! We will fix it soon.

**Comment by czkkkkkk** [comment]
`pip install  dgl -f https://data.dgl.ai/wheels/repo.html` should work as expected now.

**Comment by czkkkkkk** [comment]
Hi @ZionDoki , I am closing this issue assuming you are happy about our response. Feel free to follow up and reopen the issue if you have more questions with regard to our response.
