### ISSUE TITLE
If I want to use dgl with hdfs, does the server with dgl installed must be used as the DataNode of the hadoop cluster?

### ISSUE THREAD

**Issue by youngeryoungeryang** [dmlc/dgl#6377]
hi,

I want to make dgl load data from hdfs cluster. To achieve this, I change the parameters in the makefile of dgl as below:
 ' USE_HDFS=ON, MLC_HDFS_SHARED=ON, DMLC_HDFS_SHARED=ON, HDFS_SHARED=ON '.

When I compile dgl again, there are some problems:
![image](https://github.com/dmlc/dgl/assets/45582966/fc2b502b-e40a-4710-8e10-fd11610732fb)
I now have a GPU server with dgl installed and a hadoop cluster consisting of three CPU servers. In my vision the GPU server is only used as a client to the Hadoop server, accessing hdfs files through a Python package called hdfs, so it does not install hadoop.

I would like to ask if I want to use dgl with hdfs, do I have to install hdfs from source on the GPU server and join the GPU server to the existing hadoop cluster? If not, how to make it find the hdfs includes and libraries?

Thank you very much!

**Comment by frozenbugs** [comment]
Hi @youngeryoungeryang , Can you tell us more about what do you want to achieve so that we can give you better advice?
- Are you plan to run dataloader on your CPU servers and run the training on GPU server?
- Are you plan to run both dataloader and training on one node and fetch feature data from hdfs?
- Are you plan to run dataloader to sample graph topology stored on hdfs and then training on GPU server?
- Or more.

**Comment by youngeryoungeryang** [comment]
Hi @frozenbugs , I plan to sample neighbors and  construct subgraphs on the CPU servers that make up the Hadoop cluster, and send the subgraphs to the GPU server through network, then train them on the GPU server.

**Comment by jermainewang** [comment]
Hi @youngeryoungeryang , we inherit this USE_HDFS flag from dmlc-core https://github.com/dmlc/dmlc-core/blob/main/cmake/Modules/FindHDFS.cmake but have not formally tested it. In another word, this is not an official feature of DGL. My suggestion is to load data from HDFS using other packages before calling DGL.

**Comment by youngeryoungeryang** [comment]
Ok, I got it. Thank you for your help.



---Original---
From: "Minjie ***@***.***&gt;
Date: Sun, Oct 8, 2023 07:23 AM
To: ***@***.***&gt;;
Cc: ***@***.******@***.***&gt;;
Subject: Re: [dmlc/dgl] If I want to use dgl with hdfs, does the server withdgl installed must be used as the DataNode of the hadoop cluster? (Issue#6377)




 
Hi @youngeryoungeryang , we inherit this USE_HDFS flag from dmlc-core https://github.com/dmlc/dmlc-core/blob/main/cmake/Modules/FindHDFS.cmake but have not formally tested it. In another word, this is not an official feature of DGL. My suggestion is to load data from HDFS using other packages before calling DGL.
