### ISSUE TITLE
Incorrect Incident Matrix Shape for Hypergraph Example

### ISSUE THREAD

**Issue by osintalex** [dmlc/dgl#6379]
## 📚 Documentation

Tutorial part

It's possible I've misunderstood, but I'm not sure the documentation is correct here https://docs.dgl.ai/notebooks/sparse/hgnn.html?highlight=hypergraph. 

It says:

> For example, the hypergraph in the figure above can be characterized by a 11×5 matrix as follows:

An 11 x 5 incidence matrix, as I understand it, would characterize a graph with 5 hyperedges and 11 vertices.  I am fairly new to this so going off this quite helpful site https://www.lancaster.ac.uk/stor-i-student-sites/katie-howgate/2021/04/29/hypergraphs-not-just-a-cool-name/.

However in your documentation, the graph in the figure has 4 vertices and one hyper edge.

**Comment by BarclayII** [comment]
The said image seems to have a wrong URL.  In the source notebook (https://github.com/dmlc/dgl/blob/master/notebooks/sparse/hgnn.ipynb) the image looks like this:
![](https://data.dgl.ai/tutorial/img/hgnn/hypergraph4.PNG)
and the URL is https://data.dgl.ai/tutorial/img/hgnn/hypergraph4.PNG.  However, in the rendered HTML page the URL seems to be https://data.dgl.ai/tutorial/img/hgnn/equiv.PNG, which is the same figure below.

@frozenbugs Do you know how our notebooks are converted to docs?  This seems really weird.
