### ISSUE TITLE
Installation of the version that includes PGExplainer

### ISSUE THREAD

**Issue by kiymetkaya** [dmlc/dgl#6382]
## ❓ Questions and Help
Hello,

I want to use the PGExplainer method in the latest version. 
https://docs.dgl.ai/en/latest/generated/dgl.nn.pytorch.explain.PGExplainer.html?highlight=pgexplainer

Since the release of the latest version has not been done yet, I tried to install it by following the steps in the link below.
https://docs.dgl.ai/en/latest/install/index.html

Below is the error I got:
```bash
-- Build files have been written to: /home/kiymet/Documents/pyod-test/dgl/dgl_sparse/build/1.13.0
Scanning dependencies of target dgl_sparse_pytorch_1.13.0
[  7%] Building CXX object CMakeFiles/dgl_sparse_pytorch_1.13.0.dir/src/cpu/matrix_ops_impl.cc.o
[ 14%] Building CXX object CMakeFiles/dgl_sparse_pytorch_1.13.0.dir/src/elemenwise_op.cc.o
[ 21%] Building CXX object CMakeFiles/dgl_sparse_pytorch_1.13.0.dir/src/matmul.cc.o
[ 28%] Building CXX object CMakeFiles/dgl_sparse_pytorch_1.13.0.dir/src/matrix_ops.cc.o
[ 35%] Building CXX object CMakeFiles/dgl_sparse_pytorch_1.13.0.dir/src/python_binding.cc.o
[ 42%] Building CXX object CMakeFiles/dgl_sparse_pytorch_1.13.0.dir/src/reduction.cc.o
[ 50%] Building CXX object CMakeFiles/dgl_sparse_pytorch_1.13.0.dir/src/sddmm.cc.o
[ 57%] Building CXX object CMakeFiles/dgl_sparse_pytorch_1.13.0.dir/src/softmax.cc.o
[ 64%] Building CXX object CMakeFiles/dgl_sparse_pytorch_1.13.0.dir/src/sparse_format.cc.o
[ 71%] Building CXX object CMakeFiles/dgl_sparse_pytorch_1.13.0.dir/src/sparse_matrix.cc.o
[ 78%] Building CXX object CMakeFiles/dgl_sparse_pytorch_1.13.0.dir/src/sparse_matrix_coalesce.cc.o
[ 85%] Building CXX object CMakeFiles/dgl_sparse_pytorch_1.13.0.dir/src/spmm.cc.o
[ 92%] Building CXX object CMakeFiles/dgl_sparse_pytorch_1.13.0.dir/src/spspmm.cc.o
[100%] Linking CXX executable runUnitTests
[100%] Built target runUnitTests
/home/kiymet/Documents/pyod-test/dgl/dgl_sparse/src/matrix_ops.cc: In function ‘std::tuple<c10::intrusive_ptr<dgl::sparse::SparseMatrix, c10::detail::intrusive_target_default_null_type<dgl::sparse::SparseMatrix> >, at::Tensor> dgl::sparse::Compact(const c10::intrusive_ptr<dgl::sparse::SparseMatrix>&, uint64_t, at::Tensor)’:
/home/kiymet/Documents/pyod-test/dgl/dgl_sparse/src/matrix_ops.cc:67:1: warning: control reaches end of non-void function [-Wreturn-type]
   67 | }
      | ^
[100%] Linking CXX shared library libdgl_sparse_pytorch_1.13.0.so
[100%] Built target dgl_sparse_pytorch_1.13.0
'libdgl_sparse_pytorch_1.13.0.so' -> '/home/kiymet/Documents/pyod-test/dgl/build/dgl_sparse/libdgl_sparse_pytorch_1.13.0.so'
[100%] Built target dgl_sparse
```

I also checked the https://discuss.dgl.ai/ website as suggested, but I could not find an example with a similar problem.

Do you mind sharing the release date of the next version (which includes the PGExplainer)? 
I could install the latest pip version which does not include PGExplainer (1.1.2).
Until then, what steps should I follow to be able to use PGExplainer?
Thanks in advance.

**Comment by frozenbugs** [comment]
Hi @kiymetkaya , we plan to release dgl 2.0 in late this year ~Dec. We don't have plan for minor version yet, but we may do it in Nov if we need major update from dgl's dependency.

Meanwhile, from your log, I think you've successfully build dgl, there are no error but a warning related to our ongoing feature, which can be ignored.

**Comment by frozenbugs** [comment]
Hi @kiymetkaya , I am closing this issue assuming you are happy about our response. Feel free to follow up and reopen the issue if you have more questions with regard to our response.
