### ISSUE TITLE
dgl.seed(seed) error

### ISSUE THREAD

**Issue by 962673247** [dmlc/dgl#6403]
My Pytorch version is 1.13.0 and Cuda version is 11.7. During the coding process, I found that the model training results were inconsistent and could not reproduce the results. Therefore, I wanted to set dgl. seed, but an error occurred and I would like to inquire about a solution
Traceback (most recent call last):
File "/home/gnn/zjz/test/学长的代码测试/run.py", line 200, in
main(**d)
File "/home/gnn/zjz/test/学长的代码测试/run.py", line 81, in main
dgl.seed(seed)
File "/home/gnn/miniconda3/envs/zjz_graph_dgl/lib/python3.10/site-packages/dgl/random.py", line 19, in seed
_CAPI_SetSeed(val)
File "dgl/_ffi/_cython/./function.pxi", line 295, in dgl._ffi._cy3.core.FunctionBase.call
File "dgl/_ffi/_cython/./function.pxi", line 227, in dgl._ffi._cy3.core.FuncCall
File "dgl/_ffi/_cython/./function.pxi", line 217, in dgl._ffi._cy3.core.FuncCall3
dgl._ffi.base.DGLError: [20:55:36] /opt/dgl/src/random/random.cc:36: Check failed: e == CURAND_STATUS_SUCCESS: CURAND Error: CURAND_STATUS_INITIALIZATION_FAILED at /opt/dgl/src/random/random.cc:36
Stack trace:
[bt] (0) /home/gnn/miniconda3/envs/zjz_graph_dgl/lib/python3.10/site-packages/dgl/libdgl.so(dmlc::LogMessageFatal::~LogMessageFatal()+0x4f) [0x7f1cb6da71ef]
[bt] (1) /home/gnn/miniconda3/envs/zjz_graph_dgl/lib/python3.10/site-packages/dgl/libdgl.so(+0x6ad666) [0x7f1cb70ad666]
[bt] (2) /home/gnn/miniconda3/envs/zjz_graph_dgl/lib/python3.10/site-packages/dgl/libdgl.so(DGLFuncCall+0x48) [0x7f1cb70bad38]
[bt] (3) /home/gnn/miniconda3/envs/zjz_graph_dgl/lib/python3.10/site-packages/dgl/_ffi/_cy3/core.cpython-310-x86_64-linux-gnu.so(+0x160eb) [0x7f1cf1b550eb]
[bt] (4) /home/gnn/miniconda3/envs/zjz_graph_dgl/lib/python3.10/site-packages/dgl/_ffi/_cy3/core.cpython-310-x86_64-linux-gnu.so(+0x165cb) [0x7f1cf1b555cb]
[bt] (5) python(_PyObject_MakeTpCall+0x25b) [0x4f9d9b]
[bt] (6) python(_PyEval_EvalFrameDefault+0x4deb) [0x4f583b]
[bt] (7) python(_PyFunction_Vectorcall+0x6f) [0x500b2f]
[bt] (8) python(_PyEval_EvalFrameDefault+0x4b2b) [0x4f557b]

**Comment by jermainewang** [comment]
For bug report, could you follow the bug report template so we can know more about your hardware/software configs? Also, to better assist you, could you also provide a minimal reproducible example? Thanks.

**Comment by czkkkkkk** [comment]
Hi @962673247 , I am closing this issue assuming you are happy about our response. Feel free to follow up and reopen the issue if you have more questions with regard to our response.
