### ISSUE TITLE
More general segment_mm

### ISSUE THREAD

**Issue by wzm2256** [dmlc/dgl#6408]
## 🚀 Feature
In the current version, dgl.ops.segment_mm requires the second input to have the same shape, this can be further generalized by adding a scatter operation to the second input:
``
dgl.ops.segment_mm(a, b, seglen_a, seglen_b, full=False)
``

####Parameters
- a (Tensor) – The left operand, 2-D tensor of shape (N, D1)
- b (Tensor) – The right operand, 3-D tensor of shape (D1, M)
- seglen_a (Tensor) – An integer tensor of shape (R,). Each element is the length of segments of input a. The summation of all elements must be equal to N.
- seglen_b (Tensor) – An integer tensor of shape (R,). Each element is the length of segments of input b. The summation of all elements must be equal to M. 
- full (Bool) - Set to True to compute all $R^2$ pairwise matrix mutiplication, otherwise compute $R$ matrix mutiplications.

**(For compability, if seglen_b is set to None, the function becomes the current function.)**

#### Output
The output matrix of shape (N, M). If full == False, output is a block diagnal sparse matrix with R blocks. If full == True, the output is a dense matrix.

#### Example
Let seglen_a == [2, 4], seglen_b == [3, 1], if full=True, then 4 matrix multiplication will be computed, and the result will be arranged in a  $N \times M$ matrix:
|  |  | 
|---|---|
| a[0:2] @ b[:, 0:3] | a[0:2] @ b[:, 3:4] | 
|  a[2:6] @ b[:, 0:3] | a[2:6] @ b[:, 3:4]  | 

if full=False, then 2 matrix multiplication will be computed, and the result will be arranged in a  $N \times M$ sparse matrix:
|  |  | 
|---|---|
| a[0:2] @ b[:, 0:3] |0 | 
|  0 | a[2:6] @ b[:, 3:4]  | 

When full == False and seglen_b == None, then the input to the old API is converted as:
``
new_b = einops.rearrange(old_b, 'e c d -> c (e d) ')
``
This can be done inside the function.

## Motivation
This function can be understand as a step toward the block multiplication of matrix where each block has different shape. I have searched the internet for several days, and I found this function is closest to this idea. Another possible approach is to use sparse matrix multiplication, but unfortunately, that is not solved yet
https://github.com/pytorch/pytorch/issues/31942

## Additional context
Batch dimension is also needed, but I guess that can be done using the vmap function in Pytorch.

**Comment by wzm2256** [comment]
I will try to work on this feature, but I have never written any cuda code before, so please do not count on me...

**Comment by wzm2256** [comment]
Another related function (may be incoporated into this function) is 
``
dgl.ops.segment_mm(a, b, seglen_ab=None)
``

####Parameters
- a (Tensor) – The left operand, 2-D tensor of shape (D1, N)
- b (Tensor) – The right operand, 3-D tensor of shape (N, D2)
- seglen_a (Tensor) – An integer tensor of shape (R,). Each element is the length of segments of input a. The summation of all elements must be equal to N.

#### Output
The output matrix of shape (R, D1, D2). 


#### Example
Let seglen_ab == [2, 4], 2 matrix multiplications will be computed:
a[:, 0:2] @ b[0:2, :]  and a[:, 4:6] @ b[4:6, :]
The result of each of this mutiplication has shape (D1, D2), and they will be stacked in dim 0 to produce output of shape (2, D1, D2)

**Comment by BarclayII** [comment]
The operator `segment_mm` is primarily used for projecting heterogeneous node/edge features with type-specific weight matrices.  What is the use case of your generalized operator and how common is it?  I don't see an immediate application.

If this is only tailored for a specific application, I would suggest you to write your own PyTorch operator outside DGL.

**Comment by wzm2256** [comment]
I figured you are right, maybe I should put it as a stand alone code. I now close this feature request.
