### ISSUE TITLE
[Bug] PyTorch Example `transformer/` failed due to data server down and others

### ISSUE THREAD

**Issue by chang-l** [dmlc/dgl#6455]
## 🐛 Bug

It seems this example https://github.com/dmlc/dgl/tree/master/examples/pytorch/transformer is no longer working... Can someone please take a look?

## To Reproduce

Crash # 1
- `python3 ${EXAMPLE_DIR}/translation_train.py --gpus 0 --N 2`

Output:
```
Resolving www.quest.dcs.shef.ac.uk (www.quest.dcs.shef.ac.uk)... 143.167.8.76
Connecting to www.quest.dcs.shef.ac.uk (www.quest.dcs.shef.ac.uk)|143.167.8.76|:80... failed: Connection timed out.
Retrying.
...
Giving up.
```
Crash # 2
- `python3 ${EXAMPLE_DIR}/translation_train.py --gpus 0 --N 2 --dataset wmt14`

Output:
```
Traceback (most recent call last):
  File "/workspace/examples/transformer/translation_train.py", line 226, in <module>
    main(devices[0], args)
  File "/workspace/examples/transformer/translation_train.py", line 126, in main
    run_epoch(
  File "/workspace/examples/transformer/translation_train.py", line 19, in run_epoch
    for i, g in enumerate(data_iter):
  File "/opt/dgl/dgl-source/examples/pytorch/transformer/dataset/__init__.py", line 166, in __call__
    tgt_sample = self.tgt_field(tgt_data[idx].strip().split())
  File "/opt/dgl/dgl-source/examples/pytorch/transformer/dataset/fields.py", line 60, in __call__
    return self.postprocess(self.numericalize(self.preprocess(x)))
  File "/opt/dgl/dgl-source/examples/pytorch/transformer/dataset/fields.py", line 57, in numericalize
    return [self.vocab[token] for token in x]
  File "/opt/dgl/dgl-source/examples/pytorch/transformer/dataset/fields.py", line 57, in <listcomp>
    return [self.vocab[token] for token in x]
  File "/opt/dgl/dgl-source/examples/pytorch/transformer/dataset/fields.py", line 35, in __getitem__
    return self.vocab_dict[self.unk_token]
KeyError: None
```

## Environment

 - DGL Version (e.g., 1.0): 1.1.2

**Comment by Rhett-Ying** [comment]
@chang-l As mentioned in the README, please refer to https://github.com/yzh119/bpt.

**Comment by chang-l** [comment]
Thanks @Rhett-Ying. You mean this example will not be maintained? Can we somehow port the better implementation to here to replace the outdated one?

**Comment by drivanov** [comment]
There appears to be a bug in the `multi-bleu.perl` script loaded by the  [get_dataset(...) method](https://github.com/dmlc/dgl/blob/master/examples/pytorch/transformer/dataset/__init__.py#L205) called from  [translation_train.py](https://github.com/dmlc/dgl/blob/master/examples/pytorch/transformer/translation_train.py#L74) 

Quite often I get the following error:
```
READING file: checkpoints/2-sort-False-2.pkl
Illegal division by zero at scripts/multi-bleu.perl line 154, <STDIN> line 1000.
```
This happens in the following snippet: 
```
if ($length_reference==0){
  printf "BLEU = 0, 0/0/0/0 (BP=0, ratio=0, hyp_len=0, ref_len=0)\n";
  exit(1);
}

if ($length_translation<$length_reference) {
  $brevity_penalty = exp(1-$length_reference/$length_translation);           <<========= It happens here
```

It looks like we should use `$length_translation` instead of `$length_reference` in this snippet:
```
if ($length_translation==0){
  printf "BLEU = 0, 0/0/0/0 (BP=0, ratio=0, hyp_len=0, ref_len=0)\n";
  exit(1);
}
```

**Comment by Rhett-Ying** [comment]
@rudongyu could you please look into the issue @drivanov pointed out?

**Comment by rudongyu** [comment]
> There appears to be a bug in the `multi-bleu.perl` script loaded by the [get_dataset(...) method](https://github.com/dmlc/dgl/blob/master/examples/pytorch/transformer/dataset/__init__.py#L205) called from [translation_train.py](https://github.com/dmlc/dgl/blob/master/examples/pytorch/transformer/translation_train.py#L74)
> 
> This script is called from [here](https://github.com/dmlc/dgl/blob/master/examples/pytorch/transformer/translation_test.py#L65) and quite often it gives the following error:
> 
> ```
> READING file: checkpoints/2-sort-False-2.pkl
> Illegal division by zero at scripts/multi-bleu.perl line 154, <STDIN> line 1000.
> ```
> 
> This happens in the following snippet:
> 
> ```
> if ($length_reference==0){
>   printf "BLEU = 0, 0/0/0/0 (BP=0, ratio=0, hyp_len=0, ref_len=0)\n";
>   exit(1);
> }
> 
> if ($length_translation<$length_reference) {
>   $brevity_penalty = exp(1-$length_reference/$length_translation);           <<========= It happens here
> ```
> 
> It looks like we should use `$length_translation` instead of `$length_reference` in this snippet:
> 
> ```
> if ($length_translation==0){
>   printf "BLEU = 0, 0/0/0/0 (BP=0, ratio=0, hyp_len=0, ref_len=0)\n";
>   exit(1);
> }
> ```

Hi, @drivanov. The script is from [moses](https://github.com/moses-smt/mosesdecoder/blob/master/scripts/generic/multi-bleu.perl) and widely used. The zero-division error in your case indicates that the model doesn't output anything. The check `$length_reference==0` is to avoid zero-division when computing ratio of lengths later. It maybe unnecessary to run the script if no model predictions are given, but for sure you can add the following block to avoid such error:
```perl
if ($length_translation==0){
  printf "NIL Hypothesis.";
  exit(1);
}
```
