### ISSUE TITLE
Cause an endless loop and high memory usage when use `list()` to wrap an object of HeteroNodeView

### ISSUE THREAD

**Issue by NormanZyq** [dmlc/dgl#6483]
## To Reproduce

1. Open a terminal with python activated, import dgl and create a random graph
2. Try to print `g.nodes` with `list()` wrapped
3. Endless loop and the result cannot pop out.

```python
import dgl

g = dgl.rand_graph(20, 30)
list(g.nodes)
```

## Expected behavior

I noticed that the output of `g.nodes` is something like <dgl.view.HeteroNodeView at 0x7fxxx> so I was trying to wrap it with `list()`. The expected output should be the node list, intuitively, just like `g.nodes()`. If it is not designed to be an iterable object, I think it's better to raise an error and tell me it is not iterable. However, it falls into an endless loop and there may also a memory leak? 

<img width="1216" alt="iShot_2023-10-23_10 19 50" src="https://github.com/dmlc/dgl/assets/32858941/f783f0d1-ebed-4077-8a73-fcaba228ac2b">

## Environment

 - DGL Version (e.g., 1.0): 1.1.2post1
 - Backend Library & Version (e.g., PyTorch 0.4.1, MXNet/Gluon 1.3): PyTorch 2.0.1
 - OS (e.g., Linux): macOS and Linux all tested
 - How you installed DGL (`conda`, `pip`, source): pip
 - Build command you used (if compiling from source):
 - Python version: 3.8
 - CUDA/cuDNN version (if applicable):
 - GPU models and configuration (e.g. V100):
 - Any other relevant information:

## Additional context

Same behavior also happens on `g.edges`.
I am not sure if it is a bug because I switch from PyG to DGL recently and not very familiar with the tool. If not, sorry for bothering and pls just close it.

**Comment by rudongyu** [comment]
Thanks for reporting the issue. We expect users to use `g.nodes()` and `g.edges()` as introduced in our documentation. Feel free to reopen it if you have further questions.

**Comment by NormanZyq** [comment]
> Thanks for reporting the issue. We expect users to use `g.nodes()` and `g.edges()` as introduced in our documentation. Feel free to reopen it if you have further questions.

@rudongyu Thanks for your reply and classification. I agree with you, but `g.nodes` is an iterable object and it is an intuitive way to use `list` to wrap it if someone does not read the doc at first. However, I think the behavior when I use `list` to wrap it should be more friendly. There should be raised with an Error if you expect user not to use it in this way instead of falling into an endless loop and capturing infinite memory.

**Comment by NormanZyq** [comment]
@rudongyu I'd like to reopen the issue because the current behavior of `list(g.nodes)` is extremely not friendly, but it seems that I do not have the privilege to reopen it. Thanks.
