### ISSUE TITLE
[Graphbolt] Redesign the from_csc API.

### ISSUE THREAD

**Issue by frozenbugs** [dmlc/dgl#6486]
## 🔨Work Item

Currently the from_csc is in graphbolt namespace, but create a very detailed implementation of one sample graph. We should reconsider how to rename it to reduce the confusion.

**IMPORTANT:**
* This template is only for dev team to track project progress. For feature request or bug report, please use the corresponding issue templates.
* DO NOT create a new work item if the purpose is to fix an existing issue or feature request. We will directly use the issue in the project tracker.

Project tracker: https://github.com/orgs/dmlc/projects/2

**Comment by Rhett-Ying** [comment]
just renamed as [fused_csc_sampling_graph()](https://github.com/dmlc/dgl/blob/1f15e3bc319fc55f175e2e32d28f27d503ebb26c/python/dgl/graphbolt/impl/fused_csc_sampling_graph.py#L896).
