### ISSUE TITLE
[Graphbolt] Implement on-disk feature store with Linux Ayns IO on SSD.

### ISSUE THREAD

**Issue by frozenbugs** [dmlc/dgl#6495]
## 🔨Work Item

**IMPORTANT:**
* This template is only for dev team to track project progress. For feature request or bug report, please use the corresponding issue templates.
* DO NOT create a new work item if the purpose is to fix an existing issue or feature request. We will directly use the issue in the project tracker.

Project tracker: https://github.com/orgs/dmlc/projects/2

**Comment by mfbalin** [comment]
Do you mean io_uring? I believe it is currently the best async IO interface available, other than Intel's user space NVMe driver https://spdk.io/.

**Comment by frozenbugs** [comment]
Yes, we are looking into options that can improve on-disk feature index-select. If you have more recommendation in mind, please let us know, we will investigate.
