### ISSUE TITLE
NameError: name '_CAPI_DGLRPCReset' is not defined when calling `dgl.distributed.initialize()`

### ISSUE THREAD

**Issue by thvasilo** [dmlc/dgl#6503]
## To Reproduce

1. Install DGL CPU version on an M1 Macbook
2. Run `import dgl; dgl.distributed.initialize()` in a Python REPL

Stacktrace:

```
dgl.distributed.initialize(ip_config=None)
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "/Users/thvasilo/.pyenv/versions/jupyter-env/lib/python3.9/site-packages/dgl/distributed/dist_context.py", line 284, in initialize
    rpc.reset()
  File "/Users/thvasilo/.pyenv/versions/jupyter-env/lib/python3.9/site-packages/dgl/distributed/rpc.py", line 138, in reset
    _CAPI_DGLRPCReset()
NameError: name '_CAPI_DGLRPCReset' is not defined
```

## Expected behavior

Trying the same on my Linux instance seems to work fine, not sure if MacOS is the issue here.

## Environment

 - DGL Version (e.g., 1.0): 1.1.2post1
 - Backend Library & Version (e.g., PyTorch 0.4.1, MXNet/Gluon 1.3): CPU
 - OS (e.g., Linux): MacOS
 - How you installed DGL (`conda`, `pip`, source): pip
 - Build command you used (if compiling from source):
 - Python version: 3.9
 - CUDA/cuDNN version (if applicable):
 - GPU models and configuration (e.g. V100):
 - Any other relevant information: M1 Mac (aarch64)

**Comment by Rhett-Ying** [comment]
DistDGL supports and well tested on Linux only. For your issue, I think it's not built at all: https://github.com/dmlc/dgl/blob/14b4a90b4eface27b20a89817f1c0c4210d602da/src/rpc/rpc.cc#L6.

**Comment by thvasilo** [comment]
OK closing as it seems like DGL does not support M1 Macs.
