### ISSUE TITLE
Can't build DGL graphbolt after #6417

### ISSUE THREAD

**Issue by xwang233** [dmlc/dgl#6504]
## 🐛 Bug

Can't build DGL graphbolt after #6417

This code sets the C++ standard to 14, where pytorch now requires extensions to be built with C++ 17 compilers.

https://github.com/dmlc/dgl/commit/1b5b7de5daef4fbc93934e525ab3c0e8c7d029d1#diff-b34a77a2d1f5909475ff6bf53a5d34477c1a5a765e2d43bc04b68596ec3b4526R60-R64

https://github.com/dmlc/dgl/blob/1b5b7de5daef4fbc93934e525ab3c0e8c7d029d1/graphbolt/CMakeLists.txt#L60-L63

Not sure why it's set to 14, but I'm able to build the project simply changing that to 17.

**Comment by TristonC** [comment]
@frozenbugs This is the issue we discussed on Wednesday.

**Comment by frozenbugs** [comment]
Yes, let's change it to 17. @Rhett-Ying to take care just in case there are any unexpected issue.
