### ISSUE TITLE
[Graphbolt] Support fetch label from feature store.

### ISSUE THREAD

**Issue by frozenbugs** [dmlc/dgl#6509]
## 🔨Work Item

**IMPORTANT:**
* This template is only for dev team to track project progress. For feature request or bug report, please use the corresponding issue templates.
* DO NOT create a new work item if the purpose is to fix an existing issue or feature request. We will directly use the issue in the project tracker.

Project tracker: https://github.com/orgs/dmlc/projects/2

**Comment by mfbalin** [comment]
What is the alternative solution for this issue? Is it to utilize ItemSampler to fetch the labels?

**Comment by frozenbugs** [comment]
Yes, currently ItemSampler output label along with seed. Unless we see the demand of fetch label from feature store we can revisit.
