### ISSUE TITLE
"import dgl" error, when interacting with front-end and back-end of website. Help!!

### ISSUE THREAD

**Issue by yxgu2353** [dmlc/dgl#6552]
## ❓ Questions and Help

<img width="1003" alt="eb2d7694504524b14e7b13f5ba3cde5" src="https://github.com/dmlc/dgl/assets/58209062/a9b40ab8-2af3-4e6e-a9af-fa412c2c6d05">

We have installed dgl normally, but when we call the model from the front-end of the website, "import dgl" gives us this error.
**Please help!!**

**Comment by frozenbugs** [comment]
When we load dgl, we will read file from .dgl to get the configuration if the directory does not exist, we will create one. So please make sure the python runner has access to the directory. Or you can create .dgl by yourself first and open the access to the python runner.

**Comment by frozenbugs** [comment]
Hi @yxgu2353 , I am closing this issue assuming you are happy about our response. Feel free to follow up and reopen the issue if you have more questions with regard to our response.
