### ISSUE TITLE
Get no error while using `list` object in `bg.set_batch_num_nodes()` but will get an AttributeError when using AvgPool to pool the batched graph

### ISSUE THREAD

**Issue by NormanZyq** [dmlc/dgl#6577]
## 🐛 Bug

If use a list object as the argument of set_batch_num_nodes(), we get no error, and it seems the graph is successfully batched with the number of nodes. However, if I use AvgPooling to pool the batched graph, I would get an error:

```
AttributeError: 'list' object has no attribute 'dtype'
```
It's obvious that the list is not supported in this case. 
If I use tensor, everything works fine, as the doc mentioned.

## To Reproduce

Please refer to the notebook:
https://colab.research.google.com/drive/1n-tfuPp3R59olfxgN4I9NJ95bNUmdsdJ?usp=sharing

## Expected behavior

If I use a list, there should be an error raised, or it can be transformed into tensor automatically

## Environment

 - DGL Version (e.g., 1.0): 1.1.2
 - Backend Library & Version (e.g., PyTorch 0.4.1, MXNet/Gluon 1.3): 2.1.0+cu118
 - OS (e.g., Linux): Linux
 - How you installed DGL (`conda`, `pip`, source): pip
 - Build command you used (if compiling from source):
 - Python version: 3.10.12
 - CUDA/cuDNN version (if applicable):
 - GPU models and configuration (e.g. V100): 
 - Any other relevant information:

**Comment by Rhett-Ying** [comment]
Thanks for reporting this. We do need to avoid passing unexpected data.
