### ISSUE TITLE
is there has max edge count limit?

### ISSUE THREAD

**Issue by ZonghaoWang** [dmlc/dgl#6585]
DGLError: [23:02:45] /opt/dgl/src/array/cuda/./utils.h:53: Check failed: (range - 1) >> bits == 0 (1181544903 vs. 0) :

**Comment by mfbalin** [comment]
Yes, there seems to be a bug in the code. Let me quickly fix it.

**Comment by mfbalin** [comment]
Can you try #6586 to see if it resolves your problem? @ZonghaoWang
