### ISSUE TITLE
How to Visualize the computation graph of gnn model in dgl?

### ISSUE THREAD

**Issue by Leessen11** [dmlc/dgl#6622]
i had tried using tensorboard.SummaryWriter.add_graph() to visualize model of gnn, but refuses to accept DGL graphs as inputs.

the same question as: [https://stackoverflow.com/questions/68903982/how-to-visualize-the-model-graph-of-a-graph-neural-network-in-tensorboard](url)

has any other tools to do this?

**Comment by BarclayII** [comment]
It seems that tensorboard requires PyTorch JIT compatibility to trace PyTorch code for computation graph visualization.  Currently DGL does not support PyTorch JIT.

**Comment by jermainewang** [comment]
Related to #5275 . It needs additional support from TorchScript or TorchDynamo for custom data structure which DGL relies on.
