### ISSUE TITLE
How to solve this problem?

### ISSUE THREAD

**Issue by NJTechMXY** [dmlc/dgl#6638]
I want to Create a simple graph to test.
But I found this error:
"AttributeError: module 'dgl.backend' has no attribute 'is_tensor'"

Code:
import dgl
import torch
import torch.nn as nn
import torch.nn.functional as F
import dgl.function as fn

src = [0, 1, 2, 3, 4, 5]
dst = [1, 2, 3, 4, 5, 0]
G = dgl.graph((src, dst))

Others:
my toch version:  1.9.0+cu111
dgl version: 1.1.0

How to solve it?
THANKS~

**Comment by paoxiaode** [comment]
Could you provide more detail about the error?

**Comment by NJTechMXY** [comment]
> Could you provide more detail about the error?

哈哈哈你是中国人吧，我就不说英语了；就是我在安装pip install dgl之后运行下下边代码出错了，比之前改了改：
import dgl
import torch
import torch.nn as nn
import torch.nn.functional as F
from dgl.nn.pytorch import GATConv
from dgl import AddSelfLoop
from dgl.data import  CoraGraphDataset

transform = (
    AddSelfLoop()
) 
data = CoraGraphDataset(transform=transform)
g = data[0]
device = torch.device("cuda" if torch.cuda.is_available() else "cpu")
g = g.int().to(device)
features = g.ndata["feat"]
labels = g.ndata["label"]
masks = g.ndata["train_mask"], g.ndata["val_mask"], g.ndata["test_mask"] 
in_size = features.shape[1]
out_size = data.num_classes

DGLError: [15:58:04] C:\Users\Administrator\DGL_scripts\release\win-64\dgl\src\runtime\c_runtime_api.cc:82: Check failed: allow_missing: Device API cuda is not enabled. Please install the cuda version of dgl.

我电脑是有cuda的，11.6；torch版本是GPU的1.9.0

**Comment by paoxiaode** [comment]
you can see from the error message: **"Please install the cuda version of dgl"**
please remove the installed dgl lib, then install dgl by this command
> pip install  dgl -f https://data.dgl.ai/wheels/cu116/repo.html

**Comment by NJTechMXY** [comment]
run this code:
import dgl
import torch
import torch.nn as nn
import torch.nn.functional as F
from dgl.nn.pytorch import GATConv
from dgl import AddSelfLoop
from dgl.data import  CoraGraphDataset
RuntimeError: DGL requires PyTorch >= 1.12.0

what I should do? update my torch1.9.0 to 1.12.0?
I think it is very difficult thing.
because I met many things when I install torch

**Comment by paoxiaode** [comment]
Generally, there is no need to install a specific old version of torch, just use the new version.
I recommend you first remove you torch 1.9.0, then follow the command here to install 
> pip3 install torch torchvision torchaudio --index-url https://download.pytorch.org/whl/cu116

**Comment by frozenbugs** [comment]
I am closing this issue assuming you are happy about our response. Feel free to follow up and reopen the issue if you have more questions with regard to our response.
