### ISSUE TITLE
Cuda 12 support

### ISSUE THREAD

**Issue by laurislopata** [dmlc/dgl#6664]
When can we expect cuda 12.X to be supported?

**Comment by Rhett-Ying** [comment]
cuda12.1 and Pytorch 2.1 is ready in nightly build of DGL(Linux only). As for stable releases, we're working on and should be ready in a week.

**Comment by thuzhf** [comment]
+1
Hope to support cuda 12.x as soon as possible.

**Comment by jermainewang** [comment]
CUDA 12 support has been added in the new 1.1.3 release https://github.com/dmlc/dgl/releases/tag/v1.1.3
