### ISSUE TITLE
dgl.utils.compensate() function error?

### ISSUE THREAD

**Issue by valleu326** [dmlc/dgl#6665]
def compensate(ids, origin_ids):
    """computing the compensate set of ids from origin_ids

    Note: ids should be a subset of origin_ids.
    Any of ids and origin_ids can be non-consecutive,
    and origin_ids should be sorted.

    Example:
    >>> ids = th.Tensor([0, 2, 4])
    >>> origin_ids = th.Tensor([0, 1, 2, 4, 5])
    >>> compensate(ids, origin_ids)
    th.Tensor([1, 5])
    """

I tried, the answer is th.Tensor([1, 3]), not th.Tensor([1, 5]), is it a bug?

**Comment by valleu326** [comment]
anyway, I was reading the source code and found the bug, it's just used by heterograph.py, hopefully someone can fix it, that's it.

**Comment by jermainewang** [comment]
cc @Rhett-Ying @frozenbugs for visibility

**Comment by Rhett-Ying** [comment]
@valleu326 `compensate()` works as expected if and only if `origin_ids` is a `torch.arange(num_nodes/edges)`. And the methods that call `compensate()` in `heterograph.py` meets the requirement. So it works well.

Anyway, the example in `compensate()` is confusing and should be fixed.

**Comment by peizhou001** [comment]
Hi @valleu326 , I am closing this issue assuming you are happy about our response. Feel free to follow up and reopen the issue if you have more questions with regard to our response.
