### ISSUE TITLE
[Graphbolt] FusedCSCSamplingGraph node_attributes is missing

### ISSUE THREAD

**Issue by mfbalin** [dmlc/dgl#6667]
## 🔨Work Item

I am inventing a new sampler on my own time, I need to access node attributes during sampling, which is currently a missing feature. 
Additionally, the `node_attributes` can also be used to sample from a sampled subgraph as follows:

Let's say we have a huge graph and compute the `InSubgraph` from it for a subset of its vertices (for caching purposes on the GPU for example). Now, if we want to sample from this `InSubgraph` again, we can construct a `FusedCSCSamplingGraph` object from the `FusedSampledSubgraph` but we will need the `node_attributes` object to store the `original_row_node_ids` or `original_column_node_ids`.

@frozenbugs @peizhou001 @Rhett-Ying

**Comment by Rhett-Ying** [comment]
I was using `node_attributes` to store `dgl.NID` (original NID) when integrating DistDGL with GraphBolt. But such change is not merged into master yet.

**Comment by mfbalin** [comment]
The feature has been added.
