### ISSUE TITLE
Multiprocess training sample example references 3rd party library

### ISSUE THREAD

**Issue by JakeStevens** [dmlc/dgl#667]
## 📚 Documentation

The [sampling example](https://github.com/dmlc/dgl/tree/master/examples/mxnet/sampling) for mxnet shows how to run multiprocessing training jobs. To do so, it uses the launch script from the incubator-mxnet project. It is unclear from the documentation that this project is not a part of DGL. Should this be included in the DGL repo as a third party submodule, or should the documentation be updated to reflect that one needs to download their own repo?

**Comment by jermainewang** [comment]
That's a good point. I think it should be fixed. @zheng-da
