### ISSUE TITLE
[Misc] Polish Sparse example to use graphbolt datapipe for subgraph sampling.

### ISSUE THREAD

**Issue by frozenbugs** [dmlc/dgl#6675]
## 🔨Work Item

**IMPORTANT:**
* This template is only for dev team to track project progress. For feature request or bug report, please use the corresponding issue templates.
* DO NOT create a new work item if the purpose is to fix an existing issue or feature request. We will directly use the issue in the project tracker.

Project tracker: https://github.com/orgs/dmlc/projects/2

**Comment by Rhett-Ying** [comment]
polished in https://github.com/dmlc/dgl/pull/6691
