### ISSUE TITLE
[Graphbolt] Create a release blog.

### ISSUE THREAD

**Issue by frozenbugs** [dmlc/dgl#6683]
## 🔨Work Item

**IMPORTANT:**
* This template is only for dev team to track project progress. For feature request or bug report, please use the corresponding issue templates.
* DO NOT create a new work item if the purpose is to fix an existing issue or feature request. We will directly use the issue in the project tracker.

Project tracker: https://github.com/orgs/dmlc/projects/2

**Comment by mfbalin** [comment]
@frozenbugs I think we can ship not only the feature fetch overlap but also the graph fetch overlap optimizations. Do you think we can make another release blog mentioning these techniques? We can also mention using dgl.sparse for the sampling operation by implementing LADIES sampler with all these optimizations enabled through GraphBolt.

**Comment by mfbalin** [comment]
I will open a PR showing how to use dgl.sparse to implement a custom sampler soon.
