### ISSUE TITLE
Protein dataset

### ISSUE THREAD

**Issue by YI-MAX-YAN** [dmlc/dgl#6706]
```
dataset = DglNodePropPredDataset(name='ogbn-proteins', root = "./dataset")
g = dataset[0][0]
features = g.ndata['feat']
```
KeyError: 'feat'
`print(g.ndata.keys())`
dict_keys(['species'])

**Comment by jermainewang** [comment]
This is expected as `ogbn-proteins` dataset https://ogb.stanford.edu/docs/nodeprop/#ogbn-proteins only has `species` associated with nodes.
