### ISSUE TITLE
Can those transform operators/functionals be applied to a DistGraph object?

### ISSUE THREAD

**Issue by husimplicity** [dmlc/dgl#6708]
## ❓ Questions and Help

Hi, can I apply those transform operators/functionals to a DistGraph object? Or are there plans to extend such a feature?

**Comment by jermainewang** [comment]
No. Extending them to large graphs is non-trivial and will probably require new distributed system design.

**Comment by frozenbugs** [comment]
I am closing this issue assuming you are happy about our response. Feel free to follow up and reopen the issue if you have more questions with regard to our response.
