### ISSUE TITLE
[GraphBolt] fill input/output_nodes in DGLMiniBatch

### ISSUE THREAD

**Issue by Rhett-Ying** [dmlc/dgl#6717]
## 🔨Work Item

**IMPORTANT:**
* This template is only for dev team to track project progress. For feature request or bug report, please use the corresponding issue templates.
* DO NOT create a new work item if the purpose is to fix an existing issue or feature request. We will directly use the issue in the project tracker.

Project tracker: https://github.com/orgs/dmlc/projects/2

## Description
https://github.com/dmlc/dgl/blob/15d05be387d5e81235298d291aca88e278ca2767/python/dgl/graphbolt/minibatch.py#L466-L471 . When converting a MiniBatch to DGLMinibatch. The input_nodes and output_nodes are not set properly.

**Comment by RamonZhou** [comment]
For now in the `MiniBatch`, `input_nodes` remains the same, `output_nodes` is changed to `seed_nodes`.
