### ISSUE TITLE
the correctness of dgl.shortest_dist (especially the output path)

### ISSUE THREAD

**Issue by study1157** [dmlc/dgl#6762]
## e.g.,
![1702635852772](https://github.com/dmlc/dgl/assets/96522577/0de41ec4-256e-4a04-9aad-28f65f604f87)
![distbug](https://github.com/dmlc/dgl/assets/96522577/4c7e7c48-10a3-43b8-b2b6-794d177ed25b)

the non-existent nodes (5 and 6) appeared in the path from 2 to 1, the same as the path from 2 to 3 and the path from 2 to 4

**Comment by rudongyu** [comment]
Hi, @study1157, this is not a bug. As described in the documentation: https://docs.dgl.ai/generated/dgl.shortest_dist.html?highlight=edge%20IDs, returned path contains edge IDs instead of node IDs. You can try the following code to get node IDs.

```python
g = dgl.graph(([1, 1, 2, 3, 4, 2, 4, 3], [0, 2, 0, 4, 2, 3, 1, 2]))
dist, path = shortest_dist(g, 2, True)
print(dist, path)
# tensor([1, 3, 0, 1, 2]) tensor([[ 2, -1, -1],
#         [ 5,  3,  6],
#         [-1, -1, -1],
#         [ 5, -1, -1],
#         [ 5,  3, -1]])

for target in range(5):
    edges = []
    path_eids = [int(eid) for eid in path[target] if eid != -1]
    u, v = g.find_edges(path_eids)
    print(f"path from 2 to {target}:", list(zip(u.numpy().tolist(), v.numpy().tolist())))
# path from 2 to 0: [(2, 0)]
# path from 2 to 1: [(2, 3), (3, 4), (4, 1)]
# path from 2 to 2: []
# path from 2 to 3: [(2, 3)]
# path from 2 to 4: [(2, 3), (3, 4)]
```

**Comment by study1157** [comment]
I get it. Thank you for your reply.



---Original---
From: ***@***.***&gt;
Date: Thu, Jan 11, 2024 10:14 AM
To: ***@***.***&gt;;
Cc: ***@***.******@***.***&gt;;
Subject: Re: [dmlc/dgl] the correctness of dgl.shortest_dist (especially theoutput path) (Issue #6762)




 
Hi, @study1157, this is not a bug. As described in the documentation: https://docs.dgl.ai/generated/dgl.shortest_dist.html?highlight=edge%20IDs, returned path contains edge IDs instead of node IDs. You can try the following code to get node IDs.
 g = dgl.graph(([1, 1, 2, 3, 4, 2, 4, 3], [0, 2, 0, 4, 2, 3, 1, 2])) dist, path = shortest_dist(g, 2, True) print(dist, path) # tensor([1, 3, 0, 1, 2]) tensor([[ 2, -1, -1], #         [ 5,  3,  6], #         [-1, -1, -1], #         [ 5, -1, -1], #         [ 5,  3, -1]]) for target in range(5):     edges = []     path_eids = [int(eid) for eid in path[target] if eid != -1]     u, v = g.find_edges(path_eids)     print(f"path from 2 to {target}:", list(zip(u.numpy().tolist(), v.numpy().tolist()))) # path from 2 to 0: [(2, 0)] # path from 2 to 1: [(2, 3), (3, 4), (4, 1)] # path from 2 to 2: [] # path from 2 to 3: [(2, 3)] # path from 2 to 4: [(2, 3), (3, 4)]
