### ISSUE TITLE
GCN Layer Problem

### ISSUE THREAD

**Issue by FOURIERWANG** [dmlc/dgl#677]
This paper uses two layers of GCN to achieve the accuracy, why do you only use one layer of GCN to compare?The effect of two layers is not good.This is inconsistent with the results of the paper.

**Comment by yzh119** [comment]
We indeed use two layers: https://github.com/dmlc/dgl/blob/master/examples/pytorch/gcn/gcn.py
When `n_layers` is set to one, there is one input layer and one output layer.

**Comment by FOURIERWANG** [comment]
> We indeed use two layers: https://github.com/dmlc/dgl/blob/master/examples/pytorch/gcn/gcn.py
> When `n_layers` is set to one, there is one input layer and one output layer.

I got it! Thank you for your reply.
