### ISSUE TITLE
Where to find the definition of nodes.mailbox, edges.src and edges.dst ?

### ISSUE THREAD

**Issue by zegzag** [dmlc/dgl#681]
## ❓ Questions and Help

I want to try to figure out how the message passing is achieved in dgl. So I looked at the source code installed in my computer under /anaconda/lib/python3.7/site-pachages/dgl/*. I find that the `DGLGraph().node` returns `NodeView(self)`,`DGLGraph().edges` returns `EdgeView(self)`. And NodeView() class don't have the `mailbox` property and EdgeView() class don't have the `src` property. So I am eager to where is the definition of `nodes.mailbox` and `edges.src`.

And one more question, does `nodes.mailbox['xxx']` always include its own 'xxx' feature data or not ? If not, then all codes about GCN (tutorial, example and `dgl.nn.pytorch.GraphCov`) can be wrong, because these implementation don't consider the re-normalization trick in GCN, that means self-connections were not added, nodes drop its own original feature and only aggregate its neighbor feature in each layer. And this will cause problems when we meet isolated nodes in a graph,  `nodes.mailbox['xxx']` of isolated nodes will all be `0` because self-feature is excluded.

**Comment by VoVAllen** [comment]
Hi,

The graph loaded from dataset are preprocessed by adding self-loop. `nodes.mailbox` doesn't include its own feature. You can use `node.data` to access its own feature. 

Mailbox is defined at https://github.com/dmlc/dgl/blob/master/python/dgl/udf.py#L136

**Comment by zegzag** [comment]
Question well solved! Thx~

**Comment by jermainewang** [comment]
@zegzag We also recommend using discussion forum for general questions. Glad that your question is resolved.
