### ISSUE TITLE
[Graphbolt] Regression performance down grade

### ISSUE THREAD

**Issue by peizhou001** [dmlc/dgl#6813]
## 🔨Work Item

**IMPORTANT:**

Graphbolt node classification time from 15 -> 18, need to investigate the reason.

Project tracker: https://github.com/orgs/dmlc/projects/2

**Comment by mfbalin** [comment]
@peizhou001 this is fixed, right?

**Comment by peizhou001** [comment]
Yes, it's already fixed.

**Comment by peizhou001** [comment]
Yes, it's already fixed.
