### ISSUE TITLE
The issues in Relational Graph Convolutional Network

### ISSUE THREAD

**Issue by km1994** [dmlc/dgl#684]
RuntimeError: Expected object of type torch.IntTensor but found type torch.LongTensor for argument #3 'other'

**Comment by VoVAllen** [comment]
Could you provide more information about this error? Such as which line raises this error? And could you also provide your dgl version? Thanks.

**Comment by jermainewang** [comment]
Hey, would you please follow the instruction in the issue template? Provide at least following environment?

## Environment

 - DGL Version (e.g., 1.0):
 - Backend Library & Version (e.g., PyTorch 0.4.1, MXNet/Gluon 1.3):
 - OS (e.g., Linux):
 - How you installed DGL (`conda`, `pip`, source):
 - Build command you used (if compiling from source):
 - Python version:
 - CUDA/cuDNN version (if applicable):
 - GPU models and configuration (e.g. V100):
 - Any other relevant information:

**Comment by jermainewang** [comment]
Closed due to lack of activity and unclear information.
