### ISSUE TITLE
GCN initialize graph

### ISSUE THREAD

**Issue by FOURIERWANG** [dmlc/dgl#687]
Hello.
Initializer is not set. Why?

**Comment by yzh119** [comment]
I don't know what do you mean by initializer is not set, could you elaborate more?
By default the weights in `GraphConv` module is initialized with `xavier_uniform`: https://github.com/dmlc/dgl/blob/master/python/dgl/nn/pytorch/conv.py#L84

**Comment by yzh119** [comment]
If you mean this warning: ```UserWarning: Initializer is not set. Use zero initializer instead. To suppress this warning, use `set_initializer` to explicitly specify which initializer to use.```, this suggests that you created a new field and assigned features for a subset of nodes, for examples:
```python
>>> import dgl
>>> import torch as th
>>> g = dgl.DGLGraph()
>>> g.add_nodes(10)
>>> g.nodes[(2, 3, 4)].data['x'] = th.rand(3, 5)
/Users/yeziha/anaconda3/lib/python3.7/site-packages/dgl-0.3-py3.7-macosx-10.7-x86_64.egg/dgl/base.py:18: UserWarning: Initializer is not set. Use zero initializer instead. To suppress this warning, use `set_initializer` to explicitly specify which initializer to use.
  warnings.warn(msg)
```
By default DGL would initialize the feature of other nodes with all zero and issue the warning mentioned above.
```python
>>> g.ndata['x']
tensor([[0.0000, 0.0000, 0.0000, 0.0000, 0.0000],
        [0.0000, 0.0000, 0.0000, 0.0000, 0.0000],
        [0.8993, 0.8488, 0.8700, 0.4228, 0.1688],
        [0.3651, 0.1223, 0.2861, 0.8090, 0.4760],
        [0.0804, 0.9207, 0.7841, 0.3940, 0.1250],
        [0.0000, 0.0000, 0.0000, 0.0000, 0.0000],
        [0.0000, 0.0000, 0.0000, 0.0000, 0.0000],
        [0.0000, 0.0000, 0.0000, 0.0000, 0.0000],
        [0.0000, 0.0000, 0.0000, 0.0000, 0.0000],
        [0.0000, 0.0000, 0.0000, 0.0000, 0.0000]])
```
As suggested in the warning message, to suppress this warning you may manually specify a node/edge initializer by [set_n_initializer](https://docs.dgl.ai/generated/dgl.DGLGraph.set_n_initializer.html) or [set_e_initializer](https://docs.dgl.ai/generated/dgl.DGLGraph.set_e_initializer.html).

Related discussion thread: https://discuss.dgl.ai/t/about-setting-initializer/64

**Comment by FOURIERWANG** [comment]
I probably know what the problem is. Thank you.
