### ISSUE TITLE
Cannot import dgl

### ISSUE THREAD

**Issue by sreevishal** [dmlc/dgl#688]

**Comment by sreevishal** [comment]
import dgl
Error: 

--------------------------------------------------------------------------
OSError                                   Traceback (most recent call last)
<ipython-input-1-e63c22ad8b0e> in <module>
      4 import torch.nn as nn
      5 import torch.nn.functional as F
----> 6 import dgl
      7 #from dgl import DGLGraph
      8 #from dgl.data import register_data_args, load_data

~\AppData\Local\Continuum\anaconda3\lib\site-packages\dgl\__init__.py in <module>
      4 import socket
      5 
----> 6 from . import function
      7 from . import nn
      8 from . import contrib

~\AppData\Local\Continuum\anaconda3\lib\site-packages\dgl\function\__init__.py in <module>
      3 from __future__ import absolute_import
      4 
----> 5 from .message import *
      6 from .reducer import *
      7 from .base import *

~\AppData\Local\Continuum\anaconda3\lib\site-packages\dgl\function\message.py in <module>
      6 
      7 from .base import BuiltinFunction, TargetCode
----> 8 from ..runtime import ir
      9 from ..runtime.ir import var
     10 

~\AppData\Local\Continuum\anaconda3\lib\site-packages\dgl\runtime\__init__.py in <module>
      2 from __future__ import absolute_import
      3 
----> 4 from . import scheduler
      5 from .runtime import Runtime

~\AppData\Local\Continuum\anaconda3\lib\site-packages\dgl\runtime\scheduler.py in <module>
      2 from __future__ import absolute_import
      3 
----> 4 from .. import utils
      5 from .._ffi.function import _init_api
      6 from ..base import DGLError

~\AppData\Local\Continuum\anaconda3\lib\site-packages\dgl\utils.py in <module>
      8 
      9 from . import _api_internal
---> 10 from .base import DGLError
     11 from . import backend as F
     12 from . import ndarray as nd

~\AppData\Local\Continuum\anaconda3\lib\site-packages\dgl\base.py in <module>
      4 import warnings
      5 
----> 6 from ._ffi.base import DGLError  # pylint: disable=unused-import
      7 from ._ffi.function import _init_internal_api
      8 

~\AppData\Local\Continuum\anaconda3\lib\site-packages\dgl\_ffi\base.py in <module>
     40 __version__ = libinfo.__version__
     41 # library instance of nnvm
---> 42 _LIB, _LIB_NAME = _load_lib()
     43 
     44 # The FFI mode of DGL

~\AppData\Local\Continuum\anaconda3\lib\site-packages\dgl\_ffi\base.py in _load_lib()
     32     """Load libary by searching possible path."""
     33     lib_path = libinfo.find_lib_path()
---> 34     lib = ctypes.CDLL(lib_path[0], ctypes.RTLD_GLOBAL)
     35     # DMatrix functions
     36     lib.DGLGetLastError.restype = ctypes.c_char_p

~\AppData\Local\Continuum\anaconda3\lib\ctypes\__init__.py in __init__(self, name, mode, handle, use_errno, use_last_error)
    354 
    355         if handle is None:
--> 356             self._handle = _dlopen(self._name, mode)
    357         else:
    358             self._handle = handle

OSError: [WinError 126] The specified module could not be found

**Comment by jermainewang** [comment]
Hey, would you please follow the instruction in the issue template? Provide at least following environment?

## Environment

 - DGL Version (e.g., 1.0):
 - Backend Library & Version (e.g., PyTorch 0.4.1, MXNet/Gluon 1.3):
 - OS (e.g., Linux):
 - How you installed DGL (`conda`, `pip`, source):
 - Build command you used (if compiling from source):
 - Python version:
 - CUDA/cuDNN version (if applicable):
 - GPU models and configuration (e.g. V100):
 - Any other relevant information:

**Comment by sreevishal** [comment]
DGL Version (e.g., 1.0): dgl-0,3
Backend Library & Version (e.g., PyTorch 0.4.1, MXNet/Gluon 1.3): 
OS (e.g., Linux): Windows
How you installed DGL (conda, pip, source): conda install -c dglteam dgl
Build command you used (if compiling from source):  
Python version: 3.7
CUDA/cuDNN version (if applicable): none
GPU models and configuration (e.g. V100): none
Any other relevant information: i installed pytorch and can import it fine.

**Comment by jermainewang** [comment]
It looks like the library cannot be opened on windows somehow. @BarclayII Could you have a look?

**Comment by khfp** [comment]
I meet this error too!
this is my Environment:
DGL Version (e.g., 1.0): dgl-0,3
Backend Library & Version (e.g., PyTorch 0.4.1, MXNet/Gluon 1.3):pytorch-cpu 1.1.0
OS (e.g., Linux): Windows10
How you installed DGL (conda, pip, source): conda install -c dglteam dgl
Build command you used (if compiling from source):
Python version: python  3.7.3
CUDA/cuDNN version (if applicable): none
GPU models and configuration (e.g. V100): none
Any other relevant information: i installed pytorch and can import it fine.

**Comment by BarclayII** [comment]
@sreevishal @khfp Could you please verify if you could find the following DLLs in your `C:\Windows\System32` folder:

```
VCRUNTIME140.DLL
API-MS-WIN-CRT-RUNTIME-L1-1-0.DLL
```

If not, you probably need to install Visual C++ Redistributable for VS2015.

**Comment by sreevishal** [comment]
Thanks for replying me. 
I have VCRUNTIME140.DLL but not API-MS-WIN-CRT-RUNTIME-L1-1-0.DLL
Already have Visual C++ Redistributable for VS2015.. 
Any suggestions ?

**Comment by BarclayII** [comment]
Should be fixed.  Please uninstall the old `dgl` and reinstall it with conda.

For users that installed with pip, uninstall it and reinstall it with
```
pip install https://s3.us-east-2.amazonaws.com/dgl.ai/wheels/dgl-0.3-cp35-cp35m-win_amd64.whl
pip install https://s3.us-east-2.amazonaws.com/dgl.ai/wheels/dgl-0.3-cp36-cp36m-win_amd64.whl
pip install https://s3.us-east-2.amazonaws.com/dgl.ai/wheels/dgl-0.3-cp37-cp37m-win_amd64.whl
```

**Comment by khfp** [comment]
> Should be fixed. Please uninstall the old `dgl` and reinstall it with conda.
> 
> For users that installed with pip, uninstall it and reinstall it with
> 
> ```
> pip install https://s3.us-east-2.amazonaws.com/dgl.ai/wheels/dgl-0.3-cp35-cp35m-win_amd64.whl
> pip install https://s3.us-east-2.amazonaws.com/dgl.ai/wheels/dgl-0.3-cp36-cp36m-win_amd64.whl
> pip install https://s3.us-east-2.amazonaws.com/dgl.ai/wheels/dgl-0.3-cp37-cp37m-win_amd64.whl
> ```

Thanks! It have be fixed!  I have uninstall dgl and reinstall with "conda install -c dglteam dgl"

**Comment by khfp** [comment]
> Should be fixed. Please uninstall the old `dgl` and reinstall it with conda.
> 
> For users that installed with pip, uninstall it and reinstall it with
> 
> ```
> pip install https://s3.us-east-2.amazonaws.com/dgl.ai/wheels/dgl-0.3-cp35-cp35m-win_amd64.whl
> pip install https://s3.us-east-2.amazonaws.com/dgl.ai/wheels/dgl-0.3-cp36-cp36m-win_amd64.whl
> pip install https://s3.us-east-2.amazonaws.com/dgl.ai/wheels/dgl-0.3-cp37-cp37m-win_amd64.whl
> ```

@BarclayII 
Thanks! it has been fixed!
I reinstall with "conda install -c dglteam dgl"

**Comment by sreevishal** [comment]
> Should be fixed. Please uninstall the old `dgl` and reinstall it with conda.
> 
> For users that installed with pip, uninstall it and reinstall it with
> 
> ```
> pip install https://s3.us-east-2.amazonaws.com/dgl.ai/wheels/dgl-0.3-cp35-cp35m-win_amd64.whl
> pip install https://s3.us-east-2.amazonaws.com/dgl.ai/wheels/dgl-0.3-cp36-cp36m-win_amd64.whl
> pip install https://s3.us-east-2.amazonaws.com/dgl.ai/wheels/dgl-0.3-cp37-cp37m-win_amd64.whl
> ```

Thanks, its working now

**Comment by gcorso** [comment]
I'm having this problem with dgl 0.4.2:

DGL Version (e.g., 1.0): dgl-0.4.2
Backend Library & Version (e.g., PyTorch 0.4.1, MXNet/Gluon 1.3): pytorch 1.5.0
OS (e.g., Linux): Windows10
How you installed DGL (conda, pip, source): conda install -c dglteam dgl
Build command you used (if compiling from source):
Python version: python 3.7.6
CUDA/cuDNN version (if applicable): none
GPU models and configuration (e.g. V100): none

```
Traceback (most recent call last):
  File "main_molecules_graph_regression.py", line 9, in <module>
    import dgl
  File "C:\Users\gabri\Python\Anaconda3\envs\benchmark_gnn2\lib\site-packages\dgl\__init__.py", line 8, in <module>
    from .backend import load_backend
  File "C:\Users\gabri\Python\Anaconda3\envs\benchmark_gnn2\lib\site-packages\dgl\backend\__init__.py", line 48, in <module>
    load_backend(os.environ.get('DGLBACKEND', 'pytorch').lower())
  File "C:\Users\gabri\Python\Anaconda3\envs\benchmark_gnn2\lib\site-packages\dgl\backend\__init__.py", line 18, in load_backend
    mod = importlib.import_module('.%s' % mod_name, __name__)
  File "C:\Users\gabri\Python\Anaconda3\envs\benchmark_gnn2\lib\importlib\__init__.py", line 127, in import_module
    return _bootstrap._gcd_import(name[level:], package, level)
  File "C:\Users\gabri\Python\Anaconda3\envs\benchmark_gnn2\lib\site-packages\dgl\backend\pytorch\__init__.py", line 1, in <module>
    from .tensor import *
  File "C:\Users\gabri\Python\Anaconda3\envs\benchmark_gnn2\lib\site-packages\dgl\backend\pytorch\tensor.py", line 5, in <module>
    import torch as th
  File "C:\Users\gabri\Python\Anaconda3\envs\benchmark_gnn2\lib\site-packages\torch\__init__.py", line 81, in <module>
    ctypes.CDLL(dll)
  File "C:\Users\gabri\Python\Anaconda3\envs\benchmark_gnn2\lib\ctypes\__init__.py", line 364, in __init__
    self._handle = _dlopen(self._name, mode)
OSError: [WinError 126] Impossibile trovare il modulo specificato
```

I am forced to use dgl 0.4.2 for the gnns benchmarks https://github.com/graphdeeplearning/benchmarking-gnns/ . Any ideas on how to solve it?

**Comment by whoeverknows** [comment]
> I'm having this problem with dgl 0.4.2:
> 
> DGL Version (e.g., 1.0): dgl-0.4.2
> Backend Library & Version (e.g., PyTorch 0.4.1, MXNet/Gluon 1.3): pytorch 1.5.0
> OS (e.g., Linux): Windows10
> How you installed DGL (conda, pip, source): conda install -c dglteam dgl
> Build command you used (if compiling from source):
> Python version: python 3.7.6
> CUDA/cuDNN version (if applicable): none
> GPU models and configuration (e.g. V100): none
> 
> ```
> Traceback (most recent call last):
>   File "main_molecules_graph_regression.py", line 9, in <module>
>     import dgl
>   File "C:\Users\gabri\Python\Anaconda3\envs\benchmark_gnn2\lib\site-packages\dgl\__init__.py", line 8, in <module>
>     from .backend import load_backend
>   File "C:\Users\gabri\Python\Anaconda3\envs\benchmark_gnn2\lib\site-packages\dgl\backend\__init__.py", line 48, in <module>
>     load_backend(os.environ.get('DGLBACKEND', 'pytorch').lower())
>   File "C:\Users\gabri\Python\Anaconda3\envs\benchmark_gnn2\lib\site-packages\dgl\backend\__init__.py", line 18, in load_backend
>     mod = importlib.import_module('.%s' % mod_name, __name__)
>   File "C:\Users\gabri\Python\Anaconda3\envs\benchmark_gnn2\lib\importlib\__init__.py", line 127, in import_module
>     return _bootstrap._gcd_import(name[level:], package, level)
>   File "C:\Users\gabri\Python\Anaconda3\envs\benchmark_gnn2\lib\site-packages\dgl\backend\pytorch\__init__.py", line 1, in <module>
>     from .tensor import *
>   File "C:\Users\gabri\Python\Anaconda3\envs\benchmark_gnn2\lib\site-packages\dgl\backend\pytorch\tensor.py", line 5, in <module>
>     import torch as th
>   File "C:\Users\gabri\Python\Anaconda3\envs\benchmark_gnn2\lib\site-packages\torch\__init__.py", line 81, in <module>
>     ctypes.CDLL(dll)
>   File "C:\Users\gabri\Python\Anaconda3\envs\benchmark_gnn2\lib\ctypes\__init__.py", line 364, in __init__
>     self._handle = _dlopen(self._name, mode)
> OSError: [WinError 126] Impossibile trovare il modulo specificato
> ```
> 
> I am forced to use dgl 0.4.2 for the gnns benchmarks https://github.com/graphdeeplearning/benchmarking-gnns/ . Any ideas on how to solve it?

I got the same problem and fixed it.
I remove dgl and pytorch package by "conda remove pkgname"
And install pytorch again by using conda "conda install pytorch torchvision cpuonly -c pytorch"
then install dgl by "conda install -c dglteam dgl".

I'm using python 3.7.4, dgl-0.4.3post2 and torch 1.5.0.

**Comment by Maulpy** [comment]
I still have trouble with WinError126 after reinstalling dgl and pytorch using conda.

It is a little bit specific, WinError126 mentions "Error loading "C:\Users\Acer\anaconda3\envs\DGL\lib\site-packages\torch\lib\caffe2_detectron_ops.dll" or one of its dependencies."

DGL Version (e.g., 1.0): dgl-0.5.2
Backend Library & Version (e.g., PyTorch 0.4.1, MXNet/Gluon 1.3): pytorch 1.7.0
OS (e.g., Linux): Windows10
How you installed DGL (conda, pip, source): conda install -c dglteam dgl
Build command you used (if compiling from source): 
Python version: python 3.6.12
CUDA/cuDNN version (if applicable): none
GPU models and configuration (e.g. V100): none
Any other relevant information: I use conda 4.8.3

Complete error is

Using backend: pytorch
Traceback (most recent call last):
  File "<pyshell#0>", line 1, in <module>
    import dgl
  File "C:\Users\Acer\anaconda3\envs\DGL\lib\site-packages\dgl\__init__.py", line 14, in <module>
    from .backend import load_backend, backend_name
  File "C:\Users\Acer\anaconda3\envs\DGL\lib\site-packages\dgl\backend\__init__.py", line 73, in <module>
    load_backend(get_preferred_backend())
  File "C:\Users\Acer\anaconda3\envs\DGL\lib\site-packages\dgl\backend\__init__.py", line 23, in load_backend
    mod = importlib.import_module('.%s' % mod_name, __name__)
  File "C:\Users\Acer\anaconda3\envs\DGL\lib\importlib\__init__.py", line 126, in import_module
    return _bootstrap._gcd_import(name[level:], package, level)
  File "C:\Users\Acer\anaconda3\envs\DGL\lib\site-packages\dgl\backend\pytorch\__init__.py", line 1, in <module>
    from .tensor import *
  File "C:\Users\Acer\anaconda3\envs\DGL\lib\site-packages\dgl\backend\pytorch\tensor.py", line 6, in <module>
    import torch as th
  File "C:\Users\Acer\anaconda3\envs\DGL\lib\site-packages\torch\__init__.py", line 128, in <module>
    raise err
OSError: [WinError 126] The specified module could not be found. Error loading "C:\Users\Acer\anaconda3\envs\DGL\lib\site-packages\torch\lib\caffe2_detectron_ops.dll" or one of its dependencies.

I don't know if the following links will apply to dgl?https://discuss.pytorch.org/t/i-cannot-use-the-pytorch-that-was-built-successfully-from-source-dll-initialization-routine-failed-error-loading-caffe2-detectron-ops-gpu-dll/93243/5

Is there any advice?thank you very much.
