### ISSUE TITLE
[Packaging] Add maintainer(s) from DGL core team to conda-forge feedstock

### ISSUE THREAD

**Issue by hmacdope** [dmlc/dgl#6883]
## Motivation

The conda-forge package for DGL has been live for a bit, and seems to be working well! 

Currently it is maintained by myself (@hmacdope ) and @mikemhenry (originally motivated by our use of DGL in our own workflows), which we plan on continuing with gusto. 

However I feel it would be nice to invite some members of the DGL team to also be maintainers so that you do not need our specific approval (not affiliated with DGL project directly) to update and improve the conda-forge recipe (https://github.com/conda-forge/dgl-feedstock/issues/27). Additionally we can use our cooperative knowledge to fix issues and push updates faster. 

Would members of the DGL / dmlc team be open to this? It is a simple process to add a maintainer.  😸 

## Pitch

I would love to invite some members of the DGL team to be maintainers on the conda-forge feedstock, so that we can combine our power! 💯

**Comment by hmacdope** [comment]
Tagging @jermainewang as we corresponded previously on conda-forge things :)

**Comment by frozenbugs** [comment]
feel free to put me on the maintainer list and loop me in when you need help.

**Comment by hmacdope** [comment]
Awesome! Done in: https://github.com/conda-forge/dgl-feedstock/pull/30. You now have full power in the feedstock.
