### ISSUE TITLE
[GraphBolt][CUDA] `_convert_to_sampled_subgraph` has too many GPU synchronizations.

### ISSUE THREAD

**Issue by mfbalin** [dmlc/dgl#6887]
## 🔨Work Item

**IMPORTANT:**
* This template is only for dev team to track project progress. For feature request or bug report, please use the corresponding issue templates.
* DO NOT create a new work item if the purpose is to fix an existing issue or feature request. We will directly use the issue in the project tracker.

Project tracker: https://github.com/orgs/dmlc/projects/2

## Description

As can be seen in the picture below, almost half of the GPU sampling runtime is spent on `_convert_to_sampled_subgraph` 3ms every time it is called in the hetero sampling example. This should take around 0.1ms with an optimized custom implementation. The main culprit is the use of `torch.nonzero` causing a CPU GPU synchronization to read the size of the nonzero ids each time it is called.
![image](https://github.com/dmlc/dgl/assets/16190101/ba19d6c6-f71c-4785-ae14-34dd69570cf5)

**Comment by mfbalin** [comment]
@Rhett-Ying @yxy235

**Comment by Rhett-Ying** [comment]
```
The main culprit is the use of torch.nonzero causing a CPU GPU synchronization to read the size of the nonzero ids each time it is called.
```
@mfbalin 
The direct cause of sync is the tensor data that `torch.nonzero` operates on is not on GPU side while the `sampled_csc` is targeted on GPU?

**Comment by mfbalin** [comment]
> ```
> The main culprit is the use of torch.nonzero causing a CPU GPU synchronization to read the size of the nonzero ids each time it is called.
> ```
> 
> @mfbalin The direct cause of sync is the tensor data that `torch.nonzero` operates on is not on GPU side while the `sampled_csc` is targeted on GPU?

No, the operation happens on GPU. The reason is that nonzero checks if tensor elements are nonzero, however it is unknown how many will be nonzero. This information is needed on CPU side to allocate output tensor so there is a GPU CPU synchronization.
