### ISSUE TITLE
citegrh.load_cora() cannot download cora dataset

### ISSUE THREAD

**Issue by lichen11** [dmlc/dgl#689]
from dgl.data import citation_graph as citegrh
    data = citegrh.load_cora()

Downloading /home/user/.dgl/cora.zip from https://s3.us-east-2.amazonaws.com/dgl.ai/dataset/cora_raw.zip...
download failed, retrying, 4 attempts left
Downloading /home/user/.dgl/cora.zip from https://s3.us-east-2.amazonaws.com/dgl.ai/dataset/cora_raw.zip...
download failed, retrying, 3 attempts left
Downloading /home/user/.dgl/cora.zip from https://s3.us-east-2.amazonaws.com/dgl.ai/dataset/cora_raw.zip...
download failed, retrying, 2 attempts left
Downloading /home/user/.dgl/cora.zip from https://s3.us-east-2.amazonaws.com/dgl.ai/dataset/cora_raw.zip...

I had done exporting https_proxy and http_proxy but still see the error. Firewall is also turned off. Some help will be appreciated!

**Comment by jermainewang** [comment]
Try another mirror? https://docs.dgl.ai/env_var.html

**Comment by lichen11** [comment]
Downloading is still failing with the other link.... I still think it's a proxy issue.... 
In https://github.com/dmlc/dgl/blob/master/python/dgl/data/citation_graph.py is there somewhere that I can add a proxy to download the data?

**Comment by lichen11** [comment]
If I do 
    wget https://s3.us-east-2.amazonaws.com/dgl.ai/dataset/cora_raw.zip

I am able to download the data from computer. So I suppose it's not a firewall or proxy issue on my computer. But using data = citegrh.load_cora() keeps failing.

**Comment by VoVAllen** [comment]
The problem might be wrong setting of https certificate with python library. 
Could you try change the signature at https://github.com/dmlc/dgl/blob/master/python/dgl/data/utils.py#L27 or 
https://github.com/dmlc/dgl/blob/master/python/dgl/data/citation_graph.py#L344
from `verify_ssl=True` to `verify_ssl=False`

**Comment by lichen11** [comment]
I made the above change, still not working. 
I also did the following:

    import requests
    proxy = "https://proxy.website.com:port"
    
I also changed the line
    r = requests.get(url, stream=True, verify=verify_ssl)
to 
    r = requests.get(url, proxies = proxy, stream=True, verify=verify_ssl)

Still not working....

**Comment by VoVAllen** [comment]
You can manually download the file and put it at `~/.dgl/` folder. It should not download it again.

**Comment by jermainewang** [comment]
Closed due to inactivity. Please reopen if issue still exists.

**Comment by ZiffW** [comment]
hi I'm having the same issue, did you figure it out?

**Comment by abitofalchemy** [comment]
I downloaded the dataset manually, and unzip the file: `cora_v2.zip` to folder ~/.dgl/. I can't find an example that shows me how to load the cora dataset from its source files.  Q: how do I load this graph given the unzipped files below? 

config.json
cora_v2.zip
ind.cora_v2.allx
ind.cora_v2.ally
ind.cora_v2.graph
ind.cora_v2.test.index
ind.cora_v2.tx
ind.cora_v2.ty
ind.cora_v2.x
ind.cora_v2.y

Files seem to have a compressed signature: when I do head on any of them I get stuff like this: 
```
head ind.c 
�cscipy.sparse.csr
csr_matrix
q)�q}q(UformatqUcsrU_shapeqK�M��Uindptrqcnumpy.core.multiarray
_reconstruct
```

**Comment by densamoilov** [comment]
FWIW, sometimes it happens when you exceed quota of your home directory where `.dgl` is located.
