### ISSUE TITLE
Cannot conda install DGL due to incompatibility with PyTorch 2.1.2 and CUDA 12.1 on Linux with Python 3.10

### ISSUE THREAD

**Issue by LiutongZhou** [dmlc/dgl#6908]
## 🐛 Bug
`conda install -c dglteam/label/cu121 dgl` fails to install DGL with PyTorch 2.1.2 and CUDA 12.1

### Method 1
1. Follow the official PyTorch installation guide to install PyTorch 2.1 with CUDA 12.1 on Linux using conda (Python=3.10).   
    ```conda install pytorch torchvision torchaudio pytorch-cuda=12.1 -c pytorch -c nvidia```
1. Follow the official DGL guide to install DGL
    ```conda install -c dglteam/label/cu121 dgl``` 

### Method 2
Equivalently, 
1. Create a `test.yaml` 
    ```
    # test.yaml
    channels:
      - pytorch
      - nvidia
      - dglteam/label/cu121
      - conda-forge
    dependencies:
      - python=3.10  
      - pytorch=2.1.2=py3.10_cuda12.1_cudnn8.9.2_0 
      - pytorch-cuda=12.1
      - dgl 
    ```
1. `mamba env create -f test.yaml -n test_dgl`

### The Error
```commandline
Looking for: ["python[version='>=3.10']", 'pytorch==2.1.2=py3.10_cuda12.1_cudnn8.9.2_0', 'pytorch-cuda=12.1', 'dgl']

Could not solve for environment specs
The following packages are incompatible
├─ dgl is installable and it requires
│  └─ pytorch >=2.0.0,<2.1.0a0  with the potential options
│     ├─ pytorch [2.0.0|2.0.1], which can be installed;
│     └─ pytorch 2.0.0 would require
│        └─ __cuda, which is missing on the system;
└─ pytorch ==2.1.2 py3.10_cuda12.1_cudnn8.9.2_0 is not installable because it conflicts with any installable versions previously reported.
```

## Expected behavior
DGL should install with PyTorch 2.1 and CUDA 12.1 as per the compatibility table https://www.dgl.ai/pages/start.html 

## Environment
```
Ubuntu 20.02 LTS
Python 3.10
Conda 23.11
PyTorch 2.1.2
CUDA 12.1
```

**Comment by Rhett-Ying** [comment]
`torch 2.1.2` is not supported in latest DGL stable release while `2.1.0/1` is supported. If you want to use DGL with `torch 2.1.2`, you could try with our nightly build. But note that only Linux wheel package is available for now.

BTW, DGL 2.0.0 will be released this month and it supports `torch 2.1.2`.

**Comment by frozenbugs** [comment]
We just release DGL 2.0 on Linux last friday, can you double check. @LiutongZhou

**Comment by LiutongZhou** [comment]
Yes, confirming DGL 2.0.0 installed with Pytorch 2.1.2. 

BTW, Pytorch 2.2 was out.
