### ISSUE TITLE
Mini-batch trainning

### ISSUE THREAD

**Issue by guohh516** [dmlc/dgl#6960]
## ❓ Questions and Help

I want to know how dgl implements **mini training** and which part of the source code I should look at. How does using **block** achieve mini training, is it also spmm? Where is the **source code**?

**Comment by frozenbugs** [comment]
You can understand mini-batch training by reading this doc: https://docs.dgl.ai/en/1.1.x/tutorials/large/index.html
And the code for mini-batch creation is here: https://github.com/dmlc/dgl/tree/master/python/dgl/graphbolt
