### ISSUE TITLE
[GraphBolt][CUDA] MultiGPU example test accuracy issue

### ISSUE THREAD

**Issue by mfbalin** [dmlc/dgl#7008]
## 🔨Work Item

**IMPORTANT:**
* This template is only for dev team to track project progress. For feature request or bug report, please use the corresponding issue templates.
* DO NOT create a new work item if the purpose is to fix an existing issue or feature request. We will directly use the issue in the project tracker.

Project tracker: https://github.com/orgs/dmlc/projects/2

## Description

When multiple GPUs are used, the accuracy is 20%. I am investigating which PR or commit caused the issue.

**Comment by mfbalin** [comment]
@TristonC

**Comment by TristonC** [comment]
Currently disabling the overlap feature bring the accuracy back. Thx @mfbalin
