### ISSUE TITLE
AttributeError: 'NDArray' object has no attribute 'device'

### ISSUE THREAD

**Issue by km1994** [dmlc/dgl#701]
## ❓ Questions and Help
when I run the code of NodeFlow and Sampling. it has a dug "AttributeError: 'NDArray' object has no attribute 'device'". how ccan i do?

**Comment by mufeili** [comment]
Could you please clarify about:
- What code are you referring to?
- What's your dgl version?
- How did you install it?

**Comment by tarung-ml** [comment]
1. I encountered the same error while going through the MovieLen Recommendation tutorial.
2. '0.3'
3. pip install dgl

**Comment by mufeili** [comment]
I just tried to install dgl with `pip install dgl` and run an example, which seems to work well. Does the "MovieLen Recommendation tutorial" requires gpu support? If so, `pip install dgl` is not enough. You can refer to [get started](https://www.dgl.ai/pages/start.html) for the wheel you need depending on the cuda drive you use.

**Comment by jermainewang** [comment]
Closed due to inactiveness. Please reopen if the issue still exists.

**Comment by bijayaVT** [comment]
I am having the same issue running the nodeflow example. I am using CUDA 10. I am able to run other examples.

**Comment by zheng-da** [comment]
please set up the DGL backend properly. By default, DGL uses Pytorch backend, but some of the tutorials are written in MXNet. The problem can be fixed by simply run "export DGLBACKEND=mxnet" on the shell.

**Comment by zheng-da** [comment]
@tarung-ml The tutorial where you got the problem is this one? https://github.com/dglai/KDD-2019-Hands-on/blob/master/3_recommender_system/Recommendation.ipynb
The tutorial already sets mxnet as the backend. It's weird that you still see this error.

**Comment by bijayaVT** [comment]
Thanks alot @zheng-da. It resolved the issue.

**Comment by MohsenFazaeli** [comment]
Reporting the same issue running paper number 33 code. Used Conda install -c dglteam dgl today and cuda 11 is my version.
Graph InfoClust: Leveraging Cluster-Level Node Information For Unsupervised Graph Representation Learning, Costas Mavromatis, George Karypis

**Comment by wanzhixiao** [comment]
> @tarung-ml The tutorial where you got the problem is this one? https://github.com/dglai/KDD-2019-Hands-on/blob/master/3_recommender_system/Recommendation.ipynb
> The tutorial already sets mxnet as the backend. It's weird that you still see this error.

Hi,the url are invalid,could you send another one? thanks
