### ISSUE TITLE
[Graphbolt] Fix the seed in sampling

### ISSUE THREAD

**Issue by peizhou001** [dmlc/dgl#7010]
## 🔨Work Item

The seed can't be fixed now because `concurrent hash map ` can't be determined. To fix the seed, we can provide a relatively low-efficient implementation but have determined behavior.

Project tracker: https://github.com/orgs/dmlc/projects/2

**Comment by mfbalin** [comment]
I know how to make the current implementation deterministic. We can discuss more.
