### ISSUE TITLE
is there any model can satisfy the inclusion feature of nodes in a graph

### ISSUE THREAD

**Issue by LoadingSugar** [dmlc/dgl#704]
For example, in social networks, each person's nodes include age feature, gender feature, preference feature, etc.

**Comment by mufeili** [comment]
Sorry I don't quite understand the question. For most examples we are using existing datasets where nodes have associated features. For example, for citation networks like Cora the node features are bag of words from documents.

**Comment by jermainewang** [comment]
Please checkout our examples and tutorials on GCN and so on. If you have further general questions, please use our discussion forum. Thanks!
