### ISSUE TITLE
Fail to install from source. (GPU-version)

### ISSUE THREAD

**Issue by Gibyeng** [dmlc/dgl#7040]
## 🐛 Bug

I try to build the code from source. But I cannot create the conda environment from the script in my machine.
Then I also create a conda env by "conda create" and set "DGL_HOME" to the repo folder. However, everytime I build the source, my machine crashes.

## To Reproduce
just run:
`
bash script/create_dev_conda_env.sh -f -g 11.8 -n dgl-dev-gpu -p 3.11.5 -s -t 2.1.1
`

The error message I got:
```
Pip subprocess error:
  error: subprocess-exited-with-error
  
  × python setup.py egg_info did not run successfully.
  │ exit code: 1
  ╰─> [6 lines of output]
      Traceback (most recent call last):
        File "<string>", line 2, in <module>
        File "<pip-setuptools-caller>", line 34, in <module>
        File "/tmp/pip-install-a2ats_je/torch-scatter_6a1b8a286a7c4beda16d4b18523d6e0f/setup.py", line 8, in <module>
          import torch
      ModuleNotFoundError: No module named 'torch'
      [end of output]
  
  note: This error originates from a subprocess, and is likely not a problem with pip.
error: metadata-generation-failed

× Encountered error while generating package metadata.
╰─> See above for output.

note: This is an issue with the package mentioned above, not pip.
hint: See above for details.

```
## Expected behavior

It seems during the installation of torch-scatter, torch is not imported properly. But I am quite sure torch has been installed in my system. 
```
>>>print(torch.__version__)
2.1.1
```
## Environment

 - DGL Version (e.g., 1.0): 2.0 (the one in repo)
 - Backend Library & Version (e.g., PyTorch 0.4.1, MXNet/Gluon 1.3):PyTorch 2.1.1
 - OS (e.g., Linux): linux
 - How you installed DGL (`conda`, `pip`, source): source
 - Build command you used (if compiling from source):   bash script/build_dgl.sh -g
 - Python version: 3.11.5
 - CUDA/cuDNN version (if applicable): 11.8
 - GPU models and configuration (e.g. V100): 2080ti
 - Any other relevant information:

**Comment by BarclayII** [comment]
Could you try it again?  `torch-scatter` was introduced during our test and it has been removed.  You were just unlucky I guess...

**Comment by Rhett-Ying** [comment]
@Gibyeng One more question, are you trying to install on linux machine directly or working within a docker container? We just found `torch-scatter` installation failure happens in docker container only.

**Comment by Rhett-Ying** [comment]
@caojy1998 FYI

**Comment by caojy1998** [comment]
Yes, I also try to re-execute this command. I think it would not cause an error now.

**Comment by Gibyeng** [comment]
> Could you try it again? `torch-scatter` was introduced during our test and it has been removed. You were just unlucky I guess...

It works fine to me now.

**Comment by Gibyeng** [comment]
> @Gibyeng One more question, are you trying to install on linux machine directly or working within a docker container? We just found `torch-scatter` installation failure happens in docker container only.

Directly on the machine. I tried again just now,  tihs time I can create the env with no problem.
