### ISSUE TITLE
DGLError: Argument "key" must be either str or utils.Index type.

### ISSUE THREAD

**Issue by matgreco** [dmlc/dgl#705]
When i try to convert a nx graph to dgl graph, i receive this error

DGLError: Argument "key" must be either str or utils.Index type.

The code for convert is the following:

I use this for get all attribute names in the nx graph
`list_name_attributes = list(set(np.array([list(graphnx.node[n].keys()) for n in graphnx.nodes()]).flatten()))`
 

And next, i use this to convert to a dgl graph

```
g_dgl = dgl.DGLGraph()
g_dgl.from_networkx(graphnx , node_attrs=dgl.utils.Index(list_name_attributes))
```

**Comment by mufeili** [comment]
Could you please print `list_name_attributes`?

**Comment by matgreco** [comment]
Sure,
```
list_name_attributes = list(set(np.array([list(graphnx.node[n].keys()) for n in graphnx.nodes()]).flatten()))
print(list_name_attributes)
```
output: [0, 1, 2]

So, the name of the attributes are int numbers. Then, i can get the attribute as follow:

`nx.get_node_attributes(graphnx, 2)`

where 2 is the attribute name, and i get the follow dictionary

`{0: 0, 1: 0, 2: 0, 3: 0, 4: 0, 5: 0, 6: 0, 7: 0, 8: 0, 9: 0, 10: 0, 11: 0, 12: 0, 13: 0, 14: 0, 15: 0, 16: 0, 17: 0, 18: 0, 19: 0, 20: 0, 21: 0, 22: 0, 23: 0, 24: 0, 25: 0, 26: 0, 27: 0, 28: 0, 29: 0, 30: 0, 31: 0, 32: 0, 33: 0, 34: 0, 35: 0, 36: 0, 37: 0, 38: 0, 39: 0, 40: 0, 41: 0, 42: 0, 43: 0, 44: 0, 45: 0, 46: 0, 47: 0, 48: 0, 49: 0, 50: 0, 51: 0, 52: 0, 53: 0, 54: 0, 55: 0, 56: 0, 57: 0, 58: 0, 59: 0, 60: 0, 61: 0, 62: 0, 63: 0, 64: 0, 65: 0, 66: 0, 67: 0, 68: 0, 69: 0, 70: 0, 71: 0, 72: 0, 73: 0, 74: 0, 75: 0, 76: 0, 77: 0, 78: 0, 79: 0, 80: 0, 81: 0, 82: 0, 83: 0, 84: 0, 85: 0, 86: 0, 87: 0, 88: 0, 89: 0, 90: 0, 91: 0, 92: 0, 93: 0, 94: 0, 95: 0, 96: 0, 97: 0, 98: 0, 99: 0, 100: 0, 101: 0, 102: 0, 103: 0, 104: 0, 105: 0, 106: 0, 107: 0, 108: 0, 109: 0, 110: 0, 111: 0, 112: 0, 113: 0, 114: 0, 115: 0, 116: 0, 117: 0, 118: 0, 119: 0, 120: 0, 121: 0, 122: 0, 123: 0, 124: 0, 125: 0, 126: 0, 127: 0, 128: 0, 129: 0, 130: 0, 131: 0, 132: 0, 133: 0, 134: 0, 135: 0, 136: 0, 137: 0, 138: 0, 139: 0, 140: 0, 141: 0, 142: 0, 143: 0, 144: 0, 145: 0, 146: 0, 147: 0, 148: 0, 149: 0, 150: 0, 151: 0, 152: 0, 153: 0, 154: 0, 155: 0, 156: 0, 157: 0, 158: 0, 159: 0, 160: 0, 161: 0, 162: 0, 163: 0, 164: 0, 165: 0, 166: 0, 167: 0, 168: 0, 169: 0, 170: 0, 171: 0, 172: 0, 173: 0, 174: 0, 175: 0, 176: 0, 177: 0, 178: 0, 179: 0, 180: 0, 181: 1, 182: 0, 183: 0, 184: 0, 185: 1, 186: 0, 187: 1, 188: 0, 189: 0, 190: 0, 191: 0, 192: 0, 193: 0, 194: 0}`

graphnx has 195 nodes and the attribute 2 are sparse.

**Comment by mufeili** [comment]
In `DGLGraph` objects we only allow the use of strings for the name of node/edge features. Users are not supposed to use `dgl.utils.Index`. So the solution would be to first convert `0, 1, 2` into `'0', '1', '2'`.

**Comment by jermainewang** [comment]
Closed due to inactiveness. Please reopen if the issue still exists.
