### ISSUE TITLE
W_f missing in TreeLSTM examples

### ISSUE THREAD

**Issue by michael-hahn** [dmlc/dgl#706]
## 🐛 Bug
In [this](https://github.com/dmlc/dgl/blob/master/examples/pytorch/tree_lstm/tree_lstm.py) example that claims to re-implement TreeLSTM based on the following paper:
_Improved Semantic Representations From Tree-Structured Long Short-Term Memory Networks_, there are missing `W_f` elements.

**Comment by yzh119** [comment]
This is intentional, not a bug. You may refer to this discussion thread: https://discuss.dgl.ai/t/question-about-the-tree-lstm-implementation/111/7.

**Comment by michael-hahn** [comment]
Thank you for your quick response. 
From the discussion thread, it seems like such a "trick" is quick task-specific. Regardless, great framework! Thanks for the work!
