### ISSUE TITLE
Confusion in " NodeFlow and Sampling "

### ISSUE THREAD

**Issue by WallE-Chang** [dmlc/dgl#707]
## 📚 Documentation
it's tutorial part 
============================================================== 
I have some confusion in "NodeFlow and Sampling (https://docs.dgl.ai/tutorials/models/5_giant_graph/1_sampling_mx.html)".

1. In GCNSampling.forword()
`            nf.block_compute(i,
                             fn.copy_src(src='h', out='m'),
                             lambda node : {'h': node.mailbox['m'].mean(axis=1)},
                             layer)`
I think  the meaning of  `lambda node : {'h': node.mailbox['m'].mean(dim=1)}`  is doing mean operation for meassages, which is equal to the red cyecle content of following formula:
![image](https://user-images.githubusercontent.com/22662737/61108470-f00d9000-a4b4-11e9-969f-764e00e9bb52.png)
Is there lacking of multiply |N(v)|  ?

**Comment by jermainewang** [comment]
@zheng-da

**Comment by jermainewang** [comment]
Closed due to inactivity. Please reopen if issue still exists.

**Comment by zheng-da** [comment]
ah, I just saw this issue. @WallE-Chang if you are still interested in the answer, here it is.
it depends on the aggregation function. The original paper I believe uses sum as the aggregation function, while our implementation uses mean aggregation. For mean, we don't need to rescale the aggregation result with the original neighborhood size.
