### ISSUE TITLE
Memory issues while loading all features at once ,any better way ?

### ISSUE THREAD

**Issue by laifi** [dmlc/dgl#708]
## ❓ Questions and Help

Hello ,
As i red from the documentation , to add features to the nodes we use the ndata attribute:
`g.ndata['feats']=array of features`
So , the question is , if we have large array of features let's say 100 value for each node it will be not possible to load all the features at once .
is there any solution to load the feature of that node (from word embedding model for example) only in the forward function when we pass by that node .
**Thank you !**

**Comment by mufeili** [comment]
This sounds like what our `sampler` intends to do. When the graph is large, to perform message passing and update over the whole graph can be intractable. Researchers have realized this issue and proposed sampling based training like in [GraphSAGE](https://arxiv.org/abs/1706.02216). Back to your problem, we can first sample a subgraph from the whole graph, and then set features or load the features of the subgraph into GPU. Check our [tutorial on sampling based training](https://docs.dgl.ai/tutorials/models/5_giant_graph/1_sampling_mx.html#sphx-glr-tutorials-models-5-giant-graph-1-sampling-mx-py).

**Comment by VoVAllen** [comment]
In your scenario, I think what you need is called row-sparse matrix, which means only sparse at the first dimension. However, currently only MXNet support this.

However, one solution is that you can attach tensor only on the subgraphs if I understand your need correctly. For example, you may want to only do the partial update by `send_and_recv` on certain edges. You can use `EdgeSubgraph` to get the subgraph first, and then attach the tensor you want to the subgraph, which reduce the memory cost.

**Comment by laifi** [comment]
Thank you @mufeili and @VoVAllen for your clear responses , and  i really like the  nice documentation ! :+1:  :+1: :+1:
