### ISSUE TITLE
Missing var in Documentation

### ISSUE THREAD

**Issue by wangguan1995** [dmlc/dgl#7104]
## 📚 Documentation
It seems like this g variable is missing?

https://github.com/dmlc/dgl/blob/master/docs/source/guide/minibatch-node.rst

<img width="731" alt="image" src="https://github.com/dmlc/dgl/assets/39621324/af83736c-ccd0-4be2-a3de-164837cba94f">

**Comment by Rhett-Ying** [comment]
Thanks for reporting this.

**Comment by wangguan1995** [comment]
feature -> dataset.feature?

**Comment by Rhett-Ying** [comment]
> feature -> dataset.feature?

updated.
