### ISSUE TITLE
[GraphBolt] Tensor Constructor for TorchBasedFeatureStore

### ISSUE THREAD

**Issue by kaansancak** [dmlc/dgl#7115]
## Motivation

I'm building a TorchBasedFeatureStore from a feature tensor. However, the current TorchBasedFeatureStore constructor necessitates writing the data to disk and then reading it back.

```
np.save("/tmp/node_feat.npy", self.data.x.numpy())
feat_data = [
    gb.OnDiskFeatureData(domain="node", name="feat",
        format="numpy", path="/tmp/node_feat.npy", in_memory=False),
]
self.gb_features = gb.TorchBasedFeatureStore(feat_data).to(self.device)
```        

## Pitch

A constructor that accepts a list of tensors directly.

**Comment by Rhett-Ying** [comment]
@frozenbugs what do you think

**Comment by Rhett-Ying** [comment]
Actually, you could directly instantiate with https://github.com/dmlc/dgl/blob/b0080d5bacf78d1b6f7e20652540d0e6da7c0e9c/python/dgl/graphbolt/impl/basic_feature_store.py#L12. Here's an example: https://github.com/dmlc/dgl/blob/00f33224038924c40229bb9c6f8dbe6d0b083960/tests/python/pytorch/graphbolt/test_dataloader.py#L18-L36

**Comment by kaansancak** [comment]
Thanks for the pointer!
