### ISSUE TITLE
[GraphBolt] extend regression tests for pipelining optimization

### ISSUE THREAD

**Issue by Rhett-Ying** [dmlc/dgl#7121]
## 🔨Work Item

**IMPORTANT:**
* This template is only for dev team to track project progress. For feature request or bug report, please use the corresponding issue templates.
* DO NOT create a new work item if the purpose is to fix an existing issue or feature request. We will directly use the issue in the project tracker.

Project tracker: https://github.com/orgs/dmlc/projects/2

## Description
we need to extend the regression tests to cover `sample_layer_neigbor` and dataloader's overlap_graph_sampling arguments to verify the optimization in https://github.com/dmlc/dgl/pull/7039.

**Comment by Rhett-Ying** [comment]
@mfbalin please add more context to help @caojy1998 on this work item.

**Comment by mfbalin** [comment]
We can modify the https://github.com/dmlc/dgl/blob/master/examples/sampling/graphbolt/node_classification.py to add a sampler option to switch between sample_neighbors and sample_layer_neighbors.

Also, a boolean argument called `--overlap_graph_fetch` to be passed into the `gb.Dataloader`, https://docs.dgl.ai/en/latest/generated/dgl.graphbolt.DataLoader.html#dgl.graphbolt.DataLoader.

The regression tests will then need to be updated to cover the combination of the relevant variables, note that `overlap_graph_fetch` is applicable only for the GPU.

**Comment by caojy1998** [comment]
Done in PR: https://github.com/dglai/DGL_scripts/pull/186
