### ISSUE TITLE
Problem about DGLGraph

### ISSUE THREAD

**Issue by mulinmeng** [dmlc/dgl#713]
## ❓ Questions and Help

I do not want the graph G change after a graph layer, just like an image pass a CNN layer, how can I handle it, just take GAT example code(Pytorch) as an example, I modify the code, taking g as an input data, however I find after the layer, even I do not store g, the g stored the parameter 'a1', 'a2', thanks!

def forward(self, inputs, g):
        h = self.feat_drop(inputs)  # NxD
        ft = self.fc(h).reshape((h.shape[0], self.num_heads, -1))  # NxHxD'
        head_ft = ft.transpose(0, 1)  # HxNxD'
        a1 = torch.bmm(head_ft, self.attn_l).transpose(0, 1)  # NxHx1
        a2 = torch.bmm(head_ft, self.attn_r).transpose(0, 1)  # NxHx1
        g.ndata.update({'ft' : ft, 'a1' : a1, 'a2' : a2})

**Comment by VoVAllen** [comment]
`g.ndata['ft']=ft` should work

**Comment by mufeili** [comment]
What we typically do is to pop up the data when the computation is finished. In your case, simply add

```Python
for fname in ['a1', 'a2']:
    g.ndata.pop(fname)
```

at [L74](https://github.com/dmlc/dgl/blob/master/examples/pytorch/gat/gat.py#L74)

**Comment by mulinmeng** [comment]
> What we typically do is to pop up the data that we don't want to keep when the computation is finished. In your case, simply add
> for fname in ['a1', 'a2']:
>     g.ndata.pop(fname)
> at L74.

Thanks! I had a bug at first and fear the 'pop' operation may affect  the back propagation. I worried too much.
