### ISSUE TITLE
[Feature Request] Frame for Graph Level Data

### ISSUE THREAD

**Issue by MilkshakeForReal** [dmlc/dgl#714]
## Motivation
If I have some global information about the graph, id for example, how do I add it to the DGLGraph object?

## Pitch

```
g = dgl.DGLGraph()
g.gdata['xx'] = xxx
```

**Comment by mufeili** [comment]
Simply try `g.xx=xxx`?

**Comment by MilkshakeForReal** [comment]
> Simply try `g.xx=xxx`?

Yes it works, but the problem is that if I run `print(g)` the attributions would not show up

**Comment by MilkshakeForReal** [comment]
One can do `dir(g)` to see the additional data but there are a bunch of attributions, it's very hard to check which one is what I call `gdata`

**Comment by mufeili** [comment]
@MilkshakeForReal That's a good point. Yeah, we should probably support this.

**Comment by jermainewang** [comment]
Hi @MilkshakeForReal @mufeili @VoVAllen, I created an RFC for this feature. Let's move to that thread for discussion.
