### ISSUE TITLE
Bug when using diffpooling

### ISSUE THREAD

**Issue by xuChenSJTU** [dmlc/dgl#718]
## To Reproduce

1.run the example in /examples/diffpool/train.py  (if you cannot download the dataset inside the code, you can download by hand)
2.

![image](https://user-images.githubusercontent.com/24096174/61463077-493e5d80-a9a6-11e9-8eb5-217e0bf936fd.png)

It seems there is something wrong with the DGL code in the following part:
![image](https://user-images.githubusercontent.com/24096174/61463283-a9350400-a9a6-11e9-9505-3eaf9c1b5c58.png)

Do you have any advice? 

Thanks very much. I want to use the diffpool in DGL but it does not work.

## Environment

 - DGL Version (e.g., 1.0):
 - Backend Library & Version (e.g., PyTorch 0.4.1, MXNet/Gluon 1.3):
 - OS (e.g., Linux):
 - How you installed DGL (`conda`, `pip`, source):
 - Build command you used (if compiling from source):
 - Python version:
 - CUDA/cuDNN version (if applicable):
 - GPU models and configuration (e.g. V100):
 - Any other relevant information:

**Comment by xuChenSJTU** [comment]
![image](https://user-images.githubusercontent.com/24096174/61463478-0a5cd780-a9a7-11e9-8b1b-26e3fa15453c.png)

Add this part.

**Comment by VoVAllen** [comment]
You can add `--cuda -1` to disable using cuda or install dgl version which has gpu support. We should fix this default setting @HQ01

**Comment by VoVAllen** [comment]
This error is mainly saying there's gpu operation but dgl wasn't compiled with gpu support

**Comment by jermainewang** [comment]
@xuChenSJTU Has this been resolved?

**Comment by jermainewang** [comment]
Closed due to inactiveness. Could reopen if the issue still exists.
