### ISSUE TITLE
CUDA12.2 support?

### ISSUE THREAD

**Issue by htc20010403** [dmlc/dgl#7187]
My configuration is pytorch2.0.1+CUDA12.2+python3.10.The error message is “Check failed: allow_missing: Device API cuda is not enabled. Please install the cuda version of dgl”.
In the past period of time, I have tried dgl2.0.0, which is compatible with the dgl version of CUDA12.1, but it did not run well.May I ask if you can provide me with some ideas to solve this mismatch problem?

**Comment by rudongyu** [comment]
close as the duplication of https://discuss.dgl.ai/t/how-to-use-dgl-in-cuda12-2/4265
