### ISSUE TITLE
TGN loss calculation error

### ISSUE THREAD

**Issue by ManlioWu** [dmlc/dgl#7213]
## To Reproduce

1.
1.
1.

## Environment

 - DGL Version (e.g., 0.9.x):
 - Backend Library & Version (e.g., PyTorch 0.4.1, MXNet/Gluon 1.3):
 - OS (e.g., Linux):
 - How you installed DGL (`conda`, `pip`, source):
 - Build command you used (if compiling from source):
 - Python version:
 - CUDA/cuDNN version (if applicable):
 - GPU models and configuration (e.g. V100):
 - Any other relevant information:

## Additional context

In `[train.py](https://github.com/dmlc/dgl/blob/0.9.x/examples/pytorch/tgn/train.py#L27)`, does the total_loss need to be averaged by the num_samples? Now it is the sum of all batch_loss.

**Comment by frozenbugs** [comment]
Can you double check the original code by the TGN author, if you believe it should be averaged, feel free to file an PR and link your justification.

**Comment by jermainewang** [comment]
Hi @ManlioWu , I am closing this issue assuming you are happy about our response. Feel free to follow up and reopen the issue if you have more questions with regard to our response.
