### ISSUE TITLE
TypeError: knn_graph() got an unexpected keyword argument 'algorithm'

### ISSUE THREAD

**Issue by Random-junhao** [dmlc/dgl#7221]
I tried to execute g = dgl.knn_graph(data, k=4, algorithm='bruteforce-sharemem'), but the error message showed TypeError: knn_graph() got an unexpected keyword argument 'algorithm'. can anyone help me？

**Comment by frozenbugs** [comment]
What's your DGL version? Can you follow our DGL template for bug report?

**Comment by jermainewang** [comment]
Hi @Random-junhao , I am closing this issue assuming you are happy about our response. Feel free to follow up and reopen the issue if you have more questions with regard to our response.
