### ISSUE TITLE
Different feature sizes for different node types .

### ISSUE THREAD

**Issue by laifi** [dmlc/dgl#723]
Hi ,
I am working in a rgcn model with different node entities (limit number of types about 20 ) , each node entity type have different feature size .
My idea is to create a dictionary of weights while the key is the edge source node index , so i can get  the feature size ( incoming message ) from the neighbor node
i didn't find similar work when the size of feature arrays depend on the entity
**What do you think , is there a better solution for this ?**
Or if you know any similar work or research , please let me know :smile: .
I already start training my solution using dgl , the training works if the entities have the same feature sizes , because i can easily convert the array of features to torch.tensor but i cannot convert it to torch tensor for different feature sizes , or actually it's possible with numpy as array of lists ,but the only supported types for torch.tensor are: double, float, float16, int64, int32, and uint8.
If i pass a numpy array to` g.ndata.update( )` i get

>  'numpy.ndarray' object has no attribute 'device'

So , it seems dgl works only with torch tensors ! i want to use dgl but i am blocked with it now . 

_Thank you!_

**Comment by jermainewang** [comment]
Hey @laifi, that's a heterograph scenario and we are pushing this feature quite hard. It will be included in our next release. Just out of curiosity, could you share about what kind of dataset are you working on? Maybe we could make a demo for that.

**Comment by laifi** [comment]
@jermainewang thank you for replying , actually i'm creating fake data for testing now ( memory issues).
But , the data i want to use  from linkedin and i want to create a big graph for all the informations in a profile and make link prediction out of them .
But , i think for sure i'm not the first person who think about using different node entities with different features and sizes , another option i'm thinking on is to use a max_length for features and pad the features with zeros as we do in NLP :thinking:

**Comment by yzh119** [comment]
@laifi I understand your request, that's part of our heterograph plan. At current stage, a workaround is to project the feature of each kind of node entities to a fixed size, for example:
```python
g.nodes[nids_0]['h'] = proj_0(feat_0)
g.nodes[nids_1]['h'] = proj_1(feat_1)
...
```

**Comment by laifi** [comment]
@yzh119 Actually , i found that we can use different feature sizes by node but we should store in DGLgraph nodes only ids , and outside create a function that can map the ids to features and call this function in the propagation function to get the features , it would be hard to code but still possible !

**Comment by jermainewang** [comment]
@laifi You are totally right. In fact, if you case is each node having different feature sizes, then I would suggest your way of implementing it. Our heterograph structure is for the case where the number of types is not large (up to 100).

**Comment by jermainewang** [comment]
Closed. Please checkout the new heterograph APIs.
