### ISSUE TITLE
DGL: Inconsistent Results and Low Precision on GPU Despite Fixed Seed and Deterministic Settings for the GPU 

### ISSUE THREAD

**Issue by walidgeuttala** [dmlc/dgl#7237]
## ❓ Questions and Help
I'm using DGL, but I'm getting indeterminate results with a large gap range, even after fixing the seed of the networks. However, when I choose to use the CPU device, the results are deterministic. Why is that, and how can I fix it? Even the precision of the deterministic results is very low, as shown in the examples.

the full code I use : https://github.com/walidgeuttala/gnn_clean_code

I'm using CUDA 12.

I want to use the GPU rather than the CPU because I have a lot of experiments that I need to run, and I can't run them using the CPU. These experiments must be deterministic.

Before importing Torch, I run the following code:

import os
os.environ['CUBLAS_WORKSPACE_CONFIG'] = ':4096:8'

And before running any experiments, I fix the seed using this function:

def set_random_seed(seed=0):
    random.seed(seed)
    np.random.seed(seed)
    torch.manual_seed(seed)
    torch.use_deterministic_algorithms(True)
    if torch.cuda.is_available():
        torch.cuda.manual_seed(seed)
        torch.cuda.manual_seed_all(seed)
        torch.backends.cudnn.deterministic = True
        torch.backends.cudnn.benchmark = False
    dgl.random.seed(seed)

You can find the full code that I'm using at: [link to your code repository] (please check the main.py and network.py files to see why this behavior happened).

GPU Results:

Epoch 10: loss=0.3299
Epoch 20: loss=0.2724
Epoch 30: loss=0.2087
Epoch 40: loss=0.1503
Epoch 50: loss=0.1030
small_test : 0.6169275665283203, medium_test 5.106365718841553
Trial 1/1
Epoch 10: loss=0.3298
Epoch 20: loss=0.2728
Epoch 30: loss=0.2085
Epoch 40: loss=0.1479
Epoch 50: loss=0.1103
small_test : 0.07393280506134033, medium_test 1.6552714157104491

CPU Results:

Trial 1/1
Epoch 10: loss=0.3307
Epoch 20: loss=0.2711
Epoch 30: loss=0.1983
Epoch 40: loss=0.1489
Epoch 50: loss=0.1106
small_test : 0.12136419773101807, medium_test 1.9430083656311035
Trial 1/1
Epoch 10: loss=0.3307
Epoch 20: loss=0.2711
Epoch 30: loss=0.1983
Epoch 40: loss=0.1489
Epoch 50: loss=0.1106
small_test : 0.12136419773101807, medium_test 1.9430083656311035

**Comment by paulohdscoelho** [comment]
I'm facing the same problem. I am using the oficial Docker image provided by DGL and, even when running the SAGE example twice, I get different acc values.

**Comment by paulohdscoelho** [comment]
> > I'm facing the same problem. I am using the oficial Docker image provided by DGL and, even when running the SAGE example twice, I get different acc values.
> > (edit) it seems to be a confirmed bug. Checkout the [Issue](https://github.com/dmlc/dgl/issues/4155)
> 
> No, it is a different case for me. In the [issue](https://github.com/dmlc/dgl/issues/4155), when they also use the CPU, it gives indeterminate results, which in my case is different, as using the CPU results in deterministic outcomes

Save the initial weights of the model and reuse them in each run, as suggested by [jermainewang](https://github.com/jermainewang), did not solve your problem?

**Comment by walidgeuttala** [comment]
> > > I'm facing the same problem. I am using the oficial Docker image provided by DGL and, even when running the SAGE example twice, I get different acc values.
> > > (edit) it seems to be a confirmed bug. Checkout the [Issue](https://github.com/dmlc/dgl/issues/4155)
> > 
> > 
> > No, it is a different case for me. In the [issue](https://github.com/dmlc/dgl/issues/4155), when they also use the CPU, it gives indeterminate results, which in my case is different, as using the CPU results in deterministic outcomes
> 
> Save the initial weights of the model and reuse them in each run, as suggested by [jermainewang](https://github.com/jermainewang), did not solve your problem?

Yes I tried it but the same results.

**Comment by jermainewang** [comment]
Root cause confirmed in #7241 . The underlying cusparse algorithm DGL currently uses is not deterministic. It will requires some fixes in the C++ library. Closing this issue. Let's move future discussion to there.
