### ISSUE TITLE
Does dgl support undigraph

### ISSUE THREAD

**Issue by Smilexuhc** [dmlc/dgl#727]
## ❓ Questions and Help
I found that dgl seems to only support directed graph. I had to add some codes for precessing undirected graph.

**Comment by jermainewang** [comment]
Currently no. Could you use a bi-directional graph? This [`to_directed`](https://docs.dgl.ai/generated/dgl.transform.to_bidirected.html#dgl.transform.to_bidirected) API could be useful.

**Comment by Smilexuhc** [comment]
Thank your for your reply.
