### ISSUE TITLE
[GraphBolt] CUDA nightly installation command installs CPU version

### ISSUE THREAD

**Issue by mfbalin** [dmlc/dgl#7276]
## 🐛 Bug

`pip install --pre dgl -f https://data.dgl.ai/wheels-test/cu121/repo.html` installs the CPU version.

The multi-GPU tutorial fails: https://docs.dgl.ai/en/latest/stochastic_training/multigpu_node_classification.html

```
AttributeError: '_OpNamespace' 'graphbolt' object has no attribute 'set_max_uva_threads'
```

## To Reproduce

1.
1.
1.

## Environment

 - DGL Version (e.g., 1.0):
 - Backend Library & Version (e.g., PyTorch 0.4.1, MXNet/Gluon 1.3):
 - OS (e.g., Linux):
 - How you installed DGL (`conda`, `pip`, source):
 - Build command you used (if compiling from source):
 - Python version:
 - CUDA/cuDNN version (if applicable):
 - GPU models and configuration (e.g. V100):
 - Any other relevant information:

**Comment by mfbalin** [comment]
@frozenbugs

**Comment by mfbalin** [comment]
Or is there a problem with building the nightly packages? It looks like latest nightly wheel was built in February.

**Comment by Rhett-Ying** [comment]
Disk space is full on the build machine which results in build failure. I've just cleaned up and nightly build should be available tmr

**Comment by mfbalin** [comment]
> Disk space is full on the build machine which results in build failure. I've just cleaned up and nightly build should be available tmr

Great, that was a quick fix! I am sure the issue is resolved but I will check the tutorial tomorrow to make sure it runs successfully before closing this.

**Comment by mfbalin** [comment]
Collecting dgl
  Downloading https://data.dgl.ai/wheels-test/cu121/dgl-2.2a240407%2Bcu121-cp310-cp310-manylinux1_x86_64.whl (717.7 MB)
     ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 717.7/717.7 MB 2.0 MB/s eta 0:00:00
