### ISSUE TITLE
[build] nightly build is down due to gcc 8.5.0 does not fully support c++17

### ISSUE THREAD

**Issue by Rhett-Ying** [dmlc/dgl#7278]
## 🔨Work Item

**IMPORTANT:**
* This template is only for dev team to track project progress. For feature request or bug report, please use the corresponding issue templates.
* DO NOT create a new work item if the purpose is to fix an existing issue or feature request. We will directly use the issue in the project tracker.

Project tracker: https://github.com/orgs/dmlc/projects/2

## Description
For now, we're using `nvidia/cuda:12.1.0-cudnn8-devel-ubi8` docker base image for building. And the default gcc version is `8.5.0`. When building with it, below error is thrown:
```
/opt/dgl/graphbolt/src/cuda/extension/unique_and_compact_map.cu(151): error: namespace "std" has no member "exclusive_scan" 
```
This API is introduced by https://github.com/dmlc/dgl/pull/7239

**Comment by Rhett-Ying** [comment]
@mfbalin FYI

**Comment by Rhett-Ying** [comment]
@mfbalin could we replace it with `std::partial_sum`? how much is the performance downgrade?

**Comment by Rhett-Ying** [comment]
or any counterpart from `torch`?

**Comment by mfbalin** [comment]
I was eagerly waiting for today's regression results. When do you think the next report is going to go out?

**Comment by Rhett-Ying** [comment]
regression build is not affected by this issue. But regression build is down last night due to other issue. I've fixed it and report is supposed to be ready tmr,  around 1 o'clock AM, UTC.
