### ISSUE TITLE
[Build]  CUDA atomics are only supported for sm_60 and up on *nix and sm_70 and up on Windows

### ISSUE THREAD

**Issue by Rhett-Ying** [dmlc/dgl#7281]
## 🐛 Bug

Build based on below commit failed with cuda 11.7.
```
commit 7b470eb0faac755a52cc802a6bfdca44f5e381a9 (HEAD -> master, origin/master, origin/HEAD)
Author: Muhammed Fatih BALIN <m.f.balin@gmail.com>
Date:   Mon Apr 8 01:12:18 2024 -0400

    [GraphBolt] Quick fix for GCC 8 (#7279)
```
may be caused by
```
CUDA_ARCH='35;37;50;60;70;75;80;86'
export TORCH_CUDA_ARCH_LIST='3.5 3.7 5.0 6.0 7.0 7.5 8.0 8.6'
cmake -DCUDA_ARCH_BIN=$CUDA_ARCH" ...
```

```
In file included from /opt/dgl/third_party/cccl/libcudacxx/include/cuda/std/detail/libcxx/include/atomic:733,                 
                 from /opt/dgl/third_party/cccl/libcudacxx/include/cuda/std/atomic:18,                                        
                 from /opt/dgl/graphbolt/../third_party/cccl/libcudacxx/include/cuda/atomic:14,                               
                 from /opt/dgl/graphbolt/../third_party/cuco/include/cuco/detail/open_addressing/kernels.cuh:22,              
                 from /opt/dgl/graphbolt/../third_party/cuco/include/cuco/detail/open_addressing/open_addressing_impl.cuh:21, 
                 from /opt/dgl/graphbolt/../third_party/cuco/include/cuco/static_map.cuh:21,                                  
                 from /opt/dgl/graphbolt/src/cuda/extension/unique_and_compact_map.cu:9:                                      
/opt/dgl/third_party/cccl/libcudacxx/include/cuda/std/detail/libcxx/include/support/atomic/atomic_cuda.h:12:4: error: #error "CUDA atomics are only supported for sm_60 and up on *nix and sm_70 and up on Windows."                                        
 #  error "CUDA atomics are only supported for sm_60 and up on *nix and sm_70 and up on Windows."                             
    ^~~~~                                                                                                                     
make[5]: *** [CMakeFiles/graphbolt_pytorch_2.0.0_cuda.dir/build.make:82: CMakeFiles/graphbolt_pytorch_2.0.0_cuda.dir/src/cuda/extension/unique_and_compact_map.cu.o] Error 1
```

## Environment

 - DGL Version (e.g., 1.0): master
 - Backend Library & Version (e.g., PyTorch 0.4.1, MXNet/Gluon 1.3): torch 2.0.0
 - OS (e.g., Linux): Linux
 - How you installed DGL (`conda`, `pip`, source):
 - Build command you used (if compiling from source):
 - Python version:
 - CUDA/cuDNN version (if applicable): 11.7
 - GPU models and configuration (e.g. V100):
 - Any other relevant information:

**Comment by mfbalin** [comment]
@Rhett-Ying The architecture list comes from DGL for GraphBolt. Can you simply set those variables to `70` only?

**Comment by mfbalin** [comment]
CUDA_ARCH='70'
export TORCH_CUDA_ARCH_LIST='7.0'

**Comment by mfbalin** [comment]
See here: we pass the TORCH_CUDA_ARCH_LIST as Volta only.
https://github.com/dmlc/dgl/blob/7b470eb0faac755a52cc802a6bfdca44f5e381a9/graphbolt/build.sh#L19

**Comment by mfbalin** [comment]
@Rhett-Ying I believe we should be able to drop the use of `CUDA_ARCH` from the scripts. Setting `TORCH_CUDA_ARCH_LIST=Volta` should be enough.

**Comment by mfbalin** [comment]
#7239 was merged. There, we have an extension library that has to be compiled for 70 and up. However, when we use CUDA_ARCH or TORCH_CUDA_ARCH_LIST, it adds to nvcc compile arguments those architectures and overrides our cmake cuda architecture logic.

**Comment by mfbalin** [comment]
Now, we rely on the cmake way of selecting architectures: https://github.com/dmlc/dgl/blob/7b470eb0faac755a52cc802a6bfdca44f5e381a9/graphbolt/CMakeLists.txt#L96

**Comment by mfbalin** [comment]
The full architecture list comes from the CUDA architecture logic in DGL, from here:
https://github.com/dmlc/dgl/blob/master/cmake/modules/CUDA.cmake

**Comment by Rhett-Ying** [comment]
so even with cuda 11.7, DGL requires sm70+?

**Comment by mfbalin** [comment]
No, DGL supports all GPUs. However, if we set architectures using some constructs, it sets it for all targets. However, we need to compile the cuda extension library with 70+ only. Thus, only for GraphBolt, we need to set architectures using the cmake way of doing it.

**Comment by mfbalin** [comment]
That is why I override `TORCH_CUDA_ARCH_LIST` here for GraphBolt:
https://github.com/dmlc/dgl/blob/7b470eb0faac755a52cc802a6bfdca44f5e381a9/graphbolt/CMakeLists.txt#L96
The architecture list is provided by DGL instead.

**Comment by Rhett-Ying** [comment]
But graphbolt is in  the core of DGL for now, so any requirements from graphbolt applies to DGL, right?

**Comment by mfbalin** [comment]
If you have time, we can huddle on slack for 5 mins and I can explain it quicker.

**Comment by mfbalin** [comment]
@Rhett-Ying Is it safe to close this issue?

**Comment by Rhett-Ying** [comment]
let's wait for nightly build succeed. I will keep an eye on it

**Comment by Rhett-Ying** [comment]
confirmed. it works well in nightly build
