### ISSUE TITLE
[GraphBolt][Examples] Folder Location

### ISSUE THREAD

**Issue by mfbalin** [dmlc/dgl#7324]
## 🔨Work Item

**IMPORTANT:**
* This template is only for dev team to track project progress. For feature request or bug report, please use the corresponding issue templates.
* DO NOT create a new work item if the purpose is to fix an existing issue or feature request. We will directly use the issue in the project tracker.

Project tracker: https://github.com/orgs/dmlc/projects/2

## Description

Can we do `git mv examples/sampling/graphbolt graphbolt_examples`?

Since GraphBolt is buried deep in DGL, the documentation takes very little space on the website, the examples are 3 levels deep in the root examples folder etc. I believe we are not able to advertise our work well enough. I thought moving graphbolt examples to its separate repository could increase its visibility.

@frozenbugs @TristonC

**Comment by frozenbugs** [comment]
Sure, feel free to do so.
