### ISSUE TITLE
[GraphBolt][CUDA] Remove `extra_attrs` argument of `copy_to`

### ISSUE THREAD

**Issue by mfbalin** [dmlc/dgl#7331]
## 🔨Work Item

**IMPORTANT:**
* This template is only for dev team to track project progress. For feature request or bug report, please use the corresponding issue templates.
* DO NOT create a new work item if the purpose is to fix an existing issue or feature request. We will directly use the issue in the project tracker.

Project tracker: https://github.com/orgs/dmlc/projects/2

## Description

@frozenbugs I believe we copy all attributes automatically now so is there any use left for this parameter?

**Comment by mfbalin** [comment]
@yxy235

**Comment by yxy235** [comment]
> @yxy235 can this be done now that seeds and minibatch refactor is done? Would you like to handle it?

OK. I think this attribute can be removed.
