### ISSUE TITLE
EdgeBatch.edges() call attempts tuple item assignment

### ISSUE THREAD

**Issue by lukovnikov** [dmlc/dgl#734]
## 🐛 Bug

TypeError: 'tuple' object does not support item assignment

## To Reproduce

```python
import dgl
import torch
g = dgl.DGLGraph()
g.add_nodes(11)
h = torch.rand(11, 7)
g.nodes[:].data["h"] = h
g.add_edges(list(range(10)), 10, {"etype": torch.ones(10)})
g.add_edges(list(range(10)), list(range(10)), {"etype": torch.zeros(10)})
qnodes = torch.tensor([10])
def edgefilter(eb: dgl.EdgeBatch):
    ret = (eb.edges()[1].unsqueeze(0) == qnodes.unsqueeze(1)).any(0)
    ret &= eb.data["etype"] == 1
    return ret

g.filter_edges(edgefilter)
```

This throws the above mentioned exception, from the call to EdgeView.edges()

## Expected behavior

Not to throw errors.

## Environment

 - DGL Version (e.g., 1.0): **0.3**
 - Backend Library & Version (e.g., PyTorch 0.4.1, MXNet/Gluon 1.3): **PyTorch 1.1.0**
 - OS (e.g., Linux): **Windows**
 - How you installed DGL (`conda`, `pip`, source):
 - Build command you used (if compiling from source):
 - Python version: **3.6**
 - CUDA/cuDNN version (if applicable): N/A
 - GPU models and configuration (e.g. V100): None
 - Any other relevant information:

**Comment by yzh119** [comment]
@lukovnikov solved in #747 .
