### ISSUE TITLE
[io_uring] Disable liburing as it's not quite stable

### ISSUE THREAD

**Issue by Rhett-Ying** [dmlc/dgl#7353]
## 🔨Work Item

**IMPORTANT:**
* This template is only for dev team to track project progress. For feature request or bug report, please use the corresponding issue templates.
* DO NOT create a new work item if the purpose is to fix an existing issue or feature request. We will directly use the issue in the project tracker.

Project tracker: https://github.com/orgs/dmlc/projects/2

**Comment by Rhett-Ying** [comment]
https://github.com/dmlc/dgl/issues/7277 depends on this work item.

**Comment by mfbalin** [comment]
@Rhett-Ying could you explain what instability issues io_uring has?

**Comment by Rhett-Ying** [comment]
read access may cause segmentation fault.

**Comment by mfbalin** [comment]
I see. Then we can disable it until a solution is found. I thought that we are giving up on the feature entirely.
