### ISSUE TITLE
[GraphBolt] Remove workaround for `DILL_AVAILABLE` in torch 2.3.0

### ISSUE THREAD

**Issue by Rhett-Ying** [dmlc/dgl#7387]
## 🔨Work Item

**IMPORTANT:**
* This template is only for dev team to track project progress. For feature request or bug report, please use the corresponding issue templates.
* DO NOT create a new work item if the purpose is to fix an existing issue or feature request. We will directly use the issue in the project tracker.

Project tracker: https://github.com/orgs/dmlc/projects/2

**Comment by Rhett-Ying** [comment]
see https://github.com/dmlc/dgl/pull/7383#

**Comment by mfbalin** [comment]
https://github.com/pytorch/pytorch/issues/125425#issuecomment-2108698508

**Comment by Rhett-Ying** [comment]
back-compatible is available since torch 2.3.1. we should make change on current workaround in DGL: https://github.com/dmlc/dgl/blob/7c3d418e88fe0a20f56971ec4ca54cd026bdfe0d/python/dgl/graphbolt/base.py#L9-L16

**Comment by mfbalin** [comment]
Fixed by #7474.
