### ISSUE TITLE
Adding classes in RGCN example to the main body of library

### ISSUE THREAD

**Issue by sharifza** [dmlc/dgl#742]
## 🚀 Feature

I suggest to add the classes in RGCN example to the main body of the library. 
## Motivation

I'm using RGCN in another library and I think it would be much more convenient for everyone like me to directly import e.g. the layers from the library rather than adding them from the examples.

**Comment by jermainewang** [comment]
I think that's a good idea. Will do.

**Comment by jermainewang** [comment]
@sharifza created a PR on this. Currently implemented the pytorch module (basically copy-paste the codes from the example). Please take a look. Will merge after the documentation and mxnet modules are finished.

**Comment by sharifza** [comment]
Looks good, thanks. Should we include the base class that uses the layers, also somewhere in the library?
https://github.com/dmlc/dgl/blob/565f0c88fc5cfbcfd5476da8146e92c793af4834/examples/pytorch/rgcn/model.py#L3

**Comment by jermainewang** [comment]
@sharifza Sorry didn't notice your comment here. The module has been merged and it now has only one class `RelGraphConv`. The regularization ("basis" or "bdd") is an option. If you have other questions, please reopen this issue. Thanks!
