### ISSUE TITLE
Early stopping for gat

### ISSUE THREAD

**Issue by EtoDemerzel0427** [dmlc/dgl#743]
## 🚀 Feature
Add early stopping mechanism for GAT.

## Motivation
Noticed that the performance of GAT on CiteSeer and Pubmed is lower than the reported results in the paper. And after checking the issues of the official implementation, I noticed some people have asked about this, and the author said this is due to early stopping(Check [this](https://github.com/PetarV-/GAT/issues/14) and [this](https://github.com/PetarV-/GAT/issues/12)).

## Alternatives

None.

## Pitch

 You may add one command line argument to enable early stopping, since for Cora it is needless.

**Comment by jermainewang** [comment]
You are right. We should add this. @VoVAllen could you please help?

**Comment by derkbreeze** [comment]
@jermainewang Hi Minjie,  may I know what's the meaning of the labels in PPI dataset? Cause I noticed each node can have multiple 1's and zeros in it's label. I just wonder what's the meaning of different position's 1. e.g. a 121 dimension label can have [1 0 0 1 1 0 1 0 0...1 1 0 ]. I would appreciate if you can tell me.

**Comment by mufeili** [comment]
@derkbreeze To my knowledge, [GraphSAGE](https://arxiv.org/abs/1706.02216) is the first work to use that dataset and I'm quoting their description here:

> We classify protein roles—in terms of their cellular functions from gene ontology—in various protein-protein interaction (PPI) graphs, with each graph corresponding to a different human tissue [41]. We use positional gene sets, motif gene sets and immunological signatures as features and gene ontology sets as labels (121 in total), collected from the Molecular Signatures Database [34]. The average graph contains 2373 nodes, with an average degree of 28.8. We train all algorithms on 20 graphs and then average prediction F1 scores on two test graphs (with two other graphs used for validation).

**Comment by VoVAllen** [comment]
Thanks! I'll look into this

**Comment by derkbreeze** [comment]
> @derkbreeze To my knowledge, [GraphSAGE](https://arxiv.org/abs/1706.02216) is the first work to use that dataset and I'm quoting their description here:
> 
> > We classify protein roles—in terms of their cellular functions from gene ontology—in various protein-protein interaction (PPI) graphs, with each graph corresponding to a different human tissue [41]. We use positional gene sets, motif gene sets and immunological signatures as features and gene ontology sets as labels (121 in total), collected from the Molecular Signatures Database [34]. The average graph contains 2373 nodes, with an average degree of 28.8. We train all algorithms on 20 graphs and then average prediction F1 scores on two test graphs (with two other graphs used for validation).

Thank you Mufei for your help!
