### ISSUE TITLE
Validation out of memory

### ISSUE THREAD

**Issue by TZWwww** [dmlc/dgl#745]
## ❓ Questions and Help

Before proceeding, please note that we recommend
using our discussion forum (https://discuss.dgl.ai) for
general questions. As a result, this issue will
likely be CLOSED shortly.

I implement GAT in this repo with little change(I send different graph for each data rather than a unique graph in the __init__). However, training if good, the validation would meet out of memory problem. I check every single step. In validation, each forward would use new memory. How's that going? Thanks for answers advance!

**Comment by VoVAllen** [comment]
Hi,

How did you install dgl? It should be fixed on the current master branch. (related [PR](https://github.com/dmlc/dgl/pull/692))

@BarclayII What's our lateset binary release of DGL?

**Comment by TZWwww** [comment]
This is my code, it is batched

     class GraphAttention(nn.Module):
       def __init__(self,
                 in_dim,
                 out_dim,
                 num_heads,
                 feat_drop,
                 attn_drop,
                 alpha,
                 residual=False):
        super(GraphAttention, self).__init__()
        self.num_heads = num_heads
        self.fc = nn.Linear(in_dim, num_heads * out_dim, bias=False)
        if feat_drop:
            self.feat_drop = nn.Dropout(feat_drop)
        else:
            self.feat_drop = lambda x : x
        if attn_drop:
            self.attn_drop = nn.Dropout(attn_drop)
        else:
            self.attn_drop = lambda x : x
        self.attn_l = nn.Parameter(torch.Tensor(size=(1, num_heads, out_dim)))
        self.attn_r = nn.Parameter(torch.Tensor(size=(1, num_heads, out_dim)))
        nn.init.xavier_normal_(self.fc.weight.data, gain=1.414)
        nn.init.xavier_normal_(self.attn_l.data, gain=1.414)
        nn.init.xavier_normal_(self.attn_r.data, gain=1.414)
        self.leaky_relu = nn.LeakyReLU(alpha)
        self.softmax = edge_softmax
        self.residual = residual
        if residual:
            if in_dim != out_dim:
                self.res_fc = nn.Linear(in_dim, num_heads * out_dim, bias=False)
                nn.init.xavier_normal_(self.res_fc.weight.data, gain=1.414)
            else:
                self.res_fc = None

    def forward(self, g, inputs):
        # prepare

        h = self.feat_drop(inputs)  # NxD
        ft = self.fc(h).reshape((h.shape[0], self.num_heads, -1))  # NxHxD'
        a1 = (ft * self.attn_l).sum(dim=-1).unsqueeze(-1) # N x H x 1
        a2 = (ft * self.attn_r).sum(dim=-1).unsqueeze(-1) # N x H x 1
        g.ndata.update({'ft' : ft, 'a1' : a1, 'a2' : a2})
        # 1. compute edge attention
        g.apply_edges(self.edge_attention)
        # 2. compute softmax
        self.edge_softmax(g)
        # 3. compute the aggregated node features scaled by the dropped,
        # unnormalized attention values.
        g.update_all(fn.src_mul_edge('ft', 'a_drop', 'ft'), fn.sum('ft', 'ft'))
        ret = g.ndata.pop('ft')
        # 4. residual
        if self.residual:
            if self.res_fc is not None:
                resval = self.res_fc(h).reshape((h.shape[0], self.num_heads, -1))  # NxHxD'
            else:
                resval = torch.unsqueeze(h, 1)  # Nx1xD'
            ret = resval + ret
        return ret

    def edge_attention(self, edges):
        # an edge UDF to compute unnormalized attention values from src and dst
        a = self.leaky_relu(edges.src['a1'] + edges.dst['a2'])
        return {'a' : a}

    def edge_softmax(self, g):
        attention = self.softmax(g, g.edata.pop('a'))
        # Dropout attention scores and save them
        g.edata['a_drop'] = self.attn_drop(attention)

    class GAT(nn.Module):
    def __init__(self, opt):
        super(GAT, self).__init__()
        self.num_layers = opt['num_kb_layers']
        self.gat_layers = nn.ModuleList()

        # input projection (no residual)
        self.gat_layers.append(GraphAttention(
            opt['in_dim'], opt['num_hidden'], opt['heads'][0], opt['feat_drop'], opt['attn_drop'], opt['alpha'], False))
        # hidden layers
        for l in range(1, self.num_layers):
            # due to multi-head, the in_dim = num_hidden * num_heads
            self.gat_layers.append(GraphAttention(
                opt['num_hidden'] * opt['heads'][l-1], opt['num_hidden'], opt['heads'][l],
                opt['feat_drop'], opt['attn_drop'], opt['alpha'], opt['residual']))
        # output projection
        self.gat_layers.append(GraphAttention(
            opt['num_hidden'] * opt['heads'][-2], opt['out_dim'], opt['heads'][-1],
            opt['feat_drop'], opt['attn_drop'], opt['alpha'], opt['residual']))

    def forward(self, g, inputs):
        h = inputs
        for l in range(self.num_layers):
            h = self.gat_layers[l](g, h).flatten(1)
            h = F.elu(h)
        # output projection
        h = self.gat_layers[-1](g, h).mean(1)
        pdb.set_trace()
        heads = graph_batch_heads(g.batch_num_nodes)
        objs = graph_batch_objs(g.batch_num_nodes)
        sbj_gcn_out = h[heads]
        obj_gcn_out = h[objs]
        logits = torch.cat([sbj_gcn_out, obj_gcn_out], dim=-1)

        return logits

    def graph_batch_heads(l):
    s = 0
    res = []
    for e in l:
        res.append(s)
        s += e
    return res

    def graph_batch_objs(l):
    s = 0
    res = []
    for e in l:
        if e > 1:
            res.append(s+1)
        else:
            res.append(s)
        s += e
    return res`

**Comment by TZWwww** [comment]
> Hi,
> 
> How did you install dgl? It should be fixed on the current master branch. (related [PR](https://github.com/dmlc/dgl/pull/692))
> 
> @BarclayII What's our lateset binary release of DGL?

Hi. So you mean I should re-install dgl? And from where?

**Comment by VoVAllen** [comment]
Hi, Do you use linux or windows? You may need to reinstall dgl from source ([link](https://docs.dgl.ai/install/index.html#install-from-source)).

**Comment by VoVAllen** [comment]
Or you can directly change the installed file as the PR I mentioned for simplicity, if you are familiar with python's installation path.

**Comment by jermainewang** [comment]
We could consider a patch release for a bundle of bug fixes if that could help.

**Comment by TZWwww** [comment]
> Or you can directly change the installed file as the PR I mentioned for simplicity, if you are familiar with python's installation path.

Hi, I fix as pr you mentioned, but seems it doesn't work.

**Comment by TZWwww** [comment]
Hi @VoVAllen , I finally fix it. It is a problem with pytorch. Thanks a lot!
The solution:https://discuss.pytorch.org/t/out-of-memory-error-during-evaluation-but-training-works-fine/12274/4

**Comment by yzh119** [comment]
Yeah, in validation phase you should disable gradients.
