### ISSUE TITLE
DGL not work with numpy >= 2.0

### ISSUE THREAD

**Issue by jalencato** [dmlc/dgl#7468]
## To Reproduce

1. pip3 install dgl==2.2.1+cu121 -f  https://data.dgl.ai/wheels/torch-2.2/cu121/repo.html
2. Run a python script with ``import dgl`` 

Error:
```
A module that was compiled using NumPy 1.x cannot be run in
NumPy 2.0.0 as it may crash. To support both 1.x and 2.x
versions of NumPy, modules must be compiled with NumPy 2.0.
Some module may need to rebuild instead e.g. with 'pybind11>=2.12'.

If you are a user of the module, the easiest solution will be to
downgrade to 'numpy<2' or try to upgrade the affected module.
We expect that some modules will need time to support NumPy 2.

```

## Environment

 - DGL Version: Both 1.13.1 and 2.2.1
 - Backend Library & Version : Torch 2.1
 - OS (e.g., Linux): Amazon Linux 2023
 - How you installed DGL (`conda`, `pip`, source): pip
 - Build command you used (if compiling from source):
 - Python version:
 - CUDA/cuDNN version (if applicable):
 - GPU models and configuration (e.g. V100):
 - Any other relevant information:

**Comment by pyynb** [comment]
NumPy 2.0 is the latest release and may have some incompatibilities with the NumPy 1.x we used previously. We are currently looking into it. Downgrading NumPy to version 1.x can resolve this issue.

**Comment by jalencato** [comment]
Just FYI: The compatible problem does not appear when using DGL on torch 2.3. It always happens for torch version <= 2.3

**Comment by jakirkham** [comment]
Well PyTorch itself needs by 2.3.0 to support NumPy 2 : https://github.com/pytorch/pytorch/issues/107302

So it sounds like users just need to upgrade PyTorch and this is not actually a DGL problem

**Comment by Rhett-Ying** [comment]
@jakirkham  Thanks for your info. we'll look into and confirm.

**Comment by Rhett-Ying** [comment]
As we discussed [here](https://github.com/dmlc/dgl/pull/7479#issuecomment-2199158291), it's user's responsibility to either downgrade numpy or upgrade torch. DGL itself does have such requirement.
