### ISSUE TITLE
Only CPU versions can be installed by commands in the `Get Started` page with options `Windows` + `CUDA` selected.

### ISSUE THREAD

**Issue by chuanwise** [dmlc/dgl#7476]
I want to install `DGL` in my computer with Windows 11 and CUDA 12.1. I selected options `PyTorch 2.3.x`, `CUDA 12.1`, `Package Pip(Stable)` and `OS: Windows` in [this page](https://www.dgl.ai/pages/start.html), and it given me commands:

```
# If you have installed dgl-cuXX package, please uninstall it first.
pip install  dgl -f https://data.dgl.ai/wheels/cu121/repo.html
```

After run that, `dgl` with ONLY CPU version is installed. Users who want DGL CUDA version can only build and install it from source.

**Comment by Rhett-Ying** [comment]
DGL 2.2.1 + cuda 12.1 is released. please install with below command;
```
# If you have installed dgl-cuXX package, please uninstall it first.
pip install  dgl -f https://data.dgl.ai/wheels/cu121/repo.html
```

**Comment by mfbalin** [comment]
Is this still a problem even with the latest release?
