### ISSUE TITLE
DGLGraph.edge_ids return invalid number edges?

### ISSUE THREAD

**Issue by treble-maker123** [dmlc/dgl#754]
## 🐛 Bug

This is a very specific scenario, where the edge_ids seem to be returning an invalid tuple. 

## To Reproduce

I have a graph with 75377 nodes and 285854 edges. When I am examining a specific node, these are the values I get,

```python
>>> graph.in_degree(60320) 
1

>>> graph.out_degree(60320)
1

>>> graph.in_edges(60320)
(tensor([15610]), tensor([60320]))

>>> graph.out_edges(60320)
(tensor([60320]), tensor([15610]))

>>> graph.edge_ids(60320, 15610)
(tensor([60320]), tensor([15610]), tensor([99007]))
```

## Expected behavior

From the first 4 commands, and based on the documentation on [edge_ids](https://docs.dgl.ai/generated/dgl.DGLGraph.edge_ids.html#dgl.DGLGraph.edge_ids), I expect `edge_ids(60320, 15610)` to return something like this,

```python
(tensor([60320, 15610]), tensor([15610, 60320]), tensor([99007, different_edge_id]))
```

## Environment

 - DGL Version (e.g., 1.0): **0.3**
 - Backend Library & Version (e.g., PyTorch 0.4.1, MXNet/Gluon 1.3): **PyTorch 1.1.0**
 - OS (e.g., Linux): **MacOS**
 - How you installed DGL (`conda`, `pip`, source): **conda**
 - Build command you used (if compiling from source): **N/A**
 - Python version: **3.7**
 - CUDA/cuDNN version (if applicable): **N/A**
 - GPU models and configuration (e.g. V100): **N/A**
 - Any other relevant information: **N/A**

## Additional context

**N/A**

**Comment by BarclayII** [comment]
In DGL, all graphs are directed.  So `edge_ids(60320, 15610)` should only return edges that come from node 60320 to node 15610 (hence giving you only one edge); the reverse direction is not included.

**Comment by treble-maker123** [comment]
Oh, I think I misunderstood the documentation didn't take **source node** and **destination node** in **Return all edge IDs between source node array u and destination node array v.** literally - I thought it would return all edges, not just in a direction.

Thanks!
