### ISSUE TITLE
Number of batches as a function of number of entities [RGCN]

### ISSUE THREAD

**Issue by sharifza** [dmlc/dgl#757]
## 🐛 Potential Bug

I might be missing out something but to me this line looks a bit strange:
https://github.com/dmlc/dgl/blob/17b60e1af018e914e35f2d343d82978a00966485/examples/pytorch/rgcn/utils.py#L169

It seems like number of batches is computed by dividing number of entities (nodes) to batch size. 
Shouldn't that be` (test_size + batch_size - 1) // batch_size`  instead ?

## Expected behavior
Instead of 
https://github.com/dmlc/dgl/blob/17b60e1af018e914e35f2d343d82978a00966485/examples/pytorch/rgcn/utils.py#L198
and 
https://github.com/dmlc/dgl/blob/17b60e1af018e914e35f2d343d82978a00966485/examples/pytorch/rgcn/utils.py#L200

we should have 
`ranks_s = perturb_and_get_rank(embedding, w, o, r, s, test_triplets.shape[0], eval_bz)`
and
`ranks_o = perturb_and_get_rank(embedding, w, s, r, o, test_triplets.shape[0], eval_bz)`

I can do a pull request if someone confirms this...

**Comment by ylfdq1118** [comment]
@sharifza I think you are right. It should not be number of entities. It should be number of triplets in the test. 

Please open a PR.

**Comment by sharifza** [comment]
Thanks for looking at it @ylfdq1118, please take a look at the PR.
