### ISSUE TITLE
[liburing] redefinition of 'struct in6_pktinfo' when building on ubi7 with gcc/g++ 9.5.0

### ISSUE THREAD

**Issue by Rhett-Ying** [dmlc/dgl#7572]
## To Reproduce
filed on liburing repo: https://github.com/axboe/liburing/issues/1187.

## Environment

 - DGL Version (e.g., 1.0):
 - Backend Library & Version (e.g., PyTorch 0.4.1, MXNet/Gluon 1.3):
 - OS (e.g., Linux):
 - How you installed DGL (`conda`, `pip`, source):
 - Build command you used (if compiling from source):
 - Python version:
 - CUDA/cuDNN version (if applicable):
 - GPU models and configuration (e.g. V100):
 - Any other relevant information:

**Comment by mfbalin** [comment]
Did we get around this by only building the src directory of liburing?

**Comment by Rhett-Ying** [comment]
resolved with `make -C src/`, just do not build examples to avoid such issue
