### ISSUE TITLE
[GraphBolt] Store `ORIGINAL_EDGE_ID` in `FeatureStore`.

### ISSUE THREAD

**Issue by mfbalin** [dmlc/dgl#7591]
## 🔨Work Item

**IMPORTANT:**
* This template is only for dev team to track project progress. For feature request or bug report, please use the corresponding issue templates.
* DO NOT create a new work item if the purpose is to fix an existing issue or feature request. We will directly use the issue in the project tracker.

Project tracker: https://github.com/orgs/dmlc/projects/2

## Description

It is better to store the graph edge attribute `ORIGINAL_EDGE_ID` in FeatureStore as that is where it belongs. This will enable us to further optimize edge feature fetches.

**Comment by mfbalin** [comment]
@frozenbugs When we are fetching features, we can permute our edge ids inside feature store once and then fetch our features. There is no need to keep `ORIGINAL_EDGE_ID` in the graph. If the graph is pinned for example, we won't be able to overlap the `ORIGINAL_EDGE_ID` fetch operation with the rest of the operations.

**Comment by frozenbugs** [comment]
I am confused here, what's the key for ORIGINAL_EDGE_ID? I thought ORIGINAL_EDGE_ID is the key to fetch edge feature.

**Comment by mfbalin** [comment]
The returned edge ids from sample neighbors need to be permuted using `ORIGINAL_EDGE_ID` before fetching edge features. However, as you can see, `ORIGINAL_EDGE_ID` is only needed for `FeatureStore`. So it makes sense to store it inside `FeatureStore`.

**Comment by mfbalin** [comment]
@frozenbugs What do you think?

**Comment by mfbalin** [comment]
Let's discuss this feature tonight. I am almost done with the sampling optimizations that can be done before going multi-GPU.

**Comment by mfbalin** [comment]
https://github.com/dmlc/dgl/blob/ea940f72b5f1005d768707ecbc79354513deffae/python/dgl/graphbolt/impl/fused_csc_sampling_graph.py#L756
