### ISSUE TITLE
Restrict `torch` versions in `setup.py`

### ISSUE THREAD

**Issue by Andrew-S-Rosen** [dmlc/dgl#7668]
## 🚀 Feature

If I understand the situation correctly, at a given point in time, dgl does not necessarily support all versions of torch. There is typically a bit of a lag period, as noted in https://github.com/dmlc/dgl/issues/7247. This is fine from the perspective of reading the documentation and only using the right torch version, but it is a problem for downstream packages that don't pin torch in their CI suites or in `pyproject.toml`/`setup.py`. Given that this is a dgl compatibility concern at its core, it seems to me that the best solution would be for dgl to properly specify in its `setup.py` file the upper bound on the supported torch version for a given dgl release. In looking at [`setup.py`](https://github.com/dmlc/dgl/blob/master/python/setup.py), I don't see any restrictions on `torch` if used as the backend despite the fact that dgl 2.3.0 (for instance) doesn't seem to support torch 2.4.x. Hopefully this will help users not get incompatible versions of their various libraries.

**Comment by mfbalin** [comment]
@Rhett-Ying Do you think we can do this change in our release branches in the future?

**Comment by mfbalin** [comment]
https://github.com/dmlc/dgl/compare/master...2.4.x

**Comment by mfbalin** [comment]
DGL 2.4 release will support `torch<=2.4.0`

**Comment by mfbalin** [comment]
Closing the issue as the next release will limit the torch version. Can be reopened if the same issue arises in the future again.
