### ISSUE TITLE
[GraphBolt] WARNING: An experimental feature for CUDA allocations is turned on

### ISSUE THREAD

**Issue by Rhett-Ying** [dmlc/dgl#7671]
## 🐛 Bug

For now, even build CPU version of DGL, below warning is printed out. Could we refine it or suppress it? only print out when really necessary?

```
>>> import dgl
/home/ubuntu/workspace/dgl_4/python/dgl/graphbolt/__init__.py:17: GBWarning: 
An experimental feature for CUDA allocations is turned on for better allocation
pattern resulting in better memory usage for minibatch GNN training workloads.
See https://pytorch.org/docs/stable/notes/cuda.html#optimizing-memory-usage-with-pytorch-cuda-alloc-conf,
and set the environment variable `PYTORCH_CUDA_ALLOC_CONF=expandable_segments:False`
if you want to disable it.

  gb_warning(CUDA_ALLOCATOR_ENV_WARNING_STR)
>>> 
```

## Environment

 - DGL Version (e.g., 1.0): master
 - Backend Library & Version (e.g., PyTorch 0.4.1, MXNet/Gluon 1.3):
 - OS (e.g., Linux):
 - How you installed DGL (`conda`, `pip`, source):
 - Build command you used (if compiling from source):
 - Python version:
 - CUDA/cuDNN version (if applicable):
 - GPU models and configuration (e.g. V100):
 - Any other relevant information:

**Comment by mfbalin** [comment]
@Rhett-Ying https://github.com/dmlc/dgl/pull/7643/files

The warning should be printed only for the GPU build.

**Comment by mfbalin** [comment]
@Rhett-Ying Also, import dgl should not cause an import of GraphBolt, we discussed this today with @frozenbugs.

**Comment by Rhett-Ying** [comment]
> @Rhett-Ying Also, import dgl should not cause an import of GraphBolt, we discussed this today with @frozenbugs.

Yes. This is introduced by DistGB.

**Comment by Rhett-Ying** [comment]
@mfbalin 
if built with USE_CUDA=ON, will this warning be printed out in default?

**Comment by mfbalin** [comment]
Yes, you can add `export PYTORCH_CUDA_ALLOC_CONF=expandable_segments:True` if you want to disable the warning. This feature is about to be enabled by default for future PyTorch versions as it is already quite reliable and provides 2x GPU memory savings when using GraphBolt facilities.

**Comment by mfbalin** [comment]
> > @Rhett-Ying Also, import dgl should not cause an import of GraphBolt, we discussed this today with @frozenbugs.
> 
> Yes. This is introduced by DistGB.

DistGB could make it so that GraphBolt is imported if it being used.

**Comment by Rhett-Ying** [comment]
If Pytorch has not yet enabled it by default, could we conform to them as well? I'm afraid such warning is a bit annoying.

**Comment by mfbalin** [comment]
What about leaving 2x memory on the table?

**Comment by Rhett-Ying** [comment]
> > > @Rhett-Ying Also, import dgl should not cause an import of GraphBolt, we discussed this today with @frozenbugs.
> > 
> > 
> > Yes. This is introduced by DistGB.
> 
> @Rhett-Ying DistGB could make it so that GraphBolt is imported if it being used. It should not import GraphBolt by default.

Yes. I made that code. I will fix it.

**Comment by mfbalin** [comment]
@Rhett-Ying is there anymore action expected to be taken from my side?

**Comment by mfbalin** [comment]
Also, is it necessary to import DistDGL or DistGB when importing dgl?
