### ISSUE TITLE
[Test] Support test nn modules on CUDA

### ISSUE THREAD

**Issue by yzh119** [dmlc/dgl#771]
## 🚀 Feature
Currently we only test nn modules on CPU, as the components in our nn modules grows, I think it's necessary for us to test nn modules on both CPU and CUDA side. 

## Alternatives

No

## TODOs

Provid a frame agnostic API in `tests.backend` to move model from CPU to CUDA, and change `tests.pytorch/mxnet.test_nn.py` accordingly.

**Comment by yzh119** [comment]
@classicsong, please have a look.

**Comment by jermainewang** [comment]
Done in #775

**Comment by jermainewang** [comment]
Reopen this. I found the tests haven't been enabled in CI. Could you please fix that? @classicsong
