### ISSUE TITLE
[UnitTest] AttributeError: module 'numpy' has no attribute 'ComplexWarning'

### ISSUE THREAD

**Issue by Rhett-Ying** [dmlc/dgl#7766]
## 🐛 Bug

```
================================================ short test summary info ================================================
FAILED tests/python/common/sampling/test_sampling.py::test_global_uniform_negative_sampling[int32] - AttributeError: module 'numpy' has no attribute 'ComplexWarning'
FAILED tests/python/common/sampling/test_sampling.py::test_global_uniform_negative_sampling[int64] - AttributeError: module 'numpy' has no attribute 'ComplexWarning'
========================== 2 failed, 2872 passed, 60 skipped, 42 warnings in 148.98s (0:02:28) ==========================
```
## To Reproduce

1. `pip install  dgl -f https://data.dgl.ai/wheels/torch-2.4/cu121/repo.html`
2. `PYTHONPATH=tests:$PYTHONPATH python -m pytest tests/python/common/`

```
dgl                           2.4.0+cu121
numpy                         2.1.0
torch                         2.4.0+cu121
torch_geometric               2.5.3
torcheval                     0.0.7
torchmetrics                  1.4.1
```

## Environment

 - DGL Version (e.g., 1.0):
 - Backend Library & Version (e.g., PyTorch 0.4.1, MXNet/Gluon 1.3):
 - OS (e.g., Linux):
 - How you installed DGL (`conda`, `pip`, source):
 - Build command you used (if compiling from source):
 - Python version:
 - CUDA/cuDNN version (if applicable):
 - GPU models and configuration (e.g. V100):
 - Any other relevant information:

**Comment by az15240** [comment]
I got three more FAILED things when trying to reproduce the behavior on a freshly opened device. I'll take a look at them as well.

```
FAILED tests/python/common/data/test_data.py::test_as_nodepred1 - ModuleNotFoundError: No module named 'rdflib'
FAILED tests/python/common/data/test_data.py::test_as_nodepred2 - ModuleNotFoundError: No module named 'rdflib'
FAILED tests/python/common/data/test_utils.py::test_add_nodepred_split - ModuleNotFoundError: No module named 'rdflib'
```

**Comment by Rhett-Ying** [comment]
you should install `rdflib` before running

**Comment by az15240** [comment]
I tried to manually raise the warning by this code:
```python
import numpy as np
import warnings
warnings.warn("Manually triggering ComplexWarning", np.ComplexWarning)
```

but it still gave `AttributeError: module 'numpy' has no attribute 'ComplexWarning'`, so probably there is no ComplexWarning in numpy. 

I commented Line 1777: `warnings.simplefilter("ignore", np.ComplexWarning)` in `test_sampling.py` and the failure is solved. Since it is a simple fix, should I submit a PR?

**Comment by Rhett-Ying** [comment]
You should file a PR for it. But before that, you need to figure out the root cause. is it due to the recent numpy update? and any couterpart for such deprecated warning?

**Comment by az15240** [comment]
Got it. My numpy version is up-to-date, and I found in the NumPy source code, there is a ComplexWarning, but any invocation of `np.ComplexWarning` will gave the "has no attribute" error above. 

Check out https://github.com/numpy/numpy/blob/v2.1.0/numpy/exceptions.py#L48-L56
