### ISSUE TITLE
[Kernel][Perf] Message builtin with broadcasting is slow compared to UDF

### ISSUE THREAD

**Issue by jermainewang** [dmlc/dgl#784]
## 🐛 Performance Issue

One example is when using `u_mul_e` with broadcasting, the speed is quite slow compared to using UDF. Note that UDF should ideally be slower than built-in because node data needs to be duplicated to edges. This issue is found in NNConv module #779 .

## To Reproduce

Use the following testing script:
```python
import dgl
import time
import numpy as np
import scipy as sp
import torch

adj = sp.sparse.random(550, 550, 0.05)
G = dgl.DGLGraph(adj)
N = G.number_of_nodes()
M = G.number_of_edges()
print(N)
print(M)

def udf(edges):
    return {'m' : edges.src['h'] * edges.data['w']}

def time_udf(G):
    dur = []
    for i in range(50):
        if i >= 5:
            t0 = time.time()
        G.update_all(udf, dgl.function.sum('m', 'hh'))
        if i >= 5:
            dur.append(time.time() - t0)
    return np.average(dur)

def time_builtin(G):
    dur = []
    for i in range(50):
        if i >= 5:
            t0 = time.time()
        G.update_all(dgl.function.u_mul_e('h', 'w', 'm'), dgl.function.sum('m', 'hh'))
        if i >= 5:
            dur.append(time.time() - t0)
    return np.average(dur)

G.ndata['h'] = torch.randn((N, 64, 1))
G.edata['w'] = torch.randn((M, 64, 64))
G.to(torch.device('cuda:0'))
print('udf time:', time_udf(G))
print('builtin time:', time_builtin(G))

G.ndata['h'] = torch.randn((N, 64, 64))
G.edata['w'] = torch.randn((M, 64, 64))
G.to(torch.device('cuda:0'))
print('udf time:', time_udf(G))
print('builtin time:', time_builtin(G))
```

Run it with `CUDA_LAUNCH_BLOCKING=1 python t.py`. On a P3 machine, I got following result:

```
550
15125
udf time: 0.0021312501695421007
builtin time: 0.003366051779852973
udf time: 0.003186459011501736
builtin time: 0.001470041275024414
```

As you can see, when node feature shape is (64, 1) and edge feature shape is (64, 64), builtin kernel is ~1.5 times slower than UDF. As a comparison, if the node feature shape is also (64, 64) so no broadcasting is required, DGL builtin is much faster as expected.

## Additional context

The graph used here has ~550 nodes and ~15000 edges, which simulates the statistics in Alchemy dataset.

## Potential reasons

It might be our kernel implementation. Currently, each thread cooperatively computes each output element. To read the correct input location, it first unravel the flattened thread id to a multi-dimensional index and then flatten it again based on the shape and stride of each input tensor. I can see two issues with this:
* There is some redundancy in ravel/unravel.
* Each thread needs to store the multi-dimensional index which consumes register resources.

I wonder what's the better way to implement broadcasting?

Reference code:
https://github.com/dmlc/dgl/blob/66971c1aa44e7a1b24b3d2f5a40c624ca87ee047/src/kernel/cuda/binary_reduce_impl.cuh#L101-L111

@ylfdq1118 @yzh119 @classicsong

**Comment by yzh119** [comment]
The unravel basically compute the mapping bewteen threadIdx and coordinates. The whole mapping is of shape `(D1 * D2 * .. Dk, k)`, and I think it's not expensive to precompute and store it on GPU.
I suggest putting the mapping to `BcastGData`.

**Comment by classicsong** [comment]
I will look at this problem these days.

**Comment by classicsong** [comment]
> The unravel basically compute the mapping bewteen threadIdx and coordinates. The whole mapping is of shape `(D1 * D2 * .. Dk, k)`, and I think it's not expensive to precompute and store it on GPU.
> I suggest putting the mapping to `BcastGData`.

It is confirmed Unravel and Ravel take most of overhead in BinaryReduceBcast.
Simply combine Ravel calls on both lhs and rhs can get 10% performance on the example test code.
I will figure out whether @yzh119 suggestion can work better.

**Comment by classicsong** [comment]
Digging further into binary_reduce implementation and the underlying minigun module. The Unravel and Ravel operations are avoidable due to how minigun dispatch the parallel jobs. Currently minigun  uses edge parallel (across threadIdx.y) and takes a group of threads (threadIdx.x) to do calculation of the Op under a single edge. Under Broadcast case, each thread need to calculate the address of src and dest on each step (due to tx += stride_x; L110 on binary_reduce_impl.cuh). 

There are two solutions: 
1. Optimizing the address calculation. Combined Unravel and Ravel (10% benefit) and find out which one(lhs, rhs) is to broadcast(5% additional benefit)
2. change minigun to assign each edge to single cuda-thread. (This may cause imbalance problem if num of edges are small) Need to verify and this solution needs further discussion.

**Comment by classicsong** [comment]
> Digging further into binary_reduce implementation and the underlying minigun module. The Unravel and Ravel operations are avoidable due to how minigun dispatch the parallel jobs. Currently minigun uses edge parallel (across threadIdx.y) and takes a group of threads (threadIdx.x) to do calculation of the Op under a single edge. Under Broadcast case, each thread need to calculate the address of src and dest on each step (due to tx += stride_x; L110 on binary_reduce_impl.cuh).
> 
> There are three solutions:
> 
> 1. Optimizing the address calculation. Combined Unravel and Ravel (10% benefit)
>    `udf time: 0.002108801735772027 builtin time: 0.0028399592929416234`
>    and find out which one(lhs, rhs) is to broadcast(5% additional benefit)
>    `udf time: 0.002136129803127713 builtin time: 0.002635510762532552`
> 2. change minigun to assign each edge to single cuda-thread. (This may cause imbalance problem if num of edges are small) Need to verify and this solution needs further discussion.
> 3. slice input data (lhs and rhs) into contiguous blocks for each thread (threadIdx.x) instead of using stride (tx += stride_x). I will try this first.
> 
> @jermainewang @yzh119 @ylfdq1118

I have tried both 1,2 and 3. The solution 2 takes too much time on preparing the index mapping table. The solution 3 can not fully utilize the in-block thread parallelism and still need index translation. I have send a pull request for solution 1.

More deep optimization is still needed.
