### ISSUE TITLE
[System] Methods of 32-bit GraphIndex cannot take in utils.Index arguments

### ISSUE THREAD

**Issue by BarclayII** [dmlc/dgl#786]
## 🐛 Bug

If a `GraphIndex` is 32-bit, then most operations on the `GraphIndex` that takes in `utils.Index` arguments would either fail or return incorrect results, due to `utils.Index` always passes in 64-bit integer tensors around.

## To Reproduce

```
In [1]: import dgl

In [2]: g = dgl.DGLGraph()

In [3]: g.add_nodes(4)

In [4]: g.add_edges([0, 1, 2], [1, 2, 3])

In [5]: gi32 = g._graph.asbits(32)

In [6]: g.readonly()

In [7]: gi32 = g._graph.asbits(32)

In [8]: gi32.in_edges(dgl.utils.toindex([0]))
---------------------------------------------------------------------------
DGLError                                  Traceback (most recent call last)
<ipython-input-8-0f2e9bef43c3> in <module>
----> 1 gi32.in_edges(dgl.utils.toindex([0]))

/mnt/c/workspace/dgl/python/dgl/graph_index.py in in_edges(self, v)
    390             v_array = v.todgltensor()
    391             edge_array = _CAPI_DGLGraphInEdges_2(self, v_array)
--> 392         src = utils.toindex(edge_array(0))
    393         dst = utils.toindex(edge_array(1))
    394         eid = utils.toindex(edge_array(2))

/mnt/c/workspace/dgl/python/dgl/utils.py in toindex(data)
    240     Index
    241     """
--> 242     return data if isinstance(data, Index) else Index(data)
    243
    244 def zero_index(size):

/mnt/c/workspace/dgl/python/dgl/utils.py in __init__(self, data)
     13     """Index class that can be easily converted to list/tensor."""
     14     def __init__(self, data):
---> 15         self._initialize_data(data)
     16
     17     def _initialize_data(self, data):

/mnt/c/workspace/dgl/python/dgl/utils.py in _initialize_data(self, data)
     20         self._dgl_tensor_data = None  # a dgl ndarray
     21         self._slice_data = None # a slice type data
---> 22         self._dispatch(data)
     23
     24     def __iter__(self):

/mnt/c/workspace/dgl/python/dgl/utils.py in _dispatch(self, data)
     55         elif isinstance(data, nd.NDArray):
     56             if not (data.dtype == 'int64' and len(data.shape) == 1):
---> 57                 raise DGLError('Index data must be 1D int64 vector, but got: %s' % str(data))
     58             self._dgl_tensor_data = data
     59         elif isinstance(data, slice):

DGLError: Index data must be 1D int64 vector, but got: []

In [9]: i = dgl.utils.toindex(range(4))

In [10]: gi32.in_degrees(i).tousertensor()
Out[10]: tensor([0, 1, 0, 0])

In [11]: g.in_degrees(range(4))
Out[11]: tensor([0, 1, 1, 1])
```

Note that:
* The error is reported when converting the 32-bit array returned from CAPI to 64-bit GraphIndex.
* The result from Cell 10 and Cell 11 did not match due to a 64-bit `NDArray` passed into a 32-bit graph.

## Environment

 - DGL Version (e.g., 1.0): master

## Additional Context

Currently, the only place it matters is the `asbits()` method in `GraphIndex`, which is called by the scheduler.  This will potentially bring pitfalls when graph-structure queries are needed in the scheduler (e.g. implementing the `mean` built-in reducer requires querying the in-degrees), (CC'ing @yzh119 for this).

A solution would be forcing GraphIndex to always use 64-bit integers.  @ylfdq1118 I wonder why we had 32-bit graphs?

Another solution would be allowing `int32` in `utils.Index`.  But in this case, we will have to be careful about the type of `Index` content passing into `int32` graphs and `int64` graphs.

**Comment by BarclayII** [comment]
NVM, we have `utils.to_nbits_int`.

**Comment by jermainewang** [comment]
My view on this is we need to gradually make DGLGraph strongly-typed and device-aware to the user. That means when creating a DGLGraph, user needs to specify the integer bitwidth and device context. We could define some default values.
```python
g = DGLGraph(graph_data, idx_type=int32, ctx="cuda:0")
```
The input index arrays then need to match the type and device context. For example, int32 cuda graph can only accept int32 cuda torch tensor as the argument. This simplifies our system (for example, we don't need to cache a GPU graph index) and is also a common practice in Tensor framework.

**Comment by jermainewang** [comment]
> I wonder why we had 32-bit graphs?

CUSparse only supports int32 CSR.

**Comment by BarclayII** [comment]
I see.  We can probably do that along with the unification between `Graph` and `Bipartite`.

**Comment by safreita1** [comment]
Is there an estimated timeline for adding bit width specification in the DGLGraph function call?

**Comment by VoVAllen** [comment]
@safreita1 Hi, it's now supported in the DGLHeteroGraph, when you create graph with `dgl.graph`, you can pass argument to index_dtype to specify number of bits of graph. For DGLGraph, we are planning to deprecate this is the next release.
