### ISSUE TITLE
Bug in graph attention demo code with mxnet backend

### ISSUE THREAD

**Issue by panzheyi** [dmlc/dgl#812]
## 🐛 Bug

Executing dgl code on GPUs (id > 0) gave some unexpected errors, for example, running mxnet GAT demo code by `python3 train.py --dataset cora --gpu 1 --num-heads 8` .

However, it is fine when the code is executed on GPU0.

It seems that the error is caused by the built-in functions.  Because we tried other codes without built-in functions on GPUs, no error was raised.

## To Reproduce

1. Run mxnet GAT demo code by `python3 train.py --dataset cora --gpu 1 --num-heads 8` 

It gives an error:

Error in Function.backward: Traceback (most recent call last):
  File "/home/zhpan/.local/lib/python3.5/site-packages/mxnet/autograd.py", line 458, in backward_entry
    rets = self.backward(*output_grads)
  File "/home/zhpan/.local/lib/python3.5/site-packages/dgl/backend/mxnet/tensor.py", line 423, in backward
    self.rhs_map[1], self.out_map[1])
  File "/home/zhpan/.local/lib/python3.5/site-packages/dgl/kernel.py", line 210, in backward_lhs_binary_op_reduce
    grad_out, grad_A)
  File "/home/zhpan/.local/lib/python3.5/site-packages/dgl/_ffi/_ctypes/function.py", line 190, in __call__
    ctypes.byref(ret_val), ctypes.byref(ret_tcode)))
  File "/home/zhpan/.local/lib/python3.5/site-packages/dgl/_ffi/base.py", line 62, in check_call
    raise DGLError(py_str(_LIB.DGLGetLastError()))
dgl._ffi.base.DGLError: Resource deadlock avoided

## Environment

 - DGL Version (e.g., 1.0): v0.3.1
 - Backend Library & Version (e.g., PyTorch 0.4.1, MXNet/Gluon 1.3): MXNet 1.5.0
 - OS (e.g., Linux): ubuntu 16.04
 - How you installed DGL (`conda`, `pip`, source): pip3 install dgl-cu90 --user
 - Build command you used (if compiling from source):
 - Python version: 3.5.2
 - CUDA/cuDNN version (if applicable): cu90
 - GPU models and configuration (e.g. V100): GTX 1080
 - Any other relevant information:

**Comment by yzh119** [comment]
Thanks for reporting this bug, we will fix it soon.
Before that, you can try `CUDA_VISIBLE_DEVICES=1 python3 train.py --dataset cora --gpu 0 --num-heads 8`.
