### ISSUE TITLE
[RFC] Model Zoo for NLP

### ISSUE THREAD

**Issue by yzh119** [dmlc/dgl#813]
## 🚀 Feature
DGL could ease creating graphs and message passing for GNN models used in NLP. We already implemented TreeLSTM, Transformer, RRN(Recurrent Relational Network). However, we lack a unified data loading pipeline (https://discuss.dgl.ai/t/building-graphs-from-text/245) and our examples are not enough to educate users to write efficient Text-GNN models.

## Motivation
There has been a trend in using GNNs to deal with NLP tasks, including
- Multi-hop Machine Reading Comprehension
- Text Classification
- Relation Extraction
- Machine Translation
- Text Generation
- ...

[GNN Papers](https://github.com/thunlp/GNNPapers#natural-language-processing) list a few of them; some papers not on the list are also worth reading such as [KGLM](https://arxiv.org/pdf/1906.07241.pdf), and [GraphWriter](https://arxiv.org/pdf/1904.02342.pdf).

We do not have enough bandwidth to cover all of them, so I was wondering which of them are representative and users would like to see. This is also an opportunity to collaborate with GluonNLP @szha , a high-quality library that includes implementation of most prevalent NLP models.

Any discussions and feedbacks are appreciated.

**Comment by BarclayII** [comment]
I think we also need to put TreeLSTM as a module, as it is a classical model and we already have it in the examples.

**Comment by yzh119** [comment]
@BarclayII good idea, but how do we classify TreeLSTM? It neither a conv layer nor a pooling layer.

**Comment by jermainewang** [comment]
Due to the lack of a concrete plan for this, close it for now. We might revisit this later @HuXiangkun .
