### ISSUE TITLE
Reproduce GIN's results

### ISSUE THREAD

**Issue by mulinmeng** [dmlc/dgl#825]
## ❓ Questions and Help

Can author release the hyperparameter the GIN use to reproduce the results he reported?I can't get the results by using the default setting or a little change:)

Thx!

**Comment by VoVAllen** [comment]
Hi,

I found one part our example is not consistent to author's repo and now should be fixed in https://github.com/dmlc/dgl/pull/826. Could you try it again?

**Comment by jermainewang** [comment]
Closed due to inactivity. Please reopen if issue still exists.
