### ISSUE TITLE
[Bug] Unrecognize parameter shape after importing dgl.

### ISSUE THREAD

**Issue by panzheyi** [dmlc/dgl#829]
## 🐛 Bug

In version dgl 0.3.1, after importing dgl, the dimension of parameter shape becomes -1 instead of 0 in MXNet. 

In MXNet:
```python
from mxnet.gluon import nn
print(nn.Dense(32).collect_params())  # weight shape=(32,0)
```

After importing dgl:
```python
from mxnet.gluon import nn
import dgl
print(nn.Dense(32).collect_params())  # weight shape=(32,-1)
````
Basically, it is not a problem when creating, training & saving models.
However, when loading models from files by `net.load_parameters(filename)`, it throws errors like:
`shape (32,-1) is incompatible with shape (32, 8)`.
So we cannot correctly load the model by using the current API.

## Environment

 - DGL Version (e.g., 1.0): 0.3.1
 - Backend Library & Version (e.g., PyTorch 0.4.1, MXNet/Gluon 1.3): 1.5.0/1.6.0
 - OS (e.g., Linux): ubuntu 16.04
 - How you installed DGL (`conda`, `pip`, source): pip install dgl-cu90
 - Build command you used (if compiling from source):
 - Python version: 3.5.2
 - CUDA/cuDNN version (if applicable): cu90
 - GPU models and configuration (e.g. V100): GTX 1080
 - Any other relevant information:

**Comment by VoVAllen** [comment]
Thanks for reporting. I'll try to figure it out with MXNet Team.
