### ISSUE TITLE
module 'dgl' has no attribute 'broadcast_edges'

### ISSUE THREAD

**Issue by TZWwww** [dmlc/dgl#837]
## ❓ Questions and Help

Before proceeding, please note that we recommend
using our discussion forum (https://discuss.dgl.ai) for
general questions. As a result, this issue will
likely be CLOSED shortly.

My dal version is 0.3. There no functions like broadcast_edges, broadcast_nodes...
Can anyone help with these. Thanks!

**Comment by yzh119** [comment]
Please update your dgl version to v0.3.1.
