### ISSUE TITLE
Training GCN on multiple GPUs

### ISSUE THREAD

**Issue by lichen11** [dmlc/dgl#838]
I am trying to train GCN with multiple GPUs. I followed pytorch dataparallel API using the following:

    device = torch.device('cuda' if torch.cuda.is_available() else 'cpu')
    model = gcn_net
    if torch.cuda.device_count() > 1:
        print("Let's use", torch.cuda.device_count(), "GPUs!")
        model = nn.DataParallel(model, device_ids = [0,1])

    model.to(device)
    features = features.to(device)
    mask = mask.to(device)
    labels = labels.to(device)
Then I would get an error 
    RuntimeError: The size of tensor a (5000) must match the size of tensor b (10000) at non-singleton dimension 0. 
(Note: the length of labels is 10000) 

When I use single GPU, the following code runs fine
    device = torch.device('cuda' if torch.cuda.is_available() else 'cpu')
    model = gcn_net
    # if torch.cuda.device_count() > 1:
     #   print("Let's use", torch.cuda.device_count(), "GPUs!")
     # model = nn.DataParallel(model, device_ids = [0,1])
    model.to(device)
    features = features.to(device)
    mask = mask.to(device)
    labels = labels.to(device)

I tested if both GPUs can run using the test code from https://pytorch.org/tutorials/beginner/blitz/data_parallel_tutorial.html and they run fine. I think this could be due to some issues within the GraphConv layer or how it loads the data? Or is there another way to train GCN on multiple GPUs?

Thanks!

**Comment by VoVAllen** [comment]
Do you have multiple graphs or have a giant graph to be partitioned to multiple gpus?

**Comment by yzh119** [comment]
We encourage users to use `torch.distributed` instead of `DataParallel` for multi-GPU training.
The reason is as follows:
1. `DataParallel` uses multi-threading, which might be blocked by python GIL sometimes(cannot achieve linear speedup). While `torch.distributed` uses multi-processing and NCCL for GPU communication, which is efficient and would not be influenced by python GIL, please read https://pytorch.org/tutorials/intermediate/ddp_tutorial.html and https://pytorch.org/tutorials/intermediate/dist_tuto.html. 
2. As you mentioned the default `DataParallel` interface is not compatible with dgl. Of course, we can make a dgl version of `DataParallel`, but I would rather regard default `DataParallel` in PyTorch as a hack instead of a standard pipeline for multi-GPU training.

@VoVAllen should we write a simple tutorial for multi-GPU training?

**Comment by VoVAllen** [comment]
The error here is user trying to slice over the first dimension, which is number of node dimension instead of batch size dimension in dgl, which is a different behavior comparing to pytorch usual setting that first dimension is batch size dimension.

I thin we can make a tutorial on how to do multi-gpu training.

**Comment by lichen11** [comment]
I am training on one giant graph. You mentioned slicing over the first dimension is incompatible with dgl dimension. I am using the code from https://github.com/dmlc/dgl/tree/master/examples/pytorch/gcn 

Can you shed some light now on to fix it in the gcn.py code? 
If I use torch.distributed, will I still encounter the "first dimension" problem? Some example code of how to use torch.distributed along with dgl will be nice. Thanks.

**Comment by ralzq01** [comment]
If anyone who successfully implements multi-gpu training on gcn, I will be very appreciate he can share the code with us!

**Comment by yzh119** [comment]
Here is an example of distributed training with dgl: https://github.com/dmlc/dgl/blob/73b2668fe260017bb09e74553b65dc4a6094afa6/examples/pytorch/model_zoo/chem/generative_models/dgmg/train.py.

@lichen11 @ralzq01 I'll write a tutorial on multi-gpu training this week, please stay tuned.

**Comment by ralzq01** [comment]
Thanks for the sharing!

**Comment by chaitjo** [comment]
Looking forward to tutorial on multi-GPU training with DGL, esp. in the context of dealing with multiple graphs of variable topologies. Using `torch.distributed` has been alluded to in several issues and discussions, but seeing a concrete tutorial would be a lot better.

**Comment by ralzq01** [comment]
Hi, I just implemented a multi-gpus training API just like `torch.nn.DataParallel` for training GCN. If anyone who is still insterested in training on single-machine-multi-gpus, take a look at https://github.com/ralzq01/DGLGraphParallel

**Comment by yzh119** [comment]
@ralzq01 thanks for your contribution!
However, I'm curious if your implementation can achieve linear speedup?
According to our previous experience in using PyTorch default data parallel pipeline, the training time of using 4 GPUs is the same as using only 1 GPU.

**Comment by yzh119** [comment]
The following is a good example provided by @lingfanyu 
```python
import torch
import torch.nn as nn
import torch.nn.functional as F
import time
import sys

assert(len(sys.argv) == 2)
ngpu = int(sys.argv[1])

n_hidden = 128
n_layers = 100
n_repeat = 100
bz = 256

class Model(nn.Module):
    def __init__(self):
        super(Model, self).__init__()
        self.fc = nn.Linear(n_hidden, n_hidden)

    def forward(self, x):
        for _ in range(n_layers):
            x = self.fc(x)
            x = F.relu(x)
        torch.cuda.synchronize()
        return x

devices = [torch.device('cuda:{}'.format(gpu)) for gpu in range(ngpu)]
inputs = [torch.randn(bz, n_hidden).to(dev) for dev in devices]

model = Model().to(devices[0])
if ngpu > 1:
    model = nn.parallel.replicate(model, devices)

start = time.time()
with torch.no_grad():
    for _ in range(n_repeat):
        if ngpu > 1:
            output = nn.parallel.parallel_apply(model, inputs)
        else:
            output = model(inputs[0])
end = time.time()
print((end - start) / n_repeat * 1000)
```

Running time:
```
+------+--------------+
| GPUs | running time |
+------+--------------+
| 1    | 12.39        |
+------+--------------+
| 2    | 21.63        |
+------+--------------+
| 4    | 41.38        |
+------+--------------+
```
If we increase the hidden size from 128 to 4096, things become different:
```
+------+--------------+
| GPUs | running time |
+------+--------------+
| 1    | 77.30        |
+------+--------------+
| 2    | 81.96        |
+------+--------------+
| 4    | 91.10        |
+------+--------------+
```
This being said, when the network is relatively slow, DataParallel is not as efficient as it supposed to be.

**Comment by ralzq01** [comment]
Yes, similar results are observed. I can't observe speedup in GCN multi-GPU training. I think why data parallel can't make improvements in these situations is that the DataParallel in PyTorch implementation will require each forwarding operation to have data copy, weight copy and output copy (gather) from one GPU to another. Since GCNs are shallow models and each layer mostly only needs some element-wise and dot matrix multiplications, the computation will be very fast (similar to your example using nn.linear).  Therefore memory copy will occupy lots of time and even be slower than the computation time. 

I think when layers need high computation cost (such as convolutional operations) will show the benefit of data parallel. Under our circumstances (i.e. fc layer, GCN layer), computation cost is pretty low so the data parallel can't perform as it supposed to be.

I will post some results comparing single-machine-single-gpu with single-machine-multi-gpus later. I am curious about whether `torch.distributed` can alleviate such problem and make some speedups.

**Comment by yzh119** [comment]
@ralzq01 if you use `torch.distributed` with `NCCL` backend, the answer is yes. Instead of copying weight, this routine sync gradient with Tree-Allreduce algorithm, ane NCCL enables fast GPU-GPU communication.
[horovod](https://github.com/horovod/horovod) is another distributed training package with high throughput.

**Comment by ralzq01** [comment]
Following is the measurement of my implementation (tested on 3 GTX 1080 GPUs).
  +------+---------------+
  | GPUs | Epoch Time(s) |
  +------+---------------+
  |  1       |   3.6018          |
  +------+---------------+
  |  2       |   3.9829          |
  +------+---------------+
  |  3       |   4.5653          |
  +------+---------------+
The model has 2 GCN layers with reddit-self-loop dataset and 10 neighbors sampling. Each model replica's batch size is set to 30000.

Looking forward to the tutorials on multi-gpu training with `torch.distributed`!

**Comment by zheng-da** [comment]
We actually have multi-GPU training code in the examples: https://github.com/dmlc/dgl/tree/master/examples/mxnet/sampling
The code was written in MXNet but I think it's pretty easy to adapt it to Pytorch. It also provides you the scripts to run.

The implementation uses shared memory to share graph data (graph index, node features and edge features) and fork processes to train GCN in parallel. It doesn't have the overhead of data communication between processes.

As far as I remember, this implementation can achieve some speedup with more GPUs but not linear speedup. The main reason is that we have to store node embeddings and in CPU memory and data communication between CPU and GPU is the bottleneck.

We are thinking of having a pure multi-GPU solution, in which all data is stored in GPU and all computation (sampling and model computation) happens in GPU, so we can avoid PCI communication completely. This requires some significant effort. It is in our plan but may happen this year unless we see strong demands of such solution.

**Comment by futurely** [comment]
The multi-GPU training example works with a GPU but does not work with multiple GPUs. The GPU is Tesla V100. CUDA version is 10.0 and driver version is 410.78.

`DGLBACKEND=mxnet time python -u run_store_server.py --dataset reddit --num-workers 2`

`DGLBACKEND=mxnet time python /some_dir/incubator-mxnet/tools/launch.py -n 2 -s 1 --launcher local \
    python3 -u multi_process_train.py --model graphsage_cv --batch-size 20000 --test-batch-size 5000 --n-epochs 50 --graph-name reddit --num-neighbors 1 --n-hidden 128 --dropout 0.2 --weight-decay 0 --num-gpus 2`

```
dgl._ffi.base.DGLError: [15:01:40] /opt/dgl/src/runtime/cuda/cuda_device_api.cc:97: Check failed: e == cudaSuccess || e == cudaErrorCudartUnloading: CUDA: an illegal memory access was encountered
Stack trace:
  [bt] (0) /some_dir/miniconda3/lib/python3.7/site-packages/dgl/libdgl.so(dgl::runtime::CUDADeviceAPI::AllocDataSpace(DLContext, unsigned long, unsigned long, DLDataType)+0xdce) [0x7fde5c5ec03e]
  [bt] (1) /some_dir/miniconda3/lib/python3.7/site-packages/dgl/libdgl.so(dgl::runtime::NDArray::Empty(std::vector<long, std::allocator<long> >, DLDataType, DLContext)+0x289) [0x7fde5c534b79]
  [bt] (2) /some_dir/miniconda3/lib/python3.7/site-packages/dgl/libdgl.so(dgl::runtime::NDArray::CopyTo(DLContext const&) const+0xb7) [0x7fde5c5913b7]
  [bt] (3) /some_dir/miniconda3/lib/python3.7/site-packages/dgl/libdgl.so(dgl::UnitGraph::CSR::CopyTo(DLContext const&) const+0x46) [0x7fde5c5e0646]
  [bt] (4) /some_dir/miniconda3/lib/python3.7/site-packages/dgl/libdgl.so(dgl::UnitGraph::CopyTo(std::shared_ptr<dgl::BaseHeteroGraph>, DLContext const&)+0xb4) [0x7fde5c5db2a4]
  [bt] (5) /some_dir/miniconda3/lib/python3.7/site-packages/dgl/libdgl.so(+0xa13906) [0x7fde5c57d906]
  [bt] (6) /some_dir/miniconda3/lib/python3.7/site-packages/dgl/libdgl.so(DGLFuncCall+0x52) [0x7fde5c5122f2]
  [bt] (7) /some_dir/miniconda3/lib/python3.7/site-packages/dgl/_ffi/_cy3/core.cpython-37m-x86_64-linux-gnu.so(+0x19aeb) [0x7fdeaf9f5aeb]
  [bt] (8) /some_dir/miniconda3/lib/python3.7/site-packages/dgl/_ffi/_cy3/core.cpython-37m-x86_64-linux-gnu.so(+0x1a06d) [0x7fdeaf9f606d]


terminate called after throwing an instance of 'dmlc::Error'
  what():  [15:01:40] /opt/dgl/src/runtime/cuda/cuda_device_api.cc:103: Check failed: e == cudaSuccess || e == cudaErrorCudartUnloading: CUDA: an illegal memory access was encountered
Stack trace:
  [bt] (0) /some_dir/miniconda3/lib/python3.7/site-packages/dgl/libdgl.so(dgl::runtime::CUDADeviceAPI::FreeDataSpace(DLContext, void*)+0x65d) [0x7fde5c5e982d]
  [bt] (1) /some_dir/miniconda3/lib/python3.7/site-packages/dgl/libdgl.so(dgl::runtime::NDArray::Internal::DefaultDeleter(dgl::runtime::NDArray::Container*)+0x195) [0x7fde5c5359f5]
  [bt] (2) /some_dir/miniconda3/lib/python3.7/site-packages/dgl/libdgl.so(dgl::UnitGraph::CSR::~CSR()+0x2e) [0x7fde5c5e046e]
  [bt] (3) /some_dir/miniconda3/lib/python3.7/site-packages/dgl/libdgl.so(std::_Sp_counted_base<(__gnu_cxx::_Lock_policy)2>::_M_release()+0x39) [0x7fde5bf794a9]
  [bt] (4) /some_dir/miniconda3/lib/python3.7/site-packages/dgl/libdgl.so(dgl::UnitGraph::~UnitGraph()+0x2e) [0x7fde5c5e03fe]
  [bt] (5) /some_dir/miniconda3/lib/python3.7/site-packages/dgl/libdgl.so(DGLObjectFree+0x52) [0x7fde5c507652]
  [bt] (6) /some_dir/miniconda3/lib/python3.7/site-packages/dgl/_ffi/_cy3/core.cpython-37m-x86_64-linux-gnu.so(+0xd347) [0x7fdeaf9e9347]
  [bt] (7) python3(+0x1ad98f) [0x55b25104298f]
  [bt] (8) python3(+0x11e522) [0x55b250fb3522]
```
> We actually have multi-GPU training code in the examples: https://github.com/dmlc/dgl/tree/master/examples/mxnet/sampling
> The code was written in MXNet but I think it's pretty easy to adapt it to Pytorch. It also provides you the scripts to run.
> 
> The implementation uses shared memory to share graph data (graph index, node features and edge features) and fork processes to train GCN in parallel. It doesn't have the overhead of data communication between processes.
> 
> As far as I remember, this implementation can achieve some speedup with more GPUs but not linear speedup. The main reason is that we have to store node embeddings and in CPU memory and data communication between CPU and GPU is the bottleneck.
> 
> We are thinking of having a pure multi-GPU solution, in which all data is stored in GPU and all computation (sampling and model computation) happens in GPU, so we can avoid PCI communication completely. This requires some significant effort. It is in our plan but may happen this year unless we see strong demands of such solution.

**Comment by VoVAllen** [comment]
Hi, how many gpu are you using?

**Comment by futurely** [comment]
When using a single GPU, training with two workers is fine but both workers run on GPU 0. The speed is slower than the speed of training with a single worker. When using two workers and two GPUs, the above error occurs.

**Comment by VoVAllen** [comment]
Thanks. We'll look into this problem

**Comment by zyseula** [comment]
Just wondering has anyone implemented multi-gpu training for GCN with torch.distributed? I saw it was mentioned previously a tutorial will come out, but haven't find any resource about it online.

**Comment by classicsong** [comment]
> Just wondering has anyone implemented multi-gpu training for GCN with torch.distributed? I saw it was mentioned previously a tutorial will come out, but haven't find any resource about it online.

https://github.com/dmlc/dgl/pull/1143 Here is an example

**Comment by jermainewang** [comment]
For anyone who is interested in multi-GPU training using graph sampling, the official example is here: https://github.com/dmlc/dgl/tree/master/examples/pytorch/graphsage .

**Comment by AI678** [comment]
If I want to use DataParallel Module, how can I fix the first dimension problem ?

**Comment by AI678** [comment]
Is there another way to batch dgl graphs ?

**Comment by gaoliming123** [comment]
@yzh119 where i can see the tutorial on multi-gpu training of dgl you  write ?

**Comment by bs1119** [comment]
> Here is an example of distributed training with dgl: https://github.com/dmlc/dgl/blob/73b2668fe260017bb09e74553b65dc4a6094afa6/examples/pytorch/model_zoo/chem/generative_models/dgmg/train.py.
> 
> @lichen11 @ralzq01 I'll write a tutorial on multi-gpu training this week, please stay tuned.

Hi, where can I find a good example for multi-GPU DGL example? Thanks
