### ISSUE TITLE
[Roadmap][Dataset] Dataset related API

### ISSUE THREAD

**Issue by VoVAllen** [dmlc/dgl#849]
## 🚀 Feature
The goal is to use the recently merged DGL data format #728 to host popular datasets.

## Dataset
- [x] KarateClub
- [x] TUDataset
- [x] Planetoid
- [x] CoraFull
- [x] Coauthor
- [x] Amazon
- [x] PPI 
- [x] Reddit
- [x] QM7b
- [ ] QM9
- [ ] Entities
- [ ] GEDDataset
- [x] BitcoinOTC
- [x] ICEWS18
- [x] GDELT

CV/Mesh
- [ ] MNISTSuperpixels
- [ ] FAUST 
- [ ] DynamicFAUST
- [ ] ShapeNet
- [ ] ModelNet
- [ ] CoMA
- [ ] SHREC2016
- [ ] TOSCA 
- [ ] PCPNet dataset
- [ ] S3DIS
- [ ] GeometricShapes
- [ ] WILLOWObjectClass
- [ ] PascalVOCKeypoints

NLP
- [ ] DBP15K

I will not include mesh/cv/pointcloud dataset at this batch (seems too many and I don't know which to include). If anyone need any of those, please vote at the comment, and I'll try to implement them.

## Other Transform

- [x] AddSelfLoops
- [x] RemoveSelfLoops

**Comment by jermainewang** [comment]
The list is pretty long. Maybe we could prioritize some of them?

**Comment by VoVAllen** [comment]
I plan to implement most non-CV datasets. Not sure how far we should go for CV/point cloud dataset because many datasets are only used in the corresponding paper.

**Comment by VoVAllen** [comment]
Cannot find raw `GEDDataset`. `QM7` and `QM9b` need `gdata` support.

**Comment by mufeili** [comment]
Maybe also add a bullet point for tutorial on using data format?
