### ISSUE TITLE
[Feature Request] Add edges argument for edge_softmax

### ISSUE THREAD

**Issue by MilkshakeForReal** [dmlc/dgl#853]
## 🚀 Feature

Make `edge_softmax` function be able to apply for only part of edges
## Motivation
I noticed that `apply_edges` and `apply_nodes`  could both apply for part of e/n with arguments.   
In my brief review of transformer in the tutorial, I found this tutorial needed to update for the outdated api and implementations. I tried to refactor its implementation and was stuck cuz `edge_softmax` could only apply for all edges. I thought I could build subgraphs to apply this function, but not sure if auto-grad would work.

**Comment by yzh119** [comment]
Hi, I've implemented this in #842

**Comment by yzh119** [comment]
I've implemented this in #842 .

**Comment by MilkshakeForReal** [comment]
> I've implemented this in #842 .

Thanks for letting me know!
