### ISSUE TITLE
How to print out confidence matrix for sampling gcn_ns_sc.py code?

### ISSUE THREAD

**Issue by mjam57** [dmlc/dgl#854]
for nf in dgl.contrib.sampling.NeighborSampler(g, args.test_batch_size,
                                                       g.number_of_nodes(),
                                                       neighbor_type='in',
                                                       num_workers=32,
                                                       num_hops=args.n_layers+1,
                                                       seed_nodes=val_nid):
            nf.copy_from_parent()
            infer_model.eval()

            with torch.no_grad():
                pred = infer_model(nf)
                batch_nids = nf.layer_parent_nid(-1).to(device=pred.device, dtype=torch.long)
                batch_labels = labels[batch_nids]
                num_acc += (pred.argmax(dim=1) == batch_labels).sum().cpu().item()

            def predictedlab(model, features, labels, mask):
                 infer_model.eval()
                 with torch.no_grad():
                     logits = model(features)
                     logits = logits[mask]
                     labels = labels[mask]
                     _, indices = torch.max(logits, dim=1)

             return indices

    y_pred = predictedlab(model, features, labels, val_mask)
    np.shape(y_pred)
    tn, fp, fn, tp = confusion_matrix(labels[val_mask], y_pred).ravel()
    fpr = fp / (fp + tn)

    print("Test false positive rate {:.4f}".format(fpr))

    precision, recall, fscore, _ = precision_recall_fscore_support(labels[val_mask], y_pred, average='macro')
    print("Precision, recall, F-score")
    print(precision, recall, fscore)

Error:
Test Accuracy 0.9365
    main(args)
  File "C:/Users/<>/PycharmProjects/grades/gcn_ns_sc_rmat.py", line 334, in main
    y_pred = predictedlab(model, features, labels, val_mask)
  File "C:/Users/<>/PycharmProjects/grades/gcn_ns_sc_rmat.py", line 327, in predictedlab
    logits = model(features)
  File "C:\Users\<>\AppData\Local\Continuum\anaconda3\envs\grades\lib\site-packages\torch\nn\modules\module.py", line 547, in __call__
    result = self.forward(*input, **kwargs)
  File "C:/Users/<>/PycharmProjects/grades/gcn_ns_sc_rmat.py", line 65, in forward
    nf.layers[0].data['activation'] = nf.layers[0].data['features']
AttributeError: 'Tensor' object has no attribute 'layers'

**Comment by zheng-da** [comment]
How is your "model" defined? it seems the error happens in your own code, but you didn't show that piece of code.
