### ISSUE TITLE
Save memory to generate random walk traces with restart on large graph

### ISSUE THREAD

**Issue by futurely** [dmlc/dgl#865]
## 🚀 Feature
Save memory to generate random walk traces with restart on graphs with many vertices.

## Motivation

visit_counts use memory linear with the number of vertices in the graph even if many of the vertices won't be visited.

https://github.com/dmlc/dgl/blob/e9e587b6cb659406d697c748300d902a0d7b77e3/src/graph/randomwalk.cc#L108

## Pitch

Using hash map would save a lot memory.

## Additional context

google::dense_hash_map is faster than std::unordered_map.

https://attractivechaos.wordpress.com/2018/01/13/revisiting-hash-table-performance/

https://tessil.github.io/2016/08/29/benchmark-hopscotch-map.html

http://incise.org/hash-table-benchmarks.html

**Comment by zheng-da** [comment]
I see. The code does look not scalable. @BarclayII

**Comment by BarclayII** [comment]
We will be overhauling the sampler interface in 0.5.  The random walk implementation would also be refactored by then.
