### ISSUE TITLE
Implement multiprocessing based PrefetchingWrapper

### ISSUE THREAD

**Issue by futurely** [dmlc/dgl#867]
## 🚀 Feature
Implement multiprocessing based PrefetchingWrapper.

## Motivation

Currently only threading.Thread based PrefetchingWrapper is implemented.

https://github.com/dmlc/dgl/blob/1c9c033919acb4cce26dce528d6b00bf1484f4a0/python/dgl/contrib/sampling/sampler.py#L119

The performance of threading.Thread is limited by [Global Interpreter Lock (GIL)](https://realpython.com/python-gil/). Running with multiple threads can be much slower than running with a single thread as shown in [this benchmark](https://medium.com/practo-engineering/threading-vs-multiprocessing-in-python-7b57f224eadb).

![image](https://user-images.githubusercontent.com/9004594/65238171-c012e680-db0e-11e9-8f2b-9251b8d4f78d.png)

## Pitch

Potentially faster prefetching.

https://blog.floydhub.com/multiprocessing-vs-threading-in-python-what-every-data-scientist-needs-to-know/

**Comment by zheng-da** [comment]
Actually, we don't rely on python threads to sample data in parallel. The parallelism happens in the C code. The thread here is mainly used for overlaping model computation and sampling.

**Comment by jermainewang** [comment]
The multi-processing sampler is done in #1333 . Currently it only supports PyTorch. For other frameworks (MXNet and Tensorflow), we are investigating the similar solutions.
