### ISSUE TITLE
NodeFlow To GPU

### ISSUE THREAD

**Issue by ustchhy** [dmlc/dgl#872]
Hi, I want train my model using GPUs. I pass a nodeflow sampled from `dgl.contrib.sampling.NeighborSampler` every batch.
Then, i use `nodeflow.copy_from_parent(edge_embed_names=None, ctx=devices)` to copy nodeflow to GPU.
In the model, there is a line: `nf.layers[i].data['h'] = self.node_emb(nf.layer_parent_nid(i) + 1)`
I got an error `RuntimeError: Expected object of backend CUDA but got backend CPU for argument #3 'index'` 
I guess nf.layer_parent_nid is not on GPU. Is there someone can give me some suggestions, thaks.

**Comment by mufeili** [comment]
How about just moving `nf.layer_parent_nid(i)` to GPU?

**Comment by jermainewang** [comment]
Nodeflow API will be deprecated in favor of a more flexible sampler APIs. Currently, please refer to our latest [graphsage](https://github.com/dmlc/dgl/tree/master/examples/pytorch/graphsage) example for more details.
