### ISSUE TITLE
Need CI support for apps/kg

### ISSUE THREAD

**Issue by classicsong** [dmlc/dgl#911]
## Motivation
We have released Knowledge Graph application support in apps/kg. To make code under apps/kg consistent to future updates, we need basic CI.

**Comment by mufeili** [comment]
Chemistry will need something similar, depending on whether we make them part of DGL.

**Comment by jermainewang** [comment]
Food for thought:
* *Organization*: What is the overall organization of an app package? What is the thought process or criteria to decide which codes should belong to where?
* *Dependency*:  If some codes are in DGL main package, how to coordinate the test?  Shall we unify the versions of external dependencies? I heard KG requires pytorch-1.2.0 while DGL can support pytorch-1.1.0.
* *Reusability*: Shall we have standalone CI for each app package? If so, we might want a one-click setup script or template.

**Comment by classicsong** [comment]
> * _Dependency_:  If some codes are in DGL main package, how to coordinate the test?  Shall we unify the versions of external dependencies? I heard KG requires pytorch-1.2.0 while DGL can support pytorch-1.1.0.
I have built an docker image with pytorch-1.2.0. KG tests will all depends on that image.
KG requires pytorch-1.2.0 as it uses a new op named cdist. 

> * _Reusability_: Shall we have standalone CI for each app package? If so, we might want a one-click setup script or template.
I agree we need a standalone CI for app packages when the tests of app/ become much heavier.
