### ISSUE TITLE
How can i extract hole calculated graph nodes?

### ISSUE THREAD

**Issue by HCMY** [dmlc/dgl#917]
## ❓ Questions and Help
Hi, for some reasons,  I need extract data in each graph nodes which should be calclated(or conved), is that possible in this library?, thanks

**Comment by HCMY** [comment]
emm..yup, and its weights

**Comment by VoVAllen** [comment]
In reduce function, you can use `edges.dst.id` to get the destination node id and `edges.dst.data['h']` to get feature. Generally, you can use `g.in_degrees(g.number_of_nodes())` to get all nodes id which have in degrees and use `g.nodes[...ids].data['h']` to access them

**Comment by HCMY** [comment]
thank you for your immediately reply:), I'll try
