### ISSUE TITLE
Receiving messages from different edge-types

### ISSUE THREAD

**Issue by Junyoungpark** [dmlc/dgl#921]
Hi! 

While I implementing the network `dgl.Herterograph`, I'm wondering whether I could retrieve messages from the different edge types at once. For instance, If I want to send the messages through 2 edge types and retrieve the types of messages in a single node and fuse them into one message, what I can do?

**Comment by mufeili** [comment]
Below gives an example of what has been supported:

```python
g1 = dgl.graph([(0, 1), (1, 1)], 'user', 'follows')
g2 = dgl.bipartite([(0, 1)], 'game', 'attracts', 'user')
g = dgl.hetero_from_relations([g1, g2])
g.nodes['user'].data['h'] = torch.tensor([[1.], [2.]])
g.nodes['game'].data['h'] = torch.tensor([[1.]])

g.multi_update_all({'follows': (fn.copy_src('h', 'm'), fn.sum('m', 'h')), 
                    'attracts': (fn.copy_src('h', 'm'), fn.sum('m', 'h'))},
                    'sum')
print(g.nodes['user'].data['h'])
#      tensor([[0.],
#              [4.]])
```

Basically, you can send messages of multiple types at once, perform reduce for each type and then fuse the results of all types. See the documentation of [`dgl.DGLHeteroGraph.multi_update_all`](https://docs.dgl.ai/generated/dgl.DGLHeteroGraph.multi_update_all.html#dgl.DGLHeteroGraph.multi_update_all), [`dgl.DGLHeteroGraph.multi_send_and_recv`](https://docs.dgl.ai/generated/dgl.DGLHeteroGraph.multi_send_and_recv.html#dgl.DGLHeteroGraph.multi_send_and_recv) and [`dgl.DGLHeteroGraph.multi_pull`](https://docs.dgl.ai/generated/dgl.DGLHeteroGraph.multi_pull.html#dgl.DGLHeteroGraph.multi_pull).

**Comment by Junyoungpark** [comment]
Even though I followed the instruction what you've suggested, It is not clear to retrieve all messages from the different typed edges in the perspective of a certain node.

for instance, I want to perform an operation some like the following:

1. Get all messages from the different typed edges from one node v
2. Aggregate the messages and perform an update with some NN on the node v
3. Set the updated value as the feature of node V

**Comment by BarclayII** [comment]
Could you elaborate a bit further on how you would like to aggregate the messages from different types of edges?

Currently, heterograph messages with the same edge type are aggregated first (intra-type), then the aggregated messages are aggregated again (inter-type) using the cross-type reducer (indicated by the last argument of routines like `multi_update_all`).

**Comment by Junyoungpark** [comment]
Hi Barcalyll,

What I want to do is 
skip 'intra-type' aggregation and directly perform the 'inter-type' aggregation using some NN and cross-type reducer. The image is for describing what I wnat in mathematical expression. 

![equation](https://latex.codecogs.com/gif.latex?%5Cinline%20n_v%27%20%3D%20f%28%5Csum%20_%7Bi%20%5Cin%20%5CscriptN%28v%29%7D%20w%28%7Bm_i%20%3A%20i%20%5Cin%20%5CscriptN%28v%29%7D%20%5Ctimes%20m_i%29%29%20%5Cnewline%20m_i%20%3D%20g_%7Be%28v%2Ci%29%7D%28n_v%2C%20n_i%29%20%5Cnewline%20e%28v%2Ci%29%20%3D%20%5Cmathrm%7Bedge%20%5C%20type%7D%20%5Cnewline%20f%28%5Ccdot%29%20%3D%20%5Cmathrm%7Ba%20%5C%20neural%20%5C%20net%7D%20%5Cnewline%20g%28%5Ccdot%29%20%3D%20%5Cmathrm%7Ba%20%5C%20neural%20%5C%20net%7D%20%5Cnewline%20w%28%7B%5Ccdot%7D%29%20%3D%20%5Cmathrm%7Ba%20%5C%20neural%20%5C%20net%20%5Ctakes%20%5Cset%20%5Cas%20%5Can%20%5Cinput%20%5Cand%20%5Creturns%20%5Ca%20%5Ctensor%7D)

**Comment by mufeili** [comment]
Currently it might not be very easy to directly perform 'inter-type' aggregation, but I think the formulas you gave can also be represented by 'intra-type' aggregation followed by cross-type reduce. Essentially, this is just summing the messages for each type and then summing across all types.

I think this is very similar to our RGCN example code. See [L121-126](https://github.com/dmlc/dgl/blob/master/examples/pytorch/rgcn-hetero/entity_classify.py#L121).

**Comment by BarclayII** [comment]
> Currently it might not be very easy to directly perform 'inter-type' aggregation

We *do* have a way to aggregate over neighbors regardless of type using the slice operation with colons.  For instance, the following code
```python
fg = g[:, :, 'game']
fg.update_all(fn.copy_u('h', 'm'), fn.sum('m', 'a'))
result = fg.nodes['game'].data['a']
```
would aggregate from all neighbors of `game` nodes, regardless of what node type the neighbors are.

I observed a bug that one could not directly write something like
```python
g[:, :, 'game'].update_all(fn.copy_u('h', 'm'), fn.sum('m', 'a'))
result = g.nodes['game'].data['a']
```
I could fix this later.

**Comment by Junyoungpark** [comment]
Thanks for all the comments!
