### ISSUE TITLE
The number of normalization in graphconv.

### ISSUE THREAD

**Issue by zyyupup** [dmlc/dgl#924]
## 📚 Documentation

I am puzzled with the number of normalization in graphconv.  In the code, there is a second norm.
```        
if self._norm: 
    rst = rst * norm
```
while the first norm is excuted.
```        
if self._norm:  
   norm = th.pow(graph.in_degrees().float().clamp(min=1), -0.5)  
   shp = norm.shape + (1,) * (feat.dim() - 1)  
   norm = th.reshape(norm, shp).to(feat.device)  
   feat = feat * norm
```
I can't find a second norm in the formula.
![CodeCogsEqn](https://user-images.githubusercontent.com/15888204/66697025-4385b900-ed04-11e9-8872-9a4075220d31.gif)
I experienmented the diferent type of code by using gcn on cora dataset.
For 5 runs, the average acc is:
w/ second norm:0.8126
w/o second norm:0.8358
Any idea?

**Comment by VoVAllen** [comment]
The normalization constant `c_ij` is actually the square root of the multiplication of in degrees and out degrees. `feat = feat * norm` is multiplying the square root of in degrees while `rst = rst * norm` is multiplying the square root of out degrees.

**Comment by zyyupup** [comment]
> The normalization constant `c_ij` is actually the square root of the multiplication of in degrees and out degrees. `feat = feat * norm` is multiplying the square root of in degrees while `rst = rst * norm` is multiplying the square root of out degrees.

Yes,you are right.For an undirected graph,c_ij is the same.

**Comment by VoVAllen** [comment]
Feel free to reopen this if you have any further question
