### ISSUE TITLE
Batching DGLHeteroGraphs

### ISSUE THREAD

**Issue by Junyoungpark** [dmlc/dgl#927]
Hi!

Is there an easy way for batching `DGLHeteroGraph`s into one `DGLHetroGraph`?.

~When I use `dgl.batch([])` method, it requires edge types for batching. Do I need to MANUALLY specify all edge types of  `DGLHeteroGraph`s to construct the batched graph?~

Turns out `dgl.batch` doesn't support `DGLHeteroGraph`.

**Comment by yzh119** [comment]
Hi @Junyoungpark , would you mind re-organize this issue to a feature request?

**Comment by Junyoungpark** [comment]
It is my pleasure 🚀
