### ISSUE TITLE
[RFC] Batching DGLHeteroGraphs 

### ISSUE THREAD

**Issue by Junyoungpark** [dmlc/dgl#929]
I open this issue as a request of yzh119 from 'https://github.com/dmlc/dgl/issues/927'
I'm looking forward to using `BatchedHeteroGraphs` 👍 

Thanks! 

**Below is the original issues**

Hi!

Is there an easy way for batching `DGLHeteroGraph`s into one `DGLHetroGraph`?.

~When I use `dgl.batch([])` method, it requires edge types for batching. Do I need to MANUALLY specify all edge types of  `DGLHeteroGraph`s to construct the batched graph?~

Turns out `dgl.batch` doesn't support `DGLHeteroGraph`.

**Comment by mufeili** [comment]
I will take a look at this. Another related issue might be to support batched readout for DGLHeteroGraphs.

**Comment by mufeili** [comment]
The support for batching/unbatching DGLHeteroGraph has been added and you can use it by installing from source. See [the examples](https://github.com/dmlc/dgl/blob/master/python/dgl/batched_heterograph.py#L50). Let me know if you have any questions.

**Comment by Junyoungpark** [comment]
Thanks for supporting the cool new feature!
