### ISSUE TITLE
Any example for save/load single graph and batched graph?

### ISSUE THREAD

**Issue by LeeHuan18** [dmlc/dgl#936]
I can't find a easy way to save/load the single graph or batched graph, can anyone please provide some examples? 

I feel that the following code, in the tutorials:

```
# Create training and test sets.
trainset = MiniGCDataset(320, 10, 20)
testset = MiniGCDataset(80, 10, 20)
# Use PyTorch's DataLoader and the collate function
# defined before.
data_loader = DataLoader(trainset, batch_size=32, shuffle=True,
                         collate_fn=collate)

```

for the large trainset, it cost too much memory. Also "MiniGCDataset" generate graph when call it, however in my example it takes long time to generate graph, so I'd like to save all the graph before training.

**Comment by MilkshakeForReal** [comment]
DGL actually provides `save_graphs` API, but it is same with using `pickle`library

**Comment by LeeHuan18** [comment]
@MilkshakeForReal  Thank you!

**Comment by VoVAllen** [comment]
Hi,

We suggest using save_graphs and load_graphs, since this would be much faster than pickle.

**Comment by ZhongLi-Shi** [comment]
@VoVAllen 
Hi!
Can this function `save_graphs` save very large batched graphs?maybe almost 7Gb.
I have to split it and the pickle them.it isn’t convenient

**Comment by VoVAllen** [comment]
Hi,

Currently saving BatchedGraph is not supported, which means you need to unbatch them and store it. However, you can save them to a single file, `save_graphs` supports saving a list of DGLGraph. Does this solve your problem?
