### ISSUE TITLE
how to define multi-hop message function?

### ISSUE THREAD

**Issue by ZhongLi-Shi** [dmlc/dgl#939]
## ❓ Questions and Help
i wanna define a message function that nodes receive the msg from the 2nd-order neighbors rather than the direct neighbors.
But I don’t understand the sorce code of the defined message function.
is there any way to satisfy my demand?

Chinese:
我想定义一个能够从2阶邻居结点获得信息的传递函数,现有的似乎都是从直接相连的邻居获取信息？(可能有误，因为我看不懂已经定义好的传递函数是怎么实现的)
有什么方法能解决我的问题嘛？？

**Comment by mufeili** [comment]
You are right that the message functions only take messages from direct neighbors. For your question, I think the easiest thing it to construct DGLGraphs based on 2-hop neighbors directly, i.e. add edges indicating 2-hop distance.

**Comment by ZhongLi-Shi** [comment]
> You are right that the message functions only take messages from direct neighbors. For your question, I think the easiest thing it to construct DGLGraphs based on 2-hop neighbors directly, i.e. add edges indicating 2-hop distance.

thx,I'll have a try.By the way, is there any plan to create much more user-free msg function? I think that taking msg from only the direct neighbors in large graphs may lose the feature of the whole graph,so I issue this probelm. :)

**Comment by yzh119** [comment]
@ZhongLi-Shi , you can create a new graph where each edge corresponds to a 2-hop neighbor in the original graph by calling `dgl.khop_graph(g, 2)`. 

Doc: https://docs.dgl.ai/generated/dgl.transform.khop_graph.html

**Comment by ZhongLi-Shi** [comment]
> @ZhongLi-Shi , you can create a new graph where each edge corresponds to a 2-hop neighbor pair in the original graph by calling `dgl.khop_graph(g, 2)`.
> 
> Doc:  @https://docs.dgl.ai/generated/dgl.transform.khop_graph.html

thx! But i find that this function `dgl.khop_graph(g, 2)` seem to have one problems?
I think we'd better remove the self-loop before using this function.
otherwise the direct neighbors still regarded as the 2-hop neighors.
am I right?
@yzh119

**Comment by yzh119** [comment]
You are right, do you have any ideas on how to make it simple? We'll provide more convenient APIs according to your suggestions.

**Comment by ZhongLi-Shi** [comment]
> You are right, do you have any ideas on how to make it simple? We'll provide more convenient APIs according to your suggestions.

In the doc https://docs.dgl.ai/generated/dgl.transform.khop_graph.html, there seem to be a function `remove_self_loop(g)`.I think it works.but I didn't find it in the source code.Did I need to update dgl?

**Comment by ZhongLi-Shi** [comment]
@yzh119  I have updated the dgl and find it. I think it works, THX!  :)

**Comment by Data-Designer** [comment]
This issue pave the way for my success!
