### ISSUE TITLE
Can Downloaded Dataset's Path be modified to somewhere else?

### ISSUE THREAD

**Issue by WMF1997** [dmlc/dgl#947]
## ❓ Questions and Help

Hello, 
Are downloaed dgl's datasets(for example, ```dgl.data.citegrh.load_cora()```'s cora dataset) only saved in ```~/.dgl/``` this directory? I mean, I want to put the dataset somewhere else, for example, paths like ```/media/myhdd/dgl_datasets/```  in Linux, or ```D:/dgl_datasets/``` in Windows. 

I checked the ```dgl.data.citegrh``` 's python file, and I cannot find anything about ```.dgl``` path . 

so... how can i modify the code to change the dataset's path, and load it successfully?

yours sincerely, 
@wmf1997

**Comment by VoVAllen** [comment]
Hi,

It's at [here](https://github.com/dmlc/dgl/blob/master/python/dgl/data/utils.py#L230). You can change the environment variable `DGL_DOWNLOAD_DIR` to the directory you want.

**Comment by WMF1997** [comment]
really thanks~!
