### ISSUE TITLE
[BUG] New version of networkx will break some example code

### ISSUE THREAD

**Issue by classicsong** [dmlc/dgl#948]
## 🐛 Bug
networkx 2.4 has removed selfloop_edges func which is used by some of DGL examples.
https://networkx.github.io/documentation/stable/release/release_2.4.html?highlight=selfloop_edges

## To Reproduce

```
pip install networkx==2.4
git clone https://github.com/dmlc/dgl.git
cd dgl/examples/mxnet/gcn/
DGLBACKEND=mxnet python3 train.py  --self-loop --dataset cora
```

## Expected behavior
The example should not crash

## Environment

 - DGL Version (e.g., 1.0): 0.4.x
 - Backend Library & Version (e.g., PyTorch 0.4.1, MXNet/Gluon 1.3):MXNet
 - OS (e.g., Linux): Linux 
 - How you installed DGL (`conda`, `pip`, source): pip
 - Python version: 3.6

**Comment by jermainewang** [comment]
Fixed in #949 .
