### ISSUE TITLE
Support cuda=10.1?

### ISSUE THREAD

**Issue by wangxin0716** [dmlc/dgl#950]
## Motivation
At the time that I am writing this request, DGL 0.4 only support cuda=9.0 and cuda=10.0.  See DGL doc [https://docs.dgl.ai/en/latest/install/](url).

Will you consider supporting cuda=10.1 ?[https://developer.nvidia.com/cuda-downloads](url)

**Comment by BarclayII** [comment]
CUDA 10.1 binary is now included in 0.4.1 release.
