### ISSUE TITLE
how to feed train、val、test data to the dgl model respectively?

### ISSUE THREAD

**Issue by MisakaGeek** [dmlc/dgl#956]
Do you want live notifications when people reply to your postshere is my question 

as you know, when applying a DL task, a common way is deviding the whole dataset into three parts, one for trainning, one for evaluate and one for test.
i know there got API in dgl which can help me to devide the dataset,but i don't know how to feed the model for trainning(or val,or test) with part of the dataset after i input all the graph structure information to create a graph.

so i want know if there is an easy way to achieve this goal when using dgl

thanks

**Comment by mufeili** [comment]
It sounds like your dataset is a single graph and the task is node classification. For this kind of dataset, typically we feed the whole graph into the model and mask over training/validation/test nodes during loss/score computation. See [an example here](https://github.com/dmlc/dgl/blob/master/examples/pytorch/gcn/train.py#L17).

**Comment by MisakaGeek** [comment]
Thank you for your answer！
