### ISSUE TITLE
[Bug] u_dot_e unit test occasionally fails on CI

### ISSUE THREAD

**Issue by BarclayII** [dmlc/dgl#958]
## 🐛 Bug

`u_dot_e` occasionally fails on CI.

## To Reproduce

![image](https://user-images.githubusercontent.com/2978100/67619397-da3a9580-f82d-11e9-98e0-e5e78c5aed68.png)

## Additional context

Not sure if this is a Windows-specific problem.

**Comment by yzh119** [comment]
Do you have any ideas on how this happens? On CPU side or GPU side?

**Comment by BarclayII** [comment]
That was on torch GPU.

**Comment by classicsong** [comment]
Fixed in #1194
