### ISSUE TITLE
Index type error in graph.send_and_recv()

### ISSUE THREAD

**Issue by Junyoungpark** [dmlc/dgl#960]
Hi! 

graph.send_and_recv() returns error as follows:
```
RuntimeError: Expected object of scalar type Float but got scalar type Long for argument #4 'source' in call to _th_index_copy_
```
when I implement code as follows, the code works perfectly well.

```
graph.send(edges, message_func)
graph.receive(g.nodes().long(), reduce_func)
```
System env
- pytorch 1.3.0
- dgl 0.4
- no cuda

edit) pytorch 1.1.0 doesn't return the error.

**Comment by mufeili** [comment]
Did you try `graph.send_and_recv(edges.long(), message_func, reduce_func)`? Since the edges are indexed with integers, we expect the edges to be of data type `LongTensor`.

**Comment by Junyoungpark** [comment]
I guess the problem comes from `UDF` in  `message function` and `reduce function` .
In the `message function` and `reduce function`, the graph sends and receives integer-valued features.
when I change the dtyes from `long` to `float` it works well.

**Comment by Junyoungpark** [comment]
I found the reason. I used nn.forward(*args) instead of nn(*args). 
I'm sorry. it was totally my mistake. I'm going to close the issue.
Sorry for your inconvenience.
