### ISSUE TITLE
Error in JTNN latent space sampling from dgl model zoo

### ISSUE THREAD

**Issue by violetguos** [dmlc/dgl#961]
## 🐛 Bug

We are trying to train and test a JTNN model. However, the training script runs, but the decoding occasionally encounters empty tensor.

## To Reproduce

1. Install the requirements according to the [instruction](https://github.com/dmlc/dgl). Most notably, torch is 0.4.1, not the latest 1.0+.
2. Make sure that you clone the dgl repo at 577cf2e63b847d6e5a3ec35d68ba8241d7498182
3. Run `cd examples/pytorch/jtnn`
4. Run training script using the command `python3 vaetrain_dgl.py`. 
5. We explored running the decoder using two different options. 
      1. Run the decoder using `python3 vaetrain_dgl.py -T`
      2. Run the decoder with a specified model `python3 vaetrain_dgl.py -T --model=model.iter-20`

### Error from 5.i, `python3 vaetrain_dgl.py -T`

```
effective_nodes tensor([0])    # Note this is my debugging print. it's a zero tensor
mol_tree_sg DGLGraph(num_nodes=1, num_edges=0,
         ndata_schemes={}
         edata_schemes={}) # end of my prints
Traceback (most recent call last):
  File "vaetrain_dgl.py", line 150, in <module>
    test()
  File "vaetrain_dgl.py", line 145, in test
    smiles = model.decode(tree_vec, mol_vec)
  File "/Users/vikuo/Desktop/fall_19/invivo/code/dgl/jtnn/jtnn/jtnn_vae.py", line 190, in decode
    mol_tree_msg, _ = self.jtnn([mol_tree_sg])
  File "/Users/vikuo/anaconda3/envs/invivo_t0/lib/python3.6/site-packages/torch/nn/modules/module.py", line 477, in __call__
    result = self.forward(*input, **kwargs)
  File "/Users/vikuo/Desktop/fall_19/invivo/code/dgl/jtnn/jtnn/jtnn_enc.py", line 59, in forward
    return self.run(mol_tree_batch, mol_tree_batch_lg)
  File "/Users/vikuo/Desktop/fall_19/invivo/code/dgl/jtnn/jtnn/jtnn_enc.py", line 99, in run
    for eid in level_order(mol_tree_batch, root_ids):
  File "/Users/vikuo/Desktop/fall_19/invivo/code/dgl/jtnn/jtnn/jtnn_enc.py", line 12, in level_order
    _, leaves = forest.find_edges(edges[-1])
IndexError: tuple index out of range
```

### Error from 5.2, [5.ii](#To-Reproduce)
 running decoder with specified model `python3 vaetrain_dgl.py -T --model=model.iter-20`

Some of the attached error messages are from my print statements in [jtnn/jtnn/jtmpn.py](https://github.com/violetguos/dgl/blob/39d07aaeb02933c4334f69cf7cfee724d8cb676c/examples/pytorch/jtnn/jtnn/jtmpn.py#L210)

```
# Note that these are my debugging prints
effective_nodes tensor([0, 1, 2, 3, 4, 5])
mol_tree_sg DGLGraph(num_nodes=6, num_edges=10,
         ndata_schemes={}
         edata_schemes={})
source_features torch.Size([0])
bond_features torch.Size([0])
features torch.Size([0])
# end of my prints
Traceback (most recent call last):
  File "vaetrain_dgl.py", line 150, in <module>
    test()
  File "vaetrain_dgl.py", line 145, in test
    smiles = model.decode(tree_vec, mol_vec)
  File "/Users/code/dgl/jtnn/jtnn/jtnn_vae.py", line 198, in decode
    cur_mol = self.dfs_assemble(mol_tree_msg, mol_vec, cur_mol, global_amap, [], 0, None)
  File "/Users/code/dgl/jtnn/jtnn/jtnn_vae.py", line 264, in dfs_assemble
    mol_tree_msg,
  File "/anaconda3/envs/invivo_t0/lib/python3.6/site-packages/torch/nn/modules/module.py", line 477, in __call__
    result = self.forward(*input, **kwargs)
  File "/Users/code/dgl/jtnn/jtnn/jtmpn.py", line 184, in forward
    tree_mess_tgt_nodes, mol_tree_batch)
  File "/code/dgl/jtnn/jtnn/jtmpn.py", line 219, in run
    msg_input = self.W_i(features)
  File "/anaconda3/envs/invivo_t0/lib/python3.6/site-packages/torch/nn/modules/module.py", line 477, in __call__
    result = self.forward(*input, **kwargs)
  File "/anaconda3/envs/invivo_t0/lib/python3.6/site-packages/torch/nn/modules/linear.py", line 55, in forward
    return F.linear(input, self.weight, self.bias)
  File "/anaconda3/envs/invivo_t0/lib/python3.6/site-packages/torch/nn/functional.py", line 1026, in linear
    output = input.matmul(weight.t())
RuntimeError: cannot unsqueeze empty tensor
```
The script only throws this error when the features we sample from the latent space cannot form a `mol_tree` that has enough `effective_nodes`, and in the end at some point it returns an empty tensor `bond_features` (see the print statements in [jtnn/jtnn/jtmpn.py](https://github.com/violetguos/dgl/blob/39d07aaeb02933c4334f69cf7cfee724d8cb676c/examples/pytorch/jtnn/jtnn/jtmpn.py#L210) to find these variables)

## Expected behavior

The decoder should be able to sample from latent space, and return a molecule. The decoder script works from time to time when it doesn't sample a zero tensor from the latent space

For example:
```
(invivo_t0) Violets-MacBook-Pro:jtnn violet$ python3 vaetrain_dgl.py -T --model=model.iter-5
Loading data...
Loading finished.
	Num samples: 220011
	Vocab file: /Users/violet/.dgl/jtnn/vocab.txt
Model #Params: 1221K
Cc1ccc(O)c(Cc2ccccc2Cl)c1
effective_nodes tensor([0]) # effective_nodes should contain more than just a zero
mol_tree_sg DGLGraph(num_nodes=1, num_edges=0,
         ndata_schemes={}
         edata_schemes={})
Traceback (most recent call last): # begins the error message above
```

## Environment

 - DGL Version (e.g., 1.0): 1.0, and also cloned from dgl's 577cf2e63b847d6e5a3ec35d68ba8241d7498182 to run the source code of jtnn
 - Backend Library & Version (e.g., PyTorch 0.4.1, MXNet/Gluon 1.3): PyTorch 0.4.1,
 - OS (e.g., Linux): Mac OS Mojave 10.14.5
 - How you installed DGL (`conda`, `pip`, source): conda
 - Build command you used (if compiling from source):
 - Python version: 
 - CUDA/cuDNN version (if applicable): N/A
 - GPU models and configuration (e.g. V100): N/A
 - Any other relevant information:

**Comment by VoVAllen** [comment]
What's the version of your rdkit? You can get it by `rdkit.__version__`

**Comment by violetguos** [comment]
> rdkit.__version__

Hi, it's `2018.09.1`

**Comment by VoVAllen** [comment]
You can do this with `conda install -c conda-forge rdkit==2018.09.3`

**Comment by violetguos** [comment]
Thanks for your reply. I just tried rdkit 2018.09.3, I'm still getting 
```
  File "/Users/code/dgl/jtnn/jtnn/jtnn_enc.py", line 12, in level_order
    _, leaves = forest.find_edges(edges[-1])
IndexError: tuple index out of range
```

**Comment by VoVAllen** [comment]
Have you modified any source code? Sometime the error happens when the vector to be decoded is selected randomly far from the usual range.

**Comment by violetguos** [comment]
> Have you modified any source code? Sometime the error happens when the vector to be decoded is selected randomly far from the usual range.

Yes, in order to run a very simple prototype model, I added a subset sampler in the training function to reduce the training data size.  Most notably, I modified the `reconstruct()` method here https://github.com/violetguos/dgl/commit/69ae13493ef3b5296ec0c08ec08bc4a807a1c241#diff-c2c83714c35dc40eac3729a8e09bf782L75

After doing these modifications in model_zoo jtnn, I get the following error
```
Loading data...
Loading finished.
	Num samples: 5000
	Vocab file: /Users/.dgl/jtnn/vocab.txt
Model #Params: 1221K
Failed to encode: O=C(O[C@H]1CCOC1)C1(c2ccc(Cl)c(Cl)c2)CCC1
tuple index out of range
Failed to encode: Cc1ccccc1C(=O)N1CCC2(CC1)C[C@H](c1ccccc1)C(=O)N2C
tuple index out of range
Traceback (most recent call last):
  File "reconstruct_eval.py", line 118, in <module>
    reconstruct_acc = reconstruct()
  File "reconstruct_eval.py", line 113, in reconstruct
    len(dataloader), acc / tot))
ZeroDivisionError: float division by zero
```

**Comment by VoVAllen** [comment]
The error is an edge case that the rollout edges is zero when decoding from vectors. This happens when the model is not well-trained. Could you try training your model with more iterations or using our pretrained model?

**Comment by violetguos** [comment]
> The error is an edge case that the number of rollout edges is zero when decoding from vectors. This happens when the model is not well-trained. Could you try training your model with more iterations or using our pretrained model?

Thank you. I moved the `tot` incrementing out of the exception handling block, so now it can keep sampling. The pre-trained model is only compatible with cuda, which I haven't tried yet. I believe this issue can be closed now that model zoo's jtnn is working. Thanks again for the help.
