### ISSUE TITLE
Possible memory leak in SocketReceiver?

### ISSUE THREAD

**Issue by ranshuang** [dmlc/dgl#969]
## 🐛 Bug

For distributed sampler examples of pytorch, I find SamplerReceiver consumed more and more memory and finally threw exception as follows: 
"src/graph/network/socket_communicator.cc:299: Cannot allocate enough memory for message, (message size: 2314136)  "

## To Reproduce

1、Delete line "sender.signal(0)" in "https://github.com/dmlc/dgl/blob/master/examples/pytorch/sampling/dis_sampling/sampler.py" to make it run forever.
2、Change the for loop in https://github.com/dmlc/dgl/blob/master/examples/pytorch/sampling/dis_sampling/gcn_ns_sc_train.py to "while True" to make it run forever.

3、Run as the README says.

Stack trace:
> terminate called after throwing an instance of 'dmlc::Error'
>   what():  [18:27:57] /home/ranshuang/dgl_src/dgl_src_v0.4/src/graph/network/socket_communicator.cc:299: Cannot allocate enough memory for message, (message size: 2314136)
> Stack trace:
>   [bt] (0) /home/ranshuang/anaconda3/lib/python3.6/site-packages/dgl-0.4-py3.6-linux-x86_64.egg/dgl/libdgl.so(dmlc::LogMessageFatal::~LogMessageFatal()+0x22) [0x7f029b40dca2]
>   [bt] (1) /home/ranshuang/anaconda3/lib/python3.6/site-packages/dgl-0.4-py3.6-linux-x86_64.egg/dgl/libdgl.so(dgl::network::SocketReceiver::RecvLoop(dgl::network::TCPSocket*, dgl::network::MessageQueue*)+0x18a5) [0x7f029ba7eb45]
>   [bt] (2) /home/ranshuang/anaconda3/lib/python3.6/site-packages/torch/_C.cpython-36m-x86_64-linux-gnu.so(+0xb050) [0x7f039093a050]
>   [bt] (3) /lib64/libpthread.so.0(+0x7e25) [0x7f039a555e25]
>   [bt] (4) /lib64/libc.so.6(clone+0x6d) [0x7f039a28334d]

As the training went on, memory consumed more and more memory until above error happened.

## Environment

 - DGL Version : 0.4, GPU
 - Backend Library & Version : Pytorch 1.3.0
 - OS : CentOS
 - How you installed DGL : Source
 - Build command you used : Follow the document 
 - Python version: 3.6.8
 - CUDA/cuDNN version: 10.1 
 - GPU models and configuration : Tesla T4

**Comment by aksnzhy** [comment]
Hi, the memory-leak issue has been solved. Thanks!
