### ISSUE TITLE
Graph Convolutional Matrix Completion pytorch implement

### ISSUE THREAD

**Issue by zhangcaifu** [dmlc/dgl#974]
## 🚀 Feature
I am not quite familiar with the library you provide in example. Could you please provide another example writing in pytorch?

**Comment by burness** [comment]
Our team has finished the pytorch version of GCMC,  We will contribute it later

**Comment by classicsong** [comment]
> Our team has finished the pytorch version of GCMC, We will contribute it later. @zhangcaifu

That's cool

**Comment by zhangcaifu** [comment]
> Our team has finished the pytorch version of GCMC, We will contribute it later. @zhangcaifu

Really appreciate. Could please tell me where is the code right now?

**Comment by zhangcaifu** [comment]
> Our team has finished the pytorch version of GCMC, We will contribute it later. @zhangcaifu

I viewed the update release of the 0.5 version dgl, is gcmc will released as an API or a model in the dgl library in the next released version?　@burness

**Comment by zhangcaifu** [comment]
What do you mean by moving this issue to the main dashboard several weeks ago ? I was looking for the official example in the pytorch repository everyday but I haven't found it yet@burness @BarclayII

**Comment by yzh119** [comment]
@zhangcaifu I've finished the implementation of PyTorch-GCMC in #1101.
