### ISSUE TITLE
randomwalk reported no successors from vertex

### ISSUE THREAD

**Issue by nlj0011** [dmlc/dgl#977]
I am using DGL to implement the pinsage example. However, when run the random sampler, it reports no successors from vertex. Maybe my data is too sparse.. There are only four parameters I could change, such as max_nodes_per_seed, max_visit_counts, max_frequent_visited_nodes, and restart_prob in the "bipartite_single_sided_random_walk_with_restart" function. 

I have tried  relaxed max_nodes_per_seed to a bigger number, and  lowered restart probability, but it still failed.Could you  show me how to modify these parameters？Thank you！
Best Regards~

**Comment by VoVAllen** [comment]
Is it a naturally directed graph? If it's originally an undirected graph, you can add edges for both side (src to dst and dst to src). Then I think no successor situation would be very rare.

**Comment by nlj0011** [comment]
> Is it a naturally directed graph? If it's originally an undirected graph, you can add edges for both side (src to dst and dst to src). Then I think no successor situation would be very rare.
Thank you for your reply~  I modify the `class MovieLens(object)`, and replace the movielens dataset  with my dataset. So it is indead a undirected graph, however it still don't work........
`g.add_edges(
                rating_user_vertices,
                rating_movie_vertices,
                data={'inv': torch.zeros(self.ratings.shape[0], dtype=torch.uint8)})
 g.add_edges(
                rating_movie_vertices,
                rating_user_vertices,
                data={'inv': torch.ones(self.ratings.shape[0], dtype=torch.uint8)})
 `

**Comment by BarclayII** [comment]
Currently the random walk sampler does not work with nodes with no outbound edges.  In the MovieLens dataset in the examples I dropped all users and movies with 0 interactions, although whether doing so is reasonable is debatable.

**Comment by nlj0011** [comment]
> Currently the random walk sampler does not work with nodes with no outbound edges. In the MovieLens dataset in the examples I dropped all users and movies with 0 interactions, although whether doing so is reasonable is debatable.

yes, it did work~~~thank you very much!!
