### ISSUE TITLE
Error: device API GPU is not enabled

### ISSUE THREAD

**Issue by FANTASTPATR** [dmlc/dgl#979]
## ❓ Questions and Help

 I have modified the file 'translation_train.py' as below according to my  #environment:

![image001](https://user-images.githubusercontent.com/21437254/68366401-35de1a80-016e-11ea-9115-f962107c835c.png)
And I got error as below:
![image](https://user-images.githubusercontent.com/21437254/68366509-76d62f00-016e-11ea-9add-f65ce7236ae2.png)
This error may be caused by this function in models.py line 82:
![image](https://user-images.githubusercontent.com/21437254/68366580-a5540a00-016e-11ea-8885-aa8a88f5a21d.png)
I have no idea to fix it.

**Comment by BarclayII** [comment]
Could you try installing one of the GPU versions:

conda install -c dglteam dgl-cuda10.0

Or

pip install dgl-cu100

You may need to change 10.0 or 100 to match the CUDA version you have.

**Comment by VoVAllen** [comment]
When you build from source, remember to set the `USE_CUDA` flag to ON.
