### ISSUE TITLE
Failing rgcn examples

### ISSUE THREAD

**Issue by imehrdad2012** [dmlc/dgl#988]
Hello,

Something is wrong with the basic rgcn examples..I can run the rgcn hetro ones: without any issue.

**Failing**
(nlp) C:\Users\imehr\Downloads\dgl\examples\pytorch\rgcn>python  entity_classify.py -d mutag --l2norm 5e-4 --n-bases 30 --testing --gpu 0
Namespace(dataset='mutag', dropout=0, gpu=0, l2norm=0.0005, lr=0.01, n_bases=30, n_epochs=50, n_hidden=16, n_layers=2, relabel=False, use_self_loop=False, validation=False)
Loading dataset mutag
Number of nodes:  23644
Number of edges:  172098
Number of relations:  47
Number of classes:  2
removing nodes that are more than 3 hops away
start training...
Traceback (most recent call last):
  File "entity_classify.py", line 170, in <module>
    main(args)
  File "entity_classify.py", line 109, in main
    logits = model(g, feats, edge_type, edge_norm)
  File "C:\Users\imehr\Miniconda3\envs\nlp\lib\site-packages\torch\nn\modules\module.py", line 541, in __call__
    result = self.forward(*input, **kwargs)
  File "C:\Users\imehr\Downloads\dgl\examples\pytorch\rgcn\model.py", line 47, in forward
    h = layer(g, h, r, norm)
  File "C:\Users\imehr\Miniconda3\envs\nlp\lib\site-packages\torch\nn\modules\module.py", line 541, in __call__
    result = self.forward(*input, **kwargs)
  File "C:\Users\imehr\Miniconda3\envs\nlp\lib\site-packages\dgl\nn\pytorch\conv\relgraphconv.py", line 180, in forward
    g.update_all(self.message_func, fn.sum(msg='msg', out='h'))
  File "C:\Users\imehr\Miniconda3\envs\nlp\lib\site-packages\dgl\graph.py", line 2747, in update_all
    Runtime.run(prog)
  File "C:\Users\imehr\Miniconda3\envs\nlp\lib\site-packages\dgl\runtime\runtime.py", line 11, in run
    exe.run()
  File "C:\Users\imehr\Miniconda3\envs\nlp\lib\site-packages\dgl\runtime\ir\executor.py", line 204, in run
    udf_ret = fn_data(src_data, edge_data, dst_data)
  File "C:\Users\imehr\Miniconda3\envs\nlp\lib\site-packages\dgl\runtime\scheduler.py", line 949, in _mfunc_wrapper
    return mfunc(ebatch)
  File "C:\Users\imehr\Miniconda3\envs\nlp\lib\site-packages\dgl\nn\pytorch\conv\relgraphconv.py", line 133, in basis_message_func
    msg = utils.bmm_maybe_select(edges.src['h'], weight, edges.data['type'])
  File "C:\Users\imehr\Miniconda3\envs\nlp\lib\site-packages\dgl\nn\pytorch\utils.py", line 89, in bmm_maybe_select
    BB = B.index_select(0, index)
RuntimeError: Expected object of scalar type Long but got scalar type Int for argument #3 'index' in call to _th_index_select

**Working:**

(nlp) C:\Users\imehr\Downloads\dgl\examples\pytorch\rgcn-hetero>python  entity_classify.py -d mutag --l2norm 5e-4 --n-bases 30 --testing --gpu 0
Namespace(dataset='mutag', dropout=0, gpu=0, l2norm=0.0005, lr=0.01, n_bases=30, n_epochs=50, n_hidden=16, n_layers=2, use_self_loop=False, validation=False)
Found cached graph. Load cache ...
Creating one whole graph ...
Total #nodes: 27163
Total #edges: 148100
Convert to heterograph ...
#Node types: 5
#Canonical edge types: 50
#Unique edge type names: 46
#Training samples: 272
#Testing samples: 68
#Classes: 2
Predict category: d
start training...
C:\Users\imehr\Miniconda3\envs\nlp\lib\site-packages\numpy\lib\function_base.py:390: RuntimeWarning: Mean of empty slice.
  avg = a.mean(axis)
C:\Users\imehr\Miniconda3\envs\nlp\lib\site-packages\numpy\core\_methods.py:161: RuntimeWarning: invalid value encountered in double_scalars
  ret = ret.dtype.type(ret / rcount)
Epoch 00000 | Train Acc: 0.4228 | Train Loss: 0.6981 | Valid Acc: 0.4228 | Valid loss: 0.6981 | Time: nan
Epoch 00001 | Train Acc: 0.6140 | Train Loss: 0.6441 | Valid Acc: 0.6140 | Valid loss: 0.6441 | Time: nan
Epoch 00002 | Train Acc: 0.6140 | Train Loss: 0.6124 | Valid Acc: 0.6140 | Valid loss: 0.6124 | Time: nan
Epoch 00003 | Train Acc: 0.7169 | Train Loss: 0.5659 | Valid Acc: 0.7169 | Valid loss: 0.5659 | Time: nan
Epoch 00004 | Train Acc: 0.9081 | Train Loss: 0.5057 | Valid Acc: 0.9081 | Valid loss: 0.5057 | Time: nan
Epoch 00005 | Train Acc: 0.9890 | Train Loss: 0.4510 | Valid Acc: 0.9890 | Valid loss: 0.4510 | Time: nan
Epoch 00006 | Train Acc: 1.0000 | Train Loss: 0.3973 | Valid Acc: 1.0000 | Valid loss: 0.3973 | Time: 0.1224
Epoch 00007 | Train Acc: 1.0000 | Train Loss: 0.3590 | Valid Acc: 1.0000 | Valid loss: 0.3590 | Time: 0.1237
Epoch 00008 | Train Acc: 1.0000 | Train Loss: 0.3370 | Valid Acc: 1.0000 | Valid loss: 0.3370 | Time: 0.1276
Epoch 00009 | Train Acc: 1.0000 | Train Loss: 0.3254 | Valid Acc: 1.0000 | Valid loss: 0.3254 | Time: 0.1268
Epoch 00010 | Train Acc: 1.0000 | Train Loss: 0.3197 | Valid Acc: 1.0000 | Valid loss: 0.3197 | Time: 0.1268
Epoch 00011 | Train Acc: 1.0000 | Train Loss: 0.3168 | Valid Acc: 1.0000 | Valid loss: 0.3168 | Time: 0.1299

**Comment by jermainewang** [comment]
Sorry for not responding this issue! Since this is a pretty old thread, would you mind installing the latest DGL nightly build and see whether the issue still exists? Please reopen this if so. THanks!
