### ISSUE TITLE
On the use of Prediction of chemical properties

### ISSUE THREAD

**Issue by rookiecoder-chen** [dmlc/dgl#993]
Hello, I just contacted with deep learning and DGL. I hope to be able to use your regression model to predict molecular properties. How can I process my data and make it become the graph input of DGL?

**Comment by mufeili** [comment]
I assume [this discussion thread](https://discuss.dgl.ai/t/prediction-of-chemical-properties/520) was also opened by you. I'd suggest sticking to one place for better tracking and close the issue for now.
